// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_HOLOGRAM20220601MODEL_HPP_
#define ALIBABACLOUD_HOLOGRAM20220601MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateHoloWarehouseRequest.hpp>
#include <alibabacloud/models/CreateHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/CreateHoloWarehouseResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/DeleteHoloWarehouseRequest.hpp>
#include <alibabacloud/models/DeleteHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/DeleteHoloWarehouseResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DisableHiveAccessRequest.hpp>
#include <alibabacloud/models/DisableHiveAccessResponseBody.hpp>
#include <alibabacloud/models/DisableHiveAccessResponse.hpp>
#include <alibabacloud/models/DisableSslresponseBody.hpp>
#include <alibabacloud/models/DisableSslresponse.hpp>
#include <alibabacloud/models/EnableHiveAccessRequest.hpp>
#include <alibabacloud/models/EnableHiveAccessResponseBody.hpp>
#include <alibabacloud/models/EnableHiveAccessResponse.hpp>
#include <alibabacloud/models/EnableSslresponseBody.hpp>
#include <alibabacloud/models/EnableSslresponse.hpp>
#include <alibabacloud/models/GetCertificateAttributeResponseBody.hpp>
#include <alibabacloud/models/GetCertificateAttributeResponse.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetRootCertificateResponseBody.hpp>
#include <alibabacloud/models/GetRootCertificateResponse.hpp>
#include <alibabacloud/models/GetWarehouseDetailResponseBody.hpp>
#include <alibabacloud/models/GetWarehouseDetailResponse.hpp>
#include <alibabacloud/models/ListBackupDataRequest.hpp>
#include <alibabacloud/models/ListBackupDataResponseBody.hpp>
#include <alibabacloud/models/ListBackupDataResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListWarehousesResponseBody.hpp>
#include <alibabacloud/models/ListWarehousesResponse.hpp>
#include <alibabacloud/models/RebalanceHoloWarehouseRequest.hpp>
#include <alibabacloud/models/RebalanceHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/RebalanceHoloWarehouseResponse.hpp>
#include <alibabacloud/models/RenameHoloWarehouseRequest.hpp>
#include <alibabacloud/models/RenameHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/RenameHoloWarehouseResponse.hpp>
#include <alibabacloud/models/RenewInstanceRequest.hpp>
#include <alibabacloud/models/RenewInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewInstanceResponse.hpp>
#include <alibabacloud/models/RenewSslcertificateResponseBody.hpp>
#include <alibabacloud/models/RenewSslcertificateResponse.hpp>
#include <alibabacloud/models/RestartHoloWarehouseRequest.hpp>
#include <alibabacloud/models/RestartHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/RestartHoloWarehouseResponse.hpp>
#include <alibabacloud/models/RestartInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartInstanceResponse.hpp>
#include <alibabacloud/models/ResumeHoloWarehouseRequest.hpp>
#include <alibabacloud/models/ResumeHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/ResumeHoloWarehouseResponse.hpp>
#include <alibabacloud/models/ResumeInstanceResponseBody.hpp>
#include <alibabacloud/models/ResumeInstanceResponse.hpp>
#include <alibabacloud/models/ScaleHoloWarehouseRequest.hpp>
#include <alibabacloud/models/ScaleHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/ScaleHoloWarehouseResponse.hpp>
#include <alibabacloud/models/ScaleInstanceRequest.hpp>
#include <alibabacloud/models/ScaleInstanceResponseBody.hpp>
#include <alibabacloud/models/ScaleInstanceResponse.hpp>
#include <alibabacloud/models/StopInstanceResponseBody.hpp>
#include <alibabacloud/models/StopInstanceResponse.hpp>
#include <alibabacloud/models/SuspendHoloWarehouseRequest.hpp>
#include <alibabacloud/models/SuspendHoloWarehouseResponseBody.hpp>
#include <alibabacloud/models/SuspendHoloWarehouseResponse.hpp>
#include <alibabacloud/models/UpdateInstanceNameRequest.hpp>
#include <alibabacloud/models/UpdateInstanceNameResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceNameResponse.hpp>
#include <alibabacloud/models/UpdateInstanceNetworkTypeRequest.hpp>
#include <alibabacloud/models/UpdateInstanceNetworkTypeResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceNetworkTypeResponse.hpp>
#include <alibabacloud/models/CreateInstanceResponseBodyData.hpp>
#include <alibabacloud/models/GetCertificateAttributeResponseBodyCertificateAttributeDto.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstanceEndpoints.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstanceTags.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/GetWarehouseDetailResponseBodyWarehouseDetailWarehouseList.hpp>
#include <alibabacloud/models/GetWarehouseDetailResponseBodyWarehouseDetail.hpp>
#include <alibabacloud/models/ListBackupDataResponseBodyBackupDataList.hpp>
#include <alibabacloud/models/ListInstancesRequestTag.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListEndpoints.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListTags.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceList.hpp>
#include <alibabacloud/models/ListWarehousesResponseBodyWarehouseList.hpp>
#include <alibabacloud/models/RenewInstanceResponseBodyData.hpp>
#include <alibabacloud/models/ScaleInstanceResponseBodyData.hpp>

#endif
