// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SERVICECATALOG20210901MODEL_HPP_
#define ALIBABACLOUD_SERVICECATALOG20210901MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApproveProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/ApproveProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/ApproveProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/AssociatePrincipalWithPortfolioRequest.hpp>
#include <alibabacloud/models/AssociatePrincipalWithPortfolioResponseBody.hpp>
#include <alibabacloud/models/AssociatePrincipalWithPortfolioResponse.hpp>
#include <alibabacloud/models/AssociateProductWithPortfolioRequest.hpp>
#include <alibabacloud/models/AssociateProductWithPortfolioResponseBody.hpp>
#include <alibabacloud/models/AssociateProductWithPortfolioResponse.hpp>
#include <alibabacloud/models/AssociateTagOptionWithResourceRequest.hpp>
#include <alibabacloud/models/AssociateTagOptionWithResourceResponseBody.hpp>
#include <alibabacloud/models/AssociateTagOptionWithResourceResponse.hpp>
#include <alibabacloud/models/CancelProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/CancelProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/CancelProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/CopyProductRequest.hpp>
#include <alibabacloud/models/CopyProductResponseBody.hpp>
#include <alibabacloud/models/CopyProductResponse.hpp>
#include <alibabacloud/models/CreateConstraintRequest.hpp>
#include <alibabacloud/models/CreateConstraintResponseBody.hpp>
#include <alibabacloud/models/CreateConstraintResponse.hpp>
#include <alibabacloud/models/CreatePortfolioRequest.hpp>
#include <alibabacloud/models/CreatePortfolioResponseBody.hpp>
#include <alibabacloud/models/CreatePortfolioResponse.hpp>
#include <alibabacloud/models/CreateProductRequest.hpp>
#include <alibabacloud/models/CreateProductShrinkRequest.hpp>
#include <alibabacloud/models/CreateProductResponseBody.hpp>
#include <alibabacloud/models/CreateProductResponse.hpp>
#include <alibabacloud/models/CreateProductVersionRequest.hpp>
#include <alibabacloud/models/CreateProductVersionResponseBody.hpp>
#include <alibabacloud/models/CreateProductVersionResponse.hpp>
#include <alibabacloud/models/CreateProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/CreateProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/CreateProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/CreateTagOptionRequest.hpp>
#include <alibabacloud/models/CreateTagOptionResponseBody.hpp>
#include <alibabacloud/models/CreateTagOptionResponse.hpp>
#include <alibabacloud/models/CreateTemplateRequest.hpp>
#include <alibabacloud/models/CreateTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateTemplateResponse.hpp>
#include <alibabacloud/models/DeleteConstraintRequest.hpp>
#include <alibabacloud/models/DeleteConstraintResponseBody.hpp>
#include <alibabacloud/models/DeleteConstraintResponse.hpp>
#include <alibabacloud/models/DeletePortfolioRequest.hpp>
#include <alibabacloud/models/DeletePortfolioResponseBody.hpp>
#include <alibabacloud/models/DeletePortfolioResponse.hpp>
#include <alibabacloud/models/DeleteProductRequest.hpp>
#include <alibabacloud/models/DeleteProductResponseBody.hpp>
#include <alibabacloud/models/DeleteProductResponse.hpp>
#include <alibabacloud/models/DeleteProductVersionRequest.hpp>
#include <alibabacloud/models/DeleteProductVersionResponseBody.hpp>
#include <alibabacloud/models/DeleteProductVersionResponse.hpp>
#include <alibabacloud/models/DeleteProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/DeleteProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/DeleteTagOptionRequest.hpp>
#include <alibabacloud/models/DeleteTagOptionResponseBody.hpp>
#include <alibabacloud/models/DeleteTagOptionResponse.hpp>
#include <alibabacloud/models/DisAssociateTagOptionFromResourceRequest.hpp>
#include <alibabacloud/models/DisAssociateTagOptionFromResourceResponseBody.hpp>
#include <alibabacloud/models/DisAssociateTagOptionFromResourceResponse.hpp>
#include <alibabacloud/models/DisassociatePrincipalFromPortfolioRequest.hpp>
#include <alibabacloud/models/DisassociatePrincipalFromPortfolioResponseBody.hpp>
#include <alibabacloud/models/DisassociatePrincipalFromPortfolioResponse.hpp>
#include <alibabacloud/models/DisassociateProductFromPortfolioRequest.hpp>
#include <alibabacloud/models/DisassociateProductFromPortfolioResponseBody.hpp>
#include <alibabacloud/models/DisassociateProductFromPortfolioResponse.hpp>
#include <alibabacloud/models/ExecuteProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/ExecuteProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/ExecuteProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/GetConstraintRequest.hpp>
#include <alibabacloud/models/GetConstraintResponseBody.hpp>
#include <alibabacloud/models/GetConstraintResponse.hpp>
#include <alibabacloud/models/GetPortfolioRequest.hpp>
#include <alibabacloud/models/GetPortfolioResponseBody.hpp>
#include <alibabacloud/models/GetPortfolioResponse.hpp>
#include <alibabacloud/models/GetProductAsAdminRequest.hpp>
#include <alibabacloud/models/GetProductAsAdminResponseBody.hpp>
#include <alibabacloud/models/GetProductAsAdminResponse.hpp>
#include <alibabacloud/models/GetProductAsEndUserRequest.hpp>
#include <alibabacloud/models/GetProductAsEndUserResponseBody.hpp>
#include <alibabacloud/models/GetProductAsEndUserResponse.hpp>
#include <alibabacloud/models/GetProductVersionRequest.hpp>
#include <alibabacloud/models/GetProductVersionResponseBody.hpp>
#include <alibabacloud/models/GetProductVersionResponse.hpp>
#include <alibabacloud/models/GetProvisionedProductRequest.hpp>
#include <alibabacloud/models/GetProvisionedProductResponseBody.hpp>
#include <alibabacloud/models/GetProvisionedProductResponse.hpp>
#include <alibabacloud/models/GetProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/GetProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/GetProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/GetTagOptionRequest.hpp>
#include <alibabacloud/models/GetTagOptionResponseBody.hpp>
#include <alibabacloud/models/GetTagOptionResponse.hpp>
#include <alibabacloud/models/GetTaskRequest.hpp>
#include <alibabacloud/models/GetTaskResponseBody.hpp>
#include <alibabacloud/models/GetTaskResponse.hpp>
#include <alibabacloud/models/GetTemplateRequest.hpp>
#include <alibabacloud/models/GetTemplateResponseBody.hpp>
#include <alibabacloud/models/GetTemplateResponse.hpp>
#include <alibabacloud/models/LaunchProductRequest.hpp>
#include <alibabacloud/models/LaunchProductResponseBody.hpp>
#include <alibabacloud/models/LaunchProductResponse.hpp>
#include <alibabacloud/models/ListLaunchOptionsRequest.hpp>
#include <alibabacloud/models/ListLaunchOptionsResponseBody.hpp>
#include <alibabacloud/models/ListLaunchOptionsResponse.hpp>
#include <alibabacloud/models/ListPortfoliosRequest.hpp>
#include <alibabacloud/models/ListPortfoliosResponseBody.hpp>
#include <alibabacloud/models/ListPortfoliosResponse.hpp>
#include <alibabacloud/models/ListPrincipalsRequest.hpp>
#include <alibabacloud/models/ListPrincipalsResponseBody.hpp>
#include <alibabacloud/models/ListPrincipalsResponse.hpp>
#include <alibabacloud/models/ListProductVersionsRequest.hpp>
#include <alibabacloud/models/ListProductVersionsResponseBody.hpp>
#include <alibabacloud/models/ListProductVersionsResponse.hpp>
#include <alibabacloud/models/ListProductsAsAdminRequest.hpp>
#include <alibabacloud/models/ListProductsAsAdminResponseBody.hpp>
#include <alibabacloud/models/ListProductsAsAdminResponse.hpp>
#include <alibabacloud/models/ListProductsAsEndUserRequest.hpp>
#include <alibabacloud/models/ListProductsAsEndUserResponseBody.hpp>
#include <alibabacloud/models/ListProductsAsEndUserResponse.hpp>
#include <alibabacloud/models/ListProvisionedProductPlanApproversRequest.hpp>
#include <alibabacloud/models/ListProvisionedProductPlanApproversResponseBody.hpp>
#include <alibabacloud/models/ListProvisionedProductPlanApproversResponse.hpp>
#include <alibabacloud/models/ListProvisionedProductPlansRequest.hpp>
#include <alibabacloud/models/ListProvisionedProductPlansResponseBody.hpp>
#include <alibabacloud/models/ListProvisionedProductPlansResponse.hpp>
#include <alibabacloud/models/ListProvisionedProductsRequest.hpp>
#include <alibabacloud/models/ListProvisionedProductsResponseBody.hpp>
#include <alibabacloud/models/ListProvisionedProductsResponse.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/ListResourcesForTagOptionRequest.hpp>
#include <alibabacloud/models/ListResourcesForTagOptionResponseBody.hpp>
#include <alibabacloud/models/ListResourcesForTagOptionResponse.hpp>
#include <alibabacloud/models/ListTagOptionsRequest.hpp>
#include <alibabacloud/models/ListTagOptionsShrinkRequest.hpp>
#include <alibabacloud/models/ListTagOptionsResponseBody.hpp>
#include <alibabacloud/models/ListTagOptionsResponse.hpp>
#include <alibabacloud/models/ListTasksRequest.hpp>
#include <alibabacloud/models/ListTasksResponseBody.hpp>
#include <alibabacloud/models/ListTasksResponse.hpp>
#include <alibabacloud/models/TerminateProvisionedProductRequest.hpp>
#include <alibabacloud/models/TerminateProvisionedProductResponseBody.hpp>
#include <alibabacloud/models/TerminateProvisionedProductResponse.hpp>
#include <alibabacloud/models/UpdateConstraintRequest.hpp>
#include <alibabacloud/models/UpdateConstraintResponseBody.hpp>
#include <alibabacloud/models/UpdateConstraintResponse.hpp>
#include <alibabacloud/models/UpdatePortfolioRequest.hpp>
#include <alibabacloud/models/UpdatePortfolioResponseBody.hpp>
#include <alibabacloud/models/UpdatePortfolioResponse.hpp>
#include <alibabacloud/models/UpdateProductRequest.hpp>
#include <alibabacloud/models/UpdateProductResponseBody.hpp>
#include <alibabacloud/models/UpdateProductResponse.hpp>
#include <alibabacloud/models/UpdateProductVersionRequest.hpp>
#include <alibabacloud/models/UpdateProductVersionResponseBody.hpp>
#include <alibabacloud/models/UpdateProductVersionResponse.hpp>
#include <alibabacloud/models/UpdateProvisionedProductRequest.hpp>
#include <alibabacloud/models/UpdateProvisionedProductResponseBody.hpp>
#include <alibabacloud/models/UpdateProvisionedProductResponse.hpp>
#include <alibabacloud/models/UpdateProvisionedProductPlanRequest.hpp>
#include <alibabacloud/models/UpdateProvisionedProductPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateProvisionedProductPlanResponse.hpp>
#include <alibabacloud/models/UpdateTagOptionRequest.hpp>
#include <alibabacloud/models/UpdateTagOptionResponseBody.hpp>
#include <alibabacloud/models/UpdateTagOptionResponse.hpp>

#endif
