// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_COMPUTENEST20210601MODEL_HPP_
#define ALIBABACLOUD_COMPUTENEST20210601MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CommodityValue.hpp>
#include <alibabacloud/models/CancelServiceUsageRequest.hpp>
#include <alibabacloud/models/CancelServiceUsageResponseBody.hpp>
#include <alibabacloud/models/CancelServiceUsageResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckServiceDeployableRequest.hpp>
#include <alibabacloud/models/CheckServiceDeployableResponseBody.hpp>
#include <alibabacloud/models/CheckServiceDeployableResponse.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceRequest.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateRestoreTaskRequest.hpp>
#include <alibabacloud/models/CreateRestoreTaskResponseBody.hpp>
#include <alibabacloud/models/CreateRestoreTaskResponse.hpp>
#include <alibabacloud/models/CreateServiceInstanceRequest.hpp>
#include <alibabacloud/models/CreateServiceInstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateServiceInstanceResponse.hpp>
#include <alibabacloud/models/CreateServiceUsageRequest.hpp>
#include <alibabacloud/models/CreateServiceUsageShrinkRequest.hpp>
#include <alibabacloud/models/CreateServiceUsageResponseBody.hpp>
#include <alibabacloud/models/CreateServiceUsageResponse.hpp>
#include <alibabacloud/models/CreateSkillRequest.hpp>
#include <alibabacloud/models/CreateSkillResponseBody.hpp>
#include <alibabacloud/models/CreateSkillResponse.hpp>
#include <alibabacloud/models/CreateSkillFileDetectRequest.hpp>
#include <alibabacloud/models/CreateSkillFileDetectResponseBody.hpp>
#include <alibabacloud/models/CreateSkillFileDetectResponse.hpp>
#include <alibabacloud/models/CreateSkillHubConfigRequest.hpp>
#include <alibabacloud/models/CreateSkillHubConfigResponseBody.hpp>
#include <alibabacloud/models/CreateSkillHubConfigResponse.hpp>
#include <alibabacloud/models/CreateSkillSpaceRequest.hpp>
#include <alibabacloud/models/CreateSkillSpaceResponseBody.hpp>
#include <alibabacloud/models/CreateSkillSpaceResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteServiceInstancesRequest.hpp>
#include <alibabacloud/models/DeleteServiceInstancesResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceInstancesResponse.hpp>
#include <alibabacloud/models/DeleteSkillRequest.hpp>
#include <alibabacloud/models/DeleteSkillResponseBody.hpp>
#include <alibabacloud/models/DeleteSkillResponse.hpp>
#include <alibabacloud/models/DeleteSkillSpaceRequest.hpp>
#include <alibabacloud/models/DeleteSkillSpaceResponseBody.hpp>
#include <alibabacloud/models/DeleteSkillSpaceResponse.hpp>
#include <alibabacloud/models/DeployServiceInstanceRequest.hpp>
#include <alibabacloud/models/DeployServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/DeployServiceInstanceResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/GenerateServicePolicyRequest.hpp>
#include <alibabacloud/models/GenerateServicePolicyResponseBody.hpp>
#include <alibabacloud/models/GenerateServicePolicyResponse.hpp>
#include <alibabacloud/models/GetBackupRequest.hpp>
#include <alibabacloud/models/GetBackupResponseBody.hpp>
#include <alibabacloud/models/GetBackupResponse.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesRequest.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesResponseBody.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesResponse.hpp>
#include <alibabacloud/models/GetServiceRequest.hpp>
#include <alibabacloud/models/GetServiceResponseBody.hpp>
#include <alibabacloud/models/GetServiceResponse.hpp>
#include <alibabacloud/models/GetServiceEstimateCostRequest.hpp>
#include <alibabacloud/models/GetServiceEstimateCostShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceEstimateCostResponseBody.hpp>
#include <alibabacloud/models/GetServiceEstimateCostResponse.hpp>
#include <alibabacloud/models/GetServiceInstanceRequest.hpp>
#include <alibabacloud/models/GetServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/GetServiceInstanceResponse.hpp>
#include <alibabacloud/models/GetServiceInstanceSubscriptionEstimateCostRequest.hpp>
#include <alibabacloud/models/GetServiceInstanceSubscriptionEstimateCostResponseBody.hpp>
#include <alibabacloud/models/GetServiceInstanceSubscriptionEstimateCostResponse.hpp>
#include <alibabacloud/models/GetServiceProvisionsRequest.hpp>
#include <alibabacloud/models/GetServiceProvisionsShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceProvisionsResponseBody.hpp>
#include <alibabacloud/models/GetServiceProvisionsResponse.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsRequest.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsResponseBody.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsResponse.hpp>
#include <alibabacloud/models/GetSkillRequest.hpp>
#include <alibabacloud/models/GetSkillResponseBody.hpp>
#include <alibabacloud/models/GetSkillResponse.hpp>
#include <alibabacloud/models/GetSkillFileDetectResultRequest.hpp>
#include <alibabacloud/models/GetSkillFileDetectResultResponseBody.hpp>
#include <alibabacloud/models/GetSkillFileDetectResultResponse.hpp>
#include <alibabacloud/models/GetSkillHubConfigRequest.hpp>
#include <alibabacloud/models/GetSkillHubConfigResponseBody.hpp>
#include <alibabacloud/models/GetSkillHubConfigResponse.hpp>
#include <alibabacloud/models/GetSkillSpaceRequest.hpp>
#include <alibabacloud/models/GetSkillSpaceResponseBody.hpp>
#include <alibabacloud/models/GetSkillSpaceResponse.hpp>
#include <alibabacloud/models/GetUserInformationRequest.hpp>
#include <alibabacloud/models/GetUserInformationResponseBody.hpp>
#include <alibabacloud/models/GetUserInformationResponse.hpp>
#include <alibabacloud/models/ListBackupsRequest.hpp>
#include <alibabacloud/models/ListBackupsResponseBody.hpp>
#include <alibabacloud/models/ListBackupsResponse.hpp>
#include <alibabacloud/models/ListPoliciesRequest.hpp>
#include <alibabacloud/models/ListPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListPoliciesResponse.hpp>
#include <alibabacloud/models/ListPublicSkillsRequest.hpp>
#include <alibabacloud/models/ListPublicSkillsResponseBody.hpp>
#include <alibabacloud/models/ListPublicSkillsResponse.hpp>
#include <alibabacloud/models/ListRestoreTasksRequest.hpp>
#include <alibabacloud/models/ListRestoreTasksResponseBody.hpp>
#include <alibabacloud/models/ListRestoreTasksResponse.hpp>
#include <alibabacloud/models/ListServiceCategoriesResponseBody.hpp>
#include <alibabacloud/models/ListServiceCategoriesResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceBillRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceBillResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceBillResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryResponse.hpp>
#include <alibabacloud/models/ListServiceInstancesRequest.hpp>
#include <alibabacloud/models/ListServiceInstancesResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstancesResponse.hpp>
#include <alibabacloud/models/ListServiceUsagesRequest.hpp>
#include <alibabacloud/models/ListServiceUsagesResponseBody.hpp>
#include <alibabacloud/models/ListServiceUsagesResponse.hpp>
#include <alibabacloud/models/ListServicesRequest.hpp>
#include <alibabacloud/models/ListServicesResponseBody.hpp>
#include <alibabacloud/models/ListServicesResponse.hpp>
#include <alibabacloud/models/ListSkillFilesRequest.hpp>
#include <alibabacloud/models/ListSkillFilesResponseBody.hpp>
#include <alibabacloud/models/ListSkillFilesResponse.hpp>
#include <alibabacloud/models/ListSkillSpacesRequest.hpp>
#include <alibabacloud/models/ListSkillSpacesResponseBody.hpp>
#include <alibabacloud/models/ListSkillSpacesResponse.hpp>
#include <alibabacloud/models/ListSkillsRequest.hpp>
#include <alibabacloud/models/ListSkillsResponseBody.hpp>
#include <alibabacloud/models/ListSkillsResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/RenewServiceInstanceRequest.hpp>
#include <alibabacloud/models/RenewServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewServiceInstanceResponse.hpp>
#include <alibabacloud/models/RenewServiceInstanceResourcesRequest.hpp>
#include <alibabacloud/models/RenewServiceInstanceResourcesResponseBody.hpp>
#include <alibabacloud/models/RenewServiceInstanceResourcesResponse.hpp>
#include <alibabacloud/models/RestartServiceInstanceRequest.hpp>
#include <alibabacloud/models/RestartServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartServiceInstanceResponse.hpp>
#include <alibabacloud/models/RollbackServiceInstanceRequest.hpp>
#include <alibabacloud/models/RollbackServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/RollbackServiceInstanceResponse.hpp>
#include <alibabacloud/models/StartServiceInstanceRequest.hpp>
#include <alibabacloud/models/StartServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/StartServiceInstanceResponse.hpp>
#include <alibabacloud/models/StopServiceInstanceRequest.hpp>
#include <alibabacloud/models/StopServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/StopServiceInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnTagResourcesRequest.hpp>
#include <alibabacloud/models/UnTagResourcesResponseBody.hpp>
#include <alibabacloud/models/UnTagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributesRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributesResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributesResponse.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecResponse.hpp>
#include <alibabacloud/models/UpdateServiceUsageRequest.hpp>
#include <alibabacloud/models/UpdateServiceUsageShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceUsageResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceUsageResponse.hpp>
#include <alibabacloud/models/UpdateSkillRequest.hpp>
#include <alibabacloud/models/UpdateSkillResponseBody.hpp>
#include <alibabacloud/models/UpdateSkillResponse.hpp>
#include <alibabacloud/models/UpdateUserInformationRequest.hpp>
#include <alibabacloud/models/UpdateUserInformationResponseBody.hpp>
#include <alibabacloud/models/UpdateUserInformationResponse.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceRequest.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceShrinkRequest.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceResponse.hpp>
#include <alibabacloud/models/ValidateServiceInstanceNameRequest.hpp>
#include <alibabacloud/models/ValidateServiceInstanceNameResponseBody.hpp>
#include <alibabacloud/models/ValidateServiceInstanceNameResponse.hpp>

#endif
