// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CONFIG20200907MODEL_HPP_
#define ALIBABACLOUD_CONFIG20200907MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ResourceDirectoryFolderNode.hpp>
#include <alibabacloud/models/ActiveAggregateConfigRulesRequest.hpp>
#include <alibabacloud/models/ActiveAggregateConfigRulesResponseBody.hpp>
#include <alibabacloud/models/ActiveAggregateConfigRulesResponse.hpp>
#include <alibabacloud/models/ActiveConfigRulesRequest.hpp>
#include <alibabacloud/models/ActiveConfigRulesResponseBody.hpp>
#include <alibabacloud/models/ActiveConfigRulesResponse.hpp>
#include <alibabacloud/models/AttachAggregateConfigRuleToCompliancePackRequest.hpp>
#include <alibabacloud/models/AttachAggregateConfigRuleToCompliancePackResponseBody.hpp>
#include <alibabacloud/models/AttachAggregateConfigRuleToCompliancePackResponse.hpp>
#include <alibabacloud/models/AttachConfigRuleToCompliancePackRequest.hpp>
#include <alibabacloud/models/AttachConfigRuleToCompliancePackResponseBody.hpp>
#include <alibabacloud/models/AttachConfigRuleToCompliancePackResponse.hpp>
#include <alibabacloud/models/CopyCompliancePacksRequest.hpp>
#include <alibabacloud/models/CopyCompliancePacksResponseBody.hpp>
#include <alibabacloud/models/CopyCompliancePacksResponse.hpp>
#include <alibabacloud/models/CopyConfigRulesRequest.hpp>
#include <alibabacloud/models/CopyConfigRulesResponseBody.hpp>
#include <alibabacloud/models/CopyConfigRulesResponse.hpp>
#include <alibabacloud/models/CreateAdvancedSearchFileRequest.hpp>
#include <alibabacloud/models/CreateAdvancedSearchFileResponseBody.hpp>
#include <alibabacloud/models/CreateAdvancedSearchFileResponse.hpp>
#include <alibabacloud/models/CreateAggregateAdvancedSearchFileRequest.hpp>
#include <alibabacloud/models/CreateAggregateAdvancedSearchFileResponseBody.hpp>
#include <alibabacloud/models/CreateAggregateAdvancedSearchFileResponse.hpp>
#include <alibabacloud/models/CreateAggregateCompliancePackRequest.hpp>
#include <alibabacloud/models/CreateAggregateCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/CreateAggregateCompliancePackResponseBody.hpp>
#include <alibabacloud/models/CreateAggregateCompliancePackResponse.hpp>
#include <alibabacloud/models/CreateAggregateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/CreateAggregateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/CreateAggregateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/CreateAggregateConfigRuleRequest.hpp>
#include <alibabacloud/models/CreateAggregateConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/CreateAggregateConfigRuleResponseBody.hpp>
#include <alibabacloud/models/CreateAggregateConfigRuleResponse.hpp>
#include <alibabacloud/models/CreateAggregateRemediationRequest.hpp>
#include <alibabacloud/models/CreateAggregateRemediationResponseBody.hpp>
#include <alibabacloud/models/CreateAggregateRemediationResponse.hpp>
#include <alibabacloud/models/CreateAggregatorRequest.hpp>
#include <alibabacloud/models/CreateAggregatorShrinkRequest.hpp>
#include <alibabacloud/models/CreateAggregatorResponseBody.hpp>
#include <alibabacloud/models/CreateAggregatorResponse.hpp>
#include <alibabacloud/models/CreateCompliancePackRequest.hpp>
#include <alibabacloud/models/CreateCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/CreateCompliancePackResponseBody.hpp>
#include <alibabacloud/models/CreateCompliancePackResponse.hpp>
#include <alibabacloud/models/CreateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/CreateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/CreateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/CreateConfigRuleRequest.hpp>
#include <alibabacloud/models/CreateConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/CreateConfigRuleResponseBody.hpp>
#include <alibabacloud/models/CreateConfigRuleResponse.hpp>
#include <alibabacloud/models/CreateRemediationRequest.hpp>
#include <alibabacloud/models/CreateRemediationResponseBody.hpp>
#include <alibabacloud/models/CreateRemediationResponse.hpp>
#include <alibabacloud/models/DeactiveAggregateConfigRulesRequest.hpp>
#include <alibabacloud/models/DeactiveAggregateConfigRulesResponseBody.hpp>
#include <alibabacloud/models/DeactiveAggregateConfigRulesResponse.hpp>
#include <alibabacloud/models/DeactiveConfigRulesRequest.hpp>
#include <alibabacloud/models/DeactiveConfigRulesResponseBody.hpp>
#include <alibabacloud/models/DeactiveConfigRulesResponse.hpp>
#include <alibabacloud/models/DeleteAggregateCompliancePacksRequest.hpp>
#include <alibabacloud/models/DeleteAggregateCompliancePacksResponseBody.hpp>
#include <alibabacloud/models/DeleteAggregateCompliancePacksResponse.hpp>
#include <alibabacloud/models/DeleteAggregateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/DeleteAggregateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteAggregateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/DeleteAggregateConfigRulesRequest.hpp>
#include <alibabacloud/models/DeleteAggregateConfigRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteAggregateConfigRulesResponse.hpp>
#include <alibabacloud/models/DeleteAggregateRemediationsRequest.hpp>
#include <alibabacloud/models/DeleteAggregateRemediationsResponseBody.hpp>
#include <alibabacloud/models/DeleteAggregateRemediationsResponse.hpp>
#include <alibabacloud/models/DeleteAggregatorsRequest.hpp>
#include <alibabacloud/models/DeleteAggregatorsResponseBody.hpp>
#include <alibabacloud/models/DeleteAggregatorsResponse.hpp>
#include <alibabacloud/models/DeleteCompliancePacksRequest.hpp>
#include <alibabacloud/models/DeleteCompliancePacksResponseBody.hpp>
#include <alibabacloud/models/DeleteCompliancePacksResponse.hpp>
#include <alibabacloud/models/DeleteConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/DeleteConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/DeleteConfigRulesRequest.hpp>
#include <alibabacloud/models/DeleteConfigRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteConfigRulesResponse.hpp>
#include <alibabacloud/models/DeleteRemediationsRequest.hpp>
#include <alibabacloud/models/DeleteRemediationsResponseBody.hpp>
#include <alibabacloud/models/DeleteRemediationsResponse.hpp>
#include <alibabacloud/models/DeleteReportTemplateRequest.hpp>
#include <alibabacloud/models/DeleteReportTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteReportTemplateResponse.hpp>
#include <alibabacloud/models/DescribeDiscoveredResourceBatchRequest.hpp>
#include <alibabacloud/models/DescribeDiscoveredResourceBatchResponseBody.hpp>
#include <alibabacloud/models/DescribeDiscoveredResourceBatchResponse.hpp>
#include <alibabacloud/models/DescribeIntegratedServiceStatusRequest.hpp>
#include <alibabacloud/models/DescribeIntegratedServiceStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeIntegratedServiceStatusResponse.hpp>
#include <alibabacloud/models/DescribeRemediationRequest.hpp>
#include <alibabacloud/models/DescribeRemediationResponseBody.hpp>
#include <alibabacloud/models/DescribeRemediationResponse.hpp>
#include <alibabacloud/models/DetachAggregateConfigRuleToCompliancePackRequest.hpp>
#include <alibabacloud/models/DetachAggregateConfigRuleToCompliancePackResponseBody.hpp>
#include <alibabacloud/models/DetachAggregateConfigRuleToCompliancePackResponse.hpp>
#include <alibabacloud/models/DetachConfigRuleToCompliancePackRequest.hpp>
#include <alibabacloud/models/DetachConfigRuleToCompliancePackResponseBody.hpp>
#include <alibabacloud/models/DetachConfigRuleToCompliancePackResponse.hpp>
#include <alibabacloud/models/DryRunConfigRuleRequest.hpp>
#include <alibabacloud/models/DryRunConfigRuleResponseBody.hpp>
#include <alibabacloud/models/DryRunConfigRuleResponse.hpp>
#include <alibabacloud/models/EvaluatePreConfigRulesRequest.hpp>
#include <alibabacloud/models/EvaluatePreConfigRulesShrinkRequest.hpp>
#include <alibabacloud/models/EvaluatePreConfigRulesResponseBody.hpp>
#include <alibabacloud/models/EvaluatePreConfigRulesResponse.hpp>
#include <alibabacloud/models/GenerateAggregateCompliancePackReportRequest.hpp>
#include <alibabacloud/models/GenerateAggregateCompliancePackReportResponseBody.hpp>
#include <alibabacloud/models/GenerateAggregateCompliancePackReportResponse.hpp>
#include <alibabacloud/models/GenerateAggregateConfigRulesReportRequest.hpp>
#include <alibabacloud/models/GenerateAggregateConfigRulesReportResponseBody.hpp>
#include <alibabacloud/models/GenerateAggregateConfigRulesReportResponse.hpp>
#include <alibabacloud/models/GenerateAggregateResourceInventoryRequest.hpp>
#include <alibabacloud/models/GenerateAggregateResourceInventoryResponseBody.hpp>
#include <alibabacloud/models/GenerateAggregateResourceInventoryResponse.hpp>
#include <alibabacloud/models/GenerateCompliancePackReportRequest.hpp>
#include <alibabacloud/models/GenerateCompliancePackReportResponseBody.hpp>
#include <alibabacloud/models/GenerateCompliancePackReportResponse.hpp>
#include <alibabacloud/models/GenerateConfigRulesReportRequest.hpp>
#include <alibabacloud/models/GenerateConfigRulesReportResponseBody.hpp>
#include <alibabacloud/models/GenerateConfigRulesReportResponse.hpp>
#include <alibabacloud/models/GenerateReportFromTemplateRequest.hpp>
#include <alibabacloud/models/GenerateReportFromTemplateResponseBody.hpp>
#include <alibabacloud/models/GenerateReportFromTemplateResponse.hpp>
#include <alibabacloud/models/GenerateResourceInventoryRequest.hpp>
#include <alibabacloud/models/GenerateResourceInventoryResponseBody.hpp>
#include <alibabacloud/models/GenerateResourceInventoryResponse.hpp>
#include <alibabacloud/models/GetAdvancedSearchFileResponseBody.hpp>
#include <alibabacloud/models/GetAdvancedSearchFileResponse.hpp>
#include <alibabacloud/models/GetAggregateAccountComplianceByPackRequest.hpp>
#include <alibabacloud/models/GetAggregateAccountComplianceByPackResponseBody.hpp>
#include <alibabacloud/models/GetAggregateAccountComplianceByPackResponse.hpp>
#include <alibabacloud/models/GetAggregateAdvancedSearchFileRequest.hpp>
#include <alibabacloud/models/GetAggregateAdvancedSearchFileResponseBody.hpp>
#include <alibabacloud/models/GetAggregateAdvancedSearchFileResponse.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackRequest.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackResponseBody.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackResponse.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackReportRequest.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackReportResponseBody.hpp>
#include <alibabacloud/models/GetAggregateCompliancePackReportResponse.hpp>
#include <alibabacloud/models/GetAggregateComplianceSummaryRequest.hpp>
#include <alibabacloud/models/GetAggregateComplianceSummaryResponseBody.hpp>
#include <alibabacloud/models/GetAggregateComplianceSummaryResponse.hpp>
#include <alibabacloud/models/GetAggregateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/GetAggregateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleResponseBody.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleResponse.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleComplianceByPackRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleComplianceByPackResponseBody.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleComplianceByPackResponse.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleSummaryByRiskLevelRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleSummaryByRiskLevelResponseBody.hpp>
#include <alibabacloud/models/GetAggregateConfigRuleSummaryByRiskLevelResponse.hpp>
#include <alibabacloud/models/GetAggregateConfigRulesReportRequest.hpp>
#include <alibabacloud/models/GetAggregateConfigRulesReportResponseBody.hpp>
#include <alibabacloud/models/GetAggregateConfigRulesReportResponse.hpp>
#include <alibabacloud/models/GetAggregateDiscoveredResourceRequest.hpp>
#include <alibabacloud/models/GetAggregateDiscoveredResourceResponseBody.hpp>
#include <alibabacloud/models/GetAggregateDiscoveredResourceResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByConfigRuleRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByConfigRuleResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByConfigRuleResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByPackRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByPackResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceByPackResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByRegionRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByRegionResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByRegionResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByResourceTypeRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByResourceTypeResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceGroupByResourceTypeResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceTimelineRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceTimelineResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceComplianceTimelineResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceConfigurationTimelineRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceConfigurationTimelineResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceConfigurationTimelineResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByRegionRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByRegionResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByRegionResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByResourceTypeRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByResourceTypeResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceCountsGroupByResourceTypeResponse.hpp>
#include <alibabacloud/models/GetAggregateResourceInventoryRequest.hpp>
#include <alibabacloud/models/GetAggregateResourceInventoryResponseBody.hpp>
#include <alibabacloud/models/GetAggregateResourceInventoryResponse.hpp>
#include <alibabacloud/models/GetAggregatorRequest.hpp>
#include <alibabacloud/models/GetAggregatorShrinkRequest.hpp>
#include <alibabacloud/models/GetAggregatorResponseBody.hpp>
#include <alibabacloud/models/GetAggregatorResponse.hpp>
#include <alibabacloud/models/GetCompliancePackRequest.hpp>
#include <alibabacloud/models/GetCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/GetCompliancePackResponseBody.hpp>
#include <alibabacloud/models/GetCompliancePackResponse.hpp>
#include <alibabacloud/models/GetCompliancePackReportRequest.hpp>
#include <alibabacloud/models/GetCompliancePackReportResponseBody.hpp>
#include <alibabacloud/models/GetCompliancePackReportResponse.hpp>
#include <alibabacloud/models/GetComplianceSummaryResponseBody.hpp>
#include <alibabacloud/models/GetComplianceSummaryResponse.hpp>
#include <alibabacloud/models/GetConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/GetConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/GetConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/GetConfigRuleRequest.hpp>
#include <alibabacloud/models/GetConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/GetConfigRuleResponseBody.hpp>
#include <alibabacloud/models/GetConfigRuleResponse.hpp>
#include <alibabacloud/models/GetConfigRuleComplianceByPackRequest.hpp>
#include <alibabacloud/models/GetConfigRuleComplianceByPackResponseBody.hpp>
#include <alibabacloud/models/GetConfigRuleComplianceByPackResponse.hpp>
#include <alibabacloud/models/GetConfigRuleSummaryByRiskLevelResponseBody.hpp>
#include <alibabacloud/models/GetConfigRuleSummaryByRiskLevelResponse.hpp>
#include <alibabacloud/models/GetConfigRulesReportRequest.hpp>
#include <alibabacloud/models/GetConfigRulesReportResponseBody.hpp>
#include <alibabacloud/models/GetConfigRulesReportResponse.hpp>
#include <alibabacloud/models/GetConfigurationRecorderResponseBody.hpp>
#include <alibabacloud/models/GetConfigurationRecorderResponse.hpp>
#include <alibabacloud/models/GetDiscoveredResourceRequest.hpp>
#include <alibabacloud/models/GetDiscoveredResourceResponseBody.hpp>
#include <alibabacloud/models/GetDiscoveredResourceResponse.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByRegionRequest.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByRegionResponseBody.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByRegionResponse.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByResourceTypeRequest.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByResourceTypeResponseBody.hpp>
#include <alibabacloud/models/GetDiscoveredResourceCountsGroupByResourceTypeResponse.hpp>
#include <alibabacloud/models/GetIntegratedServiceStatusRequest.hpp>
#include <alibabacloud/models/GetIntegratedServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetIntegratedServiceStatusResponse.hpp>
#include <alibabacloud/models/GetManagedRuleRequest.hpp>
#include <alibabacloud/models/GetManagedRuleResponseBody.hpp>
#include <alibabacloud/models/GetManagedRuleResponse.hpp>
#include <alibabacloud/models/GetRemediationTemplateRequest.hpp>
#include <alibabacloud/models/GetRemediationTemplateResponseBody.hpp>
#include <alibabacloud/models/GetRemediationTemplateResponse.hpp>
#include <alibabacloud/models/GetReportFromTemplateRequest.hpp>
#include <alibabacloud/models/GetReportFromTemplateResponseBody.hpp>
#include <alibabacloud/models/GetReportFromTemplateResponse.hpp>
#include <alibabacloud/models/GetResourceComplianceByConfigRuleRequest.hpp>
#include <alibabacloud/models/GetResourceComplianceByConfigRuleResponseBody.hpp>
#include <alibabacloud/models/GetResourceComplianceByConfigRuleResponse.hpp>
#include <alibabacloud/models/GetResourceComplianceByPackRequest.hpp>
#include <alibabacloud/models/GetResourceComplianceByPackResponseBody.hpp>
#include <alibabacloud/models/GetResourceComplianceByPackResponse.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByRegionRequest.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByRegionResponseBody.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByRegionResponse.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByResourceTypeRequest.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByResourceTypeResponseBody.hpp>
#include <alibabacloud/models/GetResourceComplianceGroupByResourceTypeResponse.hpp>
#include <alibabacloud/models/GetResourceComplianceTimelineRequest.hpp>
#include <alibabacloud/models/GetResourceComplianceTimelineResponseBody.hpp>
#include <alibabacloud/models/GetResourceComplianceTimelineResponse.hpp>
#include <alibabacloud/models/GetResourceConfigurationSampleRequest.hpp>
#include <alibabacloud/models/GetResourceConfigurationSampleResponseBody.hpp>
#include <alibabacloud/models/GetResourceConfigurationSampleResponse.hpp>
#include <alibabacloud/models/GetResourceConfigurationTimelineRequest.hpp>
#include <alibabacloud/models/GetResourceConfigurationTimelineResponseBody.hpp>
#include <alibabacloud/models/GetResourceConfigurationTimelineResponse.hpp>
#include <alibabacloud/models/GetResourceInventoryResponseBody.hpp>
#include <alibabacloud/models/GetResourceInventoryResponse.hpp>
#include <alibabacloud/models/GetResourceTypePropertiesRequest.hpp>
#include <alibabacloud/models/GetResourceTypePropertiesResponseBody.hpp>
#include <alibabacloud/models/GetResourceTypePropertiesResponse.hpp>
#include <alibabacloud/models/GetSupportedResourceRelationConfigRequest.hpp>
#include <alibabacloud/models/GetSupportedResourceRelationConfigResponseBody.hpp>
#include <alibabacloud/models/GetSupportedResourceRelationConfigResponse.hpp>
#include <alibabacloud/models/IgnoreAggregateEvaluationResultsRequest.hpp>
#include <alibabacloud/models/IgnoreAggregateEvaluationResultsShrinkRequest.hpp>
#include <alibabacloud/models/IgnoreAggregateEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/IgnoreAggregateEvaluationResultsResponse.hpp>
#include <alibabacloud/models/IgnoreEvaluationResultsRequest.hpp>
#include <alibabacloud/models/IgnoreEvaluationResultsShrinkRequest.hpp>
#include <alibabacloud/models/IgnoreEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/IgnoreEvaluationResultsResponse.hpp>
#include <alibabacloud/models/ListAggregateCompliancePacksRequest.hpp>
#include <alibabacloud/models/ListAggregateCompliancePacksShrinkRequest.hpp>
#include <alibabacloud/models/ListAggregateCompliancePacksResponseBody.hpp>
#include <alibabacloud/models/ListAggregateCompliancePacksResponse.hpp>
#include <alibabacloud/models/ListAggregateConfigDeliveryChannelsRequest.hpp>
#include <alibabacloud/models/ListAggregateConfigDeliveryChannelsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateConfigDeliveryChannelsResponse.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationResultsRequest.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationResultsResponse.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationStatisticsRequest.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationStatisticsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateConfigRuleEvaluationStatisticsResponse.hpp>
#include <alibabacloud/models/ListAggregateConfigRulesRequest.hpp>
#include <alibabacloud/models/ListAggregateConfigRulesShrinkRequest.hpp>
#include <alibabacloud/models/ListAggregateConfigRulesResponseBody.hpp>
#include <alibabacloud/models/ListAggregateConfigRulesResponse.hpp>
#include <alibabacloud/models/ListAggregateDiscoveredResourcesRequest.hpp>
#include <alibabacloud/models/ListAggregateDiscoveredResourcesResponseBody.hpp>
#include <alibabacloud/models/ListAggregateDiscoveredResourcesResponse.hpp>
#include <alibabacloud/models/ListAggregateRecommendManagedRulesRequest.hpp>
#include <alibabacloud/models/ListAggregateRecommendManagedRulesResponseBody.hpp>
#include <alibabacloud/models/ListAggregateRecommendManagedRulesResponse.hpp>
#include <alibabacloud/models/ListAggregateRemediationExecutionsRequest.hpp>
#include <alibabacloud/models/ListAggregateRemediationExecutionsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateRemediationExecutionsResponse.hpp>
#include <alibabacloud/models/ListAggregateRemediationsRequest.hpp>
#include <alibabacloud/models/ListAggregateRemediationsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateRemediationsResponse.hpp>
#include <alibabacloud/models/ListAggregateResourceEvaluationResultsRequest.hpp>
#include <alibabacloud/models/ListAggregateResourceEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateResourceEvaluationResultsResponse.hpp>
#include <alibabacloud/models/ListAggregateResourceRelationsRequest.hpp>
#include <alibabacloud/models/ListAggregateResourceRelationsResponseBody.hpp>
#include <alibabacloud/models/ListAggregateResourceRelationsResponse.hpp>
#include <alibabacloud/models/ListAggregateResourcesByAdvancedSearchRequest.hpp>
#include <alibabacloud/models/ListAggregateResourcesByAdvancedSearchResponseBody.hpp>
#include <alibabacloud/models/ListAggregateResourcesByAdvancedSearchResponse.hpp>
#include <alibabacloud/models/ListAggregatorsRequest.hpp>
#include <alibabacloud/models/ListAggregatorsShrinkRequest.hpp>
#include <alibabacloud/models/ListAggregatorsResponseBody.hpp>
#include <alibabacloud/models/ListAggregatorsResponse.hpp>
#include <alibabacloud/models/ListCompliancePackTemplatesRequest.hpp>
#include <alibabacloud/models/ListCompliancePackTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListCompliancePackTemplatesResponse.hpp>
#include <alibabacloud/models/ListCompliancePacksRequest.hpp>
#include <alibabacloud/models/ListCompliancePacksShrinkRequest.hpp>
#include <alibabacloud/models/ListCompliancePacksResponseBody.hpp>
#include <alibabacloud/models/ListCompliancePacksResponse.hpp>
#include <alibabacloud/models/ListConfigDeliveryChannelsRequest.hpp>
#include <alibabacloud/models/ListConfigDeliveryChannelsResponseBody.hpp>
#include <alibabacloud/models/ListConfigDeliveryChannelsResponse.hpp>
#include <alibabacloud/models/ListConfigRuleEvaluationResultsRequest.hpp>
#include <alibabacloud/models/ListConfigRuleEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/ListConfigRuleEvaluationResultsResponse.hpp>
#include <alibabacloud/models/ListConfigRuleEvaluationStatisticsResponseBody.hpp>
#include <alibabacloud/models/ListConfigRuleEvaluationStatisticsResponse.hpp>
#include <alibabacloud/models/ListConfigRuleOperatorsResponseBody.hpp>
#include <alibabacloud/models/ListConfigRuleOperatorsResponse.hpp>
#include <alibabacloud/models/ListConfigRulesRequest.hpp>
#include <alibabacloud/models/ListConfigRulesShrinkRequest.hpp>
#include <alibabacloud/models/ListConfigRulesResponseBody.hpp>
#include <alibabacloud/models/ListConfigRulesResponse.hpp>
#include <alibabacloud/models/ListDiscoveredResourcesRequest.hpp>
#include <alibabacloud/models/ListDiscoveredResourcesResponseBody.hpp>
#include <alibabacloud/models/ListDiscoveredResourcesResponse.hpp>
#include <alibabacloud/models/ListIntegratedServiceResponseBody.hpp>
#include <alibabacloud/models/ListIntegratedServiceResponse.hpp>
#include <alibabacloud/models/ListManagedRulesRequest.hpp>
#include <alibabacloud/models/ListManagedRulesResponseBody.hpp>
#include <alibabacloud/models/ListManagedRulesResponse.hpp>
#include <alibabacloud/models/ListPreManagedRulesRequest.hpp>
#include <alibabacloud/models/ListPreManagedRulesShrinkRequest.hpp>
#include <alibabacloud/models/ListPreManagedRulesResponseBody.hpp>
#include <alibabacloud/models/ListPreManagedRulesResponse.hpp>
#include <alibabacloud/models/ListRecommendManagedRulesRequest.hpp>
#include <alibabacloud/models/ListRecommendManagedRulesResponseBody.hpp>
#include <alibabacloud/models/ListRecommendManagedRulesResponse.hpp>
#include <alibabacloud/models/ListRemediationExecutionsRequest.hpp>
#include <alibabacloud/models/ListRemediationExecutionsResponseBody.hpp>
#include <alibabacloud/models/ListRemediationExecutionsResponse.hpp>
#include <alibabacloud/models/ListRemediationTemplatesRequest.hpp>
#include <alibabacloud/models/ListRemediationTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListRemediationTemplatesResponse.hpp>
#include <alibabacloud/models/ListRemediationsRequest.hpp>
#include <alibabacloud/models/ListRemediationsResponseBody.hpp>
#include <alibabacloud/models/ListRemediationsResponse.hpp>
#include <alibabacloud/models/ListResourceEvaluationResultsRequest.hpp>
#include <alibabacloud/models/ListResourceEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/ListResourceEvaluationResultsResponse.hpp>
#include <alibabacloud/models/ListResourceRelationsRequest.hpp>
#include <alibabacloud/models/ListResourceRelationsResponseBody.hpp>
#include <alibabacloud/models/ListResourceRelationsResponse.hpp>
#include <alibabacloud/models/ListResourcesByAdvancedSearchRequest.hpp>
#include <alibabacloud/models/ListResourcesByAdvancedSearchResponseBody.hpp>
#include <alibabacloud/models/ListResourcesByAdvancedSearchResponse.hpp>
#include <alibabacloud/models/ListSupportedProductsRequest.hpp>
#include <alibabacloud/models/ListSupportedProductsResponseBody.hpp>
#include <alibabacloud/models/ListSupportedProductsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesShrinkRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/PutEvaluationsRequest.hpp>
#include <alibabacloud/models/PutEvaluationsResponseBody.hpp>
#include <alibabacloud/models/PutEvaluationsResponse.hpp>
#include <alibabacloud/models/RevertAggregateEvaluationResultsRequest.hpp>
#include <alibabacloud/models/RevertAggregateEvaluationResultsShrinkRequest.hpp>
#include <alibabacloud/models/RevertAggregateEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/RevertAggregateEvaluationResultsResponse.hpp>
#include <alibabacloud/models/RevertEvaluationResultsRequest.hpp>
#include <alibabacloud/models/RevertEvaluationResultsShrinkRequest.hpp>
#include <alibabacloud/models/RevertEvaluationResultsResponseBody.hpp>
#include <alibabacloud/models/RevertEvaluationResultsResponse.hpp>
#include <alibabacloud/models/StartAggregateConfigRuleEvaluationRequest.hpp>
#include <alibabacloud/models/StartAggregateConfigRuleEvaluationResponseBody.hpp>
#include <alibabacloud/models/StartAggregateConfigRuleEvaluationResponse.hpp>
#include <alibabacloud/models/StartAggregateRemediationRequest.hpp>
#include <alibabacloud/models/StartAggregateRemediationResponseBody.hpp>
#include <alibabacloud/models/StartAggregateRemediationResponse.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationRequest.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationResponseBody.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationResponse.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationByResourceRequest.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationByResourceResponseBody.hpp>
#include <alibabacloud/models/StartConfigRuleEvaluationByResourceResponse.hpp>
#include <alibabacloud/models/StartConfigurationRecorderResponseBody.hpp>
#include <alibabacloud/models/StartConfigurationRecorderResponse.hpp>
#include <alibabacloud/models/StartRemediationRequest.hpp>
#include <alibabacloud/models/StartRemediationResponseBody.hpp>
#include <alibabacloud/models/StartRemediationResponse.hpp>
#include <alibabacloud/models/StopConfigurationRecorderResponseBody.hpp>
#include <alibabacloud/models/StopConfigurationRecorderResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesShrinkRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TriggerReportSendRequest.hpp>
#include <alibabacloud/models/TriggerReportSendResponseBody.hpp>
#include <alibabacloud/models/TriggerReportSendResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAggregateCompliancePackRequest.hpp>
#include <alibabacloud/models/UpdateAggregateCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAggregateCompliancePackResponseBody.hpp>
#include <alibabacloud/models/UpdateAggregateCompliancePackResponse.hpp>
#include <alibabacloud/models/UpdateAggregateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/UpdateAggregateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/UpdateAggregateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/UpdateAggregateConfigRuleRequest.hpp>
#include <alibabacloud/models/UpdateAggregateConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAggregateConfigRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateAggregateConfigRuleResponse.hpp>
#include <alibabacloud/models/UpdateAggregateRemediationRequest.hpp>
#include <alibabacloud/models/UpdateAggregateRemediationResponseBody.hpp>
#include <alibabacloud/models/UpdateAggregateRemediationResponse.hpp>
#include <alibabacloud/models/UpdateAggregatorRequest.hpp>
#include <alibabacloud/models/UpdateAggregatorShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAggregatorResponseBody.hpp>
#include <alibabacloud/models/UpdateAggregatorResponse.hpp>
#include <alibabacloud/models/UpdateCompliancePackRequest.hpp>
#include <alibabacloud/models/UpdateCompliancePackShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCompliancePackResponseBody.hpp>
#include <alibabacloud/models/UpdateCompliancePackResponse.hpp>
#include <alibabacloud/models/UpdateConfigDeliveryChannelRequest.hpp>
#include <alibabacloud/models/UpdateConfigDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/UpdateConfigDeliveryChannelResponse.hpp>
#include <alibabacloud/models/UpdateConfigRuleRequest.hpp>
#include <alibabacloud/models/UpdateConfigRuleShrinkRequest.hpp>
#include <alibabacloud/models/UpdateConfigRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateConfigRuleResponse.hpp>
#include <alibabacloud/models/UpdateConfigurationRecorderRequest.hpp>
#include <alibabacloud/models/UpdateConfigurationRecorderResponseBody.hpp>
#include <alibabacloud/models/UpdateConfigurationRecorderResponse.hpp>
#include <alibabacloud/models/UpdateIntegratedServiceStatusRequest.hpp>
#include <alibabacloud/models/UpdateIntegratedServiceStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateIntegratedServiceStatusResponse.hpp>
#include <alibabacloud/models/UpdateRemediationRequest.hpp>
#include <alibabacloud/models/UpdateRemediationResponseBody.hpp>
#include <alibabacloud/models/UpdateRemediationResponse.hpp>

#endif
