// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_UPDATEINSTANCESERVERLESSSWITCHREQUEST_HPP_
#define ALIBABACLOUD_MODELS_UPDATEINSTANCESERVERLESSSWITCHREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace AmqpOpen20191212
{
namespace Models
{
  class UpdateInstanceServerlessSwitchRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const UpdateInstanceServerlessSwitchRequest& obj) { 
      DARABONBA_PTR_TO_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(InstanceId, instanceId_);
      DARABONBA_PTR_TO_JSON(ServerlessSwitch, serverlessSwitch_);
    };
    friend void from_json(const Darabonba::Json& j, UpdateInstanceServerlessSwitchRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(InstanceId, instanceId_);
      DARABONBA_PTR_FROM_JSON(ServerlessSwitch, serverlessSwitch_);
    };
    UpdateInstanceServerlessSwitchRequest() = default ;
    UpdateInstanceServerlessSwitchRequest(const UpdateInstanceServerlessSwitchRequest &) = default ;
    UpdateInstanceServerlessSwitchRequest(UpdateInstanceServerlessSwitchRequest &&) = default ;
    UpdateInstanceServerlessSwitchRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~UpdateInstanceServerlessSwitchRequest() = default ;
    UpdateInstanceServerlessSwitchRequest& operator=(const UpdateInstanceServerlessSwitchRequest &) = default ;
    UpdateInstanceServerlessSwitchRequest& operator=(UpdateInstanceServerlessSwitchRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->clientToken_ == nullptr
        && this->instanceId_ == nullptr && this->serverlessSwitch_ == nullptr; };
    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline UpdateInstanceServerlessSwitchRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // instanceId Field Functions 
    bool hasInstanceId() const { return this->instanceId_ != nullptr;};
    void deleteInstanceId() { this->instanceId_ = nullptr;};
    inline string getInstanceId() const { DARABONBA_PTR_GET_DEFAULT(instanceId_, "") };
    inline UpdateInstanceServerlessSwitchRequest& setInstanceId(string instanceId) { DARABONBA_PTR_SET_VALUE(instanceId_, instanceId) };


    // serverlessSwitch Field Functions 
    bool hasServerlessSwitch() const { return this->serverlessSwitch_ != nullptr;};
    void deleteServerlessSwitch() { this->serverlessSwitch_ = nullptr;};
    inline bool getServerlessSwitch() const { DARABONBA_PTR_GET_DEFAULT(serverlessSwitch_, false) };
    inline UpdateInstanceServerlessSwitchRequest& setServerlessSwitch(bool serverlessSwitch) { DARABONBA_PTR_SET_VALUE(serverlessSwitch_, serverlessSwitch) };


  protected:
    // The client token that is used to ensure the idempotence of the request. The value of this parameter is generated by the client and must be unique among different requests. The token can contain only ASCII characters and cannot exceed 64 characters in length.
    shared_ptr<string> clientToken_ {};
    // The instance ID.
    // 
    // This parameter is required.
    shared_ptr<string> instanceId_ {};
    // The serverless elastic capability.
    // 
    // - true (enabled): The maximum TPS of the instance is increased to the base TPS multiplied by a factor (1.5x for Professional Edition, 2x for Enterprise/Platinum Edition).
    // 
    // - false (disabled): The maximum TPS of the instance is restored to the original base TPS.
    shared_ptr<bool> serverlessSwitch_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace AmqpOpen20191212
#endif
