// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ACCOUNTCRM20160606MODEL_HPP_
#define ALIBABACLOUD_ACCOUNTCRM20160606MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AccountOneKeyDeleteRequest.hpp>
#include <alibabacloud/models/AccountOneKeyDeleteResponseBody.hpp>
#include <alibabacloud/models/AccountOneKeyDeleteResponse.hpp>
#include <alibabacloud/models/AddCustomerLabelRequest.hpp>
#include <alibabacloud/models/AddCustomerLabelResponseBody.hpp>
#include <alibabacloud/models/AddCustomerLabelResponse.hpp>
#include <alibabacloud/models/AllowAgAccountLoginRequest.hpp>
#include <alibabacloud/models/AllowAgAccountLoginResponseBody.hpp>
#include <alibabacloud/models/AllowAgAccountLoginResponse.hpp>
#include <alibabacloud/models/ApplyAgOneKeyDeleteTaskRequest.hpp>
#include <alibabacloud/models/ApplyAgOneKeyDeleteTaskResponseBody.hpp>
#include <alibabacloud/models/ApplyAgOneKeyDeleteTaskResponse.hpp>
#include <alibabacloud/models/ApplyAgOneKeyOnlyCheckerTaskRequest.hpp>
#include <alibabacloud/models/ApplyAgOneKeyOnlyCheckerTaskResponseBody.hpp>
#include <alibabacloud/models/ApplyAgOneKeyOnlyCheckerTaskResponse.hpp>
#include <alibabacloud/models/ApplyIdentityRegistrationRequest.hpp>
#include <alibabacloud/models/ApplyIdentityRegistrationResponseBody.hpp>
#include <alibabacloud/models/ApplyIdentityRegistrationResponse.hpp>
#include <alibabacloud/models/AsyncCreateAgAccountRequest.hpp>
#include <alibabacloud/models/AsyncCreateAgAccountResponseBody.hpp>
#include <alibabacloud/models/AsyncCreateAgAccountResponse.hpp>
#include <alibabacloud/models/AsyncModifyAgLoginEmailRequest.hpp>
#include <alibabacloud/models/AsyncModifyAgLoginEmailResponseBody.hpp>
#include <alibabacloud/models/AsyncModifyAgLoginEmailResponse.hpp>
#include <alibabacloud/models/AuthAndActiveWithHidRequest.hpp>
#include <alibabacloud/models/AuthAndActiveWithHidResponseBody.hpp>
#include <alibabacloud/models/AuthAndActiveWithHidResponse.hpp>
#include <alibabacloud/models/AuthAndRefreshLoginTicketRequest.hpp>
#include <alibabacloud/models/AuthAndRefreshLoginTicketResponseBody.hpp>
#include <alibabacloud/models/AuthAndRefreshLoginTicketResponse.hpp>
#include <alibabacloud/models/AuthLoginTicketRequest.hpp>
#include <alibabacloud/models/AuthLoginTicketResponseBody.hpp>
#include <alibabacloud/models/AuthLoginTicketResponse.hpp>
#include <alibabacloud/models/BatchQueryAgAccountRequest.hpp>
#include <alibabacloud/models/BatchQueryAgAccountResponseBody.hpp>
#include <alibabacloud/models/BatchQueryAgAccountResponse.hpp>
#include <alibabacloud/models/BatchQueryCreateAccountTraceRequest.hpp>
#include <alibabacloud/models/BatchQueryCreateAccountTraceResponseBody.hpp>
#include <alibabacloud/models/BatchQueryCreateAccountTraceResponse.hpp>
#include <alibabacloud/models/BatchQueryModifyLoginEmailTraceRequest.hpp>
#include <alibabacloud/models/BatchQueryModifyLoginEmailTraceResponseBody.hpp>
#include <alibabacloud/models/BatchQueryModifyLoginEmailTraceResponse.hpp>
#include <alibabacloud/models/CancelAsyncCreateAgAccountRequest.hpp>
#include <alibabacloud/models/CancelAsyncCreateAgAccountResponseBody.hpp>
#include <alibabacloud/models/CancelAsyncCreateAgAccountResponse.hpp>
#include <alibabacloud/models/CancelAsyncModifyLoginEmailRequest.hpp>
#include <alibabacloud/models/CancelAsyncModifyLoginEmailResponseBody.hpp>
#include <alibabacloud/models/CancelAsyncModifyLoginEmailResponse.hpp>
#include <alibabacloud/models/ChangeAgAccountNationalityCodeRequest.hpp>
#include <alibabacloud/models/ChangeAgAccountNationalityCodeResponseBody.hpp>
#include <alibabacloud/models/ChangeAgAccountNationalityCodeResponse.hpp>
#include <alibabacloud/models/ChangeAgSecurityEmailRequest.hpp>
#include <alibabacloud/models/ChangeAgSecurityEmailResponseBody.hpp>
#include <alibabacloud/models/ChangeAgSecurityEmailResponse.hpp>
#include <alibabacloud/models/ChangeAgSecurityMobileRequest.hpp>
#include <alibabacloud/models/ChangeAgSecurityMobileResponseBody.hpp>
#include <alibabacloud/models/ChangeAgSecurityMobileResponse.hpp>
#include <alibabacloud/models/CreateAccountProfileInfoRequest.hpp>
#include <alibabacloud/models/CreateAccountProfileInfoResponseBody.hpp>
#include <alibabacloud/models/CreateAccountProfileInfoResponse.hpp>
#include <alibabacloud/models/CreateAgAccountRequest.hpp>
#include <alibabacloud/models/CreateAgAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAgAccountResponse.hpp>
#include <alibabacloud/models/CreateContacterRequest.hpp>
#include <alibabacloud/models/CreateContacterResponseBody.hpp>
#include <alibabacloud/models/CreateContacterResponse.hpp>
#include <alibabacloud/models/CreateRealNameCertificationRequest.hpp>
#include <alibabacloud/models/CreateRealNameCertificationResponseBody.hpp>
#include <alibabacloud/models/CreateRealNameCertificationResponse.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoLogicalDeleteRequest.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoLogicalDeleteResponseBody.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoLogicalDeleteResponse.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoPhysicalDeleteRequest.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoPhysicalDeleteResponseBody.hpp>
#include <alibabacloud/models/CustomerSensitiveInfoPhysicalDeleteResponse.hpp>
#include <alibabacloud/models/DelCacheOperateSyncRequest.hpp>
#include <alibabacloud/models/DelCacheOperateSyncResponseBody.hpp>
#include <alibabacloud/models/DelCacheOperateSyncResponse.hpp>
#include <alibabacloud/models/DeleteContacterRequest.hpp>
#include <alibabacloud/models/DeleteContacterResponseBody.hpp>
#include <alibabacloud/models/DeleteContacterResponse.hpp>
#include <alibabacloud/models/DeleteCustomerLabelRequest.hpp>
#include <alibabacloud/models/DeleteCustomerLabelResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomerLabelResponse.hpp>
#include <alibabacloud/models/ExistBindsByOuterIdRequest.hpp>
#include <alibabacloud/models/ExistBindsByOuterIdResponseBody.hpp>
#include <alibabacloud/models/ExistBindsByOuterIdResponse.hpp>
#include <alibabacloud/models/FindAllContacterRequest.hpp>
#include <alibabacloud/models/FindAllContacterResponseBody.hpp>
#include <alibabacloud/models/FindAllContacterResponse.hpp>
#include <alibabacloud/models/FindBizCategoryConfigRequest.hpp>
#include <alibabacloud/models/FindBizCategoryConfigResponseBody.hpp>
#include <alibabacloud/models/FindBizCategoryConfigResponse.hpp>
#include <alibabacloud/models/FindContacterRequest.hpp>
#include <alibabacloud/models/FindContacterResponseBody.hpp>
#include <alibabacloud/models/FindContacterResponse.hpp>
#include <alibabacloud/models/FindCustomerInfoRequest.hpp>
#include <alibabacloud/models/FindCustomerInfoResponseBody.hpp>
#include <alibabacloud/models/FindCustomerInfoResponse.hpp>
#include <alibabacloud/models/FindCustomerSnapshotRequest.hpp>
#include <alibabacloud/models/FindCustomerSnapshotResponseBody.hpp>
#include <alibabacloud/models/FindCustomerSnapshotResponse.hpp>
#include <alibabacloud/models/FindFinanceTaxRequest.hpp>
#include <alibabacloud/models/FindFinanceTaxResponseBody.hpp>
#include <alibabacloud/models/FindFinanceTaxResponse.hpp>
#include <alibabacloud/models/FindFinanceTaxDetailRequest.hpp>
#include <alibabacloud/models/FindFinanceTaxDetailResponseBody.hpp>
#include <alibabacloud/models/FindFinanceTaxDetailResponse.hpp>
#include <alibabacloud/models/FindPkByHidForLoginWithLegacyRequest.hpp>
#include <alibabacloud/models/FindPkByHidForLoginWithLegacyResponseBody.hpp>
#include <alibabacloud/models/FindPkByHidForLoginWithLegacyResponse.hpp>
#include <alibabacloud/models/ForbiddenAgAccountLoginRequest.hpp>
#include <alibabacloud/models/ForbiddenAgAccountLoginResponseBody.hpp>
#include <alibabacloud/models/ForbiddenAgAccountLoginResponse.hpp>
#include <alibabacloud/models/GenerateAliyunCertUrlRequest.hpp>
#include <alibabacloud/models/GenerateAliyunCertUrlResponseBody.hpp>
#include <alibabacloud/models/GenerateAliyunCertUrlResponse.hpp>
#include <alibabacloud/models/GetAgAccountAkRequest.hpp>
#include <alibabacloud/models/GetAgAccountAkResponseBody.hpp>
#include <alibabacloud/models/GetAgAccountAkResponse.hpp>
#include <alibabacloud/models/GetAgOneKeyDeleteTaskRequest.hpp>
#include <alibabacloud/models/GetAgOneKeyDeleteTaskResponseBody.hpp>
#include <alibabacloud/models/GetAgOneKeyDeleteTaskResponse.hpp>
#include <alibabacloud/models/GetAgRelationRequest.hpp>
#include <alibabacloud/models/GetAgRelationResponseBody.hpp>
#include <alibabacloud/models/GetAgRelationResponse.hpp>
#include <alibabacloud/models/GetAliyunIdByPkRequest.hpp>
#include <alibabacloud/models/GetAliyunIdByPkResponseBody.hpp>
#include <alibabacloud/models/GetAliyunIdByPkResponse.hpp>
#include <alibabacloud/models/GetAliyunPKByAliyunIDRequest.hpp>
#include <alibabacloud/models/GetAliyunPKByAliyunIDResponseBody.hpp>
#include <alibabacloud/models/GetAliyunPKByAliyunIDResponse.hpp>
#include <alibabacloud/models/GetCustomerCategoryRequest.hpp>
#include <alibabacloud/models/GetCustomerCategoryResponseBody.hpp>
#include <alibabacloud/models/GetCustomerCategoryResponse.hpp>
#include <alibabacloud/models/GetCustomerCategoryDictionaryRequest.hpp>
#include <alibabacloud/models/GetCustomerCategoryDictionaryResponseBody.hpp>
#include <alibabacloud/models/GetCustomerCategoryDictionaryResponse.hpp>
#include <alibabacloud/models/GetCustomerInformationRequest.hpp>
#include <alibabacloud/models/GetCustomerInformationResponseBody.hpp>
#include <alibabacloud/models/GetCustomerInformationResponse.hpp>
#include <alibabacloud/models/GetDingTalkUserOrgByAliyunTmpCodeRequest.hpp>
#include <alibabacloud/models/GetDingTalkUserOrgByAliyunTmpCodeResponseBody.hpp>
#include <alibabacloud/models/GetDingTalkUserOrgByAliyunTmpCodeResponse.hpp>
#include <alibabacloud/models/GetIdentityRegistrationByCustomerRequest.hpp>
#include <alibabacloud/models/GetIdentityRegistrationByCustomerResponseBody.hpp>
#include <alibabacloud/models/GetIdentityRegistrationByCustomerResponse.hpp>
#include <alibabacloud/models/GetProfileTypeByPkRequest.hpp>
#include <alibabacloud/models/GetProfileTypeByPkResponseBody.hpp>
#include <alibabacloud/models/GetProfileTypeByPkResponse.hpp>
#include <alibabacloud/models/GetUploadIdentityRegistrationDocConfigRequest.hpp>
#include <alibabacloud/models/GetUploadIdentityRegistrationDocConfigResponseBody.hpp>
#include <alibabacloud/models/GetUploadIdentityRegistrationDocConfigResponse.hpp>
#include <alibabacloud/models/IncrByCacheOperateSyncRequest.hpp>
#include <alibabacloud/models/IncrByCacheOperateSyncResponseBody.hpp>
#include <alibabacloud/models/IncrByCacheOperateSyncResponse.hpp>
#include <alibabacloud/models/JudgeAgExistQuietPeriodRequest.hpp>
#include <alibabacloud/models/JudgeAgExistQuietPeriodResponseBody.hpp>
#include <alibabacloud/models/JudgeAgExistQuietPeriodResponse.hpp>
#include <alibabacloud/models/LoadRealNameInfoByPkRequest.hpp>
#include <alibabacloud/models/LoadRealNameInfoByPkResponseBody.hpp>
#include <alibabacloud/models/LoadRealNameInfoByPkResponse.hpp>
#include <alibabacloud/models/MapFromHavanaBindIdRequest.hpp>
#include <alibabacloud/models/MapFromHavanaBindIdShrinkRequest.hpp>
#include <alibabacloud/models/MapFromHavanaBindIdResponseBody.hpp>
#include <alibabacloud/models/MapFromHavanaBindIdResponse.hpp>
#include <alibabacloud/models/MapPkFromHidRequest.hpp>
#include <alibabacloud/models/MapPkFromHidResponseBody.hpp>
#include <alibabacloud/models/MapPkFromHidResponse.hpp>
#include <alibabacloud/models/MapPkToHidRequest.hpp>
#include <alibabacloud/models/MapPkToHidResponseBody.hpp>
#include <alibabacloud/models/MapPkToHidResponse.hpp>
#include <alibabacloud/models/MapToHavanaBindIdRequest.hpp>
#include <alibabacloud/models/MapToHavanaBindIdShrinkRequest.hpp>
#include <alibabacloud/models/MapToHavanaBindIdResponseBody.hpp>
#include <alibabacloud/models/MapToHavanaBindIdResponse.hpp>
#include <alibabacloud/models/ModifyBizCategoryRequest.hpp>
#include <alibabacloud/models/ModifyBizCategoryResponseBody.hpp>
#include <alibabacloud/models/ModifyBizCategoryResponse.hpp>
#include <alibabacloud/models/ModifyContacterRequest.hpp>
#include <alibabacloud/models/ModifyContacterResponseBody.hpp>
#include <alibabacloud/models/ModifyContacterResponse.hpp>
#include <alibabacloud/models/ModifyCustomerInfoRequest.hpp>
#include <alibabacloud/models/ModifyCustomerInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyCustomerInfoResponse.hpp>
#include <alibabacloud/models/OperateFinanceTaxRequest.hpp>
#include <alibabacloud/models/OperateFinanceTaxResponseBody.hpp>
#include <alibabacloud/models/OperateFinanceTaxResponse.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoRequest.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoResponseBody.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoResponse.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoWithoutHavanaRequest.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoWithoutHavanaResponseBody.hpp>
#include <alibabacloud/models/QueryAccountAddressInfoWithoutHavanaResponse.hpp>
#include <alibabacloud/models/QueryAccountDeliveryAddressInfoRequest.hpp>
#include <alibabacloud/models/QueryAccountDeliveryAddressInfoResponseBody.hpp>
#include <alibabacloud/models/QueryAccountDeliveryAddressInfoResponse.hpp>
#include <alibabacloud/models/QueryAccountProfileInfoRequest.hpp>
#include <alibabacloud/models/QueryAccountProfileInfoResponseBody.hpp>
#include <alibabacloud/models/QueryAccountProfileInfoResponse.hpp>
#include <alibabacloud/models/QueryAccountRealNameInfoRequest.hpp>
#include <alibabacloud/models/QueryAccountRealNameInfoResponseBody.hpp>
#include <alibabacloud/models/QueryAccountRealNameInfoResponse.hpp>
#include <alibabacloud/models/QueryAccountSiteRequest.hpp>
#include <alibabacloud/models/QueryAccountSiteResponseBody.hpp>
#include <alibabacloud/models/QueryAccountSiteResponse.hpp>
#include <alibabacloud/models/QueryAccountTrueNameRequest.hpp>
#include <alibabacloud/models/QueryAccountTrueNameResponseBody.hpp>
#include <alibabacloud/models/QueryAccountTrueNameResponse.hpp>
#include <alibabacloud/models/QueryAgAccountLoginPermissionRequest.hpp>
#include <alibabacloud/models/QueryAgAccountLoginPermissionResponseBody.hpp>
#include <alibabacloud/models/QueryAgAccountLoginPermissionResponse.hpp>
#include <alibabacloud/models/QueryAgRelationCountAndQuotaRequest.hpp>
#include <alibabacloud/models/QueryAgRelationCountAndQuotaResponseBody.hpp>
#include <alibabacloud/models/QueryAgRelationCountAndQuotaResponse.hpp>
#include <alibabacloud/models/QueryAgSecurityMobileRequest.hpp>
#include <alibabacloud/models/QueryAgSecurityMobileResponseBody.hpp>
#include <alibabacloud/models/QueryAgSecurityMobileResponse.hpp>
#include <alibabacloud/models/QueryBindsByOuterIdRequest.hpp>
#include <alibabacloud/models/QueryBindsByOuterIdResponseBody.hpp>
#include <alibabacloud/models/QueryBindsByOuterIdResponse.hpp>
#include <alibabacloud/models/QueryBindsByPkRequest.hpp>
#include <alibabacloud/models/QueryBindsByPkShrinkRequest.hpp>
#include <alibabacloud/models/QueryBindsByPkResponseBody.hpp>
#include <alibabacloud/models/QueryBindsByPkResponse.hpp>
#include <alibabacloud/models/QueryCustomerLabelRequest.hpp>
#include <alibabacloud/models/QueryCustomerLabelResponseBody.hpp>
#include <alibabacloud/models/QueryCustomerLabelResponse.hpp>
#include <alibabacloud/models/QueryDeleteTaskCheckDataRequest.hpp>
#include <alibabacloud/models/QueryDeleteTaskCheckDataResponseBody.hpp>
#include <alibabacloud/models/QueryDeleteTaskCheckDataResponse.hpp>
#include <alibabacloud/models/QueryEncryptedAccountProfileInfoRequest.hpp>
#include <alibabacloud/models/QueryEncryptedAccountProfileInfoResponseBody.hpp>
#include <alibabacloud/models/QueryEncryptedAccountProfileInfoResponse.hpp>
#include <alibabacloud/models/QueryEnterpriseInfoRequest.hpp>
#include <alibabacloud/models/QueryEnterpriseInfoResponseBody.hpp>
#include <alibabacloud/models/QueryEnterpriseInfoResponse.hpp>
#include <alibabacloud/models/QueryEnumConfigByTypeRequest.hpp>
#include <alibabacloud/models/QueryEnumConfigByTypeResponseBody.hpp>
#include <alibabacloud/models/QueryEnumConfigByTypeResponse.hpp>
#include <alibabacloud/models/QueryOneKeyDeleteBlockListRequest.hpp>
#include <alibabacloud/models/QueryOneKeyDeleteBlockListResponseBody.hpp>
#include <alibabacloud/models/QueryOneKeyDeleteBlockListResponse.hpp>
#include <alibabacloud/models/QuerySecurityInfoRequest.hpp>
#include <alibabacloud/models/QuerySecurityInfoResponseBody.hpp>
#include <alibabacloud/models/QuerySecurityInfoResponse.hpp>
#include <alibabacloud/models/RegisterInternalAccountForBucRequest.hpp>
#include <alibabacloud/models/RegisterInternalAccountForBucResponseBody.hpp>
#include <alibabacloud/models/RegisterInternalAccountForBucResponse.hpp>
#include <alibabacloud/models/ReleaseAgAccountRequest.hpp>
#include <alibabacloud/models/ReleaseAgAccountResponseBody.hpp>
#include <alibabacloud/models/ReleaseAgAccountResponse.hpp>
#include <alibabacloud/models/ResendAsyncCreateAgAccountRequest.hpp>
#include <alibabacloud/models/ResendAsyncCreateAgAccountResponseBody.hpp>
#include <alibabacloud/models/ResendAsyncCreateAgAccountResponse.hpp>
#include <alibabacloud/models/ResendAsyncModifyLoginEmailRequest.hpp>
#include <alibabacloud/models/ResendAsyncModifyLoginEmailResponseBody.hpp>
#include <alibabacloud/models/ResendAsyncModifyLoginEmailResponse.hpp>
#include <alibabacloud/models/SeparateAgRelationRequest.hpp>
#include <alibabacloud/models/SeparateAgRelationResponseBody.hpp>
#include <alibabacloud/models/SeparateAgRelationResponse.hpp>
#include <alibabacloud/models/SetCacheOperateSyncRequest.hpp>
#include <alibabacloud/models/SetCacheOperateSyncResponseBody.hpp>
#include <alibabacloud/models/SetCacheOperateSyncResponse.hpp>
#include <alibabacloud/models/UpdateAccountAddressInfoRequest.hpp>
#include <alibabacloud/models/UpdateAccountAddressInfoShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAccountAddressInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateAccountAddressInfoResponse.hpp>
#include <alibabacloud/models/UpdateAccountProfileInfoRequest.hpp>
#include <alibabacloud/models/UpdateAccountProfileInfoShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAccountProfileInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateAccountProfileInfoResponse.hpp>
#include <alibabacloud/models/UpdateAgAccountAddressInfoRequest.hpp>
#include <alibabacloud/models/UpdateAgAccountAddressInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateAgAccountAddressInfoResponse.hpp>
#include <alibabacloud/models/UpdateAgServiceStatusRequest.hpp>
#include <alibabacloud/models/UpdateAgServiceStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateAgServiceStatusResponse.hpp>
#include <alibabacloud/models/UpdateCustomerCategoryRequest.hpp>
#include <alibabacloud/models/UpdateCustomerCategoryResponseBody.hpp>
#include <alibabacloud/models/UpdateCustomerCategoryResponse.hpp>
#include <alibabacloud/models/UpdateCustomerInformationRequest.hpp>
#include <alibabacloud/models/UpdateCustomerInformationResponseBody.hpp>
#include <alibabacloud/models/UpdateCustomerInformationResponse.hpp>
#include <alibabacloud/models/UpdateOrInsertEnterpriseInfoRequest.hpp>
#include <alibabacloud/models/UpdateOrInsertEnterpriseInfoShrinkRequest.hpp>
#include <alibabacloud/models/UpdateOrInsertEnterpriseInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateOrInsertEnterpriseInfoResponse.hpp>
#include <alibabacloud/models/DoLogicalDeleteResourceRequest.hpp>
#include <alibabacloud/models/DoLogicalDeleteResourceResponseBody.hpp>
#include <alibabacloud/models/DoLogicalDeleteResourceResponse.hpp>

#endif
