// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DAS20200116MODEL_HPP_
#define ALIBABACLOUD_DAS20200116MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DataResultValue.hpp>
#include <alibabacloud/models/DataSessionStatClientStatsValue.hpp>
#include <alibabacloud/models/DataSessionStatDbStatsValue.hpp>
#include <alibabacloud/models/DataValue.hpp>
#include <alibabacloud/models/AddHDMInstanceRequest.hpp>
#include <alibabacloud/models/AddHDMInstanceResponseBody.hpp>
#include <alibabacloud/models/AddHDMInstanceResponse.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobRequest.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponseBody.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponse.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksRequest.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksResponseBody.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksResponse.hpp>
#include <alibabacloud/models/CreateDiagnosticReportRequest.hpp>
#include <alibabacloud/models/CreateDiagnosticReportResponseBody.hpp>
#include <alibabacloud/models/CreateDiagnosticReportResponse.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskRequest.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskResponse.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserRequest.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserResponseBody.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserResponse.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisRequest.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisResponseBody.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisResponse.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagRequest.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagResponseBody.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagResponse.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisRequest.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisResponseBody.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisResponse.hpp>
#include <alibabacloud/models/CreateSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/CreateSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/CreateSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/CreateSqlLogTaskRequest.hpp>
#include <alibabacloud/models/CreateSqlLogTaskResponseBody.hpp>
#include <alibabacloud/models/CreateSqlLogTaskResponse.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskRequest.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskResponse.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskRequest.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskResponse.hpp>
#include <alibabacloud/models/DeleteSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DeleteSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DeleteStopGatewayRequest.hpp>
#include <alibabacloud/models/DeleteStopGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteStopGatewayResponse.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryRequest.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponse.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksRequest.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponse.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskRequest.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskResponse.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigRequest.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListResponse.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeHotBigKeysRequest.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponse.hpp>
#include <alibabacloud/models/DescribeHotKeysRequest.hpp>
#include <alibabacloud/models/DescribeHotKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeHotKeysResponse.hpp>
#include <alibabacloud/models/DescribeInstanceDasProRequest.hpp>
#include <alibabacloud/models/DescribeInstanceDasProResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceDasProResponse.hpp>
#include <alibabacloud/models/DescribeQueryExplainRequest.hpp>
#include <alibabacloud/models/DescribeQueryExplainResponseBody.hpp>
#include <alibabacloud/models/DescribeQueryExplainResponse.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponse.hpp>
#include <alibabacloud/models/DescribeTopBigKeysRequest.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponse.hpp>
#include <alibabacloud/models/DescribeTopHotKeysRequest.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponse.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesRequest.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesResponse.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesRequest.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponse.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesRequest.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponse.hpp>
#include <alibabacloud/models/DisableDasProRequest.hpp>
#include <alibabacloud/models/DisableDasProResponseBody.hpp>
#include <alibabacloud/models/DisableDasProResponse.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigRequest.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigResponseBody.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigResponse.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlRequest.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlResponseBody.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlResponse.hpp>
#include <alibabacloud/models/EnableDasProRequest.hpp>
#include <alibabacloud/models/EnableDasProResponseBody.hpp>
#include <alibabacloud/models/EnableDasProResponse.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlRequest.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlResponseBody.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultResponse.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticRequest.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponseBody.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponse.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesRequest.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBody.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponse.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesRequest.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponseBody.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponse.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentRequest.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentResponseBody.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentResponse.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeRequest.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponseBody.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponse.hpp>
#include <alibabacloud/models/GetBlockingDetailListRequest.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponseBody.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponse.hpp>
#include <alibabacloud/models/GetDBInstanceConnectivityDiagnosisRequest.hpp>
#include <alibabacloud/models/GetDBInstanceConnectivityDiagnosisResponseBody.hpp>
#include <alibabacloud/models/GetDBInstanceConnectivityDiagnosisResponse.hpp>
#include <alibabacloud/models/GetDasAgentSSERequest.hpp>
#include <alibabacloud/models/GetDasAgentSSEResponseBody.hpp>
#include <alibabacloud/models/GetDasAgentSSEResponse.hpp>
#include <alibabacloud/models/GetDasProServiceUsageRequest.hpp>
#include <alibabacloud/models/GetDasProServiceUsageResponseBody.hpp>
#include <alibabacloud/models/GetDasProServiceUsageResponse.hpp>
#include <alibabacloud/models/GetDasSQLLogHotDataRequest.hpp>
#include <alibabacloud/models/GetDasSQLLogHotDataResponseBody.hpp>
#include <alibabacloud/models/GetDasSQLLogHotDataResponse.hpp>
#include <alibabacloud/models/GetDeadLockDetailRequest.hpp>
#include <alibabacloud/models/GetDeadLockDetailResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockDetailResponse.hpp>
#include <alibabacloud/models/GetDeadLockDetailListRequest.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponse.hpp>
#include <alibabacloud/models/GetDeadLockHistoryRequest.hpp>
#include <alibabacloud/models/GetDeadLockHistoryResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockHistoryResponse.hpp>
#include <alibabacloud/models/GetDeadlockHistogramRequest.hpp>
#include <alibabacloud/models/GetDeadlockHistogramResponseBody.hpp>
#include <alibabacloud/models/GetDeadlockHistogramResponse.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskRequest.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskResponseBody.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskResponse.hpp>
#include <alibabacloud/models/GetErrorRequestSampleRequest.hpp>
#include <alibabacloud/models/GetErrorRequestSampleResponseBody.hpp>
#include <alibabacloud/models/GetErrorRequestSampleResponse.hpp>
#include <alibabacloud/models/GetEventSubscriptionRequest.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponseBody.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponse.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetHDMAliyunResourceSyncResultRequest.hpp>
#include <alibabacloud/models/GetHDMAliyunResourceSyncResultResponseBody.hpp>
#include <alibabacloud/models/GetHDMAliyunResourceSyncResultResponse.hpp>
#include <alibabacloud/models/GetHDMLastAliyunResourceSyncResultRequest.hpp>
#include <alibabacloud/models/GetHDMLastAliyunResourceSyncResultResponseBody.hpp>
#include <alibabacloud/models/GetHDMLastAliyunResourceSyncResultResponse.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportDetailRequest.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportDetailResponseBody.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportDetailResponse.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportListRequest.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportListResponseBody.hpp>
#include <alibabacloud/models/GetInstanceGroupInspectReportListResponse.hpp>
#include <alibabacloud/models/GetInstanceInspectionsRequest.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBody.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponse.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListRequest.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponseBody.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponse.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticRequest.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticResponseBody.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticResponse.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultRequest.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponseBody.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponse.hpp>
#include <alibabacloud/models/GetMongoDBCurrentOpRequest.hpp>
#include <alibabacloud/models/GetMongoDBCurrentOpResponseBody.hpp>
#include <alibabacloud/models/GetMongoDBCurrentOpResponse.hpp>
#include <alibabacloud/models/GetMySQLAllSessionAsyncRequest.hpp>
#include <alibabacloud/models/GetMySQLAllSessionAsyncResponseBody.hpp>
#include <alibabacloud/models/GetMySQLAllSessionAsyncResponse.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapRequest.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapResponseBody.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapResponse.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsRequest.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsResponseBody.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsResponse.hpp>
#include <alibabacloud/models/GetPfsSqlSampleRequest.hpp>
#include <alibabacloud/models/GetPfsSqlSampleResponseBody.hpp>
#include <alibabacloud/models/GetPfsSqlSampleResponse.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesRequest.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponseBody.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagResponse.hpp>
#include <alibabacloud/models/GetRedisAllSessionRequest.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponseBody.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponse.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageRequest.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponseBody.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponse.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultRequest.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultResponseBody.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultResponse.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesRequest.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponseBody.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponse.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextRequest.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextResponseBody.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextResponse.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryRequest.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponseBody.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponse.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceRequest.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceResponseBody.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceResponse.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultRequest.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBody.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponse.hpp>
#include <alibabacloud/models/KillInstanceAllSessionRequest.hpp>
#include <alibabacloud/models/KillInstanceAllSessionResponseBody.hpp>
#include <alibabacloud/models/KillInstanceAllSessionResponse.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupRequest.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupResponse.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/ModifySqlLogConfigRequest.hpp>
#include <alibabacloud/models/ModifySqlLogConfigResponseBody.hpp>
#include <alibabacloud/models/ModifySqlLogConfigResponse.hpp>
#include <alibabacloud/models/RunCloudBenchTaskRequest.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponseBody.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponse.hpp>
#include <alibabacloud/models/SetEventSubscriptionRequest.hpp>
#include <alibabacloud/models/SetEventSubscriptionResponseBody.hpp>
#include <alibabacloud/models/SetEventSubscriptionResponse.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncRequest.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponse.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusRequest.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusResponse.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncRequest.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponse.hpp>

#endif
