// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DAS20200116MODEL_HPP_
#define ALIBABACLOUD_DAS20200116MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DataResultValue.hpp>
#include <alibabacloud/models/DataSessionStatClientStatsValue.hpp>
#include <alibabacloud/models/DataSessionStatDbStatsValue.hpp>
#include <alibabacloud/models/DataValue.hpp>
#include <alibabacloud/models/AddHdmInstanceRequest.hpp>
#include <alibabacloud/models/AddHdmInstanceResponseBody.hpp>
#include <alibabacloud/models/AddHdmInstanceResponse.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobRequest.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponseBody.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponse.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksRequest.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksResponseBody.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksResponse.hpp>
#include <alibabacloud/models/CreateDiagnosticReportRequest.hpp>
#include <alibabacloud/models/CreateDiagnosticReportResponseBody.hpp>
#include <alibabacloud/models/CreateDiagnosticReportResponse.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskRequest.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskResponse.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserRequest.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserResponseBody.hpp>
#include <alibabacloud/models/CreateKillInstanceSessionTaskWithMaintainUserResponse.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisRequest.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisResponseBody.hpp>
#include <alibabacloud/models/CreateLatestDeadLockAnalysisResponse.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagRequest.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagResponseBody.hpp>
#include <alibabacloud/models/CreateQueryOptimizeTagResponse.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisRequest.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisResponseBody.hpp>
#include <alibabacloud/models/CreateRequestDiagnosisResponse.hpp>
#include <alibabacloud/models/CreateSqlLogTaskRequest.hpp>
#include <alibabacloud/models/CreateSqlLogTaskResponseBody.hpp>
#include <alibabacloud/models/CreateSqlLogTaskResponse.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskRequest.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskResponse.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskRequest.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudBenchTaskResponse.hpp>
#include <alibabacloud/models/DeleteStopGatewayRequest.hpp>
#include <alibabacloud/models/DeleteStopGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteStopGatewayResponse.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryRequest.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponse.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksRequest.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponse.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskRequest.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskResponse.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigRequest.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosticReportListResponse.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeHotBigKeysRequest.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponse.hpp>
#include <alibabacloud/models/DescribeHotKeysRequest.hpp>
#include <alibabacloud/models/DescribeHotKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeHotKeysResponse.hpp>
#include <alibabacloud/models/DescribeInstanceDasProRequest.hpp>
#include <alibabacloud/models/DescribeInstanceDasProResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceDasProResponse.hpp>
#include <alibabacloud/models/DescribeQueryExplainRequest.hpp>
#include <alibabacloud/models/DescribeQueryExplainResponseBody.hpp>
#include <alibabacloud/models/DescribeQueryExplainResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponse.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksRequest.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponse.hpp>
#include <alibabacloud/models/DescribeTopBigKeysRequest.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponse.hpp>
#include <alibabacloud/models/DescribeTopHotKeysRequest.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponse.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesRequest.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAllSqlConcurrencyControlRulesResponse.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesRequest.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponse.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesRequest.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponseBody.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponse.hpp>
#include <alibabacloud/models/DisableDasProRequest.hpp>
#include <alibabacloud/models/DisableDasProResponseBody.hpp>
#include <alibabacloud/models/DisableDasProResponse.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigRequest.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigResponseBody.hpp>
#include <alibabacloud/models/DisableInstanceDasConfigResponse.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlRequest.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlResponseBody.hpp>
#include <alibabacloud/models/DisableSqlConcurrencyControlResponse.hpp>
#include <alibabacloud/models/EnableDasProRequest.hpp>
#include <alibabacloud/models/EnableDasProResponseBody.hpp>
#include <alibabacloud/models/EnableDasProResponse.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlRequest.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlResponseBody.hpp>
#include <alibabacloud/models/EnableSqlConcurrencyControlResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponse.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultRequest.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultResponseBody.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultResponse.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticRequest.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponseBody.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponse.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesRequest.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBody.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponse.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesRequest.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponseBody.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponse.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentRequest.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentResponseBody.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventContentResponse.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeRequest.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponseBody.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponse.hpp>
#include <alibabacloud/models/GetBlockingDetailListRequest.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponseBody.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponse.hpp>
#include <alibabacloud/models/GetDbInstanceConnectivityDiagnosisRequest.hpp>
#include <alibabacloud/models/GetDbInstanceConnectivityDiagnosisResponseBody.hpp>
#include <alibabacloud/models/GetDbInstanceConnectivityDiagnosisResponse.hpp>
#include <alibabacloud/models/GetDasProServiceUsageRequest.hpp>
#include <alibabacloud/models/GetDasProServiceUsageResponseBody.hpp>
#include <alibabacloud/models/GetDasProServiceUsageResponse.hpp>
#include <alibabacloud/models/GetDasSqlLogHotDataRequest.hpp>
#include <alibabacloud/models/GetDasSqlLogHotDataResponseBody.hpp>
#include <alibabacloud/models/GetDasSqlLogHotDataResponse.hpp>
#include <alibabacloud/models/GetDeadLockDetailRequest.hpp>
#include <alibabacloud/models/GetDeadLockDetailResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockDetailResponse.hpp>
#include <alibabacloud/models/GetDeadLockDetailListRequest.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponse.hpp>
#include <alibabacloud/models/GetDeadLockHistoryRequest.hpp>
#include <alibabacloud/models/GetDeadLockHistoryResponseBody.hpp>
#include <alibabacloud/models/GetDeadLockHistoryResponse.hpp>
#include <alibabacloud/models/GetDeadlockHistogramRequest.hpp>
#include <alibabacloud/models/GetDeadlockHistogramResponseBody.hpp>
#include <alibabacloud/models/GetDeadlockHistogramResponse.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskRequest.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskResponseBody.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskResponse.hpp>
#include <alibabacloud/models/GetErrorRequestSampleRequest.hpp>
#include <alibabacloud/models/GetErrorRequestSampleResponseBody.hpp>
#include <alibabacloud/models/GetErrorRequestSampleResponse.hpp>
#include <alibabacloud/models/GetEventSubscriptionRequest.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponseBody.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponse.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdRequest.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponse.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultRequest.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultResponseBody.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultResponse.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultRequest.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultResponseBody.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultResponse.hpp>
#include <alibabacloud/models/GetInstanceInspectionsRequest.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBody.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponse.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListRequest.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponseBody.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponse.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticRequest.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticResponseBody.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticResponse.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultRequest.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponseBody.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponse.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpRequest.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpResponseBody.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpResponse.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncRequest.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBody.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponse.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapRequest.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapResponseBody.hpp>
#include <alibabacloud/models/GetPartitionsHeatmapResponse.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsRequest.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsResponseBody.hpp>
#include <alibabacloud/models/GetPfsMetricTrendsResponse.hpp>
#include <alibabacloud/models/GetPfsSqlSampleRequest.hpp>
#include <alibabacloud/models/GetPfsSqlSampleResponseBody.hpp>
#include <alibabacloud/models/GetPfsSqlSampleResponse.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesRequest.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponseBody.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeShareUrlResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponse.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagRequest.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagResponseBody.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagResponse.hpp>
#include <alibabacloud/models/GetRedisAllSessionRequest.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponseBody.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponse.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageRequest.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponseBody.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponse.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultRequest.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultResponseBody.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultResponse.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesRequest.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponseBody.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponse.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextRequest.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextResponseBody.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlKeywordsFromSqlTextResponse.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryRequest.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponseBody.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponse.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceRequest.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceResponseBody.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceResponse.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultRequest.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBody.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponse.hpp>
#include <alibabacloud/models/KillInstanceAllSessionRequest.hpp>
#include <alibabacloud/models/KillInstanceAllSessionResponseBody.hpp>
#include <alibabacloud/models/KillInstanceAllSessionResponse.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/ModifySqlLogConfigRequest.hpp>
#include <alibabacloud/models/ModifySqlLogConfigResponseBody.hpp>
#include <alibabacloud/models/ModifySqlLogConfigResponse.hpp>
#include <alibabacloud/models/RunCloudBenchTaskRequest.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponseBody.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponse.hpp>
#include <alibabacloud/models/SetEventSubscriptionRequest.hpp>
#include <alibabacloud/models/SetEventSubscriptionResponseBody.hpp>
#include <alibabacloud/models/SetEventSubscriptionResponse.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncRequest.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponse.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusRequest.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusResponse.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncRequest.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponse.hpp>
#include <alibabacloud/models/AddHdmInstanceResponseBodyData.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponseBodyDataBigKeysKeyInfo.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponseBodyDataBigKeys.hpp>
#include <alibabacloud/models/CreateCacheAnalysisJobResponseBodyData.hpp>
#include <alibabacloud/models/CreateCloudBenchTasksResponseBodyData.hpp>
#include <alibabacloud/models/CreateSqlLogTaskRequestFilters.hpp>
#include <alibabacloud/models/CreateSqlLogTaskResponseBodyData.hpp>
#include <alibabacloud/models/CreateStorageAnalysisTaskResponseBodyData.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyDataBandwidth.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyDataResource.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyDataShard.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyDataSpec.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyDataStorage.hpp>
#include <alibabacloud/models/DescribeAutoScalingConfigResponseBodyData.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponseBodyDataSpecHistory.hpp>
#include <alibabacloud/models/DescribeAutoScalingHistoryResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataBigKeysKeyInfo.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataBigKeys.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataBigKeysOfNumKeyInfo.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataBigKeysOfNum.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataExpiryKeysLevelCountExpiryLevel.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataExpiryKeysLevelCount.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataKeyPrefixesPrefix.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataKeyPrefixes.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataUnexBigKeysOfBytesKeyInfo.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataUnexBigKeysOfBytes.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataUnexBigKeysOfNumKeyInfo.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyDataUnexBigKeysOfNum.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBodyDataListCacheAnalysisJobBigKeysKeyInfo.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBodyDataListCacheAnalysisJobBigKeys.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBodyDataListCacheAnalysisJob.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBodyDataList.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisJobsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponseBodyDataListCloudbenchTasks.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponseBodyDataList.hpp>
#include <alibabacloud/models/DescribeCloudBenchTasksResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCloudbenchTaskConfigResponseBodyData.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsRequestFilters.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponseBodyDataLogs.hpp>
#include <alibabacloud/models/DescribeErrorLogRecordsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataBigKeysBigKey.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataBigKeys.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataHighTrafficKeysHighTrafficKey.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataHighTrafficKeys.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataHotKeysHotKey.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyDataHotKeys.hpp>
#include <alibabacloud/models/DescribeHotBigKeysResponseBodyData.hpp>
#include <alibabacloud/models/DescribeHotKeysResponseBodyDataHotKey.hpp>
#include <alibabacloud/models/DescribeHotKeysResponseBodyData.hpp>
#include <alibabacloud/models/DescribeQueryExplainResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncRequestFilters.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBodyDataDataItemInsItems.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBodyDataDataItem.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBodyDataData.hpp>
#include <alibabacloud/models/DescribeSlowLogHistogramAsyncResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequestFilters.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyDataLogsSqlTag.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyDataLogs.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticRequestFilters.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataDataLogsHistogramItem.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataDataLogsHistogram.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataDataLogsSqlTag.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataDataLogsTrend.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataDataLogs.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyDataData.hpp>
#include <alibabacloud/models/DescribeSlowLogStatisticResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSqlLogConfigResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsRequestFilters.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponseBodyDataItemsSqlLogRecord.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponseBodyDataItems.hpp>
#include <alibabacloud/models/DescribeSqlLogRecordsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSqlLogStatisticResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponseBodyDataFilters.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponseBodyDataQueries.hpp>
#include <alibabacloud/models/DescribeSqlLogTaskResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksRequestFilters.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponseBodyDataListFilters.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponseBodyDataList.hpp>
#include <alibabacloud/models/DescribeSqlLogTasksResponseBodyData.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponseBodyDataBigKey.hpp>
#include <alibabacloud/models/DescribeTopBigKeysResponseBodyData.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponseBodyDataHotKey.hpp>
#include <alibabacloud/models/DescribeTopHotKeysResponseBodyData.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponseBodyDataConfigFailInstanceList.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponseBodyDataConfigSuccessInstanceList.hpp>
#include <alibabacloud/models/DisableAutoResourceOptimizeRulesResponseBodyData.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponseBodyDataConfigFailInstanceList.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponseBodyDataConfigSuccessInstanceList.hpp>
#include <alibabacloud/models/DisableAutoThrottleRulesResponseBodyData.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestListByCodeResponseBodyData.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatByCodeResponseBodyData.hpp>
#include <alibabacloud/models/GetAsyncErrorRequestStatResultResponseBodyData.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponseBodyDataAutoIncrementUsageList.hpp>
#include <alibabacloud/models/GetAutoIncrementUsageStatisticResponseBodyData.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBodyDataEnableAutoResourceOptimizeList.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBodyDataHasEnableRuleButNotDasProList.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBodyDataTurnOffAutoResourceOptimizeList.hpp>
#include <alibabacloud/models/GetAutoResourceOptimizeRulesResponseBodyData.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponseBodyDataEnableAutoThrottleList.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponseBodyDataTurnOffAutoThrottleList.hpp>
#include <alibabacloud/models/GetAutoThrottleRulesResponseBodyData.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponseBodyDataList.hpp>
#include <alibabacloud/models/GetAutonomousNotifyEventsInRangeResponseBodyData.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponseBodyDataList.hpp>
#include <alibabacloud/models/GetBlockingDetailListResponseBodyData.hpp>
#include <alibabacloud/models/GetDbInstanceConnectivityDiagnosisResponseBodyData.hpp>
#include <alibabacloud/models/GetDasProServiceUsageResponseBodyData.hpp>
#include <alibabacloud/models/GetDasSqlLogHotDataResponseBodyDataList.hpp>
#include <alibabacloud/models/GetDasSqlLogHotDataResponseBodyData.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponseBodyDataListBlockProcessList.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponseBodyDataList.hpp>
#include <alibabacloud/models/GetDeadLockDetailListResponseBodyData.hpp>
#include <alibabacloud/models/GetDeadlockHistogramResponseBodyData.hpp>
#include <alibabacloud/models/GetEndpointSwitchTaskResponseBodyData.hpp>
#include <alibabacloud/models/GetErrorRequestSampleResponseBodyData.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponseBodyDataContactGroups.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponseBodyDataContacts.hpp>
#include <alibabacloud/models/GetEventSubscriptionResponseBodyData.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponseBodyDataList.hpp>
#include <alibabacloud/models/GetFullRequestOriginStatByInstanceIdResponseBodyData.hpp>
#include <alibabacloud/models/GetFullRequestSampleByInstanceIdResponseBodyData.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponseBodyDataResultList.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetFullRequestStatResultByInstanceIdResponseBodyData.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultResponseBodyDataSubResultsResourceSyncSubResult.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultResponseBodyDataSubResults.hpp>
#include <alibabacloud/models/GetHdmAliyunResourceSyncResultResponseBodyData.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultResponseBodyDataSubResultsResourceSyncSubResult.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultResponseBodyDataSubResults.hpp>
#include <alibabacloud/models/GetHdmLastAliyunResourceSyncResultResponseBodyData.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBodyDataListAutoFunction.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBodyDataListInstance.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBodyDataList.hpp>
#include <alibabacloud/models/GetInstanceInspectionsResponseBodyData.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponseBodyDataList.hpp>
#include <alibabacloud/models/GetInstanceMissingIndexListResponseBodyData.hpp>
#include <alibabacloud/models/GetInstanceSqlOptimizeStatisticResponseBodyData.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetKillInstanceSessionTaskResultResponseBodyData.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpResponseBodyDataSessionList.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpResponseBodyDataSessionStat.hpp>
#include <alibabacloud/models/GetMongoDbCurrentOpResponseBodyData.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyDataSessionDataClientStats.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyDataSessionDataDbStats.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyDataSessionDataSessionList.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyDataSessionDataUserStats.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyDataSessionData.hpp>
#include <alibabacloud/models/GetMySqlAllSessionAsyncResponseBodyData.hpp>
#include <alibabacloud/models/GetPfsSqlSampleResponseBodyData.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponseBodyDataList.hpp>
#include <alibabacloud/models/GetPfsSqlSummariesResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponseBodyDataListRuleList.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataStatsResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTopResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeDataTrendResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorSampleResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeExecErrorStatsResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeRuleListResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponseBodyDataList.hpp>
#include <alibabacloud/models/GetQueryOptimizeSolutionResponseBodyData.hpp>
#include <alibabacloud/models/GetQueryOptimizeTagResponseBodyData.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponseBodyDataSessions.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponseBodyDataSourceStats.hpp>
#include <alibabacloud/models/GetRedisAllSessionResponseBodyData.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponseBodyDataList.hpp>
#include <alibabacloud/models/GetRequestDiagnosisPageResponseBodyData.hpp>
#include <alibabacloud/models/GetRequestDiagnosisResultResponseBodyData.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponseBodyDataListRunningRules.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponseBodyDataList.hpp>
#include <alibabacloud/models/GetRunningSqlConcurrencyControlRulesResponseBodyData.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponseBodyDataListRules.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponseBodyDataList.hpp>
#include <alibabacloud/models/GetSqlConcurrencyControlRulesHistoryResponseBodyData.hpp>
#include <alibabacloud/models/GetSqlOptimizeAdviceResponseBodyData.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBodyDataStorageAnalysisResultNeedOptimizeItemList.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBodyDataStorageAnalysisResultTableStats.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBodyDataStorageAnalysisResult.hpp>
#include <alibabacloud/models/GetStorageAnalysisResultResponseBodyData.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequestBandwidth.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequestResource.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequestShard.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequestSpec.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequestStorage.hpp>
#include <alibabacloud/models/ModifySqlLogConfigRequestFilters.hpp>
#include <alibabacloud/models/ModifySqlLogConfigResponseBodyData.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponseBodyDataPreCheckItem.hpp>
#include <alibabacloud/models/RunCloudBenchTaskResponseBodyData.hpp>
#include <alibabacloud/models/SetEventSubscriptionResponseBodyData.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBodyDataConfigResponseConfigFailInstanceList.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBodyDataConfigResponseConfigSuccessInstanceList.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBodyDataConfigResponse.hpp>
#include <alibabacloud/models/UpdateAutoResourceOptimizeRulesAsyncResponseBodyData.hpp>
#include <alibabacloud/models/UpdateAutoSqlOptimizeStatusResponseBodyData.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBodyDataConfigResponseConfigFailInstanceList.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBodyDataConfigResponseConfigSuccessInstanceList.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBodyDataConfigResponse.hpp>
#include <alibabacloud/models/UpdateAutoThrottleRulesAsyncResponseBodyData.hpp>

#endif
