// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_RKVSTORE20150101MODEL_HPP_
#define ALIBABACLOUD_RKVSTORE20150101MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddShardingNodeRequest.hpp>
#include <alibabacloud/models/AddShardingNodeResponseBody.hpp>
#include <alibabacloud/models/AddShardingNodeResponse.hpp>
#include <alibabacloud/models/AllocateDirectConnectionRequest.hpp>
#include <alibabacloud/models/AllocateDirectConnectionResponseBody.hpp>
#include <alibabacloud/models/AllocateDirectConnectionResponse.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionRequest.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionResponseBody.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionResponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CheckCloudResourceAuthorizedRequest.hpp>
#include <alibabacloud/models/CheckCloudResourceAuthorizedResponseBody.hpp>
#include <alibabacloud/models/CheckCloudResourceAuthorizedResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateCacheAnalysisTaskRequest.hpp>
#include <alibabacloud/models/CreateCacheAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/CreateCacheAnalysisTaskResponse.hpp>
#include <alibabacloud/models/CreateGlobalDistributeCacheRequest.hpp>
#include <alibabacloud/models/CreateGlobalDistributeCacheResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDistributeCacheResponse.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateInstancesRequest.hpp>
#include <alibabacloud/models/CreateInstancesResponseBody.hpp>
#include <alibabacloud/models/CreateInstancesResponse.hpp>
#include <alibabacloud/models/CreateParameterGroupRequest.hpp>
#include <alibabacloud/models/CreateParameterGroupResponseBody.hpp>
#include <alibabacloud/models/CreateParameterGroupResponse.hpp>
#include <alibabacloud/models/CreateTCInstanceRequest.hpp>
#include <alibabacloud/models/CreateTCInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateTCInstanceResponse.hpp>
#include <alibabacloud/models/CreateTairInstanceRequest.hpp>
#include <alibabacloud/models/CreateTairInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateTairInstanceResponse.hpp>
#include <alibabacloud/models/CreateTairKVCacheVNodeRequest.hpp>
#include <alibabacloud/models/CreateTairKVCacheVNodeResponseBody.hpp>
#include <alibabacloud/models/CreateTairKVCacheVNodeResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteParameterGroupRequest.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponse.hpp>
#include <alibabacloud/models/DeleteShardingNodeRequest.hpp>
#include <alibabacloud/models/DeleteShardingNodeResponseBody.hpp>
#include <alibabacloud/models/DeleteShardingNodeResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintenanceConfigRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintenanceConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintenanceConfigResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskCountRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskCountResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTaskCountResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigRequest.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigResponse.hpp>
#include <alibabacloud/models/DescribeAuditRecordsRequest.hpp>
#include <alibabacloud/models/DescribeAuditRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeAuditRecordsResponse.hpp>
#include <alibabacloud/models/DescribeAvailableResourceRequest.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupTasksRequest.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportResponse.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportListRequest.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportListResponseBody.hpp>
#include <alibabacloud/models/DescribeCacheAnalysisReportListResponse.hpp>
#include <alibabacloud/models/DescribeClusterBackupListRequest.hpp>
#include <alibabacloud/models/DescribeClusterBackupListResponseBody.hpp>
#include <alibabacloud/models/DescribeClusterBackupListResponse.hpp>
#include <alibabacloud/models/DescribeClusterMemberInfoRequest.hpp>
#include <alibabacloud/models/DescribeClusterMemberInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeClusterMemberInfoResponse.hpp>
#include <alibabacloud/models/DescribeDBInstanceMonitorRequest.hpp>
#include <alibabacloud/models/DescribeDBInstanceMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeDBInstanceMonitorResponse.hpp>
#include <alibabacloud/models/DescribeDBInstanceNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDBInstanceNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDBInstanceNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDBNodeDirectVipInfoRequest.hpp>
#include <alibabacloud/models/DescribeDBNodeDirectVipInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDBNodeDirectVipInfoResponse.hpp>
#include <alibabacloud/models/DescribeDbInstanceConnectivityRequest.hpp>
#include <alibabacloud/models/DescribeDbInstanceConnectivityResponseBody.hpp>
#include <alibabacloud/models/DescribeDbInstanceConnectivityResponse.hpp>
#include <alibabacloud/models/DescribeDedicatedClusterInstanceListRequest.hpp>
#include <alibabacloud/models/DescribeDedicatedClusterInstanceListResponseBody.hpp>
#include <alibabacloud/models/DescribeDedicatedClusterInstanceListResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/DescribeEngineVersionRequest.hpp>
#include <alibabacloud/models/DescribeEngineVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeEngineVersionResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDistributeCacheRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDistributeCacheResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDistributeCacheResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/DescribeHistoryEventsRequest.hpp>
#include <alibabacloud/models/DescribeHistoryEventsResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryEventsResponse.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatResponse.hpp>
#include <alibabacloud/models/DescribeHistoryMonitorValuesRequest.hpp>
#include <alibabacloud/models/DescribeHistoryMonitorValuesResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryMonitorValuesResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponse.hpp>
#include <alibabacloud/models/DescribeInstanceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeInstanceAutoRenewalAttributeRequest.hpp>
#include <alibabacloud/models/DescribeInstanceAutoRenewalAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceAutoRenewalAttributeResponse.hpp>
#include <alibabacloud/models/DescribeInstanceConfigRequest.hpp>
#include <alibabacloud/models/DescribeInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceConfigResponse.hpp>
#include <alibabacloud/models/DescribeInstanceSSLRequest.hpp>
#include <alibabacloud/models/DescribeInstanceSSLResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceSSLResponse.hpp>
#include <alibabacloud/models/DescribeInstanceTDEStatusRequest.hpp>
#include <alibabacloud/models/DescribeInstanceTDEStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceTDEStatusResponse.hpp>
#include <alibabacloud/models/DescribeInstancesRequest.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancesResponse.hpp>
#include <alibabacloud/models/DescribeInstancesOverviewRequest.hpp>
#include <alibabacloud/models/DescribeInstancesOverviewResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancesOverviewResponse.hpp>
#include <alibabacloud/models/DescribeIntranetAttributeRequest.hpp>
#include <alibabacloud/models/DescribeIntranetAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeIntranetAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLogicInstanceTopologyRequest.hpp>
#include <alibabacloud/models/DescribeLogicInstanceTopologyResponseBody.hpp>
#include <alibabacloud/models/DescribeLogicInstanceTopologyResponse.hpp>
#include <alibabacloud/models/DescribeMonitorItemsRequest.hpp>
#include <alibabacloud/models/DescribeMonitorItemsResponseBody.hpp>
#include <alibabacloud/models/DescribeMonitorItemsResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupSupportParamRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupSupportParamResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupSupportParamResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupTemplateListRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupTemplateListResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupTemplateListResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupsRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponse.hpp>
#include <alibabacloud/models/DescribeParameterModificationHistoryRequest.hpp>
#include <alibabacloud/models/DescribeParameterModificationHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterModificationHistoryResponse.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeParametersRequest.hpp>
#include <alibabacloud/models/DescribeParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeParametersResponse.hpp>
#include <alibabacloud/models/DescribePriceRequest.hpp>
#include <alibabacloud/models/DescribePriceResponseBody.hpp>
#include <alibabacloud/models/DescribePriceResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRoleZoneInfoRequest.hpp>
#include <alibabacloud/models/DescribeRoleZoneInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeRoleZoneInfoResponse.hpp>
#include <alibabacloud/models/DescribeRunningLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeRunningLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeRunningLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSecurityGroupConfigurationRequest.hpp>
#include <alibabacloud/models/DescribeSecurityGroupConfigurationResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityGroupConfigurationResponse.hpp>
#include <alibabacloud/models/DescribeSecurityIpsRequest.hpp>
#include <alibabacloud/models/DescribeSecurityIpsResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityIpsResponse.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleExistsRequest.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleExistsResponseBody.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleExistsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeTagsRequest.hpp>
#include <alibabacloud/models/DescribeTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeTagsResponse.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceHistoryMonitorValuesRequest.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceHistoryMonitorValuesResponseBody.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstanceHistoryMonitorValuesResponse.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstancesRequest.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeTairKVCacheCustomInstancesResponse.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstanceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstanceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstancesRequest.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeTairKVCacheInferInstancesResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DestroyInstanceRequest.hpp>
#include <alibabacloud/models/DestroyInstanceResponseBody.hpp>
#include <alibabacloud/models/DestroyInstanceResponse.hpp>
#include <alibabacloud/models/EnableAdditionalBandwidthRequest.hpp>
#include <alibabacloud/models/EnableAdditionalBandwidthResponseBody.hpp>
#include <alibabacloud/models/EnableAdditionalBandwidthResponse.hpp>
#include <alibabacloud/models/FlushExpireKeysRequest.hpp>
#include <alibabacloud/models/FlushExpireKeysResponseBody.hpp>
#include <alibabacloud/models/FlushExpireKeysResponse.hpp>
#include <alibabacloud/models/FlushInstanceRequest.hpp>
#include <alibabacloud/models/FlushInstanceResponseBody.hpp>
#include <alibabacloud/models/FlushInstanceResponse.hpp>
#include <alibabacloud/models/FlushInstanceForDBRequest.hpp>
#include <alibabacloud/models/FlushInstanceForDBResponseBody.hpp>
#include <alibabacloud/models/FlushInstanceForDBResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/InitializeKvstorePermissionRequest.hpp>
#include <alibabacloud/models/InitializeKvstorePermissionResponseBody.hpp>
#include <alibabacloud/models/InitializeKvstorePermissionResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/LockDBInstanceWriteRequest.hpp>
#include <alibabacloud/models/LockDBInstanceWriteResponseBody.hpp>
#include <alibabacloud/models/LockDBInstanceWriteResponse.hpp>
#include <alibabacloud/models/MasterNodeShutDownFailOverRequest.hpp>
#include <alibabacloud/models/MasterNodeShutDownFailOverResponseBody.hpp>
#include <alibabacloud/models/MasterNodeShutDownFailOverResponse.hpp>
#include <alibabacloud/models/MigrateToOtherZoneRequest.hpp>
#include <alibabacloud/models/MigrateToOtherZoneResponseBody.hpp>
#include <alibabacloud/models/MigrateToOtherZoneResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfigRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfigResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTaskRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTaskResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigRequest.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigResponse.hpp>
#include <alibabacloud/models/ModifyBackupExpireTimeRequest.hpp>
#include <alibabacloud/models/ModifyBackupExpireTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupExpireTimeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyDBInstanceAutoUpgradeRequest.hpp>
#include <alibabacloud/models/ModifyDBInstanceAutoUpgradeResponseBody.hpp>
#include <alibabacloud/models/ModifyDBInstanceAutoUpgradeResponse.hpp>
#include <alibabacloud/models/ModifyDBInstanceConnectionStringRequest.hpp>
#include <alibabacloud/models/ModifyDBInstanceConnectionStringResponseBody.hpp>
#include <alibabacloud/models/ModifyDBInstanceConnectionStringResponse.hpp>
#include <alibabacloud/models/ModifyDBInstanceMonitorRequest.hpp>
#include <alibabacloud/models/ModifyDBInstanceMonitorResponseBody.hpp>
#include <alibabacloud/models/ModifyDBInstanceMonitorResponse.hpp>
#include <alibabacloud/models/ModifyEventInfoRequest.hpp>
#include <alibabacloud/models/ModifyEventInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyEventInfoResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyInstanceAutoRenewalAttributeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAutoRenewalAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceAutoRenewalAttributeResponse.hpp>
#include <alibabacloud/models/ModifyInstanceBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyInstanceBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyInstanceConfigRequest.hpp>
#include <alibabacloud/models/ModifyInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceConfigResponse.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyInstanceMajorVersionRequest.hpp>
#include <alibabacloud/models/ModifyInstanceMajorVersionResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceMajorVersionResponse.hpp>
#include <alibabacloud/models/ModifyInstanceMinorVersionRequest.hpp>
#include <alibabacloud/models/ModifyInstanceMinorVersionResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceMinorVersionResponse.hpp>
#include <alibabacloud/models/ModifyInstanceNetExpireTimeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceNetExpireTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceNetExpireTimeResponse.hpp>
#include <alibabacloud/models/ModifyInstanceParameterRequest.hpp>
#include <alibabacloud/models/ModifyInstanceParameterResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceParameterResponse.hpp>
#include <alibabacloud/models/ModifyInstanceSSLRequest.hpp>
#include <alibabacloud/models/ModifyInstanceSSLResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceSSLResponse.hpp>
#include <alibabacloud/models/ModifyInstanceSpecRequest.hpp>
#include <alibabacloud/models/ModifyInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceSpecResponse.hpp>
#include <alibabacloud/models/ModifyInstanceTDERequest.hpp>
#include <alibabacloud/models/ModifyInstanceTDEResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceTDEResponse.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAuthModeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAuthModeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAuthModeResponse.hpp>
#include <alibabacloud/models/ModifyIntranetAttributeRequest.hpp>
#include <alibabacloud/models/ModifyIntranetAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyIntranetAttributeResponse.hpp>
#include <alibabacloud/models/ModifyParameterGroupRequest.hpp>
#include <alibabacloud/models/ModifyParameterGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyParameterGroupResponse.hpp>
#include <alibabacloud/models/ModifyResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifySecurityGroupConfigurationRequest.hpp>
#include <alibabacloud/models/ModifySecurityGroupConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityGroupConfigurationResponse.hpp>
#include <alibabacloud/models/ModifySecurityIpsRequest.hpp>
#include <alibabacloud/models/ModifySecurityIpsResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityIpsResponse.hpp>
#include <alibabacloud/models/ModifyTairKVCacheCustomInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyTairKVCacheCustomInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyTairKVCacheCustomInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyTaskInfoRequest.hpp>
#include <alibabacloud/models/ModifyTaskInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyTaskInfoResponse.hpp>
#include <alibabacloud/models/RebootProxyRequest.hpp>
#include <alibabacloud/models/RebootProxyResponseBody.hpp>
#include <alibabacloud/models/RebootProxyResponse.hpp>
#include <alibabacloud/models/ReleaseDirectConnectionRequest.hpp>
#include <alibabacloud/models/ReleaseDirectConnectionResponseBody.hpp>
#include <alibabacloud/models/ReleaseDirectConnectionResponse.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionRequest.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionResponseBody.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionResponse.hpp>
#include <alibabacloud/models/RemoveSubInstanceRequest.hpp>
#include <alibabacloud/models/RemoveSubInstanceResponseBody.hpp>
#include <alibabacloud/models/RemoveSubInstanceResponse.hpp>
#include <alibabacloud/models/RenewAdditionalBandwidthRequest.hpp>
#include <alibabacloud/models/RenewAdditionalBandwidthResponseBody.hpp>
#include <alibabacloud/models/RenewAdditionalBandwidthResponse.hpp>
#include <alibabacloud/models/RenewInstanceRequest.hpp>
#include <alibabacloud/models/RenewInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewInstanceResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/ResetTairKVCacheCustomInstancePasswordRequest.hpp>
#include <alibabacloud/models/ResetTairKVCacheCustomInstancePasswordResponseBody.hpp>
#include <alibabacloud/models/ResetTairKVCacheCustomInstancePasswordResponse.hpp>
#include <alibabacloud/models/ResizeTairKVCacheCustomInstanceDiskRequest.hpp>
#include <alibabacloud/models/ResizeTairKVCacheCustomInstanceDiskResponseBody.hpp>
#include <alibabacloud/models/ResizeTairKVCacheCustomInstanceDiskResponse.hpp>
#include <alibabacloud/models/RestartInstanceRequest.hpp>
#include <alibabacloud/models/RestartInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartInstanceResponse.hpp>
#include <alibabacloud/models/RestartTairKVCacheCustomInstanceRequest.hpp>
#include <alibabacloud/models/RestartTairKVCacheCustomInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartTairKVCacheCustomInstanceResponse.hpp>
#include <alibabacloud/models/RestoreInstanceRequest.hpp>
#include <alibabacloud/models/RestoreInstanceResponseBody.hpp>
#include <alibabacloud/models/RestoreInstanceResponse.hpp>
#include <alibabacloud/models/StartTairKVCacheCustomInstanceRequest.hpp>
#include <alibabacloud/models/StartTairKVCacheCustomInstanceResponseBody.hpp>
#include <alibabacloud/models/StartTairKVCacheCustomInstanceResponse.hpp>
#include <alibabacloud/models/StopTairKVCacheCustomInstanceRequest.hpp>
#include <alibabacloud/models/StopTairKVCacheCustomInstanceResponseBody.hpp>
#include <alibabacloud/models/StopTairKVCacheCustomInstanceResponse.hpp>
#include <alibabacloud/models/SwitchInstanceHARequest.hpp>
#include <alibabacloud/models/SwitchInstanceHAResponseBody.hpp>
#include <alibabacloud/models/SwitchInstanceHAResponse.hpp>
#include <alibabacloud/models/SwitchInstanceProxyRequest.hpp>
#include <alibabacloud/models/SwitchInstanceProxyResponseBody.hpp>
#include <alibabacloud/models/SwitchInstanceProxyResponse.hpp>
#include <alibabacloud/models/SwitchInstanceZoneFailOverRequest.hpp>
#include <alibabacloud/models/SwitchInstanceZoneFailOverResponseBody.hpp>
#include <alibabacloud/models/SwitchInstanceZoneFailOverResponse.hpp>
#include <alibabacloud/models/SwitchNetworkRequest.hpp>
#include <alibabacloud/models/SwitchNetworkResponseBody.hpp>
#include <alibabacloud/models/SwitchNetworkResponse.hpp>
#include <alibabacloud/models/SyncDtsStatusRequest.hpp>
#include <alibabacloud/models/SyncDtsStatusResponseBody.hpp>
#include <alibabacloud/models/SyncDtsStatusResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TransformInstanceChargeTypeRequest.hpp>
#include <alibabacloud/models/TransformInstanceChargeTypeResponseBody.hpp>
#include <alibabacloud/models/TransformInstanceChargeTypeResponse.hpp>
#include <alibabacloud/models/TransformToEcsRequest.hpp>
#include <alibabacloud/models/TransformToEcsResponseBody.hpp>
#include <alibabacloud/models/TransformToEcsResponse.hpp>
#include <alibabacloud/models/TransformToPrePaidRequest.hpp>
#include <alibabacloud/models/TransformToPrePaidResponseBody.hpp>
#include <alibabacloud/models/TransformToPrePaidResponse.hpp>
#include <alibabacloud/models/UnlockDBInstanceWriteRequest.hpp>
#include <alibabacloud/models/UnlockDBInstanceWriteResponseBody.hpp>
#include <alibabacloud/models/UnlockDBInstanceWriteResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpgradeProxyRequest.hpp>
#include <alibabacloud/models/UpgradeProxyResponseBody.hpp>
#include <alibabacloud/models/UpgradeProxyResponse.hpp>

#endif
