// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_GPDB20160503MODEL_HPP_
#define ALIBABACLOUD_GPDB20160503MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ColumnMetadata.hpp>
#include <alibabacloud/models/Field.hpp>
#include <alibabacloud/models/StatementData.hpp>
#include <alibabacloud/models/AddAinodeRequest.hpp>
#include <alibabacloud/models/AddAinodeResponseBody.hpp>
#include <alibabacloud/models/AddAinodeResponse.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionRequest.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionResponseBody.hpp>
#include <alibabacloud/models/AllocateInstancePublicConnectionResponse.hpp>
#include <alibabacloud/models/BindDbresourceGroupWithRoleRequest.hpp>
#include <alibabacloud/models/BindDbresourceGroupWithRoleShrinkRequest.hpp>
#include <alibabacloud/models/BindDbresourceGroupWithRoleResponseBody.hpp>
#include <alibabacloud/models/BindDbresourceGroupWithRoleResponse.hpp>
#include <alibabacloud/models/CancelCreateIndexJobRequest.hpp>
#include <alibabacloud/models/CancelCreateIndexJobResponseBody.hpp>
#include <alibabacloud/models/CancelCreateIndexJobResponse.hpp>
#include <alibabacloud/models/CancelUploadDocumentJobRequest.hpp>
#include <alibabacloud/models/CancelUploadDocumentJobResponseBody.hpp>
#include <alibabacloud/models/CancelUploadDocumentJobResponse.hpp>
#include <alibabacloud/models/CancelUpsertCollectionDataJobRequest.hpp>
#include <alibabacloud/models/CancelUpsertCollectionDataJobResponseBody.hpp>
#include <alibabacloud/models/CancelUpsertCollectionDataJobResponse.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseShrinkRequest.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequest.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamShrinkRequest.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBody.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponse.hpp>
#include <alibabacloud/models/CheckHadoopDataSourceRequest.hpp>
#include <alibabacloud/models/CheckHadoopDataSourceResponseBody.hpp>
#include <alibabacloud/models/CheckHadoopDataSourceResponse.hpp>
#include <alibabacloud/models/CheckHadoopNetConnectionRequest.hpp>
#include <alibabacloud/models/CheckHadoopNetConnectionResponseBody.hpp>
#include <alibabacloud/models/CheckHadoopNetConnectionResponse.hpp>
#include <alibabacloud/models/CheckJdbcsourceNetConnectionRequest.hpp>
#include <alibabacloud/models/CheckJdbcsourceNetConnectionResponseBody.hpp>
#include <alibabacloud/models/CheckJdbcsourceNetConnectionResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CloneDbinstanceRequest.hpp>
#include <alibabacloud/models/CloneDbinstanceResponseBody.hpp>
#include <alibabacloud/models/CloneDbinstanceResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateCollectionRequest.hpp>
#include <alibabacloud/models/CreateCollectionShrinkRequest.hpp>
#include <alibabacloud/models/CreateCollectionResponseBody.hpp>
#include <alibabacloud/models/CreateCollectionResponse.hpp>
#include <alibabacloud/models/CreateDbinstanceRequest.hpp>
#include <alibabacloud/models/CreateDbinstanceResponseBody.hpp>
#include <alibabacloud/models/CreateDbinstanceResponse.hpp>
#include <alibabacloud/models/CreateDbinstancePlanRequest.hpp>
#include <alibabacloud/models/CreateDbinstancePlanResponseBody.hpp>
#include <alibabacloud/models/CreateDbinstancePlanResponse.hpp>
#include <alibabacloud/models/CreateDbresourceGroupRequest.hpp>
#include <alibabacloud/models/CreateDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDbresourceGroupResponse.hpp>
#include <alibabacloud/models/CreateDocumentCollectionRequest.hpp>
#include <alibabacloud/models/CreateDocumentCollectionShrinkRequest.hpp>
#include <alibabacloud/models/CreateDocumentCollectionResponseBody.hpp>
#include <alibabacloud/models/CreateDocumentCollectionResponse.hpp>
#include <alibabacloud/models/CreateExtensionsRequest.hpp>
#include <alibabacloud/models/CreateExtensionsResponseBody.hpp>
#include <alibabacloud/models/CreateExtensionsResponse.hpp>
#include <alibabacloud/models/CreateExternalDataServiceRequest.hpp>
#include <alibabacloud/models/CreateExternalDataServiceResponseBody.hpp>
#include <alibabacloud/models/CreateExternalDataServiceResponse.hpp>
#include <alibabacloud/models/CreateHadoopDataSourceRequest.hpp>
#include <alibabacloud/models/CreateHadoopDataSourceResponseBody.hpp>
#include <alibabacloud/models/CreateHadoopDataSourceResponse.hpp>
#include <alibabacloud/models/CreateIndexRequest.hpp>
#include <alibabacloud/models/CreateIndexResponseBody.hpp>
#include <alibabacloud/models/CreateIndexResponse.hpp>
#include <alibabacloud/models/CreateJdbcdataSourceRequest.hpp>
#include <alibabacloud/models/CreateJdbcdataSourceResponseBody.hpp>
#include <alibabacloud/models/CreateJdbcdataSourceResponse.hpp>
#include <alibabacloud/models/CreateModelServiceRequest.hpp>
#include <alibabacloud/models/CreateModelServiceShrinkRequest.hpp>
#include <alibabacloud/models/CreateModelServiceResponseBody.hpp>
#include <alibabacloud/models/CreateModelServiceResponse.hpp>
#include <alibabacloud/models/CreateNamespaceRequest.hpp>
#include <alibabacloud/models/CreateNamespaceResponseBody.hpp>
#include <alibabacloud/models/CreateNamespaceResponse.hpp>
#include <alibabacloud/models/CreateRemoteAdbdataSourceRequest.hpp>
#include <alibabacloud/models/CreateRemoteAdbdataSourceResponseBody.hpp>
#include <alibabacloud/models/CreateRemoteAdbdataSourceResponse.hpp>
#include <alibabacloud/models/CreateSampleDataRequest.hpp>
#include <alibabacloud/models/CreateSampleDataResponseBody.hpp>
#include <alibabacloud/models/CreateSampleDataResponse.hpp>
#include <alibabacloud/models/CreateSecretRequest.hpp>
#include <alibabacloud/models/CreateSecretResponseBody.hpp>
#include <alibabacloud/models/CreateSecretResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateStreamingDataServiceRequest.hpp>
#include <alibabacloud/models/CreateStreamingDataServiceResponseBody.hpp>
#include <alibabacloud/models/CreateStreamingDataServiceResponse.hpp>
#include <alibabacloud/models/CreateStreamingDataSourceRequest.hpp>
#include <alibabacloud/models/CreateStreamingDataSourceResponseBody.hpp>
#include <alibabacloud/models/CreateStreamingDataSourceResponse.hpp>
#include <alibabacloud/models/CreateStreamingJobRequest.hpp>
#include <alibabacloud/models/CreateStreamingJobShrinkRequest.hpp>
#include <alibabacloud/models/CreateStreamingJobResponseBody.hpp>
#include <alibabacloud/models/CreateStreamingJobResponse.hpp>
#include <alibabacloud/models/CreateSupabaseProjectRequest.hpp>
#include <alibabacloud/models/CreateSupabaseProjectResponseBody.hpp>
#include <alibabacloud/models/CreateSupabaseProjectResponse.hpp>
#include <alibabacloud/models/CreateVectorIndexRequest.hpp>
#include <alibabacloud/models/CreateVectorIndexResponseBody.hpp>
#include <alibabacloud/models/CreateVectorIndexResponse.hpp>
#include <alibabacloud/models/DeleteAinodeRequest.hpp>
#include <alibabacloud/models/DeleteAinodeResponseBody.hpp>
#include <alibabacloud/models/DeleteAinodeResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteCollectionRequest.hpp>
#include <alibabacloud/models/DeleteCollectionResponseBody.hpp>
#include <alibabacloud/models/DeleteCollectionResponse.hpp>
#include <alibabacloud/models/DeleteCollectionDataRequest.hpp>
#include <alibabacloud/models/DeleteCollectionDataResponseBody.hpp>
#include <alibabacloud/models/DeleteCollectionDataResponse.hpp>
#include <alibabacloud/models/DeleteDbinstanceRequest.hpp>
#include <alibabacloud/models/DeleteDbinstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteDbinstanceResponse.hpp>
#include <alibabacloud/models/DeleteDbinstancePlanRequest.hpp>
#include <alibabacloud/models/DeleteDbinstancePlanResponseBody.hpp>
#include <alibabacloud/models/DeleteDbinstancePlanResponse.hpp>
#include <alibabacloud/models/DeleteDbresourceGroupRequest.hpp>
#include <alibabacloud/models/DeleteDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDbresourceGroupResponse.hpp>
#include <alibabacloud/models/DeleteDocumentRequest.hpp>
#include <alibabacloud/models/DeleteDocumentResponseBody.hpp>
#include <alibabacloud/models/DeleteDocumentResponse.hpp>
#include <alibabacloud/models/DeleteDocumentCollectionRequest.hpp>
#include <alibabacloud/models/DeleteDocumentCollectionResponseBody.hpp>
#include <alibabacloud/models/DeleteDocumentCollectionResponse.hpp>
#include <alibabacloud/models/DeleteExtensionRequest.hpp>
#include <alibabacloud/models/DeleteExtensionResponseBody.hpp>
#include <alibabacloud/models/DeleteExtensionResponse.hpp>
#include <alibabacloud/models/DeleteExternalDataServiceRequest.hpp>
#include <alibabacloud/models/DeleteExternalDataServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteExternalDataServiceResponse.hpp>
#include <alibabacloud/models/DeleteHadoopDataSourceRequest.hpp>
#include <alibabacloud/models/DeleteHadoopDataSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteHadoopDataSourceResponse.hpp>
#include <alibabacloud/models/DeleteIndexRequest.hpp>
#include <alibabacloud/models/DeleteIndexResponseBody.hpp>
#include <alibabacloud/models/DeleteIndexResponse.hpp>
#include <alibabacloud/models/DeleteJdbcdataSourceRequest.hpp>
#include <alibabacloud/models/DeleteJdbcdataSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteJdbcdataSourceResponse.hpp>
#include <alibabacloud/models/DeleteModelServiceRequest.hpp>
#include <alibabacloud/models/DeleteModelServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteModelServiceResponse.hpp>
#include <alibabacloud/models/DeleteNamespaceRequest.hpp>
#include <alibabacloud/models/DeleteNamespaceResponseBody.hpp>
#include <alibabacloud/models/DeleteNamespaceResponse.hpp>
#include <alibabacloud/models/DeleteRemoteAdbdataSourceRequest.hpp>
#include <alibabacloud/models/DeleteRemoteAdbdataSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteRemoteAdbdataSourceResponse.hpp>
#include <alibabacloud/models/DeleteSecretRequest.hpp>
#include <alibabacloud/models/DeleteSecretResponseBody.hpp>
#include <alibabacloud/models/DeleteSecretResponse.hpp>
#include <alibabacloud/models/DeleteStreamingDataServiceRequest.hpp>
#include <alibabacloud/models/DeleteStreamingDataServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteStreamingDataServiceResponse.hpp>
#include <alibabacloud/models/DeleteStreamingDataSourceRequest.hpp>
#include <alibabacloud/models/DeleteStreamingDataSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteStreamingDataSourceResponse.hpp>
#include <alibabacloud/models/DeleteStreamingJobRequest.hpp>
#include <alibabacloud/models/DeleteStreamingJobResponseBody.hpp>
#include <alibabacloud/models/DeleteStreamingJobResponse.hpp>
#include <alibabacloud/models/DeleteSupabaseProjectRequest.hpp>
#include <alibabacloud/models/DeleteSupabaseProjectResponseBody.hpp>
#include <alibabacloud/models/DeleteSupabaseProjectResponse.hpp>
#include <alibabacloud/models/DeleteVectorIndexRequest.hpp>
#include <alibabacloud/models/DeleteVectorIndexResponseBody.hpp>
#include <alibabacloud/models/DeleteVectorIndexResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeActiveSqlrecordsRequest.hpp>
#include <alibabacloud/models/DescribeActiveSqlrecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveSqlrecordsResponse.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesRequest.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponse.hpp>
#include <alibabacloud/models/DescribeBackupJobRequest.hpp>
#include <alibabacloud/models/DescribeBackupJobResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupJobResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeCollectionRequest.hpp>
#include <alibabacloud/models/DescribeCollectionResponseBody.hpp>
#include <alibabacloud/models/DescribeCollectionResponse.hpp>
#include <alibabacloud/models/DescribeCreateIndexJobRequest.hpp>
#include <alibabacloud/models/DescribeCreateIndexJobResponseBody.hpp>
#include <alibabacloud/models/DescribeCreateIndexJobResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterNodeRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterNodeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterNodeResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataBloatRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataBloatResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataBloatResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSkewRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSkewResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSkewResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceErrorLogRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceErrorLogResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceErrorLogResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceIparrayListRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceIparrayListResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceIparrayListResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceIndexUsageRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceIndexUsageResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceIndexUsageResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbinstancePlansRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancePlansResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstancePlansResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceSslrequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceSslresponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceSslresponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceSupportMaxPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceSupportMaxPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceSupportMaxPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbinstancesRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponse.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupRequest.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupResponse.hpp>
#include <alibabacloud/models/DescribeDbresourceManagementModeRequest.hpp>
#include <alibabacloud/models/DescribeDbresourceManagementModeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbresourceManagementModeResponse.hpp>
#include <alibabacloud/models/DescribeDbversionInfosRequest.hpp>
#include <alibabacloud/models/DescribeDbversionInfosResponseBody.hpp>
#include <alibabacloud/models/DescribeDbversionInfosResponse.hpp>
#include <alibabacloud/models/DescribeDataBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDataBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDataBackupsResponse.hpp>
#include <alibabacloud/models/DescribeDataReDistributeInfoRequest.hpp>
#include <alibabacloud/models/DescribeDataReDistributeInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDataReDistributeInfoResponse.hpp>
#include <alibabacloud/models/DescribeDataShareInstancesRequest.hpp>
#include <alibabacloud/models/DescribeDataShareInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeDataShareInstancesResponse.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlinfoRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlinfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlinfoResponse.hpp>
#include <alibabacloud/models/DescribeDocumentRequest.hpp>
#include <alibabacloud/models/DescribeDocumentResponseBody.hpp>
#include <alibabacloud/models/DescribeDocumentResponse.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsRequest.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponse.hpp>
#include <alibabacloud/models/DescribeDownloadSqllogsRequest.hpp>
#include <alibabacloud/models/DescribeDownloadSqllogsResponseBody.hpp>
#include <alibabacloud/models/DescribeDownloadSqllogsResponse.hpp>
#include <alibabacloud/models/DescribeExternalDataServiceRequest.hpp>
#include <alibabacloud/models/DescribeExternalDataServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeExternalDataServiceResponse.hpp>
#include <alibabacloud/models/DescribeHadoopClustersInSameNetRequest.hpp>
#include <alibabacloud/models/DescribeHadoopClustersInSameNetResponseBody.hpp>
#include <alibabacloud/models/DescribeHadoopClustersInSameNetResponse.hpp>
#include <alibabacloud/models/DescribeHadoopConfigsRequest.hpp>
#include <alibabacloud/models/DescribeHadoopConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeHadoopConfigsResponse.hpp>
#include <alibabacloud/models/DescribeHadoopDataSourceRequest.hpp>
#include <alibabacloud/models/DescribeHadoopDataSourceResponseBody.hpp>
#include <alibabacloud/models/DescribeHadoopDataSourceResponse.hpp>
#include <alibabacloud/models/DescribeHealthStatusRequest.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponse.hpp>
#include <alibabacloud/models/DescribeImvinfosRequest.hpp>
#include <alibabacloud/models/DescribeImvinfosResponseBody.hpp>
#include <alibabacloud/models/DescribeImvinfosResponse.hpp>
#include <alibabacloud/models/DescribeIndexRequest.hpp>
#include <alibabacloud/models/DescribeIndexResponseBody.hpp>
#include <alibabacloud/models/DescribeIndexResponse.hpp>
#include <alibabacloud/models/DescribeJdbcdataSourceRequest.hpp>
#include <alibabacloud/models/DescribeJdbcdataSourceResponseBody.hpp>
#include <alibabacloud/models/DescribeJdbcdataSourceResponse.hpp>
#include <alibabacloud/models/DescribeLogBackupsRequest.hpp>
#include <alibabacloud/models/DescribeLogBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeLogBackupsResponse.hpp>
#include <alibabacloud/models/DescribeModelServiceRequest.hpp>
#include <alibabacloud/models/DescribeModelServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeModelServiceResponse.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogRequest.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBody.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponse.hpp>
#include <alibabacloud/models/DescribeNamespaceRequest.hpp>
#include <alibabacloud/models/DescribeNamespaceResponseBody.hpp>
#include <alibabacloud/models/DescribeNamespaceResponse.hpp>
#include <alibabacloud/models/DescribeParametersRequest.hpp>
#include <alibabacloud/models/DescribeParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeParametersResponse.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponse.hpp>
#include <alibabacloud/models/DescribeRdsVpcsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRolesRequest.hpp>
#include <alibabacloud/models/DescribeRolesResponseBody.hpp>
#include <alibabacloud/models/DescribeRolesResponse.hpp>
#include <alibabacloud/models/DescribeSqllogCountRequest.hpp>
#include <alibabacloud/models/DescribeSqllogCountResponseBody.hpp>
#include <alibabacloud/models/DescribeSqllogCountResponse.hpp>
#include <alibabacloud/models/DescribeSqllogsRequest.hpp>
#include <alibabacloud/models/DescribeSqllogsResponseBody.hpp>
#include <alibabacloud/models/DescribeSqllogsResponse.hpp>
#include <alibabacloud/models/DescribeSqllogsV2request.hpp>
#include <alibabacloud/models/DescribeSqllogsV2responseBody.hpp>
#include <alibabacloud/models/DescribeSqllogsV2response.hpp>
#include <alibabacloud/models/DescribeSampleDataRequest.hpp>
#include <alibabacloud/models/DescribeSampleDataResponseBody.hpp>
#include <alibabacloud/models/DescribeSampleDataResponse.hpp>
#include <alibabacloud/models/DescribeStreamingDataServiceRequest.hpp>
#include <alibabacloud/models/DescribeStreamingDataServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamingDataServiceResponse.hpp>
#include <alibabacloud/models/DescribeStreamingDataSourceRequest.hpp>
#include <alibabacloud/models/DescribeStreamingDataSourceResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamingDataSourceResponse.hpp>
#include <alibabacloud/models/DescribeStreamingJobRequest.hpp>
#include <alibabacloud/models/DescribeStreamingJobResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamingJobResponse.hpp>
#include <alibabacloud/models/DescribeSupportFeaturesRequest.hpp>
#include <alibabacloud/models/DescribeSupportFeaturesResponseBody.hpp>
#include <alibabacloud/models/DescribeSupportFeaturesResponse.hpp>
#include <alibabacloud/models/DescribeTableRequest.hpp>
#include <alibabacloud/models/DescribeTableResponseBody.hpp>
#include <alibabacloud/models/DescribeTableResponse.hpp>
#include <alibabacloud/models/DescribeTagsRequest.hpp>
#include <alibabacloud/models/DescribeTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeTagsResponse.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/DescribeWaitingSqlinfoRequest.hpp>
#include <alibabacloud/models/DescribeWaitingSqlinfoResponseBody.hpp>
#include <alibabacloud/models/DescribeWaitingSqlinfoResponse.hpp>
#include <alibabacloud/models/DescribeWaitingSqlrecordsRequest.hpp>
#include <alibabacloud/models/DescribeWaitingSqlrecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeWaitingSqlrecordsResponse.hpp>
#include <alibabacloud/models/DisableDbresourceGroupRequest.hpp>
#include <alibabacloud/models/DisableDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/DisableDbresourceGroupResponse.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsRequest.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsResponseBody.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsResponse.hpp>
#include <alibabacloud/models/DownloadSqllogsRecordsRequest.hpp>
#include <alibabacloud/models/DownloadSqllogsRecordsResponseBody.hpp>
#include <alibabacloud/models/DownloadSqllogsRecordsResponse.hpp>
#include <alibabacloud/models/EnableCollectionGraphRagrequest.hpp>
#include <alibabacloud/models/EnableCollectionGraphRagshrinkRequest.hpp>
#include <alibabacloud/models/EnableCollectionGraphRagresponseBody.hpp>
#include <alibabacloud/models/EnableCollectionGraphRagresponse.hpp>
#include <alibabacloud/models/EnableDbresourceGroupRequest.hpp>
#include <alibabacloud/models/EnableDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/EnableDbresourceGroupResponse.hpp>
#include <alibabacloud/models/ExecuteStatementRequest.hpp>
#include <alibabacloud/models/ExecuteStatementShrinkRequest.hpp>
#include <alibabacloud/models/ExecuteStatementResponseBody.hpp>
#include <alibabacloud/models/ExecuteStatementResponse.hpp>
#include <alibabacloud/models/GetAccountRequest.hpp>
#include <alibabacloud/models/GetAccountResponseBody.hpp>
#include <alibabacloud/models/GetAccountResponse.hpp>
#include <alibabacloud/models/GetGraphRagjobRequest.hpp>
#include <alibabacloud/models/GetGraphRagjobResponseBody.hpp>
#include <alibabacloud/models/GetGraphRagjobResponse.hpp>
#include <alibabacloud/models/GetSecretValueRequest.hpp>
#include <alibabacloud/models/GetSecretValueResponseBody.hpp>
#include <alibabacloud/models/GetSecretValueResponse.hpp>
#include <alibabacloud/models/GetStatementResultRequest.hpp>
#include <alibabacloud/models/GetStatementResultResponseBody.hpp>
#include <alibabacloud/models/GetStatementResultResponse.hpp>
#include <alibabacloud/models/GetSupabaseProjectRequest.hpp>
#include <alibabacloud/models/GetSupabaseProjectResponseBody.hpp>
#include <alibabacloud/models/GetSupabaseProjectResponse.hpp>
#include <alibabacloud/models/GetSupabaseProjectApiKeysRequest.hpp>
#include <alibabacloud/models/GetSupabaseProjectApiKeysResponseBody.hpp>
#include <alibabacloud/models/GetSupabaseProjectApiKeysResponse.hpp>
#include <alibabacloud/models/GetSupabaseProjectDashboardAccountRequest.hpp>
#include <alibabacloud/models/GetSupabaseProjectDashboardAccountResponseBody.hpp>
#include <alibabacloud/models/GetSupabaseProjectDashboardAccountResponse.hpp>
#include <alibabacloud/models/GetUploadDocumentJobRequest.hpp>
#include <alibabacloud/models/GetUploadDocumentJobResponseBody.hpp>
#include <alibabacloud/models/GetUploadDocumentJobResponse.hpp>
#include <alibabacloud/models/GetUpsertCollectionDataJobRequest.hpp>
#include <alibabacloud/models/GetUpsertCollectionDataJobResponseBody.hpp>
#include <alibabacloud/models/GetUpsertCollectionDataJobResponse.hpp>
#include <alibabacloud/models/GrantCollectionRequest.hpp>
#include <alibabacloud/models/GrantCollectionResponseBody.hpp>
#include <alibabacloud/models/GrantCollectionResponse.hpp>
#include <alibabacloud/models/HandleActiveSqlrecordRequest.hpp>
#include <alibabacloud/models/HandleActiveSqlrecordResponseBody.hpp>
#include <alibabacloud/models/HandleActiveSqlrecordResponse.hpp>
#include <alibabacloud/models/InitVectorDatabaseRequest.hpp>
#include <alibabacloud/models/InitVectorDatabaseResponseBody.hpp>
#include <alibabacloud/models/InitVectorDatabaseResponse.hpp>
#include <alibabacloud/models/ListAinodePoolsRequest.hpp>
#include <alibabacloud/models/ListAinodePoolsResponseBody.hpp>
#include <alibabacloud/models/ListAinodePoolsResponse.hpp>
#include <alibabacloud/models/ListBackupJobsRequest.hpp>
#include <alibabacloud/models/ListBackupJobsResponseBody.hpp>
#include <alibabacloud/models/ListBackupJobsResponse.hpp>
#include <alibabacloud/models/ListCollectionsRequest.hpp>
#include <alibabacloud/models/ListCollectionsResponseBody.hpp>
#include <alibabacloud/models/ListCollectionsResponse.hpp>
#include <alibabacloud/models/ListDatabasesRequest.hpp>
#include <alibabacloud/models/ListDatabasesResponseBody.hpp>
#include <alibabacloud/models/ListDatabasesResponse.hpp>
#include <alibabacloud/models/ListDocumentCollectionsRequest.hpp>
#include <alibabacloud/models/ListDocumentCollectionsResponseBody.hpp>
#include <alibabacloud/models/ListDocumentCollectionsResponse.hpp>
#include <alibabacloud/models/ListDocumentsRequest.hpp>
#include <alibabacloud/models/ListDocumentsResponseBody.hpp>
#include <alibabacloud/models/ListDocumentsResponse.hpp>
#include <alibabacloud/models/ListExternalDataServicesRequest.hpp>
#include <alibabacloud/models/ListExternalDataServicesResponseBody.hpp>
#include <alibabacloud/models/ListExternalDataServicesResponse.hpp>
#include <alibabacloud/models/ListExternalDataSourcesRequest.hpp>
#include <alibabacloud/models/ListExternalDataSourcesResponseBody.hpp>
#include <alibabacloud/models/ListExternalDataSourcesResponse.hpp>
#include <alibabacloud/models/ListIndicesRequest.hpp>
#include <alibabacloud/models/ListIndicesResponseBody.hpp>
#include <alibabacloud/models/ListIndicesResponse.hpp>
#include <alibabacloud/models/ListInstanceExtensionsRequest.hpp>
#include <alibabacloud/models/ListInstanceExtensionsResponseBody.hpp>
#include <alibabacloud/models/ListInstanceExtensionsResponse.hpp>
#include <alibabacloud/models/ListModelServicesRequest.hpp>
#include <alibabacloud/models/ListModelServicesResponseBody.hpp>
#include <alibabacloud/models/ListModelServicesResponse.hpp>
#include <alibabacloud/models/ListNamespacesRequest.hpp>
#include <alibabacloud/models/ListNamespacesResponseBody.hpp>
#include <alibabacloud/models/ListNamespacesResponse.hpp>
#include <alibabacloud/models/ListRemoteAdbdataSourcesRequest.hpp>
#include <alibabacloud/models/ListRemoteAdbdataSourcesResponseBody.hpp>
#include <alibabacloud/models/ListRemoteAdbdataSourcesResponse.hpp>
#include <alibabacloud/models/ListSchemasRequest.hpp>
#include <alibabacloud/models/ListSchemasResponseBody.hpp>
#include <alibabacloud/models/ListSchemasResponse.hpp>
#include <alibabacloud/models/ListSecretsRequest.hpp>
#include <alibabacloud/models/ListSecretsResponseBody.hpp>
#include <alibabacloud/models/ListSecretsResponse.hpp>
#include <alibabacloud/models/ListStreamingDataServicesRequest.hpp>
#include <alibabacloud/models/ListStreamingDataServicesResponseBody.hpp>
#include <alibabacloud/models/ListStreamingDataServicesResponse.hpp>
#include <alibabacloud/models/ListStreamingDataSourcesRequest.hpp>
#include <alibabacloud/models/ListStreamingDataSourcesResponseBody.hpp>
#include <alibabacloud/models/ListStreamingDataSourcesResponse.hpp>
#include <alibabacloud/models/ListStreamingJobsRequest.hpp>
#include <alibabacloud/models/ListStreamingJobsResponseBody.hpp>
#include <alibabacloud/models/ListStreamingJobsResponse.hpp>
#include <alibabacloud/models/ListSupabaseProjectsRequest.hpp>
#include <alibabacloud/models/ListSupabaseProjectsResponseBody.hpp>
#include <alibabacloud/models/ListSupabaseProjectsResponse.hpp>
#include <alibabacloud/models/ListSupportModelsRequest.hpp>
#include <alibabacloud/models/ListSupportModelsResponseBody.hpp>
#include <alibabacloud/models/ListSupportModelsResponse.hpp>
#include <alibabacloud/models/ListTablesRequest.hpp>
#include <alibabacloud/models/ListTablesResponseBody.hpp>
#include <alibabacloud/models/ListTablesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyCollectionRequest.hpp>
#include <alibabacloud/models/ModifyCollectionResponseBody.hpp>
#include <alibabacloud/models/ModifyCollectionResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceDeploymentModeRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceDeploymentModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceDeploymentModeResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceNetworkTypeRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceNetworkTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceNetworkTypeResponse.hpp>
#include <alibabacloud/models/ModifyDbinstancePayTypeRequest.hpp>
#include <alibabacloud/models/ModifyDbinstancePayTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstancePayTypeResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceSslrequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceSslresponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceSslresponse.hpp>
#include <alibabacloud/models/ModifyDbresourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbresourceGroupShrinkRequest.hpp>
#include <alibabacloud/models/ModifyDbresourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbresourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyExternalDataServiceRequest.hpp>
#include <alibabacloud/models/ModifyExternalDataServiceResponseBody.hpp>
#include <alibabacloud/models/ModifyExternalDataServiceResponse.hpp>
#include <alibabacloud/models/ModifyHadoopDataSourceRequest.hpp>
#include <alibabacloud/models/ModifyHadoopDataSourceResponseBody.hpp>
#include <alibabacloud/models/ModifyHadoopDataSourceResponse.hpp>
#include <alibabacloud/models/ModifyJdbcdataSourceRequest.hpp>
#include <alibabacloud/models/ModifyJdbcdataSourceResponseBody.hpp>
#include <alibabacloud/models/ModifyJdbcdataSourceResponse.hpp>
#include <alibabacloud/models/ModifyMasterSpecRequest.hpp>
#include <alibabacloud/models/ModifyMasterSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyMasterSpecResponse.hpp>
#include <alibabacloud/models/ModifyParametersRequest.hpp>
#include <alibabacloud/models/ModifyParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyParametersResponse.hpp>
#include <alibabacloud/models/ModifyRemoteAdbdataSourceRequest.hpp>
#include <alibabacloud/models/ModifyRemoteAdbdataSourceResponseBody.hpp>
#include <alibabacloud/models/ModifyRemoteAdbdataSourceResponse.hpp>
#include <alibabacloud/models/ModifySqlcollectorPolicyRequest.hpp>
#include <alibabacloud/models/ModifySqlcollectorPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifySqlcollectorPolicyResponse.hpp>
#include <alibabacloud/models/ModifySecurityIpsRequest.hpp>
#include <alibabacloud/models/ModifySecurityIpsResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityIpsResponse.hpp>
#include <alibabacloud/models/ModifyStreamingDataServiceRequest.hpp>
#include <alibabacloud/models/ModifyStreamingDataServiceResponseBody.hpp>
#include <alibabacloud/models/ModifyStreamingDataServiceResponse.hpp>
#include <alibabacloud/models/ModifyStreamingDataSourceRequest.hpp>
#include <alibabacloud/models/ModifyStreamingDataSourceResponseBody.hpp>
#include <alibabacloud/models/ModifyStreamingDataSourceResponse.hpp>
#include <alibabacloud/models/ModifyStreamingJobRequest.hpp>
#include <alibabacloud/models/ModifyStreamingJobShrinkRequest.hpp>
#include <alibabacloud/models/ModifyStreamingJobResponseBody.hpp>
#include <alibabacloud/models/ModifyStreamingJobResponse.hpp>
#include <alibabacloud/models/ModifySupabaseProjectSecurityIpsRequest.hpp>
#include <alibabacloud/models/ModifySupabaseProjectSecurityIpsResponseBody.hpp>
#include <alibabacloud/models/ModifySupabaseProjectSecurityIpsResponse.hpp>
#include <alibabacloud/models/ModifyVectorConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyVectorConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyVectorConfigurationResponse.hpp>
#include <alibabacloud/models/PauseDataRedistributeRequest.hpp>
#include <alibabacloud/models/PauseDataRedistributeResponseBody.hpp>
#include <alibabacloud/models/PauseDataRedistributeResponse.hpp>
#include <alibabacloud/models/PauseInstanceRequest.hpp>
#include <alibabacloud/models/PauseInstanceResponseBody.hpp>
#include <alibabacloud/models/PauseInstanceResponse.hpp>
#include <alibabacloud/models/QueryCollectionDataRequest.hpp>
#include <alibabacloud/models/QueryCollectionDataShrinkRequest.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBody.hpp>
#include <alibabacloud/models/QueryCollectionDataResponse.hpp>
#include <alibabacloud/models/QueryContentRequest.hpp>
#include <alibabacloud/models/QueryContentAdvanceRequest.hpp>
#include <alibabacloud/models/QueryContentShrinkRequest.hpp>
#include <alibabacloud/models/QueryContentResponseBody.hpp>
#include <alibabacloud/models/QueryContentResponse.hpp>
#include <alibabacloud/models/RebalanceDbinstanceRequest.hpp>
#include <alibabacloud/models/RebalanceDbinstanceResponseBody.hpp>
#include <alibabacloud/models/RebalanceDbinstanceResponse.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionRequest.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionResponseBody.hpp>
#include <alibabacloud/models/ReleaseInstancePublicConnectionResponse.hpp>
#include <alibabacloud/models/RerankRequest.hpp>
#include <alibabacloud/models/RerankShrinkRequest.hpp>
#include <alibabacloud/models/RerankResponseBody.hpp>
#include <alibabacloud/models/RerankResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/ResetImvmonitorDataRequest.hpp>
#include <alibabacloud/models/ResetImvmonitorDataResponseBody.hpp>
#include <alibabacloud/models/ResetImvmonitorDataResponse.hpp>
#include <alibabacloud/models/ResetSupabaseProjectPasswordRequest.hpp>
#include <alibabacloud/models/ResetSupabaseProjectPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetSupabaseProjectPasswordResponse.hpp>
#include <alibabacloud/models/RestartDbinstanceRequest.hpp>
#include <alibabacloud/models/RestartDbinstanceResponseBody.hpp>
#include <alibabacloud/models/RestartDbinstanceResponse.hpp>
#include <alibabacloud/models/ResumeDataRedistributeRequest.hpp>
#include <alibabacloud/models/ResumeDataRedistributeResponseBody.hpp>
#include <alibabacloud/models/ResumeDataRedistributeResponse.hpp>
#include <alibabacloud/models/ResumeInstanceRequest.hpp>
#include <alibabacloud/models/ResumeInstanceResponseBody.hpp>
#include <alibabacloud/models/ResumeInstanceResponse.hpp>
#include <alibabacloud/models/SetDbinstancePlanStatusRequest.hpp>
#include <alibabacloud/models/SetDbinstancePlanStatusResponseBody.hpp>
#include <alibabacloud/models/SetDbinstancePlanStatusResponse.hpp>
#include <alibabacloud/models/SetDataShareInstanceRequest.hpp>
#include <alibabacloud/models/SetDataShareInstanceShrinkRequest.hpp>
#include <alibabacloud/models/SetDataShareInstanceResponseBody.hpp>
#include <alibabacloud/models/SetDataShareInstanceResponse.hpp>
#include <alibabacloud/models/SwitchDbinstanceNetTypeRequest.hpp>
#include <alibabacloud/models/SwitchDbinstanceNetTypeResponseBody.hpp>
#include <alibabacloud/models/SwitchDbinstanceNetTypeResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TextEmbeddingRequest.hpp>
#include <alibabacloud/models/TextEmbeddingShrinkRequest.hpp>
#include <alibabacloud/models/TextEmbeddingResponseBody.hpp>
#include <alibabacloud/models/TextEmbeddingResponse.hpp>
#include <alibabacloud/models/UnbindDbresourceGroupWithRoleRequest.hpp>
#include <alibabacloud/models/UnbindDbresourceGroupWithRoleShrinkRequest.hpp>
#include <alibabacloud/models/UnbindDbresourceGroupWithRoleResponseBody.hpp>
#include <alibabacloud/models/UnbindDbresourceGroupWithRoleResponse.hpp>
#include <alibabacloud/models/UnloadSampleDataRequest.hpp>
#include <alibabacloud/models/UnloadSampleDataResponseBody.hpp>
#include <alibabacloud/models/UnloadSampleDataResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateCollectionDataMetadataRequest.hpp>
#include <alibabacloud/models/UpdateCollectionDataMetadataShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCollectionDataMetadataResponseBody.hpp>
#include <alibabacloud/models/UpdateCollectionDataMetadataResponse.hpp>
#include <alibabacloud/models/UpdateDbinstancePlanRequest.hpp>
#include <alibabacloud/models/UpdateDbinstancePlanResponseBody.hpp>
#include <alibabacloud/models/UpdateDbinstancePlanResponse.hpp>
#include <alibabacloud/models/UpgradeDbinstanceRequest.hpp>
#include <alibabacloud/models/UpgradeDbinstanceResponseBody.hpp>
#include <alibabacloud/models/UpgradeDbinstanceResponse.hpp>
#include <alibabacloud/models/UpgradeDbversionRequest.hpp>
#include <alibabacloud/models/UpgradeDbversionResponseBody.hpp>
#include <alibabacloud/models/UpgradeDbversionResponse.hpp>
#include <alibabacloud/models/UpgradeExtensionsRequest.hpp>
#include <alibabacloud/models/UpgradeExtensionsResponseBody.hpp>
#include <alibabacloud/models/UpgradeExtensionsResponse.hpp>
#include <alibabacloud/models/UploadDocumentAsyncRequest.hpp>
#include <alibabacloud/models/UploadDocumentAsyncAdvanceRequest.hpp>
#include <alibabacloud/models/UploadDocumentAsyncShrinkRequest.hpp>
#include <alibabacloud/models/UploadDocumentAsyncResponseBody.hpp>
#include <alibabacloud/models/UploadDocumentAsyncResponse.hpp>
#include <alibabacloud/models/UpsertChunksRequest.hpp>
#include <alibabacloud/models/UpsertChunksShrinkRequest.hpp>
#include <alibabacloud/models/UpsertChunksResponseBody.hpp>
#include <alibabacloud/models/UpsertChunksResponse.hpp>
#include <alibabacloud/models/UpsertCollectionDataRequest.hpp>
#include <alibabacloud/models/UpsertCollectionDataShrinkRequest.hpp>
#include <alibabacloud/models/UpsertCollectionDataResponseBody.hpp>
#include <alibabacloud/models/UpsertCollectionDataResponse.hpp>
#include <alibabacloud/models/UpsertCollectionDataAsyncRequest.hpp>
#include <alibabacloud/models/UpsertCollectionDataAsyncAdvanceRequest.hpp>
#include <alibabacloud/models/UpsertCollectionDataAsyncResponseBody.hpp>
#include <alibabacloud/models/UpsertCollectionDataAsyncResponse.hpp>
#include <alibabacloud/models/AddAinodeRequestAinodeSpecInfos.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsMergeMethodArgsRrf.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsMergeMethodArgsWeight.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsMergeMethodArgs.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsSourceCollectionQueryParamsGraphSearchArgs.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsSourceCollectionQueryParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParamsSourceCollection.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestKnowledgeParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestModelParamsMessages.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestModelParamsToolsFunction.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestModelParamsTools.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseRequestModelParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionChoicesMessageToolCallsFunction.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionChoicesMessageToolCalls.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionChoicesMessage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionChoices.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionUsagePromptTokensDetails.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletionUsage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyChatCompletion.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyMultiCollectionRecallResultMatchesMetadata.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyMultiCollectionRecallResultMatches.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyMultiCollectionRecallResultUsage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseResponseBodyMultiCollectionRecallResult.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsMergeMethodArgsRrf.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsMergeMethodArgsWeight.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsMergeMethodArgs.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsSourceCollectionQueryParamsGraphSearchArgs.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsSourceCollectionQueryParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParamsSourceCollection.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestKnowledgeParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestModelParamsMessages.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestModelParamsToolsFunction.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestModelParamsTools.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamRequestModelParams.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionChoicesMessageToolCallsFunction.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionChoicesMessageToolCalls.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionChoicesMessage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionChoices.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionUsagePromptTokensDetails.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletionUsage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyChatCompletion.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyMultiCollectionRecallResultMatchesMetadata.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyMultiCollectionRecallResultMatches.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyMultiCollectionRecallResultUsage.hpp>
#include <alibabacloud/models/ChatWithKnowledgeBaseStreamResponseBodyMultiCollectionRecallResult.hpp>
#include <alibabacloud/models/CreateCollectionRequestSparseVectorIndexConfig.hpp>
#include <alibabacloud/models/CreateDbinstanceRequestAinodeSpecInfos.hpp>
#include <alibabacloud/models/CreateDbinstanceRequestTag.hpp>
#include <alibabacloud/models/CreateRemoteAdbdataSourceResponseBodyDataSourceItem.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountsDbinstanceAccount.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccounts.hpp>
#include <alibabacloud/models/DescribeActiveSqlrecordsResponseBodyQueries.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBodyResourcesSupportedEnginesSupportedInstanceClassesNodeCount.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBodyResourcesSupportedEnginesSupportedInstanceClassesStorageSize.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBodyResourcesSupportedEnginesSupportedInstanceClasses.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBodyResourcesSupportedEngines.hpp>
#include <alibabacloud/models/DescribeAvailableResourcesResponseBodyResources.hpp>
#include <alibabacloud/models/DescribeCreateIndexJobResponseBodyJob.hpp>
#include <alibabacloud/models/DescribeDbclusterNodeResponseBodyNodes.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeysSeriesValues.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeysSeries.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyItemsDbinstanceAttributeTagsTag.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyItemsDbinstanceAttributeTags.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyItemsDbinstanceAttribute.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataBloatResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSkewResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryResponseBodyMasterStatusInfo.hpp>
#include <alibabacloud/models/DescribeDbinstanceDiagnosisSummaryResponseBodySegmentStatusInfo.hpp>
#include <alibabacloud/models/DescribeDbinstanceErrorLogResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceIparrayListResponseBodyItemsDbinstanceIparray.hpp>
#include <alibabacloud/models/DescribeDbinstanceIparrayListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceIndexUsageResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceNetInfoResponseBodyDbinstanceNetInfosDbinstanceNetInfo.hpp>
#include <alibabacloud/models/DescribeDbinstanceNetInfoResponseBodyDbinstanceNetInfos.hpp>
#include <alibabacloud/models/DescribeDbinstancePlansResponseBodyItemsPlanList.hpp>
#include <alibabacloud/models/DescribeDbinstancePlansResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceSupportMaxPerformanceResponseBodyPerformancesPerformance.hpp>
#include <alibabacloud/models/DescribeDbinstanceSupportMaxPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDbinstancesRequestTag.hpp>
#include <alibabacloud/models/DescribeDbinstancesShrinkRequestTag.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyItemsDbinstanceTagsTag.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyItemsDbinstanceTags.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyItemsDbinstance.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupResponseBodyResourceGroupItemsResourceGroupItemRoleList.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupResponseBodyResourceGroupItemsResourceGroupItem.hpp>
#include <alibabacloud/models/DescribeDbresourceGroupResponseBodyResourceGroupItems.hpp>
#include <alibabacloud/models/DescribeDbversionInfosResponseBodyVersionDetails.hpp>
#include <alibabacloud/models/DescribeDataBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDataReDistributeInfoResponseBodyDataReDistributeInfo.hpp>
#include <alibabacloud/models/DescribeDataShareInstancesResponseBodyItemsDbinstance.hpp>
#include <alibabacloud/models/DescribeDataShareInstancesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceResponseBodyPerformanceKeysSeriesValues.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceResponseBodyPerformanceKeysSeries.hpp>
#include <alibabacloud/models/DescribeDataSharePerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponseBodyRecords.hpp>
#include <alibabacloud/models/DescribeDownloadSqllogsResponseBodyRecords.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbgpSegmentDiskUsagePercentMax.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgConnectionStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgDiskStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgDiskUsagePercent.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgInstanceColdDataGb.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgInstanceHotDataGb.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgInstanceTotalDataGb.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgMasterDiskUsagePercentMax.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgMasterStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgSegmentStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusAdbpgStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusNodeMasterConnectionStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusNodeMasterStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusNodeSegmentConnectionStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatusNodeSegmentDiskStatus.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyStatus.hpp>
#include <alibabacloud/models/DescribeImvinfosResponseBodyImvInfos.hpp>
#include <alibabacloud/models/DescribeLogBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBodyChangelogs.hpp>
#include <alibabacloud/models/DescribeParametersResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBodyVswitchesVswitch.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBodyVswitches.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpcVswitchs.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpc.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZonesZone.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeRolesResponseBodyRoleList.hpp>
#include <alibabacloud/models/DescribeSqllogCountResponseBodyItemsSeriesValues.hpp>
#include <alibabacloud/models/DescribeSqllogCountResponseBodyItemsSeries.hpp>
#include <alibabacloud/models/DescribeSqllogCountResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSqllogsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSqllogsV2responseBodyItems.hpp>
#include <alibabacloud/models/DescribeTableResponseBodyColumnList.hpp>
#include <alibabacloud/models/DescribeTagsResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBodyKmsKeys.hpp>
#include <alibabacloud/models/DescribeWaitingSqlinfoResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeWaitingSqlrecordsResponseBodyItems.hpp>
#include <alibabacloud/models/ExecuteStatementRequestRagWorkspaceCollection.hpp>
#include <alibabacloud/models/ExecuteStatementResponseBodyDataColumnMetadata.hpp>
#include <alibabacloud/models/ExecuteStatementResponseBodyDataRecordsRecords.hpp>
#include <alibabacloud/models/ExecuteStatementResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ExecuteStatementResponseBodyData.hpp>
#include <alibabacloud/models/GetGraphRagjobResponseBodyJob.hpp>
#include <alibabacloud/models/GetGraphRagjobResponseBodyUsage.hpp>
#include <alibabacloud/models/GetStatementResultResponseBodyDataColumnMetadata.hpp>
#include <alibabacloud/models/GetStatementResultResponseBodyDataRecordsRecords.hpp>
#include <alibabacloud/models/GetStatementResultResponseBodyDataRecords.hpp>
#include <alibabacloud/models/GetStatementResultResponseBodyData.hpp>
#include <alibabacloud/models/GetSupabaseProjectApiKeysResponseBodyApiKeys.hpp>
#include <alibabacloud/models/GetUploadDocumentJobResponseBodyChunkResult.hpp>
#include <alibabacloud/models/GetUploadDocumentJobResponseBodyJob.hpp>
#include <alibabacloud/models/GetUploadDocumentJobResponseBodyUsage.hpp>
#include <alibabacloud/models/GetUpsertCollectionDataJobResponseBodyJob.hpp>
#include <alibabacloud/models/HandleActiveSqlrecordResponseBodyResults.hpp>
#include <alibabacloud/models/ListAinodePoolsResponseBodyAinodePoolInfosAinodeInfos.hpp>
#include <alibabacloud/models/ListAinodePoolsResponseBodyAinodePoolInfos.hpp>
#include <alibabacloud/models/ListBackupJobsResponseBodyItemsBackupJob.hpp>
#include <alibabacloud/models/ListBackupJobsResponseBodyItems.hpp>
#include <alibabacloud/models/ListCollectionsResponseBodyCollections.hpp>
#include <alibabacloud/models/ListDatabasesResponseBodyDatabases.hpp>
#include <alibabacloud/models/ListDocumentCollectionsResponseBodyItemsCollectionList.hpp>
#include <alibabacloud/models/ListDocumentCollectionsResponseBodyItems.hpp>
#include <alibabacloud/models/ListDocumentsResponseBodyItemsDocumentList.hpp>
#include <alibabacloud/models/ListDocumentsResponseBodyItems.hpp>
#include <alibabacloud/models/ListExternalDataServicesResponseBodyServiceItems.hpp>
#include <alibabacloud/models/ListExternalDataSourcesResponseBodyItems.hpp>
#include <alibabacloud/models/ListIndicesResponseBodyIndicesIndices.hpp>
#include <alibabacloud/models/ListIndicesResponseBodyIndices.hpp>
#include <alibabacloud/models/ListInstanceExtensionsResponseBodyItems.hpp>
#include <alibabacloud/models/ListModelServicesResponseBodyModelServices.hpp>
#include <alibabacloud/models/ListNamespacesResponseBodyNamespaces.hpp>
#include <alibabacloud/models/ListRemoteAdbdataSourcesResponseBodyDataSourceItemsRemoteDataSources.hpp>
#include <alibabacloud/models/ListRemoteAdbdataSourcesResponseBodyDataSourceItems.hpp>
#include <alibabacloud/models/ListSchemasResponseBodySchemas.hpp>
#include <alibabacloud/models/ListSecretsResponseBodySecretsSecrets.hpp>
#include <alibabacloud/models/ListSecretsResponseBodySecrets.hpp>
#include <alibabacloud/models/ListStreamingDataServicesResponseBodyServiceItems.hpp>
#include <alibabacloud/models/ListStreamingDataSourcesResponseBodyDataSourceItems.hpp>
#include <alibabacloud/models/ListStreamingJobsResponseBodyJobItems.hpp>
#include <alibabacloud/models/ListSupabaseProjectsResponseBodyItems.hpp>
#include <alibabacloud/models/ListSupportModelsResponseBodyModelNames.hpp>
#include <alibabacloud/models/ListTablesResponseBodyTables.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyDbresourceGroupRequestResourceGroupItems.hpp>
#include <alibabacloud/models/ModifyRemoteAdbdataSourceResponseBodyDataSourceItem.hpp>
#include <alibabacloud/models/QueryCollectionDataRequestRelationalTableFilter.hpp>
#include <alibabacloud/models/QueryCollectionDataRequestSparseVector.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatchesMatchSparseValuesIndices.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatchesMatchSparseValuesValues.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatchesMatchSparseValues.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatchesMatchValues.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatchesMatch.hpp>
#include <alibabacloud/models/QueryCollectionDataResponseBodyMatches.hpp>
#include <alibabacloud/models/QueryContentRequestGraphSearchArgs.hpp>
#include <alibabacloud/models/QueryContentAdvanceRequestGraphSearchArgs.hpp>
#include <alibabacloud/models/QueryContentResponseBodyEntitiesEntities.hpp>
#include <alibabacloud/models/QueryContentResponseBodyEntities.hpp>
#include <alibabacloud/models/QueryContentResponseBodyMatchesMatchListVector.hpp>
#include <alibabacloud/models/QueryContentResponseBodyMatchesMatchList.hpp>
#include <alibabacloud/models/QueryContentResponseBodyMatches.hpp>
#include <alibabacloud/models/QueryContentResponseBodyRelationsRelations.hpp>
#include <alibabacloud/models/QueryContentResponseBodyRelations.hpp>
#include <alibabacloud/models/QueryContentResponseBodyUsage.hpp>
#include <alibabacloud/models/QueryContentResponseBodyWindowMatchesWindowMatchesWindowMatchWindowMatch.hpp>
#include <alibabacloud/models/QueryContentResponseBodyWindowMatchesWindowMatchesWindowMatch.hpp>
#include <alibabacloud/models/QueryContentResponseBodyWindowMatchesWindowMatches.hpp>
#include <alibabacloud/models/QueryContentResponseBodyWindowMatches.hpp>
#include <alibabacloud/models/RerankResponseBodyResultsResults.hpp>
#include <alibabacloud/models/RerankResponseBodyResults.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/TextEmbeddingResponseBodyResultsResultsEmbedding.hpp>
#include <alibabacloud/models/TextEmbeddingResponseBodyResultsResults.hpp>
#include <alibabacloud/models/TextEmbeddingResponseBodyResults.hpp>
#include <alibabacloud/models/UpsertChunksRequestTextChunks.hpp>
#include <alibabacloud/models/UpsertCollectionDataRequestRowsSparseVector.hpp>
#include <alibabacloud/models/UpsertCollectionDataRequestRows.hpp>

#endif
