// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ADBAI20250812MODEL_HPP_
#define ALIBABACLOUD_ADBAI20250812MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateAgentPlatformRequest.hpp>
#include <alibabacloud/models/CreateAgentPlatformShrinkRequest.hpp>
#include <alibabacloud/models/CreateAgentPlatformResponseBody.hpp>
#include <alibabacloud/models/CreateAgentPlatformResponse.hpp>
#include <alibabacloud/models/CreateEmbodiedAIPlatformRequest.hpp>
#include <alibabacloud/models/CreateEmbodiedAIPlatformShrinkRequest.hpp>
#include <alibabacloud/models/CreateEmbodiedAIPlatformResponseBody.hpp>
#include <alibabacloud/models/CreateEmbodiedAIPlatformResponse.hpp>
#include <alibabacloud/models/DeleteAgentPlatformRequest.hpp>
#include <alibabacloud/models/DeleteAgentPlatformResponseBody.hpp>
#include <alibabacloud/models/DeleteAgentPlatformResponse.hpp>
#include <alibabacloud/models/DeleteEmbodiedAIPlatformRequest.hpp>
#include <alibabacloud/models/DeleteEmbodiedAIPlatformResponseBody.hpp>
#include <alibabacloud/models/DeleteEmbodiedAIPlatformResponse.hpp>
#include <alibabacloud/models/DescribeChatMessageRequest.hpp>
#include <alibabacloud/models/DescribeChatMessageResponseBody.hpp>
#include <alibabacloud/models/DescribeChatMessageResponse.hpp>
#include <alibabacloud/models/DescribeEapDeviceResourceAllocationRequest.hpp>
#include <alibabacloud/models/DescribeEapDeviceResourceAllocationResponseBody.hpp>
#include <alibabacloud/models/DescribeEapDeviceResourceAllocationResponse.hpp>
#include <alibabacloud/models/DescribeEmbodiedAIPlatformsRequest.hpp>
#include <alibabacloud/models/DescribeEmbodiedAIPlatformsResponseBody.hpp>
#include <alibabacloud/models/DescribeEmbodiedAIPlatformsResponse.hpp>
#include <alibabacloud/models/GetEmbodiedAIPlatformResourceUsageInfoRequest.hpp>
#include <alibabacloud/models/GetEmbodiedAIPlatformResourceUsageInfoResponseBody.hpp>
#include <alibabacloud/models/GetEmbodiedAIPlatformResourceUsageInfoResponse.hpp>
#include <alibabacloud/models/LockEmbodiedAIPlatformRequest.hpp>
#include <alibabacloud/models/LockEmbodiedAIPlatformResponseBody.hpp>
#include <alibabacloud/models/LockEmbodiedAIPlatformResponse.hpp>
#include <alibabacloud/models/ModifyAgentPlatformRequest.hpp>
#include <alibabacloud/models/ModifyAgentPlatformShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAgentPlatformResponseBody.hpp>
#include <alibabacloud/models/ModifyAgentPlatformResponse.hpp>
#include <alibabacloud/models/ModifyEmbodiedAIPlatformRequest.hpp>
#include <alibabacloud/models/ModifyEmbodiedAIPlatformShrinkRequest.hpp>
#include <alibabacloud/models/ModifyEmbodiedAIPlatformResponseBody.hpp>
#include <alibabacloud/models/ModifyEmbodiedAIPlatformResponse.hpp>
#include <alibabacloud/models/ResetEmbodiedAIPlatformPasswordRequest.hpp>
#include <alibabacloud/models/ResetEmbodiedAIPlatformPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetEmbodiedAIPlatformPasswordResponse.hpp>
#include <alibabacloud/models/UnlockEmbodiedAIPlatformRequest.hpp>
#include <alibabacloud/models/UnlockEmbodiedAIPlatformResponseBody.hpp>
#include <alibabacloud/models/UnlockEmbodiedAIPlatformResponse.hpp>

#endif
