// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLOUDFW20171207MODEL_HPP_
#define ALIBABACLOUD_CLOUDFW20171207MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddAclBackupDataRequest.hpp>
#include <alibabacloud/models/AddAclBackupDataResponseBody.hpp>
#include <alibabacloud/models/AddAclBackupDataResponse.hpp>
#include <alibabacloud/models/AddAddressBookRequest.hpp>
#include <alibabacloud/models/AddAddressBookResponseBody.hpp>
#include <alibabacloud/models/AddAddressBookResponse.hpp>
#include <alibabacloud/models/AddControlPolicyRequest.hpp>
#include <alibabacloud/models/AddControlPolicyResponseBody.hpp>
#include <alibabacloud/models/AddControlPolicyResponse.hpp>
#include <alibabacloud/models/AddDnsFirewallPolicyRequest.hpp>
#include <alibabacloud/models/AddDnsFirewallPolicyResponseBody.hpp>
#include <alibabacloud/models/AddDnsFirewallPolicyResponse.hpp>
#include <alibabacloud/models/AddDomainResolveRealtimeTaskRequest.hpp>
#include <alibabacloud/models/AddDomainResolveRealtimeTaskResponseBody.hpp>
#include <alibabacloud/models/AddDomainResolveRealtimeTaskResponse.hpp>
#include <alibabacloud/models/AddInstanceMembersRequest.hpp>
#include <alibabacloud/models/AddInstanceMembersResponseBody.hpp>
#include <alibabacloud/models/AddInstanceMembersResponse.hpp>
#include <alibabacloud/models/AddPrivateDnsDomainNameRequest.hpp>
#include <alibabacloud/models/AddPrivateDnsDomainNameResponseBody.hpp>
#include <alibabacloud/models/AddPrivateDnsDomainNameResponse.hpp>
#include <alibabacloud/models/BatchCopyVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/BatchCopyVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/BatchCopyVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/BatchDeleteVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/BatchDeleteVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/ClearLogStoreStorageRequest.hpp>
#include <alibabacloud/models/ClearLogStoreStorageResponseBody.hpp>
#include <alibabacloud/models/ClearLogStoreStorageResponse.hpp>
#include <alibabacloud/models/CreateAckClusterConnectorRequest.hpp>
#include <alibabacloud/models/CreateAckClusterConnectorResponseBody.hpp>
#include <alibabacloud/models/CreateAckClusterConnectorResponse.hpp>
#include <alibabacloud/models/CreateAclCheckRequest.hpp>
#include <alibabacloud/models/CreateAclCheckResponseBody.hpp>
#include <alibabacloud/models/CreateAclCheckResponse.hpp>
#include <alibabacloud/models/CreateDownloadTaskRequest.hpp>
#include <alibabacloud/models/CreateDownloadTaskResponseBody.hpp>
#include <alibabacloud/models/CreateDownloadTaskResponse.hpp>
#include <alibabacloud/models/CreateInstanceSyncTaskRequest.hpp>
#include <alibabacloud/models/CreateInstanceSyncTaskResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceSyncTaskResponse.hpp>
#include <alibabacloud/models/CreateIpsPrivateAssocRequest.hpp>
#include <alibabacloud/models/CreateIpsPrivateAssocResponseBody.hpp>
#include <alibabacloud/models/CreateIpsPrivateAssocResponse.hpp>
#include <alibabacloud/models/CreateNatFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/CreateNatFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateNatFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/CreateNatFirewallPreCheckRequest.hpp>
#include <alibabacloud/models/CreateNatFirewallPreCheckResponseBody.hpp>
#include <alibabacloud/models/CreateNatFirewallPreCheckResponse.hpp>
#include <alibabacloud/models/CreateNatFirewallSyncTaskRequest.hpp>
#include <alibabacloud/models/CreateNatFirewallSyncTaskResponseBody.hpp>
#include <alibabacloud/models/CreateNatFirewallSyncTaskResponse.hpp>
#include <alibabacloud/models/CreatePrivateDnsEndpointRequest.hpp>
#include <alibabacloud/models/CreatePrivateDnsEndpointResponseBody.hpp>
#include <alibabacloud/models/CreatePrivateDnsEndpointResponse.hpp>
#include <alibabacloud/models/CreateSecurityProxyRequest.hpp>
#include <alibabacloud/models/CreateSecurityProxyResponseBody.hpp>
#include <alibabacloud/models/CreateSecurityProxyResponse.hpp>
#include <alibabacloud/models/CreateSlsLogDispatchRequest.hpp>
#include <alibabacloud/models/CreateSlsLogDispatchResponseBody.hpp>
#include <alibabacloud/models/CreateSlsLogDispatchResponse.hpp>
#include <alibabacloud/models/CreateTrFirewallV2Request.hpp>
#include <alibabacloud/models/CreateTrFirewallV2ResponseBody.hpp>
#include <alibabacloud/models/CreateTrFirewallV2Response.hpp>
#include <alibabacloud/models/CreateTrFirewallV2RoutePolicyRequest.hpp>
#include <alibabacloud/models/CreateTrFirewallV2RoutePolicyShrinkRequest.hpp>
#include <alibabacloud/models/CreateTrFirewallV2RoutePolicyResponseBody.hpp>
#include <alibabacloud/models/CreateTrFirewallV2RoutePolicyResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenConfigureRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenConfigureResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenConfigureResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenManualConfigureRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenManualConfigureResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallCenManualConfigureResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallConfigureRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallConfigureResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallConfigureResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallPrecheckRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallPrecheckResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallPrecheckResponse.hpp>
#include <alibabacloud/models/CreateVpcFirewallTaskRequest.hpp>
#include <alibabacloud/models/CreateVpcFirewallTaskResponseBody.hpp>
#include <alibabacloud/models/CreateVpcFirewallTaskResponse.hpp>
#include <alibabacloud/models/DeleteAckClusterConnectorRequest.hpp>
#include <alibabacloud/models/DeleteAckClusterConnectorResponseBody.hpp>
#include <alibabacloud/models/DeleteAckClusterConnectorResponse.hpp>
#include <alibabacloud/models/DeleteAclBackupDataRequest.hpp>
#include <alibabacloud/models/DeleteAclBackupDataResponseBody.hpp>
#include <alibabacloud/models/DeleteAclBackupDataResponse.hpp>
#include <alibabacloud/models/DeleteAddressBookRequest.hpp>
#include <alibabacloud/models/DeleteAddressBookResponseBody.hpp>
#include <alibabacloud/models/DeleteAddressBookResponse.hpp>
#include <alibabacloud/models/DeleteControlPolicyRequest.hpp>
#include <alibabacloud/models/DeleteControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteControlPolicyResponse.hpp>
#include <alibabacloud/models/DeleteControlPolicyTemplateRequest.hpp>
#include <alibabacloud/models/DeleteControlPolicyTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteControlPolicyTemplateResponse.hpp>
#include <alibabacloud/models/DeleteDnsFirewallPolicyRequest.hpp>
#include <alibabacloud/models/DeleteDnsFirewallPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteDnsFirewallPolicyResponse.hpp>
#include <alibabacloud/models/DeleteDownloadTaskRequest.hpp>
#include <alibabacloud/models/DeleteDownloadTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteDownloadTaskResponse.hpp>
#include <alibabacloud/models/DeleteFirewallV2RoutePoliciesRequest.hpp>
#include <alibabacloud/models/DeleteFirewallV2RoutePoliciesResponseBody.hpp>
#include <alibabacloud/models/DeleteFirewallV2RoutePoliciesResponse.hpp>
#include <alibabacloud/models/DeleteInstanceMembersRequest.hpp>
#include <alibabacloud/models/DeleteInstanceMembersResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceMembersResponse.hpp>
#include <alibabacloud/models/DeleteIpsPrivateAssocRequest.hpp>
#include <alibabacloud/models/DeleteIpsPrivateAssocResponseBody.hpp>
#include <alibabacloud/models/DeleteIpsPrivateAssocResponse.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyBatchRequest.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyBatchResponseBody.hpp>
#include <alibabacloud/models/DeleteNatFirewallControlPolicyBatchResponse.hpp>
#include <alibabacloud/models/DeletePrivateDnsAllDomainNameRequest.hpp>
#include <alibabacloud/models/DeletePrivateDnsAllDomainNameResponseBody.hpp>
#include <alibabacloud/models/DeletePrivateDnsAllDomainNameResponse.hpp>
#include <alibabacloud/models/DeletePrivateDnsDomainNameRequest.hpp>
#include <alibabacloud/models/DeletePrivateDnsDomainNameResponseBody.hpp>
#include <alibabacloud/models/DeletePrivateDnsDomainNameResponse.hpp>
#include <alibabacloud/models/DeletePrivateDnsEndpointRequest.hpp>
#include <alibabacloud/models/DeletePrivateDnsEndpointResponseBody.hpp>
#include <alibabacloud/models/DeletePrivateDnsEndpointResponse.hpp>
#include <alibabacloud/models/DeleteSecurityProxyRequest.hpp>
#include <alibabacloud/models/DeleteSecurityProxyResponseBody.hpp>
#include <alibabacloud/models/DeleteSecurityProxyResponse.hpp>
#include <alibabacloud/models/DeleteTrFirewallV2Request.hpp>
#include <alibabacloud/models/DeleteTrFirewallV2ResponseBody.hpp>
#include <alibabacloud/models/DeleteTrFirewallV2Response.hpp>
#include <alibabacloud/models/DeleteVpcFirewallCenConfigureRequest.hpp>
#include <alibabacloud/models/DeleteVpcFirewallCenConfigureResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcFirewallCenConfigureResponse.hpp>
#include <alibabacloud/models/DeleteVpcFirewallConfigureRequest.hpp>
#include <alibabacloud/models/DeleteVpcFirewallConfigureResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcFirewallConfigureResponse.hpp>
#include <alibabacloud/models/DeleteVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/DeleteVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/DescribeACLProtectTrendRequest.hpp>
#include <alibabacloud/models/DescribeACLProtectTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeACLProtectTrendResponse.hpp>
#include <alibabacloud/models/DescribeAITrafficAnalysisStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAITrafficAnalysisStatusResponse.hpp>
#include <alibabacloud/models/DescribeAccessInstanceRegionListRequest.hpp>
#include <alibabacloud/models/DescribeAccessInstanceRegionListResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessInstanceRegionListResponse.hpp>
#include <alibabacloud/models/DescribeAccessInstanceTaskRequest.hpp>
#include <alibabacloud/models/DescribeAccessInstanceTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessInstanceTaskResponse.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVSwitchListRequest.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVSwitchListResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVSwitchListResponse.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVpcListRequest.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVpcListResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessInstanceVpcListResponse.hpp>
#include <alibabacloud/models/DescribeAccessInstanceZoneListRequest.hpp>
#include <alibabacloud/models/DescribeAccessInstanceZoneListResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessInstanceZoneListResponse.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorRequest.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorResponseBody.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorResponse.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorsRequest.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorsResponseBody.hpp>
#include <alibabacloud/models/DescribeAckClusterConnectorsResponse.hpp>
#include <alibabacloud/models/DescribeAckClusterNamespacesRequest.hpp>
#include <alibabacloud/models/DescribeAckClusterNamespacesResponseBody.hpp>
#include <alibabacloud/models/DescribeAckClusterNamespacesResponse.hpp>
#include <alibabacloud/models/DescribeAckClusterPodLabelsRequest.hpp>
#include <alibabacloud/models/DescribeAckClusterPodLabelsResponseBody.hpp>
#include <alibabacloud/models/DescribeAckClusterPodLabelsResponse.hpp>
#include <alibabacloud/models/DescribeAckClustersRequest.hpp>
#include <alibabacloud/models/DescribeAckClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeAckClustersResponse.hpp>
#include <alibabacloud/models/DescribeAclAppsRequest.hpp>
#include <alibabacloud/models/DescribeAclAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAclAppsResponse.hpp>
#include <alibabacloud/models/DescribeAclBackupListRequest.hpp>
#include <alibabacloud/models/DescribeAclBackupListResponseBody.hpp>
#include <alibabacloud/models/DescribeAclBackupListResponse.hpp>
#include <alibabacloud/models/DescribeAclCheckRequest.hpp>
#include <alibabacloud/models/DescribeAclCheckResponseBody.hpp>
#include <alibabacloud/models/DescribeAclCheckResponse.hpp>
#include <alibabacloud/models/DescribeAclCheckQuotaRequest.hpp>
#include <alibabacloud/models/DescribeAclCheckQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeAclCheckQuotaResponse.hpp>
#include <alibabacloud/models/DescribeAclChecksRequest.hpp>
#include <alibabacloud/models/DescribeAclChecksResponseBody.hpp>
#include <alibabacloud/models/DescribeAclChecksResponse.hpp>
#include <alibabacloud/models/DescribeAclRuleCountRequest.hpp>
#include <alibabacloud/models/DescribeAclRuleCountResponseBody.hpp>
#include <alibabacloud/models/DescribeAclRuleCountResponse.hpp>
#include <alibabacloud/models/DescribeAclWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeAclWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeAclWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeAddressBookRequest.hpp>
#include <alibabacloud/models/DescribeAddressBookResponseBody.hpp>
#include <alibabacloud/models/DescribeAddressBookResponse.hpp>
#include <alibabacloud/models/DescribeAssetListRequest.hpp>
#include <alibabacloud/models/DescribeAssetListResponseBody.hpp>
#include <alibabacloud/models/DescribeAssetListResponse.hpp>
#include <alibabacloud/models/DescribeAssetRiskListRequest.hpp>
#include <alibabacloud/models/DescribeAssetRiskListResponseBody.hpp>
#include <alibabacloud/models/DescribeAssetRiskListResponse.hpp>
#include <alibabacloud/models/DescribeAssetStatisticRequest.hpp>
#include <alibabacloud/models/DescribeAssetStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeAssetStatisticResponse.hpp>
#include <alibabacloud/models/DescribeAttackAppCategoryRequest.hpp>
#include <alibabacloud/models/DescribeAttackAppCategoryResponseBody.hpp>
#include <alibabacloud/models/DescribeAttackAppCategoryResponse.hpp>
#include <alibabacloud/models/DescribeBatchSlsDispatchStatusRequest.hpp>
#include <alibabacloud/models/DescribeBatchSlsDispatchStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeBatchSlsDispatchStatusResponse.hpp>
#include <alibabacloud/models/DescribeCfwRiskLevelSummaryRequest.hpp>
#include <alibabacloud/models/DescribeCfwRiskLevelSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeCfwRiskLevelSummaryResponse.hpp>
#include <alibabacloud/models/DescribeClearAuthInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeClearAuthInfoResponse.hpp>
#include <alibabacloud/models/DescribeConfiguredDestinationIPRequest.hpp>
#include <alibabacloud/models/DescribeConfiguredDestinationIPResponseBody.hpp>
#include <alibabacloud/models/DescribeConfiguredDestinationIPResponse.hpp>
#include <alibabacloud/models/DescribeConfiguredDomainNamesRequest.hpp>
#include <alibabacloud/models/DescribeConfiguredDomainNamesResponseBody.hpp>
#include <alibabacloud/models/DescribeConfiguredDomainNamesResponse.hpp>
#include <alibabacloud/models/DescribeControlPolicyRequest.hpp>
#include <alibabacloud/models/DescribeControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeControlPolicyResponse.hpp>
#include <alibabacloud/models/DescribeControlPolicyDomainResolveRequest.hpp>
#include <alibabacloud/models/DescribeControlPolicyDomainResolveResponseBody.hpp>
#include <alibabacloud/models/DescribeControlPolicyDomainResolveResponse.hpp>
#include <alibabacloud/models/DescribeCreatedNatFirewallRequest.hpp>
#include <alibabacloud/models/DescribeCreatedNatFirewallResponseBody.hpp>
#include <alibabacloud/models/DescribeCreatedNatFirewallResponse.hpp>
#include <alibabacloud/models/DescribeCtrlInstanceMemberAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeCtrlInstanceMemberAccountsResponse.hpp>
#include <alibabacloud/models/DescribeDefaultIPSConfigRequest.hpp>
#include <alibabacloud/models/DescribeDefaultIPSConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDefaultIPSConfigResponse.hpp>
#include <alibabacloud/models/DescribeDnsFirewallPolicyRequest.hpp>
#include <alibabacloud/models/DescribeDnsFirewallPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsFirewallPolicyResponse.hpp>
#include <alibabacloud/models/DescribeDomainResolveRequest.hpp>
#include <alibabacloud/models/DescribeDomainResolveResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainResolveResponse.hpp>
#include <alibabacloud/models/DescribeDownloadTaskRequest.hpp>
#include <alibabacloud/models/DescribeDownloadTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeDownloadTaskResponse.hpp>
#include <alibabacloud/models/DescribeDownloadTaskTypeRequest.hpp>
#include <alibabacloud/models/DescribeDownloadTaskTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeDownloadTaskTypeResponse.hpp>
#include <alibabacloud/models/DescribeFirewallDropStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallDropStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeFirewallTaskRequest.hpp>
#include <alibabacloud/models/DescribeFirewallTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallTaskResponse.hpp>
#include <alibabacloud/models/DescribeFirewallVSwitchRequest.hpp>
#include <alibabacloud/models/DescribeFirewallVSwitchResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallVSwitchResponse.hpp>
#include <alibabacloud/models/DescribeFirewallVswitchResourcesRequest.hpp>
#include <alibabacloud/models/DescribeFirewallVswitchResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallVswitchResourcesResponse.hpp>
#include <alibabacloud/models/DescribeInstanceMembersRequest.hpp>
#include <alibabacloud/models/DescribeInstanceMembersResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceMembersResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRdAccountsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceRdAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceRdAccountsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRiskLevelsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceRiskLevelsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceRiskLevelsResponse.hpp>
#include <alibabacloud/models/DescribeInternetDropTrafficTrendRequest.hpp>
#include <alibabacloud/models/DescribeInternetDropTrafficTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetDropTrafficTrendResponse.hpp>
#include <alibabacloud/models/DescribeInternetOpenDetailRequest.hpp>
#include <alibabacloud/models/DescribeInternetOpenDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetOpenDetailResponse.hpp>
#include <alibabacloud/models/DescribeInternetOpenIpRequest.hpp>
#include <alibabacloud/models/DescribeInternetOpenIpResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetOpenIpResponse.hpp>
#include <alibabacloud/models/DescribeInternetOpenPortRequest.hpp>
#include <alibabacloud/models/DescribeInternetOpenPortResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetOpenPortResponse.hpp>
#include <alibabacloud/models/DescribeInternetOpenServiceRequest.hpp>
#include <alibabacloud/models/DescribeInternetOpenServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetOpenServiceResponse.hpp>
#include <alibabacloud/models/DescribeInternetOpenStatisticRequest.hpp>
#include <alibabacloud/models/DescribeInternetOpenStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetOpenStatisticResponse.hpp>
#include <alibabacloud/models/DescribeInternetServiceNameListRequest.hpp>
#include <alibabacloud/models/DescribeInternetServiceNameListResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetServiceNameListResponse.hpp>
#include <alibabacloud/models/DescribeInternetSlbRequest.hpp>
#include <alibabacloud/models/DescribeInternetSlbResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetSlbResponse.hpp>
#include <alibabacloud/models/DescribeInternetTimeTopRequest.hpp>
#include <alibabacloud/models/DescribeInternetTimeTopResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetTimeTopResponse.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTopRequest.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTopResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTopResponse.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTrendRequest.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetTrafficTrendResponse.hpp>
#include <alibabacloud/models/DescribeInvadeEcsTrendRequest.hpp>
#include <alibabacloud/models/DescribeInvadeEcsTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeInvadeEcsTrendResponse.hpp>
#include <alibabacloud/models/DescribeInvadeEventDetailRequest.hpp>
#include <alibabacloud/models/DescribeInvadeEventDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeInvadeEventDetailResponse.hpp>
#include <alibabacloud/models/DescribeInvadeEventListRequest.hpp>
#include <alibabacloud/models/DescribeInvadeEventListResponseBody.hpp>
#include <alibabacloud/models/DescribeInvadeEventListResponse.hpp>
#include <alibabacloud/models/DescribeInvadeEventNameListRequest.hpp>
#include <alibabacloud/models/DescribeInvadeEventNameListResponseBody.hpp>
#include <alibabacloud/models/DescribeInvadeEventNameListResponse.hpp>
#include <alibabacloud/models/DescribeInvadeEventStatisticRequest.hpp>
#include <alibabacloud/models/DescribeInvadeEventStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeInvadeEventStatisticResponse.hpp>
#include <alibabacloud/models/DescribeIpsPrivateAssocRequest.hpp>
#include <alibabacloud/models/DescribeIpsPrivateAssocResponseBody.hpp>
#include <alibabacloud/models/DescribeIpsPrivateAssocResponse.hpp>
#include <alibabacloud/models/DescribeIspInfoRequest.hpp>
#include <alibabacloud/models/DescribeIspInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeIspInfoResponse.hpp>
#include <alibabacloud/models/DescribeLocationInfoRequest.hpp>
#include <alibabacloud/models/DescribeLocationInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeLocationInfoResponse.hpp>
#include <alibabacloud/models/DescribeLogStoreInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeLogStoreInfoResponse.hpp>
#include <alibabacloud/models/DescribeMemberInfoRequest.hpp>
#include <alibabacloud/models/DescribeMemberInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeMemberInfoResponse.hpp>
#include <alibabacloud/models/DescribeNatAclPageStatusRequest.hpp>
#include <alibabacloud/models/DescribeNatAclPageStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeNatAclPageStatusResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallAclGroupListRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallAclGroupListResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallAclGroupListResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallDropTrafficTrendRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallDropTrafficTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallDropTrafficTrendResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallListRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallListResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallListResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallPolicyPriorUsedRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallPolicyPriorUsedResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallPolicyPriorUsedResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallPrecheckDetailRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallPrecheckDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallPrecheckDetailResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallQuotaRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallQuotaResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallTimeTopRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallTimeTopResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallTimeTopResponse.hpp>
#include <alibabacloud/models/DescribeNatFirewallTrafficTrendRequest.hpp>
#include <alibabacloud/models/DescribeNatFirewallTrafficTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeNatFirewallTrafficTrendResponse.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceListRequest.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceListResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceListResponse.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceRelationListRequest.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceRelationListResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkInstanceRelationListResponse.hpp>
#include <alibabacloud/models/DescribeNetworkTrafficTopRatioRequest.hpp>
#include <alibabacloud/models/DescribeNetworkTrafficTopRatioResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkTrafficTopRatioResponse.hpp>
#include <alibabacloud/models/DescribeOpenIpAccessSrcStatRequest.hpp>
#include <alibabacloud/models/DescribeOpenIpAccessSrcStatResponseBody.hpp>
#include <alibabacloud/models/DescribeOpenIpAccessSrcStatResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingAssetListRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingAssetListResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingAssetListResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationCategoryRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationCategoryResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationCategoryResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPDetailRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDestinationIPDetailResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskDomainAndIpCountRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskDomainAndIpCountResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskDomainAndIpCountResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskTrendRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingRiskTrendResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingStatisticRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingStatisticResponse.hpp>
#include <alibabacloud/models/DescribeOutgoingTagRequest.hpp>
#include <alibabacloud/models/DescribeOutgoingTagResponseBody.hpp>
#include <alibabacloud/models/DescribeOutgoingTagResponse.hpp>
#include <alibabacloud/models/DescribePageDocumentsRequest.hpp>
#include <alibabacloud/models/DescribePageDocumentsResponseBody.hpp>
#include <alibabacloud/models/DescribePageDocumentsResponse.hpp>
#include <alibabacloud/models/DescribePolicyAdvancedConfigRequest.hpp>
#include <alibabacloud/models/DescribePolicyAdvancedConfigResponseBody.hpp>
#include <alibabacloud/models/DescribePolicyAdvancedConfigResponse.hpp>
#include <alibabacloud/models/DescribePolicyPriorUsedRequest.hpp>
#include <alibabacloud/models/DescribePolicyPriorUsedResponseBody.hpp>
#include <alibabacloud/models/DescribePolicyPriorUsedResponse.hpp>
#include <alibabacloud/models/DescribePostpayEnabledProtectionRequest.hpp>
#include <alibabacloud/models/DescribePostpayEnabledProtectionResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayEnabledProtectionResponse.hpp>
#include <alibabacloud/models/DescribePostpayTrafficDetailRequest.hpp>
#include <alibabacloud/models/DescribePostpayTrafficDetailResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayTrafficDetailResponse.hpp>
#include <alibabacloud/models/DescribePostpayTrafficTotalRequest.hpp>
#include <alibabacloud/models/DescribePostpayTrafficTotalResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayTrafficTotalResponse.hpp>
#include <alibabacloud/models/DescribePostpayUserInternetStatusRequest.hpp>
#include <alibabacloud/models/DescribePostpayUserInternetStatusResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayUserInternetStatusResponse.hpp>
#include <alibabacloud/models/DescribePostpayUserNatStatusRequest.hpp>
#include <alibabacloud/models/DescribePostpayUserNatStatusResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayUserNatStatusResponse.hpp>
#include <alibabacloud/models/DescribePostpayUserVpcStatusRequest.hpp>
#include <alibabacloud/models/DescribePostpayUserVpcStatusResponseBody.hpp>
#include <alibabacloud/models/DescribePostpayUserVpcStatusResponse.hpp>
#include <alibabacloud/models/DescribePrefixListsRequest.hpp>
#include <alibabacloud/models/DescribePrefixListsResponseBody.hpp>
#include <alibabacloud/models/DescribePrefixListsResponse.hpp>
#include <alibabacloud/models/DescribePrivateDnsDomainNameListRequest.hpp>
#include <alibabacloud/models/DescribePrivateDnsDomainNameListResponseBody.hpp>
#include <alibabacloud/models/DescribePrivateDnsDomainNameListResponse.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointDetailRequest.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointDetailResponseBody.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointDetailResponse.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointListRequest.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointListResponseBody.hpp>
#include <alibabacloud/models/DescribePrivateDnsEndpointListResponse.hpp>
#include <alibabacloud/models/DescribePrivateDnsStatisticsRequest.hpp>
#include <alibabacloud/models/DescribePrivateDnsStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribePrivateDnsStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeRegionInfoRequest.hpp>
#include <alibabacloud/models/DescribeRegionInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionInfoResponse.hpp>
#include <alibabacloud/models/DescribeRegionResourceTypeAutoEnableRequest.hpp>
#include <alibabacloud/models/DescribeRegionResourceTypeAutoEnableResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionResourceTypeAutoEnableResponse.hpp>
#include <alibabacloud/models/DescribeResourceTypeAutoEnableRequest.hpp>
#include <alibabacloud/models/DescribeResourceTypeAutoEnableResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceTypeAutoEnableResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventGroupRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventGroupResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventPayloadRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventPayloadResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventPayloadResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventStatisticRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventStatisticResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAppRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAppResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAppResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAssetRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAssetResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackAssetResponse.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackTypeRequest.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskEventTopAttackTypeResponse.hpp>
#include <alibabacloud/models/DescribeRiskSecurityGroupDetailRequest.hpp>
#include <alibabacloud/models/DescribeRiskSecurityGroupDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeRiskSecurityGroupDetailResponse.hpp>
#include <alibabacloud/models/DescribeSdlEventDetailRequest.hpp>
#include <alibabacloud/models/DescribeSdlEventDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeSdlEventDetailResponse.hpp>
#include <alibabacloud/models/DescribeSdlEventListRequest.hpp>
#include <alibabacloud/models/DescribeSdlEventListResponseBody.hpp>
#include <alibabacloud/models/DescribeSdlEventListResponse.hpp>
#include <alibabacloud/models/DescribeSdlEventSdListRequest.hpp>
#include <alibabacloud/models/DescribeSdlEventSdListResponseBody.hpp>
#include <alibabacloud/models/DescribeSdlEventSdListResponse.hpp>
#include <alibabacloud/models/DescribeSdlEventStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSdlEventStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSdlEventStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSdlStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSdlStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSdlStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSecurityModeRequest.hpp>
#include <alibabacloud/models/DescribeSecurityModeResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityModeResponse.hpp>
#include <alibabacloud/models/DescribeSecurityProxyRequest.hpp>
#include <alibabacloud/models/DescribeSecurityProxyResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityProxyResponse.hpp>
#include <alibabacloud/models/DescribeSecurityProxyResourcesRequest.hpp>
#include <alibabacloud/models/DescribeSecurityProxyResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityProxyResourcesResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveSwitchRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveSwitchResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveSwitchResponse.hpp>
#include <alibabacloud/models/DescribeSignatureLibVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeSignatureLibVersionResponse.hpp>
#include <alibabacloud/models/DescribeSlrGrantRequest.hpp>
#include <alibabacloud/models/DescribeSlrGrantResponseBody.hpp>
#include <alibabacloud/models/DescribeSlrGrantResponse.hpp>
#include <alibabacloud/models/DescribeSlsAnalyzeOpenStatusRequest.hpp>
#include <alibabacloud/models/DescribeSlsAnalyzeOpenStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeSlsAnalyzeOpenStatusResponse.hpp>
#include <alibabacloud/models/DescribeThreatIntelligenceSwitchResponseBody.hpp>
#include <alibabacloud/models/DescribeThreatIntelligenceSwitchResponse.hpp>
#include <alibabacloud/models/DescribeTrFirewallPolicyBackUpAssociationListRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallPolicyBackUpAssociationListShrinkRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallPolicyBackUpAssociationListResponseBody.hpp>
#include <alibabacloud/models/DescribeTrFirewallPolicyBackUpAssociationListResponse.hpp>
#include <alibabacloud/models/DescribeTrFirewallV2RoutePolicyListRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallV2RoutePolicyListResponseBody.hpp>
#include <alibabacloud/models/DescribeTrFirewallV2RoutePolicyListResponse.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2DetailRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2DetailResponseBody.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2DetailResponse.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2ListRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2ListResponseBody.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2ListResponse.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2RouteListRequest.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2RouteListResponseBody.hpp>
#include <alibabacloud/models/DescribeTrFirewallsV2RouteListResponse.hpp>
#include <alibabacloud/models/DescribeTrafficLogRequest.hpp>
#include <alibabacloud/models/DescribeTrafficLogResponseBody.hpp>
#include <alibabacloud/models/DescribeTrafficLogResponse.hpp>
#include <alibabacloud/models/DescribeTransitRouterResourcesListRequest.hpp>
#include <alibabacloud/models/DescribeTransitRouterResourcesListResponseBody.hpp>
#include <alibabacloud/models/DescribeTransitRouterResourcesListResponse.hpp>
#include <alibabacloud/models/DescribeUnprotectedPortTrendRequest.hpp>
#include <alibabacloud/models/DescribeUnprotectedPortTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeUnprotectedPortTrendResponse.hpp>
#include <alibabacloud/models/DescribeUnprotectedVulnTrendRequest.hpp>
#include <alibabacloud/models/DescribeUnprotectedVulnTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeUnprotectedVulnTrendResponse.hpp>
#include <alibabacloud/models/DescribeUserAlarmConfigRequest.hpp>
#include <alibabacloud/models/DescribeUserAlarmConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAlarmConfigResponse.hpp>
#include <alibabacloud/models/DescribeUserAssetIPTrafficInfoRequest.hpp>
#include <alibabacloud/models/DescribeUserAssetIPTrafficInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAssetIPTrafficInfoResponse.hpp>
#include <alibabacloud/models/DescribeUserBuyVersionRequest.hpp>
#include <alibabacloud/models/DescribeUserBuyVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeUserBuyVersionResponse.hpp>
#include <alibabacloud/models/DescribeUserIPSWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeUserIPSWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeUserIPSWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeVfwIPSConfigListRequest.hpp>
#include <alibabacloud/models/DescribeVfwIPSConfigListResponseBody.hpp>
#include <alibabacloud/models/DescribeVfwIPSConfigListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAccessDetailRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAccessDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAccessDetailResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAclGroupListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAclGroupListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAclGroupListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetRegionListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetRegionListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallAssetRegionListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenDetailRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenDetailResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenSummaryListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenSummaryListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallCenSummaryListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDefaultIPSConfigRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDefaultIPSConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDefaultIPSConfigResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDetailRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDetailResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainRelationListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainRelationListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDomainRelationListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDropTrafficTrendRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDropTrafficTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallDropTrafficTrendResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallIPSWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallIPSWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallIPSWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallManualVSwitchListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallManualVSwitchListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallManualVSwitchListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPolicyPriorUsedRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPolicyPriorUsedResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPolicyPriorUsedResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPrecheckDetailRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPrecheckDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallPrecheckDetailResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallSummaryInfoRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallSummaryInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallSummaryInfoResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallTrafficAssetListRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallTrafficAssetListResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallTrafficAssetListResponse.hpp>
#include <alibabacloud/models/DescribeVpcFirewallZoneRequest.hpp>
#include <alibabacloud/models/DescribeVpcFirewallZoneResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcFirewallZoneResponse.hpp>
#include <alibabacloud/models/DescribeVpcListLiteRequest.hpp>
#include <alibabacloud/models/DescribeVpcListLiteResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcListLiteResponse.hpp>
#include <alibabacloud/models/DescribeVpcZoneRequest.hpp>
#include <alibabacloud/models/DescribeVpcZoneResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcZoneResponse.hpp>
#include <alibabacloud/models/DescribeVulnerabilityProtectedListRequest.hpp>
#include <alibabacloud/models/DescribeVulnerabilityProtectedListResponseBody.hpp>
#include <alibabacloud/models/DescribeVulnerabilityProtectedListResponse.hpp>
#include <alibabacloud/models/DisableSdlProtectedAssetRequest.hpp>
#include <alibabacloud/models/DisableSdlProtectedAssetResponseBody.hpp>
#include <alibabacloud/models/DisableSdlProtectedAssetResponse.hpp>
#include <alibabacloud/models/EnableSdlProtectedAssetRequest.hpp>
#include <alibabacloud/models/EnableSdlProtectedAssetResponseBody.hpp>
#include <alibabacloud/models/EnableSdlProtectedAssetResponse.hpp>
#include <alibabacloud/models/GetTlsInspectCertificateDownloadUrlRequest.hpp>
#include <alibabacloud/models/GetTlsInspectCertificateDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/GetTlsInspectCertificateDownloadUrlResponse.hpp>
#include <alibabacloud/models/ListTlsInspectCACertificatesRequest.hpp>
#include <alibabacloud/models/ListTlsInspectCACertificatesResponseBody.hpp>
#include <alibabacloud/models/ListTlsInspectCACertificatesResponse.hpp>
#include <alibabacloud/models/ModifyAddressBookRequest.hpp>
#include <alibabacloud/models/ModifyAddressBookResponseBody.hpp>
#include <alibabacloud/models/ModifyAddressBookResponse.hpp>
#include <alibabacloud/models/ModifyCfwInstanceRequest.hpp>
#include <alibabacloud/models/ModifyCfwInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyCfwInstanceResponse.hpp>
#include <alibabacloud/models/ModifyControlPolicyRequest.hpp>
#include <alibabacloud/models/ModifyControlPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyControlPolicyResponse.hpp>
#include <alibabacloud/models/ModifyControlPolicyPositionRequest.hpp>
#include <alibabacloud/models/ModifyControlPolicyPositionResponseBody.hpp>
#include <alibabacloud/models/ModifyControlPolicyPositionResponse.hpp>
#include <alibabacloud/models/ModifyControlPolicyPriorityRequest.hpp>
#include <alibabacloud/models/ModifyControlPolicyPriorityResponseBody.hpp>
#include <alibabacloud/models/ModifyControlPolicyPriorityResponse.hpp>
#include <alibabacloud/models/ModifyDefaultIPSConfigRequest.hpp>
#include <alibabacloud/models/ModifyDefaultIPSConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDefaultIPSConfigResponse.hpp>
#include <alibabacloud/models/ModifyDnsFirewallPolicyRequest.hpp>
#include <alibabacloud/models/ModifyDnsFirewallPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyDnsFirewallPolicyResponse.hpp>
#include <alibabacloud/models/ModifyFirewallV2RoutePolicySwitchRequest.hpp>
#include <alibabacloud/models/ModifyFirewallV2RoutePolicySwitchResponseBody.hpp>
#include <alibabacloud/models/ModifyFirewallV2RoutePolicySwitchResponse.hpp>
#include <alibabacloud/models/ModifyInstanceMemberAttributesRequest.hpp>
#include <alibabacloud/models/ModifyInstanceMemberAttributesResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceMemberAttributesResponse.hpp>
#include <alibabacloud/models/ModifyIpsRulesRequest.hpp>
#include <alibabacloud/models/ModifyIpsRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyIpsRulesResponse.hpp>
#include <alibabacloud/models/ModifyIpsRulesToDefaultRequest.hpp>
#include <alibabacloud/models/ModifyIpsRulesToDefaultResponseBody.hpp>
#include <alibabacloud/models/ModifyIpsRulesToDefaultResponse.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyPositionRequest.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyPositionResponseBody.hpp>
#include <alibabacloud/models/ModifyNatFirewallControlPolicyPositionResponse.hpp>
#include <alibabacloud/models/ModifyObjectGroupOperationRequest.hpp>
#include <alibabacloud/models/ModifyObjectGroupOperationResponseBody.hpp>
#include <alibabacloud/models/ModifyObjectGroupOperationResponse.hpp>
#include <alibabacloud/models/ModifyPolicyAdvancedConfigRequest.hpp>
#include <alibabacloud/models/ModifyPolicyAdvancedConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyAdvancedConfigResponse.hpp>
#include <alibabacloud/models/ModifyPrivateDnsEndpointRequest.hpp>
#include <alibabacloud/models/ModifyPrivateDnsEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyPrivateDnsEndpointResponse.hpp>
#include <alibabacloud/models/ModifyResourceTypeAutoEnableRequest.hpp>
#include <alibabacloud/models/ModifyResourceTypeAutoEnableResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceTypeAutoEnableResponse.hpp>
#include <alibabacloud/models/ModifySensitiveSwitchRequest.hpp>
#include <alibabacloud/models/ModifySensitiveSwitchResponseBody.hpp>
#include <alibabacloud/models/ModifySensitiveSwitchResponse.hpp>
#include <alibabacloud/models/ModifySlsDispatchStatusRequest.hpp>
#include <alibabacloud/models/ModifySlsDispatchStatusResponseBody.hpp>
#include <alibabacloud/models/ModifySlsDispatchStatusResponse.hpp>
#include <alibabacloud/models/ModifyThreatIntelligenceSwitchRequest.hpp>
#include <alibabacloud/models/ModifyThreatIntelligenceSwitchResponseBody.hpp>
#include <alibabacloud/models/ModifyThreatIntelligenceSwitchResponse.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2ConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2ConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2ConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2RoutePolicyScopeRequest.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2RoutePolicyScopeShrinkRequest.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2RoutePolicyScopeResponseBody.hpp>
#include <alibabacloud/models/ModifyTrFirewallV2RoutePolicyScopeResponse.hpp>
#include <alibabacloud/models/ModifyUserAlarmConfigRequest.hpp>
#include <alibabacloud/models/ModifyUserAlarmConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyUserAlarmConfigResponse.hpp>
#include <alibabacloud/models/ModifyUserIPSWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyUserIPSWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyUserIPSWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyUserSlsLogStorageTimeRequest.hpp>
#include <alibabacloud/models/ModifyUserSlsLogStorageTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyUserSlsLogStorageTimeResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallAclEngineModeRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallAclEngineModeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallAclEngineModeResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenConfigureRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenConfigureResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenConfigureResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenSwitchStatusRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenSwitchStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallCenSwitchStatusResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallConfigureRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallConfigureResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallConfigureResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyPositionRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyPositionResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallControlPolicyPositionResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallDefaultIPSConfigRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallDefaultIPSConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallDefaultIPSConfigResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallIPSWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallIPSWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallIPSWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyVpcFirewallSwitchStatusRequest.hpp>
#include <alibabacloud/models/ModifyVpcFirewallSwitchStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcFirewallSwitchStatusResponse.hpp>
#include <alibabacloud/models/PutDisableAllFwSwitchRequest.hpp>
#include <alibabacloud/models/PutDisableAllFwSwitchResponseBody.hpp>
#include <alibabacloud/models/PutDisableAllFwSwitchResponse.hpp>
#include <alibabacloud/models/PutDisableFwSwitchRequest.hpp>
#include <alibabacloud/models/PutDisableFwSwitchResponseBody.hpp>
#include <alibabacloud/models/PutDisableFwSwitchResponse.hpp>
#include <alibabacloud/models/PutEnableAllFwSwitchRequest.hpp>
#include <alibabacloud/models/PutEnableAllFwSwitchResponseBody.hpp>
#include <alibabacloud/models/PutEnableAllFwSwitchResponse.hpp>
#include <alibabacloud/models/PutEnableFwSwitchRequest.hpp>
#include <alibabacloud/models/PutEnableFwSwitchResponseBody.hpp>
#include <alibabacloud/models/PutEnableFwSwitchResponse.hpp>
#include <alibabacloud/models/ReleaseExpiredInstanceRequest.hpp>
#include <alibabacloud/models/ReleaseExpiredInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseExpiredInstanceResponse.hpp>
#include <alibabacloud/models/ReleasePostInstanceRequest.hpp>
#include <alibabacloud/models/ReleasePostInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleasePostInstanceResponse.hpp>
#include <alibabacloud/models/ResetNatFirewallRuleHitCountRequest.hpp>
#include <alibabacloud/models/ResetNatFirewallRuleHitCountResponseBody.hpp>
#include <alibabacloud/models/ResetNatFirewallRuleHitCountResponse.hpp>
#include <alibabacloud/models/ResetRuleHitCountRequest.hpp>
#include <alibabacloud/models/ResetRuleHitCountResponseBody.hpp>
#include <alibabacloud/models/ResetRuleHitCountResponse.hpp>
#include <alibabacloud/models/ResetVpcFirewallRuleHitCountRequest.hpp>
#include <alibabacloud/models/ResetVpcFirewallRuleHitCountResponseBody.hpp>
#include <alibabacloud/models/ResetVpcFirewallRuleHitCountResponse.hpp>
#include <alibabacloud/models/SetAutoProtectNewAssetsRequest.hpp>
#include <alibabacloud/models/SetAutoProtectNewAssetsResponseBody.hpp>
#include <alibabacloud/models/SetAutoProtectNewAssetsResponse.hpp>
#include <alibabacloud/models/SwitchSecurityProxyRequest.hpp>
#include <alibabacloud/models/SwitchSecurityProxyResponseBody.hpp>
#include <alibabacloud/models/SwitchSecurityProxyResponse.hpp>
#include <alibabacloud/models/UpdateAITrafficAnalysisStatusRequest.hpp>
#include <alibabacloud/models/UpdateAITrafficAnalysisStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateAITrafficAnalysisStatusResponse.hpp>
#include <alibabacloud/models/UpdateAckClusterConnectorRequest.hpp>
#include <alibabacloud/models/UpdateAckClusterConnectorResponseBody.hpp>
#include <alibabacloud/models/UpdateAckClusterConnectorResponse.hpp>
#include <alibabacloud/models/UpdateAclCheckDetailStatusRequest.hpp>
#include <alibabacloud/models/UpdateAclCheckDetailStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateAclCheckDetailStatusResponse.hpp>
#include <alibabacloud/models/UpdatePostpayUserInternetStatusRequest.hpp>
#include <alibabacloud/models/UpdatePostpayUserInternetStatusResponseBody.hpp>
#include <alibabacloud/models/UpdatePostpayUserInternetStatusResponse.hpp>
#include <alibabacloud/models/UpdatePostpayUserNatStatusRequest.hpp>
#include <alibabacloud/models/UpdatePostpayUserNatStatusResponseBody.hpp>
#include <alibabacloud/models/UpdatePostpayUserNatStatusResponse.hpp>
#include <alibabacloud/models/UpdatePostpayUserVpcStatusRequest.hpp>
#include <alibabacloud/models/UpdatePostpayUserVpcStatusResponseBody.hpp>
#include <alibabacloud/models/UpdatePostpayUserVpcStatusResponse.hpp>
#include <alibabacloud/models/UpdateSecurityProxyRequest.hpp>
#include <alibabacloud/models/UpdateSecurityProxyResponseBody.hpp>
#include <alibabacloud/models/UpdateSecurityProxyResponse.hpp>
#include <alibabacloud/models/UseAclBackupDataRequest.hpp>
#include <alibabacloud/models/UseAclBackupDataResponseBody.hpp>
#include <alibabacloud/models/UseAclBackupDataResponse.hpp>

#endif
