// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_REGISTERKNOWLEDGEBASEFILERESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_REGISTERKNOWLEDGEBASEFILERESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Polardb20170801
{
namespace Models
{
  class RegisterKnowledgeBaseFileResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const RegisterKnowledgeBaseFileResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(FileId, fileId_);
      DARABONBA_PTR_TO_JSON(FileName, fileName_);
      DARABONBA_PTR_TO_JSON(FilePath, filePath_);
      DARABONBA_PTR_TO_JSON(Idempotent, idempotent_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(Status, status_);
    };
    friend void from_json(const Darabonba::Json& j, RegisterKnowledgeBaseFileResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(FileId, fileId_);
      DARABONBA_PTR_FROM_JSON(FileName, fileName_);
      DARABONBA_PTR_FROM_JSON(FilePath, filePath_);
      DARABONBA_PTR_FROM_JSON(Idempotent, idempotent_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(Status, status_);
    };
    RegisterKnowledgeBaseFileResponseBody() = default ;
    RegisterKnowledgeBaseFileResponseBody(const RegisterKnowledgeBaseFileResponseBody &) = default ;
    RegisterKnowledgeBaseFileResponseBody(RegisterKnowledgeBaseFileResponseBody &&) = default ;
    RegisterKnowledgeBaseFileResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~RegisterKnowledgeBaseFileResponseBody() = default ;
    RegisterKnowledgeBaseFileResponseBody& operator=(const RegisterKnowledgeBaseFileResponseBody &) = default ;
    RegisterKnowledgeBaseFileResponseBody& operator=(RegisterKnowledgeBaseFileResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->fileId_ == nullptr
        && this->fileName_ == nullptr && this->filePath_ == nullptr && this->idempotent_ == nullptr && this->requestId_ == nullptr && this->status_ == nullptr; };
    // fileId Field Functions 
    bool hasFileId() const { return this->fileId_ != nullptr;};
    void deleteFileId() { this->fileId_ = nullptr;};
    inline string getFileId() const { DARABONBA_PTR_GET_DEFAULT(fileId_, "") };
    inline RegisterKnowledgeBaseFileResponseBody& setFileId(string fileId) { DARABONBA_PTR_SET_VALUE(fileId_, fileId) };


    // fileName Field Functions 
    bool hasFileName() const { return this->fileName_ != nullptr;};
    void deleteFileName() { this->fileName_ = nullptr;};
    inline string getFileName() const { DARABONBA_PTR_GET_DEFAULT(fileName_, "") };
    inline RegisterKnowledgeBaseFileResponseBody& setFileName(string fileName) { DARABONBA_PTR_SET_VALUE(fileName_, fileName) };


    // filePath Field Functions 
    bool hasFilePath() const { return this->filePath_ != nullptr;};
    void deleteFilePath() { this->filePath_ = nullptr;};
    inline string getFilePath() const { DARABONBA_PTR_GET_DEFAULT(filePath_, "") };
    inline RegisterKnowledgeBaseFileResponseBody& setFilePath(string filePath) { DARABONBA_PTR_SET_VALUE(filePath_, filePath) };


    // idempotent Field Functions 
    bool hasIdempotent() const { return this->idempotent_ != nullptr;};
    void deleteIdempotent() { this->idempotent_ = nullptr;};
    inline bool getIdempotent() const { DARABONBA_PTR_GET_DEFAULT(idempotent_, false) };
    inline RegisterKnowledgeBaseFileResponseBody& setIdempotent(bool idempotent) { DARABONBA_PTR_SET_VALUE(idempotent_, idempotent) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline RegisterKnowledgeBaseFileResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // status Field Functions 
    bool hasStatus() const { return this->status_ != nullptr;};
    void deleteStatus() { this->status_ = nullptr;};
    inline string getStatus() const { DARABONBA_PTR_GET_DEFAULT(status_, "") };
    inline RegisterKnowledgeBaseFileResponseBody& setStatus(string status) { DARABONBA_PTR_SET_VALUE(status_, status) };


  protected:
    // The file ID, which is generated by the server based on the ETL rules for native OSS files.
    shared_ptr<string> fileId_ {};
    // The file name.
    shared_ptr<string> fileName_ {};
    // The OSS object key of the registered file.
    shared_ptr<string> filePath_ {};
    // Indicates whether an existing idempotent record is matched. Valid values:
    // - true: An existing idempotent record is matched.
    // - false: No existing idempotent record is matched.
    shared_ptr<bool> idempotent_ {};
    // The request ID.
    shared_ptr<string> requestId_ {};
    // The file processing status.
    shared_ptr<string> status_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Polardb20170801
#endif
