// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SYSOM20231230MODEL_HPP_
#define ALIBABACLOUD_SYSOM20231230MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AuthDiagnosisRequest.hpp>
#include <alibabacloud/models/AuthDiagnosisResponseBody.hpp>
#include <alibabacloud/models/AuthDiagnosisResponse.hpp>
#include <alibabacloud/models/CheckInstanceSupportRequest.hpp>
#include <alibabacloud/models/CheckInstanceSupportResponseBody.hpp>
#include <alibabacloud/models/CheckInstanceSupportResponse.hpp>
#include <alibabacloud/models/CreateAlertStrategyRequest.hpp>
#include <alibabacloud/models/CreateAlertStrategyResponseBody.hpp>
#include <alibabacloud/models/CreateAlertStrategyResponse.hpp>
#include <alibabacloud/models/CreateVmcoreDiagnosisTaskRequest.hpp>
#include <alibabacloud/models/CreateVmcoreDiagnosisTaskResponseBody.hpp>
#include <alibabacloud/models/CreateVmcoreDiagnosisTaskResponse.hpp>
#include <alibabacloud/models/DeleteAlertStrategyRequest.hpp>
#include <alibabacloud/models/DeleteAlertStrategyResponseBody.hpp>
#include <alibabacloud/models/DeleteAlertStrategyResponse.hpp>
#include <alibabacloud/models/DescribeMetricListRequest.hpp>
#include <alibabacloud/models/DescribeMetricListResponseBody.hpp>
#include <alibabacloud/models/DescribeMetricListResponse.hpp>
#include <alibabacloud/models/GenerateCopilotResponseRequest.hpp>
#include <alibabacloud/models/GenerateCopilotResponseResponseBody.hpp>
#include <alibabacloud/models/GenerateCopilotResponseResponse.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseRequest.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseResponseBody.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseResponse.hpp>
#include <alibabacloud/models/GetAIQueryResultRequest.hpp>
#include <alibabacloud/models/GetAIQueryResultResponseBody.hpp>
#include <alibabacloud/models/GetAIQueryResultResponse.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountRequest.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountResponseBody.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountResponse.hpp>
#include <alibabacloud/models/GetAgentRequest.hpp>
#include <alibabacloud/models/GetAgentResponseBody.hpp>
#include <alibabacloud/models/GetAgentResponse.hpp>
#include <alibabacloud/models/GetAgentTaskRequest.hpp>
#include <alibabacloud/models/GetAgentTaskResponseBody.hpp>
#include <alibabacloud/models/GetAgentTaskResponse.hpp>
#include <alibabacloud/models/GetAlertStrategyRequest.hpp>
#include <alibabacloud/models/GetAlertStrategyResponseBody.hpp>
#include <alibabacloud/models/GetAlertStrategyResponse.hpp>
#include <alibabacloud/models/GetCopilotHistoryRequest.hpp>
#include <alibabacloud/models/GetCopilotHistoryResponseBody.hpp>
#include <alibabacloud/models/GetCopilotHistoryResponse.hpp>
#include <alibabacloud/models/GetDiagnosisResultRequest.hpp>
#include <alibabacloud/models/GetDiagnosisResultResponseBody.hpp>
#include <alibabacloud/models/GetDiagnosisResultResponse.hpp>
#include <alibabacloud/models/GetHealthPercentageRequest.hpp>
#include <alibabacloud/models/GetHealthPercentageResponseBody.hpp>
#include <alibabacloud/models/GetHealthPercentageResponse.hpp>
#include <alibabacloud/models/GetHostCountRequest.hpp>
#include <alibabacloud/models/GetHostCountResponseBody.hpp>
#include <alibabacloud/models/GetHostCountResponse.hpp>
#include <alibabacloud/models/GetHotSpotUniqListRequest.hpp>
#include <alibabacloud/models/GetHotSpotUniqListResponseBody.hpp>
#include <alibabacloud/models/GetHotSpotUniqListResponse.hpp>
#include <alibabacloud/models/GetHotspotAnalysisRequest.hpp>
#include <alibabacloud/models/GetHotspotAnalysisResponseBody.hpp>
#include <alibabacloud/models/GetHotspotAnalysisResponse.hpp>
#include <alibabacloud/models/GetHotspotCompareRequest.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBody.hpp>
#include <alibabacloud/models/GetHotspotCompareResponse.hpp>
#include <alibabacloud/models/GetHotspotInstanceListRequest.hpp>
#include <alibabacloud/models/GetHotspotInstanceListResponseBody.hpp>
#include <alibabacloud/models/GetHotspotInstanceListResponse.hpp>
#include <alibabacloud/models/GetHotspotPidListRequest.hpp>
#include <alibabacloud/models/GetHotspotPidListResponseBody.hpp>
#include <alibabacloud/models/GetHotspotPidListResponse.hpp>
#include <alibabacloud/models/GetHotspotTrackingRequest.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponseBody.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponse.hpp>
#include <alibabacloud/models/GetInstantScoreRequest.hpp>
#include <alibabacloud/models/GetInstantScoreResponseBody.hpp>
#include <alibabacloud/models/GetInstantScoreResponse.hpp>
#include <alibabacloud/models/GetListRecordRequest.hpp>
#include <alibabacloud/models/GetListRecordResponseBody.hpp>
#include <alibabacloud/models/GetListRecordResponse.hpp>
#include <alibabacloud/models/GetProblemPercentageRequest.hpp>
#include <alibabacloud/models/GetProblemPercentageResponseBody.hpp>
#include <alibabacloud/models/GetProblemPercentageResponse.hpp>
#include <alibabacloud/models/GetRangeScoreRequest.hpp>
#include <alibabacloud/models/GetRangeScoreResponseBody.hpp>
#include <alibabacloud/models/GetRangeScoreResponse.hpp>
#include <alibabacloud/models/GetResourcesRequest.hpp>
#include <alibabacloud/models/GetResourcesResponseBody.hpp>
#include <alibabacloud/models/GetResourcesResponse.hpp>
#include <alibabacloud/models/GetServiceFuncStatusRequest.hpp>
#include <alibabacloud/models/GetServiceFuncStatusShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponseBody.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponse.hpp>
#include <alibabacloud/models/GetVmcoreDiagnosisTaskRequest.hpp>
#include <alibabacloud/models/GetVmcoreDiagnosisTaskResponseBody.hpp>
#include <alibabacloud/models/GetVmcoreDiagnosisTaskResponse.hpp>
#include <alibabacloud/models/InitialSysomRequest.hpp>
#include <alibabacloud/models/InitialSysomResponseBody.hpp>
#include <alibabacloud/models/InitialSysomResponse.hpp>
#include <alibabacloud/models/InstallAgentRequest.hpp>
#include <alibabacloud/models/InstallAgentResponseBody.hpp>
#include <alibabacloud/models/InstallAgentResponse.hpp>
#include <alibabacloud/models/InstallAgentForClusterRequest.hpp>
#include <alibabacloud/models/InstallAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/InstallAgentForClusterResponse.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisRequest.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisResponseBody.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisResponse.hpp>
#include <alibabacloud/models/InvokeDiagnosisRequest.hpp>
#include <alibabacloud/models/InvokeDiagnosisResponseBody.hpp>
#include <alibabacloud/models/InvokeDiagnosisResponse.hpp>
#include <alibabacloud/models/ListAbnormalyEventsRequest.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponseBody.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponse.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsRequest.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsResponseBody.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsResponse.hpp>
#include <alibabacloud/models/ListAgentsRequest.hpp>
#include <alibabacloud/models/ListAgentsResponseBody.hpp>
#include <alibabacloud/models/ListAgentsResponse.hpp>
#include <alibabacloud/models/ListAlertItemsResponseBody.hpp>
#include <alibabacloud/models/ListAlertItemsResponse.hpp>
#include <alibabacloud/models/ListAlertStrategiesRequest.hpp>
#include <alibabacloud/models/ListAlertStrategiesResponseBody.hpp>
#include <alibabacloud/models/ListAlertStrategiesResponse.hpp>
#include <alibabacloud/models/ListAllInstancesRequest.hpp>
#include <alibabacloud/models/ListAllInstancesResponseBody.hpp>
#include <alibabacloud/models/ListAllInstancesResponse.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsRequest.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsResponseBody.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsResponse.hpp>
#include <alibabacloud/models/ListClustersRequest.hpp>
#include <alibabacloud/models/ListClustersResponseBody.hpp>
#include <alibabacloud/models/ListClustersResponse.hpp>
#include <alibabacloud/models/ListDiagnosisRequest.hpp>
#include <alibabacloud/models/ListDiagnosisResponseBody.hpp>
#include <alibabacloud/models/ListDiagnosisResponse.hpp>
#include <alibabacloud/models/ListInstanceHealthRequest.hpp>
#include <alibabacloud/models/ListInstanceHealthResponseBody.hpp>
#include <alibabacloud/models/ListInstanceHealthResponse.hpp>
#include <alibabacloud/models/ListInstanceStatusRequest.hpp>
#include <alibabacloud/models/ListInstanceStatusResponseBody.hpp>
#include <alibabacloud/models/ListInstanceStatusResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListRequest.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListResponseBody.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListResponse.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoRequest.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoShrinkRequest.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponseBody.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponse.hpp>
#include <alibabacloud/models/ListPluginsInstancesRequest.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponseBody.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponse.hpp>
#include <alibabacloud/models/ListPodsOfInstanceRequest.hpp>
#include <alibabacloud/models/ListPodsOfInstanceResponseBody.hpp>
#include <alibabacloud/models/ListPodsOfInstanceResponse.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/ListVmcoreDiagnosisTaskRequest.hpp>
#include <alibabacloud/models/ListVmcoreDiagnosisTaskResponseBody.hpp>
#include <alibabacloud/models/ListVmcoreDiagnosisTaskResponse.hpp>
#include <alibabacloud/models/StartAIAnalysisRequest.hpp>
#include <alibabacloud/models/StartAIAnalysisResponseBody.hpp>
#include <alibabacloud/models/StartAIAnalysisResponse.hpp>
#include <alibabacloud/models/StartAIDiffAnalysisRequest.hpp>
#include <alibabacloud/models/StartAIDiffAnalysisResponseBody.hpp>
#include <alibabacloud/models/StartAIDiffAnalysisResponse.hpp>
#include <alibabacloud/models/UninstallAgentRequest.hpp>
#include <alibabacloud/models/UninstallAgentResponseBody.hpp>
#include <alibabacloud/models/UninstallAgentResponse.hpp>
#include <alibabacloud/models/UninstallAgentForClusterRequest.hpp>
#include <alibabacloud/models/UninstallAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/UninstallAgentForClusterResponse.hpp>
#include <alibabacloud/models/UpdateAlertEnabledRequest.hpp>
#include <alibabacloud/models/UpdateAlertEnabledResponseBody.hpp>
#include <alibabacloud/models/UpdateAlertEnabledResponse.hpp>
#include <alibabacloud/models/UpdateAlertStrategyRequest.hpp>
#include <alibabacloud/models/UpdateAlertStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateAlertStrategyResponse.hpp>
#include <alibabacloud/models/UpdateEventsAttentionRequest.hpp>
#include <alibabacloud/models/UpdateEventsAttentionResponseBody.hpp>
#include <alibabacloud/models/UpdateEventsAttentionResponse.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordRequest.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordShrinkRequest.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordResponseBody.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordResponse.hpp>
#include <alibabacloud/models/UpgradeAgentRequest.hpp>
#include <alibabacloud/models/UpgradeAgentResponseBody.hpp>
#include <alibabacloud/models/UpgradeAgentResponse.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterRequest.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterResponse.hpp>

#endif
