// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SYSOM20231230MODEL_HPP_
#define ALIBABACLOUD_SYSOM20231230MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AuthDiagnosisRequest.hpp>
#include <alibabacloud/models/AuthDiagnosisResponseBody.hpp>
#include <alibabacloud/models/AuthDiagnosisResponse.hpp>
#include <alibabacloud/models/CheckInstanceSupportRequest.hpp>
#include <alibabacloud/models/CheckInstanceSupportResponseBody.hpp>
#include <alibabacloud/models/CheckInstanceSupportResponse.hpp>
#include <alibabacloud/models/GenerateCopilotResponseRequest.hpp>
#include <alibabacloud/models/GenerateCopilotResponseResponseBody.hpp>
#include <alibabacloud/models/GenerateCopilotResponseResponse.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseRequest.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseResponseBody.hpp>
#include <alibabacloud/models/GenerateCopilotStreamResponseResponse.hpp>
#include <alibabacloud/models/GetAiqueryResultRequest.hpp>
#include <alibabacloud/models/GetAiqueryResultResponseBody.hpp>
#include <alibabacloud/models/GetAiqueryResultResponse.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountRequest.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountResponseBody.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountResponse.hpp>
#include <alibabacloud/models/GetAgentRequest.hpp>
#include <alibabacloud/models/GetAgentResponseBody.hpp>
#include <alibabacloud/models/GetAgentResponse.hpp>
#include <alibabacloud/models/GetAgentTaskRequest.hpp>
#include <alibabacloud/models/GetAgentTaskResponseBody.hpp>
#include <alibabacloud/models/GetAgentTaskResponse.hpp>
#include <alibabacloud/models/GetCopilotHistoryRequest.hpp>
#include <alibabacloud/models/GetCopilotHistoryResponseBody.hpp>
#include <alibabacloud/models/GetCopilotHistoryResponse.hpp>
#include <alibabacloud/models/GetDiagnosisResultRequest.hpp>
#include <alibabacloud/models/GetDiagnosisResultResponseBody.hpp>
#include <alibabacloud/models/GetDiagnosisResultResponse.hpp>
#include <alibabacloud/models/GetHealthPercentageRequest.hpp>
#include <alibabacloud/models/GetHealthPercentageResponseBody.hpp>
#include <alibabacloud/models/GetHealthPercentageResponse.hpp>
#include <alibabacloud/models/GetHostCountRequest.hpp>
#include <alibabacloud/models/GetHostCountResponseBody.hpp>
#include <alibabacloud/models/GetHostCountResponse.hpp>
#include <alibabacloud/models/GetHotSpotUniqListRequest.hpp>
#include <alibabacloud/models/GetHotSpotUniqListResponseBody.hpp>
#include <alibabacloud/models/GetHotSpotUniqListResponse.hpp>
#include <alibabacloud/models/GetHotspotAnalysisRequest.hpp>
#include <alibabacloud/models/GetHotspotAnalysisResponseBody.hpp>
#include <alibabacloud/models/GetHotspotAnalysisResponse.hpp>
#include <alibabacloud/models/GetHotspotCompareRequest.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBody.hpp>
#include <alibabacloud/models/GetHotspotCompareResponse.hpp>
#include <alibabacloud/models/GetHotspotInstanceListRequest.hpp>
#include <alibabacloud/models/GetHotspotInstanceListResponseBody.hpp>
#include <alibabacloud/models/GetHotspotInstanceListResponse.hpp>
#include <alibabacloud/models/GetHotspotPidListRequest.hpp>
#include <alibabacloud/models/GetHotspotPidListResponseBody.hpp>
#include <alibabacloud/models/GetHotspotPidListResponse.hpp>
#include <alibabacloud/models/GetHotspotTrackingRequest.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponseBody.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponse.hpp>
#include <alibabacloud/models/GetInstantScoreRequest.hpp>
#include <alibabacloud/models/GetInstantScoreResponseBody.hpp>
#include <alibabacloud/models/GetInstantScoreResponse.hpp>
#include <alibabacloud/models/GetListRecordRequest.hpp>
#include <alibabacloud/models/GetListRecordResponseBody.hpp>
#include <alibabacloud/models/GetListRecordResponse.hpp>
#include <alibabacloud/models/GetProblemPercentageRequest.hpp>
#include <alibabacloud/models/GetProblemPercentageResponseBody.hpp>
#include <alibabacloud/models/GetProblemPercentageResponse.hpp>
#include <alibabacloud/models/GetRangeScoreRequest.hpp>
#include <alibabacloud/models/GetRangeScoreResponseBody.hpp>
#include <alibabacloud/models/GetRangeScoreResponse.hpp>
#include <alibabacloud/models/GetResourcesRequest.hpp>
#include <alibabacloud/models/GetResourcesResponseBody.hpp>
#include <alibabacloud/models/GetResourcesResponse.hpp>
#include <alibabacloud/models/GetServiceFuncStatusRequest.hpp>
#include <alibabacloud/models/GetServiceFuncStatusShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponseBody.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponse.hpp>
#include <alibabacloud/models/InitialSysomRequest.hpp>
#include <alibabacloud/models/InitialSysomResponseBody.hpp>
#include <alibabacloud/models/InitialSysomResponse.hpp>
#include <alibabacloud/models/InstallAgentRequest.hpp>
#include <alibabacloud/models/InstallAgentResponseBody.hpp>
#include <alibabacloud/models/InstallAgentResponse.hpp>
#include <alibabacloud/models/InstallAgentForClusterRequest.hpp>
#include <alibabacloud/models/InstallAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/InstallAgentForClusterResponse.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisRequest.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisResponseBody.hpp>
#include <alibabacloud/models/InvokeAnomalyDiagnosisResponse.hpp>
#include <alibabacloud/models/InvokeDiagnosisRequest.hpp>
#include <alibabacloud/models/InvokeDiagnosisResponseBody.hpp>
#include <alibabacloud/models/InvokeDiagnosisResponse.hpp>
#include <alibabacloud/models/ListAbnormalyEventsRequest.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponseBody.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponse.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsRequest.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsResponseBody.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsResponse.hpp>
#include <alibabacloud/models/ListAgentsRequest.hpp>
#include <alibabacloud/models/ListAgentsResponseBody.hpp>
#include <alibabacloud/models/ListAgentsResponse.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsRequest.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsResponseBody.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsResponse.hpp>
#include <alibabacloud/models/ListClustersRequest.hpp>
#include <alibabacloud/models/ListClustersResponseBody.hpp>
#include <alibabacloud/models/ListClustersResponse.hpp>
#include <alibabacloud/models/ListDiagnosisRequest.hpp>
#include <alibabacloud/models/ListDiagnosisResponseBody.hpp>
#include <alibabacloud/models/ListDiagnosisResponse.hpp>
#include <alibabacloud/models/ListInstanceHealthRequest.hpp>
#include <alibabacloud/models/ListInstanceHealthResponseBody.hpp>
#include <alibabacloud/models/ListInstanceHealthResponse.hpp>
#include <alibabacloud/models/ListInstanceStatusRequest.hpp>
#include <alibabacloud/models/ListInstanceStatusResponseBody.hpp>
#include <alibabacloud/models/ListInstanceStatusResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListRequest.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListResponseBody.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListResponse.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoRequest.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoShrinkRequest.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponseBody.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponse.hpp>
#include <alibabacloud/models/ListPluginsInstancesRequest.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponseBody.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponse.hpp>
#include <alibabacloud/models/ListPodsOfInstanceRequest.hpp>
#include <alibabacloud/models/ListPodsOfInstanceResponseBody.hpp>
#include <alibabacloud/models/ListPodsOfInstanceResponse.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/StartAianalysisRequest.hpp>
#include <alibabacloud/models/StartAianalysisResponseBody.hpp>
#include <alibabacloud/models/StartAianalysisResponse.hpp>
#include <alibabacloud/models/StartAidiffAnalysisRequest.hpp>
#include <alibabacloud/models/StartAidiffAnalysisResponseBody.hpp>
#include <alibabacloud/models/StartAidiffAnalysisResponse.hpp>
#include <alibabacloud/models/UninstallAgentRequest.hpp>
#include <alibabacloud/models/UninstallAgentResponseBody.hpp>
#include <alibabacloud/models/UninstallAgentResponse.hpp>
#include <alibabacloud/models/UninstallAgentForClusterRequest.hpp>
#include <alibabacloud/models/UninstallAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/UninstallAgentForClusterResponse.hpp>
#include <alibabacloud/models/UpdateEventsAttentionRequest.hpp>
#include <alibabacloud/models/UpdateEventsAttentionResponseBody.hpp>
#include <alibabacloud/models/UpdateEventsAttentionResponse.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordRequest.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordShrinkRequest.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordResponseBody.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordResponse.hpp>
#include <alibabacloud/models/UpgradeAgentRequest.hpp>
#include <alibabacloud/models/UpgradeAgentResponseBody.hpp>
#include <alibabacloud/models/UpgradeAgentResponse.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterRequest.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterResponseBody.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterResponse.hpp>
#include <alibabacloud/models/AuthDiagnosisRequestInstances.hpp>
#include <alibabacloud/models/CheckInstanceSupportResponseBodyData.hpp>
#include <alibabacloud/models/GetAbnormalEventsCountResponseBodyData.hpp>
#include <alibabacloud/models/GetAgentResponseBodyDataVersions.hpp>
#include <alibabacloud/models/GetAgentResponseBodyData.hpp>
#include <alibabacloud/models/GetAgentTaskResponseBodyDataJobs.hpp>
#include <alibabacloud/models/GetAgentTaskResponseBodyData.hpp>
#include <alibabacloud/models/GetCopilotHistoryResponseBodyData.hpp>
#include <alibabacloud/models/GetDiagnosisResultResponseBodyData.hpp>
#include <alibabacloud/models/GetHealthPercentageResponseBodyData.hpp>
#include <alibabacloud/models/GetHostCountResponseBodyData.hpp>
#include <alibabacloud/models/GetHotSpotUniqListResponseBodyData.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBodyDataFlame.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBodyDataSeriesInstance1.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBodyDataSeriesInstance2.hpp>
#include <alibabacloud/models/GetHotspotCompareResponseBodyData.hpp>
#include <alibabacloud/models/GetHotspotInstanceListResponseBodyData.hpp>
#include <alibabacloud/models/GetHotspotPidListResponseBodyData.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponseBodyDataFlame.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponseBodyDataSeries.hpp>
#include <alibabacloud/models/GetHotspotTrackingResponseBodyData.hpp>
#include <alibabacloud/models/GetInstantScoreResponseBodyData.hpp>
#include <alibabacloud/models/GetListRecordResponseBodyData.hpp>
#include <alibabacloud/models/GetProblemPercentageResponseBodyData.hpp>
#include <alibabacloud/models/GetRangeScoreResponseBodyData.hpp>
#include <alibabacloud/models/GetResourcesResponseBodyData.hpp>
#include <alibabacloud/models/GetServiceFuncStatusRequestParams.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponseBodyDataArgs.hpp>
#include <alibabacloud/models/GetServiceFuncStatusResponseBodyData.hpp>
#include <alibabacloud/models/InitialSysomResponseBodyData.hpp>
#include <alibabacloud/models/InstallAgentRequestInstances.hpp>
#include <alibabacloud/models/InstallAgentResponseBodyData.hpp>
#include <alibabacloud/models/InstallAgentForClusterResponseBodyData.hpp>
#include <alibabacloud/models/InvokeDiagnosisResponseBodyData.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponseBodyDataOptsResult.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponseBodyDataOpts.hpp>
#include <alibabacloud/models/ListAbnormalyEventsResponseBodyData.hpp>
#include <alibabacloud/models/ListAgentInstallRecordsResponseBodyData.hpp>
#include <alibabacloud/models/ListAgentsResponseBodyDataVersions.hpp>
#include <alibabacloud/models/ListAgentsResponseBodyData.hpp>
#include <alibabacloud/models/ListClusterAgentInstallRecordsResponseBodyData.hpp>
#include <alibabacloud/models/ListClustersResponseBodyData.hpp>
#include <alibabacloud/models/ListDiagnosisResponseBodyData.hpp>
#include <alibabacloud/models/ListInstanceHealthResponseBodyData.hpp>
#include <alibabacloud/models/ListInstanceStatusResponseBodyData.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyData.hpp>
#include <alibabacloud/models/ListInstancesEcsInfoListResponseBodyData.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoRequestInstanceTag.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponseBodyDataInstanceTag.hpp>
#include <alibabacloud/models/ListInstancesWithEcsInfoResponseBodyData.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponseBodyDataInstanceTag.hpp>
#include <alibabacloud/models/ListPluginsInstancesResponseBodyData.hpp>
#include <alibabacloud/models/ListPodsOfInstanceResponseBodyData.hpp>
#include <alibabacloud/models/StartAianalysisResponseBodyData.hpp>
#include <alibabacloud/models/StartAidiffAnalysisRequestTask1.hpp>
#include <alibabacloud/models/StartAidiffAnalysisRequestTask2.hpp>
#include <alibabacloud/models/UninstallAgentRequestInstances.hpp>
#include <alibabacloud/models/UninstallAgentResponseBodyData.hpp>
#include <alibabacloud/models/UninstallAgentForClusterResponseBodyData.hpp>
#include <alibabacloud/models/UpdateEventsAttentionResponseBodyData.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordRequestParamsArgs.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordRequestParams.hpp>
#include <alibabacloud/models/UpdateFuncSwitchRecordResponseBodyData.hpp>
#include <alibabacloud/models/UpgradeAgentRequestInstances.hpp>
#include <alibabacloud/models/UpgradeAgentResponseBodyData.hpp>
#include <alibabacloud/models/UpgradeAgentForClusterResponseBodyData.hpp>

#endif
