// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SEARCHPLAT20240401MODEL_HPP_
#define ALIBABACLOUD_SEARCHPLAT20240401MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CeaseFunctionInstanceRequest.hpp>
#include <alibabacloud/models/CeaseFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/CeaseFunctionInstanceResponse.hpp>
#include <alibabacloud/models/CreateAsyncTaskRequest.hpp>
#include <alibabacloud/models/CreateAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/CreateAsyncTaskResponse.hpp>
#include <alibabacloud/models/CreateCapabilityRequest.hpp>
#include <alibabacloud/models/CreateCapabilityResponseBody.hpp>
#include <alibabacloud/models/CreateCapabilityResponse.hpp>
#include <alibabacloud/models/CreateConfigRequest.hpp>
#include <alibabacloud/models/CreateConfigResponseBody.hpp>
#include <alibabacloud/models/CreateConfigResponse.hpp>
#include <alibabacloud/models/CreateCredentialsRequest.hpp>
#include <alibabacloud/models/CreateCredentialsResponseBody.hpp>
#include <alibabacloud/models/CreateCredentialsResponse.hpp>
#include <alibabacloud/models/CreateExperienceDataRequest.hpp>
#include <alibabacloud/models/CreateExperienceDataResponseBody.hpp>
#include <alibabacloud/models/CreateExperienceDataResponse.hpp>
#include <alibabacloud/models/CreateFunctionInstanceRequest.hpp>
#include <alibabacloud/models/CreateFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateFunctionInstanceResponse.hpp>
#include <alibabacloud/models/CreateFunctionTaskRequest.hpp>
#include <alibabacloud/models/CreateFunctionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFunctionTaskResponse.hpp>
#include <alibabacloud/models/CreateOfflineTaskRequest.hpp>
#include <alibabacloud/models/CreateOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/CreateOfflineTaskResponse.hpp>
#include <alibabacloud/models/CreateRagEvaluatorTaskRequest.hpp>
#include <alibabacloud/models/CreateRagEvaluatorTaskResponseBody.hpp>
#include <alibabacloud/models/CreateRagEvaluatorTaskResponse.hpp>
#include <alibabacloud/models/CreateWorkspaceRequest.hpp>
#include <alibabacloud/models/CreateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/CreateWorkspaceResponse.hpp>
#include <alibabacloud/models/DeleteCapabilityRequest.hpp>
#include <alibabacloud/models/DeleteCapabilityResponseBody.hpp>
#include <alibabacloud/models/DeleteCapabilityResponse.hpp>
#include <alibabacloud/models/DeleteConfigRequest.hpp>
#include <alibabacloud/models/DeleteConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteConfigResponse.hpp>
#include <alibabacloud/models/DeleteCredentialsRequest.hpp>
#include <alibabacloud/models/DeleteCredentialsResponseBody.hpp>
#include <alibabacloud/models/DeleteCredentialsResponse.hpp>
#include <alibabacloud/models/DeleteExperienceDataRequest.hpp>
#include <alibabacloud/models/DeleteExperienceDataResponseBody.hpp>
#include <alibabacloud/models/DeleteExperienceDataResponse.hpp>
#include <alibabacloud/models/DeleteFunctionInstanceRequest.hpp>
#include <alibabacloud/models/DeleteFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteFunctionInstanceResponse.hpp>
#include <alibabacloud/models/DeleteOfflineTaskRequest.hpp>
#include <alibabacloud/models/DeleteOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteOfflineTaskResponse.hpp>
#include <alibabacloud/models/DeleteRagEvaluatorTaskRequest.hpp>
#include <alibabacloud/models/DeleteRagEvaluatorTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteRagEvaluatorTaskResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceRequest.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponse.hpp>
#include <alibabacloud/models/DescribeCapabilityRequest.hpp>
#include <alibabacloud/models/DescribeCapabilityResponseBody.hpp>
#include <alibabacloud/models/DescribeCapabilityResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/GetAsyncTaskRequest.hpp>
#include <alibabacloud/models/GetAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/GetAsyncTaskResponse.hpp>
#include <alibabacloud/models/GetConfigRequest.hpp>
#include <alibabacloud/models/GetConfigResponseBody.hpp>
#include <alibabacloud/models/GetConfigResponse.hpp>
#include <alibabacloud/models/GetCredentialsRequest.hpp>
#include <alibabacloud/models/GetCredentialsResponseBody.hpp>
#include <alibabacloud/models/GetCredentialsResponse.hpp>
#include <alibabacloud/models/GetExperienceDataRequest.hpp>
#include <alibabacloud/models/GetExperienceDataResponseBody.hpp>
#include <alibabacloud/models/GetExperienceDataResponse.hpp>
#include <alibabacloud/models/GetFunctionInstanceRequest.hpp>
#include <alibabacloud/models/GetFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/GetFunctionInstanceResponse.hpp>
#include <alibabacloud/models/GetOfflineTaskRequest.hpp>
#include <alibabacloud/models/GetOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/GetOfflineTaskResponse.hpp>
#include <alibabacloud/models/GetOfflineTaskLogRequest.hpp>
#include <alibabacloud/models/GetOfflineTaskLogResponseBody.hpp>
#include <alibabacloud/models/GetOfflineTaskLogResponse.hpp>
#include <alibabacloud/models/GetRagEvaluatorTaskRequest.hpp>
#include <alibabacloud/models/GetRagEvaluatorTaskResponseBody.hpp>
#include <alibabacloud/models/GetRagEvaluatorTaskResponse.hpp>
#include <alibabacloud/models/GetTableColumnsRequest.hpp>
#include <alibabacloud/models/GetTableColumnsResponseBody.hpp>
#include <alibabacloud/models/GetTableColumnsResponse.hpp>
#include <alibabacloud/models/GetTableFieldsRequest.hpp>
#include <alibabacloud/models/GetTableFieldsResponseBody.hpp>
#include <alibabacloud/models/GetTableFieldsResponse.hpp>
#include <alibabacloud/models/GetTablesRequest.hpp>
#include <alibabacloud/models/GetTablesResponseBody.hpp>
#include <alibabacloud/models/GetTablesResponse.hpp>
#include <alibabacloud/models/GetWorkspaceRequest.hpp>
#include <alibabacloud/models/GetWorkspaceResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceResponse.hpp>
#include <alibabacloud/models/ListAsyncTasksRequest.hpp>
#include <alibabacloud/models/ListAsyncTasksResponseBody.hpp>
#include <alibabacloud/models/ListAsyncTasksResponse.hpp>
#include <alibabacloud/models/ListCapabilitiesRequest.hpp>
#include <alibabacloud/models/ListCapabilitiesResponseBody.hpp>
#include <alibabacloud/models/ListCapabilitiesResponse.hpp>
#include <alibabacloud/models/ListConfigsRequest.hpp>
#include <alibabacloud/models/ListConfigsResponseBody.hpp>
#include <alibabacloud/models/ListConfigsResponse.hpp>
#include <alibabacloud/models/ListCredentialsRequest.hpp>
#include <alibabacloud/models/ListCredentialsResponseBody.hpp>
#include <alibabacloud/models/ListCredentialsResponse.hpp>
#include <alibabacloud/models/ListExperienceDataRequest.hpp>
#include <alibabacloud/models/ListExperienceDataResponseBody.hpp>
#include <alibabacloud/models/ListExperienceDataResponse.hpp>
#include <alibabacloud/models/ListFunctionInstancesRequest.hpp>
#include <alibabacloud/models/ListFunctionInstancesResponseBody.hpp>
#include <alibabacloud/models/ListFunctionInstancesResponse.hpp>
#include <alibabacloud/models/ListFunctionRestrictionsRequest.hpp>
#include <alibabacloud/models/ListFunctionRestrictionsResponseBody.hpp>
#include <alibabacloud/models/ListFunctionRestrictionsResponse.hpp>
#include <alibabacloud/models/ListOfflineTaskRequest.hpp>
#include <alibabacloud/models/ListOfflineTaskShrinkRequest.hpp>
#include <alibabacloud/models/ListOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/ListOfflineTaskResponse.hpp>
#include <alibabacloud/models/ListOfflineTaskErrorLogsRequest.hpp>
#include <alibabacloud/models/ListOfflineTaskErrorLogsResponseBody.hpp>
#include <alibabacloud/models/ListOfflineTaskErrorLogsResponse.hpp>
#include <alibabacloud/models/ListRagEvaluatorTasksRequest.hpp>
#include <alibabacloud/models/ListRagEvaluatorTasksResponseBody.hpp>
#include <alibabacloud/models/ListRagEvaluatorTasksResponse.hpp>
#include <alibabacloud/models/ListServicesRequest.hpp>
#include <alibabacloud/models/ListServicesResponseBody.hpp>
#include <alibabacloud/models/ListServicesResponse.hpp>
#include <alibabacloud/models/ListWorkspacesRequest.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBody.hpp>
#include <alibabacloud/models/ListWorkspacesResponse.hpp>
#include <alibabacloud/models/ModifyOfflineTaskRequest.hpp>
#include <alibabacloud/models/ModifyOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyOfflineTaskResponse.hpp>
#include <alibabacloud/models/ModifyOfflineTaskLogRequest.hpp>
#include <alibabacloud/models/ModifyOfflineTaskLogResponseBody.hpp>
#include <alibabacloud/models/ModifyOfflineTaskLogResponse.hpp>
#include <alibabacloud/models/ResumeFunctionInstanceRequest.hpp>
#include <alibabacloud/models/ResumeFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/ResumeFunctionInstanceResponse.hpp>
#include <alibabacloud/models/StartOfflineTaskRequest.hpp>
#include <alibabacloud/models/StartOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/StartOfflineTaskResponse.hpp>
#include <alibabacloud/models/StopOfflineTaskRequest.hpp>
#include <alibabacloud/models/StopOfflineTaskResponseBody.hpp>
#include <alibabacloud/models/StopOfflineTaskResponse.hpp>
#include <alibabacloud/models/UpdateCapabilityRequest.hpp>
#include <alibabacloud/models/UpdateCapabilityResponseBody.hpp>
#include <alibabacloud/models/UpdateCapabilityResponse.hpp>
#include <alibabacloud/models/UpdateConfigRequest.hpp>
#include <alibabacloud/models/UpdateConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateConfigResponse.hpp>
#include <alibabacloud/models/UpdateCredentialsRequest.hpp>
#include <alibabacloud/models/UpdateCredentialsResponseBody.hpp>
#include <alibabacloud/models/UpdateCredentialsResponse.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceRequest.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceResponse.hpp>
#include <alibabacloud/models/UpdateWorkspaceRequest.hpp>
#include <alibabacloud/models/UpdateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkspaceResponse.hpp>

#endif
