// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MAXCOMPUTE20220104MODEL_HPP_
#define ALIBABACLOUD_MAXCOMPUTE20220104MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApplyComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/ApplyComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/CreateComputeQuotaPlanRequest.hpp>
#include <alibabacloud/models/CreateComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/CreateComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/CreateMmsDataSourceRequest.hpp>
#include <alibabacloud/models/CreateMmsDataSourceResponseBody.hpp>
#include <alibabacloud/models/CreateMmsDataSourceResponse.hpp>
#include <alibabacloud/models/CreateMmsFetchMetadataJobRequest.hpp>
#include <alibabacloud/models/CreateMmsFetchMetadataJobResponseBody.hpp>
#include <alibabacloud/models/CreateMmsFetchMetadataJobResponse.hpp>
#include <alibabacloud/models/CreateMmsJobRequest.hpp>
#include <alibabacloud/models/CreateMmsJobResponseBody.hpp>
#include <alibabacloud/models/CreateMmsJobResponse.hpp>
#include <alibabacloud/models/CreatePackageRequest.hpp>
#include <alibabacloud/models/CreatePackageResponseBody.hpp>
#include <alibabacloud/models/CreatePackageResponse.hpp>
#include <alibabacloud/models/CreateProjectRequest.hpp>
#include <alibabacloud/models/CreateProjectResponseBody.hpp>
#include <alibabacloud/models/CreateProjectResponse.hpp>
#include <alibabacloud/models/CreateQuotaRequest.hpp>
#include <alibabacloud/models/CreateQuotaResponseBody.hpp>
#include <alibabacloud/models/CreateQuotaResponse.hpp>
#include <alibabacloud/models/CreateQuotaPlanRequest.hpp>
#include <alibabacloud/models/CreateQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/CreateQuotaPlanResponse.hpp>
#include <alibabacloud/models/CreateRoleRequest.hpp>
#include <alibabacloud/models/CreateRoleResponseBody.hpp>
#include <alibabacloud/models/CreateRoleResponse.hpp>
#include <alibabacloud/models/DeleteComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/DeleteMmsDataSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteMmsDataSourceResponse.hpp>
#include <alibabacloud/models/DeleteMmsJobResponseBody.hpp>
#include <alibabacloud/models/DeleteMmsJobResponse.hpp>
#include <alibabacloud/models/DeleteProjectRequest.hpp>
#include <alibabacloud/models/DeleteProjectResponseBody.hpp>
#include <alibabacloud/models/DeleteProjectResponse.hpp>
#include <alibabacloud/models/DeleteQuotaPlanRequest.hpp>
#include <alibabacloud/models/DeleteQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteQuotaPlanResponse.hpp>
#include <alibabacloud/models/GetComputeEffectivePlanResponseBody.hpp>
#include <alibabacloud/models/GetComputeEffectivePlanResponse.hpp>
#include <alibabacloud/models/GetComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/GetComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/GetComputeQuotaScheduleRequest.hpp>
#include <alibabacloud/models/GetComputeQuotaScheduleResponseBody.hpp>
#include <alibabacloud/models/GetComputeQuotaScheduleResponse.hpp>
#include <alibabacloud/models/GetJobInfoResponseBody.hpp>
#include <alibabacloud/models/GetJobInfoResponse.hpp>
#include <alibabacloud/models/GetJobResourceUsageRequest.hpp>
#include <alibabacloud/models/GetJobResourceUsageShrinkRequest.hpp>
#include <alibabacloud/models/GetJobResourceUsageResponseBody.hpp>
#include <alibabacloud/models/GetJobResourceUsageResponse.hpp>
#include <alibabacloud/models/GetMmsAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/GetMmsAsyncTaskResponse.hpp>
#include <alibabacloud/models/GetMmsDataSourceRequest.hpp>
#include <alibabacloud/models/GetMmsDataSourceResponseBody.hpp>
#include <alibabacloud/models/GetMmsDataSourceResponse.hpp>
#include <alibabacloud/models/GetMmsDbResponseBody.hpp>
#include <alibabacloud/models/GetMmsDbResponse.hpp>
#include <alibabacloud/models/GetMmsFetchMetadataJobResponseBody.hpp>
#include <alibabacloud/models/GetMmsFetchMetadataJobResponse.hpp>
#include <alibabacloud/models/GetMmsJobResponseBody.hpp>
#include <alibabacloud/models/GetMmsJobResponse.hpp>
#include <alibabacloud/models/GetMmsPartitionResponseBody.hpp>
#include <alibabacloud/models/GetMmsPartitionResponse.hpp>
#include <alibabacloud/models/GetMmsTableResponseBody.hpp>
#include <alibabacloud/models/GetMmsTableResponse.hpp>
#include <alibabacloud/models/GetMmsTaskResponseBody.hpp>
#include <alibabacloud/models/GetMmsTaskResponse.hpp>
#include <alibabacloud/models/GetPackageRequest.hpp>
#include <alibabacloud/models/GetPackageResponseBody.hpp>
#include <alibabacloud/models/GetPackageResponse.hpp>
#include <alibabacloud/models/GetProjectRequest.hpp>
#include <alibabacloud/models/GetProjectResponseBody.hpp>
#include <alibabacloud/models/GetProjectResponse.hpp>
#include <alibabacloud/models/GetQuotaRequest.hpp>
#include <alibabacloud/models/GetQuotaResponseBody.hpp>
#include <alibabacloud/models/GetQuotaResponse.hpp>
#include <alibabacloud/models/GetQuotaPlanRequest.hpp>
#include <alibabacloud/models/GetQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/GetQuotaPlanResponse.hpp>
#include <alibabacloud/models/GetQuotaScheduleRequest.hpp>
#include <alibabacloud/models/GetQuotaScheduleResponseBody.hpp>
#include <alibabacloud/models/GetQuotaScheduleResponse.hpp>
#include <alibabacloud/models/GetQuotaUsageRequest.hpp>
#include <alibabacloud/models/GetQuotaUsageShrinkRequest.hpp>
#include <alibabacloud/models/GetQuotaUsageResponseBody.hpp>
#include <alibabacloud/models/GetQuotaUsageResponse.hpp>
#include <alibabacloud/models/GetRoleAclResponseBody.hpp>
#include <alibabacloud/models/GetRoleAclResponse.hpp>
#include <alibabacloud/models/GetRoleAclOnObjectRequest.hpp>
#include <alibabacloud/models/GetRoleAclOnObjectResponseBody.hpp>
#include <alibabacloud/models/GetRoleAclOnObjectResponse.hpp>
#include <alibabacloud/models/GetRolePolicyResponseBody.hpp>
#include <alibabacloud/models/GetRolePolicyResponse.hpp>
#include <alibabacloud/models/GetRunningJobsRequest.hpp>
#include <alibabacloud/models/GetRunningJobsShrinkRequest.hpp>
#include <alibabacloud/models/GetRunningJobsResponseBody.hpp>
#include <alibabacloud/models/GetRunningJobsResponse.hpp>
#include <alibabacloud/models/GetStorageAmountSummaryRequest.hpp>
#include <alibabacloud/models/GetStorageAmountSummaryResponseBody.hpp>
#include <alibabacloud/models/GetStorageAmountSummaryResponse.hpp>
#include <alibabacloud/models/GetStorageSizeSummaryRequest.hpp>
#include <alibabacloud/models/GetStorageSizeSummaryResponseBody.hpp>
#include <alibabacloud/models/GetStorageSizeSummaryResponse.hpp>
#include <alibabacloud/models/GetStorageSummaryComparedRequest.hpp>
#include <alibabacloud/models/GetStorageSummaryComparedShrinkRequest.hpp>
#include <alibabacloud/models/GetStorageSummaryComparedResponseBody.hpp>
#include <alibabacloud/models/GetStorageSummaryComparedResponse.hpp>
#include <alibabacloud/models/GetTableInfoRequest.hpp>
#include <alibabacloud/models/GetTableInfoResponseBody.hpp>
#include <alibabacloud/models/GetTableInfoResponse.hpp>
#include <alibabacloud/models/GetTrustedProjectsResponseBody.hpp>
#include <alibabacloud/models/GetTrustedProjectsResponse.hpp>
#include <alibabacloud/models/KillJobsRequest.hpp>
#include <alibabacloud/models/KillJobsResponseBody.hpp>
#include <alibabacloud/models/KillJobsResponse.hpp>
#include <alibabacloud/models/ListComputeMetricsByInstanceRequest.hpp>
#include <alibabacloud/models/ListComputeMetricsByInstanceResponseBody.hpp>
#include <alibabacloud/models/ListComputeMetricsByInstanceResponse.hpp>
#include <alibabacloud/models/ListComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/ListComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/ListFunctionsRequest.hpp>
#include <alibabacloud/models/ListFunctionsResponseBody.hpp>
#include <alibabacloud/models/ListFunctionsResponse.hpp>
#include <alibabacloud/models/ListJobInfosRequest.hpp>
#include <alibabacloud/models/ListJobInfosResponseBody.hpp>
#include <alibabacloud/models/ListJobInfosResponse.hpp>
#include <alibabacloud/models/ListJobMetricRequest.hpp>
#include <alibabacloud/models/ListJobMetricResponseBody.hpp>
#include <alibabacloud/models/ListJobMetricResponse.hpp>
#include <alibabacloud/models/ListJobSnapshotInfosRequest.hpp>
#include <alibabacloud/models/ListJobSnapshotInfosResponseBody.hpp>
#include <alibabacloud/models/ListJobSnapshotInfosResponse.hpp>
#include <alibabacloud/models/ListMmsDataSourcesRequest.hpp>
#include <alibabacloud/models/ListMmsDataSourcesResponseBody.hpp>
#include <alibabacloud/models/ListMmsDataSourcesResponse.hpp>
#include <alibabacloud/models/ListMmsDbsRequest.hpp>
#include <alibabacloud/models/ListMmsDbsShrinkRequest.hpp>
#include <alibabacloud/models/ListMmsDbsResponseBody.hpp>
#include <alibabacloud/models/ListMmsDbsResponse.hpp>
#include <alibabacloud/models/ListMmsJobsRequest.hpp>
#include <alibabacloud/models/ListMmsJobsResponseBody.hpp>
#include <alibabacloud/models/ListMmsJobsResponse.hpp>
#include <alibabacloud/models/ListMmsPartitionsRequest.hpp>
#include <alibabacloud/models/ListMmsPartitionsShrinkRequest.hpp>
#include <alibabacloud/models/ListMmsPartitionsResponseBody.hpp>
#include <alibabacloud/models/ListMmsPartitionsResponse.hpp>
#include <alibabacloud/models/ListMmsTablesRequest.hpp>
#include <alibabacloud/models/ListMmsTablesShrinkRequest.hpp>
#include <alibabacloud/models/ListMmsTablesResponseBody.hpp>
#include <alibabacloud/models/ListMmsTablesResponse.hpp>
#include <alibabacloud/models/ListMmsTaskLogsResponseBody.hpp>
#include <alibabacloud/models/ListMmsTaskLogsResponse.hpp>
#include <alibabacloud/models/ListMmsTasksRequest.hpp>
#include <alibabacloud/models/ListMmsTasksResponseBody.hpp>
#include <alibabacloud/models/ListMmsTasksResponse.hpp>
#include <alibabacloud/models/ListPackagesResponseBody.hpp>
#include <alibabacloud/models/ListPackagesResponse.hpp>
#include <alibabacloud/models/ListProjectUsersResponseBody.hpp>
#include <alibabacloud/models/ListProjectUsersResponse.hpp>
#include <alibabacloud/models/ListProjectsRequest.hpp>
#include <alibabacloud/models/ListProjectsResponseBody.hpp>
#include <alibabacloud/models/ListProjectsResponse.hpp>
#include <alibabacloud/models/ListQuotasRequest.hpp>
#include <alibabacloud/models/ListQuotasResponseBody.hpp>
#include <alibabacloud/models/ListQuotasResponse.hpp>
#include <alibabacloud/models/ListQuotasPlansRequest.hpp>
#include <alibabacloud/models/ListQuotasPlansResponseBody.hpp>
#include <alibabacloud/models/ListQuotasPlansResponse.hpp>
#include <alibabacloud/models/ListResourcesRequest.hpp>
#include <alibabacloud/models/ListResourcesResponseBody.hpp>
#include <alibabacloud/models/ListResourcesResponse.hpp>
#include <alibabacloud/models/ListRolesResponseBody.hpp>
#include <alibabacloud/models/ListRolesResponse.hpp>
#include <alibabacloud/models/ListStoragePartitionsInfoRequest.hpp>
#include <alibabacloud/models/ListStoragePartitionsInfoShrinkRequest.hpp>
#include <alibabacloud/models/ListStoragePartitionsInfoResponseBody.hpp>
#include <alibabacloud/models/ListStoragePartitionsInfoResponse.hpp>
#include <alibabacloud/models/ListStorageProjectsInfoRequest.hpp>
#include <alibabacloud/models/ListStorageProjectsInfoResponseBody.hpp>
#include <alibabacloud/models/ListStorageProjectsInfoResponse.hpp>
#include <alibabacloud/models/ListStorageTablesInfoRequest.hpp>
#include <alibabacloud/models/ListStorageTablesInfoShrinkRequest.hpp>
#include <alibabacloud/models/ListStorageTablesInfoResponseBody.hpp>
#include <alibabacloud/models/ListStorageTablesInfoResponse.hpp>
#include <alibabacloud/models/ListTablesRequest.hpp>
#include <alibabacloud/models/ListTablesResponseBody.hpp>
#include <alibabacloud/models/ListTablesResponse.hpp>
#include <alibabacloud/models/ListTunnelQuotaTimerResponseBody.hpp>
#include <alibabacloud/models/ListTunnelQuotaTimerResponse.hpp>
#include <alibabacloud/models/ListUsersRequest.hpp>
#include <alibabacloud/models/ListUsersResponseBody.hpp>
#include <alibabacloud/models/ListUsersResponse.hpp>
#include <alibabacloud/models/ListUsersByRoleResponseBody.hpp>
#include <alibabacloud/models/ListUsersByRoleResponse.hpp>
#include <alibabacloud/models/QueryQuotaRequest.hpp>
#include <alibabacloud/models/QueryQuotaResponseBody.hpp>
#include <alibabacloud/models/QueryQuotaResponse.hpp>
#include <alibabacloud/models/QueryQuotaMetricRequest.hpp>
#include <alibabacloud/models/QueryQuotaMetricResponseBody.hpp>
#include <alibabacloud/models/QueryQuotaMetricResponse.hpp>
#include <alibabacloud/models/QueryStorageMetricRequest.hpp>
#include <alibabacloud/models/QueryStorageMetricResponseBody.hpp>
#include <alibabacloud/models/QueryStorageMetricResponse.hpp>
#include <alibabacloud/models/QueryTunnelMetricRequest.hpp>
#include <alibabacloud/models/QueryTunnelMetricResponseBody.hpp>
#include <alibabacloud/models/QueryTunnelMetricResponse.hpp>
#include <alibabacloud/models/QueryTunnelMetricDetailRequest.hpp>
#include <alibabacloud/models/QueryTunnelMetricDetailResponseBody.hpp>
#include <alibabacloud/models/QueryTunnelMetricDetailResponse.hpp>
#include <alibabacloud/models/RetryMmsJobResponseBody.hpp>
#include <alibabacloud/models/RetryMmsJobResponse.hpp>
#include <alibabacloud/models/StartMmsJobResponseBody.hpp>
#include <alibabacloud/models/StartMmsJobResponse.hpp>
#include <alibabacloud/models/StopMmsJobResponseBody.hpp>
#include <alibabacloud/models/StopMmsJobResponse.hpp>
#include <alibabacloud/models/SumStorageMetricsByDateRequest.hpp>
#include <alibabacloud/models/SumStorageMetricsByDateResponseBody.hpp>
#include <alibabacloud/models/SumStorageMetricsByDateResponse.hpp>
#include <alibabacloud/models/UpdateComputeQuotaPlanRequest.hpp>
#include <alibabacloud/models/UpdateComputeQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateComputeQuotaPlanResponse.hpp>
#include <alibabacloud/models/UpdateComputeQuotaScheduleRequest.hpp>
#include <alibabacloud/models/UpdateComputeQuotaScheduleResponseBody.hpp>
#include <alibabacloud/models/UpdateComputeQuotaScheduleResponse.hpp>
#include <alibabacloud/models/UpdateComputeSubQuotaRequest.hpp>
#include <alibabacloud/models/UpdateComputeSubQuotaResponseBody.hpp>
#include <alibabacloud/models/UpdateComputeSubQuotaResponse.hpp>
#include <alibabacloud/models/UpdateMmsDataSourceRequest.hpp>
#include <alibabacloud/models/UpdateMmsDataSourceResponseBody.hpp>
#include <alibabacloud/models/UpdateMmsDataSourceResponse.hpp>
#include <alibabacloud/models/UpdatePackageRequest.hpp>
#include <alibabacloud/models/UpdatePackageResponseBody.hpp>
#include <alibabacloud/models/UpdatePackageResponse.hpp>
#include <alibabacloud/models/UpdateProjectBasicMetaRequest.hpp>
#include <alibabacloud/models/UpdateProjectBasicMetaResponseBody.hpp>
#include <alibabacloud/models/UpdateProjectBasicMetaResponse.hpp>
#include <alibabacloud/models/UpdateProjectDefaultQuotaRequest.hpp>
#include <alibabacloud/models/UpdateProjectDefaultQuotaResponseBody.hpp>
#include <alibabacloud/models/UpdateProjectDefaultQuotaResponse.hpp>
#include <alibabacloud/models/UpdateProjectIpWhiteListRequest.hpp>
#include <alibabacloud/models/UpdateProjectIpWhiteListResponseBody.hpp>
#include <alibabacloud/models/UpdateProjectIpWhiteListResponse.hpp>
#include <alibabacloud/models/UpdateProjectModelTierResponseBody.hpp>
#include <alibabacloud/models/UpdateProjectModelTierResponse.hpp>
#include <alibabacloud/models/UpdateQuotaPlanRequest.hpp>
#include <alibabacloud/models/UpdateQuotaPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateQuotaPlanResponse.hpp>
#include <alibabacloud/models/UpdateQuotaScheduleRequest.hpp>
#include <alibabacloud/models/UpdateQuotaScheduleResponseBody.hpp>
#include <alibabacloud/models/UpdateQuotaScheduleResponse.hpp>
#include <alibabacloud/models/UpdateTunnelQuotaTimerRequest.hpp>
#include <alibabacloud/models/UpdateTunnelQuotaTimerResponseBody.hpp>
#include <alibabacloud/models/UpdateTunnelQuotaTimerResponse.hpp>
#include <alibabacloud/models/UpdateUsersToRoleRequest.hpp>
#include <alibabacloud/models/UpdateUsersToRoleResponseBody.hpp>
#include <alibabacloud/models/UpdateUsersToRoleResponse.hpp>

#endif
