// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ALIDNS20150109MODEL_HPP_
#define ALIBABACLOUD_ALIDNS20150109MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddCustomLineRequest.hpp>
#include <alibabacloud/models/AddCustomLineResponseBody.hpp>
#include <alibabacloud/models/AddCustomLineResponse.hpp>
#include <alibabacloud/models/AddDnsCacheDomainRequest.hpp>
#include <alibabacloud/models/AddDnsCacheDomainResponseBody.hpp>
#include <alibabacloud/models/AddDnsCacheDomainResponse.hpp>
#include <alibabacloud/models/AddDnsGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/AddDnsGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/AddDnsGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/AddDnsGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/AddDnsGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/AddDnsGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/AddDnsGtmMonitorRequest.hpp>
#include <alibabacloud/models/AddDnsGtmMonitorResponseBody.hpp>
#include <alibabacloud/models/AddDnsGtmMonitorResponse.hpp>
#include <alibabacloud/models/AddDomainRequest.hpp>
#include <alibabacloud/models/AddDomainResponseBody.hpp>
#include <alibabacloud/models/AddDomainResponse.hpp>
#include <alibabacloud/models/AddDomainBackupRequest.hpp>
#include <alibabacloud/models/AddDomainBackupResponseBody.hpp>
#include <alibabacloud/models/AddDomainBackupResponse.hpp>
#include <alibabacloud/models/AddDomainGroupRequest.hpp>
#include <alibabacloud/models/AddDomainGroupResponseBody.hpp>
#include <alibabacloud/models/AddDomainGroupResponse.hpp>
#include <alibabacloud/models/AddDomainRecordRequest.hpp>
#include <alibabacloud/models/AddDomainRecordResponseBody.hpp>
#include <alibabacloud/models/AddDomainRecordResponse.hpp>
#include <alibabacloud/models/AddGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/AddGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/AddGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/AddGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/AddGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/AddGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/AddGtmMonitorRequest.hpp>
#include <alibabacloud/models/AddGtmMonitorResponseBody.hpp>
#include <alibabacloud/models/AddGtmMonitorResponse.hpp>
#include <alibabacloud/models/AddGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/AddGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/AddGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/AddRecursionRecordRequest.hpp>
#include <alibabacloud/models/AddRecursionRecordResponseBody.hpp>
#include <alibabacloud/models/AddRecursionRecordResponse.hpp>
#include <alibabacloud/models/AddRecursionZoneRequest.hpp>
#include <alibabacloud/models/AddRecursionZoneResponseBody.hpp>
#include <alibabacloud/models/AddRecursionZoneResponse.hpp>
#include <alibabacloud/models/AddRspDomainServerHoldStatusForGatewayRequest.hpp>
#include <alibabacloud/models/AddRspDomainServerHoldStatusForGatewayResponseBody.hpp>
#include <alibabacloud/models/AddRspDomainServerHoldStatusForGatewayResponse.hpp>
#include <alibabacloud/models/BindInstanceDomainsRequest.hpp>
#include <alibabacloud/models/BindInstanceDomainsResponseBody.hpp>
#include <alibabacloud/models/BindInstanceDomainsResponse.hpp>
#include <alibabacloud/models/ChangeDomainGroupRequest.hpp>
#include <alibabacloud/models/ChangeDomainGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeDomainGroupResponse.hpp>
#include <alibabacloud/models/ChangeDomainOfDnsProductRequest.hpp>
#include <alibabacloud/models/ChangeDomainOfDnsProductResponseBody.hpp>
#include <alibabacloud/models/ChangeDomainOfDnsProductResponse.hpp>
#include <alibabacloud/models/CopyGtmConfigRequest.hpp>
#include <alibabacloud/models/CopyGtmConfigResponseBody.hpp>
#include <alibabacloud/models/CopyGtmConfigResponse.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressShrinkRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressResponseBody.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressResponse.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/CreateCloudGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/CreateCloudGtmInstanceConfigRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/CreateCloudGtmInstanceConfigResponse.hpp>
#include <alibabacloud/models/CreateCloudGtmMonitorTemplateRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmMonitorTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateCloudGtmMonitorTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateCloudGtmMonitorTemplateResponse.hpp>
#include <alibabacloud/models/CreatePdnsAppKeyRequest.hpp>
#include <alibabacloud/models/CreatePdnsAppKeyResponseBody.hpp>
#include <alibabacloud/models/CreatePdnsAppKeyResponse.hpp>
#include <alibabacloud/models/CreatePdnsUdpIpSegmentRequest.hpp>
#include <alibabacloud/models/CreatePdnsUdpIpSegmentResponseBody.hpp>
#include <alibabacloud/models/CreatePdnsUdpIpSegmentResponse.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressRequest.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressResponse.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/DeleteCloudGtmInstanceConfigRequest.hpp>
#include <alibabacloud/models/DeleteCloudGtmInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudGtmInstanceConfigResponse.hpp>
#include <alibabacloud/models/DeleteCloudGtmMonitorTemplateRequest.hpp>
#include <alibabacloud/models/DeleteCloudGtmMonitorTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudGtmMonitorTemplateResponse.hpp>
#include <alibabacloud/models/DeleteCustomLinesRequest.hpp>
#include <alibabacloud/models/DeleteCustomLinesResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomLinesResponse.hpp>
#include <alibabacloud/models/DeleteDnsCacheDomainRequest.hpp>
#include <alibabacloud/models/DeleteDnsCacheDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDnsCacheDomainResponse.hpp>
#include <alibabacloud/models/DeleteDnsGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/DeleteDnsGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/DeleteDnsGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/DeleteDnsGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/DeleteDnsGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DeleteDnsGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/DeleteDomainRequest.hpp>
#include <alibabacloud/models/DeleteDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainResponse.hpp>
#include <alibabacloud/models/DeleteDomainGroupRequest.hpp>
#include <alibabacloud/models/DeleteDomainGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainGroupResponse.hpp>
#include <alibabacloud/models/DeleteDomainRecordRequest.hpp>
#include <alibabacloud/models/DeleteDomainRecordResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainRecordResponse.hpp>
#include <alibabacloud/models/DeleteGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/DeleteGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/DeleteGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/DeleteGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/DeleteGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DeleteGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/DeleteGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/DeleteGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/DeleteRecursionRecordRequest.hpp>
#include <alibabacloud/models/DeleteRecursionRecordResponseBody.hpp>
#include <alibabacloud/models/DeleteRecursionRecordResponse.hpp>
#include <alibabacloud/models/DeleteRecursionZoneRequest.hpp>
#include <alibabacloud/models/DeleteRecursionZoneResponseBody.hpp>
#include <alibabacloud/models/DeleteRecursionZoneResponse.hpp>
#include <alibabacloud/models/DeleteSubDomainRecordsRequest.hpp>
#include <alibabacloud/models/DeleteSubDomainRecordsResponseBody.hpp>
#include <alibabacloud/models/DeleteSubDomainRecordsResponse.hpp>
#include <alibabacloud/models/DescribeBatchResultCountRequest.hpp>
#include <alibabacloud/models/DescribeBatchResultCountResponseBody.hpp>
#include <alibabacloud/models/DescribeBatchResultCountResponse.hpp>
#include <alibabacloud/models/DescribeBatchResultDetailRequest.hpp>
#include <alibabacloud/models/DescribeBatchResultDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeBatchResultDetailResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolReferenceRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolReferenceResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressPoolReferenceResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressReferenceRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressReferenceResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmAddressReferenceResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmGlobalAlertRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmGlobalAlertResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmGlobalAlertResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigAlertRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigAlertResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigAlertResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigFullInfoRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigFullInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmInstanceConfigFullInfoResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmMonitorTemplateRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmMonitorTemplateResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmMonitorTemplateResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmSummaryRequest.hpp>
#include <alibabacloud/models/DescribeCloudGtmSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmSummaryResponse.hpp>
#include <alibabacloud/models/DescribeCloudGtmSystemLinesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudGtmSystemLinesResponse.hpp>
#include <alibabacloud/models/DescribeCustomLineRequest.hpp>
#include <alibabacloud/models/DescribeCustomLineResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomLineResponse.hpp>
#include <alibabacloud/models/DescribeCustomLinesRequest.hpp>
#include <alibabacloud/models/DescribeCustomLinesResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomLinesResponse.hpp>
#include <alibabacloud/models/DescribeDnsslbSubDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDnsslbSubDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsslbSubDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDnsCacheDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDnsCacheDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsCacheDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategiesRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategiesResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategiesResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAccessStrategyAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddrAttributeInfoRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddrAttributeInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddrAttributeInfoResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddressPoolAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddressPoolAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAddressPoolAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmAvailableAlertGroupRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmAvailableAlertGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmAvailableAlertGroupResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolsRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolsResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceAddressPoolsResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceStatusRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceStatusResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceSystemCnameRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceSystemCnameResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstanceSystemCnameResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstancesRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmInstancesResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmLogsRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmLogsResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorConfigRequest.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsGtmMonitorConfigResponse.hpp>
#include <alibabacloud/models/DescribeDnsProductInstanceRequest.hpp>
#include <alibabacloud/models/DescribeDnsProductInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsProductInstanceResponse.hpp>
#include <alibabacloud/models/DescribeDnsProductInstancesRequest.hpp>
#include <alibabacloud/models/DescribeDnsProductInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeDnsProductInstancesResponse.hpp>
#include <alibabacloud/models/DescribeDohAccountStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDohAccountStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDohAccountStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDohDomainStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDohSubDomainStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDohUserInfoRequest.hpp>
#include <alibabacloud/models/DescribeDohUserInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDohUserInfoResponse.hpp>
#include <alibabacloud/models/DescribeDomainDnssecInfoRequest.hpp>
#include <alibabacloud/models/DescribeDomainDnssecInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainDnssecInfoResponse.hpp>
#include <alibabacloud/models/DescribeDomainGroupsRequest.hpp>
#include <alibabacloud/models/DescribeDomainGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainGroupsResponse.hpp>
#include <alibabacloud/models/DescribeDomainInfoRequest.hpp>
#include <alibabacloud/models/DescribeDomainInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainInfoResponse.hpp>
#include <alibabacloud/models/DescribeDomainLogsRequest.hpp>
#include <alibabacloud/models/DescribeDomainLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainLogsResponse.hpp>
#include <alibabacloud/models/DescribeDomainNsRequest.hpp>
#include <alibabacloud/models/DescribeDomainNsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainNsResponse.hpp>
#include <alibabacloud/models/DescribeDomainRecordInfoRequest.hpp>
#include <alibabacloud/models/DescribeDomainRecordInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainRecordInfoResponse.hpp>
#include <alibabacloud/models/DescribeDomainRecordsRequest.hpp>
#include <alibabacloud/models/DescribeDomainRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainRecordsResponse.hpp>
#include <alibabacloud/models/DescribeDomainResolveStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDomainResolveStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainResolveStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainsResponse.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategiesRequest.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategiesResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategiesResponse.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmAccessStrategyAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeGtmAvailableAlertGroupRequest.hpp>
#include <alibabacloud/models/DescribeGtmAvailableAlertGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmAvailableAlertGroupResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstanceRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstanceResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolsRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolsResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstanceAddressPoolsResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstanceStatusRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstanceStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstanceStatusResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstanceSystemCnameRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstanceSystemCnameResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstanceSystemCnameResponse.hpp>
#include <alibabacloud/models/DescribeGtmInstancesRequest.hpp>
#include <alibabacloud/models/DescribeGtmInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmInstancesResponse.hpp>
#include <alibabacloud/models/DescribeGtmLogsRequest.hpp>
#include <alibabacloud/models/DescribeGtmLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmLogsResponse.hpp>
#include <alibabacloud/models/DescribeGtmMonitorAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeGtmMonitorAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmMonitorAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeGtmMonitorConfigRequest.hpp>
#include <alibabacloud/models/DescribeGtmMonitorConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmMonitorConfigResponse.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanAvailableConfigRequest.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanAvailableConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlanAvailableConfigResponse.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlansRequest.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlansResponseBody.hpp>
#include <alibabacloud/models/DescribeGtmRecoveryPlansResponse.hpp>
#include <alibabacloud/models/DescribeInstanceDomainsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceDomainsResponse.hpp>
#include <alibabacloud/models/DescribeInternetDnsLogsRequest.hpp>
#include <alibabacloud/models/DescribeInternetDnsLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeInternetDnsLogsResponse.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheInstancesRequest.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheInstancesResponse.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheRemainQuotaRequest.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheRemainQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheRemainQuotaResponse.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTaskRequest.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTaskResponse.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTasksRequest.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeIspFlushCacheTasksResponse.hpp>
#include <alibabacloud/models/DescribePdnsAccountSummaryRequest.hpp>
#include <alibabacloud/models/DescribePdnsAccountSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsAccountSummaryResponse.hpp>
#include <alibabacloud/models/DescribePdnsAppKeyRequest.hpp>
#include <alibabacloud/models/DescribePdnsAppKeyResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsAppKeyResponse.hpp>
#include <alibabacloud/models/DescribePdnsAppKeysRequest.hpp>
#include <alibabacloud/models/DescribePdnsAppKeysResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsAppKeysResponse.hpp>
#include <alibabacloud/models/DescribePdnsOperateLogsRequest.hpp>
#include <alibabacloud/models/DescribePdnsOperateLogsResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsOperateLogsResponse.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticRequest.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticResponse.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticsRequest.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsRequestStatisticsResponse.hpp>
#include <alibabacloud/models/DescribePdnsThreatLogsRequest.hpp>
#include <alibabacloud/models/DescribePdnsThreatLogsResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsThreatLogsResponse.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticRequest.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticResponse.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticsRequest.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsThreatStatisticsResponse.hpp>
#include <alibabacloud/models/DescribePdnsUdpIpSegmentsRequest.hpp>
#include <alibabacloud/models/DescribePdnsUdpIpSegmentsResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsUdpIpSegmentsResponse.hpp>
#include <alibabacloud/models/DescribePdnsUserInfoRequest.hpp>
#include <alibabacloud/models/DescribePdnsUserInfoResponseBody.hpp>
#include <alibabacloud/models/DescribePdnsUserInfoResponse.hpp>
#include <alibabacloud/models/DescribeRecordLogsRequest.hpp>
#include <alibabacloud/models/DescribeRecordLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordLogsResponse.hpp>
#include <alibabacloud/models/DescribeRecordResolveStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeRecordResolveStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordResolveStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordStatisticsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeRecursionRecordRequest.hpp>
#include <alibabacloud/models/DescribeRecursionRecordResponseBody.hpp>
#include <alibabacloud/models/DescribeRecursionRecordResponse.hpp>
#include <alibabacloud/models/DescribeRecursionZoneRequest.hpp>
#include <alibabacloud/models/DescribeRecursionZoneResponseBody.hpp>
#include <alibabacloud/models/DescribeRecursionZoneResponse.hpp>
#include <alibabacloud/models/DescribeSubDomainRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSubDomainRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSubDomainRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSupportLinesRequest.hpp>
#include <alibabacloud/models/DescribeSupportLinesResponseBody.hpp>
#include <alibabacloud/models/DescribeSupportLinesResponse.hpp>
#include <alibabacloud/models/DescribeTagsRequest.hpp>
#include <alibabacloud/models/DescribeTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeTagsResponse.hpp>
#include <alibabacloud/models/DescribeTransferDomainsRequest.hpp>
#include <alibabacloud/models/DescribeTransferDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeTransferDomainsResponse.hpp>
#include <alibabacloud/models/ExecuteGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/ExecuteGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/ExecuteGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/GetMainDomainNameRequest.hpp>
#include <alibabacloud/models/GetMainDomainNameResponseBody.hpp>
#include <alibabacloud/models/GetMainDomainNameResponse.hpp>
#include <alibabacloud/models/GetTxtRecordForVerifyRequest.hpp>
#include <alibabacloud/models/GetTxtRecordForVerifyResponseBody.hpp>
#include <alibabacloud/models/GetTxtRecordForVerifyResponse.hpp>
#include <alibabacloud/models/ListCloudGtmAddressPoolsRequest.hpp>
#include <alibabacloud/models/ListCloudGtmAddressPoolsResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmAddressPoolsResponse.hpp>
#include <alibabacloud/models/ListCloudGtmAddressesRequest.hpp>
#include <alibabacloud/models/ListCloudGtmAddressesResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmAddressesResponse.hpp>
#include <alibabacloud/models/ListCloudGtmAlertLogsRequest.hpp>
#include <alibabacloud/models/ListCloudGtmAlertLogsResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmAlertLogsResponse.hpp>
#include <alibabacloud/models/ListCloudGtmAvailableAlertGroupsRequest.hpp>
#include <alibabacloud/models/ListCloudGtmAvailableAlertGroupsResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmAvailableAlertGroupsResponse.hpp>
#include <alibabacloud/models/ListCloudGtmInstanceConfigsRequest.hpp>
#include <alibabacloud/models/ListCloudGtmInstanceConfigsResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmInstanceConfigsResponse.hpp>
#include <alibabacloud/models/ListCloudGtmInstancesRequest.hpp>
#include <alibabacloud/models/ListCloudGtmInstancesResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmInstancesResponse.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorNodesRequest.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorNodesResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorNodesResponse.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorTemplatesRequest.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListCloudGtmMonitorTemplatesResponse.hpp>
#include <alibabacloud/models/ListRecursionRecordsRequest.hpp>
#include <alibabacloud/models/ListRecursionRecordsResponseBody.hpp>
#include <alibabacloud/models/ListRecursionRecordsResponse.hpp>
#include <alibabacloud/models/ListRecursionZonesRequest.hpp>
#include <alibabacloud/models/ListRecursionZonesResponseBody.hpp>
#include <alibabacloud/models/ListRecursionZonesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyHichinaDomainDnsRequest.hpp>
#include <alibabacloud/models/ModifyHichinaDomainDnsResponseBody.hpp>
#include <alibabacloud/models/ModifyHichinaDomainDnsResponse.hpp>
#include <alibabacloud/models/MoveDomainResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveDomainResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveDomainResourceGroupResponse.hpp>
#include <alibabacloud/models/MoveGtmResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveGtmResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveGtmResourceGroupResponse.hpp>
#include <alibabacloud/models/OperateBatchDomainRequest.hpp>
#include <alibabacloud/models/OperateBatchDomainResponseBody.hpp>
#include <alibabacloud/models/OperateBatchDomainResponse.hpp>
#include <alibabacloud/models/PausePdnsServiceRequest.hpp>
#include <alibabacloud/models/PausePdnsServiceResponseBody.hpp>
#include <alibabacloud/models/PausePdnsServiceResponse.hpp>
#include <alibabacloud/models/PreviewGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/PreviewGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/PreviewGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/RemovePdnsAppKeyRequest.hpp>
#include <alibabacloud/models/RemovePdnsAppKeyResponseBody.hpp>
#include <alibabacloud/models/RemovePdnsAppKeyResponse.hpp>
#include <alibabacloud/models/RemovePdnsUdpIpSegmentRequest.hpp>
#include <alibabacloud/models/RemovePdnsUdpIpSegmentResponseBody.hpp>
#include <alibabacloud/models/RemovePdnsUdpIpSegmentResponse.hpp>
#include <alibabacloud/models/RemoveRspDomainServerHoldStatusForGatewayRequest.hpp>
#include <alibabacloud/models/RemoveRspDomainServerHoldStatusForGatewayResponseBody.hpp>
#include <alibabacloud/models/RemoveRspDomainServerHoldStatusForGatewayResponse.hpp>
#include <alibabacloud/models/ReplaceCloudGtmAddressPoolAddressRequest.hpp>
#include <alibabacloud/models/ReplaceCloudGtmAddressPoolAddressShrinkRequest.hpp>
#include <alibabacloud/models/ReplaceCloudGtmAddressPoolAddressResponseBody.hpp>
#include <alibabacloud/models/ReplaceCloudGtmAddressPoolAddressResponse.hpp>
#include <alibabacloud/models/ReplaceCloudGtmInstanceConfigAddressPoolRequest.hpp>
#include <alibabacloud/models/ReplaceCloudGtmInstanceConfigAddressPoolShrinkRequest.hpp>
#include <alibabacloud/models/ReplaceCloudGtmInstanceConfigAddressPoolResponseBody.hpp>
#include <alibabacloud/models/ReplaceCloudGtmInstanceConfigAddressPoolResponse.hpp>
#include <alibabacloud/models/ResumePdnsServiceRequest.hpp>
#include <alibabacloud/models/ResumePdnsServiceResponseBody.hpp>
#include <alibabacloud/models/ResumePdnsServiceResponse.hpp>
#include <alibabacloud/models/RetrieveDomainRequest.hpp>
#include <alibabacloud/models/RetrieveDomainResponseBody.hpp>
#include <alibabacloud/models/RetrieveDomainResponse.hpp>
#include <alibabacloud/models/RollbackGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/RollbackGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/RollbackGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressPoolsRequest.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressPoolsResponseBody.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressPoolsResponse.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressesRequest.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressesResponseBody.hpp>
#include <alibabacloud/models/SearchCloudGtmAddressesResponse.hpp>
#include <alibabacloud/models/SearchCloudGtmInstanceConfigsRequest.hpp>
#include <alibabacloud/models/SearchCloudGtmInstanceConfigsResponseBody.hpp>
#include <alibabacloud/models/SearchCloudGtmInstanceConfigsResponse.hpp>
#include <alibabacloud/models/SearchCloudGtmInstancesRequest.hpp>
#include <alibabacloud/models/SearchCloudGtmInstancesResponseBody.hpp>
#include <alibabacloud/models/SearchCloudGtmInstancesResponse.hpp>
#include <alibabacloud/models/SearchCloudGtmMonitorTemplatesRequest.hpp>
#include <alibabacloud/models/SearchCloudGtmMonitorTemplatesResponseBody.hpp>
#include <alibabacloud/models/SearchCloudGtmMonitorTemplatesResponse.hpp>
#include <alibabacloud/models/SearchRecursionRecordsRequest.hpp>
#include <alibabacloud/models/SearchRecursionRecordsResponseBody.hpp>
#include <alibabacloud/models/SearchRecursionRecordsResponse.hpp>
#include <alibabacloud/models/SearchRecursionZonesRequest.hpp>
#include <alibabacloud/models/SearchRecursionZonesShrinkRequest.hpp>
#include <alibabacloud/models/SearchRecursionZonesResponseBody.hpp>
#include <alibabacloud/models/SearchRecursionZonesResponse.hpp>
#include <alibabacloud/models/SetDnsslbStatusRequest.hpp>
#include <alibabacloud/models/SetDnsslbStatusResponseBody.hpp>
#include <alibabacloud/models/SetDnsslbStatusResponse.hpp>
#include <alibabacloud/models/SetDnsGtmAccessModeRequest.hpp>
#include <alibabacloud/models/SetDnsGtmAccessModeResponseBody.hpp>
#include <alibabacloud/models/SetDnsGtmAccessModeResponse.hpp>
#include <alibabacloud/models/SetDnsGtmMonitorStatusRequest.hpp>
#include <alibabacloud/models/SetDnsGtmMonitorStatusResponseBody.hpp>
#include <alibabacloud/models/SetDnsGtmMonitorStatusResponse.hpp>
#include <alibabacloud/models/SetDomainDnssecStatusRequest.hpp>
#include <alibabacloud/models/SetDomainDnssecStatusResponseBody.hpp>
#include <alibabacloud/models/SetDomainDnssecStatusResponse.hpp>
#include <alibabacloud/models/SetDomainRecordStatusRequest.hpp>
#include <alibabacloud/models/SetDomainRecordStatusResponseBody.hpp>
#include <alibabacloud/models/SetDomainRecordStatusResponse.hpp>
#include <alibabacloud/models/SetGtmAccessModeRequest.hpp>
#include <alibabacloud/models/SetGtmAccessModeResponseBody.hpp>
#include <alibabacloud/models/SetGtmAccessModeResponse.hpp>
#include <alibabacloud/models/SetGtmMonitorStatusRequest.hpp>
#include <alibabacloud/models/SetGtmMonitorStatusResponseBody.hpp>
#include <alibabacloud/models/SetGtmMonitorStatusResponse.hpp>
#include <alibabacloud/models/SubmitIspFlushCacheTaskRequest.hpp>
#include <alibabacloud/models/SubmitIspFlushCacheTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitIspFlushCacheTaskResponse.hpp>
#include <alibabacloud/models/SwitchDnsGtmInstanceStrategyModeRequest.hpp>
#include <alibabacloud/models/SwitchDnsGtmInstanceStrategyModeResponseBody.hpp>
#include <alibabacloud/models/SwitchDnsGtmInstanceStrategyModeResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TransferDomainRequest.hpp>
#include <alibabacloud/models/TransferDomainResponseBody.hpp>
#include <alibabacloud/models/TransferDomainResponse.hpp>
#include <alibabacloud/models/UnbindInstanceDomainsRequest.hpp>
#include <alibabacloud/models/UnbindInstanceDomainsResponseBody.hpp>
#include <alibabacloud/models/UnbindInstanceDomainsResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAppKeyStateRequest.hpp>
#include <alibabacloud/models/UpdateAppKeyStateResponseBody.hpp>
#include <alibabacloud/models/UpdateAppKeyStateResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressEnableStatusRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressEnableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressEnableStatusResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressManualAvailableStatusRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressManualAvailableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressManualAvailableStatusResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolBasicConfigRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolBasicConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolBasicConfigResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolEnableStatusRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolEnableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolEnableStatusResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolLbStrategyRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolLbStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolLbStrategyResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolRemarkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressPoolRemarkResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressRemarkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmAddressRemarkResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmGlobalAlertRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmGlobalAlertShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmGlobalAlertResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmGlobalAlertResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigAlertRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigAlertShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigAlertResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigAlertResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigBasicRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigBasicResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigBasicResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigEnableStatusRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigEnableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigEnableStatusResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigLbStrategyRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigLbStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigLbStrategyResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigRemarkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceConfigRemarkResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceNameRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceNameResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmInstanceNameResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateResponse.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateRemarkRequest.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudGtmMonitorTemplateRemarkResponse.hpp>
#include <alibabacloud/models/UpdateCustomLineRequest.hpp>
#include <alibabacloud/models/UpdateCustomLineResponseBody.hpp>
#include <alibabacloud/models/UpdateCustomLineResponse.hpp>
#include <alibabacloud/models/UpdateDnsslbWeightRequest.hpp>
#include <alibabacloud/models/UpdateDnsslbWeightResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsslbWeightResponse.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainRequest.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainResponse.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainRemarkRequest.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsCacheDomainRemarkResponse.hpp>
#include <alibabacloud/models/UpdateDnsGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/UpdateDnsGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/UpdateDnsGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/UpdateDnsGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/UpdateDnsGtmInstanceGlobalConfigRequest.hpp>
#include <alibabacloud/models/UpdateDnsGtmInstanceGlobalConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsGtmInstanceGlobalConfigResponse.hpp>
#include <alibabacloud/models/UpdateDnsGtmMonitorRequest.hpp>
#include <alibabacloud/models/UpdateDnsGtmMonitorResponseBody.hpp>
#include <alibabacloud/models/UpdateDnsGtmMonitorResponse.hpp>
#include <alibabacloud/models/UpdateDomainGroupRequest.hpp>
#include <alibabacloud/models/UpdateDomainGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateDomainGroupResponse.hpp>
#include <alibabacloud/models/UpdateDomainRecordRequest.hpp>
#include <alibabacloud/models/UpdateDomainRecordResponseBody.hpp>
#include <alibabacloud/models/UpdateDomainRecordResponse.hpp>
#include <alibabacloud/models/UpdateDomainRecordRemarkRequest.hpp>
#include <alibabacloud/models/UpdateDomainRecordRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateDomainRecordRemarkResponse.hpp>
#include <alibabacloud/models/UpdateDomainRemarkRequest.hpp>
#include <alibabacloud/models/UpdateDomainRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateDomainRemarkResponse.hpp>
#include <alibabacloud/models/UpdateGtmAccessStrategyRequest.hpp>
#include <alibabacloud/models/UpdateGtmAccessStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateGtmAccessStrategyResponse.hpp>
#include <alibabacloud/models/UpdateGtmAddressPoolRequest.hpp>
#include <alibabacloud/models/UpdateGtmAddressPoolResponseBody.hpp>
#include <alibabacloud/models/UpdateGtmAddressPoolResponse.hpp>
#include <alibabacloud/models/UpdateGtmInstanceGlobalConfigRequest.hpp>
#include <alibabacloud/models/UpdateGtmInstanceGlobalConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateGtmInstanceGlobalConfigResponse.hpp>
#include <alibabacloud/models/UpdateGtmMonitorRequest.hpp>
#include <alibabacloud/models/UpdateGtmMonitorResponseBody.hpp>
#include <alibabacloud/models/UpdateGtmMonitorResponse.hpp>
#include <alibabacloud/models/UpdateGtmRecoveryPlanRequest.hpp>
#include <alibabacloud/models/UpdateGtmRecoveryPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateGtmRecoveryPlanResponse.hpp>
#include <alibabacloud/models/UpdateIspFlushCacheInstanceConfigRequest.hpp>
#include <alibabacloud/models/UpdateIspFlushCacheInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateIspFlushCacheInstanceConfigResponse.hpp>
#include <alibabacloud/models/UpdateRecursionRecordRequest.hpp>
#include <alibabacloud/models/UpdateRecursionRecordResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionRecordResponse.hpp>
#include <alibabacloud/models/UpdateRecursionRecordEnableStatusRequest.hpp>
#include <alibabacloud/models/UpdateRecursionRecordEnableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionRecordEnableStatusResponse.hpp>
#include <alibabacloud/models/UpdateRecursionRecordRemarkRequest.hpp>
#include <alibabacloud/models/UpdateRecursionRecordRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionRecordRemarkResponse.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightRequest.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightResponse.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightEnableStatusRequest.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightEnableStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionRecordWeightEnableStatusResponse.hpp>
#include <alibabacloud/models/UpdateRecursionZoneEffectiveScopeRequest.hpp>
#include <alibabacloud/models/UpdateRecursionZoneEffectiveScopeShrinkRequest.hpp>
#include <alibabacloud/models/UpdateRecursionZoneEffectiveScopeResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionZoneEffectiveScopeResponse.hpp>
#include <alibabacloud/models/UpdateRecursionZoneProxyPatternRequest.hpp>
#include <alibabacloud/models/UpdateRecursionZoneProxyPatternResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionZoneProxyPatternResponse.hpp>
#include <alibabacloud/models/UpdateRecursionZoneRemarkRequest.hpp>
#include <alibabacloud/models/UpdateRecursionZoneRemarkResponseBody.hpp>
#include <alibabacloud/models/UpdateRecursionZoneRemarkResponse.hpp>
#include <alibabacloud/models/UpdateRspDomainServerProhibitStatusForGatewayRequest.hpp>
#include <alibabacloud/models/UpdateRspDomainServerProhibitStatusForGatewayResponseBody.hpp>
#include <alibabacloud/models/UpdateRspDomainServerProhibitStatusForGatewayResponse.hpp>
#include <alibabacloud/models/ValidateDnsGtmCnameRrCanUseRequest.hpp>
#include <alibabacloud/models/ValidateDnsGtmCnameRrCanUseResponseBody.hpp>
#include <alibabacloud/models/ValidateDnsGtmCnameRrCanUseResponse.hpp>
#include <alibabacloud/models/ValidatePdnsUdpIpSegmentRequest.hpp>
#include <alibabacloud/models/ValidatePdnsUdpIpSegmentResponseBody.hpp>
#include <alibabacloud/models/ValidatePdnsUdpIpSegmentResponse.hpp>

#endif
