// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MARKET20151101MODEL_HPP_
#define ALIBABACLOUD_MARKET20151101MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ActivateLicenseRequest.hpp>
#include <alibabacloud/models/ActivateLicenseResponseBody.hpp>
#include <alibabacloud/models/ActivateLicenseResponse.hpp>
#include <alibabacloud/models/AutoRenewInstanceRequest.hpp>
#include <alibabacloud/models/AutoRenewInstanceResponseBody.hpp>
#include <alibabacloud/models/AutoRenewInstanceResponse.hpp>
#include <alibabacloud/models/ConfirmNotificationRequest.hpp>
#include <alibabacloud/models/ConfirmNotificationResponseBody.hpp>
#include <alibabacloud/models/ConfirmNotificationResponse.hpp>
#include <alibabacloud/models/CreateOrderRequest.hpp>
#include <alibabacloud/models/CreateOrderResponseBody.hpp>
#include <alibabacloud/models/CreateOrderResponse.hpp>
#include <alibabacloud/models/CrossAccountVerifyTokenRequest.hpp>
#include <alibabacloud/models/CrossAccountVerifyTokenResponseBody.hpp>
#include <alibabacloud/models/CrossAccountVerifyTokenResponse.hpp>
#include <alibabacloud/models/DescribeApiMeteringRequest.hpp>
#include <alibabacloud/models/DescribeApiMeteringResponseBody.hpp>
#include <alibabacloud/models/DescribeApiMeteringResponse.hpp>
#include <alibabacloud/models/DescribeCurrentNodeInfoRequest.hpp>
#include <alibabacloud/models/DescribeCurrentNodeInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeCurrentNodeInfoResponse.hpp>
#include <alibabacloud/models/DescribeDistributionProductsRequest.hpp>
#include <alibabacloud/models/DescribeDistributionProductsResponseBody.hpp>
#include <alibabacloud/models/DescribeDistributionProductsResponse.hpp>
#include <alibabacloud/models/DescribeDistributionProductsLinkRequest.hpp>
#include <alibabacloud/models/DescribeDistributionProductsLinkShrinkRequest.hpp>
#include <alibabacloud/models/DescribeDistributionProductsLinkResponseBody.hpp>
#include <alibabacloud/models/DescribeDistributionProductsLinkResponse.hpp>
#include <alibabacloud/models/DescribeFailedNotificationsRequest.hpp>
#include <alibabacloud/models/DescribeFailedNotificationsResponseBody.hpp>
#include <alibabacloud/models/DescribeFailedNotificationsResponse.hpp>
#include <alibabacloud/models/DescribeImageInstanceForIsvRequest.hpp>
#include <alibabacloud/models/DescribeImageInstanceForIsvResponseBody.hpp>
#include <alibabacloud/models/DescribeImageInstanceForIsvResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRequest.hpp>
#include <alibabacloud/models/DescribeInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceResponse.hpp>
#include <alibabacloud/models/DescribeInstanceForIsvRequest.hpp>
#include <alibabacloud/models/DescribeInstanceForIsvResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceForIsvResponse.hpp>
#include <alibabacloud/models/DescribeInstancesRequest.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancesResponse.hpp>
#include <alibabacloud/models/DescribeInvoiceForIsvRequest.hpp>
#include <alibabacloud/models/DescribeInvoiceForIsvResponseBody.hpp>
#include <alibabacloud/models/DescribeInvoiceForIsvResponse.hpp>
#include <alibabacloud/models/DescribeLicenseRequest.hpp>
#include <alibabacloud/models/DescribeLicenseResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseResponse.hpp>
#include <alibabacloud/models/DescribeOrderRequest.hpp>
#include <alibabacloud/models/DescribeOrderResponseBody.hpp>
#include <alibabacloud/models/DescribeOrderResponse.hpp>
#include <alibabacloud/models/DescribeOrderForIsvRequest.hpp>
#include <alibabacloud/models/DescribeOrderForIsvResponseBody.hpp>
#include <alibabacloud/models/DescribeOrderForIsvResponse.hpp>
#include <alibabacloud/models/DescribePriceRequest.hpp>
#include <alibabacloud/models/DescribePriceResponseBody.hpp>
#include <alibabacloud/models/DescribePriceResponse.hpp>
#include <alibabacloud/models/DescribeProductRequest.hpp>
#include <alibabacloud/models/DescribeProductResponseBody.hpp>
#include <alibabacloud/models/DescribeProductResponse.hpp>
#include <alibabacloud/models/DescribeProductsRequest.hpp>
#include <alibabacloud/models/DescribeProductsResponseBody.hpp>
#include <alibabacloud/models/DescribeProductsResponse.hpp>
#include <alibabacloud/models/DescribeProjectAttachmentsRequest.hpp>
#include <alibabacloud/models/DescribeProjectAttachmentsResponseBody.hpp>
#include <alibabacloud/models/DescribeProjectAttachmentsResponse.hpp>
#include <alibabacloud/models/DescribeProjectInfoRequest.hpp>
#include <alibabacloud/models/DescribeProjectInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeProjectInfoResponse.hpp>
#include <alibabacloud/models/DescribeProjectMessagesRequest.hpp>
#include <alibabacloud/models/DescribeProjectMessagesResponseBody.hpp>
#include <alibabacloud/models/DescribeProjectMessagesResponse.hpp>
#include <alibabacloud/models/DescribeProjectNodesRequest.hpp>
#include <alibabacloud/models/DescribeProjectNodesResponseBody.hpp>
#include <alibabacloud/models/DescribeProjectNodesResponse.hpp>
#include <alibabacloud/models/DescribeProjectOperateLogsRequest.hpp>
#include <alibabacloud/models/DescribeProjectOperateLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeProjectOperateLogsResponse.hpp>
#include <alibabacloud/models/FinishCurrentProjectNodeRequest.hpp>
#include <alibabacloud/models/FinishCurrentProjectNodeResponseBody.hpp>
#include <alibabacloud/models/FinishCurrentProjectNodeResponse.hpp>
#include <alibabacloud/models/ModifyInvoiceForIsvRequest.hpp>
#include <alibabacloud/models/ModifyInvoiceForIsvResponseBody.hpp>
#include <alibabacloud/models/ModifyInvoiceForIsvResponse.hpp>
#include <alibabacloud/models/PauseProjectRequest.hpp>
#include <alibabacloud/models/PauseProjectResponseBody.hpp>
#include <alibabacloud/models/PauseProjectResponse.hpp>
#include <alibabacloud/models/PushMeteringDataRequest.hpp>
#include <alibabacloud/models/PushMeteringDataResponseBody.hpp>
#include <alibabacloud/models/PushMeteringDataResponse.hpp>
#include <alibabacloud/models/PushTimesUsageRequest.hpp>
#include <alibabacloud/models/PushTimesUsageResponseBody.hpp>
#include <alibabacloud/models/PushTimesUsageResponse.hpp>
#include <alibabacloud/models/ResumeProjectRequest.hpp>
#include <alibabacloud/models/ResumeProjectResponseBody.hpp>
#include <alibabacloud/models/ResumeProjectResponse.hpp>
#include <alibabacloud/models/RollbackCurrentProjectNodeRequest.hpp>
#include <alibabacloud/models/RollbackCurrentProjectNodeResponseBody.hpp>
#include <alibabacloud/models/RollbackCurrentProjectNodeResponse.hpp>

#endif
