// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SLB20140515MODEL_HPP_
#define ALIBABACLOUD_SLB20140515MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddAccessControlListEntryRequest.hpp>
#include <alibabacloud/models/AddAccessControlListEntryResponseBody.hpp>
#include <alibabacloud/models/AddAccessControlListEntryResponse.hpp>
#include <alibabacloud/models/AddBackendServersRequest.hpp>
#include <alibabacloud/models/AddBackendServersResponseBody.hpp>
#include <alibabacloud/models/AddBackendServersResponse.hpp>
#include <alibabacloud/models/AddListenerWhiteListItemRequest.hpp>
#include <alibabacloud/models/AddListenerWhiteListItemResponseBody.hpp>
#include <alibabacloud/models/AddListenerWhiteListItemResponse.hpp>
#include <alibabacloud/models/AddTagsRequest.hpp>
#include <alibabacloud/models/AddTagsResponseBody.hpp>
#include <alibabacloud/models/AddTagsResponse.hpp>
#include <alibabacloud/models/AddVServerGroupBackendServersRequest.hpp>
#include <alibabacloud/models/AddVServerGroupBackendServersResponseBody.hpp>
#include <alibabacloud/models/AddVServerGroupBackendServersResponse.hpp>
#include <alibabacloud/models/CreateAccessControlListRequest.hpp>
#include <alibabacloud/models/CreateAccessControlListResponseBody.hpp>
#include <alibabacloud/models/CreateAccessControlListResponse.hpp>
#include <alibabacloud/models/CreateDomainExtensionRequest.hpp>
#include <alibabacloud/models/CreateDomainExtensionResponseBody.hpp>
#include <alibabacloud/models/CreateDomainExtensionResponse.hpp>
#include <alibabacloud/models/CreateLoadBalancerRequest.hpp>
#include <alibabacloud/models/CreateLoadBalancerResponseBody.hpp>
#include <alibabacloud/models/CreateLoadBalancerResponse.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpListenerRequest.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpListenerResponseBody.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpListenerResponse.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpsListenerRequest.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpsListenerResponseBody.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpsListenerResponse.hpp>
#include <alibabacloud/models/CreateLoadBalancerTcpListenerRequest.hpp>
#include <alibabacloud/models/CreateLoadBalancerTcpListenerResponseBody.hpp>
#include <alibabacloud/models/CreateLoadBalancerTcpListenerResponse.hpp>
#include <alibabacloud/models/CreateLoadBalancerUdpListenerRequest.hpp>
#include <alibabacloud/models/CreateLoadBalancerUdpListenerResponseBody.hpp>
#include <alibabacloud/models/CreateLoadBalancerUdpListenerResponse.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupRequest.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupResponseBody.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupResponse.hpp>
#include <alibabacloud/models/CreateRulesRequest.hpp>
#include <alibabacloud/models/CreateRulesResponseBody.hpp>
#include <alibabacloud/models/CreateRulesResponse.hpp>
#include <alibabacloud/models/CreateTlsCipherPolicyRequest.hpp>
#include <alibabacloud/models/CreateTlsCipherPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateTlsCipherPolicyResponse.hpp>
#include <alibabacloud/models/CreateVServerGroupRequest.hpp>
#include <alibabacloud/models/CreateVServerGroupResponseBody.hpp>
#include <alibabacloud/models/CreateVServerGroupResponse.hpp>
#include <alibabacloud/models/DeleteAccessControlListRequest.hpp>
#include <alibabacloud/models/DeleteAccessControlListResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessControlListResponse.hpp>
#include <alibabacloud/models/DeleteAccessLogsDownloadAttributeRequest.hpp>
#include <alibabacloud/models/DeleteAccessLogsDownloadAttributeResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessLogsDownloadAttributeResponse.hpp>
#include <alibabacloud/models/DeleteCaCertificateRequest.hpp>
#include <alibabacloud/models/DeleteCaCertificateResponseBody.hpp>
#include <alibabacloud/models/DeleteCaCertificateResponse.hpp>
#include <alibabacloud/models/DeleteDomainExtensionRequest.hpp>
#include <alibabacloud/models/DeleteDomainExtensionResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainExtensionResponse.hpp>
#include <alibabacloud/models/DeleteLoadBalancerRequest.hpp>
#include <alibabacloud/models/DeleteLoadBalancerResponseBody.hpp>
#include <alibabacloud/models/DeleteLoadBalancerResponse.hpp>
#include <alibabacloud/models/DeleteLoadBalancerListenerRequest.hpp>
#include <alibabacloud/models/DeleteLoadBalancerListenerResponseBody.hpp>
#include <alibabacloud/models/DeleteLoadBalancerListenerResponse.hpp>
#include <alibabacloud/models/DeleteMasterSlaveServerGroupRequest.hpp>
#include <alibabacloud/models/DeleteMasterSlaveServerGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteMasterSlaveServerGroupResponse.hpp>
#include <alibabacloud/models/DeleteRulesRequest.hpp>
#include <alibabacloud/models/DeleteRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteRulesResponse.hpp>
#include <alibabacloud/models/DeleteServerCertificateRequest.hpp>
#include <alibabacloud/models/DeleteServerCertificateResponseBody.hpp>
#include <alibabacloud/models/DeleteServerCertificateResponse.hpp>
#include <alibabacloud/models/DeleteTlsCipherPolicyRequest.hpp>
#include <alibabacloud/models/DeleteTlsCipherPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteTlsCipherPolicyResponse.hpp>
#include <alibabacloud/models/DeleteVServerGroupRequest.hpp>
#include <alibabacloud/models/DeleteVServerGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteVServerGroupResponse.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAccessControlListsRequest.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponse.hpp>
#include <alibabacloud/models/DescribeAccessLogsDownloadAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAccessLogsDownloadAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessLogsDownloadAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAvailableResourceRequest.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponse.hpp>
#include <alibabacloud/models/DescribeCaCertificatesRequest.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponseBody.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponse.hpp>
#include <alibabacloud/models/DescribeDomainExtensionAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDomainExtensionAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainExtensionAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDomainExtensionsRequest.hpp>
#include <alibabacloud/models/DescribeDomainExtensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainExtensionsResponse.hpp>
#include <alibabacloud/models/DescribeHealthStatusRequest.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponse.hpp>
#include <alibabacloud/models/DescribeHighDefinationMonitorRequest.hpp>
#include <alibabacloud/models/DescribeHighDefinationMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeHighDefinationMonitorResponse.hpp>
#include <alibabacloud/models/DescribeListenerAccessControlAttributeRequest.hpp>
#include <alibabacloud/models/DescribeListenerAccessControlAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeListenerAccessControlAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLoadBalancersRequest.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponse.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeRequest.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponse.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsRequest.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRuleAttributeRequest.hpp>
#include <alibabacloud/models/DescribeRuleAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleAttributeResponse.hpp>
#include <alibabacloud/models/DescribeRulesRequest.hpp>
#include <alibabacloud/models/DescribeRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeRulesResponse.hpp>
#include <alibabacloud/models/DescribeServerCertificatesRequest.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBody.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponse.hpp>
#include <alibabacloud/models/DescribeTagsRequest.hpp>
#include <alibabacloud/models/DescribeTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeTagsResponse.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeRequest.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponse.hpp>
#include <alibabacloud/models/DescribeVServerGroupsRequest.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/EnableHighDefinationMonitorRequest.hpp>
#include <alibabacloud/models/EnableHighDefinationMonitorResponseBody.hpp>
#include <alibabacloud/models/EnableHighDefinationMonitorResponse.hpp>
#include <alibabacloud/models/ListTlsCipherPoliciesRequest.hpp>
#include <alibabacloud/models/ListTlsCipherPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListTlsCipherPoliciesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyHighDefinationMonitorRequest.hpp>
#include <alibabacloud/models/ModifyHighDefinationMonitorResponseBody.hpp>
#include <alibabacloud/models/ModifyHighDefinationMonitorResponse.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceChargeTypeRequest.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceChargeTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceChargeTypeResponse.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceSpecRequest.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInstanceSpecResponse.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInternetSpecRequest.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInternetSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyLoadBalancerInternetSpecResponse.hpp>
#include <alibabacloud/models/ModifyLoadBalancerPayTypeRequest.hpp>
#include <alibabacloud/models/ModifyLoadBalancerPayTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyLoadBalancerPayTypeResponse.hpp>
#include <alibabacloud/models/ModifyVServerGroupBackendServersRequest.hpp>
#include <alibabacloud/models/ModifyVServerGroupBackendServersResponseBody.hpp>
#include <alibabacloud/models/ModifyVServerGroupBackendServersResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryRequest.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryResponseBody.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryResponse.hpp>
#include <alibabacloud/models/RemoveBackendServersRequest.hpp>
#include <alibabacloud/models/RemoveBackendServersResponseBody.hpp>
#include <alibabacloud/models/RemoveBackendServersResponse.hpp>
#include <alibabacloud/models/RemoveListenerWhiteListItemRequest.hpp>
#include <alibabacloud/models/RemoveListenerWhiteListItemResponseBody.hpp>
#include <alibabacloud/models/RemoveListenerWhiteListItemResponse.hpp>
#include <alibabacloud/models/RemoveTagsRequest.hpp>
#include <alibabacloud/models/RemoveTagsResponseBody.hpp>
#include <alibabacloud/models/RemoveTagsResponse.hpp>
#include <alibabacloud/models/RemoveVServerGroupBackendServersRequest.hpp>
#include <alibabacloud/models/RemoveVServerGroupBackendServersResponseBody.hpp>
#include <alibabacloud/models/RemoveVServerGroupBackendServersResponse.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeRequest.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeResponseBody.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeResponse.hpp>
#include <alibabacloud/models/SetAccessLogsDownloadAttributeRequest.hpp>
#include <alibabacloud/models/SetAccessLogsDownloadAttributeResponseBody.hpp>
#include <alibabacloud/models/SetAccessLogsDownloadAttributeResponse.hpp>
#include <alibabacloud/models/SetBackendServersRequest.hpp>
#include <alibabacloud/models/SetBackendServersResponseBody.hpp>
#include <alibabacloud/models/SetBackendServersResponse.hpp>
#include <alibabacloud/models/SetCaCertificateNameRequest.hpp>
#include <alibabacloud/models/SetCaCertificateNameResponseBody.hpp>
#include <alibabacloud/models/SetCaCertificateNameResponse.hpp>
#include <alibabacloud/models/SetDomainExtensionAttributeRequest.hpp>
#include <alibabacloud/models/SetDomainExtensionAttributeResponseBody.hpp>
#include <alibabacloud/models/SetDomainExtensionAttributeResponse.hpp>
#include <alibabacloud/models/SetListenerAccessControlStatusRequest.hpp>
#include <alibabacloud/models/SetListenerAccessControlStatusResponseBody.hpp>
#include <alibabacloud/models/SetListenerAccessControlStatusResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerDeleteProtectionRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerDeleteProtectionResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerDeleteProtectionResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpListenerAttributeRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpListenerAttributeResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpsListenerAttributeRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpsListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerHttpsListenerAttributeResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerModificationProtectionRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerModificationProtectionResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerModificationProtectionResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerNameRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerNameResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerNameResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerStatusRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerStatusResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerStatusResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerTcpListenerAttributeRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerTcpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerTcpListenerAttributeResponse.hpp>
#include <alibabacloud/models/SetLoadBalancerUdpListenerAttributeRequest.hpp>
#include <alibabacloud/models/SetLoadBalancerUdpListenerAttributeResponseBody.hpp>
#include <alibabacloud/models/SetLoadBalancerUdpListenerAttributeResponse.hpp>
#include <alibabacloud/models/SetRuleRequest.hpp>
#include <alibabacloud/models/SetRuleResponseBody.hpp>
#include <alibabacloud/models/SetRuleResponse.hpp>
#include <alibabacloud/models/SetServerCertificateNameRequest.hpp>
#include <alibabacloud/models/SetServerCertificateNameResponseBody.hpp>
#include <alibabacloud/models/SetServerCertificateNameResponse.hpp>
#include <alibabacloud/models/SetTlsCipherPolicyAttributeRequest.hpp>
#include <alibabacloud/models/SetTlsCipherPolicyAttributeResponseBody.hpp>
#include <alibabacloud/models/SetTlsCipherPolicyAttributeResponse.hpp>
#include <alibabacloud/models/SetVServerGroupAttributeRequest.hpp>
#include <alibabacloud/models/SetVServerGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/SetVServerGroupAttributeResponse.hpp>
#include <alibabacloud/models/StartLoadBalancerListenerRequest.hpp>
#include <alibabacloud/models/StartLoadBalancerListenerResponseBody.hpp>
#include <alibabacloud/models/StartLoadBalancerListenerResponse.hpp>
#include <alibabacloud/models/StopLoadBalancerListenerRequest.hpp>
#include <alibabacloud/models/StopLoadBalancerListenerResponseBody.hpp>
#include <alibabacloud/models/StopLoadBalancerListenerResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UploadCaCertificateRequest.hpp>
#include <alibabacloud/models/UploadCaCertificateResponseBody.hpp>
#include <alibabacloud/models/UploadCaCertificateResponse.hpp>
#include <alibabacloud/models/UploadServerCertificateRequest.hpp>
#include <alibabacloud/models/UploadServerCertificateResponseBody.hpp>
#include <alibabacloud/models/UploadServerCertificateResponse.hpp>
#include <alibabacloud/models/AddBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/AddBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/AddVServerGroupBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/AddVServerGroupBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/CreateAccessControlListRequestTag.hpp>
#include <alibabacloud/models/CreateLoadBalancerRequestTag.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpListenerRequestTag.hpp>
#include <alibabacloud/models/CreateLoadBalancerHttpsListenerRequestTag.hpp>
#include <alibabacloud/models/CreateLoadBalancerTcpListenerRequestTag.hpp>
#include <alibabacloud/models/CreateLoadBalancerUdpListenerRequestTag.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupRequestTag.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupResponseBodyMasterSlaveBackendServersMasterSlaveBackendServer.hpp>
#include <alibabacloud/models/CreateMasterSlaveServerGroupResponseBodyMasterSlaveBackendServers.hpp>
#include <alibabacloud/models/CreateRulesResponseBodyRulesRule.hpp>
#include <alibabacloud/models/CreateRulesResponseBodyRules.hpp>
#include <alibabacloud/models/CreateVServerGroupRequestTag.hpp>
#include <alibabacloud/models/CreateVServerGroupResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/CreateVServerGroupResponseBodyBackendServers.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyAclEntrysAclEntry.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyAclEntrys.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyRelatedListenersRelatedListener.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyRelatedListeners.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeAccessControlListsRequestTag.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAclsAclTagsTag.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAclsAclTags.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAclsAcl.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAcls.hpp>
#include <alibabacloud/models/DescribeAccessLogsDownloadAttributeResponseBodyLogsDownloadAttributesLogsDownloadAttribute.hpp>
#include <alibabacloud/models/DescribeAccessLogsDownloadAttributeResponseBodyLogsDownloadAttributes.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableResourcesAvailableResourceSupportResourcesSupportResource.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableResourcesAvailableResourceSupportResources.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableResourcesAvailableResource.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableResources.hpp>
#include <alibabacloud/models/DescribeCaCertificatesRequestTag.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponseBodyCaCertificatesCaCertificateTagsTag.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponseBodyCaCertificatesCaCertificateTags.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponseBodyCaCertificatesCaCertificate.hpp>
#include <alibabacloud/models/DescribeCaCertificatesResponseBodyCaCertificates.hpp>
#include <alibabacloud/models/DescribeDomainExtensionsResponseBodyDomainExtensionsDomainExtension.hpp>
#include <alibabacloud/models/DescribeDomainExtensionsResponseBodyDomainExtensions.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/DescribeHealthStatusResponseBodyBackendServers.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyBackendServers.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyListenerPorts.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyListenerPortsAndProtocalListenerPortAndProtocal.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyListenerPortsAndProtocal.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyListenerPortsAndProtocolListenerPortAndProtocol.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyListenerPortsAndProtocol.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBodyAclIds.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBodyRulesRule.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpListenerAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyAclIds.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyDomainExtensionsDomainExtension.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyDomainExtensions.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyRulesRule.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerHttpsListenerAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersRequestTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListenersHttpListenerConfig.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListenersHttpsListenerConfig.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListenersTcpListenerConfig.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListenersTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListenersUdpListenerConfig.hpp>
#include <alibabacloud/models/DescribeLoadBalancerListenersResponseBodyListeners.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeResponseBodyAclIds.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerTcpListenerAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeResponseBodyAclIds.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancerUdpListenerAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancersRequestTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponseBodyLoadBalancersLoadBalancerTagsTag.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponseBodyLoadBalancersLoadBalancerTags.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponseBodyLoadBalancersLoadBalancer.hpp>
#include <alibabacloud/models/DescribeLoadBalancersResponseBodyLoadBalancers.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponseBodyMasterSlaveBackendServersMasterSlaveBackendServer.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponseBodyMasterSlaveBackendServers.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsRequestTag.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroupAssociatedObjectsListenersListener.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroupAssociatedObjectsListeners.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroupAssociatedObjects.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroupTagsTag.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroupTags.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroupsMasterSlaveServerGroup.hpp>
#include <alibabacloud/models/DescribeMasterSlaveServerGroupsResponseBodyMasterSlaveServerGroups.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeRulesResponseBodyRulesRule.hpp>
#include <alibabacloud/models/DescribeRulesResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeServerCertificatesRequestTag.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBodyServerCertificatesServerCertificateSubjectAlternativeNames.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBodyServerCertificatesServerCertificateTagsTag.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBodyServerCertificatesServerCertificateTags.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBodyServerCertificatesServerCertificate.hpp>
#include <alibabacloud/models/DescribeServerCertificatesResponseBodyServerCertificates.hpp>
#include <alibabacloud/models/DescribeTagsResponseBodyTagSetsTagSet.hpp>
#include <alibabacloud/models/DescribeTagsResponseBodyTagSets.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponseBodyBackendServers.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponseBodyTagsTag.hpp>
#include <alibabacloud/models/DescribeVServerGroupAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeVServerGroupsRequestTag.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupAssociatedObjectsListenersListener.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupAssociatedObjectsListeners.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupAssociatedObjectsRulesRule.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupAssociatedObjectsRules.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupAssociatedObjects.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupTagsTag.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroupTags.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroupsVServerGroup.hpp>
#include <alibabacloud/models/DescribeVServerGroupsResponseBodyVServerGroups.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZonesZoneSlaveZonesSlaveZone.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZonesZoneSlaveZones.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZonesZone.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZones.hpp>
#include <alibabacloud/models/ListTlsCipherPoliciesResponseBodyTlsCipherPoliciesRelateListeners.hpp>
#include <alibabacloud/models/ListTlsCipherPoliciesResponseBodyTlsCipherPolicies.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyVServerGroupBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/ModifyVServerGroupBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/RemoveBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/RemoveBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/RemoveVServerGroupBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/RemoveVServerGroupBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/SetBackendServersResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/SetBackendServersResponseBodyBackendServers.hpp>
#include <alibabacloud/models/SetVServerGroupAttributeResponseBodyBackendServersBackendServer.hpp>
#include <alibabacloud/models/SetVServerGroupAttributeResponseBodyBackendServers.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/UploadCaCertificateRequestTag.hpp>
#include <alibabacloud/models/UploadServerCertificateRequestTag.hpp>
#include <alibabacloud/models/UploadServerCertificateResponseBodySubjectAlternativeNames.hpp>

#endif
