// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DELETECHECKITEMRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DELETECHECKITEMRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/DeleteCheckItemResponseBodyCheckItems.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class DeleteCheckItemResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DeleteCheckItemResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(CheckItems, checkItems_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, DeleteCheckItemResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(CheckItems, checkItems_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    DeleteCheckItemResponseBody() = default ;
    DeleteCheckItemResponseBody(const DeleteCheckItemResponseBody &) = default ;
    DeleteCheckItemResponseBody(DeleteCheckItemResponseBody &&) = default ;
    DeleteCheckItemResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DeleteCheckItemResponseBody() = default ;
    DeleteCheckItemResponseBody& operator=(const DeleteCheckItemResponseBody &) = default ;
    DeleteCheckItemResponseBody& operator=(DeleteCheckItemResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->checkItems_ == nullptr
        && return this->requestId_ == nullptr; };
    // checkItems Field Functions 
    bool hasCheckItems() const { return this->checkItems_ != nullptr;};
    void deleteCheckItems() { this->checkItems_ = nullptr;};
    inline const vector<DeleteCheckItemResponseBodyCheckItems> & checkItems() const { DARABONBA_PTR_GET_CONST(checkItems_, vector<DeleteCheckItemResponseBodyCheckItems>) };
    inline vector<DeleteCheckItemResponseBodyCheckItems> checkItems() { DARABONBA_PTR_GET(checkItems_, vector<DeleteCheckItemResponseBodyCheckItems>) };
    inline DeleteCheckItemResponseBody& setCheckItems(const vector<DeleteCheckItemResponseBodyCheckItems> & checkItems) { DARABONBA_PTR_SET_VALUE(checkItems_, checkItems) };
    inline DeleteCheckItemResponseBody& setCheckItems(vector<DeleteCheckItemResponseBodyCheckItems> && checkItems) { DARABONBA_PTR_SET_RVALUE(checkItems_, checkItems) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DeleteCheckItemResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // List of deleted custom check items.
    std::shared_ptr<vector<DeleteCheckItemResponseBodyCheckItems>> checkItems_ = nullptr;
    // The ID of the current request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
