// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBESOARSTRATEGYTASKPARAMSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBESOARSTRATEGYTASKPARAMSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DescribeSoarStrategyTaskParamsResponseBodyTaskDetail.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class DescribeSoarStrategyTaskParamsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeSoarStrategyTaskParamsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(TaskDetail, taskDetail_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeSoarStrategyTaskParamsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(TaskDetail, taskDetail_);
    };
    DescribeSoarStrategyTaskParamsResponseBody() = default ;
    DescribeSoarStrategyTaskParamsResponseBody(const DescribeSoarStrategyTaskParamsResponseBody &) = default ;
    DescribeSoarStrategyTaskParamsResponseBody(DescribeSoarStrategyTaskParamsResponseBody &&) = default ;
    DescribeSoarStrategyTaskParamsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeSoarStrategyTaskParamsResponseBody() = default ;
    DescribeSoarStrategyTaskParamsResponseBody& operator=(const DescribeSoarStrategyTaskParamsResponseBody &) = default ;
    DescribeSoarStrategyTaskParamsResponseBody& operator=(DescribeSoarStrategyTaskParamsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->requestId_ != nullptr
        && this->taskDetail_ != nullptr; };
    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeSoarStrategyTaskParamsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // taskDetail Field Functions 
    bool hasTaskDetail() const { return this->taskDetail_ != nullptr;};
    void deleteTaskDetail() { this->taskDetail_ = nullptr;};
    inline const DescribeSoarStrategyTaskParamsResponseBodyTaskDetail & taskDetail() const { DARABONBA_PTR_GET_CONST(taskDetail_, DescribeSoarStrategyTaskParamsResponseBodyTaskDetail) };
    inline DescribeSoarStrategyTaskParamsResponseBodyTaskDetail taskDetail() { DARABONBA_PTR_GET(taskDetail_, DescribeSoarStrategyTaskParamsResponseBodyTaskDetail) };
    inline DescribeSoarStrategyTaskParamsResponseBody& setTaskDetail(const DescribeSoarStrategyTaskParamsResponseBodyTaskDetail & taskDetail) { DARABONBA_PTR_SET_VALUE(taskDetail_, taskDetail) };
    inline DescribeSoarStrategyTaskParamsResponseBody& setTaskDetail(DescribeSoarStrategyTaskParamsResponseBodyTaskDetail && taskDetail) { DARABONBA_PTR_SET_RVALUE(taskDetail_, taskDetail) };


  protected:
    // The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request, and can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
    // Task details.
    std::shared_ptr<DescribeSoarStrategyTaskParamsResponseBodyTaskDetail> taskDetail_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
