// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBECANACCESSVPCSALERESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBECANACCESSVPCSALERESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class DescribeCanAccessVpcSaleResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeCanAccessVpcSaleResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(CanAccess, canAccess_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeCanAccessVpcSaleResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(CanAccess, canAccess_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    DescribeCanAccessVpcSaleResponseBody() = default ;
    DescribeCanAccessVpcSaleResponseBody(const DescribeCanAccessVpcSaleResponseBody &) = default ;
    DescribeCanAccessVpcSaleResponseBody(DescribeCanAccessVpcSaleResponseBody &&) = default ;
    DescribeCanAccessVpcSaleResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeCanAccessVpcSaleResponseBody() = default ;
    DescribeCanAccessVpcSaleResponseBody& operator=(const DescribeCanAccessVpcSaleResponseBody &) = default ;
    DescribeCanAccessVpcSaleResponseBody& operator=(DescribeCanAccessVpcSaleResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->canAccess_ == nullptr
        && this->requestId_ == nullptr; };
    // canAccess Field Functions 
    bool hasCanAccess() const { return this->canAccess_ != nullptr;};
    void deleteCanAccess() { this->canAccess_ = nullptr;};
    inline bool getCanAccess() const { DARABONBA_PTR_GET_DEFAULT(canAccess_, false) };
    inline DescribeCanAccessVpcSaleResponseBody& setCanAccess(bool canAccess) { DARABONBA_PTR_SET_VALUE(canAccess_, canAccess) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeCanAccessVpcSaleResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Indicates whether the purchase can be made according to VPC.
    shared_ptr<bool> canAccess_ {};
    // The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used for troubleshooting and problem localization.
    shared_ptr<string> requestId_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
