// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBEDOMAINSECURESUGGESTSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBEDOMAINSECURESUGGESTSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class DescribeDomainSecureSuggestsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeDomainSecureSuggestsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(RiskSuggest, riskSuggest_);
      DARABONBA_PTR_TO_JSON(TotalCount, totalCount_);
      DARABONBA_PTR_TO_JSON(VulSuggest, vulSuggest_);
      DARABONBA_PTR_TO_JSON(WebLockSuggest, webLockSuggest_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeDomainSecureSuggestsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(RiskSuggest, riskSuggest_);
      DARABONBA_PTR_FROM_JSON(TotalCount, totalCount_);
      DARABONBA_PTR_FROM_JSON(VulSuggest, vulSuggest_);
      DARABONBA_PTR_FROM_JSON(WebLockSuggest, webLockSuggest_);
    };
    DescribeDomainSecureSuggestsResponseBody() = default ;
    DescribeDomainSecureSuggestsResponseBody(const DescribeDomainSecureSuggestsResponseBody &) = default ;
    DescribeDomainSecureSuggestsResponseBody(DescribeDomainSecureSuggestsResponseBody &&) = default ;
    DescribeDomainSecureSuggestsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeDomainSecureSuggestsResponseBody() = default ;
    DescribeDomainSecureSuggestsResponseBody& operator=(const DescribeDomainSecureSuggestsResponseBody &) = default ;
    DescribeDomainSecureSuggestsResponseBody& operator=(DescribeDomainSecureSuggestsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->requestId_ != nullptr
        && this->riskSuggest_ != nullptr && this->totalCount_ != nullptr && this->vulSuggest_ != nullptr && this->webLockSuggest_ != nullptr; };
    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeDomainSecureSuggestsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // riskSuggest Field Functions 
    bool hasRiskSuggest() const { return this->riskSuggest_ != nullptr;};
    void deleteRiskSuggest() { this->riskSuggest_ = nullptr;};
    inline string riskSuggest() const { DARABONBA_PTR_GET_DEFAULT(riskSuggest_, "") };
    inline DescribeDomainSecureSuggestsResponseBody& setRiskSuggest(string riskSuggest) { DARABONBA_PTR_SET_VALUE(riskSuggest_, riskSuggest) };


    // totalCount Field Functions 
    bool hasTotalCount() const { return this->totalCount_ != nullptr;};
    void deleteTotalCount() { this->totalCount_ = nullptr;};
    inline int32_t totalCount() const { DARABONBA_PTR_GET_DEFAULT(totalCount_, 0) };
    inline DescribeDomainSecureSuggestsResponseBody& setTotalCount(int32_t totalCount) { DARABONBA_PTR_SET_VALUE(totalCount_, totalCount) };


    // vulSuggest Field Functions 
    bool hasVulSuggest() const { return this->vulSuggest_ != nullptr;};
    void deleteVulSuggest() { this->vulSuggest_ = nullptr;};
    inline int64_t vulSuggest() const { DARABONBA_PTR_GET_DEFAULT(vulSuggest_, 0L) };
    inline DescribeDomainSecureSuggestsResponseBody& setVulSuggest(int64_t vulSuggest) { DARABONBA_PTR_SET_VALUE(vulSuggest_, vulSuggest) };


    // webLockSuggest Field Functions 
    bool hasWebLockSuggest() const { return this->webLockSuggest_ != nullptr;};
    void deleteWebLockSuggest() { this->webLockSuggest_ = nullptr;};
    inline string webLockSuggest() const { DARABONBA_PTR_GET_DEFAULT(webLockSuggest_, "") };
    inline DescribeDomainSecureSuggestsResponseBody& setWebLockSuggest(string webLockSuggest) { DARABONBA_PTR_SET_VALUE(webLockSuggest_, webLockSuggest) };


  protected:
    // The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
    // Overall suggestions for security reinforcement.
    std::shared_ptr<string> riskSuggest_ = nullptr;
    // Total number of security recommendations.
    std::shared_ptr<int32_t> totalCount_ = nullptr;
    // Suggestions for vulnerability repair.
    std::shared_ptr<int64_t> vulSuggest_ = nullptr;
    // Suggestions for website tamper prevention.
    std::shared_ptr<string> webLockSuggest_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
