// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBEALLREGIONSSTATISTICSRESPONSEBODYDATA_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBEALLREGIONSSTATISTICSRESPONSEBODYDATA_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class DescribeAllRegionsStatisticsResponseBodyData : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeAllRegionsStatisticsResponseBodyData& obj) { 
      DARABONBA_PTR_TO_JSON(Account, account_);
      DARABONBA_PTR_TO_JSON(Health, health_);
      DARABONBA_PTR_TO_JSON(NewSuspicious, newSuspicious_);
      DARABONBA_PTR_TO_JSON(Suspicious, suspicious_);
      DARABONBA_PTR_TO_JSON(Trojan, trojan_);
      DARABONBA_PTR_TO_JSON(Vul, vul_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeAllRegionsStatisticsResponseBodyData& obj) { 
      DARABONBA_PTR_FROM_JSON(Account, account_);
      DARABONBA_PTR_FROM_JSON(Health, health_);
      DARABONBA_PTR_FROM_JSON(NewSuspicious, newSuspicious_);
      DARABONBA_PTR_FROM_JSON(Suspicious, suspicious_);
      DARABONBA_PTR_FROM_JSON(Trojan, trojan_);
      DARABONBA_PTR_FROM_JSON(Vul, vul_);
    };
    DescribeAllRegionsStatisticsResponseBodyData() = default ;
    DescribeAllRegionsStatisticsResponseBodyData(const DescribeAllRegionsStatisticsResponseBodyData &) = default ;
    DescribeAllRegionsStatisticsResponseBodyData(DescribeAllRegionsStatisticsResponseBodyData &&) = default ;
    DescribeAllRegionsStatisticsResponseBodyData(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeAllRegionsStatisticsResponseBodyData() = default ;
    DescribeAllRegionsStatisticsResponseBodyData& operator=(const DescribeAllRegionsStatisticsResponseBodyData &) = default ;
    DescribeAllRegionsStatisticsResponseBodyData& operator=(DescribeAllRegionsStatisticsResponseBodyData &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->account_ != nullptr
        && this->health_ != nullptr && this->newSuspicious_ != nullptr && this->suspicious_ != nullptr && this->trojan_ != nullptr && this->vul_ != nullptr; };
    // account Field Functions 
    bool hasAccount() const { return this->account_ != nullptr;};
    void deleteAccount() { this->account_ = nullptr;};
    inline int32_t account() const { DARABONBA_PTR_GET_DEFAULT(account_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setAccount(int32_t account) { DARABONBA_PTR_SET_VALUE(account_, account) };


    // health Field Functions 
    bool hasHealth() const { return this->health_ != nullptr;};
    void deleteHealth() { this->health_ = nullptr;};
    inline int32_t health() const { DARABONBA_PTR_GET_DEFAULT(health_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setHealth(int32_t health) { DARABONBA_PTR_SET_VALUE(health_, health) };


    // newSuspicious Field Functions 
    bool hasNewSuspicious() const { return this->newSuspicious_ != nullptr;};
    void deleteNewSuspicious() { this->newSuspicious_ = nullptr;};
    inline int32_t newSuspicious() const { DARABONBA_PTR_GET_DEFAULT(newSuspicious_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setNewSuspicious(int32_t newSuspicious) { DARABONBA_PTR_SET_VALUE(newSuspicious_, newSuspicious) };


    // suspicious Field Functions 
    bool hasSuspicious() const { return this->suspicious_ != nullptr;};
    void deleteSuspicious() { this->suspicious_ = nullptr;};
    inline int32_t suspicious() const { DARABONBA_PTR_GET_DEFAULT(suspicious_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setSuspicious(int32_t suspicious) { DARABONBA_PTR_SET_VALUE(suspicious_, suspicious) };


    // trojan Field Functions 
    bool hasTrojan() const { return this->trojan_ != nullptr;};
    void deleteTrojan() { this->trojan_ = nullptr;};
    inline int32_t trojan() const { DARABONBA_PTR_GET_DEFAULT(trojan_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setTrojan(int32_t trojan) { DARABONBA_PTR_SET_VALUE(trojan_, trojan) };


    // vul Field Functions 
    bool hasVul() const { return this->vul_ != nullptr;};
    void deleteVul() { this->vul_ = nullptr;};
    inline int32_t vul() const { DARABONBA_PTR_GET_DEFAULT(vul_, 0) };
    inline DescribeAllRegionsStatisticsResponseBodyData& setVul(int32_t vul) { DARABONBA_PTR_SET_VALUE(vul_, vul) };


  protected:
    // The number of logons to the asset.
    std::shared_ptr<int32_t> account_ = nullptr;
    // The total number of unfixed baseline risks.
    std::shared_ptr<int32_t> health_ = nullptr;
    // The number of alerts that are generated by Server Guard or Security Center.
    // 
    // > 
    // 
    // *   If **From** is set to **sas**, this parameter indicates the number of alerts that are generated by Security Center.
    // 
    // *   If **From** is set to **aqs**, this parameter indicates the number of alerts that are generated by Server Guard.
    std::shared_ptr<int32_t> newSuspicious_ = nullptr;
    // The number of alerts that are generated by Server Guard.
    std::shared_ptr<int32_t> suspicious_ = nullptr;
    // The number of webshell alerts.
    std::shared_ptr<int32_t> trojan_ = nullptr;
    // The number of unfixed vulnerabilities.
    std::shared_ptr<int32_t> vul_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
