// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETATTACKPATHSENSITIVEASSETCONFIGRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETATTACKPATHSENSITIVEASSETCONFIGRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetAttackPathSensitiveAssetConfigResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetAttackPathSensitiveAssetConfigResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(AttackPathSensitiveAssetConfig, attackPathSensitiveAssetConfig_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetAttackPathSensitiveAssetConfigResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(AttackPathSensitiveAssetConfig, attackPathSensitiveAssetConfig_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetAttackPathSensitiveAssetConfigResponseBody() = default ;
    GetAttackPathSensitiveAssetConfigResponseBody(const GetAttackPathSensitiveAssetConfigResponseBody &) = default ;
    GetAttackPathSensitiveAssetConfigResponseBody(GetAttackPathSensitiveAssetConfigResponseBody &&) = default ;
    GetAttackPathSensitiveAssetConfigResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetAttackPathSensitiveAssetConfigResponseBody() = default ;
    GetAttackPathSensitiveAssetConfigResponseBody& operator=(const GetAttackPathSensitiveAssetConfigResponseBody &) = default ;
    GetAttackPathSensitiveAssetConfigResponseBody& operator=(GetAttackPathSensitiveAssetConfigResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->attackPathSensitiveAssetConfig_ == nullptr
        && return this->requestId_ == nullptr; };
    // attackPathSensitiveAssetConfig Field Functions 
    bool hasAttackPathSensitiveAssetConfig() const { return this->attackPathSensitiveAssetConfig_ != nullptr;};
    void deleteAttackPathSensitiveAssetConfig() { this->attackPathSensitiveAssetConfig_ = nullptr;};
    inline const GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig & attackPathSensitiveAssetConfig() const { DARABONBA_PTR_GET_CONST(attackPathSensitiveAssetConfig_, GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig) };
    inline GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig attackPathSensitiveAssetConfig() { DARABONBA_PTR_GET(attackPathSensitiveAssetConfig_, GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig) };
    inline GetAttackPathSensitiveAssetConfigResponseBody& setAttackPathSensitiveAssetConfig(const GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig & attackPathSensitiveAssetConfig) { DARABONBA_PTR_SET_VALUE(attackPathSensitiveAssetConfig_, attackPathSensitiveAssetConfig) };
    inline GetAttackPathSensitiveAssetConfigResponseBody& setAttackPathSensitiveAssetConfig(GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig && attackPathSensitiveAssetConfig) { DARABONBA_PTR_SET_RVALUE(attackPathSensitiveAssetConfig_, attackPathSensitiveAssetConfig) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetAttackPathSensitiveAssetConfigResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Data of the attack path sensitive asset configuration.
    std::shared_ptr<GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig> attackPathSensitiveAssetConfig_ = nullptr;
    // The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
