// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETAGENTLESSTASKUSEDSIZEESTIMATERESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETAGENTLESSTASKUSEDSIZEESTIMATERESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetAgentlessTaskUsedSizeEstimateResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetAgentlessTaskUsedSizeEstimateResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(EstimateUsedSize, estimateUsedSize_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetAgentlessTaskUsedSizeEstimateResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(EstimateUsedSize, estimateUsedSize_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetAgentlessTaskUsedSizeEstimateResponseBody() = default ;
    GetAgentlessTaskUsedSizeEstimateResponseBody(const GetAgentlessTaskUsedSizeEstimateResponseBody &) = default ;
    GetAgentlessTaskUsedSizeEstimateResponseBody(GetAgentlessTaskUsedSizeEstimateResponseBody &&) = default ;
    GetAgentlessTaskUsedSizeEstimateResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetAgentlessTaskUsedSizeEstimateResponseBody() = default ;
    GetAgentlessTaskUsedSizeEstimateResponseBody& operator=(const GetAgentlessTaskUsedSizeEstimateResponseBody &) = default ;
    GetAgentlessTaskUsedSizeEstimateResponseBody& operator=(GetAgentlessTaskUsedSizeEstimateResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->estimateUsedSize_ == nullptr
        && this->requestId_ == nullptr; };
    // estimateUsedSize Field Functions 
    bool hasEstimateUsedSize() const { return this->estimateUsedSize_ != nullptr;};
    void deleteEstimateUsedSize() { this->estimateUsedSize_ = nullptr;};
    inline int64_t getEstimateUsedSize() const { DARABONBA_PTR_GET_DEFAULT(estimateUsedSize_, 0L) };
    inline GetAgentlessTaskUsedSizeEstimateResponseBody& setEstimateUsedSize(int64_t estimateUsedSize) { DARABONBA_PTR_SET_VALUE(estimateUsedSize_, estimateUsedSize) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetAgentlessTaskUsedSizeEstimateResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // The estimated volume for this detection task, in GB.
    shared_ptr<int64_t> estimateUsedSize_ {};
    // The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request and can be used to troubleshoot and locate issues.
    shared_ptr<string> requestId_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
