// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETCHECKTIMEDIMENSIONSTATISTICRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETCHECKTIMEDIMENSIONSTATISTICRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetCheckTimeDimensionStatisticResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetCheckTimeDimensionStatisticResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(TimeDimensionStatisticDTO, timeDimensionStatisticDTO_);
    };
    friend void from_json(const Darabonba::Json& j, GetCheckTimeDimensionStatisticResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(TimeDimensionStatisticDTO, timeDimensionStatisticDTO_);
    };
    GetCheckTimeDimensionStatisticResponseBody() = default ;
    GetCheckTimeDimensionStatisticResponseBody(const GetCheckTimeDimensionStatisticResponseBody &) = default ;
    GetCheckTimeDimensionStatisticResponseBody(GetCheckTimeDimensionStatisticResponseBody &&) = default ;
    GetCheckTimeDimensionStatisticResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetCheckTimeDimensionStatisticResponseBody() = default ;
    GetCheckTimeDimensionStatisticResponseBody& operator=(const GetCheckTimeDimensionStatisticResponseBody &) = default ;
    GetCheckTimeDimensionStatisticResponseBody& operator=(GetCheckTimeDimensionStatisticResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->requestId_ == nullptr
        && return this->timeDimensionStatisticDTO_ == nullptr; };
    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetCheckTimeDimensionStatisticResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // timeDimensionStatisticDTO Field Functions 
    bool hasTimeDimensionStatisticDTO() const { return this->timeDimensionStatisticDTO_ != nullptr;};
    void deleteTimeDimensionStatisticDTO() { this->timeDimensionStatisticDTO_ = nullptr;};
    inline const GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO & timeDimensionStatisticDTO() const { DARABONBA_PTR_GET_CONST(timeDimensionStatisticDTO_, GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO) };
    inline GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO timeDimensionStatisticDTO() { DARABONBA_PTR_GET(timeDimensionStatisticDTO_, GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO) };
    inline GetCheckTimeDimensionStatisticResponseBody& setTimeDimensionStatisticDTO(const GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO & timeDimensionStatisticDTO) { DARABONBA_PTR_SET_VALUE(timeDimensionStatisticDTO_, timeDimensionStatisticDTO) };
    inline GetCheckTimeDimensionStatisticResponseBody& setTimeDimensionStatisticDTO(GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO && timeDimensionStatisticDTO) { DARABONBA_PTR_SET_RVALUE(timeDimensionStatisticDTO_, timeDimensionStatisticDTO) };


  protected:
    // The ID of the current request, a unique identifier generated by Alibaba Cloud for this request, which can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
    // List of time trend statistical data results.
    std::shared_ptr<GetCheckTimeDimensionStatisticResponseBodyTimeDimensionStatisticDTO> timeDimensionStatisticDTO_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
