// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETFUNCTIONTRIALSTATUSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETFUNCTIONTRIALSTATUSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetFunctionTrialStatusResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetFunctionTrialStatusResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetFunctionTrialStatusResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetFunctionTrialStatusResponseBody() = default ;
    GetFunctionTrialStatusResponseBody(const GetFunctionTrialStatusResponseBody &) = default ;
    GetFunctionTrialStatusResponseBody(GetFunctionTrialStatusResponseBody &&) = default ;
    GetFunctionTrialStatusResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetFunctionTrialStatusResponseBody() = default ;
    GetFunctionTrialStatusResponseBody& operator=(const GetFunctionTrialStatusResponseBody &) = default ;
    GetFunctionTrialStatusResponseBody& operator=(GetFunctionTrialStatusResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->data_ != nullptr
        && this->requestId_ != nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline int32_t data() const { DARABONBA_PTR_GET_DEFAULT(data_, 0) };
    inline GetFunctionTrialStatusResponseBody& setData(int32_t data) { DARABONBA_PTR_SET_VALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetFunctionTrialStatusResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Indicates eligibility. Values:
    // 
    // - **0**: Eligible
    // - **1**: Not eligible
    // - **2**: Trial ended
    // - **3**: In trial
    std::shared_ptr<int32_t> data_ = nullptr;
    // The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request and can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
