// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETINSTANCEALARMSTATISTICSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETINSTANCEALARMSTATISTICSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GetInstanceAlarmStatisticsResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetInstanceAlarmStatisticsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetInstanceAlarmStatisticsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetInstanceAlarmStatisticsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetInstanceAlarmStatisticsResponseBody() = default ;
    GetInstanceAlarmStatisticsResponseBody(const GetInstanceAlarmStatisticsResponseBody &) = default ;
    GetInstanceAlarmStatisticsResponseBody(GetInstanceAlarmStatisticsResponseBody &&) = default ;
    GetInstanceAlarmStatisticsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetInstanceAlarmStatisticsResponseBody() = default ;
    GetInstanceAlarmStatisticsResponseBody& operator=(const GetInstanceAlarmStatisticsResponseBody &) = default ;
    GetInstanceAlarmStatisticsResponseBody& operator=(GetInstanceAlarmStatisticsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->data_ != nullptr
        && this->requestId_ != nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const GetInstanceAlarmStatisticsResponseBodyData & data() const { DARABONBA_PTR_GET_CONST(data_, GetInstanceAlarmStatisticsResponseBodyData) };
    inline GetInstanceAlarmStatisticsResponseBodyData data() { DARABONBA_PTR_GET(data_, GetInstanceAlarmStatisticsResponseBodyData) };
    inline GetInstanceAlarmStatisticsResponseBody& setData(const GetInstanceAlarmStatisticsResponseBodyData & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline GetInstanceAlarmStatisticsResponseBody& setData(GetInstanceAlarmStatisticsResponseBodyData && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetInstanceAlarmStatisticsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Data structure.
    std::shared_ptr<GetInstanceAlarmStatisticsResponseBodyData> data_ = nullptr;
    // The unique identifier generated by Alibaba Cloud for this request.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
