// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETPUBLISHCRONRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETPUBLISHCRONRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GetPublishCronResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetPublishCronResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetPublishCronResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetPublishCronResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetPublishCronResponseBody() = default ;
    GetPublishCronResponseBody(const GetPublishCronResponseBody &) = default ;
    GetPublishCronResponseBody(GetPublishCronResponseBody &&) = default ;
    GetPublishCronResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetPublishCronResponseBody() = default ;
    GetPublishCronResponseBody& operator=(const GetPublishCronResponseBody &) = default ;
    GetPublishCronResponseBody& operator=(GetPublishCronResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->data_ != nullptr
        && this->requestId_ != nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const GetPublishCronResponseBodyData & data() const { DARABONBA_PTR_GET_CONST(data_, GetPublishCronResponseBodyData) };
    inline GetPublishCronResponseBodyData data() { DARABONBA_PTR_GET(data_, GetPublishCronResponseBodyData) };
    inline GetPublishCronResponseBody& setData(const GetPublishCronResponseBodyData & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline GetPublishCronResponseBody& setData(GetPublishCronResponseBodyData && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetPublishCronResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Publish scheduling configuration information.
    std::shared_ptr<GetPublishCronResponseBodyData> data_ = nullptr;
    // The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
