// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETSERVERLESSAPPAUTHDETAILRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETSERVERLESSAPPAUTHDETAILRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GetServerlessAppAuthDetailResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class GetServerlessAppAuthDetailResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetServerlessAppAuthDetailResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(Success, success_);
    };
    friend void from_json(const Darabonba::Json& j, GetServerlessAppAuthDetailResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(Success, success_);
    };
    GetServerlessAppAuthDetailResponseBody() = default ;
    GetServerlessAppAuthDetailResponseBody(const GetServerlessAppAuthDetailResponseBody &) = default ;
    GetServerlessAppAuthDetailResponseBody(GetServerlessAppAuthDetailResponseBody &&) = default ;
    GetServerlessAppAuthDetailResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetServerlessAppAuthDetailResponseBody() = default ;
    GetServerlessAppAuthDetailResponseBody& operator=(const GetServerlessAppAuthDetailResponseBody &) = default ;
    GetServerlessAppAuthDetailResponseBody& operator=(GetServerlessAppAuthDetailResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->data_ == nullptr
        && return this->requestId_ == nullptr && return this->success_ == nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const GetServerlessAppAuthDetailResponseBodyData & data() const { DARABONBA_PTR_GET_CONST(data_, GetServerlessAppAuthDetailResponseBodyData) };
    inline GetServerlessAppAuthDetailResponseBodyData data() { DARABONBA_PTR_GET(data_, GetServerlessAppAuthDetailResponseBodyData) };
    inline GetServerlessAppAuthDetailResponseBody& setData(const GetServerlessAppAuthDetailResponseBodyData & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline GetServerlessAppAuthDetailResponseBody& setData(GetServerlessAppAuthDetailResponseBodyData && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetServerlessAppAuthDetailResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // success Field Functions 
    bool hasSuccess() const { return this->success_ != nullptr;};
    void deleteSuccess() { this->success_ = nullptr;};
    inline bool success() const { DARABONBA_PTR_GET_DEFAULT(success_, false) };
    inline GetServerlessAppAuthDetailResponseBody& setSuccess(bool success) { DARABONBA_PTR_SET_VALUE(success_, success) };


  protected:
    // Data details.
    std::shared_ptr<GetServerlessAppAuthDetailResponseBodyData> data_ = nullptr;
    // The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and pinpoint issues.
    std::shared_ptr<string> requestId_ = nullptr;
    // Whether the API call was successful. Values: 
    // - **true**: Success
    // - **false**: Failure
    std::shared_ptr<bool> success_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
