// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTATTACKPATHEVENTRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTATTACKPATHEVENTRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListAttackPathEventResponseBodyAttackPathEventList.hpp>
#include <alibabacloud/models/ListAttackPathEventResponseBodyPageInfo.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListAttackPathEventResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListAttackPathEventResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(AttackPathEventList, attackPathEventList_);
      DARABONBA_PTR_TO_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListAttackPathEventResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(AttackPathEventList, attackPathEventList_);
      DARABONBA_PTR_FROM_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListAttackPathEventResponseBody() = default ;
    ListAttackPathEventResponseBody(const ListAttackPathEventResponseBody &) = default ;
    ListAttackPathEventResponseBody(ListAttackPathEventResponseBody &&) = default ;
    ListAttackPathEventResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListAttackPathEventResponseBody() = default ;
    ListAttackPathEventResponseBody& operator=(const ListAttackPathEventResponseBody &) = default ;
    ListAttackPathEventResponseBody& operator=(ListAttackPathEventResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->attackPathEventList_ == nullptr
        && return this->pageInfo_ == nullptr && return this->requestId_ == nullptr; };
    // attackPathEventList Field Functions 
    bool hasAttackPathEventList() const { return this->attackPathEventList_ != nullptr;};
    void deleteAttackPathEventList() { this->attackPathEventList_ = nullptr;};
    inline const vector<ListAttackPathEventResponseBodyAttackPathEventList> & attackPathEventList() const { DARABONBA_PTR_GET_CONST(attackPathEventList_, vector<ListAttackPathEventResponseBodyAttackPathEventList>) };
    inline vector<ListAttackPathEventResponseBodyAttackPathEventList> attackPathEventList() { DARABONBA_PTR_GET(attackPathEventList_, vector<ListAttackPathEventResponseBodyAttackPathEventList>) };
    inline ListAttackPathEventResponseBody& setAttackPathEventList(const vector<ListAttackPathEventResponseBodyAttackPathEventList> & attackPathEventList) { DARABONBA_PTR_SET_VALUE(attackPathEventList_, attackPathEventList) };
    inline ListAttackPathEventResponseBody& setAttackPathEventList(vector<ListAttackPathEventResponseBodyAttackPathEventList> && attackPathEventList) { DARABONBA_PTR_SET_RVALUE(attackPathEventList_, attackPathEventList) };


    // pageInfo Field Functions 
    bool hasPageInfo() const { return this->pageInfo_ != nullptr;};
    void deletePageInfo() { this->pageInfo_ = nullptr;};
    inline const ListAttackPathEventResponseBodyPageInfo & pageInfo() const { DARABONBA_PTR_GET_CONST(pageInfo_, ListAttackPathEventResponseBodyPageInfo) };
    inline ListAttackPathEventResponseBodyPageInfo pageInfo() { DARABONBA_PTR_GET(pageInfo_, ListAttackPathEventResponseBodyPageInfo) };
    inline ListAttackPathEventResponseBody& setPageInfo(const ListAttackPathEventResponseBodyPageInfo & pageInfo) { DARABONBA_PTR_SET_VALUE(pageInfo_, pageInfo) };
    inline ListAttackPathEventResponseBody& setPageInfo(ListAttackPathEventResponseBodyPageInfo && pageInfo) { DARABONBA_PTR_SET_RVALUE(pageInfo_, pageInfo) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListAttackPathEventResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // List of attack path events.
    std::shared_ptr<vector<ListAttackPathEventResponseBodyAttackPathEventList>> attackPathEventList_ = nullptr;
    // Pagination information.
    std::shared_ptr<ListAttackPathEventResponseBodyPageInfo> pageInfo_ = nullptr;
    // The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request. It can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
