// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTAGENTLESSASSETRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTAGENTLESSASSETRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListAgentlessAssetResponseBodyAssetList.hpp>
#include <alibabacloud/models/ListAgentlessAssetResponseBodyPageInfo.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListAgentlessAssetResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListAgentlessAssetResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(AssetList, assetList_);
      DARABONBA_PTR_TO_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListAgentlessAssetResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(AssetList, assetList_);
      DARABONBA_PTR_FROM_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListAgentlessAssetResponseBody() = default ;
    ListAgentlessAssetResponseBody(const ListAgentlessAssetResponseBody &) = default ;
    ListAgentlessAssetResponseBody(ListAgentlessAssetResponseBody &&) = default ;
    ListAgentlessAssetResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListAgentlessAssetResponseBody() = default ;
    ListAgentlessAssetResponseBody& operator=(const ListAgentlessAssetResponseBody &) = default ;
    ListAgentlessAssetResponseBody& operator=(ListAgentlessAssetResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->assetList_ == nullptr
        && return this->pageInfo_ == nullptr && return this->requestId_ == nullptr; };
    // assetList Field Functions 
    bool hasAssetList() const { return this->assetList_ != nullptr;};
    void deleteAssetList() { this->assetList_ = nullptr;};
    inline const vector<ListAgentlessAssetResponseBodyAssetList> & assetList() const { DARABONBA_PTR_GET_CONST(assetList_, vector<ListAgentlessAssetResponseBodyAssetList>) };
    inline vector<ListAgentlessAssetResponseBodyAssetList> assetList() { DARABONBA_PTR_GET(assetList_, vector<ListAgentlessAssetResponseBodyAssetList>) };
    inline ListAgentlessAssetResponseBody& setAssetList(const vector<ListAgentlessAssetResponseBodyAssetList> & assetList) { DARABONBA_PTR_SET_VALUE(assetList_, assetList) };
    inline ListAgentlessAssetResponseBody& setAssetList(vector<ListAgentlessAssetResponseBodyAssetList> && assetList) { DARABONBA_PTR_SET_RVALUE(assetList_, assetList) };


    // pageInfo Field Functions 
    bool hasPageInfo() const { return this->pageInfo_ != nullptr;};
    void deletePageInfo() { this->pageInfo_ = nullptr;};
    inline const ListAgentlessAssetResponseBodyPageInfo & pageInfo() const { DARABONBA_PTR_GET_CONST(pageInfo_, ListAgentlessAssetResponseBodyPageInfo) };
    inline ListAgentlessAssetResponseBodyPageInfo pageInfo() { DARABONBA_PTR_GET(pageInfo_, ListAgentlessAssetResponseBodyPageInfo) };
    inline ListAgentlessAssetResponseBody& setPageInfo(const ListAgentlessAssetResponseBodyPageInfo & pageInfo) { DARABONBA_PTR_SET_VALUE(pageInfo_, pageInfo) };
    inline ListAgentlessAssetResponseBody& setPageInfo(ListAgentlessAssetResponseBodyPageInfo && pageInfo) { DARABONBA_PTR_SET_RVALUE(pageInfo_, pageInfo) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListAgentlessAssetResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // The list of returned assets.
    std::shared_ptr<vector<ListAgentlessAssetResponseBodyAssetList>> assetList_ = nullptr;
    // Pagination information.
    std::shared_ptr<ListAgentlessAssetResponseBodyPageInfo> pageInfo_ = nullptr;
    // The ID of the request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
