// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTSUPPORTATTACKPATHASSETRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTSUPPORTATTACKPATHASSETRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListSupportAttackPathAssetResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListSupportAttackPathAssetResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(AttackPathAssetTypeList, attackPathAssetTypeList_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListSupportAttackPathAssetResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(AttackPathAssetTypeList, attackPathAssetTypeList_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListSupportAttackPathAssetResponseBody() = default ;
    ListSupportAttackPathAssetResponseBody(const ListSupportAttackPathAssetResponseBody &) = default ;
    ListSupportAttackPathAssetResponseBody(ListSupportAttackPathAssetResponseBody &&) = default ;
    ListSupportAttackPathAssetResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListSupportAttackPathAssetResponseBody() = default ;
    ListSupportAttackPathAssetResponseBody& operator=(const ListSupportAttackPathAssetResponseBody &) = default ;
    ListSupportAttackPathAssetResponseBody& operator=(ListSupportAttackPathAssetResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->attackPathAssetTypeList_ == nullptr
        && return this->requestId_ == nullptr; };
    // attackPathAssetTypeList Field Functions 
    bool hasAttackPathAssetTypeList() const { return this->attackPathAssetTypeList_ != nullptr;};
    void deleteAttackPathAssetTypeList() { this->attackPathAssetTypeList_ = nullptr;};
    inline const vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList> & attackPathAssetTypeList() const { DARABONBA_PTR_GET_CONST(attackPathAssetTypeList_, vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList>) };
    inline vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList> attackPathAssetTypeList() { DARABONBA_PTR_GET(attackPathAssetTypeList_, vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList>) };
    inline ListSupportAttackPathAssetResponseBody& setAttackPathAssetTypeList(const vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList> & attackPathAssetTypeList) { DARABONBA_PTR_SET_VALUE(attackPathAssetTypeList_, attackPathAssetTypeList) };
    inline ListSupportAttackPathAssetResponseBody& setAttackPathAssetTypeList(vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList> && attackPathAssetTypeList) { DARABONBA_PTR_SET_RVALUE(attackPathAssetTypeList_, attackPathAssetTypeList) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListSupportAttackPathAssetResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // List of cloud product asset types for the attack path.
    std::shared_ptr<vector<ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList>> attackPathAssetTypeList_ = nullptr;
    // The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
