// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTOPERATIONCHECKRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTOPERATIONCHECKRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListOperationCheckResponseBodyOperationTaskInstanceDetails.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListOperationCheckResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListOperationCheckResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(OperationTaskInstanceDetails, operationTaskInstanceDetails_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListOperationCheckResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(OperationTaskInstanceDetails, operationTaskInstanceDetails_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListOperationCheckResponseBody() = default ;
    ListOperationCheckResponseBody(const ListOperationCheckResponseBody &) = default ;
    ListOperationCheckResponseBody(ListOperationCheckResponseBody &&) = default ;
    ListOperationCheckResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListOperationCheckResponseBody() = default ;
    ListOperationCheckResponseBody& operator=(const ListOperationCheckResponseBody &) = default ;
    ListOperationCheckResponseBody& operator=(ListOperationCheckResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->operationTaskInstanceDetails_ == nullptr
        && return this->requestId_ == nullptr; };
    // operationTaskInstanceDetails Field Functions 
    bool hasOperationTaskInstanceDetails() const { return this->operationTaskInstanceDetails_ != nullptr;};
    void deleteOperationTaskInstanceDetails() { this->operationTaskInstanceDetails_ = nullptr;};
    inline const vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails> & operationTaskInstanceDetails() const { DARABONBA_PTR_GET_CONST(operationTaskInstanceDetails_, vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails>) };
    inline vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails> operationTaskInstanceDetails() { DARABONBA_PTR_GET(operationTaskInstanceDetails_, vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails>) };
    inline ListOperationCheckResponseBody& setOperationTaskInstanceDetails(const vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails> & operationTaskInstanceDetails) { DARABONBA_PTR_SET_VALUE(operationTaskInstanceDetails_, operationTaskInstanceDetails) };
    inline ListOperationCheckResponseBody& setOperationTaskInstanceDetails(vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails> && operationTaskInstanceDetails) { DARABONBA_PTR_SET_RVALUE(operationTaskInstanceDetails_, operationTaskInstanceDetails) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListOperationCheckResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Detailed information about the operation instances.
    std::shared_ptr<vector<ListOperationCheckResponseBodyOperationTaskInstanceDetails>> operationTaskInstanceDetails_ = nullptr;
    // The ID of the current call request, which is a unique identifier generated by Alibaba Cloud for the request, and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
