// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTOPERATIONTASKRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTOPERATIONTASKRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListOperationTaskResponseBodyOperationTasks.hpp>
#include <alibabacloud/models/ListOperationTaskResponseBodyPageInfo.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListOperationTaskResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListOperationTaskResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(OperationTasks, operationTasks_);
      DARABONBA_PTR_TO_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListOperationTaskResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(OperationTasks, operationTasks_);
      DARABONBA_PTR_FROM_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListOperationTaskResponseBody() = default ;
    ListOperationTaskResponseBody(const ListOperationTaskResponseBody &) = default ;
    ListOperationTaskResponseBody(ListOperationTaskResponseBody &&) = default ;
    ListOperationTaskResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListOperationTaskResponseBody() = default ;
    ListOperationTaskResponseBody& operator=(const ListOperationTaskResponseBody &) = default ;
    ListOperationTaskResponseBody& operator=(ListOperationTaskResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->operationTasks_ != nullptr
        && this->pageInfo_ != nullptr && this->requestId_ != nullptr; };
    // operationTasks Field Functions 
    bool hasOperationTasks() const { return this->operationTasks_ != nullptr;};
    void deleteOperationTasks() { this->operationTasks_ = nullptr;};
    inline const vector<ListOperationTaskResponseBodyOperationTasks> & operationTasks() const { DARABONBA_PTR_GET_CONST(operationTasks_, vector<ListOperationTaskResponseBodyOperationTasks>) };
    inline vector<ListOperationTaskResponseBodyOperationTasks> operationTasks() { DARABONBA_PTR_GET(operationTasks_, vector<ListOperationTaskResponseBodyOperationTasks>) };
    inline ListOperationTaskResponseBody& setOperationTasks(const vector<ListOperationTaskResponseBodyOperationTasks> & operationTasks) { DARABONBA_PTR_SET_VALUE(operationTasks_, operationTasks) };
    inline ListOperationTaskResponseBody& setOperationTasks(vector<ListOperationTaskResponseBodyOperationTasks> && operationTasks) { DARABONBA_PTR_SET_RVALUE(operationTasks_, operationTasks) };


    // pageInfo Field Functions 
    bool hasPageInfo() const { return this->pageInfo_ != nullptr;};
    void deletePageInfo() { this->pageInfo_ = nullptr;};
    inline const ListOperationTaskResponseBodyPageInfo & pageInfo() const { DARABONBA_PTR_GET_CONST(pageInfo_, ListOperationTaskResponseBodyPageInfo) };
    inline ListOperationTaskResponseBodyPageInfo pageInfo() { DARABONBA_PTR_GET(pageInfo_, ListOperationTaskResponseBodyPageInfo) };
    inline ListOperationTaskResponseBody& setPageInfo(const ListOperationTaskResponseBodyPageInfo & pageInfo) { DARABONBA_PTR_SET_VALUE(pageInfo_, pageInfo) };
    inline ListOperationTaskResponseBody& setPageInfo(ListOperationTaskResponseBodyPageInfo && pageInfo) { DARABONBA_PTR_SET_RVALUE(pageInfo_, pageInfo) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListOperationTaskResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Detailed instance information list of operation tasks.
    std::shared_ptr<vector<ListOperationTaskResponseBodyOperationTasks>> operationTasks_ = nullptr;
    // Page information when performing a paginated query.
    std::shared_ptr<ListOperationTaskResponseBodyPageInfo> pageInfo_ = nullptr;
    // The ID of the current request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
