// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTCHECKITEMSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTCHECKITEMSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListCheckItemsResponseBodyCheckItems.hpp>
#include <alibabacloud/models/ListCheckItemsResponseBodyPageInfo.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class ListCheckItemsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListCheckItemsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(CheckItems, checkItems_);
      DARABONBA_PTR_TO_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ListCheckItemsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(CheckItems, checkItems_);
      DARABONBA_PTR_FROM_JSON(PageInfo, pageInfo_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ListCheckItemsResponseBody() = default ;
    ListCheckItemsResponseBody(const ListCheckItemsResponseBody &) = default ;
    ListCheckItemsResponseBody(ListCheckItemsResponseBody &&) = default ;
    ListCheckItemsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListCheckItemsResponseBody() = default ;
    ListCheckItemsResponseBody& operator=(const ListCheckItemsResponseBody &) = default ;
    ListCheckItemsResponseBody& operator=(ListCheckItemsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->checkItems_ == nullptr
        && return this->pageInfo_ == nullptr && return this->requestId_ == nullptr; };
    // checkItems Field Functions 
    bool hasCheckItems() const { return this->checkItems_ != nullptr;};
    void deleteCheckItems() { this->checkItems_ = nullptr;};
    inline const vector<ListCheckItemsResponseBodyCheckItems> & checkItems() const { DARABONBA_PTR_GET_CONST(checkItems_, vector<ListCheckItemsResponseBodyCheckItems>) };
    inline vector<ListCheckItemsResponseBodyCheckItems> checkItems() { DARABONBA_PTR_GET(checkItems_, vector<ListCheckItemsResponseBodyCheckItems>) };
    inline ListCheckItemsResponseBody& setCheckItems(const vector<ListCheckItemsResponseBodyCheckItems> & checkItems) { DARABONBA_PTR_SET_VALUE(checkItems_, checkItems) };
    inline ListCheckItemsResponseBody& setCheckItems(vector<ListCheckItemsResponseBodyCheckItems> && checkItems) { DARABONBA_PTR_SET_RVALUE(checkItems_, checkItems) };


    // pageInfo Field Functions 
    bool hasPageInfo() const { return this->pageInfo_ != nullptr;};
    void deletePageInfo() { this->pageInfo_ = nullptr;};
    inline const ListCheckItemsResponseBodyPageInfo & pageInfo() const { DARABONBA_PTR_GET_CONST(pageInfo_, ListCheckItemsResponseBodyPageInfo) };
    inline ListCheckItemsResponseBodyPageInfo pageInfo() { DARABONBA_PTR_GET(pageInfo_, ListCheckItemsResponseBodyPageInfo) };
    inline ListCheckItemsResponseBody& setPageInfo(const ListCheckItemsResponseBodyPageInfo & pageInfo) { DARABONBA_PTR_SET_VALUE(pageInfo_, pageInfo) };
    inline ListCheckItemsResponseBody& setPageInfo(ListCheckItemsResponseBodyPageInfo && pageInfo) { DARABONBA_PTR_SET_RVALUE(pageInfo_, pageInfo) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListCheckItemsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Information about the check items.
    std::shared_ptr<vector<ListCheckItemsResponseBodyCheckItems>> checkItems_ = nullptr;
    // Page information for paginated queries.
    std::shared_ptr<ListCheckItemsResponseBodyPageInfo> pageInfo_ = nullptr;
    // The ID of the current request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
