// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_OPENBACKUPAUTOCONFIGREQUEST_HPP_
#define ALIBABACLOUD_MODELS_OPENBACKUPAUTOCONFIGREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class OpenBackupAutoConfigRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const OpenBackupAutoConfigRequest& obj) { 
      DARABONBA_PTR_TO_JSON(MaxBatchSize, maxBatchSize_);
    };
    friend void from_json(const Darabonba::Json& j, OpenBackupAutoConfigRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(MaxBatchSize, maxBatchSize_);
    };
    OpenBackupAutoConfigRequest() = default ;
    OpenBackupAutoConfigRequest(const OpenBackupAutoConfigRequest &) = default ;
    OpenBackupAutoConfigRequest(OpenBackupAutoConfigRequest &&) = default ;
    OpenBackupAutoConfigRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~OpenBackupAutoConfigRequest() = default ;
    OpenBackupAutoConfigRequest& operator=(const OpenBackupAutoConfigRequest &) = default ;
    OpenBackupAutoConfigRequest& operator=(OpenBackupAutoConfigRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->maxBatchSize_ == nullptr; };
    // maxBatchSize Field Functions 
    bool hasMaxBatchSize() const { return this->maxBatchSize_ != nullptr;};
    void deleteMaxBatchSize() { this->maxBatchSize_ = nullptr;};
    inline int32_t getMaxBatchSize() const { DARABONBA_PTR_GET_DEFAULT(maxBatchSize_, 0) };
    inline OpenBackupAutoConfigRequest& setMaxBatchSize(int32_t maxBatchSize) { DARABONBA_PTR_SET_VALUE(maxBatchSize_, maxBatchSize) };


  protected:
    // The number of servers specified in a batch of anti-ransomware policies that are automatically generated by the managed anti-ransomware feature.
    // 
    // >  The maximum value is 50. If the number of specified servers exceeds 50, the value 50 is used.
    shared_ptr<int32_t> maxBatchSize_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
