// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_UPDATECHECKITEMRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_UPDATECHECKITEMRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/UpdateCheckItemResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class UpdateCheckItemResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const UpdateCheckItemResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, UpdateCheckItemResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    UpdateCheckItemResponseBody() = default ;
    UpdateCheckItemResponseBody(const UpdateCheckItemResponseBody &) = default ;
    UpdateCheckItemResponseBody(UpdateCheckItemResponseBody &&) = default ;
    UpdateCheckItemResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~UpdateCheckItemResponseBody() = default ;
    UpdateCheckItemResponseBody& operator=(const UpdateCheckItemResponseBody &) = default ;
    UpdateCheckItemResponseBody& operator=(UpdateCheckItemResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->data_ == nullptr
        && return this->requestId_ == nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const UpdateCheckItemResponseBodyData & data() const { DARABONBA_PTR_GET_CONST(data_, UpdateCheckItemResponseBodyData) };
    inline UpdateCheckItemResponseBodyData data() { DARABONBA_PTR_GET(data_, UpdateCheckItemResponseBodyData) };
    inline UpdateCheckItemResponseBody& setData(const UpdateCheckItemResponseBodyData & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline UpdateCheckItemResponseBody& setData(UpdateCheckItemResponseBodyData && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline UpdateCheckItemResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Return data.
    std::shared_ptr<UpdateCheckItemResponseBodyData> data_ = nullptr;
    // ID of the current request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
