// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_UPDATEPOSTPAIDBINDRELRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_UPDATEPOSTPAIDBINDRELRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sas20181203
{
namespace Models
{
  class UpdatePostPaidBindRelResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const UpdatePostPaidBindRelResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(BindCount, bindCount_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(ResultCode, resultCode_);
    };
    friend void from_json(const Darabonba::Json& j, UpdatePostPaidBindRelResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(BindCount, bindCount_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(ResultCode, resultCode_);
    };
    UpdatePostPaidBindRelResponseBody() = default ;
    UpdatePostPaidBindRelResponseBody(const UpdatePostPaidBindRelResponseBody &) = default ;
    UpdatePostPaidBindRelResponseBody(UpdatePostPaidBindRelResponseBody &&) = default ;
    UpdatePostPaidBindRelResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~UpdatePostPaidBindRelResponseBody() = default ;
    UpdatePostPaidBindRelResponseBody& operator=(const UpdatePostPaidBindRelResponseBody &) = default ;
    UpdatePostPaidBindRelResponseBody& operator=(UpdatePostPaidBindRelResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->bindCount_ == nullptr
        && this->requestId_ == nullptr && this->resultCode_ == nullptr; };
    // bindCount Field Functions 
    bool hasBindCount() const { return this->bindCount_ != nullptr;};
    void deleteBindCount() { this->bindCount_ = nullptr;};
    inline int64_t getBindCount() const { DARABONBA_PTR_GET_DEFAULT(bindCount_, 0L) };
    inline UpdatePostPaidBindRelResponseBody& setBindCount(int64_t bindCount) { DARABONBA_PTR_SET_VALUE(bindCount_, bindCount) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline UpdatePostPaidBindRelResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // resultCode Field Functions 
    bool hasResultCode() const { return this->resultCode_ != nullptr;};
    void deleteResultCode() { this->resultCode_ = nullptr;};
    inline int32_t getResultCode() const { DARABONBA_PTR_GET_DEFAULT(resultCode_, 0) };
    inline UpdatePostPaidBindRelResponseBody& setResultCode(int32_t resultCode) { DARABONBA_PTR_SET_VALUE(resultCode_, resultCode) };


  protected:
    // The number of servers that are successfully bound.
    shared_ptr<int64_t> bindCount_ {};
    // The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
    shared_ptr<string> requestId_ {};
    // The binding result status code. Valid values:
    // 
    // - **0**: Success.
    // - **1**: Parameter error.
    // - **2**: Insufficient server authorization quota.
    // - **3**: Insufficient server authorization core quota.
    // - **4**: Pay-as-you-go billing is not activated.
    // - **5**: Service suspended due to overdue payment.
    // - **6**: Serverless protection is not enabled.
    // - **7**: Pay-as-you-go host and container security service is not activated.
    // - **-1**: Binding exception.
    shared_ptr<int32_t> resultCode_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sas20181203
#endif
