// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_YIKE20260707MODEL_HPP_
#define ALIBABACLOUD_YIKE20260707MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BatchGetMediasRequest.hpp>
#include <alibabacloud/models/BatchGetMediasResponseBody.hpp>
#include <alibabacloud/models/BatchGetMediasResponse.hpp>
#include <alibabacloud/models/CreateAssetCategoryRequest.hpp>
#include <alibabacloud/models/CreateAssetCategoryResponseBody.hpp>
#include <alibabacloud/models/CreateAssetCategoryResponse.hpp>
#include <alibabacloud/models/CreateInfiniteCanvasRequest.hpp>
#include <alibabacloud/models/CreateInfiniteCanvasResponseBody.hpp>
#include <alibabacloud/models/CreateInfiniteCanvasResponse.hpp>
#include <alibabacloud/models/DeleteAssetCategoryRequest.hpp>
#include <alibabacloud/models/DeleteAssetCategoryResponseBody.hpp>
#include <alibabacloud/models/DeleteAssetCategoryResponse.hpp>
#include <alibabacloud/models/DeleteInfiniteCanvasRequest.hpp>
#include <alibabacloud/models/DeleteInfiniteCanvasResponseBody.hpp>
#include <alibabacloud/models/DeleteInfiniteCanvasResponse.hpp>
#include <alibabacloud/models/DeleteMediasRequest.hpp>
#include <alibabacloud/models/DeleteMediasResponseBody.hpp>
#include <alibabacloud/models/DeleteMediasResponse.hpp>
#include <alibabacloud/models/GenerateYikeLoginTokenRequest.hpp>
#include <alibabacloud/models/GenerateYikeLoginTokenResponseBody.hpp>
#include <alibabacloud/models/GenerateYikeLoginTokenResponse.hpp>
#include <alibabacloud/models/GetAssetCategoryRequest.hpp>
#include <alibabacloud/models/GetAssetCategoryResponseBody.hpp>
#include <alibabacloud/models/GetAssetCategoryResponse.hpp>
#include <alibabacloud/models/GetImageGenerationJobRequest.hpp>
#include <alibabacloud/models/GetImageGenerationJobResponseBody.hpp>
#include <alibabacloud/models/GetImageGenerationJobResponse.hpp>
#include <alibabacloud/models/GetInfiniteCanvasRequest.hpp>
#include <alibabacloud/models/GetInfiniteCanvasResponseBody.hpp>
#include <alibabacloud/models/GetInfiniteCanvasResponse.hpp>
#include <alibabacloud/models/GetMediaRequest.hpp>
#include <alibabacloud/models/GetMediaResponseBody.hpp>
#include <alibabacloud/models/GetMediaResponse.hpp>
#include <alibabacloud/models/GetMediaComprehensionJobRequest.hpp>
#include <alibabacloud/models/GetMediaComprehensionJobResponseBody.hpp>
#include <alibabacloud/models/GetMediaComprehensionJobResponse.hpp>
#include <alibabacloud/models/GetRemakeScriptJobRequest.hpp>
#include <alibabacloud/models/GetRemakeScriptJobResponseBody.hpp>
#include <alibabacloud/models/GetRemakeScriptJobResponse.hpp>
#include <alibabacloud/models/GetVideoGenerationJobRequest.hpp>
#include <alibabacloud/models/GetVideoGenerationJobResponseBody.hpp>
#include <alibabacloud/models/GetVideoGenerationJobResponse.hpp>
#include <alibabacloud/models/GetVideoRenderJobRequest.hpp>
#include <alibabacloud/models/GetVideoRenderJobResponseBody.hpp>
#include <alibabacloud/models/GetVideoRenderJobResponse.hpp>
#include <alibabacloud/models/GetVideoTranslationJobRequest.hpp>
#include <alibabacloud/models/GetVideoTranslationJobResponseBody.hpp>
#include <alibabacloud/models/GetVideoTranslationJobResponse.hpp>
#include <alibabacloud/models/GetYikeAccountCreditRequest.hpp>
#include <alibabacloud/models/GetYikeAccountCreditResponseBody.hpp>
#include <alibabacloud/models/GetYikeAccountCreditResponse.hpp>
#include <alibabacloud/models/GetYikeJobCreditRequest.hpp>
#include <alibabacloud/models/GetYikeJobCreditResponseBody.hpp>
#include <alibabacloud/models/GetYikeJobCreditResponse.hpp>
#include <alibabacloud/models/ImportMediaRequest.hpp>
#include <alibabacloud/models/ImportMediaResponseBody.hpp>
#include <alibabacloud/models/ImportMediaResponse.hpp>
#include <alibabacloud/models/ListAssetCategoriesRequest.hpp>
#include <alibabacloud/models/ListAssetCategoriesResponseBody.hpp>
#include <alibabacloud/models/ListAssetCategoriesResponse.hpp>
#include <alibabacloud/models/ListInfiniteCanvasesRequest.hpp>
#include <alibabacloud/models/ListInfiniteCanvasesResponseBody.hpp>
#include <alibabacloud/models/ListInfiniteCanvasesResponse.hpp>
#include <alibabacloud/models/SearchMediaRequest.hpp>
#include <alibabacloud/models/SearchMediaResponseBody.hpp>
#include <alibabacloud/models/SearchMediaResponse.hpp>
#include <alibabacloud/models/SubmitImageGenerationJobRequest.hpp>
#include <alibabacloud/models/SubmitImageGenerationJobResponseBody.hpp>
#include <alibabacloud/models/SubmitImageGenerationJobResponse.hpp>
#include <alibabacloud/models/SubmitMediaComprehensionJobRequest.hpp>
#include <alibabacloud/models/SubmitMediaComprehensionJobResponseBody.hpp>
#include <alibabacloud/models/SubmitMediaComprehensionJobResponse.hpp>
#include <alibabacloud/models/SubmitRemakeScriptJobRequest.hpp>
#include <alibabacloud/models/SubmitRemakeScriptJobResponseBody.hpp>
#include <alibabacloud/models/SubmitRemakeScriptJobResponse.hpp>
#include <alibabacloud/models/SubmitVideoGenerationJobRequest.hpp>
#include <alibabacloud/models/SubmitVideoGenerationJobResponseBody.hpp>
#include <alibabacloud/models/SubmitVideoGenerationJobResponse.hpp>
#include <alibabacloud/models/SubmitVideoRenderJobRequest.hpp>
#include <alibabacloud/models/SubmitVideoRenderJobResponseBody.hpp>
#include <alibabacloud/models/SubmitVideoRenderJobResponse.hpp>
#include <alibabacloud/models/SubmitVideoTranslationJobRequest.hpp>
#include <alibabacloud/models/SubmitVideoTranslationJobResponseBody.hpp>
#include <alibabacloud/models/SubmitVideoTranslationJobResponse.hpp>
#include <alibabacloud/models/UpdateAssetCategoryRequest.hpp>
#include <alibabacloud/models/UpdateAssetCategoryResponseBody.hpp>
#include <alibabacloud/models/UpdateAssetCategoryResponse.hpp>
#include <alibabacloud/models/UpdateInfiniteCanvasRequest.hpp>
#include <alibabacloud/models/UpdateInfiniteCanvasResponseBody.hpp>
#include <alibabacloud/models/UpdateInfiniteCanvasResponse.hpp>
#include <alibabacloud/models/UpdateMediaRequest.hpp>
#include <alibabacloud/models/UpdateMediaResponseBody.hpp>
#include <alibabacloud/models/UpdateMediaResponse.hpp>

#endif
