// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MSE20190531MODEL_HPP_
#define ALIBABACLOUD_MSE20190531MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/GatewayDomain.hpp>
#include <alibabacloud/models/GatewayOption.hpp>
#include <alibabacloud/models/GatewayService.hpp>
#include <alibabacloud/models/TrafficPolicy.hpp>
#include <alibabacloud/models/RulesValue.hpp>
#include <alibabacloud/models/DataValue.hpp>
#include <alibabacloud/models/AddAuthPolicyRequest.hpp>
#include <alibabacloud/models/AddAuthPolicyResponseBody.hpp>
#include <alibabacloud/models/AddAuthPolicyResponse.hpp>
#include <alibabacloud/models/AddAuthResourceRequest.hpp>
#include <alibabacloud/models/AddAuthResourceShrinkRequest.hpp>
#include <alibabacloud/models/AddAuthResourceResponseBody.hpp>
#include <alibabacloud/models/AddAuthResourceResponse.hpp>
#include <alibabacloud/models/AddBlackWhiteListRequest.hpp>
#include <alibabacloud/models/AddBlackWhiteListResponseBody.hpp>
#include <alibabacloud/models/AddBlackWhiteListResponse.hpp>
#include <alibabacloud/models/AddGatewayRequest.hpp>
#include <alibabacloud/models/AddGatewayShrinkRequest.hpp>
#include <alibabacloud/models/AddGatewayResponseBody.hpp>
#include <alibabacloud/models/AddGatewayResponse.hpp>
#include <alibabacloud/models/AddGatewayAuthRequest.hpp>
#include <alibabacloud/models/AddGatewayAuthShrinkRequest.hpp>
#include <alibabacloud/models/AddGatewayAuthResponseBody.hpp>
#include <alibabacloud/models/AddGatewayAuthResponse.hpp>
#include <alibabacloud/models/AddGatewayAuthConsumerRequest.hpp>
#include <alibabacloud/models/AddGatewayAuthConsumerResponseBody.hpp>
#include <alibabacloud/models/AddGatewayAuthConsumerResponse.hpp>
#include <alibabacloud/models/AddGatewayDomainRequest.hpp>
#include <alibabacloud/models/AddGatewayDomainShrinkRequest.hpp>
#include <alibabacloud/models/AddGatewayDomainResponseBody.hpp>
#include <alibabacloud/models/AddGatewayDomainResponse.hpp>
#include <alibabacloud/models/AddGatewayRouteRequest.hpp>
#include <alibabacloud/models/AddGatewayRouteShrinkRequest.hpp>
#include <alibabacloud/models/AddGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/AddGatewayRouteResponse.hpp>
#include <alibabacloud/models/AddGatewayServiceVersionRequest.hpp>
#include <alibabacloud/models/AddGatewayServiceVersionResponseBody.hpp>
#include <alibabacloud/models/AddGatewayServiceVersionResponse.hpp>
#include <alibabacloud/models/AddGatewaySlbRequest.hpp>
#include <alibabacloud/models/AddGatewaySlbShrinkRequest.hpp>
#include <alibabacloud/models/AddGatewaySlbResponseBody.hpp>
#include <alibabacloud/models/AddGatewaySlbResponse.hpp>
#include <alibabacloud/models/AddMigrationTaskRequest.hpp>
#include <alibabacloud/models/AddMigrationTaskResponseBody.hpp>
#include <alibabacloud/models/AddMigrationTaskResponse.hpp>
#include <alibabacloud/models/AddMockRuleRequest.hpp>
#include <alibabacloud/models/AddMockRuleResponseBody.hpp>
#include <alibabacloud/models/AddMockRuleResponse.hpp>
#include <alibabacloud/models/AddSslcertRequest.hpp>
#include <alibabacloud/models/AddSslcertResponseBody.hpp>
#include <alibabacloud/models/AddSslcertResponse.hpp>
#include <alibabacloud/models/AddSecurityGroupRuleRequest.hpp>
#include <alibabacloud/models/AddSecurityGroupRuleResponseBody.hpp>
#include <alibabacloud/models/AddSecurityGroupRuleResponse.hpp>
#include <alibabacloud/models/AddServiceSourceRequest.hpp>
#include <alibabacloud/models/AddServiceSourceShrinkRequest.hpp>
#include <alibabacloud/models/AddServiceSourceResponseBody.hpp>
#include <alibabacloud/models/AddServiceSourceResponse.hpp>
#include <alibabacloud/models/ApplyGatewayRouteRequest.hpp>
#include <alibabacloud/models/ApplyGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/ApplyGatewayRouteResponse.hpp>
#include <alibabacloud/models/ApplyTagPoliciesRequest.hpp>
#include <alibabacloud/models/ApplyTagPoliciesShrinkRequest.hpp>
#include <alibabacloud/models/ApplyTagPoliciesResponseBody.hpp>
#include <alibabacloud/models/ApplyTagPoliciesResponse.hpp>
#include <alibabacloud/models/BindSentinelBlockFallbackDefinitionRequest.hpp>
#include <alibabacloud/models/BindSentinelBlockFallbackDefinitionResponseBody.hpp>
#include <alibabacloud/models/BindSentinelBlockFallbackDefinitionResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CloneNacosConfigRequest.hpp>
#include <alibabacloud/models/CloneNacosConfigResponseBody.hpp>
#include <alibabacloud/models/CloneNacosConfigResponse.hpp>
#include <alibabacloud/models/CloneSentinelRuleFromAhasRequest.hpp>
#include <alibabacloud/models/CloneSentinelRuleFromAhasResponseBody.hpp>
#include <alibabacloud/models/CloneSentinelRuleFromAhasResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationShrinkRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/CreateCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/CreateCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/CreateClusterRequest.hpp>
#include <alibabacloud/models/CreateClusterResponseBody.hpp>
#include <alibabacloud/models/CreateClusterResponse.hpp>
#include <alibabacloud/models/CreateEngineNamespaceRequest.hpp>
#include <alibabacloud/models/CreateEngineNamespaceResponseBody.hpp>
#include <alibabacloud/models/CreateEngineNamespaceResponse.hpp>
#include <alibabacloud/models/CreateFlowRuleRequest.hpp>
#include <alibabacloud/models/CreateFlowRuleResponseBody.hpp>
#include <alibabacloud/models/CreateFlowRuleResponse.hpp>
#include <alibabacloud/models/CreateGatewayCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/CreateGatewayCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/CreateGatewayCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/CreateGatewayFlowRuleRequest.hpp>
#include <alibabacloud/models/CreateGatewayFlowRuleResponseBody.hpp>
#include <alibabacloud/models/CreateGatewayFlowRuleResponse.hpp>
#include <alibabacloud/models/CreateGatewayIsolationRuleRequest.hpp>
#include <alibabacloud/models/CreateGatewayIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/CreateGatewayIsolationRuleResponse.hpp>
#include <alibabacloud/models/CreateIsolationRuleRequest.hpp>
#include <alibabacloud/models/CreateIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/CreateIsolationRuleResponse.hpp>
#include <alibabacloud/models/CreateMseServiceApplicationRequest.hpp>
#include <alibabacloud/models/CreateMseServiceApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateMseServiceApplicationResponse.hpp>
#include <alibabacloud/models/CreateNacosConfigRequest.hpp>
#include <alibabacloud/models/CreateNacosConfigResponseBody.hpp>
#include <alibabacloud/models/CreateNacosConfigResponse.hpp>
#include <alibabacloud/models/CreateNacosInstanceRequest.hpp>
#include <alibabacloud/models/CreateNacosInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateNacosInstanceResponse.hpp>
#include <alibabacloud/models/CreateNacosServiceRequest.hpp>
#include <alibabacloud/models/CreateNacosServiceResponseBody.hpp>
#include <alibabacloud/models/CreateNacosServiceResponse.hpp>
#include <alibabacloud/models/CreateNamespaceRequest.hpp>
#include <alibabacloud/models/CreateNamespaceShrinkRequest.hpp>
#include <alibabacloud/models/CreateNamespaceResponseBody.hpp>
#include <alibabacloud/models/CreateNamespaceResponse.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequest.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneShrinkRequest.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneResponseBody.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneResponse.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneGroupRequest.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneGroupShrinkRequest.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneGroupResponseBody.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneGroupResponse.hpp>
#include <alibabacloud/models/CreatePluginConfigRequest.hpp>
#include <alibabacloud/models/CreatePluginConfigShrinkRequest.hpp>
#include <alibabacloud/models/CreatePluginConfigResponseBody.hpp>
#include <alibabacloud/models/CreatePluginConfigResponse.hpp>
#include <alibabacloud/models/CreateSentinelBlockFallbackDefinitionRequest.hpp>
#include <alibabacloud/models/CreateSentinelBlockFallbackDefinitionResponseBody.hpp>
#include <alibabacloud/models/CreateSentinelBlockFallbackDefinitionResponse.hpp>
#include <alibabacloud/models/CreateWebFlowRuleRequest.hpp>
#include <alibabacloud/models/CreateWebFlowRuleResponseBody.hpp>
#include <alibabacloud/models/CreateWebFlowRuleResponse.hpp>
#include <alibabacloud/models/CreateZnodeRequest.hpp>
#include <alibabacloud/models/CreateZnodeResponseBody.hpp>
#include <alibabacloud/models/CreateZnodeResponse.hpp>
#include <alibabacloud/models/DeleteAuthResourceRequest.hpp>
#include <alibabacloud/models/DeleteAuthResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteAuthResourceResponse.hpp>
#include <alibabacloud/models/DeleteCircuitBreakerRulesRequest.hpp>
#include <alibabacloud/models/DeleteCircuitBreakerRulesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteCircuitBreakerRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteCircuitBreakerRulesResponse.hpp>
#include <alibabacloud/models/DeleteClusterRequest.hpp>
#include <alibabacloud/models/DeleteClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteClusterResponse.hpp>
#include <alibabacloud/models/DeleteEngineNamespaceRequest.hpp>
#include <alibabacloud/models/DeleteEngineNamespaceResponseBody.hpp>
#include <alibabacloud/models/DeleteEngineNamespaceResponse.hpp>
#include <alibabacloud/models/DeleteFlowRulesRequest.hpp>
#include <alibabacloud/models/DeleteFlowRulesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteFlowRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteFlowRulesResponse.hpp>
#include <alibabacloud/models/DeleteGatewayRequest.hpp>
#include <alibabacloud/models/DeleteGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayResponse.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerRequest.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerResponse.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerResourceRequest.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayAuthConsumerResourceResponse.hpp>
#include <alibabacloud/models/DeleteGatewayCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/DeleteGatewayCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/DeleteGatewayDomainRequest.hpp>
#include <alibabacloud/models/DeleteGatewayDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayDomainResponse.hpp>
#include <alibabacloud/models/DeleteGatewayFlowRuleRequest.hpp>
#include <alibabacloud/models/DeleteGatewayFlowRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayFlowRuleResponse.hpp>
#include <alibabacloud/models/DeleteGatewayIsolationRuleRequest.hpp>
#include <alibabacloud/models/DeleteGatewayIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayIsolationRuleResponse.hpp>
#include <alibabacloud/models/DeleteGatewayRouteRequest.hpp>
#include <alibabacloud/models/DeleteGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayRouteResponse.hpp>
#include <alibabacloud/models/DeleteGatewayServiceRequest.hpp>
#include <alibabacloud/models/DeleteGatewayServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayServiceResponse.hpp>
#include <alibabacloud/models/DeleteGatewayServiceVersionRequest.hpp>
#include <alibabacloud/models/DeleteGatewayServiceVersionResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayServiceVersionResponse.hpp>
#include <alibabacloud/models/DeleteGatewaySlbRequest.hpp>
#include <alibabacloud/models/DeleteGatewaySlbResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewaySlbResponse.hpp>
#include <alibabacloud/models/DeleteIsolationRulesRequest.hpp>
#include <alibabacloud/models/DeleteIsolationRulesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteIsolationRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteIsolationRulesResponse.hpp>
#include <alibabacloud/models/DeleteMigrationTaskRequest.hpp>
#include <alibabacloud/models/DeleteMigrationTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteMigrationTaskResponse.hpp>
#include <alibabacloud/models/DeleteNacosConfigRequest.hpp>
#include <alibabacloud/models/DeleteNacosConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteNacosConfigResponse.hpp>
#include <alibabacloud/models/DeleteNacosConfigsRequest.hpp>
#include <alibabacloud/models/DeleteNacosConfigsResponseBody.hpp>
#include <alibabacloud/models/DeleteNacosConfigsResponse.hpp>
#include <alibabacloud/models/DeleteNacosInstanceRequest.hpp>
#include <alibabacloud/models/DeleteNacosInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteNacosInstanceResponse.hpp>
#include <alibabacloud/models/DeleteNacosServiceRequest.hpp>
#include <alibabacloud/models/DeleteNacosServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteNacosServiceResponse.hpp>
#include <alibabacloud/models/DeleteNamespaceRequest.hpp>
#include <alibabacloud/models/DeleteNamespaceResponseBody.hpp>
#include <alibabacloud/models/DeleteNamespaceResponse.hpp>
#include <alibabacloud/models/DeletePluginConfigRequest.hpp>
#include <alibabacloud/models/DeletePluginConfigResponseBody.hpp>
#include <alibabacloud/models/DeletePluginConfigResponse.hpp>
#include <alibabacloud/models/DeleteSecurityGroupRuleRequest.hpp>
#include <alibabacloud/models/DeleteSecurityGroupRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteSecurityGroupRuleResponse.hpp>
#include <alibabacloud/models/DeleteServiceSourceRequest.hpp>
#include <alibabacloud/models/DeleteServiceSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceSourceResponse.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneRequest.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneResponseBody.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneResponse.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneGroupRequest.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteSwimmingLaneGroupResponse.hpp>
#include <alibabacloud/models/DeleteWebFlowRulesRequest.hpp>
#include <alibabacloud/models/DeleteWebFlowRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteWebFlowRulesResponse.hpp>
#include <alibabacloud/models/DeleteZnodeRequest.hpp>
#include <alibabacloud/models/DeleteZnodeResponseBody.hpp>
#include <alibabacloud/models/DeleteZnodeResponse.hpp>
#include <alibabacloud/models/EnableHttp2request.hpp>
#include <alibabacloud/models/EnableHttp2responseBody.hpp>
#include <alibabacloud/models/EnableHttp2response.hpp>
#include <alibabacloud/models/EnableProxyProtocolRequest.hpp>
#include <alibabacloud/models/EnableProxyProtocolResponseBody.hpp>
#include <alibabacloud/models/EnableProxyProtocolResponse.hpp>
#include <alibabacloud/models/ExportNacosConfigRequest.hpp>
#include <alibabacloud/models/ExportNacosConfigResponseBody.hpp>
#include <alibabacloud/models/ExportNacosConfigResponse.hpp>
#include <alibabacloud/models/ExportZookeeperDataRequest.hpp>
#include <alibabacloud/models/ExportZookeeperDataResponseBody.hpp>
#include <alibabacloud/models/ExportZookeeperDataResponse.hpp>
#include <alibabacloud/models/FetchLosslessRuleListRequest.hpp>
#include <alibabacloud/models/FetchLosslessRuleListResponseBody.hpp>
#include <alibabacloud/models/FetchLosslessRuleListResponse.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListRequest.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListShrinkRequest.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListResponseBody.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListResponse.hpp>
#include <alibabacloud/models/GetAppMessageQueueRouteRequest.hpp>
#include <alibabacloud/models/GetAppMessageQueueRouteResponseBody.hpp>
#include <alibabacloud/models/GetAppMessageQueueRouteResponse.hpp>
#include <alibabacloud/models/GetApplicationInstanceListRequest.hpp>
#include <alibabacloud/models/GetApplicationInstanceListResponseBody.hpp>
#include <alibabacloud/models/GetApplicationInstanceListResponse.hpp>
#include <alibabacloud/models/GetApplicationListRequest.hpp>
#include <alibabacloud/models/GetApplicationListShrinkRequest.hpp>
#include <alibabacloud/models/GetApplicationListResponseBody.hpp>
#include <alibabacloud/models/GetApplicationListResponse.hpp>
#include <alibabacloud/models/GetBlackWhiteListRequest.hpp>
#include <alibabacloud/models/GetBlackWhiteListResponseBody.hpp>
#include <alibabacloud/models/GetBlackWhiteListResponse.hpp>
#include <alibabacloud/models/GetEngineNamepaceRequest.hpp>
#include <alibabacloud/models/GetEngineNamepaceResponseBody.hpp>
#include <alibabacloud/models/GetEngineNamepaceResponse.hpp>
#include <alibabacloud/models/GetGatewayRequest.hpp>
#include <alibabacloud/models/GetGatewayResponseBody.hpp>
#include <alibabacloud/models/GetGatewayResponse.hpp>
#include <alibabacloud/models/GetGatewayAuthConsumerDetailRequest.hpp>
#include <alibabacloud/models/GetGatewayAuthConsumerDetailResponseBody.hpp>
#include <alibabacloud/models/GetGatewayAuthConsumerDetailResponse.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailRequest.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBody.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponse.hpp>
#include <alibabacloud/models/GetGatewayConfigRequest.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBody.hpp>
#include <alibabacloud/models/GetGatewayConfigResponse.hpp>
#include <alibabacloud/models/GetGatewayDomainDetailRequest.hpp>
#include <alibabacloud/models/GetGatewayDomainDetailResponseBody.hpp>
#include <alibabacloud/models/GetGatewayDomainDetailResponse.hpp>
#include <alibabacloud/models/GetGatewayOptionRequest.hpp>
#include <alibabacloud/models/GetGatewayOptionResponseBody.hpp>
#include <alibabacloud/models/GetGatewayOptionResponse.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailRequest.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBody.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponse.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailRequest.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBody.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponse.hpp>
#include <alibabacloud/models/GetGovernanceKubernetesClusterRequest.hpp>
#include <alibabacloud/models/GetGovernanceKubernetesClusterResponseBody.hpp>
#include <alibabacloud/models/GetGovernanceKubernetesClusterResponse.hpp>
#include <alibabacloud/models/GetImageRequest.hpp>
#include <alibabacloud/models/GetImageResponseBody.hpp>
#include <alibabacloud/models/GetImageResponse.hpp>
#include <alibabacloud/models/GetImportFileUrlRequest.hpp>
#include <alibabacloud/models/GetImportFileUrlResponseBody.hpp>
#include <alibabacloud/models/GetImportFileUrlResponse.hpp>
#include <alibabacloud/models/GetKubernetesSourceRequest.hpp>
#include <alibabacloud/models/GetKubernetesSourceResponseBody.hpp>
#include <alibabacloud/models/GetKubernetesSourceResponse.hpp>
#include <alibabacloud/models/GetLocalityRuleRequest.hpp>
#include <alibabacloud/models/GetLocalityRuleResponseBody.hpp>
#include <alibabacloud/models/GetLocalityRuleResponse.hpp>
#include <alibabacloud/models/GetLosslessRuleByAppRequest.hpp>
#include <alibabacloud/models/GetLosslessRuleByAppResponseBody.hpp>
#include <alibabacloud/models/GetLosslessRuleByAppResponse.hpp>
#include <alibabacloud/models/GetMseFeatureSwitchRequest.hpp>
#include <alibabacloud/models/GetMseFeatureSwitchResponseBody.hpp>
#include <alibabacloud/models/GetMseFeatureSwitchResponse.hpp>
#include <alibabacloud/models/GetMseSourceRequest.hpp>
#include <alibabacloud/models/GetMseSourceResponseBody.hpp>
#include <alibabacloud/models/GetMseSourceResponse.hpp>
#include <alibabacloud/models/GetNacosConfigRequest.hpp>
#include <alibabacloud/models/GetNacosConfigResponseBody.hpp>
#include <alibabacloud/models/GetNacosConfigResponse.hpp>
#include <alibabacloud/models/GetNacosHistoryConfigRequest.hpp>
#include <alibabacloud/models/GetNacosHistoryConfigResponseBody.hpp>
#include <alibabacloud/models/GetNacosHistoryConfigResponse.hpp>
#include <alibabacloud/models/GetOverviewRequest.hpp>
#include <alibabacloud/models/GetOverviewResponseBody.hpp>
#include <alibabacloud/models/GetOverviewResponse.hpp>
#include <alibabacloud/models/GetPluginConfigRequest.hpp>
#include <alibabacloud/models/GetPluginConfigResponseBody.hpp>
#include <alibabacloud/models/GetPluginConfigResponse.hpp>
#include <alibabacloud/models/GetPluginsRequest.hpp>
#include <alibabacloud/models/GetPluginsResponseBody.hpp>
#include <alibabacloud/models/GetPluginsResponse.hpp>
#include <alibabacloud/models/GetServiceListRequest.hpp>
#include <alibabacloud/models/GetServiceListResponseBody.hpp>
#include <alibabacloud/models/GetServiceListResponse.hpp>
#include <alibabacloud/models/GetServiceListPageRequest.hpp>
#include <alibabacloud/models/GetServiceListPageResponseBody.hpp>
#include <alibabacloud/models/GetServiceListPageResponse.hpp>
#include <alibabacloud/models/GetServiceListenersRequest.hpp>
#include <alibabacloud/models/GetServiceListenersResponseBody.hpp>
#include <alibabacloud/models/GetServiceListenersResponse.hpp>
#include <alibabacloud/models/GetServiceMethodPageRequest.hpp>
#include <alibabacloud/models/GetServiceMethodPageResponseBody.hpp>
#include <alibabacloud/models/GetServiceMethodPageResponse.hpp>
#include <alibabacloud/models/GetTagsBySwimmingLaneGroupIdRequest.hpp>
#include <alibabacloud/models/GetTagsBySwimmingLaneGroupIdResponseBody.hpp>
#include <alibabacloud/models/GetTagsBySwimmingLaneGroupIdResponse.hpp>
#include <alibabacloud/models/GetZookeeperDataImportUrlRequest.hpp>
#include <alibabacloud/models/GetZookeeperDataImportUrlResponseBody.hpp>
#include <alibabacloud/models/GetZookeeperDataImportUrlResponse.hpp>
#include <alibabacloud/models/ImportNacosConfigRequest.hpp>
#include <alibabacloud/models/ImportNacosConfigResponseBody.hpp>
#include <alibabacloud/models/ImportNacosConfigResponse.hpp>
#include <alibabacloud/models/ImportServicesRequest.hpp>
#include <alibabacloud/models/ImportServicesShrinkRequest.hpp>
#include <alibabacloud/models/ImportServicesResponseBody.hpp>
#include <alibabacloud/models/ImportServicesResponse.hpp>
#include <alibabacloud/models/ImportZookeeperDataRequest.hpp>
#include <alibabacloud/models/ImportZookeeperDataResponseBody.hpp>
#include <alibabacloud/models/ImportZookeeperDataResponse.hpp>
#include <alibabacloud/models/InitializeServiceLinkRoleRequest.hpp>
#include <alibabacloud/models/InitializeServiceLinkRoleResponseBody.hpp>
#include <alibabacloud/models/InitializeServiceLinkRoleResponse.hpp>
#include <alibabacloud/models/ListAnsInstancesRequest.hpp>
#include <alibabacloud/models/ListAnsInstancesResponseBody.hpp>
#include <alibabacloud/models/ListAnsInstancesResponse.hpp>
#include <alibabacloud/models/ListAnsServiceClustersRequest.hpp>
#include <alibabacloud/models/ListAnsServiceClustersResponseBody.hpp>
#include <alibabacloud/models/ListAnsServiceClustersResponse.hpp>
#include <alibabacloud/models/ListAnsServicesRequest.hpp>
#include <alibabacloud/models/ListAnsServicesResponseBody.hpp>
#include <alibabacloud/models/ListAnsServicesResponse.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagRequest.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagResponseBody.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagResponse.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagsRequest.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagsShrinkRequest.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagsResponseBody.hpp>
#include <alibabacloud/models/ListAppBySwimmingLaneGroupTagsResponse.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesRequest.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBody.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponse.hpp>
#include <alibabacloud/models/ListAuthPolicyRequest.hpp>
#include <alibabacloud/models/ListAuthPolicyResponseBody.hpp>
#include <alibabacloud/models/ListAuthPolicyResponse.hpp>
#include <alibabacloud/models/ListCircuitBreakerRulesRequest.hpp>
#include <alibabacloud/models/ListCircuitBreakerRulesResponseBody.hpp>
#include <alibabacloud/models/ListCircuitBreakerRulesResponse.hpp>
#include <alibabacloud/models/ListClusterConnectionTypesRequest.hpp>
#include <alibabacloud/models/ListClusterConnectionTypesResponseBody.hpp>
#include <alibabacloud/models/ListClusterConnectionTypesResponse.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskRequest.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskResponseBody.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskResponse.hpp>
#include <alibabacloud/models/ListClusterTypesRequest.hpp>
#include <alibabacloud/models/ListClusterTypesResponseBody.hpp>
#include <alibabacloud/models/ListClusterTypesResponse.hpp>
#include <alibabacloud/models/ListClusterVersionsRequest.hpp>
#include <alibabacloud/models/ListClusterVersionsResponseBody.hpp>
#include <alibabacloud/models/ListClusterVersionsResponse.hpp>
#include <alibabacloud/models/ListClustersRequest.hpp>
#include <alibabacloud/models/ListClustersResponseBody.hpp>
#include <alibabacloud/models/ListClustersResponse.hpp>
#include <alibabacloud/models/ListConfigTrackRequest.hpp>
#include <alibabacloud/models/ListConfigTrackResponseBody.hpp>
#include <alibabacloud/models/ListConfigTrackResponse.hpp>
#include <alibabacloud/models/ListEngineNamespacesRequest.hpp>
#include <alibabacloud/models/ListEngineNamespacesResponseBody.hpp>
#include <alibabacloud/models/ListEngineNamespacesResponse.hpp>
#include <alibabacloud/models/ListEurekaInstancesRequest.hpp>
#include <alibabacloud/models/ListEurekaInstancesResponseBody.hpp>
#include <alibabacloud/models/ListEurekaInstancesResponse.hpp>
#include <alibabacloud/models/ListEurekaServicesRequest.hpp>
#include <alibabacloud/models/ListEurekaServicesResponseBody.hpp>
#include <alibabacloud/models/ListEurekaServicesResponse.hpp>
#include <alibabacloud/models/ListExportZookeeperDataRequest.hpp>
#include <alibabacloud/models/ListExportZookeeperDataResponseBody.hpp>
#include <alibabacloud/models/ListExportZookeeperDataResponse.hpp>
#include <alibabacloud/models/ListFlowRulesRequest.hpp>
#include <alibabacloud/models/ListFlowRulesResponseBody.hpp>
#include <alibabacloud/models/ListFlowRulesResponse.hpp>
#include <alibabacloud/models/ListGatewayRequest.hpp>
#include <alibabacloud/models/ListGatewayShrinkRequest.hpp>
#include <alibabacloud/models/ListGatewayResponseBody.hpp>
#include <alibabacloud/models/ListGatewayResponse.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerRequest.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResponseBody.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResponse.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResourceRequest.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResourceResponseBody.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResourceResponse.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/ListGatewayDomainRequest.hpp>
#include <alibabacloud/models/ListGatewayDomainResponseBody.hpp>
#include <alibabacloud/models/ListGatewayDomainResponse.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleRequest.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleResponseBody.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleResponse.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleRequest.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleResponse.hpp>
#include <alibabacloud/models/ListGatewayRouteRequest.hpp>
#include <alibabacloud/models/ListGatewayRouteShrinkRequest.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/ListGatewayRouteResponse.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthRequest.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthResponseBody.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthResponse.hpp>
#include <alibabacloud/models/ListGatewayServiceRequest.hpp>
#include <alibabacloud/models/ListGatewayServiceShrinkRequest.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBody.hpp>
#include <alibabacloud/models/ListGatewayServiceResponse.hpp>
#include <alibabacloud/models/ListGatewaySlbRequest.hpp>
#include <alibabacloud/models/ListGatewaySlbResponseBody.hpp>
#include <alibabacloud/models/ListGatewaySlbResponse.hpp>
#include <alibabacloud/models/ListGatewayZoneRequest.hpp>
#include <alibabacloud/models/ListGatewayZoneResponseBody.hpp>
#include <alibabacloud/models/ListGatewayZoneResponse.hpp>
#include <alibabacloud/models/ListInstanceCountRequest.hpp>
#include <alibabacloud/models/ListInstanceCountResponseBody.hpp>
#include <alibabacloud/models/ListInstanceCountResponse.hpp>
#include <alibabacloud/models/ListIsolationRulesRequest.hpp>
#include <alibabacloud/models/ListIsolationRulesResponseBody.hpp>
#include <alibabacloud/models/ListIsolationRulesResponse.hpp>
#include <alibabacloud/models/ListListenersByConfigRequest.hpp>
#include <alibabacloud/models/ListListenersByConfigShrinkRequest.hpp>
#include <alibabacloud/models/ListListenersByConfigResponseBody.hpp>
#include <alibabacloud/models/ListListenersByConfigResponse.hpp>
#include <alibabacloud/models/ListListenersByIpRequest.hpp>
#include <alibabacloud/models/ListListenersByIpResponseBody.hpp>
#include <alibabacloud/models/ListListenersByIpResponse.hpp>
#include <alibabacloud/models/ListMigrationTaskRequest.hpp>
#include <alibabacloud/models/ListMigrationTaskResponseBody.hpp>
#include <alibabacloud/models/ListMigrationTaskResponse.hpp>
#include <alibabacloud/models/ListNacosConfigsRequest.hpp>
#include <alibabacloud/models/ListNacosConfigsResponseBody.hpp>
#include <alibabacloud/models/ListNacosConfigsResponse.hpp>
#include <alibabacloud/models/ListNacosHistoryConfigsRequest.hpp>
#include <alibabacloud/models/ListNacosHistoryConfigsResponseBody.hpp>
#include <alibabacloud/models/ListNacosHistoryConfigsResponse.hpp>
#include <alibabacloud/models/ListNamespacesRequest.hpp>
#include <alibabacloud/models/ListNamespacesShrinkRequest.hpp>
#include <alibabacloud/models/ListNamespacesResponseBody.hpp>
#include <alibabacloud/models/ListNamespacesResponse.hpp>
#include <alibabacloud/models/ListNamingTrackRequest.hpp>
#include <alibabacloud/models/ListNamingTrackResponseBody.hpp>
#include <alibabacloud/models/ListNamingTrackResponse.hpp>
#include <alibabacloud/models/ListSslcertRequest.hpp>
#include <alibabacloud/models/ListSslcertResponseBody.hpp>
#include <alibabacloud/models/ListSslcertResponse.hpp>
#include <alibabacloud/models/ListSecurityGroupRequest.hpp>
#include <alibabacloud/models/ListSecurityGroupResponseBody.hpp>
#include <alibabacloud/models/ListSecurityGroupResponse.hpp>
#include <alibabacloud/models/ListSecurityGroupRuleRequest.hpp>
#include <alibabacloud/models/ListSecurityGroupRuleResponseBody.hpp>
#include <alibabacloud/models/ListSecurityGroupRuleResponse.hpp>
#include <alibabacloud/models/ListSentinelBlockFallbackDefinitionsRequest.hpp>
#include <alibabacloud/models/ListSentinelBlockFallbackDefinitionsShrinkRequest.hpp>
#include <alibabacloud/models/ListSentinelBlockFallbackDefinitionsResponseBody.hpp>
#include <alibabacloud/models/ListSentinelBlockFallbackDefinitionsResponse.hpp>
#include <alibabacloud/models/ListServiceSourceRequest.hpp>
#include <alibabacloud/models/ListServiceSourceResponseBody.hpp>
#include <alibabacloud/models/ListServiceSourceResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListWebFlowRulesRequest.hpp>
#include <alibabacloud/models/ListWebFlowRulesResponseBody.hpp>
#include <alibabacloud/models/ListWebFlowRulesResponse.hpp>
#include <alibabacloud/models/ListZkTrackRequest.hpp>
#include <alibabacloud/models/ListZkTrackResponseBody.hpp>
#include <alibabacloud/models/ListZkTrackResponse.hpp>
#include <alibabacloud/models/ListZnodeChildrenRequest.hpp>
#include <alibabacloud/models/ListZnodeChildrenResponseBody.hpp>
#include <alibabacloud/models/ListZnodeChildrenResponse.hpp>
#include <alibabacloud/models/ModifyGovernanceKubernetesClusterRequest.hpp>
#include <alibabacloud/models/ModifyGovernanceKubernetesClusterShrinkRequest.hpp>
#include <alibabacloud/models/ModifyGovernanceKubernetesClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyGovernanceKubernetesClusterResponse.hpp>
#include <alibabacloud/models/ModifyLosslessRuleRequest.hpp>
#include <alibabacloud/models/ModifyLosslessRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyLosslessRuleResponse.hpp>
#include <alibabacloud/models/OfflineGatewayRouteRequest.hpp>
#include <alibabacloud/models/OfflineGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/OfflineGatewayRouteResponse.hpp>
#include <alibabacloud/models/OrderClusterHealthCheckRiskNoticeRequest.hpp>
#include <alibabacloud/models/OrderClusterHealthCheckRiskNoticeResponseBody.hpp>
#include <alibabacloud/models/OrderClusterHealthCheckRiskNoticeResponse.hpp>
#include <alibabacloud/models/PreserveHeaderFormatRequest.hpp>
#include <alibabacloud/models/PreserveHeaderFormatResponseBody.hpp>
#include <alibabacloud/models/PreserveHeaderFormatResponse.hpp>
#include <alibabacloud/models/PullServicesRequest.hpp>
#include <alibabacloud/models/PullServicesResponseBody.hpp>
#include <alibabacloud/models/PullServicesResponse.hpp>
#include <alibabacloud/models/PutClusterHealthCheckTaskRequest.hpp>
#include <alibabacloud/models/PutClusterHealthCheckTaskResponseBody.hpp>
#include <alibabacloud/models/PutClusterHealthCheckTaskResponse.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneRequest.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBody.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponse.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneGroupRequest.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneGroupResponseBody.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneGroupResponse.hpp>
#include <alibabacloud/models/QueryBusinessLocationsRequest.hpp>
#include <alibabacloud/models/QueryBusinessLocationsResponseBody.hpp>
#include <alibabacloud/models/QueryBusinessLocationsResponse.hpp>
#include <alibabacloud/models/QueryClusterDetailRequest.hpp>
#include <alibabacloud/models/QueryClusterDetailResponseBody.hpp>
#include <alibabacloud/models/QueryClusterDetailResponse.hpp>
#include <alibabacloud/models/QueryClusterDiskSpecificationRequest.hpp>
#include <alibabacloud/models/QueryClusterDiskSpecificationResponseBody.hpp>
#include <alibabacloud/models/QueryClusterDiskSpecificationResponse.hpp>
#include <alibabacloud/models/QueryClusterInfoRequest.hpp>
#include <alibabacloud/models/QueryClusterInfoResponseBody.hpp>
#include <alibabacloud/models/QueryClusterInfoResponse.hpp>
#include <alibabacloud/models/QueryClusterSpecificationRequest.hpp>
#include <alibabacloud/models/QueryClusterSpecificationResponseBody.hpp>
#include <alibabacloud/models/QueryClusterSpecificationResponse.hpp>
#include <alibabacloud/models/QueryConfigRequest.hpp>
#include <alibabacloud/models/QueryConfigResponseBody.hpp>
#include <alibabacloud/models/QueryConfigResponse.hpp>
#include <alibabacloud/models/QueryGatewayRegionRequest.hpp>
#include <alibabacloud/models/QueryGatewayRegionResponseBody.hpp>
#include <alibabacloud/models/QueryGatewayRegionResponse.hpp>
#include <alibabacloud/models/QueryGatewayTypeRequest.hpp>
#include <alibabacloud/models/QueryGatewayTypeResponseBody.hpp>
#include <alibabacloud/models/QueryGatewayTypeResponse.hpp>
#include <alibabacloud/models/QueryGovernanceKubernetesClusterRequest.hpp>
#include <alibabacloud/models/QueryGovernanceKubernetesClusterResponseBody.hpp>
#include <alibabacloud/models/QueryGovernanceKubernetesClusterResponse.hpp>
#include <alibabacloud/models/QueryInstancesInfoRequest.hpp>
#include <alibabacloud/models/QueryInstancesInfoResponseBody.hpp>
#include <alibabacloud/models/QueryInstancesInfoResponse.hpp>
#include <alibabacloud/models/QueryMonitorRequest.hpp>
#include <alibabacloud/models/QueryMonitorResponseBody.hpp>
#include <alibabacloud/models/QueryMonitorResponse.hpp>
#include <alibabacloud/models/QueryNamespaceRequest.hpp>
#include <alibabacloud/models/QueryNamespaceResponseBody.hpp>
#include <alibabacloud/models/QueryNamespaceResponse.hpp>
#include <alibabacloud/models/QuerySlbSpecRequest.hpp>
#include <alibabacloud/models/QuerySlbSpecResponseBody.hpp>
#include <alibabacloud/models/QuerySlbSpecResponse.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdRequest.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdResponseBody.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdResponse.hpp>
#include <alibabacloud/models/QueryZnodeDetailRequest.hpp>
#include <alibabacloud/models/QueryZnodeDetailResponseBody.hpp>
#include <alibabacloud/models/QueryZnodeDetailResponse.hpp>
#include <alibabacloud/models/RemoveApplicationRequest.hpp>
#include <alibabacloud/models/RemoveApplicationResponseBody.hpp>
#include <alibabacloud/models/RemoveApplicationResponse.hpp>
#include <alibabacloud/models/RemoveAuthPolicyRequest.hpp>
#include <alibabacloud/models/RemoveAuthPolicyResponseBody.hpp>
#include <alibabacloud/models/RemoveAuthPolicyResponse.hpp>
#include <alibabacloud/models/RestartClusterRequest.hpp>
#include <alibabacloud/models/RestartClusterResponseBody.hpp>
#include <alibabacloud/models/RestartClusterResponse.hpp>
#include <alibabacloud/models/RetryClusterRequest.hpp>
#include <alibabacloud/models/RetryClusterResponseBody.hpp>
#include <alibabacloud/models/RetryClusterResponse.hpp>
#include <alibabacloud/models/SelectGatewaySlbRequest.hpp>
#include <alibabacloud/models/SelectGatewaySlbResponseBody.hpp>
#include <alibabacloud/models/SelectGatewaySlbResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAclRequest.hpp>
#include <alibabacloud/models/UpdateAclResponseBody.hpp>
#include <alibabacloud/models/UpdateAclResponse.hpp>
#include <alibabacloud/models/UpdateAuthPolicyRequest.hpp>
#include <alibabacloud/models/UpdateAuthPolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateAuthPolicyResponse.hpp>
#include <alibabacloud/models/UpdateBlackWhiteListRequest.hpp>
#include <alibabacloud/models/UpdateBlackWhiteListResponseBody.hpp>
#include <alibabacloud/models/UpdateBlackWhiteListResponse.hpp>
#include <alibabacloud/models/UpdateCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/UpdateCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/UpdateClusterRequest.hpp>
#include <alibabacloud/models/UpdateClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateClusterResponse.hpp>
#include <alibabacloud/models/UpdateClusterSpecRequest.hpp>
#include <alibabacloud/models/UpdateClusterSpecResponseBody.hpp>
#include <alibabacloud/models/UpdateClusterSpecResponse.hpp>
#include <alibabacloud/models/UpdateConfigRequest.hpp>
#include <alibabacloud/models/UpdateConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateConfigResponse.hpp>
#include <alibabacloud/models/UpdateEngineNamespaceRequest.hpp>
#include <alibabacloud/models/UpdateEngineNamespaceResponseBody.hpp>
#include <alibabacloud/models/UpdateEngineNamespaceResponse.hpp>
#include <alibabacloud/models/UpdateFlowRuleRequest.hpp>
#include <alibabacloud/models/UpdateFlowRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateFlowRuleResponse.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerRequest.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResponse.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceRequest.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceResponse.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceStatusRequest.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceStatusResponse.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerStatusRequest.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerStatusResponse.hpp>
#include <alibabacloud/models/UpdateGatewayCircuitBreakerRuleRequest.hpp>
#include <alibabacloud/models/UpdateGatewayCircuitBreakerRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayCircuitBreakerRuleResponse.hpp>
#include <alibabacloud/models/UpdateGatewayConfigRequest.hpp>
#include <alibabacloud/models/UpdateGatewayConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayConfigResponse.hpp>
#include <alibabacloud/models/UpdateGatewayDomainRequest.hpp>
#include <alibabacloud/models/UpdateGatewayDomainShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayDomainResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayDomainResponse.hpp>
#include <alibabacloud/models/UpdateGatewayFlowRuleRequest.hpp>
#include <alibabacloud/models/UpdateGatewayFlowRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayFlowRuleResponse.hpp>
#include <alibabacloud/models/UpdateGatewayIsolationRuleRequest.hpp>
#include <alibabacloud/models/UpdateGatewayIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayIsolationRuleResponse.hpp>
#include <alibabacloud/models/UpdateGatewayNameRequest.hpp>
#include <alibabacloud/models/UpdateGatewayNameResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayNameResponse.hpp>
#include <alibabacloud/models/UpdateGatewayOptionRequest.hpp>
#include <alibabacloud/models/UpdateGatewayOptionShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayOptionResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayOptionResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteAuthRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteAuthShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteAuthResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteAuthResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteCorsrequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteCorsshrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteCorsresponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteCorsresponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHttprewriteRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHttprewriteResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHttprewriteResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHeaderOpRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHeaderOpResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteHeaderOpResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRetryRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRetryShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRetryResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRetryResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTimeoutRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTimeoutShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTimeoutResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTimeoutResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponse.hpp>
#include <alibabacloud/models/UpdateGatewayServiceRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayServiceResponse.hpp>
#include <alibabacloud/models/UpdateGatewayServiceCheckRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceCheckShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceCheckResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayServiceCheckResponse.hpp>
#include <alibabacloud/models/UpdateGatewayServiceTrafficPolicyRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceTrafficPolicyShrinkRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceTrafficPolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayServiceTrafficPolicyResponse.hpp>
#include <alibabacloud/models/UpdateGatewayServiceVersionRequest.hpp>
#include <alibabacloud/models/UpdateGatewayServiceVersionResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayServiceVersionResponse.hpp>
#include <alibabacloud/models/UpdateGatewaySpecRequest.hpp>
#include <alibabacloud/models/UpdateGatewaySpecResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewaySpecResponse.hpp>
#include <alibabacloud/models/UpdateImageRequest.hpp>
#include <alibabacloud/models/UpdateImageResponseBody.hpp>
#include <alibabacloud/models/UpdateImageResponse.hpp>
#include <alibabacloud/models/UpdateIsolationRuleRequest.hpp>
#include <alibabacloud/models/UpdateIsolationRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateIsolationRuleResponse.hpp>
#include <alibabacloud/models/UpdateLocalityRuleRequest.hpp>
#include <alibabacloud/models/UpdateLocalityRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateLocalityRuleResponse.hpp>
#include <alibabacloud/models/UpdateMessageQueueRouteRequest.hpp>
#include <alibabacloud/models/UpdateMessageQueueRouteShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMessageQueueRouteResponseBody.hpp>
#include <alibabacloud/models/UpdateMessageQueueRouteResponse.hpp>
#include <alibabacloud/models/UpdateMigrationTaskRequest.hpp>
#include <alibabacloud/models/UpdateMigrationTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateMigrationTaskResponse.hpp>
#include <alibabacloud/models/UpdateNacosClusterRequest.hpp>
#include <alibabacloud/models/UpdateNacosClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateNacosClusterResponse.hpp>
#include <alibabacloud/models/UpdateNacosConfigRequest.hpp>
#include <alibabacloud/models/UpdateNacosConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateNacosConfigResponse.hpp>
#include <alibabacloud/models/UpdateNacosGrayConfigRequest.hpp>
#include <alibabacloud/models/UpdateNacosGrayConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateNacosGrayConfigResponse.hpp>
#include <alibabacloud/models/UpdateNacosInstanceRequest.hpp>
#include <alibabacloud/models/UpdateNacosInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateNacosInstanceResponse.hpp>
#include <alibabacloud/models/UpdateNacosServiceRequest.hpp>
#include <alibabacloud/models/UpdateNacosServiceResponseBody.hpp>
#include <alibabacloud/models/UpdateNacosServiceResponse.hpp>
#include <alibabacloud/models/UpdatePluginConfigRequest.hpp>
#include <alibabacloud/models/UpdatePluginConfigShrinkRequest.hpp>
#include <alibabacloud/models/UpdatePluginConfigResponseBody.hpp>
#include <alibabacloud/models/UpdatePluginConfigResponse.hpp>
#include <alibabacloud/models/UpdateSslcertRequest.hpp>
#include <alibabacloud/models/UpdateSslcertResponseBody.hpp>
#include <alibabacloud/models/UpdateSslcertResponse.hpp>
#include <alibabacloud/models/UpdateServiceSourceRequest.hpp>
#include <alibabacloud/models/UpdateServiceSourceShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceSourceResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceSourceResponse.hpp>
#include <alibabacloud/models/UpdateWebFlowRuleRequest.hpp>
#include <alibabacloud/models/UpdateWebFlowRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateWebFlowRuleResponse.hpp>
#include <alibabacloud/models/UpdateZnodeRequest.hpp>
#include <alibabacloud/models/UpdateZnodeResponseBody.hpp>
#include <alibabacloud/models/UpdateZnodeResponse.hpp>
#include <alibabacloud/models/UpgradeClusterRequest.hpp>
#include <alibabacloud/models/UpgradeClusterResponseBody.hpp>
#include <alibabacloud/models/UpgradeClusterResponse.hpp>
#include <alibabacloud/models/GatewayOptionLogConfigDetails.hpp>
#include <alibabacloud/models/GatewayOptionTraceDetails.hpp>
#include <alibabacloud/models/TrafficPolicyLoadBalancerSettingsConsistentHashLbconfigHttpCookie.hpp>
#include <alibabacloud/models/TrafficPolicyLoadBalancerSettingsConsistentHashLbconfig.hpp>
#include <alibabacloud/models/TrafficPolicyLoadBalancerSettings.hpp>
#include <alibabacloud/models/TrafficPolicyTlsSetting.hpp>
#include <alibabacloud/models/RulesValueRulesSpringcloudRestItems.hpp>
#include <alibabacloud/models/RulesValueRulesSpringcloud.hpp>
#include <alibabacloud/models/RulesValueRulesDubboArgumentItems.hpp>
#include <alibabacloud/models/RulesValueRulesDubbo.hpp>
#include <alibabacloud/models/RulesValueRules.hpp>
#include <alibabacloud/models/AddAuthResourceRequestAuthResourceHeaderList.hpp>
#include <alibabacloud/models/AddGatewayRequestTag.hpp>
#include <alibabacloud/models/AddGatewayRequestZoneInfo.hpp>
#include <alibabacloud/models/AddGatewayShrinkRequestTag.hpp>
#include <alibabacloud/models/AddGatewayResponseBodyData.hpp>
#include <alibabacloud/models/AddGatewayAuthRequestAuthResourceListAuthResourceHeaderList.hpp>
#include <alibabacloud/models/AddGatewayAuthRequestAuthResourceList.hpp>
#include <alibabacloud/models/AddGatewayAuthRequestExternalAuthZjson.hpp>
#include <alibabacloud/models/AddGatewayDomainRequestTlsCipherSuitesConfigJson.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestDirectResponseJson.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestFallbackServices.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestPredicatesHeaderPredicates.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestPredicatesPathPredicates.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestPredicatesQueryPredicates.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestPredicates.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestRedirectJson.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestServicesHttpDubboTranscoderMothedMapListParamMapsList.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestServicesHttpDubboTranscoderMothedMapList.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestServicesHttpDubboTranscoder.hpp>
#include <alibabacloud/models/AddGatewayRouteRequestServices.hpp>
#include <alibabacloud/models/AddGatewaySlbRequestVserviceList.hpp>
#include <alibabacloud/models/AddMigrationTaskResponseBodyData.hpp>
#include <alibabacloud/models/AddMockRuleResponseBodyData.hpp>
#include <alibabacloud/models/AddServiceSourceRequestIngressOptionsRequest.hpp>
#include <alibabacloud/models/AddServiceSourceRequestToAuthorizeSecurityGroups.hpp>
#include <alibabacloud/models/ApplyTagPoliciesResponseBodyData.hpp>
#include <alibabacloud/models/CloneNacosConfigResponseBodyDataFailData.hpp>
#include <alibabacloud/models/CloneNacosConfigResponseBodyDataSkipData.hpp>
#include <alibabacloud/models/CloneNacosConfigResponseBodyData.hpp>
#include <alibabacloud/models/CreateApplicationRequestTags.hpp>
#include <alibabacloud/models/CreateApplicationResponseBodyData.hpp>
#include <alibabacloud/models/CreateCircuitBreakerRuleResponseBodyData.hpp>
#include <alibabacloud/models/CreateClusterRequestTag.hpp>
#include <alibabacloud/models/CreateEngineNamespaceResponseBodyData.hpp>
#include <alibabacloud/models/CreateFlowRuleResponseBodyData.hpp>
#include <alibabacloud/models/CreateIsolationRuleResponseBodyData.hpp>
#include <alibabacloud/models/CreateMseServiceApplicationResponseBodyData.hpp>
#include <alibabacloud/models/CreateNamespaceRequestTag.hpp>
#include <alibabacloud/models/CreateNamespaceResponseBodyData.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequestEntryRulesRestItems.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequestEntryRules.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequestGatewaySwimmingLaneRouteJsonConditions.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequestGatewaySwimmingLaneRouteJsonRouteIndependentPercentageList.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneRequestGatewaySwimmingLaneRouteJson.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneShrinkRequestEntryRulesRestItems.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneShrinkRequestEntryRules.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneResponseBodyDataEntryRulesRestItems.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneResponseBodyDataEntryRules.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneResponseBodyData.hpp>
#include <alibabacloud/models/CreateOrUpdateSwimmingLaneGroupResponseBodyData.hpp>
#include <alibabacloud/models/CreateSentinelBlockFallbackDefinitionResponseBodyData.hpp>
#include <alibabacloud/models/CreateWebFlowRuleResponseBodyData.hpp>
#include <alibabacloud/models/CreateZnodeResponseBodyData.hpp>
#include <alibabacloud/models/DeleteAuthResourceResponseBodyData.hpp>
#include <alibabacloud/models/DeleteGatewayResponseBodyData.hpp>
#include <alibabacloud/models/DeleteGatewayDomainResponseBodyData.hpp>
#include <alibabacloud/models/DeleteGatewayRouteResponseBodyData.hpp>
#include <alibabacloud/models/DeleteGatewayServiceResponseBodyData.hpp>
#include <alibabacloud/models/DeleteSecurityGroupRuleResponseBodyData.hpp>
#include <alibabacloud/models/DeleteZnodeResponseBodyData.hpp>
#include <alibabacloud/models/ExportNacosConfigResponseBodyData.hpp>
#include <alibabacloud/models/ExportZookeeperDataResponseBodyData.hpp>
#include <alibabacloud/models/FetchLosslessRuleListResponseBodyDataResults.hpp>
#include <alibabacloud/models/FetchLosslessRuleListResponseBodyData.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListRequestFilterParams.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListResponseBodyDataResult.hpp>
#include <alibabacloud/models/GatewayBlackWhiteListResponseBodyData.hpp>
#include <alibabacloud/models/GetAppMessageQueueRouteResponseBodyData.hpp>
#include <alibabacloud/models/GetApplicationInstanceListResponseBodyDataResultTags.hpp>
#include <alibabacloud/models/GetApplicationInstanceListResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetApplicationInstanceListResponseBodyData.hpp>
#include <alibabacloud/models/GetApplicationListRequestTags.hpp>
#include <alibabacloud/models/GetApplicationListResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetApplicationListResponseBodyData.hpp>
#include <alibabacloud/models/GetBlackWhiteListResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayResponseBodyDataElasticPolicyTimePolicyList.hpp>
#include <alibabacloud/models/GetGatewayResponseBodyDataElasticPolicy.hpp>
#include <alibabacloud/models/GetGatewayResponseBodyDataLogConfigDetails.hpp>
#include <alibabacloud/models/GetGatewayResponseBodyDataXtraceDetails.hpp>
#include <alibabacloud/models/GetGatewayResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayAuthConsumerDetailResponseBodyDataResourceList.hpp>
#include <alibabacloud/models/GetGatewayAuthConsumerDetailResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBodyDataExternalAuthZservice.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBodyDataExternalAuthZ.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBodyDataResourceListAuthResourceHeaderList.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBodyDataResourceList.hpp>
#include <alibabacloud/models/GetGatewayAuthDetailResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBodyDataEnableK8sSourceWorkloadFilter.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBodyDataEnableXffTrustedCidrs.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBodyDataSlsConfigDetails.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBodyDataXtraceDetails.hpp>
#include <alibabacloud/models/GetGatewayConfigResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayDomainDetailResponseBodyDataTlsCipherSuitesConfig.hpp>
#include <alibabacloud/models/GetGatewayDomainDetailResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataCors.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataDirectResponse.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataFallbackServices.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataFlowMirror.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataHttprewrite.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataHeaderOpHeaderOpItems.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataHeaderOp.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRedirect.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRetry.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRoutePredicatesHeaderPredicates.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRoutePredicatesPathPredicates.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRoutePredicatesQueryPredicates.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRoutePredicates.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRouteServicesHttpDubboTranscoderMothedMapListParamMapsList.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRouteServicesHttpDubboTranscoderMothedMapList.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRouteServicesHttpDubboTranscoder.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataRouteServices.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyDataTimeout.hpp>
#include <alibabacloud/models/GetGatewayRouteDetailResponseBodyData.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataLabelDetails.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataPortTrafficPolicyList.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataVersionDetailsServiceVersionLabels.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataVersionDetailsServiceVersion.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataVersionDetails.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyDataVersions.hpp>
#include <alibabacloud/models/GetGatewayServiceDetailResponseBodyData.hpp>
#include <alibabacloud/models/GetGovernanceKubernetesClusterResponseBodyDataNamespaces.hpp>
#include <alibabacloud/models/GetGovernanceKubernetesClusterResponseBodyData.hpp>
#include <alibabacloud/models/GetImageResponseBodyData.hpp>
#include <alibabacloud/models/GetImportFileUrlResponseBodyData.hpp>
#include <alibabacloud/models/GetKubernetesSourceResponseBodyData.hpp>
#include <alibabacloud/models/GetLosslessRuleByAppResponseBodyData.hpp>
#include <alibabacloud/models/GetMseSourceResponseBodyData.hpp>
#include <alibabacloud/models/GetNacosConfigResponseBodyConfigurationGrayVersions.hpp>
#include <alibabacloud/models/GetNacosConfigResponseBodyConfiguration.hpp>
#include <alibabacloud/models/GetNacosHistoryConfigResponseBodyConfiguration.hpp>
#include <alibabacloud/models/GetPluginConfigResponseBodyDataGatewayConfigListResourceList.hpp>
#include <alibabacloud/models/GetPluginConfigResponseBodyDataGatewayConfigList.hpp>
#include <alibabacloud/models/GetPluginConfigResponseBodyData.hpp>
#include <alibabacloud/models/GetPluginsResponseBodyData.hpp>
#include <alibabacloud/models/GetServiceListResponseBodyDataMethods.hpp>
#include <alibabacloud/models/GetServiceListResponseBodyData.hpp>
#include <alibabacloud/models/GetServiceListPageResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetServiceListPageResponseBodyData.hpp>
#include <alibabacloud/models/GetServiceListenersResponseBodyData.hpp>
#include <alibabacloud/models/GetServiceMethodPageResponseBodyDataResultParameterDefinitions.hpp>
#include <alibabacloud/models/GetServiceMethodPageResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetServiceMethodPageResponseBodyData.hpp>
#include <alibabacloud/models/GetZookeeperDataImportUrlResponseBodyData.hpp>
#include <alibabacloud/models/ImportNacosConfigResponseBodyDataFailData.hpp>
#include <alibabacloud/models/ImportNacosConfigResponseBodyDataSkipData.hpp>
#include <alibabacloud/models/ImportNacosConfigResponseBodyData.hpp>
#include <alibabacloud/models/ImportServicesRequestServiceList.hpp>
#include <alibabacloud/models/InitializeServiceLinkRoleResponseBodyData.hpp>
#include <alibabacloud/models/ListAnsInstancesResponseBodyData.hpp>
#include <alibabacloud/models/ListAnsServiceClustersResponseBodyDataAppDetail.hpp>
#include <alibabacloud/models/ListAnsServiceClustersResponseBodyDataClusters.hpp>
#include <alibabacloud/models/ListAnsServiceClustersResponseBodyData.hpp>
#include <alibabacloud/models/ListAnsServicesResponseBodyData.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRulesRulesDubboArgumentItems.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRulesRulesDubbo.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRulesRulesSpringcloudRestItems.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRulesRulesSpringcloud.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRulesRules.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResultRouteRules.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListApplicationsWithTagRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListAuthPolicyResponseBodyDataResultAuthRuleMethod.hpp>
#include <alibabacloud/models/ListAuthPolicyResponseBodyDataResultAuthRule.hpp>
#include <alibabacloud/models/ListAuthPolicyResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListAuthPolicyResponseBodyData.hpp>
#include <alibabacloud/models/ListCircuitBreakerRulesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListCircuitBreakerRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListClusterConnectionTypesResponseBodyData.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskResponseBodyDataResultRiskList.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListClusterHealthCheckTaskResponseBodyData.hpp>
#include <alibabacloud/models/ListClusterTypesResponseBodyData.hpp>
#include <alibabacloud/models/ListClusterVersionsResponseBodyData.hpp>
#include <alibabacloud/models/ListClustersRequestTag.hpp>
#include <alibabacloud/models/ListClustersResponseBodyDataMaintenancePeriod.hpp>
#include <alibabacloud/models/ListClustersResponseBodyData.hpp>
#include <alibabacloud/models/ListConfigTrackResponseBodyTraces.hpp>
#include <alibabacloud/models/ListEngineNamespacesResponseBodyData.hpp>
#include <alibabacloud/models/ListEurekaInstancesResponseBodyData.hpp>
#include <alibabacloud/models/ListEurekaServicesResponseBodyData.hpp>
#include <alibabacloud/models/ListExportZookeeperDataResponseBodyData.hpp>
#include <alibabacloud/models/ListFlowRulesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListFlowRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayRequestFilterParams.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultElasticPolicyEnableScaleTimePolicyList.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultElasticPolicyTimePolicyList.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultElasticPolicy.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultGatewayEntry.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultInitConfig.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultInternetSlb.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultMaintenancePeriod.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResultSlb.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResourceResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayAuthConsumerResourceResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleResponseBodyDataResults.hpp>
#include <alibabacloud/models/ListGatewayCircuitBreakerRuleResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayDomainResponseBodyDataComment.hpp>
#include <alibabacloud/models/ListGatewayDomainResponseBodyDataTlsCipherSuitesConfig.hpp>
#include <alibabacloud/models/ListGatewayDomainResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleResponseBodyDataResults.hpp>
#include <alibabacloud/models/ListGatewayFlowRuleResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleResponseBodyDataResults.hpp>
#include <alibabacloud/models/ListGatewayIsolationRuleResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayRouteRequestFilterParams.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultComment.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultDirectResponse.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultFallbackServices.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRedirect.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRoutePredicatesHeaderPredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRoutePredicatesPathPredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRoutePredicatesQueryPredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRoutePredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRouteServicesHttpDubboTranscoderMothedMapListParamMapsList.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRouteServicesHttpDubboTranscoderMothedMapList.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRouteServicesHttpDubboTranscoder.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResultRouteServices.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayRouteResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthResponseBodyDataRoutePredicatesPathPredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthResponseBodyDataRoutePredicates.hpp>
#include <alibabacloud/models/ListGatewayRouteOnAuthResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayServiceRequestFilterParams.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultGatewayTrafficPolicyLoadBalancerSettingsConsistentHashLbconfigHttpCookie.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultGatewayTrafficPolicyLoadBalancerSettingsConsistentHashLbconfig.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultGatewayTrafficPolicyLoadBalancerSettings.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultGatewayTrafficPolicyTls.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultGatewayTrafficPolicy.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultHealthCheckInfo.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResultVersions.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListGatewayServiceResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewaySlbResponseBodyDataVserviceList.hpp>
#include <alibabacloud/models/ListGatewaySlbResponseBodyData.hpp>
#include <alibabacloud/models/ListGatewayZoneResponseBodyData.hpp>
#include <alibabacloud/models/ListIsolationRulesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListIsolationRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListListenersByConfigRequestExtGrayRules.hpp>
#include <alibabacloud/models/ListListenersByConfigResponseBodyListeners.hpp>
#include <alibabacloud/models/ListListenersByIpResponseBodyListeners.hpp>
#include <alibabacloud/models/ListMigrationTaskResponseBodyData.hpp>
#include <alibabacloud/models/ListNacosConfigsResponseBodyConfigurations.hpp>
#include <alibabacloud/models/ListNacosHistoryConfigsResponseBodyHistoryItems.hpp>
#include <alibabacloud/models/ListNamespacesRequestTag.hpp>
#include <alibabacloud/models/ListNamespacesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListNamespacesResponseBodyDataResults.hpp>
#include <alibabacloud/models/ListNamespacesResponseBodyData.hpp>
#include <alibabacloud/models/ListNamingTrackResponseBodyTraces.hpp>
#include <alibabacloud/models/ListSslcertResponseBodyData.hpp>
#include <alibabacloud/models/ListSecurityGroupResponseBodyData.hpp>
#include <alibabacloud/models/ListSecurityGroupRuleResponseBodyData.hpp>
#include <alibabacloud/models/ListSentinelBlockFallbackDefinitionsResponseBodyData.hpp>
#include <alibabacloud/models/ListServiceSourceResponseBodyDataIngressOptions.hpp>
#include <alibabacloud/models/ListServiceSourceResponseBodyData.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListWebFlowRulesResponseBodyDataResult.hpp>
#include <alibabacloud/models/ListWebFlowRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListZkTrackResponseBodyTraces.hpp>
#include <alibabacloud/models/ListZnodeChildrenResponseBodyData.hpp>
#include <alibabacloud/models/ModifyGovernanceKubernetesClusterRequestNamespaceInfos.hpp>
#include <alibabacloud/models/PullServicesResponseBodyDataServices.hpp>
#include <alibabacloud/models/PullServicesResponseBodyData.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyDataEntryRulesRestItems.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyDataEntryRules.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyDataGatewaySwimmingLaneRouteConditions.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyDataGatewaySwimmingLaneRouteRouteIndependentPercentageList.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyDataGatewaySwimmingLaneRoute.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneResponseBodyData.hpp>
#include <alibabacloud/models/QueryAllSwimmingLaneGroupResponseBodyData.hpp>
#include <alibabacloud/models/QueryBusinessLocationsResponseBodyData.hpp>
#include <alibabacloud/models/QueryClusterDetailResponseBodyDataInstanceModels.hpp>
#include <alibabacloud/models/QueryClusterDetailResponseBodyData.hpp>
#include <alibabacloud/models/QueryClusterDiskSpecificationResponseBodyData.hpp>
#include <alibabacloud/models/QueryClusterInfoResponseBodyDataInstanceModels.hpp>
#include <alibabacloud/models/QueryClusterInfoResponseBodyDataMaintenancePeriod.hpp>
#include <alibabacloud/models/QueryClusterInfoResponseBodyData.hpp>
#include <alibabacloud/models/QueryClusterSpecificationResponseBodyData.hpp>
#include <alibabacloud/models/QueryConfigResponseBodyDataNacosRunningEnv.hpp>
#include <alibabacloud/models/QueryConfigResponseBodyData.hpp>
#include <alibabacloud/models/QueryGovernanceKubernetesClusterResponseBodyDataResult.hpp>
#include <alibabacloud/models/QueryGovernanceKubernetesClusterResponseBodyData.hpp>
#include <alibabacloud/models/QueryInstancesInfoResponseBodyData.hpp>
#include <alibabacloud/models/QueryMonitorResponseBodyData.hpp>
#include <alibabacloud/models/QueryNamespaceResponseBodyData.hpp>
#include <alibabacloud/models/QuerySlbSpecResponseBodyData.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdResponseBodyDataEntryRulesRestItems.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdResponseBodyDataEntryRules.hpp>
#include <alibabacloud/models/QuerySwimmingLaneByIdResponseBodyData.hpp>
#include <alibabacloud/models/QueryZnodeDetailResponseBodyData.hpp>
#include <alibabacloud/models/SelectGatewaySlbResponseBodyData.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/UpdateCircuitBreakerRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateEngineNamespaceResponseBodyData.hpp>
#include <alibabacloud/models/UpdateFlowRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateGatewayAuthConsumerResourceRequestResourceList.hpp>
#include <alibabacloud/models/UpdateGatewayCircuitBreakerRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateGatewayDomainRequestTlsCipherSuitesConfigJson.hpp>
#include <alibabacloud/models/UpdateGatewayFlowRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateGatewayIsolationRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestDirectResponseJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestFallbackServices.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestPredicatesHeaderPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestPredicatesPathPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestPredicatesQueryPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestRedirectJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestServicesHttpDubboTranscoderMothedMapListParamMapsList.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestServicesHttpDubboTranscoderMothedMapList.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestServicesHttpDubboTranscoder.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRequestServices.hpp>
#include <alibabacloud/models/UpdateGatewayRouteAuthRequestAuthJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteCorsrequestCorsJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteRetryRequestRetryJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTimeoutRequestTimeoutJson.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataCors.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataDirectResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataHttprewrite.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataHeaderOpHeaderOpItems.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataHeaderOp.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRedirect.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRetry.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRoutePredicatesHeaderPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRoutePredicatesPathPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRoutePredicatesQueryPredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRoutePredicates.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataRouteServices.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyDataTimeout.hpp>
#include <alibabacloud/models/UpdateGatewayRouteWafStatusResponseBodyData.hpp>
#include <alibabacloud/models/UpdateIsolationRuleResponseBodyData.hpp>
#include <alibabacloud/models/UpdateMigrationTaskResponseBodyData.hpp>
#include <alibabacloud/models/UpdateServiceSourceRequestIngressOptionsRequest.hpp>
#include <alibabacloud/models/UpdateWebFlowRuleResponseBodyData.hpp>

#endif
