// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#define ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AbortDbclusterMigrationRequest.hpp>
#include <alibabacloud/models/AbortDbclusterMigrationResponseBody.hpp>
#include <alibabacloud/models/AbortDbclusterMigrationResponse.hpp>
#include <alibabacloud/models/AddEncryptionDbrolePrivilegeRequest.hpp>
#include <alibabacloud/models/AddEncryptionDbrolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/AddEncryptionDbrolePrivilegeResponse.hpp>
#include <alibabacloud/models/AddFirewallRulesRequest.hpp>
#include <alibabacloud/models/AddFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/AddFirewallRulesResponse.hpp>
#include <alibabacloud/models/AddSqlrateLimitingRulesRequest.hpp>
#include <alibabacloud/models/AddSqlrateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/AddSqlrateLimitingRulesResponse.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsrequest.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsresponseBody.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsresponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CancelScheduleTasksRequest.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponse.hpp>
#include <alibabacloud/models/CheckAccountNameRequest.hpp>
#include <alibabacloud/models/CheckAccountNameResponseBody.hpp>
#include <alibabacloud/models/CheckAccountNameResponse.hpp>
#include <alibabacloud/models/CheckConnectionStringRequest.hpp>
#include <alibabacloud/models/CheckConnectionStringResponseBody.hpp>
#include <alibabacloud/models/CheckConnectionStringResponse.hpp>
#include <alibabacloud/models/CheckDbnameRequest.hpp>
#include <alibabacloud/models/CheckDbnameResponseBody.hpp>
#include <alibabacloud/models/CheckDbnameResponse.hpp>
#include <alibabacloud/models/CheckKmsauthorizedRequest.hpp>
#include <alibabacloud/models/CheckKmsauthorizedResponseBody.hpp>
#include <alibabacloud/models/CheckKmsauthorizedResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CloseAitaskRequest.hpp>
#include <alibabacloud/models/CloseAitaskResponseBody.hpp>
#include <alibabacloud/models/CloseAitaskResponse.hpp>
#include <alibabacloud/models/CloseDbclusterMigrationRequest.hpp>
#include <alibabacloud/models/CloseDbclusterMigrationResponseBody.hpp>
#include <alibabacloud/models/CloseDbclusterMigrationResponse.hpp>
#include <alibabacloud/models/ContinueDbclusterMigrationRequest.hpp>
#include <alibabacloud/models/ContinueDbclusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ContinueDbclusterMigrationResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateActivationCodeRequest.hpp>
#include <alibabacloud/models/CreateActivationCodeResponseBody.hpp>
#include <alibabacloud/models/CreateActivationCodeResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationShrinkRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CreateDbclusterRequest.hpp>
#include <alibabacloud/models/CreateDbclusterResponseBody.hpp>
#include <alibabacloud/models/CreateDbclusterResponse.hpp>
#include <alibabacloud/models/CreateDbclusterEndpointRequest.hpp>
#include <alibabacloud/models/CreateDbclusterEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateDbclusterEndpointResponse.hpp>
#include <alibabacloud/models/CreateDbendpointAddressRequest.hpp>
#include <alibabacloud/models/CreateDbendpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateDbendpointAddressResponse.hpp>
#include <alibabacloud/models/CreateDblinkRequest.hpp>
#include <alibabacloud/models/CreateDblinkResponseBody.hpp>
#include <alibabacloud/models/CreateDblinkResponse.hpp>
#include <alibabacloud/models/CreateDbnodesRequest.hpp>
#include <alibabacloud/models/CreateDbnodesResponseBody.hpp>
#include <alibabacloud/models/CreateDbnodesResponse.hpp>
#include <alibabacloud/models/CreateDatabaseRequest.hpp>
#include <alibabacloud/models/CreateDatabaseResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseResponse.hpp>
#include <alibabacloud/models/CreateExtensionsRequest.hpp>
#include <alibabacloud/models/CreateExtensionsResponseBody.hpp>
#include <alibabacloud/models/CreateExtensionsResponse.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpgroupRequest.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpgroupResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpgroupResponse.hpp>
#include <alibabacloud/models/CreateNetworkChannelRequest.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponse.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderRequest.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponseBody.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponse.hpp>
#include <alibabacloud/models/CreateParameterGroupRequest.hpp>
#include <alibabacloud/models/CreateParameterGroupResponseBody.hpp>
#include <alibabacloud/models/CreateParameterGroupResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateStoragePlanRequest.hpp>
#include <alibabacloud/models/CreateStoragePlanResponseBody.hpp>
#include <alibabacloud/models/CreateStoragePlanResponse.hpp>
#include <alibabacloud/models/DeleteAidbclusterRequest.hpp>
#include <alibabacloud/models/DeleteAidbclusterResponseBody.hpp>
#include <alibabacloud/models/DeleteAidbclusterResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteApplicationRequest.hpp>
#include <alibabacloud/models/DeleteApplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationResponse.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteDbclusterRequest.hpp>
#include <alibabacloud/models/DeleteDbclusterResponseBody.hpp>
#include <alibabacloud/models/DeleteDbclusterResponse.hpp>
#include <alibabacloud/models/DeleteDbclusterEndpointRequest.hpp>
#include <alibabacloud/models/DeleteDbclusterEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteDbclusterEndpointResponse.hpp>
#include <alibabacloud/models/DeleteDbendpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteDbendpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteDbendpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteDblinkRequest.hpp>
#include <alibabacloud/models/DeleteDblinkResponseBody.hpp>
#include <alibabacloud/models/DeleteDblinkResponse.hpp>
#include <alibabacloud/models/DeleteDbnodesRequest.hpp>
#include <alibabacloud/models/DeleteDbnodesResponseBody.hpp>
#include <alibabacloud/models/DeleteDbnodesResponse.hpp>
#include <alibabacloud/models/DeleteDatabaseRequest.hpp>
#include <alibabacloud/models/DeleteDatabaseResponseBody.hpp>
#include <alibabacloud/models/DeleteDatabaseResponse.hpp>
#include <alibabacloud/models/DeleteEncryptionDbrolePrivilegeRequest.hpp>
#include <alibabacloud/models/DeleteEncryptionDbrolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DeleteEncryptionDbrolePrivilegeResponse.hpp>
#include <alibabacloud/models/DeleteExtensionsRequest.hpp>
#include <alibabacloud/models/DeleteExtensionsResponseBody.hpp>
#include <alibabacloud/models/DeleteExtensionsResponse.hpp>
#include <alibabacloud/models/DeleteFirewallRulesRequest.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpgroupRequest.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpgroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpgroupResponse.hpp>
#include <alibabacloud/models/DeleteMaskingRulesRequest.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponse.hpp>
#include <alibabacloud/models/DeleteNetworkChannelRequest.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponse.hpp>
#include <alibabacloud/models/DeleteParameterGroupRequest.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponse.hpp>
#include <alibabacloud/models/DeleteSqlrateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DeleteSqlrateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteSqlrateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAidbclusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeAidbclusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbclusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeAidbclustersRequest.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponse.hpp>
#include <alibabacloud/models/DescribeAitaskStatusRequest.hpp>
#include <alibabacloud/models/DescribeAitaskStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAitaskStatusResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodesRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeRequest.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponse.hpp>
#include <alibabacloud/models/DescribeApplicationParametersRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersShrinkRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponse.hpp>
#include <alibabacloud/models/DescribeApplicationsRequest.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationsResponse.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsRequest.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupLogsRequest.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupRegionsRequest.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupTasksRequest.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameRequest.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponseBody.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponse.hpp>
#include <alibabacloud/models/DescribeClassListRequest.hpp>
#include <alibabacloud/models/DescribeClassListResponseBody.hpp>
#include <alibabacloud/models/DescribeClassListResponse.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterConnectivityRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterConnectivityResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterConnectivityResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterEncryptionKeyRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterEncryptionKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterEncryptionKeyResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterEndpointsRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterEndpointsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterEndpointsResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterMonitorRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterMonitorResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterProxyRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterProxyResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterProxyResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterSslrequest.hpp>
#include <alibabacloud/models/DescribeDbclusterSslresponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterSslresponse.hpp>
#include <alibabacloud/models/DescribeDbclusterServerlessConfRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterServerlessConfResponse.hpp>
#include <alibabacloud/models/DescribeDbclusterTderequest.hpp>
#include <alibabacloud/models/DescribeDbclusterTderesponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterTderesponse.hpp>
#include <alibabacloud/models/DescribeDbclusterVersionRequest.hpp>
#include <alibabacloud/models/DescribeDbclusterVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclusterVersionResponse.hpp>
#include <alibabacloud/models/DescribeDbclustersRequest.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclustersResponse.hpp>
#include <alibabacloud/models/DescribeDbclustersWithBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDbclustersWithBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbclustersWithBackupsResponse.hpp>
#include <alibabacloud/models/DescribeDbinitializeVariableRequest.hpp>
#include <alibabacloud/models/DescribeDbinitializeVariableResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinitializeVariableResponse.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDblinksRequest.hpp>
#include <alibabacloud/models/DescribeDblinksResponseBody.hpp>
#include <alibabacloud/models/DescribeDblinksResponse.hpp>
#include <alibabacloud/models/DescribeDblogFilesRequest.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponse.hpp>
#include <alibabacloud/models/DescribeDbminiEngineVersionsRequest.hpp>
#include <alibabacloud/models/DescribeDbminiEngineVersionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbminiEngineVersionsResponse.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbnodesParametersRequest.hpp>
#include <alibabacloud/models/DescribeDbnodesParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbnodesParametersResponse.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDasConfigRequest.hpp>
#include <alibabacloud/models/DescribeDasConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDasConfigResponse.hpp>
#include <alibabacloud/models/DescribeDatabasesRequest.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBody.hpp>
#include <alibabacloud/models/DescribeDatabasesResponse.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDbrolePrivilegeRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDbrolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDbrolePrivilegeResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDbsecretRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDbsecretResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDbsecretResponse.hpp>
#include <alibabacloud/models/DescribeExtensionsRequest.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeExtensionsResponse.hpp>
#include <alibabacloud/models/DescribeFirewallRulesRequest.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupRelationRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupRelationResponse.hpp>
#include <alibabacloud/models/DescribeHalogsRequest.hpp>
#include <alibabacloud/models/DescribeHalogsResponseBody.hpp>
#include <alibabacloud/models/DescribeHalogsResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponse.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeRequest.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponseBody.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponse.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeMaskingRulesRequest.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponse.hpp>
#include <alibabacloud/models/DescribeMetaListRequest.hpp>
#include <alibabacloud/models/DescribeMetaListResponseBody.hpp>
#include <alibabacloud/models/DescribeMetaListResponse.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogRequest.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBody.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponse.hpp>
#include <alibabacloud/models/DescribeNetworkChannelRequest.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupsRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponse.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponse.hpp>
#include <alibabacloud/models/DescribePolarSqlcollectorPolicyRequest.hpp>
#include <alibabacloud/models/DescribePolarSqlcollectorPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribePolarSqlcollectorPolicyResponse.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponse.hpp>
#include <alibabacloud/models/DescribeRdsVpcsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBody.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponse.hpp>
#include <alibabacloud/models/DescribeSqlrateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DescribeSqlrateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlrateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeScheduleTasksRequest.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponse.hpp>
#include <alibabacloud/models/DescribeTasksRequest.hpp>
#include <alibabacloud/models/DescribeTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeTasksResponse.hpp>
#include <alibabacloud/models/DescribeUpgradeReportRequest.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBody.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponse.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/DescribeVswitchListRequest.hpp>
#include <alibabacloud/models/DescribeVswitchListResponseBody.hpp>
#include <alibabacloud/models/DescribeVswitchListResponse.hpp>
#include <alibabacloud/models/DescribeVswitchesRequest.hpp>
#include <alibabacloud/models/DescribeVswitchesResponseBody.hpp>
#include <alibabacloud/models/DescribeVswitchesResponse.hpp>
#include <alibabacloud/models/DescribeVpcsRequest.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DisableDbclusterOrcaRequest.hpp>
#include <alibabacloud/models/DisableDbclusterOrcaResponseBody.hpp>
#include <alibabacloud/models/DisableDbclusterOrcaResponse.hpp>
#include <alibabacloud/models/DisableDbclusterServerlessRequest.hpp>
#include <alibabacloud/models/DisableDbclusterServerlessResponseBody.hpp>
#include <alibabacloud/models/DisableDbclusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableDbclusterOrcaRequest.hpp>
#include <alibabacloud/models/EnableDbclusterOrcaResponseBody.hpp>
#include <alibabacloud/models/EnableDbclusterOrcaResponse.hpp>
#include <alibabacloud/models/EnableDbclusterServerlessRequest.hpp>
#include <alibabacloud/models/EnableDbclusterServerlessResponseBody.hpp>
#include <alibabacloud/models/EnableDbclusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableFirewallRulesRequest.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponse.hpp>
#include <alibabacloud/models/EnableSqlrateLimitingRulesRequest.hpp>
#include <alibabacloud/models/EnableSqlrateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/EnableSqlrateLimitingRulesResponse.hpp>
#include <alibabacloud/models/EvaluateRegionResourceRequest.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponseBody.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponse.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApirequest.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApiresponseBody.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApiresponse.hpp>
#include <alibabacloud/models/FailoverDbclusterRequest.hpp>
#include <alibabacloud/models/FailoverDbclusterResponseBody.hpp>
#include <alibabacloud/models/FailoverDbclusterResponse.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneRequest.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponseBody.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/ListOrdersRequest.hpp>
#include <alibabacloud/models/ListOrdersResponseBody.hpp>
#include <alibabacloud/models/ListOrdersResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionRequest.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponse.hpp>
#include <alibabacloud/models/ManuallyStartDbclusterRequest.hpp>
#include <alibabacloud/models/ManuallyStartDbclusterResponseBody.hpp>
#include <alibabacloud/models/ManuallyStartDbclusterResponse.hpp>
#include <alibabacloud/models/ModifyAidbclusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAidbclusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAidbclusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountLockStateRequest.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyApplicationParameterRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterShrinkRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponse.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterAndNodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterAndNodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterAndNodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterArchRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterArchResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterArchResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterDeletionRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterDeletionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterDeletionResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterMigrationEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterMonitorRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterMonitorResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterMonitorResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterParametersResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterPrimaryZoneRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterPrimaryZoneResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterPrimaryZoneResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterSslrequest.hpp>
#include <alibabacloud/models/ModifyDbclusterSslresponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterSslresponse.hpp>
#include <alibabacloud/models/ModifyDbclusterServerlessConfRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterServerlessConfResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterStoragePerformanceRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterStoragePerformanceResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterStoragePerformanceResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterStorageSpaceRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterStorageSpaceResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterStorageSpaceResponse.hpp>
#include <alibabacloud/models/ModifyDbclusterTderequest.hpp>
#include <alibabacloud/models/ModifyDbclusterTderesponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterTderesponse.hpp>
#include <alibabacloud/models/ModifyDbclusterVpcRequest.hpp>
#include <alibabacloud/models/ModifyDbclusterVpcResponseBody.hpp>
#include <alibabacloud/models/ModifyDbclusterVpcResponse.hpp>
#include <alibabacloud/models/ModifyDbdescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbdescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbdescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbendpointAddressRequest.hpp>
#include <alibabacloud/models/ModifyDbendpointAddressResponseBody.hpp>
#include <alibabacloud/models/ModifyDbendpointAddressResponse.hpp>
#include <alibabacloud/models/ModifyDbnodeClassRequest.hpp>
#include <alibabacloud/models/ModifyDbnodeClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodeClassResponse.hpp>
#include <alibabacloud/models/ModifyDbnodeConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbnodeConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodeConfigResponse.hpp>
#include <alibabacloud/models/ModifyDbnodeDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbnodeDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodeDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbnodeHotReplicaModeRequest.hpp>
#include <alibabacloud/models/ModifyDbnodeHotReplicaModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodeHotReplicaModeResponse.hpp>
#include <alibabacloud/models/ModifyDbnodeSccModeRequest.hpp>
#include <alibabacloud/models/ModifyDbnodeSccModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodeSccModeResponse.hpp>
#include <alibabacloud/models/ModifyDbnodesClassRequest.hpp>
#include <alibabacloud/models/ModifyDbnodesClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodesClassResponse.hpp>
#include <alibabacloud/models/ModifyDbnodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbnodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbnodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDbrolePrivilegeRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDbrolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDbrolePrivilegeResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDbsecretRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDbsecretResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDbsecretResponse.hpp>
#include <alibabacloud/models/ModifyFirewallRulesRequest.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponse.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupNameRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupNameResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupNameResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupRelationRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupRelationResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupRelationResponse.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyMaskingRulesRequest.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponse.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/ModifyResourcePackageRequest.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponseBody.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponse.hpp>
#include <alibabacloud/models/ModifySqlrateLimitingRulesRequest.hpp>
#include <alibabacloud/models/ModifySqlrateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifySqlrateLimitingRulesResponse.hpp>
#include <alibabacloud/models/ModifyScheduleTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponse.hpp>
#include <alibabacloud/models/OpenAitaskRequest.hpp>
#include <alibabacloud/models/OpenAitaskResponseBody.hpp>
#include <alibabacloud/models/OpenAitaskResponse.hpp>
#include <alibabacloud/models/ReactivateDbclusterBackupRequest.hpp>
#include <alibabacloud/models/ReactivateDbclusterBackupResponseBody.hpp>
#include <alibabacloud/models/ReactivateDbclusterBackupResponse.hpp>
#include <alibabacloud/models/RefreshDbclusterStorageUsageRequest.hpp>
#include <alibabacloud/models/RefreshDbclusterStorageUsageResponseBody.hpp>
#include <alibabacloud/models/RefreshDbclusterStorageUsageResponse.hpp>
#include <alibabacloud/models/RemoveDbclusterFromGdnrequest.hpp>
#include <alibabacloud/models/RemoveDbclusterFromGdnresponseBody.hpp>
#include <alibabacloud/models/RemoveDbclusterFromGdnresponse.hpp>
#include <alibabacloud/models/ResetAccountRequest.hpp>
#include <alibabacloud/models/ResetAccountResponseBody.hpp>
#include <alibabacloud/models/ResetAccountResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/RestartDblinkRequest.hpp>
#include <alibabacloud/models/RestartDblinkResponseBody.hpp>
#include <alibabacloud/models/RestartDblinkResponse.hpp>
#include <alibabacloud/models/RestartDbnodeRequest.hpp>
#include <alibabacloud/models/RestartDbnodeResponseBody.hpp>
#include <alibabacloud/models/RestartDbnodeResponse.hpp>
#include <alibabacloud/models/RestoreTableRequest.hpp>
#include <alibabacloud/models/RestoreTableResponseBody.hpp>
#include <alibabacloud/models/RestoreTableResponse.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TempModifyDbnodeRequest.hpp>
#include <alibabacloud/models/TempModifyDbnodeResponseBody.hpp>
#include <alibabacloud/models/TempModifyDbnodeResponse.hpp>
#include <alibabacloud/models/TransformDbclusterPayTypeRequest.hpp>
#include <alibabacloud/models/TransformDbclusterPayTypeResponseBody.hpp>
#include <alibabacloud/models/TransformDbclusterPayTypeResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateExtensionsRequest.hpp>
#include <alibabacloud/models/UpdateExtensionsResponseBody.hpp>
#include <alibabacloud/models/UpdateExtensionsResponse.hpp>
#include <alibabacloud/models/UpgradeDbclusterVersionRequest.hpp>
#include <alibabacloud/models/UpgradeDbclusterVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeDbclusterVersionResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequestComponents.hpp>
#include <alibabacloud/models/CreateApplicationRequestEndpoints.hpp>
#include <alibabacloud/models/CreateApplicationResponseBodyComponents.hpp>
#include <alibabacloud/models/CreateDbclusterRequestTag.hpp>
#include <alibabacloud/models/CreateDbendpointAddressRequestZoneInfo.hpp>
#include <alibabacloud/models/CreateDbnodesRequestDbnode.hpp>
#include <alibabacloud/models/CreateDbnodesResponseBodyDbnodeIds.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpgroupResponseBodyGlobalSecurityIpgroup.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpgroupResponseBodyGlobalSecurityIpgroup.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBodyDbnodesVolumes.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBodyDbnodes.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBodyEndpointListNetInfoItems.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBodyEndpointList.hpp>
#include <alibabacloud/models/DescribeAidbclusterAttributeResponseBodyVolumes.hpp>
#include <alibabacloud/models/DescribeAidbclusterPerformanceResponseBodyPerformanceKeysPoints.hpp>
#include <alibabacloud/models/DescribeAidbclusterPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeAidbclustersRequestTag.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponseBodyItemsDbclusterTagsTag.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponseBodyItemsDbclusterTags.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponseBodyItemsDbcluster.hpp>
#include <alibabacloud/models/DescribeAidbclustersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountsDatabasePrivileges.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccounts.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBodyConfig.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsSecurityGroups.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsSecurityIparrays.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsTopology.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponents.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyEndpoints.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodySecurityGroups.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodySecurityIparrays.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplatesComponentParameterTemplatesParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplatesComponentParameterTemplates.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplates.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParametersComponentParametersParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParametersComponentParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplicationsEndpointsEndpoint.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplicationsEndpoints.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplications.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItemsAutoRenewAttribute.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBodyItemsBackupLog.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBodyAdvancedDataPoliciesAdvancedDataPolicy.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBodyAdvancedDataPolicies.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBodyItemsBackupJob.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItemsBackup.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponseBodyCharacterSetNameItems.hpp>
#include <alibabacloud/models/DescribeClassListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyOssClusterInfoList.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyTablesChildObjects.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponseBodyCrossCloudLevelList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBodyCrossCloudRegionListCrossCloudZoneList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBodyCrossCloudRegionList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponseBodyCrossCloudRegionMappingList.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponseBodyDbclusterSecurityGroupsDbclusterSecurityGroup.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponseBodyDbclusterSecurityGroups.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponseBodyItemsDbclusterIparray.hpp>
#include <alibabacloud/models/DescribeDbclusterAccessWhitelistResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbclusterAttributeResponseBodyDbnodes.hpp>
#include <alibabacloud/models/DescribeDbclusterAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesResponseBodyAvailableZonesSupportedEnginesAvailableResources.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesResponseBodyAvailableZonesSupportedEngines.hpp>
#include <alibabacloud/models/DescribeDbclusterAvailableResourcesResponseBodyAvailableZones.hpp>
#include <alibabacloud/models/DescribeDbclusterEncryptionKeyResponseBodyEncryptionKeyList.hpp>
#include <alibabacloud/models/DescribeDbclusterEndpointsResponseBodyItemsAddressItems.hpp>
#include <alibabacloud/models/DescribeDbclusterEndpointsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponseBodyDbclusterEndpointListAddressItems.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponseBodyDbclusterEndpointList.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponseBodyRdsEndpointListAddressItems.hpp>
#include <alibabacloud/models/DescribeDbclusterMigrationResponseBodyRdsEndpointList.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbclusterNetInfosDbclusterNetInfo.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbclusterNetInfos.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbnodeNetInfosDbnodeNetInfoNetInfosNetInfo.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbnodeNetInfosDbnodeNetInfoNetInfos.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbnodeNetInfosDbnodeNetInfo.hpp>
#include <alibabacloud/models/DescribeDbclusterNetInfoResponseBodyDbnodeNetInfos.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponseBodyParametersParameters.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponseBodyRunningParametersParameter.hpp>
#include <alibabacloud/models/DescribeDbclusterParametersResponseBodyRunningParameters.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbclusterPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbclusterProxyResponseBodyChildInstances.hpp>
#include <alibabacloud/models/DescribeDbclusterSslresponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbclusterVersionResponseBodyDbrevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbclusterVersionResponseBodyProxyRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbclustersRequestTag.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItemsDbclusterDbnodesDbnode.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItemsDbclusterDbnodes.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItemsDbclusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItemsDbclusterTags.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItemsDbcluster.hpp>
#include <alibabacloud/models/DescribeDbclustersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbclustersWithBackupsResponseBodyItemsDbcluster.hpp>
#include <alibabacloud/models/DescribeDbclustersWithBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinitializeVariableResponseBodyVariablesVariable.hpp>
#include <alibabacloud/models/DescribeDbinitializeVariableResponseBodyVariables.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbinstancePerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDblinksResponseBodyDblinkInfos.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodyHaLogItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchListItemsSwitchLogItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchListItemsSwitchLogItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchListItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchListItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchLogItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDblogFilesResponseBodySwitchLogItems.hpp>
#include <alibabacloud/models/DescribeDbminiEngineVersionsResponseBodyDbrevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbnodePerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbnodesParametersResponseBodyDbnodeIdsRunningParameters.hpp>
#include <alibabacloud/models/DescribeDbnodesParametersResponseBodyDbnodeIds.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbproxyPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabaseAccountsAccount.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabaseAccounts.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabase.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabases.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBodyItemsBackup.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeEncryptionDbrolePrivilegeResponseBodyDataRolePrivilegeList.hpp>
#include <alibabacloud/models/DescribeEncryptionDbrolePrivilegeResponseBodyData.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBodyInstalledExtensions.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBodyUninstalledExtensions.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksChannels.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopologyDestinations.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopologySources.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopology.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworks.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyConnections.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyDbclustersDbnodes.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyDbclusters.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyLabels.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItemsDbclusters.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItemsLabels.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupResponseBodyGlobalSecurityIpgroup.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpgroupRelationResponseBodyGlobalSecurityIpgroupRel.hpp>
#include <alibabacloud/models/DescribeHalogsResponseBodyHaLogItems.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBodyAdvancedLogPoliciesAdvancedLogPolicy.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBodyAdvancedLogPolicies.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeMetaListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponseBodyChannelInfos.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBodyParameterGroupParameterDetail.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBodyParameterGroup.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBodyParameterGroups.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBodyParametersTemplateRecord.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponseBodyItems.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponseBodyTypeList.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBodyVswitchesVswitch.hpp>
#include <alibabacloud/models/DescribeRdsVswitchsResponseBodyVswitches.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpcVswitchs.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpc.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZonesZone.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageListResourcePackageQuotaList.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageListTags.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageList.hpp>
#include <alibabacloud/models/DescribeSqlrateLimitingRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBodyDataTimerInfos.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItemsSqlslowRecord.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBodyItemsSqlslowLog.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTasksResponseBodyTasksTask.hpp>
#include <alibabacloud/models/DescribeTasksResponseBodyTasks.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBodyUpgradeReportList.hpp>
#include <alibabacloud/models/DescribeVswitchListResponseBodyVswitchs.hpp>
#include <alibabacloud/models/DescribeVswitchesResponseBodyVswitchs.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcsVswitchs.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZones.hpp>
#include <alibabacloud/models/ListOrdersResponseBodyOrderList.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyApplicationParameterRequestParameters.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequestAdvancedDataPolicies.hpp>
#include <alibabacloud/models/ModifyDbnodesClassRequestDbnode.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupResponseBodyGlobalSecurityIpgroup.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupNameResponseBodyGlobalSecurityIpgroup.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpgroupRelationResponseBodyGlobalSecurityIpgroupRel.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/TempModifyDbnodeRequestDbnode.hpp>

#endif
