// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#define ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AbortDbClusterMigrationRequest.hpp>
#include <alibabacloud/models/AbortDbClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/AbortDbClusterMigrationResponse.hpp>
#include <alibabacloud/models/AddEncryptionDbRolePrivilegeRequest.hpp>
#include <alibabacloud/models/AddEncryptionDbRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/AddEncryptionDbRolePrivilegeResponse.hpp>
#include <alibabacloud/models/AddFirewallRulesRequest.hpp>
#include <alibabacloud/models/AddFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/AddFirewallRulesResponse.hpp>
#include <alibabacloud/models/AddPolarFsQuotaRequest.hpp>
#include <alibabacloud/models/AddPolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/AddPolarFsQuotaResponse.hpp>
#include <alibabacloud/models/AddSqlRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/AddSqlRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/AddSqlRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsRequest.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsResponseBody.hpp>
#include <alibabacloud/models/AttachApplicationPolarFsResponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaRequest.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaResponseBody.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaResponse.hpp>
#include <alibabacloud/models/CancelScheduleTasksRequest.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponse.hpp>
#include <alibabacloud/models/CheckAccountNameRequest.hpp>
#include <alibabacloud/models/CheckAccountNameResponseBody.hpp>
#include <alibabacloud/models/CheckAccountNameResponse.hpp>
#include <alibabacloud/models/CheckAccountNameZonalRequest.hpp>
#include <alibabacloud/models/CheckAccountNameZonalResponseBody.hpp>
#include <alibabacloud/models/CheckAccountNameZonalResponse.hpp>
#include <alibabacloud/models/CheckConnectionStringRequest.hpp>
#include <alibabacloud/models/CheckConnectionStringResponseBody.hpp>
#include <alibabacloud/models/CheckConnectionStringResponse.hpp>
#include <alibabacloud/models/CheckDbNameRequest.hpp>
#include <alibabacloud/models/CheckDbNameResponseBody.hpp>
#include <alibabacloud/models/CheckDbNameResponse.hpp>
#include <alibabacloud/models/CheckDbNameZonalRequest.hpp>
#include <alibabacloud/models/CheckDbNameZonalResponseBody.hpp>
#include <alibabacloud/models/CheckDbNameZonalResponse.hpp>
#include <alibabacloud/models/CheckKmsAuthorizedRequest.hpp>
#include <alibabacloud/models/CheckKmsAuthorizedResponseBody.hpp>
#include <alibabacloud/models/CheckKmsAuthorizedResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CloseAiTaskRequest.hpp>
#include <alibabacloud/models/CloseAiTaskResponseBody.hpp>
#include <alibabacloud/models/CloseAiTaskResponse.hpp>
#include <alibabacloud/models/CloseDbClusterMigrationRequest.hpp>
#include <alibabacloud/models/CloseDbClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/CloseDbClusterMigrationResponse.hpp>
#include <alibabacloud/models/ContinueDbClusterMigrationRequest.hpp>
#include <alibabacloud/models/ContinueDbClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ContinueDbClusterMigrationResponse.hpp>
#include <alibabacloud/models/CreateAiNodesRequest.hpp>
#include <alibabacloud/models/CreateAiNodesResponseBody.hpp>
#include <alibabacloud/models/CreateAiNodesResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateAccountZonalRequest.hpp>
#include <alibabacloud/models/CreateAccountZonalResponseBody.hpp>
#include <alibabacloud/models/CreateAccountZonalResponse.hpp>
#include <alibabacloud/models/CreateActivationCodeRequest.hpp>
#include <alibabacloud/models/CreateActivationCodeResponseBody.hpp>
#include <alibabacloud/models/CreateActivationCodeResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationShrinkRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CreateDbClusterRequest.hpp>
#include <alibabacloud/models/CreateDbClusterResponseBody.hpp>
#include <alibabacloud/models/CreateDbClusterResponse.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointRequest.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointResponse.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/CreateDbClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/CreateDbEndpointAddressRequest.hpp>
#include <alibabacloud/models/CreateDbEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateDbEndpointAddressResponse.hpp>
#include <alibabacloud/models/CreateDbLinkRequest.hpp>
#include <alibabacloud/models/CreateDbLinkResponseBody.hpp>
#include <alibabacloud/models/CreateDbLinkResponse.hpp>
#include <alibabacloud/models/CreateDbNodesRequest.hpp>
#include <alibabacloud/models/CreateDbNodesResponseBody.hpp>
#include <alibabacloud/models/CreateDbNodesResponse.hpp>
#include <alibabacloud/models/CreateDatabaseRequest.hpp>
#include <alibabacloud/models/CreateDatabaseResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseResponse.hpp>
#include <alibabacloud/models/CreateDatabaseZonalRequest.hpp>
#include <alibabacloud/models/CreateDatabaseZonalResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseZonalResponse.hpp>
#include <alibabacloud/models/CreateExtensionsRequest.hpp>
#include <alibabacloud/models/CreateExtensionsResponseBody.hpp>
#include <alibabacloud/models/CreateExtensionsResponse.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpGroupRequest.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpGroupResponse.hpp>
#include <alibabacloud/models/CreateNetworkChannelRequest.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponse.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderRequest.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponseBody.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponse.hpp>
#include <alibabacloud/models/CreateParameterGroupRequest.hpp>
#include <alibabacloud/models/CreateParameterGroupResponseBody.hpp>
#include <alibabacloud/models/CreateParameterGroupResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateStoragePlanRequest.hpp>
#include <alibabacloud/models/CreateStoragePlanResponseBody.hpp>
#include <alibabacloud/models/CreateStoragePlanResponse.hpp>
#include <alibabacloud/models/DeleteAidbClusterRequest.hpp>
#include <alibabacloud/models/DeleteAidbClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteAidbClusterResponse.hpp>
#include <alibabacloud/models/DeleteAiNodesRequest.hpp>
#include <alibabacloud/models/DeleteAiNodesResponseBody.hpp>
#include <alibabacloud/models/DeleteAiNodesResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteAccountZonalRequest.hpp>
#include <alibabacloud/models/DeleteAccountZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountZonalResponse.hpp>
#include <alibabacloud/models/DeleteApplicationRequest.hpp>
#include <alibabacloud/models/DeleteApplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationResponse.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteDbClusterRequest.hpp>
#include <alibabacloud/models/DeleteDbClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteDbClusterResponse.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointRequest.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointResponse.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteDbClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/DeleteDbEndpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteDbEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteDbEndpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteDbLinkRequest.hpp>
#include <alibabacloud/models/DeleteDbLinkResponseBody.hpp>
#include <alibabacloud/models/DeleteDbLinkResponse.hpp>
#include <alibabacloud/models/DeleteDbNodesRequest.hpp>
#include <alibabacloud/models/DeleteDbNodesResponseBody.hpp>
#include <alibabacloud/models/DeleteDbNodesResponse.hpp>
#include <alibabacloud/models/DeleteDatabaseRequest.hpp>
#include <alibabacloud/models/DeleteDatabaseResponseBody.hpp>
#include <alibabacloud/models/DeleteDatabaseResponse.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalRequest.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalResponse.hpp>
#include <alibabacloud/models/DeleteEncryptionDbRolePrivilegeRequest.hpp>
#include <alibabacloud/models/DeleteEncryptionDbRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DeleteEncryptionDbRolePrivilegeResponse.hpp>
#include <alibabacloud/models/DeleteExtensionsRequest.hpp>
#include <alibabacloud/models/DeleteExtensionsResponseBody.hpp>
#include <alibabacloud/models/DeleteExtensionsResponse.hpp>
#include <alibabacloud/models/DeleteFirewallRulesRequest.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpGroupRequest.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpGroupResponse.hpp>
#include <alibabacloud/models/DeleteMaskingRulesRequest.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponse.hpp>
#include <alibabacloud/models/DeleteNetworkChannelRequest.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponse.hpp>
#include <alibabacloud/models/DeleteParameterGroupRequest.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponse.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaRequest.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaResponse.hpp>
#include <alibabacloud/models/DeleteSqlRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DeleteSqlRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteSqlRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAidbClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeAidbClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeAidbClustersRequest.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponse.hpp>
#include <alibabacloud/models/DescribeAiTaskStatusRequest.hpp>
#include <alibabacloud/models/DescribeAiTaskStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAiTaskStatusResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeAccountsZonalRequest.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodesRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeRequest.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponse.hpp>
#include <alibabacloud/models/DescribeApplicationParametersRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersShrinkRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponse.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfRequest.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfResponse.hpp>
#include <alibabacloud/models/DescribeApplicationsRequest.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationsResponse.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsRequest.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupLogsRequest.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupRegionsRequest.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupTasksRequest.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameRequest.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponseBody.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponse.hpp>
#include <alibabacloud/models/DescribeClassListRequest.hpp>
#include <alibabacloud/models/DescribeClassListResponseBody.hpp>
#include <alibabacloud/models/DescribeClassListResponse.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterConnectivityRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterConnectivityResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterConnectivityResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterEncryptionKeyRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterEncryptionKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterEncryptionKeyResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsZonalRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsZonalResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterMonitorRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterMonitorResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterProxyRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterProxyResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterProxyResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterSslRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterSslResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterSslResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterServerlessConfRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterServerlessConfResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterTdeRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterTdeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterTdeResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionZonalRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionZonalResponse.hpp>
#include <alibabacloud/models/DescribeDbClustersRequest.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClustersResponse.hpp>
#include <alibabacloud/models/DescribeDbClustersWithBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDbClustersWithBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClustersWithBackupsResponse.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalRequest.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalResponse.hpp>
#include <alibabacloud/models/DescribeDbInitializeVariableRequest.hpp>
#include <alibabacloud/models/DescribeDbInitializeVariableResponseBody.hpp>
#include <alibabacloud/models/DescribeDbInitializeVariableResponse.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbLinksRequest.hpp>
#include <alibabacloud/models/DescribeDbLinksResponseBody.hpp>
#include <alibabacloud/models/DescribeDbLinksResponse.hpp>
#include <alibabacloud/models/DescribeDbLogFilesRequest.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponse.hpp>
#include <alibabacloud/models/DescribeDbMiniEngineVersionsRequest.hpp>
#include <alibabacloud/models/DescribeDbMiniEngineVersionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbMiniEngineVersionsResponse.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbNodesParametersRequest.hpp>
#include <alibabacloud/models/DescribeDbNodesParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbNodesParametersResponse.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDasConfigRequest.hpp>
#include <alibabacloud/models/DescribeDasConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDasConfigResponse.hpp>
#include <alibabacloud/models/DescribeDatabasesRequest.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBody.hpp>
#include <alibabacloud/models/DescribeDatabasesResponse.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalRequest.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponse.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDbRolePrivilegeRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDbRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDbRolePrivilegeResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDbSecretRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDbSecretResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDbSecretResponse.hpp>
#include <alibabacloud/models/DescribeExtensionsRequest.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeExtensionsResponse.hpp>
#include <alibabacloud/models/DescribeFirewallRulesRequest.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupRelationRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupRelationResponse.hpp>
#include <alibabacloud/models/DescribeHaLogsRequest.hpp>
#include <alibabacloud/models/DescribeHaLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeHaLogsResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponse.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeRequest.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponseBody.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponse.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeMaskingRulesRequest.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponse.hpp>
#include <alibabacloud/models/DescribeMetaListRequest.hpp>
#include <alibabacloud/models/DescribeMetaListResponseBody.hpp>
#include <alibabacloud/models/DescribeMetaListResponse.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogRequest.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBody.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponse.hpp>
#include <alibabacloud/models/DescribeNetworkChannelRequest.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupsRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponse.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponse.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeRequest.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeResponse.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaRequest.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaResponse.hpp>
#include <alibabacloud/models/DescribePolarSqlCollectorPolicyRequest.hpp>
#include <alibabacloud/models/DescribePolarSqlCollectorPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribePolarSqlCollectorPolicyResponse.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponse.hpp>
#include <alibabacloud/models/DescribeRdsVpcsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBody.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponse.hpp>
#include <alibabacloud/models/DescribeSqlRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DescribeSqlRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeScheduleTasksRequest.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponse.hpp>
#include <alibabacloud/models/DescribeTasksRequest.hpp>
#include <alibabacloud/models/DescribeTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeTasksResponse.hpp>
#include <alibabacloud/models/DescribeUpgradeReportRequest.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBody.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponse.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchListRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchListResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchListResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchesRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponse.hpp>
#include <alibabacloud/models/DescribeVpcsRequest.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DisableDbClusterOrcaRequest.hpp>
#include <alibabacloud/models/DisableDbClusterOrcaResponseBody.hpp>
#include <alibabacloud/models/DisableDbClusterOrcaResponse.hpp>
#include <alibabacloud/models/DisableDbClusterServerlessRequest.hpp>
#include <alibabacloud/models/DisableDbClusterServerlessResponseBody.hpp>
#include <alibabacloud/models/DisableDbClusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableDbClusterOrcaRequest.hpp>
#include <alibabacloud/models/EnableDbClusterOrcaResponseBody.hpp>
#include <alibabacloud/models/EnableDbClusterOrcaResponse.hpp>
#include <alibabacloud/models/EnableDbClusterServerlessRequest.hpp>
#include <alibabacloud/models/EnableDbClusterServerlessResponseBody.hpp>
#include <alibabacloud/models/EnableDbClusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableFirewallRulesRequest.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponse.hpp>
#include <alibabacloud/models/EnableSqlRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/EnableSqlRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/EnableSqlRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/EvaluateRegionResourceRequest.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponseBody.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponse.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApiRequest.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApiResponseBody.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenApiResponse.hpp>
#include <alibabacloud/models/FailoverDbClusterRequest.hpp>
#include <alibabacloud/models/FailoverDbClusterResponseBody.hpp>
#include <alibabacloud/models/FailoverDbClusterResponse.hpp>
#include <alibabacloud/models/FailoverDbClusterZonalRequest.hpp>
#include <alibabacloud/models/FailoverDbClusterZonalResponseBody.hpp>
#include <alibabacloud/models/FailoverDbClusterZonalResponse.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneRequest.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponseBody.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalResponse.hpp>
#include <alibabacloud/models/ListOrdersRequest.hpp>
#include <alibabacloud/models/ListOrdersResponseBody.hpp>
#include <alibabacloud/models/ListOrdersResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionRequest.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponse.hpp>
#include <alibabacloud/models/ManuallyStartDbClusterRequest.hpp>
#include <alibabacloud/models/ManuallyStartDbClusterResponseBody.hpp>
#include <alibabacloud/models/ManuallyStartDbClusterResponse.hpp>
#include <alibabacloud/models/ModifyAidbClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAidbClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAidbClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyAccountLockStateRequest.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyApplicationParameterRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterShrinkRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponse.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfRequest.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfResponse.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterAndNodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterAndNodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterAndNodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterArchRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterArchResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterArchResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterDeletionRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterDeletionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterDeletionResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMigrationEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMonitorRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMonitorResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMonitorResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterParametersResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterPrimaryZoneRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterPrimaryZoneResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterPrimaryZoneResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterSslRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterSslResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterSslResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterServerlessConfRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterServerlessConfResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterStoragePerformanceRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterStoragePerformanceResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterStoragePerformanceResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterStorageSpaceRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterStorageSpaceResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterStorageSpaceResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterTdeRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterTdeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterTdeResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterVpcRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterVpcResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterVpcResponse.hpp>
#include <alibabacloud/models/ModifyDbDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyDbDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDbDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyDbEndpointAddressRequest.hpp>
#include <alibabacloud/models/ModifyDbEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/ModifyDbEndpointAddressResponse.hpp>
#include <alibabacloud/models/ModifyDbNodeClassRequest.hpp>
#include <alibabacloud/models/ModifyDbNodeClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodeClassResponse.hpp>
#include <alibabacloud/models/ModifyDbNodeConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbNodeConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodeConfigResponse.hpp>
#include <alibabacloud/models/ModifyDbNodeDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbNodeDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodeDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbNodeHotReplicaModeRequest.hpp>
#include <alibabacloud/models/ModifyDbNodeHotReplicaModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodeHotReplicaModeResponse.hpp>
#include <alibabacloud/models/ModifyDbNodeSccModeRequest.hpp>
#include <alibabacloud/models/ModifyDbNodeSccModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodeSccModeResponse.hpp>
#include <alibabacloud/models/ModifyDbNodesClassRequest.hpp>
#include <alibabacloud/models/ModifyDbNodesClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodesClassResponse.hpp>
#include <alibabacloud/models/ModifyDbNodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDbNodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDbNodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDbRolePrivilegeRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDbRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDbRolePrivilegeResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDbSecretRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDbSecretResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDbSecretResponse.hpp>
#include <alibabacloud/models/ModifyFirewallRulesRequest.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponse.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupNameRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupNameResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupNameResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupRelationRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupRelationResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupRelationResponse.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyMaskingRulesRequest.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponse.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/ModifyResourcePackageRequest.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponseBody.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponse.hpp>
#include <alibabacloud/models/ModifySqlRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/ModifySqlRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifySqlRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/ModifyScheduleTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponse.hpp>
#include <alibabacloud/models/OpenAiTaskRequest.hpp>
#include <alibabacloud/models/OpenAiTaskResponseBody.hpp>
#include <alibabacloud/models/OpenAiTaskResponse.hpp>
#include <alibabacloud/models/ReactivateDbClusterBackupRequest.hpp>
#include <alibabacloud/models/ReactivateDbClusterBackupResponseBody.hpp>
#include <alibabacloud/models/ReactivateDbClusterBackupResponse.hpp>
#include <alibabacloud/models/RefreshDbClusterStorageUsageRequest.hpp>
#include <alibabacloud/models/RefreshDbClusterStorageUsageResponseBody.hpp>
#include <alibabacloud/models/RefreshDbClusterStorageUsageResponse.hpp>
#include <alibabacloud/models/RemoveDbClusterFromGdnRequest.hpp>
#include <alibabacloud/models/RemoveDbClusterFromGdnResponseBody.hpp>
#include <alibabacloud/models/RemoveDbClusterFromGdnResponse.hpp>
#include <alibabacloud/models/ResetAccountRequest.hpp>
#include <alibabacloud/models/ResetAccountResponseBody.hpp>
#include <alibabacloud/models/ResetAccountResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/ResetAccountZonalRequest.hpp>
#include <alibabacloud/models/ResetAccountZonalResponseBody.hpp>
#include <alibabacloud/models/ResetAccountZonalResponse.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/RestartDbLinkRequest.hpp>
#include <alibabacloud/models/RestartDbLinkResponseBody.hpp>
#include <alibabacloud/models/RestartDbLinkResponse.hpp>
#include <alibabacloud/models/RestartDbNodeRequest.hpp>
#include <alibabacloud/models/RestartDbNodeResponseBody.hpp>
#include <alibabacloud/models/RestartDbNodeResponse.hpp>
#include <alibabacloud/models/RestartDbNodeZonalRequest.hpp>
#include <alibabacloud/models/RestartDbNodeZonalResponseBody.hpp>
#include <alibabacloud/models/RestartDbNodeZonalResponse.hpp>
#include <alibabacloud/models/RestoreTableRequest.hpp>
#include <alibabacloud/models/RestoreTableResponseBody.hpp>
#include <alibabacloud/models/RestoreTableResponse.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalRequest.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalResponseBody.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalResponse.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaRequest.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaResponseBody.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaResponse.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TempModifyDbNodeRequest.hpp>
#include <alibabacloud/models/TempModifyDbNodeResponseBody.hpp>
#include <alibabacloud/models/TempModifyDbNodeResponse.hpp>
#include <alibabacloud/models/TransformDbClusterPayTypeRequest.hpp>
#include <alibabacloud/models/TransformDbClusterPayTypeResponseBody.hpp>
#include <alibabacloud/models/TransformDbClusterPayTypeResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateExtensionsRequest.hpp>
#include <alibabacloud/models/UpdateExtensionsResponseBody.hpp>
#include <alibabacloud/models/UpdateExtensionsResponse.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionRequest.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionResponse.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionZonalRequest.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionZonalResponseBody.hpp>
#include <alibabacloud/models/UpgradeDbClusterVersionZonalResponse.hpp>
#include <alibabacloud/models/AddPolarFsQuotaRequestQuotas.hpp>
#include <alibabacloud/models/CreateAiNodesRequestDbNodes.hpp>
#include <alibabacloud/models/CreateApplicationRequestComponents.hpp>
#include <alibabacloud/models/CreateApplicationRequestEndpoints.hpp>
#include <alibabacloud/models/CreateApplicationResponseBodyComponents.hpp>
#include <alibabacloud/models/CreateDbClusterRequestTag.hpp>
#include <alibabacloud/models/CreateDbEndpointAddressRequestZoneInfo.hpp>
#include <alibabacloud/models/CreateDbNodesRequestDbNode.hpp>
#include <alibabacloud/models/CreateDbNodesResponseBodyDbNodeIds.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIpGroupResponseBodyGlobalSecurityIpGroup.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIpGroupResponseBodyGlobalSecurityIpGroup.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaRequestQuotas.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBodyDbNodesChildVolumes.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBodyDbNodes.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBodyEndpointListNetInfoItems.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBodyEndpointList.hpp>
#include <alibabacloud/models/DescribeAidbClusterAttributeResponseBodyVolumes.hpp>
#include <alibabacloud/models/DescribeAidbClusterPerformanceResponseBodyPerformanceKeysPoints.hpp>
#include <alibabacloud/models/DescribeAidbClusterPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeAidbClustersRequestTag.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponseBodyItemsDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponseBodyItemsDbClusterTags.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponseBodyItemsDbCluster.hpp>
#include <alibabacloud/models/DescribeAidbClustersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountsDatabasePrivileges.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccounts.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponseBodyAccountsDatabasePrivileges.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponseBodyAccounts.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBodyConfig.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsSecurityGroups.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsSecurityIpArrays.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponentsTopology.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyComponents.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodyEndpoints.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodySecurityGroups.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBodySecurityIpArrays.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplatesComponentParameterTemplatesParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplatesComponentParameterTemplates.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameterTemplates.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParametersComponentParametersParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParametersComponentParameters.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfResponseBodyServerlessConfItems.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplicationsEndpointsEndpoint.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplicationsEndpoints.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItemsApplications.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItemsAutoRenewAttribute.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBodyItemsBackupLog.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBodyAdvancedDataPoliciesAdvancedDataPolicy.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBodyAdvancedDataPolicies.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBodyItemsBackupJob.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItemsBackup.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponseBodyCharacterSetNameItems.hpp>
#include <alibabacloud/models/DescribeClassListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyOssClusterInfoList.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyTablesChildObjects.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponseBodyCrossCloudLevelList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBodyCrossCloudRegionListCrossCloudZoneList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBodyCrossCloudRegionList.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponseBodyCrossCloudRegionMappingList.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponseBodyDbClusterSecurityGroupsDbClusterSecurityGroup.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponseBodyDbClusterSecurityGroups.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponseBodyItemsDbClusterIpArray.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhitelistResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyDbNodes.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesResponseBodyAvailableZonesSupportedEnginesAvailableResources.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesResponseBodyAvailableZonesSupportedEngines.hpp>
#include <alibabacloud/models/DescribeDbClusterAvailableResourcesResponseBodyAvailableZones.hpp>
#include <alibabacloud/models/DescribeDbClusterEncryptionKeyResponseBodyEncryptionKeyList.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsResponseBodyItemsAddressItems.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsZonalResponseBodyItemsAddressItems.hpp>
#include <alibabacloud/models/DescribeDbClusterEndpointsZonalResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponseBodyDbClusterEndpointListAddressItems.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponseBodyDbClusterEndpointList.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponseBodyRdsEndpointListAddressItems.hpp>
#include <alibabacloud/models/DescribeDbClusterMigrationResponseBodyRdsEndpointList.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbClusterNetInfosDbClusterNetInfo.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbClusterNetInfos.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbNodeNetInfosDbNodeNetInfoNetInfosNetInfo.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbNodeNetInfosDbNodeNetInfoNetInfos.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbNodeNetInfosDbNodeNetInfo.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyDbNodeNetInfos.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponseBodyParametersParameters.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponseBodyRunningParametersParameter.hpp>
#include <alibabacloud/models/DescribeDbClusterParametersResponseBodyRunningParameters.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbClusterProxyResponseBodyChildInstances.hpp>
#include <alibabacloud/models/DescribeDbClusterSslResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionResponseBodyDbRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionResponseBodyProxyRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionZonalResponseBodyDbRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbClusterVersionZonalResponseBodyProxyRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbClustersRequestTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterDbNodesDbNode.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterDbNodes.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTags.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClustersWithBackupsResponseBodyItemsDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClustersWithBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalRequestTag.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalResponseBodyItemsTags.hpp>
#include <alibabacloud/models/DescribeDbClustersZonalResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbInitializeVariableResponseBodyVariablesVariable.hpp>
#include <alibabacloud/models/DescribeDbInitializeVariableResponseBodyVariables.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbInstancePerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbLinksResponseBodyDbLinkInfos.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodyHaLogItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchListItemsSwitchLogItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchListItemsSwitchLogItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchListItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchListItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchLogItemsSwitchStepItems.hpp>
#include <alibabacloud/models/DescribeDbLogFilesResponseBodySwitchLogItems.hpp>
#include <alibabacloud/models/DescribeDbMiniEngineVersionsResponseBodyDbRevisionVersionList.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbNodePerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDbNodesParametersResponseBodyDbNodeIdsRunningParameters.hpp>
#include <alibabacloud/models/DescribeDbNodesParametersResponseBodyDbNodeIds.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponseBodyPerformanceKeysPerformanceItemPointsPerformanceItemValue.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponseBodyPerformanceKeysPerformanceItemPoints.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponseBodyPerformanceKeysPerformanceItem.hpp>
#include <alibabacloud/models/DescribeDbProxyPerformanceResponseBodyPerformanceKeys.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabaseAccountsAccount.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabaseAccounts.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabasesDatabase.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBodyDatabases.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponseBodyDatabasesAccounts.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponseBodyDatabases.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponseBodyDbNodes.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBodyItemsBackup.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeEncryptionDbRolePrivilegeResponseBodyDataRolePrivilegeList.hpp>
#include <alibabacloud/models/DescribeEncryptionDbRolePrivilegeResponseBodyData.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBodyInstalledExtensions.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBodyUninstalledExtensions.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksChannels.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopologyDestinations.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopologySources.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworksNetworkTopology.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItemsNetworks.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyConnections.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyDbClustersDbNodes.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyDbClusters.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBodyLabels.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItemsDbClusters.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItemsLabels.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupResponseBodyGlobalSecurityIpGroup.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIpGroupRelationResponseBodyGlobalSecurityIpGroupRel.hpp>
#include <alibabacloud/models/DescribeHaLogsResponseBodyHaLogItems.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBodyAdvancedLogPoliciesAdvancedLogPolicy.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBodyAdvancedLogPolicies.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeMetaListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponseBodyChannelInfos.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBodyParameterGroupParameterDetail.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBodyParameterGroup.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBodyParameterGroups.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBodyParametersTemplateRecord.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBodyParameters.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponseBodyItems.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponseBodyTypeList.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeResponseBodyMountInfo.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaResponseBodyPolicyItems.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponseBodyVSwitchesVSwitch.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponseBodyVSwitches.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpcVSwitchs.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcsVpc.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZonesZone.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageListResourcePackageQuotaList.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageListTags.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBodyResourcePackageList.hpp>
#include <alibabacloud/models/DescribeSqlRateLimitingRulesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBodyDataTimerInfos.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItemsSqlSlowRecord.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBodyItemsSqlSlowLog.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTasksResponseBodyTasksTask.hpp>
#include <alibabacloud/models/DescribeTasksResponseBodyTasks.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBodyUpgradeReportList.hpp>
#include <alibabacloud/models/DescribeVSwitchListResponseBodyVSwitchs.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBodyVSwitchs.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcsVSwitchs.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZones.hpp>
#include <alibabacloud/models/ListOrdersResponseBodyOrderList.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyApplicationParameterRequestParameters.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfRequestServerlessConfList.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequestAdvancedDataPolicies.hpp>
#include <alibabacloud/models/ModifyDbNodesClassRequestDbNode.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupResponseBodyGlobalSecurityIpGroup.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupNameResponseBodyGlobalSecurityIpGroup.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIpGroupRelationResponseBodyGlobalSecurityIpGroupRel.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyRequestAdvancedLogPolicies.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaRequestFilePathQuotas.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/TempModifyDbNodeRequestDbNode.hpp>

#endif
