// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#define ALIBABACLOUD_POLARDB20170801MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AbortDBClusterMigrationRequest.hpp>
#include <alibabacloud/models/AbortDBClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/AbortDBClusterMigrationResponse.hpp>
#include <alibabacloud/models/AddEncryptionDBRolePrivilegeRequest.hpp>
#include <alibabacloud/models/AddEncryptionDBRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/AddEncryptionDBRolePrivilegeResponse.hpp>
#include <alibabacloud/models/AddFirewallRulesRequest.hpp>
#include <alibabacloud/models/AddFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/AddFirewallRulesResponse.hpp>
#include <alibabacloud/models/AddPolarFsQuotaRequest.hpp>
#include <alibabacloud/models/AddPolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/AddPolarFsQuotaResponse.hpp>
#include <alibabacloud/models/AddSQLRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/AddSQLRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/AddSQLRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/AttachApplicationPolarFSRequest.hpp>
#include <alibabacloud/models/AttachApplicationPolarFSResponseBody.hpp>
#include <alibabacloud/models/AttachApplicationPolarFSResponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CancelCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaRequest.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaResponseBody.hpp>
#include <alibabacloud/models/CancelPolarFsFileQuotaResponse.hpp>
#include <alibabacloud/models/CancelScheduleTasksRequest.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/CancelScheduleTasksResponse.hpp>
#include <alibabacloud/models/CheckAccountNameRequest.hpp>
#include <alibabacloud/models/CheckAccountNameResponseBody.hpp>
#include <alibabacloud/models/CheckAccountNameResponse.hpp>
#include <alibabacloud/models/CheckAccountNameZonalRequest.hpp>
#include <alibabacloud/models/CheckAccountNameZonalResponseBody.hpp>
#include <alibabacloud/models/CheckAccountNameZonalResponse.hpp>
#include <alibabacloud/models/CheckConnectionStringRequest.hpp>
#include <alibabacloud/models/CheckConnectionStringResponseBody.hpp>
#include <alibabacloud/models/CheckConnectionStringResponse.hpp>
#include <alibabacloud/models/CheckDBNameRequest.hpp>
#include <alibabacloud/models/CheckDBNameResponseBody.hpp>
#include <alibabacloud/models/CheckDBNameResponse.hpp>
#include <alibabacloud/models/CheckDBNameZonalRequest.hpp>
#include <alibabacloud/models/CheckDBNameZonalResponseBody.hpp>
#include <alibabacloud/models/CheckDBNameZonalResponse.hpp>
#include <alibabacloud/models/CheckKMSAuthorizedRequest.hpp>
#include <alibabacloud/models/CheckKMSAuthorizedResponseBody.hpp>
#include <alibabacloud/models/CheckKMSAuthorizedResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/ClonePolarFsBasicSnapshotRequest.hpp>
#include <alibabacloud/models/ClonePolarFsBasicSnapshotResponseBody.hpp>
#include <alibabacloud/models/ClonePolarFsBasicSnapshotResponse.hpp>
#include <alibabacloud/models/CloseAITaskRequest.hpp>
#include <alibabacloud/models/CloseAITaskResponseBody.hpp>
#include <alibabacloud/models/CloseAITaskResponse.hpp>
#include <alibabacloud/models/CloseDBClusterMigrationRequest.hpp>
#include <alibabacloud/models/CloseDBClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/CloseDBClusterMigrationResponse.hpp>
#include <alibabacloud/models/ContinueDBClusterMigrationRequest.hpp>
#include <alibabacloud/models/ContinueDBClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ContinueDBClusterMigrationResponse.hpp>
#include <alibabacloud/models/CreateAINodesRequest.hpp>
#include <alibabacloud/models/CreateAINodesResponseBody.hpp>
#include <alibabacloud/models/CreateAINodesResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateAccountZonalRequest.hpp>
#include <alibabacloud/models/CreateAccountZonalResponseBody.hpp>
#include <alibabacloud/models/CreateAccountZonalResponse.hpp>
#include <alibabacloud/models/CreateActivationCodeRequest.hpp>
#include <alibabacloud/models/CreateActivationCodeResponseBody.hpp>
#include <alibabacloud/models/CreateActivationCodeResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationShrinkRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/CreateBackupRequest.hpp>
#include <alibabacloud/models/CreateBackupResponseBody.hpp>
#include <alibabacloud/models/CreateBackupResponse.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/CreateCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/CreateDBClusterRequest.hpp>
#include <alibabacloud/models/CreateDBClusterResponseBody.hpp>
#include <alibabacloud/models/CreateDBClusterResponse.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointRequest.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointResponse.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/CreateDBClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/CreateDBEndpointAddressRequest.hpp>
#include <alibabacloud/models/CreateDBEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/CreateDBEndpointAddressResponse.hpp>
#include <alibabacloud/models/CreateDBLinkRequest.hpp>
#include <alibabacloud/models/CreateDBLinkResponseBody.hpp>
#include <alibabacloud/models/CreateDBLinkResponse.hpp>
#include <alibabacloud/models/CreateDBNodesRequest.hpp>
#include <alibabacloud/models/CreateDBNodesResponseBody.hpp>
#include <alibabacloud/models/CreateDBNodesResponse.hpp>
#include <alibabacloud/models/CreateDatabaseRequest.hpp>
#include <alibabacloud/models/CreateDatabaseResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseResponse.hpp>
#include <alibabacloud/models/CreateDatabaseZonalRequest.hpp>
#include <alibabacloud/models/CreateDatabaseZonalResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseZonalResponse.hpp>
#include <alibabacloud/models/CreateExtensionsRequest.hpp>
#include <alibabacloud/models/CreateExtensionsResponseBody.hpp>
#include <alibabacloud/models/CreateExtensionsResponse.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/CreateNetworkChannelRequest.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/CreateNetworkChannelResponse.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderRequest.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponseBody.hpp>
#include <alibabacloud/models/CreateOrGetVirtualLicenseOrderResponse.hpp>
#include <alibabacloud/models/CreateParameterGroupRequest.hpp>
#include <alibabacloud/models/CreateParameterGroupResponseBody.hpp>
#include <alibabacloud/models/CreateParameterGroupResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateStoragePlanRequest.hpp>
#include <alibabacloud/models/CreateStoragePlanResponseBody.hpp>
#include <alibabacloud/models/CreateStoragePlanResponse.hpp>
#include <alibabacloud/models/DeleteAIDBClusterRequest.hpp>
#include <alibabacloud/models/DeleteAIDBClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteAIDBClusterResponse.hpp>
#include <alibabacloud/models/DeleteAINodesRequest.hpp>
#include <alibabacloud/models/DeleteAINodesResponseBody.hpp>
#include <alibabacloud/models/DeleteAINodesResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteAccountZonalRequest.hpp>
#include <alibabacloud/models/DeleteAccountZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountZonalResponse.hpp>
#include <alibabacloud/models/DeleteApplicationRequest.hpp>
#include <alibabacloud/models/DeleteApplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationResponse.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationEndpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteBackupRequest.hpp>
#include <alibabacloud/models/DeleteBackupResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupResponse.hpp>
#include <alibabacloud/models/DeleteDBClusterRequest.hpp>
#include <alibabacloud/models/DeleteDBClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteDBClusterResponse.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointRequest.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointResponse.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteDBClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/DeleteDBEndpointAddressRequest.hpp>
#include <alibabacloud/models/DeleteDBEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteDBEndpointAddressResponse.hpp>
#include <alibabacloud/models/DeleteDBLinkRequest.hpp>
#include <alibabacloud/models/DeleteDBLinkResponseBody.hpp>
#include <alibabacloud/models/DeleteDBLinkResponse.hpp>
#include <alibabacloud/models/DeleteDBNodesRequest.hpp>
#include <alibabacloud/models/DeleteDBNodesResponseBody.hpp>
#include <alibabacloud/models/DeleteDBNodesResponse.hpp>
#include <alibabacloud/models/DeleteDatabaseRequest.hpp>
#include <alibabacloud/models/DeleteDatabaseResponseBody.hpp>
#include <alibabacloud/models/DeleteDatabaseResponse.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalRequest.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalResponseBody.hpp>
#include <alibabacloud/models/DeleteDatabaseZonalResponse.hpp>
#include <alibabacloud/models/DeleteEncryptionDBRolePrivilegeRequest.hpp>
#include <alibabacloud/models/DeleteEncryptionDBRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DeleteEncryptionDBRolePrivilegeResponse.hpp>
#include <alibabacloud/models/DeleteExtensionsRequest.hpp>
#include <alibabacloud/models/DeleteExtensionsResponseBody.hpp>
#include <alibabacloud/models/DeleteExtensionsResponse.hpp>
#include <alibabacloud/models/DeleteFirewallRulesRequest.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteFirewallRulesResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDataNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DeleteMaskingRulesRequest.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteMaskingRulesResponse.hpp>
#include <alibabacloud/models/DeleteNetworkChannelRequest.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteNetworkChannelResponse.hpp>
#include <alibabacloud/models/DeleteParameterGroupRequest.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteParameterGroupResponse.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaRequest.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/DeletePolarFsQuotaResponse.hpp>
#include <alibabacloud/models/DeleteSQLRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DeleteSQLRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteSQLRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeAIDBClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAIDBClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAIDBClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAIDBClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeAIDBClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeAIDBClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskLogFilesRequest.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskLogFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskLogFilesResponse.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskMetricsRequest.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskMetricsResponseBody.hpp>
#include <alibabacloud/models/DescribeAIDBClusterTaskMetricsResponse.hpp>
#include <alibabacloud/models/DescribeAIDBClustersRequest.hpp>
#include <alibabacloud/models/DescribeAIDBClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeAIDBClustersResponse.hpp>
#include <alibabacloud/models/DescribeAITaskStatusRequest.hpp>
#include <alibabacloud/models/DescribeAITaskStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAITaskStatusResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeAccountsZonalRequest.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsZonalResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodeDetailsResponse.hpp>
#include <alibabacloud/models/DescribeActivationCodesRequest.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponseBody.hpp>
#include <alibabacloud/models/DescribeActivationCodesResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeRequest.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationAttributeResponse.hpp>
#include <alibabacloud/models/DescribeApplicationParametersRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersShrinkRequest.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationParametersResponse.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfRequest.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationServerlessConfResponse.hpp>
#include <alibabacloud/models/DescribeApplicationsRequest.hpp>
#include <alibabacloud/models/DescribeApplicationsResponseBody.hpp>
#include <alibabacloud/models/DescribeApplicationsResponse.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsRequest.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableCrossRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupLogsRequest.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupLogsResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupRegionsRequest.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupRegionsResponse.hpp>
#include <alibabacloud/models/DescribeBackupTasksRequest.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupTasksResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameRequest.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponseBody.hpp>
#include <alibabacloud/models/DescribeCharacterSetNameResponse.hpp>
#include <alibabacloud/models/DescribeClassListRequest.hpp>
#include <alibabacloud/models/DescribeClassListResponseBody.hpp>
#include <alibabacloud/models/DescribeClassListResponse.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceRequest.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeColdStorageInstanceResponse.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/DescribeCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudLevelsResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionResponse.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunRequest.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossCloudRegionMappingToAliyunResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterAvailableResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterAvailableResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterAvailableResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterConnectivityRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterConnectivityResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterConnectivityResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterEncryptionKeyRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterEncryptionKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterEncryptionKeyResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsZonalRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterEndpointsZonalResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterMigrationRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterMigrationResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterMonitorRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterMonitorResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterParametersRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterParametersResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterProxyRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterProxyResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterProxyResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterSSLRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterSSLResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterSSLResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterServerlessConfRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterServerlessConfResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterTDERequest.hpp>
#include <alibabacloud/models/DescribeDBClusterTDEResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterTDEResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionResponse.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionZonalRequest.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClusterVersionZonalResponse.hpp>
#include <alibabacloud/models/DescribeDBClustersRequest.hpp>
#include <alibabacloud/models/DescribeDBClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClustersResponse.hpp>
#include <alibabacloud/models/DescribeDBClustersWithBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDBClustersWithBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClustersWithBackupsResponse.hpp>
#include <alibabacloud/models/DescribeDBClustersZonalRequest.hpp>
#include <alibabacloud/models/DescribeDBClustersZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDBClustersZonalResponse.hpp>
#include <alibabacloud/models/DescribeDBInitializeVariableRequest.hpp>
#include <alibabacloud/models/DescribeDBInitializeVariableResponseBody.hpp>
#include <alibabacloud/models/DescribeDBInitializeVariableResponse.hpp>
#include <alibabacloud/models/DescribeDBInstancePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDBInstancePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDBInstancePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDBLinksRequest.hpp>
#include <alibabacloud/models/DescribeDBLinksResponseBody.hpp>
#include <alibabacloud/models/DescribeDBLinksResponse.hpp>
#include <alibabacloud/models/DescribeDBLogFilesRequest.hpp>
#include <alibabacloud/models/DescribeDBLogFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeDBLogFilesResponse.hpp>
#include <alibabacloud/models/DescribeDBMiniEngineVersionsRequest.hpp>
#include <alibabacloud/models/DescribeDBMiniEngineVersionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDBMiniEngineVersionsResponse.hpp>
#include <alibabacloud/models/DescribeDBNodePerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDBNodePerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDBNodePerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDBNodesParametersRequest.hpp>
#include <alibabacloud/models/DescribeDBNodesParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeDBNodesParametersResponse.hpp>
#include <alibabacloud/models/DescribeDBProxyPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDBProxyPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDBProxyPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDasConfigRequest.hpp>
#include <alibabacloud/models/DescribeDasConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDasConfigResponse.hpp>
#include <alibabacloud/models/DescribeDatabasesRequest.hpp>
#include <alibabacloud/models/DescribeDatabasesResponseBody.hpp>
#include <alibabacloud/models/DescribeDatabasesResponse.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalRequest.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDatabasesZonalResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeZonalResponse.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsRequest.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDetachedBackupsResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDBRolePrivilegeRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDBRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDBRolePrivilegeResponse.hpp>
#include <alibabacloud/models/DescribeEncryptionDBSecretRequest.hpp>
#include <alibabacloud/models/DescribeEncryptionDBSecretResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptionDBSecretResponse.hpp>
#include <alibabacloud/models/DescribeExtensionsRequest.hpp>
#include <alibabacloud/models/DescribeExtensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeExtensionsResponse.hpp>
#include <alibabacloud/models/DescribeFirewallRulesRequest.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeFirewallRulesResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDataNetworkListResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDatabaseNetworksResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalSecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/DescribeHALogsRequest.hpp>
#include <alibabacloud/models/DescribeHALogsResponseBody.hpp>
#include <alibabacloud/models/DescribeHALogsResponse.hpp>
#include <alibabacloud/models/DescribeHistoryEventsRequest.hpp>
#include <alibabacloud/models/DescribeHistoryEventsResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryEventsResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksResponse.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryTasksStatResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrderDetailsResponse.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersRequest.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponseBody.hpp>
#include <alibabacloud/models/DescribeLicenseOrdersResponse.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeRequest.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponseBody.hpp>
#include <alibabacloud/models/DescribeLocalAvailableRecoveryTimeResponse.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeMaskingRulesRequest.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeMaskingRulesResponse.hpp>
#include <alibabacloud/models/DescribeMetaListRequest.hpp>
#include <alibabacloud/models/DescribeMetaListResponseBody.hpp>
#include <alibabacloud/models/DescribeMetaListResponse.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogRequest.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponseBody.hpp>
#include <alibabacloud/models/DescribeModifyParameterLogResponse.hpp>
#include <alibabacloud/models/DescribeNetworkChannelRequest.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkChannelResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupResponse.hpp>
#include <alibabacloud/models/DescribeParameterGroupsRequest.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterGroupsResponse.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeParameterTemplatesResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsRequest.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponseBody.hpp>
#include <alibabacloud/models/DescribePendingMaintenanceActionsResponse.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeRequest.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribePolarFsAttributeResponse.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaRequest.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribePolarFsQuotaResponse.hpp>
#include <alibabacloud/models/DescribePolarSQLCollectorPolicyRequest.hpp>
#include <alibabacloud/models/DescribePolarSQLCollectorPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribePolarSQLCollectorPolicyResponse.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVSwitchsResponse.hpp>
#include <alibabacloud/models/DescribeRdsVpcsRequest.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsVpcsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponseBody.hpp>
#include <alibabacloud/models/DescribeResourcePackagesResponse.hpp>
#include <alibabacloud/models/DescribeSQLRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/DescribeSQLRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeSQLRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/DescribeScheduleTasksRequest.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduleTasksResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogsResponse.hpp>
#include <alibabacloud/models/DescribeTasksRequest.hpp>
#include <alibabacloud/models/DescribeTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeTasksResponse.hpp>
#include <alibabacloud/models/DescribeUpgradeReportRequest.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponseBody.hpp>
#include <alibabacloud/models/DescribeUpgradeReportResponse.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchListRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchListResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchListResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchesRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponse.hpp>
#include <alibabacloud/models/DescribeVpcsRequest.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DisableDBClusterOrcaRequest.hpp>
#include <alibabacloud/models/DisableDBClusterOrcaResponseBody.hpp>
#include <alibabacloud/models/DisableDBClusterOrcaResponse.hpp>
#include <alibabacloud/models/DisableDBClusterServerlessRequest.hpp>
#include <alibabacloud/models/DisableDBClusterServerlessResponseBody.hpp>
#include <alibabacloud/models/DisableDBClusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableDBClusterOrcaRequest.hpp>
#include <alibabacloud/models/EnableDBClusterOrcaResponseBody.hpp>
#include <alibabacloud/models/EnableDBClusterOrcaResponse.hpp>
#include <alibabacloud/models/EnableDBClusterServerlessRequest.hpp>
#include <alibabacloud/models/EnableDBClusterServerlessResponseBody.hpp>
#include <alibabacloud/models/EnableDBClusterServerlessResponse.hpp>
#include <alibabacloud/models/EnableFirewallRulesRequest.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/EnableFirewallRulesResponse.hpp>
#include <alibabacloud/models/EnableSQLRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/EnableSQLRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/EnableSQLRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/EvaluateRegionResourceRequest.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponseBody.hpp>
#include <alibabacloud/models/EvaluateRegionResourceResponse.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenAPIRequest.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenAPIResponseBody.hpp>
#include <alibabacloud/models/ExecuteCrossCloudOpenAPIResponse.hpp>
#include <alibabacloud/models/FailoverDBClusterRequest.hpp>
#include <alibabacloud/models/FailoverDBClusterResponseBody.hpp>
#include <alibabacloud/models/FailoverDBClusterResponse.hpp>
#include <alibabacloud/models/FailoverDBClusterZonalRequest.hpp>
#include <alibabacloud/models/FailoverDBClusterZonalResponseBody.hpp>
#include <alibabacloud/models/FailoverDBClusterZonalResponse.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneRequest.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponseBody.hpp>
#include <alibabacloud/models/GenerateUpgradeReportForSyncCloneResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalRequest.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalResponseBody.hpp>
#include <alibabacloud/models/GrantAccountPrivilegeZonalResponse.hpp>
#include <alibabacloud/models/ListOrdersRequest.hpp>
#include <alibabacloud/models/ListOrdersResponseBody.hpp>
#include <alibabacloud/models/ListOrdersResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionRequest.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesForRegionResponse.hpp>
#include <alibabacloud/models/ManuallyStartDBClusterRequest.hpp>
#include <alibabacloud/models/ManuallyStartDBClusterResponseBody.hpp>
#include <alibabacloud/models/ManuallyStartDBClusterResponse.hpp>
#include <alibabacloud/models/ModifyAIDBClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAIDBClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAIDBClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyAccountLockStateRequest.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountLockStateResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordResponse.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalRequest.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountPasswordZonalResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyApplicationParameterRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterShrinkRequest.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationParameterResponse.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfRequest.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationServerlessConfResponse.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyApplicationWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessRequest.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponseBody.hpp>
#include <alibabacloud/models/ModifyCronJobPolicyServerlessResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterAccessWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterAccessWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterAccessWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterAndNodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterAndNodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterAndNodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterArchRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterArchResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterArchResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterAuditLogCollectorRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterAuditLogCollectorResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterAuditLogCollectorResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterDeletionRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterDeletionResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterDeletionResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointZonalRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterEndpointZonalResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationEndpointRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationEndpointResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterMigrationEndpointResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterMonitorRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterMonitorResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterMonitorResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterParametersRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterParametersResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterPrimaryZoneRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterPrimaryZoneResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterPrimaryZoneResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterSSLRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterSSLResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterSSLResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterServerlessConfRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterServerlessConfResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterServerlessConfResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterStoragePerformanceRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterStoragePerformanceResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterStoragePerformanceResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterStorageSpaceRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterStorageSpaceResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterStorageSpaceResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterTDERequest.hpp>
#include <alibabacloud/models/ModifyDBClusterTDEResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterTDEResponse.hpp>
#include <alibabacloud/models/ModifyDBClusterVpcRequest.hpp>
#include <alibabacloud/models/ModifyDBClusterVpcResponseBody.hpp>
#include <alibabacloud/models/ModifyDBClusterVpcResponse.hpp>
#include <alibabacloud/models/ModifyDBDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDBDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDBDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDBDescriptionZonalRequest.hpp>
#include <alibabacloud/models/ModifyDBDescriptionZonalResponseBody.hpp>
#include <alibabacloud/models/ModifyDBDescriptionZonalResponse.hpp>
#include <alibabacloud/models/ModifyDBEndpointAddressRequest.hpp>
#include <alibabacloud/models/ModifyDBEndpointAddressResponseBody.hpp>
#include <alibabacloud/models/ModifyDBEndpointAddressResponse.hpp>
#include <alibabacloud/models/ModifyDBNodeClassRequest.hpp>
#include <alibabacloud/models/ModifyDBNodeClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodeClassResponse.hpp>
#include <alibabacloud/models/ModifyDBNodeConfigRequest.hpp>
#include <alibabacloud/models/ModifyDBNodeConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodeConfigResponse.hpp>
#include <alibabacloud/models/ModifyDBNodeDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDBNodeDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodeDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDBNodeHotReplicaModeRequest.hpp>
#include <alibabacloud/models/ModifyDBNodeHotReplicaModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodeHotReplicaModeResponse.hpp>
#include <alibabacloud/models/ModifyDBNodeSccModeRequest.hpp>
#include <alibabacloud/models/ModifyDBNodeSccModeResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodeSccModeResponse.hpp>
#include <alibabacloud/models/ModifyDBNodesClassRequest.hpp>
#include <alibabacloud/models/ModifyDBNodesClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodesClassResponse.hpp>
#include <alibabacloud/models/ModifyDBNodesParametersRequest.hpp>
#include <alibabacloud/models/ModifyDBNodesParametersResponseBody.hpp>
#include <alibabacloud/models/ModifyDBNodesParametersResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDBRolePrivilegeRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDBRolePrivilegeResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDBRolePrivilegeResponse.hpp>
#include <alibabacloud/models/ModifyEncryptionDBSecretRequest.hpp>
#include <alibabacloud/models/ModifyEncryptionDBSecretResponseBody.hpp>
#include <alibabacloud/models/ModifyEncryptionDBSecretResponse.hpp>
#include <alibabacloud/models/ModifyFirewallRulesRequest.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyFirewallRulesResponse.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupNameResponse.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationRequest.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalSecurityIPGroupRelationResponse.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyMaskingRulesRequest.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifyMaskingRulesResponse.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionRequest.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/ModifyPendingMaintenanceActionResponse.hpp>
#include <alibabacloud/models/ModifyResourcePackageRequest.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponseBody.hpp>
#include <alibabacloud/models/ModifyResourcePackageResponse.hpp>
#include <alibabacloud/models/ModifySQLRateLimitingRulesRequest.hpp>
#include <alibabacloud/models/ModifySQLRateLimitingRulesResponseBody.hpp>
#include <alibabacloud/models/ModifySQLRateLimitingRulesResponse.hpp>
#include <alibabacloud/models/ModifyScheduleTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduleTaskResponse.hpp>
#include <alibabacloud/models/OpenAITaskRequest.hpp>
#include <alibabacloud/models/OpenAITaskResponseBody.hpp>
#include <alibabacloud/models/OpenAITaskResponse.hpp>
#include <alibabacloud/models/ReactivateDBClusterBackupRequest.hpp>
#include <alibabacloud/models/ReactivateDBClusterBackupResponseBody.hpp>
#include <alibabacloud/models/ReactivateDBClusterBackupResponse.hpp>
#include <alibabacloud/models/RefreshDBClusterStorageUsageRequest.hpp>
#include <alibabacloud/models/RefreshDBClusterStorageUsageResponseBody.hpp>
#include <alibabacloud/models/RefreshDBClusterStorageUsageResponse.hpp>
#include <alibabacloud/models/RemoveDBClusterFromGDNRequest.hpp>
#include <alibabacloud/models/RemoveDBClusterFromGDNResponseBody.hpp>
#include <alibabacloud/models/RemoveDBClusterFromGDNResponse.hpp>
#include <alibabacloud/models/ResetAccountRequest.hpp>
#include <alibabacloud/models/ResetAccountResponseBody.hpp>
#include <alibabacloud/models/ResetAccountResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/ResetAccountZonalRequest.hpp>
#include <alibabacloud/models/ResetAccountZonalResponseBody.hpp>
#include <alibabacloud/models/ResetAccountZonalResponse.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/ResetGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/RestartDBLinkRequest.hpp>
#include <alibabacloud/models/RestartDBLinkResponseBody.hpp>
#include <alibabacloud/models/RestartDBLinkResponse.hpp>
#include <alibabacloud/models/RestartDBNodeRequest.hpp>
#include <alibabacloud/models/RestartDBNodeResponseBody.hpp>
#include <alibabacloud/models/RestartDBNodeResponse.hpp>
#include <alibabacloud/models/RestartDBNodeZonalRequest.hpp>
#include <alibabacloud/models/RestartDBNodeZonalResponseBody.hpp>
#include <alibabacloud/models/RestartDBNodeZonalResponse.hpp>
#include <alibabacloud/models/RestoreTableRequest.hpp>
#include <alibabacloud/models/RestoreTableResponseBody.hpp>
#include <alibabacloud/models/RestoreTableResponse.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeRequest.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponseBody.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeResponse.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalRequest.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalResponseBody.hpp>
#include <alibabacloud/models/RevokeAccountPrivilegeZonalResponse.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaRequest.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaResponseBody.hpp>
#include <alibabacloud/models/SetPolarFsFileQuotaResponse.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkRequest.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponseBody.hpp>
#include <alibabacloud/models/SwitchOverGlobalDatabaseNetworkResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TempModifyDBNodeRequest.hpp>
#include <alibabacloud/models/TempModifyDBNodeResponseBody.hpp>
#include <alibabacloud/models/TempModifyDBNodeResponse.hpp>
#include <alibabacloud/models/TransformDBClusterPayTypeRequest.hpp>
#include <alibabacloud/models/TransformDBClusterPayTypeResponseBody.hpp>
#include <alibabacloud/models/TransformDBClusterPayTypeResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateExtensionsRequest.hpp>
#include <alibabacloud/models/UpdateExtensionsResponseBody.hpp>
#include <alibabacloud/models/UpdateExtensionsResponse.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionRequest.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionResponse.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionZonalRequest.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionZonalResponseBody.hpp>
#include <alibabacloud/models/UpgradeDBClusterVersionZonalResponse.hpp>

#endif
