// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ADB20190315MODEL_HPP_
#define ALIBABACLOUD_ADB20190315MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionRequest.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionResponseBody.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionResponse.hpp>
#include <alibabacloud/models/ApplyAdviceByIdRequest.hpp>
#include <alibabacloud/models/ApplyAdviceByIdResponseBody.hpp>
#include <alibabacloud/models/ApplyAdviceByIdResponse.hpp>
#include <alibabacloud/models/AttachUserEniRequest.hpp>
#include <alibabacloud/models/AttachUserEniResponseBody.hpp>
#include <alibabacloud/models/AttachUserEniResponse.hpp>
#include <alibabacloud/models/BatchApplyAdviceByIdListRequest.hpp>
#include <alibabacloud/models/BatchApplyAdviceByIdListResponseBody.hpp>
#include <alibabacloud/models/BatchApplyAdviceByIdListResponse.hpp>
#include <alibabacloud/models/BindDbResourceGroupWithUserRequest.hpp>
#include <alibabacloud/models/BindDbResourceGroupWithUserResponseBody.hpp>
#include <alibabacloud/models/BindDbResourceGroupWithUserResponse.hpp>
#include <alibabacloud/models/BindDbResourcePoolWithUserRequest.hpp>
#include <alibabacloud/models/BindDbResourcePoolWithUserResponseBody.hpp>
#include <alibabacloud/models/BindDbResourcePoolWithUserResponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountShrinkRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateDbClusterRequest.hpp>
#include <alibabacloud/models/CreateDbClusterResponseBody.hpp>
#include <alibabacloud/models/CreateDbClusterResponse.hpp>
#include <alibabacloud/models/CreateDbResourceGroupRequest.hpp>
#include <alibabacloud/models/CreateDbResourceGroupShrinkRequest.hpp>
#include <alibabacloud/models/CreateDbResourceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDbResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateDbResourcePoolRequest.hpp>
#include <alibabacloud/models/CreateDbResourcePoolResponseBody.hpp>
#include <alibabacloud/models/CreateDbResourcePoolResponse.hpp>
#include <alibabacloud/models/CreateElasticPlanRequest.hpp>
#include <alibabacloud/models/CreateElasticPlanResponseBody.hpp>
#include <alibabacloud/models/CreateElasticPlanResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBackupsRequest.hpp>
#include <alibabacloud/models/DeleteBackupsResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupsResponse.hpp>
#include <alibabacloud/models/DeleteDbClusterRequest.hpp>
#include <alibabacloud/models/DeleteDbClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteDbClusterResponse.hpp>
#include <alibabacloud/models/DeleteDbResourceGroupRequest.hpp>
#include <alibabacloud/models/DeleteDbResourceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDbResourceGroupResponse.hpp>
#include <alibabacloud/models/DeleteDbResourcePoolRequest.hpp>
#include <alibabacloud/models/DeleteDbResourcePoolResponseBody.hpp>
#include <alibabacloud/models/DeleteDbResourcePoolResponse.hpp>
#include <alibabacloud/models/DeleteElasticPlanRequest.hpp>
#include <alibabacloud/models/DeleteElasticPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteElasticPlanResponse.hpp>
#include <alibabacloud/models/DescribeAbnormalPatternDetectionRequest.hpp>
#include <alibabacloud/models/DescribeAbnormalPatternDetectionResponseBody.hpp>
#include <alibabacloud/models/DescribeAbnormalPatternDetectionResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeAdviceServiceEnabledRequest.hpp>
#include <alibabacloud/models/DescribeAdviceServiceEnabledResponseBody.hpp>
#include <alibabacloud/models/DescribeAdviceServiceEnabledResponse.hpp>
#include <alibabacloud/models/DescribeAllAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAllAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAllAccountsResponse.hpp>
#include <alibabacloud/models/DescribeAllDataSourceRequest.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBody.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponse.hpp>
#include <alibabacloud/models/DescribeAppliedAdvicesRequest.hpp>
#include <alibabacloud/models/DescribeAppliedAdvicesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppliedAdvicesResponse.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigRequest.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeAuditLogConfigResponse.hpp>
#include <alibabacloud/models/DescribeAuditLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeAuditLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeAuditLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAvailableAdvicesRequest.hpp>
#include <alibabacloud/models/DescribeAvailableAdvicesResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableAdvicesResponse.hpp>
#include <alibabacloud/models/DescribeAvailableResourceRequest.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionRequest.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionResponseBody.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionResponse.hpp>
#include <alibabacloud/models/DescribeColumnsRequest.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBody.hpp>
#include <alibabacloud/models/DescribeColumnsResponse.hpp>
#include <alibabacloud/models/DescribeComputeResourceRequest.hpp>
#include <alibabacloud/models/DescribeComputeResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeComputeResourceResponse.hpp>
#include <alibabacloud/models/DescribeConnectionCountRecordsRequest.hpp>
#include <alibabacloud/models/DescribeConnectionCountRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeConnectionCountRecordsResponse.hpp>
#include <alibabacloud/models/DescribeControllerDetectionRequest.hpp>
#include <alibabacloud/models/DescribeControllerDetectionResponseBody.hpp>
#include <alibabacloud/models/DescribeControllerDetectionResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterSslRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterSslResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterSslResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterShardNumberRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterShardNumberResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterShardNumberResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusResponse.hpp>
#include <alibabacloud/models/DescribeDbClustersRequest.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClustersResponse.hpp>
#include <alibabacloud/models/DescribeDbResourceGroupRequest.hpp>
#include <alibabacloud/models/DescribeDbResourceGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDbResourceGroupResponse.hpp>
#include <alibabacloud/models/DescribeDbResourcePoolRequest.hpp>
#include <alibabacloud/models/DescribeDbResourcePoolResponseBody.hpp>
#include <alibabacloud/models/DescribeDbResourcePoolResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisDimensionsResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlInfoRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlInfoResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisTasksRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisTasksResponse.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsRequest.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponse.hpp>
#include <alibabacloud/models/DescribeEiuRangeRequest.hpp>
#include <alibabacloud/models/DescribeEiuRangeResponseBody.hpp>
#include <alibabacloud/models/DescribeEiuRangeResponse.hpp>
#include <alibabacloud/models/DescribeElasticDailyPlanRequest.hpp>
#include <alibabacloud/models/DescribeElasticDailyPlanResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticDailyPlanResponse.hpp>
#include <alibabacloud/models/DescribeElasticPlanRequest.hpp>
#include <alibabacloud/models/DescribeElasticPlanResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticPlanResponse.hpp>
#include <alibabacloud/models/DescribeExcessivePrimaryKeysRequest.hpp>
#include <alibabacloud/models/DescribeExcessivePrimaryKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeExcessivePrimaryKeysResponse.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionRequest.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBody.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponse.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatRequest.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatResponse.hpp>
#include <alibabacloud/models/DescribeInclinedNodesRequest.hpp>
#include <alibabacloud/models/DescribeInclinedNodesResponseBody.hpp>
#include <alibabacloud/models/DescribeInclinedNodesResponse.hpp>
#include <alibabacloud/models/DescribeInclinedTablesRequest.hpp>
#include <alibabacloud/models/DescribeInclinedTablesResponseBody.hpp>
#include <alibabacloud/models/DescribeInclinedTablesResponse.hpp>
#include <alibabacloud/models/DescribeKernelVersionRequest.hpp>
#include <alibabacloud/models/DescribeKernelVersionResponseBody.hpp>
#include <alibabacloud/models/DescribeKernelVersionResponse.hpp>
#include <alibabacloud/models/DescribeKmsKeysRequest.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponse.hpp>
#include <alibabacloud/models/DescribeLoadTasksRecordsRequest.hpp>
#include <alibabacloud/models/DescribeLoadTasksRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeLoadTasksRecordsResponse.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeRequest.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeResponse.hpp>
#include <alibabacloud/models/DescribeLogStoreKeysRequest.hpp>
#include <alibabacloud/models/DescribeLogStoreKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeLogStoreKeysResponse.hpp>
#include <alibabacloud/models/DescribeLoghubDetailRequest.hpp>
#include <alibabacloud/models/DescribeLoghubDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeLoghubDetailResponse.hpp>
#include <alibabacloud/models/DescribeMaintenanceActionRequest.hpp>
#include <alibabacloud/models/DescribeMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/DescribeMaintenanceActionResponse.hpp>
#include <alibabacloud/models/DescribeOperatorPermissionRequest.hpp>
#include <alibabacloud/models/DescribeOperatorPermissionResponseBody.hpp>
#include <alibabacloud/models/DescribeOperatorPermissionResponse.hpp>
#include <alibabacloud/models/DescribeOversizeNonPartitionTableInfosRequest.hpp>
#include <alibabacloud/models/DescribeOversizeNonPartitionTableInfosResponseBody.hpp>
#include <alibabacloud/models/DescribeOversizeNonPartitionTableInfosResponse.hpp>
#include <alibabacloud/models/DescribePatternPerformanceRequest.hpp>
#include <alibabacloud/models/DescribePatternPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribePatternPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeProcessListRequest.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBody.hpp>
#include <alibabacloud/models/DescribeProcessListResponse.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasRequest.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBody.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRegionsMixedRequest.hpp>
#include <alibabacloud/models/DescribeRegionsMixedResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsMixedResponse.hpp>
#include <alibabacloud/models/DescribeResubmitConfigRequest.hpp>
#include <alibabacloud/models/DescribeResubmitConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeResubmitConfigResponse.hpp>
#include <alibabacloud/models/DescribeSqaConfigRequest.hpp>
#include <alibabacloud/models/DescribeSqaConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeSqaConfigResponse.hpp>
#include <alibabacloud/models/DescribeSqlPatternsRequest.hpp>
#include <alibabacloud/models/DescribeSqlPatternsResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlPatternsResponse.hpp>
#include <alibabacloud/models/DescribeSqlPlanRequest.hpp>
#include <alibabacloud/models/DescribeSqlPlanResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlPlanResponse.hpp>
#include <alibabacloud/models/DescribeSqlPlanTaskRequest.hpp>
#include <alibabacloud/models/DescribeSqlPlanTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlPlanTaskResponse.hpp>
#include <alibabacloud/models/DescribeSchemasRequest.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBody.hpp>
#include <alibabacloud/models/DescribeSchemasResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSqlPatternRequest.hpp>
#include <alibabacloud/models/DescribeSqlPatternResponseBody.hpp>
#include <alibabacloud/models/DescribeSqlPatternResponse.hpp>
#include <alibabacloud/models/DescribeSyncAvailableDbClusterListRequest.hpp>
#include <alibabacloud/models/DescribeSyncAvailableDbClusterListResponseBody.hpp>
#include <alibabacloud/models/DescribeSyncAvailableDbClusterListResponse.hpp>
#include <alibabacloud/models/DescribeSyncJobListRequest.hpp>
#include <alibabacloud/models/DescribeSyncJobListResponseBody.hpp>
#include <alibabacloud/models/DescribeSyncJobListResponse.hpp>
#include <alibabacloud/models/DescribeTableAccessCountRequest.hpp>
#include <alibabacloud/models/DescribeTableAccessCountResponseBody.hpp>
#include <alibabacloud/models/DescribeTableAccessCountResponse.hpp>
#include <alibabacloud/models/DescribeTableDetailRequest.hpp>
#include <alibabacloud/models/DescribeTableDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeTableDetailResponse.hpp>
#include <alibabacloud/models/DescribeTablePartitionDiagnoseRequest.hpp>
#include <alibabacloud/models/DescribeTablePartitionDiagnoseResponseBody.hpp>
#include <alibabacloud/models/DescribeTablePartitionDiagnoseResponse.hpp>
#include <alibabacloud/models/DescribeTableStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeTableStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeTableStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeTablesRequest.hpp>
#include <alibabacloud/models/DescribeTablesResponseBody.hpp>
#include <alibabacloud/models/DescribeTablesResponse.hpp>
#include <alibabacloud/models/DescribeTaskInfoRequest.hpp>
#include <alibabacloud/models/DescribeTaskInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeTaskInfoResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchesRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchsRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchsResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchsResponse.hpp>
#include <alibabacloud/models/DescribeVpcsRequest.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcsResponse.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionRequest.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBody.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponse.hpp>
#include <alibabacloud/models/DetachUserEniRequest.hpp>
#include <alibabacloud/models/DetachUserEniResponseBody.hpp>
#include <alibabacloud/models/DetachUserEniResponse.hpp>
#include <alibabacloud/models/DisableAdviceServiceRequest.hpp>
#include <alibabacloud/models/DisableAdviceServiceResponseBody.hpp>
#include <alibabacloud/models/DisableAdviceServiceResponse.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsRequest.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsResponseBody.hpp>
#include <alibabacloud/models/DownloadDiagnosisRecordsResponse.hpp>
#include <alibabacloud/models/EnableAdviceServiceRequest.hpp>
#include <alibabacloud/models/EnableAdviceServiceResponseBody.hpp>
#include <alibabacloud/models/EnableAdviceServiceResponse.hpp>
#include <alibabacloud/models/GetCreateTableSqlRequest.hpp>
#include <alibabacloud/models/GetCreateTableSqlResponseBody.hpp>
#include <alibabacloud/models/GetCreateTableSqlResponse.hpp>
#include <alibabacloud/models/GrantOperatorPermissionRequest.hpp>
#include <alibabacloud/models/GrantOperatorPermissionResponseBody.hpp>
#include <alibabacloud/models/GrantOperatorPermissionResponse.hpp>
#include <alibabacloud/models/KillProcessRequest.hpp>
#include <alibabacloud/models/KillProcessResponseBody.hpp>
#include <alibabacloud/models/KillProcessResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/MigrateDbClusterRequest.hpp>
#include <alibabacloud/models/MigrateDbClusterResponseBody.hpp>
#include <alibabacloud/models/MigrateDbClusterResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigRequest.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyAuditLogConfigResponse.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyClusterConnectionStringRequest.hpp>
#include <alibabacloud/models/ModifyClusterConnectionStringResponseBody.hpp>
#include <alibabacloud/models/ModifyClusterConnectionStringResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterPayTypeRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterPayTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterPayTypeResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterSslRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterSslResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterSslResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterShardNumberRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterShardNumberResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterShardNumberResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterVipRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterVipResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterVipResponse.hpp>
#include <alibabacloud/models/ModifyDbResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDbResourceGroupShrinkRequest.hpp>
#include <alibabacloud/models/ModifyDbResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDbResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDbResourcePoolRequest.hpp>
#include <alibabacloud/models/ModifyDbResourcePoolResponseBody.hpp>
#include <alibabacloud/models/ModifyDbResourcePoolResponse.hpp>
#include <alibabacloud/models/ModifyElasticPlanRequest.hpp>
#include <alibabacloud/models/ModifyElasticPlanResponseBody.hpp>
#include <alibabacloud/models/ModifyElasticPlanResponse.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyLogBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyLogHubStatusRequest.hpp>
#include <alibabacloud/models/ModifyLogHubStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyLogHubStatusResponse.hpp>
#include <alibabacloud/models/ModifyMaintenanceActionRequest.hpp>
#include <alibabacloud/models/ModifyMaintenanceActionResponseBody.hpp>
#include <alibabacloud/models/ModifyMaintenanceActionResponse.hpp>
#include <alibabacloud/models/ModifyResubmitConfigRequest.hpp>
#include <alibabacloud/models/ModifyResubmitConfigShrinkRequest.hpp>
#include <alibabacloud/models/ModifyResubmitConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyResubmitConfigResponse.hpp>
#include <alibabacloud/models/ModifySqaConfigRequest.hpp>
#include <alibabacloud/models/ModifySqaConfigResponseBody.hpp>
#include <alibabacloud/models/ModifySqaConfigResponse.hpp>
#include <alibabacloud/models/ModifySyncJobRequest.hpp>
#include <alibabacloud/models/ModifySyncJobResponseBody.hpp>
#include <alibabacloud/models/ModifySyncJobResponse.hpp>
#include <alibabacloud/models/OperateLogHubRequest.hpp>
#include <alibabacloud/models/OperateLogHubResponseBody.hpp>
#include <alibabacloud/models/OperateLogHubResponse.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionRequest.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionResponseBody.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/RevokeOperatorPermissionRequest.hpp>
#include <alibabacloud/models/RevokeOperatorPermissionResponseBody.hpp>
#include <alibabacloud/models/RevokeOperatorPermissionResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnbindDbResourceGroupWithUserRequest.hpp>
#include <alibabacloud/models/UnbindDbResourceGroupWithUserResponseBody.hpp>
#include <alibabacloud/models/UnbindDbResourceGroupWithUserResponse.hpp>
#include <alibabacloud/models/UnbindDbResourcePoolWithUserRequest.hpp>
#include <alibabacloud/models/UnbindDbResourcePoolWithUserResponseBody.hpp>
#include <alibabacloud/models/UnbindDbResourcePoolWithUserResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpgradeKernelVersionRequest.hpp>
#include <alibabacloud/models/UpgradeKernelVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeKernelVersionResponse.hpp>
#include <alibabacloud/models/CreateAccountRequestTag.hpp>
#include <alibabacloud/models/CreateDbClusterRequestTag.hpp>
#include <alibabacloud/models/DescribeAbnormalPatternDetectionResponseBodyDetectionItemsResults.hpp>
#include <alibabacloud/models/DescribeAbnormalPatternDetectionResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeAccountsRequestTags.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountListDbAccountTagsTag.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountListDbAccountTags.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountListDbAccount.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountList.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBodyConfig.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAllAccountsResponseBodyAccountList.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyColumnsColumn.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyColumns.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodySchemasSchema.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodySchemas.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyTablesTable.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeAppliedAdvicesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAuditLogRecordsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItemsAutoRenewAttribute.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAvailableAdvicesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedFlexibleResourceSupportedElasticIoResource.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedFlexibleResource.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedInstanceClassListSupportedExecutorListNodeCount.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedInstanceClassListSupportedExecutorList.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedInstanceClassListSupportedNodeCountListNodeCount.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedInstanceClassListSupportedNodeCountList.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialListSupportedInstanceClassList.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedModeSupportedSerialList.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneListSupportedMode.hpp>
#include <alibabacloud/models/DescribeAvailableResourceResponseBodyAvailableZoneList.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItemsBackup.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionResponseBodyDetectionItemsResultsDiagnosisResults.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionResponseBodyDetectionItemsResults.hpp>
#include <alibabacloud/models/DescribeBadSqlDetectionResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBodyItemsColumn.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeComputeResourceResponseBodyComputeResource.hpp>
#include <alibabacloud/models/DescribeConnectionCountRecordsResponseBodyAccessIpRecords.hpp>
#include <alibabacloud/models/DescribeConnectionCountRecordsResponseBodyUserRecords.hpp>
#include <alibabacloud/models/DescribeControllerDetectionResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBodyItemsIpArray.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbClusterTags.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbClusterTaskInfoStepListStepList.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbClusterTaskInfoStepList.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbClusterTaskInfo.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItemsDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusResponseBodyCs.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusResponseBodyExecutor.hpp>
#include <alibabacloud/models/DescribeDbClusterHealthStatusResponseBodyWorker.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyItemsAddress.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformancesSeries.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceResponseBodyPerformancesResourcePoolPerformancesResourcePoolSeries.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceResponseBodyPerformancesResourcePoolPerformances.hpp>
#include <alibabacloud/models/DescribeDbClusterResourcePoolPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDbClusterShardNumberResponseBodyAvailableShardNumberList.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponseBodyDataColdData.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponseBodyDataDataGrowth.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponseBodyDataHotData.hpp>
#include <alibabacloud/models/DescribeDbClusterSpaceSummaryResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDbClustersRequestTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTags.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTaskInfoStepListStepList.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTaskInfoStepList.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbClusterTaskInfo.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItemsDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbResourceGroupResponseBodyGroupsInfo.hpp>
#include <alibabacloud/models/DescribeDbResourcePoolResponseBodyPoolsInfo.hpp>
#include <alibabacloud/models/DescribeDiagnosisMonitorPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponseBodyQuerysQueryProperties.hpp>
#include <alibabacloud/models/DescribeDiagnosisRecordsResponseBodyQuerys.hpp>
#include <alibabacloud/models/DescribeDiagnosisSqlInfoResponseBodyStageInfos.hpp>
#include <alibabacloud/models/DescribeDiagnosisTasksResponseBodyTaskList.hpp>
#include <alibabacloud/models/DescribeDownloadRecordsResponseBodyRecords.hpp>
#include <alibabacloud/models/DescribeEiuRangeResponseBodyEiuInfo.hpp>
#include <alibabacloud/models/DescribeElasticDailyPlanResponseBodyElasticDailyPlanList.hpp>
#include <alibabacloud/models/DescribeElasticPlanResponseBodyElasticPlanList.hpp>
#include <alibabacloud/models/DescribeExcessivePrimaryKeysResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeExcessivePrimaryKeysResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItemsResultsOperatorAggSearchResults.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItemsResultsOperatorAgg.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItemsResultsOperatorDetailsSearchResults.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItemsResultsOperatorDetails.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItemsResults.hpp>
#include <alibabacloud/models/DescribeExecutorDetectionResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeHistoryEventsStatResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeInclinedNodesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeInclinedTablesResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeInclinedTablesResponseBodyItemsTable.hpp>
#include <alibabacloud/models/DescribeInclinedTablesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeKernelVersionResponseBodyAvailableKernelVersions.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponseBodyKmsKeysKmsKey.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponseBodyKmsKeys.hpp>
#include <alibabacloud/models/DescribeLoadTasksRecordsResponseBodyLoadTasksRecords.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeResponseBodyLoghubInfoLogHubStoresLogHubStore.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeResponseBodyLoghubInfoLogHubStores.hpp>
#include <alibabacloud/models/DescribeLogHubAttributeResponseBodyLoghubInfo.hpp>
#include <alibabacloud/models/DescribeLogStoreKeysResponseBodyLogStoreKeys.hpp>
#include <alibabacloud/models/DescribeLoghubDetailResponseBodyLoghubInfoLogHubStoresLogHubStore.hpp>
#include <alibabacloud/models/DescribeLoghubDetailResponseBodyLoghubInfoLogHubStores.hpp>
#include <alibabacloud/models/DescribeLoghubDetailResponseBodyLoghubInfo.hpp>
#include <alibabacloud/models/DescribeMaintenanceActionResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeOversizeNonPartitionTableInfosResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeOversizeNonPartitionTableInfosResponseBodyTables.hpp>
#include <alibabacloud/models/DescribePatternPerformanceResponseBodyPerformancesSeries.hpp>
#include <alibabacloud/models/DescribePatternPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyItemsProcess.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeCategoryListDbNodeCategory.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeCategoryList.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeClassListDbNodeClass.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeClassList.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeStorageListDbNodeStorage.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyDbNodeStorageList.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyEngineVersionListEngineVersion.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyEngineVersionList.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyModeListMode.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyModeList.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyStorageTypeListStorageType.hpp>
#include <alibabacloud/models/DescribeRdsAnalysisResourceQuotasResponseBodyStorageTypeList.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZonesZone.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeRegionsMixedResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsMixedResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeResubmitConfigResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeSqlPatternsResponseBodyPatternDetails.hpp>
#include <alibabacloud/models/DescribeSqlPlanResponseBodyDetail.hpp>
#include <alibabacloud/models/DescribeSqlPlanResponseBodyStageList.hpp>
#include <alibabacloud/models/DescribeSqlPlanTaskResponseBodyTaskList.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBodyItemsSchema.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItemsSlowLogRecord.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSqlPatternResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSyncAvailableDbClusterListRequestSourceDbCluster.hpp>
#include <alibabacloud/models/DescribeSyncAvailableDbClusterListResponseBodySyncAvailableDbClusters.hpp>
#include <alibabacloud/models/DescribeSyncJobListResponseBodySyncJobs.hpp>
#include <alibabacloud/models/DescribeTableAccessCountResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTableDetailResponseBodyItemsShard.hpp>
#include <alibabacloud/models/DescribeTableDetailResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTablePartitionDiagnoseResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/DescribeTablePartitionDiagnoseResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTableStatisticsResponseBodyItemsTableStatisticRecords.hpp>
#include <alibabacloud/models/DescribeTableStatisticsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTablesResponseBodyItemsTable.hpp>
#include <alibabacloud/models/DescribeTablesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTaskInfoResponseBodyTaskInfo.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBodyVSwitchesVSwitch.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBodyVSwitches.hpp>
#include <alibabacloud/models/DescribeVSwitchsResponseBodyVSwitchesVSwitch.hpp>
#include <alibabacloud/models/DescribeVSwitchsResponseBodyVSwitches.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcsVpcVSwitchs.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcsVpc.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBodyVpcs.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsOperatorAggSearchResults.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsOperatorAgg.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsOperatorDetailsSearchResults.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsOperatorDetails.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsPartitionedTables.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsSkewedTables.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsTopAccessTablesSearchResults.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResultsTopAccessTables.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItemsResults.hpp>
#include <alibabacloud/models/DescribeWorkerDetectionResponseBodyDetectionItems.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyResubmitConfigRequestRules.hpp>
#include <alibabacloud/models/ModifySyncJobRequestSourceDbCluster.hpp>
#include <alibabacloud/models/OperateLogHubRequestLogHubStores.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
