// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_EXPORTDATAKEYRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_EXPORTDATAKEYRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Kms20160120
{
namespace Models
{
  class ExportDataKeyResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ExportDataKeyResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(ExportedDataKey, exportedDataKey_);
      DARABONBA_PTR_TO_JSON(KeyId, keyId_);
      DARABONBA_PTR_TO_JSON(KeyVersionId, keyVersionId_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, ExportDataKeyResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(ExportedDataKey, exportedDataKey_);
      DARABONBA_PTR_FROM_JSON(KeyId, keyId_);
      DARABONBA_PTR_FROM_JSON(KeyVersionId, keyVersionId_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    ExportDataKeyResponseBody() = default ;
    ExportDataKeyResponseBody(const ExportDataKeyResponseBody &) = default ;
    ExportDataKeyResponseBody(ExportDataKeyResponseBody &&) = default ;
    ExportDataKeyResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ExportDataKeyResponseBody() = default ;
    ExportDataKeyResponseBody& operator=(const ExportDataKeyResponseBody &) = default ;
    ExportDataKeyResponseBody& operator=(ExportDataKeyResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->exportedDataKey_ == nullptr
        && this->keyId_ == nullptr && this->keyVersionId_ == nullptr && this->requestId_ == nullptr; };
    // exportedDataKey Field Functions 
    bool hasExportedDataKey() const { return this->exportedDataKey_ != nullptr;};
    void deleteExportedDataKey() { this->exportedDataKey_ = nullptr;};
    inline string getExportedDataKey() const { DARABONBA_PTR_GET_DEFAULT(exportedDataKey_, "") };
    inline ExportDataKeyResponseBody& setExportedDataKey(string exportedDataKey) { DARABONBA_PTR_SET_VALUE(exportedDataKey_, exportedDataKey) };


    // keyId Field Functions 
    bool hasKeyId() const { return this->keyId_ != nullptr;};
    void deleteKeyId() { this->keyId_ = nullptr;};
    inline string getKeyId() const { DARABONBA_PTR_GET_DEFAULT(keyId_, "") };
    inline ExportDataKeyResponseBody& setKeyId(string keyId) { DARABONBA_PTR_SET_VALUE(keyId_, keyId) };


    // keyVersionId Field Functions 
    bool hasKeyVersionId() const { return this->keyVersionId_ != nullptr;};
    void deleteKeyVersionId() { this->keyVersionId_ = nullptr;};
    inline string getKeyVersionId() const { DARABONBA_PTR_GET_DEFAULT(keyVersionId_, "") };
    inline ExportDataKeyResponseBody& setKeyVersionId(string keyVersionId) { DARABONBA_PTR_SET_VALUE(keyVersionId_, keyVersionId) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ExportDataKeyResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // The exported data key that is protected by public key encryption.
    shared_ptr<string> exportedDataKey_ {};
    // The ID of the CMK that is used to decrypt the ciphertext of the specified data key.<br> The globally unique identifier of the CMK.<br><br>
    shared_ptr<string> keyId_ {};
    // The ID of the key version that is used to decrypt the ciphertext of the specified data key.
    shared_ptr<string> keyVersionId_ {};
    // The ID of the request, which is a unique identifier generated by Alibaba Cloud for the request. You can use the request ID to troubleshoot issues.
    shared_ptr<string> requestId_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Kms20160120
#endif
