// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_IMM20200930MODEL_HPP_
#define ALIBABACLOUD_IMM20200930MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/Address.hpp>
#include <alibabacloud/models/AddressForStory.hpp>
#include <alibabacloud/models/MetaData.hpp>
#include <alibabacloud/models/Property.hpp>
#include <alibabacloud/models/CustomParams.hpp>
#include <alibabacloud/models/Spec.hpp>
#include <alibabacloud/models/ModelSpecification.hpp>
#include <alibabacloud/models/Optimization.hpp>
#include <alibabacloud/models/Schedule.hpp>
#include <alibabacloud/models/Hyperparameters.hpp>
#include <alibabacloud/models/Resource.hpp>
#include <alibabacloud/models/Runtime.hpp>
#include <alibabacloud/models/TrainingSpecification.hpp>
#include <alibabacloud/models/AlgorithmDefinition.hpp>
#include <alibabacloud/models/ReferenceFile.hpp>
#include <alibabacloud/models/Answer.hpp>
#include <alibabacloud/models/App.hpp>
#include <alibabacloud/models/AssumeRoleChainNode.hpp>
#include <alibabacloud/models/AssumeRoleChain.hpp>
#include <alibabacloud/models/AudioStream.hpp>
#include <alibabacloud/models/Binding.hpp>
#include <alibabacloud/models/PointInt64.hpp>
#include <alibabacloud/models/Boundary.hpp>
#include <alibabacloud/models/Body.hpp>
#include <alibabacloud/models/LicensePlate.hpp>
#include <alibabacloud/models/Car.hpp>
#include <alibabacloud/models/Clip.hpp>
#include <alibabacloud/models/ClusterForReq.hpp>
#include <alibabacloud/models/Codes.hpp>
#include <alibabacloud/models/ElementContent.hpp>
#include <alibabacloud/models/ElementRelation.hpp>
#include <alibabacloud/models/Element.hpp>
#include <alibabacloud/models/ContextualFile.hpp>
#include <alibabacloud/models/ContextualMessage.hpp>
#include <alibabacloud/models/CredentialConfig.hpp>
#include <alibabacloud/models/CroppingSuggestion.hpp>
#include <alibabacloud/models/CustomPrompt.hpp>
#include <alibabacloud/models/InputOSS.hpp>
#include <alibabacloud/models/Input.hpp>
#include <alibabacloud/models/DataIngestion.hpp>
#include <alibabacloud/models/InsightsConfig.hpp>
#include <alibabacloud/models/DatasetConfig.hpp>
#include <alibabacloud/models/WorkflowParameter.hpp>
#include <alibabacloud/models/Dataset.hpp>
#include <alibabacloud/models/DatasetTaskStatus.hpp>
#include <alibabacloud/models/DocumentParseKeywordOption.hpp>
#include <alibabacloud/models/DocumentParseNarratorOption.hpp>
#include <alibabacloud/models/DocumentParseQuestionOption.hpp>
#include <alibabacloud/models/DocumentParseSummaryOption.hpp>
#include <alibabacloud/models/DocumentParseOption.hpp>
#include <alibabacloud/models/FastFailPolicy.hpp>
#include <alibabacloud/models/HeadPose.hpp>
#include <alibabacloud/models/Figure.hpp>
#include <alibabacloud/models/ImageScore.hpp>
#include <alibabacloud/models/OCRContents.hpp>
#include <alibabacloud/models/Image.hpp>
#include <alibabacloud/models/ImageInsight.hpp>
#include <alibabacloud/models/VideoInsight.hpp>
#include <alibabacloud/models/Insights.hpp>
#include <alibabacloud/models/Label.hpp>
#include <alibabacloud/models/SceneElement.hpp>
#include <alibabacloud/models/SubtitleStream.hpp>
#include <alibabacloud/models/VideoStream.hpp>
#include <alibabacloud/models/File.hpp>
#include <alibabacloud/models/FigureCluster.hpp>
#include <alibabacloud/models/FigureClusterForReq.hpp>
#include <alibabacloud/models/FileSmartCluster.hpp>
#include <alibabacloud/models/FunctionCall.hpp>
#include <alibabacloud/models/ImageURL.hpp>
#include <alibabacloud/models/InputFile.hpp>
#include <alibabacloud/models/KdtreeOption.hpp>
#include <alibabacloud/models/KeyValuePair.hpp>
#include <alibabacloud/models/LocationDateCluster.hpp>
#include <alibabacloud/models/MNS.hpp>
#include <alibabacloud/models/Message.hpp>
#include <alibabacloud/models/RocketMQ.hpp>
#include <alibabacloud/models/Notification.hpp>
#include <alibabacloud/models/OctreeOption.hpp>
#include <alibabacloud/models/Project.hpp>
#include <alibabacloud/models/RegionType.hpp>
#include <alibabacloud/models/Row.hpp>
#include <alibabacloud/models/SimilarImage.hpp>
#include <alibabacloud/models/SimilarImageCluster.hpp>
#include <alibabacloud/models/SimpleQuery.hpp>
#include <alibabacloud/models/SmartClusterRule.hpp>
#include <alibabacloud/models/SmartCluster.hpp>
#include <alibabacloud/models/Story.hpp>
#include <alibabacloud/models/StreamOptions.hpp>
#include <alibabacloud/models/TargetAudio.hpp>
#include <alibabacloud/models/TargetImage.hpp>
#include <alibabacloud/models/TargetSubtitle.hpp>
#include <alibabacloud/models/TargetVideo.hpp>
#include <alibabacloud/models/TaskInfo.hpp>
#include <alibabacloud/models/TimeRange.hpp>
#include <alibabacloud/models/ToolCall.hpp>
#include <alibabacloud/models/TrimPolicy.hpp>
#include <alibabacloud/models/WebofficePermission.hpp>
#include <alibabacloud/models/WebofficeUser.hpp>
#include <alibabacloud/models/WebofficeWatermark.hpp>
#include <alibabacloud/models/AddImageMosaicRequest.hpp>
#include <alibabacloud/models/AddImageMosaicShrinkRequest.hpp>
#include <alibabacloud/models/AddImageMosaicResponseBody.hpp>
#include <alibabacloud/models/AddImageMosaicResponse.hpp>
#include <alibabacloud/models/AddStoryFilesRequest.hpp>
#include <alibabacloud/models/AddStoryFilesShrinkRequest.hpp>
#include <alibabacloud/models/AddStoryFilesResponseBody.hpp>
#include <alibabacloud/models/AddStoryFilesResponse.hpp>
#include <alibabacloud/models/AttachOSSBucketRequest.hpp>
#include <alibabacloud/models/AttachOSSBucketResponseBody.hpp>
#include <alibabacloud/models/AttachOSSBucketResponse.hpp>
#include <alibabacloud/models/BatchDeleteFileMetaRequest.hpp>
#include <alibabacloud/models/BatchDeleteFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/BatchDeleteFileMetaResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteFileMetaResponse.hpp>
#include <alibabacloud/models/BatchGetFigureClusterRequest.hpp>
#include <alibabacloud/models/BatchGetFigureClusterShrinkRequest.hpp>
#include <alibabacloud/models/BatchGetFigureClusterResponseBody.hpp>
#include <alibabacloud/models/BatchGetFigureClusterResponse.hpp>
#include <alibabacloud/models/BatchGetFileMetaRequest.hpp>
#include <alibabacloud/models/BatchGetFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/BatchGetFileMetaResponseBody.hpp>
#include <alibabacloud/models/BatchGetFileMetaResponse.hpp>
#include <alibabacloud/models/BatchIndexFileMetaRequest.hpp>
#include <alibabacloud/models/BatchIndexFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/BatchIndexFileMetaResponseBody.hpp>
#include <alibabacloud/models/BatchIndexFileMetaResponse.hpp>
#include <alibabacloud/models/BatchUpdateFileMetaRequest.hpp>
#include <alibabacloud/models/BatchUpdateFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/BatchUpdateFileMetaResponseBody.hpp>
#include <alibabacloud/models/BatchUpdateFileMetaResponse.hpp>
#include <alibabacloud/models/CompareImageFacesRequest.hpp>
#include <alibabacloud/models/CompareImageFacesShrinkRequest.hpp>
#include <alibabacloud/models/CompareImageFacesResponseBody.hpp>
#include <alibabacloud/models/CompareImageFacesResponse.hpp>
#include <alibabacloud/models/ContextualAnswerRequest.hpp>
#include <alibabacloud/models/ContextualAnswerShrinkRequest.hpp>
#include <alibabacloud/models/ContextualAnswerResponseBody.hpp>
#include <alibabacloud/models/ContextualAnswerResponse.hpp>
#include <alibabacloud/models/ContextualRetrievalRequest.hpp>
#include <alibabacloud/models/ContextualRetrievalShrinkRequest.hpp>
#include <alibabacloud/models/ContextualRetrievalResponseBody.hpp>
#include <alibabacloud/models/ContextualRetrievalResponse.hpp>
#include <alibabacloud/models/CreateArchiveFileInspectionTaskRequest.hpp>
#include <alibabacloud/models/CreateArchiveFileInspectionTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateArchiveFileInspectionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateArchiveFileInspectionTaskResponse.hpp>
#include <alibabacloud/models/CreateBatchRequest.hpp>
#include <alibabacloud/models/CreateBatchShrinkRequest.hpp>
#include <alibabacloud/models/CreateBatchResponseBody.hpp>
#include <alibabacloud/models/CreateBatchResponse.hpp>
#include <alibabacloud/models/CreateBindingRequest.hpp>
#include <alibabacloud/models/CreateBindingResponseBody.hpp>
#include <alibabacloud/models/CreateBindingResponse.hpp>
#include <alibabacloud/models/CreateCompressPointCloudTaskRequest.hpp>
#include <alibabacloud/models/CreateCompressPointCloudTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateCompressPointCloudTaskResponseBody.hpp>
#include <alibabacloud/models/CreateCompressPointCloudTaskResponse.hpp>
#include <alibabacloud/models/CreateCustomizedStoryRequest.hpp>
#include <alibabacloud/models/CreateCustomizedStoryShrinkRequest.hpp>
#include <alibabacloud/models/CreateCustomizedStoryResponseBody.hpp>
#include <alibabacloud/models/CreateCustomizedStoryResponse.hpp>
#include <alibabacloud/models/CreateDatasetRequest.hpp>
#include <alibabacloud/models/CreateDatasetShrinkRequest.hpp>
#include <alibabacloud/models/CreateDatasetResponseBody.hpp>
#include <alibabacloud/models/CreateDatasetResponse.hpp>
#include <alibabacloud/models/CreateDecodeBlindWatermarkTaskRequest.hpp>
#include <alibabacloud/models/CreateDecodeBlindWatermarkTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateDecodeBlindWatermarkTaskResponseBody.hpp>
#include <alibabacloud/models/CreateDecodeBlindWatermarkTaskResponse.hpp>
#include <alibabacloud/models/CreateFacesSearchingTaskRequest.hpp>
#include <alibabacloud/models/CreateFacesSearchingTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateFacesSearchingTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFacesSearchingTaskResponse.hpp>
#include <alibabacloud/models/CreateFigureClusteringTaskRequest.hpp>
#include <alibabacloud/models/CreateFigureClusteringTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateFigureClusteringTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFigureClusteringTaskResponse.hpp>
#include <alibabacloud/models/CreateFigureClustersMergingTaskRequest.hpp>
#include <alibabacloud/models/CreateFigureClustersMergingTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateFigureClustersMergingTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFigureClustersMergingTaskResponse.hpp>
#include <alibabacloud/models/CreateFileCompressionTaskRequest.hpp>
#include <alibabacloud/models/CreateFileCompressionTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateFileCompressionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFileCompressionTaskResponse.hpp>
#include <alibabacloud/models/CreateFileUncompressionTaskRequest.hpp>
#include <alibabacloud/models/CreateFileUncompressionTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateFileUncompressionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFileUncompressionTaskResponse.hpp>
#include <alibabacloud/models/CreateImageModerationTaskRequest.hpp>
#include <alibabacloud/models/CreateImageModerationTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateImageModerationTaskResponseBody.hpp>
#include <alibabacloud/models/CreateImageModerationTaskResponse.hpp>
#include <alibabacloud/models/CreateImageSplicingTaskRequest.hpp>
#include <alibabacloud/models/CreateImageSplicingTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateImageSplicingTaskResponseBody.hpp>
#include <alibabacloud/models/CreateImageSplicingTaskResponse.hpp>
#include <alibabacloud/models/CreateImageToPDFTaskRequest.hpp>
#include <alibabacloud/models/CreateImageToPDFTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateImageToPDFTaskResponseBody.hpp>
#include <alibabacloud/models/CreateImageToPDFTaskResponse.hpp>
#include <alibabacloud/models/CreateLocationDateClusteringTaskRequest.hpp>
#include <alibabacloud/models/CreateLocationDateClusteringTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateLocationDateClusteringTaskResponseBody.hpp>
#include <alibabacloud/models/CreateLocationDateClusteringTaskResponse.hpp>
#include <alibabacloud/models/CreateMediaConvertTaskRequest.hpp>
#include <alibabacloud/models/CreateMediaConvertTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateMediaConvertTaskResponseBody.hpp>
#include <alibabacloud/models/CreateMediaConvertTaskResponse.hpp>
#include <alibabacloud/models/CreateOfficeConversionTaskRequest.hpp>
#include <alibabacloud/models/CreateOfficeConversionTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateOfficeConversionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateOfficeConversionTaskResponse.hpp>
#include <alibabacloud/models/CreateProjectRequest.hpp>
#include <alibabacloud/models/CreateProjectShrinkRequest.hpp>
#include <alibabacloud/models/CreateProjectResponseBody.hpp>
#include <alibabacloud/models/CreateProjectResponse.hpp>
#include <alibabacloud/models/CreateSimilarImageClusteringTaskRequest.hpp>
#include <alibabacloud/models/CreateSimilarImageClusteringTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateSimilarImageClusteringTaskResponseBody.hpp>
#include <alibabacloud/models/CreateSimilarImageClusteringTaskResponse.hpp>
#include <alibabacloud/models/CreateStoryRequest.hpp>
#include <alibabacloud/models/CreateStoryShrinkRequest.hpp>
#include <alibabacloud/models/CreateStoryResponseBody.hpp>
#include <alibabacloud/models/CreateStoryResponse.hpp>
#include <alibabacloud/models/CreateTriggerRequest.hpp>
#include <alibabacloud/models/CreateTriggerShrinkRequest.hpp>
#include <alibabacloud/models/CreateTriggerResponseBody.hpp>
#include <alibabacloud/models/CreateTriggerResponse.hpp>
#include <alibabacloud/models/CreateVideoLabelClassificationTaskRequest.hpp>
#include <alibabacloud/models/CreateVideoLabelClassificationTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateVideoLabelClassificationTaskResponseBody.hpp>
#include <alibabacloud/models/CreateVideoLabelClassificationTaskResponse.hpp>
#include <alibabacloud/models/CreateVideoModerationTaskRequest.hpp>
#include <alibabacloud/models/CreateVideoModerationTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateVideoModerationTaskResponseBody.hpp>
#include <alibabacloud/models/CreateVideoModerationTaskResponse.hpp>
#include <alibabacloud/models/DeleteBatchRequest.hpp>
#include <alibabacloud/models/DeleteBatchResponseBody.hpp>
#include <alibabacloud/models/DeleteBatchResponse.hpp>
#include <alibabacloud/models/DeleteBindingRequest.hpp>
#include <alibabacloud/models/DeleteBindingResponseBody.hpp>
#include <alibabacloud/models/DeleteBindingResponse.hpp>
#include <alibabacloud/models/DeleteDatasetRequest.hpp>
#include <alibabacloud/models/DeleteDatasetResponseBody.hpp>
#include <alibabacloud/models/DeleteDatasetResponse.hpp>
#include <alibabacloud/models/DeleteFileMetaRequest.hpp>
#include <alibabacloud/models/DeleteFileMetaResponseBody.hpp>
#include <alibabacloud/models/DeleteFileMetaResponse.hpp>
#include <alibabacloud/models/DeleteLocationDateClusterRequest.hpp>
#include <alibabacloud/models/DeleteLocationDateClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteLocationDateClusterResponse.hpp>
#include <alibabacloud/models/DeleteProjectRequest.hpp>
#include <alibabacloud/models/DeleteProjectResponseBody.hpp>
#include <alibabacloud/models/DeleteProjectResponse.hpp>
#include <alibabacloud/models/DeleteStoryRequest.hpp>
#include <alibabacloud/models/DeleteStoryResponseBody.hpp>
#include <alibabacloud/models/DeleteStoryResponse.hpp>
#include <alibabacloud/models/DeleteTriggerRequest.hpp>
#include <alibabacloud/models/DeleteTriggerResponseBody.hpp>
#include <alibabacloud/models/DeleteTriggerResponse.hpp>
#include <alibabacloud/models/DetachOSSBucketRequest.hpp>
#include <alibabacloud/models/DetachOSSBucketResponseBody.hpp>
#include <alibabacloud/models/DetachOSSBucketResponse.hpp>
#include <alibabacloud/models/DetectImageBodiesRequest.hpp>
#include <alibabacloud/models/DetectImageBodiesShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageBodiesResponseBody.hpp>
#include <alibabacloud/models/DetectImageBodiesResponse.hpp>
#include <alibabacloud/models/DetectImageCarsRequest.hpp>
#include <alibabacloud/models/DetectImageCarsShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageCarsResponseBody.hpp>
#include <alibabacloud/models/DetectImageCarsResponse.hpp>
#include <alibabacloud/models/DetectImageCodesRequest.hpp>
#include <alibabacloud/models/DetectImageCodesShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageCodesResponseBody.hpp>
#include <alibabacloud/models/DetectImageCodesResponse.hpp>
#include <alibabacloud/models/DetectImageCroppingRequest.hpp>
#include <alibabacloud/models/DetectImageCroppingShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageCroppingResponseBody.hpp>
#include <alibabacloud/models/DetectImageCroppingResponse.hpp>
#include <alibabacloud/models/DetectImageFacesRequest.hpp>
#include <alibabacloud/models/DetectImageFacesShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageFacesResponseBody.hpp>
#include <alibabacloud/models/DetectImageFacesResponse.hpp>
#include <alibabacloud/models/DetectImageLabelsRequest.hpp>
#include <alibabacloud/models/DetectImageLabelsShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageLabelsResponseBody.hpp>
#include <alibabacloud/models/DetectImageLabelsResponse.hpp>
#include <alibabacloud/models/DetectImageScoreRequest.hpp>
#include <alibabacloud/models/DetectImageScoreShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageScoreResponseBody.hpp>
#include <alibabacloud/models/DetectImageScoreResponse.hpp>
#include <alibabacloud/models/DetectImageTextsRequest.hpp>
#include <alibabacloud/models/DetectImageTextsShrinkRequest.hpp>
#include <alibabacloud/models/DetectImageTextsResponseBody.hpp>
#include <alibabacloud/models/DetectImageTextsResponse.hpp>
#include <alibabacloud/models/DetectMediaMetaRequest.hpp>
#include <alibabacloud/models/DetectMediaMetaShrinkRequest.hpp>
#include <alibabacloud/models/DetectMediaMetaResponseBody.hpp>
#include <alibabacloud/models/DetectMediaMetaResponse.hpp>
#include <alibabacloud/models/DetectTextAnomalyRequest.hpp>
#include <alibabacloud/models/DetectTextAnomalyResponseBody.hpp>
#include <alibabacloud/models/DetectTextAnomalyResponse.hpp>
#include <alibabacloud/models/EncodeBlindWatermarkRequest.hpp>
#include <alibabacloud/models/EncodeBlindWatermarkResponseBody.hpp>
#include <alibabacloud/models/EncodeBlindWatermarkResponse.hpp>
#include <alibabacloud/models/ExtractDocumentTextRequest.hpp>
#include <alibabacloud/models/ExtractDocumentTextShrinkRequest.hpp>
#include <alibabacloud/models/ExtractDocumentTextResponseBody.hpp>
#include <alibabacloud/models/ExtractDocumentTextResponse.hpp>
#include <alibabacloud/models/FuzzyQueryRequest.hpp>
#include <alibabacloud/models/FuzzyQueryShrinkRequest.hpp>
#include <alibabacloud/models/FuzzyQueryResponseBody.hpp>
#include <alibabacloud/models/FuzzyQueryResponse.hpp>
#include <alibabacloud/models/GenerateVideoPlaylistRequest.hpp>
#include <alibabacloud/models/GenerateVideoPlaylistShrinkRequest.hpp>
#include <alibabacloud/models/GenerateVideoPlaylistResponseBody.hpp>
#include <alibabacloud/models/GenerateVideoPlaylistResponse.hpp>
#include <alibabacloud/models/GenerateWebofficeTokenRequest.hpp>
#include <alibabacloud/models/GenerateWebofficeTokenShrinkRequest.hpp>
#include <alibabacloud/models/GenerateWebofficeTokenResponseBody.hpp>
#include <alibabacloud/models/GenerateWebofficeTokenResponse.hpp>
#include <alibabacloud/models/GetBatchRequest.hpp>
#include <alibabacloud/models/GetBatchResponseBody.hpp>
#include <alibabacloud/models/GetBatchResponse.hpp>
#include <alibabacloud/models/GetBindingRequest.hpp>
#include <alibabacloud/models/GetBindingResponseBody.hpp>
#include <alibabacloud/models/GetBindingResponse.hpp>
#include <alibabacloud/models/GetDRMLicenseRequest.hpp>
#include <alibabacloud/models/GetDRMLicenseResponseBody.hpp>
#include <alibabacloud/models/GetDRMLicenseResponse.hpp>
#include <alibabacloud/models/GetDatasetRequest.hpp>
#include <alibabacloud/models/GetDatasetResponseBody.hpp>
#include <alibabacloud/models/GetDatasetResponse.hpp>
#include <alibabacloud/models/GetDecodeBlindWatermarkResultRequest.hpp>
#include <alibabacloud/models/GetDecodeBlindWatermarkResultResponseBody.hpp>
#include <alibabacloud/models/GetDecodeBlindWatermarkResultResponse.hpp>
#include <alibabacloud/models/GetFigureClusterRequest.hpp>
#include <alibabacloud/models/GetFigureClusterResponseBody.hpp>
#include <alibabacloud/models/GetFigureClusterResponse.hpp>
#include <alibabacloud/models/GetFileMetaRequest.hpp>
#include <alibabacloud/models/GetFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/GetFileMetaResponseBody.hpp>
#include <alibabacloud/models/GetFileMetaResponse.hpp>
#include <alibabacloud/models/GetImageModerationResultRequest.hpp>
#include <alibabacloud/models/GetImageModerationResultResponseBody.hpp>
#include <alibabacloud/models/GetImageModerationResultResponse.hpp>
#include <alibabacloud/models/GetOSSBucketAttachmentRequest.hpp>
#include <alibabacloud/models/GetOSSBucketAttachmentResponseBody.hpp>
#include <alibabacloud/models/GetOSSBucketAttachmentResponse.hpp>
#include <alibabacloud/models/GetProjectRequest.hpp>
#include <alibabacloud/models/GetProjectResponseBody.hpp>
#include <alibabacloud/models/GetProjectResponse.hpp>
#include <alibabacloud/models/GetStoryRequest.hpp>
#include <alibabacloud/models/GetStoryResponseBody.hpp>
#include <alibabacloud/models/GetStoryResponse.hpp>
#include <alibabacloud/models/GetTaskRequest.hpp>
#include <alibabacloud/models/GetTaskResponseBody.hpp>
#include <alibabacloud/models/GetTaskResponse.hpp>
#include <alibabacloud/models/GetTriggerRequest.hpp>
#include <alibabacloud/models/GetTriggerResponseBody.hpp>
#include <alibabacloud/models/GetTriggerResponse.hpp>
#include <alibabacloud/models/GetVideoLabelClassificationResultRequest.hpp>
#include <alibabacloud/models/GetVideoLabelClassificationResultResponseBody.hpp>
#include <alibabacloud/models/GetVideoLabelClassificationResultResponse.hpp>
#include <alibabacloud/models/GetVideoModerationResultRequest.hpp>
#include <alibabacloud/models/GetVideoModerationResultResponseBody.hpp>
#include <alibabacloud/models/GetVideoModerationResultResponse.hpp>
#include <alibabacloud/models/IndexFileMetaRequest.hpp>
#include <alibabacloud/models/IndexFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/IndexFileMetaResponseBody.hpp>
#include <alibabacloud/models/IndexFileMetaResponse.hpp>
#include <alibabacloud/models/ListAttachedOSSBucketsRequest.hpp>
#include <alibabacloud/models/ListAttachedOSSBucketsResponseBody.hpp>
#include <alibabacloud/models/ListAttachedOSSBucketsResponse.hpp>
#include <alibabacloud/models/ListBatchesRequest.hpp>
#include <alibabacloud/models/ListBatchesResponseBody.hpp>
#include <alibabacloud/models/ListBatchesResponse.hpp>
#include <alibabacloud/models/ListBindingsRequest.hpp>
#include <alibabacloud/models/ListBindingsResponseBody.hpp>
#include <alibabacloud/models/ListBindingsResponse.hpp>
#include <alibabacloud/models/ListDatasetsRequest.hpp>
#include <alibabacloud/models/ListDatasetsResponseBody.hpp>
#include <alibabacloud/models/ListDatasetsResponse.hpp>
#include <alibabacloud/models/ListProjectsRequest.hpp>
#include <alibabacloud/models/ListProjectsShrinkRequest.hpp>
#include <alibabacloud/models/ListProjectsResponseBody.hpp>
#include <alibabacloud/models/ListProjectsResponse.hpp>
#include <alibabacloud/models/ListRegionsRequest.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/ListTasksRequest.hpp>
#include <alibabacloud/models/ListTasksShrinkRequest.hpp>
#include <alibabacloud/models/ListTasksResponseBody.hpp>
#include <alibabacloud/models/ListTasksResponse.hpp>
#include <alibabacloud/models/ListTriggersRequest.hpp>
#include <alibabacloud/models/ListTriggersResponseBody.hpp>
#include <alibabacloud/models/ListTriggersResponse.hpp>
#include <alibabacloud/models/QueryFigureClustersRequest.hpp>
#include <alibabacloud/models/QueryFigureClustersShrinkRequest.hpp>
#include <alibabacloud/models/QueryFigureClustersResponseBody.hpp>
#include <alibabacloud/models/QueryFigureClustersResponse.hpp>
#include <alibabacloud/models/QueryLocationDateClustersRequest.hpp>
#include <alibabacloud/models/QueryLocationDateClustersShrinkRequest.hpp>
#include <alibabacloud/models/QueryLocationDateClustersResponseBody.hpp>
#include <alibabacloud/models/QueryLocationDateClustersResponse.hpp>
#include <alibabacloud/models/QuerySimilarImageClustersRequest.hpp>
#include <alibabacloud/models/QuerySimilarImageClustersResponseBody.hpp>
#include <alibabacloud/models/QuerySimilarImageClustersResponse.hpp>
#include <alibabacloud/models/QueryStoriesRequest.hpp>
#include <alibabacloud/models/QueryStoriesShrinkRequest.hpp>
#include <alibabacloud/models/QueryStoriesResponseBody.hpp>
#include <alibabacloud/models/QueryStoriesResponse.hpp>
#include <alibabacloud/models/RefreshWebofficeTokenRequest.hpp>
#include <alibabacloud/models/RefreshWebofficeTokenShrinkRequest.hpp>
#include <alibabacloud/models/RefreshWebofficeTokenResponseBody.hpp>
#include <alibabacloud/models/RefreshWebofficeTokenResponse.hpp>
#include <alibabacloud/models/RemoveStoryFilesRequest.hpp>
#include <alibabacloud/models/RemoveStoryFilesShrinkRequest.hpp>
#include <alibabacloud/models/RemoveStoryFilesResponseBody.hpp>
#include <alibabacloud/models/RemoveStoryFilesResponse.hpp>
#include <alibabacloud/models/ResumeBatchRequest.hpp>
#include <alibabacloud/models/ResumeBatchResponseBody.hpp>
#include <alibabacloud/models/ResumeBatchResponse.hpp>
#include <alibabacloud/models/ResumeTriggerRequest.hpp>
#include <alibabacloud/models/ResumeTriggerResponseBody.hpp>
#include <alibabacloud/models/ResumeTriggerResponse.hpp>
#include <alibabacloud/models/SearchImageFigureClusterRequest.hpp>
#include <alibabacloud/models/SearchImageFigureClusterShrinkRequest.hpp>
#include <alibabacloud/models/SearchImageFigureClusterResponseBody.hpp>
#include <alibabacloud/models/SearchImageFigureClusterResponse.hpp>
#include <alibabacloud/models/SemanticQueryRequest.hpp>
#include <alibabacloud/models/SemanticQueryShrinkRequest.hpp>
#include <alibabacloud/models/SemanticQueryResponseBody.hpp>
#include <alibabacloud/models/SemanticQueryResponse.hpp>
#include <alibabacloud/models/SimpleQueryRequest.hpp>
#include <alibabacloud/models/SimpleQueryShrinkRequest.hpp>
#include <alibabacloud/models/SimpleQueryResponseBody.hpp>
#include <alibabacloud/models/SimpleQueryResponse.hpp>
#include <alibabacloud/models/SuspendBatchRequest.hpp>
#include <alibabacloud/models/SuspendBatchResponseBody.hpp>
#include <alibabacloud/models/SuspendBatchResponse.hpp>
#include <alibabacloud/models/SuspendTriggerRequest.hpp>
#include <alibabacloud/models/SuspendTriggerResponseBody.hpp>
#include <alibabacloud/models/SuspendTriggerResponse.hpp>
#include <alibabacloud/models/UpdateBatchRequest.hpp>
#include <alibabacloud/models/UpdateBatchShrinkRequest.hpp>
#include <alibabacloud/models/UpdateBatchResponseBody.hpp>
#include <alibabacloud/models/UpdateBatchResponse.hpp>
#include <alibabacloud/models/UpdateDatasetRequest.hpp>
#include <alibabacloud/models/UpdateDatasetShrinkRequest.hpp>
#include <alibabacloud/models/UpdateDatasetResponseBody.hpp>
#include <alibabacloud/models/UpdateDatasetResponse.hpp>
#include <alibabacloud/models/UpdateFigureClusterRequest.hpp>
#include <alibabacloud/models/UpdateFigureClusterShrinkRequest.hpp>
#include <alibabacloud/models/UpdateFigureClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateFigureClusterResponse.hpp>
#include <alibabacloud/models/UpdateFileMetaRequest.hpp>
#include <alibabacloud/models/UpdateFileMetaShrinkRequest.hpp>
#include <alibabacloud/models/UpdateFileMetaResponseBody.hpp>
#include <alibabacloud/models/UpdateFileMetaResponse.hpp>
#include <alibabacloud/models/UpdateLocationDateClusterRequest.hpp>
#include <alibabacloud/models/UpdateLocationDateClusterShrinkRequest.hpp>
#include <alibabacloud/models/UpdateLocationDateClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateLocationDateClusterResponse.hpp>
#include <alibabacloud/models/UpdateProjectRequest.hpp>
#include <alibabacloud/models/UpdateProjectShrinkRequest.hpp>
#include <alibabacloud/models/UpdateProjectResponseBody.hpp>
#include <alibabacloud/models/UpdateProjectResponse.hpp>
#include <alibabacloud/models/UpdateStoryRequest.hpp>
#include <alibabacloud/models/UpdateStoryShrinkRequest.hpp>
#include <alibabacloud/models/UpdateStoryResponseBody.hpp>
#include <alibabacloud/models/UpdateStoryResponse.hpp>
#include <alibabacloud/models/UpdateTriggerRequest.hpp>
#include <alibabacloud/models/UpdateTriggerShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTriggerResponseBody.hpp>
#include <alibabacloud/models/UpdateTriggerResponse.hpp>

#endif
