// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_IMS20190815MODEL_HPP_
#define ALIBABACLOUD_IMS20190815MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddClientIdToOIDCProviderRequest.hpp>
#include <alibabacloud/models/AddClientIdToOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/AddClientIdToOIDCProviderResponse.hpp>
#include <alibabacloud/models/AddFingerprintToOIDCProviderRequest.hpp>
#include <alibabacloud/models/AddFingerprintToOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/AddFingerprintToOIDCProviderResponse.hpp>
#include <alibabacloud/models/AddUserToGroupRequest.hpp>
#include <alibabacloud/models/AddUserToGroupResponseBody.hpp>
#include <alibabacloud/models/AddUserToGroupResponse.hpp>
#include <alibabacloud/models/BindMFADeviceRequest.hpp>
#include <alibabacloud/models/BindMFADeviceResponseBody.hpp>
#include <alibabacloud/models/BindMFADeviceResponse.hpp>
#include <alibabacloud/models/ChangePasswordRequest.hpp>
#include <alibabacloud/models/ChangePasswordResponseBody.hpp>
#include <alibabacloud/models/ChangePasswordResponse.hpp>
#include <alibabacloud/models/CreateAccessKeyRequest.hpp>
#include <alibabacloud/models/CreateAccessKeyResponseBody.hpp>
#include <alibabacloud/models/CreateAccessKeyResponse.hpp>
#include <alibabacloud/models/CreateAppSecretRequest.hpp>
#include <alibabacloud/models/CreateAppSecretResponseBody.hpp>
#include <alibabacloud/models/CreateAppSecretResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateGroupRequest.hpp>
#include <alibabacloud/models/CreateGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGroupResponse.hpp>
#include <alibabacloud/models/CreateLoginProfileRequest.hpp>
#include <alibabacloud/models/CreateLoginProfileResponseBody.hpp>
#include <alibabacloud/models/CreateLoginProfileResponse.hpp>
#include <alibabacloud/models/CreateOIDCProviderRequest.hpp>
#include <alibabacloud/models/CreateOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/CreateOIDCProviderResponse.hpp>
#include <alibabacloud/models/CreateSAMLProviderRequest.hpp>
#include <alibabacloud/models/CreateSAMLProviderResponseBody.hpp>
#include <alibabacloud/models/CreateSAMLProviderResponse.hpp>
#include <alibabacloud/models/CreateUserRequest.hpp>
#include <alibabacloud/models/CreateUserResponseBody.hpp>
#include <alibabacloud/models/CreateUserResponse.hpp>
#include <alibabacloud/models/CreateVirtualMFADeviceRequest.hpp>
#include <alibabacloud/models/CreateVirtualMFADeviceResponseBody.hpp>
#include <alibabacloud/models/CreateVirtualMFADeviceResponse.hpp>
#include <alibabacloud/models/DeleteAccessKeyRequest.hpp>
#include <alibabacloud/models/DeleteAccessKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessKeyResponse.hpp>
#include <alibabacloud/models/DeleteAccessKeyInRecycleBinRequest.hpp>
#include <alibabacloud/models/DeleteAccessKeyInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessKeyInRecycleBinResponse.hpp>
#include <alibabacloud/models/DeleteAppSecretRequest.hpp>
#include <alibabacloud/models/DeleteAppSecretResponseBody.hpp>
#include <alibabacloud/models/DeleteAppSecretResponse.hpp>
#include <alibabacloud/models/DeleteApplicationRequest.hpp>
#include <alibabacloud/models/DeleteApplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationResponse.hpp>
#include <alibabacloud/models/DeleteGroupRequest.hpp>
#include <alibabacloud/models/DeleteGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGroupResponse.hpp>
#include <alibabacloud/models/DeleteLoginProfileRequest.hpp>
#include <alibabacloud/models/DeleteLoginProfileResponseBody.hpp>
#include <alibabacloud/models/DeleteLoginProfileResponse.hpp>
#include <alibabacloud/models/DeleteOIDCProviderRequest.hpp>
#include <alibabacloud/models/DeleteOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/DeleteOIDCProviderResponse.hpp>
#include <alibabacloud/models/DeletePasskeyRequest.hpp>
#include <alibabacloud/models/DeletePasskeyResponseBody.hpp>
#include <alibabacloud/models/DeletePasskeyResponse.hpp>
#include <alibabacloud/models/DeleteSAMLProviderRequest.hpp>
#include <alibabacloud/models/DeleteSAMLProviderResponseBody.hpp>
#include <alibabacloud/models/DeleteSAMLProviderResponse.hpp>
#include <alibabacloud/models/DeleteUserRequest.hpp>
#include <alibabacloud/models/DeleteUserResponseBody.hpp>
#include <alibabacloud/models/DeleteUserResponse.hpp>
#include <alibabacloud/models/DeleteUserInRecycleBinRequest.hpp>
#include <alibabacloud/models/DeleteUserInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/DeleteUserInRecycleBinResponse.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceRequest.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceResponseBody.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceResponse.hpp>
#include <alibabacloud/models/DeprovisionApplicationRequest.hpp>
#include <alibabacloud/models/DeprovisionApplicationResponseBody.hpp>
#include <alibabacloud/models/DeprovisionApplicationResponse.hpp>
#include <alibabacloud/models/DeprovisionExternalApplicationRequest.hpp>
#include <alibabacloud/models/DeprovisionExternalApplicationResponseBody.hpp>
#include <alibabacloud/models/DeprovisionExternalApplicationResponse.hpp>
#include <alibabacloud/models/DisableVirtualMFARequest.hpp>
#include <alibabacloud/models/DisableVirtualMFAResponseBody.hpp>
#include <alibabacloud/models/DisableVirtualMFAResponse.hpp>
#include <alibabacloud/models/GenerateCredentialReportResponseBody.hpp>
#include <alibabacloud/models/GenerateCredentialReportResponse.hpp>
#include <alibabacloud/models/GenerateGovernanceReportResponseBody.hpp>
#include <alibabacloud/models/GenerateGovernanceReportResponse.hpp>
#include <alibabacloud/models/GetAccessKeyInfoInRecycleBinRequest.hpp>
#include <alibabacloud/models/GetAccessKeyInfoInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/GetAccessKeyInfoInRecycleBinResponse.hpp>
#include <alibabacloud/models/GetAccessKeyLastUsedRequest.hpp>
#include <alibabacloud/models/GetAccessKeyLastUsedResponseBody.hpp>
#include <alibabacloud/models/GetAccessKeyLastUsedResponse.hpp>
#include <alibabacloud/models/GetAccountMFAInfoResponseBody.hpp>
#include <alibabacloud/models/GetAccountMFAInfoResponse.hpp>
#include <alibabacloud/models/GetAccountSecurityPracticeReportResponseBody.hpp>
#include <alibabacloud/models/GetAccountSecurityPracticeReportResponse.hpp>
#include <alibabacloud/models/GetAccountSummaryResponseBody.hpp>
#include <alibabacloud/models/GetAccountSummaryResponse.hpp>
#include <alibabacloud/models/GetAppSecretRequest.hpp>
#include <alibabacloud/models/GetAppSecretResponseBody.hpp>
#include <alibabacloud/models/GetAppSecretResponse.hpp>
#include <alibabacloud/models/GetApplicationRequest.hpp>
#include <alibabacloud/models/GetApplicationResponseBody.hpp>
#include <alibabacloud/models/GetApplicationResponse.hpp>
#include <alibabacloud/models/GetApplicationProvisionInfoRequest.hpp>
#include <alibabacloud/models/GetApplicationProvisionInfoResponseBody.hpp>
#include <alibabacloud/models/GetApplicationProvisionInfoResponse.hpp>
#include <alibabacloud/models/GetCredentialReportRequest.hpp>
#include <alibabacloud/models/GetCredentialReportResponseBody.hpp>
#include <alibabacloud/models/GetCredentialReportResponse.hpp>
#include <alibabacloud/models/GetDefaultDomainResponseBody.hpp>
#include <alibabacloud/models/GetDefaultDomainResponse.hpp>
#include <alibabacloud/models/GetExternalApplicationRequest.hpp>
#include <alibabacloud/models/GetExternalApplicationResponseBody.hpp>
#include <alibabacloud/models/GetExternalApplicationResponse.hpp>
#include <alibabacloud/models/GetGovernanceItemReportRequest.hpp>
#include <alibabacloud/models/GetGovernanceItemReportResponseBody.hpp>
#include <alibabacloud/models/GetGovernanceItemReportResponse.hpp>
#include <alibabacloud/models/GetGovernanceReportStatusResponseBody.hpp>
#include <alibabacloud/models/GetGovernanceReportStatusResponse.hpp>
#include <alibabacloud/models/GetGroupRequest.hpp>
#include <alibabacloud/models/GetGroupResponseBody.hpp>
#include <alibabacloud/models/GetGroupResponse.hpp>
#include <alibabacloud/models/GetLoginProfileRequest.hpp>
#include <alibabacloud/models/GetLoginProfileResponseBody.hpp>
#include <alibabacloud/models/GetLoginProfileResponse.hpp>
#include <alibabacloud/models/GetOIDCProviderRequest.hpp>
#include <alibabacloud/models/GetOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/GetOIDCProviderResponse.hpp>
#include <alibabacloud/models/GetPasswordPolicyResponseBody.hpp>
#include <alibabacloud/models/GetPasswordPolicyResponse.hpp>
#include <alibabacloud/models/GetSAMLProviderRequest.hpp>
#include <alibabacloud/models/GetSAMLProviderResponseBody.hpp>
#include <alibabacloud/models/GetSAMLProviderResponse.hpp>
#include <alibabacloud/models/GetSecurityPreferenceResponseBody.hpp>
#include <alibabacloud/models/GetSecurityPreferenceResponse.hpp>
#include <alibabacloud/models/GetUserRequest.hpp>
#include <alibabacloud/models/GetUserResponseBody.hpp>
#include <alibabacloud/models/GetUserResponse.hpp>
#include <alibabacloud/models/GetUserInRecycleBinRequest.hpp>
#include <alibabacloud/models/GetUserInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/GetUserInRecycleBinResponse.hpp>
#include <alibabacloud/models/GetUserMFAInfoRequest.hpp>
#include <alibabacloud/models/GetUserMFAInfoResponseBody.hpp>
#include <alibabacloud/models/GetUserMFAInfoResponse.hpp>
#include <alibabacloud/models/GetUserSsoSettingsResponseBody.hpp>
#include <alibabacloud/models/GetUserSsoSettingsResponse.hpp>
#include <alibabacloud/models/GetVerificationInfoRequest.hpp>
#include <alibabacloud/models/GetVerificationInfoResponseBody.hpp>
#include <alibabacloud/models/GetVerificationInfoResponse.hpp>
#include <alibabacloud/models/ListAccessKeysRequest.hpp>
#include <alibabacloud/models/ListAccessKeysResponseBody.hpp>
#include <alibabacloud/models/ListAccessKeysResponse.hpp>
#include <alibabacloud/models/ListAccessKeysInRecycleBinRequest.hpp>
#include <alibabacloud/models/ListAccessKeysInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/ListAccessKeysInRecycleBinResponse.hpp>
#include <alibabacloud/models/ListAppSecretIdsRequest.hpp>
#include <alibabacloud/models/ListAppSecretIdsResponseBody.hpp>
#include <alibabacloud/models/ListAppSecretIdsResponse.hpp>
#include <alibabacloud/models/ListApplicationProvisionInfosRequest.hpp>
#include <alibabacloud/models/ListApplicationProvisionInfosResponseBody.hpp>
#include <alibabacloud/models/ListApplicationProvisionInfosResponse.hpp>
#include <alibabacloud/models/ListApplicationsResponseBody.hpp>
#include <alibabacloud/models/ListApplicationsResponse.hpp>
#include <alibabacloud/models/ListExternalApplicationsResponseBody.hpp>
#include <alibabacloud/models/ListExternalApplicationsResponse.hpp>
#include <alibabacloud/models/ListGroupsRequest.hpp>
#include <alibabacloud/models/ListGroupsResponseBody.hpp>
#include <alibabacloud/models/ListGroupsResponse.hpp>
#include <alibabacloud/models/ListGroupsForUserRequest.hpp>
#include <alibabacloud/models/ListGroupsForUserResponseBody.hpp>
#include <alibabacloud/models/ListGroupsForUserResponse.hpp>
#include <alibabacloud/models/ListOIDCProvidersRequest.hpp>
#include <alibabacloud/models/ListOIDCProvidersResponseBody.hpp>
#include <alibabacloud/models/ListOIDCProvidersResponse.hpp>
#include <alibabacloud/models/ListPasskeysRequest.hpp>
#include <alibabacloud/models/ListPasskeysResponseBody.hpp>
#include <alibabacloud/models/ListPasskeysResponse.hpp>
#include <alibabacloud/models/ListPredefinedScopesRequest.hpp>
#include <alibabacloud/models/ListPredefinedScopesResponseBody.hpp>
#include <alibabacloud/models/ListPredefinedScopesResponse.hpp>
#include <alibabacloud/models/ListRecentGovernanceMetricsResponseBody.hpp>
#include <alibabacloud/models/ListRecentGovernanceMetricsResponse.hpp>
#include <alibabacloud/models/ListSAMLProvidersRequest.hpp>
#include <alibabacloud/models/ListSAMLProvidersResponseBody.hpp>
#include <alibabacloud/models/ListSAMLProvidersResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListUserBasicInfosRequest.hpp>
#include <alibabacloud/models/ListUserBasicInfosResponseBody.hpp>
#include <alibabacloud/models/ListUserBasicInfosResponse.hpp>
#include <alibabacloud/models/ListUsersRequest.hpp>
#include <alibabacloud/models/ListUsersResponseBody.hpp>
#include <alibabacloud/models/ListUsersResponse.hpp>
#include <alibabacloud/models/ListUsersForGroupRequest.hpp>
#include <alibabacloud/models/ListUsersForGroupResponseBody.hpp>
#include <alibabacloud/models/ListUsersForGroupResponse.hpp>
#include <alibabacloud/models/ListUsersInRecycleBinRequest.hpp>
#include <alibabacloud/models/ListUsersInRecycleBinResponseBody.hpp>
#include <alibabacloud/models/ListUsersInRecycleBinResponse.hpp>
#include <alibabacloud/models/ListVirtualMFADevicesRequest.hpp>
#include <alibabacloud/models/ListVirtualMFADevicesResponseBody.hpp>
#include <alibabacloud/models/ListVirtualMFADevicesResponse.hpp>
#include <alibabacloud/models/ProvisionApplicationRequest.hpp>
#include <alibabacloud/models/ProvisionApplicationResponseBody.hpp>
#include <alibabacloud/models/ProvisionApplicationResponse.hpp>
#include <alibabacloud/models/ProvisionExternalApplicationRequest.hpp>
#include <alibabacloud/models/ProvisionExternalApplicationResponseBody.hpp>
#include <alibabacloud/models/ProvisionExternalApplicationResponse.hpp>
#include <alibabacloud/models/RemoveClientIdFromOIDCProviderRequest.hpp>
#include <alibabacloud/models/RemoveClientIdFromOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/RemoveClientIdFromOIDCProviderResponse.hpp>
#include <alibabacloud/models/RemoveFingerprintFromOIDCProviderRequest.hpp>
#include <alibabacloud/models/RemoveFingerprintFromOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/RemoveFingerprintFromOIDCProviderResponse.hpp>
#include <alibabacloud/models/RemoveUserFromGroupRequest.hpp>
#include <alibabacloud/models/RemoveUserFromGroupResponseBody.hpp>
#include <alibabacloud/models/RemoveUserFromGroupResponse.hpp>
#include <alibabacloud/models/RestoreAccessKeyFromRecycleBinRequest.hpp>
#include <alibabacloud/models/RestoreAccessKeyFromRecycleBinResponseBody.hpp>
#include <alibabacloud/models/RestoreAccessKeyFromRecycleBinResponse.hpp>
#include <alibabacloud/models/RestoreUserFromRecycleBinRequest.hpp>
#include <alibabacloud/models/RestoreUserFromRecycleBinResponseBody.hpp>
#include <alibabacloud/models/RestoreUserFromRecycleBinResponse.hpp>
#include <alibabacloud/models/SetDefaultDomainRequest.hpp>
#include <alibabacloud/models/SetDefaultDomainResponseBody.hpp>
#include <alibabacloud/models/SetDefaultDomainResponse.hpp>
#include <alibabacloud/models/SetPasswordPolicyRequest.hpp>
#include <alibabacloud/models/SetPasswordPolicyResponseBody.hpp>
#include <alibabacloud/models/SetPasswordPolicyResponse.hpp>
#include <alibabacloud/models/SetSecurityPreferenceRequest.hpp>
#include <alibabacloud/models/SetSecurityPreferenceShrinkRequest.hpp>
#include <alibabacloud/models/SetSecurityPreferenceResponseBody.hpp>
#include <alibabacloud/models/SetSecurityPreferenceResponse.hpp>
#include <alibabacloud/models/SetUserSsoSettingsRequest.hpp>
#include <alibabacloud/models/SetUserSsoSettingsResponseBody.hpp>
#include <alibabacloud/models/SetUserSsoSettingsResponse.hpp>
#include <alibabacloud/models/SetVerificationInfoRequest.hpp>
#include <alibabacloud/models/SetVerificationInfoResponseBody.hpp>
#include <alibabacloud/models/SetVerificationInfoResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnbindMFADeviceRequest.hpp>
#include <alibabacloud/models/UnbindMFADeviceResponseBody.hpp>
#include <alibabacloud/models/UnbindMFADeviceResponse.hpp>
#include <alibabacloud/models/UnbindVerificationRequest.hpp>
#include <alibabacloud/models/UnbindVerificationResponseBody.hpp>
#include <alibabacloud/models/UnbindVerificationResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAccessKeyRequest.hpp>
#include <alibabacloud/models/UpdateAccessKeyResponseBody.hpp>
#include <alibabacloud/models/UpdateAccessKeyResponse.hpp>
#include <alibabacloud/models/UpdateApplicationRequest.hpp>
#include <alibabacloud/models/UpdateApplicationResponseBody.hpp>
#include <alibabacloud/models/UpdateApplicationResponse.hpp>
#include <alibabacloud/models/UpdateGroupRequest.hpp>
#include <alibabacloud/models/UpdateGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateGroupResponse.hpp>
#include <alibabacloud/models/UpdateLoginProfileRequest.hpp>
#include <alibabacloud/models/UpdateLoginProfileResponseBody.hpp>
#include <alibabacloud/models/UpdateLoginProfileResponse.hpp>
#include <alibabacloud/models/UpdateOIDCProviderRequest.hpp>
#include <alibabacloud/models/UpdateOIDCProviderResponseBody.hpp>
#include <alibabacloud/models/UpdateOIDCProviderResponse.hpp>
#include <alibabacloud/models/UpdatePasskeyRequest.hpp>
#include <alibabacloud/models/UpdatePasskeyResponseBody.hpp>
#include <alibabacloud/models/UpdatePasskeyResponse.hpp>
#include <alibabacloud/models/UpdateSAMLProviderRequest.hpp>
#include <alibabacloud/models/UpdateSAMLProviderResponseBody.hpp>
#include <alibabacloud/models/UpdateSAMLProviderResponse.hpp>
#include <alibabacloud/models/UpdateUserRequest.hpp>
#include <alibabacloud/models/UpdateUserResponseBody.hpp>
#include <alibabacloud/models/UpdateUserResponse.hpp>

#endif
