// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_COMPUTENESTSUPPLIER20210521MODEL_HPP_
#define ALIBABACLOUD_COMPUTENESTSUPPLIER20210521MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddServiceSharedAccountsRequest.hpp>
#include <alibabacloud/models/AddServiceSharedAccountsResponseBody.hpp>
#include <alibabacloud/models/AddServiceSharedAccountsResponse.hpp>
#include <alibabacloud/models/ApproveServiceUsageRequest.hpp>
#include <alibabacloud/models/ApproveServiceUsageResponseBody.hpp>
#include <alibabacloud/models/ApproveServiceUsageResponse.hpp>
#include <alibabacloud/models/CancelServiceRegistrationRequest.hpp>
#include <alibabacloud/models/CancelServiceRegistrationResponseBody.hpp>
#include <alibabacloud/models/CancelServiceRegistrationResponse.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceRequest.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/ContinueDeployServiceInstanceResponse.hpp>
#include <alibabacloud/models/CreateArtifactRequest.hpp>
#include <alibabacloud/models/CreateArtifactShrinkRequest.hpp>
#include <alibabacloud/models/CreateArtifactResponseBody.hpp>
#include <alibabacloud/models/CreateArtifactResponse.hpp>
#include <alibabacloud/models/CreateOpsNoticeRequest.hpp>
#include <alibabacloud/models/CreateOpsNoticeShrinkRequest.hpp>
#include <alibabacloud/models/CreateOpsNoticeResponseBody.hpp>
#include <alibabacloud/models/CreateOpsNoticeResponse.hpp>
#include <alibabacloud/models/CreateServiceRequest.hpp>
#include <alibabacloud/models/CreateServiceShrinkRequest.hpp>
#include <alibabacloud/models/CreateServiceResponseBody.hpp>
#include <alibabacloud/models/CreateServiceResponse.hpp>
#include <alibabacloud/models/CreateServiceInstanceRequest.hpp>
#include <alibabacloud/models/CreateServiceInstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateServiceInstanceResponse.hpp>
#include <alibabacloud/models/CreateServiceTestCaseRequest.hpp>
#include <alibabacloud/models/CreateServiceTestCaseResponseBody.hpp>
#include <alibabacloud/models/CreateServiceTestCaseResponse.hpp>
#include <alibabacloud/models/CreateServiceTestTaskRequest.hpp>
#include <alibabacloud/models/CreateServiceTestTaskResponseBody.hpp>
#include <alibabacloud/models/CreateServiceTestTaskResponse.hpp>
#include <alibabacloud/models/CreateServiceUsageRequest.hpp>
#include <alibabacloud/models/CreateServiceUsageResponseBody.hpp>
#include <alibabacloud/models/CreateServiceUsageResponse.hpp>
#include <alibabacloud/models/CreateSupplierRegistrationRequest.hpp>
#include <alibabacloud/models/CreateSupplierRegistrationResponseBody.hpp>
#include <alibabacloud/models/CreateSupplierRegistrationResponse.hpp>
#include <alibabacloud/models/DeleteAcrImageRepositoriesRequest.hpp>
#include <alibabacloud/models/DeleteAcrImageRepositoriesResponseBody.hpp>
#include <alibabacloud/models/DeleteAcrImageRepositoriesResponse.hpp>
#include <alibabacloud/models/DeleteAcrImageTagsRequest.hpp>
#include <alibabacloud/models/DeleteAcrImageTagsResponseBody.hpp>
#include <alibabacloud/models/DeleteAcrImageTagsResponse.hpp>
#include <alibabacloud/models/DeleteArtifactRequest.hpp>
#include <alibabacloud/models/DeleteArtifactResponseBody.hpp>
#include <alibabacloud/models/DeleteArtifactResponse.hpp>
#include <alibabacloud/models/DeleteServiceRequest.hpp>
#include <alibabacloud/models/DeleteServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceResponse.hpp>
#include <alibabacloud/models/DeleteServiceInstancesRequest.hpp>
#include <alibabacloud/models/DeleteServiceInstancesResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceInstancesResponse.hpp>
#include <alibabacloud/models/DeleteServiceTestCaseRequest.hpp>
#include <alibabacloud/models/DeleteServiceTestCaseResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceTestCaseResponse.hpp>
#include <alibabacloud/models/DeployServiceInstanceRequest.hpp>
#include <alibabacloud/models/DeployServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/DeployServiceInstanceResponse.hpp>
#include <alibabacloud/models/GenerateDefaultServiceTestConfigRequest.hpp>
#include <alibabacloud/models/GenerateDefaultServiceTestConfigResponseBody.hpp>
#include <alibabacloud/models/GenerateDefaultServiceTestConfigResponse.hpp>
#include <alibabacloud/models/GenerateServicePolicyRequest.hpp>
#include <alibabacloud/models/GenerateServicePolicyResponseBody.hpp>
#include <alibabacloud/models/GenerateServicePolicyResponse.hpp>
#include <alibabacloud/models/GetArtifactRequest.hpp>
#include <alibabacloud/models/GetArtifactResponseBody.hpp>
#include <alibabacloud/models/GetArtifactResponse.hpp>
#include <alibabacloud/models/GetArtifactRepositoryCredentialsRequest.hpp>
#include <alibabacloud/models/GetArtifactRepositoryCredentialsResponseBody.hpp>
#include <alibabacloud/models/GetArtifactRepositoryCredentialsResponse.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesRequest.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesResponseBody.hpp>
#include <alibabacloud/models/GetNetworkAvailableZonesResponse.hpp>
#include <alibabacloud/models/GetOpsNoticeRequest.hpp>
#include <alibabacloud/models/GetOpsNoticeResponseBody.hpp>
#include <alibabacloud/models/GetOpsNoticeResponse.hpp>
#include <alibabacloud/models/GetServiceRequest.hpp>
#include <alibabacloud/models/GetServiceResponseBody.hpp>
#include <alibabacloud/models/GetServiceResponse.hpp>
#include <alibabacloud/models/GetServiceEstimateCostRequest.hpp>
#include <alibabacloud/models/GetServiceEstimateCostShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceEstimateCostResponseBody.hpp>
#include <alibabacloud/models/GetServiceEstimateCostResponse.hpp>
#include <alibabacloud/models/GetServiceInstanceRequest.hpp>
#include <alibabacloud/models/GetServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/GetServiceInstanceResponse.hpp>
#include <alibabacloud/models/GetServiceProvisionsRequest.hpp>
#include <alibabacloud/models/GetServiceProvisionsShrinkRequest.hpp>
#include <alibabacloud/models/GetServiceProvisionsResponseBody.hpp>
#include <alibabacloud/models/GetServiceProvisionsResponse.hpp>
#include <alibabacloud/models/GetServiceRegistrationRequest.hpp>
#include <alibabacloud/models/GetServiceRegistrationResponseBody.hpp>
#include <alibabacloud/models/GetServiceRegistrationResponse.hpp>
#include <alibabacloud/models/GetServiceTemplateCriterionIssuesRequest.hpp>
#include <alibabacloud/models/GetServiceTemplateCriterionIssuesResponseBody.hpp>
#include <alibabacloud/models/GetServiceTemplateCriterionIssuesResponse.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsRequest.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsResponseBody.hpp>
#include <alibabacloud/models/GetServiceTemplateParameterConstraintsResponse.hpp>
#include <alibabacloud/models/GetServiceTestTaskRequest.hpp>
#include <alibabacloud/models/GetServiceTestTaskResponseBody.hpp>
#include <alibabacloud/models/GetServiceTestTaskResponse.hpp>
#include <alibabacloud/models/GetSupplierInformationRequest.hpp>
#include <alibabacloud/models/GetSupplierInformationResponseBody.hpp>
#include <alibabacloud/models/GetSupplierInformationResponse.hpp>
#include <alibabacloud/models/GetUploadCredentialsRequest.hpp>
#include <alibabacloud/models/GetUploadCredentialsResponseBody.hpp>
#include <alibabacloud/models/GetUploadCredentialsResponse.hpp>
#include <alibabacloud/models/LaunchServiceRequest.hpp>
#include <alibabacloud/models/LaunchServiceResponseBody.hpp>
#include <alibabacloud/models/LaunchServiceResponse.hpp>
#include <alibabacloud/models/ListAcrImageRepositoriesRequest.hpp>
#include <alibabacloud/models/ListAcrImageRepositoriesResponseBody.hpp>
#include <alibabacloud/models/ListAcrImageRepositoriesResponse.hpp>
#include <alibabacloud/models/ListAcrImageTagsRequest.hpp>
#include <alibabacloud/models/ListAcrImageTagsResponseBody.hpp>
#include <alibabacloud/models/ListAcrImageTagsResponse.hpp>
#include <alibabacloud/models/ListArtifactBuildLogsRequest.hpp>
#include <alibabacloud/models/ListArtifactBuildLogsResponseBody.hpp>
#include <alibabacloud/models/ListArtifactBuildLogsResponse.hpp>
#include <alibabacloud/models/ListArtifactRisksRequest.hpp>
#include <alibabacloud/models/ListArtifactRisksResponseBody.hpp>
#include <alibabacloud/models/ListArtifactRisksResponse.hpp>
#include <alibabacloud/models/ListArtifactVersionsRequest.hpp>
#include <alibabacloud/models/ListArtifactVersionsShrinkRequest.hpp>
#include <alibabacloud/models/ListArtifactVersionsResponseBody.hpp>
#include <alibabacloud/models/ListArtifactVersionsResponse.hpp>
#include <alibabacloud/models/ListArtifactsRequest.hpp>
#include <alibabacloud/models/ListArtifactsResponseBody.hpp>
#include <alibabacloud/models/ListArtifactsResponse.hpp>
#include <alibabacloud/models/ListOpsNoticesRequest.hpp>
#include <alibabacloud/models/ListOpsNoticesResponseBody.hpp>
#include <alibabacloud/models/ListOpsNoticesResponse.hpp>
#include <alibabacloud/models/ListResellersRequest.hpp>
#include <alibabacloud/models/ListResellersResponseBody.hpp>
#include <alibabacloud/models/ListResellersResponse.hpp>
#include <alibabacloud/models/ListServiceBuildLogsRequest.hpp>
#include <alibabacloud/models/ListServiceBuildLogsResponseBody.hpp>
#include <alibabacloud/models/ListServiceBuildLogsResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceBillRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceBillResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceBillResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceDeployDetailsRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceDeployDetailsResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceDeployDetailsResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceLogsResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceResourcesResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceUpgradeHistoryResponse.hpp>
#include <alibabacloud/models/ListServiceInstancesRequest.hpp>
#include <alibabacloud/models/ListServiceInstancesResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstancesResponse.hpp>
#include <alibabacloud/models/ListServiceRegistrationsRequest.hpp>
#include <alibabacloud/models/ListServiceRegistrationsResponseBody.hpp>
#include <alibabacloud/models/ListServiceRegistrationsResponse.hpp>
#include <alibabacloud/models/ListServiceSharedAccountsRequest.hpp>
#include <alibabacloud/models/ListServiceSharedAccountsResponseBody.hpp>
#include <alibabacloud/models/ListServiceSharedAccountsResponse.hpp>
#include <alibabacloud/models/ListServiceTestCasesRequest.hpp>
#include <alibabacloud/models/ListServiceTestCasesResponseBody.hpp>
#include <alibabacloud/models/ListServiceTestCasesResponse.hpp>
#include <alibabacloud/models/ListServiceTestTaskLogsRequest.hpp>
#include <alibabacloud/models/ListServiceTestTaskLogsResponseBody.hpp>
#include <alibabacloud/models/ListServiceTestTaskLogsResponse.hpp>
#include <alibabacloud/models/ListServiceTestTasksRequest.hpp>
#include <alibabacloud/models/ListServiceTestTasksResponseBody.hpp>
#include <alibabacloud/models/ListServiceTestTasksResponse.hpp>
#include <alibabacloud/models/ListServiceUsagesRequest.hpp>
#include <alibabacloud/models/ListServiceUsagesResponseBody.hpp>
#include <alibabacloud/models/ListServiceUsagesResponse.hpp>
#include <alibabacloud/models/ListServicesRequest.hpp>
#include <alibabacloud/models/ListServicesResponseBody.hpp>
#include <alibabacloud/models/ListServicesResponse.hpp>
#include <alibabacloud/models/ListSupplierRegistrationsRequest.hpp>
#include <alibabacloud/models/ListSupplierRegistrationsResponseBody.hpp>
#include <alibabacloud/models/ListSupplierRegistrationsResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/ModifyServiceInstanceResourcesRequest.hpp>
#include <alibabacloud/models/ModifyServiceInstanceResourcesResponseBody.hpp>
#include <alibabacloud/models/ModifyServiceInstanceResourcesResponse.hpp>
#include <alibabacloud/models/PreLaunchServiceRequest.hpp>
#include <alibabacloud/models/PreLaunchServiceResponseBody.hpp>
#include <alibabacloud/models/PreLaunchServiceResponse.hpp>
#include <alibabacloud/models/PushMeteringDataRequest.hpp>
#include <alibabacloud/models/PushMeteringDataResponseBody.hpp>
#include <alibabacloud/models/PushMeteringDataResponse.hpp>
#include <alibabacloud/models/RegisterServiceRequest.hpp>
#include <alibabacloud/models/RegisterServiceResponseBody.hpp>
#include <alibabacloud/models/RegisterServiceResponse.hpp>
#include <alibabacloud/models/RejectServiceUsageRequest.hpp>
#include <alibabacloud/models/RejectServiceUsageResponseBody.hpp>
#include <alibabacloud/models/RejectServiceUsageResponse.hpp>
#include <alibabacloud/models/ReleaseArtifactRequest.hpp>
#include <alibabacloud/models/ReleaseArtifactResponseBody.hpp>
#include <alibabacloud/models/ReleaseArtifactResponse.hpp>
#include <alibabacloud/models/RemoveServiceSharedAccountsRequest.hpp>
#include <alibabacloud/models/RemoveServiceSharedAccountsResponseBody.hpp>
#include <alibabacloud/models/RemoveServiceSharedAccountsResponse.hpp>
#include <alibabacloud/models/RestartServiceInstanceRequest.hpp>
#include <alibabacloud/models/RestartServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartServiceInstanceResponse.hpp>
#include <alibabacloud/models/RollbackServiceInstanceRequest.hpp>
#include <alibabacloud/models/RollbackServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/RollbackServiceInstanceResponse.hpp>
#include <alibabacloud/models/StartServiceInstanceRequest.hpp>
#include <alibabacloud/models/StartServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/StartServiceInstanceResponse.hpp>
#include <alibabacloud/models/StopServiceInstanceRequest.hpp>
#include <alibabacloud/models/StopServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/StopServiceInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnTagResourcesRequest.hpp>
#include <alibabacloud/models/UnTagResourcesResponseBody.hpp>
#include <alibabacloud/models/UnTagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateArtifactRequest.hpp>
#include <alibabacloud/models/UpdateArtifactShrinkRequest.hpp>
#include <alibabacloud/models/UpdateArtifactResponseBody.hpp>
#include <alibabacloud/models/UpdateArtifactResponse.hpp>
#include <alibabacloud/models/UpdateServiceRequest.hpp>
#include <alibabacloud/models/UpdateServiceShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceResponse.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributeRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributeShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceInstanceAttributeResponse.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecShrinkRequest.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceInstanceSpecResponse.hpp>
#include <alibabacloud/models/UpdateServiceTestCaseRequest.hpp>
#include <alibabacloud/models/UpdateServiceTestCaseResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceTestCaseResponse.hpp>
#include <alibabacloud/models/UpdateSharedAccountPermissionRequest.hpp>
#include <alibabacloud/models/UpdateSharedAccountPermissionResponseBody.hpp>
#include <alibabacloud/models/UpdateSharedAccountPermissionResponse.hpp>
#include <alibabacloud/models/UpdateSupplierInformationRequest.hpp>
#include <alibabacloud/models/UpdateSupplierInformationResponseBody.hpp>
#include <alibabacloud/models/UpdateSupplierInformationResponse.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceRequest.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceShrinkRequest.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceResponseBody.hpp>
#include <alibabacloud/models/UpgradeServiceInstanceResponse.hpp>
#include <alibabacloud/models/WithdrawServiceRequest.hpp>
#include <alibabacloud/models/WithdrawServiceResponseBody.hpp>
#include <alibabacloud/models/WithdrawServiceResponse.hpp>

#endif
