// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GETPRIVATEACCESSAPPLICATIONRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_GETPRIVATEACCESSAPPLICATIONRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/AddressGroup.hpp>
#include <alibabacloud/models/PAL7Config.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Csas20230120
{
namespace Models
{
  class GetPrivateAccessApplicationResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GetPrivateAccessApplicationResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Application, application_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, GetPrivateAccessApplicationResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Application, application_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    GetPrivateAccessApplicationResponseBody() = default ;
    GetPrivateAccessApplicationResponseBody(const GetPrivateAccessApplicationResponseBody &) = default ;
    GetPrivateAccessApplicationResponseBody(GetPrivateAccessApplicationResponseBody &&) = default ;
    GetPrivateAccessApplicationResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GetPrivateAccessApplicationResponseBody() = default ;
    GetPrivateAccessApplicationResponseBody& operator=(const GetPrivateAccessApplicationResponseBody &) = default ;
    GetPrivateAccessApplicationResponseBody& operator=(GetPrivateAccessApplicationResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    class Application : public Darabonba::Model {
    public:
      friend void to_json(Darabonba::Json& j, const Application& obj) { 
        DARABONBA_PTR_TO_JSON(AddressGroups, addressGroups_);
        DARABONBA_PTR_TO_JSON(Addresses, addresses_);
        DARABONBA_PTR_TO_JSON(ApplicationId, applicationId_);
        DARABONBA_PTR_TO_JSON(AutoGenerated, autoGenerated_);
        DARABONBA_PTR_TO_JSON(BrowserAccessStatus, browserAccessStatus_);
        DARABONBA_PTR_TO_JSON(ConfigMode, configMode_);
        DARABONBA_PTR_TO_JSON(ConnectorIds, connectorIds_);
        DARABONBA_PTR_TO_JSON(CreateTime, createTime_);
        DARABONBA_PTR_TO_JSON(Description, description_);
        DARABONBA_PTR_TO_JSON(L7Config, l7Config_);
        DARABONBA_PTR_TO_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
        DARABONBA_PTR_TO_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
        DARABONBA_PTR_TO_JSON(Name, name_);
        DARABONBA_PTR_TO_JSON(PolicyIds, policyIds_);
        DARABONBA_PTR_TO_JSON(PortRanges, portRanges_);
        DARABONBA_PTR_TO_JSON(Protocol, protocol_);
        DARABONBA_PTR_TO_JSON(Status, status_);
        DARABONBA_PTR_TO_JSON(TagIds, tagIds_);
      };
      friend void from_json(const Darabonba::Json& j, Application& obj) { 
        DARABONBA_PTR_FROM_JSON(AddressGroups, addressGroups_);
        DARABONBA_PTR_FROM_JSON(Addresses, addresses_);
        DARABONBA_PTR_FROM_JSON(ApplicationId, applicationId_);
        DARABONBA_PTR_FROM_JSON(AutoGenerated, autoGenerated_);
        DARABONBA_PTR_FROM_JSON(BrowserAccessStatus, browserAccessStatus_);
        DARABONBA_PTR_FROM_JSON(ConfigMode, configMode_);
        DARABONBA_PTR_FROM_JSON(ConnectorIds, connectorIds_);
        DARABONBA_PTR_FROM_JSON(CreateTime, createTime_);
        DARABONBA_PTR_FROM_JSON(Description, description_);
        DARABONBA_PTR_FROM_JSON(L7Config, l7Config_);
        DARABONBA_PTR_FROM_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
        DARABONBA_PTR_FROM_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
        DARABONBA_PTR_FROM_JSON(Name, name_);
        DARABONBA_PTR_FROM_JSON(PolicyIds, policyIds_);
        DARABONBA_PTR_FROM_JSON(PortRanges, portRanges_);
        DARABONBA_PTR_FROM_JSON(Protocol, protocol_);
        DARABONBA_PTR_FROM_JSON(Status, status_);
        DARABONBA_PTR_FROM_JSON(TagIds, tagIds_);
      };
      Application() = default ;
      Application(const Application &) = default ;
      Application(Application &&) = default ;
      Application(const Darabonba::Json & obj) { from_json(obj, *this); };
      virtual ~Application() = default ;
      Application& operator=(const Application &) = default ;
      Application& operator=(Application &&) = default ;
      virtual void validate() const override {
      };
      virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
      virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
      class PortRanges : public Darabonba::Model {
      public:
        friend void to_json(Darabonba::Json& j, const PortRanges& obj) { 
          DARABONBA_PTR_TO_JSON(Begin, begin_);
          DARABONBA_PTR_TO_JSON(End, end_);
        };
        friend void from_json(const Darabonba::Json& j, PortRanges& obj) { 
          DARABONBA_PTR_FROM_JSON(Begin, begin_);
          DARABONBA_PTR_FROM_JSON(End, end_);
        };
        PortRanges() = default ;
        PortRanges(const PortRanges &) = default ;
        PortRanges(PortRanges &&) = default ;
        PortRanges(const Darabonba::Json & obj) { from_json(obj, *this); };
        virtual ~PortRanges() = default ;
        PortRanges& operator=(const PortRanges &) = default ;
        PortRanges& operator=(PortRanges &&) = default ;
        virtual void validate() const override {
        };
        virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
        virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
        virtual bool empty() const override { return this->begin_ == nullptr
        && this->end_ == nullptr; };
        // begin Field Functions 
        bool hasBegin() const { return this->begin_ != nullptr;};
        void deleteBegin() { this->begin_ = nullptr;};
        inline int32_t getBegin() const { DARABONBA_PTR_GET_DEFAULT(begin_, 0) };
        inline PortRanges& setBegin(int32_t begin) { DARABONBA_PTR_SET_VALUE(begin_, begin) };


        // end Field Functions 
        bool hasEnd() const { return this->end_ != nullptr;};
        void deleteEnd() { this->end_ = nullptr;};
        inline int32_t getEnd() const { DARABONBA_PTR_GET_DEFAULT(end_, 0) };
        inline PortRanges& setEnd(int32_t end) { DARABONBA_PTR_SET_VALUE(end_, end) };


      protected:
        // The start port.
        shared_ptr<int32_t> begin_ {};
        // The end port.
        shared_ptr<int32_t> end_ {};
      };

      virtual bool empty() const override { return this->addressGroups_ == nullptr
        && this->addresses_ == nullptr && this->applicationId_ == nullptr && this->autoGenerated_ == nullptr && this->browserAccessStatus_ == nullptr && this->configMode_ == nullptr
        && this->connectorIds_ == nullptr && this->createTime_ == nullptr && this->description_ == nullptr && this->l7Config_ == nullptr && this->l7ProxyDomainAutomatic_ == nullptr
        && this->l7ProxyDomainCustom_ == nullptr && this->name_ == nullptr && this->policyIds_ == nullptr && this->portRanges_ == nullptr && this->protocol_ == nullptr
        && this->status_ == nullptr && this->tagIds_ == nullptr; };
      // addressGroups Field Functions 
      bool hasAddressGroups() const { return this->addressGroups_ != nullptr;};
      void deleteAddressGroups() { this->addressGroups_ = nullptr;};
      inline const vector<AddressGroup> & getAddressGroups() const { DARABONBA_PTR_GET_CONST(addressGroups_, vector<AddressGroup>) };
      inline vector<AddressGroup> getAddressGroups() { DARABONBA_PTR_GET(addressGroups_, vector<AddressGroup>) };
      inline Application& setAddressGroups(const vector<AddressGroup> & addressGroups) { DARABONBA_PTR_SET_VALUE(addressGroups_, addressGroups) };
      inline Application& setAddressGroups(vector<AddressGroup> && addressGroups) { DARABONBA_PTR_SET_RVALUE(addressGroups_, addressGroups) };


      // addresses Field Functions 
      bool hasAddresses() const { return this->addresses_ != nullptr;};
      void deleteAddresses() { this->addresses_ = nullptr;};
      inline const vector<string> & getAddresses() const { DARABONBA_PTR_GET_CONST(addresses_, vector<string>) };
      inline vector<string> getAddresses() { DARABONBA_PTR_GET(addresses_, vector<string>) };
      inline Application& setAddresses(const vector<string> & addresses) { DARABONBA_PTR_SET_VALUE(addresses_, addresses) };
      inline Application& setAddresses(vector<string> && addresses) { DARABONBA_PTR_SET_RVALUE(addresses_, addresses) };


      // applicationId Field Functions 
      bool hasApplicationId() const { return this->applicationId_ != nullptr;};
      void deleteApplicationId() { this->applicationId_ = nullptr;};
      inline string getApplicationId() const { DARABONBA_PTR_GET_DEFAULT(applicationId_, "") };
      inline Application& setApplicationId(string applicationId) { DARABONBA_PTR_SET_VALUE(applicationId_, applicationId) };


      // autoGenerated Field Functions 
      bool hasAutoGenerated() const { return this->autoGenerated_ != nullptr;};
      void deleteAutoGenerated() { this->autoGenerated_ = nullptr;};
      inline int32_t getAutoGenerated() const { DARABONBA_PTR_GET_DEFAULT(autoGenerated_, 0) };
      inline Application& setAutoGenerated(int32_t autoGenerated) { DARABONBA_PTR_SET_VALUE(autoGenerated_, autoGenerated) };


      // browserAccessStatus Field Functions 
      bool hasBrowserAccessStatus() const { return this->browserAccessStatus_ != nullptr;};
      void deleteBrowserAccessStatus() { this->browserAccessStatus_ = nullptr;};
      inline string getBrowserAccessStatus() const { DARABONBA_PTR_GET_DEFAULT(browserAccessStatus_, "") };
      inline Application& setBrowserAccessStatus(string browserAccessStatus) { DARABONBA_PTR_SET_VALUE(browserAccessStatus_, browserAccessStatus) };


      // configMode Field Functions 
      bool hasConfigMode() const { return this->configMode_ != nullptr;};
      void deleteConfigMode() { this->configMode_ = nullptr;};
      inline string getConfigMode() const { DARABONBA_PTR_GET_DEFAULT(configMode_, "") };
      inline Application& setConfigMode(string configMode) { DARABONBA_PTR_SET_VALUE(configMode_, configMode) };


      // connectorIds Field Functions 
      bool hasConnectorIds() const { return this->connectorIds_ != nullptr;};
      void deleteConnectorIds() { this->connectorIds_ = nullptr;};
      inline const vector<string> & getConnectorIds() const { DARABONBA_PTR_GET_CONST(connectorIds_, vector<string>) };
      inline vector<string> getConnectorIds() { DARABONBA_PTR_GET(connectorIds_, vector<string>) };
      inline Application& setConnectorIds(const vector<string> & connectorIds) { DARABONBA_PTR_SET_VALUE(connectorIds_, connectorIds) };
      inline Application& setConnectorIds(vector<string> && connectorIds) { DARABONBA_PTR_SET_RVALUE(connectorIds_, connectorIds) };


      // createTime Field Functions 
      bool hasCreateTime() const { return this->createTime_ != nullptr;};
      void deleteCreateTime() { this->createTime_ = nullptr;};
      inline string getCreateTime() const { DARABONBA_PTR_GET_DEFAULT(createTime_, "") };
      inline Application& setCreateTime(string createTime) { DARABONBA_PTR_SET_VALUE(createTime_, createTime) };


      // description Field Functions 
      bool hasDescription() const { return this->description_ != nullptr;};
      void deleteDescription() { this->description_ = nullptr;};
      inline string getDescription() const { DARABONBA_PTR_GET_DEFAULT(description_, "") };
      inline Application& setDescription(string description) { DARABONBA_PTR_SET_VALUE(description_, description) };


      // l7Config Field Functions 
      bool hasL7Config() const { return this->l7Config_ != nullptr;};
      void deleteL7Config() { this->l7Config_ = nullptr;};
      inline const PAL7Config & getL7Config() const { DARABONBA_PTR_GET_CONST(l7Config_, PAL7Config) };
      inline PAL7Config getL7Config() { DARABONBA_PTR_GET(l7Config_, PAL7Config) };
      inline Application& setL7Config(const PAL7Config & l7Config) { DARABONBA_PTR_SET_VALUE(l7Config_, l7Config) };
      inline Application& setL7Config(PAL7Config && l7Config) { DARABONBA_PTR_SET_RVALUE(l7Config_, l7Config) };


      // l7ProxyDomainAutomatic Field Functions 
      bool hasL7ProxyDomainAutomatic() const { return this->l7ProxyDomainAutomatic_ != nullptr;};
      void deleteL7ProxyDomainAutomatic() { this->l7ProxyDomainAutomatic_ = nullptr;};
      inline string getL7ProxyDomainAutomatic() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainAutomatic_, "") };
      inline Application& setL7ProxyDomainAutomatic(string l7ProxyDomainAutomatic) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainAutomatic_, l7ProxyDomainAutomatic) };


      // l7ProxyDomainCustom Field Functions 
      bool hasL7ProxyDomainCustom() const { return this->l7ProxyDomainCustom_ != nullptr;};
      void deleteL7ProxyDomainCustom() { this->l7ProxyDomainCustom_ = nullptr;};
      inline string getL7ProxyDomainCustom() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainCustom_, "") };
      inline Application& setL7ProxyDomainCustom(string l7ProxyDomainCustom) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainCustom_, l7ProxyDomainCustom) };


      // name Field Functions 
      bool hasName() const { return this->name_ != nullptr;};
      void deleteName() { this->name_ = nullptr;};
      inline string getName() const { DARABONBA_PTR_GET_DEFAULT(name_, "") };
      inline Application& setName(string name) { DARABONBA_PTR_SET_VALUE(name_, name) };


      // policyIds Field Functions 
      bool hasPolicyIds() const { return this->policyIds_ != nullptr;};
      void deletePolicyIds() { this->policyIds_ = nullptr;};
      inline const vector<string> & getPolicyIds() const { DARABONBA_PTR_GET_CONST(policyIds_, vector<string>) };
      inline vector<string> getPolicyIds() { DARABONBA_PTR_GET(policyIds_, vector<string>) };
      inline Application& setPolicyIds(const vector<string> & policyIds) { DARABONBA_PTR_SET_VALUE(policyIds_, policyIds) };
      inline Application& setPolicyIds(vector<string> && policyIds) { DARABONBA_PTR_SET_RVALUE(policyIds_, policyIds) };


      // portRanges Field Functions 
      bool hasPortRanges() const { return this->portRanges_ != nullptr;};
      void deletePortRanges() { this->portRanges_ = nullptr;};
      inline const vector<Application::PortRanges> & getPortRanges() const { DARABONBA_PTR_GET_CONST(portRanges_, vector<Application::PortRanges>) };
      inline vector<Application::PortRanges> getPortRanges() { DARABONBA_PTR_GET(portRanges_, vector<Application::PortRanges>) };
      inline Application& setPortRanges(const vector<Application::PortRanges> & portRanges) { DARABONBA_PTR_SET_VALUE(portRanges_, portRanges) };
      inline Application& setPortRanges(vector<Application::PortRanges> && portRanges) { DARABONBA_PTR_SET_RVALUE(portRanges_, portRanges) };


      // protocol Field Functions 
      bool hasProtocol() const { return this->protocol_ != nullptr;};
      void deleteProtocol() { this->protocol_ = nullptr;};
      inline string getProtocol() const { DARABONBA_PTR_GET_DEFAULT(protocol_, "") };
      inline Application& setProtocol(string protocol) { DARABONBA_PTR_SET_VALUE(protocol_, protocol) };


      // status Field Functions 
      bool hasStatus() const { return this->status_ != nullptr;};
      void deleteStatus() { this->status_ = nullptr;};
      inline string getStatus() const { DARABONBA_PTR_GET_DEFAULT(status_, "") };
      inline Application& setStatus(string status) { DARABONBA_PTR_SET_VALUE(status_, status) };


      // tagIds Field Functions 
      bool hasTagIds() const { return this->tagIds_ != nullptr;};
      void deleteTagIds() { this->tagIds_ = nullptr;};
      inline const vector<string> & getTagIds() const { DARABONBA_PTR_GET_CONST(tagIds_, vector<string>) };
      inline vector<string> getTagIds() { DARABONBA_PTR_GET(tagIds_, vector<string>) };
      inline Application& setTagIds(const vector<string> & tagIds) { DARABONBA_PTR_SET_VALUE(tagIds_, tagIds) };
      inline Application& setTagIds(vector<string> && tagIds) { DARABONBA_PTR_SET_RVALUE(tagIds_, tagIds) };


    protected:
      shared_ptr<vector<AddressGroup>> addressGroups_ {};
      // The addresses of the office applications.
      shared_ptr<vector<string>> addresses_ {};
      // The ID of the office application.
      shared_ptr<string> applicationId_ {};
      shared_ptr<int32_t> autoGenerated_ {};
      // The browser access mode. Valid values:
      // 
      // *   **Enabled**
      // *   **Disabled**
      shared_ptr<string> browserAccessStatus_ {};
      shared_ptr<string> configMode_ {};
      // The IDs of connectors.
      shared_ptr<vector<string>> connectorIds_ {};
      // The creation time of the office application.
      shared_ptr<string> createTime_ {};
      // The description of the office application.
      shared_ptr<string> description_ {};
      // The browser access mode parameter. The parameter indicates the configurations of Layer 7 applications.
      shared_ptr<PAL7Config> l7Config_ {};
      // The browser access mode parameter. The parameter indicates the domain name that the proxy gateway uses.
      shared_ptr<string> l7ProxyDomainAutomatic_ {};
      // The browser access mode parameter. The parameter indicates the custom domain name of the proxy gateway.
      shared_ptr<string> l7ProxyDomainCustom_ {};
      // The name of the office application.
      shared_ptr<string> name_ {};
      // The IDs of the private access policies.
      shared_ptr<vector<string>> policyIds_ {};
      // The port ranges of the office applications. Multiple port ranges cannot be duplicated or overlapped.
      shared_ptr<vector<Application::PortRanges>> portRanges_ {};
      // The protocol that is used by the office application. Valid values:
      // 
      // *   **All**
      // *   **TCP**
      // *   **UDP**
      shared_ptr<string> protocol_ {};
      // The status of the office application. Valid values:
      // 
      // *   **Enabled**
      // *   **Disabled**
      shared_ptr<string> status_ {};
      // The IDs of the tags for the office applications.
      shared_ptr<vector<string>> tagIds_ {};
    };

    virtual bool empty() const override { return this->application_ == nullptr
        && this->requestId_ == nullptr; };
    // application Field Functions 
    bool hasApplication() const { return this->application_ != nullptr;};
    void deleteApplication() { this->application_ = nullptr;};
    inline const GetPrivateAccessApplicationResponseBody::Application & getApplication() const { DARABONBA_PTR_GET_CONST(application_, GetPrivateAccessApplicationResponseBody::Application) };
    inline GetPrivateAccessApplicationResponseBody::Application getApplication() { DARABONBA_PTR_GET(application_, GetPrivateAccessApplicationResponseBody::Application) };
    inline GetPrivateAccessApplicationResponseBody& setApplication(const GetPrivateAccessApplicationResponseBody::Application & application) { DARABONBA_PTR_SET_VALUE(application_, application) };
    inline GetPrivateAccessApplicationResponseBody& setApplication(GetPrivateAccessApplicationResponseBody::Application && application) { DARABONBA_PTR_SET_RVALUE(application_, application) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline GetPrivateAccessApplicationResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // The office application.
    shared_ptr<GetPrivateAccessApplicationResponseBody::Application> application_ {};
    // The ID of the request.
    shared_ptr<string> requestId_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Csas20230120
#endif
