// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTPRIVATEACCESSAPPLICATIONSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_LISTPRIVATEACCESSAPPLICATIONSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/AddressGroup.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Csas20230120
{
namespace Models
{
  class ListPrivateAccessApplicationsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListPrivateAccessApplicationsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Applications, applications_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(TotalNum, totalNum_);
    };
    friend void from_json(const Darabonba::Json& j, ListPrivateAccessApplicationsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Applications, applications_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(TotalNum, totalNum_);
    };
    ListPrivateAccessApplicationsResponseBody() = default ;
    ListPrivateAccessApplicationsResponseBody(const ListPrivateAccessApplicationsResponseBody &) = default ;
    ListPrivateAccessApplicationsResponseBody(ListPrivateAccessApplicationsResponseBody &&) = default ;
    ListPrivateAccessApplicationsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListPrivateAccessApplicationsResponseBody() = default ;
    ListPrivateAccessApplicationsResponseBody& operator=(const ListPrivateAccessApplicationsResponseBody &) = default ;
    ListPrivateAccessApplicationsResponseBody& operator=(ListPrivateAccessApplicationsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    class Applications : public Darabonba::Model {
    public:
      friend void to_json(Darabonba::Json& j, const Applications& obj) { 
        DARABONBA_PTR_TO_JSON(AddressGroups, addressGroups_);
        DARABONBA_PTR_TO_JSON(Addresses, addresses_);
        DARABONBA_PTR_TO_JSON(ApplicationId, applicationId_);
        DARABONBA_PTR_TO_JSON(AutoGenerated, autoGenerated_);
        DARABONBA_PTR_TO_JSON(BrowserAccessStatus, browserAccessStatus_);
        DARABONBA_PTR_TO_JSON(ConfigMode, configMode_);
        DARABONBA_PTR_TO_JSON(ConnectorIds, connectorIds_);
        DARABONBA_PTR_TO_JSON(CreateTime, createTime_);
        DARABONBA_PTR_TO_JSON(Description, description_);
        DARABONBA_PTR_TO_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
        DARABONBA_PTR_TO_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
        DARABONBA_PTR_TO_JSON(Name, name_);
        DARABONBA_PTR_TO_JSON(PolicyIds, policyIds_);
        DARABONBA_PTR_TO_JSON(PortRanges, portRanges_);
        DARABONBA_PTR_TO_JSON(Protocol, protocol_);
        DARABONBA_PTR_TO_JSON(Status, status_);
        DARABONBA_PTR_TO_JSON(TagIds, tagIds_);
      };
      friend void from_json(const Darabonba::Json& j, Applications& obj) { 
        DARABONBA_PTR_FROM_JSON(AddressGroups, addressGroups_);
        DARABONBA_PTR_FROM_JSON(Addresses, addresses_);
        DARABONBA_PTR_FROM_JSON(ApplicationId, applicationId_);
        DARABONBA_PTR_FROM_JSON(AutoGenerated, autoGenerated_);
        DARABONBA_PTR_FROM_JSON(BrowserAccessStatus, browserAccessStatus_);
        DARABONBA_PTR_FROM_JSON(ConfigMode, configMode_);
        DARABONBA_PTR_FROM_JSON(ConnectorIds, connectorIds_);
        DARABONBA_PTR_FROM_JSON(CreateTime, createTime_);
        DARABONBA_PTR_FROM_JSON(Description, description_);
        DARABONBA_PTR_FROM_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
        DARABONBA_PTR_FROM_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
        DARABONBA_PTR_FROM_JSON(Name, name_);
        DARABONBA_PTR_FROM_JSON(PolicyIds, policyIds_);
        DARABONBA_PTR_FROM_JSON(PortRanges, portRanges_);
        DARABONBA_PTR_FROM_JSON(Protocol, protocol_);
        DARABONBA_PTR_FROM_JSON(Status, status_);
        DARABONBA_PTR_FROM_JSON(TagIds, tagIds_);
      };
      Applications() = default ;
      Applications(const Applications &) = default ;
      Applications(Applications &&) = default ;
      Applications(const Darabonba::Json & obj) { from_json(obj, *this); };
      virtual ~Applications() = default ;
      Applications& operator=(const Applications &) = default ;
      Applications& operator=(Applications &&) = default ;
      virtual void validate() const override {
      };
      virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
      virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
      class PortRanges : public Darabonba::Model {
      public:
        friend void to_json(Darabonba::Json& j, const PortRanges& obj) { 
          DARABONBA_PTR_TO_JSON(Begin, begin_);
          DARABONBA_PTR_TO_JSON(End, end_);
        };
        friend void from_json(const Darabonba::Json& j, PortRanges& obj) { 
          DARABONBA_PTR_FROM_JSON(Begin, begin_);
          DARABONBA_PTR_FROM_JSON(End, end_);
        };
        PortRanges() = default ;
        PortRanges(const PortRanges &) = default ;
        PortRanges(PortRanges &&) = default ;
        PortRanges(const Darabonba::Json & obj) { from_json(obj, *this); };
        virtual ~PortRanges() = default ;
        PortRanges& operator=(const PortRanges &) = default ;
        PortRanges& operator=(PortRanges &&) = default ;
        virtual void validate() const override {
        };
        virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
        virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
        virtual bool empty() const override { return this->begin_ == nullptr
        && this->end_ == nullptr; };
        // begin Field Functions 
        bool hasBegin() const { return this->begin_ != nullptr;};
        void deleteBegin() { this->begin_ = nullptr;};
        inline int32_t getBegin() const { DARABONBA_PTR_GET_DEFAULT(begin_, 0) };
        inline PortRanges& setBegin(int32_t begin) { DARABONBA_PTR_SET_VALUE(begin_, begin) };


        // end Field Functions 
        bool hasEnd() const { return this->end_ != nullptr;};
        void deleteEnd() { this->end_ = nullptr;};
        inline int32_t getEnd() const { DARABONBA_PTR_GET_DEFAULT(end_, 0) };
        inline PortRanges& setEnd(int32_t end) { DARABONBA_PTR_SET_VALUE(end_, end) };


      protected:
        shared_ptr<int32_t> begin_ {};
        shared_ptr<int32_t> end_ {};
      };

      virtual bool empty() const override { return this->addressGroups_ == nullptr
        && this->addresses_ == nullptr && this->applicationId_ == nullptr && this->autoGenerated_ == nullptr && this->browserAccessStatus_ == nullptr && this->configMode_ == nullptr
        && this->connectorIds_ == nullptr && this->createTime_ == nullptr && this->description_ == nullptr && this->l7ProxyDomainAutomatic_ == nullptr && this->l7ProxyDomainCustom_ == nullptr
        && this->name_ == nullptr && this->policyIds_ == nullptr && this->portRanges_ == nullptr && this->protocol_ == nullptr && this->status_ == nullptr
        && this->tagIds_ == nullptr; };
      // addressGroups Field Functions 
      bool hasAddressGroups() const { return this->addressGroups_ != nullptr;};
      void deleteAddressGroups() { this->addressGroups_ = nullptr;};
      inline const vector<AddressGroup> & getAddressGroups() const { DARABONBA_PTR_GET_CONST(addressGroups_, vector<AddressGroup>) };
      inline vector<AddressGroup> getAddressGroups() { DARABONBA_PTR_GET(addressGroups_, vector<AddressGroup>) };
      inline Applications& setAddressGroups(const vector<AddressGroup> & addressGroups) { DARABONBA_PTR_SET_VALUE(addressGroups_, addressGroups) };
      inline Applications& setAddressGroups(vector<AddressGroup> && addressGroups) { DARABONBA_PTR_SET_RVALUE(addressGroups_, addressGroups) };


      // addresses Field Functions 
      bool hasAddresses() const { return this->addresses_ != nullptr;};
      void deleteAddresses() { this->addresses_ = nullptr;};
      inline const vector<string> & getAddresses() const { DARABONBA_PTR_GET_CONST(addresses_, vector<string>) };
      inline vector<string> getAddresses() { DARABONBA_PTR_GET(addresses_, vector<string>) };
      inline Applications& setAddresses(const vector<string> & addresses) { DARABONBA_PTR_SET_VALUE(addresses_, addresses) };
      inline Applications& setAddresses(vector<string> && addresses) { DARABONBA_PTR_SET_RVALUE(addresses_, addresses) };


      // applicationId Field Functions 
      bool hasApplicationId() const { return this->applicationId_ != nullptr;};
      void deleteApplicationId() { this->applicationId_ = nullptr;};
      inline string getApplicationId() const { DARABONBA_PTR_GET_DEFAULT(applicationId_, "") };
      inline Applications& setApplicationId(string applicationId) { DARABONBA_PTR_SET_VALUE(applicationId_, applicationId) };


      // autoGenerated Field Functions 
      bool hasAutoGenerated() const { return this->autoGenerated_ != nullptr;};
      void deleteAutoGenerated() { this->autoGenerated_ = nullptr;};
      inline int32_t getAutoGenerated() const { DARABONBA_PTR_GET_DEFAULT(autoGenerated_, 0) };
      inline Applications& setAutoGenerated(int32_t autoGenerated) { DARABONBA_PTR_SET_VALUE(autoGenerated_, autoGenerated) };


      // browserAccessStatus Field Functions 
      bool hasBrowserAccessStatus() const { return this->browserAccessStatus_ != nullptr;};
      void deleteBrowserAccessStatus() { this->browserAccessStatus_ = nullptr;};
      inline string getBrowserAccessStatus() const { DARABONBA_PTR_GET_DEFAULT(browserAccessStatus_, "") };
      inline Applications& setBrowserAccessStatus(string browserAccessStatus) { DARABONBA_PTR_SET_VALUE(browserAccessStatus_, browserAccessStatus) };


      // configMode Field Functions 
      bool hasConfigMode() const { return this->configMode_ != nullptr;};
      void deleteConfigMode() { this->configMode_ = nullptr;};
      inline string getConfigMode() const { DARABONBA_PTR_GET_DEFAULT(configMode_, "") };
      inline Applications& setConfigMode(string configMode) { DARABONBA_PTR_SET_VALUE(configMode_, configMode) };


      // connectorIds Field Functions 
      bool hasConnectorIds() const { return this->connectorIds_ != nullptr;};
      void deleteConnectorIds() { this->connectorIds_ = nullptr;};
      inline const vector<string> & getConnectorIds() const { DARABONBA_PTR_GET_CONST(connectorIds_, vector<string>) };
      inline vector<string> getConnectorIds() { DARABONBA_PTR_GET(connectorIds_, vector<string>) };
      inline Applications& setConnectorIds(const vector<string> & connectorIds) { DARABONBA_PTR_SET_VALUE(connectorIds_, connectorIds) };
      inline Applications& setConnectorIds(vector<string> && connectorIds) { DARABONBA_PTR_SET_RVALUE(connectorIds_, connectorIds) };


      // createTime Field Functions 
      bool hasCreateTime() const { return this->createTime_ != nullptr;};
      void deleteCreateTime() { this->createTime_ = nullptr;};
      inline string getCreateTime() const { DARABONBA_PTR_GET_DEFAULT(createTime_, "") };
      inline Applications& setCreateTime(string createTime) { DARABONBA_PTR_SET_VALUE(createTime_, createTime) };


      // description Field Functions 
      bool hasDescription() const { return this->description_ != nullptr;};
      void deleteDescription() { this->description_ = nullptr;};
      inline string getDescription() const { DARABONBA_PTR_GET_DEFAULT(description_, "") };
      inline Applications& setDescription(string description) { DARABONBA_PTR_SET_VALUE(description_, description) };


      // l7ProxyDomainAutomatic Field Functions 
      bool hasL7ProxyDomainAutomatic() const { return this->l7ProxyDomainAutomatic_ != nullptr;};
      void deleteL7ProxyDomainAutomatic() { this->l7ProxyDomainAutomatic_ = nullptr;};
      inline string getL7ProxyDomainAutomatic() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainAutomatic_, "") };
      inline Applications& setL7ProxyDomainAutomatic(string l7ProxyDomainAutomatic) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainAutomatic_, l7ProxyDomainAutomatic) };


      // l7ProxyDomainCustom Field Functions 
      bool hasL7ProxyDomainCustom() const { return this->l7ProxyDomainCustom_ != nullptr;};
      void deleteL7ProxyDomainCustom() { this->l7ProxyDomainCustom_ = nullptr;};
      inline string getL7ProxyDomainCustom() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainCustom_, "") };
      inline Applications& setL7ProxyDomainCustom(string l7ProxyDomainCustom) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainCustom_, l7ProxyDomainCustom) };


      // name Field Functions 
      bool hasName() const { return this->name_ != nullptr;};
      void deleteName() { this->name_ = nullptr;};
      inline string getName() const { DARABONBA_PTR_GET_DEFAULT(name_, "") };
      inline Applications& setName(string name) { DARABONBA_PTR_SET_VALUE(name_, name) };


      // policyIds Field Functions 
      bool hasPolicyIds() const { return this->policyIds_ != nullptr;};
      void deletePolicyIds() { this->policyIds_ = nullptr;};
      inline const vector<string> & getPolicyIds() const { DARABONBA_PTR_GET_CONST(policyIds_, vector<string>) };
      inline vector<string> getPolicyIds() { DARABONBA_PTR_GET(policyIds_, vector<string>) };
      inline Applications& setPolicyIds(const vector<string> & policyIds) { DARABONBA_PTR_SET_VALUE(policyIds_, policyIds) };
      inline Applications& setPolicyIds(vector<string> && policyIds) { DARABONBA_PTR_SET_RVALUE(policyIds_, policyIds) };


      // portRanges Field Functions 
      bool hasPortRanges() const { return this->portRanges_ != nullptr;};
      void deletePortRanges() { this->portRanges_ = nullptr;};
      inline const vector<Applications::PortRanges> & getPortRanges() const { DARABONBA_PTR_GET_CONST(portRanges_, vector<Applications::PortRanges>) };
      inline vector<Applications::PortRanges> getPortRanges() { DARABONBA_PTR_GET(portRanges_, vector<Applications::PortRanges>) };
      inline Applications& setPortRanges(const vector<Applications::PortRanges> & portRanges) { DARABONBA_PTR_SET_VALUE(portRanges_, portRanges) };
      inline Applications& setPortRanges(vector<Applications::PortRanges> && portRanges) { DARABONBA_PTR_SET_RVALUE(portRanges_, portRanges) };


      // protocol Field Functions 
      bool hasProtocol() const { return this->protocol_ != nullptr;};
      void deleteProtocol() { this->protocol_ = nullptr;};
      inline string getProtocol() const { DARABONBA_PTR_GET_DEFAULT(protocol_, "") };
      inline Applications& setProtocol(string protocol) { DARABONBA_PTR_SET_VALUE(protocol_, protocol) };


      // status Field Functions 
      bool hasStatus() const { return this->status_ != nullptr;};
      void deleteStatus() { this->status_ = nullptr;};
      inline string getStatus() const { DARABONBA_PTR_GET_DEFAULT(status_, "") };
      inline Applications& setStatus(string status) { DARABONBA_PTR_SET_VALUE(status_, status) };


      // tagIds Field Functions 
      bool hasTagIds() const { return this->tagIds_ != nullptr;};
      void deleteTagIds() { this->tagIds_ = nullptr;};
      inline const vector<string> & getTagIds() const { DARABONBA_PTR_GET_CONST(tagIds_, vector<string>) };
      inline vector<string> getTagIds() { DARABONBA_PTR_GET(tagIds_, vector<string>) };
      inline Applications& setTagIds(const vector<string> & tagIds) { DARABONBA_PTR_SET_VALUE(tagIds_, tagIds) };
      inline Applications& setTagIds(vector<string> && tagIds) { DARABONBA_PTR_SET_RVALUE(tagIds_, tagIds) };


    protected:
      shared_ptr<vector<AddressGroup>> addressGroups_ {};
      shared_ptr<vector<string>> addresses_ {};
      shared_ptr<string> applicationId_ {};
      shared_ptr<int32_t> autoGenerated_ {};
      shared_ptr<string> browserAccessStatus_ {};
      shared_ptr<string> configMode_ {};
      shared_ptr<vector<string>> connectorIds_ {};
      shared_ptr<string> createTime_ {};
      shared_ptr<string> description_ {};
      shared_ptr<string> l7ProxyDomainAutomatic_ {};
      shared_ptr<string> l7ProxyDomainCustom_ {};
      shared_ptr<string> name_ {};
      shared_ptr<vector<string>> policyIds_ {};
      shared_ptr<vector<Applications::PortRanges>> portRanges_ {};
      shared_ptr<string> protocol_ {};
      shared_ptr<string> status_ {};
      shared_ptr<vector<string>> tagIds_ {};
    };

    virtual bool empty() const override { return this->applications_ == nullptr
        && this->requestId_ == nullptr && this->totalNum_ == nullptr; };
    // applications Field Functions 
    bool hasApplications() const { return this->applications_ != nullptr;};
    void deleteApplications() { this->applications_ = nullptr;};
    inline const vector<ListPrivateAccessApplicationsResponseBody::Applications> & getApplications() const { DARABONBA_PTR_GET_CONST(applications_, vector<ListPrivateAccessApplicationsResponseBody::Applications>) };
    inline vector<ListPrivateAccessApplicationsResponseBody::Applications> getApplications() { DARABONBA_PTR_GET(applications_, vector<ListPrivateAccessApplicationsResponseBody::Applications>) };
    inline ListPrivateAccessApplicationsResponseBody& setApplications(const vector<ListPrivateAccessApplicationsResponseBody::Applications> & applications) { DARABONBA_PTR_SET_VALUE(applications_, applications) };
    inline ListPrivateAccessApplicationsResponseBody& setApplications(vector<ListPrivateAccessApplicationsResponseBody::Applications> && applications) { DARABONBA_PTR_SET_RVALUE(applications_, applications) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline ListPrivateAccessApplicationsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // totalNum Field Functions 
    bool hasTotalNum() const { return this->totalNum_ != nullptr;};
    void deleteTotalNum() { this->totalNum_ = nullptr;};
    inline int32_t getTotalNum() const { DARABONBA_PTR_GET_DEFAULT(totalNum_, 0) };
    inline ListPrivateAccessApplicationsResponseBody& setTotalNum(int32_t totalNum) { DARABONBA_PTR_SET_VALUE(totalNum_, totalNum) };


  protected:
    shared_ptr<vector<ListPrivateAccessApplicationsResponseBody::Applications>> applications_ {};
    shared_ptr<string> requestId_ {};
    shared_ptr<int32_t> totalNum_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Csas20230120
#endif
