// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_LISTPRIVATEACCESSAPPLICATIONSRESPONSEBODYAPPLICATIONS_HPP_
#define ALIBABACLOUD_MODELS_LISTPRIVATEACCESSAPPLICATIONSRESPONSEBODYAPPLICATIONS_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Csas20230120
{
namespace Models
{
  class ListPrivateAccessApplicationsResponseBodyApplications : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const ListPrivateAccessApplicationsResponseBodyApplications& obj) { 
      DARABONBA_PTR_TO_JSON(Addresses, addresses_);
      DARABONBA_PTR_TO_JSON(ApplicationId, applicationId_);
      DARABONBA_PTR_TO_JSON(AutoGenerated, autoGenerated_);
      DARABONBA_PTR_TO_JSON(BrowserAccessStatus, browserAccessStatus_);
      DARABONBA_PTR_TO_JSON(ConnectorIds, connectorIds_);
      DARABONBA_PTR_TO_JSON(CreateTime, createTime_);
      DARABONBA_PTR_TO_JSON(Description, description_);
      DARABONBA_PTR_TO_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
      DARABONBA_PTR_TO_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
      DARABONBA_PTR_TO_JSON(Name, name_);
      DARABONBA_PTR_TO_JSON(PolicyIds, policyIds_);
      DARABONBA_PTR_TO_JSON(PortRanges, portRanges_);
      DARABONBA_PTR_TO_JSON(Protocol, protocol_);
      DARABONBA_PTR_TO_JSON(Status, status_);
      DARABONBA_PTR_TO_JSON(TagIds, tagIds_);
    };
    friend void from_json(const Darabonba::Json& j, ListPrivateAccessApplicationsResponseBodyApplications& obj) { 
      DARABONBA_PTR_FROM_JSON(Addresses, addresses_);
      DARABONBA_PTR_FROM_JSON(ApplicationId, applicationId_);
      DARABONBA_PTR_FROM_JSON(AutoGenerated, autoGenerated_);
      DARABONBA_PTR_FROM_JSON(BrowserAccessStatus, browserAccessStatus_);
      DARABONBA_PTR_FROM_JSON(ConnectorIds, connectorIds_);
      DARABONBA_PTR_FROM_JSON(CreateTime, createTime_);
      DARABONBA_PTR_FROM_JSON(Description, description_);
      DARABONBA_PTR_FROM_JSON(L7ProxyDomainAutomatic, l7ProxyDomainAutomatic_);
      DARABONBA_PTR_FROM_JSON(L7ProxyDomainCustom, l7ProxyDomainCustom_);
      DARABONBA_PTR_FROM_JSON(Name, name_);
      DARABONBA_PTR_FROM_JSON(PolicyIds, policyIds_);
      DARABONBA_PTR_FROM_JSON(PortRanges, portRanges_);
      DARABONBA_PTR_FROM_JSON(Protocol, protocol_);
      DARABONBA_PTR_FROM_JSON(Status, status_);
      DARABONBA_PTR_FROM_JSON(TagIds, tagIds_);
    };
    ListPrivateAccessApplicationsResponseBodyApplications() = default ;
    ListPrivateAccessApplicationsResponseBodyApplications(const ListPrivateAccessApplicationsResponseBodyApplications &) = default ;
    ListPrivateAccessApplicationsResponseBodyApplications(ListPrivateAccessApplicationsResponseBodyApplications &&) = default ;
    ListPrivateAccessApplicationsResponseBodyApplications(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~ListPrivateAccessApplicationsResponseBodyApplications() = default ;
    ListPrivateAccessApplicationsResponseBodyApplications& operator=(const ListPrivateAccessApplicationsResponseBodyApplications &) = default ;
    ListPrivateAccessApplicationsResponseBodyApplications& operator=(ListPrivateAccessApplicationsResponseBodyApplications &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->addresses_ == nullptr
        && return this->applicationId_ == nullptr && return this->autoGenerated_ == nullptr && return this->browserAccessStatus_ == nullptr && return this->connectorIds_ == nullptr && return this->createTime_ == nullptr
        && return this->description_ == nullptr && return this->l7ProxyDomainAutomatic_ == nullptr && return this->l7ProxyDomainCustom_ == nullptr && return this->name_ == nullptr && return this->policyIds_ == nullptr
        && return this->portRanges_ == nullptr && return this->protocol_ == nullptr && return this->status_ == nullptr && return this->tagIds_ == nullptr; };
    // addresses Field Functions 
    bool hasAddresses() const { return this->addresses_ != nullptr;};
    void deleteAddresses() { this->addresses_ = nullptr;};
    inline const vector<string> & addresses() const { DARABONBA_PTR_GET_CONST(addresses_, vector<string>) };
    inline vector<string> addresses() { DARABONBA_PTR_GET(addresses_, vector<string>) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setAddresses(const vector<string> & addresses) { DARABONBA_PTR_SET_VALUE(addresses_, addresses) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setAddresses(vector<string> && addresses) { DARABONBA_PTR_SET_RVALUE(addresses_, addresses) };


    // applicationId Field Functions 
    bool hasApplicationId() const { return this->applicationId_ != nullptr;};
    void deleteApplicationId() { this->applicationId_ = nullptr;};
    inline string applicationId() const { DARABONBA_PTR_GET_DEFAULT(applicationId_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setApplicationId(string applicationId) { DARABONBA_PTR_SET_VALUE(applicationId_, applicationId) };


    // autoGenerated Field Functions 
    bool hasAutoGenerated() const { return this->autoGenerated_ != nullptr;};
    void deleteAutoGenerated() { this->autoGenerated_ = nullptr;};
    inline int32_t autoGenerated() const { DARABONBA_PTR_GET_DEFAULT(autoGenerated_, 0) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setAutoGenerated(int32_t autoGenerated) { DARABONBA_PTR_SET_VALUE(autoGenerated_, autoGenerated) };


    // browserAccessStatus Field Functions 
    bool hasBrowserAccessStatus() const { return this->browserAccessStatus_ != nullptr;};
    void deleteBrowserAccessStatus() { this->browserAccessStatus_ = nullptr;};
    inline string browserAccessStatus() const { DARABONBA_PTR_GET_DEFAULT(browserAccessStatus_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setBrowserAccessStatus(string browserAccessStatus) { DARABONBA_PTR_SET_VALUE(browserAccessStatus_, browserAccessStatus) };


    // connectorIds Field Functions 
    bool hasConnectorIds() const { return this->connectorIds_ != nullptr;};
    void deleteConnectorIds() { this->connectorIds_ = nullptr;};
    inline const vector<string> & connectorIds() const { DARABONBA_PTR_GET_CONST(connectorIds_, vector<string>) };
    inline vector<string> connectorIds() { DARABONBA_PTR_GET(connectorIds_, vector<string>) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setConnectorIds(const vector<string> & connectorIds) { DARABONBA_PTR_SET_VALUE(connectorIds_, connectorIds) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setConnectorIds(vector<string> && connectorIds) { DARABONBA_PTR_SET_RVALUE(connectorIds_, connectorIds) };


    // createTime Field Functions 
    bool hasCreateTime() const { return this->createTime_ != nullptr;};
    void deleteCreateTime() { this->createTime_ = nullptr;};
    inline string createTime() const { DARABONBA_PTR_GET_DEFAULT(createTime_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setCreateTime(string createTime) { DARABONBA_PTR_SET_VALUE(createTime_, createTime) };


    // description Field Functions 
    bool hasDescription() const { return this->description_ != nullptr;};
    void deleteDescription() { this->description_ = nullptr;};
    inline string description() const { DARABONBA_PTR_GET_DEFAULT(description_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setDescription(string description) { DARABONBA_PTR_SET_VALUE(description_, description) };


    // l7ProxyDomainAutomatic Field Functions 
    bool hasL7ProxyDomainAutomatic() const { return this->l7ProxyDomainAutomatic_ != nullptr;};
    void deleteL7ProxyDomainAutomatic() { this->l7ProxyDomainAutomatic_ = nullptr;};
    inline string l7ProxyDomainAutomatic() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainAutomatic_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setL7ProxyDomainAutomatic(string l7ProxyDomainAutomatic) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainAutomatic_, l7ProxyDomainAutomatic) };


    // l7ProxyDomainCustom Field Functions 
    bool hasL7ProxyDomainCustom() const { return this->l7ProxyDomainCustom_ != nullptr;};
    void deleteL7ProxyDomainCustom() { this->l7ProxyDomainCustom_ = nullptr;};
    inline string l7ProxyDomainCustom() const { DARABONBA_PTR_GET_DEFAULT(l7ProxyDomainCustom_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setL7ProxyDomainCustom(string l7ProxyDomainCustom) { DARABONBA_PTR_SET_VALUE(l7ProxyDomainCustom_, l7ProxyDomainCustom) };


    // name Field Functions 
    bool hasName() const { return this->name_ != nullptr;};
    void deleteName() { this->name_ = nullptr;};
    inline string name() const { DARABONBA_PTR_GET_DEFAULT(name_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setName(string name) { DARABONBA_PTR_SET_VALUE(name_, name) };


    // policyIds Field Functions 
    bool hasPolicyIds() const { return this->policyIds_ != nullptr;};
    void deletePolicyIds() { this->policyIds_ = nullptr;};
    inline const vector<string> & policyIds() const { DARABONBA_PTR_GET_CONST(policyIds_, vector<string>) };
    inline vector<string> policyIds() { DARABONBA_PTR_GET(policyIds_, vector<string>) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setPolicyIds(const vector<string> & policyIds) { DARABONBA_PTR_SET_VALUE(policyIds_, policyIds) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setPolicyIds(vector<string> && policyIds) { DARABONBA_PTR_SET_RVALUE(policyIds_, policyIds) };


    // portRanges Field Functions 
    bool hasPortRanges() const { return this->portRanges_ != nullptr;};
    void deletePortRanges() { this->portRanges_ = nullptr;};
    inline const vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges> & portRanges() const { DARABONBA_PTR_GET_CONST(portRanges_, vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges>) };
    inline vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges> portRanges() { DARABONBA_PTR_GET(portRanges_, vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges>) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setPortRanges(const vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges> & portRanges) { DARABONBA_PTR_SET_VALUE(portRanges_, portRanges) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setPortRanges(vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges> && portRanges) { DARABONBA_PTR_SET_RVALUE(portRanges_, portRanges) };


    // protocol Field Functions 
    bool hasProtocol() const { return this->protocol_ != nullptr;};
    void deleteProtocol() { this->protocol_ = nullptr;};
    inline string protocol() const { DARABONBA_PTR_GET_DEFAULT(protocol_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setProtocol(string protocol) { DARABONBA_PTR_SET_VALUE(protocol_, protocol) };


    // status Field Functions 
    bool hasStatus() const { return this->status_ != nullptr;};
    void deleteStatus() { this->status_ = nullptr;};
    inline string status() const { DARABONBA_PTR_GET_DEFAULT(status_, "") };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setStatus(string status) { DARABONBA_PTR_SET_VALUE(status_, status) };


    // tagIds Field Functions 
    bool hasTagIds() const { return this->tagIds_ != nullptr;};
    void deleteTagIds() { this->tagIds_ = nullptr;};
    inline const vector<string> & tagIds() const { DARABONBA_PTR_GET_CONST(tagIds_, vector<string>) };
    inline vector<string> tagIds() { DARABONBA_PTR_GET(tagIds_, vector<string>) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setTagIds(const vector<string> & tagIds) { DARABONBA_PTR_SET_VALUE(tagIds_, tagIds) };
    inline ListPrivateAccessApplicationsResponseBodyApplications& setTagIds(vector<string> && tagIds) { DARABONBA_PTR_SET_RVALUE(tagIds_, tagIds) };


  protected:
    std::shared_ptr<vector<string>> addresses_ = nullptr;
    std::shared_ptr<string> applicationId_ = nullptr;
    std::shared_ptr<int32_t> autoGenerated_ = nullptr;
    std::shared_ptr<string> browserAccessStatus_ = nullptr;
    std::shared_ptr<vector<string>> connectorIds_ = nullptr;
    std::shared_ptr<string> createTime_ = nullptr;
    std::shared_ptr<string> description_ = nullptr;
    std::shared_ptr<string> l7ProxyDomainAutomatic_ = nullptr;
    std::shared_ptr<string> l7ProxyDomainCustom_ = nullptr;
    std::shared_ptr<string> name_ = nullptr;
    std::shared_ptr<vector<string>> policyIds_ = nullptr;
    std::shared_ptr<vector<Models::ListPrivateAccessApplicationsResponseBodyApplicationsPortRanges>> portRanges_ = nullptr;
    std::shared_ptr<string> protocol_ = nullptr;
    std::shared_ptr<string> status_ = nullptr;
    std::shared_ptr<vector<string>> tagIds_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Csas20230120
#endif
