// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_AGENTTEAMS20260605MODEL_HPP_
#define ALIBABACLOUD_AGENTTEAMS20260605MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BindIdentityProviderRequest.hpp>
#include <alibabacloud/models/BindIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/BindIdentityProviderResponse.hpp>
#include <alibabacloud/models/ConfigureNatGatewayRequest.hpp>
#include <alibabacloud/models/ConfigureNatGatewayResponseBody.hpp>
#include <alibabacloud/models/ConfigureNatGatewayResponse.hpp>
#include <alibabacloud/models/CreateCredentialRequest.hpp>
#include <alibabacloud/models/CreateCredentialResponseBody.hpp>
#include <alibabacloud/models/CreateCredentialResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateMcpRequest.hpp>
#include <alibabacloud/models/CreateMcpShrinkRequest.hpp>
#include <alibabacloud/models/CreateMcpResponseBody.hpp>
#include <alibabacloud/models/CreateMcpResponse.hpp>
#include <alibabacloud/models/CreateModelRequest.hpp>
#include <alibabacloud/models/CreateModelShrinkRequest.hpp>
#include <alibabacloud/models/CreateModelResponseBody.hpp>
#include <alibabacloud/models/CreateModelResponse.hpp>
#include <alibabacloud/models/CreateModelProviderRequest.hpp>
#include <alibabacloud/models/CreateModelProviderShrinkRequest.hpp>
#include <alibabacloud/models/CreateModelProviderResponseBody.hpp>
#include <alibabacloud/models/CreateModelProviderResponse.hpp>
#include <alibabacloud/models/CreateServiceEndpointRequest.hpp>
#include <alibabacloud/models/CreateServiceEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateServiceEndpointResponse.hpp>
#include <alibabacloud/models/CreateTeamRequest.hpp>
#include <alibabacloud/models/CreateTeamShrinkRequest.hpp>
#include <alibabacloud/models/CreateTeamResponseBody.hpp>
#include <alibabacloud/models/CreateTeamResponse.hpp>
#include <alibabacloud/models/CreateUserRequest.hpp>
#include <alibabacloud/models/CreateUserResponseBody.hpp>
#include <alibabacloud/models/CreateUserResponse.hpp>
#include <alibabacloud/models/CreateWorkerRequest.hpp>
#include <alibabacloud/models/CreateWorkerShrinkRequest.hpp>
#include <alibabacloud/models/CreateWorkerResponseBody.hpp>
#include <alibabacloud/models/CreateWorkerResponse.hpp>
#include <alibabacloud/models/CreateWorkerBootstrapTokenRequest.hpp>
#include <alibabacloud/models/CreateWorkerBootstrapTokenResponseBody.hpp>
#include <alibabacloud/models/CreateWorkerBootstrapTokenResponse.hpp>
#include <alibabacloud/models/DeleteCredentialRequest.hpp>
#include <alibabacloud/models/DeleteCredentialResponseBody.hpp>
#include <alibabacloud/models/DeleteCredentialResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteMcpRequest.hpp>
#include <alibabacloud/models/DeleteMcpResponseBody.hpp>
#include <alibabacloud/models/DeleteMcpResponse.hpp>
#include <alibabacloud/models/DeleteModelRequest.hpp>
#include <alibabacloud/models/DeleteModelResponseBody.hpp>
#include <alibabacloud/models/DeleteModelResponse.hpp>
#include <alibabacloud/models/DeleteModelProviderRequest.hpp>
#include <alibabacloud/models/DeleteModelProviderResponseBody.hpp>
#include <alibabacloud/models/DeleteModelProviderResponse.hpp>
#include <alibabacloud/models/DeleteServiceEndpointRequest.hpp>
#include <alibabacloud/models/DeleteServiceEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceEndpointResponse.hpp>
#include <alibabacloud/models/DeleteTeamRequest.hpp>
#include <alibabacloud/models/DeleteTeamResponseBody.hpp>
#include <alibabacloud/models/DeleteTeamResponse.hpp>
#include <alibabacloud/models/DeleteUserRequest.hpp>
#include <alibabacloud/models/DeleteUserResponseBody.hpp>
#include <alibabacloud/models/DeleteUserResponse.hpp>
#include <alibabacloud/models/DeleteWorkerRequest.hpp>
#include <alibabacloud/models/DeleteWorkerResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkerResponse.hpp>
#include <alibabacloud/models/GetCredentialRequest.hpp>
#include <alibabacloud/models/GetCredentialResponseBody.hpp>
#include <alibabacloud/models/GetCredentialResponse.hpp>
#include <alibabacloud/models/GetIdentityProviderRequest.hpp>
#include <alibabacloud/models/GetIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/GetIdentityProviderResponse.hpp>
#include <alibabacloud/models/GetInstanceRequest.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetInstanceAsyncTaskRequest.hpp>
#include <alibabacloud/models/GetInstanceAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/GetInstanceAsyncTaskResponse.hpp>
#include <alibabacloud/models/GetInstanceOssMountRamAuthorizeUrlRequest.hpp>
#include <alibabacloud/models/GetInstanceOssMountRamAuthorizeUrlResponseBody.hpp>
#include <alibabacloud/models/GetInstanceOssMountRamAuthorizeUrlResponse.hpp>
#include <alibabacloud/models/GetMcpRequest.hpp>
#include <alibabacloud/models/GetMcpResponseBody.hpp>
#include <alibabacloud/models/GetMcpResponse.hpp>
#include <alibabacloud/models/GetModelInvocationSummaryRequest.hpp>
#include <alibabacloud/models/GetModelInvocationSummaryResponseBody.hpp>
#include <alibabacloud/models/GetModelInvocationSummaryResponse.hpp>
#include <alibabacloud/models/GetModelProviderRequest.hpp>
#include <alibabacloud/models/GetModelProviderResponseBody.hpp>
#include <alibabacloud/models/GetModelProviderResponse.hpp>
#include <alibabacloud/models/GetNatGatewayStatusRequest.hpp>
#include <alibabacloud/models/GetNatGatewayStatusResponseBody.hpp>
#include <alibabacloud/models/GetNatGatewayStatusResponse.hpp>
#include <alibabacloud/models/GetServiceEndpointRequest.hpp>
#include <alibabacloud/models/GetServiceEndpointResponseBody.hpp>
#include <alibabacloud/models/GetServiceEndpointResponse.hpp>
#include <alibabacloud/models/GetTaskStatsSummaryRequest.hpp>
#include <alibabacloud/models/GetTaskStatsSummaryResponseBody.hpp>
#include <alibabacloud/models/GetTaskStatsSummaryResponse.hpp>
#include <alibabacloud/models/GetTeamRequest.hpp>
#include <alibabacloud/models/GetTeamResponseBody.hpp>
#include <alibabacloud/models/GetTeamResponse.hpp>
#include <alibabacloud/models/GetTokenTrendRequest.hpp>
#include <alibabacloud/models/GetTokenTrendResponseBody.hpp>
#include <alibabacloud/models/GetTokenTrendResponse.hpp>
#include <alibabacloud/models/GetToolCallDistributionRequest.hpp>
#include <alibabacloud/models/GetToolCallDistributionResponseBody.hpp>
#include <alibabacloud/models/GetToolCallDistributionResponse.hpp>
#include <alibabacloud/models/GetUserRequest.hpp>
#include <alibabacloud/models/GetUserResponseBody.hpp>
#include <alibabacloud/models/GetUserResponse.hpp>
#include <alibabacloud/models/GetUserPasswordRequest.hpp>
#include <alibabacloud/models/GetUserPasswordResponseBody.hpp>
#include <alibabacloud/models/GetUserPasswordResponse.hpp>
#include <alibabacloud/models/GetWorkerRequest.hpp>
#include <alibabacloud/models/GetWorkerResponseBody.hpp>
#include <alibabacloud/models/GetWorkerResponse.hpp>
#include <alibabacloud/models/GetWorkerBootstrapOptionsRequest.hpp>
#include <alibabacloud/models/GetWorkerBootstrapOptionsResponseBody.hpp>
#include <alibabacloud/models/GetWorkerBootstrapOptionsResponse.hpp>
#include <alibabacloud/models/GetWorkerMaxVersionRequest.hpp>
#include <alibabacloud/models/GetWorkerMaxVersionResponseBody.hpp>
#include <alibabacloud/models/GetWorkerMaxVersionResponse.hpp>
#include <alibabacloud/models/GetWorkerStatsSummaryRequest.hpp>
#include <alibabacloud/models/GetWorkerStatsSummaryResponseBody.hpp>
#include <alibabacloud/models/GetWorkerStatsSummaryResponse.hpp>
#include <alibabacloud/models/ListCredentialsRequest.hpp>
#include <alibabacloud/models/ListCredentialsResponseBody.hpp>
#include <alibabacloud/models/ListCredentialsResponse.hpp>
#include <alibabacloud/models/ListIdentityProvidersRequest.hpp>
#include <alibabacloud/models/ListIdentityProvidersResponseBody.hpp>
#include <alibabacloud/models/ListIdentityProvidersResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListMcpToolsRequest.hpp>
#include <alibabacloud/models/ListMcpToolsResponseBody.hpp>
#include <alibabacloud/models/ListMcpToolsResponse.hpp>
#include <alibabacloud/models/ListMcpsRequest.hpp>
#include <alibabacloud/models/ListMcpsResponseBody.hpp>
#include <alibabacloud/models/ListMcpsResponse.hpp>
#include <alibabacloud/models/ListModelProvidersRequest.hpp>
#include <alibabacloud/models/ListModelProvidersResponseBody.hpp>
#include <alibabacloud/models/ListModelProvidersResponse.hpp>
#include <alibabacloud/models/ListModelsRequest.hpp>
#include <alibabacloud/models/ListModelsResponseBody.hpp>
#include <alibabacloud/models/ListModelsResponse.hpp>
#include <alibabacloud/models/ListServiceEndpointsRequest.hpp>
#include <alibabacloud/models/ListServiceEndpointsResponseBody.hpp>
#include <alibabacloud/models/ListServiceEndpointsResponse.hpp>
#include <alibabacloud/models/ListSslCertsRequest.hpp>
#include <alibabacloud/models/ListSslCertsResponseBody.hpp>
#include <alibabacloud/models/ListSslCertsResponse.hpp>
#include <alibabacloud/models/ListTeamDetailsRequest.hpp>
#include <alibabacloud/models/ListTeamDetailsResponseBody.hpp>
#include <alibabacloud/models/ListTeamDetailsResponse.hpp>
#include <alibabacloud/models/ListTeamTasksRequest.hpp>
#include <alibabacloud/models/ListTeamTasksResponseBody.hpp>
#include <alibabacloud/models/ListTeamTasksResponse.hpp>
#include <alibabacloud/models/ListTeamsRequest.hpp>
#include <alibabacloud/models/ListTeamsResponseBody.hpp>
#include <alibabacloud/models/ListTeamsResponse.hpp>
#include <alibabacloud/models/ListUsersRequest.hpp>
#include <alibabacloud/models/ListUsersResponseBody.hpp>
#include <alibabacloud/models/ListUsersResponse.hpp>
#include <alibabacloud/models/ListWorkerStatsDetailsRequest.hpp>
#include <alibabacloud/models/ListWorkerStatsDetailsResponseBody.hpp>
#include <alibabacloud/models/ListWorkerStatsDetailsResponse.hpp>
#include <alibabacloud/models/ListWorkersRequest.hpp>
#include <alibabacloud/models/ListWorkersShrinkRequest.hpp>
#include <alibabacloud/models/ListWorkersResponseBody.hpp>
#include <alibabacloud/models/ListWorkersResponse.hpp>
#include <alibabacloud/models/PutCmsWorkspaceRequest.hpp>
#include <alibabacloud/models/PutCmsWorkspaceResponseBody.hpp>
#include <alibabacloud/models/PutCmsWorkspaceResponse.hpp>
#include <alibabacloud/models/QueryFeaturesRequest.hpp>
#include <alibabacloud/models/QueryFeaturesResponseBody.hpp>
#include <alibabacloud/models/QueryFeaturesResponse.hpp>
#include <alibabacloud/models/QuerySupportedZonesRequest.hpp>
#include <alibabacloud/models/QuerySupportedZonesResponseBody.hpp>
#include <alibabacloud/models/QuerySupportedZonesResponse.hpp>
#include <alibabacloud/models/ResetUserPasswordRequest.hpp>
#include <alibabacloud/models/ResetUserPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetUserPasswordResponse.hpp>
#include <alibabacloud/models/TestModelProviderRequest.hpp>
#include <alibabacloud/models/TestModelProviderResponseBody.hpp>
#include <alibabacloud/models/TestModelProviderResponse.hpp>
#include <alibabacloud/models/UnbindIdentityProviderRequest.hpp>
#include <alibabacloud/models/UnbindIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/UnbindIdentityProviderResponse.hpp>
#include <alibabacloud/models/UpdateCredentialRequest.hpp>
#include <alibabacloud/models/UpdateCredentialResponseBody.hpp>
#include <alibabacloud/models/UpdateCredentialResponse.hpp>
#include <alibabacloud/models/UpdateIdentityProviderRequest.hpp>
#include <alibabacloud/models/UpdateIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/UpdateIdentityProviderResponse.hpp>
#include <alibabacloud/models/UpdateInstanceRequest.hpp>
#include <alibabacloud/models/UpdateInstanceShrinkRequest.hpp>
#include <alibabacloud/models/UpdateInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceResponse.hpp>
#include <alibabacloud/models/UpdateInstanceAsyncTaskRequest.hpp>
#include <alibabacloud/models/UpdateInstanceAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceAsyncTaskResponse.hpp>
#include <alibabacloud/models/UpdateMcpRequest.hpp>
#include <alibabacloud/models/UpdateMcpShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMcpResponseBody.hpp>
#include <alibabacloud/models/UpdateMcpResponse.hpp>
#include <alibabacloud/models/UpdateModelRequest.hpp>
#include <alibabacloud/models/UpdateModelResponseBody.hpp>
#include <alibabacloud/models/UpdateModelResponse.hpp>
#include <alibabacloud/models/UpdateModelProviderRequest.hpp>
#include <alibabacloud/models/UpdateModelProviderShrinkRequest.hpp>
#include <alibabacloud/models/UpdateModelProviderResponseBody.hpp>
#include <alibabacloud/models/UpdateModelProviderResponse.hpp>
#include <alibabacloud/models/UpdateServiceEndpointRequest.hpp>
#include <alibabacloud/models/UpdateServiceEndpointResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceEndpointResponse.hpp>
#include <alibabacloud/models/UpdateTeamRequest.hpp>
#include <alibabacloud/models/UpdateTeamShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTeamResponseBody.hpp>
#include <alibabacloud/models/UpdateTeamResponse.hpp>
#include <alibabacloud/models/UpdateUserRequest.hpp>
#include <alibabacloud/models/UpdateUserResponseBody.hpp>
#include <alibabacloud/models/UpdateUserResponse.hpp>
#include <alibabacloud/models/UpdateWorkerRequest.hpp>
#include <alibabacloud/models/UpdateWorkerShrinkRequest.hpp>
#include <alibabacloud/models/UpdateWorkerResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkerResponse.hpp>

#endif
