// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_EMASAPPMONITOR20190611MODEL_HPP_
#define ALIBABACLOUD_EMASAPPMONITOR20190611MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ConditionalRule.hpp>
#include <alibabacloud/models/EventFilter.hpp>
#include <alibabacloud/models/EventRule.hpp>
#include <alibabacloud/models/Filter.hpp>
#include <alibabacloud/models/FullSampleItem.hpp>
#include <alibabacloud/models/SampleBase.hpp>
#include <alibabacloud/models/GetErrorRequest.hpp>
#include <alibabacloud/models/GetErrorResponseBody.hpp>
#include <alibabacloud/models/GetErrorResponse.hpp>
#include <alibabacloud/models/GetErrorsRequest.hpp>
#include <alibabacloud/models/GetErrorsShrinkRequest.hpp>
#include <alibabacloud/models/GetErrorsResponseBody.hpp>
#include <alibabacloud/models/GetErrorsResponse.hpp>
#include <alibabacloud/models/GetIssueRequest.hpp>
#include <alibabacloud/models/GetIssueShrinkRequest.hpp>
#include <alibabacloud/models/GetIssueResponseBody.hpp>
#include <alibabacloud/models/GetIssueResponse.hpp>
#include <alibabacloud/models/GetIssuesRequest.hpp>
#include <alibabacloud/models/GetIssuesShrinkRequest.hpp>
#include <alibabacloud/models/GetIssuesResponseBody.hpp>
#include <alibabacloud/models/GetIssuesResponse.hpp>
#include <alibabacloud/models/GetSymbolicFilesRequest.hpp>
#include <alibabacloud/models/GetSymbolicFilesResponseBody.hpp>
#include <alibabacloud/models/GetSymbolicFilesResponse.hpp>
#include <alibabacloud/models/RequestUploadTokenRequest.hpp>
#include <alibabacloud/models/RequestUploadTokenResponseBody.hpp>
#include <alibabacloud/models/RequestUploadTokenResponse.hpp>
#include <alibabacloud/models/SubmitSymbolicRequest.hpp>
#include <alibabacloud/models/SubmitSymbolicResponseBody.hpp>
#include <alibabacloud/models/SubmitSymbolicResponse.hpp>
#include <alibabacloud/models/GetErrorResponseBodyModel.hpp>
#include <alibabacloud/models/GetErrorsRequestFilter.hpp>
#include <alibabacloud/models/GetErrorsRequestTimeRange.hpp>
#include <alibabacloud/models/GetErrorsShrinkRequestTimeRange.hpp>
#include <alibabacloud/models/GetErrorsResponseBodyModelItems.hpp>
#include <alibabacloud/models/GetErrorsResponseBodyModel.hpp>
#include <alibabacloud/models/GetIssueRequestFilter.hpp>
#include <alibabacloud/models/GetIssueRequestTimeRange.hpp>
#include <alibabacloud/models/GetIssueShrinkRequestTimeRange.hpp>
#include <alibabacloud/models/GetIssueResponseBodyModel.hpp>
#include <alibabacloud/models/GetIssuesRequestFilter.hpp>
#include <alibabacloud/models/GetIssuesRequestTimeRange.hpp>
#include <alibabacloud/models/GetIssuesShrinkRequestTimeRange.hpp>
#include <alibabacloud/models/GetIssuesResponseBodyModelItems.hpp>
#include <alibabacloud/models/GetIssuesResponseBodyModel.hpp>
#include <alibabacloud/models/GetSymbolicFilesResponseBodyModelItems.hpp>
#include <alibabacloud/models/GetSymbolicFilesResponseBodyModel.hpp>
#include <alibabacloud/models/RequestUploadTokenResponseBodyModel.hpp>

#endif
