// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_VS20181212MODEL_HPP_
#define ALIBABACLOUD_VS20181212MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddVsPullStreamInfoConfigRequest.hpp>
#include <alibabacloud/models/AddVsPullStreamInfoConfigResponseBody.hpp>
#include <alibabacloud/models/AddVsPullStreamInfoConfigResponse.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesRequest.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesShrinkRequest.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesResponseBody.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesResponse.hpp>
#include <alibabacloud/models/BatchBindDirectoriesRequest.hpp>
#include <alibabacloud/models/BatchBindDirectoriesResponseBody.hpp>
#include <alibabacloud/models/BatchBindDirectoriesResponse.hpp>
#include <alibabacloud/models/BatchBindParentPlatformDevicesRequest.hpp>
#include <alibabacloud/models/BatchBindParentPlatformDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchBindParentPlatformDevicesResponse.hpp>
#include <alibabacloud/models/BatchBindPurchasedDevicesRequest.hpp>
#include <alibabacloud/models/BatchBindPurchasedDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchBindPurchasedDevicesResponse.hpp>
#include <alibabacloud/models/BatchBindTemplateRequest.hpp>
#include <alibabacloud/models/BatchBindTemplateResponseBody.hpp>
#include <alibabacloud/models/BatchBindTemplateResponse.hpp>
#include <alibabacloud/models/BatchBindTemplatesRequest.hpp>
#include <alibabacloud/models/BatchBindTemplatesResponseBody.hpp>
#include <alibabacloud/models/BatchBindTemplatesResponse.hpp>
#include <alibabacloud/models/BatchDeleteDevicesRequest.hpp>
#include <alibabacloud/models/BatchDeleteDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDevicesResponse.hpp>
#include <alibabacloud/models/BatchDeleteVsDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchDeleteVsDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteVsDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchForbidVsStreamRequest.hpp>
#include <alibabacloud/models/BatchForbidVsStreamResponseBody.hpp>
#include <alibabacloud/models/BatchForbidVsStreamResponse.hpp>
#include <alibabacloud/models/BatchResumeVsStreamRequest.hpp>
#include <alibabacloud/models/BatchResumeVsStreamResponseBody.hpp>
#include <alibabacloud/models/BatchResumeVsStreamResponse.hpp>
#include <alibabacloud/models/BatchSetVsDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchSetVsDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchSetVsDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchStartDevicesRequest.hpp>
#include <alibabacloud/models/BatchStartDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchStartDevicesResponse.hpp>
#include <alibabacloud/models/BatchStartStreamsRequest.hpp>
#include <alibabacloud/models/BatchStartStreamsResponseBody.hpp>
#include <alibabacloud/models/BatchStartStreamsResponse.hpp>
#include <alibabacloud/models/BatchStopDevicesRequest.hpp>
#include <alibabacloud/models/BatchStopDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchStopDevicesResponse.hpp>
#include <alibabacloud/models/BatchStopStreamsRequest.hpp>
#include <alibabacloud/models/BatchStopStreamsResponseBody.hpp>
#include <alibabacloud/models/BatchStopStreamsResponse.hpp>
#include <alibabacloud/models/BatchUnbindDirectoriesRequest.hpp>
#include <alibabacloud/models/BatchUnbindDirectoriesResponseBody.hpp>
#include <alibabacloud/models/BatchUnbindDirectoriesResponse.hpp>
#include <alibabacloud/models/BatchUnbindParentPlatformDevicesRequest.hpp>
#include <alibabacloud/models/BatchUnbindParentPlatformDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchUnbindParentPlatformDevicesResponse.hpp>
#include <alibabacloud/models/BatchUnbindPurchasedDevicesRequest.hpp>
#include <alibabacloud/models/BatchUnbindPurchasedDevicesResponseBody.hpp>
#include <alibabacloud/models/BatchUnbindPurchasedDevicesResponse.hpp>
#include <alibabacloud/models/BatchUnbindTemplateRequest.hpp>
#include <alibabacloud/models/BatchUnbindTemplateResponseBody.hpp>
#include <alibabacloud/models/BatchUnbindTemplateResponse.hpp>
#include <alibabacloud/models/BatchUnbindTemplatesRequest.hpp>
#include <alibabacloud/models/BatchUnbindTemplatesResponseBody.hpp>
#include <alibabacloud/models/BatchUnbindTemplatesResponse.hpp>
#include <alibabacloud/models/BindDirectoryRequest.hpp>
#include <alibabacloud/models/BindDirectoryResponseBody.hpp>
#include <alibabacloud/models/BindDirectoryResponse.hpp>
#include <alibabacloud/models/BindParentPlatformDeviceRequest.hpp>
#include <alibabacloud/models/BindParentPlatformDeviceResponseBody.hpp>
#include <alibabacloud/models/BindParentPlatformDeviceResponse.hpp>
#include <alibabacloud/models/BindPurchasedDeviceRequest.hpp>
#include <alibabacloud/models/BindPurchasedDeviceResponseBody.hpp>
#include <alibabacloud/models/BindPurchasedDeviceResponse.hpp>
#include <alibabacloud/models/BindTemplateRequest.hpp>
#include <alibabacloud/models/BindTemplateResponseBody.hpp>
#include <alibabacloud/models/BindTemplateResponse.hpp>
#include <alibabacloud/models/ContinuousAdjustRequest.hpp>
#include <alibabacloud/models/ContinuousAdjustResponseBody.hpp>
#include <alibabacloud/models/ContinuousAdjustResponse.hpp>
#include <alibabacloud/models/ContinuousMoveRequest.hpp>
#include <alibabacloud/models/ContinuousMoveResponseBody.hpp>
#include <alibabacloud/models/ContinuousMoveResponse.hpp>
#include <alibabacloud/models/CreateDeviceRequest.hpp>
#include <alibabacloud/models/CreateDeviceResponseBody.hpp>
#include <alibabacloud/models/CreateDeviceResponse.hpp>
#include <alibabacloud/models/CreateDeviceAlarmRequest.hpp>
#include <alibabacloud/models/CreateDeviceAlarmResponseBody.hpp>
#include <alibabacloud/models/CreateDeviceAlarmResponse.hpp>
#include <alibabacloud/models/CreateDirectoryRequest.hpp>
#include <alibabacloud/models/CreateDirectoryResponseBody.hpp>
#include <alibabacloud/models/CreateDirectoryResponse.hpp>
#include <alibabacloud/models/CreateGroupRequest.hpp>
#include <alibabacloud/models/CreateGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGroupResponse.hpp>
#include <alibabacloud/models/CreateParentPlatformRequest.hpp>
#include <alibabacloud/models/CreateParentPlatformResponseBody.hpp>
#include <alibabacloud/models/CreateParentPlatformResponse.hpp>
#include <alibabacloud/models/CreateRenderingDataPackageRequest.hpp>
#include <alibabacloud/models/CreateRenderingDataPackageResponseBody.hpp>
#include <alibabacloud/models/CreateRenderingDataPackageResponse.hpp>
#include <alibabacloud/models/CreateRenderingInstanceRequest.hpp>
#include <alibabacloud/models/CreateRenderingInstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateRenderingInstanceResponse.hpp>
#include <alibabacloud/models/CreateRenderingInstanceGatewayRequest.hpp>
#include <alibabacloud/models/CreateRenderingInstanceGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateRenderingInstanceGatewayResponse.hpp>
#include <alibabacloud/models/CreateRenderingProjectRequest.hpp>
#include <alibabacloud/models/CreateRenderingProjectShrinkRequest.hpp>
#include <alibabacloud/models/CreateRenderingProjectResponseBody.hpp>
#include <alibabacloud/models/CreateRenderingProjectResponse.hpp>
#include <alibabacloud/models/CreateStreamSnapshotRequest.hpp>
#include <alibabacloud/models/CreateStreamSnapshotResponseBody.hpp>
#include <alibabacloud/models/CreateStreamSnapshotResponse.hpp>
#include <alibabacloud/models/CreateTemplateRequest.hpp>
#include <alibabacloud/models/CreateTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateTemplateResponse.hpp>
#include <alibabacloud/models/DeleteCloudAppRequest.hpp>
#include <alibabacloud/models/DeleteCloudAppResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudAppResponse.hpp>
#include <alibabacloud/models/DeleteDeviceRequest.hpp>
#include <alibabacloud/models/DeleteDeviceResponseBody.hpp>
#include <alibabacloud/models/DeleteDeviceResponse.hpp>
#include <alibabacloud/models/DeleteDirectoryRequest.hpp>
#include <alibabacloud/models/DeleteDirectoryResponseBody.hpp>
#include <alibabacloud/models/DeleteDirectoryResponse.hpp>
#include <alibabacloud/models/DeleteFileRequest.hpp>
#include <alibabacloud/models/DeleteFileResponseBody.hpp>
#include <alibabacloud/models/DeleteFileResponse.hpp>
#include <alibabacloud/models/DeleteGroupRequest.hpp>
#include <alibabacloud/models/DeleteGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGroupResponse.hpp>
#include <alibabacloud/models/DeleteParentPlatformRequest.hpp>
#include <alibabacloud/models/DeleteParentPlatformResponseBody.hpp>
#include <alibabacloud/models/DeleteParentPlatformResponse.hpp>
#include <alibabacloud/models/DeletePresetRequest.hpp>
#include <alibabacloud/models/DeletePresetResponseBody.hpp>
#include <alibabacloud/models/DeletePresetResponse.hpp>
#include <alibabacloud/models/DeletePublicKeyRequest.hpp>
#include <alibabacloud/models/DeletePublicKeyResponseBody.hpp>
#include <alibabacloud/models/DeletePublicKeyResponse.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceGatewayRequest.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceGatewayResponse.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceSettingsRequest.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceSettingsShrinkRequest.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceSettingsResponseBody.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceSettingsResponse.hpp>
#include <alibabacloud/models/DeleteRenderingProjectRequest.hpp>
#include <alibabacloud/models/DeleteRenderingProjectResponseBody.hpp>
#include <alibabacloud/models/DeleteRenderingProjectResponse.hpp>
#include <alibabacloud/models/DeleteTemplateRequest.hpp>
#include <alibabacloud/models/DeleteTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteTemplateResponse.hpp>
#include <alibabacloud/models/DeleteVsPullStreamInfoConfigRequest.hpp>
#include <alibabacloud/models/DeleteVsPullStreamInfoConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteVsPullStreamInfoConfigResponse.hpp>
#include <alibabacloud/models/DeleteVsStreamsNotifyUrlConfigRequest.hpp>
#include <alibabacloud/models/DeleteVsStreamsNotifyUrlConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteVsStreamsNotifyUrlConfigResponse.hpp>
#include <alibabacloud/models/DescribeAccountStatRequest.hpp>
#include <alibabacloud/models/DescribeAccountStatResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountStatResponse.hpp>
#include <alibabacloud/models/DescribeDeviceRequest.hpp>
#include <alibabacloud/models/DescribeDeviceResponseBody.hpp>
#include <alibabacloud/models/DescribeDeviceResponse.hpp>
#include <alibabacloud/models/DescribeDeviceChannelsRequest.hpp>
#include <alibabacloud/models/DescribeDeviceChannelsResponseBody.hpp>
#include <alibabacloud/models/DescribeDeviceChannelsResponse.hpp>
#include <alibabacloud/models/DescribeDeviceGatewayRequest.hpp>
#include <alibabacloud/models/DescribeDeviceGatewayResponseBody.hpp>
#include <alibabacloud/models/DescribeDeviceGatewayResponse.hpp>
#include <alibabacloud/models/DescribeDeviceUrlRequest.hpp>
#include <alibabacloud/models/DescribeDeviceUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeDeviceUrlResponse.hpp>
#include <alibabacloud/models/DescribeDevicesRequest.hpp>
#include <alibabacloud/models/DescribeDevicesResponseBody.hpp>
#include <alibabacloud/models/DescribeDevicesResponse.hpp>
#include <alibabacloud/models/DescribeDirectoriesRequest.hpp>
#include <alibabacloud/models/DescribeDirectoriesResponseBody.hpp>
#include <alibabacloud/models/DescribeDirectoriesResponse.hpp>
#include <alibabacloud/models/DescribeDirectoryRequest.hpp>
#include <alibabacloud/models/DescribeDirectoryResponseBody.hpp>
#include <alibabacloud/models/DescribeDirectoryResponse.hpp>
#include <alibabacloud/models/DescribeGroupRequest.hpp>
#include <alibabacloud/models/DescribeGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupResponse.hpp>
#include <alibabacloud/models/DescribeGroupsRequest.hpp>
#include <alibabacloud/models/DescribeGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupsResponse.hpp>
#include <alibabacloud/models/DescribeParentPlatformRequest.hpp>
#include <alibabacloud/models/DescribeParentPlatformResponseBody.hpp>
#include <alibabacloud/models/DescribeParentPlatformResponse.hpp>
#include <alibabacloud/models/DescribeParentPlatformDevicesRequest.hpp>
#include <alibabacloud/models/DescribeParentPlatformDevicesResponseBody.hpp>
#include <alibabacloud/models/DescribeParentPlatformDevicesResponse.hpp>
#include <alibabacloud/models/DescribeParentPlatformsRequest.hpp>
#include <alibabacloud/models/DescribeParentPlatformsResponseBody.hpp>
#include <alibabacloud/models/DescribeParentPlatformsResponse.hpp>
#include <alibabacloud/models/DescribePresetsRequest.hpp>
#include <alibabacloud/models/DescribePresetsResponseBody.hpp>
#include <alibabacloud/models/DescribePresetsResponse.hpp>
#include <alibabacloud/models/DescribePublishStreamStatusRequest.hpp>
#include <alibabacloud/models/DescribePublishStreamStatusResponseBody.hpp>
#include <alibabacloud/models/DescribePublishStreamStatusResponse.hpp>
#include <alibabacloud/models/DescribePurchasedDeviceRequest.hpp>
#include <alibabacloud/models/DescribePurchasedDeviceResponseBody.hpp>
#include <alibabacloud/models/DescribePurchasedDeviceResponse.hpp>
#include <alibabacloud/models/DescribePurchasedDevicesRequest.hpp>
#include <alibabacloud/models/DescribePurchasedDevicesResponseBody.hpp>
#include <alibabacloud/models/DescribePurchasedDevicesResponse.hpp>
#include <alibabacloud/models/DescribeRecordsRequest.hpp>
#include <alibabacloud/models/DescribeRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordsResponse.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceRequest.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponse.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationRequest.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationResponseBody.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationResponse.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceSettingsRequest.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceSettingsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceSettingsResponseBody.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceSettingsResponse.hpp>
#include <alibabacloud/models/DescribeRenderingSessionRequest.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBody.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponse.hpp>
#include <alibabacloud/models/DescribeStreamRequest.hpp>
#include <alibabacloud/models/DescribeStreamResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamResponse.hpp>
#include <alibabacloud/models/DescribeStreamUrlRequest.hpp>
#include <alibabacloud/models/DescribeStreamUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamUrlResponse.hpp>
#include <alibabacloud/models/DescribeStreamVodListRequest.hpp>
#include <alibabacloud/models/DescribeStreamVodListResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamVodListResponse.hpp>
#include <alibabacloud/models/DescribeStreamsRequest.hpp>
#include <alibabacloud/models/DescribeStreamsResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamsResponse.hpp>
#include <alibabacloud/models/DescribeTemplateRequest.hpp>
#include <alibabacloud/models/DescribeTemplateResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplateResponse.hpp>
#include <alibabacloud/models/DescribeTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeVodStreamUrlRequest.hpp>
#include <alibabacloud/models/DescribeVodStreamUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeVodStreamUrlResponse.hpp>
#include <alibabacloud/models/DescribeVsCertificateDetailRequest.hpp>
#include <alibabacloud/models/DescribeVsCertificateDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVsCertificateDetailResponse.hpp>
#include <alibabacloud/models/DescribeVsCertificateListRequest.hpp>
#include <alibabacloud/models/DescribeVsCertificateListResponseBody.hpp>
#include <alibabacloud/models/DescribeVsCertificateListResponse.hpp>
#include <alibabacloud/models/DescribeVsDevicesDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDevicesDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDevicesDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainCertificateInfoRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainCertificateInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainCertificateInfoResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainConfigsRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainConfigsResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainPvDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainPvDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainPvDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainPvUvDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainPvUvDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainPvUvDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainRecordDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainRecordDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainRecordDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainRegionDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainRegionDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainRegionDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainReqBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainReqBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainReqBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainReqTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainReqTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainReqTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainSnapshotDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainSnapshotDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainSnapshotDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeVsDomainUvDataRequest.hpp>
#include <alibabacloud/models/DescribeVsDomainUvDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsDomainUvDataResponse.hpp>
#include <alibabacloud/models/DescribeVsPullStreamInfoConfigRequest.hpp>
#include <alibabacloud/models/DescribeVsPullStreamInfoConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeVsPullStreamInfoConfigResponse.hpp>
#include <alibabacloud/models/DescribeVsStreamsNotifyUrlConfigRequest.hpp>
#include <alibabacloud/models/DescribeVsStreamsNotifyUrlConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeVsStreamsNotifyUrlConfigResponse.hpp>
#include <alibabacloud/models/DescribeVsStreamsOnlineListRequest.hpp>
#include <alibabacloud/models/DescribeVsStreamsOnlineListResponseBody.hpp>
#include <alibabacloud/models/DescribeVsStreamsOnlineListResponse.hpp>
#include <alibabacloud/models/DescribeVsStreamsPublishListRequest.hpp>
#include <alibabacloud/models/DescribeVsStreamsPublishListResponseBody.hpp>
#include <alibabacloud/models/DescribeVsStreamsPublishListResponse.hpp>
#include <alibabacloud/models/DescribeVsTopDomainsByFlowRequest.hpp>
#include <alibabacloud/models/DescribeVsTopDomainsByFlowResponseBody.hpp>
#include <alibabacloud/models/DescribeVsTopDomainsByFlowResponse.hpp>
#include <alibabacloud/models/DescribeVsUpPeakPublishStreamDataRequest.hpp>
#include <alibabacloud/models/DescribeVsUpPeakPublishStreamDataResponseBody.hpp>
#include <alibabacloud/models/DescribeVsUpPeakPublishStreamDataResponse.hpp>
#include <alibabacloud/models/DescribeVsUserResourcePackageRequest.hpp>
#include <alibabacloud/models/DescribeVsUserResourcePackageResponseBody.hpp>
#include <alibabacloud/models/DescribeVsUserResourcePackageResponse.hpp>
#include <alibabacloud/models/DescribeVsVerifyContentRequest.hpp>
#include <alibabacloud/models/DescribeVsVerifyContentResponseBody.hpp>
#include <alibabacloud/models/DescribeVsVerifyContentResponse.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesRequest.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesShrinkRequest.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesResponseBody.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesResponse.hpp>
#include <alibabacloud/models/ForbidVsStreamRequest.hpp>
#include <alibabacloud/models/ForbidVsStreamResponseBody.hpp>
#include <alibabacloud/models/ForbidVsStreamResponse.hpp>
#include <alibabacloud/models/GetRenderingInstanceCommandsStatusRequest.hpp>
#include <alibabacloud/models/GetRenderingInstanceCommandsStatusResponseBody.hpp>
#include <alibabacloud/models/GetRenderingInstanceCommandsStatusResponse.hpp>
#include <alibabacloud/models/GetRenderingInstanceStreamingInfoRequest.hpp>
#include <alibabacloud/models/GetRenderingInstanceStreamingInfoResponseBody.hpp>
#include <alibabacloud/models/GetRenderingInstanceStreamingInfoResponse.hpp>
#include <alibabacloud/models/GetRenderingProjectInstanceStateMetricsRequest.hpp>
#include <alibabacloud/models/GetRenderingProjectInstanceStateMetricsResponseBody.hpp>
#include <alibabacloud/models/GetRenderingProjectInstanceStateMetricsResponse.hpp>
#include <alibabacloud/models/GotoPresetRequest.hpp>
#include <alibabacloud/models/GotoPresetResponseBody.hpp>
#include <alibabacloud/models/GotoPresetResponse.hpp>
#include <alibabacloud/models/InstallCloudAppRequest.hpp>
#include <alibabacloud/models/InstallCloudAppShrinkRequest.hpp>
#include <alibabacloud/models/InstallCloudAppResponseBody.hpp>
#include <alibabacloud/models/InstallCloudAppResponse.hpp>
#include <alibabacloud/models/ListCloudAppInstallationsRequest.hpp>
#include <alibabacloud/models/ListCloudAppInstallationsResponseBody.hpp>
#include <alibabacloud/models/ListCloudAppInstallationsResponse.hpp>
#include <alibabacloud/models/ListCloudAppPatchesRequest.hpp>
#include <alibabacloud/models/ListCloudAppPatchesResponseBody.hpp>
#include <alibabacloud/models/ListCloudAppPatchesResponse.hpp>
#include <alibabacloud/models/ListCloudAppsRequest.hpp>
#include <alibabacloud/models/ListCloudAppsResponseBody.hpp>
#include <alibabacloud/models/ListCloudAppsResponse.hpp>
#include <alibabacloud/models/ListFilePushStatusesRequest.hpp>
#include <alibabacloud/models/ListFilePushStatusesResponseBody.hpp>
#include <alibabacloud/models/ListFilePushStatusesResponse.hpp>
#include <alibabacloud/models/ListFilesRequest.hpp>
#include <alibabacloud/models/ListFilesResponseBody.hpp>
#include <alibabacloud/models/ListFilesResponse.hpp>
#include <alibabacloud/models/ListPublicKeysRequest.hpp>
#include <alibabacloud/models/ListPublicKeysResponseBody.hpp>
#include <alibabacloud/models/ListPublicKeysResponse.hpp>
#include <alibabacloud/models/ListRenderingDataPackagesRequest.hpp>
#include <alibabacloud/models/ListRenderingDataPackagesResponseBody.hpp>
#include <alibabacloud/models/ListRenderingDataPackagesResponse.hpp>
#include <alibabacloud/models/ListRenderingInstanceGatewayRequest.hpp>
#include <alibabacloud/models/ListRenderingInstanceGatewayResponseBody.hpp>
#include <alibabacloud/models/ListRenderingInstanceGatewayResponse.hpp>
#include <alibabacloud/models/ListRenderingInstancesRequest.hpp>
#include <alibabacloud/models/ListRenderingInstancesResponseBody.hpp>
#include <alibabacloud/models/ListRenderingInstancesResponse.hpp>
#include <alibabacloud/models/ListRenderingProjectInstancesRequest.hpp>
#include <alibabacloud/models/ListRenderingProjectInstancesResponseBody.hpp>
#include <alibabacloud/models/ListRenderingProjectInstancesResponse.hpp>
#include <alibabacloud/models/ListRenderingProjectsRequest.hpp>
#include <alibabacloud/models/ListRenderingProjectsResponseBody.hpp>
#include <alibabacloud/models/ListRenderingProjectsResponse.hpp>
#include <alibabacloud/models/ListRenderingSessionsRequest.hpp>
#include <alibabacloud/models/ListRenderingSessionsResponseBody.hpp>
#include <alibabacloud/models/ListRenderingSessionsResponse.hpp>
#include <alibabacloud/models/ManageLoginRequest.hpp>
#include <alibabacloud/models/ManageLoginResponseBody.hpp>
#include <alibabacloud/models/ManageLoginResponse.hpp>
#include <alibabacloud/models/ModifyDeviceRequest.hpp>
#include <alibabacloud/models/ModifyDeviceResponseBody.hpp>
#include <alibabacloud/models/ModifyDeviceResponse.hpp>
#include <alibabacloud/models/ModifyDeviceAlarmRequest.hpp>
#include <alibabacloud/models/ModifyDeviceAlarmResponseBody.hpp>
#include <alibabacloud/models/ModifyDeviceAlarmResponse.hpp>
#include <alibabacloud/models/ModifyDeviceCaptureRequest.hpp>
#include <alibabacloud/models/ModifyDeviceCaptureResponseBody.hpp>
#include <alibabacloud/models/ModifyDeviceCaptureResponse.hpp>
#include <alibabacloud/models/ModifyDeviceChannelsRequest.hpp>
#include <alibabacloud/models/ModifyDeviceChannelsResponseBody.hpp>
#include <alibabacloud/models/ModifyDeviceChannelsResponse.hpp>
#include <alibabacloud/models/ModifyDirectoryRequest.hpp>
#include <alibabacloud/models/ModifyDirectoryResponseBody.hpp>
#include <alibabacloud/models/ModifyDirectoryResponse.hpp>
#include <alibabacloud/models/ModifyGroupRequest.hpp>
#include <alibabacloud/models/ModifyGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyGroupResponse.hpp>
#include <alibabacloud/models/ModifyParentPlatformRequest.hpp>
#include <alibabacloud/models/ModifyParentPlatformResponseBody.hpp>
#include <alibabacloud/models/ModifyParentPlatformResponse.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceRequest.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceResponse.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyRenderingInstanceBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyTemplateRequest.hpp>
#include <alibabacloud/models/ModifyTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyTemplateResponse.hpp>
#include <alibabacloud/models/OpenVsServiceResponseBody.hpp>
#include <alibabacloud/models/OpenVsServiceResponse.hpp>
#include <alibabacloud/models/PushFileRequest.hpp>
#include <alibabacloud/models/PushFileResponseBody.hpp>
#include <alibabacloud/models/PushFileResponse.hpp>
#include <alibabacloud/models/RebootRenderingInstanceRequest.hpp>
#include <alibabacloud/models/RebootRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/RebootRenderingInstanceResponse.hpp>
#include <alibabacloud/models/RebootRenderingServerRequest.hpp>
#include <alibabacloud/models/RebootRenderingServerShrinkRequest.hpp>
#include <alibabacloud/models/RebootRenderingServerResponseBody.hpp>
#include <alibabacloud/models/RebootRenderingServerResponse.hpp>
#include <alibabacloud/models/RecoverRenderingDataPackageRequest.hpp>
#include <alibabacloud/models/RecoverRenderingDataPackageResponseBody.hpp>
#include <alibabacloud/models/RecoverRenderingDataPackageResponse.hpp>
#include <alibabacloud/models/RefreshRenderingInstanceStreamingRequest.hpp>
#include <alibabacloud/models/RefreshRenderingInstanceStreamingShrinkRequest.hpp>
#include <alibabacloud/models/RefreshRenderingInstanceStreamingResponseBody.hpp>
#include <alibabacloud/models/RefreshRenderingInstanceStreamingResponse.hpp>
#include <alibabacloud/models/ReleaseRenderingDataPackageRequest.hpp>
#include <alibabacloud/models/ReleaseRenderingDataPackageResponseBody.hpp>
#include <alibabacloud/models/ReleaseRenderingDataPackageResponse.hpp>
#include <alibabacloud/models/ReleaseRenderingInstanceRequest.hpp>
#include <alibabacloud/models/ReleaseRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseRenderingInstanceResponse.hpp>
#include <alibabacloud/models/RenewRenderingInstanceRequest.hpp>
#include <alibabacloud/models/RenewRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewRenderingInstanceResponse.hpp>
#include <alibabacloud/models/ResetRenderingInstanceRequest.hpp>
#include <alibabacloud/models/ResetRenderingInstanceResponseBody.hpp>
#include <alibabacloud/models/ResetRenderingInstanceResponse.hpp>
#include <alibabacloud/models/ResumeVsStreamRequest.hpp>
#include <alibabacloud/models/ResumeVsStreamResponseBody.hpp>
#include <alibabacloud/models/ResumeVsStreamResponse.hpp>
#include <alibabacloud/models/SendRenderingInstanceCommandsRequest.hpp>
#include <alibabacloud/models/SendRenderingInstanceCommandsResponseBody.hpp>
#include <alibabacloud/models/SendRenderingInstanceCommandsResponse.hpp>
#include <alibabacloud/models/SetPresetRequest.hpp>
#include <alibabacloud/models/SetPresetResponseBody.hpp>
#include <alibabacloud/models/SetPresetResponse.hpp>
#include <alibabacloud/models/SetVsDomainCertificateRequest.hpp>
#include <alibabacloud/models/SetVsDomainCertificateResponseBody.hpp>
#include <alibabacloud/models/SetVsDomainCertificateResponse.hpp>
#include <alibabacloud/models/SetVsStreamsNotifyUrlConfigRequest.hpp>
#include <alibabacloud/models/SetVsStreamsNotifyUrlConfigResponseBody.hpp>
#include <alibabacloud/models/SetVsStreamsNotifyUrlConfigResponse.hpp>
#include <alibabacloud/models/StartDeviceRequest.hpp>
#include <alibabacloud/models/StartDeviceResponseBody.hpp>
#include <alibabacloud/models/StartDeviceResponse.hpp>
#include <alibabacloud/models/StartParentPlatformRequest.hpp>
#include <alibabacloud/models/StartParentPlatformResponseBody.hpp>
#include <alibabacloud/models/StartParentPlatformResponse.hpp>
#include <alibabacloud/models/StartPublishStreamRequest.hpp>
#include <alibabacloud/models/StartPublishStreamResponseBody.hpp>
#include <alibabacloud/models/StartPublishStreamResponse.hpp>
#include <alibabacloud/models/StartRecordStreamRequest.hpp>
#include <alibabacloud/models/StartRecordStreamResponseBody.hpp>
#include <alibabacloud/models/StartRecordStreamResponse.hpp>
#include <alibabacloud/models/StartRenderingSessionRequest.hpp>
#include <alibabacloud/models/StartRenderingSessionShrinkRequest.hpp>
#include <alibabacloud/models/StartRenderingSessionResponseBody.hpp>
#include <alibabacloud/models/StartRenderingSessionResponse.hpp>
#include <alibabacloud/models/StartStreamRequest.hpp>
#include <alibabacloud/models/StartStreamResponseBody.hpp>
#include <alibabacloud/models/StartStreamResponse.hpp>
#include <alibabacloud/models/StartTransferStreamRequest.hpp>
#include <alibabacloud/models/StartTransferStreamResponseBody.hpp>
#include <alibabacloud/models/StartTransferStreamResponse.hpp>
#include <alibabacloud/models/StopAdjustRequest.hpp>
#include <alibabacloud/models/StopAdjustResponseBody.hpp>
#include <alibabacloud/models/StopAdjustResponse.hpp>
#include <alibabacloud/models/StopDeviceRequest.hpp>
#include <alibabacloud/models/StopDeviceResponseBody.hpp>
#include <alibabacloud/models/StopDeviceResponse.hpp>
#include <alibabacloud/models/StopMoveRequest.hpp>
#include <alibabacloud/models/StopMoveResponseBody.hpp>
#include <alibabacloud/models/StopMoveResponse.hpp>
#include <alibabacloud/models/StopPublishStreamRequest.hpp>
#include <alibabacloud/models/StopPublishStreamResponseBody.hpp>
#include <alibabacloud/models/StopPublishStreamResponse.hpp>
#include <alibabacloud/models/StopRecordStreamRequest.hpp>
#include <alibabacloud/models/StopRecordStreamResponseBody.hpp>
#include <alibabacloud/models/StopRecordStreamResponse.hpp>
#include <alibabacloud/models/StopRenderingSessionRequest.hpp>
#include <alibabacloud/models/StopRenderingSessionResponseBody.hpp>
#include <alibabacloud/models/StopRenderingSessionResponse.hpp>
#include <alibabacloud/models/StopStreamRequest.hpp>
#include <alibabacloud/models/StopStreamResponseBody.hpp>
#include <alibabacloud/models/StopStreamResponse.hpp>
#include <alibabacloud/models/StopTransferStreamRequest.hpp>
#include <alibabacloud/models/StopTransferStreamResponseBody.hpp>
#include <alibabacloud/models/StopTransferStreamResponse.hpp>
#include <alibabacloud/models/SyncCatalogsRequest.hpp>
#include <alibabacloud/models/SyncCatalogsResponseBody.hpp>
#include <alibabacloud/models/SyncCatalogsResponse.hpp>
#include <alibabacloud/models/UnbindDirectoryRequest.hpp>
#include <alibabacloud/models/UnbindDirectoryResponseBody.hpp>
#include <alibabacloud/models/UnbindDirectoryResponse.hpp>
#include <alibabacloud/models/UnbindParentPlatformDeviceRequest.hpp>
#include <alibabacloud/models/UnbindParentPlatformDeviceResponseBody.hpp>
#include <alibabacloud/models/UnbindParentPlatformDeviceResponse.hpp>
#include <alibabacloud/models/UnbindPurchasedDeviceRequest.hpp>
#include <alibabacloud/models/UnbindPurchasedDeviceResponseBody.hpp>
#include <alibabacloud/models/UnbindPurchasedDeviceResponse.hpp>
#include <alibabacloud/models/UnbindTemplateRequest.hpp>
#include <alibabacloud/models/UnbindTemplateResponseBody.hpp>
#include <alibabacloud/models/UnbindTemplateResponse.hpp>
#include <alibabacloud/models/UninstallCloudAppRequest.hpp>
#include <alibabacloud/models/UninstallCloudAppShrinkRequest.hpp>
#include <alibabacloud/models/UninstallCloudAppResponseBody.hpp>
#include <alibabacloud/models/UninstallCloudAppResponse.hpp>
#include <alibabacloud/models/UnlockDeviceRequest.hpp>
#include <alibabacloud/models/UnlockDeviceResponseBody.hpp>
#include <alibabacloud/models/UnlockDeviceResponse.hpp>
#include <alibabacloud/models/UpdateCloudAppInfoRequest.hpp>
#include <alibabacloud/models/UpdateCloudAppInfoShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudAppInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudAppInfoResponse.hpp>
#include <alibabacloud/models/UpdateFileInfoRequest.hpp>
#include <alibabacloud/models/UpdateFileInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateFileInfoResponse.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationRequest.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationResponseBody.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationResponse.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceSettingsRequest.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceSettingsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceSettingsResponse.hpp>
#include <alibabacloud/models/UpdateRenderingProjectRequest.hpp>
#include <alibabacloud/models/UpdateRenderingProjectShrinkRequest.hpp>
#include <alibabacloud/models/UpdateRenderingProjectResponseBody.hpp>
#include <alibabacloud/models/UpdateRenderingProjectResponse.hpp>
#include <alibabacloud/models/UpdateVsPullStreamInfoConfigRequest.hpp>
#include <alibabacloud/models/UpdateVsPullStreamInfoConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateVsPullStreamInfoConfigResponse.hpp>
#include <alibabacloud/models/UploadCloudAppRequest.hpp>
#include <alibabacloud/models/UploadCloudAppResponseBody.hpp>
#include <alibabacloud/models/UploadCloudAppResponse.hpp>
#include <alibabacloud/models/UploadFileRequest.hpp>
#include <alibabacloud/models/UploadFileResponseBody.hpp>
#include <alibabacloud/models/UploadFileResponse.hpp>
#include <alibabacloud/models/UploadPublicKeyRequest.hpp>
#include <alibabacloud/models/UploadPublicKeyResponseBody.hpp>
#include <alibabacloud/models/UploadPublicKeyResponse.hpp>
#include <alibabacloud/models/VerifyVsDomainOwnerRequest.hpp>
#include <alibabacloud/models/VerifyVsDomainOwnerResponseBody.hpp>
#include <alibabacloud/models/VerifyVsDomainOwnerResponse.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesResponseBodyFailedInstances.hpp>
#include <alibabacloud/models/AssociateRenderingProjectInstancesResponseBodySuccessInstances.hpp>
#include <alibabacloud/models/BatchBindDirectoriesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchBindParentPlatformDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchBindPurchasedDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchBindTemplateResponseBodyBindings.hpp>
#include <alibabacloud/models/BatchBindTemplatesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchDeleteDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchForbidVsStreamResponseBodyForbidResultForbidResultInfoChannels.hpp>
#include <alibabacloud/models/BatchForbidVsStreamResponseBodyForbidResultForbidResultInfo.hpp>
#include <alibabacloud/models/BatchForbidVsStreamResponseBodyForbidResult.hpp>
#include <alibabacloud/models/BatchResumeVsStreamResponseBodyResumeResultResumeResultInfoChannels.hpp>
#include <alibabacloud/models/BatchResumeVsStreamResponseBodyResumeResultResumeResultInfo.hpp>
#include <alibabacloud/models/BatchResumeVsStreamResponseBodyResumeResult.hpp>
#include <alibabacloud/models/BatchStartDevicesResponseBodyResultsStreams.hpp>
#include <alibabacloud/models/BatchStartDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchStartStreamsResponseBodyResults.hpp>
#include <alibabacloud/models/BatchStopDevicesResponseBodyResultsStreams.hpp>
#include <alibabacloud/models/BatchStopDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchStopStreamsResponseBodyResults.hpp>
#include <alibabacloud/models/BatchUnbindDirectoriesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchUnbindParentPlatformDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchUnbindPurchasedDevicesResponseBodyResults.hpp>
#include <alibabacloud/models/BatchUnbindTemplateResponseBodyBindings.hpp>
#include <alibabacloud/models/BatchUnbindTemplatesResponseBodyResults.hpp>
#include <alibabacloud/models/CreateRenderingInstanceRequestAttributes.hpp>
#include <alibabacloud/models/CreateRenderingInstanceRequestClientInfo.hpp>
#include <alibabacloud/models/CreateRenderingProjectRequestSessionAttribs.hpp>
#include <alibabacloud/models/DeleteRenderingInstanceConfigurationRequestConfiguration.hpp>
#include <alibabacloud/models/DescribeDeviceResponseBodyDirectory.hpp>
#include <alibabacloud/models/DescribeDeviceResponseBodyStats.hpp>
#include <alibabacloud/models/DescribeDeviceChannelsResponseBodyChannels.hpp>
#include <alibabacloud/models/DescribeDevicesResponseBodyDevicesDirectory.hpp>
#include <alibabacloud/models/DescribeDevicesResponseBodyDevicesStats.hpp>
#include <alibabacloud/models/DescribeDevicesResponseBodyDevices.hpp>
#include <alibabacloud/models/DescribeDirectoriesResponseBodyDirectories.hpp>
#include <alibabacloud/models/DescribeGroupResponseBodyStats.hpp>
#include <alibabacloud/models/DescribeGroupsResponseBodyGroupsStats.hpp>
#include <alibabacloud/models/DescribeGroupsResponseBodyGroups.hpp>
#include <alibabacloud/models/DescribeParentPlatformDevicesResponseBodyDevices.hpp>
#include <alibabacloud/models/DescribeParentPlatformsResponseBodyPlatforms.hpp>
#include <alibabacloud/models/DescribePresetsResponseBodyPresets.hpp>
#include <alibabacloud/models/DescribePurchasedDevicesResponseBodyDevices.hpp>
#include <alibabacloud/models/DescribeRecordsResponseBodyRecords.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyAdditionalIngressesPortMappings.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyAdditionalIngresses.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyConfigInfoConfigurationAttributes.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyConfigInfoConfiguration.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyConfigInfoNetworkConfig.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyConfigInfo.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyPortMappings.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyRenderingStatus.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodyResourceAttributes.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceResponseBodySystemInfo.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationRequestConfiguration.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationResponseBodyConfigurationAttributes.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceConfigurationResponseBodyConfiguration.hpp>
#include <alibabacloud/models/DescribeRenderingInstanceSettingsResponseBodySettings.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBodyAdditionalIngressesPortMappings.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBodyAdditionalIngresses.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBodyLocation.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBodyPortMappings.hpp>
#include <alibabacloud/models/DescribeRenderingSessionResponseBodyStateInfo.hpp>
#include <alibabacloud/models/DescribeStreamVodListResponseBodyRecords.hpp>
#include <alibabacloud/models/DescribeStreamsResponseBodyStreams.hpp>
#include <alibabacloud/models/DescribeTemplateResponseBodyTransConfigs.hpp>
#include <alibabacloud/models/DescribeTemplatesResponseBodyTemplatesTransConfigs.hpp>
#include <alibabacloud/models/DescribeTemplatesResponseBodyTemplates.hpp>
#include <alibabacloud/models/DescribeVsCertificateListResponseBodyCertificateListModelCertList.hpp>
#include <alibabacloud/models/DescribeVsCertificateListResponseBodyCertificateListModel.hpp>
#include <alibabacloud/models/DescribeVsDevicesDataResponseBodyDevicesDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDevicesDataResponseBodyDevicesDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainBpsDataResponseBodyBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainBpsDataResponseBodyBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainCertificateInfoResponseBodyCertInfosCertInfo.hpp>
#include <alibabacloud/models/DescribeVsDomainCertificateInfoResponseBodyCertInfos.hpp>
#include <alibabacloud/models/DescribeVsDomainConfigsResponseBodyDomainConfigsFunctionArgs.hpp>
#include <alibabacloud/models/DescribeVsDomainConfigsResponseBodyDomainConfigs.hpp>
#include <alibabacloud/models/DescribeVsDomainDetailResponseBodyDomainConfig.hpp>
#include <alibabacloud/models/DescribeVsDomainPvDataResponseBodyPvDataIntervalUsageData.hpp>
#include <alibabacloud/models/DescribeVsDomainPvDataResponseBodyPvDataInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainPvUvDataResponseBodyPvUvDataInfosPvUvDataInfo.hpp>
#include <alibabacloud/models/DescribeVsDomainPvUvDataResponseBodyPvUvDataInfos.hpp>
#include <alibabacloud/models/DescribeVsDomainRecordDataResponseBodyRecordDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainRecordDataResponseBodyRecordDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainRegionDataResponseBodyValueRegionProportionData.hpp>
#include <alibabacloud/models/DescribeVsDomainRegionDataResponseBodyValue.hpp>
#include <alibabacloud/models/DescribeVsDomainReqBpsDataResponseBodyReqBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainReqBpsDataResponseBodyReqBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainReqTrafficDataResponseBodyReqTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainReqTrafficDataResponseBodyReqTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainSnapshotDataResponseBodySnapshotDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainSnapshotDataResponseBodySnapshotDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainTrafficDataResponseBodyTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeVsDomainTrafficDataResponseBodyTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeVsDomainUvDataResponseBodyUvDataIntervalUsageData.hpp>
#include <alibabacloud/models/DescribeVsDomainUvDataResponseBodyUvDataInterval.hpp>
#include <alibabacloud/models/DescribeVsPullStreamInfoConfigResponseBodyLiveAppRecordListLiveAppRecord.hpp>
#include <alibabacloud/models/DescribeVsPullStreamInfoConfigResponseBodyLiveAppRecordList.hpp>
#include <alibabacloud/models/DescribeVsStreamsNotifyUrlConfigResponseBodyLiveStreamsNotifyConfig.hpp>
#include <alibabacloud/models/DescribeVsStreamsOnlineListResponseBodyOnlineInfoLiveStreamOnlineInfo.hpp>
#include <alibabacloud/models/DescribeVsStreamsOnlineListResponseBodyOnlineInfo.hpp>
#include <alibabacloud/models/DescribeVsStreamsPublishListResponseBodyPublishInfoLiveStreamPublishInfo.hpp>
#include <alibabacloud/models/DescribeVsStreamsPublishListResponseBodyPublishInfo.hpp>
#include <alibabacloud/models/DescribeVsTopDomainsByFlowResponseBodyTopDomainsTopDomain.hpp>
#include <alibabacloud/models/DescribeVsTopDomainsByFlowResponseBodyTopDomains.hpp>
#include <alibabacloud/models/DescribeVsUpPeakPublishStreamDataResponseBodyDescribeVsUpPeakPublishStreamDatasDescribeVsUpPeakPublishStreamData.hpp>
#include <alibabacloud/models/DescribeVsUpPeakPublishStreamDataResponseBodyDescribeVsUpPeakPublishStreamDatas.hpp>
#include <alibabacloud/models/DescribeVsUserResourcePackageResponseBodyResourcePackageInfosResourcePackageInfo.hpp>
#include <alibabacloud/models/DescribeVsUserResourcePackageResponseBodyResourcePackageInfos.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesResponseBodyFailedInstances.hpp>
#include <alibabacloud/models/DisassociateRenderingProjectInstancesResponseBodySuccessInstances.hpp>
#include <alibabacloud/models/GetRenderingProjectInstanceStateMetricsResponseBodyStateMetrics.hpp>
#include <alibabacloud/models/InstallCloudAppResponseBodyFailedInstances.hpp>
#include <alibabacloud/models/InstallCloudAppResponseBodySuccessInstances.hpp>
#include <alibabacloud/models/ListCloudAppInstallationsResponseBodyInstallationInfos.hpp>
#include <alibabacloud/models/ListCloudAppPatchesResponseBodyPatches.hpp>
#include <alibabacloud/models/ListCloudAppsResponseBodyCloudApps.hpp>
#include <alibabacloud/models/ListFilePushStatusesResponseBodyPushStatuses.hpp>
#include <alibabacloud/models/ListFilesResponseBodyFiles.hpp>
#include <alibabacloud/models/ListPublicKeysResponseBodyPublicKeys.hpp>
#include <alibabacloud/models/ListRenderingDataPackagesResponseBodyDataPackages.hpp>
#include <alibabacloud/models/ListRenderingInstanceGatewayResponseBodyGatewayConfigurationInfos.hpp>
#include <alibabacloud/models/ListRenderingInstancesResponseBodyRenderingInstances.hpp>
#include <alibabacloud/models/ListRenderingProjectInstancesResponseBodyRenderingInstancesStateInfo.hpp>
#include <alibabacloud/models/ListRenderingProjectInstancesResponseBodyRenderingInstances.hpp>
#include <alibabacloud/models/ListRenderingProjectsResponseBodyProjectsSessionAttribs.hpp>
#include <alibabacloud/models/ListRenderingProjectsResponseBodyProjects.hpp>
#include <alibabacloud/models/ListRenderingSessionsResponseBodySessions.hpp>
#include <alibabacloud/models/ManageLoginResponseBodyLoginInfo.hpp>
#include <alibabacloud/models/RebootRenderingServerResponseBodyFailedInstances.hpp>
#include <alibabacloud/models/RebootRenderingServerResponseBodySuccessInstances.hpp>
#include <alibabacloud/models/RefreshRenderingInstanceStreamingRequestClientInfo.hpp>
#include <alibabacloud/models/StartRenderingSessionRequestClientParams.hpp>
#include <alibabacloud/models/StartRenderingSessionResponseBodyLocation.hpp>
#include <alibabacloud/models/StartRenderingSessionResponseBodyPortMappings.hpp>
#include <alibabacloud/models/StartRenderingSessionResponseBodyStateInfo.hpp>
#include <alibabacloud/models/UninstallCloudAppResponseBodyFailedInstances.hpp>
#include <alibabacloud/models/UninstallCloudAppResponseBodySuccessInstances.hpp>
#include <alibabacloud/models/UpdateCloudAppInfoRequestPatch.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationRequestConfigurationAttributes.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceConfigurationRequestConfiguration.hpp>
#include <alibabacloud/models/UpdateRenderingInstanceSettingsRequestSettings.hpp>
#include <alibabacloud/models/UpdateRenderingProjectRequestSessionAttribs.hpp>

#endif
