// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DELETELOGSTASHREQUEST_HPP_
#define ALIBABACLOUD_MODELS_DELETELOGSTASHREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Elasticsearch20170613
{
namespace Models
{
  class DeleteLogstashRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DeleteLogstashRequest& obj) { 
      DARABONBA_PTR_TO_JSON(clientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(deleteType, deleteType_);
    };
    friend void from_json(const Darabonba::Json& j, DeleteLogstashRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(clientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(deleteType, deleteType_);
    };
    DeleteLogstashRequest() = default ;
    DeleteLogstashRequest(const DeleteLogstashRequest &) = default ;
    DeleteLogstashRequest(DeleteLogstashRequest &&) = default ;
    DeleteLogstashRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DeleteLogstashRequest() = default ;
    DeleteLogstashRequest& operator=(const DeleteLogstashRequest &) = default ;
    DeleteLogstashRequest& operator=(DeleteLogstashRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->clientToken_ == nullptr
        && this->deleteType_ == nullptr; };
    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline DeleteLogstashRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // deleteType Field Functions 
    bool hasDeleteType() const { return this->deleteType_ != nullptr;};
    void deleteDeleteType() { this->deleteType_ = nullptr;};
    inline string getDeleteType() const { DARABONBA_PTR_GET_DEFAULT(deleteType_, "") };
    inline DeleteLogstashRequest& setDeleteType(string deleteType) { DARABONBA_PTR_SET_VALUE(deleteType_, deleteType) };


  protected:
    // A unique token generated by the client to ensure the idempotence of the request. The value of this parameter must be unique across different requests and can contain a maximum of 64 ASCII characters.
    shared_ptr<string> clientToken_ {};
    // The release type. Valid values:
    // 
    // - immediate: immediately deletes the instance. After deletion, the system permanently clears all data, and the instance no longer appears in the instance list.
    // - protective: freezes the instance for 24 hours before permanently clearing the data. During this period, the instance is still displayed in the instance list. You can choose to [recover the instance](https://help.aliyun.com/document_detail/202205.html) or [immediately release it](https://help.aliyun.com/document_detail/160591.html).
    shared_ptr<string> deleteType_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Elasticsearch20170613
#endif
