// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DELETESNAPSHOTREPOREQUEST_HPP_
#define ALIBABACLOUD_MODELS_DELETESNAPSHOTREPOREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Elasticsearch20170613
{
namespace Models
{
  class DeleteSnapshotRepoRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DeleteSnapshotRepoRequest& obj) { 
      DARABONBA_PTR_TO_JSON(clientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(repoPath, repoPath_);
    };
    friend void from_json(const Darabonba::Json& j, DeleteSnapshotRepoRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(clientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(repoPath, repoPath_);
    };
    DeleteSnapshotRepoRequest() = default ;
    DeleteSnapshotRepoRequest(const DeleteSnapshotRepoRequest &) = default ;
    DeleteSnapshotRepoRequest(DeleteSnapshotRepoRequest &&) = default ;
    DeleteSnapshotRepoRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DeleteSnapshotRepoRequest() = default ;
    DeleteSnapshotRepoRequest& operator=(const DeleteSnapshotRepoRequest &) = default ;
    DeleteSnapshotRepoRequest& operator=(DeleteSnapshotRepoRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->clientToken_ == nullptr
        && this->repoPath_ == nullptr; };
    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline DeleteSnapshotRepoRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // repoPath Field Functions 
    bool hasRepoPath() const { return this->repoPath_ != nullptr;};
    void deleteRepoPath() { this->repoPath_ = nullptr;};
    inline string getRepoPath() const { DARABONBA_PTR_GET_DEFAULT(repoPath_, "") };
    inline DeleteSnapshotRepoRequest& setRepoPath(string repoPath) { DARABONBA_PTR_SET_VALUE(repoPath_, repoPath) };


  protected:
    // A client token that is used to ensure the idempotence of the request. The value is generated by the client and must be unique among different requests. The value can contain up to 64 ASCII characters.
    shared_ptr<string> clientToken_ {};
    // The referenced instance ID. To obtain this parameter, see [ListSnapshotReposByInstanceId](https://help.aliyun.com/document_detail/178513.html).
    // .
    // 
    // This parameter is required.
    shared_ptr<string> repoPath_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Elasticsearch20170613
#endif
