// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_INITIALIZEOPERATIONROLEREQUEST_HPP_
#define ALIBABACLOUD_MODELS_INITIALIZEOPERATIONROLEREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Elasticsearch20170613
{
namespace Models
{
  class InitializeOperationRoleRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const InitializeOperationRoleRequest& obj) { 
      DARABONBA_PTR_TO_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(body, body_);
    };
    friend void from_json(const Darabonba::Json& j, InitializeOperationRoleRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(body, body_);
    };
    InitializeOperationRoleRequest() = default ;
    InitializeOperationRoleRequest(const InitializeOperationRoleRequest &) = default ;
    InitializeOperationRoleRequest(InitializeOperationRoleRequest &&) = default ;
    InitializeOperationRoleRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~InitializeOperationRoleRequest() = default ;
    InitializeOperationRoleRequest& operator=(const InitializeOperationRoleRequest &) = default ;
    InitializeOperationRoleRequest& operator=(InitializeOperationRoleRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->clientToken_ == nullptr
        && this->body_ == nullptr; };
    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline InitializeOperationRoleRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // body Field Functions 
    bool hasBody() const { return this->body_ != nullptr;};
    void deleteBody() { this->body_ = nullptr;};
    inline string getBody() const { DARABONBA_PTR_GET_DEFAULT(body_, "") };
    inline InitializeOperationRoleRequest& setBody(string body) { DARABONBA_PTR_SET_VALUE(body_, body) };


  protected:
    // A unique token generated by the client to ensure the idempotence of the request. The value of this parameter must be unique across different requests and can contain up to 64 ASCII characters.
    shared_ptr<string> clientToken_ {};
    shared_ptr<string> body_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Elasticsearch20170613
#endif
