// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_UPDATEPRIVATENETWORKWHITEIPSREQUEST_HPP_
#define ALIBABACLOUD_MODELS_UPDATEPRIVATENETWORKWHITEIPSREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Elasticsearch20170613
{
namespace Models
{
  class UpdatePrivateNetworkWhiteIpsRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const UpdatePrivateNetworkWhiteIpsRequest& obj) { 
      DARABONBA_PTR_TO_JSON(body, body_);
      DARABONBA_PTR_TO_JSON(clientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(modifyMode, modifyMode_);
    };
    friend void from_json(const Darabonba::Json& j, UpdatePrivateNetworkWhiteIpsRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(body, body_);
      DARABONBA_PTR_FROM_JSON(clientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(modifyMode, modifyMode_);
    };
    UpdatePrivateNetworkWhiteIpsRequest() = default ;
    UpdatePrivateNetworkWhiteIpsRequest(const UpdatePrivateNetworkWhiteIpsRequest &) = default ;
    UpdatePrivateNetworkWhiteIpsRequest(UpdatePrivateNetworkWhiteIpsRequest &&) = default ;
    UpdatePrivateNetworkWhiteIpsRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~UpdatePrivateNetworkWhiteIpsRequest() = default ;
    UpdatePrivateNetworkWhiteIpsRequest& operator=(const UpdatePrivateNetworkWhiteIpsRequest &) = default ;
    UpdatePrivateNetworkWhiteIpsRequest& operator=(UpdatePrivateNetworkWhiteIpsRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->body_ == nullptr
        && this->clientToken_ == nullptr && this->modifyMode_ == nullptr; };
    // body Field Functions 
    bool hasBody() const { return this->body_ != nullptr;};
    void deleteBody() { this->body_ = nullptr;};
    inline string getBody() const { DARABONBA_PTR_GET_DEFAULT(body_, "") };
    inline UpdatePrivateNetworkWhiteIpsRequest& setBody(string body) { DARABONBA_PTR_SET_VALUE(body_, body) };


    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline UpdatePrivateNetworkWhiteIpsRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // modifyMode Field Functions 
    bool hasModifyMode() const { return this->modifyMode_ != nullptr;};
    void deleteModifyMode() { this->modifyMode_ = nullptr;};
    inline string getModifyMode() const { DARABONBA_PTR_GET_DEFAULT(modifyMode_, "") };
    inline UpdatePrivateNetworkWhiteIpsRequest& setModifyMode(string modifyMode) { DARABONBA_PTR_SET_VALUE(modifyMode_, modifyMode) };


  protected:
    shared_ptr<string> body_ {};
    // A client token that is used to ensure the idempotence of the request. The value is generated by the client and must be unique among different requests. The maximum length is 64 ASCII characters.
    shared_ptr<string> clientToken_ {};
    // The modification mode. Valid values:
    // 
    // - Cover (default): overwrites the original IP whitelist with the value of the ips parameter.
    // 
    // - Append: adds the IP addresses specified in the ips parameter to the original IP whitelist.
    // 
    // - Delete: removes the IP addresses specified in the ips parameter from the original IP whitelist. At least one IP address must be retained.
    shared_ptr<string> modifyMode_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Elasticsearch20170613
#endif
