// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ESS20220222MODEL_HPP_
#define ALIBABACLOUD_ESS20220222MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ApplyScalingGroupRequest.hpp>
#include <alibabacloud/models/ApplyScalingGroupResponseBody.hpp>
#include <alibabacloud/models/ApplyScalingGroupResponse.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsResponse.hpp>
#include <alibabacloud/models/AttachDbInstancesRequest.hpp>
#include <alibabacloud/models/AttachDbInstancesResponseBody.hpp>
#include <alibabacloud/models/AttachDbInstancesResponse.hpp>
#include <alibabacloud/models/AttachInstancesRequest.hpp>
#include <alibabacloud/models/AttachInstancesResponseBody.hpp>
#include <alibabacloud/models/AttachInstancesResponse.hpp>
#include <alibabacloud/models/AttachLoadBalancersRequest.hpp>
#include <alibabacloud/models/AttachLoadBalancersResponseBody.hpp>
#include <alibabacloud/models/AttachLoadBalancersResponse.hpp>
#include <alibabacloud/models/AttachServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachServerGroupsResponse.hpp>
#include <alibabacloud/models/AttachVServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachVServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachVServerGroupsResponse.hpp>
#include <alibabacloud/models/CancelInstanceRefreshRequest.hpp>
#include <alibabacloud/models/CancelInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/CancelInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CompleteLifecycleActionRequest.hpp>
#include <alibabacloud/models/CompleteLifecycleActionResponseBody.hpp>
#include <alibabacloud/models/CompleteLifecycleActionResponse.hpp>
#include <alibabacloud/models/CreateAlarmRequest.hpp>
#include <alibabacloud/models/CreateAlarmResponseBody.hpp>
#include <alibabacloud/models/CreateAlarmResponse.hpp>
#include <alibabacloud/models/CreateDiagnoseReportRequest.hpp>
#include <alibabacloud/models/CreateDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/CreateDiagnoseReportResponse.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/CreateLifecycleHookRequest.hpp>
#include <alibabacloud/models/CreateLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/CreateLifecycleHookResponse.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequest.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/CreateScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateScalingConfigurationResponse.hpp>
#include <alibabacloud/models/CreateScalingGroupRequest.hpp>
#include <alibabacloud/models/CreateScalingGroupResponseBody.hpp>
#include <alibabacloud/models/CreateScalingGroupResponse.hpp>
#include <alibabacloud/models/CreateScalingRuleRequest.hpp>
#include <alibabacloud/models/CreateScalingRuleResponseBody.hpp>
#include <alibabacloud/models/CreateScalingRuleResponse.hpp>
#include <alibabacloud/models/CreateScheduledTaskRequest.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponse.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteAlarmRequest.hpp>
#include <alibabacloud/models/DeleteAlarmResponseBody.hpp>
#include <alibabacloud/models/DeleteAlarmResponse.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportRequest.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportResponse.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteLifecycleHookRequest.hpp>
#include <alibabacloud/models/DeleteLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/DeleteLifecycleHookResponse.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteScalingGroupRequest.hpp>
#include <alibabacloud/models/DeleteScalingGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingGroupResponse.hpp>
#include <alibabacloud/models/DeleteScalingRuleRequest.hpp>
#include <alibabacloud/models/DeleteScalingRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingRuleResponse.hpp>
#include <alibabacloud/models/DeleteScheduledTaskRequest.hpp>
#include <alibabacloud/models/DeleteScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteScheduledTaskResponse.hpp>
#include <alibabacloud/models/DescribeAlarmsRequest.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBody.hpp>
#include <alibabacloud/models/DescribeAlarmsResponse.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationRequest.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationResponseBody.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationResponse.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponse.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailRequest.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponse.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeElasticStrengthRequest.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponse.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesRequest.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponse.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsRequest.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsResponseBody.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsResponse.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksRequest.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksResponseBody.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksResponse.hpp>
#include <alibabacloud/models/DescribeLimitationRequest.hpp>
#include <alibabacloud/models/DescribeLimitationResponseBody.hpp>
#include <alibabacloud/models/DescribeLimitationResponse.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeNotificationTypesRequest.hpp>
#include <alibabacloud/models/DescribeNotificationTypesResponseBody.hpp>
#include <alibabacloud/models/DescribeNotificationTypesResponse.hpp>
#include <alibabacloud/models/DescribePatternTypesRequest.hpp>
#include <alibabacloud/models/DescribePatternTypesResponseBody.hpp>
#include <alibabacloud/models/DescribePatternTypesResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupsRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponse.hpp>
#include <alibabacloud/models/DescribeScalingInstancesRequest.hpp>
#include <alibabacloud/models/DescribeScalingInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingInstancesResponse.hpp>
#include <alibabacloud/models/DescribeScalingRulesRequest.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponse.hpp>
#include <alibabacloud/models/DescribeScheduledTasksRequest.hpp>
#include <alibabacloud/models/DescribeScheduledTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduledTasksResponse.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsResponse.hpp>
#include <alibabacloud/models/DetachDbInstancesRequest.hpp>
#include <alibabacloud/models/DetachDbInstancesResponseBody.hpp>
#include <alibabacloud/models/DetachDbInstancesResponse.hpp>
#include <alibabacloud/models/DetachInstancesRequest.hpp>
#include <alibabacloud/models/DetachInstancesResponseBody.hpp>
#include <alibabacloud/models/DetachInstancesResponse.hpp>
#include <alibabacloud/models/DetachLoadBalancersRequest.hpp>
#include <alibabacloud/models/DetachLoadBalancersResponseBody.hpp>
#include <alibabacloud/models/DetachLoadBalancersResponse.hpp>
#include <alibabacloud/models/DetachServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachServerGroupsResponse.hpp>
#include <alibabacloud/models/DetachVServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachVServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachVServerGroupsResponse.hpp>
#include <alibabacloud/models/DisableAlarmRequest.hpp>
#include <alibabacloud/models/DisableAlarmResponseBody.hpp>
#include <alibabacloud/models/DisableAlarmResponse.hpp>
#include <alibabacloud/models/DisableScalingGroupRequest.hpp>
#include <alibabacloud/models/DisableScalingGroupResponseBody.hpp>
#include <alibabacloud/models/DisableScalingGroupResponse.hpp>
#include <alibabacloud/models/EnableAlarmRequest.hpp>
#include <alibabacloud/models/EnableAlarmResponseBody.hpp>
#include <alibabacloud/models/EnableAlarmResponse.hpp>
#include <alibabacloud/models/EnableScalingGroupRequest.hpp>
#include <alibabacloud/models/EnableScalingGroupResponseBody.hpp>
#include <alibabacloud/models/EnableScalingGroupResponse.hpp>
#include <alibabacloud/models/EnterStandbyRequest.hpp>
#include <alibabacloud/models/EnterStandbyResponseBody.hpp>
#include <alibabacloud/models/EnterStandbyResponse.hpp>
#include <alibabacloud/models/ExecuteScalingRuleRequest.hpp>
#include <alibabacloud/models/ExecuteScalingRuleResponseBody.hpp>
#include <alibabacloud/models/ExecuteScalingRuleResponse.hpp>
#include <alibabacloud/models/ExitStandbyRequest.hpp>
#include <alibabacloud/models/ExitStandbyResponseBody.hpp>
#include <alibabacloud/models/ExitStandbyResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/ModifyAlarmRequest.hpp>
#include <alibabacloud/models/ModifyAlarmResponseBody.hpp>
#include <alibabacloud/models/ModifyAlarmResponse.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyLifecycleHookRequest.hpp>
#include <alibabacloud/models/ModifyLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/ModifyLifecycleHookResponse.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyScalingGroupRequest.hpp>
#include <alibabacloud/models/ModifyScalingGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingGroupResponse.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequest.hpp>
#include <alibabacloud/models/ModifyScalingRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingRuleResponse.hpp>
#include <alibabacloud/models/ModifyScheduledTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponse.hpp>
#include <alibabacloud/models/QueryHistoricalMetricRequest.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponseBody.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponse.hpp>
#include <alibabacloud/models/QueryPredictiveMetricRequest.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponse.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoRequest.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponse.hpp>
#include <alibabacloud/models/QueryPredictiveValueRequest.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponse.hpp>
#include <alibabacloud/models/RebalanceInstancesRequest.hpp>
#include <alibabacloud/models/RebalanceInstancesResponseBody.hpp>
#include <alibabacloud/models/RebalanceInstancesResponse.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatRequest.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatResponseBody.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatResponse.hpp>
#include <alibabacloud/models/RemoveInstancesRequest.hpp>
#include <alibabacloud/models/RemoveInstancesShrinkRequest.hpp>
#include <alibabacloud/models/RemoveInstancesResponseBody.hpp>
#include <alibabacloud/models/RemoveInstancesResponse.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshRequest.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ResumeProcessesRequest.hpp>
#include <alibabacloud/models/ResumeProcessesResponseBody.hpp>
#include <alibabacloud/models/ResumeProcessesResponse.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshRequest.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequest.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentShrinkRequest.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponseBody.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponse.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionRequest.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionResponseBody.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionResponse.hpp>
#include <alibabacloud/models/SetInstanceHealthRequest.hpp>
#include <alibabacloud/models/SetInstanceHealthResponseBody.hpp>
#include <alibabacloud/models/SetInstanceHealthResponse.hpp>
#include <alibabacloud/models/SetInstancesProtectionRequest.hpp>
#include <alibabacloud/models/SetInstancesProtectionResponseBody.hpp>
#include <alibabacloud/models/SetInstancesProtectionResponse.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequest.hpp>
#include <alibabacloud/models/StartInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/StartInstanceRefreshResponse.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshRequest.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshResponse.hpp>
#include <alibabacloud/models/SuspendProcessesRequest.hpp>
#include <alibabacloud/models/SuspendProcessesResponseBody.hpp>
#include <alibabacloud/models/SuspendProcessesResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/VerifyAuthenticationRequest.hpp>
#include <alibabacloud/models/VerifyAuthenticationResponseBody.hpp>
#include <alibabacloud/models/VerifyAuthenticationResponse.hpp>
#include <alibabacloud/models/VerifyUserRequest.hpp>
#include <alibabacloud/models/VerifyUserResponseBody.hpp>
#include <alibabacloud/models/VerifyUserResponse.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsRequestAlbServerGroups.hpp>
#include <alibabacloud/models/AttachLoadBalancersRequestLoadBalancerConfigs.hpp>
#include <alibabacloud/models/AttachServerGroupsRequestServerGroups.hpp>
#include <alibabacloud/models/AttachVServerGroupsRequestVServerGroupsVServerGroupAttributes.hpp>
#include <alibabacloud/models/AttachVServerGroupsRequestVServerGroups.hpp>
#include <alibabacloud/models/CreateAlarmRequestDimensions.hpp>
#include <alibabacloud/models/CreateAlarmRequestExpressions.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestAcrRegistryInfos.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersLivenessProbeExec.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersLivenessProbeHttpGet.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersLivenessProbeTcpSocket.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersLivenessProbe.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersReadinessProbeExec.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersReadinessProbeHttpGet.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersReadinessProbeTcpSocket.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersReadinessProbe.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersSecurityContextCapability.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersSecurityContext.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersEnvironmentVars.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersPorts.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainersVolumeMounts.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestContainers.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestDnsConfigOptions.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestHostAliases.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestImageRegistryCredentials.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainersSecurityContextCapability.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainersSecurityContext.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainersInitContainerEnvironmentVars.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainersInitContainerPorts.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainersInitContainerVolumeMounts.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestInitContainers.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestSecurityContextSysctls.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestTags.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesDiskVolume.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesEmptyDirVolume.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesFlexVolume.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesHostPathVolume.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesNfsVolume.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumesConfigFileVolumeConfigFileToPaths.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequestVolumes.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestImageOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestPrivatePoolOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestSystemDisk.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestCustomPriorities.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestDataDisks.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestInstancePatternInfos.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestInstanceTypeOverrides.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestNetworkInterfaces.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestResourcePoolOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestSecurityOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequestSpotPriceLimits.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestImageOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestPrivatePoolOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestSystemDisk.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestCustomPriorities.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestDataDisks.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestInstancePatternInfos.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestInstanceTypeOverrides.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestNetworkInterfaces.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestResourcePoolOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestSecurityOptions.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequestSpotPriceLimits.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestAlbServerGroups.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestCapacityOptions.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestDbInstances.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestLifecycleHooks.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestLoadBalancerConfigs.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestServerGroups.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestTags.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestVServerGroupsVServerGroupAttributes.hpp>
#include <alibabacloud/models/CreateScalingGroupRequestVServerGroups.hpp>
#include <alibabacloud/models/CreateScalingRuleRequestAlarmDimensions.hpp>
#include <alibabacloud/models/CreateScalingRuleRequestAlarmOptions.hpp>
#include <alibabacloud/models/CreateScalingRuleRequestHybridMetricsDimensions.hpp>
#include <alibabacloud/models/CreateScalingRuleRequestHybridMetrics.hpp>
#include <alibabacloud/models/CreateScalingRuleRequestStepAdjustments.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBodyAlarmListDimensions.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBodyAlarmListExpressions.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBodyAlarmListHybridMetricsDimensions.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBodyAlarmListHybridMetrics.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBodyAlarmList.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponseBodyReportsDetails.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponseBodyReports.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationAcrRegistryInfos.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationContainersEnvironmentVars.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationContainersPorts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationContainersVolumeMounts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationContainers.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationDnsConfigOptions.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationHostAliases.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationImageRegistryCredentials.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationInitContainersInitContainerEnvironmentVars.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationInitContainersInitContainerPorts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationInitContainersInitContainerVolumeMounts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationInitContainers.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationSecurityContextSysCtls.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationTags.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationVolumesConfigFileVolumeConfigFileToPaths.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfigurationVolumes.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBodyScalingConfiguration.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsAcrRegistryInfos.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsContainersEnvironmentVars.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsContainersPorts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsContainersVolumeMounts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsContainers.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsDnsConfigOptions.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsHostAliases.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsImageRegistryCredentials.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsInitContainersInitContainerEnvironmentVars.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsInitContainersInitContainerPorts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsInitContainersInitContainerVolumeMounts.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsInitContainers.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsSecurityContextSysCtls.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsTags.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsVolumesConfigFileVolumeConfigFileToPaths.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurationsVolumes.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBodyScalingConfigurations.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBodyElasticStrengthModelsResourcePoolsInventoryHealth.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBodyElasticStrengthModelsResourcePools.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBodyElasticStrengthModels.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBodyResourcePoolsInventoryHealth.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBodyResourcePools.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponseBodyInstanceCreateAndDeleteStatisticsStatistic.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponseBodyInstanceCreateAndDeleteStatistics.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasksCheckpoints.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasksDesiredConfigurationContainersEnvironmentVars.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasksDesiredConfigurationContainers.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasksDesiredConfigurationLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasksDesiredConfiguration.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBodyInstanceRefreshTasks.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsResponseBodyLifecycleActions.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksResponseBodyLifecycleHooks.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsResponseBodyNotificationConfigurationModels.hpp>
#include <alibabacloud/models/DescribePatternTypesResponseBodyPatternTypes.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponseBodyScalingActivitiesErrorMessages.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponseBodyScalingActivitiesLifecycleHookContext.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponseBodyScalingActivities.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBodyScalingActivityErrorCodeStatisticsErrorStatistic.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBodyScalingActivityErrorCodeStatistics.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBodyScalingActivityStatusStatisticsStatistic.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBodyScalingActivityStatusStatistics.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsCustomPriorities.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsDataDisks.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsInstancePatternInfos.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsNetworkInterfaces.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsResourcePoolOptions.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsSchedulerOptions.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsSecurityOptions.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsSpotPriceLimits.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurationsTags.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBodyScalingConfigurations.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupAlbServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupLoadBalancerConfigs.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupTags.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupVServerGroupsVServerGroupAttributes.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroupVServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBodyScalingGroup.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsResponseBodyDetails.hpp>
#include <alibabacloud/models/DescribeScalingGroupsRequestTags.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsAlbServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsCapacityOptions.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsDbInstances.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsLoadBalancerConfigs.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsTags.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsVServerGroupsVServerGroupAttributes.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroupsVServerGroups.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBodyScalingGroups.hpp>
#include <alibabacloud/models/DescribeScalingInstancesResponseBodyScalingInstances.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesAlarmDimensions.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesAlarmsDimensions.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesAlarms.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesHybridMetricsDimensions.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesHybridMetrics.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRulesStepAdjustments.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBodyScalingRules.hpp>
#include <alibabacloud/models/DescribeScheduledTasksResponseBodyScheduledTasks.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsRequestAlbServerGroups.hpp>
#include <alibabacloud/models/DetachServerGroupsRequestServerGroups.hpp>
#include <alibabacloud/models/DetachVServerGroupsRequestVServerGroupsVServerGroupAttributes.hpp>
#include <alibabacloud/models/DetachVServerGroupsRequestVServerGroups.hpp>
#include <alibabacloud/models/EnableScalingGroupRequestLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTags.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyAlarmRequestDimensions.hpp>
#include <alibabacloud/models/ModifyAlarmRequestExpressions.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestAcrRegistryInfos.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersLivenessProbeExec.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersLivenessProbeHttpGet.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersLivenessProbeTcpSocket.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersLivenessProbe.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersReadinessProbeExec.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersReadinessProbeHttpGet.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersReadinessProbeTcpSocket.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersReadinessProbe.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersSecurityContextCapability.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersSecurityContext.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersEnvironmentVarsFieldRef.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersEnvironmentVars.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersPorts.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainersVolumeMounts.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestContainers.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestDnsConfigOptions.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestHostAliases.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestImageRegistryCredentials.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersSecurityContextCapability.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersSecurityContext.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersInitContainerEnvironmentVarsFieldRef.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersInitContainerEnvironmentVars.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersInitContainerPorts.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainersInitContainerVolumeMounts.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestInitContainers.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestSecurityContextSysCtls.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestTags.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesDiskVolume.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesEmptyDirVolume.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesFlexVolume.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesHostPathVolume.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesNfsVolume.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumesConfigFileVolumeConfigFileToPath.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequestVolumes.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestImageOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestPrivatePoolOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestSystemDisk.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestCustomPriorities.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestDataDisks.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestInstancePatternInfos.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestInstanceTypeOverrides.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestNetworkInterfaces.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestResourcePoolOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestSecurityOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequestSpotPriceLimits.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestImageOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestPrivatePoolOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestSystemDisk.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestCustomPriorities.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestDataDisks.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestInstancePatternInfos.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestInstanceTypeOverrides.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestNetworkInterfaces.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestResourcePoolOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestSecurityOptions.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequestSpotPriceLimits.hpp>
#include <alibabacloud/models/ModifyScalingGroupRequestCapacityOptions.hpp>
#include <alibabacloud/models/ModifyScalingGroupRequestLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequestAlarmDimensions.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequestAlarmOptions.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequestHybridMetricsDimensions.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequestHybridMetrics.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequestStepAdjustments.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponseBodyHistoricalMetricsHistoricalMetric.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponseBodyHistoricalMetrics.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponseBodyPredictiveMetricsPredictiveMetric.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponseBodyPredictiveMetrics.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponseBodyTaskInfosTaskInfo.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponseBodyTaskInfos.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponseBodyPredictiveValuesPredictiveValue.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponseBodyPredictiveValues.hpp>
#include <alibabacloud/models/RemoveInstancesRequestLifecycleHookContext.hpp>
#include <alibabacloud/models/RemoveInstancesResponseBodyIgnoredInstances.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequestLifecycleHookContext.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequestOverridesContainerOverridesEnvironmentVars.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequestOverridesContainerOverrides.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequestOverrides.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponseBodyPlanResultResourceAllocations.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponseBodyPlanResult.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequestCheckpoints.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequestDesiredConfigurationContainersEnvironmentVars.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequestDesiredConfigurationContainers.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequestDesiredConfigurationLaunchTemplateOverrides.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequestDesiredConfiguration.hpp>
#include <alibabacloud/models/TagResourcesRequestTags.hpp>

#endif
