// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ESS20220222MODEL_HPP_
#define ALIBABACLOUD_ESS20220222MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ApplyEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ApplyScalingGroupRequest.hpp>
#include <alibabacloud/models/ApplyScalingGroupResponseBody.hpp>
#include <alibabacloud/models/ApplyScalingGroupResponse.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachAlbServerGroupsResponse.hpp>
#include <alibabacloud/models/AttachDBInstancesRequest.hpp>
#include <alibabacloud/models/AttachDBInstancesResponseBody.hpp>
#include <alibabacloud/models/AttachDBInstancesResponse.hpp>
#include <alibabacloud/models/AttachInstancesRequest.hpp>
#include <alibabacloud/models/AttachInstancesResponseBody.hpp>
#include <alibabacloud/models/AttachInstancesResponse.hpp>
#include <alibabacloud/models/AttachLoadBalancersRequest.hpp>
#include <alibabacloud/models/AttachLoadBalancersResponseBody.hpp>
#include <alibabacloud/models/AttachLoadBalancersResponse.hpp>
#include <alibabacloud/models/AttachServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachServerGroupsResponse.hpp>
#include <alibabacloud/models/AttachVServerGroupsRequest.hpp>
#include <alibabacloud/models/AttachVServerGroupsResponseBody.hpp>
#include <alibabacloud/models/AttachVServerGroupsResponse.hpp>
#include <alibabacloud/models/CancelInstanceRefreshRequest.hpp>
#include <alibabacloud/models/CancelInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/CancelInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CompleteLifecycleActionRequest.hpp>
#include <alibabacloud/models/CompleteLifecycleActionResponseBody.hpp>
#include <alibabacloud/models/CompleteLifecycleActionResponse.hpp>
#include <alibabacloud/models/CreateAlarmRequest.hpp>
#include <alibabacloud/models/CreateAlarmResponseBody.hpp>
#include <alibabacloud/models/CreateAlarmResponse.hpp>
#include <alibabacloud/models/CreateDiagnoseReportRequest.hpp>
#include <alibabacloud/models/CreateDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/CreateDiagnoseReportResponse.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/CreateLifecycleHookRequest.hpp>
#include <alibabacloud/models/CreateLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/CreateLifecycleHookResponse.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/CreateScalingConfigurationRequest.hpp>
#include <alibabacloud/models/CreateScalingConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/CreateScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateScalingConfigurationResponse.hpp>
#include <alibabacloud/models/CreateScalingGroupRequest.hpp>
#include <alibabacloud/models/CreateScalingGroupResponseBody.hpp>
#include <alibabacloud/models/CreateScalingGroupResponse.hpp>
#include <alibabacloud/models/CreateScalingRuleRequest.hpp>
#include <alibabacloud/models/CreateScalingRuleResponseBody.hpp>
#include <alibabacloud/models/CreateScalingRuleResponse.hpp>
#include <alibabacloud/models/CreateScheduledTaskRequest.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponse.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeactivateScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteAlarmRequest.hpp>
#include <alibabacloud/models/DeleteAlarmResponseBody.hpp>
#include <alibabacloud/models/DeleteAlarmResponse.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportRequest.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/DeleteDiagnoseReportResponse.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteLifecycleHookRequest.hpp>
#include <alibabacloud/models/DeleteLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/DeleteLifecycleHookResponse.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteScalingGroupRequest.hpp>
#include <alibabacloud/models/DeleteScalingGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingGroupResponse.hpp>
#include <alibabacloud/models/DeleteScalingRuleRequest.hpp>
#include <alibabacloud/models/DeleteScalingRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteScalingRuleResponse.hpp>
#include <alibabacloud/models/DeleteScheduledTaskRequest.hpp>
#include <alibabacloud/models/DeleteScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteScheduledTaskResponse.hpp>
#include <alibabacloud/models/DescribeAlarmsRequest.hpp>
#include <alibabacloud/models/DescribeAlarmsResponseBody.hpp>
#include <alibabacloud/models/DescribeAlarmsResponse.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationRequest.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationResponseBody.hpp>
#include <alibabacloud/models/DescribeAlertConfigurationResponse.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportsResponse.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailRequest.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationDetailResponse.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeEciScalingConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeElasticStrengthRequest.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticStrengthResponse.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceCreateAndDeleteStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesRequest.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceRefreshesResponse.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsRequest.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsResponseBody.hpp>
#include <alibabacloud/models/DescribeLifecycleActionsResponse.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksRequest.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksResponseBody.hpp>
#include <alibabacloud/models/DescribeLifecycleHooksResponse.hpp>
#include <alibabacloud/models/DescribeLimitationRequest.hpp>
#include <alibabacloud/models/DescribeLimitationResponseBody.hpp>
#include <alibabacloud/models/DescribeLimitationResponse.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeNotificationConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeNotificationTypesRequest.hpp>
#include <alibabacloud/models/DescribeNotificationTypesResponseBody.hpp>
#include <alibabacloud/models/DescribeNotificationTypesResponse.hpp>
#include <alibabacloud/models/DescribePatternTypesRequest.hpp>
#include <alibabacloud/models/DescribePatternTypesResponseBody.hpp>
#include <alibabacloud/models/DescribePatternTypesResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivitiesResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivityDetailResponse.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingActivityStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsRequest.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingConfigurationsResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupDetailResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupDiagnoseDetailsResponse.hpp>
#include <alibabacloud/models/DescribeScalingGroupsRequest.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingGroupsResponse.hpp>
#include <alibabacloud/models/DescribeScalingInstancesRequest.hpp>
#include <alibabacloud/models/DescribeScalingInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingInstancesResponse.hpp>
#include <alibabacloud/models/DescribeScalingRulesRequest.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeScalingRulesResponse.hpp>
#include <alibabacloud/models/DescribeScheduledTasksRequest.hpp>
#include <alibabacloud/models/DescribeScheduledTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduledTasksResponse.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachAlbServerGroupsResponse.hpp>
#include <alibabacloud/models/DetachDBInstancesRequest.hpp>
#include <alibabacloud/models/DetachDBInstancesResponseBody.hpp>
#include <alibabacloud/models/DetachDBInstancesResponse.hpp>
#include <alibabacloud/models/DetachInstancesRequest.hpp>
#include <alibabacloud/models/DetachInstancesResponseBody.hpp>
#include <alibabacloud/models/DetachInstancesResponse.hpp>
#include <alibabacloud/models/DetachLoadBalancersRequest.hpp>
#include <alibabacloud/models/DetachLoadBalancersResponseBody.hpp>
#include <alibabacloud/models/DetachLoadBalancersResponse.hpp>
#include <alibabacloud/models/DetachServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachServerGroupsResponse.hpp>
#include <alibabacloud/models/DetachVServerGroupsRequest.hpp>
#include <alibabacloud/models/DetachVServerGroupsResponseBody.hpp>
#include <alibabacloud/models/DetachVServerGroupsResponse.hpp>
#include <alibabacloud/models/DisableAlarmRequest.hpp>
#include <alibabacloud/models/DisableAlarmResponseBody.hpp>
#include <alibabacloud/models/DisableAlarmResponse.hpp>
#include <alibabacloud/models/DisableScalingGroupRequest.hpp>
#include <alibabacloud/models/DisableScalingGroupResponseBody.hpp>
#include <alibabacloud/models/DisableScalingGroupResponse.hpp>
#include <alibabacloud/models/EnableAlarmRequest.hpp>
#include <alibabacloud/models/EnableAlarmResponseBody.hpp>
#include <alibabacloud/models/EnableAlarmResponse.hpp>
#include <alibabacloud/models/EnableScalingGroupRequest.hpp>
#include <alibabacloud/models/EnableScalingGroupResponseBody.hpp>
#include <alibabacloud/models/EnableScalingGroupResponse.hpp>
#include <alibabacloud/models/EnterStandbyRequest.hpp>
#include <alibabacloud/models/EnterStandbyResponseBody.hpp>
#include <alibabacloud/models/EnterStandbyResponse.hpp>
#include <alibabacloud/models/ExecuteScalingRuleRequest.hpp>
#include <alibabacloud/models/ExecuteScalingRuleResponseBody.hpp>
#include <alibabacloud/models/ExecuteScalingRuleResponse.hpp>
#include <alibabacloud/models/ExitStandbyRequest.hpp>
#include <alibabacloud/models/ExitStandbyResponseBody.hpp>
#include <alibabacloud/models/ExitStandbyResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/ModifyAlarmRequest.hpp>
#include <alibabacloud/models/ModifyAlarmResponseBody.hpp>
#include <alibabacloud/models/ModifyAlarmResponse.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyAlertConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyEciScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyLifecycleHookRequest.hpp>
#include <alibabacloud/models/ModifyLifecycleHookResponseBody.hpp>
#include <alibabacloud/models/ModifyLifecycleHookResponse.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyNotificationConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationShrinkRequest.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyScalingGroupRequest.hpp>
#include <alibabacloud/models/ModifyScalingGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingGroupResponse.hpp>
#include <alibabacloud/models/ModifyScalingRuleRequest.hpp>
#include <alibabacloud/models/ModifyScalingRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyScalingRuleResponse.hpp>
#include <alibabacloud/models/ModifyScheduledTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponse.hpp>
#include <alibabacloud/models/QueryHistoricalMetricRequest.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponseBody.hpp>
#include <alibabacloud/models/QueryHistoricalMetricResponse.hpp>
#include <alibabacloud/models/QueryPredictiveMetricRequest.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveMetricResponse.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoRequest.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveTaskInfoResponse.hpp>
#include <alibabacloud/models/QueryPredictiveValueRequest.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponseBody.hpp>
#include <alibabacloud/models/QueryPredictiveValueResponse.hpp>
#include <alibabacloud/models/RebalanceInstancesRequest.hpp>
#include <alibabacloud/models/RebalanceInstancesResponseBody.hpp>
#include <alibabacloud/models/RebalanceInstancesResponse.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatRequest.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatResponseBody.hpp>
#include <alibabacloud/models/RecordLifecycleActionHeartbeatResponse.hpp>
#include <alibabacloud/models/RemoveInstancesRequest.hpp>
#include <alibabacloud/models/RemoveInstancesShrinkRequest.hpp>
#include <alibabacloud/models/RemoveInstancesResponseBody.hpp>
#include <alibabacloud/models/RemoveInstancesResponse.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshRequest.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/ResumeInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ResumeProcessesRequest.hpp>
#include <alibabacloud/models/ResumeProcessesResponseBody.hpp>
#include <alibabacloud/models/ResumeProcessesResponse.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshRequest.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/RollbackInstanceRefreshResponse.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentRequest.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentShrinkRequest.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponseBody.hpp>
#include <alibabacloud/models/ScaleWithAdjustmentResponse.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionRequest.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionResponseBody.hpp>
#include <alibabacloud/models/SetGroupDeletionProtectionResponse.hpp>
#include <alibabacloud/models/SetInstanceHealthRequest.hpp>
#include <alibabacloud/models/SetInstanceHealthResponseBody.hpp>
#include <alibabacloud/models/SetInstanceHealthResponse.hpp>
#include <alibabacloud/models/SetInstancesProtectionRequest.hpp>
#include <alibabacloud/models/SetInstancesProtectionResponseBody.hpp>
#include <alibabacloud/models/SetInstancesProtectionResponse.hpp>
#include <alibabacloud/models/StartInstanceRefreshRequest.hpp>
#include <alibabacloud/models/StartInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/StartInstanceRefreshResponse.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshRequest.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshResponseBody.hpp>
#include <alibabacloud/models/SuspendInstanceRefreshResponse.hpp>
#include <alibabacloud/models/SuspendProcessesRequest.hpp>
#include <alibabacloud/models/SuspendProcessesResponseBody.hpp>
#include <alibabacloud/models/SuspendProcessesResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/VerifyAuthenticationRequest.hpp>
#include <alibabacloud/models/VerifyAuthenticationResponseBody.hpp>
#include <alibabacloud/models/VerifyAuthenticationResponse.hpp>
#include <alibabacloud/models/VerifyUserRequest.hpp>
#include <alibabacloud/models/VerifyUserResponseBody.hpp>
#include <alibabacloud/models/VerifyUserResponse.hpp>

#endif
