// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_OPENAPIEXPLORER20241130MODEL_HPP_
#define ALIBABACLOUD_OPENAPIEXPLORER20241130MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApiMcpServerValidateHclRequest.hpp>
#include <alibabacloud/models/ApiMcpServerValidateHclResponseBody.hpp>
#include <alibabacloud/models/ApiMcpServerValidateHclResponse.hpp>
#include <alibabacloud/models/CreateApiMcpServerRequest.hpp>
#include <alibabacloud/models/CreateApiMcpServerResponseBody.hpp>
#include <alibabacloud/models/CreateApiMcpServerResponse.hpp>
#include <alibabacloud/models/DeleteApiMcpServerRequest.hpp>
#include <alibabacloud/models/DeleteApiMcpServerResponseBody.hpp>
#include <alibabacloud/models/DeleteApiMcpServerResponse.hpp>
#include <alibabacloud/models/GenerateCLICommandRequest.hpp>
#include <alibabacloud/models/GenerateCLICommandShrinkRequest.hpp>
#include <alibabacloud/models/GenerateCLICommandResponseBody.hpp>
#include <alibabacloud/models/GenerateCLICommandResponse.hpp>
#include <alibabacloud/models/GetApiDefinitionRequest.hpp>
#include <alibabacloud/models/GetApiDefinitionResponse.hpp>
#include <alibabacloud/models/GetApiMcpServerRequest.hpp>
#include <alibabacloud/models/GetApiMcpServerResponseBody.hpp>
#include <alibabacloud/models/GetApiMcpServerResponse.hpp>
#include <alibabacloud/models/GetApiMcpServerUserConfigResponseBody.hpp>
#include <alibabacloud/models/GetApiMcpServerUserConfigResponse.hpp>
#include <alibabacloud/models/GetErrorCodeSolutionsRequest.hpp>
#include <alibabacloud/models/GetErrorCodeSolutionsResponseBody.hpp>
#include <alibabacloud/models/GetErrorCodeSolutionsResponse.hpp>
#include <alibabacloud/models/GetOwnRequestLogRequest.hpp>
#include <alibabacloud/models/GetOwnRequestLogResponseBody.hpp>
#include <alibabacloud/models/GetOwnRequestLogResponse.hpp>
#include <alibabacloud/models/GetProductEndpointsRequest.hpp>
#include <alibabacloud/models/GetProductEndpointsResponse.hpp>
#include <alibabacloud/models/GetRequestLogRequest.hpp>
#include <alibabacloud/models/GetRequestLogResponseBody.hpp>
#include <alibabacloud/models/GetRequestLogResponse.hpp>
#include <alibabacloud/models/ListApiDefinitionsRequest.hpp>
#include <alibabacloud/models/ListApiDefinitionsResponse.hpp>
#include <alibabacloud/models/ListApiMcpServerSystemToolsRequest.hpp>
#include <alibabacloud/models/ListApiMcpServerSystemToolsResponseBody.hpp>
#include <alibabacloud/models/ListApiMcpServerSystemToolsResponse.hpp>
#include <alibabacloud/models/ListApiMcpServersRequest.hpp>
#include <alibabacloud/models/ListApiMcpServersResponseBody.hpp>
#include <alibabacloud/models/ListApiMcpServersResponse.hpp>
#include <alibabacloud/models/UpdateApiMcpServerRequest.hpp>
#include <alibabacloud/models/UpdateApiMcpServerResponseBody.hpp>
#include <alibabacloud/models/UpdateApiMcpServerResponse.hpp>
#include <alibabacloud/models/UpdateApiMcpServerUserConfigRequest.hpp>
#include <alibabacloud/models/UpdateApiMcpServerUserConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateApiMcpServerUserConfigResponse.hpp>

#endif
