// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_IMAGEENHAN20190930MODEL_HPP_
#define ALIBABACLOUD_IMAGEENHAN20190930MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AssessCompositionRequest.hpp>
#include <alibabacloud/models/AssessCompositionAdvanceRequest.hpp>
#include <alibabacloud/models/AssessCompositionResponseBody.hpp>
#include <alibabacloud/models/AssessCompositionResponse.hpp>
#include <alibabacloud/models/AssessExposureRequest.hpp>
#include <alibabacloud/models/AssessExposureAdvanceRequest.hpp>
#include <alibabacloud/models/AssessExposureResponseBody.hpp>
#include <alibabacloud/models/AssessExposureResponse.hpp>
#include <alibabacloud/models/AssessSharpnessRequest.hpp>
#include <alibabacloud/models/AssessSharpnessAdvanceRequest.hpp>
#include <alibabacloud/models/AssessSharpnessResponseBody.hpp>
#include <alibabacloud/models/AssessSharpnessResponse.hpp>
#include <alibabacloud/models/ChangeImageSizeRequest.hpp>
#include <alibabacloud/models/ChangeImageSizeAdvanceRequest.hpp>
#include <alibabacloud/models/ChangeImageSizeResponseBody.hpp>
#include <alibabacloud/models/ChangeImageSizeResponse.hpp>
#include <alibabacloud/models/ColorizeImageRequest.hpp>
#include <alibabacloud/models/ColorizeImageAdvanceRequest.hpp>
#include <alibabacloud/models/ColorizeImageResponseBody.hpp>
#include <alibabacloud/models/ColorizeImageResponse.hpp>
#include <alibabacloud/models/EnhanceImageColorRequest.hpp>
#include <alibabacloud/models/EnhanceImageColorAdvanceRequest.hpp>
#include <alibabacloud/models/EnhanceImageColorResponseBody.hpp>
#include <alibabacloud/models/EnhanceImageColorResponse.hpp>
#include <alibabacloud/models/ErasePersonRequest.hpp>
#include <alibabacloud/models/ErasePersonAdvanceRequest.hpp>
#include <alibabacloud/models/ErasePersonResponseBody.hpp>
#include <alibabacloud/models/ErasePersonResponse.hpp>
#include <alibabacloud/models/ExtendImageStyleRequest.hpp>
#include <alibabacloud/models/ExtendImageStyleAdvanceRequest.hpp>
#include <alibabacloud/models/ExtendImageStyleResponseBody.hpp>
#include <alibabacloud/models/ExtendImageStyleResponse.hpp>
#include <alibabacloud/models/GenerateCartoonizedImageRequest.hpp>
#include <alibabacloud/models/GenerateCartoonizedImageAdvanceRequest.hpp>
#include <alibabacloud/models/GenerateCartoonizedImageResponseBody.hpp>
#include <alibabacloud/models/GenerateCartoonizedImageResponse.hpp>
#include <alibabacloud/models/GenerateSuperResolutionImageRequest.hpp>
#include <alibabacloud/models/GenerateSuperResolutionImageAdvanceRequest.hpp>
#include <alibabacloud/models/GenerateSuperResolutionImageResponseBody.hpp>
#include <alibabacloud/models/GenerateSuperResolutionImageResponse.hpp>
#include <alibabacloud/models/GetAsyncJobResultRequest.hpp>
#include <alibabacloud/models/GetAsyncJobResultResponseBody.hpp>
#include <alibabacloud/models/GetAsyncJobResultResponse.hpp>
#include <alibabacloud/models/ImageBlindCharacterWatermarkRequest.hpp>
#include <alibabacloud/models/ImageBlindCharacterWatermarkAdvanceRequest.hpp>
#include <alibabacloud/models/ImageBlindCharacterWatermarkResponseBody.hpp>
#include <alibabacloud/models/ImageBlindCharacterWatermarkResponse.hpp>
#include <alibabacloud/models/ImageBlindPicWatermarkRequest.hpp>
#include <alibabacloud/models/ImageBlindPicWatermarkAdvanceRequest.hpp>
#include <alibabacloud/models/ImageBlindPicWatermarkResponseBody.hpp>
#include <alibabacloud/models/ImageBlindPicWatermarkResponse.hpp>
#include <alibabacloud/models/ImitatePhotoStyleRequest.hpp>
#include <alibabacloud/models/ImitatePhotoStyleAdvanceRequest.hpp>
#include <alibabacloud/models/ImitatePhotoStyleResponseBody.hpp>
#include <alibabacloud/models/ImitatePhotoStyleResponse.hpp>
#include <alibabacloud/models/IntelligentCompositionRequest.hpp>
#include <alibabacloud/models/IntelligentCompositionAdvanceRequest.hpp>
#include <alibabacloud/models/IntelligentCompositionResponseBody.hpp>
#include <alibabacloud/models/IntelligentCompositionResponse.hpp>
#include <alibabacloud/models/MakeSuperResolutionImageRequest.hpp>
#include <alibabacloud/models/MakeSuperResolutionImageAdvanceRequest.hpp>
#include <alibabacloud/models/MakeSuperResolutionImageResponseBody.hpp>
#include <alibabacloud/models/MakeSuperResolutionImageResponse.hpp>
#include <alibabacloud/models/RecolorHdImageRequest.hpp>
#include <alibabacloud/models/RecolorHdImageAdvanceRequest.hpp>
#include <alibabacloud/models/RecolorHdImageResponseBody.hpp>
#include <alibabacloud/models/RecolorHdImageResponse.hpp>
#include <alibabacloud/models/RecolorImageRequest.hpp>
#include <alibabacloud/models/RecolorImageAdvanceRequest.hpp>
#include <alibabacloud/models/RecolorImageResponseBody.hpp>
#include <alibabacloud/models/RecolorImageResponse.hpp>
#include <alibabacloud/models/RemoveImageSubtitlesRequest.hpp>
#include <alibabacloud/models/RemoveImageSubtitlesAdvanceRequest.hpp>
#include <alibabacloud/models/RemoveImageSubtitlesResponseBody.hpp>
#include <alibabacloud/models/RemoveImageSubtitlesResponse.hpp>
#include <alibabacloud/models/RemoveImageWatermarkRequest.hpp>
#include <alibabacloud/models/RemoveImageWatermarkAdvanceRequest.hpp>
#include <alibabacloud/models/RemoveImageWatermarkResponseBody.hpp>
#include <alibabacloud/models/RemoveImageWatermarkResponse.hpp>
#include <alibabacloud/models/AssessCompositionResponseBodyData.hpp>
#include <alibabacloud/models/AssessExposureResponseBodyData.hpp>
#include <alibabacloud/models/AssessSharpnessResponseBodyData.hpp>
#include <alibabacloud/models/ChangeImageSizeResponseBodyDataRetainLocation.hpp>
#include <alibabacloud/models/ChangeImageSizeResponseBodyData.hpp>
#include <alibabacloud/models/ColorizeImageResponseBodyData.hpp>
#include <alibabacloud/models/EnhanceImageColorResponseBodyData.hpp>
#include <alibabacloud/models/ErasePersonResponseBodyData.hpp>
#include <alibabacloud/models/ExtendImageStyleResponseBodyData.hpp>
#include <alibabacloud/models/GenerateCartoonizedImageResponseBodyData.hpp>
#include <alibabacloud/models/GenerateSuperResolutionImageResponseBodyData.hpp>
#include <alibabacloud/models/GetAsyncJobResultResponseBodyData.hpp>
#include <alibabacloud/models/ImageBlindCharacterWatermarkResponseBodyData.hpp>
#include <alibabacloud/models/ImageBlindPicWatermarkResponseBodyData.hpp>
#include <alibabacloud/models/ImitatePhotoStyleResponseBodyData.hpp>
#include <alibabacloud/models/IntelligentCompositionResponseBodyDataElements.hpp>
#include <alibabacloud/models/IntelligentCompositionResponseBodyData.hpp>
#include <alibabacloud/models/MakeSuperResolutionImageResponseBodyData.hpp>
#include <alibabacloud/models/RecolorHdImageRequestColorTemplate.hpp>
#include <alibabacloud/models/RecolorHdImageAdvanceRequestColorTemplate.hpp>
#include <alibabacloud/models/RecolorHdImageResponseBodyData.hpp>
#include <alibabacloud/models/RecolorImageRequestColorTemplate.hpp>
#include <alibabacloud/models/RecolorImageAdvanceRequestColorTemplate.hpp>
#include <alibabacloud/models/RecolorImageResponseBodyData.hpp>
#include <alibabacloud/models/RemoveImageSubtitlesResponseBodyData.hpp>
#include <alibabacloud/models/RemoveImageWatermarkResponseBodyData.hpp>

#endif
