// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ESSERVERLESS20230627MODEL_HPP_
#define ALIBABACLOUD_ESSERVERLESS20230627MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CancelSpecReviewTaskResponseBody.hpp>
#include <alibabacloud/models/CancelSpecReviewTaskResponse.hpp>
#include <alibabacloud/models/CreateAppRequest.hpp>
#include <alibabacloud/models/CreateAppResponseBody.hpp>
#include <alibabacloud/models/CreateAppResponse.hpp>
#include <alibabacloud/models/CreateEndpointRequest.hpp>
#include <alibabacloud/models/CreateEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateEndpointResponse.hpp>
#include <alibabacloud/models/CreateSnapshotRequest.hpp>
#include <alibabacloud/models/CreateSnapshotResponseBody.hpp>
#include <alibabacloud/models/CreateSnapshotResponse.hpp>
#include <alibabacloud/models/DeleteAppResponseBody.hpp>
#include <alibabacloud/models/DeleteAppResponse.hpp>
#include <alibabacloud/models/DeleteDictRequest.hpp>
#include <alibabacloud/models/DeleteDictResponseBody.hpp>
#include <alibabacloud/models/DeleteDictResponse.hpp>
#include <alibabacloud/models/DeleteEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteEndpointResponse.hpp>
#include <alibabacloud/models/DeleteSnapshotResponseBody.hpp>
#include <alibabacloud/models/DeleteSnapshotResponse.hpp>
#include <alibabacloud/models/GetAppRequest.hpp>
#include <alibabacloud/models/GetAppResponseBody.hpp>
#include <alibabacloud/models/GetAppResponse.hpp>
#include <alibabacloud/models/GetAppQuotaResponseBody.hpp>
#include <alibabacloud/models/GetAppQuotaResponse.hpp>
#include <alibabacloud/models/GetMonitorDataRequest.hpp>
#include <alibabacloud/models/GetMonitorDataResponseBody.hpp>
#include <alibabacloud/models/GetMonitorDataResponse.hpp>
#include <alibabacloud/models/GetSnapshotSettingResponseBody.hpp>
#include <alibabacloud/models/GetSnapshotSettingResponse.hpp>
#include <alibabacloud/models/GetSpecReviewTaskResponseBody.hpp>
#include <alibabacloud/models/GetSpecReviewTaskResponse.hpp>
#include <alibabacloud/models/ListAppsRequest.hpp>
#include <alibabacloud/models/ListAppsResponseBody.hpp>
#include <alibabacloud/models/ListAppsResponse.hpp>
#include <alibabacloud/models/ListDictsRequest.hpp>
#include <alibabacloud/models/ListDictsResponseBody.hpp>
#include <alibabacloud/models/ListDictsResponse.hpp>
#include <alibabacloud/models/ListEndpointsRequest.hpp>
#include <alibabacloud/models/ListEndpointsResponseBody.hpp>
#include <alibabacloud/models/ListEndpointsResponse.hpp>
#include <alibabacloud/models/ListIndicesResponseBody.hpp>
#include <alibabacloud/models/ListIndicesResponse.hpp>
#include <alibabacloud/models/ListSnapshotRepositoriesResponseBody.hpp>
#include <alibabacloud/models/ListSnapshotRepositoriesResponse.hpp>
#include <alibabacloud/models/ListSnapshotsRequest.hpp>
#include <alibabacloud/models/ListSnapshotsResponseBody.hpp>
#include <alibabacloud/models/ListSnapshotsResponse.hpp>
#include <alibabacloud/models/ListSpecReviewTasksRequest.hpp>
#include <alibabacloud/models/ListSpecReviewTasksResponseBody.hpp>
#include <alibabacloud/models/ListSpecReviewTasksResponse.hpp>
#include <alibabacloud/models/UpdateAppRequest.hpp>
#include <alibabacloud/models/UpdateAppResponseBody.hpp>
#include <alibabacloud/models/UpdateAppResponse.hpp>
#include <alibabacloud/models/UpdateDictRequest.hpp>
#include <alibabacloud/models/UpdateDictResponseBody.hpp>
#include <alibabacloud/models/UpdateDictResponse.hpp>
#include <alibabacloud/models/UpdateEndpointRequest.hpp>
#include <alibabacloud/models/UpdateEndpointResponseBody.hpp>
#include <alibabacloud/models/UpdateEndpointResponse.hpp>
#include <alibabacloud/models/UpdateNetworkRequest.hpp>
#include <alibabacloud/models/UpdateNetworkResponseBody.hpp>
#include <alibabacloud/models/UpdateNetworkResponse.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingRequest.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingResponseBody.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingResponse.hpp>
#include <alibabacloud/models/CreateAppRequestAuthenticationBasicAuth.hpp>
#include <alibabacloud/models/CreateAppRequestAuthentication.hpp>
#include <alibabacloud/models/CreateAppRequestNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/CreateAppRequestNetwork.hpp>
#include <alibabacloud/models/CreateAppRequestPrivateNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/CreateAppRequestPrivateNetwork.hpp>
#include <alibabacloud/models/CreateAppRequestQuotaInfo.hpp>
#include <alibabacloud/models/CreateAppRequestTags.hpp>
#include <alibabacloud/models/CreateAppResponseBodyResult.hpp>
#include <alibabacloud/models/CreateEndpointRequestEndpointZones.hpp>
#include <alibabacloud/models/CreateEndpointResponseBodyResult.hpp>
#include <alibabacloud/models/DeleteAppResponseBodyResult.hpp>
#include <alibabacloud/models/GetAppResponseBodyResultNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/GetAppResponseBodyResultNetwork.hpp>
#include <alibabacloud/models/GetAppResponseBodyResultPrivateNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/GetAppResponseBodyResultPrivateNetwork.hpp>
#include <alibabacloud/models/GetAppResponseBodyResultTags.hpp>
#include <alibabacloud/models/GetAppResponseBodyResult.hpp>
#include <alibabacloud/models/GetAppQuotaResponseBodyResultLimiterInfoLimiters.hpp>
#include <alibabacloud/models/GetAppQuotaResponseBodyResultLimiterInfo.hpp>
#include <alibabacloud/models/GetAppQuotaResponseBodyResult.hpp>
#include <alibabacloud/models/GetMonitorDataResponseBodyResult.hpp>
#include <alibabacloud/models/GetSnapshotSettingResponseBodyResult.hpp>
#include <alibabacloud/models/GetSpecReviewTaskResponseBodyResult.hpp>
#include <alibabacloud/models/ListAppsResponseBodyResultTags.hpp>
#include <alibabacloud/models/ListAppsResponseBodyResult.hpp>
#include <alibabacloud/models/ListDictsResponseBodyResult.hpp>
#include <alibabacloud/models/ListEndpointsResponseBodyResultEndpointZones.hpp>
#include <alibabacloud/models/ListEndpointsResponseBodyResult.hpp>
#include <alibabacloud/models/ListSpecReviewTasksResponseBodyResult.hpp>
#include <alibabacloud/models/UpdateAppRequestAuthenticationBasicAuth.hpp>
#include <alibabacloud/models/UpdateAppRequestAuthentication.hpp>
#include <alibabacloud/models/UpdateAppRequestLimiterInfoLimiters.hpp>
#include <alibabacloud/models/UpdateAppRequestLimiterInfo.hpp>
#include <alibabacloud/models/UpdateAppRequestNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/UpdateAppRequestNetwork.hpp>
#include <alibabacloud/models/UpdateAppRequestPrivateNetworkWhiteIpGroup.hpp>
#include <alibabacloud/models/UpdateAppRequestPrivateNetwork.hpp>
#include <alibabacloud/models/UpdateAppResponseBodyResult.hpp>
#include <alibabacloud/models/UpdateDictRequestFilesOssObject.hpp>
#include <alibabacloud/models/UpdateDictRequestFiles.hpp>
#include <alibabacloud/models/UpdateEndpointRequestEndpointZones.hpp>
#include <alibabacloud/models/UpdateEndpointResponseBodyResult.hpp>
#include <alibabacloud/models/UpdateNetworkRequestBodyWhiteIpGroup.hpp>
#include <alibabacloud/models/UpdateNetworkRequestBody.hpp>
#include <alibabacloud/models/UpdateNetworkResponseBodyResultWhiteIpGroup.hpp>
#include <alibabacloud/models/UpdateNetworkResponseBodyResult.hpp>

#endif
