// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_PAISTUDIO20210202MODEL_HPP_
#define ALIBABACLOUD_PAISTUDIO20210202MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CopyExperimentRequest.hpp>
#include <alibabacloud/models/CopyExperimentResponseBody.hpp>
#include <alibabacloud/models/CopyExperimentResponse.hpp>
#include <alibabacloud/models/CreateExperimentRequest.hpp>
#include <alibabacloud/models/CreateExperimentResponseBody.hpp>
#include <alibabacloud/models/CreateExperimentResponse.hpp>
#include <alibabacloud/models/CreateExperimentFolderRequest.hpp>
#include <alibabacloud/models/CreateExperimentFolderResponseBody.hpp>
#include <alibabacloud/models/CreateExperimentFolderResponse.hpp>
#include <alibabacloud/models/CreateExperimentMigrateValidationRequest.hpp>
#include <alibabacloud/models/CreateExperimentMigrateValidationResponseBody.hpp>
#include <alibabacloud/models/CreateExperimentMigrateValidationResponse.hpp>
#include <alibabacloud/models/CreateJobRequest.hpp>
#include <alibabacloud/models/CreateJobResponseBody.hpp>
#include <alibabacloud/models/CreateJobResponse.hpp>
#include <alibabacloud/models/DeleteExperimentResponseBody.hpp>
#include <alibabacloud/models/DeleteExperimentResponse.hpp>
#include <alibabacloud/models/DeleteExperimentFolderResponseBody.hpp>
#include <alibabacloud/models/DeleteExperimentFolderResponse.hpp>
#include <alibabacloud/models/GetAlgoTreeRequest.hpp>
#include <alibabacloud/models/GetAlgoTreeResponseBody.hpp>
#include <alibabacloud/models/GetAlgoTreeResponse.hpp>
#include <alibabacloud/models/GetAlgorithmDefRequest.hpp>
#include <alibabacloud/models/GetAlgorithmDefResponseBody.hpp>
#include <alibabacloud/models/GetAlgorithmDefResponse.hpp>
#include <alibabacloud/models/GetAlgorithmDefsRequest.hpp>
#include <alibabacloud/models/GetAlgorithmDefsResponseBody.hpp>
#include <alibabacloud/models/GetAlgorithmDefsResponse.hpp>
#include <alibabacloud/models/GetAlgorithmTreeRequest.hpp>
#include <alibabacloud/models/GetAlgorithmTreeResponseBody.hpp>
#include <alibabacloud/models/GetAlgorithmTreeResponse.hpp>
#include <alibabacloud/models/GetExperimentResponseBody.hpp>
#include <alibabacloud/models/GetExperimentResponse.hpp>
#include <alibabacloud/models/GetExperimentFolderChildrenRequest.hpp>
#include <alibabacloud/models/GetExperimentFolderChildrenResponseBody.hpp>
#include <alibabacloud/models/GetExperimentFolderChildrenResponse.hpp>
#include <alibabacloud/models/GetExperimentMetaResponseBody.hpp>
#include <alibabacloud/models/GetExperimentMetaResponse.hpp>
#include <alibabacloud/models/GetExperimentStatusResponseBody.hpp>
#include <alibabacloud/models/GetExperimentStatusResponse.hpp>
#include <alibabacloud/models/GetExperimentVisualizationMetaRequest.hpp>
#include <alibabacloud/models/GetExperimentVisualizationMetaResponseBody.hpp>
#include <alibabacloud/models/GetExperimentVisualizationMetaResponse.hpp>
#include <alibabacloud/models/GetExperimentsStatisticsRequest.hpp>
#include <alibabacloud/models/GetExperimentsStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetExperimentsStatisticsResponse.hpp>
#include <alibabacloud/models/GetExperimentsUsersStatisticsRequest.hpp>
#include <alibabacloud/models/GetExperimentsUsersStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetExperimentsUsersStatisticsResponse.hpp>
#include <alibabacloud/models/GetJobRequest.hpp>
#include <alibabacloud/models/GetJobResponseBody.hpp>
#include <alibabacloud/models/GetJobResponse.hpp>
#include <alibabacloud/models/GetMcTableSchemaRequest.hpp>
#include <alibabacloud/models/GetMcTableSchemaResponseBody.hpp>
#include <alibabacloud/models/GetMcTableSchemaResponse.hpp>
#include <alibabacloud/models/GetNodeInputSchemaRequest.hpp>
#include <alibabacloud/models/GetNodeInputSchemaResponseBody.hpp>
#include <alibabacloud/models/GetNodeInputSchemaResponse.hpp>
#include <alibabacloud/models/GetNodeOutputRequest.hpp>
#include <alibabacloud/models/GetNodeOutputResponseBody.hpp>
#include <alibabacloud/models/GetNodeOutputResponse.hpp>
#include <alibabacloud/models/GetTemplateRequest.hpp>
#include <alibabacloud/models/GetTemplateResponseBody.hpp>
#include <alibabacloud/models/GetTemplateResponse.hpp>
#include <alibabacloud/models/ListAuthRolesRequest.hpp>
#include <alibabacloud/models/ListAuthRolesResponseBody.hpp>
#include <alibabacloud/models/ListAuthRolesResponse.hpp>
#include <alibabacloud/models/ListExperimentsRequest.hpp>
#include <alibabacloud/models/ListExperimentsResponseBody.hpp>
#include <alibabacloud/models/ListExperimentsResponse.hpp>
#include <alibabacloud/models/ListImageLabelsRequest.hpp>
#include <alibabacloud/models/ListImageLabelsResponseBody.hpp>
#include <alibabacloud/models/ListImageLabelsResponse.hpp>
#include <alibabacloud/models/ListImagesRequest.hpp>
#include <alibabacloud/models/ListImagesResponseBody.hpp>
#include <alibabacloud/models/ListImagesResponse.hpp>
#include <alibabacloud/models/ListJobsRequest.hpp>
#include <alibabacloud/models/ListJobsResponseBody.hpp>
#include <alibabacloud/models/ListJobsResponse.hpp>
#include <alibabacloud/models/ListNodeOutputsResponseBody.hpp>
#include <alibabacloud/models/ListNodeOutputsResponse.hpp>
#include <alibabacloud/models/ListRecentExperimentsRequest.hpp>
#include <alibabacloud/models/ListRecentExperimentsResponseBody.hpp>
#include <alibabacloud/models/ListRecentExperimentsResponse.hpp>
#include <alibabacloud/models/ListTemplatesRequest.hpp>
#include <alibabacloud/models/ListTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListTemplatesResponse.hpp>
#include <alibabacloud/models/MigrateExperimentFoldersRequest.hpp>
#include <alibabacloud/models/MigrateExperimentFoldersResponseBody.hpp>
#include <alibabacloud/models/MigrateExperimentFoldersResponse.hpp>
#include <alibabacloud/models/MigrateExperimentsRequest.hpp>
#include <alibabacloud/models/MigrateExperimentsResponseBody.hpp>
#include <alibabacloud/models/MigrateExperimentsResponse.hpp>
#include <alibabacloud/models/PreviewMcTableRequest.hpp>
#include <alibabacloud/models/PreviewMcTableResponseBody.hpp>
#include <alibabacloud/models/PreviewMcTableResponse.hpp>
#include <alibabacloud/models/PublishExperimentRequest.hpp>
#include <alibabacloud/models/PublishExperimentResponseBody.hpp>
#include <alibabacloud/models/PublishExperimentResponse.hpp>
#include <alibabacloud/models/QueryExperimentVisualizationDataRequest.hpp>
#include <alibabacloud/models/QueryExperimentVisualizationDataResponseBody.hpp>
#include <alibabacloud/models/QueryExperimentVisualizationDataResponse.hpp>
#include <alibabacloud/models/SearchMcTablesRequest.hpp>
#include <alibabacloud/models/SearchMcTablesResponseBody.hpp>
#include <alibabacloud/models/SearchMcTablesResponse.hpp>
#include <alibabacloud/models/StopExperimentResponseBody.hpp>
#include <alibabacloud/models/StopExperimentResponse.hpp>
#include <alibabacloud/models/StopJobResponseBody.hpp>
#include <alibabacloud/models/StopJobResponse.hpp>
#include <alibabacloud/models/UpdateExperimentContentRequest.hpp>
#include <alibabacloud/models/UpdateExperimentContentResponseBody.hpp>
#include <alibabacloud/models/UpdateExperimentContentResponse.hpp>
#include <alibabacloud/models/UpdateExperimentFolderRequest.hpp>
#include <alibabacloud/models/UpdateExperimentFolderResponseBody.hpp>
#include <alibabacloud/models/UpdateExperimentFolderResponse.hpp>
#include <alibabacloud/models/UpdateExperimentMetaRequest.hpp>
#include <alibabacloud/models/UpdateExperimentMetaResponseBody.hpp>
#include <alibabacloud/models/UpdateExperimentMetaResponse.hpp>
#include <alibabacloud/models/GetExperimentFolderChildrenResponseBodyItems.hpp>
#include <alibabacloud/models/GetExperimentStatusResponseBodyNodes.hpp>
#include <alibabacloud/models/GetExperimentVisualizationMetaResponseBodyVisualizationMeta.hpp>
#include <alibabacloud/models/GetExperimentsStatisticsResponseBodyData.hpp>
#include <alibabacloud/models/GetExperimentsUsersStatisticsResponseBodyUsers.hpp>
#include <alibabacloud/models/GetMcTableSchemaResponseBodyColumns.hpp>
#include <alibabacloud/models/ListAuthRolesResponseBodyRolesToken.hpp>
#include <alibabacloud/models/ListAuthRolesResponseBodyRoles.hpp>
#include <alibabacloud/models/ListExperimentsResponseBodyExperiments.hpp>
#include <alibabacloud/models/ListImageLabelsResponseBodyLabels.hpp>
#include <alibabacloud/models/ListImagesResponseBodyImagesLabels.hpp>
#include <alibabacloud/models/ListImagesResponseBodyImages.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobs.hpp>
#include <alibabacloud/models/ListNodeOutputsResponseBodyOutputs.hpp>
#include <alibabacloud/models/ListRecentExperimentsResponseBodyExperiments.hpp>
#include <alibabacloud/models/ListTemplatesResponseBodyTemplateDataTemplate.hpp>
#include <alibabacloud/models/ListTemplatesResponseBodyTemplateDataTemplateTag.hpp>
#include <alibabacloud/models/ListTemplatesResponseBodyTemplateDataTemplateType.hpp>
#include <alibabacloud/models/ListTemplatesResponseBodyTemplateData.hpp>
#include <alibabacloud/models/MigrateExperimentsResponseBodyData.hpp>
#include <alibabacloud/models/QueryExperimentVisualizationDataRequestBody.hpp>
#include <alibabacloud/models/QueryExperimentVisualizationDataResponseBodyVisualizationData.hpp>

#endif
