// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_RESOURCECENTER20221201MODEL_HPP_
#define ALIBABACLOUD_RESOURCECENTER20221201MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AssociateDefaultFilterRequest.hpp>
#include <alibabacloud/models/AssociateDefaultFilterResponseBody.hpp>
#include <alibabacloud/models/AssociateDefaultFilterResponse.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequest.hpp>
#include <alibabacloud/models/CreateDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/CreateDeliveryChannelResponse.hpp>
#include <alibabacloud/models/CreateFilterRequest.hpp>
#include <alibabacloud/models/CreateFilterResponseBody.hpp>
#include <alibabacloud/models/CreateFilterResponse.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequest.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelResponse.hpp>
#include <alibabacloud/models/CreateSavedQueryRequest.hpp>
#include <alibabacloud/models/CreateSavedQueryResponseBody.hpp>
#include <alibabacloud/models/CreateSavedQueryResponse.hpp>
#include <alibabacloud/models/DeleteDeliveryChannelRequest.hpp>
#include <alibabacloud/models/DeleteDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteDeliveryChannelResponse.hpp>
#include <alibabacloud/models/DeleteFilterRequest.hpp>
#include <alibabacloud/models/DeleteFilterResponseBody.hpp>
#include <alibabacloud/models/DeleteFilterResponse.hpp>
#include <alibabacloud/models/DeleteMultiAccountDeliveryChannelRequest.hpp>
#include <alibabacloud/models/DeleteMultiAccountDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteMultiAccountDeliveryChannelResponse.hpp>
#include <alibabacloud/models/DeleteSavedQueryRequest.hpp>
#include <alibabacloud/models/DeleteSavedQueryResponseBody.hpp>
#include <alibabacloud/models/DeleteSavedQueryResponse.hpp>
#include <alibabacloud/models/DisableMultiAccountResourceCenterResponseBody.hpp>
#include <alibabacloud/models/DisableMultiAccountResourceCenterResponse.hpp>
#include <alibabacloud/models/DisableResourceCenterResponseBody.hpp>
#include <alibabacloud/models/DisableResourceCenterResponse.hpp>
#include <alibabacloud/models/DisassociateDefaultFilterResponseBody.hpp>
#include <alibabacloud/models/DisassociateDefaultFilterResponse.hpp>
#include <alibabacloud/models/EnableMultiAccountResourceCenterResponseBody.hpp>
#include <alibabacloud/models/EnableMultiAccountResourceCenterResponse.hpp>
#include <alibabacloud/models/EnableResourceCenterResponseBody.hpp>
#include <alibabacloud/models/EnableResourceCenterResponse.hpp>
#include <alibabacloud/models/ExecuteMultiAccountSqlqueryRequest.hpp>
#include <alibabacloud/models/ExecuteMultiAccountSqlqueryResponseBody.hpp>
#include <alibabacloud/models/ExecuteMultiAccountSqlqueryResponse.hpp>
#include <alibabacloud/models/ExecuteSqlqueryRequest.hpp>
#include <alibabacloud/models/ExecuteSqlqueryResponseBody.hpp>
#include <alibabacloud/models/ExecuteSqlqueryResponse.hpp>
#include <alibabacloud/models/GetDeliveryChannelRequest.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponse.hpp>
#include <alibabacloud/models/GetDeliveryChannelStatisticsRequest.hpp>
#include <alibabacloud/models/GetDeliveryChannelStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetDeliveryChannelStatisticsResponse.hpp>
#include <alibabacloud/models/GetExampleQueryRequest.hpp>
#include <alibabacloud/models/GetExampleQueryResponseBody.hpp>
#include <alibabacloud/models/GetExampleQueryResponse.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelRequest.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponse.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelStatisticsRequest.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelStatisticsResponse.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCenterServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCenterServiceStatusResponse.hpp>
#include <alibabacloud/models/GetMultiAccountResourceConfigurationRequest.hpp>
#include <alibabacloud/models/GetMultiAccountResourceConfigurationResponseBody.hpp>
#include <alibabacloud/models/GetMultiAccountResourceConfigurationResponse.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsRequest.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsResponseBody.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsResponse.hpp>
#include <alibabacloud/models/GetResourceCenterServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetResourceCenterServiceStatusResponse.hpp>
#include <alibabacloud/models/GetResourceConfigurationRequest.hpp>
#include <alibabacloud/models/GetResourceConfigurationResponseBody.hpp>
#include <alibabacloud/models/GetResourceConfigurationResponse.hpp>
#include <alibabacloud/models/GetResourceCountsRequest.hpp>
#include <alibabacloud/models/GetResourceCountsResponseBody.hpp>
#include <alibabacloud/models/GetResourceCountsResponse.hpp>
#include <alibabacloud/models/GetSavedQueryRequest.hpp>
#include <alibabacloud/models/GetSavedQueryResponseBody.hpp>
#include <alibabacloud/models/GetSavedQueryResponse.hpp>
#include <alibabacloud/models/ListDeliveryChannelsRequest.hpp>
#include <alibabacloud/models/ListDeliveryChannelsResponseBody.hpp>
#include <alibabacloud/models/ListDeliveryChannelsResponse.hpp>
#include <alibabacloud/models/ListExampleQueriesRequest.hpp>
#include <alibabacloud/models/ListExampleQueriesResponseBody.hpp>
#include <alibabacloud/models/ListExampleQueriesResponse.hpp>
#include <alibabacloud/models/ListFiltersResponseBody.hpp>
#include <alibabacloud/models/ListFiltersResponse.hpp>
#include <alibabacloud/models/ListMultiAccountDeliveryChannelsRequest.hpp>
#include <alibabacloud/models/ListMultiAccountDeliveryChannelsResponseBody.hpp>
#include <alibabacloud/models/ListMultiAccountDeliveryChannelsResponse.hpp>
#include <alibabacloud/models/ListMultiAccountResourceGroupsRequest.hpp>
#include <alibabacloud/models/ListMultiAccountResourceGroupsResponseBody.hpp>
#include <alibabacloud/models/ListMultiAccountResourceGroupsResponse.hpp>
#include <alibabacloud/models/ListMultiAccountResourceRelationshipsRequest.hpp>
#include <alibabacloud/models/ListMultiAccountResourceRelationshipsResponseBody.hpp>
#include <alibabacloud/models/ListMultiAccountResourceRelationshipsResponse.hpp>
#include <alibabacloud/models/ListMultiAccountTagKeysRequest.hpp>
#include <alibabacloud/models/ListMultiAccountTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListMultiAccountTagKeysResponse.hpp>
#include <alibabacloud/models/ListMultiAccountTagValuesRequest.hpp>
#include <alibabacloud/models/ListMultiAccountTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListMultiAccountTagValuesResponse.hpp>
#include <alibabacloud/models/ListResourceRelationshipsRequest.hpp>
#include <alibabacloud/models/ListResourceRelationshipsResponseBody.hpp>
#include <alibabacloud/models/ListResourceRelationshipsResponse.hpp>
#include <alibabacloud/models/ListResourceTypesRequest.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBody.hpp>
#include <alibabacloud/models/ListResourceTypesResponse.hpp>
#include <alibabacloud/models/ListSavedQueriesRequest.hpp>
#include <alibabacloud/models/ListSavedQueriesResponseBody.hpp>
#include <alibabacloud/models/ListSavedQueriesResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesRequest.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponseBody.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponse.hpp>
#include <alibabacloud/models/SearchResourcesRequest.hpp>
#include <alibabacloud/models/SearchResourcesResponseBody.hpp>
#include <alibabacloud/models/SearchResourcesResponse.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequest.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelResponse.hpp>
#include <alibabacloud/models/UpdateFilterRequest.hpp>
#include <alibabacloud/models/UpdateFilterResponseBody.hpp>
#include <alibabacloud/models/UpdateFilterResponse.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequest.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelResponseBody.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelResponse.hpp>
#include <alibabacloud/models/UpdateSavedQueryRequest.hpp>
#include <alibabacloud/models/UpdateSavedQueryResponseBody.hpp>
#include <alibabacloud/models/UpdateSavedQueryResponse.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequestDeliveryChannelFilter.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequestResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequestResourceChangeDelivery.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequestResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/CreateDeliveryChannelRequestResourceSnapshotDelivery.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequestDeliveryChannelFilter.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequestResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequestResourceChangeDelivery.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequestResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/CreateMultiAccountDeliveryChannelRequestResourceSnapshotDelivery.hpp>
#include <alibabacloud/models/ExecuteMultiAccountSqlqueryResponseBodyColumns.hpp>
#include <alibabacloud/models/ExecuteSqlqueryResponseBodyColumns.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBodyDeliveryChannelFilter.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBodyResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBodyResourceChangeDelivery.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBodyResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/GetDeliveryChannelResponseBodyResourceSnapshotDelivery.hpp>
#include <alibabacloud/models/GetDeliveryChannelStatisticsResponseBodyDeliveryChannelStatistics.hpp>
#include <alibabacloud/models/GetExampleQueryResponseBodyExampleQuery.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBodyDeliveryChannelFilter.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBodyResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBodyResourceChangeDelivery.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBodyResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelResponseBodyResourceSnapshotDelivery.hpp>
#include <alibabacloud/models/GetMultiAccountDeliveryChannelStatisticsResponseBodyDeliveryChannelStatistics.hpp>
#include <alibabacloud/models/GetMultiAccountResourceConfigurationResponseBodyIpAddressAttributes.hpp>
#include <alibabacloud/models/GetMultiAccountResourceConfigurationResponseBodyTags.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsRequestFilter.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsResponseBodyFilters.hpp>
#include <alibabacloud/models/GetMultiAccountResourceCountsResponseBodyResourceCounts.hpp>
#include <alibabacloud/models/GetResourceConfigurationResponseBodyIpAddressAttributes.hpp>
#include <alibabacloud/models/GetResourceConfigurationResponseBodyTags.hpp>
#include <alibabacloud/models/GetResourceCountsRequestFilter.hpp>
#include <alibabacloud/models/GetResourceCountsResponseBodyFilters.hpp>
#include <alibabacloud/models/GetResourceCountsResponseBodyResourceCounts.hpp>
#include <alibabacloud/models/GetSavedQueryResponseBodySavedQuery.hpp>
#include <alibabacloud/models/ListDeliveryChannelsResponseBodyDeliveryChannels.hpp>
#include <alibabacloud/models/ListExampleQueriesResponseBodyExampleQueries.hpp>
#include <alibabacloud/models/ListFiltersResponseBodyFilters.hpp>
#include <alibabacloud/models/ListMultiAccountDeliveryChannelsResponseBodyDeliveryChannels.hpp>
#include <alibabacloud/models/ListMultiAccountResourceGroupsResponseBodyResourceGroups.hpp>
#include <alibabacloud/models/ListMultiAccountResourceRelationshipsRequestRelatedResourceFilter.hpp>
#include <alibabacloud/models/ListMultiAccountResourceRelationshipsResponseBodyResourceRelationships.hpp>
#include <alibabacloud/models/ListResourceRelationshipsRequestRelatedResourceFilter.hpp>
#include <alibabacloud/models/ListResourceRelationshipsResponseBodyResourceRelationships.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesCodeMapping.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypes.hpp>
#include <alibabacloud/models/ListSavedQueriesResponseBodySavedQueries.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesRequestFilter.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesRequestSortCriterion.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponseBodyFilters.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponseBodyResourcesIpAddressAttributes.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponseBodyResourcesTags.hpp>
#include <alibabacloud/models/SearchMultiAccountResourcesResponseBodyResources.hpp>
#include <alibabacloud/models/SearchResourcesRequestFilter.hpp>
#include <alibabacloud/models/SearchResourcesRequestSortCriterion.hpp>
#include <alibabacloud/models/SearchResourcesResponseBodyFilters.hpp>
#include <alibabacloud/models/SearchResourcesResponseBodyResourcesIpAddressAttributes.hpp>
#include <alibabacloud/models/SearchResourcesResponseBodyResourcesTags.hpp>
#include <alibabacloud/models/SearchResourcesResponseBodyResources.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequestDeliveryChannelFilter.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequestResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequestResourceChangeDelivery.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequestResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/UpdateDeliveryChannelRequestResourceSnapshotDelivery.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequestDeliveryChannelFilter.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequestResourceChangeDeliverySlsProperties.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequestResourceChangeDelivery.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequestResourceSnapshotDeliverySlsProperties.hpp>
#include <alibabacloud/models/UpdateMultiAccountDeliveryChannelRequestResourceSnapshotDelivery.hpp>

#endif
