// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLOUDCONTROL20220830MODEL_HPP_
#define ALIBABACLOUD_CLOUDCONTROL20220830MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CancelTaskResponseBody.hpp>
#include <alibabacloud/models/CancelTaskResponse.hpp>
#include <alibabacloud/models/CreateResourceRequest.hpp>
#include <alibabacloud/models/CreateResourceResponseBody.hpp>
#include <alibabacloud/models/CreateResourceResponse.hpp>
#include <alibabacloud/models/DeleteResourceRequest.hpp>
#include <alibabacloud/models/DeleteResourceShrinkRequest.hpp>
#include <alibabacloud/models/DeleteResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteResourceResponse.hpp>
#include <alibabacloud/models/GetPriceRequest.hpp>
#include <alibabacloud/models/GetPriceShrinkRequest.hpp>
#include <alibabacloud/models/GetPriceResponseBody.hpp>
#include <alibabacloud/models/GetPriceResponse.hpp>
#include <alibabacloud/models/GetResourceTypeHeaders.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBody.hpp>
#include <alibabacloud/models/GetResourceTypeResponse.hpp>
#include <alibabacloud/models/GetResourcesRequest.hpp>
#include <alibabacloud/models/GetResourcesShrinkRequest.hpp>
#include <alibabacloud/models/GetResourcesResponseBody.hpp>
#include <alibabacloud/models/GetResourcesResponse.hpp>
#include <alibabacloud/models/GetTaskResponseBody.hpp>
#include <alibabacloud/models/GetTaskResponse.hpp>
#include <alibabacloud/models/ListDataSourcesRequest.hpp>
#include <alibabacloud/models/ListDataSourcesShrinkRequest.hpp>
#include <alibabacloud/models/ListDataSourcesResponseBody.hpp>
#include <alibabacloud/models/ListDataSourcesResponse.hpp>
#include <alibabacloud/models/ListProductsHeaders.hpp>
#include <alibabacloud/models/ListProductsRequest.hpp>
#include <alibabacloud/models/ListProductsResponseBody.hpp>
#include <alibabacloud/models/ListProductsResponse.hpp>
#include <alibabacloud/models/ListResourceTypesHeaders.hpp>
#include <alibabacloud/models/ListResourceTypesRequest.hpp>
#include <alibabacloud/models/ListResourceTypesShrinkRequest.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBody.hpp>
#include <alibabacloud/models/ListResourceTypesResponse.hpp>
#include <alibabacloud/models/UpdateResourceRequest.hpp>
#include <alibabacloud/models/UpdateResourceResponseBody.hpp>
#include <alibabacloud/models/UpdateResourceResponse.hpp>
#include <alibabacloud/models/GetPriceResponseBodyPriceModuleDetails.hpp>
#include <alibabacloud/models/GetPriceResponseBodyPricePromotionDetails.hpp>
#include <alibabacloud/models/GetPriceResponseBodyPrice.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlersCreate.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlersDelete.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlersGet.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlersList.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlersUpdate.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeHandlers.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceTypeInfo.hpp>
#include <alibabacloud/models/GetResourceTypeResponseBodyResourceType.hpp>
#include <alibabacloud/models/GetResourcesResponseBodyResource.hpp>
#include <alibabacloud/models/GetResourcesResponseBodyResources.hpp>
#include <alibabacloud/models/GetTaskResponseBodyTaskError.hpp>
#include <alibabacloud/models/GetTaskResponseBodyTask.hpp>
#include <alibabacloud/models/ListDataSourcesResponseBodyDataSources.hpp>
#include <alibabacloud/models/ListProductsResponseBodyProducts.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlersCreate.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlersDelete.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlersGet.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlersList.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlersUpdate.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesHandlers.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypesInfo.hpp>
#include <alibabacloud/models/ListResourceTypesResponseBodyResourceTypes.hpp>

#endif
