// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MSSP20161228MODEL_HPP_
#define ALIBABACLOUD_MSSP20161228MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ConfirmDjbhReportRequest.hpp>
#include <alibabacloud/models/ConfirmDjbhReportResponseBody.hpp>
#include <alibabacloud/models/ConfirmDjbhReportResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateServiceWorkOrderRequest.hpp>
#include <alibabacloud/models/CreateServiceWorkOrderResponseBody.hpp>
#include <alibabacloud/models/CreateServiceWorkOrderResponse.hpp>
#include <alibabacloud/models/DeleteDjbhReportRequest.hpp>
#include <alibabacloud/models/DeleteDjbhReportResponseBody.hpp>
#include <alibabacloud/models/DeleteDjbhReportResponse.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/DescribeServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/DisposeServiceWorkOrderRequest.hpp>
#include <alibabacloud/models/DisposeServiceWorkOrderResponseBody.hpp>
#include <alibabacloud/models/DisposeServiceWorkOrderResponse.hpp>
#include <alibabacloud/models/DisposeWorkTaskRequest.hpp>
#include <alibabacloud/models/DisposeWorkTaskShrinkRequest.hpp>
#include <alibabacloud/models/DisposeWorkTaskResponseBody.hpp>
#include <alibabacloud/models/DisposeWorkTaskResponse.hpp>
#include <alibabacloud/models/GetAlarmDetailByIdRequest.hpp>
#include <alibabacloud/models/GetAlarmDetailByIdResponseBody.hpp>
#include <alibabacloud/models/GetAlarmDetailByIdResponse.hpp>
#include <alibabacloud/models/GetAttackedAssetDealRequest.hpp>
#include <alibabacloud/models/GetAttackedAssetDealResponseBody.hpp>
#include <alibabacloud/models/GetAttackedAssetDealResponse.hpp>
#include <alibabacloud/models/GetBaselineSummaryRequest.hpp>
#include <alibabacloud/models/GetBaselineSummaryResponseBody.hpp>
#include <alibabacloud/models/GetBaselineSummaryResponse.hpp>
#include <alibabacloud/models/GetConsoleScoreRequest.hpp>
#include <alibabacloud/models/GetConsoleScoreResponseBody.hpp>
#include <alibabacloud/models/GetConsoleScoreResponse.hpp>
#include <alibabacloud/models/GetDetailByIdRequest.hpp>
#include <alibabacloud/models/GetDetailByIdResponseBody.hpp>
#include <alibabacloud/models/GetDetailByIdResponse.hpp>
#include <alibabacloud/models/GetDocumentDownloadUrlRequest.hpp>
#include <alibabacloud/models/GetDocumentDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/GetDocumentDownloadUrlResponse.hpp>
#include <alibabacloud/models/GetDocumentPageRequest.hpp>
#include <alibabacloud/models/GetDocumentPageResponseBody.hpp>
#include <alibabacloud/models/GetDocumentPageResponse.hpp>
#include <alibabacloud/models/GetDocumentSummaryRequest.hpp>
#include <alibabacloud/models/GetDocumentSummaryResponseBody.hpp>
#include <alibabacloud/models/GetDocumentSummaryResponse.hpp>
#include <alibabacloud/models/GetRecentDocumentRequest.hpp>
#include <alibabacloud/models/GetRecentDocumentResponseBody.hpp>
#include <alibabacloud/models/GetRecentDocumentResponse.hpp>
#include <alibabacloud/models/GetSafetyCoverRequest.hpp>
#include <alibabacloud/models/GetSafetyCoverResponseBody.hpp>
#include <alibabacloud/models/GetSafetyCoverResponse.hpp>
#include <alibabacloud/models/GetSowListRequest.hpp>
#include <alibabacloud/models/GetSowListResponseBody.hpp>
#include <alibabacloud/models/GetSowListResponse.hpp>
#include <alibabacloud/models/GetSuspEventPageRequest.hpp>
#include <alibabacloud/models/GetSuspEventPageResponseBody.hpp>
#include <alibabacloud/models/GetSuspEventPageResponse.hpp>
#include <alibabacloud/models/GetSuspEventSummaryRequest.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBody.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponse.hpp>
#include <alibabacloud/models/GetSuspPageSummaryResponseBody.hpp>
#include <alibabacloud/models/GetSuspPageSummaryResponse.hpp>
#include <alibabacloud/models/GetUserStatusResponseBody.hpp>
#include <alibabacloud/models/GetUserStatusResponse.hpp>
#include <alibabacloud/models/GetVulItemPageRequest.hpp>
#include <alibabacloud/models/GetVulItemPageResponseBody.hpp>
#include <alibabacloud/models/GetVulItemPageResponse.hpp>
#include <alibabacloud/models/GetVulListByIdRequest.hpp>
#include <alibabacloud/models/GetVulListByIdResponseBody.hpp>
#include <alibabacloud/models/GetVulListByIdResponse.hpp>
#include <alibabacloud/models/GetVulPageSummaryResponseBody.hpp>
#include <alibabacloud/models/GetVulPageSummaryResponse.hpp>
#include <alibabacloud/models/GetVulSummaryRequest.hpp>
#include <alibabacloud/models/GetVulSummaryResponseBody.hpp>
#include <alibabacloud/models/GetVulSummaryResponse.hpp>
#include <alibabacloud/models/GetWorkTaskSummaryRequest.hpp>
#include <alibabacloud/models/GetWorkTaskSummaryResponseBody.hpp>
#include <alibabacloud/models/GetWorkTaskSummaryResponse.hpp>
#include <alibabacloud/models/PageServiceCustomerRequest.hpp>
#include <alibabacloud/models/PageServiceCustomerResponseBody.hpp>
#include <alibabacloud/models/PageServiceCustomerResponse.hpp>
#include <alibabacloud/models/SendCustomEventRequest.hpp>
#include <alibabacloud/models/SendCustomEventResponseBody.hpp>
#include <alibabacloud/models/SendCustomEventResponse.hpp>
#include <alibabacloud/models/CreateServiceWorkOrderResponseBodyData.hpp>
#include <alibabacloud/models/DisposeWorkTaskRequestWorkTaskAnalysisResults.hpp>
#include <alibabacloud/models/GetAlarmDetailByIdResponseBodyDataEventDetails.hpp>
#include <alibabacloud/models/GetAlarmDetailByIdResponseBodyData.hpp>
#include <alibabacloud/models/GetAttackedAssetDealResponseBodyDataEcsTrendList.hpp>
#include <alibabacloud/models/GetAttackedAssetDealResponseBodyData.hpp>
#include <alibabacloud/models/GetBaselineSummaryResponseBodyDataTrendDtoList.hpp>
#include <alibabacloud/models/GetBaselineSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetDetailByIdResponseBodyDataVulDetails.hpp>
#include <alibabacloud/models/GetDetailByIdResponseBodyData.hpp>
#include <alibabacloud/models/GetDocumentPageResponseBodyData.hpp>
#include <alibabacloud/models/GetDocumentPageResponseBodyPageInfo.hpp>
#include <alibabacloud/models/GetDocumentSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetRecentDocumentResponseBodyData.hpp>
#include <alibabacloud/models/GetSafetyCoverResponseBodyDataCfwProtection.hpp>
#include <alibabacloud/models/GetSafetyCoverResponseBodyDataEcsProtection.hpp>
#include <alibabacloud/models/GetSafetyCoverResponseBodyDataWafProtection.hpp>
#include <alibabacloud/models/GetSafetyCoverResponseBodyData.hpp>
#include <alibabacloud/models/GetSowListResponseBodyData.hpp>
#include <alibabacloud/models/GetSuspEventPageResponseBodyData.hpp>
#include <alibabacloud/models/GetSuspEventPageResponseBodyPageInfo.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataNetworkAttackTrendDtoTrendList.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataNetworkAttackTrendDto.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataSuspEventDealSummaryDto.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataSuspEventTopDtoSuspEventList.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataSuspEventTopDto.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataSuspEventTrendDtoTrendList.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyDataSuspEventTrendDto.hpp>
#include <alibabacloud/models/GetSuspEventSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetSuspPageSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetUserStatusResponseBodyData.hpp>
#include <alibabacloud/models/GetVulItemPageResponseBodyData.hpp>
#include <alibabacloud/models/GetVulItemPageResponseBodyPageInfo.hpp>
#include <alibabacloud/models/GetVulListByIdResponseBodyDataEffectMsgDtos.hpp>
#include <alibabacloud/models/GetVulListByIdResponseBodyData.hpp>
#include <alibabacloud/models/GetVulListByIdResponseBodyPageInfo.hpp>
#include <alibabacloud/models/GetVulPageSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetVulSummaryResponseBodyDataTrendList.hpp>
#include <alibabacloud/models/GetVulSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetWorkTaskSummaryResponseBodyData.hpp>
#include <alibabacloud/models/PageServiceCustomerResponseBodyData.hpp>
#include <alibabacloud/models/PageServiceCustomerResponseBodyPageInfo.hpp>
#include <alibabacloud/models/SendCustomEventResponseBodyData.hpp>

#endif
