// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DMSENTERPRISE20181101MODEL_HPP_
#define ALIBABACLOUD_DMSENTERPRISE20181101MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AsyncTaskVo.hpp>
#include <alibabacloud/models/ColumnKnowledgeInfo.hpp>
#include <alibabacloud/models/Dlcatalog.hpp>
#include <alibabacloud/models/Dlcolumn.hpp>
#include <alibabacloud/models/Dldatabase.hpp>
#include <alibabacloud/models/Dlfunction.hpp>
#include <alibabacloud/models/DlfunctionInput.hpp>
#include <alibabacloud/models/Dlorder.hpp>
#include <alibabacloud/models/Dlpartition.hpp>
#include <alibabacloud/models/DlpartitionInput.hpp>
#include <alibabacloud/models/DlresourceUri.hpp>
#include <alibabacloud/models/DlserdeInfo.hpp>
#include <alibabacloud/models/DlskewedInfo.hpp>
#include <alibabacloud/models/DlstorageDescriptor.hpp>
#include <alibabacloud/models/Dltable.hpp>
#include <alibabacloud/models/DltablebaseInfo.hpp>
#include <alibabacloud/models/DatasetItemVo.hpp>
#include <alibabacloud/models/GetTableDataKeyVo.hpp>
#include <alibabacloud/models/ImportMasterKeyVo.hpp>
#include <alibabacloud/models/MetaCategory.hpp>
#include <alibabacloud/models/MetaCategoryTableEntity.hpp>
#include <alibabacloud/models/PartitionError.hpp>
#include <alibabacloud/models/ProjectDetailsLiteVo.hpp>
#include <alibabacloud/models/StsApplyVo.hpp>
#include <alibabacloud/models/StsTokenVo.hpp>
#include <alibabacloud/models/TableKnowledgeInfo.hpp>
#include <alibabacloud/models/TeeEvidenceVo.hpp>
#include <alibabacloud/models/UsersDetailsVo.hpp>
#include <alibabacloud/models/OpenStructDltableInput.hpp>
#include <alibabacloud/models/AddAuthorityTemplateItemsRequest.hpp>
#include <alibabacloud/models/AddAuthorityTemplateItemsShrinkRequest.hpp>
#include <alibabacloud/models/AddAuthorityTemplateItemsResponseBody.hpp>
#include <alibabacloud/models/AddAuthorityTemplateItemsResponse.hpp>
#include <alibabacloud/models/AddDesensitizationRuleRequest.hpp>
#include <alibabacloud/models/AddDesensitizationRuleResponseBody.hpp>
#include <alibabacloud/models/AddDesensitizationRuleResponse.hpp>
#include <alibabacloud/models/AddInstanceRequest.hpp>
#include <alibabacloud/models/AddInstanceResponseBody.hpp>
#include <alibabacloud/models/AddInstanceResponse.hpp>
#include <alibabacloud/models/AddLhMembersRequest.hpp>
#include <alibabacloud/models/AddLhMembersShrinkRequest.hpp>
#include <alibabacloud/models/AddLhMembersResponseBody.hpp>
#include <alibabacloud/models/AddLhMembersResponse.hpp>
#include <alibabacloud/models/AddLogicTableRouteConfigRequest.hpp>
#include <alibabacloud/models/AddLogicTableRouteConfigResponseBody.hpp>
#include <alibabacloud/models/AddLogicTableRouteConfigResponse.hpp>
#include <alibabacloud/models/AddTableToCategoryRequest.hpp>
#include <alibabacloud/models/AddTableToCategoryResponseBody.hpp>
#include <alibabacloud/models/AddTableToCategoryResponse.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesRequest.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesShrinkRequest.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesResponseBody.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesResponse.hpp>
#include <alibabacloud/models/AnalyzeSqllineageRequest.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBody.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponse.hpp>
#include <alibabacloud/models/AnswerSqlSyntaxByMetaAgentRequest.hpp>
#include <alibabacloud/models/AnswerSqlSyntaxByMetaAgentResponseBody.hpp>
#include <alibabacloud/models/AnswerSqlSyntaxByMetaAgentResponse.hpp>
#include <alibabacloud/models/ApproveOrderRequest.hpp>
#include <alibabacloud/models/ApproveOrderResponseBody.hpp>
#include <alibabacloud/models/ApproveOrderResponse.hpp>
#include <alibabacloud/models/BackFillRequest.hpp>
#include <alibabacloud/models/BackFillShrinkRequest.hpp>
#include <alibabacloud/models/BackFillResponseBody.hpp>
#include <alibabacloud/models/BackFillResponse.hpp>
#include <alibabacloud/models/BatchCreateDataLakePartitionsRequest.hpp>
#include <alibabacloud/models/BatchCreateDataLakePartitionsShrinkRequest.hpp>
#include <alibabacloud/models/BatchCreateDataLakePartitionsResponseBody.hpp>
#include <alibabacloud/models/BatchCreateDataLakePartitionsResponse.hpp>
#include <alibabacloud/models/BatchDeleteDataLakePartitionsRequest.hpp>
#include <alibabacloud/models/BatchDeleteDataLakePartitionsResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDataLakePartitionsResponse.hpp>
#include <alibabacloud/models/BatchUpdateDataLakePartitionsRequest.hpp>
#include <alibabacloud/models/BatchUpdateDataLakePartitionsShrinkRequest.hpp>
#include <alibabacloud/models/BatchUpdateDataLakePartitionsResponseBody.hpp>
#include <alibabacloud/models/BatchUpdateDataLakePartitionsResponse.hpp>
#include <alibabacloud/models/BuyPayAsYouGoOrderRequest.hpp>
#include <alibabacloud/models/BuyPayAsYouGoOrderResponseBody.hpp>
#include <alibabacloud/models/BuyPayAsYouGoOrderResponse.hpp>
#include <alibabacloud/models/ChangeColumnSecLevelRequest.hpp>
#include <alibabacloud/models/ChangeColumnSecLevelResponseBody.hpp>
#include <alibabacloud/models/ChangeColumnSecLevelResponse.hpp>
#include <alibabacloud/models/ChangeColumnSecurityLevelRequest.hpp>
#include <alibabacloud/models/ChangeColumnSecurityLevelResponseBody.hpp>
#include <alibabacloud/models/ChangeColumnSecurityLevelResponse.hpp>
#include <alibabacloud/models/ChangeLhDagOwnerRequest.hpp>
#include <alibabacloud/models/ChangeLhDagOwnerResponseBody.hpp>
#include <alibabacloud/models/ChangeLhDagOwnerResponse.hpp>
#include <alibabacloud/models/CloseOrderRequest.hpp>
#include <alibabacloud/models/CloseOrderResponseBody.hpp>
#include <alibabacloud/models/CloseOrderResponse.hpp>
#include <alibabacloud/models/CreateAbacAuthorizationRequest.hpp>
#include <alibabacloud/models/CreateAbacAuthorizationResponseBody.hpp>
#include <alibabacloud/models/CreateAbacAuthorizationResponse.hpp>
#include <alibabacloud/models/CreateAbacPolicyRequest.hpp>
#include <alibabacloud/models/CreateAbacPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateAbacPolicyResponse.hpp>
#include <alibabacloud/models/CreateAuthorityTemplateRequest.hpp>
#include <alibabacloud/models/CreateAuthorityTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateAuthorityTemplateResponse.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderRequest.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderResponse.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderRequest.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderResponse.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderRequest.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderResponse.hpp>
#include <alibabacloud/models/CreateDataExportOrderRequest.hpp>
#include <alibabacloud/models/CreateDataExportOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataExportOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataExportOrderResponse.hpp>
#include <alibabacloud/models/CreateDataImportOrderRequest.hpp>
#include <alibabacloud/models/CreateDataImportOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataImportOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataImportOrderResponse.hpp>
#include <alibabacloud/models/CreateDataLakeDatabaseRequest.hpp>
#include <alibabacloud/models/CreateDataLakeDatabaseShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataLakeDatabaseResponseBody.hpp>
#include <alibabacloud/models/CreateDataLakeDatabaseResponse.hpp>
#include <alibabacloud/models/CreateDataLakeFunctionRequest.hpp>
#include <alibabacloud/models/CreateDataLakeFunctionShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataLakeFunctionResponseBody.hpp>
#include <alibabacloud/models/CreateDataLakeFunctionResponse.hpp>
#include <alibabacloud/models/CreateDataLakePartitionRequest.hpp>
#include <alibabacloud/models/CreateDataLakePartitionShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataLakePartitionResponseBody.hpp>
#include <alibabacloud/models/CreateDataLakePartitionResponse.hpp>
#include <alibabacloud/models/CreateDataLakeTableRequest.hpp>
#include <alibabacloud/models/CreateDataLakeTableShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataLakeTableResponseBody.hpp>
#include <alibabacloud/models/CreateDataLakeTableResponse.hpp>
#include <alibabacloud/models/CreateDataTrackOrderRequest.hpp>
#include <alibabacloud/models/CreateDataTrackOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataTrackOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDataTrackOrderResponse.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderRequest.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderResponseBody.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderResponse.hpp>
#include <alibabacloud/models/CreateDifyInstanceRequest.hpp>
#include <alibabacloud/models/CreateDifyInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateDifyInstanceResponse.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderRequest.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderResponseBody.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderResponse.hpp>
#include <alibabacloud/models/CreateLakeHouseSpaceRequest.hpp>
#include <alibabacloud/models/CreateLakeHouseSpaceResponseBody.hpp>
#include <alibabacloud/models/CreateLakeHouseSpaceResponse.hpp>
#include <alibabacloud/models/CreateLogicDatabaseRequest.hpp>
#include <alibabacloud/models/CreateLogicDatabaseShrinkRequest.hpp>
#include <alibabacloud/models/CreateLogicDatabaseResponseBody.hpp>
#include <alibabacloud/models/CreateLogicDatabaseResponse.hpp>
#include <alibabacloud/models/CreateMetaCategoryRequest.hpp>
#include <alibabacloud/models/CreateMetaCategoryResponseBody.hpp>
#include <alibabacloud/models/CreateMetaCategoryResponse.hpp>
#include <alibabacloud/models/CreateOrderRequest.hpp>
#include <alibabacloud/models/CreateOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateOrderResponseBody.hpp>
#include <alibabacloud/models/CreateOrderResponse.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderRequest.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderResponseBody.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderResponse.hpp>
#include <alibabacloud/models/CreateProxyRequest.hpp>
#include <alibabacloud/models/CreateProxyResponseBody.hpp>
#include <alibabacloud/models/CreateProxyResponse.hpp>
#include <alibabacloud/models/CreateProxyAccessRequest.hpp>
#include <alibabacloud/models/CreateProxyAccessResponseBody.hpp>
#include <alibabacloud/models/CreateProxyAccessResponse.hpp>
#include <alibabacloud/models/CreatePublishGroupTaskRequest.hpp>
#include <alibabacloud/models/CreatePublishGroupTaskResponseBody.hpp>
#include <alibabacloud/models/CreatePublishGroupTaskResponse.hpp>
#include <alibabacloud/models/CreateSqlreviewOrderRequest.hpp>
#include <alibabacloud/models/CreateSqlreviewOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateSqlreviewOrderResponseBody.hpp>
#include <alibabacloud/models/CreateSqlreviewOrderResponse.hpp>
#include <alibabacloud/models/CreateScenarioRequest.hpp>
#include <alibabacloud/models/CreateScenarioResponseBody.hpp>
#include <alibabacloud/models/CreateScenarioResponse.hpp>
#include <alibabacloud/models/CreateStandardGroupRequest.hpp>
#include <alibabacloud/models/CreateStandardGroupResponseBody.hpp>
#include <alibabacloud/models/CreateStandardGroupResponse.hpp>
#include <alibabacloud/models/CreateStructSyncOrderRequest.hpp>
#include <alibabacloud/models/CreateStructSyncOrderShrinkRequest.hpp>
#include <alibabacloud/models/CreateStructSyncOrderResponseBody.hpp>
#include <alibabacloud/models/CreateStructSyncOrderResponse.hpp>
#include <alibabacloud/models/CreateTaskRequest.hpp>
#include <alibabacloud/models/CreateTaskResponseBody.hpp>
#include <alibabacloud/models/CreateTaskResponse.hpp>
#include <alibabacloud/models/CreateTaskFlowRequest.hpp>
#include <alibabacloud/models/CreateTaskFlowResponseBody.hpp>
#include <alibabacloud/models/CreateTaskFlowResponse.hpp>
#include <alibabacloud/models/CreateUploadFileJobRequest.hpp>
#include <alibabacloud/models/CreateUploadFileJobResponseBody.hpp>
#include <alibabacloud/models/CreateUploadFileJobResponse.hpp>
#include <alibabacloud/models/CreateUploadOssfileJobRequest.hpp>
#include <alibabacloud/models/CreateUploadOssfileJobShrinkRequest.hpp>
#include <alibabacloud/models/CreateUploadOssfileJobResponseBody.hpp>
#include <alibabacloud/models/CreateUploadOssfileJobResponse.hpp>
#include <alibabacloud/models/CreateWorkspaceRequest.hpp>
#include <alibabacloud/models/CreateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/CreateWorkspaceResponse.hpp>
#include <alibabacloud/models/DeleteAbacAuthorizationRequest.hpp>
#include <alibabacloud/models/DeleteAbacAuthorizationResponseBody.hpp>
#include <alibabacloud/models/DeleteAbacAuthorizationResponse.hpp>
#include <alibabacloud/models/DeleteAbacPolicyRequest.hpp>
#include <alibabacloud/models/DeleteAbacPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteAbacPolicyResponse.hpp>
#include <alibabacloud/models/DeleteAuthorityTemplateRequest.hpp>
#include <alibabacloud/models/DeleteAuthorityTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteAuthorityTemplateResponse.hpp>
#include <alibabacloud/models/DeleteDataLakeDatabaseRequest.hpp>
#include <alibabacloud/models/DeleteDataLakeDatabaseResponseBody.hpp>
#include <alibabacloud/models/DeleteDataLakeDatabaseResponse.hpp>
#include <alibabacloud/models/DeleteDataLakeFunctionRequest.hpp>
#include <alibabacloud/models/DeleteDataLakeFunctionResponseBody.hpp>
#include <alibabacloud/models/DeleteDataLakeFunctionResponse.hpp>
#include <alibabacloud/models/DeleteDataLakePartitionRequest.hpp>
#include <alibabacloud/models/DeleteDataLakePartitionShrinkRequest.hpp>
#include <alibabacloud/models/DeleteDataLakePartitionResponseBody.hpp>
#include <alibabacloud/models/DeleteDataLakePartitionResponse.hpp>
#include <alibabacloud/models/DeleteDataLakeTableRequest.hpp>
#include <alibabacloud/models/DeleteDataLakeTableResponseBody.hpp>
#include <alibabacloud/models/DeleteDataLakeTableResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteLakeHouseSpaceRequest.hpp>
#include <alibabacloud/models/DeleteLakeHouseSpaceResponseBody.hpp>
#include <alibabacloud/models/DeleteLakeHouseSpaceResponse.hpp>
#include <alibabacloud/models/DeleteLhMembersRequest.hpp>
#include <alibabacloud/models/DeleteLhMembersShrinkRequest.hpp>
#include <alibabacloud/models/DeleteLhMembersResponseBody.hpp>
#include <alibabacloud/models/DeleteLhMembersResponse.hpp>
#include <alibabacloud/models/DeleteLogicDatabaseRequest.hpp>
#include <alibabacloud/models/DeleteLogicDatabaseResponseBody.hpp>
#include <alibabacloud/models/DeleteLogicDatabaseResponse.hpp>
#include <alibabacloud/models/DeleteLogicTableRouteConfigRequest.hpp>
#include <alibabacloud/models/DeleteLogicTableRouteConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteLogicTableRouteConfigResponse.hpp>
#include <alibabacloud/models/DeleteMetaCategoryRequest.hpp>
#include <alibabacloud/models/DeleteMetaCategoryResponseBody.hpp>
#include <alibabacloud/models/DeleteMetaCategoryResponse.hpp>
#include <alibabacloud/models/DeleteProxyRequest.hpp>
#include <alibabacloud/models/DeleteProxyResponseBody.hpp>
#include <alibabacloud/models/DeleteProxyResponse.hpp>
#include <alibabacloud/models/DeleteProxyAccessRequest.hpp>
#include <alibabacloud/models/DeleteProxyAccessResponseBody.hpp>
#include <alibabacloud/models/DeleteProxyAccessResponse.hpp>
#include <alibabacloud/models/DeleteScenarioRequest.hpp>
#include <alibabacloud/models/DeleteScenarioResponseBody.hpp>
#include <alibabacloud/models/DeleteScenarioResponse.hpp>
#include <alibabacloud/models/DeleteStandardGroupRequest.hpp>
#include <alibabacloud/models/DeleteStandardGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteStandardGroupResponse.hpp>
#include <alibabacloud/models/DeleteTaskRequest.hpp>
#include <alibabacloud/models/DeleteTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteTaskResponse.hpp>
#include <alibabacloud/models/DeleteTaskFlowRequest.hpp>
#include <alibabacloud/models/DeleteTaskFlowResponseBody.hpp>
#include <alibabacloud/models/DeleteTaskFlowResponse.hpp>
#include <alibabacloud/models/DeleteTaskFlowEdgesByConditionRequest.hpp>
#include <alibabacloud/models/DeleteTaskFlowEdgesByConditionResponseBody.hpp>
#include <alibabacloud/models/DeleteTaskFlowEdgesByConditionResponse.hpp>
#include <alibabacloud/models/DeleteUserRequest.hpp>
#include <alibabacloud/models/DeleteUserResponseBody.hpp>
#include <alibabacloud/models/DeleteUserResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceRequest.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponse.hpp>
#include <alibabacloud/models/DescribeDifyAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDifyAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDifyAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDifyDefaultVpcRequest.hpp>
#include <alibabacloud/models/DescribeDifyDefaultVpcResponseBody.hpp>
#include <alibabacloud/models/DescribeDifyDefaultVpcResponse.hpp>
#include <alibabacloud/models/DescribeDifyEditionsRequest.hpp>
#include <alibabacloud/models/DescribeDifyEditionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDifyEditionsResponse.hpp>
#include <alibabacloud/models/DescribeDifyRegionsRequest.hpp>
#include <alibabacloud/models/DescribeDifyRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDifyRegionsResponse.hpp>
#include <alibabacloud/models/DisableUserRequest.hpp>
#include <alibabacloud/models/DisableUserResponseBody.hpp>
#include <alibabacloud/models/DisableUserResponse.hpp>
#include <alibabacloud/models/DownloadDataTrackResultRequest.hpp>
#include <alibabacloud/models/DownloadDataTrackResultShrinkRequest.hpp>
#include <alibabacloud/models/DownloadDataTrackResultResponseBody.hpp>
#include <alibabacloud/models/DownloadDataTrackResultResponse.hpp>
#include <alibabacloud/models/EditLogicDatabaseRequest.hpp>
#include <alibabacloud/models/EditLogicDatabaseShrinkRequest.hpp>
#include <alibabacloud/models/EditLogicDatabaseResponseBody.hpp>
#include <alibabacloud/models/EditLogicDatabaseResponse.hpp>
#include <alibabacloud/models/EditMetaKnowledgeAssetRequest.hpp>
#include <alibabacloud/models/EditMetaKnowledgeAssetResponseBody.hpp>
#include <alibabacloud/models/EditMetaKnowledgeAssetResponse.hpp>
#include <alibabacloud/models/EnableUserRequest.hpp>
#include <alibabacloud/models/EnableUserResponseBody.hpp>
#include <alibabacloud/models/EnableUserResponse.hpp>
#include <alibabacloud/models/ExecuteDataCorrectRequest.hpp>
#include <alibabacloud/models/ExecuteDataCorrectShrinkRequest.hpp>
#include <alibabacloud/models/ExecuteDataCorrectResponseBody.hpp>
#include <alibabacloud/models/ExecuteDataCorrectResponse.hpp>
#include <alibabacloud/models/ExecuteDataExportRequest.hpp>
#include <alibabacloud/models/ExecuteDataExportShrinkRequest.hpp>
#include <alibabacloud/models/ExecuteDataExportResponseBody.hpp>
#include <alibabacloud/models/ExecuteDataExportResponse.hpp>
#include <alibabacloud/models/ExecuteScriptRequest.hpp>
#include <alibabacloud/models/ExecuteScriptResponseBody.hpp>
#include <alibabacloud/models/ExecuteScriptResponse.hpp>
#include <alibabacloud/models/ExecuteStructSyncRequest.hpp>
#include <alibabacloud/models/ExecuteStructSyncResponseBody.hpp>
#include <alibabacloud/models/ExecuteStructSyncResponse.hpp>
#include <alibabacloud/models/FixSqlByMetaAgentRequest.hpp>
#include <alibabacloud/models/FixSqlByMetaAgentResponseBody.hpp>
#include <alibabacloud/models/FixSqlByMetaAgentResponse.hpp>
#include <alibabacloud/models/GenMetaKnowledgeAssetRequest.hpp>
#include <alibabacloud/models/GenMetaKnowledgeAssetResponseBody.hpp>
#include <alibabacloud/models/GenMetaKnowledgeAssetResponse.hpp>
#include <alibabacloud/models/GenerateSqlFromNlrequest.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponseBody.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponse.hpp>
#include <alibabacloud/models/GetAbacPolicyRequest.hpp>
#include <alibabacloud/models/GetAbacPolicyResponseBody.hpp>
#include <alibabacloud/models/GetAbacPolicyResponse.hpp>
#include <alibabacloud/models/GetApprovalDetailRequest.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBody.hpp>
#include <alibabacloud/models/GetApprovalDetailResponse.hpp>
#include <alibabacloud/models/GetAuthorityTemplateRequest.hpp>
#include <alibabacloud/models/GetAuthorityTemplateResponseBody.hpp>
#include <alibabacloud/models/GetAuthorityTemplateResponse.hpp>
#include <alibabacloud/models/GetAuthorityTemplateItemRequest.hpp>
#include <alibabacloud/models/GetAuthorityTemplateItemResponseBody.hpp>
#include <alibabacloud/models/GetAuthorityTemplateItemResponse.hpp>
#include <alibabacloud/models/GetClassificationTemplateRequest.hpp>
#include <alibabacloud/models/GetClassificationTemplateResponseBody.hpp>
#include <alibabacloud/models/GetClassificationTemplateResponse.hpp>
#include <alibabacloud/models/GetDbtaskSqljobLogRequest.hpp>
#include <alibabacloud/models/GetDbtaskSqljobLogResponseBody.hpp>
#include <alibabacloud/models/GetDbtaskSqljobLogResponse.hpp>
#include <alibabacloud/models/GetDbtopologyRequest.hpp>
#include <alibabacloud/models/GetDbtopologyResponseBody.hpp>
#include <alibabacloud/models/GetDbtopologyResponse.hpp>
#include <alibabacloud/models/GetDataArchiveCountRequest.hpp>
#include <alibabacloud/models/GetDataArchiveCountResponseBody.hpp>
#include <alibabacloud/models/GetDataArchiveCountResponse.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailRequest.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponse.hpp>
#include <alibabacloud/models/GetDataCorrectBackupFilesRequest.hpp>
#include <alibabacloud/models/GetDataCorrectBackupFilesShrinkRequest.hpp>
#include <alibabacloud/models/GetDataCorrectBackupFilesResponseBody.hpp>
#include <alibabacloud/models/GetDataCorrectBackupFilesResponse.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailRequest.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponse.hpp>
#include <alibabacloud/models/GetDataCorrectRollbackFileRequest.hpp>
#include <alibabacloud/models/GetDataCorrectRollbackFileResponseBody.hpp>
#include <alibabacloud/models/GetDataCorrectRollbackFileResponse.hpp>
#include <alibabacloud/models/GetDataCorrectSqlfileRequest.hpp>
#include <alibabacloud/models/GetDataCorrectSqlfileResponseBody.hpp>
#include <alibabacloud/models/GetDataCorrectSqlfileResponse.hpp>
#include <alibabacloud/models/GetDataCorrectTaskDetailRequest.hpp>
#include <alibabacloud/models/GetDataCorrectTaskDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataCorrectTaskDetailResponse.hpp>
#include <alibabacloud/models/GetDataCronClearConfigRequest.hpp>
#include <alibabacloud/models/GetDataCronClearConfigResponseBody.hpp>
#include <alibabacloud/models/GetDataCronClearConfigResponse.hpp>
#include <alibabacloud/models/GetDataCronClearTaskDetailListRequest.hpp>
#include <alibabacloud/models/GetDataCronClearTaskDetailListResponseBody.hpp>
#include <alibabacloud/models/GetDataCronClearTaskDetailListResponse.hpp>
#include <alibabacloud/models/GetDataExportDownloadUrlrequest.hpp>
#include <alibabacloud/models/GetDataExportDownloadUrlresponseBody.hpp>
#include <alibabacloud/models/GetDataExportDownloadUrlresponse.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailRequest.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailResponse.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailRequest.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailResponse.hpp>
#include <alibabacloud/models/GetDataImportSqlrequest.hpp>
#include <alibabacloud/models/GetDataImportSqlresponseBody.hpp>
#include <alibabacloud/models/GetDataImportSqlresponse.hpp>
#include <alibabacloud/models/GetDataLakeCatalogRequest.hpp>
#include <alibabacloud/models/GetDataLakeCatalogResponseBody.hpp>
#include <alibabacloud/models/GetDataLakeCatalogResponse.hpp>
#include <alibabacloud/models/GetDataLakeDatabaseRequest.hpp>
#include <alibabacloud/models/GetDataLakeDatabaseResponseBody.hpp>
#include <alibabacloud/models/GetDataLakeDatabaseResponse.hpp>
#include <alibabacloud/models/GetDataLakeFunctionRequest.hpp>
#include <alibabacloud/models/GetDataLakeFunctionResponseBody.hpp>
#include <alibabacloud/models/GetDataLakeFunctionResponse.hpp>
#include <alibabacloud/models/GetDataLakePartitionRequest.hpp>
#include <alibabacloud/models/GetDataLakePartitionShrinkRequest.hpp>
#include <alibabacloud/models/GetDataLakePartitionResponseBody.hpp>
#include <alibabacloud/models/GetDataLakePartitionResponse.hpp>
#include <alibabacloud/models/GetDataLakeTableRequest.hpp>
#include <alibabacloud/models/GetDataLakeTableResponseBody.hpp>
#include <alibabacloud/models/GetDataLakeTableResponse.hpp>
#include <alibabacloud/models/GetDataTrackJobDegreeRequest.hpp>
#include <alibabacloud/models/GetDataTrackJobDegreeResponseBody.hpp>
#include <alibabacloud/models/GetDataTrackJobDegreeResponse.hpp>
#include <alibabacloud/models/GetDataTrackJobTableMetaRequest.hpp>
#include <alibabacloud/models/GetDataTrackJobTableMetaResponseBody.hpp>
#include <alibabacloud/models/GetDataTrackJobTableMetaResponse.hpp>
#include <alibabacloud/models/GetDataTrackOrderDetailRequest.hpp>
#include <alibabacloud/models/GetDataTrackOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetDataTrackOrderDetailResponse.hpp>
#include <alibabacloud/models/GetDatabaseRequest.hpp>
#include <alibabacloud/models/GetDatabaseResponseBody.hpp>
#include <alibabacloud/models/GetDatabaseResponse.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailRequest.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponse.hpp>
#include <alibabacloud/models/GetDbExportDownloadUrlrequest.hpp>
#include <alibabacloud/models/GetDbExportDownloadUrlresponseBody.hpp>
#include <alibabacloud/models/GetDbExportDownloadUrlresponse.hpp>
#include <alibabacloud/models/GetInstanceRequest.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetIntervalLimitOfSlarequest.hpp>
#include <alibabacloud/models/GetIntervalLimitOfSlaresponseBody.hpp>
#include <alibabacloud/models/GetIntervalLimitOfSlaresponse.hpp>
#include <alibabacloud/models/GetLhSpaceByNameRequest.hpp>
#include <alibabacloud/models/GetLhSpaceByNameResponseBody.hpp>
#include <alibabacloud/models/GetLhSpaceByNameResponse.hpp>
#include <alibabacloud/models/GetLogicDatabaseRequest.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponseBody.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponse.hpp>
#include <alibabacloud/models/GetMetaTableColumnRequest.hpp>
#include <alibabacloud/models/GetMetaTableColumnResponseBody.hpp>
#include <alibabacloud/models/GetMetaTableColumnResponse.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoRequest.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoResponseBody.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoResponse.hpp>
#include <alibabacloud/models/GetOnlineDdlprogressRequest.hpp>
#include <alibabacloud/models/GetOnlineDdlprogressResponseBody.hpp>
#include <alibabacloud/models/GetOnlineDdlprogressResponse.hpp>
#include <alibabacloud/models/GetOpLogRequest.hpp>
#include <alibabacloud/models/GetOpLogResponseBody.hpp>
#include <alibabacloud/models/GetOpLogResponse.hpp>
#include <alibabacloud/models/GetOrderAttachmentFileRequest.hpp>
#include <alibabacloud/models/GetOrderAttachmentFileResponseBody.hpp>
#include <alibabacloud/models/GetOrderAttachmentFileResponse.hpp>
#include <alibabacloud/models/GetOrderBaseInfoRequest.hpp>
#include <alibabacloud/models/GetOrderBaseInfoResponseBody.hpp>
#include <alibabacloud/models/GetOrderBaseInfoResponse.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailRequest.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailResponse.hpp>
#include <alibabacloud/models/GetPagedInstanceRequest.hpp>
#include <alibabacloud/models/GetPagedInstanceResponseBody.hpp>
#include <alibabacloud/models/GetPagedInstanceResponse.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailRequest.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponse.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseRequest.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseResponseBody.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseResponse.hpp>
#include <alibabacloud/models/GetProxyRequest.hpp>
#include <alibabacloud/models/GetProxyResponseBody.hpp>
#include <alibabacloud/models/GetProxyResponse.hpp>
#include <alibabacloud/models/GetProxyAccessRequest.hpp>
#include <alibabacloud/models/GetProxyAccessResponseBody.hpp>
#include <alibabacloud/models/GetProxyAccessResponse.hpp>
#include <alibabacloud/models/GetRuleNumLimitOfSlarequest.hpp>
#include <alibabacloud/models/GetRuleNumLimitOfSlaresponseBody.hpp>
#include <alibabacloud/models/GetRuleNumLimitOfSlaresponse.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusRequest.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusResponseBody.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusResponse.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailRequest.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponseBody.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponse.hpp>
#include <alibabacloud/models/GetStandardGroupRequest.hpp>
#include <alibabacloud/models/GetStandardGroupResponseBody.hpp>
#include <alibabacloud/models/GetStandardGroupResponse.hpp>
#include <alibabacloud/models/GetStructSyncExecSqlDetailRequest.hpp>
#include <alibabacloud/models/GetStructSyncExecSqlDetailResponseBody.hpp>
#include <alibabacloud/models/GetStructSyncExecSqlDetailResponse.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultRequest.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultResponseBody.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultResponse.hpp>
#include <alibabacloud/models/GetStructSyncJobDetailRequest.hpp>
#include <alibabacloud/models/GetStructSyncJobDetailResponseBody.hpp>
#include <alibabacloud/models/GetStructSyncJobDetailResponse.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailRequest.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBody.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponse.hpp>
#include <alibabacloud/models/GetTableDbtopologyRequest.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponseBody.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponse.hpp>
#include <alibabacloud/models/GetTableDesignProjectFlowRequest.hpp>
#include <alibabacloud/models/GetTableDesignProjectFlowResponseBody.hpp>
#include <alibabacloud/models/GetTableDesignProjectFlowResponse.hpp>
#include <alibabacloud/models/GetTableDesignProjectInfoRequest.hpp>
#include <alibabacloud/models/GetTableDesignProjectInfoResponseBody.hpp>
#include <alibabacloud/models/GetTableDesignProjectInfoResponse.hpp>
#include <alibabacloud/models/GetTableKnowledgeInfoRequest.hpp>
#include <alibabacloud/models/GetTableKnowledgeInfoResponseBody.hpp>
#include <alibabacloud/models/GetTableKnowledgeInfoResponse.hpp>
#include <alibabacloud/models/GetTableTopologyRequest.hpp>
#include <alibabacloud/models/GetTableTopologyResponseBody.hpp>
#include <alibabacloud/models/GetTableTopologyResponse.hpp>
#include <alibabacloud/models/GetTaskRequest.hpp>
#include <alibabacloud/models/GetTaskResponseBody.hpp>
#include <alibabacloud/models/GetTaskResponse.hpp>
#include <alibabacloud/models/GetTaskFlowGraphRequest.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBody.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponse.hpp>
#include <alibabacloud/models/GetTaskFlowNotificationRequest.hpp>
#include <alibabacloud/models/GetTaskFlowNotificationResponseBody.hpp>
#include <alibabacloud/models/GetTaskFlowNotificationResponse.hpp>
#include <alibabacloud/models/GetTaskInstanceRelationRequest.hpp>
#include <alibabacloud/models/GetTaskInstanceRelationResponseBody.hpp>
#include <alibabacloud/models/GetTaskInstanceRelationResponse.hpp>
#include <alibabacloud/models/GetUserRequest.hpp>
#include <alibabacloud/models/GetUserResponseBody.hpp>
#include <alibabacloud/models/GetUserResponse.hpp>
#include <alibabacloud/models/GetUserActiveTenantRequest.hpp>
#include <alibabacloud/models/GetUserActiveTenantResponseBody.hpp>
#include <alibabacloud/models/GetUserActiveTenantResponse.hpp>
#include <alibabacloud/models/GetUserUploadFileJobRequest.hpp>
#include <alibabacloud/models/GetUserUploadFileJobResponseBody.hpp>
#include <alibabacloud/models/GetUserUploadFileJobResponse.hpp>
#include <alibabacloud/models/GetWorkspaceRequest.hpp>
#include <alibabacloud/models/GetWorkspaceResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceResponse.hpp>
#include <alibabacloud/models/GrantTemplateAuthorityRequest.hpp>
#include <alibabacloud/models/GrantTemplateAuthorityResponseBody.hpp>
#include <alibabacloud/models/GrantTemplateAuthorityResponse.hpp>
#include <alibabacloud/models/GrantUserPermissionRequest.hpp>
#include <alibabacloud/models/GrantUserPermissionResponseBody.hpp>
#include <alibabacloud/models/GrantUserPermissionResponse.hpp>
#include <alibabacloud/models/InspectProxyAccessSecretRequest.hpp>
#include <alibabacloud/models/InspectProxyAccessSecretResponseBody.hpp>
#include <alibabacloud/models/InspectProxyAccessSecretResponse.hpp>
#include <alibabacloud/models/ListAbacAuthorizationsRequest.hpp>
#include <alibabacloud/models/ListAbacAuthorizationsResponseBody.hpp>
#include <alibabacloud/models/ListAbacAuthorizationsResponse.hpp>
#include <alibabacloud/models/ListAbacPoliciesRequest.hpp>
#include <alibabacloud/models/ListAbacPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListAbacPoliciesResponse.hpp>
#include <alibabacloud/models/ListAuthorityTemplateRequest.hpp>
#include <alibabacloud/models/ListAuthorityTemplateResponseBody.hpp>
#include <alibabacloud/models/ListAuthorityTemplateResponse.hpp>
#include <alibabacloud/models/ListAuthorizedDatabasesForUserRequest.hpp>
#include <alibabacloud/models/ListAuthorizedDatabasesForUserResponseBody.hpp>
#include <alibabacloud/models/ListAuthorizedDatabasesForUserResponse.hpp>
#include <alibabacloud/models/ListAuthorizedInstancesForUserRequest.hpp>
#include <alibabacloud/models/ListAuthorizedInstancesForUserResponseBody.hpp>
#include <alibabacloud/models/ListAuthorizedInstancesForUserResponse.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForDatabaseRequest.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForDatabaseResponseBody.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForDatabaseResponse.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForInstanceRequest.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForInstanceResponseBody.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForInstanceResponse.hpp>
#include <alibabacloud/models/ListClassificationTemplatesRequest.hpp>
#include <alibabacloud/models/ListClassificationTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListClassificationTemplatesResponse.hpp>
#include <alibabacloud/models/ListColumnsRequest.hpp>
#include <alibabacloud/models/ListColumnsResponseBody.hpp>
#include <alibabacloud/models/ListColumnsResponse.hpp>
#include <alibabacloud/models/ListDagversionsRequest.hpp>
#include <alibabacloud/models/ListDagversionsResponseBody.hpp>
#include <alibabacloud/models/ListDagversionsResponse.hpp>
#include <alibabacloud/models/ListDbtaskSqljobRequest.hpp>
#include <alibabacloud/models/ListDbtaskSqljobResponseBody.hpp>
#include <alibabacloud/models/ListDbtaskSqljobResponse.hpp>
#include <alibabacloud/models/ListDbtaskSqljobDetailRequest.hpp>
#include <alibabacloud/models/ListDbtaskSqljobDetailResponseBody.hpp>
#include <alibabacloud/models/ListDbtaskSqljobDetailResponse.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsRequest.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsResponseBody.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsResponse.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckDbrequest.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckDbresponseBody.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckDbresponse.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckSqlrequest.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckSqlresponseBody.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckSqlresponse.hpp>
#include <alibabacloud/models/ListDataImportSqlpreCheckDetailRequest.hpp>
#include <alibabacloud/models/ListDataImportSqlpreCheckDetailResponseBody.hpp>
#include <alibabacloud/models/ListDataImportSqlpreCheckDetailResponse.hpp>
#include <alibabacloud/models/ListDataImportSqltypeRequest.hpp>
#include <alibabacloud/models/ListDataImportSqltypeResponseBody.hpp>
#include <alibabacloud/models/ListDataImportSqltypeResponse.hpp>
#include <alibabacloud/models/ListDataLakeCatalogRequest.hpp>
#include <alibabacloud/models/ListDataLakeCatalogResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeCatalogResponse.hpp>
#include <alibabacloud/models/ListDataLakeDatabaseRequest.hpp>
#include <alibabacloud/models/ListDataLakeDatabaseResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeDatabaseResponse.hpp>
#include <alibabacloud/models/ListDataLakeFunctionRequest.hpp>
#include <alibabacloud/models/ListDataLakeFunctionResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeFunctionResponse.hpp>
#include <alibabacloud/models/ListDataLakeFunctionNameRequest.hpp>
#include <alibabacloud/models/ListDataLakeFunctionNameResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeFunctionNameResponse.hpp>
#include <alibabacloud/models/ListDataLakePartitionRequest.hpp>
#include <alibabacloud/models/ListDataLakePartitionShrinkRequest.hpp>
#include <alibabacloud/models/ListDataLakePartitionResponseBody.hpp>
#include <alibabacloud/models/ListDataLakePartitionResponse.hpp>
#include <alibabacloud/models/ListDataLakePartitionByFilterRequest.hpp>
#include <alibabacloud/models/ListDataLakePartitionByFilterResponseBody.hpp>
#include <alibabacloud/models/ListDataLakePartitionByFilterResponse.hpp>
#include <alibabacloud/models/ListDataLakePartitionNameRequest.hpp>
#include <alibabacloud/models/ListDataLakePartitionNameResponseBody.hpp>
#include <alibabacloud/models/ListDataLakePartitionNameResponse.hpp>
#include <alibabacloud/models/ListDataLakeTableRequest.hpp>
#include <alibabacloud/models/ListDataLakeTableResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeTableResponse.hpp>
#include <alibabacloud/models/ListDataLakeTableNameRequest.hpp>
#include <alibabacloud/models/ListDataLakeTableNameResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeTableNameResponse.hpp>
#include <alibabacloud/models/ListDataLakeTablebaseInfoRequest.hpp>
#include <alibabacloud/models/ListDataLakeTablebaseInfoResponseBody.hpp>
#include <alibabacloud/models/ListDataLakeTablebaseInfoResponse.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsRequest.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponseBody.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponse.hpp>
#include <alibabacloud/models/ListDatabasesRequest.hpp>
#include <alibabacloud/models/ListDatabasesResponseBody.hpp>
#include <alibabacloud/models/ListDatabasesResponse.hpp>
#include <alibabacloud/models/ListDefaultSlarulesRequest.hpp>
#include <alibabacloud/models/ListDefaultSlarulesResponseBody.hpp>
#include <alibabacloud/models/ListDefaultSlarulesResponse.hpp>
#include <alibabacloud/models/ListDesensitizationRuleRequest.hpp>
#include <alibabacloud/models/ListDesensitizationRuleResponseBody.hpp>
#include <alibabacloud/models/ListDesensitizationRuleResponse.hpp>
#include <alibabacloud/models/ListDifyInstancesRequest.hpp>
#include <alibabacloud/models/ListDifyInstancesResponseBody.hpp>
#include <alibabacloud/models/ListDifyInstancesResponse.hpp>
#include <alibabacloud/models/ListEffectiveOrdersRequest.hpp>
#include <alibabacloud/models/ListEffectiveOrdersResponseBody.hpp>
#include <alibabacloud/models/ListEffectiveOrdersResponse.hpp>
#include <alibabacloud/models/ListIndexesRequest.hpp>
#include <alibabacloud/models/ListIndexesResponseBody.hpp>
#include <alibabacloud/models/ListIndexesResponse.hpp>
#include <alibabacloud/models/ListInstanceLoginAuditLogRequest.hpp>
#include <alibabacloud/models/ListInstanceLoginAuditLogResponseBody.hpp>
#include <alibabacloud/models/ListInstanceLoginAuditLogResponse.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsRequest.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponseBody.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioRequest.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBody.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponse.hpp>
#include <alibabacloud/models/ListLogicDatabasesRequest.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBody.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponse.hpp>
#include <alibabacloud/models/ListLogicTableRouteConfigRequest.hpp>
#include <alibabacloud/models/ListLogicTableRouteConfigResponseBody.hpp>
#include <alibabacloud/models/ListLogicTableRouteConfigResponse.hpp>
#include <alibabacloud/models/ListLogicTablesRequest.hpp>
#include <alibabacloud/models/ListLogicTablesResponseBody.hpp>
#include <alibabacloud/models/ListLogicTablesResponse.hpp>
#include <alibabacloud/models/ListMetaCategoryRequest.hpp>
#include <alibabacloud/models/ListMetaCategoryResponseBody.hpp>
#include <alibabacloud/models/ListMetaCategoryResponse.hpp>
#include <alibabacloud/models/ListOrdersRequest.hpp>
#include <alibabacloud/models/ListOrdersResponseBody.hpp>
#include <alibabacloud/models/ListOrdersResponse.hpp>
#include <alibabacloud/models/ListProxiesRequest.hpp>
#include <alibabacloud/models/ListProxiesResponseBody.hpp>
#include <alibabacloud/models/ListProxiesResponse.hpp>
#include <alibabacloud/models/ListProxyAccessesRequest.hpp>
#include <alibabacloud/models/ListProxyAccessesResponseBody.hpp>
#include <alibabacloud/models/ListProxyAccessesResponse.hpp>
#include <alibabacloud/models/ListProxySqlexecAuditLogRequest.hpp>
#include <alibabacloud/models/ListProxySqlexecAuditLogResponseBody.hpp>
#include <alibabacloud/models/ListProxySqlexecAuditLogResponse.hpp>
#include <alibabacloud/models/ListSlarulesRequest.hpp>
#include <alibabacloud/models/ListSlarulesResponseBody.hpp>
#include <alibabacloud/models/ListSlarulesResponse.hpp>
#include <alibabacloud/models/ListSqlexecAuditLogRequest.hpp>
#include <alibabacloud/models/ListSqlexecAuditLogResponseBody.hpp>
#include <alibabacloud/models/ListSqlexecAuditLogResponse.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlrequest.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlshrinkRequest.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlresponseBody.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlresponse.hpp>
#include <alibabacloud/models/ListScenariosRequest.hpp>
#include <alibabacloud/models/ListScenariosResponseBody.hpp>
#include <alibabacloud/models/ListScenariosResponse.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoRequest.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBody.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponse.hpp>
#include <alibabacloud/models/ListSensitiveColumnsRequest.hpp>
#include <alibabacloud/models/ListSensitiveColumnsResponseBody.hpp>
#include <alibabacloud/models/ListSensitiveColumnsResponse.hpp>
#include <alibabacloud/models/ListSensitiveColumnsDetailRequest.hpp>
#include <alibabacloud/models/ListSensitiveColumnsDetailResponseBody.hpp>
#include <alibabacloud/models/ListSensitiveColumnsDetailResponse.hpp>
#include <alibabacloud/models/ListSensitiveDataAuditLogRequest.hpp>
#include <alibabacloud/models/ListSensitiveDataAuditLogResponseBody.hpp>
#include <alibabacloud/models/ListSensitiveDataAuditLogResponse.hpp>
#include <alibabacloud/models/ListSensitivityLevelRequest.hpp>
#include <alibabacloud/models/ListSensitivityLevelResponseBody.hpp>
#include <alibabacloud/models/ListSensitivityLevelResponse.hpp>
#include <alibabacloud/models/ListStandardGroupsRequest.hpp>
#include <alibabacloud/models/ListStandardGroupsResponseBody.hpp>
#include <alibabacloud/models/ListStandardGroupsResponse.hpp>
#include <alibabacloud/models/ListTableColumnsRequest.hpp>
#include <alibabacloud/models/ListTableColumnsResponseBody.hpp>
#include <alibabacloud/models/ListTableColumnsResponse.hpp>
#include <alibabacloud/models/ListTablesRequest.hpp>
#include <alibabacloud/models/ListTablesResponseBody.hpp>
#include <alibabacloud/models/ListTablesResponse.hpp>
#include <alibabacloud/models/ListTablesInCategoryRequest.hpp>
#include <alibabacloud/models/ListTablesInCategoryResponseBody.hpp>
#include <alibabacloud/models/ListTablesInCategoryResponse.hpp>
#include <alibabacloud/models/ListTaskFlowRequest.hpp>
#include <alibabacloud/models/ListTaskFlowResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowResponse.hpp>
#include <alibabacloud/models/ListTaskFlowConstantsRequest.hpp>
#include <alibabacloud/models/ListTaskFlowConstantsResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowConstantsResponse.hpp>
#include <alibabacloud/models/ListTaskFlowCooperatorsRequest.hpp>
#include <alibabacloud/models/ListTaskFlowCooperatorsResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowCooperatorsResponse.hpp>
#include <alibabacloud/models/ListTaskFlowEdgesByConditionRequest.hpp>
#include <alibabacloud/models/ListTaskFlowEdgesByConditionResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowEdgesByConditionResponse.hpp>
#include <alibabacloud/models/ListTaskFlowInstanceRequest.hpp>
#include <alibabacloud/models/ListTaskFlowInstanceResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowInstanceResponse.hpp>
#include <alibabacloud/models/ListTaskFlowTimeVariablesRequest.hpp>
#include <alibabacloud/models/ListTaskFlowTimeVariablesResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowTimeVariablesResponse.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageRequest.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageShrinkRequest.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageResponseBody.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageResponse.hpp>
#include <alibabacloud/models/ListTasksInTaskFlowRequest.hpp>
#include <alibabacloud/models/ListTasksInTaskFlowResponseBody.hpp>
#include <alibabacloud/models/ListTasksInTaskFlowResponse.hpp>
#include <alibabacloud/models/ListUserPermissionsRequest.hpp>
#include <alibabacloud/models/ListUserPermissionsResponseBody.hpp>
#include <alibabacloud/models/ListUserPermissionsResponse.hpp>
#include <alibabacloud/models/ListUserTenantsRequest.hpp>
#include <alibabacloud/models/ListUserTenantsResponseBody.hpp>
#include <alibabacloud/models/ListUserTenantsResponse.hpp>
#include <alibabacloud/models/ListUsersRequest.hpp>
#include <alibabacloud/models/ListUsersResponseBody.hpp>
#include <alibabacloud/models/ListUsersResponse.hpp>
#include <alibabacloud/models/ListWorkFlowNodesRequest.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponseBody.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponse.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesRequest.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponse.hpp>
#include <alibabacloud/models/ListWorkspacesRequest.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBody.hpp>
#include <alibabacloud/models/ListWorkspacesResponse.hpp>
#include <alibabacloud/models/MakeTaskFlowInstanceSuccessRequest.hpp>
#include <alibabacloud/models/MakeTaskFlowInstanceSuccessResponseBody.hpp>
#include <alibabacloud/models/MakeTaskFlowInstanceSuccessResponse.hpp>
#include <alibabacloud/models/ModifyDataCorrectExecSqlrequest.hpp>
#include <alibabacloud/models/ModifyDataCorrectExecSqlresponseBody.hpp>
#include <alibabacloud/models/ModifyDataCorrectExecSqlresponse.hpp>
#include <alibabacloud/models/ModifyDesensitizationStrategyRequest.hpp>
#include <alibabacloud/models/ModifyDesensitizationStrategyResponseBody.hpp>
#include <alibabacloud/models/ModifyDesensitizationStrategyResponse.hpp>
#include <alibabacloud/models/ModifyInstanceRequest.hpp>
#include <alibabacloud/models/ModifyInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceResponse.hpp>
#include <alibabacloud/models/MoveTaskFlowToScenarioRequest.hpp>
#include <alibabacloud/models/MoveTaskFlowToScenarioResponseBody.hpp>
#include <alibabacloud/models/MoveTaskFlowToScenarioResponse.hpp>
#include <alibabacloud/models/OfflineTaskFlowRequest.hpp>
#include <alibabacloud/models/OfflineTaskFlowResponseBody.hpp>
#include <alibabacloud/models/OfflineTaskFlowResponse.hpp>
#include <alibabacloud/models/OptimizeSqlByMetaAgentRequest.hpp>
#include <alibabacloud/models/OptimizeSqlByMetaAgentResponseBody.hpp>
#include <alibabacloud/models/OptimizeSqlByMetaAgentResponse.hpp>
#include <alibabacloud/models/PauseDataCorrectSqljobRequest.hpp>
#include <alibabacloud/models/PauseDataCorrectSqljobResponseBody.hpp>
#include <alibabacloud/models/PauseDataCorrectSqljobResponse.hpp>
#include <alibabacloud/models/PauseDataExportJobRequest.hpp>
#include <alibabacloud/models/PauseDataExportJobResponseBody.hpp>
#include <alibabacloud/models/PauseDataExportJobResponse.hpp>
#include <alibabacloud/models/PreviewWorkflowRequest.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBody.hpp>
#include <alibabacloud/models/PreviewWorkflowResponse.hpp>
#include <alibabacloud/models/PublishAndDeployTaskFlowRequest.hpp>
#include <alibabacloud/models/PublishAndDeployTaskFlowResponseBody.hpp>
#include <alibabacloud/models/PublishAndDeployTaskFlowResponse.hpp>
#include <alibabacloud/models/QueryDataTrackResultDownloadStatusRequest.hpp>
#include <alibabacloud/models/QueryDataTrackResultDownloadStatusResponseBody.hpp>
#include <alibabacloud/models/QueryDataTrackResultDownloadStatusResponse.hpp>
#include <alibabacloud/models/ReDeployLhDagVersionRequest.hpp>
#include <alibabacloud/models/ReDeployLhDagVersionResponseBody.hpp>
#include <alibabacloud/models/ReDeployLhDagVersionResponse.hpp>
#include <alibabacloud/models/ReRunTaskFlowInstanceRequest.hpp>
#include <alibabacloud/models/ReRunTaskFlowInstanceResponseBody.hpp>
#include <alibabacloud/models/ReRunTaskFlowInstanceResponse.hpp>
#include <alibabacloud/models/RedeployDifyInstanceRequest.hpp>
#include <alibabacloud/models/RedeployDifyInstanceResponseBody.hpp>
#include <alibabacloud/models/RedeployDifyInstanceResponse.hpp>
#include <alibabacloud/models/RefundPayAsYouGoOrderRequest.hpp>
#include <alibabacloud/models/RefundPayAsYouGoOrderResponseBody.hpp>
#include <alibabacloud/models/RefundPayAsYouGoOrderResponse.hpp>
#include <alibabacloud/models/RegisterInstanceRequest.hpp>
#include <alibabacloud/models/RegisterInstanceResponseBody.hpp>
#include <alibabacloud/models/RegisterInstanceResponse.hpp>
#include <alibabacloud/models/RegisterUserRequest.hpp>
#include <alibabacloud/models/RegisterUserResponseBody.hpp>
#include <alibabacloud/models/RegisterUserResponse.hpp>
#include <alibabacloud/models/RemoveDataExportJobRequest.hpp>
#include <alibabacloud/models/RemoveDataExportJobResponseBody.hpp>
#include <alibabacloud/models/RemoveDataExportJobResponse.hpp>
#include <alibabacloud/models/RemoveTableFromCategoryRequest.hpp>
#include <alibabacloud/models/RemoveTableFromCategoryResponseBody.hpp>
#include <alibabacloud/models/RemoveTableFromCategoryResponse.hpp>
#include <alibabacloud/models/RestartDataCorrectSqljobRequest.hpp>
#include <alibabacloud/models/RestartDataCorrectSqljobResponseBody.hpp>
#include <alibabacloud/models/RestartDataCorrectSqljobResponse.hpp>
#include <alibabacloud/models/RestartDataExportJobRequest.hpp>
#include <alibabacloud/models/RestartDataExportJobResponseBody.hpp>
#include <alibabacloud/models/RestartDataExportJobResponse.hpp>
#include <alibabacloud/models/ResumeTaskFlowInstanceRequest.hpp>
#include <alibabacloud/models/ResumeTaskFlowInstanceResponseBody.hpp>
#include <alibabacloud/models/ResumeTaskFlowInstanceResponse.hpp>
#include <alibabacloud/models/RetryDataCorrectPreCheckRequest.hpp>
#include <alibabacloud/models/RetryDataCorrectPreCheckResponseBody.hpp>
#include <alibabacloud/models/RetryDataCorrectPreCheckResponse.hpp>
#include <alibabacloud/models/RevokeTemplateAuthorityRequest.hpp>
#include <alibabacloud/models/RevokeTemplateAuthorityResponseBody.hpp>
#include <alibabacloud/models/RevokeTemplateAuthorityResponse.hpp>
#include <alibabacloud/models/RevokeUserPermissionRequest.hpp>
#include <alibabacloud/models/RevokeUserPermissionResponseBody.hpp>
#include <alibabacloud/models/RevokeUserPermissionResponse.hpp>
#include <alibabacloud/models/SearchDataTrackResultRequest.hpp>
#include <alibabacloud/models/SearchDataTrackResultShrinkRequest.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponseBody.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponse.hpp>
#include <alibabacloud/models/SearchDatabaseRequest.hpp>
#include <alibabacloud/models/SearchDatabaseResponseBody.hpp>
#include <alibabacloud/models/SearchDatabaseResponse.hpp>
#include <alibabacloud/models/SearchTableRequest.hpp>
#include <alibabacloud/models/SearchTableResponseBody.hpp>
#include <alibabacloud/models/SearchTableResponse.hpp>
#include <alibabacloud/models/SetOwnersRequest.hpp>
#include <alibabacloud/models/SetOwnersResponseBody.hpp>
#include <alibabacloud/models/SetOwnersResponse.hpp>
#include <alibabacloud/models/SetWorkflowExtraInfoRequest.hpp>
#include <alibabacloud/models/SetWorkflowExtraInfoResponseBody.hpp>
#include <alibabacloud/models/SetWorkflowExtraInfoResponse.hpp>
#include <alibabacloud/models/SimplyAddInstanceRequest.hpp>
#include <alibabacloud/models/SimplyAddInstanceResponseBody.hpp>
#include <alibabacloud/models/SimplyAddInstanceResponse.hpp>
#include <alibabacloud/models/SkipDataCorrectRowCheckRequest.hpp>
#include <alibabacloud/models/SkipDataCorrectRowCheckResponseBody.hpp>
#include <alibabacloud/models/SkipDataCorrectRowCheckResponse.hpp>
#include <alibabacloud/models/StopTaskFlowInstanceRequest.hpp>
#include <alibabacloud/models/StopTaskFlowInstanceResponseBody.hpp>
#include <alibabacloud/models/StopTaskFlowInstanceResponse.hpp>
#include <alibabacloud/models/SubmitOrderApprovalRequest.hpp>
#include <alibabacloud/models/SubmitOrderApprovalResponseBody.hpp>
#include <alibabacloud/models/SubmitOrderApprovalResponse.hpp>
#include <alibabacloud/models/SubmitStructSyncOrderApprovalRequest.hpp>
#include <alibabacloud/models/SubmitStructSyncOrderApprovalResponseBody.hpp>
#include <alibabacloud/models/SubmitStructSyncOrderApprovalResponse.hpp>
#include <alibabacloud/models/SuspendDataExportJobRequest.hpp>
#include <alibabacloud/models/SuspendDataExportJobResponseBody.hpp>
#include <alibabacloud/models/SuspendDataExportJobResponse.hpp>
#include <alibabacloud/models/SuspendTaskFlowInstanceRequest.hpp>
#include <alibabacloud/models/SuspendTaskFlowInstanceResponseBody.hpp>
#include <alibabacloud/models/SuspendTaskFlowInstanceResponse.hpp>
#include <alibabacloud/models/SyncDatabaseMetaRequest.hpp>
#include <alibabacloud/models/SyncDatabaseMetaResponseBody.hpp>
#include <alibabacloud/models/SyncDatabaseMetaResponse.hpp>
#include <alibabacloud/models/SyncInstanceMetaRequest.hpp>
#include <alibabacloud/models/SyncInstanceMetaResponseBody.hpp>
#include <alibabacloud/models/SyncInstanceMetaResponse.hpp>
#include <alibabacloud/models/TryRunTaskFlowRequest.hpp>
#include <alibabacloud/models/TryRunTaskFlowResponseBody.hpp>
#include <alibabacloud/models/TryRunTaskFlowResponse.hpp>
#include <alibabacloud/models/UpdateAbacPolicyRequest.hpp>
#include <alibabacloud/models/UpdateAbacPolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateAbacPolicyResponse.hpp>
#include <alibabacloud/models/UpdateAuthorityTemplateRequest.hpp>
#include <alibabacloud/models/UpdateAuthorityTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateAuthorityTemplateResponse.hpp>
#include <alibabacloud/models/UpdateDataLakeDatabaseRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeDatabaseShrinkRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeDatabaseResponseBody.hpp>
#include <alibabacloud/models/UpdateDataLakeDatabaseResponse.hpp>
#include <alibabacloud/models/UpdateDataLakeFunctionRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeFunctionShrinkRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeFunctionResponseBody.hpp>
#include <alibabacloud/models/UpdateDataLakeFunctionResponse.hpp>
#include <alibabacloud/models/UpdateDataLakePartitionRequest.hpp>
#include <alibabacloud/models/UpdateDataLakePartitionShrinkRequest.hpp>
#include <alibabacloud/models/UpdateDataLakePartitionResponseBody.hpp>
#include <alibabacloud/models/UpdateDataLakePartitionResponse.hpp>
#include <alibabacloud/models/UpdateDataLakeTableRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeTableShrinkRequest.hpp>
#include <alibabacloud/models/UpdateDataLakeTableResponseBody.hpp>
#include <alibabacloud/models/UpdateDataLakeTableResponse.hpp>
#include <alibabacloud/models/UpdateInstanceRequest.hpp>
#include <alibabacloud/models/UpdateInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceResponse.hpp>
#include <alibabacloud/models/UpdateMetaCategoryRequest.hpp>
#include <alibabacloud/models/UpdateMetaCategoryResponseBody.hpp>
#include <alibabacloud/models/UpdateMetaCategoryResponse.hpp>
#include <alibabacloud/models/UpdateSlarulesRequest.hpp>
#include <alibabacloud/models/UpdateSlarulesShrinkRequest.hpp>
#include <alibabacloud/models/UpdateSlarulesResponseBody.hpp>
#include <alibabacloud/models/UpdateSlarulesResponse.hpp>
#include <alibabacloud/models/UpdateScenarioRequest.hpp>
#include <alibabacloud/models/UpdateScenarioResponseBody.hpp>
#include <alibabacloud/models/UpdateScenarioResponse.hpp>
#include <alibabacloud/models/UpdateStandardGroupRequest.hpp>
#include <alibabacloud/models/UpdateStandardGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateStandardGroupResponse.hpp>
#include <alibabacloud/models/UpdateTaskConfigRequest.hpp>
#include <alibabacloud/models/UpdateTaskConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskConfigResponse.hpp>
#include <alibabacloud/models/UpdateTaskContentRequest.hpp>
#include <alibabacloud/models/UpdateTaskContentResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskContentResponse.hpp>
#include <alibabacloud/models/UpdateTaskContentV2request.hpp>
#include <alibabacloud/models/UpdateTaskContentV2responseBody.hpp>
#include <alibabacloud/models/UpdateTaskContentV2response.hpp>
#include <alibabacloud/models/UpdateTaskFlowConstantsRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowConstantsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowConstantsResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowConstantsResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowCooperatorsRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowCooperatorsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowCooperatorsResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowCooperatorsResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowEdgesRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowEdgesShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowEdgesResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowEdgesResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowNameAndDescRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowNameAndDescResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowNameAndDescResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowNotificationRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowNotificationResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowNotificationResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowOwnerRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowOwnerResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowOwnerResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowRelationsRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowRelationsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowRelationsResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowRelationsResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowScheduleRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowScheduleResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowScheduleResponse.hpp>
#include <alibabacloud/models/UpdateTaskFlowTimeVariablesRequest.hpp>
#include <alibabacloud/models/UpdateTaskFlowTimeVariablesResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskFlowTimeVariablesResponse.hpp>
#include <alibabacloud/models/UpdateTaskNameRequest.hpp>
#include <alibabacloud/models/UpdateTaskNameResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskNameResponse.hpp>
#include <alibabacloud/models/UpdateTaskOutputRequest.hpp>
#include <alibabacloud/models/UpdateTaskOutputResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskOutputResponse.hpp>
#include <alibabacloud/models/UpdateTaskTimeVariablesRequest.hpp>
#include <alibabacloud/models/UpdateTaskTimeVariablesResponseBody.hpp>
#include <alibabacloud/models/UpdateTaskTimeVariablesResponse.hpp>
#include <alibabacloud/models/UpdateUserRequest.hpp>
#include <alibabacloud/models/UpdateUserResponseBody.hpp>
#include <alibabacloud/models/UpdateUserResponse.hpp>
#include <alibabacloud/models/UpdateWorkspaceRequest.hpp>
#include <alibabacloud/models/UpdateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkspaceResponse.hpp>
#include <alibabacloud/models/AddAuthorityTemplateItemsRequestItems.hpp>
#include <alibabacloud/models/AddLhMembersRequestMembers.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesRequestEdges.hpp>
#include <alibabacloud/models/AddTaskFlowEdgesResponseBodyEdgeIds.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBodyLineageResultLineagesProcessDetail.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBodyLineageResultLineages.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBodyLineageResultObjectMetadataFields.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBodyLineageResultObjectMetadata.hpp>
#include <alibabacloud/models/AnalyzeSqllineageResponseBodyLineageResult.hpp>
#include <alibabacloud/models/AnswerSqlSyntaxByMetaAgentResponseBodyData.hpp>
#include <alibabacloud/models/CreateAuthorityTemplateResponseBodyAuthorityTemplateView.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderRequestParamTableIncludes.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderRequestParamVariables.hpp>
#include <alibabacloud/models/CreateDataArchiveOrderRequestParam.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderRequestParamDbItemList.hpp>
#include <alibabacloud/models/CreateDataCorrectOrderRequestParam.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderRequestParamCronClearItemList.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderRequestParamDbItemList.hpp>
#include <alibabacloud/models/CreateDataCronClearOrderRequestParam.hpp>
#include <alibabacloud/models/CreateDataExportOrderRequestPluginParamWatermark.hpp>
#include <alibabacloud/models/CreateDataExportOrderRequestPluginParam.hpp>
#include <alibabacloud/models/CreateDataExportOrderResponseBodyCreateOrderResult.hpp>
#include <alibabacloud/models/CreateDataImportOrderRequestParamDbItemList.hpp>
#include <alibabacloud/models/CreateDataImportOrderRequestParam.hpp>
#include <alibabacloud/models/CreateDataTrackOrderRequestParam.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderRequestPluginParamConfig.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderRequestPluginParam.hpp>
#include <alibabacloud/models/CreateDatabaseExportOrderResponseBodyCreateOrderResult.hpp>
#include <alibabacloud/models/CreateDifyInstanceResponseBodyData.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderRequestParamDbItemList.hpp>
#include <alibabacloud/models/CreateFreeLockCorrectOrderRequestParam.hpp>
#include <alibabacloud/models/CreateOrderResponseBodyCreateOrderResult.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderRequestParamDbItemList.hpp>
#include <alibabacloud/models/CreateProcCorrectOrderRequestParam.hpp>
#include <alibabacloud/models/CreateSqlreviewOrderRequestParam.hpp>
#include <alibabacloud/models/CreateStandardGroupResponseBodyStandardGroup.hpp>
#include <alibabacloud/models/CreateStructSyncOrderRequestParamSource.hpp>
#include <alibabacloud/models/CreateStructSyncOrderRequestParamTableInfoList.hpp>
#include <alibabacloud/models/CreateStructSyncOrderRequestParamTarget.hpp>
#include <alibabacloud/models/CreateStructSyncOrderRequestParam.hpp>
#include <alibabacloud/models/CreateUploadOssfileJobRequestUploadTarget.hpp>
#include <alibabacloud/models/DescribeDifyAttributeResponseBodyRoot.hpp>
#include <alibabacloud/models/DescribeDifyDefaultVpcResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDifyEditionsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDifyRegionsResponseBodyData.hpp>
#include <alibabacloud/models/DownloadDataTrackResultRequestColumnFilter.hpp>
#include <alibabacloud/models/ExecuteScriptResponseBodyResults.hpp>
#include <alibabacloud/models/FixSqlByMetaAgentResponseBodyData.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponseBodyDataKnowledgeReferences.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponseBodyDataSimilarSql.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponseBodyDataTables.hpp>
#include <alibabacloud/models/GenerateSqlFromNlresponseBodyData.hpp>
#include <alibabacloud/models/GetAbacPolicyResponseBodyPolicy.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailCurrentHandlersCurrentHandler.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailCurrentHandlers.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailReasonList.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailWorkflowNodesWorkflowNodeAuditUserIdList.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailWorkflowNodesWorkflowNode.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetailWorkflowNodes.hpp>
#include <alibabacloud/models/GetApprovalDetailResponseBodyApprovalDetail.hpp>
#include <alibabacloud/models/GetAuthorityTemplateResponseBodyAuthorityTemplateViewAuthorityTemplateItemListAuthorityTemplateItem.hpp>
#include <alibabacloud/models/GetAuthorityTemplateResponseBodyAuthorityTemplateViewAuthorityTemplateItemList.hpp>
#include <alibabacloud/models/GetAuthorityTemplateResponseBodyAuthorityTemplateView.hpp>
#include <alibabacloud/models/GetAuthorityTemplateItemResponseBodyAuthorityTemplateItemListAuthorityTemplateItem.hpp>
#include <alibabacloud/models/GetAuthorityTemplateItemResponseBodyAuthorityTemplateItemList.hpp>
#include <alibabacloud/models/GetClassificationTemplateResponseBodyClassificationResourceTemplateMap.hpp>
#include <alibabacloud/models/GetDbtopologyResponseBodyDbtopologyDbtopologyInfoList.hpp>
#include <alibabacloud/models/GetDbtopologyResponseBodyDbtopology.hpp>
#include <alibabacloud/models/GetDataArchiveCountResponseBodyData.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraDataDagInfo.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraDataDbBaseInfoStandardGroup.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraDataDbBaseInfo.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraDataInstances.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraDataNextFireTimeResult.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginExtraData.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginParamTableIncludes.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetailPluginParam.hpp>
#include <alibabacloud/models/GetDataArchiveOrderDetailResponseBodyDataArchiveOrderDetail.hpp>
#include <alibabacloud/models/GetDataCorrectBackupFilesResponseBodyDataCorrectBackupFiles.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailConfigDetailCronExtConfig.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailConfigDetailImportExtConfig.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailConfigDetail.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailDatabaseListDatabase.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailDatabaseList.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailOrderDetail.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailPreCheckDetailTaskCheckDo.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetailPreCheckDetail.hpp>
#include <alibabacloud/models/GetDataCorrectOrderDetailResponseBodyDataCorrectOrderDetail.hpp>
#include <alibabacloud/models/GetDataCorrectTaskDetailResponseBodyDataCorrectTaskDetail.hpp>
#include <alibabacloud/models/GetDataCronClearConfigResponseBodyDataCronClearConfig.hpp>
#include <alibabacloud/models/GetDataCronClearTaskDetailListResponseBodyDataCronClearTaskDetailList.hpp>
#include <alibabacloud/models/GetDataExportDownloadUrlresponseBodyDownloadUrlresult.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailResponseBodyDataExportOrderDetailKeyInfo.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailResponseBodyDataExportOrderDetailOrderDetail.hpp>
#include <alibabacloud/models/GetDataExportOrderDetailResponseBodyDataExportOrderDetail.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailResponseBodyPreCheckResultPreCheckDetailListPreCheckDetailList.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailResponseBodyPreCheckResultPreCheckDetailList.hpp>
#include <alibabacloud/models/GetDataExportPreCheckDetailResponseBodyPreCheckResult.hpp>
#include <alibabacloud/models/GetDataImportSqlresponseBodySqldetail.hpp>
#include <alibabacloud/models/GetDataTrackJobDegreeResponseBodyJobDegree.hpp>
#include <alibabacloud/models/GetDataTrackJobTableMetaResponseBodyTableMetaListColumns.hpp>
#include <alibabacloud/models/GetDataTrackJobTableMetaResponseBodyTableMetaList.hpp>
#include <alibabacloud/models/GetDataTrackOrderDetailResponseBodyDataTrackOrderDetail.hpp>
#include <alibabacloud/models/GetDatabaseResponseBodyDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/GetDatabaseResponseBodyDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/GetDatabaseResponseBodyDatabase.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetailKeyInfoConfigExportTypes.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetailKeyInfoConfigSqlextOption.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetailKeyInfoConfigSelectedTables.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetailKeyInfoConfig.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetailKeyInfo.hpp>
#include <alibabacloud/models/GetDatabaseExportOrderDetailResponseBodyDatabaseExportOrderDetail.hpp>
#include <alibabacloud/models/GetDbExportDownloadUrlresponseBodyDownloadUrlresult.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstanceOwnerIdList.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstanceOwnerNameList.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstanceStandardGroup.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/GetLhSpaceByNameResponseBodyLakehouseSpace.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponseBodyLogicDatabaseDatabaseIds.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponseBodyLogicDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponseBodyLogicDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/GetLogicDatabaseResponseBodyLogicDatabase.hpp>
#include <alibabacloud/models/GetMetaTableColumnResponseBodyColumnList.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoResponseBodyDetailInfoColumnList.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoResponseBodyDetailInfoIndexList.hpp>
#include <alibabacloud/models/GetMetaTableDetailInfoResponseBodyDetailInfo.hpp>
#include <alibabacloud/models/GetOnlineDdlprogressResponseBodyOnlineDdltaskDetail.hpp>
#include <alibabacloud/models/GetOpLogResponseBodyOpLogDetailsOpLogDetail.hpp>
#include <alibabacloud/models/GetOpLogResponseBodyOpLogDetails.hpp>
#include <alibabacloud/models/GetOrderBaseInfoResponseBodyOrderBaseInfoRelatedUserList.hpp>
#include <alibabacloud/models/GetOrderBaseInfoResponseBodyOrderBaseInfoRelatedUserNickList.hpp>
#include <alibabacloud/models/GetOrderBaseInfoResponseBodyOrderBaseInfo.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailResponseBodyOwnerApplyOrderDetailResourcesResourceDetail.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailResponseBodyOwnerApplyOrderDetailResources.hpp>
#include <alibabacloud/models/GetOwnerApplyOrderDetailResponseBodyOwnerApplyOrderDetail.hpp>
#include <alibabacloud/models/GetPagedInstanceResponseBodyDataInstance.hpp>
#include <alibabacloud/models/GetPagedInstanceResponseBodyData.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetailResourcesColumnInfo.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetailResourcesDatabaseInfo.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetailResourcesInstanceInfo.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetailResourcesTableInfo.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetailResources.hpp>
#include <alibabacloud/models/GetPermApplyOrderDetailResponseBodyPermApplyOrderDetail.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseResponseBodyDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseResponseBodyDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/GetPhysicalDatabaseResponseBodyDatabase.hpp>
#include <alibabacloud/models/GetProxyAccessResponseBodyProxyAccess.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusResponseBodyCheckResultStatusCheckStatusResult.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusResponseBodyCheckResultStatusSqlreviewResult.hpp>
#include <alibabacloud/models/GetSqlreviewCheckResultStatusResponseBodyCheckResultStatus.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponseBodyOptimizeDetailQualityResultResultsScripts.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponseBodyOptimizeDetailQualityResultResults.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponseBodyOptimizeDetailQualityResult.hpp>
#include <alibabacloud/models/GetSqlreviewOptimizeDetailResponseBodyOptimizeDetail.hpp>
#include <alibabacloud/models/GetStandardGroupResponseBodyStandardGroup.hpp>
#include <alibabacloud/models/GetStructSyncExecSqlDetailResponseBodyStructSyncExecSqlDetail.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultResponseBodyStructSyncJobAnalyzeResultResultList.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultResponseBodyStructSyncJobAnalyzeResultSummaryList.hpp>
#include <alibabacloud/models/GetStructSyncJobAnalyzeResultResponseBodyStructSyncJobAnalyzeResult.hpp>
#include <alibabacloud/models/GetStructSyncJobDetailResponseBodyStructSyncJobDetail.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetailSourceDatabaseInfo.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetailSourceVersionInfo.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetailTableInfoList.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetailTargetDatabaseInfo.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetailTargetVersionInfo.hpp>
#include <alibabacloud/models/GetStructSyncOrderDetailResponseBodyStructSyncOrderDetail.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponseBodyDbtopologyDataSourceListDatabaseListTableList.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponseBodyDbtopologyDataSourceListDatabaseList.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponseBodyDbtopologyDataSourceList.hpp>
#include <alibabacloud/models/GetTableDbtopologyResponseBodyDbtopology.hpp>
#include <alibabacloud/models/GetTableDesignProjectFlowResponseBodyProjectFlowFlowNodeArray.hpp>
#include <alibabacloud/models/GetTableDesignProjectFlowResponseBodyProjectFlow.hpp>
#include <alibabacloud/models/GetTableDesignProjectInfoResponseBodyProjectInfoBaseDatabase.hpp>
#include <alibabacloud/models/GetTableDesignProjectInfoResponseBodyProjectInfo.hpp>
#include <alibabacloud/models/GetTableTopologyResponseBodyTableTopologyTableTopologyInfoList.hpp>
#include <alibabacloud/models/GetTableTopologyResponseBodyTableTopology.hpp>
#include <alibabacloud/models/GetTaskResponseBodyTask.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBodyTaskFlowGraphEdgesEdge.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBodyTaskFlowGraphEdges.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBodyTaskFlowGraphNodesNode.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBodyTaskFlowGraphNodes.hpp>
#include <alibabacloud/models/GetTaskFlowGraphResponseBodyTaskFlowGraph.hpp>
#include <alibabacloud/models/GetTaskFlowNotificationResponseBodyNotification.hpp>
#include <alibabacloud/models/GetTaskInstanceRelationResponseBodyNodeListNode.hpp>
#include <alibabacloud/models/GetTaskInstanceRelationResponseBodyNodeList.hpp>
#include <alibabacloud/models/GetUserResponseBodyUserRoleIdList.hpp>
#include <alibabacloud/models/GetUserResponseBodyUserRoleNameList.hpp>
#include <alibabacloud/models/GetUserResponseBodyUser.hpp>
#include <alibabacloud/models/GetUserActiveTenantResponseBodyTenant.hpp>
#include <alibabacloud/models/GetUserUploadFileJobResponseBodyUploadFileJobDetailUploadOssparam.hpp>
#include <alibabacloud/models/GetUserUploadFileJobResponseBodyUploadFileJobDetail.hpp>
#include <alibabacloud/models/GetWorkspaceResponseBodyData.hpp>
#include <alibabacloud/models/ListAbacAuthorizationsResponseBodyAuthorizationList.hpp>
#include <alibabacloud/models/ListAbacPoliciesResponseBodyPolicyList.hpp>
#include <alibabacloud/models/ListAuthorityTemplateResponseBodyAuthorityTemplateViewListAuthorityTemplateView.hpp>
#include <alibabacloud/models/ListAuthorityTemplateResponseBodyAuthorityTemplateViewList.hpp>
#include <alibabacloud/models/ListAuthorizedDatabasesForUserResponseBodyDatabasesPermissionDetail.hpp>
#include <alibabacloud/models/ListAuthorizedDatabasesForUserResponseBodyDatabases.hpp>
#include <alibabacloud/models/ListAuthorizedInstancesForUserResponseBodyInstancesPermissionDetail.hpp>
#include <alibabacloud/models/ListAuthorizedInstancesForUserResponseBodyInstances.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForDatabaseResponseBodyUsers.hpp>
#include <alibabacloud/models/ListAuthorizedUsersForInstanceResponseBodyUsers.hpp>
#include <alibabacloud/models/ListClassificationTemplatesResponseBodyTemplateList.hpp>
#include <alibabacloud/models/ListColumnsResponseBodyColumnListColumn.hpp>
#include <alibabacloud/models/ListColumnsResponseBodyColumnList.hpp>
#include <alibabacloud/models/ListDagversionsResponseBodyDagVersionListDagVersion.hpp>
#include <alibabacloud/models/ListDagversionsResponseBodyDagVersionList.hpp>
#include <alibabacloud/models/ListDbtaskSqljobResponseBodyDbtaskSqljobList.hpp>
#include <alibabacloud/models/ListDbtaskSqljobDetailResponseBodyDbtaskSqljobDetailList.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsResponseBodyDdlpublishRecordListPublishTaskInfoListPublishJobList.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsResponseBodyDdlpublishRecordListPublishTaskInfoList.hpp>
#include <alibabacloud/models/ListDdlpublishRecordsResponseBodyDdlpublishRecordList.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckDbresponseBodyPreCheckDblist.hpp>
#include <alibabacloud/models/ListDataCorrectPreCheckSqlresponseBodyPreCheckSqllist.hpp>
#include <alibabacloud/models/ListDataImportSqlpreCheckDetailResponseBodyPreCheckSqldetailList.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponseBodyUserPermissionsUserPermissionPermDetailsPermDetail.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponseBodyUserPermissionsUserPermissionPermDetails.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponseBodyUserPermissionsUserPermission.hpp>
#include <alibabacloud/models/ListDatabaseUserPermssionsResponseBodyUserPermissions.hpp>
#include <alibabacloud/models/ListDatabasesResponseBodyDatabaseListDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/ListDatabasesResponseBodyDatabaseListDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/ListDatabasesResponseBodyDatabaseListDatabase.hpp>
#include <alibabacloud/models/ListDatabasesResponseBodyDatabaseList.hpp>
#include <alibabacloud/models/ListDefaultSlarulesResponseBodySlaruleListSlarule.hpp>
#include <alibabacloud/models/ListDefaultSlarulesResponseBodySlaruleList.hpp>
#include <alibabacloud/models/ListDesensitizationRuleResponseBodyDesensitizationRuleList.hpp>
#include <alibabacloud/models/ListDifyInstancesResponseBodyRootData.hpp>
#include <alibabacloud/models/ListDifyInstancesResponseBodyRoot.hpp>
#include <alibabacloud/models/ListEffectiveOrdersResponseBodyOrderSummaryOrderList.hpp>
#include <alibabacloud/models/ListEffectiveOrdersResponseBodyOrderSummary.hpp>
#include <alibabacloud/models/ListIndexesResponseBodyIndexListIndex.hpp>
#include <alibabacloud/models/ListIndexesResponseBodyIndexList.hpp>
#include <alibabacloud/models/ListInstanceLoginAuditLogResponseBodyInstanceLoginAuditLogListInstanceLoginAuditLog.hpp>
#include <alibabacloud/models/ListInstanceLoginAuditLogResponseBodyInstanceLoginAuditLogList.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponseBodyUserPermissionsUserPermissionPermDetailsPermDetail.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponseBodyUserPermissionsUserPermissionPermDetails.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponseBodyUserPermissionsUserPermission.hpp>
#include <alibabacloud/models/ListInstanceUserPermissionsResponseBodyUserPermissions.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListInstanceOwnerIdList.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListInstanceOwnerNameList.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListInstanceStandardGroup.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceListInstance.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstanceList.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyRawDaglistDag.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyRawDaglist.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyScenarioDaglistScenarioDagdagListDag.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyScenarioDaglistScenarioDagdagList.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyScenarioDaglistScenarioDagscenario.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyScenarioDaglistScenarioDag.hpp>
#include <alibabacloud/models/ListLhTaskFlowAndScenarioResponseBodyScenarioDaglist.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBodyLogicDatabaseListLogicDatabaseDatabaseIds.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBodyLogicDatabaseListLogicDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBodyLogicDatabaseListLogicDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBodyLogicDatabaseListLogicDatabase.hpp>
#include <alibabacloud/models/ListLogicDatabasesResponseBodyLogicDatabaseList.hpp>
#include <alibabacloud/models/ListLogicTableRouteConfigResponseBodyLogicTableRouteConfigListLogicTableRouteConfig.hpp>
#include <alibabacloud/models/ListLogicTableRouteConfigResponseBodyLogicTableRouteConfigList.hpp>
#include <alibabacloud/models/ListLogicTablesResponseBodyLogicTableListLogicTableOwnerIdList.hpp>
#include <alibabacloud/models/ListLogicTablesResponseBodyLogicTableListLogicTableOwnerNameList.hpp>
#include <alibabacloud/models/ListLogicTablesResponseBodyLogicTableListLogicTable.hpp>
#include <alibabacloud/models/ListLogicTablesResponseBodyLogicTableList.hpp>
#include <alibabacloud/models/ListMetaCategoryResponseBodyCategoryList.hpp>
#include <alibabacloud/models/ListOrdersResponseBodyOrdersOrder.hpp>
#include <alibabacloud/models/ListOrdersResponseBodyOrders.hpp>
#include <alibabacloud/models/ListProxiesResponseBodyProxyList.hpp>
#include <alibabacloud/models/ListProxyAccessesResponseBodyProxyAccessList.hpp>
#include <alibabacloud/models/ListProxySqlexecAuditLogResponseBodyProxySqlexecAuditLogListProxySqlexecAuditLog.hpp>
#include <alibabacloud/models/ListProxySqlexecAuditLogResponseBodyProxySqlexecAuditLogList.hpp>
#include <alibabacloud/models/ListSlarulesResponseBodySlaruleListSlarule.hpp>
#include <alibabacloud/models/ListSlarulesResponseBodySlaruleList.hpp>
#include <alibabacloud/models/ListSqlexecAuditLogResponseBodySqlexecAuditLogListSqlexecAuditLog.hpp>
#include <alibabacloud/models/ListSqlexecAuditLogResponseBodySqlexecAuditLogList.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlrequestOrderActionDetailPage.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlrequestOrderActionDetail.hpp>
#include <alibabacloud/models/ListSqlreviewOriginSqlresponseBodyOriginSqllist.hpp>
#include <alibabacloud/models/ListScenariosResponseBodyScenarioList.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBodySensitiveColumnListSensitiveColumnDefaultDesensitizationRule.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBodySensitiveColumnListSensitiveColumnSemiDesensitizationRuleListSemiDesensitizationRule.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBodySensitiveColumnListSensitiveColumnSemiDesensitizationRuleList.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBodySensitiveColumnListSensitiveColumn.hpp>
#include <alibabacloud/models/ListSensitiveColumnInfoResponseBodySensitiveColumnList.hpp>
#include <alibabacloud/models/ListSensitiveColumnsResponseBodySensitiveColumnListSensitiveColumn.hpp>
#include <alibabacloud/models/ListSensitiveColumnsResponseBodySensitiveColumnList.hpp>
#include <alibabacloud/models/ListSensitiveColumnsDetailResponseBodySensitiveColumnsDetailListSensitiveColumnsDetail.hpp>
#include <alibabacloud/models/ListSensitiveColumnsDetailResponseBodySensitiveColumnsDetailList.hpp>
#include <alibabacloud/models/ListSensitiveDataAuditLogResponseBodySensitiveDataAuditLogListSensitiveDataLog.hpp>
#include <alibabacloud/models/ListSensitiveDataAuditLogResponseBodySensitiveDataAuditLogList.hpp>
#include <alibabacloud/models/ListSensitivityLevelResponseBodySensitivityLevelList.hpp>
#include <alibabacloud/models/ListStandardGroupsResponseBodyStandardGroupList.hpp>
#include <alibabacloud/models/ListTableColumnsResponseBodyColumnListColumn.hpp>
#include <alibabacloud/models/ListTableColumnsResponseBodyColumnList.hpp>
#include <alibabacloud/models/ListTablesResponseBodyTableListTableOwnerIdList.hpp>
#include <alibabacloud/models/ListTablesResponseBodyTableListTableOwnerNameList.hpp>
#include <alibabacloud/models/ListTablesResponseBodyTableListTable.hpp>
#include <alibabacloud/models/ListTablesResponseBodyTableList.hpp>
#include <alibabacloud/models/ListTablesInCategoryResponseBodyEntityList.hpp>
#include <alibabacloud/models/ListTaskFlowResponseBodyTaskFlowListTaskFlow.hpp>
#include <alibabacloud/models/ListTaskFlowResponseBodyTaskFlowList.hpp>
#include <alibabacloud/models/ListTaskFlowConstantsResponseBodyDagConstantsDagConstant.hpp>
#include <alibabacloud/models/ListTaskFlowConstantsResponseBodyDagConstants.hpp>
#include <alibabacloud/models/ListTaskFlowCooperatorsResponseBodyCooperatorListCooperator.hpp>
#include <alibabacloud/models/ListTaskFlowCooperatorsResponseBodyCooperatorList.hpp>
#include <alibabacloud/models/ListTaskFlowEdgesByConditionResponseBodyEdgesEdge.hpp>
#include <alibabacloud/models/ListTaskFlowEdgesByConditionResponseBodyEdges.hpp>
#include <alibabacloud/models/ListTaskFlowInstanceResponseBodyDaginstanceListDaginstance.hpp>
#include <alibabacloud/models/ListTaskFlowInstanceResponseBodyDaginstanceList.hpp>
#include <alibabacloud/models/ListTaskFlowTimeVariablesResponseBodyTimeVariablesTimeVariable.hpp>
#include <alibabacloud/models/ListTaskFlowTimeVariablesResponseBodyTimeVariables.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageResponseBodyTaskFlowListTaskFlow.hpp>
#include <alibabacloud/models/ListTaskFlowsByPageResponseBodyTaskFlowList.hpp>
#include <alibabacloud/models/ListTasksInTaskFlowResponseBodyTasksTask.hpp>
#include <alibabacloud/models/ListTasksInTaskFlowResponseBodyTasks.hpp>
#include <alibabacloud/models/ListUserPermissionsResponseBodyUserPermissionsUserPermissionPermDetailsPermDetail.hpp>
#include <alibabacloud/models/ListUserPermissionsResponseBodyUserPermissionsUserPermissionPermDetails.hpp>
#include <alibabacloud/models/ListUserPermissionsResponseBodyUserPermissionsUserPermission.hpp>
#include <alibabacloud/models/ListUserPermissionsResponseBodyUserPermissions.hpp>
#include <alibabacloud/models/ListUserTenantsResponseBodyTenantList.hpp>
#include <alibabacloud/models/ListUsersResponseBodyUserListUserRoleIdList.hpp>
#include <alibabacloud/models/ListUsersResponseBodyUserListUserRoleNameList.hpp>
#include <alibabacloud/models/ListUsersResponseBodyUserListUser.hpp>
#include <alibabacloud/models/ListUsersResponseBodyUserList.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponseBodyWorkflowNodesWorkflowNodeAuditUsersAuditUser.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponseBodyWorkflowNodesWorkflowNodeAuditUsers.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponseBodyWorkflowNodesWorkflowNode.hpp>
#include <alibabacloud/models/ListWorkFlowNodesResponseBodyWorkflowNodes.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponseBodyWorkFlowTemplatesWorkFlowTemplateWorkflowNodesWorkflowNode.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponseBodyWorkFlowTemplatesWorkFlowTemplateWorkflowNodes.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponseBodyWorkFlowTemplatesWorkFlowTemplate.hpp>
#include <alibabacloud/models/ListWorkFlowTemplatesResponseBodyWorkFlowTemplates.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBodyDataBaseWorkspaces.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBodyData.hpp>
#include <alibabacloud/models/OptimizeSqlByMetaAgentResponseBodyData.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBodyWorkflowDetailWorkflowNodeListWorkflowNodeAuditUserListAuditUser.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBodyWorkflowDetailWorkflowNodeListWorkflowNodeAuditUserList.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBodyWorkflowDetailWorkflowNodeListWorkflowNode.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBodyWorkflowDetailWorkflowNodeList.hpp>
#include <alibabacloud/models/PreviewWorkflowResponseBodyWorkflowDetail.hpp>
#include <alibabacloud/models/QueryDataTrackResultDownloadStatusResponseBodyStatusResult.hpp>
#include <alibabacloud/models/RedeployDifyInstanceResponseBodyData.hpp>
#include <alibabacloud/models/SearchDataTrackResultRequestColumnFilter.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponseBodyTrackResultEventList.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponseBodyTrackResultTableInfoListColumns.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponseBodyTrackResultTableInfoList.hpp>
#include <alibabacloud/models/SearchDataTrackResultResponseBodyTrackResult.hpp>
#include <alibabacloud/models/SearchDatabaseResponseBodySearchDatabaseListSearchDatabaseOwnerIdList.hpp>
#include <alibabacloud/models/SearchDatabaseResponseBodySearchDatabaseListSearchDatabaseOwnerNameList.hpp>
#include <alibabacloud/models/SearchDatabaseResponseBodySearchDatabaseListSearchDatabase.hpp>
#include <alibabacloud/models/SearchDatabaseResponseBodySearchDatabaseList.hpp>
#include <alibabacloud/models/SearchTableResponseBodySearchTableListSearchTableOwnerIdList.hpp>
#include <alibabacloud/models/SearchTableResponseBodySearchTableListSearchTableOwnerNameList.hpp>
#include <alibabacloud/models/SearchTableResponseBodySearchTableListSearchTable.hpp>
#include <alibabacloud/models/SearchTableResponseBodySearchTableList.hpp>
#include <alibabacloud/models/SimplyAddInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/UpdateAuthorityTemplateResponseBodyAuthorityTemplateView.hpp>
#include <alibabacloud/models/UpdateSlarulesRequestSlaRuleList.hpp>
#include <alibabacloud/models/UpdateStandardGroupResponseBodyStandardGroup.hpp>
#include <alibabacloud/models/UpdateTaskFlowConstantsRequestDagConstants.hpp>
#include <alibabacloud/models/UpdateTaskFlowEdgesRequestEdges.hpp>
#include <alibabacloud/models/UpdateTaskFlowRelationsRequestEdges.hpp>

#endif
