// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_UNIMKT20181212MODEL_HPP_
#define ALIBABACLOUD_UNIMKT20181212MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateProxyBrandUserRequest.hpp>
#include <alibabacloud/models/CreateProxyBrandUserResponseBody.hpp>
#include <alibabacloud/models/CreateProxyBrandUserResponse.hpp>
#include <alibabacloud/models/CreateUnionTaskRequest.hpp>
#include <alibabacloud/models/CreateUnionTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateUnionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateUnionTaskResponse.hpp>
#include <alibabacloud/models/DeleteUnionBrandRequest.hpp>
#include <alibabacloud/models/DeleteUnionBrandResponseBody.hpp>
#include <alibabacloud/models/DeleteUnionBrandResponse.hpp>
#include <alibabacloud/models/EndUnionTaskRequest.hpp>
#include <alibabacloud/models/EndUnionTaskResponseBody.hpp>
#include <alibabacloud/models/EndUnionTaskResponse.hpp>
#include <alibabacloud/models/ListUnionMediaIndustryRequest.hpp>
#include <alibabacloud/models/ListUnionMediaIndustryResponseBody.hpp>
#include <alibabacloud/models/ListUnionMediaIndustryResponse.hpp>
#include <alibabacloud/models/QueryAvailableBalanceRequest.hpp>
#include <alibabacloud/models/QueryAvailableBalanceResponseBody.hpp>
#include <alibabacloud/models/QueryAvailableBalanceResponse.hpp>
#include <alibabacloud/models/QueryContentListRequest.hpp>
#include <alibabacloud/models/QueryContentListResponseBody.hpp>
#include <alibabacloud/models/QueryContentListResponse.hpp>
#include <alibabacloud/models/QueryIndustryLabelBagRequest.hpp>
#include <alibabacloud/models/QueryIndustryLabelBagResponseBody.hpp>
#include <alibabacloud/models/QueryIndustryLabelBagResponse.hpp>
#include <alibabacloud/models/QueryTaskBizTypeRequest.hpp>
#include <alibabacloud/models/QueryTaskBizTypeResponseBody.hpp>
#include <alibabacloud/models/QueryTaskBizTypeResponse.hpp>
#include <alibabacloud/models/QueryTaskRuleLimitRequest.hpp>
#include <alibabacloud/models/QueryTaskRuleLimitResponseBody.hpp>
#include <alibabacloud/models/QueryTaskRuleLimitResponse.hpp>
#include <alibabacloud/models/QueryUnionChannelRequest.hpp>
#include <alibabacloud/models/QueryUnionChannelResponseBody.hpp>
#include <alibabacloud/models/QueryUnionChannelResponse.hpp>
#include <alibabacloud/models/QueryUnionContentInfoRequest.hpp>
#include <alibabacloud/models/QueryUnionContentInfoResponseBody.hpp>
#include <alibabacloud/models/QueryUnionContentInfoResponse.hpp>
#include <alibabacloud/models/QueryUnionTaskInfoRequest.hpp>
#include <alibabacloud/models/QueryUnionTaskInfoResponseBody.hpp>
#include <alibabacloud/models/QueryUnionTaskInfoResponse.hpp>
#include <alibabacloud/models/QueryUnionTaskListRequest.hpp>
#include <alibabacloud/models/QueryUnionTaskListResponseBody.hpp>
#include <alibabacloud/models/QueryUnionTaskListResponse.hpp>
#include <alibabacloud/models/StartUnionTaskRequest.hpp>
#include <alibabacloud/models/StartUnionTaskResponseBody.hpp>
#include <alibabacloud/models/StartUnionTaskResponse.hpp>
#include <alibabacloud/models/StopUnionTaskRequest.hpp>
#include <alibabacloud/models/StopUnionTaskResponseBody.hpp>
#include <alibabacloud/models/StopUnionTaskResponse.hpp>
#include <alibabacloud/models/UpdateUnionTaskRequest.hpp>
#include <alibabacloud/models/UpdateUnionTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateUnionTaskResponse.hpp>

#endif
