// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_CREATESCHEDULEDPRELOADEXECUTIONSREQUEST_HPP_
#define ALIBABACLOUD_MODELS_CREATESCHEDULEDPRELOADEXECUTIONSREQUEST_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/CreateScheduledPreloadExecutionsRequestExecutions.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace ESA20240910
{
namespace Models
{
  class CreateScheduledPreloadExecutionsRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const CreateScheduledPreloadExecutionsRequest& obj) { 
      DARABONBA_PTR_TO_JSON(Executions, executions_);
      DARABONBA_PTR_TO_JSON(Id, id_);
    };
    friend void from_json(const Darabonba::Json& j, CreateScheduledPreloadExecutionsRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(Executions, executions_);
      DARABONBA_PTR_FROM_JSON(Id, id_);
    };
    CreateScheduledPreloadExecutionsRequest() = default ;
    CreateScheduledPreloadExecutionsRequest(const CreateScheduledPreloadExecutionsRequest &) = default ;
    CreateScheduledPreloadExecutionsRequest(CreateScheduledPreloadExecutionsRequest &&) = default ;
    CreateScheduledPreloadExecutionsRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~CreateScheduledPreloadExecutionsRequest() = default ;
    CreateScheduledPreloadExecutionsRequest& operator=(const CreateScheduledPreloadExecutionsRequest &) = default ;
    CreateScheduledPreloadExecutionsRequest& operator=(CreateScheduledPreloadExecutionsRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->executions_ == nullptr
        && return this->id_ == nullptr; };
    // executions Field Functions 
    bool hasExecutions() const { return this->executions_ != nullptr;};
    void deleteExecutions() { this->executions_ = nullptr;};
    inline const vector<CreateScheduledPreloadExecutionsRequestExecutions> & executions() const { DARABONBA_PTR_GET_CONST(executions_, vector<CreateScheduledPreloadExecutionsRequestExecutions>) };
    inline vector<CreateScheduledPreloadExecutionsRequestExecutions> executions() { DARABONBA_PTR_GET(executions_, vector<CreateScheduledPreloadExecutionsRequestExecutions>) };
    inline CreateScheduledPreloadExecutionsRequest& setExecutions(const vector<CreateScheduledPreloadExecutionsRequestExecutions> & executions) { DARABONBA_PTR_SET_VALUE(executions_, executions) };
    inline CreateScheduledPreloadExecutionsRequest& setExecutions(vector<CreateScheduledPreloadExecutionsRequestExecutions> && executions) { DARABONBA_PTR_SET_RVALUE(executions_, executions) };


    // id Field Functions 
    bool hasId() const { return this->id_ != nullptr;};
    void deleteId() { this->id_ = nullptr;};
    inline string id() const { DARABONBA_PTR_GET_DEFAULT(id_, "") };
    inline CreateScheduledPreloadExecutionsRequest& setId(string id) { DARABONBA_PTR_SET_VALUE(id_, id) };


  protected:
    // The scheduled prefetch plans to create.
    // 
    // This parameter is required.
    std::shared_ptr<vector<CreateScheduledPreloadExecutionsRequestExecutions>> executions_ = nullptr;
    // The ID of the prefetch task, which is generated by calling the [CreateScheduledPreloadJob](https://help.aliyun.com/document_detail/2850459.html) operation.
    std::shared_ptr<string> id_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace ESA20240910
#endif
