// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_PAILANGSTUDIO20240710MODEL_HPP_
#define ALIBABACLOUD_PAILANGSTUDIO20240710MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/UserVpc.hpp>
#include <alibabacloud/models/AutoUpdateConfig.hpp>
#include <alibabacloud/models/Connection.hpp>
#include <alibabacloud/models/Deployment.hpp>
#include <alibabacloud/models/EcsSpec.hpp>
#include <alibabacloud/models/Flow.hpp>
#include <alibabacloud/models/FlowRun.hpp>
#include <alibabacloud/models/FlowTemplate.hpp>
#include <alibabacloud/models/KnowledgeBase.hpp>
#include <alibabacloud/models/KnowledgeBaseFileChunk.hpp>
#include <alibabacloud/models/KnowledgeBaseJob.hpp>
#include <alibabacloud/models/KnowledgeBaseMeta.hpp>
#include <alibabacloud/models/Runtime.hpp>
#include <alibabacloud/models/Snapshot.hpp>
#include <alibabacloud/models/Toolset.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobRequest.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobResponseBody.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobResponse.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseJobRequest.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseJobResponseBody.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseJobResponse.hpp>
#include <alibabacloud/models/GetKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobRequest.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBody.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponse.hpp>
#include <alibabacloud/models/ListKnowledgeBaseJobsRequest.hpp>
#include <alibabacloud/models/ListKnowledgeBaseJobsResponseBody.hpp>
#include <alibabacloud/models/ListKnowledgeBaseJobsResponse.hpp>
#include <alibabacloud/models/ListKnowledgeBasesRequest.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResponseBody.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResponse.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseJobRequest.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseJobResponseBody.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseJobResponse.hpp>
#include <alibabacloud/models/AutoUpdateConfigEcsSpecs.hpp>
#include <alibabacloud/models/AutoUpdateConfigEmbeddingConfig.hpp>
#include <alibabacloud/models/ConnectionModels.hpp>
#include <alibabacloud/models/ConnectionResourceMeta.hpp>
#include <alibabacloud/models/DeploymentChatHistoryConfig.hpp>
#include <alibabacloud/models/DeploymentContentModerationConfig.hpp>
#include <alibabacloud/models/DeploymentCredentialConfigCredentialConfigItemsRoles.hpp>
#include <alibabacloud/models/DeploymentCredentialConfigCredentialConfigItems.hpp>
#include <alibabacloud/models/DeploymentCredentialConfig.hpp>
#include <alibabacloud/models/DeploymentDataSources.hpp>
#include <alibabacloud/models/DeploymentEcsSpecComputingInstanceConfigComputingInstances.hpp>
#include <alibabacloud/models/DeploymentEcsSpecComputingInstanceConfig.hpp>
#include <alibabacloud/models/DeploymentEcsSpec.hpp>
#include <alibabacloud/models/DeploymentEnvs.hpp>
#include <alibabacloud/models/DeploymentLabels.hpp>
#include <alibabacloud/models/DeploymentUserVpc.hpp>
#include <alibabacloud/models/FlowRuntime.hpp>
#include <alibabacloud/models/FlowRunChildRunsFlowSource.hpp>
#include <alibabacloud/models/FlowRunChildRunsJobInfo.hpp>
#include <alibabacloud/models/FlowRunChildRuns.hpp>
#include <alibabacloud/models/FlowRunCredentialConfigCredentialConfigItemsRoles.hpp>
#include <alibabacloud/models/FlowRunCredentialConfigCredentialConfigItems.hpp>
#include <alibabacloud/models/FlowRunCredentialConfig.hpp>
#include <alibabacloud/models/FlowRunDataSources.hpp>
#include <alibabacloud/models/FlowRunEcsSpec.hpp>
#include <alibabacloud/models/FlowRunEnvs.hpp>
#include <alibabacloud/models/FlowRunEvaluationConfigsFlowSource.hpp>
#include <alibabacloud/models/FlowRunEvaluationConfigs.hpp>
#include <alibabacloud/models/FlowRunLabels.hpp>
#include <alibabacloud/models/FlowRunNodeRunInfos.hpp>
#include <alibabacloud/models/FlowRunUserVpc.hpp>
#include <alibabacloud/models/KnowledgeBaseAutoUpdateConfigEcsSpecs.hpp>
#include <alibabacloud/models/KnowledgeBaseAutoUpdateConfigEmbeddingConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseAutoUpdateConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseChunkConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseDataSources.hpp>
#include <alibabacloud/models/KnowledgeBaseEmbeddingConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseIndexColumnConfigColumnDefinitions.hpp>
#include <alibabacloud/models/KnowledgeBaseIndexColumnConfigContentColumns.hpp>
#include <alibabacloud/models/KnowledgeBaseIndexColumnConfigEmbeddingColumns.hpp>
#include <alibabacloud/models/KnowledgeBaseIndexColumnConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseMetaDataConfigCustomMetaData.hpp>
#include <alibabacloud/models/KnowledgeBaseMetaDataConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseVectorDbConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseFileChunkChunkAttachment.hpp>
#include <alibabacloud/models/KnowledgeBaseFileChunkMetaData.hpp>
#include <alibabacloud/models/KnowledgeBaseJobEcsSpecs.hpp>
#include <alibabacloud/models/KnowledgeBaseJobEmbeddingConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseJobKnowledgeBaseJobResult.hpp>
#include <alibabacloud/models/KnowledgeBaseJobPipelineRunInfo.hpp>
#include <alibabacloud/models/KnowledgeBaseJobUserVpc.hpp>
#include <alibabacloud/models/KnowledgeBaseMetaChunkAttachment.hpp>
#include <alibabacloud/models/KnowledgeBaseMetaMetaData.hpp>
#include <alibabacloud/models/RuntimeCredentialConfigCredentialConfigItemsRoles.hpp>
#include <alibabacloud/models/RuntimeCredentialConfigCredentialConfigItems.hpp>
#include <alibabacloud/models/RuntimeCredentialConfig.hpp>
#include <alibabacloud/models/RuntimeDataSources.hpp>
#include <alibabacloud/models/RuntimeEcsSpec.hpp>
#include <alibabacloud/models/RuntimeEnvs.hpp>
#include <alibabacloud/models/RuntimeFlows.hpp>
#include <alibabacloud/models/RuntimeLabels.hpp>
#include <alibabacloud/models/RuntimeUserVpc.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestChunkConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestDataSources.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestEmbeddingConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestIndexColumnConfigColumnDefinitions.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestIndexColumnConfigContentColumns.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestIndexColumnConfigEmbeddingColumns.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestIndexColumnConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestMetaDataConfigCustomMetaData.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestMetaDataConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequestVectorDbConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobRequestEcsSpecs.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobRequestEmbeddingConfig.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseJobRequestUserVpc.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyAutoUpdateConfigEcsSpecs.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyAutoUpdateConfigEmbeddingConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyAutoUpdateConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyChunkConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyDataSources.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyEmbeddingConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyIndexColumnConfigColumnDefinitions.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyIndexColumnConfigContentColumns.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyIndexColumnConfigEmbeddingColumns.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyIndexColumnConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyMetaDataConfigCustomMetaData.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyMetaDataConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponseBodyVectorDbConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBodyEcsSpecs.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBodyEmbeddingConfig.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBodyKnowledgeBaseJobResult.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBodyPipelineRunInfo.hpp>
#include <alibabacloud/models/GetKnowledgeBaseJobResponseBodyUserVpc.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequestAutoUpdateConfigEcsSpecs.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequestAutoUpdateConfigEmbeddingConfig.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequestAutoUpdateConfig.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequestMetaDataConfigCustomMetaData.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequestMetaDataConfig.hpp>

#endif
