// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_OPENSEARCH20171225MODEL_HPP_
#define ALIBABACLOUD_OPENSEARCH20171225MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ABTestExperiment.hpp>
#include <alibabacloud/models/ABTestGroup.hpp>
#include <alibabacloud/models/ABTestScene.hpp>
#include <alibabacloud/models/DataSourcePluginsValue.hpp>
#include <alibabacloud/models/DataSource.hpp>
#include <alibabacloud/models/Domain.hpp>
#include <alibabacloud/models/FirstRank.hpp>
#include <alibabacloud/models/QueryProcessor.hpp>
#include <alibabacloud/models/Quota.hpp>
#include <alibabacloud/models/SchemaTablesValueFieldsValue.hpp>
#include <alibabacloud/models/SchemaTablesValue.hpp>
#include <alibabacloud/models/Schema.hpp>
#include <alibabacloud/models/SecondRank.hpp>
#include <alibabacloud/models/Summary.hpp>
#include <alibabacloud/models/App.hpp>
#include <alibabacloud/models/AppGroup.hpp>
#include <alibabacloud/models/PrepayOrderInfo.hpp>
#include <alibabacloud/models/Proceeding.hpp>
#include <alibabacloud/models/ScheduledTask.hpp>
#include <alibabacloud/models/SearchStrategy.hpp>
#include <alibabacloud/models/SchemaIndexesSearchFieldsValue.hpp>
#include <alibabacloud/models/BindESUserAnalyzerRequest.hpp>
#include <alibabacloud/models/BindESUserAnalyzerResponseBody.hpp>
#include <alibabacloud/models/BindESUserAnalyzerResponse.hpp>
#include <alibabacloud/models/BindEsInstanceRequest.hpp>
#include <alibabacloud/models/BindEsInstanceResponseBody.hpp>
#include <alibabacloud/models/BindEsInstanceResponse.hpp>
#include <alibabacloud/models/CompileSortScriptResponseBody.hpp>
#include <alibabacloud/models/CompileSortScriptResponse.hpp>
#include <alibabacloud/models/CreateABTestExperimentRequest.hpp>
#include <alibabacloud/models/CreateABTestExperimentResponseBody.hpp>
#include <alibabacloud/models/CreateABTestExperimentResponse.hpp>
#include <alibabacloud/models/CreateABTestGroupRequest.hpp>
#include <alibabacloud/models/CreateABTestGroupResponseBody.hpp>
#include <alibabacloud/models/CreateABTestGroupResponse.hpp>
#include <alibabacloud/models/CreateABTestSceneRequest.hpp>
#include <alibabacloud/models/CreateABTestSceneResponseBody.hpp>
#include <alibabacloud/models/CreateABTestSceneResponse.hpp>
#include <alibabacloud/models/CreateAppRequest.hpp>
#include <alibabacloud/models/CreateAppResponseBody.hpp>
#include <alibabacloud/models/CreateAppResponse.hpp>
#include <alibabacloud/models/CreateAppGroupRequest.hpp>
#include <alibabacloud/models/CreateAppGroupResponseBody.hpp>
#include <alibabacloud/models/CreateAppGroupResponse.hpp>
#include <alibabacloud/models/CreateAppGroupCredentialsRequest.hpp>
#include <alibabacloud/models/CreateAppGroupCredentialsResponseBody.hpp>
#include <alibabacloud/models/CreateAppGroupCredentialsResponse.hpp>
#include <alibabacloud/models/CreateElasticPlanRequest.hpp>
#include <alibabacloud/models/CreateElasticPlanResponseBody.hpp>
#include <alibabacloud/models/CreateElasticPlanResponse.hpp>
#include <alibabacloud/models/CreateFirstRankRequest.hpp>
#include <alibabacloud/models/CreateFirstRankResponseBody.hpp>
#include <alibabacloud/models/CreateFirstRankResponse.hpp>
#include <alibabacloud/models/CreateFunctionInstanceRequest.hpp>
#include <alibabacloud/models/CreateFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateFunctionInstanceResponse.hpp>
#include <alibabacloud/models/CreateFunctionResourceRequest.hpp>
#include <alibabacloud/models/CreateFunctionResourceResponseBody.hpp>
#include <alibabacloud/models/CreateFunctionResourceResponse.hpp>
#include <alibabacloud/models/CreateFunctionTaskResponseBody.hpp>
#include <alibabacloud/models/CreateFunctionTaskResponse.hpp>
#include <alibabacloud/models/CreateInterventionDictionaryRequest.hpp>
#include <alibabacloud/models/CreateInterventionDictionaryResponseBody.hpp>
#include <alibabacloud/models/CreateInterventionDictionaryResponse.hpp>
#include <alibabacloud/models/CreateQueryProcessorRequest.hpp>
#include <alibabacloud/models/CreateQueryProcessorResponseBody.hpp>
#include <alibabacloud/models/CreateQueryProcessorResponse.hpp>
#include <alibabacloud/models/CreateScheduledTaskRequest.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/CreateScheduledTaskResponse.hpp>
#include <alibabacloud/models/CreateSearchStrategyRequest.hpp>
#include <alibabacloud/models/CreateSearchStrategyResponseBody.hpp>
#include <alibabacloud/models/CreateSearchStrategyResponse.hpp>
#include <alibabacloud/models/CreateSecondRankRequest.hpp>
#include <alibabacloud/models/CreateSecondRankResponseBody.hpp>
#include <alibabacloud/models/CreateSecondRankResponse.hpp>
#include <alibabacloud/models/CreateSortScriptRequest.hpp>
#include <alibabacloud/models/CreateSortScriptResponseBody.hpp>
#include <alibabacloud/models/CreateSortScriptResponse.hpp>
#include <alibabacloud/models/CreateUserAnalyzerRequest.hpp>
#include <alibabacloud/models/CreateUserAnalyzerResponseBody.hpp>
#include <alibabacloud/models/CreateUserAnalyzerResponse.hpp>
#include <alibabacloud/models/DeleteABTestExperimentResponseBody.hpp>
#include <alibabacloud/models/DeleteABTestExperimentResponse.hpp>
#include <alibabacloud/models/DeleteABTestGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteABTestGroupResponse.hpp>
#include <alibabacloud/models/DeleteABTestSceneResponseBody.hpp>
#include <alibabacloud/models/DeleteABTestSceneResponse.hpp>
#include <alibabacloud/models/DeleteFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteFunctionInstanceResponse.hpp>
#include <alibabacloud/models/DeleteFunctionResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteFunctionResourceResponse.hpp>
#include <alibabacloud/models/DeleteFunctionTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteFunctionTaskResponse.hpp>
#include <alibabacloud/models/DeleteSortScriptResponseBody.hpp>
#include <alibabacloud/models/DeleteSortScriptResponse.hpp>
#include <alibabacloud/models/DeleteSortScriptFileResponseBody.hpp>
#include <alibabacloud/models/DeleteSortScriptFileResponse.hpp>
#include <alibabacloud/models/DescribeABTestExperimentResponseBody.hpp>
#include <alibabacloud/models/DescribeABTestExperimentResponse.hpp>
#include <alibabacloud/models/DescribeABTestGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeABTestGroupResponse.hpp>
#include <alibabacloud/models/DescribeABTestSceneResponseBody.hpp>
#include <alibabacloud/models/DescribeABTestSceneResponse.hpp>
#include <alibabacloud/models/DescribeAppResponseBody.hpp>
#include <alibabacloud/models/DescribeAppResponse.hpp>
#include <alibabacloud/models/DescribeAppGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeAppGroupResponse.hpp>
#include <alibabacloud/models/DescribeAppStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppsResponse.hpp>
#include <alibabacloud/models/DescribeDataCollctionResponseBody.hpp>
#include <alibabacloud/models/DescribeDataCollctionResponse.hpp>
#include <alibabacloud/models/DescribeElasticPlanRequest.hpp>
#include <alibabacloud/models/DescribeElasticPlanResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticPlanResponse.hpp>
#include <alibabacloud/models/DescribeFirstRankResponseBody.hpp>
#include <alibabacloud/models/DescribeFirstRankResponse.hpp>
#include <alibabacloud/models/DescribeInterventionDictionaryResponseBody.hpp>
#include <alibabacloud/models/DescribeInterventionDictionaryResponse.hpp>
#include <alibabacloud/models/DescribeQueryProcessorResponseBody.hpp>
#include <alibabacloud/models/DescribeQueryProcessorResponse.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeScheduledTaskResponse.hpp>
#include <alibabacloud/models/DescribeSecondRankResponseBody.hpp>
#include <alibabacloud/models/DescribeSecondRankResponse.hpp>
#include <alibabacloud/models/DescribeSlowQueryStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowQueryStatusResponse.hpp>
#include <alibabacloud/models/DescribeUserAnalyzerRequest.hpp>
#include <alibabacloud/models/DescribeUserAnalyzerResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAnalyzerResponse.hpp>
#include <alibabacloud/models/DisableSlowQueryResponseBody.hpp>
#include <alibabacloud/models/DisableSlowQueryResponse.hpp>
#include <alibabacloud/models/EnableSlowQueryResponseBody.hpp>
#include <alibabacloud/models/EnableSlowQueryResponse.hpp>
#include <alibabacloud/models/GenerateMergedTableRequest.hpp>
#include <alibabacloud/models/GenerateMergedTableResponseBody.hpp>
#include <alibabacloud/models/GenerateMergedTableResponse.hpp>
#include <alibabacloud/models/GetDomainRequest.hpp>
#include <alibabacloud/models/GetDomainResponseBody.hpp>
#include <alibabacloud/models/GetDomainResponse.hpp>
#include <alibabacloud/models/GetFunctionCurrentVersionRequest.hpp>
#include <alibabacloud/models/GetFunctionCurrentVersionResponseBody.hpp>
#include <alibabacloud/models/GetFunctionCurrentVersionResponse.hpp>
#include <alibabacloud/models/GetFunctionDefaultInstanceResponseBody.hpp>
#include <alibabacloud/models/GetFunctionDefaultInstanceResponse.hpp>
#include <alibabacloud/models/GetFunctionInstanceRequest.hpp>
#include <alibabacloud/models/GetFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/GetFunctionInstanceResponse.hpp>
#include <alibabacloud/models/GetFunctionResourceRequest.hpp>
#include <alibabacloud/models/GetFunctionResourceResponseBody.hpp>
#include <alibabacloud/models/GetFunctionResourceResponse.hpp>
#include <alibabacloud/models/GetFunctionTaskResponseBody.hpp>
#include <alibabacloud/models/GetFunctionTaskResponse.hpp>
#include <alibabacloud/models/GetFunctionVersionResponseBody.hpp>
#include <alibabacloud/models/GetFunctionVersionResponse.hpp>
#include <alibabacloud/models/GetScriptFileNamesResponseBody.hpp>
#include <alibabacloud/models/GetScriptFileNamesResponse.hpp>
#include <alibabacloud/models/GetSearchStrategyResponseBody.hpp>
#include <alibabacloud/models/GetSearchStrategyResponse.hpp>
#include <alibabacloud/models/GetSortScriptResponseBody.hpp>
#include <alibabacloud/models/GetSortScriptResponse.hpp>
#include <alibabacloud/models/GetSortScriptFileResponseBody.hpp>
#include <alibabacloud/models/GetSortScriptFileResponse.hpp>
#include <alibabacloud/models/ListABTestExperimentsResponseBody.hpp>
#include <alibabacloud/models/ListABTestExperimentsResponse.hpp>
#include <alibabacloud/models/ListABTestFixedFlowDividersResponseBody.hpp>
#include <alibabacloud/models/ListABTestFixedFlowDividersResponse.hpp>
#include <alibabacloud/models/ListABTestGroupsResponseBody.hpp>
#include <alibabacloud/models/ListABTestGroupsResponse.hpp>
#include <alibabacloud/models/ListABTestScenesResponseBody.hpp>
#include <alibabacloud/models/ListABTestScenesResponse.hpp>
#include <alibabacloud/models/ListAppGroupsRequest.hpp>
#include <alibabacloud/models/ListAppGroupsShrinkRequest.hpp>
#include <alibabacloud/models/ListAppGroupsResponseBody.hpp>
#include <alibabacloud/models/ListAppGroupsResponse.hpp>
#include <alibabacloud/models/ListDataCollectionsRequest.hpp>
#include <alibabacloud/models/ListDataCollectionsResponseBody.hpp>
#include <alibabacloud/models/ListDataCollectionsResponse.hpp>
#include <alibabacloud/models/ListDataSourceTableFieldsRequest.hpp>
#include <alibabacloud/models/ListDataSourceTableFieldsResponseBody.hpp>
#include <alibabacloud/models/ListDataSourceTableFieldsResponse.hpp>
#include <alibabacloud/models/ListDataSourceTablesRequest.hpp>
#include <alibabacloud/models/ListDataSourceTablesResponseBody.hpp>
#include <alibabacloud/models/ListDataSourceTablesResponse.hpp>
#include <alibabacloud/models/ListElasticPlansRequest.hpp>
#include <alibabacloud/models/ListElasticPlansResponseBody.hpp>
#include <alibabacloud/models/ListElasticPlansResponse.hpp>
#include <alibabacloud/models/ListFirstRanksResponseBody.hpp>
#include <alibabacloud/models/ListFirstRanksResponse.hpp>
#include <alibabacloud/models/ListFunctionInstancesRequest.hpp>
#include <alibabacloud/models/ListFunctionInstancesResponseBody.hpp>
#include <alibabacloud/models/ListFunctionInstancesResponse.hpp>
#include <alibabacloud/models/ListFunctionResourcesRequest.hpp>
#include <alibabacloud/models/ListFunctionResourcesResponseBody.hpp>
#include <alibabacloud/models/ListFunctionResourcesResponse.hpp>
#include <alibabacloud/models/ListFunctionTasksRequest.hpp>
#include <alibabacloud/models/ListFunctionTasksResponseBody.hpp>
#include <alibabacloud/models/ListFunctionTasksResponse.hpp>
#include <alibabacloud/models/ListInterventionDictionariesRequest.hpp>
#include <alibabacloud/models/ListInterventionDictionariesResponseBody.hpp>
#include <alibabacloud/models/ListInterventionDictionariesResponse.hpp>
#include <alibabacloud/models/ListInterventionDictionaryEntriesRequest.hpp>
#include <alibabacloud/models/ListInterventionDictionaryEntriesResponseBody.hpp>
#include <alibabacloud/models/ListInterventionDictionaryEntriesResponse.hpp>
#include <alibabacloud/models/ListInterventionDictionaryNerResultsRequest.hpp>
#include <alibabacloud/models/ListInterventionDictionaryNerResultsResponseBody.hpp>
#include <alibabacloud/models/ListInterventionDictionaryNerResultsResponse.hpp>
#include <alibabacloud/models/ListInterventionDictionaryRelatedEntitiesResponseBody.hpp>
#include <alibabacloud/models/ListInterventionDictionaryRelatedEntitiesResponse.hpp>
#include <alibabacloud/models/ListProceedingsRequest.hpp>
#include <alibabacloud/models/ListProceedingsResponseBody.hpp>
#include <alibabacloud/models/ListProceedingsResponse.hpp>
#include <alibabacloud/models/ListQueryProcessorAnalyzerResultsRequest.hpp>
#include <alibabacloud/models/ListQueryProcessorAnalyzerResultsResponseBody.hpp>
#include <alibabacloud/models/ListQueryProcessorAnalyzerResultsResponse.hpp>
#include <alibabacloud/models/ListQueryProcessorNersRequest.hpp>
#include <alibabacloud/models/ListQueryProcessorNersResponseBody.hpp>
#include <alibabacloud/models/ListQueryProcessorNersResponse.hpp>
#include <alibabacloud/models/ListQueryProcessorsRequest.hpp>
#include <alibabacloud/models/ListQueryProcessorsResponseBody.hpp>
#include <alibabacloud/models/ListQueryProcessorsResponse.hpp>
#include <alibabacloud/models/ListQuotaReviewTasksRequest.hpp>
#include <alibabacloud/models/ListQuotaReviewTasksResponseBody.hpp>
#include <alibabacloud/models/ListQuotaReviewTasksResponse.hpp>
#include <alibabacloud/models/ListScheduledTasksRequest.hpp>
#include <alibabacloud/models/ListScheduledTasksResponseBody.hpp>
#include <alibabacloud/models/ListScheduledTasksResponse.hpp>
#include <alibabacloud/models/ListSearchStrategiesResponseBody.hpp>
#include <alibabacloud/models/ListSearchStrategiesResponse.hpp>
#include <alibabacloud/models/ListSecondRanksResponseBody.hpp>
#include <alibabacloud/models/ListSecondRanksResponse.hpp>
#include <alibabacloud/models/ListSlowQueryCategoriesResponseBody.hpp>
#include <alibabacloud/models/ListSlowQueryCategoriesResponse.hpp>
#include <alibabacloud/models/ListSlowQueryQueriesResponseBody.hpp>
#include <alibabacloud/models/ListSlowQueryQueriesResponse.hpp>
#include <alibabacloud/models/ListSortExpressionsResponseBody.hpp>
#include <alibabacloud/models/ListSortExpressionsResponse.hpp>
#include <alibabacloud/models/ListSortScriptsResponseBody.hpp>
#include <alibabacloud/models/ListSortScriptsResponse.hpp>
#include <alibabacloud/models/ListStatisticLogsRequest.hpp>
#include <alibabacloud/models/ListStatisticLogsResponseBody.hpp>
#include <alibabacloud/models/ListStatisticLogsResponse.hpp>
#include <alibabacloud/models/ListStatisticReportRequest.hpp>
#include <alibabacloud/models/ListStatisticReportResponseBody.hpp>
#include <alibabacloud/models/ListStatisticReportResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesShrinkRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListUserAnalyzerEntriesRequest.hpp>
#include <alibabacloud/models/ListUserAnalyzerEntriesResponseBody.hpp>
#include <alibabacloud/models/ListUserAnalyzerEntriesResponse.hpp>
#include <alibabacloud/models/ListUserAnalyzersRequest.hpp>
#include <alibabacloud/models/ListUserAnalyzersResponseBody.hpp>
#include <alibabacloud/models/ListUserAnalyzersResponse.hpp>
#include <alibabacloud/models/ModifyAppGroupRequest.hpp>
#include <alibabacloud/models/ModifyAppGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyAppGroupResponse.hpp>
#include <alibabacloud/models/ModifyAppGroupQuotaRequest.hpp>
#include <alibabacloud/models/ModifyAppGroupQuotaResponseBody.hpp>
#include <alibabacloud/models/ModifyAppGroupQuotaResponse.hpp>
#include <alibabacloud/models/ModifyElasticPlanRequest.hpp>
#include <alibabacloud/models/ModifyElasticPlanResponseBody.hpp>
#include <alibabacloud/models/ModifyElasticPlanResponse.hpp>
#include <alibabacloud/models/ModifyFirstRankRequest.hpp>
#include <alibabacloud/models/ModifyFirstRankResponseBody.hpp>
#include <alibabacloud/models/ModifyFirstRankResponse.hpp>
#include <alibabacloud/models/ModifyQueryProcessorRequest.hpp>
#include <alibabacloud/models/ModifyQueryProcessorResponseBody.hpp>
#include <alibabacloud/models/ModifyQueryProcessorResponse.hpp>
#include <alibabacloud/models/ModifyScheduledTaskRequest.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/ModifyScheduledTaskResponse.hpp>
#include <alibabacloud/models/ModifySecondRankRequest.hpp>
#include <alibabacloud/models/ModifySecondRankResponseBody.hpp>
#include <alibabacloud/models/ModifySecondRankResponse.hpp>
#include <alibabacloud/models/PushInterventionDictionaryEntriesRequest.hpp>
#include <alibabacloud/models/PushInterventionDictionaryEntriesResponseBody.hpp>
#include <alibabacloud/models/PushInterventionDictionaryEntriesResponse.hpp>
#include <alibabacloud/models/PushUserAnalyzerEntriesRequest.hpp>
#include <alibabacloud/models/PushUserAnalyzerEntriesResponseBody.hpp>
#include <alibabacloud/models/PushUserAnalyzerEntriesResponse.hpp>
#include <alibabacloud/models/ReleaseSortScriptResponseBody.hpp>
#include <alibabacloud/models/ReleaseSortScriptResponse.hpp>
#include <alibabacloud/models/RemoveAppResponseBody.hpp>
#include <alibabacloud/models/RemoveAppResponse.hpp>
#include <alibabacloud/models/RemoveAppGroupResponseBody.hpp>
#include <alibabacloud/models/RemoveAppGroupResponse.hpp>
#include <alibabacloud/models/RemoveDataCollectionResponseBody.hpp>
#include <alibabacloud/models/RemoveDataCollectionResponse.hpp>
#include <alibabacloud/models/RemoveElasticPlanRequest.hpp>
#include <alibabacloud/models/RemoveElasticPlanResponseBody.hpp>
#include <alibabacloud/models/RemoveElasticPlanResponse.hpp>
#include <alibabacloud/models/RemoveFirstRankResponseBody.hpp>
#include <alibabacloud/models/RemoveFirstRankResponse.hpp>
#include <alibabacloud/models/RemoveInterventionDictionaryResponseBody.hpp>
#include <alibabacloud/models/RemoveInterventionDictionaryResponse.hpp>
#include <alibabacloud/models/RemoveQueryProcessorResponseBody.hpp>
#include <alibabacloud/models/RemoveQueryProcessorResponse.hpp>
#include <alibabacloud/models/RemoveScheduledTaskResponseBody.hpp>
#include <alibabacloud/models/RemoveScheduledTaskResponse.hpp>
#include <alibabacloud/models/RemoveSearchStrategyResponseBody.hpp>
#include <alibabacloud/models/RemoveSearchStrategyResponse.hpp>
#include <alibabacloud/models/RemoveSecondRankResponseBody.hpp>
#include <alibabacloud/models/RemoveSecondRankResponse.hpp>
#include <alibabacloud/models/RemoveUserAnalyzerResponseBody.hpp>
#include <alibabacloud/models/RemoveUserAnalyzerResponse.hpp>
#include <alibabacloud/models/RenewAppGroupRequest.hpp>
#include <alibabacloud/models/RenewAppGroupResponseBody.hpp>
#include <alibabacloud/models/RenewAppGroupResponse.hpp>
#include <alibabacloud/models/ReplaceAppGroupCommodityCodeResponseBody.hpp>
#include <alibabacloud/models/ReplaceAppGroupCommodityCodeResponse.hpp>
#include <alibabacloud/models/SaveSortScriptFileRequest.hpp>
#include <alibabacloud/models/SaveSortScriptFileResponseBody.hpp>
#include <alibabacloud/models/SaveSortScriptFileResponse.hpp>
#include <alibabacloud/models/StartSlowQueryAnalyzerResponseBody.hpp>
#include <alibabacloud/models/StartSlowQueryAnalyzerResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnbindESUserAnalyzerRequest.hpp>
#include <alibabacloud/models/UnbindESUserAnalyzerResponseBody.hpp>
#include <alibabacloud/models/UnbindESUserAnalyzerResponse.hpp>
#include <alibabacloud/models/UnbindEsInstanceResponseBody.hpp>
#include <alibabacloud/models/UnbindEsInstanceResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesShrinkRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateABTestExperimentRequest.hpp>
#include <alibabacloud/models/UpdateABTestExperimentResponseBody.hpp>
#include <alibabacloud/models/UpdateABTestExperimentResponse.hpp>
#include <alibabacloud/models/UpdateABTestFixedFlowDividersRequest.hpp>
#include <alibabacloud/models/UpdateABTestFixedFlowDividersResponseBody.hpp>
#include <alibabacloud/models/UpdateABTestFixedFlowDividersResponse.hpp>
#include <alibabacloud/models/UpdateABTestGroupRequest.hpp>
#include <alibabacloud/models/UpdateABTestGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateABTestGroupResponse.hpp>
#include <alibabacloud/models/UpdateABTestSceneRequest.hpp>
#include <alibabacloud/models/UpdateABTestSceneResponseBody.hpp>
#include <alibabacloud/models/UpdateABTestSceneResponse.hpp>
#include <alibabacloud/models/UpdateAppGroupDeleteProtectionRequest.hpp>
#include <alibabacloud/models/UpdateAppGroupDeleteProtectionResponseBody.hpp>
#include <alibabacloud/models/UpdateAppGroupDeleteProtectionResponse.hpp>
#include <alibabacloud/models/UpdateFetchFieldsRequest.hpp>
#include <alibabacloud/models/UpdateFetchFieldsResponseBody.hpp>
#include <alibabacloud/models/UpdateFetchFieldsResponse.hpp>
#include <alibabacloud/models/UpdateFunctionDefaultInstanceRequest.hpp>
#include <alibabacloud/models/UpdateFunctionDefaultInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateFunctionDefaultInstanceResponse.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceRequest.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateFunctionInstanceResponse.hpp>
#include <alibabacloud/models/UpdateFunctionResourceRequest.hpp>
#include <alibabacloud/models/UpdateFunctionResourceResponseBody.hpp>
#include <alibabacloud/models/UpdateFunctionResourceResponse.hpp>
#include <alibabacloud/models/UpdateSearchStrategyRequest.hpp>
#include <alibabacloud/models/UpdateSearchStrategyResponseBody.hpp>
#include <alibabacloud/models/UpdateSearchStrategyResponse.hpp>
#include <alibabacloud/models/UpdateSortScriptRequest.hpp>
#include <alibabacloud/models/UpdateSortScriptResponseBody.hpp>
#include <alibabacloud/models/UpdateSortScriptResponse.hpp>
#include <alibabacloud/models/UpdateSummariesRequest.hpp>
#include <alibabacloud/models/UpdateSummariesResponseBody.hpp>
#include <alibabacloud/models/UpdateSummariesResponse.hpp>
#include <alibabacloud/models/ValidateDataSourcesRequest.hpp>
#include <alibabacloud/models/ValidateDataSourcesResponseBody.hpp>
#include <alibabacloud/models/ValidateDataSourcesResponse.hpp>

#endif
