// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_SAVEDATASERVICEAPITESTRESULTREQUEST_HPP_
#define ALIBABACLOUD_MODELS_SAVEDATASERVICEAPITESTRESULTREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace DataworksPublic20200518
{
namespace Models
{
  class SaveDataServiceApiTestResultRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const SaveDataServiceApiTestResultRequest& obj) { 
      DARABONBA_PTR_TO_JSON(ApiId, apiId_);
      DARABONBA_PTR_TO_JSON(AutoGenerate, autoGenerate_);
      DARABONBA_PTR_TO_JSON(FailResultSample, failResultSample_);
      DARABONBA_PTR_TO_JSON(ProjectId, projectId_);
      DARABONBA_PTR_TO_JSON(ResultSample, resultSample_);
    };
    friend void from_json(const Darabonba::Json& j, SaveDataServiceApiTestResultRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(ApiId, apiId_);
      DARABONBA_PTR_FROM_JSON(AutoGenerate, autoGenerate_);
      DARABONBA_PTR_FROM_JSON(FailResultSample, failResultSample_);
      DARABONBA_PTR_FROM_JSON(ProjectId, projectId_);
      DARABONBA_PTR_FROM_JSON(ResultSample, resultSample_);
    };
    SaveDataServiceApiTestResultRequest() = default ;
    SaveDataServiceApiTestResultRequest(const SaveDataServiceApiTestResultRequest &) = default ;
    SaveDataServiceApiTestResultRequest(SaveDataServiceApiTestResultRequest &&) = default ;
    SaveDataServiceApiTestResultRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~SaveDataServiceApiTestResultRequest() = default ;
    SaveDataServiceApiTestResultRequest& operator=(const SaveDataServiceApiTestResultRequest &) = default ;
    SaveDataServiceApiTestResultRequest& operator=(SaveDataServiceApiTestResultRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { this->apiId_ != nullptr
        && this->autoGenerate_ != nullptr && this->failResultSample_ != nullptr && this->projectId_ != nullptr && this->resultSample_ != nullptr; };
    // apiId Field Functions 
    bool hasApiId() const { return this->apiId_ != nullptr;};
    void deleteApiId() { this->apiId_ = nullptr;};
    inline int64_t apiId() const { DARABONBA_PTR_GET_DEFAULT(apiId_, 0L) };
    inline SaveDataServiceApiTestResultRequest& setApiId(int64_t apiId) { DARABONBA_PTR_SET_VALUE(apiId_, apiId) };


    // autoGenerate Field Functions 
    bool hasAutoGenerate() const { return this->autoGenerate_ != nullptr;};
    void deleteAutoGenerate() { this->autoGenerate_ = nullptr;};
    inline bool autoGenerate() const { DARABONBA_PTR_GET_DEFAULT(autoGenerate_, false) };
    inline SaveDataServiceApiTestResultRequest& setAutoGenerate(bool autoGenerate) { DARABONBA_PTR_SET_VALUE(autoGenerate_, autoGenerate) };


    // failResultSample Field Functions 
    bool hasFailResultSample() const { return this->failResultSample_ != nullptr;};
    void deleteFailResultSample() { this->failResultSample_ = nullptr;};
    inline string failResultSample() const { DARABONBA_PTR_GET_DEFAULT(failResultSample_, "") };
    inline SaveDataServiceApiTestResultRequest& setFailResultSample(string failResultSample) { DARABONBA_PTR_SET_VALUE(failResultSample_, failResultSample) };


    // projectId Field Functions 
    bool hasProjectId() const { return this->projectId_ != nullptr;};
    void deleteProjectId() { this->projectId_ = nullptr;};
    inline int64_t projectId() const { DARABONBA_PTR_GET_DEFAULT(projectId_, 0L) };
    inline SaveDataServiceApiTestResultRequest& setProjectId(int64_t projectId) { DARABONBA_PTR_SET_VALUE(projectId_, projectId) };


    // resultSample Field Functions 
    bool hasResultSample() const { return this->resultSample_ != nullptr;};
    void deleteResultSample() { this->resultSample_ = nullptr;};
    inline string resultSample() const { DARABONBA_PTR_GET_DEFAULT(resultSample_, "") };
    inline SaveDataServiceApiTestResultRequest& setResultSample(string resultSample) { DARABONBA_PTR_SET_VALUE(resultSample_, resultSample) };


  protected:
    // The API ID. You can call the [ListDataServiceApis](https://help.aliyun.com/document_detail/174012.html) operation to obtain the ID.
    // 
    // This parameter is required.
    std::shared_ptr<int64_t> apiId_ = nullptr;
    // Specifies whether to use the test results generated by the system. If you do not configure the resultSample or failResultSample parameter, the test results generated by the system are used.
    std::shared_ptr<bool> autoGenerate_ = nullptr;
    // The sample failure response of the API. This parameter is optional.
    std::shared_ptr<string> failResultSample_ = nullptr;
    // The DataWorks workspace ID. You can log on to the [DataWorks console](https://workbench.data.aliyun.com/console) and go to the Workspace page to obtain the workspace ID.
    // 
    // This parameter is required.
    std::shared_ptr<int64_t> projectId_ = nullptr;
    // The sample success response of the API. This parameter is optional.
    std::shared_ptr<string> resultSample_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace DataworksPublic20200518
#endif
