// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DMS20250414MODEL_HPP_
#define ALIBABACLOUD_DMS20250414MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AgentServiceOrderSummaryVO.hpp>
#include <alibabacloud/models/AgentServiceOrderVO.hpp>
#include <alibabacloud/models/AgenticCatalog.hpp>
#include <alibabacloud/models/AgenticDatabaseEngineMeta.hpp>
#include <alibabacloud/models/AgenticDatabase.hpp>
#include <alibabacloud/models/AgenticDatabaseObject.hpp>
#include <alibabacloud/models/AgenticDmsInstanceSyncTask.hpp>
#include <alibabacloud/models/AgenticDmsInstanceSyncTaskInstance.hpp>
#include <alibabacloud/models/AgenticKnowledgeView.hpp>
#include <alibabacloud/models/AgenticResourceOwner.hpp>
#include <alibabacloud/models/AgenticTableEngineMeta.hpp>
#include <alibabacloud/models/AgenticTableBaseInfo.hpp>
#include <alibabacloud/models/AgenticTableColumnEngineMeta.hpp>
#include <alibabacloud/models/AgenticTableColumn.hpp>
#include <alibabacloud/models/AgenticTableIndex.hpp>
#include <alibabacloud/models/DLCatalog.hpp>
#include <alibabacloud/models/DLColumn.hpp>
#include <alibabacloud/models/DLDatabase.hpp>
#include <alibabacloud/models/DLResourceUri.hpp>
#include <alibabacloud/models/DLFunction.hpp>
#include <alibabacloud/models/DLFunctionInput.hpp>
#include <alibabacloud/models/DLOrder.hpp>
#include <alibabacloud/models/DLSerdeInfo.hpp>
#include <alibabacloud/models/DLSkewedInfo.hpp>
#include <alibabacloud/models/DLStorageDescriptor.hpp>
#include <alibabacloud/models/DLPartition.hpp>
#include <alibabacloud/models/DLPartitionInput.hpp>
#include <alibabacloud/models/DLTable.hpp>
#include <alibabacloud/models/DLTableInput.hpp>
#include <alibabacloud/models/DLTablebaseInfo.hpp>
#include <alibabacloud/models/DataAgentApplication.hpp>
#include <alibabacloud/models/DataAgentBillingInstance.hpp>
#include <alibabacloud/models/DataMountInfo.hpp>
#include <alibabacloud/models/DmsGatewayOrder.hpp>
#include <alibabacloud/models/DmsKnowledgeSearchOrderInfoDO.hpp>
#include <alibabacloud/models/ForeignInstance.hpp>
#include <alibabacloud/models/ForeignInstanceCredInfo.hpp>
#include <alibabacloud/models/ManagedDaOrderSummaryVO.hpp>
#include <alibabacloud/models/ManagedDaOrderVO.hpp>
#include <alibabacloud/models/MdbAgentInstanceVo.hpp>
#include <alibabacloud/models/OneMetaDatabaseEngineMeta.hpp>
#include <alibabacloud/models/OneMetaDatabase.hpp>
#include <alibabacloud/models/OneMetaDatabaseObject.hpp>
#include <alibabacloud/models/OneMetaKnowledgeBase.hpp>
#include <alibabacloud/models/OneMetaKnowledgeBaseChunk.hpp>
#include <alibabacloud/models/OneMetaKnowledgeBaseDocument.hpp>
#include <alibabacloud/models/OneMetaSqlTemplateView.hpp>
#include <alibabacloud/models/OneMetaTableEngineMeta.hpp>
#include <alibabacloud/models/OneMetaTableBaseInfo.hpp>
#include <alibabacloud/models/OneMetaTableColumnEngineMeta.hpp>
#include <alibabacloud/models/OneMetaTableColumn.hpp>
#include <alibabacloud/models/OneMetaTableIndex.hpp>
#include <alibabacloud/models/OpenClawInstanceQuotaVO.hpp>
#include <alibabacloud/models/OpenClawInstanceVO.hpp>
#include <alibabacloud/models/OssieModelView.hpp>
#include <alibabacloud/models/PartitionError.hpp>
#include <alibabacloud/models/TrialOrderEligibilityVO.hpp>
#include <alibabacloud/models/AddDataAgentMemoryRequest.hpp>
#include <alibabacloud/models/AddDataAgentMemoryResponseBody.hpp>
#include <alibabacloud/models/AddDataAgentMemoryResponse.hpp>
#include <alibabacloud/models/AddUserToDataAgentWorkspaceRequest.hpp>
#include <alibabacloud/models/AddUserToDataAgentWorkspaceResponseBody.hpp>
#include <alibabacloud/models/AddUserToDataAgentWorkspaceResponse.hpp>
#include <alibabacloud/models/CheckDataAgentMemoryConfigRequest.hpp>
#include <alibabacloud/models/CheckDataAgentMemoryConfigResponseBody.hpp>
#include <alibabacloud/models/CheckDataAgentMemoryConfigResponse.hpp>
#include <alibabacloud/models/ConfigAirflowRequest.hpp>
#include <alibabacloud/models/ConfigAirflowShrinkRequest.hpp>
#include <alibabacloud/models/ConfigAirflowResponseBody.hpp>
#include <alibabacloud/models/ConfigAirflowResponse.hpp>
#include <alibabacloud/models/ConfigDataAgentMemoryRequest.hpp>
#include <alibabacloud/models/ConfigDataAgentMemoryResponseBody.hpp>
#include <alibabacloud/models/ConfigDataAgentMemoryResponse.hpp>
#include <alibabacloud/models/CreateAgentRequest.hpp>
#include <alibabacloud/models/CreateAgentResponseBody.hpp>
#include <alibabacloud/models/CreateAgentResponse.hpp>
#include <alibabacloud/models/CreateAirflowRequest.hpp>
#include <alibabacloud/models/CreateAirflowShrinkRequest.hpp>
#include <alibabacloud/models/CreateAirflowResponseBody.hpp>
#include <alibabacloud/models/CreateAirflowResponse.hpp>
#include <alibabacloud/models/CreateAirflowLoginTokenRequest.hpp>
#include <alibabacloud/models/CreateAirflowLoginTokenResponseBody.hpp>
#include <alibabacloud/models/CreateAirflowLoginTokenResponse.hpp>
#include <alibabacloud/models/CreateCustomAgentRequest.hpp>
#include <alibabacloud/models/CreateCustomAgentShrinkRequest.hpp>
#include <alibabacloud/models/CreateCustomAgentResponseBody.hpp>
#include <alibabacloud/models/CreateCustomAgentResponse.hpp>
#include <alibabacloud/models/CreateDataAgentAccuracyTestRequest.hpp>
#include <alibabacloud/models/CreateDataAgentAccuracyTestResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentAccuracyTestResponse.hpp>
#include <alibabacloud/models/CreateDataAgentFeedbackRequest.hpp>
#include <alibabacloud/models/CreateDataAgentFeedbackResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentFeedbackResponse.hpp>
#include <alibabacloud/models/CreateDataAgentKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/CreateDataAgentKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/CreateDataAgentSessionRequest.hpp>
#include <alibabacloud/models/CreateDataAgentSessionShrinkRequest.hpp>
#include <alibabacloud/models/CreateDataAgentSessionResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentSessionResponse.hpp>
#include <alibabacloud/models/CreateDataAgentSkillMetaRequest.hpp>
#include <alibabacloud/models/CreateDataAgentSkillMetaResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentSkillMetaResponse.hpp>
#include <alibabacloud/models/CreateDataAgentThemeRequest.hpp>
#include <alibabacloud/models/CreateDataAgentThemeResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentThemeResponse.hpp>
#include <alibabacloud/models/CreateDataAgentWorkspaceRequest.hpp>
#include <alibabacloud/models/CreateDataAgentWorkspaceResponseBody.hpp>
#include <alibabacloud/models/CreateDataAgentWorkspaceResponse.hpp>
#include <alibabacloud/models/CreateOneMetaSqlTemplateRequest.hpp>
#include <alibabacloud/models/CreateOneMetaSqlTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateOneMetaSqlTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAirflowRequest.hpp>
#include <alibabacloud/models/DeleteAirflowResponseBody.hpp>
#include <alibabacloud/models/DeleteAirflowResponse.hpp>
#include <alibabacloud/models/DeleteCustomAgentRequest.hpp>
#include <alibabacloud/models/DeleteCustomAgentResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomAgentResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentAccuracyTestRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentAccuracyTestResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentAccuracyTestResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentMcpRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentMcpShrinkRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentMcpResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentMcpResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentMemoryRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentMemoryResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentMemoryResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentSkillMetaRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentSkillMetaResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentSkillMetaResponse.hpp>
#include <alibabacloud/models/DeleteDataAgentWorkspaceRequest.hpp>
#include <alibabacloud/models/DeleteDataAgentWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteDataAgentWorkspaceResponse.hpp>
#include <alibabacloud/models/DeleteDocumentRequest.hpp>
#include <alibabacloud/models/DeleteDocumentResponseBody.hpp>
#include <alibabacloud/models/DeleteDocumentResponse.hpp>
#include <alibabacloud/models/DeleteDocumentChunksRequest.hpp>
#include <alibabacloud/models/DeleteDocumentChunksShrinkRequest.hpp>
#include <alibabacloud/models/DeleteDocumentChunksResponseBody.hpp>
#include <alibabacloud/models/DeleteDocumentChunksResponse.hpp>
#include <alibabacloud/models/DeleteFileUploadRequest.hpp>
#include <alibabacloud/models/DeleteFileUploadResponseBody.hpp>
#include <alibabacloud/models/DeleteFileUploadResponse.hpp>
#include <alibabacloud/models/DeleteOneMetaOssieModelRequest.hpp>
#include <alibabacloud/models/DeleteOneMetaOssieModelResponseBody.hpp>
#include <alibabacloud/models/DeleteOneMetaOssieModelResponse.hpp>
#include <alibabacloud/models/DeleteOneMetaSqlTemplateRequest.hpp>
#include <alibabacloud/models/DeleteOneMetaSqlTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteOneMetaSqlTemplateResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceCodeRequest.hpp>
#include <alibabacloud/models/DeleteWorkspaceCodeResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceCodeResponse.hpp>
#include <alibabacloud/models/DescribeCustomAgentRequest.hpp>
#include <alibabacloud/models/DescribeCustomAgentResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomAgentResponse.hpp>
#include <alibabacloud/models/DescribeCustomAgentMonitorMetricsRequest.hpp>
#include <alibabacloud/models/DescribeCustomAgentMonitorMetricsResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomAgentMonitorMetricsResponse.hpp>
#include <alibabacloud/models/DescribeDataAgentMetricsRequest.hpp>
#include <alibabacloud/models/DescribeDataAgentMetricsResponseBody.hpp>
#include <alibabacloud/models/DescribeDataAgentMetricsResponse.hpp>
#include <alibabacloud/models/DescribeDataAgentSessionRequest.hpp>
#include <alibabacloud/models/DescribeDataAgentSessionResponseBody.hpp>
#include <alibabacloud/models/DescribeDataAgentSessionResponse.hpp>
#include <alibabacloud/models/DescribeDataAgentThemeRequest.hpp>
#include <alibabacloud/models/DescribeDataAgentThemeResponseBody.hpp>
#include <alibabacloud/models/DescribeDataAgentThemeResponse.hpp>
#include <alibabacloud/models/DescribeDocumentRequest.hpp>
#include <alibabacloud/models/DescribeDocumentResponseBody.hpp>
#include <alibabacloud/models/DescribeDocumentResponse.hpp>
#include <alibabacloud/models/DescribeFileUploadSignatureRequest.hpp>
#include <alibabacloud/models/DescribeFileUploadSignatureResponseBody.hpp>
#include <alibabacloud/models/DescribeFileUploadSignatureResponse.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseStatsRequest.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseStatsResponseBody.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseStatsResponse.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseUploadSignatureRequest.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseUploadSignatureResponseBody.hpp>
#include <alibabacloud/models/DescribeKnowledgeBaseUploadSignatureResponse.hpp>
#include <alibabacloud/models/DescribeSkillFileUploadSignatureRequest.hpp>
#include <alibabacloud/models/DescribeSkillFileUploadSignatureResponseBody.hpp>
#include <alibabacloud/models/DescribeSkillFileUploadSignatureResponse.hpp>
#include <alibabacloud/models/FileUploadCallbackRequest.hpp>
#include <alibabacloud/models/FileUploadCallbackResponseBody.hpp>
#include <alibabacloud/models/FileUploadCallbackResponse.hpp>
#include <alibabacloud/models/GetAgenticAgentByInstallTokenRequest.hpp>
#include <alibabacloud/models/GetAgenticAgentByInstallTokenResponseBody.hpp>
#include <alibabacloud/models/GetAgenticAgentByInstallTokenResponse.hpp>
#include <alibabacloud/models/GetAirflowRequest.hpp>
#include <alibabacloud/models/GetAirflowResponseBody.hpp>
#include <alibabacloud/models/GetAirflowResponse.hpp>
#include <alibabacloud/models/GetChatContentRequest.hpp>
#include <alibabacloud/models/GetChatContentResponseBody.hpp>
#include <alibabacloud/models/GetChatContentResponse.hpp>
#include <alibabacloud/models/GetDataAgentMcpRequest.hpp>
#include <alibabacloud/models/GetDataAgentMcpResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentMcpResponse.hpp>
#include <alibabacloud/models/GetDataAgentSubAccountInfoRequest.hpp>
#include <alibabacloud/models/GetDataAgentSubAccountInfoResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentSubAccountInfoResponse.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageRequest.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageShrinkRequest.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageResponse.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageMetricsRequest.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageMetricsShrinkRequest.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageMetricsResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentTaskModelUsageMetricsResponse.hpp>
#include <alibabacloud/models/GetDataAgentThemeUploadSignatureRequest.hpp>
#include <alibabacloud/models/GetDataAgentThemeUploadSignatureResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentThemeUploadSignatureResponse.hpp>
#include <alibabacloud/models/GetDataAgentWorkspaceInfoRequest.hpp>
#include <alibabacloud/models/GetDataAgentWorkspaceInfoResponseBody.hpp>
#include <alibabacloud/models/GetDataAgentWorkspaceInfoResponse.hpp>
#include <alibabacloud/models/GetListMcpServerToolsResultRequest.hpp>
#include <alibabacloud/models/GetListMcpServerToolsResultResponseBody.hpp>
#include <alibabacloud/models/GetListMcpServerToolsResultResponse.hpp>
#include <alibabacloud/models/GetNotebookAndSubmitTaskRequest.hpp>
#include <alibabacloud/models/GetNotebookAndSubmitTaskResponseBody.hpp>
#include <alibabacloud/models/GetNotebookAndSubmitTaskResponse.hpp>
#include <alibabacloud/models/GetNotebookTaskStatusRequest.hpp>
#include <alibabacloud/models/GetNotebookTaskStatusResponseBody.hpp>
#include <alibabacloud/models/GetNotebookTaskStatusResponse.hpp>
#include <alibabacloud/models/GetOneMetaOssieModelRequest.hpp>
#include <alibabacloud/models/GetOneMetaOssieModelResponseBody.hpp>
#include <alibabacloud/models/GetOneMetaOssieModelResponse.hpp>
#include <alibabacloud/models/GetSqlConsoleOperationLogRequest.hpp>
#include <alibabacloud/models/GetSqlConsoleOperationLogResponseBody.hpp>
#include <alibabacloud/models/GetSqlConsoleOperationLogResponse.hpp>
#include <alibabacloud/models/GetWorkspaceCodeRequest.hpp>
#include <alibabacloud/models/GetWorkspaceCodeResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceCodeResponse.hpp>
#include <alibabacloud/models/GetWorkspaceCodePublishSettingRequest.hpp>
#include <alibabacloud/models/GetWorkspaceCodePublishSettingResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceCodePublishSettingResponse.hpp>
#include <alibabacloud/models/GetWorkspaceQuotaRequest.hpp>
#include <alibabacloud/models/GetWorkspaceQuotaResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceQuotaResponse.hpp>
#include <alibabacloud/models/ImportOneMetaOssieModelRequest.hpp>
#include <alibabacloud/models/ImportOneMetaOssieModelResponseBody.hpp>
#include <alibabacloud/models/ImportOneMetaOssieModelResponse.hpp>
#include <alibabacloud/models/InitWorkspaceSystemMcpServerRequest.hpp>
#include <alibabacloud/models/InitWorkspaceSystemMcpServerResponseBody.hpp>
#include <alibabacloud/models/InitWorkspaceSystemMcpServerResponse.hpp>
#include <alibabacloud/models/InstallDataAgentMcpRequest.hpp>
#include <alibabacloud/models/InstallDataAgentMcpResponseBody.hpp>
#include <alibabacloud/models/InstallDataAgentMcpResponse.hpp>
#include <alibabacloud/models/ListAirflowVersionsRequest.hpp>
#include <alibabacloud/models/ListAirflowVersionsResponseBody.hpp>
#include <alibabacloud/models/ListAirflowVersionsResponse.hpp>
#include <alibabacloud/models/ListAirflowsRequest.hpp>
#include <alibabacloud/models/ListAirflowsResponseBody.hpp>
#include <alibabacloud/models/ListAirflowsResponse.hpp>
#include <alibabacloud/models/ListCustomAgentRequest.hpp>
#include <alibabacloud/models/ListCustomAgentResponseBody.hpp>
#include <alibabacloud/models/ListCustomAgentResponse.hpp>
#include <alibabacloud/models/ListCustomAgentMonitorSessionsRequest.hpp>
#include <alibabacloud/models/ListCustomAgentMonitorSessionsResponseBody.hpp>
#include <alibabacloud/models/ListCustomAgentMonitorSessionsResponse.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestInstancesRequest.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestInstancesResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestInstancesResponse.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestResultsRequest.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestResultsResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestResultsResponse.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestTasksRequest.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestTasksResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentAccuracyTestTasksResponse.hpp>
#include <alibabacloud/models/ListDataAgentMcpRequest.hpp>
#include <alibabacloud/models/ListDataAgentMcpResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentMcpResponse.hpp>
#include <alibabacloud/models/ListDataAgentMemoryRequest.hpp>
#include <alibabacloud/models/ListDataAgentMemoryResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentMemoryResponse.hpp>
#include <alibabacloud/models/ListDataAgentSessionRequest.hpp>
#include <alibabacloud/models/ListDataAgentSessionResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentSessionResponse.hpp>
#include <alibabacloud/models/ListDataAgentSkillMetaRequest.hpp>
#include <alibabacloud/models/ListDataAgentSkillMetaResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentSkillMetaResponse.hpp>
#include <alibabacloud/models/ListDataAgentThemeRequest.hpp>
#include <alibabacloud/models/ListDataAgentThemeResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentThemeResponse.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceRequest.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceResponse.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceMemberRequest.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceMemberResponseBody.hpp>
#include <alibabacloud/models/ListDataAgentWorkspaceMemberResponse.hpp>
#include <alibabacloud/models/ListDataCenterDatabaseRequest.hpp>
#include <alibabacloud/models/ListDataCenterDatabaseResponseBody.hpp>
#include <alibabacloud/models/ListDataCenterDatabaseResponse.hpp>
#include <alibabacloud/models/ListDataCenterTableRequest.hpp>
#include <alibabacloud/models/ListDataCenterTableResponseBody.hpp>
#include <alibabacloud/models/ListDataCenterTableResponse.hpp>
#include <alibabacloud/models/ListDocumentChunksRequest.hpp>
#include <alibabacloud/models/ListDocumentChunksResponseBody.hpp>
#include <alibabacloud/models/ListDocumentChunksResponse.hpp>
#include <alibabacloud/models/ListDocumentsRequest.hpp>
#include <alibabacloud/models/ListDocumentsResponseBody.hpp>
#include <alibabacloud/models/ListDocumentsResponse.hpp>
#include <alibabacloud/models/ListFileUploadRequest.hpp>
#include <alibabacloud/models/ListFileUploadResponseBody.hpp>
#include <alibabacloud/models/ListFileUploadResponse.hpp>
#include <alibabacloud/models/ListKnowledgeBasesRequest.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResponseBody.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResponse.hpp>
#include <alibabacloud/models/ListOneMetaOssieModelsRequest.hpp>
#include <alibabacloud/models/ListOneMetaOssieModelsResponseBody.hpp>
#include <alibabacloud/models/ListOneMetaOssieModelsResponse.hpp>
#include <alibabacloud/models/ListOneMetaSqlTemplatesRequest.hpp>
#include <alibabacloud/models/ListOneMetaSqlTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListOneMetaSqlTemplatesResponse.hpp>
#include <alibabacloud/models/ListWorkspaceCodeRequest.hpp>
#include <alibabacloud/models/ListWorkspaceCodeResponseBody.hpp>
#include <alibabacloud/models/ListWorkspaceCodeResponse.hpp>
#include <alibabacloud/models/ModifyCustomAgentRequest.hpp>
#include <alibabacloud/models/ModifyCustomAgentShrinkRequest.hpp>
#include <alibabacloud/models/ModifyCustomAgentResponseBody.hpp>
#include <alibabacloud/models/ModifyCustomAgentResponse.hpp>
#include <alibabacloud/models/ModifyDataAgentMcpRequest.hpp>
#include <alibabacloud/models/ModifyDataAgentMcpResponseBody.hpp>
#include <alibabacloud/models/ModifyDataAgentMcpResponse.hpp>
#include <alibabacloud/models/ModifyDataAgentThemeRequest.hpp>
#include <alibabacloud/models/ModifyDataAgentThemeResponseBody.hpp>
#include <alibabacloud/models/ModifyDataAgentThemeResponse.hpp>
#include <alibabacloud/models/OperateCustomAgentRequest.hpp>
#include <alibabacloud/models/OperateCustomAgentResponseBody.hpp>
#include <alibabacloud/models/OperateCustomAgentResponse.hpp>
#include <alibabacloud/models/RedeployAirflowRequest.hpp>
#include <alibabacloud/models/RedeployAirflowResponseBody.hpp>
#include <alibabacloud/models/RedeployAirflowResponse.hpp>
#include <alibabacloud/models/RemoveUserToDataAgentWorkspaceRequest.hpp>
#include <alibabacloud/models/RemoveUserToDataAgentWorkspaceResponseBody.hpp>
#include <alibabacloud/models/RemoveUserToDataAgentWorkspaceResponse.hpp>
#include <alibabacloud/models/ResetAgenticApiKeyRequest.hpp>
#include <alibabacloud/models/ResetAgenticApiKeyResponseBody.hpp>
#include <alibabacloud/models/ResetAgenticApiKeyResponse.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/RetrieveKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/SaveWorkspaceCodeRequest.hpp>
#include <alibabacloud/models/SaveWorkspaceCodeResponseBody.hpp>
#include <alibabacloud/models/SaveWorkspaceCodeResponse.hpp>
#include <alibabacloud/models/SendChatMessageRequest.hpp>
#include <alibabacloud/models/SendChatMessageShrinkRequest.hpp>
#include <alibabacloud/models/SendChatMessageResponseBody.hpp>
#include <alibabacloud/models/SendChatMessageResponse.hpp>
#include <alibabacloud/models/SetWorkspaceCodePublishSettingRequest.hpp>
#include <alibabacloud/models/SetWorkspaceCodePublishSettingResponseBody.hpp>
#include <alibabacloud/models/SetWorkspaceCodePublishSettingResponse.hpp>
#include <alibabacloud/models/SetWorkspaceQuotaRequest.hpp>
#include <alibabacloud/models/SetWorkspaceQuotaResponseBody.hpp>
#include <alibabacloud/models/SetWorkspaceQuotaResponse.hpp>
#include <alibabacloud/models/StartDataAgentAccuracyTestTaskRequest.hpp>
#include <alibabacloud/models/StartDataAgentAccuracyTestTaskResponseBody.hpp>
#include <alibabacloud/models/StartDataAgentAccuracyTestTaskResponse.hpp>
#include <alibabacloud/models/StartListMcpServerToolsRequest.hpp>
#include <alibabacloud/models/StartListMcpServerToolsResponseBody.hpp>
#include <alibabacloud/models/StartListMcpServerToolsResponse.hpp>
#include <alibabacloud/models/StopDataAgentAccuracyTestTaskRequest.hpp>
#include <alibabacloud/models/StopDataAgentAccuracyTestTaskResponseBody.hpp>
#include <alibabacloud/models/StopDataAgentAccuracyTestTaskResponse.hpp>
#include <alibabacloud/models/UpdateAirflowRequest.hpp>
#include <alibabacloud/models/UpdateAirflowShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAirflowResponseBody.hpp>
#include <alibabacloud/models/UpdateAirflowResponse.hpp>
#include <alibabacloud/models/UpdateDataAgentAccuracyTestRequest.hpp>
#include <alibabacloud/models/UpdateDataAgentAccuracyTestResponseBody.hpp>
#include <alibabacloud/models/UpdateDataAgentAccuracyTestResponse.hpp>
#include <alibabacloud/models/UpdateDataAgentMemoryRequest.hpp>
#include <alibabacloud/models/UpdateDataAgentMemoryResponseBody.hpp>
#include <alibabacloud/models/UpdateDataAgentMemoryResponse.hpp>
#include <alibabacloud/models/UpdateDataAgentSpaceInfoRequest.hpp>
#include <alibabacloud/models/UpdateDataAgentSpaceInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateDataAgentSpaceInfoResponse.hpp>
#include <alibabacloud/models/UpdateDataAgentWorkspaceMemberRoleRequest.hpp>
#include <alibabacloud/models/UpdateDataAgentWorkspaceMemberRoleResponseBody.hpp>
#include <alibabacloud/models/UpdateDataAgentWorkspaceMemberRoleResponse.hpp>
#include <alibabacloud/models/UpdateDocumentRequest.hpp>
#include <alibabacloud/models/UpdateDocumentResponseBody.hpp>
#include <alibabacloud/models/UpdateDocumentResponse.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseResponseBody.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/UpdateOneMetaOssieModelRequest.hpp>
#include <alibabacloud/models/UpdateOneMetaOssieModelResponseBody.hpp>
#include <alibabacloud/models/UpdateOneMetaOssieModelResponse.hpp>
#include <alibabacloud/models/UpdateOneMetaSqlTemplateRequest.hpp>
#include <alibabacloud/models/UpdateOneMetaSqlTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateOneMetaSqlTemplateResponse.hpp>
#include <alibabacloud/models/UploadDocumentRequest.hpp>
#include <alibabacloud/models/UploadDocumentShrinkRequest.hpp>
#include <alibabacloud/models/UploadDocumentResponseBody.hpp>
#include <alibabacloud/models/UploadDocumentResponse.hpp>
#include <alibabacloud/models/UpsertDocumentChunksRequest.hpp>
#include <alibabacloud/models/UpsertDocumentChunksResponseBody.hpp>
#include <alibabacloud/models/UpsertDocumentChunksResponse.hpp>
#include <alibabacloud/models/WorkspaceActionLogRequest.hpp>
#include <alibabacloud/models/WorkspaceActionLogResponseBody.hpp>
#include <alibabacloud/models/WorkspaceActionLogResponse.hpp>
#include <alibabacloud/models/WorkspaceActionStatusRequest.hpp>
#include <alibabacloud/models/WorkspaceActionStatusResponseBody.hpp>
#include <alibabacloud/models/WorkspaceActionStatusResponse.hpp>
#include <alibabacloud/models/WorkspaceCodePublishRequest.hpp>
#include <alibabacloud/models/WorkspaceCodePublishResponseBody.hpp>
#include <alibabacloud/models/WorkspaceCodePublishResponse.hpp>

#endif
