// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_HITSDB20200615MODEL_HPP_
#define ALIBABACLOUD_HITSDB20200615MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckLdpsColumnarIndexStatusRequest.hpp>
#include <alibabacloud/models/CheckLdpsColumnarIndexStatusResponseBody.hpp>
#include <alibabacloud/models/CheckLdpsColumnarIndexStatusResponse.hpp>
#include <alibabacloud/models/CreateAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/CreateAutoScalingConfigShrinkRequest.hpp>
#include <alibabacloud/models/CreateAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/CreateAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/CreateAutoScalingRuleRequest.hpp>
#include <alibabacloud/models/CreateAutoScalingRuleResponseBody.hpp>
#include <alibabacloud/models/CreateAutoScalingRuleResponse.hpp>
#include <alibabacloud/models/CreateLdpsComputeGroupRequest.hpp>
#include <alibabacloud/models/CreateLdpsComputeGroupResponseBody.hpp>
#include <alibabacloud/models/CreateLdpsComputeGroupResponse.hpp>
#include <alibabacloud/models/CreateLindormInstanceRequest.hpp>
#include <alibabacloud/models/CreateLindormInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateLindormInstanceResponse.hpp>
#include <alibabacloud/models/CreateLindormV2instanceRequest.hpp>
#include <alibabacloud/models/CreateLindormV2instanceResponseBody.hpp>
#include <alibabacloud/models/CreateLindormV2instanceResponse.hpp>
#include <alibabacloud/models/DeleteAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/DeleteAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/DeleteAutoScalingRuleRequest.hpp>
#include <alibabacloud/models/DeleteAutoScalingRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteAutoScalingRuleResponse.hpp>
#include <alibabacloud/models/DeleteCustomResourceRequest.hpp>
#include <alibabacloud/models/DeleteCustomResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomResourceResponse.hpp>
#include <alibabacloud/models/DeleteLdpsComputeGroupRequest.hpp>
#include <alibabacloud/models/DeleteLdpsComputeGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteLdpsComputeGroupResponse.hpp>
#include <alibabacloud/models/DeployLdpsSemiManagedComponentRequest.hpp>
#include <alibabacloud/models/DeployLdpsSemiManagedComponentResponseBody.hpp>
#include <alibabacloud/models/DeployLdpsSemiManagedComponentResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/GetAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/GetAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/GetAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/GetAutoScalingRuleRequest.hpp>
#include <alibabacloud/models/GetAutoScalingRuleResponseBody.hpp>
#include <alibabacloud/models/GetAutoScalingRuleResponse.hpp>
#include <alibabacloud/models/GetClientSourceIpRequest.hpp>
#include <alibabacloud/models/GetClientSourceIpResponseBody.hpp>
#include <alibabacloud/models/GetClientSourceIpResponse.hpp>
#include <alibabacloud/models/GetEngineDefaultAuthRequest.hpp>
#include <alibabacloud/models/GetEngineDefaultAuthResponseBody.hpp>
#include <alibabacloud/models/GetEngineDefaultAuthResponse.hpp>
#include <alibabacloud/models/GetInstanceIpWhiteListRequest.hpp>
#include <alibabacloud/models/GetInstanceIpWhiteListResponseBody.hpp>
#include <alibabacloud/models/GetInstanceIpWhiteListResponse.hpp>
#include <alibabacloud/models/GetInstanceSecurityGroupsRequest.hpp>
#include <alibabacloud/models/GetInstanceSecurityGroupsResponseBody.hpp>
#include <alibabacloud/models/GetInstanceSecurityGroupsResponse.hpp>
#include <alibabacloud/models/GetLdpsComputeGroupRequest.hpp>
#include <alibabacloud/models/GetLdpsComputeGroupResponseBody.hpp>
#include <alibabacloud/models/GetLdpsComputeGroupResponse.hpp>
#include <alibabacloud/models/GetLdpsNamespacedQuotaRequest.hpp>
#include <alibabacloud/models/GetLdpsNamespacedQuotaResponseBody.hpp>
#include <alibabacloud/models/GetLdpsNamespacedQuotaResponse.hpp>
#include <alibabacloud/models/GetLdpsResourceCostRequest.hpp>
#include <alibabacloud/models/GetLdpsResourceCostResponseBody.hpp>
#include <alibabacloud/models/GetLdpsResourceCostResponse.hpp>
#include <alibabacloud/models/GetLindormEngineConfigRequest.hpp>
#include <alibabacloud/models/GetLindormEngineConfigResponseBody.hpp>
#include <alibabacloud/models/GetLindormEngineConfigResponse.hpp>
#include <alibabacloud/models/GetLindormFsUsedDetailRequest.hpp>
#include <alibabacloud/models/GetLindormFsUsedDetailResponseBody.hpp>
#include <alibabacloud/models/GetLindormFsUsedDetailResponse.hpp>
#include <alibabacloud/models/GetLindormInstanceRequest.hpp>
#include <alibabacloud/models/GetLindormInstanceResponseBody.hpp>
#include <alibabacloud/models/GetLindormInstanceResponse.hpp>
#include <alibabacloud/models/GetLindormInstanceEngineListRequest.hpp>
#include <alibabacloud/models/GetLindormInstanceEngineListResponseBody.hpp>
#include <alibabacloud/models/GetLindormInstanceEngineListResponse.hpp>
#include <alibabacloud/models/GetLindormInstanceListRequest.hpp>
#include <alibabacloud/models/GetLindormInstanceListResponseBody.hpp>
#include <alibabacloud/models/GetLindormInstanceListResponse.hpp>
#include <alibabacloud/models/GetLindormV2instanceRequest.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponse.hpp>
#include <alibabacloud/models/GetLindormV2instanceEngineListRequest.hpp>
#include <alibabacloud/models/GetLindormV2instanceEngineListResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2instanceEngineListResponse.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformRequest.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponse.hpp>
#include <alibabacloud/models/GetLindormV2instanceSecurityGroupsRequest.hpp>
#include <alibabacloud/models/GetLindormV2instanceSecurityGroupsResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2instanceSecurityGroupsResponse.hpp>
#include <alibabacloud/models/GetLindormV2storageUsageRequest.hpp>
#include <alibabacloud/models/GetLindormV2storageUsageResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2storageUsageResponse.hpp>
#include <alibabacloud/models/GetLindormV2streamEngineInfoRequest.hpp>
#include <alibabacloud/models/GetLindormV2streamEngineInfoResponseBody.hpp>
#include <alibabacloud/models/GetLindormV2streamEngineInfoResponse.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsRequest.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsResponseBody.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsResponse.hpp>
#include <alibabacloud/models/ListAutoScalingRecordsRequest.hpp>
#include <alibabacloud/models/ListAutoScalingRecordsResponseBody.hpp>
#include <alibabacloud/models/ListAutoScalingRecordsResponse.hpp>
#include <alibabacloud/models/ListAutoScalingRulesRequest.hpp>
#include <alibabacloud/models/ListAutoScalingRulesResponseBody.hpp>
#include <alibabacloud/models/ListAutoScalingRulesResponse.hpp>
#include <alibabacloud/models/ListLdpsComputeGroupsRequest.hpp>
#include <alibabacloud/models/ListLdpsComputeGroupsResponseBody.hpp>
#include <alibabacloud/models/ListLdpsComputeGroupsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/MigrateSingleZoneToMultiZoneRequest.hpp>
#include <alibabacloud/models/MigrateSingleZoneToMultiZoneResponseBody.hpp>
#include <alibabacloud/models/MigrateSingleZoneToMultiZoneResponse.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigRequest.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoScalingConfigResponse.hpp>
#include <alibabacloud/models/ModifyAutoScalingRuleRequest.hpp>
#include <alibabacloud/models/ModifyAutoScalingRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoScalingRuleResponse.hpp>
#include <alibabacloud/models/ModifyInstancePayTypeRequest.hpp>
#include <alibabacloud/models/ModifyInstancePayTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstancePayTypeResponse.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceRequest.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceResponseBody.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceResponse.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceSecurityGroupsRequest.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceSecurityGroupsResponseBody.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceSecurityGroupsResponse.hpp>
#include <alibabacloud/models/ModifyLindormV2whiteIpListRequest.hpp>
#include <alibabacloud/models/ModifyLindormV2whiteIpListResponseBody.hpp>
#include <alibabacloud/models/ModifyLindormV2whiteIpListResponse.hpp>
#include <alibabacloud/models/OpenComputeEngineRequest.hpp>
#include <alibabacloud/models/OpenComputeEngineResponseBody.hpp>
#include <alibabacloud/models/OpenComputeEngineResponse.hpp>
#include <alibabacloud/models/OpenComputePreCheckRequest.hpp>
#include <alibabacloud/models/OpenComputePreCheckResponseBody.hpp>
#include <alibabacloud/models/OpenComputePreCheckResponse.hpp>
#include <alibabacloud/models/ReleaseLindormInstanceRequest.hpp>
#include <alibabacloud/models/ReleaseLindormInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseLindormInstanceResponse.hpp>
#include <alibabacloud/models/ReleaseLindormV2instanceRequest.hpp>
#include <alibabacloud/models/ReleaseLindormV2instanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseLindormV2instanceResponse.hpp>
#include <alibabacloud/models/RenewLindormInstanceRequest.hpp>
#include <alibabacloud/models/RenewLindormInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewLindormInstanceResponse.hpp>
#include <alibabacloud/models/RestartLdpsComputeGroupRequest.hpp>
#include <alibabacloud/models/RestartLdpsComputeGroupResponseBody.hpp>
#include <alibabacloud/models/RestartLdpsComputeGroupResponse.hpp>
#include <alibabacloud/models/SetDefaultOlapComputeGroupRequest.hpp>
#include <alibabacloud/models/SetDefaultOlapComputeGroupResponseBody.hpp>
#include <alibabacloud/models/SetDefaultOlapComputeGroupResponse.hpp>
#include <alibabacloud/models/SwitchLsqlv3mySqlserviceRequest.hpp>
#include <alibabacloud/models/SwitchLsqlv3mySqlserviceResponseBody.hpp>
#include <alibabacloud/models/SwitchLsqlv3mySqlserviceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateInstanceIpWhiteListRequest.hpp>
#include <alibabacloud/models/UpdateInstanceIpWhiteListResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceIpWhiteListResponse.hpp>
#include <alibabacloud/models/UpdateInstanceSecurityGroupsRequest.hpp>
#include <alibabacloud/models/UpdateInstanceSecurityGroupsResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceSecurityGroupsResponse.hpp>
#include <alibabacloud/models/UpdateLdpsComputeGroupRequest.hpp>
#include <alibabacloud/models/UpdateLdpsComputeGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateLdpsComputeGroupResponse.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceRequest.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceResponseBody.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceResponse.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceParameterRequest.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceParameterResponseBody.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceParameterResponse.hpp>
#include <alibabacloud/models/UpgradeLindormInstanceRequest.hpp>
#include <alibabacloud/models/UpgradeLindormInstanceResponseBody.hpp>
#include <alibabacloud/models/UpgradeLindormInstanceResponse.hpp>
#include <alibabacloud/models/UpgradeLindormV2streamEngineRequest.hpp>
#include <alibabacloud/models/UpgradeLindormV2streamEngineResponseBody.hpp>
#include <alibabacloud/models/UpgradeLindormV2streamEngineResponse.hpp>
#include <alibabacloud/models/CreateAutoScalingConfigRequestScaleRuleList.hpp>
#include <alibabacloud/models/CreateLindormInstanceRequestTag.hpp>
#include <alibabacloud/models/CreateLindormV2instanceRequestEngineListNodeGroupList.hpp>
#include <alibabacloud/models/CreateLindormV2instanceRequestEngineList.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/GetAutoScalingConfigResponseBodyDataScaleRuleList.hpp>
#include <alibabacloud/models/GetAutoScalingConfigResponseBodyData.hpp>
#include <alibabacloud/models/GetAutoScalingRuleResponseBodyData.hpp>
#include <alibabacloud/models/GetEngineDefaultAuthResponseBodyAuthInfos.hpp>
#include <alibabacloud/models/GetInstanceIpWhiteListResponseBodyGroupList.hpp>
#include <alibabacloud/models/GetLdpsNamespacedQuotaResponseBodyNamespacedQuotas.hpp>
#include <alibabacloud/models/GetLindormEngineConfigResponseBodyEngineConfigsConfigFilesConfigItems.hpp>
#include <alibabacloud/models/GetLindormEngineConfigResponseBodyEngineConfigsConfigFiles.hpp>
#include <alibabacloud/models/GetLindormEngineConfigResponseBodyEngineConfigs.hpp>
#include <alibabacloud/models/GetLindormFsUsedDetailResponseBodyLstorageUsageList.hpp>
#include <alibabacloud/models/GetLindormInstanceResponseBodyEngineList.hpp>
#include <alibabacloud/models/GetLindormInstanceEngineListResponseBodyEngineListNetInfoList.hpp>
#include <alibabacloud/models/GetLindormInstanceEngineListResponseBodyEngineList.hpp>
#include <alibabacloud/models/GetLindormInstanceListRequestTag.hpp>
#include <alibabacloud/models/GetLindormInstanceListResponseBodyInstanceListTags.hpp>
#include <alibabacloud/models/GetLindormInstanceListResponseBodyInstanceList.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBodyEngineListConnectAddressList.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBodyEngineListNodeGroup.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBodyEngineList.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBodyStorageUsage.hpp>
#include <alibabacloud/models/GetLindormV2instanceResponseBodyWhiteIpList.hpp>
#include <alibabacloud/models/GetLindormV2instanceEngineListResponseBodyEngineListNetInfoList.hpp>
#include <alibabacloud/models/GetLindormV2instanceEngineListResponseBodyEngineList.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBodyEngineListConnectAddressList.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBodyEngineListNodeGroup.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBodyEngineList.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBodyStorageUsage.hpp>
#include <alibabacloud/models/GetLindormV2instanceForTerraformResponseBodyWhiteIpList.hpp>
#include <alibabacloud/models/GetLindormV2instanceSecurityGroupsResponseBodySgList.hpp>
#include <alibabacloud/models/GetLindormV2streamEngineInfoResponseBodyResourceGroupList.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsResponseBodyDataScaleConfigsScaleRuleList.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsResponseBodyDataScaleConfigs.hpp>
#include <alibabacloud/models/ListAutoScalingConfigsResponseBodyData.hpp>
#include <alibabacloud/models/ListAutoScalingRecordsResponseBodyDataScaleRecords.hpp>
#include <alibabacloud/models/ListAutoScalingRecordsResponseBodyData.hpp>
#include <alibabacloud/models/ListAutoScalingRulesResponseBodyDataScaleRules.hpp>
#include <alibabacloud/models/ListAutoScalingRulesResponseBodyData.hpp>
#include <alibabacloud/models/ListLdpsComputeGroupsResponseBodyGroupList.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyLindormV2instanceRequestNodeGroupList.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceRequestEngineListNodeGroupList.hpp>
#include <alibabacloud/models/UpdateLindormV2instanceRequestEngineList.hpp>

#endif
