// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DYVMSAPI20170525MODEL_HPP_
#define ALIBABACLOUD_DYVMSAPI20170525MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationRequest.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationResponseBody.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationResponse.hpp>
#include <alibabacloud/models/BatchRobotSmartCallRequest.hpp>
#include <alibabacloud/models/BatchRobotSmartCallResponseBody.hpp>
#include <alibabacloud/models/BatchRobotSmartCallResponse.hpp>
#include <alibabacloud/models/CancelCallRequest.hpp>
#include <alibabacloud/models/CancelCallResponseBody.hpp>
#include <alibabacloud/models/CancelCallResponse.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskRequest.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskResponse.hpp>
#include <alibabacloud/models/CancelRobotTaskRequest.hpp>
#include <alibabacloud/models/CancelRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CancelRobotTaskResponse.hpp>
#include <alibabacloud/models/ChangeMediaTypeRequest.hpp>
#include <alibabacloud/models/ChangeMediaTypeResponseBody.hpp>
#include <alibabacloud/models/ChangeMediaTypeResponse.hpp>
#include <alibabacloud/models/CloudAgentLoginRequest.hpp>
#include <alibabacloud/models/CloudAgentLoginResponseBody.hpp>
#include <alibabacloud/models/CloudAgentLoginResponse.hpp>
#include <alibabacloud/models/CloudAgentLogoutRequest.hpp>
#include <alibabacloud/models/CloudAgentLogoutResponseBody.hpp>
#include <alibabacloud/models/CloudAgentLogoutResponse.hpp>
#include <alibabacloud/models/CloudAgentMonitorStatisticsRequest.hpp>
#include <alibabacloud/models/CloudAgentMonitorStatisticsResponseBody.hpp>
#include <alibabacloud/models/CloudAgentMonitorStatisticsResponse.hpp>
#include <alibabacloud/models/CloudAgentSetUserDataRequest.hpp>
#include <alibabacloud/models/CloudAgentSetUserDataResponseBody.hpp>
#include <alibabacloud/models/CloudAgentSetUserDataResponse.hpp>
#include <alibabacloud/models/CloudAgentUnlinkRequest.hpp>
#include <alibabacloud/models/CloudAgentUnlinkResponseBody.hpp>
#include <alibabacloud/models/CloudAgentUnlinkResponse.hpp>
#include <alibabacloud/models/CloudAgentWorkloadReportRequest.hpp>
#include <alibabacloud/models/CloudAgentWorkloadReportResponseBody.hpp>
#include <alibabacloud/models/CloudAgentWorkloadReportResponse.hpp>
#include <alibabacloud/models/CloudAssignAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudAssignAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudAssignAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudBatchCreateAgentRequest.hpp>
#include <alibabacloud/models/CloudBatchCreateAgentResponseBody.hpp>
#include <alibabacloud/models/CloudBatchCreateAgentResponse.hpp>
#include <alibabacloud/models/CloudBatchGetAgentStatusRequest.hpp>
#include <alibabacloud/models/CloudBatchGetAgentStatusResponseBody.hpp>
#include <alibabacloud/models/CloudBatchGetAgentStatusResponse.hpp>
#include <alibabacloud/models/CloudBatchUpdateAgentRequest.hpp>
#include <alibabacloud/models/CloudBatchUpdateAgentResponseBody.hpp>
#include <alibabacloud/models/CloudBatchUpdateAgentResponse.hpp>
#include <alibabacloud/models/CloudCreateAgentRequest.hpp>
#include <alibabacloud/models/CloudCreateAgentResponseBody.hpp>
#include <alibabacloud/models/CloudCreateAgentResponse.hpp>
#include <alibabacloud/models/CloudCreateAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudCreateAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudCreateAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudCreateAsrRequest.hpp>
#include <alibabacloud/models/CloudCreateAsrResponseBody.hpp>
#include <alibabacloud/models/CloudCreateAsrResponse.hpp>
#include <alibabacloud/models/CloudCreateEnterpriseTimeRequest.hpp>
#include <alibabacloud/models/CloudCreateEnterpriseTimeResponseBody.hpp>
#include <alibabacloud/models/CloudCreateEnterpriseTimeResponse.hpp>
#include <alibabacloud/models/CloudCreateExtenRequest.hpp>
#include <alibabacloud/models/CloudCreateExtenResponseBody.hpp>
#include <alibabacloud/models/CloudCreateExtenResponse.hpp>
#include <alibabacloud/models/CloudCreateQueueRequest.hpp>
#include <alibabacloud/models/CloudCreateQueueShrinkRequest.hpp>
#include <alibabacloud/models/CloudCreateQueueResponseBody.hpp>
#include <alibabacloud/models/CloudCreateQueueResponse.hpp>
#include <alibabacloud/models/CloudCreateQueueSkillRequest.hpp>
#include <alibabacloud/models/CloudCreateQueueSkillResponseBody.hpp>
#include <alibabacloud/models/CloudCreateQueueSkillResponse.hpp>
#include <alibabacloud/models/CloudCreateSkillRequest.hpp>
#include <alibabacloud/models/CloudCreateSkillResponseBody.hpp>
#include <alibabacloud/models/CloudCreateSkillResponse.hpp>
#include <alibabacloud/models/CloudCreateTaskRequest.hpp>
#include <alibabacloud/models/CloudCreateTaskResponseBody.hpp>
#include <alibabacloud/models/CloudCreateTaskResponse.hpp>
#include <alibabacloud/models/CloudDeleteAgentRequest.hpp>
#include <alibabacloud/models/CloudDeleteAgentResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteAgentResponse.hpp>
#include <alibabacloud/models/CloudDeleteAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudDeleteAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudDeleteAgentTelRequest.hpp>
#include <alibabacloud/models/CloudDeleteAgentTelResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteAgentTelResponse.hpp>
#include <alibabacloud/models/CloudDeleteEnterpriseTimeRequest.hpp>
#include <alibabacloud/models/CloudDeleteEnterpriseTimeResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteEnterpriseTimeResponse.hpp>
#include <alibabacloud/models/CloudDeleteExtenRequest.hpp>
#include <alibabacloud/models/CloudDeleteExtenResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteExtenResponse.hpp>
#include <alibabacloud/models/CloudDeleteQueueRequest.hpp>
#include <alibabacloud/models/CloudDeleteQueueResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteQueueResponse.hpp>
#include <alibabacloud/models/CloudDeleteQueueSkillRequest.hpp>
#include <alibabacloud/models/CloudDeleteQueueSkillResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteQueueSkillResponse.hpp>
#include <alibabacloud/models/CloudDeleteSkillRequest.hpp>
#include <alibabacloud/models/CloudDeleteSkillResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteSkillResponse.hpp>
#include <alibabacloud/models/CloudDeleteTaskRequest.hpp>
#include <alibabacloud/models/CloudDeleteTaskResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteTaskResponse.hpp>
#include <alibabacloud/models/CloudDeleteTaskTelRequest.hpp>
#include <alibabacloud/models/CloudDeleteTaskTelResponseBody.hpp>
#include <alibabacloud/models/CloudDeleteTaskTelResponse.hpp>
#include <alibabacloud/models/CloudGetAgentRequest.hpp>
#include <alibabacloud/models/CloudGetAgentResponseBody.hpp>
#include <alibabacloud/models/CloudGetAgentResponse.hpp>
#include <alibabacloud/models/CloudGetAgentStatusRequest.hpp>
#include <alibabacloud/models/CloudGetAgentStatusResponseBody.hpp>
#include <alibabacloud/models/CloudGetAgentStatusResponse.hpp>
#include <alibabacloud/models/CloudGetAreaCodeRequest.hpp>
#include <alibabacloud/models/CloudGetAreaCodeResponseBody.hpp>
#include <alibabacloud/models/CloudGetAreaCodeResponse.hpp>
#include <alibabacloud/models/CloudGetAsrRequest.hpp>
#include <alibabacloud/models/CloudGetAsrResponseBody.hpp>
#include <alibabacloud/models/CloudGetAsrResponse.hpp>
#include <alibabacloud/models/CloudGetExtenRequest.hpp>
#include <alibabacloud/models/CloudGetExtenResponseBody.hpp>
#include <alibabacloud/models/CloudGetExtenResponse.hpp>
#include <alibabacloud/models/CloudGetObCdrRequest.hpp>
#include <alibabacloud/models/CloudGetObCdrResponseBody.hpp>
#include <alibabacloud/models/CloudGetObCdrResponse.hpp>
#include <alibabacloud/models/CloudGetQueueRequest.hpp>
#include <alibabacloud/models/CloudGetQueueResponseBody.hpp>
#include <alibabacloud/models/CloudGetQueueResponse.hpp>
#include <alibabacloud/models/CloudGetRecordUrlRequest.hpp>
#include <alibabacloud/models/CloudGetRecordUrlResponseBody.hpp>
#include <alibabacloud/models/CloudGetRecordUrlResponse.hpp>
#include <alibabacloud/models/CloudGetTaskRequest.hpp>
#include <alibabacloud/models/CloudGetTaskResponseBody.hpp>
#include <alibabacloud/models/CloudGetTaskResponse.hpp>
#include <alibabacloud/models/CloudImportTaskTelRequest.hpp>
#include <alibabacloud/models/CloudImportTaskTelShrinkRequest.hpp>
#include <alibabacloud/models/CloudImportTaskTelResponseBody.hpp>
#include <alibabacloud/models/CloudImportTaskTelResponse.hpp>
#include <alibabacloud/models/CloudInterruptIvrRequest.hpp>
#include <alibabacloud/models/CloudInterruptIvrResponseBody.hpp>
#include <alibabacloud/models/CloudInterruptIvrResponse.hpp>
#include <alibabacloud/models/CloudListAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudListAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudListAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudListAgentTelRequest.hpp>
#include <alibabacloud/models/CloudListAgentTelResponseBody.hpp>
#include <alibabacloud/models/CloudListAgentTelResponse.hpp>
#include <alibabacloud/models/CloudListAssignedAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudListAssignedAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudListAssignedAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudListCurlLogRequest.hpp>
#include <alibabacloud/models/CloudListCurlLogResponseBody.hpp>
#include <alibabacloud/models/CloudListCurlLogResponse.hpp>
#include <alibabacloud/models/CloudListEnterpriseTimeRequest.hpp>
#include <alibabacloud/models/CloudListEnterpriseTimeResponseBody.hpp>
#include <alibabacloud/models/CloudListEnterpriseTimeResponse.hpp>
#include <alibabacloud/models/CloudListExtenRequest.hpp>
#include <alibabacloud/models/CloudListExtenResponseBody.hpp>
#include <alibabacloud/models/CloudListExtenResponse.hpp>
#include <alibabacloud/models/CloudListFreeAgentRequest.hpp>
#include <alibabacloud/models/CloudListFreeAgentResponseBody.hpp>
#include <alibabacloud/models/CloudListFreeAgentResponse.hpp>
#include <alibabacloud/models/CloudListOnlineAgentRequest.hpp>
#include <alibabacloud/models/CloudListOnlineAgentResponseBody.hpp>
#include <alibabacloud/models/CloudListOnlineAgentResponse.hpp>
#include <alibabacloud/models/CloudListQueueRequest.hpp>
#include <alibabacloud/models/CloudListQueueResponseBody.hpp>
#include <alibabacloud/models/CloudListQueueResponse.hpp>
#include <alibabacloud/models/CloudListQueueSkillRequest.hpp>
#include <alibabacloud/models/CloudListQueueSkillResponseBody.hpp>
#include <alibabacloud/models/CloudListQueueSkillResponse.hpp>
#include <alibabacloud/models/CloudListSkillRequest.hpp>
#include <alibabacloud/models/CloudListSkillResponseBody.hpp>
#include <alibabacloud/models/CloudListSkillResponse.hpp>
#include <alibabacloud/models/CloudListTaskFileRequest.hpp>
#include <alibabacloud/models/CloudListTaskFileResponseBody.hpp>
#include <alibabacloud/models/CloudListTaskFileResponse.hpp>
#include <alibabacloud/models/CloudMonitorTaskRequest.hpp>
#include <alibabacloud/models/CloudMonitorTaskResponseBody.hpp>
#include <alibabacloud/models/CloudMonitorTaskResponse.hpp>
#include <alibabacloud/models/CloudOutboundObClidReportRequest.hpp>
#include <alibabacloud/models/CloudOutboundObClidReportResponseBody.hpp>
#include <alibabacloud/models/CloudOutboundObClidReportResponse.hpp>
#include <alibabacloud/models/CloudOutboundPreviewObReportRequest.hpp>
#include <alibabacloud/models/CloudOutboundPreviewObReportResponseBody.hpp>
#include <alibabacloud/models/CloudOutboundPreviewObReportResponse.hpp>
#include <alibabacloud/models/CloudPauseTaskRequest.hpp>
#include <alibabacloud/models/CloudPauseTaskResponseBody.hpp>
#include <alibabacloud/models/CloudPauseTaskResponse.hpp>
#include <alibabacloud/models/CloudPreviewoutcallRequest.hpp>
#include <alibabacloud/models/CloudPreviewoutcallResponseBody.hpp>
#include <alibabacloud/models/CloudPreviewoutcallResponse.hpp>
#include <alibabacloud/models/CloudQueryAgentRequest.hpp>
#include <alibabacloud/models/CloudQueryAgentResponseBody.hpp>
#include <alibabacloud/models/CloudQueryAgentResponse.hpp>
#include <alibabacloud/models/CloudQueryAgentCnoAndNameRequest.hpp>
#include <alibabacloud/models/CloudQueryAgentCnoAndNameResponseBody.hpp>
#include <alibabacloud/models/CloudQueryAgentCnoAndNameResponse.hpp>
#include <alibabacloud/models/CloudQueryAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudQueryAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudQueryAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudQueryAgentSkillRequest.hpp>
#include <alibabacloud/models/CloudQueryAgentSkillResponseBody.hpp>
#include <alibabacloud/models/CloudQueryAgentSkillResponse.hpp>
#include <alibabacloud/models/CloudQueryIbCdrRequest.hpp>
#include <alibabacloud/models/CloudQueryIbCdrResponseBody.hpp>
#include <alibabacloud/models/CloudQueryIbCdrResponse.hpp>
#include <alibabacloud/models/CloudQueryObCdrRequest.hpp>
#include <alibabacloud/models/CloudQueryObCdrResponseBody.hpp>
#include <alibabacloud/models/CloudQueryObCdrResponse.hpp>
#include <alibabacloud/models/CloudQueryPredictiveCallCdrRequest.hpp>
#include <alibabacloud/models/CloudQueryPredictiveCallCdrResponseBody.hpp>
#include <alibabacloud/models/CloudQueryPredictiveCallCdrResponse.hpp>
#include <alibabacloud/models/CloudQueryRasrEventRequest.hpp>
#include <alibabacloud/models/CloudQueryRasrEventResponseBody.hpp>
#include <alibabacloud/models/CloudQueryRasrEventResponse.hpp>
#include <alibabacloud/models/CloudQueryTaskRequest.hpp>
#include <alibabacloud/models/CloudQueryTaskResponseBody.hpp>
#include <alibabacloud/models/CloudQueryTaskResponse.hpp>
#include <alibabacloud/models/CloudQueryWebcallCdrRequest.hpp>
#include <alibabacloud/models/CloudQueryWebcallCdrResponseBody.hpp>
#include <alibabacloud/models/CloudQueryWebcallCdrResponse.hpp>
#include <alibabacloud/models/CloudStartTaskRequest.hpp>
#include <alibabacloud/models/CloudStartTaskResponseBody.hpp>
#include <alibabacloud/models/CloudStartTaskResponse.hpp>
#include <alibabacloud/models/CloudUnassignAgentGroupRequest.hpp>
#include <alibabacloud/models/CloudUnassignAgentGroupResponseBody.hpp>
#include <alibabacloud/models/CloudUnassignAgentGroupResponse.hpp>
#include <alibabacloud/models/CloudUpdateAgentRequest.hpp>
#include <alibabacloud/models/CloudUpdateAgentResponseBody.hpp>
#include <alibabacloud/models/CloudUpdateAgentResponse.hpp>
#include <alibabacloud/models/CloudUpdateTaskRequest.hpp>
#include <alibabacloud/models/CloudUpdateTaskResponseBody.hpp>
#include <alibabacloud/models/CloudUpdateTaskResponse.hpp>
#include <alibabacloud/models/CloudWebcallRequest.hpp>
#include <alibabacloud/models/CloudWebcallResponseBody.hpp>
#include <alibabacloud/models/CloudWebcallResponse.hpp>
#include <alibabacloud/models/CreateCallTaskRequest.hpp>
#include <alibabacloud/models/CreateCallTaskResponseBody.hpp>
#include <alibabacloud/models/CreateCallTaskResponse.hpp>
#include <alibabacloud/models/CreateRobotTaskRequest.hpp>
#include <alibabacloud/models/CreateRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CreateRobotTaskResponse.hpp>
#include <alibabacloud/models/DegradeVideoFileRequest.hpp>
#include <alibabacloud/models/DegradeVideoFileResponseBody.hpp>
#include <alibabacloud/models/DegradeVideoFileResponse.hpp>
#include <alibabacloud/models/DeleteRobotTaskRequest.hpp>
#include <alibabacloud/models/DeleteRobotTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteRobotTaskResponse.hpp>
#include <alibabacloud/models/ExecuteCallTaskRequest.hpp>
#include <alibabacloud/models/ExecuteCallTaskResponseBody.hpp>
#include <alibabacloud/models/ExecuteCallTaskResponse.hpp>
#include <alibabacloud/models/GetCallMediaTypeRequest.hpp>
#include <alibabacloud/models/GetCallMediaTypeResponseBody.hpp>
#include <alibabacloud/models/GetCallMediaTypeResponse.hpp>
#include <alibabacloud/models/GetCallProgressRequest.hpp>
#include <alibabacloud/models/GetCallProgressResponseBody.hpp>
#include <alibabacloud/models/GetCallProgressResponse.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderRequest.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderResponseBody.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderResponse.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlRequest.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlResponseBody.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlResponse.hpp>
#include <alibabacloud/models/GetTokenRequest.hpp>
#include <alibabacloud/models/GetTokenResponseBody.hpp>
#include <alibabacloud/models/GetTokenResponse.hpp>
#include <alibabacloud/models/GetVideoFieldUrlRequest.hpp>
#include <alibabacloud/models/GetVideoFieldUrlResponseBody.hpp>
#include <alibabacloud/models/GetVideoFieldUrlResponse.hpp>
#include <alibabacloud/models/IvrCallRequest.hpp>
#include <alibabacloud/models/IvrCallResponseBody.hpp>
#include <alibabacloud/models/IvrCallResponse.hpp>
#include <alibabacloud/models/ListCallTaskRequest.hpp>
#include <alibabacloud/models/ListCallTaskResponseBody.hpp>
#include <alibabacloud/models/ListCallTaskResponse.hpp>
#include <alibabacloud/models/ListCallTaskDetailRequest.hpp>
#include <alibabacloud/models/ListCallTaskDetailResponseBody.hpp>
#include <alibabacloud/models/ListCallTaskDetailResponse.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileRequest.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileResponseBody.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageShrinkRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageResponse.hpp>
#include <alibabacloud/models/PauseVideoFileRequest.hpp>
#include <alibabacloud/models/PauseVideoFileResponseBody.hpp>
#include <alibabacloud/models/PauseVideoFileResponse.hpp>
#include <alibabacloud/models/PlayVideoFileRequest.hpp>
#include <alibabacloud/models/PlayVideoFileResponseBody.hpp>
#include <alibabacloud/models/PlayVideoFileResponse.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdRequest.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdResponseBody.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdResponse.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdRequest.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdResponseBody.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdResponse.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigRequest.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigResponseBody.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigResponse.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordRequest.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordResponseBody.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordResponse.hpp>
#include <alibabacloud/models/QueryRobotInfoListRequest.hpp>
#include <alibabacloud/models/QueryRobotInfoListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotInfoListResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskListRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskListResponse.hpp>
#include <alibabacloud/models/QueryRobotv2AllListRequest.hpp>
#include <alibabacloud/models/QueryRobotv2AllListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotv2AllListResponse.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressRequest.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressResponseBody.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressResponse.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationRequest.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationResponseBody.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationResponse.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoRequest.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoResponseBody.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoResponse.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageRequest.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageResponseBody.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageResponse.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoRequest.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoResponseBody.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoResponse.hpp>
#include <alibabacloud/models/RecoverCallInConfigRequest.hpp>
#include <alibabacloud/models/RecoverCallInConfigResponseBody.hpp>
#include <alibabacloud/models/RecoverCallInConfigResponse.hpp>
#include <alibabacloud/models/ResumeVideoFileRequest.hpp>
#include <alibabacloud/models/ResumeVideoFileResponseBody.hpp>
#include <alibabacloud/models/ResumeVideoFileResponse.hpp>
#include <alibabacloud/models/SeekVideoFileRequest.hpp>
#include <alibabacloud/models/SeekVideoFileResponseBody.hpp>
#include <alibabacloud/models/SeekVideoFileResponse.hpp>
#include <alibabacloud/models/SendVerificationRequest.hpp>
#include <alibabacloud/models/SendVerificationResponseBody.hpp>
#include <alibabacloud/models/SendVerificationResponse.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigRequest.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigResponseBody.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigResponse.hpp>
#include <alibabacloud/models/SingleCallByTtsRequest.hpp>
#include <alibabacloud/models/SingleCallByTtsResponseBody.hpp>
#include <alibabacloud/models/SingleCallByTtsResponse.hpp>
#include <alibabacloud/models/SingleCallByVideoRequest.hpp>
#include <alibabacloud/models/SingleCallByVideoResponseBody.hpp>
#include <alibabacloud/models/SingleCallByVideoResponse.hpp>
#include <alibabacloud/models/SingleCallByVoiceRequest.hpp>
#include <alibabacloud/models/SingleCallByVoiceResponseBody.hpp>
#include <alibabacloud/models/SingleCallByVoiceResponse.hpp>
#include <alibabacloud/models/SkipVideoFileRequest.hpp>
#include <alibabacloud/models/SkipVideoFileResponseBody.hpp>
#include <alibabacloud/models/SkipVideoFileResponse.hpp>
#include <alibabacloud/models/SmartCallRequest.hpp>
#include <alibabacloud/models/SmartCallResponseBody.hpp>
#include <alibabacloud/models/SmartCallResponse.hpp>
#include <alibabacloud/models/SmartCallOperateRequest.hpp>
#include <alibabacloud/models/SmartCallOperateResponseBody.hpp>
#include <alibabacloud/models/SmartCallOperateResponse.hpp>
#include <alibabacloud/models/StartRobotTaskRequest.hpp>
#include <alibabacloud/models/StartRobotTaskResponseBody.hpp>
#include <alibabacloud/models/StartRobotTaskResponse.hpp>
#include <alibabacloud/models/StopCallInConfigRequest.hpp>
#include <alibabacloud/models/StopCallInConfigResponseBody.hpp>
#include <alibabacloud/models/StopCallInConfigResponse.hpp>
#include <alibabacloud/models/StopRobotTaskRequest.hpp>
#include <alibabacloud/models/StopRobotTaskResponseBody.hpp>
#include <alibabacloud/models/StopRobotTaskResponse.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterRequest.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterResponseBody.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterResponse.hpp>
#include <alibabacloud/models/UpgradeVideoFileRequest.hpp>
#include <alibabacloud/models/UpgradeVideoFileResponseBody.hpp>
#include <alibabacloud/models/UpgradeVideoFileResponse.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileRequest.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileResponseBody.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileResponse.hpp>

#endif
