// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DYVMSAPI20170525MODEL_HPP_
#define ALIBABACLOUD_DYVMSAPI20170525MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationRequest.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationResponseBody.hpp>
#include <alibabacloud/models/AddVirtualNumberRelationResponse.hpp>
#include <alibabacloud/models/BatchRobotSmartCallRequest.hpp>
#include <alibabacloud/models/BatchRobotSmartCallResponseBody.hpp>
#include <alibabacloud/models/BatchRobotSmartCallResponse.hpp>
#include <alibabacloud/models/CancelCallRequest.hpp>
#include <alibabacloud/models/CancelCallResponseBody.hpp>
#include <alibabacloud/models/CancelCallResponse.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskRequest.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CancelOrderRobotTaskResponse.hpp>
#include <alibabacloud/models/CancelRobotTaskRequest.hpp>
#include <alibabacloud/models/CancelRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CancelRobotTaskResponse.hpp>
#include <alibabacloud/models/ChangeMediaTypeRequest.hpp>
#include <alibabacloud/models/ChangeMediaTypeResponseBody.hpp>
#include <alibabacloud/models/ChangeMediaTypeResponse.hpp>
#include <alibabacloud/models/CreateCallTaskRequest.hpp>
#include <alibabacloud/models/CreateCallTaskResponseBody.hpp>
#include <alibabacloud/models/CreateCallTaskResponse.hpp>
#include <alibabacloud/models/CreateRobotTaskRequest.hpp>
#include <alibabacloud/models/CreateRobotTaskResponseBody.hpp>
#include <alibabacloud/models/CreateRobotTaskResponse.hpp>
#include <alibabacloud/models/DegradeVideoFileRequest.hpp>
#include <alibabacloud/models/DegradeVideoFileResponseBody.hpp>
#include <alibabacloud/models/DegradeVideoFileResponse.hpp>
#include <alibabacloud/models/DeleteRobotTaskRequest.hpp>
#include <alibabacloud/models/DeleteRobotTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteRobotTaskResponse.hpp>
#include <alibabacloud/models/ExecuteCallTaskRequest.hpp>
#include <alibabacloud/models/ExecuteCallTaskResponseBody.hpp>
#include <alibabacloud/models/ExecuteCallTaskResponse.hpp>
#include <alibabacloud/models/GetCallMediaTypeRequest.hpp>
#include <alibabacloud/models/GetCallMediaTypeResponseBody.hpp>
#include <alibabacloud/models/GetCallMediaTypeResponse.hpp>
#include <alibabacloud/models/GetCallProgressRequest.hpp>
#include <alibabacloud/models/GetCallProgressResponseBody.hpp>
#include <alibabacloud/models/GetCallProgressResponse.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderRequest.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderResponseBody.hpp>
#include <alibabacloud/models/GetHotlineQualificationByOrderResponse.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlRequest.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlResponseBody.hpp>
#include <alibabacloud/models/GetTemporaryFileUrlResponse.hpp>
#include <alibabacloud/models/GetTokenRequest.hpp>
#include <alibabacloud/models/GetTokenResponseBody.hpp>
#include <alibabacloud/models/GetTokenResponse.hpp>
#include <alibabacloud/models/GetVideoFieldUrlRequest.hpp>
#include <alibabacloud/models/GetVideoFieldUrlResponseBody.hpp>
#include <alibabacloud/models/GetVideoFieldUrlResponse.hpp>
#include <alibabacloud/models/IvrCallRequest.hpp>
#include <alibabacloud/models/IvrCallResponseBody.hpp>
#include <alibabacloud/models/IvrCallResponse.hpp>
#include <alibabacloud/models/ListCallTaskRequest.hpp>
#include <alibabacloud/models/ListCallTaskResponseBody.hpp>
#include <alibabacloud/models/ListCallTaskResponse.hpp>
#include <alibabacloud/models/ListCallTaskDetailRequest.hpp>
#include <alibabacloud/models/ListCallTaskDetailResponseBody.hpp>
#include <alibabacloud/models/ListCallTaskDetailResponse.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileRequest.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileResponseBody.hpp>
#include <alibabacloud/models/ListHotlineTransferRegisterFileResponse.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageShrinkRequest.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageResponseBody.hpp>
#include <alibabacloud/models/ListServiceInstanceForPageResponse.hpp>
#include <alibabacloud/models/PauseVideoFileRequest.hpp>
#include <alibabacloud/models/PauseVideoFileResponseBody.hpp>
#include <alibabacloud/models/PauseVideoFileResponse.hpp>
#include <alibabacloud/models/PlayVideoFileRequest.hpp>
#include <alibabacloud/models/PlayVideoFileResponseBody.hpp>
#include <alibabacloud/models/PlayVideoFileResponse.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdRequest.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdResponseBody.hpp>
#include <alibabacloud/models/QueryCallDetailByCallIdResponse.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdRequest.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdResponseBody.hpp>
#include <alibabacloud/models/QueryCallDetailByTaskIdResponse.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigRequest.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigResponseBody.hpp>
#include <alibabacloud/models/QueryCallInPoolTransferConfigResponse.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordRequest.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordResponseBody.hpp>
#include <alibabacloud/models/QueryCallInTransferRecordResponse.hpp>
#include <alibabacloud/models/QueryRobotInfoListRequest.hpp>
#include <alibabacloud/models/QueryRobotInfoListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotInfoListResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskCallDetailResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskCallListResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskDetailResponse.hpp>
#include <alibabacloud/models/QueryRobotTaskListRequest.hpp>
#include <alibabacloud/models/QueryRobotTaskListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotTaskListResponse.hpp>
#include <alibabacloud/models/QueryRobotv2AllListRequest.hpp>
#include <alibabacloud/models/QueryRobotv2AllListResponseBody.hpp>
#include <alibabacloud/models/QueryRobotv2AllListResponse.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressRequest.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressResponseBody.hpp>
#include <alibabacloud/models/QueryVideoPlayProgressResponse.hpp>
#include <alibabacloud/models/QueryVirtualNumberRequest.hpp>
#include <alibabacloud/models/QueryVirtualNumberResponseBody.hpp>
#include <alibabacloud/models/QueryVirtualNumberResponse.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationRequest.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationResponseBody.hpp>
#include <alibabacloud/models/QueryVirtualNumberRelationResponse.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoRequest.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoResponseBody.hpp>
#include <alibabacloud/models/QueryVmsRealNumberCallConnectionRateInfoResponse.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageRequest.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageResponseBody.hpp>
#include <alibabacloud/models/QueryVmsVirtualNumberRelationByPageResponse.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoRequest.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoResponseBody.hpp>
#include <alibabacloud/models/QueryVoiceFileAuditInfoResponse.hpp>
#include <alibabacloud/models/RecoverCallInConfigRequest.hpp>
#include <alibabacloud/models/RecoverCallInConfigResponseBody.hpp>
#include <alibabacloud/models/RecoverCallInConfigResponse.hpp>
#include <alibabacloud/models/ResumeVideoFileRequest.hpp>
#include <alibabacloud/models/ResumeVideoFileResponseBody.hpp>
#include <alibabacloud/models/ResumeVideoFileResponse.hpp>
#include <alibabacloud/models/SeekVideoFileRequest.hpp>
#include <alibabacloud/models/SeekVideoFileResponseBody.hpp>
#include <alibabacloud/models/SeekVideoFileResponse.hpp>
#include <alibabacloud/models/SendVerificationRequest.hpp>
#include <alibabacloud/models/SendVerificationResponseBody.hpp>
#include <alibabacloud/models/SendVerificationResponse.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigRequest.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigResponseBody.hpp>
#include <alibabacloud/models/SetTransferCalleePoolConfigResponse.hpp>
#include <alibabacloud/models/SingleCallByTtsRequest.hpp>
#include <alibabacloud/models/SingleCallByTtsResponseBody.hpp>
#include <alibabacloud/models/SingleCallByTtsResponse.hpp>
#include <alibabacloud/models/SingleCallByVideoRequest.hpp>
#include <alibabacloud/models/SingleCallByVideoResponseBody.hpp>
#include <alibabacloud/models/SingleCallByVideoResponse.hpp>
#include <alibabacloud/models/SingleCallByVoiceRequest.hpp>
#include <alibabacloud/models/SingleCallByVoiceResponseBody.hpp>
#include <alibabacloud/models/SingleCallByVoiceResponse.hpp>
#include <alibabacloud/models/SkipVideoFileRequest.hpp>
#include <alibabacloud/models/SkipVideoFileResponseBody.hpp>
#include <alibabacloud/models/SkipVideoFileResponse.hpp>
#include <alibabacloud/models/SmartCallRequest.hpp>
#include <alibabacloud/models/SmartCallResponseBody.hpp>
#include <alibabacloud/models/SmartCallResponse.hpp>
#include <alibabacloud/models/SmartCallOperateRequest.hpp>
#include <alibabacloud/models/SmartCallOperateResponseBody.hpp>
#include <alibabacloud/models/SmartCallOperateResponse.hpp>
#include <alibabacloud/models/StartRobotTaskRequest.hpp>
#include <alibabacloud/models/StartRobotTaskResponseBody.hpp>
#include <alibabacloud/models/StartRobotTaskResponse.hpp>
#include <alibabacloud/models/StopCallInConfigRequest.hpp>
#include <alibabacloud/models/StopCallInConfigResponseBody.hpp>
#include <alibabacloud/models/StopCallInConfigResponse.hpp>
#include <alibabacloud/models/StopRobotTaskRequest.hpp>
#include <alibabacloud/models/StopRobotTaskResponseBody.hpp>
#include <alibabacloud/models/StopRobotTaskResponse.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterRequest.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterResponseBody.hpp>
#include <alibabacloud/models/SubmitHotlineTransferRegisterResponse.hpp>
#include <alibabacloud/models/UpgradeVideoFileRequest.hpp>
#include <alibabacloud/models/UpgradeVideoFileResponseBody.hpp>
#include <alibabacloud/models/UpgradeVideoFileResponse.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileRequest.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileResponseBody.hpp>
#include <alibabacloud/models/UploadRobotTaskCalledFileResponse.hpp>

#endif
