// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_AGENTRUN20250910MODEL_HPP_
#define ALIBABACLOUD_AGENTRUN20250910MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CodeConfiguration.hpp>
#include <alibabacloud/models/ContainerConfiguration.hpp>
#include <alibabacloud/models/HealthCheckConfiguration.hpp>
#include <alibabacloud/models/LogConfiguration.hpp>
#include <alibabacloud/models/NetworkConfiguration.hpp>
#include <alibabacloud/models/ProtocolSettings.hpp>
#include <alibabacloud/models/ProtocolConfiguration.hpp>
#include <alibabacloud/models/AgentRuntime.hpp>
#include <alibabacloud/models/VersionWeight.hpp>
#include <alibabacloud/models/RoutingConfiguration.hpp>
#include <alibabacloud/models/AgentRuntimeEndpoint.hpp>
#include <alibabacloud/models/AgentRuntimeEndpointResult.hpp>
#include <alibabacloud/models/AgentRuntimeResult.hpp>
#include <alibabacloud/models/AgentRuntimeVersion.hpp>
#include <alibabacloud/models/AgentRuntimeVersionResult.hpp>
#include <alibabacloud/models/AiFallbackServiceConfig.hpp>
#include <alibabacloud/models/AiFallbackConfig.hpp>
#include <alibabacloud/models/AiServiceConfig.hpp>
#include <alibabacloud/models/ApigLLMModel.hpp>
#include <alibabacloud/models/ArmsConfiguration.hpp>
#include <alibabacloud/models/AttachPolicyConfig.hpp>
#include <alibabacloud/models/BrowserOssLocation.hpp>
#include <alibabacloud/models/BrowserRecordingConfiguration.hpp>
#include <alibabacloud/models/Browser.hpp>
#include <alibabacloud/models/BrowserAutomationStream.hpp>
#include <alibabacloud/models/ViewPortConfiguration.hpp>
#include <alibabacloud/models/BrowserConfiguration.hpp>
#include <alibabacloud/models/BrowserLiveViewStream.hpp>
#include <alibabacloud/models/BrowserResult.hpp>
#include <alibabacloud/models/BrowserSessionOut.hpp>
#include <alibabacloud/models/BrowserSessionListOut.hpp>
#include <alibabacloud/models/BrowserStreams.hpp>
#include <alibabacloud/models/BrowserViewPort.hpp>
#include <alibabacloud/models/CAPConfig.hpp>
#include <alibabacloud/models/CertConfig.hpp>
#include <alibabacloud/models/CodeInfo.hpp>
#include <alibabacloud/models/CodeInterpreter.hpp>
#include <alibabacloud/models/CodeInterpreterResult.hpp>
#include <alibabacloud/models/CodeInterpreterSessionConfig.hpp>
#include <alibabacloud/models/CodeInterpreterSessionOut.hpp>
#include <alibabacloud/models/CodeInterpreterSessionListOut.hpp>
#include <alibabacloud/models/CommonResult.hpp>
#include <alibabacloud/models/CreateAgentRuntimeEndpointInput.hpp>
#include <alibabacloud/models/CreateAgentRuntimeInput.hpp>
#include <alibabacloud/models/CreateAgentRuntimeVersionInput.hpp>
#include <alibabacloud/models/CreateApigLLMModelInput.hpp>
#include <alibabacloud/models/CreateBrowserInput.hpp>
#include <alibabacloud/models/CreateCodeInterpreterInput.hpp>
#include <alibabacloud/models/CredentialPublicConfig.hpp>
#include <alibabacloud/models/CreateCredentialInput.hpp>
#include <alibabacloud/models/RelatedResource.hpp>
#include <alibabacloud/models/CreateCredentialOutput.hpp>
#include <alibabacloud/models/PathConfig.hpp>
#include <alibabacloud/models/RouteConfig.hpp>
#include <alibabacloud/models/TLSConfig.hpp>
#include <alibabacloud/models/CreateCustomDomainInput.hpp>
#include <alibabacloud/models/CreateDomainInput.hpp>
#include <alibabacloud/models/GatewayNetworkConfiguration.hpp>
#include <alibabacloud/models/CreateGatewayInput.hpp>
#include <alibabacloud/models/PolicyConfig.hpp>
#include <alibabacloud/models/TargetServiceConfig.hpp>
#include <alibabacloud/models/LLMDeployConfig.hpp>
#include <alibabacloud/models/LLMAPIConfiguration.hpp>
#include <alibabacloud/models/MCPAPIConfiguration.hpp>
#include <alibabacloud/models/TargetConfiguration.hpp>
#include <alibabacloud/models/CreateGatewayTargetInput.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseInput.hpp>
#include <alibabacloud/models/EmbedderConfig.hpp>
#include <alibabacloud/models/LLMConfig.hpp>
#include <alibabacloud/models/VectorStoreConfig.hpp>
#include <alibabacloud/models/CreateMemoryCollectionInput.hpp>
#include <alibabacloud/models/CreateModelInput.hpp>
#include <alibabacloud/models/ProxyConfig.hpp>
#include <alibabacloud/models/CreateModelProxyInput.hpp>
#include <alibabacloud/models/ModelFeatures.hpp>
#include <alibabacloud/models/ModelParameterRule.hpp>
#include <alibabacloud/models/ModelProperties.hpp>
#include <alibabacloud/models/ModelInfoConfig.hpp>
#include <alibabacloud/models/ProviderSettings.hpp>
#include <alibabacloud/models/CreateModelServiceInput.hpp>
#include <alibabacloud/models/NASMountConfig.hpp>
#include <alibabacloud/models/NASConfig.hpp>
#include <alibabacloud/models/OSSMountPoint.hpp>
#include <alibabacloud/models/OSSMountConfig.hpp>
#include <alibabacloud/models/CreateSandboxInput.hpp>
#include <alibabacloud/models/CredentialConfiguration.hpp>
#include <alibabacloud/models/OssConfiguration.hpp>
#include <alibabacloud/models/CreateTemplateInput.hpp>
#include <alibabacloud/models/CreateToolData.hpp>
#include <alibabacloud/models/CreateToolInput.hpp>
#include <alibabacloud/models/CreateToolOutput.hpp>
#include <alibabacloud/models/Credential.hpp>
#include <alibabacloud/models/CredentialListItem.hpp>
#include <alibabacloud/models/CredentialResult.hpp>
#include <alibabacloud/models/CustomDomain.hpp>
#include <alibabacloud/models/CustomDomainResult.hpp>
#include <alibabacloud/models/CustomRuntimeConfig.hpp>
#include <alibabacloud/models/DeleteBrowserOut.hpp>
#include <alibabacloud/models/DeleteBrowserResult.hpp>
#include <alibabacloud/models/DeleteCodeInterpreterOut.hpp>
#include <alibabacloud/models/DeleteCodeInterpreterResult.hpp>
#include <alibabacloud/models/KnowledgeBase.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseResult.hpp>
#include <alibabacloud/models/ModelProxy.hpp>
#include <alibabacloud/models/DeleteModelProxyResult.hpp>
#include <alibabacloud/models/ModelService.hpp>
#include <alibabacloud/models/DeleteModelServiceResult.hpp>
#include <alibabacloud/models/Sandbox.hpp>
#include <alibabacloud/models/DeleteSandboxResult.hpp>
#include <alibabacloud/models/Template.hpp>
#include <alibabacloud/models/DeleteTemplateResult.hpp>
#include <alibabacloud/models/DeregisterServiceInput.hpp>
#include <alibabacloud/models/DomainInfo.hpp>
#include <alibabacloud/models/ErrorResult.hpp>
#include <alibabacloud/models/FCLinkConfig.hpp>
#include <alibabacloud/models/Gateway.hpp>
#include <alibabacloud/models/GetBrowserSessionResult.hpp>
#include <alibabacloud/models/GetCodeInterpreterSessionResult.hpp>
#include <alibabacloud/models/GetCredentialOutput.hpp>
#include <alibabacloud/models/ToolInfo.hpp>
#include <alibabacloud/models/GetToolOutput.hpp>
#include <alibabacloud/models/GrayTrafficWeight.hpp>
#include <alibabacloud/models/HealthCheckConfig.hpp>
#include <alibabacloud/models/KnowledgeBaseResult.hpp>
#include <alibabacloud/models/ListAgentRuntimeEndpointsInput.hpp>
#include <alibabacloud/models/ListAgentRuntimeEndpointsOutput.hpp>
#include <alibabacloud/models/ListAgentRuntimeEndpointsResult.hpp>
#include <alibabacloud/models/ListAgentRuntimeVersionsInput.hpp>
#include <alibabacloud/models/ListAgentRuntimeVersionsOutput.hpp>
#include <alibabacloud/models/ListAgentRuntimeVersionsResult.hpp>
#include <alibabacloud/models/ListAgentRuntimesInput.hpp>
#include <alibabacloud/models/ListAgentRuntimesOutput.hpp>
#include <alibabacloud/models/ListAgentRuntimesResult.hpp>
#include <alibabacloud/models/ListBrowserSessionResult.hpp>
#include <alibabacloud/models/ListBrowsersInput.hpp>
#include <alibabacloud/models/ListBrowsersOutput.hpp>
#include <alibabacloud/models/ListBrowsersResult.hpp>
#include <alibabacloud/models/ListCodeInterpreterSessionResult.hpp>
#include <alibabacloud/models/ListCodeInterpretersInput.hpp>
#include <alibabacloud/models/ListCodeInterpretersOutput.hpp>
#include <alibabacloud/models/ListCodeInterpretersResult.hpp>
#include <alibabacloud/models/ListCredentialsOutput.hpp>
#include <alibabacloud/models/ListCredentialsResult.hpp>
#include <alibabacloud/models/ListCustomDomainsOutput.hpp>
#include <alibabacloud/models/ListCustomDomainsResult.hpp>
#include <alibabacloud/models/ListDomainsOutput.hpp>
#include <alibabacloud/models/ListGatewaysOutput.hpp>
#include <alibabacloud/models/ListKnowledgeBasesOutput.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResult.hpp>
#include <alibabacloud/models/MemoryCollection.hpp>
#include <alibabacloud/models/ListMemoryCollectionsOutput.hpp>
#include <alibabacloud/models/ListMemoryCollectionsResult.hpp>
#include <alibabacloud/models/ListModelProxiesOutput.hpp>
#include <alibabacloud/models/ListModelProxiesResult.hpp>
#include <alibabacloud/models/ListModelServicesOutput.hpp>
#include <alibabacloud/models/ListModelServicesResult.hpp>
#include <alibabacloud/models/ListSandboxesOutput.hpp>
#include <alibabacloud/models/ListSandboxesResult.hpp>
#include <alibabacloud/models/ListTemplatesOutput.hpp>
#include <alibabacloud/models/ListTemplatesResult.hpp>
#include <alibabacloud/models/ToolListItem.hpp>
#include <alibabacloud/models/ListToolsOutput.hpp>
#include <alibabacloud/models/MCPServiceConfig.hpp>
#include <alibabacloud/models/MCPBackendConfig.hpp>
#include <alibabacloud/models/MCPPathMatch.hpp>
#include <alibabacloud/models/MCPMatch.hpp>
#include <alibabacloud/models/MCPAPI.hpp>
#include <alibabacloud/models/MCPServerConfig.hpp>
#include <alibabacloud/models/MemoryCollectionResult.hpp>
#include <alibabacloud/models/Model.hpp>
#include <alibabacloud/models/ModelProxyResult.hpp>
#include <alibabacloud/models/ModelServiceResult.hpp>
#include <alibabacloud/models/PaginationInfo.hpp>
#include <alibabacloud/models/PolarFsMountConfig.hpp>
#include <alibabacloud/models/PolarFsConfig.hpp>
#include <alibabacloud/models/PublishRuntimeVersionInput.hpp>
#include <alibabacloud/models/RecordingConfiguration.hpp>
#include <alibabacloud/models/RegisterServiceInput.hpp>
#include <alibabacloud/models/RelatedWorkload.hpp>
#include <alibabacloud/models/SandboxHealthCheckOut.hpp>
#include <alibabacloud/models/SandboxHealthCheckResult.hpp>
#include <alibabacloud/models/SandboxResult.hpp>
#include <alibabacloud/models/ServiceConfig.hpp>
#include <alibabacloud/models/ServiceResult.hpp>
#include <alibabacloud/models/StartBrowserSessionInput.hpp>
#include <alibabacloud/models/StartBrowserSessionResult.hpp>
#include <alibabacloud/models/StartCodeInterpreterSessionInput.hpp>
#include <alibabacloud/models/StartCodeInterpreterSessionResult.hpp>
#include <alibabacloud/models/StopCodeInterpreterSessionResult.hpp>
#include <alibabacloud/models/StopSandboxResult.hpp>
#include <alibabacloud/models/Target.hpp>
#include <alibabacloud/models/TemplateResult.hpp>
#include <alibabacloud/models/TriggerConfig.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeEndpointInput.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeInput.hpp>
#include <alibabacloud/models/UpdateApigLLMModelInput.hpp>
#include <alibabacloud/models/UpdateCredentialInput.hpp>
#include <alibabacloud/models/UpdateCredentialOutput.hpp>
#include <alibabacloud/models/UpdateCustomDomainInput.hpp>
#include <alibabacloud/models/UpdateDomainInput.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseInput.hpp>
#include <alibabacloud/models/UpdateMemoryCollectionInput.hpp>
#include <alibabacloud/models/UpdateModelInput.hpp>
#include <alibabacloud/models/UpdateModelProxyInput.hpp>
#include <alibabacloud/models/UpdateModelServiceInput.hpp>
#include <alibabacloud/models/UpdateTargetConfigurationInput.hpp>
#include <alibabacloud/models/UpdateTemplateInput.hpp>
#include <alibabacloud/models/UpdateToolData.hpp>
#include <alibabacloud/models/UpdateToolInput.hpp>
#include <alibabacloud/models/UpdateToolOutput.hpp>
#include <alibabacloud/models/ActivateTemplateMCPRequest.hpp>
#include <alibabacloud/models/ActivateTemplateMCPResponse.hpp>
#include <alibabacloud/models/CreateAgentRuntimeRequest.hpp>
#include <alibabacloud/models/CreateAgentRuntimeResponse.hpp>
#include <alibabacloud/models/CreateAgentRuntimeEndpointRequest.hpp>
#include <alibabacloud/models/CreateAgentRuntimeEndpointResponse.hpp>
#include <alibabacloud/models/CreateBrowserRequest.hpp>
#include <alibabacloud/models/CreateBrowserResponse.hpp>
#include <alibabacloud/models/CreateCodeInterpreterRequest.hpp>
#include <alibabacloud/models/CreateCodeInterpreterResponse.hpp>
#include <alibabacloud/models/CreateCredentialRequest.hpp>
#include <alibabacloud/models/CreateCredentialResponse.hpp>
#include <alibabacloud/models/CreateCustomDomainRequest.hpp>
#include <alibabacloud/models/CreateCustomDomainResponse.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/CreateKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/CreateMemoryCollectionRequest.hpp>
#include <alibabacloud/models/CreateMemoryCollectionResponse.hpp>
#include <alibabacloud/models/CreateModelProxyRequest.hpp>
#include <alibabacloud/models/CreateModelProxyResponse.hpp>
#include <alibabacloud/models/CreateModelServiceRequest.hpp>
#include <alibabacloud/models/CreateModelServiceResponse.hpp>
#include <alibabacloud/models/CreateSandboxRequest.hpp>
#include <alibabacloud/models/CreateSandboxResponse.hpp>
#include <alibabacloud/models/CreateTemplateRequest.hpp>
#include <alibabacloud/models/CreateTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAgentRuntimeResponse.hpp>
#include <alibabacloud/models/DeleteAgentRuntimeEndpointResponse.hpp>
#include <alibabacloud/models/DeleteBrowserResponse.hpp>
#include <alibabacloud/models/DeleteCodeInterpreterResponse.hpp>
#include <alibabacloud/models/DeleteCredentialResponse.hpp>
#include <alibabacloud/models/DeleteCustomDomainResponse.hpp>
#include <alibabacloud/models/DeleteKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/DeleteMemoryCollectionResponse.hpp>
#include <alibabacloud/models/DeleteModelProxyResponse.hpp>
#include <alibabacloud/models/DeleteModelServiceResponse.hpp>
#include <alibabacloud/models/DeleteSandboxResponse.hpp>
#include <alibabacloud/models/DeleteTemplateResponse.hpp>
#include <alibabacloud/models/GetAccessTokenRequest.hpp>
#include <alibabacloud/models/GetAccessTokenResponseBody.hpp>
#include <alibabacloud/models/GetAccessTokenResponse.hpp>
#include <alibabacloud/models/GetAgentRuntimeRequest.hpp>
#include <alibabacloud/models/GetAgentRuntimeResponse.hpp>
#include <alibabacloud/models/GetAgentRuntimeEndpointResponse.hpp>
#include <alibabacloud/models/GetBrowserResponse.hpp>
#include <alibabacloud/models/GetCodeInterpreterResponse.hpp>
#include <alibabacloud/models/GetCredentialResponse.hpp>
#include <alibabacloud/models/GetCustomDomainResponse.hpp>
#include <alibabacloud/models/GetKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/GetMemoryCollectionResponse.hpp>
#include <alibabacloud/models/GetModelProxyResponse.hpp>
#include <alibabacloud/models/GetModelServiceResponse.hpp>
#include <alibabacloud/models/GetSandboxResponse.hpp>
#include <alibabacloud/models/GetTemplateResponse.hpp>
#include <alibabacloud/models/ListAgentRuntimeEndpointsRequest.hpp>
#include <alibabacloud/models/ListAgentRuntimeEndpointsResponse.hpp>
#include <alibabacloud/models/ListAgentRuntimeVersionsRequest.hpp>
#include <alibabacloud/models/ListAgentRuntimeVersionsResponse.hpp>
#include <alibabacloud/models/ListAgentRuntimesRequest.hpp>
#include <alibabacloud/models/ListAgentRuntimesResponse.hpp>
#include <alibabacloud/models/ListBrowsersRequest.hpp>
#include <alibabacloud/models/ListBrowsersResponse.hpp>
#include <alibabacloud/models/ListCodeInterpretersRequest.hpp>
#include <alibabacloud/models/ListCodeInterpretersResponse.hpp>
#include <alibabacloud/models/ListCredentialsRequest.hpp>
#include <alibabacloud/models/ListCredentialsResponse.hpp>
#include <alibabacloud/models/ListCustomDomainsRequest.hpp>
#include <alibabacloud/models/ListCustomDomainsResponse.hpp>
#include <alibabacloud/models/ListKnowledgeBasesRequest.hpp>
#include <alibabacloud/models/ListKnowledgeBasesResponse.hpp>
#include <alibabacloud/models/ListMemoryCollectionsRequest.hpp>
#include <alibabacloud/models/ListMemoryCollectionsResponse.hpp>
#include <alibabacloud/models/ListModelProvidersRequest.hpp>
#include <alibabacloud/models/ListModelProvidersResponseBody.hpp>
#include <alibabacloud/models/ListModelProvidersResponse.hpp>
#include <alibabacloud/models/ListModelProxiesRequest.hpp>
#include <alibabacloud/models/ListModelProxiesResponse.hpp>
#include <alibabacloud/models/ListModelServicesRequest.hpp>
#include <alibabacloud/models/ListModelServicesResponse.hpp>
#include <alibabacloud/models/ListSandboxesRequest.hpp>
#include <alibabacloud/models/ListSandboxesResponse.hpp>
#include <alibabacloud/models/ListTemplatesRequest.hpp>
#include <alibabacloud/models/ListTemplatesResponse.hpp>
#include <alibabacloud/models/PublishRuntimeVersionRequest.hpp>
#include <alibabacloud/models/PublishRuntimeVersionResponse.hpp>
#include <alibabacloud/models/StopSandboxResponse.hpp>
#include <alibabacloud/models/StopTemplateMCPResponse.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeRequest.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeResponse.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeEndpointRequest.hpp>
#include <alibabacloud/models/UpdateAgentRuntimeEndpointResponse.hpp>
#include <alibabacloud/models/UpdateCredentialRequest.hpp>
#include <alibabacloud/models/UpdateCredentialResponse.hpp>
#include <alibabacloud/models/UpdateCustomDomainRequest.hpp>
#include <alibabacloud/models/UpdateCustomDomainResponse.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseRequest.hpp>
#include <alibabacloud/models/UpdateKnowledgeBaseResponse.hpp>
#include <alibabacloud/models/UpdateMemoryCollectionRequest.hpp>
#include <alibabacloud/models/UpdateMemoryCollectionResponse.hpp>
#include <alibabacloud/models/UpdateModelProxyRequest.hpp>
#include <alibabacloud/models/UpdateModelProxyResponse.hpp>
#include <alibabacloud/models/UpdateModelServiceRequest.hpp>
#include <alibabacloud/models/UpdateModelServiceResponse.hpp>
#include <alibabacloud/models/UpdateTemplateRequest.hpp>
#include <alibabacloud/models/UpdateTemplateResponse.hpp>

#endif
