// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DYTNSAPI20200217MODEL_HPP_
#define ALIBABACLOUD_DYTNSAPI20200217MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CertNoThreeElementVerificationRequest.hpp>
#include <alibabacloud/models/CertNoThreeElementVerificationResponseBody.hpp>
#include <alibabacloud/models/CertNoThreeElementVerificationResponse.hpp>
#include <alibabacloud/models/CertNoTwoElementVerificationRequest.hpp>
#include <alibabacloud/models/CertNoTwoElementVerificationResponseBody.hpp>
#include <alibabacloud/models/CertNoTwoElementVerificationResponse.hpp>
#include <alibabacloud/models/CompanyFourElementsVerificationRequest.hpp>
#include <alibabacloud/models/CompanyFourElementsVerificationResponseBody.hpp>
#include <alibabacloud/models/CompanyFourElementsVerificationResponse.hpp>
#include <alibabacloud/models/CompanyThreeElementsVerificationRequest.hpp>
#include <alibabacloud/models/CompanyThreeElementsVerificationResponseBody.hpp>
#include <alibabacloud/models/CompanyThreeElementsVerificationResponse.hpp>
#include <alibabacloud/models/CompanyTwoElementsVerificationRequest.hpp>
#include <alibabacloud/models/CompanyTwoElementsVerificationResponseBody.hpp>
#include <alibabacloud/models/CompanyTwoElementsVerificationResponse.hpp>
#include <alibabacloud/models/DeleteContactsRequest.hpp>
#include <alibabacloud/models/DeleteContactsResponseBody.hpp>
#include <alibabacloud/models/DeleteContactsResponse.hpp>
#include <alibabacloud/models/DescribeEmptyNumberRequest.hpp>
#include <alibabacloud/models/DescribeEmptyNumberResponseBody.hpp>
#include <alibabacloud/models/DescribeEmptyNumberResponse.hpp>
#include <alibabacloud/models/DescribeMobileOperatorAttributeRequest.hpp>
#include <alibabacloud/models/DescribeMobileOperatorAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeMobileOperatorAttributeResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisAiRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisAiResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisAiResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisPaiRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisPaiResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisPaiResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisTransparentRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisTransparentResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberAnalysisTransparentResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberAttributeRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberAttributeResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberOnlineTimeRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberOnlineTimeResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberOnlineTimeResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualUseRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualUseResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberOperatorAttributeAnnualUseResponse.hpp>
#include <alibabacloud/models/DescribePhoneNumberRiskRequest.hpp>
#include <alibabacloud/models/DescribePhoneNumberRiskResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneNumberRiskResponse.hpp>
#include <alibabacloud/models/DescribePhoneTwiceTelVerifyRequest.hpp>
#include <alibabacloud/models/DescribePhoneTwiceTelVerifyResponseBody.hpp>
#include <alibabacloud/models/DescribePhoneTwiceTelVerifyResponse.hpp>
#include <alibabacloud/models/GetUaidApplyTokenSignRequest.hpp>
#include <alibabacloud/models/GetUaidApplyTokenSignResponseBody.hpp>
#include <alibabacloud/models/GetUaidApplyTokenSignResponse.hpp>
#include <alibabacloud/models/GetUaidConversionSignRequest.hpp>
#include <alibabacloud/models/GetUaidConversionSignResponseBody.hpp>
#include <alibabacloud/models/GetUaidConversionSignResponse.hpp>
#include <alibabacloud/models/InvalidPhoneNumberFilterRequest.hpp>
#include <alibabacloud/models/InvalidPhoneNumberFilterResponseBody.hpp>
#include <alibabacloud/models/InvalidPhoneNumberFilterResponse.hpp>
#include <alibabacloud/models/ListContactsRequest.hpp>
#include <alibabacloud/models/ListContactsResponseBody.hpp>
#include <alibabacloud/models/ListContactsResponse.hpp>
#include <alibabacloud/models/PhoneNumberConvertServiceRequest.hpp>
#include <alibabacloud/models/PhoneNumberConvertServiceResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberConvertServiceResponse.hpp>
#include <alibabacloud/models/PhoneNumberEncryptRequest.hpp>
#include <alibabacloud/models/PhoneNumberEncryptResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberEncryptResponse.hpp>
#include <alibabacloud/models/PhoneNumberStatusForAccountRequest.hpp>
#include <alibabacloud/models/PhoneNumberStatusForAccountResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberStatusForAccountResponse.hpp>
#include <alibabacloud/models/PhoneNumberStatusForPublicRequest.hpp>
#include <alibabacloud/models/PhoneNumberStatusForPublicResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberStatusForPublicResponse.hpp>
#include <alibabacloud/models/PhoneNumberStatusForRealRequest.hpp>
#include <alibabacloud/models/PhoneNumberStatusForRealResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberStatusForRealResponse.hpp>
#include <alibabacloud/models/PhoneNumberStatusForSmsRequest.hpp>
#include <alibabacloud/models/PhoneNumberStatusForSmsResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberStatusForSmsResponse.hpp>
#include <alibabacloud/models/PhoneNumberStatusForVoiceRequest.hpp>
#include <alibabacloud/models/PhoneNumberStatusForVoiceResponseBody.hpp>
#include <alibabacloud/models/PhoneNumberStatusForVoiceResponse.hpp>
#include <alibabacloud/models/QueryAvailableAuthCodeRequest.hpp>
#include <alibabacloud/models/QueryAvailableAuthCodeResponseBody.hpp>
#include <alibabacloud/models/QueryAvailableAuthCodeResponse.hpp>
#include <alibabacloud/models/QueryPackageTypeInfoRequest.hpp>
#include <alibabacloud/models/QueryPackageTypeInfoResponseBody.hpp>
#include <alibabacloud/models/QueryPackageTypeInfoResponse.hpp>
#include <alibabacloud/models/QueryPhoneNumberOnlineTimeRequest.hpp>
#include <alibabacloud/models/QueryPhoneNumberOnlineTimeResponseBody.hpp>
#include <alibabacloud/models/QueryPhoneNumberOnlineTimeResponse.hpp>
#include <alibabacloud/models/QueryPhoneTwiceTelVerifyRequest.hpp>
#include <alibabacloud/models/QueryPhoneTwiceTelVerifyResponseBody.hpp>
#include <alibabacloud/models/QueryPhoneTwiceTelVerifyResponse.hpp>
#include <alibabacloud/models/QueryTagApplyRuleRequest.hpp>
#include <alibabacloud/models/QueryTagApplyRuleResponseBody.hpp>
#include <alibabacloud/models/QueryTagApplyRuleResponse.hpp>
#include <alibabacloud/models/QueryTagInfoBySelectionRequest.hpp>
#include <alibabacloud/models/QueryTagInfoBySelectionResponseBody.hpp>
#include <alibabacloud/models/QueryTagInfoBySelectionResponse.hpp>
#include <alibabacloud/models/QueryTagListPageRequest.hpp>
#include <alibabacloud/models/QueryTagListPageResponseBody.hpp>
#include <alibabacloud/models/QueryTagListPageResponse.hpp>
#include <alibabacloud/models/QueryTaskListRequest.hpp>
#include <alibabacloud/models/QueryTaskListShrinkRequest.hpp>
#include <alibabacloud/models/QueryTaskListResponseBody.hpp>
#include <alibabacloud/models/QueryTaskListResponse.hpp>
#include <alibabacloud/models/QueryUsageStatisticsByTagIdRequest.hpp>
#include <alibabacloud/models/QueryUsageStatisticsByTagIdResponseBody.hpp>
#include <alibabacloud/models/QueryUsageStatisticsByTagIdResponse.hpp>
#include <alibabacloud/models/ThreeElementsVerificationRequest.hpp>
#include <alibabacloud/models/ThreeElementsVerificationResponseBody.hpp>
#include <alibabacloud/models/ThreeElementsVerificationResponse.hpp>
#include <alibabacloud/models/TwoElementsVerificationRequest.hpp>
#include <alibabacloud/models/TwoElementsVerificationResponseBody.hpp>
#include <alibabacloud/models/TwoElementsVerificationResponse.hpp>
#include <alibabacloud/models/UaidCollectionRequest.hpp>
#include <alibabacloud/models/UaidCollectionResponseBody.hpp>
#include <alibabacloud/models/UaidCollectionResponse.hpp>
#include <alibabacloud/models/UaidConversionRequest.hpp>
#include <alibabacloud/models/UaidConversionResponseBody.hpp>
#include <alibabacloud/models/UaidConversionResponse.hpp>
#include <alibabacloud/models/UaidVerificationRequest.hpp>
#include <alibabacloud/models/UaidVerificationResponseBody.hpp>
#include <alibabacloud/models/UaidVerificationResponse.hpp>
#include <alibabacloud/models/UpdateContactsRequest.hpp>
#include <alibabacloud/models/UpdateContactsResponseBody.hpp>
#include <alibabacloud/models/UpdateContactsResponse.hpp>

#endif
