// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLICKHOUSE20191111MODEL_HPP_
#define ALIBABACLOUD_CLICKHOUSE20191111MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionRequest.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionResponseBody.hpp>
#include <alibabacloud/models/AllocateClusterPublicConnectionResponse.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/CancelActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/CancelAppointmentElectZookeeperLeaderRequest.hpp>
#include <alibabacloud/models/CancelAppointmentElectZookeeperLeaderResponseBody.hpp>
#include <alibabacloud/models/CancelAppointmentElectZookeeperLeaderResponse.hpp>
#include <alibabacloud/models/CancelAppointmentRestartInstanceNodeListRequest.hpp>
#include <alibabacloud/models/CancelAppointmentRestartInstanceNodeListResponseBody.hpp>
#include <alibabacloud/models/CancelAppointmentRestartInstanceNodeListResponse.hpp>
#include <alibabacloud/models/CancelRestartInstanceRequest.hpp>
#include <alibabacloud/models/CancelRestartInstanceResponseBody.hpp>
#include <alibabacloud/models/CancelRestartInstanceResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckClickhouseToRdsRequest.hpp>
#include <alibabacloud/models/CheckClickhouseToRdsResponseBody.hpp>
#include <alibabacloud/models/CheckClickhouseToRdsResponse.hpp>
#include <alibabacloud/models/CheckModifyConfigNeedRestartRequest.hpp>
#include <alibabacloud/models/CheckModifyConfigNeedRestartResponseBody.hpp>
#include <alibabacloud/models/CheckModifyConfigNeedRestartResponse.hpp>
#include <alibabacloud/models/CheckMonitorAlertRequest.hpp>
#include <alibabacloud/models/CheckMonitorAlertResponseBody.hpp>
#include <alibabacloud/models/CheckMonitorAlertResponse.hpp>
#include <alibabacloud/models/CheckScaleOutBalancedRequest.hpp>
#include <alibabacloud/models/CheckScaleOutBalancedResponseBody.hpp>
#include <alibabacloud/models/CheckScaleOutBalancedResponse.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateAccountAndAuthorityRequest.hpp>
#include <alibabacloud/models/CreateAccountAndAuthorityResponseBody.hpp>
#include <alibabacloud/models/CreateAccountAndAuthorityResponse.hpp>
#include <alibabacloud/models/CreateBackupPolicyRequest.hpp>
#include <alibabacloud/models/CreateBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateBackupPolicyResponse.hpp>
#include <alibabacloud/models/CreateDbInstanceRequest.hpp>
#include <alibabacloud/models/CreateDbInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateDbInstanceResponse.hpp>
#include <alibabacloud/models/CreateMonitorDataReportRequest.hpp>
#include <alibabacloud/models/CreateMonitorDataReportResponseBody.hpp>
#include <alibabacloud/models/CreateMonitorDataReportResponse.hpp>
#include <alibabacloud/models/CreateOssStorageRequest.hpp>
#include <alibabacloud/models/CreateOssStorageResponseBody.hpp>
#include <alibabacloud/models/CreateOssStorageResponse.hpp>
#include <alibabacloud/models/CreatePortsForClickHouseRequest.hpp>
#include <alibabacloud/models/CreatePortsForClickHouseResponseBody.hpp>
#include <alibabacloud/models/CreatePortsForClickHouseResponse.hpp>
#include <alibabacloud/models/CreateRdsToClickhouseDbRequest.hpp>
#include <alibabacloud/models/CreateRdsToClickhouseDbResponseBody.hpp>
#include <alibabacloud/models/CreateRdsToClickhouseDbResponse.hpp>
#include <alibabacloud/models/CreateSlbRequest.hpp>
#include <alibabacloud/models/CreateSlbResponseBody.hpp>
#include <alibabacloud/models/CreateSlbResponse.hpp>
#include <alibabacloud/models/CreateSqlAccountRequest.hpp>
#include <alibabacloud/models/CreateSqlAccountResponseBody.hpp>
#include <alibabacloud/models/CreateSqlAccountResponse.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleRequest.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponseBody.hpp>
#include <alibabacloud/models/CreateServiceLinkedRoleResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBackupPolicyRequest.hpp>
#include <alibabacloud/models/DeleteBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupPolicyResponse.hpp>
#include <alibabacloud/models/DeleteDbClusterRequest.hpp>
#include <alibabacloud/models/DeleteDbClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteDbClusterResponse.hpp>
#include <alibabacloud/models/DeleteSlbRequest.hpp>
#include <alibabacloud/models/DeleteSlbResponseBody.hpp>
#include <alibabacloud/models/DeleteSlbResponse.hpp>
#include <alibabacloud/models/DeleteSyndbRequest.hpp>
#include <alibabacloud/models/DeleteSyndbResponseBody.hpp>
#include <alibabacloud/models/DeleteSyndbResponse.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityRequest.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/DescribeAllDataSourceRequest.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBody.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponse.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesRequest.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponse.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeColumnsRequest.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBody.hpp>
#include <alibabacloud/models/DescribeColumnsResponse.hpp>
#include <alibabacloud/models/DescribeConfigHistoryRequest.hpp>
#include <alibabacloud/models/DescribeConfigHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeConfigHistoryResponse.hpp>
#include <alibabacloud/models/DescribeConfigVersionDifferenceRequest.hpp>
#include <alibabacloud/models/DescribeConfigVersionDifferenceResponseBody.hpp>
#include <alibabacloud/models/DescribeConfigVersionDifferenceResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigInXmlRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigInXmlResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterConfigInXmlResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoItemsRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoItemsResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoItemsResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterNodeInfosRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterNodeInfosResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterNodeInfosResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponse.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusSetRequest.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusSetResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClusterStatusSetResponse.hpp>
#include <alibabacloud/models/DescribeDbClustersRequest.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeDbClustersResponse.hpp>
#include <alibabacloud/models/DescribeDbConfigRequest.hpp>
#include <alibabacloud/models/DescribeDbConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDbConfigResponse.hpp>
#include <alibabacloud/models/DescribeEventMetaInfoRequest.hpp>
#include <alibabacloud/models/DescribeEventMetaInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeEventMetaInfoResponse.hpp>
#include <alibabacloud/models/DescribeOssStorageRequest.hpp>
#include <alibabacloud/models/DescribeOssStorageResponseBody.hpp>
#include <alibabacloud/models/DescribeOssStorageResponse.hpp>
#include <alibabacloud/models/DescribeProcessListRequest.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBody.hpp>
#include <alibabacloud/models/DescribeProcessListResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeSchemasRequest.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBody.hpp>
#include <alibabacloud/models/DescribeSchemasResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponse.hpp>
#include <alibabacloud/models/DescribeSynDbTablesRequest.hpp>
#include <alibabacloud/models/DescribeSynDbTablesResponseBody.hpp>
#include <alibabacloud/models/DescribeSynDbTablesResponse.hpp>
#include <alibabacloud/models/DescribeSynDbsRequest.hpp>
#include <alibabacloud/models/DescribeSynDbsResponseBody.hpp>
#include <alibabacloud/models/DescribeSynDbsResponse.hpp>
#include <alibabacloud/models/DescribeTablesRequest.hpp>
#include <alibabacloud/models/DescribeTablesResponseBody.hpp>
#include <alibabacloud/models/DescribeTablesResponse.hpp>
#include <alibabacloud/models/DescribeTransferHistoryRequest.hpp>
#include <alibabacloud/models/DescribeTransferHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeTransferHistoryResponse.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListRequest.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponse.hpp>
#include <alibabacloud/models/ElectZookeeperLeaderRequest.hpp>
#include <alibabacloud/models/ElectZookeeperLeaderResponseBody.hpp>
#include <alibabacloud/models/ElectZookeeperLeaderResponse.hpp>
#include <alibabacloud/models/KillProcessRequest.hpp>
#include <alibabacloud/models/KillProcessResponseBody.hpp>
#include <alibabacloud/models/KillProcessResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityRequest.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationMaintainConfResponse.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksRequest.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponseBody.hpp>
#include <alibabacloud/models/ModifyActiveOperationTasksResponse.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoRenewAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterAccessWhiteListResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigInXmlRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigInXmlResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterConfigInXmlResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbClusterMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyDbConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbConfigResponse.hpp>
#include <alibabacloud/models/ModifyMinorVersionGreadeTypeRequest.hpp>
#include <alibabacloud/models/ModifyMinorVersionGreadeTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyMinorVersionGreadeTypeResponse.hpp>
#include <alibabacloud/models/ModifyRdsToClickhouseDbRequest.hpp>
#include <alibabacloud/models/ModifyRdsToClickhouseDbResponseBody.hpp>
#include <alibabacloud/models/ModifyRdsToClickhouseDbResponse.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionRequest.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionResponseBody.hpp>
#include <alibabacloud/models/ReleaseClusterPublicConnectionResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/RestartInstanceRequest.hpp>
#include <alibabacloud/models/RestartInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartInstanceResponse.hpp>
#include <alibabacloud/models/RestartInstanceNodeListRequest.hpp>
#include <alibabacloud/models/RestartInstanceNodeListShrinkRequest.hpp>
#include <alibabacloud/models/RestartInstanceNodeListResponseBody.hpp>
#include <alibabacloud/models/RestartInstanceNodeListResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TransferVersionRequest.hpp>
#include <alibabacloud/models/TransferVersionResponseBody.hpp>
#include <alibabacloud/models/TransferVersionResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpgradeMinorVersionRequest.hpp>
#include <alibabacloud/models/UpgradeMinorVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeMinorVersionResponse.hpp>
#include <alibabacloud/models/CheckScaleOutBalancedResponseBodyTableDetailsTableDetail.hpp>
#include <alibabacloud/models/CheckScaleOutBalancedResponseBodyTableDetails.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccountsAccount.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyAccounts.hpp>
#include <alibabacloud/models/DescribeActiveOperationMaintainConfResponseBodyConfig.hpp>
#include <alibabacloud/models/DescribeActiveOperationTasksResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyColumnsColumn.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyColumns.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodySchemasSchema.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodySchemas.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyTablesTable.hpp>
#include <alibabacloud/models/DescribeAllDataSourceResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodyColumnsColumn.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodyColumns.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodySchemasSchema.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodySchemas.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodyTablesTable.hpp>
#include <alibabacloud/models/DescribeAllDataSourcesResponseBodyTables.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItemsAutoRenewAttribute.hpp>
#include <alibabacloud/models/DescribeAutoRenewAttributeResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBodyItemsColumn.hpp>
#include <alibabacloud/models/DescribeColumnsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeConfigHistoryResponseBodyConfigHistoryItems.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBodyDbClusterAccessWhiteListIpArray.hpp>
#include <alibabacloud/models/DescribeDbClusterAccessWhiteListResponseBodyDbClusterAccessWhiteList.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyDbClusterScaleOutStatus.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyDbClusterTags.hpp>
#include <alibabacloud/models/DescribeDbClusterAttributeResponseBodyDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoItemsResponseBodyNetInfoItemsNetInfoItem.hpp>
#include <alibabacloud/models/DescribeDbClusterNetInfoItemsResponseBodyNetInfoItems.hpp>
#include <alibabacloud/models/DescribeDbClusterNodeInfosResponseBodyNodeInfos.hpp>
#include <alibabacloud/models/DescribeDbClusterNodeInfosResponseBodyZkNodeInfos.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformancesSeriesValues.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformancesSeries.hpp>
#include <alibabacloud/models/DescribeDbClusterPerformanceResponseBodyPerformances.hpp>
#include <alibabacloud/models/DescribeDbClustersRequestTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyDbClustersDbClusterScaleOutStatus.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyDbClustersDbClusterTagsTag.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyDbClustersDbClusterTags.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyDbClustersDbCluster.hpp>
#include <alibabacloud/models/DescribeDbClustersResponseBodyDbClusters.hpp>
#include <alibabacloud/models/DescribeEventMetaInfoResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessListDataResultSet.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessListData.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessListStatistics.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessListTableSchemaResultSet.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessListTableSchema.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyProcessList.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZonesZone.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBodyItemsSchema.hpp>
#include <alibabacloud/models/DescribeSchemasResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecordsDataResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecordsData.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecordsStatistics.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecordsTableSchemaResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecordsTableSchema.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodySlowLogRecords.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrendDataResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrendData.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrendStatistics.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrendTableSchemaResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrendTableSchema.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodySlowLogTrend.hpp>
#include <alibabacloud/models/DescribeSynDbsResponseBodySynDbs.hpp>
#include <alibabacloud/models/DescribeTablesResponseBodyItemsTable.hpp>
#include <alibabacloud/models/DescribeTablesResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeTransferHistoryResponseBodyHistoryDetailsHistoryDetail.hpp>
#include <alibabacloud/models/DescribeTransferHistoryResponseBodyHistoryDetails.hpp>
#include <alibabacloud/models/DescribeUserEncryptionKeyListResponseBodyKmsKeys.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyDbClusterResponseBodyDbCluster.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
