// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_WAFOPENAPI20211001MODEL_HPP_
#define ALIBABACLOUD_WAFOPENAPI20211001MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddAddressRequest.hpp>
#include <alibabacloud/models/AddAddressResponseBody.hpp>
#include <alibabacloud/models/AddAddressResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/ClearAddressRequest.hpp>
#include <alibabacloud/models/ClearAddressResponseBody.hpp>
#include <alibabacloud/models/ClearAddressResponse.hpp>
#include <alibabacloud/models/ClearMajorProtectionBlackIpRequest.hpp>
#include <alibabacloud/models/ClearMajorProtectionBlackIpResponseBody.hpp>
#include <alibabacloud/models/ClearMajorProtectionBlackIpResponse.hpp>
#include <alibabacloud/models/CopyDefenseTemplateRequest.hpp>
#include <alibabacloud/models/CopyDefenseTemplateResponseBody.hpp>
#include <alibabacloud/models/CopyDefenseTemplateResponse.hpp>
#include <alibabacloud/models/CreateApiExportRequest.hpp>
#include <alibabacloud/models/CreateApiExportResponseBody.hpp>
#include <alibabacloud/models/CreateApiExportResponse.hpp>
#include <alibabacloud/models/CreateCertsRequest.hpp>
#include <alibabacloud/models/CreateCertsResponseBody.hpp>
#include <alibabacloud/models/CreateCertsResponse.hpp>
#include <alibabacloud/models/CreateCloudResourceRequest.hpp>
#include <alibabacloud/models/CreateCloudResourceShrinkRequest.hpp>
#include <alibabacloud/models/CreateCloudResourceResponseBody.hpp>
#include <alibabacloud/models/CreateCloudResourceResponse.hpp>
#include <alibabacloud/models/CreateDefenseResourceRequest.hpp>
#include <alibabacloud/models/CreateDefenseResourceShrinkRequest.hpp>
#include <alibabacloud/models/CreateDefenseResourceResponseBody.hpp>
#include <alibabacloud/models/CreateDefenseResourceResponse.hpp>
#include <alibabacloud/models/CreateDefenseResourceGroupRequest.hpp>
#include <alibabacloud/models/CreateDefenseResourceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDefenseResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateDefenseRuleRequest.hpp>
#include <alibabacloud/models/CreateDefenseRuleResponseBody.hpp>
#include <alibabacloud/models/CreateDefenseRuleResponse.hpp>
#include <alibabacloud/models/CreateDefenseTemplateRequest.hpp>
#include <alibabacloud/models/CreateDefenseTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateDefenseTemplateResponse.hpp>
#include <alibabacloud/models/CreateDomainRequest.hpp>
#include <alibabacloud/models/CreateDomainShrinkRequest.hpp>
#include <alibabacloud/models/CreateDomainResponseBody.hpp>
#include <alibabacloud/models/CreateDomainResponse.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterRequest.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterResponseBody.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterResponse.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterRuleRequest.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterRuleResponseBody.hpp>
#include <alibabacloud/models/CreateHybridCloudClusterRuleResponse.hpp>
#include <alibabacloud/models/CreateHybridCloudGroupRequest.hpp>
#include <alibabacloud/models/CreateHybridCloudGroupResponseBody.hpp>
#include <alibabacloud/models/CreateHybridCloudGroupResponse.hpp>
#include <alibabacloud/models/CreateLogDeliveryConfigRequest.hpp>
#include <alibabacloud/models/CreateLogDeliveryConfigResponseBody.hpp>
#include <alibabacloud/models/CreateLogDeliveryConfigResponse.hpp>
#include <alibabacloud/models/CreateMajorProtectionBlackIpRequest.hpp>
#include <alibabacloud/models/CreateMajorProtectionBlackIpResponseBody.hpp>
#include <alibabacloud/models/CreateMajorProtectionBlackIpResponse.hpp>
#include <alibabacloud/models/CreateMemberAccountsRequest.hpp>
#include <alibabacloud/models/CreateMemberAccountsResponseBody.hpp>
#include <alibabacloud/models/CreateMemberAccountsResponse.hpp>
#include <alibabacloud/models/CreatePocFunctionRequest.hpp>
#include <alibabacloud/models/CreatePocFunctionResponseBody.hpp>
#include <alibabacloud/models/CreatePocFunctionResponse.hpp>
#include <alibabacloud/models/CreatePostpaidInstanceRequest.hpp>
#include <alibabacloud/models/CreatePostpaidInstanceResponseBody.hpp>
#include <alibabacloud/models/CreatePostpaidInstanceResponse.hpp>
#include <alibabacloud/models/CreateSm2CertRequest.hpp>
#include <alibabacloud/models/CreateSm2CertResponseBody.hpp>
#include <alibabacloud/models/CreateSm2CertResponse.hpp>
#include <alibabacloud/models/DeleteAddressRequest.hpp>
#include <alibabacloud/models/DeleteAddressResponseBody.hpp>
#include <alibabacloud/models/DeleteAddressResponse.hpp>
#include <alibabacloud/models/DeleteApisecAbnormalsRequest.hpp>
#include <alibabacloud/models/DeleteApisecAbnormalsResponseBody.hpp>
#include <alibabacloud/models/DeleteApisecAbnormalsResponse.hpp>
#include <alibabacloud/models/DeleteApisecEventsRequest.hpp>
#include <alibabacloud/models/DeleteApisecEventsResponseBody.hpp>
#include <alibabacloud/models/DeleteApisecEventsResponse.hpp>
#include <alibabacloud/models/DeleteCloudResourceRequest.hpp>
#include <alibabacloud/models/DeleteCloudResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudResourceResponse.hpp>
#include <alibabacloud/models/DeleteDefenseResourceRequest.hpp>
#include <alibabacloud/models/DeleteDefenseResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteDefenseResourceResponse.hpp>
#include <alibabacloud/models/DeleteDefenseResourceGroupRequest.hpp>
#include <alibabacloud/models/DeleteDefenseResourceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDefenseResourceGroupResponse.hpp>
#include <alibabacloud/models/DeleteDefenseRuleRequest.hpp>
#include <alibabacloud/models/DeleteDefenseRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteDefenseRuleResponse.hpp>
#include <alibabacloud/models/DeleteDefenseRuleBlockIpRequest.hpp>
#include <alibabacloud/models/DeleteDefenseRuleBlockIpResponseBody.hpp>
#include <alibabacloud/models/DeleteDefenseRuleBlockIpResponse.hpp>
#include <alibabacloud/models/DeleteDefenseTemplateRequest.hpp>
#include <alibabacloud/models/DeleteDefenseTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteDefenseTemplateResponse.hpp>
#include <alibabacloud/models/DeleteDomainRequest.hpp>
#include <alibabacloud/models/DeleteDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainResponse.hpp>
#include <alibabacloud/models/DeleteHybridCloudClusterRuleRequest.hpp>
#include <alibabacloud/models/DeleteHybridCloudClusterRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteHybridCloudClusterRuleResponse.hpp>
#include <alibabacloud/models/DeleteHybridCloudGroupRequest.hpp>
#include <alibabacloud/models/DeleteHybridCloudGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteHybridCloudGroupResponse.hpp>
#include <alibabacloud/models/DeleteLogDeliveryConfigRequest.hpp>
#include <alibabacloud/models/DeleteLogDeliveryConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteLogDeliveryConfigResponse.hpp>
#include <alibabacloud/models/DeleteMajorProtectionBlackIpRequest.hpp>
#include <alibabacloud/models/DeleteMajorProtectionBlackIpResponseBody.hpp>
#include <alibabacloud/models/DeleteMajorProtectionBlackIpResponse.hpp>
#include <alibabacloud/models/DeleteMemberAccountRequest.hpp>
#include <alibabacloud/models/DeleteMemberAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteMemberAccountResponse.hpp>
#include <alibabacloud/models/DescribeAbnormalCloudResourcesRequest.hpp>
#include <alibabacloud/models/DescribeAbnormalCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeAbnormalCloudResourcesResponse.hpp>
#include <alibabacloud/models/DescribeAccountDelegatedStatusRequest.hpp>
#include <alibabacloud/models/DescribeAccountDelegatedStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountDelegatedStatusResponse.hpp>
#include <alibabacloud/models/DescribeAddressesRequest.hpp>
#include <alibabacloud/models/DescribeAddressesResponseBody.hpp>
#include <alibabacloud/models/DescribeAddressesResponse.hpp>
#include <alibabacloud/models/DescribeAlarmBannerRequest.hpp>
#include <alibabacloud/models/DescribeAlarmBannerResponseBody.hpp>
#include <alibabacloud/models/DescribeAlarmBannerResponse.hpp>
#include <alibabacloud/models/DescribeAlarmListRequest.hpp>
#include <alibabacloud/models/DescribeAlarmListResponseBody.hpp>
#include <alibabacloud/models/DescribeAlarmListResponse.hpp>
#include <alibabacloud/models/DescribeApiExportsRequest.hpp>
#include <alibabacloud/models/DescribeApiExportsResponseBody.hpp>
#include <alibabacloud/models/DescribeApiExportsResponse.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalDomainStatisticRequest.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalDomainStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalDomainStatisticResponse.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalsRequest.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecAbnormalsResponse.hpp>
#include <alibabacloud/models/DescribeApisecApiResourcesRequest.hpp>
#include <alibabacloud/models/DescribeApisecApiResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecApiResourcesResponse.hpp>
#include <alibabacloud/models/DescribeApisecAssetTrendRequest.hpp>
#include <alibabacloud/models/DescribeApisecAssetTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecAssetTrendResponse.hpp>
#include <alibabacloud/models/DescribeApisecEventDetailRequest.hpp>
#include <alibabacloud/models/DescribeApisecEventDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecEventDetailResponse.hpp>
#include <alibabacloud/models/DescribeApisecEventDomainStatisticRequest.hpp>
#include <alibabacloud/models/DescribeApisecEventDomainStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecEventDomainStatisticResponse.hpp>
#include <alibabacloud/models/DescribeApisecEventsRequest.hpp>
#include <alibabacloud/models/DescribeApisecEventsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecEventsResponse.hpp>
#include <alibabacloud/models/DescribeApisecExamplesRequest.hpp>
#include <alibabacloud/models/DescribeApisecExamplesResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecExamplesResponse.hpp>
#include <alibabacloud/models/DescribeApisecLogDeliveriesRequest.hpp>
#include <alibabacloud/models/DescribeApisecLogDeliveriesResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecLogDeliveriesResponse.hpp>
#include <alibabacloud/models/DescribeApisecMatchedHostsRequest.hpp>
#include <alibabacloud/models/DescribeApisecMatchedHostsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecMatchedHostsResponse.hpp>
#include <alibabacloud/models/DescribeApisecProtectionGroupsRequest.hpp>
#include <alibabacloud/models/DescribeApisecProtectionGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecProtectionGroupsResponse.hpp>
#include <alibabacloud/models/DescribeApisecProtectionResourcesRequest.hpp>
#include <alibabacloud/models/DescribeApisecProtectionResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecProtectionResourcesResponse.hpp>
#include <alibabacloud/models/DescribeApisecRulesRequest.hpp>
#include <alibabacloud/models/DescribeApisecRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecRulesResponse.hpp>
#include <alibabacloud/models/DescribeApisecSensitiveDomainStatisticRequest.hpp>
#include <alibabacloud/models/DescribeApisecSensitiveDomainStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecSensitiveDomainStatisticResponse.hpp>
#include <alibabacloud/models/DescribeApisecSlsLogStoresRequest.hpp>
#include <alibabacloud/models/DescribeApisecSlsLogStoresResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecSlsLogStoresResponse.hpp>
#include <alibabacloud/models/DescribeApisecSlsProjectsRequest.hpp>
#include <alibabacloud/models/DescribeApisecSlsProjectsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecSlsProjectsResponse.hpp>
#include <alibabacloud/models/DescribeApisecStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeApisecStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeApisecSuggestionsRequest.hpp>
#include <alibabacloud/models/DescribeApisecSuggestionsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecSuggestionsResponse.hpp>
#include <alibabacloud/models/DescribeApisecUserOperationsRequest.hpp>
#include <alibabacloud/models/DescribeApisecUserOperationsResponseBody.hpp>
#include <alibabacloud/models/DescribeApisecUserOperationsResponse.hpp>
#include <alibabacloud/models/DescribeBaseSystemRulesRequest.hpp>
#include <alibabacloud/models/DescribeBaseSystemRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeBaseSystemRulesResponse.hpp>
#include <alibabacloud/models/DescribeBotAppKeyRequest.hpp>
#include <alibabacloud/models/DescribeBotAppKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeBotAppKeyResponse.hpp>
#include <alibabacloud/models/DescribeBotRuleLabelsRequest.hpp>
#include <alibabacloud/models/DescribeBotRuleLabelsResponseBody.hpp>
#include <alibabacloud/models/DescribeBotRuleLabelsResponse.hpp>
#include <alibabacloud/models/DescribeCertDetailRequest.hpp>
#include <alibabacloud/models/DescribeCertDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeCertDetailResponse.hpp>
#include <alibabacloud/models/DescribeCertsRequest.hpp>
#include <alibabacloud/models/DescribeCertsResponseBody.hpp>
#include <alibabacloud/models/DescribeCertsResponse.hpp>
#include <alibabacloud/models/DescribeChargeModuleRequest.hpp>
#include <alibabacloud/models/DescribeChargeModuleResponseBody.hpp>
#include <alibabacloud/models/DescribeChargeModuleResponse.hpp>
#include <alibabacloud/models/DescribeChargeResultRequest.hpp>
#include <alibabacloud/models/DescribeChargeResultResponseBody.hpp>
#include <alibabacloud/models/DescribeChargeResultResponse.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessPortDetailsRequest.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessPortDetailsResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessPortDetailsResponse.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessedPortsRequest.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessedPortsResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudResourceAccessedPortsResponse.hpp>
#include <alibabacloud/models/DescribeCloudResourcesRequest.hpp>
#include <alibabacloud/models/DescribeCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudResourcesResponse.hpp>
#include <alibabacloud/models/DescribeCnameCountRequest.hpp>
#include <alibabacloud/models/DescribeCnameCountResponseBody.hpp>
#include <alibabacloud/models/DescribeCnameCountResponse.hpp>
#include <alibabacloud/models/DescribeCommonLogFieldsRequest.hpp>
#include <alibabacloud/models/DescribeCommonLogFieldsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeCommonLogFieldsResponseBody.hpp>
#include <alibabacloud/models/DescribeCommonLogFieldsResponse.hpp>
#include <alibabacloud/models/DescribeCustomBaseRuleCompileResultRequest.hpp>
#include <alibabacloud/models/DescribeCustomBaseRuleCompileResultResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomBaseRuleCompileResultResponse.hpp>
#include <alibabacloud/models/DescribeDDoSStatusRequest.hpp>
#include <alibabacloud/models/DescribeDDoSStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDDoSStatusResponse.hpp>
#include <alibabacloud/models/DescribeDefaultHttpsRequest.hpp>
#include <alibabacloud/models/DescribeDefaultHttpsResponseBody.hpp>
#include <alibabacloud/models/DescribeDefaultHttpsResponse.hpp>
#include <alibabacloud/models/DescribeDefenseGroupValidResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseGroupValidResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseGroupValidResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupNamesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupNamesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupNamesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupsRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceGroupsResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceNamesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceNamesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceNamesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceOwnerUidRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceOwnerUidResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceOwnerUidResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourceTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourceTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourceTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseRuleRequest.hpp>
#include <alibabacloud/models/DescribeDefenseRuleResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseRuleResponse.hpp>
#include <alibabacloud/models/DescribeDefenseRuleStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDefenseRuleStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseRuleStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDefenseRulesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseRulesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseSceneConfigRequest.hpp>
#include <alibabacloud/models/DescribeDefenseSceneConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseSceneConfigResponse.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateRequest.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateResponse.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidGroupsRequest.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidGroupsResponse.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseTemplateValidResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDefenseTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeDefenseTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeDefenseTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeDomainDnsRecordRequest.hpp>
#include <alibabacloud/models/DescribeDomainDnsRecordResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainDnsRecordResponse.hpp>
#include <alibabacloud/models/DescribeDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeDomainUsedPortsRequest.hpp>
#include <alibabacloud/models/DescribeDomainUsedPortsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainUsedPortsResponse.hpp>
#include <alibabacloud/models/DescribeDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainsResponse.hpp>
#include <alibabacloud/models/DescribeFlowChartRequest.hpp>
#include <alibabacloud/models/DescribeFlowChartResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowChartResponse.hpp>
#include <alibabacloud/models/DescribeFlowTopResourceRequest.hpp>
#include <alibabacloud/models/DescribeFlowTopResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowTopResourceResponse.hpp>
#include <alibabacloud/models/DescribeFlowTopUrlRequest.hpp>
#include <alibabacloud/models/DescribeFlowTopUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowTopUrlResponse.hpp>
#include <alibabacloud/models/DescribeFreeUserAssetCountRequest.hpp>
#include <alibabacloud/models/DescribeFreeUserAssetCountResponseBody.hpp>
#include <alibabacloud/models/DescribeFreeUserAssetCountResponse.hpp>
#include <alibabacloud/models/DescribeFreeUserEventCountRequest.hpp>
#include <alibabacloud/models/DescribeFreeUserEventCountResponseBody.hpp>
#include <alibabacloud/models/DescribeFreeUserEventCountResponse.hpp>
#include <alibabacloud/models/DescribeFreeUserEventTypesRequest.hpp>
#include <alibabacloud/models/DescribeFreeUserEventTypesResponseBody.hpp>
#include <alibabacloud/models/DescribeFreeUserEventTypesResponse.hpp>
#include <alibabacloud/models/DescribeFreeUserEventsRequest.hpp>
#include <alibabacloud/models/DescribeFreeUserEventsResponseBody.hpp>
#include <alibabacloud/models/DescribeFreeUserEventsResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudBasicMonitorRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudBasicMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudBasicMonitorResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRuleRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRuleResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRuleResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRulesRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterRulesResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterServersRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterServersResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudClusterServersResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudClustersRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudClustersResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudGroupsRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudGroupsResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudProcessMonitorRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudProcessMonitorResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudProcessMonitorResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudProtectableCountRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudProtectableCountResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudProtectableCountResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourceDetailRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourceDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourceDetailResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourcesRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudResourcesResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudSdkServersRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudSdkServersResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudSdkServersResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudServerRegionsRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudServerRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudServerRegionsResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudSupportRegionsRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudSupportRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudSupportRegionsResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnassignedMachinesRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnassignedMachinesResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnassignedMachinesResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnsupportPortsRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnsupportPortsResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudUnsupportPortsResponse.hpp>
#include <alibabacloud/models/DescribeHybridCloudUserRequest.hpp>
#include <alibabacloud/models/DescribeHybridCloudUserResponseBody.hpp>
#include <alibabacloud/models/DescribeHybridCloudUserResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRequest.hpp>
#include <alibabacloud/models/DescribeInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceResponse.hpp>
#include <alibabacloud/models/DescribeIpAbroadCountryInfosRequest.hpp>
#include <alibabacloud/models/DescribeIpAbroadCountryInfosResponseBody.hpp>
#include <alibabacloud/models/DescribeIpAbroadCountryInfosResponse.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigRequest.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigResponse.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigsRequest.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeLogDeliveryConfigsResponse.hpp>
#include <alibabacloud/models/DescribeMajorProtectionBlackIpsRequest.hpp>
#include <alibabacloud/models/DescribeMajorProtectionBlackIpsResponseBody.hpp>
#include <alibabacloud/models/DescribeMajorProtectionBlackIpsResponse.hpp>
#include <alibabacloud/models/DescribeMemberAccountsRequest.hpp>
#include <alibabacloud/models/DescribeMemberAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeMemberAccountsResponse.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTimeSeriesMetricRequest.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTimeSeriesMetricShrinkRequest.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTimeSeriesMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTimeSeriesMetricResponse.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTopNMetricRequest.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTopNMetricShrinkRequest.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTopNMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkFlowTopNMetricResponse.hpp>
#include <alibabacloud/models/DescribePauseProtectionStatusRequest.hpp>
#include <alibabacloud/models/DescribePauseProtectionStatusResponseBody.hpp>
#include <alibabacloud/models/DescribePauseProtectionStatusResponse.hpp>
#include <alibabacloud/models/DescribePeakTrendRequest.hpp>
#include <alibabacloud/models/DescribePeakTrendResponseBody.hpp>
#include <alibabacloud/models/DescribePeakTrendResponse.hpp>
#include <alibabacloud/models/DescribePocFunctionsRequest.hpp>
#include <alibabacloud/models/DescribePocFunctionsResponseBody.hpp>
#include <alibabacloud/models/DescribePocFunctionsResponse.hpp>
#include <alibabacloud/models/DescribeProductInstancesRequest.hpp>
#include <alibabacloud/models/DescribeProductInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeProductInstancesResponse.hpp>
#include <alibabacloud/models/DescribePunishedDomainsRequest.hpp>
#include <alibabacloud/models/DescribePunishedDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribePunishedDomainsResponse.hpp>
#include <alibabacloud/models/DescribeRelatedDefenseRulesRequest.hpp>
#include <alibabacloud/models/DescribeRelatedDefenseRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeRelatedDefenseRulesResponse.hpp>
#include <alibabacloud/models/DescribeResourceInstanceCertsRequest.hpp>
#include <alibabacloud/models/DescribeResourceInstanceCertsResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceInstanceCertsResponse.hpp>
#include <alibabacloud/models/DescribeResourceLogDeliveryStatusRequest.hpp>
#include <alibabacloud/models/DescribeResourceLogDeliveryStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceLogDeliveryStatusResponse.hpp>
#include <alibabacloud/models/DescribeResourceLogFieldConfigRequest.hpp>
#include <alibabacloud/models/DescribeResourceLogFieldConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceLogFieldConfigResponse.hpp>
#include <alibabacloud/models/DescribeResourceLogStatusRequest.hpp>
#include <alibabacloud/models/DescribeResourceLogStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceLogStatusResponse.hpp>
#include <alibabacloud/models/DescribeResourcePortRequest.hpp>
#include <alibabacloud/models/DescribeResourcePortResponseBody.hpp>
#include <alibabacloud/models/DescribeResourcePortResponse.hpp>
#include <alibabacloud/models/DescribeResourceRegionIdRequest.hpp>
#include <alibabacloud/models/DescribeResourceRegionIdResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceRegionIdResponse.hpp>
#include <alibabacloud/models/DescribeResourceSupportRegionsRequest.hpp>
#include <alibabacloud/models/DescribeResourceSupportRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceSupportRegionsResponse.hpp>
#include <alibabacloud/models/DescribeResponseCodeTrendGraphRequest.hpp>
#include <alibabacloud/models/DescribeResponseCodeTrendGraphResponseBody.hpp>
#include <alibabacloud/models/DescribeResponseCodeTrendGraphResponse.hpp>
#include <alibabacloud/models/DescribeRoleAuthStatusRequest.hpp>
#include <alibabacloud/models/DescribeRoleAuthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeRoleAuthStatusResponse.hpp>
#include <alibabacloud/models/DescribeRuleGroupsRequest.hpp>
#include <alibabacloud/models/DescribeRuleGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleGroupsResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopClientIpRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopClientIpResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopClientIpResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopResourceRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopResourceResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopResourceResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopRuleIdRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopRuleIdResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopRuleIdResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopTuleTypeRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopTuleTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopTuleTypeResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUaRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUaResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUaResponse.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUrlRequest.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeRuleHitsTopUrlResponse.hpp>
#include <alibabacloud/models/DescribeSecurityEventLogsRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventLogsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityEventLogsResponse.hpp>
#include <alibabacloud/models/DescribeSecurityEventTimeSeriesMetricRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventTimeSeriesMetricShrinkRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventTimeSeriesMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityEventTimeSeriesMetricResponse.hpp>
#include <alibabacloud/models/DescribeSecurityEventTopNMetricRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventTopNMetricShrinkRequest.hpp>
#include <alibabacloud/models/DescribeSecurityEventTopNMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityEventTopNMetricResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveApiStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveApiStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveApiStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveDetectionResultRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveDetectionResultResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveDetectionResultResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundDistributionRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundDistributionResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundDistributionResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundTrendRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveOutboundTrendResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestLogRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestLogResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestLogResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestsRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestsResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveRequestsResponse.hpp>
#include <alibabacloud/models/DescribeSensitiveStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSensitiveStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSensitiveStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSlsAuthStatusRequest.hpp>
#include <alibabacloud/models/DescribeSlsAuthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeSlsAuthStatusResponse.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreRequest.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreResponseBody.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreResponse.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreStatusRequest.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeSlsLogStoreStatusResponse.hpp>
#include <alibabacloud/models/DescribeTemplateResourceCountRequest.hpp>
#include <alibabacloud/models/DescribeTemplateResourceCountResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplateResourceCountResponse.hpp>
#include <alibabacloud/models/DescribeTemplateResourcesRequest.hpp>
#include <alibabacloud/models/DescribeTemplateResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplateResourcesResponse.hpp>
#include <alibabacloud/models/DescribeThreatEventRequest.hpp>
#include <alibabacloud/models/DescribeThreatEventResponseBody.hpp>
#include <alibabacloud/models/DescribeThreatEventResponse.hpp>
#include <alibabacloud/models/DescribeThreatEventDetailRequest.hpp>
#include <alibabacloud/models/DescribeThreatEventDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeThreatEventDetailResponse.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTrendRequest.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTrendResponse.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTypeRequest.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAbnormalTypeResponse.hpp>
#include <alibabacloud/models/DescribeUserApiRequestRequest.hpp>
#include <alibabacloud/models/DescribeUserApiRequestResponseBody.hpp>
#include <alibabacloud/models/DescribeUserApiRequestResponse.hpp>
#include <alibabacloud/models/DescribeUserAssetRequest.hpp>
#include <alibabacloud/models/DescribeUserAssetResponseBody.hpp>
#include <alibabacloud/models/DescribeUserAssetResponse.hpp>
#include <alibabacloud/models/DescribeUserEventTrendRequest.hpp>
#include <alibabacloud/models/DescribeUserEventTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEventTrendResponse.hpp>
#include <alibabacloud/models/DescribeUserEventTypeRequest.hpp>
#include <alibabacloud/models/DescribeUserEventTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeUserEventTypeResponse.hpp>
#include <alibabacloud/models/DescribeUserLogFieldConfigRequest.hpp>
#include <alibabacloud/models/DescribeUserLogFieldConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeUserLogFieldConfigResponse.hpp>
#include <alibabacloud/models/DescribeUserSlsLogRegionsRequest.hpp>
#include <alibabacloud/models/DescribeUserSlsLogRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeUserSlsLogRegionsResponse.hpp>
#include <alibabacloud/models/DescribeUserWafLogStatusRequest.hpp>
#include <alibabacloud/models/DescribeUserWafLogStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeUserWafLogStatusResponse.hpp>
#include <alibabacloud/models/DescribeVerifyContentRequest.hpp>
#include <alibabacloud/models/DescribeVerifyContentResponseBody.hpp>
#include <alibabacloud/models/DescribeVerifyContentResponse.hpp>
#include <alibabacloud/models/DescribeVisitTopIpRequest.hpp>
#include <alibabacloud/models/DescribeVisitTopIpResponseBody.hpp>
#include <alibabacloud/models/DescribeVisitTopIpResponse.hpp>
#include <alibabacloud/models/DescribeVisitUasRequest.hpp>
#include <alibabacloud/models/DescribeVisitUasResponseBody.hpp>
#include <alibabacloud/models/DescribeVisitUasResponse.hpp>
#include <alibabacloud/models/DescribeWafSourceIpSegmentRequest.hpp>
#include <alibabacloud/models/DescribeWafSourceIpSegmentResponseBody.hpp>
#include <alibabacloud/models/DescribeWafSourceIpSegmentResponse.hpp>
#include <alibabacloud/models/InitializeWafOperationRoleRequest.hpp>
#include <alibabacloud/models/InitializeWafOperationRoleResponseBody.hpp>
#include <alibabacloud/models/InitializeWafOperationRoleResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/ModifyApisecAbnormalsRequest.hpp>
#include <alibabacloud/models/ModifyApisecAbnormalsResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecAbnormalsResponse.hpp>
#include <alibabacloud/models/ModifyApisecApiResourceRequest.hpp>
#include <alibabacloud/models/ModifyApisecApiResourceResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecApiResourceResponse.hpp>
#include <alibabacloud/models/ModifyApisecEventsRequest.hpp>
#include <alibabacloud/models/ModifyApisecEventsResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecEventsResponse.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryRequest.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryResponse.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryStatusRequest.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecLogDeliveryStatusResponse.hpp>
#include <alibabacloud/models/ModifyApisecModuleStatusRequest.hpp>
#include <alibabacloud/models/ModifyApisecModuleStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecModuleStatusResponse.hpp>
#include <alibabacloud/models/ModifyApisecStatusRequest.hpp>
#include <alibabacloud/models/ModifyApisecStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyApisecStatusResponse.hpp>
#include <alibabacloud/models/ModifyCloudResourceRequest.hpp>
#include <alibabacloud/models/ModifyCloudResourceShrinkRequest.hpp>
#include <alibabacloud/models/ModifyCloudResourceResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudResourceResponse.hpp>
#include <alibabacloud/models/ModifyCloudResourceCertRequest.hpp>
#include <alibabacloud/models/ModifyCloudResourceCertResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudResourceCertResponse.hpp>
#include <alibabacloud/models/ModifyDefaultHttpsRequest.hpp>
#include <alibabacloud/models/ModifyDefaultHttpsResponseBody.hpp>
#include <alibabacloud/models/ModifyDefaultHttpsResponse.hpp>
#include <alibabacloud/models/ModifyDefenseResourceGroupRequest.hpp>
#include <alibabacloud/models/ModifyDefenseResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseResourceGroupResponse.hpp>
#include <alibabacloud/models/ModifyDefenseResourceXffRequest.hpp>
#include <alibabacloud/models/ModifyDefenseResourceXffResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseResourceXffResponse.hpp>
#include <alibabacloud/models/ModifyDefenseRuleRequest.hpp>
#include <alibabacloud/models/ModifyDefenseRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseRuleResponse.hpp>
#include <alibabacloud/models/ModifyDefenseRuleCacheRequest.hpp>
#include <alibabacloud/models/ModifyDefenseRuleCacheResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseRuleCacheResponse.hpp>
#include <alibabacloud/models/ModifyDefenseRuleStatusRequest.hpp>
#include <alibabacloud/models/ModifyDefenseRuleStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseRuleStatusResponse.hpp>
#include <alibabacloud/models/ModifyDefenseSceneConfigRequest.hpp>
#include <alibabacloud/models/ModifyDefenseSceneConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseSceneConfigResponse.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateRequest.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateResponse.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateStatusRequest.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyDefenseTemplateStatusResponse.hpp>
#include <alibabacloud/models/ModifyDomainRequest.hpp>
#include <alibabacloud/models/ModifyDomainShrinkRequest.hpp>
#include <alibabacloud/models/ModifyDomainResponseBody.hpp>
#include <alibabacloud/models/ModifyDomainResponse.hpp>
#include <alibabacloud/models/ModifyDomainCertRequest.hpp>
#include <alibabacloud/models/ModifyDomainCertResponseBody.hpp>
#include <alibabacloud/models/ModifyDomainCertResponse.hpp>
#include <alibabacloud/models/ModifyDomainPunishStatusRequest.hpp>
#include <alibabacloud/models/ModifyDomainPunishStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyDomainPunishStatusResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterBypassStatusRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterBypassStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterBypassStatusResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterRuleRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudClusterRuleResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupExpansionServerRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupExpansionServerResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupExpansionServerResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupShrinkServerRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupShrinkServerResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudGroupShrinkServerResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudSdkPullinStatusRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudSdkPullinStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudSdkPullinStatusResponse.hpp>
#include <alibabacloud/models/ModifyHybridCloudServerRequest.hpp>
#include <alibabacloud/models/ModifyHybridCloudServerResponseBody.hpp>
#include <alibabacloud/models/ModifyHybridCloudServerResponse.hpp>
#include <alibabacloud/models/ModifyLogDeliveryConfigRequest.hpp>
#include <alibabacloud/models/ModifyLogDeliveryConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyLogDeliveryConfigResponse.hpp>
#include <alibabacloud/models/ModifyMajorProtectionBlackIpRequest.hpp>
#include <alibabacloud/models/ModifyMajorProtectionBlackIpResponseBody.hpp>
#include <alibabacloud/models/ModifyMajorProtectionBlackIpResponse.hpp>
#include <alibabacloud/models/ModifyMemberAccountRequest.hpp>
#include <alibabacloud/models/ModifyMemberAccountResponseBody.hpp>
#include <alibabacloud/models/ModifyMemberAccountResponse.hpp>
#include <alibabacloud/models/ModifyPauseProtectionStatusRequest.hpp>
#include <alibabacloud/models/ModifyPauseProtectionStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyPauseProtectionStatusResponse.hpp>
#include <alibabacloud/models/ModifyResourceLogDeliveryStatusRequest.hpp>
#include <alibabacloud/models/ModifyResourceLogDeliveryStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceLogDeliveryStatusResponse.hpp>
#include <alibabacloud/models/ModifyResourceLogFieldConfigRequest.hpp>
#include <alibabacloud/models/ModifyResourceLogFieldConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceLogFieldConfigResponse.hpp>
#include <alibabacloud/models/ModifyResourceLogStatusRequest.hpp>
#include <alibabacloud/models/ModifyResourceLogStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceLogStatusResponse.hpp>
#include <alibabacloud/models/ModifyTemplateResourcesRequest.hpp>
#include <alibabacloud/models/ModifyTemplateResourcesResponseBody.hpp>
#include <alibabacloud/models/ModifyTemplateResourcesResponse.hpp>
#include <alibabacloud/models/ModifyUserLogFieldConfigRequest.hpp>
#include <alibabacloud/models/ModifyUserLogFieldConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyUserLogFieldConfigResponse.hpp>
#include <alibabacloud/models/ModifyUserWafLogStatusRequest.hpp>
#include <alibabacloud/models/ModifyUserWafLogStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyUserWafLogStatusResponse.hpp>
#include <alibabacloud/models/ReCreateCloudResourceRequest.hpp>
#include <alibabacloud/models/ReCreateCloudResourceResponseBody.hpp>
#include <alibabacloud/models/ReCreateCloudResourceResponse.hpp>
#include <alibabacloud/models/ReleaseInstanceRequest.hpp>
#include <alibabacloud/models/ReleaseInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseInstanceResponse.hpp>
#include <alibabacloud/models/SyncProductInstanceRequest.hpp>
#include <alibabacloud/models/SyncProductInstanceResponseBody.hpp>
#include <alibabacloud/models/SyncProductInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/VerifyDomainOwnerRequest.hpp>
#include <alibabacloud/models/VerifyDomainOwnerResponseBody.hpp>
#include <alibabacloud/models/VerifyDomainOwnerResponse.hpp>

#endif
