// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_VERVERICA20220718MODEL_HPP_
#define ALIBABACLOUD_VERVERICA20220718MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/MetadataInfo.hpp>
#include <alibabacloud/models/TableColumn.hpp>
#include <alibabacloud/models/PrimaryKey.hpp>
#include <alibabacloud/models/WatermarkSpec.hpp>
#include <alibabacloud/models/Schema.hpp>
#include <alibabacloud/models/AiModel.hpp>
#include <alibabacloud/models/JarArtifact.hpp>
#include <alibabacloud/models/PythonArtifact.hpp>
#include <alibabacloud/models/SqlArtifact.hpp>
#include <alibabacloud/models/Artifact.hpp>
#include <alibabacloud/models/ValidationErrorDetails.hpp>
#include <alibabacloud/models/ValidateStatementResult.hpp>
#include <alibabacloud/models/AsyncDraftDeployResult.hpp>
#include <alibabacloud/models/AsyncResourcePlanOperationResult.hpp>
#include <alibabacloud/models/BasicResourceSettingSpec.hpp>
#include <alibabacloud/models/BasicResourceSetting.hpp>
#include <alibabacloud/models/BatchResourceSetting.hpp>
#include <alibabacloud/models/BriefDeploymentTarget.hpp>
#include <alibabacloud/models/ExpertResourceSetting.hpp>
#include <alibabacloud/models/StreamingResourceSetting.hpp>
#include <alibabacloud/models/BriefResourceSetting.hpp>
#include <alibabacloud/models/Catalog.hpp>
#include <alibabacloud/models/Cell.hpp>
#include <alibabacloud/models/Property.hpp>
#include <alibabacloud/models/Connector.hpp>
#include <alibabacloud/models/UdfClass.hpp>
#include <alibabacloud/models/UdfArtifact.hpp>
#include <alibabacloud/models/CreateUdfArtifactResult.hpp>
#include <alibabacloud/models/Database.hpp>
#include <alibabacloud/models/DeleteUdfArtifactResult.hpp>
#include <alibabacloud/models/JobSummary.hpp>
#include <alibabacloud/models/LocalVariable.hpp>
#include <alibabacloud/models/Log4jLogger.hpp>
#include <alibabacloud/models/LogReservePolicy.hpp>
#include <alibabacloud/models/Logging.hpp>
#include <alibabacloud/models/Deployment.hpp>
#include <alibabacloud/models/Lock.hpp>
#include <alibabacloud/models/DeploymentDraft.hpp>
#include <alibabacloud/models/DeploymentRestoreStrategy.hpp>
#include <alibabacloud/models/ResourceSpec.hpp>
#include <alibabacloud/models/ResourceQuota.hpp>
#include <alibabacloud/models/DeploymentTarget.hpp>
#include <alibabacloud/models/DraftDeployParams.hpp>
#include <alibabacloud/models/DraftDeployResult.hpp>
#include <alibabacloud/models/Relation.hpp>
#include <alibabacloud/models/Edge.hpp>
#include <alibabacloud/models/EditableNamespace.hpp>
#include <alibabacloud/models/EngineVersionSupportedFeatures.hpp>
#include <alibabacloud/models/EngineVersionMetadata.hpp>
#include <alibabacloud/models/EngineVersionMetadataIndex.hpp>
#include <alibabacloud/models/ErrorDetails.hpp>
#include <alibabacloud/models/Event.hpp>
#include <alibabacloud/models/Row.hpp>
#include <alibabacloud/models/RowUpdate.hpp>
#include <alibabacloud/models/TableResult.hpp>
#include <alibabacloud/models/FetchResult.hpp>
#include <alibabacloud/models/SubFolder.hpp>
#include <alibabacloud/models/Folder.hpp>
#include <alibabacloud/models/Function.hpp>
#include <alibabacloud/models/GetLineageInfoParams.hpp>
#include <alibabacloud/models/GetPreSignedUrlForObjectResult.hpp>
#include <alibabacloud/models/HotUpdateJobFailureInfo.hpp>
#include <alibabacloud/models/RescaleJobParam.hpp>
#include <alibabacloud/models/UpdateJobConfigParam.hpp>
#include <alibabacloud/models/HotUpdateJobParams.hpp>
#include <alibabacloud/models/HotUpdateJobStatus.hpp>
#include <alibabacloud/models/HotUpdateJobResult.hpp>
#include <alibabacloud/models/JobMetric.hpp>
#include <alibabacloud/models/JobFailure.hpp>
#include <alibabacloud/models/JobStatusRunning.hpp>
#include <alibabacloud/models/JobStatus.hpp>
#include <alibabacloud/models/Job.hpp>
#include <alibabacloud/models/JobDiagnosisSymptom.hpp>
#include <alibabacloud/models/JobDiagnosisSymptoms.hpp>
#include <alibabacloud/models/JobDiagnosis.hpp>
#include <alibabacloud/models/JobInfo.hpp>
#include <alibabacloud/models/JobStartParameters.hpp>
#include <alibabacloud/models/LineageColumn.hpp>
#include <alibabacloud/models/LineageTable.hpp>
#include <alibabacloud/models/Node.hpp>
#include <alibabacloud/models/LineageInfo.hpp>
#include <alibabacloud/models/Member.hpp>
#include <alibabacloud/models/NodeExecutionContextDto.hpp>
#include <alibabacloud/models/NodeExecutionStatusDto.hpp>
#include <alibabacloud/models/PeriodicSchedulingPolicy.hpp>
#include <alibabacloud/models/Resource.hpp>
#include <alibabacloud/models/SavepointFailure.hpp>
#include <alibabacloud/models/SavepointStatus.hpp>
#include <alibabacloud/models/Savepoint.hpp>
#include <alibabacloud/models/ScheduledPlan.hpp>
#include <alibabacloud/models/ScheduledPlanAppliedInfo.hpp>
#include <alibabacloud/models/ScheduledPlanExecutedStatus.hpp>
#include <alibabacloud/models/ScheduledPlanExecutedInfo.hpp>
#include <alibabacloud/models/SessionClusterFailureInfo.hpp>
#include <alibabacloud/models/SessionClusterRunningInfo.hpp>
#include <alibabacloud/models/SessionClusterStatus.hpp>
#include <alibabacloud/models/SessionCluster.hpp>
#include <alibabacloud/models/SqlStatementExecuteResult.hpp>
#include <alibabacloud/models/SqlStatementValidationResult.hpp>
#include <alibabacloud/models/SqlStatementWithContext.hpp>
#include <alibabacloud/models/StartJobRequestBody.hpp>
#include <alibabacloud/models/StopJobRequestBody.hpp>
#include <alibabacloud/models/TableSchema.hpp>
#include <alibabacloud/models/SubmitPreview.hpp>
#include <alibabacloud/models/SubmitPreviewResult.hpp>
#include <alibabacloud/models/Table.hpp>
#include <alibabacloud/models/TableMeta.hpp>
#include <alibabacloud/models/UdfFunction.hpp>
#include <alibabacloud/models/UpdateUdfArtifactResult.hpp>
#include <alibabacloud/models/Variable.hpp>
#include <alibabacloud/models/ApplyScheduledPlanHeaders.hpp>
#include <alibabacloud/models/ApplyScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/ApplyScheduledPlanResponse.hpp>
#include <alibabacloud/models/CancelSqlPreviewHeaders.hpp>
#include <alibabacloud/models/CancelSqlPreviewRequest.hpp>
#include <alibabacloud/models/CancelSqlPreviewResponseBody.hpp>
#include <alibabacloud/models/CancelSqlPreviewResponse.hpp>
#include <alibabacloud/models/CreateDeploymentHeaders.hpp>
#include <alibabacloud/models/CreateDeploymentRequest.hpp>
#include <alibabacloud/models/CreateDeploymentResponseBody.hpp>
#include <alibabacloud/models/CreateDeploymentResponse.hpp>
#include <alibabacloud/models/CreateDeploymentDraftHeaders.hpp>
#include <alibabacloud/models/CreateDeploymentDraftRequest.hpp>
#include <alibabacloud/models/CreateDeploymentDraftResponseBody.hpp>
#include <alibabacloud/models/CreateDeploymentDraftResponse.hpp>
#include <alibabacloud/models/CreateDeploymentTargetHeaders.hpp>
#include <alibabacloud/models/CreateDeploymentTargetRequest.hpp>
#include <alibabacloud/models/CreateDeploymentTargetResponseBody.hpp>
#include <alibabacloud/models/CreateDeploymentTargetResponse.hpp>
#include <alibabacloud/models/CreateDeploymentTargetV2Headers.hpp>
#include <alibabacloud/models/CreateDeploymentTargetV2Request.hpp>
#include <alibabacloud/models/CreateDeploymentTargetV2ResponseBody.hpp>
#include <alibabacloud/models/CreateDeploymentTargetV2Response.hpp>
#include <alibabacloud/models/CreateFolderHeaders.hpp>
#include <alibabacloud/models/CreateFolderRequest.hpp>
#include <alibabacloud/models/CreateFolderResponseBody.hpp>
#include <alibabacloud/models/CreateFolderResponse.hpp>
#include <alibabacloud/models/CreateMemberHeaders.hpp>
#include <alibabacloud/models/CreateMemberRequest.hpp>
#include <alibabacloud/models/CreateMemberResponseBody.hpp>
#include <alibabacloud/models/CreateMemberResponse.hpp>
#include <alibabacloud/models/CreateSavepointHeaders.hpp>
#include <alibabacloud/models/CreateSavepointRequest.hpp>
#include <alibabacloud/models/CreateSavepointResponseBody.hpp>
#include <alibabacloud/models/CreateSavepointResponse.hpp>
#include <alibabacloud/models/CreateScheduledPlanHeaders.hpp>
#include <alibabacloud/models/CreateScheduledPlanRequest.hpp>
#include <alibabacloud/models/CreateScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/CreateScheduledPlanResponse.hpp>
#include <alibabacloud/models/CreateSessionClusterHeaders.hpp>
#include <alibabacloud/models/CreateSessionClusterRequest.hpp>
#include <alibabacloud/models/CreateSessionClusterResponseBody.hpp>
#include <alibabacloud/models/CreateSessionClusterResponse.hpp>
#include <alibabacloud/models/CreateUdfArtifactHeaders.hpp>
#include <alibabacloud/models/CreateUdfArtifactRequest.hpp>
#include <alibabacloud/models/CreateUdfArtifactResponseBody.hpp>
#include <alibabacloud/models/CreateUdfArtifactResponse.hpp>
#include <alibabacloud/models/CreateVariableHeaders.hpp>
#include <alibabacloud/models/CreateVariableRequest.hpp>
#include <alibabacloud/models/CreateVariableResponseBody.hpp>
#include <alibabacloud/models/CreateVariableResponse.hpp>
#include <alibabacloud/models/DeleteCustomConnectorHeaders.hpp>
#include <alibabacloud/models/DeleteCustomConnectorResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomConnectorResponse.hpp>
#include <alibabacloud/models/DeleteDeploymentHeaders.hpp>
#include <alibabacloud/models/DeleteDeploymentResponseBody.hpp>
#include <alibabacloud/models/DeleteDeploymentResponse.hpp>
#include <alibabacloud/models/DeleteDeploymentDraftHeaders.hpp>
#include <alibabacloud/models/DeleteDeploymentDraftResponseBody.hpp>
#include <alibabacloud/models/DeleteDeploymentDraftResponse.hpp>
#include <alibabacloud/models/DeleteDeploymentTargetHeaders.hpp>
#include <alibabacloud/models/DeleteDeploymentTargetResponseBody.hpp>
#include <alibabacloud/models/DeleteDeploymentTargetResponse.hpp>
#include <alibabacloud/models/DeleteFolderHeaders.hpp>
#include <alibabacloud/models/DeleteFolderResponseBody.hpp>
#include <alibabacloud/models/DeleteFolderResponse.hpp>
#include <alibabacloud/models/DeleteJobHeaders.hpp>
#include <alibabacloud/models/DeleteJobResponseBody.hpp>
#include <alibabacloud/models/DeleteJobResponse.hpp>
#include <alibabacloud/models/DeleteMemberHeaders.hpp>
#include <alibabacloud/models/DeleteMemberResponseBody.hpp>
#include <alibabacloud/models/DeleteMemberResponse.hpp>
#include <alibabacloud/models/DeleteSavepointHeaders.hpp>
#include <alibabacloud/models/DeleteSavepointResponseBody.hpp>
#include <alibabacloud/models/DeleteSavepointResponse.hpp>
#include <alibabacloud/models/DeleteScheduledPlanHeaders.hpp>
#include <alibabacloud/models/DeleteScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteScheduledPlanResponse.hpp>
#include <alibabacloud/models/DeleteSessionClusterHeaders.hpp>
#include <alibabacloud/models/DeleteSessionClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteSessionClusterResponse.hpp>
#include <alibabacloud/models/DeleteUdfArtifactHeaders.hpp>
#include <alibabacloud/models/DeleteUdfArtifactResponseBody.hpp>
#include <alibabacloud/models/DeleteUdfArtifactResponse.hpp>
#include <alibabacloud/models/DeleteUdfFunctionHeaders.hpp>
#include <alibabacloud/models/DeleteUdfFunctionRequest.hpp>
#include <alibabacloud/models/DeleteUdfFunctionResponseBody.hpp>
#include <alibabacloud/models/DeleteUdfFunctionResponse.hpp>
#include <alibabacloud/models/DeleteVariableHeaders.hpp>
#include <alibabacloud/models/DeleteVariableResponseBody.hpp>
#include <alibabacloud/models/DeleteVariableResponse.hpp>
#include <alibabacloud/models/DeployDeploymentDraftAsyncHeaders.hpp>
#include <alibabacloud/models/DeployDeploymentDraftAsyncRequest.hpp>
#include <alibabacloud/models/DeployDeploymentDraftAsyncResponseBody.hpp>
#include <alibabacloud/models/DeployDeploymentDraftAsyncResponse.hpp>
#include <alibabacloud/models/ExecuteSqlStatementHeaders.hpp>
#include <alibabacloud/models/ExecuteSqlStatementRequest.hpp>
#include <alibabacloud/models/ExecuteSqlStatementResponseBody.hpp>
#include <alibabacloud/models/ExecuteSqlStatementResponse.hpp>
#include <alibabacloud/models/FetchSqlPreviewResultsHeaders.hpp>
#include <alibabacloud/models/FetchSqlPreviewResultsRequest.hpp>
#include <alibabacloud/models/FetchSqlPreviewResultsResponseBody.hpp>
#include <alibabacloud/models/FetchSqlPreviewResultsResponse.hpp>
#include <alibabacloud/models/FlinkApiProxyHeaders.hpp>
#include <alibabacloud/models/FlinkApiProxyRequest.hpp>
#include <alibabacloud/models/FlinkApiProxyResponseBody.hpp>
#include <alibabacloud/models/FlinkApiProxyResponse.hpp>
#include <alibabacloud/models/GenerateResourcePlanWithFlinkConfAsyncHeaders.hpp>
#include <alibabacloud/models/GenerateResourcePlanWithFlinkConfAsyncRequest.hpp>
#include <alibabacloud/models/GenerateResourcePlanWithFlinkConfAsyncResponseBody.hpp>
#include <alibabacloud/models/GenerateResourcePlanWithFlinkConfAsyncResponse.hpp>
#include <alibabacloud/models/GetAppliedScheduledPlanHeaders.hpp>
#include <alibabacloud/models/GetAppliedScheduledPlanRequest.hpp>
#include <alibabacloud/models/GetAppliedScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/GetAppliedScheduledPlanResponse.hpp>
#include <alibabacloud/models/GetCatalogsHeaders.hpp>
#include <alibabacloud/models/GetCatalogsRequest.hpp>
#include <alibabacloud/models/GetCatalogsResponseBody.hpp>
#include <alibabacloud/models/GetCatalogsResponse.hpp>
#include <alibabacloud/models/GetDatabasesHeaders.hpp>
#include <alibabacloud/models/GetDatabasesRequest.hpp>
#include <alibabacloud/models/GetDatabasesResponseBody.hpp>
#include <alibabacloud/models/GetDatabasesResponse.hpp>
#include <alibabacloud/models/GetDeployDeploymentDraftResultHeaders.hpp>
#include <alibabacloud/models/GetDeployDeploymentDraftResultResponseBody.hpp>
#include <alibabacloud/models/GetDeployDeploymentDraftResultResponse.hpp>
#include <alibabacloud/models/GetDeploymentHeaders.hpp>
#include <alibabacloud/models/GetDeploymentResponseBody.hpp>
#include <alibabacloud/models/GetDeploymentResponse.hpp>
#include <alibabacloud/models/GetDeploymentDraftHeaders.hpp>
#include <alibabacloud/models/GetDeploymentDraftResponseBody.hpp>
#include <alibabacloud/models/GetDeploymentDraftResponse.hpp>
#include <alibabacloud/models/GetDeploymentDraftLockHeaders.hpp>
#include <alibabacloud/models/GetDeploymentDraftLockRequest.hpp>
#include <alibabacloud/models/GetDeploymentDraftLockResponseBody.hpp>
#include <alibabacloud/models/GetDeploymentDraftLockResponse.hpp>
#include <alibabacloud/models/GetEventsHeaders.hpp>
#include <alibabacloud/models/GetEventsRequest.hpp>
#include <alibabacloud/models/GetEventsResponseBody.hpp>
#include <alibabacloud/models/GetEventsResponse.hpp>
#include <alibabacloud/models/GetFolderHeaders.hpp>
#include <alibabacloud/models/GetFolderRequest.hpp>
#include <alibabacloud/models/GetFolderResponseBody.hpp>
#include <alibabacloud/models/GetFolderResponse.hpp>
#include <alibabacloud/models/GetGenerateResourcePlanResultHeaders.hpp>
#include <alibabacloud/models/GetGenerateResourcePlanResultResponseBody.hpp>
#include <alibabacloud/models/GetGenerateResourcePlanResultResponse.hpp>
#include <alibabacloud/models/GetHotUpdateJobResultHeaders.hpp>
#include <alibabacloud/models/GetHotUpdateJobResultResponseBody.hpp>
#include <alibabacloud/models/GetHotUpdateJobResultResponse.hpp>
#include <alibabacloud/models/GetJobHeaders.hpp>
#include <alibabacloud/models/GetJobResponseBody.hpp>
#include <alibabacloud/models/GetJobResponse.hpp>
#include <alibabacloud/models/GetJobDiagnosisHeaders.hpp>
#include <alibabacloud/models/GetJobDiagnosisResponseBody.hpp>
#include <alibabacloud/models/GetJobDiagnosisResponse.hpp>
#include <alibabacloud/models/GetLatestJobStartLogHeaders.hpp>
#include <alibabacloud/models/GetLatestJobStartLogResponseBody.hpp>
#include <alibabacloud/models/GetLatestJobStartLogResponse.hpp>
#include <alibabacloud/models/GetLineageInfoHeaders.hpp>
#include <alibabacloud/models/GetLineageInfoRequest.hpp>
#include <alibabacloud/models/GetLineageInfoResponseBody.hpp>
#include <alibabacloud/models/GetLineageInfoResponse.hpp>
#include <alibabacloud/models/GetMemberHeaders.hpp>
#include <alibabacloud/models/GetMemberResponseBody.hpp>
#include <alibabacloud/models/GetMemberResponse.hpp>
#include <alibabacloud/models/GetPreSignedUrlForPutObjectHeaders.hpp>
#include <alibabacloud/models/GetPreSignedUrlForPutObjectRequest.hpp>
#include <alibabacloud/models/GetPreSignedUrlForPutObjectResponseBody.hpp>
#include <alibabacloud/models/GetPreSignedUrlForPutObjectResponse.hpp>
#include <alibabacloud/models/GetSavepointHeaders.hpp>
#include <alibabacloud/models/GetSavepointResponseBody.hpp>
#include <alibabacloud/models/GetSavepointResponse.hpp>
#include <alibabacloud/models/GetSessionClusterHeaders.hpp>
#include <alibabacloud/models/GetSessionClusterResponseBody.hpp>
#include <alibabacloud/models/GetSessionClusterResponse.hpp>
#include <alibabacloud/models/GetTablesHeaders.hpp>
#include <alibabacloud/models/GetTablesRequest.hpp>
#include <alibabacloud/models/GetTablesResponseBody.hpp>
#include <alibabacloud/models/GetTablesResponse.hpp>
#include <alibabacloud/models/GetUdfArtifactsHeaders.hpp>
#include <alibabacloud/models/GetUdfArtifactsRequest.hpp>
#include <alibabacloud/models/GetUdfArtifactsResponseBody.hpp>
#include <alibabacloud/models/GetUdfArtifactsResponse.hpp>
#include <alibabacloud/models/HotUpdateJobHeaders.hpp>
#include <alibabacloud/models/HotUpdateJobResponseBody.hpp>
#include <alibabacloud/models/HotUpdateJobResponse.hpp>
#include <alibabacloud/models/ListCustomConnectorsHeaders.hpp>
#include <alibabacloud/models/ListCustomConnectorsResponseBody.hpp>
#include <alibabacloud/models/ListCustomConnectorsResponse.hpp>
#include <alibabacloud/models/ListDeploymentDraftsHeaders.hpp>
#include <alibabacloud/models/ListDeploymentDraftsRequest.hpp>
#include <alibabacloud/models/ListDeploymentDraftsResponseBody.hpp>
#include <alibabacloud/models/ListDeploymentDraftsResponse.hpp>
#include <alibabacloud/models/ListDeploymentTargetsHeaders.hpp>
#include <alibabacloud/models/ListDeploymentTargetsRequest.hpp>
#include <alibabacloud/models/ListDeploymentTargetsResponseBody.hpp>
#include <alibabacloud/models/ListDeploymentTargetsResponse.hpp>
#include <alibabacloud/models/ListDeploymentsHeaders.hpp>
#include <alibabacloud/models/ListDeploymentsRequest.hpp>
#include <alibabacloud/models/ListDeploymentsResponseBody.hpp>
#include <alibabacloud/models/ListDeploymentsResponse.hpp>
#include <alibabacloud/models/ListEditableNamespaceRequest.hpp>
#include <alibabacloud/models/ListEditableNamespaceResponseBody.hpp>
#include <alibabacloud/models/ListEditableNamespaceResponse.hpp>
#include <alibabacloud/models/ListEngineVersionMetadataHeaders.hpp>
#include <alibabacloud/models/ListEngineVersionMetadataResponseBody.hpp>
#include <alibabacloud/models/ListEngineVersionMetadataResponse.hpp>
#include <alibabacloud/models/ListJobsHeaders.hpp>
#include <alibabacloud/models/ListJobsRequest.hpp>
#include <alibabacloud/models/ListJobsResponseBody.hpp>
#include <alibabacloud/models/ListJobsResponse.hpp>
#include <alibabacloud/models/ListMembersHeaders.hpp>
#include <alibabacloud/models/ListMembersRequest.hpp>
#include <alibabacloud/models/ListMembersResponseBody.hpp>
#include <alibabacloud/models/ListMembersResponse.hpp>
#include <alibabacloud/models/ListSavepointsHeaders.hpp>
#include <alibabacloud/models/ListSavepointsRequest.hpp>
#include <alibabacloud/models/ListSavepointsResponseBody.hpp>
#include <alibabacloud/models/ListSavepointsResponse.hpp>
#include <alibabacloud/models/ListScheduledPlanHeaders.hpp>
#include <alibabacloud/models/ListScheduledPlanRequest.hpp>
#include <alibabacloud/models/ListScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/ListScheduledPlanResponse.hpp>
#include <alibabacloud/models/ListScheduledPlanExecutedHistoryHeaders.hpp>
#include <alibabacloud/models/ListScheduledPlanExecutedHistoryRequest.hpp>
#include <alibabacloud/models/ListScheduledPlanExecutedHistoryResponseBody.hpp>
#include <alibabacloud/models/ListScheduledPlanExecutedHistoryResponse.hpp>
#include <alibabacloud/models/ListSessionClustersHeaders.hpp>
#include <alibabacloud/models/ListSessionClustersResponseBody.hpp>
#include <alibabacloud/models/ListSessionClustersResponse.hpp>
#include <alibabacloud/models/ListVariablesHeaders.hpp>
#include <alibabacloud/models/ListVariablesRequest.hpp>
#include <alibabacloud/models/ListVariablesResponseBody.hpp>
#include <alibabacloud/models/ListVariablesResponse.hpp>
#include <alibabacloud/models/RegisterCustomConnectorHeaders.hpp>
#include <alibabacloud/models/RegisterCustomConnectorRequest.hpp>
#include <alibabacloud/models/RegisterCustomConnectorResponseBody.hpp>
#include <alibabacloud/models/RegisterCustomConnectorResponse.hpp>
#include <alibabacloud/models/RegisterUdfFunctionHeaders.hpp>
#include <alibabacloud/models/RegisterUdfFunctionRequest.hpp>
#include <alibabacloud/models/RegisterUdfFunctionResponseBody.hpp>
#include <alibabacloud/models/RegisterUdfFunctionResponse.hpp>
#include <alibabacloud/models/StartJobHeaders.hpp>
#include <alibabacloud/models/StartJobRequest.hpp>
#include <alibabacloud/models/StartJobResponseBody.hpp>
#include <alibabacloud/models/StartJobResponse.hpp>
#include <alibabacloud/models/StartJobWithParamsHeaders.hpp>
#include <alibabacloud/models/StartJobWithParamsRequest.hpp>
#include <alibabacloud/models/StartJobWithParamsResponseBody.hpp>
#include <alibabacloud/models/StartJobWithParamsResponse.hpp>
#include <alibabacloud/models/StartSessionClusterHeaders.hpp>
#include <alibabacloud/models/StartSessionClusterResponseBody.hpp>
#include <alibabacloud/models/StartSessionClusterResponse.hpp>
#include <alibabacloud/models/StopApplyScheduledPlanHeaders.hpp>
#include <alibabacloud/models/StopApplyScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/StopApplyScheduledPlanResponse.hpp>
#include <alibabacloud/models/StopJobHeaders.hpp>
#include <alibabacloud/models/StopJobRequest.hpp>
#include <alibabacloud/models/StopJobResponseBody.hpp>
#include <alibabacloud/models/StopJobResponse.hpp>
#include <alibabacloud/models/StopSessionClusterHeaders.hpp>
#include <alibabacloud/models/StopSessionClusterResponseBody.hpp>
#include <alibabacloud/models/StopSessionClusterResponse.hpp>
#include <alibabacloud/models/SubmitSqlPreviewHeaders.hpp>
#include <alibabacloud/models/SubmitSqlPreviewRequest.hpp>
#include <alibabacloud/models/SubmitSqlPreviewResponseBody.hpp>
#include <alibabacloud/models/SubmitSqlPreviewResponse.hpp>
#include <alibabacloud/models/UpdateDeploymentHeaders.hpp>
#include <alibabacloud/models/UpdateDeploymentRequest.hpp>
#include <alibabacloud/models/UpdateDeploymentResponseBody.hpp>
#include <alibabacloud/models/UpdateDeploymentResponse.hpp>
#include <alibabacloud/models/UpdateDeploymentDraftHeaders.hpp>
#include <alibabacloud/models/UpdateDeploymentDraftRequest.hpp>
#include <alibabacloud/models/UpdateDeploymentDraftResponseBody.hpp>
#include <alibabacloud/models/UpdateDeploymentDraftResponse.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetHeaders.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetRequest.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetResponseBody.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetResponse.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetV2Headers.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetV2Request.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetV2ResponseBody.hpp>
#include <alibabacloud/models/UpdateDeploymentTargetV2Response.hpp>
#include <alibabacloud/models/UpdateFolderHeaders.hpp>
#include <alibabacloud/models/UpdateFolderRequest.hpp>
#include <alibabacloud/models/UpdateFolderResponseBody.hpp>
#include <alibabacloud/models/UpdateFolderResponse.hpp>
#include <alibabacloud/models/UpdateMemberHeaders.hpp>
#include <alibabacloud/models/UpdateMemberRequest.hpp>
#include <alibabacloud/models/UpdateMemberResponseBody.hpp>
#include <alibabacloud/models/UpdateMemberResponse.hpp>
#include <alibabacloud/models/UpdateScheduledPlanHeaders.hpp>
#include <alibabacloud/models/UpdateScheduledPlanRequest.hpp>
#include <alibabacloud/models/UpdateScheduledPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateScheduledPlanResponse.hpp>
#include <alibabacloud/models/UpdateSessionClusterHeaders.hpp>
#include <alibabacloud/models/UpdateSessionClusterRequest.hpp>
#include <alibabacloud/models/UpdateSessionClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateSessionClusterResponse.hpp>
#include <alibabacloud/models/UpdateUdfArtifactHeaders.hpp>
#include <alibabacloud/models/UpdateUdfArtifactRequest.hpp>
#include <alibabacloud/models/UpdateUdfArtifactResponseBody.hpp>
#include <alibabacloud/models/UpdateUdfArtifactResponse.hpp>
#include <alibabacloud/models/UpdateVariableHeaders.hpp>
#include <alibabacloud/models/UpdateVariableRequest.hpp>
#include <alibabacloud/models/UpdateVariableResponseBody.hpp>
#include <alibabacloud/models/UpdateVariableResponse.hpp>
#include <alibabacloud/models/ValidateSqlStatementHeaders.hpp>
#include <alibabacloud/models/ValidateSqlStatementRequest.hpp>
#include <alibabacloud/models/ValidateSqlStatementResponseBody.hpp>
#include <alibabacloud/models/ValidateSqlStatementResponse.hpp>
#include <alibabacloud/models/DeployDeploymentDraftAsyncResponseBodyData.hpp>
#include <alibabacloud/models/GenerateResourcePlanWithFlinkConfAsyncResponseBodyData.hpp>
#include <alibabacloud/models/ListEditableNamespaceResponseBodyData.hpp>

#endif
