// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ALIGENIEIAP_1_0MODEL_HPP_
#define ALIBABACLOUD_ALIGENIEIAP_1_0MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AppUseTimeReportHeaders.hpp>
#include <alibabacloud/models/AppUseTimeReportRequest.hpp>
#include <alibabacloud/models/AppUseTimeReportShrinkRequest.hpp>
#include <alibabacloud/models/AppUseTimeReportResponseBody.hpp>
#include <alibabacloud/models/AppUseTimeReportResponse.hpp>
#include <alibabacloud/models/CallBackThirdRightSendPlanHeaders.hpp>
#include <alibabacloud/models/CallBackThirdRightSendPlanRequest.hpp>
#include <alibabacloud/models/CallBackThirdRightSendPlanShrinkRequest.hpp>
#include <alibabacloud/models/CallBackThirdRightSendPlanResponseBody.hpp>
#include <alibabacloud/models/CallBackThirdRightSendPlanResponse.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanHeaders.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanRequest.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanShrinkRequest.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanResponseBody.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanResponse.hpp>
#include <alibabacloud/models/CreateReminderHeaders.hpp>
#include <alibabacloud/models/CreateReminderRequest.hpp>
#include <alibabacloud/models/CreateReminderShrinkRequest.hpp>
#include <alibabacloud/models/CreateReminderResponseBody.hpp>
#include <alibabacloud/models/CreateReminderResponse.hpp>
#include <alibabacloud/models/DeleteReminderHeaders.hpp>
#include <alibabacloud/models/DeleteReminderRequest.hpp>
#include <alibabacloud/models/DeleteReminderShrinkRequest.hpp>
#include <alibabacloud/models/DeleteReminderResponseBody.hpp>
#include <alibabacloud/models/DeleteReminderResponse.hpp>
#include <alibabacloud/models/GetAccountForAppHeaders.hpp>
#include <alibabacloud/models/GetAccountForAppRequest.hpp>
#include <alibabacloud/models/GetAccountForAppShrinkRequest.hpp>
#include <alibabacloud/models/GetAccountForAppResponseBody.hpp>
#include <alibabacloud/models/GetAccountForAppResponse.hpp>
#include <alibabacloud/models/GetBusAppConfigHeaders.hpp>
#include <alibabacloud/models/GetBusAppConfigRequest.hpp>
#include <alibabacloud/models/GetBusAppConfigShrinkRequest.hpp>
#include <alibabacloud/models/GetBusAppConfigResponseBody.hpp>
#include <alibabacloud/models/GetBusAppConfigResponse.hpp>
#include <alibabacloud/models/GetPhoneNumberHeaders.hpp>
#include <alibabacloud/models/GetPhoneNumberRequest.hpp>
#include <alibabacloud/models/GetPhoneNumberShrinkRequest.hpp>
#include <alibabacloud/models/GetPhoneNumberResponseBody.hpp>
#include <alibabacloud/models/GetPhoneNumberResponse.hpp>
#include <alibabacloud/models/GetReminderHeaders.hpp>
#include <alibabacloud/models/GetReminderRequest.hpp>
#include <alibabacloud/models/GetReminderShrinkRequest.hpp>
#include <alibabacloud/models/GetReminderResponseBody.hpp>
#include <alibabacloud/models/GetReminderResponse.hpp>
#include <alibabacloud/models/ListRemindersHeaders.hpp>
#include <alibabacloud/models/ListRemindersRequest.hpp>
#include <alibabacloud/models/ListRemindersShrinkRequest.hpp>
#include <alibabacloud/models/ListRemindersResponseBody.hpp>
#include <alibabacloud/models/ListRemindersResponse.hpp>
#include <alibabacloud/models/PullCashierHeaders.hpp>
#include <alibabacloud/models/PullCashierRequest.hpp>
#include <alibabacloud/models/PullCashierShrinkRequest.hpp>
#include <alibabacloud/models/PullCashierResponseBody.hpp>
#include <alibabacloud/models/PullCashierResponse.hpp>
#include <alibabacloud/models/PushNotificationsHeaders.hpp>
#include <alibabacloud/models/PushNotificationsRequest.hpp>
#include <alibabacloud/models/PushNotificationsShrinkRequest.hpp>
#include <alibabacloud/models/PushNotificationsResponse.hpp>
#include <alibabacloud/models/SendNotificationsHeaders.hpp>
#include <alibabacloud/models/SendNotificationsRequest.hpp>
#include <alibabacloud/models/SendNotificationsShrinkRequest.hpp>
#include <alibabacloud/models/SendNotificationsResponse.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushHeaders.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushRequest.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponseBody.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponse.hpp>
#include <alibabacloud/models/UpdateReminderHeaders.hpp>
#include <alibabacloud/models/UpdateReminderRequest.hpp>
#include <alibabacloud/models/UpdateReminderShrinkRequest.hpp>
#include <alibabacloud/models/UpdateReminderResponseBody.hpp>
#include <alibabacloud/models/UpdateReminderResponse.hpp>
#include <alibabacloud/models/VideoAppReportHeaders.hpp>
#include <alibabacloud/models/VideoAppReportRequest.hpp>
#include <alibabacloud/models/VideoAppReportShrinkRequest.hpp>
#include <alibabacloud/models/VideoAppReportResponseBody.hpp>
#include <alibabacloud/models/VideoAppReportResponse.hpp>
#include <alibabacloud/models/WakeUpAppHeaders.hpp>
#include <alibabacloud/models/WakeUpAppRequest.hpp>
#include <alibabacloud/models/WakeUpAppResponse.hpp>
#include <alibabacloud/models/AppUseTimeReportRequestDeviceInfo.hpp>
#include <alibabacloud/models/AppUseTimeReportRequestPayload.hpp>
#include <alibabacloud/models/AppUseTimeReportRequestUserInfo.hpp>
#include <alibabacloud/models/CheckThirdRightSendPlanResponseBodyRetValue.hpp>
#include <alibabacloud/models/CreateReminderRequestDeviceInfo.hpp>
#include <alibabacloud/models/CreateReminderRequestPayloadRecurrenceRule.hpp>
#include <alibabacloud/models/CreateReminderRequestPayload.hpp>
#include <alibabacloud/models/CreateReminderRequestUserInfo.hpp>
#include <alibabacloud/models/DeleteReminderRequestDeviceInfo.hpp>
#include <alibabacloud/models/DeleteReminderRequestPayload.hpp>
#include <alibabacloud/models/DeleteReminderRequestUserInfo.hpp>
#include <alibabacloud/models/GetAccountForAppRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetAccountForAppRequestPayload.hpp>
#include <alibabacloud/models/GetAccountForAppRequestUserInfo.hpp>
#include <alibabacloud/models/GetAccountForAppResponseBodyRetValue.hpp>
#include <alibabacloud/models/GetBusAppConfigRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetBusAppConfigRequestPayload.hpp>
#include <alibabacloud/models/GetBusAppConfigRequestUserInfo.hpp>
#include <alibabacloud/models/GetBusAppConfigResponseBodyRetValue.hpp>
#include <alibabacloud/models/GetPhoneNumberRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetPhoneNumberRequestUserInfo.hpp>
#include <alibabacloud/models/GetReminderRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetReminderRequestPayload.hpp>
#include <alibabacloud/models/GetReminderRequestUserInfo.hpp>
#include <alibabacloud/models/GetReminderResponseBodyModelRemindResponsesRecurrenceRule.hpp>
#include <alibabacloud/models/GetReminderResponseBodyModelRemindResponses.hpp>
#include <alibabacloud/models/GetReminderResponseBodyModel.hpp>
#include <alibabacloud/models/ListRemindersRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListRemindersRequestPayload.hpp>
#include <alibabacloud/models/ListRemindersRequestUserInfo.hpp>
#include <alibabacloud/models/ListRemindersResponseBodyModelRemindResponsesRecurrenceRule.hpp>
#include <alibabacloud/models/ListRemindersResponseBodyModelRemindResponses.hpp>
#include <alibabacloud/models/ListRemindersResponseBodyModel.hpp>
#include <alibabacloud/models/PullCashierRequestDeviceInfo.hpp>
#include <alibabacloud/models/PullCashierRequestPayload.hpp>
#include <alibabacloud/models/PullCashierRequestUserInfo.hpp>
#include <alibabacloud/models/PushNotificationsRequestNotificationUnicastRequestSendTarget.hpp>
#include <alibabacloud/models/PushNotificationsRequestNotificationUnicastRequest.hpp>
#include <alibabacloud/models/PushNotificationsRequestTenantInfo.hpp>
#include <alibabacloud/models/SendNotificationsRequestDeviceInfo.hpp>
#include <alibabacloud/models/SendNotificationsRequestNotificationUnicastRequestSendTarget.hpp>
#include <alibabacloud/models/SendNotificationsRequestNotificationUnicastRequest.hpp>
#include <alibabacloud/models/SendNotificationsRequestTenantInfo.hpp>
#include <alibabacloud/models/SendNotificationsRequestUserInfo.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponseBodyModel.hpp>
#include <alibabacloud/models/UpdateReminderRequestDeviceInfo.hpp>
#include <alibabacloud/models/UpdateReminderRequestPayloadRecurrenceRule.hpp>
#include <alibabacloud/models/UpdateReminderRequestPayload.hpp>
#include <alibabacloud/models/UpdateReminderRequestUserInfo.hpp>
#include <alibabacloud/models/VideoAppReportRequestDeviceInfo.hpp>
#include <alibabacloud/models/VideoAppReportRequestPayload.hpp>
#include <alibabacloud/models/VideoAppReportRequestUserInfo.hpp>
#include <alibabacloud/models/WakeUpAppRequestTargetInfo.hpp>

#endif
