// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_BAILIANVOICEBOT20250101MODEL_HPP_
#define ALIBABACLOUD_BAILIANVOICEBOT20250101MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BridgeWebCallRequest.hpp>
#include <alibabacloud/models/BridgeWebCallResponseBody.hpp>
#include <alibabacloud/models/BridgeWebCallResponse.hpp>
#include <alibabacloud/models/CreateApplicationRequest.hpp>
#include <alibabacloud/models/CreateApplicationResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationResponse.hpp>
#include <alibabacloud/models/CreateApplicationVersionRequest.hpp>
#include <alibabacloud/models/CreateApplicationVersionShrinkRequest.hpp>
#include <alibabacloud/models/CreateApplicationVersionResponseBody.hpp>
#include <alibabacloud/models/CreateApplicationVersionResponse.hpp>
#include <alibabacloud/models/CreateCloneVoiceRequest.hpp>
#include <alibabacloud/models/CreateCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/CreateCloneVoiceResponse.hpp>
#include <alibabacloud/models/CreateVariableRequest.hpp>
#include <alibabacloud/models/CreateVariableResponseBody.hpp>
#include <alibabacloud/models/CreateVariableResponse.hpp>
#include <alibabacloud/models/DeleteApplicationRequest.hpp>
#include <alibabacloud/models/DeleteApplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteApplicationResponse.hpp>
#include <alibabacloud/models/DeleteCloneVoiceRequest.hpp>
#include <alibabacloud/models/DeleteCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/DeleteCloneVoiceResponse.hpp>
#include <alibabacloud/models/DeleteVariableRequest.hpp>
#include <alibabacloud/models/DeleteVariableResponseBody.hpp>
#include <alibabacloud/models/DeleteVariableResponse.hpp>
#include <alibabacloud/models/GenerateFileUploadParamsRequest.hpp>
#include <alibabacloud/models/GenerateFileUploadParamsResponseBody.hpp>
#include <alibabacloud/models/GenerateFileUploadParamsResponse.hpp>
#include <alibabacloud/models/GetApplicationRequest.hpp>
#include <alibabacloud/models/GetApplicationResponseBody.hpp>
#include <alibabacloud/models/GetApplicationResponse.hpp>
#include <alibabacloud/models/GetDataChannelCredentialRequest.hpp>
#include <alibabacloud/models/GetDataChannelCredentialResponseBody.hpp>
#include <alibabacloud/models/GetDataChannelCredentialResponse.hpp>
#include <alibabacloud/models/ListApplicationsRequest.hpp>
#include <alibabacloud/models/ListApplicationsResponseBody.hpp>
#include <alibabacloud/models/ListApplicationsResponse.hpp>
#include <alibabacloud/models/ListCloneVoiceRequest.hpp>
#include <alibabacloud/models/ListCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/ListCloneVoiceResponse.hpp>
#include <alibabacloud/models/ListVariableRequest.hpp>
#include <alibabacloud/models/ListVariableResponseBody.hpp>
#include <alibabacloud/models/ListVariableResponse.hpp>
#include <alibabacloud/models/PublishApplicationVersionRequest.hpp>
#include <alibabacloud/models/PublishApplicationVersionResponseBody.hpp>
#include <alibabacloud/models/PublishApplicationVersionResponse.hpp>
#include <alibabacloud/models/UpdateApplicationRequest.hpp>
#include <alibabacloud/models/UpdateApplicationResponseBody.hpp>
#include <alibabacloud/models/UpdateApplicationResponse.hpp>
#include <alibabacloud/models/UpdateApplicationVersionRequest.hpp>
#include <alibabacloud/models/UpdateApplicationVersionShrinkRequest.hpp>
#include <alibabacloud/models/UpdateApplicationVersionResponseBody.hpp>
#include <alibabacloud/models/UpdateApplicationVersionResponse.hpp>
#include <alibabacloud/models/UpdateCloneVoiceRequest.hpp>
#include <alibabacloud/models/UpdateCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/UpdateCloneVoiceResponse.hpp>
#include <alibabacloud/models/UpdateVariableRequest.hpp>
#include <alibabacloud/models/UpdateVariableResponseBody.hpp>
#include <alibabacloud/models/UpdateVariableResponse.hpp>

#endif
