// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SCHEDULERX320240624MODEL_HPP_
#define ALIBABACLOUD_SCHEDULERX320240624MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateAppRequest.hpp>
#include <alibabacloud/models/CreateAppResponseBody.hpp>
#include <alibabacloud/models/CreateAppResponse.hpp>
#include <alibabacloud/models/CreateCalendarRequest.hpp>
#include <alibabacloud/models/CreateCalendarResponseBody.hpp>
#include <alibabacloud/models/CreateCalendarResponse.hpp>
#include <alibabacloud/models/CreateClusterRequest.hpp>
#include <alibabacloud/models/CreateClusterShrinkRequest.hpp>
#include <alibabacloud/models/CreateClusterResponseBody.hpp>
#include <alibabacloud/models/CreateClusterResponse.hpp>
#include <alibabacloud/models/CreateExecutorsRequest.hpp>
#include <alibabacloud/models/CreateExecutorsResponseBody.hpp>
#include <alibabacloud/models/CreateExecutorsResponse.hpp>
#include <alibabacloud/models/CreateJobRequest.hpp>
#include <alibabacloud/models/CreateJobShrinkRequest.hpp>
#include <alibabacloud/models/CreateJobResponseBody.hpp>
#include <alibabacloud/models/CreateJobResponse.hpp>
#include <alibabacloud/models/CreateWorkflowRequest.hpp>
#include <alibabacloud/models/CreateWorkflowResponseBody.hpp>
#include <alibabacloud/models/CreateWorkflowResponse.hpp>
#include <alibabacloud/models/DeleteAppRequest.hpp>
#include <alibabacloud/models/DeleteAppResponseBody.hpp>
#include <alibabacloud/models/DeleteAppResponse.hpp>
#include <alibabacloud/models/DeleteCalendarRequest.hpp>
#include <alibabacloud/models/DeleteCalendarResponseBody.hpp>
#include <alibabacloud/models/DeleteCalendarResponse.hpp>
#include <alibabacloud/models/DeleteClusterRequest.hpp>
#include <alibabacloud/models/DeleteClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteClusterResponse.hpp>
#include <alibabacloud/models/DeleteJobsRequest.hpp>
#include <alibabacloud/models/DeleteJobsShrinkRequest.hpp>
#include <alibabacloud/models/DeleteJobsResponseBody.hpp>
#include <alibabacloud/models/DeleteJobsResponse.hpp>
#include <alibabacloud/models/DeleteWorkflowRequest.hpp>
#include <alibabacloud/models/DeleteWorkflowResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkflowResponse.hpp>
#include <alibabacloud/models/DeleteWorkflowsRequest.hpp>
#include <alibabacloud/models/DeleteWorkflowsShrinkRequest.hpp>
#include <alibabacloud/models/DeleteWorkflowsResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkflowsResponse.hpp>
#include <alibabacloud/models/ExportJobsRequest.hpp>
#include <alibabacloud/models/ExportJobsShrinkRequest.hpp>
#include <alibabacloud/models/ExportJobsResponse.hpp>
#include <alibabacloud/models/ExportWorkflowsRequest.hpp>
#include <alibabacloud/models/ExportWorkflowsShrinkRequest.hpp>
#include <alibabacloud/models/ExportWorkflowsResponse.hpp>
#include <alibabacloud/models/GetAppRequest.hpp>
#include <alibabacloud/models/GetAppResponseBody.hpp>
#include <alibabacloud/models/GetAppResponse.hpp>
#include <alibabacloud/models/GetCalendarRequest.hpp>
#include <alibabacloud/models/GetCalendarResponseBody.hpp>
#include <alibabacloud/models/GetCalendarResponse.hpp>
#include <alibabacloud/models/GetClusterRequest.hpp>
#include <alibabacloud/models/GetClusterResponseBody.hpp>
#include <alibabacloud/models/GetClusterResponse.hpp>
#include <alibabacloud/models/GetDesigateInfoRequest.hpp>
#include <alibabacloud/models/GetDesigateInfoResponseBody.hpp>
#include <alibabacloud/models/GetDesigateInfoResponse.hpp>
#include <alibabacloud/models/GetExecutorConfigRequest.hpp>
#include <alibabacloud/models/GetExecutorConfigResponseBody.hpp>
#include <alibabacloud/models/GetExecutorConfigResponse.hpp>
#include <alibabacloud/models/GetJobExecutionRequest.hpp>
#include <alibabacloud/models/GetJobExecutionResponseBody.hpp>
#include <alibabacloud/models/GetJobExecutionResponse.hpp>
#include <alibabacloud/models/GetJobExecutionProgressRequest.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBody.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponse.hpp>
#include <alibabacloud/models/GetJobExecutionThreadDumpRequest.hpp>
#include <alibabacloud/models/GetJobExecutionThreadDumpResponseBody.hpp>
#include <alibabacloud/models/GetJobExecutionThreadDumpResponse.hpp>
#include <alibabacloud/models/GetLogRequest.hpp>
#include <alibabacloud/models/GetLogResponseBody.hpp>
#include <alibabacloud/models/GetLogResponse.hpp>
#include <alibabacloud/models/GetLogEventRequest.hpp>
#include <alibabacloud/models/GetLogEventResponseBody.hpp>
#include <alibabacloud/models/GetLogEventResponse.hpp>
#include <alibabacloud/models/GetWorkflowRequest.hpp>
#include <alibabacloud/models/GetWorkflowResponseBody.hpp>
#include <alibabacloud/models/GetWorkflowResponse.hpp>
#include <alibabacloud/models/GetWorkflowDagRequest.hpp>
#include <alibabacloud/models/GetWorkflowDagResponseBody.hpp>
#include <alibabacloud/models/GetWorkflowDagResponse.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewRequest.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponseBody.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponse.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagRequest.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponseBody.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponse.hpp>
#include <alibabacloud/models/ImportCalendarRequest.hpp>
#include <alibabacloud/models/ImportCalendarResponseBody.hpp>
#include <alibabacloud/models/ImportCalendarResponse.hpp>
#include <alibabacloud/models/ImportJobsRequest.hpp>
#include <alibabacloud/models/ImportJobsResponseBody.hpp>
#include <alibabacloud/models/ImportJobsResponse.hpp>
#include <alibabacloud/models/ImportWorkflowsRequest.hpp>
#include <alibabacloud/models/ImportWorkflowsResponseBody.hpp>
#include <alibabacloud/models/ImportWorkflowsResponse.hpp>
#include <alibabacloud/models/ListAlarmEventRequest.hpp>
#include <alibabacloud/models/ListAlarmEventResponseBody.hpp>
#include <alibabacloud/models/ListAlarmEventResponse.hpp>
#include <alibabacloud/models/ListAppNamesRequest.hpp>
#include <alibabacloud/models/ListAppNamesResponseBody.hpp>
#include <alibabacloud/models/ListAppNamesResponse.hpp>
#include <alibabacloud/models/ListAppsRequest.hpp>
#include <alibabacloud/models/ListAppsResponseBody.hpp>
#include <alibabacloud/models/ListAppsResponse.hpp>
#include <alibabacloud/models/ListCalendarNamesRequest.hpp>
#include <alibabacloud/models/ListCalendarNamesResponseBody.hpp>
#include <alibabacloud/models/ListCalendarNamesResponse.hpp>
#include <alibabacloud/models/ListCalendarsRequest.hpp>
#include <alibabacloud/models/ListCalendarsResponseBody.hpp>
#include <alibabacloud/models/ListCalendarsResponse.hpp>
#include <alibabacloud/models/ListClustersRequest.hpp>
#include <alibabacloud/models/ListClustersResponseBody.hpp>
#include <alibabacloud/models/ListClustersResponse.hpp>
#include <alibabacloud/models/ListExecutorsRequest.hpp>
#include <alibabacloud/models/ListExecutorsResponseBody.hpp>
#include <alibabacloud/models/ListExecutorsResponse.hpp>
#include <alibabacloud/models/ListJobExecutionsRequest.hpp>
#include <alibabacloud/models/ListJobExecutionsResponseBody.hpp>
#include <alibabacloud/models/ListJobExecutionsResponse.hpp>
#include <alibabacloud/models/ListJobScriptHistoryRequest.hpp>
#include <alibabacloud/models/ListJobScriptHistoryResponseBody.hpp>
#include <alibabacloud/models/ListJobScriptHistoryResponse.hpp>
#include <alibabacloud/models/ListJobsRequest.hpp>
#include <alibabacloud/models/ListJobsResponseBody.hpp>
#include <alibabacloud/models/ListJobsResponse.hpp>
#include <alibabacloud/models/ListK8sResourceRequest.hpp>
#include <alibabacloud/models/ListK8sResourceResponseBody.hpp>
#include <alibabacloud/models/ListK8sResourceResponse.hpp>
#include <alibabacloud/models/ListLablesRequest.hpp>
#include <alibabacloud/models/ListLablesResponseBody.hpp>
#include <alibabacloud/models/ListLablesResponse.hpp>
#include <alibabacloud/models/ListRegionZoneResponseBody.hpp>
#include <alibabacloud/models/ListRegionZoneResponse.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/ListScheduleEventRequest.hpp>
#include <alibabacloud/models/ListScheduleEventResponseBody.hpp>
#include <alibabacloud/models/ListScheduleEventResponse.hpp>
#include <alibabacloud/models/ListScheduleTimesRequest.hpp>
#include <alibabacloud/models/ListScheduleTimesResponseBody.hpp>
#include <alibabacloud/models/ListScheduleTimesResponse.hpp>
#include <alibabacloud/models/ListWorkflowExecutionsRequest.hpp>
#include <alibabacloud/models/ListWorkflowExecutionsResponseBody.hpp>
#include <alibabacloud/models/ListWorkflowExecutionsResponse.hpp>
#include <alibabacloud/models/ListWorkflowVersionsRequest.hpp>
#include <alibabacloud/models/ListWorkflowVersionsResponseBody.hpp>
#include <alibabacloud/models/ListWorkflowVersionsResponse.hpp>
#include <alibabacloud/models/ListWorkflowsRequest.hpp>
#include <alibabacloud/models/ListWorkflowsResponseBody.hpp>
#include <alibabacloud/models/ListWorkflowsResponse.hpp>
#include <alibabacloud/models/OperateBackfillWorkflowRequest.hpp>
#include <alibabacloud/models/OperateBackfillWorkflowResponseBody.hpp>
#include <alibabacloud/models/OperateBackfillWorkflowResponse.hpp>
#include <alibabacloud/models/OperateDesignateExecutorsRequest.hpp>
#include <alibabacloud/models/OperateDesignateExecutorsShrinkRequest.hpp>
#include <alibabacloud/models/OperateDesignateExecutorsResponseBody.hpp>
#include <alibabacloud/models/OperateDesignateExecutorsResponse.hpp>
#include <alibabacloud/models/OperateDisableJobsRequest.hpp>
#include <alibabacloud/models/OperateDisableJobsShrinkRequest.hpp>
#include <alibabacloud/models/OperateDisableJobsResponseBody.hpp>
#include <alibabacloud/models/OperateDisableJobsResponse.hpp>
#include <alibabacloud/models/OperateDisableWorkflowsRequest.hpp>
#include <alibabacloud/models/OperateDisableWorkflowsShrinkRequest.hpp>
#include <alibabacloud/models/OperateDisableWorkflowsResponseBody.hpp>
#include <alibabacloud/models/OperateDisableWorkflowsResponse.hpp>
#include <alibabacloud/models/OperateEnableJobsRequest.hpp>
#include <alibabacloud/models/OperateEnableJobsShrinkRequest.hpp>
#include <alibabacloud/models/OperateEnableJobsResponseBody.hpp>
#include <alibabacloud/models/OperateEnableJobsResponse.hpp>
#include <alibabacloud/models/OperateEnableWorkflowsRequest.hpp>
#include <alibabacloud/models/OperateEnableWorkflowsShrinkRequest.hpp>
#include <alibabacloud/models/OperateEnableWorkflowsResponseBody.hpp>
#include <alibabacloud/models/OperateEnableWorkflowsResponse.hpp>
#include <alibabacloud/models/OperateExecuteJobRequest.hpp>
#include <alibabacloud/models/OperateExecuteJobResponseBody.hpp>
#include <alibabacloud/models/OperateExecuteJobResponse.hpp>
#include <alibabacloud/models/OperateExecuteWorkflowRequest.hpp>
#include <alibabacloud/models/OperateExecuteWorkflowResponseBody.hpp>
#include <alibabacloud/models/OperateExecuteWorkflowResponse.hpp>
#include <alibabacloud/models/OperateHoldJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateHoldJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateHoldJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateHoldWorkflowExecutionRequest.hpp>
#include <alibabacloud/models/OperateHoldWorkflowExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateHoldWorkflowExecutionResponse.hpp>
#include <alibabacloud/models/OperateMarkSuccessJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateMarkSuccessJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateMarkSuccessJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateMarkSuccessWorkflowExecutionRequest.hpp>
#include <alibabacloud/models/OperateMarkSuccessWorkflowExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateMarkSuccessWorkflowExecutionResponse.hpp>
#include <alibabacloud/models/OperateRerunJobRequest.hpp>
#include <alibabacloud/models/OperateRerunJobResponseBody.hpp>
#include <alibabacloud/models/OperateRerunJobResponse.hpp>
#include <alibabacloud/models/OperateRetryJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateRetryJobExecutionShrinkRequest.hpp>
#include <alibabacloud/models/OperateRetryJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateRetryJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateRetryWorkflowExecutionRequest.hpp>
#include <alibabacloud/models/OperateRetryWorkflowExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateRetryWorkflowExecutionResponse.hpp>
#include <alibabacloud/models/OperateSkipJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateSkipJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateSkipJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateStopJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateStopJobExecutionShrinkRequest.hpp>
#include <alibabacloud/models/OperateStopJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateStopJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateStopWorkflowExecutionRequest.hpp>
#include <alibabacloud/models/OperateStopWorkflowExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateStopWorkflowExecutionResponse.hpp>
#include <alibabacloud/models/OperateUnholdJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateUnholdJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateUnholdJobExecutionResponse.hpp>
#include <alibabacloud/models/OperateUnholdWorkflowExecutionRequest.hpp>
#include <alibabacloud/models/OperateUnholdWorkflowExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateUnholdWorkflowExecutionResponse.hpp>
#include <alibabacloud/models/OperateUnskipJobExecutionRequest.hpp>
#include <alibabacloud/models/OperateUnskipJobExecutionResponseBody.hpp>
#include <alibabacloud/models/OperateUnskipJobExecutionResponse.hpp>
#include <alibabacloud/models/SyncJobsRequest.hpp>
#include <alibabacloud/models/SyncJobsShrinkRequest.hpp>
#include <alibabacloud/models/SyncJobsResponseBody.hpp>
#include <alibabacloud/models/SyncJobsResponse.hpp>
#include <alibabacloud/models/UpdateAppRequest.hpp>
#include <alibabacloud/models/UpdateAppResponseBody.hpp>
#include <alibabacloud/models/UpdateAppResponse.hpp>
#include <alibabacloud/models/UpdateCalendarRequest.hpp>
#include <alibabacloud/models/UpdateCalendarResponseBody.hpp>
#include <alibabacloud/models/UpdateCalendarResponse.hpp>
#include <alibabacloud/models/UpdateClusterRequest.hpp>
#include <alibabacloud/models/UpdateClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateClusterResponse.hpp>
#include <alibabacloud/models/UpdateExecutorsRequest.hpp>
#include <alibabacloud/models/UpdateExecutorsResponseBody.hpp>
#include <alibabacloud/models/UpdateExecutorsResponse.hpp>
#include <alibabacloud/models/UpdateJobRequest.hpp>
#include <alibabacloud/models/UpdateJobShrinkRequest.hpp>
#include <alibabacloud/models/UpdateJobResponseBody.hpp>
#include <alibabacloud/models/UpdateJobResponse.hpp>
#include <alibabacloud/models/UpdateJobScriptRequest.hpp>
#include <alibabacloud/models/UpdateJobScriptResponseBody.hpp>
#include <alibabacloud/models/UpdateJobScriptResponse.hpp>
#include <alibabacloud/models/UpdateWorkflowRequest.hpp>
#include <alibabacloud/models/UpdateWorkflowResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkflowResponse.hpp>
#include <alibabacloud/models/UpdateWorkflowDagRequest.hpp>
#include <alibabacloud/models/UpdateWorkflowDagShrinkRequest.hpp>
#include <alibabacloud/models/UpdateWorkflowDagResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkflowDagResponse.hpp>
#include <alibabacloud/models/UpdateWorkflowDagVersionRequest.hpp>
#include <alibabacloud/models/UpdateWorkflowDagVersionResponseBody.hpp>
#include <alibabacloud/models/UpdateWorkflowDagVersionResponse.hpp>
#include <alibabacloud/models/CreateAppResponseBodyData.hpp>
#include <alibabacloud/models/CreateClusterRequestTag.hpp>
#include <alibabacloud/models/CreateClusterRequestVSwitches.hpp>
#include <alibabacloud/models/CreateClusterShrinkRequestTag.hpp>
#include <alibabacloud/models/CreateClusterResponseBodyData.hpp>
#include <alibabacloud/models/CreateExecutorsResponseBodyData.hpp>
#include <alibabacloud/models/CreateJobRequestCoordinate.hpp>
#include <alibabacloud/models/CreateJobRequestNoticeConfig.hpp>
#include <alibabacloud/models/CreateJobRequestNoticeContacts.hpp>
#include <alibabacloud/models/CreateJobResponseBodyData.hpp>
#include <alibabacloud/models/CreateWorkflowResponseBodyData.hpp>
#include <alibabacloud/models/GetAppResponseBodyData.hpp>
#include <alibabacloud/models/GetCalendarResponseBodyData.hpp>
#include <alibabacloud/models/GetClusterResponseBodyDataVSwitches.hpp>
#include <alibabacloud/models/GetClusterResponseBodyData.hpp>
#include <alibabacloud/models/GetDesigateInfoResponseBodyData.hpp>
#include <alibabacloud/models/GetExecutorConfigResponseBodyData.hpp>
#include <alibabacloud/models/GetJobExecutionResponseBodyData.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataRootProgress.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataShardingProgressStatusType.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataShardingProgress.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataTaskProgress.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataTotalProgress.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyDataWorkerProgress.hpp>
#include <alibabacloud/models/GetJobExecutionProgressResponseBodyData.hpp>
#include <alibabacloud/models/GetJobExecutionThreadDumpResponseBodyData.hpp>
#include <alibabacloud/models/GetLogEventResponseBodyDataRecords.hpp>
#include <alibabacloud/models/GetLogEventResponseBodyData.hpp>
#include <alibabacloud/models/GetWorkflowResponseBodyData.hpp>
#include <alibabacloud/models/GetWorkflowDagResponseBodyDataEdges.hpp>
#include <alibabacloud/models/GetWorkflowDagResponseBodyDataNodesCoordinate.hpp>
#include <alibabacloud/models/GetWorkflowDagResponseBodyDataNodes.hpp>
#include <alibabacloud/models/GetWorkflowDagResponseBodyData.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponseBodyDataEdges.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponseBodyDataNodesCoordinate.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponseBodyDataNodes.hpp>
#include <alibabacloud/models/GetWorkflowDagPreviewResponseBodyData.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponseBodyDataEdges.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponseBodyDataNodesCoordinate.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponseBodyDataNodes.hpp>
#include <alibabacloud/models/GetWorkflowExecutionDagResponseBodyData.hpp>
#include <alibabacloud/models/ListAlarmEventResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListAlarmEventResponseBodyData.hpp>
#include <alibabacloud/models/ListAppNamesResponseBodyData.hpp>
#include <alibabacloud/models/ListAppsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListAppsResponseBodyData.hpp>
#include <alibabacloud/models/ListCalendarsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListCalendarsResponseBodyData.hpp>
#include <alibabacloud/models/ListClustersRequestTag.hpp>
#include <alibabacloud/models/ListClustersResponseBodyDataRecordsVSwitches.hpp>
#include <alibabacloud/models/ListClustersResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListClustersResponseBodyData.hpp>
#include <alibabacloud/models/ListExecutorsResponseBodyData.hpp>
#include <alibabacloud/models/ListJobExecutionsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListJobExecutionsResponseBodyData.hpp>
#include <alibabacloud/models/ListJobScriptHistoryResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListJobScriptHistoryResponseBodyData.hpp>
#include <alibabacloud/models/ListJobsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListJobsResponseBodyData.hpp>
#include <alibabacloud/models/ListK8sResourceResponseBodyData.hpp>
#include <alibabacloud/models/ListLablesResponseBodyData.hpp>
#include <alibabacloud/models/ListRegionZoneResponseBodyData.hpp>
#include <alibabacloud/models/ListRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/ListScheduleEventResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListScheduleEventResponseBodyData.hpp>
#include <alibabacloud/models/ListWorkflowExecutionsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListWorkflowExecutionsResponseBodyData.hpp>
#include <alibabacloud/models/ListWorkflowVersionsResponseBodyData.hpp>
#include <alibabacloud/models/ListWorkflowsResponseBodyDataRecords.hpp>
#include <alibabacloud/models/ListWorkflowsResponseBodyData.hpp>
#include <alibabacloud/models/OperateExecuteJobResponseBodyData.hpp>
#include <alibabacloud/models/OperateExecuteWorkflowResponseBodyData.hpp>
#include <alibabacloud/models/UpdateExecutorsResponseBodyData.hpp>
#include <alibabacloud/models/UpdateJobRequestNoticeConfig.hpp>
#include <alibabacloud/models/UpdateJobRequestNoticeContacts.hpp>
#include <alibabacloud/models/UpdateWorkflowDagRequestDagEdges.hpp>
#include <alibabacloud/models/UpdateWorkflowDagRequestDagNodesCoordinate.hpp>
#include <alibabacloud/models/UpdateWorkflowDagRequestDagNodes.hpp>
#include <alibabacloud/models/UpdateWorkflowDagRequestDag.hpp>

#endif
