// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_VPCPEER20220101MODEL_HPP_
#define ALIBABACLOUD_VPCPEER20220101MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AcceptVpcPeerConnectionRequest.hpp>
#include <alibabacloud/models/AcceptVpcPeerConnectionResponseBody.hpp>
#include <alibabacloud/models/AcceptVpcPeerConnectionResponse.hpp>
#include <alibabacloud/models/CreateVpcPeerConnectionRequest.hpp>
#include <alibabacloud/models/CreateVpcPeerConnectionResponseBody.hpp>
#include <alibabacloud/models/CreateVpcPeerConnectionResponse.hpp>
#include <alibabacloud/models/DeleteVpcPeerConnectionRequest.hpp>
#include <alibabacloud/models/DeleteVpcPeerConnectionResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcPeerConnectionResponse.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeRequest.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeResponseBody.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsRequest.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsShrinkRequest.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponseBody.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponse.hpp>
#include <alibabacloud/models/ModifyVpcPeerConnectionRequest.hpp>
#include <alibabacloud/models/ModifyVpcPeerConnectionResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcPeerConnectionResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/RejectVpcPeerConnectionRequest.hpp>
#include <alibabacloud/models/RejectVpcPeerConnectionResponseBody.hpp>
#include <alibabacloud/models/RejectVpcPeerConnectionResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UnTagResourcesRequest.hpp>
#include <alibabacloud/models/UnTagResourcesResponseBody.hpp>
#include <alibabacloud/models/UnTagResourcesResponse.hpp>
#include <alibabacloud/models/AcceptVpcPeerConnectionRequestTag.hpp>
#include <alibabacloud/models/CreateVpcPeerConnectionRequestTag.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeResponseBodyAcceptingVpc.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeResponseBodyTags.hpp>
#include <alibabacloud/models/GetVpcPeerConnectionAttributeResponseBodyVpc.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsRequestTags.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsShrinkRequestTags.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponseBodyVpcPeerConnectsAcceptingVpc.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponseBodyVpcPeerConnectsTags.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponseBodyVpcPeerConnectsVpc.hpp>
#include <alibabacloud/models/ListVpcPeerConnectionsResponseBodyVpcPeerConnects.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
