// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_OSSAGENT20260622_HPP_
#define ALIBABACLOUD_OSSAGENT20260622_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/OssAgent20260622Model.hpp>
#include <alibabacloud/Openapi.hpp>
#include <alibabacloud/Utils.hpp>
#include <map>
#include <alibabacloud/OssAgent20260622.hpp>
#include <darabonba/Runtime.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace OssAgent20260622
{
  class Client : public AlibabaCloud::OpenApi::Client {
    public:

      Client(AlibabaCloud::OpenApi::Utils::Models::Config &config);
      string getEndpoint(const string &productId, const string &regionId, const string &endpointRule, const string &network, const string &suffix, const map<string, string> &endpointMap, const string &endpoint);

      /**
       * @summary Initiates a streaming chat session.
       *
       * @param request ChatRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return ChatResponse
       */
      FutureGenerator<Models::ChatResponse> chatWithSSE(const Models::ChatRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Initiates a streaming chat session.
       *
       * @param request ChatRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return ChatResponse
       */
      Models::ChatResponse chatWithOptions(const Models::ChatRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Initiates a streaming chat session.
       *
       * @param request ChatRequest
       * @return ChatResponse
       */
      Models::ChatResponse chat(const Models::ChatRequest &request);

      /**
       * @summary Confirms a tool calling operation.
       *
       * @param request ConfirmRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return ConfirmResponse
       */
      FutureGenerator<Models::ConfirmResponse> confirmWithSSE(const Models::ConfirmRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Confirms a tool calling operation.
       *
       * @param request ConfirmRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return ConfirmResponse
       */
      Models::ConfirmResponse confirmWithOptions(const Models::ConfirmRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Confirms a tool calling operation.
       *
       * @param request ConfirmRequest
       * @return ConfirmResponse
       */
      Models::ConfirmResponse confirm(const Models::ConfirmRequest &request);

      /**
       * @summary Retrieves the details of a session. You can only query sessions generated by your own account.
       *
       * @param request GetSessionContentRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return GetSessionContentResponse
       */
      Models::GetSessionContentResponse getSessionContentWithOptions(const Models::GetSessionContentRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Retrieves the details of a session. You can only query sessions generated by your own account.
       *
       * @param request GetSessionContentRequest
       * @return GetSessionContentResponse
       */
      Models::GetSessionContentResponse getSessionContent(const Models::GetSessionContentRequest &request);

      /**
       * @summary Interrupts a chat session.
       *
       * @param request InterruptRequest
       * @param headers map
       * @param runtime runtime options for this request RuntimeOptions
       * @return InterruptResponse
       */
      Models::InterruptResponse interruptWithOptions(const string &sessionId, const Models::InterruptRequest &request, const map<string, string> &headers, const Darabonba::RuntimeOptions &runtime);

      /**
       * @summary Interrupts a chat session.
       *
       * @param request InterruptRequest
       * @return InterruptResponse
       */
      Models::InterruptResponse interrupt(const string &sessionId, const Models::InterruptRequest &request);
  };
} // namespace AlibabaCloud
} // namespace OssAgent20260622
#endif
