// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ALIMT20181012MODEL_HPP_
#define ALIBABACLOUD_ALIMT20181012MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateAsyncTranslateRequest.hpp>
#include <alibabacloud/models/CreateAsyncTranslateResponseBody.hpp>
#include <alibabacloud/models/CreateAsyncTranslateResponse.hpp>
#include <alibabacloud/models/CreateDocTranslateTaskRequest.hpp>
#include <alibabacloud/models/CreateDocTranslateTaskAdvanceRequest.hpp>
#include <alibabacloud/models/CreateDocTranslateTaskResponseBody.hpp>
#include <alibabacloud/models/CreateDocTranslateTaskResponse.hpp>
#include <alibabacloud/models/CreateImageTranslateTaskRequest.hpp>
#include <alibabacloud/models/CreateImageTranslateTaskResponseBody.hpp>
#include <alibabacloud/models/CreateImageTranslateTaskResponse.hpp>
#include <alibabacloud/models/GetAsyncTranslateRequest.hpp>
#include <alibabacloud/models/GetAsyncTranslateResponseBody.hpp>
#include <alibabacloud/models/GetAsyncTranslateResponse.hpp>
#include <alibabacloud/models/GetBatchTranslateRequest.hpp>
#include <alibabacloud/models/GetBatchTranslateResponseBody.hpp>
#include <alibabacloud/models/GetBatchTranslateResponse.hpp>
#include <alibabacloud/models/GetBatchTranslateByVpcRequest.hpp>
#include <alibabacloud/models/GetBatchTranslateByVpcResponseBody.hpp>
#include <alibabacloud/models/GetBatchTranslateByVpcResponse.hpp>
#include <alibabacloud/models/GetDetectLanguageRequest.hpp>
#include <alibabacloud/models/GetDetectLanguageResponseBody.hpp>
#include <alibabacloud/models/GetDetectLanguageResponse.hpp>
#include <alibabacloud/models/GetDetectLanguageVpcRequest.hpp>
#include <alibabacloud/models/GetDetectLanguageVpcResponseBody.hpp>
#include <alibabacloud/models/GetDetectLanguageVpcResponse.hpp>
#include <alibabacloud/models/GetDocTranslateTaskRequest.hpp>
#include <alibabacloud/models/GetDocTranslateTaskResponseBody.hpp>
#include <alibabacloud/models/GetDocTranslateTaskResponse.hpp>
#include <alibabacloud/models/GetImageDiagnoseRequest.hpp>
#include <alibabacloud/models/GetImageDiagnoseResponseBody.hpp>
#include <alibabacloud/models/GetImageDiagnoseResponse.hpp>
#include <alibabacloud/models/GetImageTranslateRequest.hpp>
#include <alibabacloud/models/GetImageTranslateResponseBody.hpp>
#include <alibabacloud/models/GetImageTranslateResponse.hpp>
#include <alibabacloud/models/GetImageTranslateTaskRequest.hpp>
#include <alibabacloud/models/GetImageTranslateTaskResponseBody.hpp>
#include <alibabacloud/models/GetImageTranslateTaskResponse.hpp>
#include <alibabacloud/models/GetTitleDiagnoseRequest.hpp>
#include <alibabacloud/models/GetTitleDiagnoseResponseBody.hpp>
#include <alibabacloud/models/GetTitleDiagnoseResponse.hpp>
#include <alibabacloud/models/GetTitleGenerateRequest.hpp>
#include <alibabacloud/models/GetTitleGenerateResponseBody.hpp>
#include <alibabacloud/models/GetTitleGenerateResponse.hpp>
#include <alibabacloud/models/GetTitleIntelligenceRequest.hpp>
#include <alibabacloud/models/GetTitleIntelligenceResponseBody.hpp>
#include <alibabacloud/models/GetTitleIntelligenceResponse.hpp>
#include <alibabacloud/models/GetTranslateImageBatchResultRequest.hpp>
#include <alibabacloud/models/GetTranslateImageBatchResultResponseBody.hpp>
#include <alibabacloud/models/GetTranslateImageBatchResultResponse.hpp>
#include <alibabacloud/models/GetTranslateReportRequest.hpp>
#include <alibabacloud/models/GetTranslateReportResponseBody.hpp>
#include <alibabacloud/models/GetTranslateReportResponse.hpp>
#include <alibabacloud/models/OpenAlimtServiceRequest.hpp>
#include <alibabacloud/models/OpenAlimtServiceResponseBody.hpp>
#include <alibabacloud/models/OpenAlimtServiceResponse.hpp>
#include <alibabacloud/models/TranslateRequest.hpp>
#include <alibabacloud/models/TranslateResponseBody.hpp>
#include <alibabacloud/models/TranslateResponse.hpp>
#include <alibabacloud/models/TranslateCertificateRequest.hpp>
#include <alibabacloud/models/TranslateCertificateAdvanceRequest.hpp>
#include <alibabacloud/models/TranslateCertificateResponseBody.hpp>
#include <alibabacloud/models/TranslateCertificateResponse.hpp>
#include <alibabacloud/models/TranslateECommerceRequest.hpp>
#include <alibabacloud/models/TranslateECommerceResponseBody.hpp>
#include <alibabacloud/models/TranslateECommerceResponse.hpp>
#include <alibabacloud/models/TranslateGeneralRequest.hpp>
#include <alibabacloud/models/TranslateGeneralResponseBody.hpp>
#include <alibabacloud/models/TranslateGeneralResponse.hpp>
#include <alibabacloud/models/TranslateGeneralVpcRequest.hpp>
#include <alibabacloud/models/TranslateGeneralVpcResponseBody.hpp>
#include <alibabacloud/models/TranslateGeneralVpcResponse.hpp>
#include <alibabacloud/models/TranslateImageRequest.hpp>
#include <alibabacloud/models/TranslateImageResponseBody.hpp>
#include <alibabacloud/models/TranslateImageResponse.hpp>
#include <alibabacloud/models/TranslateImageBatchRequest.hpp>
#include <alibabacloud/models/TranslateImageBatchResponseBody.hpp>
#include <alibabacloud/models/TranslateImageBatchResponse.hpp>
#include <alibabacloud/models/TranslateSearchRequest.hpp>
#include <alibabacloud/models/TranslateSearchResponseBody.hpp>
#include <alibabacloud/models/TranslateSearchResponse.hpp>
#include <alibabacloud/models/CreateAsyncTranslateResponseBodyData.hpp>
#include <alibabacloud/models/CreateImageTranslateTaskResponseBodyData.hpp>
#include <alibabacloud/models/GetAsyncTranslateResponseBodyData.hpp>
#include <alibabacloud/models/GetImageDiagnoseResponseBodyData.hpp>
#include <alibabacloud/models/GetImageTranslateResponseBodyData.hpp>
#include <alibabacloud/models/GetImageTranslateTaskResponseBodyData.hpp>
#include <alibabacloud/models/GetTitleDiagnoseResponseBodyData.hpp>
#include <alibabacloud/models/GetTitleGenerateResponseBodyData.hpp>
#include <alibabacloud/models/GetTitleIntelligenceResponseBodyData.hpp>
#include <alibabacloud/models/GetTranslateImageBatchResultResponseBodyDataResult.hpp>
#include <alibabacloud/models/GetTranslateImageBatchResultResponseBodyData.hpp>
#include <alibabacloud/models/TranslateResponseBodyData.hpp>
#include <alibabacloud/models/TranslateCertificateResponseBodyDataTranslatedValues.hpp>
#include <alibabacloud/models/TranslateCertificateResponseBodyData.hpp>
#include <alibabacloud/models/TranslateECommerceResponseBodyData.hpp>
#include <alibabacloud/models/TranslateGeneralResponseBodyData.hpp>
#include <alibabacloud/models/TranslateGeneralVpcResponseBodyData.hpp>
#include <alibabacloud/models/TranslateImageResponseBodyData.hpp>
#include <alibabacloud/models/TranslateImageBatchResponseBodyData.hpp>
#include <alibabacloud/models/TranslateSearchResponseBodyData.hpp>

#endif
