// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ELASTICSEARCH20170613MODEL_HPP_
#define ALIBABACLOUD_ELASTICSEARCH20170613MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ClientNodeConfiguration.hpp>
#include <alibabacloud/models/CollectorDeployMachine.hpp>
#include <alibabacloud/models/CollectorKibanaInstance.hpp>
#include <alibabacloud/models/CollectorTargetInstance.hpp>
#include <alibabacloud/models/DictInfo.hpp>
#include <alibabacloud/models/ElasticDataNodeConfiguration.hpp>
#include <alibabacloud/models/KibanaNodeConfiguration.hpp>
#include <alibabacloud/models/MasterNodeConfiguration.hpp>
#include <alibabacloud/models/WhiteIpGroup.hpp>
#include <alibabacloud/models/NetworkConfig.hpp>
#include <alibabacloud/models/NodeSpec.hpp>
#include <alibabacloud/models/ReadWritePolicy.hpp>
#include <alibabacloud/models/Tag.hpp>
#include <alibabacloud/models/WarmNodeConfiguration.hpp>
#include <alibabacloud/models/ZoneInfo.hpp>
#include <alibabacloud/models/Elasticsearch.hpp>
#include <alibabacloud/models/Logstash.hpp>
#include <alibabacloud/models/MigrationJob.hpp>
#include <alibabacloud/models/NodeInfo.hpp>
#include <alibabacloud/models/PaymentInfo.hpp>
#include <alibabacloud/models/ResultSpecInfoMapValue.hpp>
#include <alibabacloud/models/ActivateZonesRequest.hpp>
#include <alibabacloud/models/ActivateZonesResponseBody.hpp>
#include <alibabacloud/models/ActivateZonesResponse.hpp>
#include <alibabacloud/models/AddConnectableClusterRequest.hpp>
#include <alibabacloud/models/AddConnectableClusterResponseBody.hpp>
#include <alibabacloud/models/AddConnectableClusterResponse.hpp>
#include <alibabacloud/models/AddSnapshotRepoRequest.hpp>
#include <alibabacloud/models/AddSnapshotRepoResponseBody.hpp>
#include <alibabacloud/models/AddSnapshotRepoResponse.hpp>
#include <alibabacloud/models/CancelDeletionRequest.hpp>
#include <alibabacloud/models/CancelDeletionResponseBody.hpp>
#include <alibabacloud/models/CancelDeletionResponse.hpp>
#include <alibabacloud/models/CancelLogstashDeletionRequest.hpp>
#include <alibabacloud/models/CancelLogstashDeletionResponseBody.hpp>
#include <alibabacloud/models/CancelLogstashDeletionResponse.hpp>
#include <alibabacloud/models/CancelTaskRequest.hpp>
#include <alibabacloud/models/CancelTaskResponseBody.hpp>
#include <alibabacloud/models/CancelTaskResponse.hpp>
#include <alibabacloud/models/CapacityPlanRequest.hpp>
#include <alibabacloud/models/CapacityPlanResponseBody.hpp>
#include <alibabacloud/models/CapacityPlanResponse.hpp>
#include <alibabacloud/models/CloseDiagnosisRequest.hpp>
#include <alibabacloud/models/CloseDiagnosisResponseBody.hpp>
#include <alibabacloud/models/CloseDiagnosisResponse.hpp>
#include <alibabacloud/models/CloseHttpsRequest.hpp>
#include <alibabacloud/models/CloseHttpsResponseBody.hpp>
#include <alibabacloud/models/CloseHttpsResponse.hpp>
#include <alibabacloud/models/CloseManagedIndexRequest.hpp>
#include <alibabacloud/models/CloseManagedIndexResponseBody.hpp>
#include <alibabacloud/models/CloseManagedIndexResponse.hpp>
#include <alibabacloud/models/CreateCollectorRequest.hpp>
#include <alibabacloud/models/CreateCollectorResponseBody.hpp>
#include <alibabacloud/models/CreateCollectorResponse.hpp>
#include <alibabacloud/models/CreateComponentIndexRequest.hpp>
#include <alibabacloud/models/CreateComponentIndexResponseBody.hpp>
#include <alibabacloud/models/CreateComponentIndexResponse.hpp>
#include <alibabacloud/models/CreateDataStreamRequest.hpp>
#include <alibabacloud/models/CreateDataStreamResponseBody.hpp>
#include <alibabacloud/models/CreateDataStreamResponse.hpp>
#include <alibabacloud/models/CreateILMPolicyRequest.hpp>
#include <alibabacloud/models/CreateILMPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateILMPolicyResponse.hpp>
#include <alibabacloud/models/CreateIndexTemplateRequest.hpp>
#include <alibabacloud/models/CreateIndexTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateIndexTemplateResponse.hpp>
#include <alibabacloud/models/CreateLogstashRequest.hpp>
#include <alibabacloud/models/CreateLogstashResponseBody.hpp>
#include <alibabacloud/models/CreateLogstashResponse.hpp>
#include <alibabacloud/models/CreatePipelinesRequest.hpp>
#include <alibabacloud/models/CreatePipelinesResponseBody.hpp>
#include <alibabacloud/models/CreatePipelinesResponse.hpp>
#include <alibabacloud/models/CreateSnapshotRequest.hpp>
#include <alibabacloud/models/CreateSnapshotResponseBody.hpp>
#include <alibabacloud/models/CreateSnapshotResponse.hpp>
#include <alibabacloud/models/CreateVpcEndpointRequest.hpp>
#include <alibabacloud/models/CreateVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateVpcEndpointResponse.hpp>
#include <alibabacloud/models/DeactivateZonesRequest.hpp>
#include <alibabacloud/models/DeactivateZonesResponseBody.hpp>
#include <alibabacloud/models/DeactivateZonesResponse.hpp>
#include <alibabacloud/models/DeleteCollectorRequest.hpp>
#include <alibabacloud/models/DeleteCollectorResponseBody.hpp>
#include <alibabacloud/models/DeleteCollectorResponse.hpp>
#include <alibabacloud/models/DeleteComponentIndexResponseBody.hpp>
#include <alibabacloud/models/DeleteComponentIndexResponse.hpp>
#include <alibabacloud/models/DeleteConnectedClusterRequest.hpp>
#include <alibabacloud/models/DeleteConnectedClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteConnectedClusterResponse.hpp>
#include <alibabacloud/models/DeleteDataStreamRequest.hpp>
#include <alibabacloud/models/DeleteDataStreamResponseBody.hpp>
#include <alibabacloud/models/DeleteDataStreamResponse.hpp>
#include <alibabacloud/models/DeleteDataTaskRequest.hpp>
#include <alibabacloud/models/DeleteDataTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteDataTaskResponse.hpp>
#include <alibabacloud/models/DeleteDeprecatedTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteDeprecatedTemplateResponse.hpp>
#include <alibabacloud/models/DeleteILMPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteILMPolicyResponse.hpp>
#include <alibabacloud/models/DeleteIndexTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteIndexTemplateResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteLogstashRequest.hpp>
#include <alibabacloud/models/DeleteLogstashResponseBody.hpp>
#include <alibabacloud/models/DeleteLogstashResponse.hpp>
#include <alibabacloud/models/DeletePipelinesRequest.hpp>
#include <alibabacloud/models/DeletePipelinesResponseBody.hpp>
#include <alibabacloud/models/DeletePipelinesResponse.hpp>
#include <alibabacloud/models/DeleteSnapshotRepoRequest.hpp>
#include <alibabacloud/models/DeleteSnapshotRepoResponseBody.hpp>
#include <alibabacloud/models/DeleteSnapshotRepoResponse.hpp>
#include <alibabacloud/models/DeleteVpcEndpointRequest.hpp>
#include <alibabacloud/models/DeleteVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcEndpointResponse.hpp>
#include <alibabacloud/models/DescribeAckOperatorResponseBody.hpp>
#include <alibabacloud/models/DescribeAckOperatorResponse.hpp>
#include <alibabacloud/models/DescribeCollectorResponseBody.hpp>
#include <alibabacloud/models/DescribeCollectorResponse.hpp>
#include <alibabacloud/models/DescribeComponentIndexResponseBody.hpp>
#include <alibabacloud/models/DescribeComponentIndexResponse.hpp>
#include <alibabacloud/models/DescribeConnectableClustersRequest.hpp>
#include <alibabacloud/models/DescribeConnectableClustersResponseBody.hpp>
#include <alibabacloud/models/DescribeConnectableClustersResponse.hpp>
#include <alibabacloud/models/DescribeDeprecatedTemplateResponseBody.hpp>
#include <alibabacloud/models/DescribeDeprecatedTemplateResponse.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportRequest.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnoseReportResponse.hpp>
#include <alibabacloud/models/DescribeDiagnosisSettingsRequest.hpp>
#include <alibabacloud/models/DescribeDiagnosisSettingsResponseBody.hpp>
#include <alibabacloud/models/DescribeDiagnosisSettingsResponse.hpp>
#include <alibabacloud/models/DescribeDynamicSettingsResponseBody.hpp>
#include <alibabacloud/models/DescribeDynamicSettingsResponse.hpp>
#include <alibabacloud/models/DescribeElasticsearchHealthResponseBody.hpp>
#include <alibabacloud/models/DescribeElasticsearchHealthResponse.hpp>
#include <alibabacloud/models/DescribeILMPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeILMPolicyResponse.hpp>
#include <alibabacloud/models/DescribeIndexTemplateResponseBody.hpp>
#include <alibabacloud/models/DescribeIndexTemplateResponse.hpp>
#include <alibabacloud/models/DescribeInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceResponse.hpp>
#include <alibabacloud/models/DescribeKibanaSettingsResponseBody.hpp>
#include <alibabacloud/models/DescribeKibanaSettingsResponse.hpp>
#include <alibabacloud/models/DescribeLogstashResponseBody.hpp>
#include <alibabacloud/models/DescribeLogstashResponse.hpp>
#include <alibabacloud/models/DescribePipelineResponseBody.hpp>
#include <alibabacloud/models/DescribePipelineResponse.hpp>
#include <alibabacloud/models/DescribePipelineManagementConfigRequest.hpp>
#include <alibabacloud/models/DescribePipelineManagementConfigResponseBody.hpp>
#include <alibabacloud/models/DescribePipelineManagementConfigResponse.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeSnapshotSettingResponseBody.hpp>
#include <alibabacloud/models/DescribeSnapshotSettingResponse.hpp>
#include <alibabacloud/models/DescribeTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeXpackMonitorConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeXpackMonitorConfigResponse.hpp>
#include <alibabacloud/models/DiagnoseInstanceRequest.hpp>
#include <alibabacloud/models/DiagnoseInstanceResponseBody.hpp>
#include <alibabacloud/models/DiagnoseInstanceResponse.hpp>
#include <alibabacloud/models/DisableKibanaPvlNetworkResponseBody.hpp>
#include <alibabacloud/models/DisableKibanaPvlNetworkResponse.hpp>
#include <alibabacloud/models/EnableKibanaPvlNetworkRequest.hpp>
#include <alibabacloud/models/EnableKibanaPvlNetworkResponseBody.hpp>
#include <alibabacloud/models/EnableKibanaPvlNetworkResponse.hpp>
#include <alibabacloud/models/EstimatedLogstashRestartTimeRequest.hpp>
#include <alibabacloud/models/EstimatedLogstashRestartTimeResponseBody.hpp>
#include <alibabacloud/models/EstimatedLogstashRestartTimeResponse.hpp>
#include <alibabacloud/models/EstimatedRestartTimeRequest.hpp>
#include <alibabacloud/models/EstimatedRestartTimeResponseBody.hpp>
#include <alibabacloud/models/EstimatedRestartTimeResponse.hpp>
#include <alibabacloud/models/GetClusterDataInformationRequest.hpp>
#include <alibabacloud/models/GetClusterDataInformationResponseBody.hpp>
#include <alibabacloud/models/GetClusterDataInformationResponse.hpp>
#include <alibabacloud/models/GetElastictaskResponseBody.hpp>
#include <alibabacloud/models/GetElastictaskResponse.hpp>
#include <alibabacloud/models/GetEmonAlarmRecordStatisticsDistributeRequest.hpp>
#include <alibabacloud/models/GetEmonAlarmRecordStatisticsDistributeResponseBody.hpp>
#include <alibabacloud/models/GetEmonAlarmRecordStatisticsDistributeResponse.hpp>
#include <alibabacloud/models/GetEmonGrafanaAlertsRequest.hpp>
#include <alibabacloud/models/GetEmonGrafanaAlertsResponseBody.hpp>
#include <alibabacloud/models/GetEmonGrafanaAlertsResponse.hpp>
#include <alibabacloud/models/GetEmonGrafanaDashboardsRequest.hpp>
#include <alibabacloud/models/GetEmonGrafanaDashboardsResponseBody.hpp>
#include <alibabacloud/models/GetEmonGrafanaDashboardsResponse.hpp>
#include <alibabacloud/models/GetEmonMonitorDataRequest.hpp>
#include <alibabacloud/models/GetEmonMonitorDataResponseBody.hpp>
#include <alibabacloud/models/GetEmonMonitorDataResponse.hpp>
#include <alibabacloud/models/GetOpenStoreUsageResponseBody.hpp>
#include <alibabacloud/models/GetOpenStoreUsageResponse.hpp>
#include <alibabacloud/models/GetRegionConfigurationRequest.hpp>
#include <alibabacloud/models/GetRegionConfigurationResponseBody.hpp>
#include <alibabacloud/models/GetRegionConfigurationResponse.hpp>
#include <alibabacloud/models/GetRegionalInstanceConfigResponseBody.hpp>
#include <alibabacloud/models/GetRegionalInstanceConfigResponse.hpp>
#include <alibabacloud/models/GetSuggestShrinkableNodesRequest.hpp>
#include <alibabacloud/models/GetSuggestShrinkableNodesResponseBody.hpp>
#include <alibabacloud/models/GetSuggestShrinkableNodesResponse.hpp>
#include <alibabacloud/models/GetTransferableNodesRequest.hpp>
#include <alibabacloud/models/GetTransferableNodesResponseBody.hpp>
#include <alibabacloud/models/GetTransferableNodesResponse.hpp>
#include <alibabacloud/models/InitializeOperationRoleRequest.hpp>
#include <alibabacloud/models/InitializeOperationRoleResponseBody.hpp>
#include <alibabacloud/models/InitializeOperationRoleResponse.hpp>
#include <alibabacloud/models/InstallAckOperatorRequest.hpp>
#include <alibabacloud/models/InstallAckOperatorResponseBody.hpp>
#include <alibabacloud/models/InstallAckOperatorResponse.hpp>
#include <alibabacloud/models/InstallKibanaSystemPluginRequest.hpp>
#include <alibabacloud/models/InstallKibanaSystemPluginResponseBody.hpp>
#include <alibabacloud/models/InstallKibanaSystemPluginResponse.hpp>
#include <alibabacloud/models/InstallLogstashSystemPluginRequest.hpp>
#include <alibabacloud/models/InstallLogstashSystemPluginResponseBody.hpp>
#include <alibabacloud/models/InstallLogstashSystemPluginResponse.hpp>
#include <alibabacloud/models/InstallSystemPluginRequest.hpp>
#include <alibabacloud/models/InstallSystemPluginResponseBody.hpp>
#include <alibabacloud/models/InstallSystemPluginResponse.hpp>
#include <alibabacloud/models/InstallUserPluginsRequest.hpp>
#include <alibabacloud/models/InstallUserPluginsResponseBody.hpp>
#include <alibabacloud/models/InstallUserPluginsResponse.hpp>
#include <alibabacloud/models/InterruptElasticsearchTaskRequest.hpp>
#include <alibabacloud/models/InterruptElasticsearchTaskResponseBody.hpp>
#include <alibabacloud/models/InterruptElasticsearchTaskResponse.hpp>
#include <alibabacloud/models/InterruptLogstashTaskRequest.hpp>
#include <alibabacloud/models/InterruptLogstashTaskResponseBody.hpp>
#include <alibabacloud/models/InterruptLogstashTaskResponse.hpp>
#include <alibabacloud/models/ListAckClustersRequest.hpp>
#include <alibabacloud/models/ListAckClustersResponseBody.hpp>
#include <alibabacloud/models/ListAckClustersResponse.hpp>
#include <alibabacloud/models/ListAckNamespacesRequest.hpp>
#include <alibabacloud/models/ListAckNamespacesResponseBody.hpp>
#include <alibabacloud/models/ListAckNamespacesResponse.hpp>
#include <alibabacloud/models/ListActionRecordsRequest.hpp>
#include <alibabacloud/models/ListActionRecordsResponseBody.hpp>
#include <alibabacloud/models/ListActionRecordsResponse.hpp>
#include <alibabacloud/models/ListAllNodeRequest.hpp>
#include <alibabacloud/models/ListAllNodeResponseBody.hpp>
#include <alibabacloud/models/ListAllNodeResponse.hpp>
#include <alibabacloud/models/ListAlternativeSnapshotReposRequest.hpp>
#include <alibabacloud/models/ListAlternativeSnapshotReposResponseBody.hpp>
#include <alibabacloud/models/ListAlternativeSnapshotReposResponse.hpp>
#include <alibabacloud/models/ListAvailableEsInstanceIdsResponseBody.hpp>
#include <alibabacloud/models/ListAvailableEsInstanceIdsResponse.hpp>
#include <alibabacloud/models/ListCollectorsRequest.hpp>
#include <alibabacloud/models/ListCollectorsResponseBody.hpp>
#include <alibabacloud/models/ListCollectorsResponse.hpp>
#include <alibabacloud/models/ListComponentIndicesRequest.hpp>
#include <alibabacloud/models/ListComponentIndicesResponseBody.hpp>
#include <alibabacloud/models/ListComponentIndicesResponse.hpp>
#include <alibabacloud/models/ListConnectedClustersResponseBody.hpp>
#include <alibabacloud/models/ListConnectedClustersResponse.hpp>
#include <alibabacloud/models/ListDataStreamsRequest.hpp>
#include <alibabacloud/models/ListDataStreamsResponseBody.hpp>
#include <alibabacloud/models/ListDataStreamsResponse.hpp>
#include <alibabacloud/models/ListDataTasksResponseBody.hpp>
#include <alibabacloud/models/ListDataTasksResponse.hpp>
#include <alibabacloud/models/ListDefaultCollectorConfigurationsRequest.hpp>
#include <alibabacloud/models/ListDefaultCollectorConfigurationsResponseBody.hpp>
#include <alibabacloud/models/ListDefaultCollectorConfigurationsResponse.hpp>
#include <alibabacloud/models/ListDeprecatedTemplatesRequest.hpp>
#include <alibabacloud/models/ListDeprecatedTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListDeprecatedTemplatesResponse.hpp>
#include <alibabacloud/models/ListDiagnoseIndicesRequest.hpp>
#include <alibabacloud/models/ListDiagnoseIndicesResponseBody.hpp>
#include <alibabacloud/models/ListDiagnoseIndicesResponse.hpp>
#include <alibabacloud/models/ListDiagnoseReportRequest.hpp>
#include <alibabacloud/models/ListDiagnoseReportResponseBody.hpp>
#include <alibabacloud/models/ListDiagnoseReportResponse.hpp>
#include <alibabacloud/models/ListDiagnoseReportIdsRequest.hpp>
#include <alibabacloud/models/ListDiagnoseReportIdsResponseBody.hpp>
#include <alibabacloud/models/ListDiagnoseReportIdsResponse.hpp>
#include <alibabacloud/models/ListDiagnosisItemsRequest.hpp>
#include <alibabacloud/models/ListDiagnosisItemsResponseBody.hpp>
#include <alibabacloud/models/ListDiagnosisItemsResponse.hpp>
#include <alibabacloud/models/ListDictInformationRequest.hpp>
#include <alibabacloud/models/ListDictInformationResponseBody.hpp>
#include <alibabacloud/models/ListDictInformationResponse.hpp>
#include <alibabacloud/models/ListDictsRequest.hpp>
#include <alibabacloud/models/ListDictsResponseBody.hpp>
#include <alibabacloud/models/ListDictsResponse.hpp>
#include <alibabacloud/models/ListEcsInstancesRequest.hpp>
#include <alibabacloud/models/ListEcsInstancesResponseBody.hpp>
#include <alibabacloud/models/ListEcsInstancesResponse.hpp>
#include <alibabacloud/models/ListExtendfilesResponseBody.hpp>
#include <alibabacloud/models/ListExtendfilesResponse.hpp>
#include <alibabacloud/models/ListILMPoliciesRequest.hpp>
#include <alibabacloud/models/ListILMPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListILMPoliciesResponse.hpp>
#include <alibabacloud/models/ListIndexTemplatesRequest.hpp>
#include <alibabacloud/models/ListIndexTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListIndexTemplatesResponse.hpp>
#include <alibabacloud/models/ListInstanceRequest.hpp>
#include <alibabacloud/models/ListInstanceResponseBody.hpp>
#include <alibabacloud/models/ListInstanceResponse.hpp>
#include <alibabacloud/models/ListInstanceHistoryEventsRequest.hpp>
#include <alibabacloud/models/ListInstanceHistoryEventsShrinkRequest.hpp>
#include <alibabacloud/models/ListInstanceHistoryEventsResponseBody.hpp>
#include <alibabacloud/models/ListInstanceHistoryEventsResponse.hpp>
#include <alibabacloud/models/ListInstanceIndicesRequest.hpp>
#include <alibabacloud/models/ListInstanceIndicesResponseBody.hpp>
#include <alibabacloud/models/ListInstanceIndicesResponse.hpp>
#include <alibabacloud/models/ListKibanaPluginsRequest.hpp>
#include <alibabacloud/models/ListKibanaPluginsResponseBody.hpp>
#include <alibabacloud/models/ListKibanaPluginsResponse.hpp>
#include <alibabacloud/models/ListKibanaPvlNetworkResponseBody.hpp>
#include <alibabacloud/models/ListKibanaPvlNetworkResponse.hpp>
#include <alibabacloud/models/ListLogstashRequest.hpp>
#include <alibabacloud/models/ListLogstashResponseBody.hpp>
#include <alibabacloud/models/ListLogstashResponse.hpp>
#include <alibabacloud/models/ListLogstashLogRequest.hpp>
#include <alibabacloud/models/ListLogstashLogResponseBody.hpp>
#include <alibabacloud/models/ListLogstashLogResponse.hpp>
#include <alibabacloud/models/ListLogstashPluginsRequest.hpp>
#include <alibabacloud/models/ListLogstashPluginsResponseBody.hpp>
#include <alibabacloud/models/ListLogstashPluginsResponse.hpp>
#include <alibabacloud/models/ListNodesRequest.hpp>
#include <alibabacloud/models/ListNodesResponseBody.hpp>
#include <alibabacloud/models/ListNodesResponse.hpp>
#include <alibabacloud/models/ListPipelineRequest.hpp>
#include <alibabacloud/models/ListPipelineResponseBody.hpp>
#include <alibabacloud/models/ListPipelineResponse.hpp>
#include <alibabacloud/models/ListPipelineIdsRequest.hpp>
#include <alibabacloud/models/ListPipelineIdsResponseBody.hpp>
#include <alibabacloud/models/ListPipelineIdsResponse.hpp>
#include <alibabacloud/models/ListPluginsRequest.hpp>
#include <alibabacloud/models/ListPluginsResponseBody.hpp>
#include <alibabacloud/models/ListPluginsResponse.hpp>
#include <alibabacloud/models/ListSearchLogRequest.hpp>
#include <alibabacloud/models/ListSearchLogResponseBody.hpp>
#include <alibabacloud/models/ListSearchLogResponse.hpp>
#include <alibabacloud/models/ListShardRecoveriesRequest.hpp>
#include <alibabacloud/models/ListShardRecoveriesResponseBody.hpp>
#include <alibabacloud/models/ListShardRecoveriesResponse.hpp>
#include <alibabacloud/models/ListSnapshotReposByInstanceIdResponseBody.hpp>
#include <alibabacloud/models/ListSnapshotReposByInstanceIdResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagsRequest.hpp>
#include <alibabacloud/models/ListTagsResponseBody.hpp>
#include <alibabacloud/models/ListTagsResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointsRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponse.hpp>
#include <alibabacloud/models/MigrateToOtherZoneRequest.hpp>
#include <alibabacloud/models/MigrateToOtherZoneResponseBody.hpp>
#include <alibabacloud/models/MigrateToOtherZoneResponse.hpp>
#include <alibabacloud/models/ModifyDeployMachineRequest.hpp>
#include <alibabacloud/models/ModifyDeployMachineResponseBody.hpp>
#include <alibabacloud/models/ModifyDeployMachineResponse.hpp>
#include <alibabacloud/models/ModifyElastictaskRequest.hpp>
#include <alibabacloud/models/ModifyElastictaskResponseBody.hpp>
#include <alibabacloud/models/ModifyElastictaskResponse.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceMaintainTimeResponse.hpp>
#include <alibabacloud/models/ModifyWhiteIpsRequest.hpp>
#include <alibabacloud/models/ModifyWhiteIpsResponseBody.hpp>
#include <alibabacloud/models/ModifyWhiteIpsResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/OpenDiagnosisRequest.hpp>
#include <alibabacloud/models/OpenDiagnosisResponseBody.hpp>
#include <alibabacloud/models/OpenDiagnosisResponse.hpp>
#include <alibabacloud/models/OpenHttpsRequest.hpp>
#include <alibabacloud/models/OpenHttpsResponseBody.hpp>
#include <alibabacloud/models/OpenHttpsResponse.hpp>
#include <alibabacloud/models/PostEmonTryAlarmRuleRequest.hpp>
#include <alibabacloud/models/PostEmonTryAlarmRuleResponseBody.hpp>
#include <alibabacloud/models/PostEmonTryAlarmRuleResponse.hpp>
#include <alibabacloud/models/RecommendTemplatesRequest.hpp>
#include <alibabacloud/models/RecommendTemplatesResponseBody.hpp>
#include <alibabacloud/models/RecommendTemplatesResponse.hpp>
#include <alibabacloud/models/ReinstallCollectorRequest.hpp>
#include <alibabacloud/models/ReinstallCollectorResponseBody.hpp>
#include <alibabacloud/models/ReinstallCollectorResponse.hpp>
#include <alibabacloud/models/RenewInstanceRequest.hpp>
#include <alibabacloud/models/RenewInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewInstanceResponse.hpp>
#include <alibabacloud/models/RenewLogstashRequest.hpp>
#include <alibabacloud/models/RenewLogstashResponseBody.hpp>
#include <alibabacloud/models/RenewLogstashResponse.hpp>
#include <alibabacloud/models/RestartCollectorRequest.hpp>
#include <alibabacloud/models/RestartCollectorResponseBody.hpp>
#include <alibabacloud/models/RestartCollectorResponse.hpp>
#include <alibabacloud/models/RestartInstanceRequest.hpp>
#include <alibabacloud/models/RestartInstanceResponseBody.hpp>
#include <alibabacloud/models/RestartInstanceResponse.hpp>
#include <alibabacloud/models/RestartLogstashRequest.hpp>
#include <alibabacloud/models/RestartLogstashResponseBody.hpp>
#include <alibabacloud/models/RestartLogstashResponse.hpp>
#include <alibabacloud/models/ResumeElasticsearchTaskRequest.hpp>
#include <alibabacloud/models/ResumeElasticsearchTaskResponseBody.hpp>
#include <alibabacloud/models/ResumeElasticsearchTaskResponse.hpp>
#include <alibabacloud/models/ResumeLogstashTaskRequest.hpp>
#include <alibabacloud/models/ResumeLogstashTaskResponseBody.hpp>
#include <alibabacloud/models/ResumeLogstashTaskResponse.hpp>
#include <alibabacloud/models/RolloverDataStreamRequest.hpp>
#include <alibabacloud/models/RolloverDataStreamResponseBody.hpp>
#include <alibabacloud/models/RolloverDataStreamResponse.hpp>
#include <alibabacloud/models/RunPipelinesRequest.hpp>
#include <alibabacloud/models/RunPipelinesResponseBody.hpp>
#include <alibabacloud/models/RunPipelinesResponse.hpp>
#include <alibabacloud/models/ShrinkNodeRequest.hpp>
#include <alibabacloud/models/ShrinkNodeResponseBody.hpp>
#include <alibabacloud/models/ShrinkNodeResponse.hpp>
#include <alibabacloud/models/StartCollectorRequest.hpp>
#include <alibabacloud/models/StartCollectorResponseBody.hpp>
#include <alibabacloud/models/StartCollectorResponse.hpp>
#include <alibabacloud/models/StopCollectorRequest.hpp>
#include <alibabacloud/models/StopCollectorResponseBody.hpp>
#include <alibabacloud/models/StopCollectorResponse.hpp>
#include <alibabacloud/models/StopPipelinesRequest.hpp>
#include <alibabacloud/models/StopPipelinesResponseBody.hpp>
#include <alibabacloud/models/StopPipelinesResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TransferNodeRequest.hpp>
#include <alibabacloud/models/TransferNodeResponseBody.hpp>
#include <alibabacloud/models/TransferNodeResponse.hpp>
#include <alibabacloud/models/TriggerNetworkRequest.hpp>
#include <alibabacloud/models/TriggerNetworkResponseBody.hpp>
#include <alibabacloud/models/TriggerNetworkResponse.hpp>
#include <alibabacloud/models/TurnOffZoneRequest.hpp>
#include <alibabacloud/models/TurnOffZoneResponseBody.hpp>
#include <alibabacloud/models/TurnOffZoneResponse.hpp>
#include <alibabacloud/models/TurnOnZoneRequest.hpp>
#include <alibabacloud/models/TurnOnZoneResponseBody.hpp>
#include <alibabacloud/models/TurnOnZoneResponse.hpp>
#include <alibabacloud/models/UninstallKibanaPluginRequest.hpp>
#include <alibabacloud/models/UninstallKibanaPluginResponseBody.hpp>
#include <alibabacloud/models/UninstallKibanaPluginResponse.hpp>
#include <alibabacloud/models/UninstallLogstashPluginRequest.hpp>
#include <alibabacloud/models/UninstallLogstashPluginResponseBody.hpp>
#include <alibabacloud/models/UninstallLogstashPluginResponse.hpp>
#include <alibabacloud/models/UninstallPluginRequest.hpp>
#include <alibabacloud/models/UninstallPluginResponseBody.hpp>
#include <alibabacloud/models/UninstallPluginResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAdminPasswordRequest.hpp>
#include <alibabacloud/models/UpdateAdminPasswordResponseBody.hpp>
#include <alibabacloud/models/UpdateAdminPasswordResponse.hpp>
#include <alibabacloud/models/UpdateAdvancedSettingRequest.hpp>
#include <alibabacloud/models/UpdateAdvancedSettingResponseBody.hpp>
#include <alibabacloud/models/UpdateAdvancedSettingResponse.hpp>
#include <alibabacloud/models/UpdateAliwsDictRequest.hpp>
#include <alibabacloud/models/UpdateAliwsDictResponseBody.hpp>
#include <alibabacloud/models/UpdateAliwsDictResponse.hpp>
#include <alibabacloud/models/UpdateBlackIpsRequest.hpp>
#include <alibabacloud/models/UpdateBlackIpsResponseBody.hpp>
#include <alibabacloud/models/UpdateBlackIpsResponse.hpp>
#include <alibabacloud/models/UpdateCollectorRequest.hpp>
#include <alibabacloud/models/UpdateCollectorResponseBody.hpp>
#include <alibabacloud/models/UpdateCollectorResponse.hpp>
#include <alibabacloud/models/UpdateCollectorNameRequest.hpp>
#include <alibabacloud/models/UpdateCollectorNameResponseBody.hpp>
#include <alibabacloud/models/UpdateCollectorNameResponse.hpp>
#include <alibabacloud/models/UpdateComponentIndexRequest.hpp>
#include <alibabacloud/models/UpdateComponentIndexResponseBody.hpp>
#include <alibabacloud/models/UpdateComponentIndexResponse.hpp>
#include <alibabacloud/models/UpdateDescriptionRequest.hpp>
#include <alibabacloud/models/UpdateDescriptionResponseBody.hpp>
#include <alibabacloud/models/UpdateDescriptionResponse.hpp>
#include <alibabacloud/models/UpdateDiagnosisSettingsRequest.hpp>
#include <alibabacloud/models/UpdateDiagnosisSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateDiagnosisSettingsResponse.hpp>
#include <alibabacloud/models/UpdateDictRequest.hpp>
#include <alibabacloud/models/UpdateDictResponseBody.hpp>
#include <alibabacloud/models/UpdateDictResponse.hpp>
#include <alibabacloud/models/UpdateDynamicSettingsRequest.hpp>
#include <alibabacloud/models/UpdateDynamicSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateDynamicSettingsResponse.hpp>
#include <alibabacloud/models/UpdateExtendConfigRequest.hpp>
#include <alibabacloud/models/UpdateExtendConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateExtendConfigResponse.hpp>
#include <alibabacloud/models/UpdateExtendfilesRequest.hpp>
#include <alibabacloud/models/UpdateExtendfilesResponseBody.hpp>
#include <alibabacloud/models/UpdateExtendfilesResponse.hpp>
#include <alibabacloud/models/UpdateHotIkDictsRequest.hpp>
#include <alibabacloud/models/UpdateHotIkDictsResponseBody.hpp>
#include <alibabacloud/models/UpdateHotIkDictsResponse.hpp>
#include <alibabacloud/models/UpdateILMPolicyRequest.hpp>
#include <alibabacloud/models/UpdateILMPolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateILMPolicyResponse.hpp>
#include <alibabacloud/models/UpdateIndexTemplateRequest.hpp>
#include <alibabacloud/models/UpdateIndexTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateIndexTemplateResponse.hpp>
#include <alibabacloud/models/UpdateInstanceRequest.hpp>
#include <alibabacloud/models/UpdateInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceResponse.hpp>
#include <alibabacloud/models/UpdateInstanceChargeTypeRequest.hpp>
#include <alibabacloud/models/UpdateInstanceChargeTypeResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceChargeTypeResponse.hpp>
#include <alibabacloud/models/UpdateInstanceSettingsRequest.hpp>
#include <alibabacloud/models/UpdateInstanceSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceSettingsResponse.hpp>
#include <alibabacloud/models/UpdateKibanaPvlNetworkRequest.hpp>
#include <alibabacloud/models/UpdateKibanaPvlNetworkResponseBody.hpp>
#include <alibabacloud/models/UpdateKibanaPvlNetworkResponse.hpp>
#include <alibabacloud/models/UpdateKibanaSettingsRequest.hpp>
#include <alibabacloud/models/UpdateKibanaSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateKibanaSettingsResponse.hpp>
#include <alibabacloud/models/UpdateKibanaWhiteIpsRequest.hpp>
#include <alibabacloud/models/UpdateKibanaWhiteIpsResponseBody.hpp>
#include <alibabacloud/models/UpdateKibanaWhiteIpsResponse.hpp>
#include <alibabacloud/models/UpdateLogstashRequest.hpp>
#include <alibabacloud/models/UpdateLogstashResponseBody.hpp>
#include <alibabacloud/models/UpdateLogstashResponse.hpp>
#include <alibabacloud/models/UpdateLogstashChargeTypeRequest.hpp>
#include <alibabacloud/models/UpdateLogstashChargeTypeResponseBody.hpp>
#include <alibabacloud/models/UpdateLogstashChargeTypeResponse.hpp>
#include <alibabacloud/models/UpdateLogstashDescriptionRequest.hpp>
#include <alibabacloud/models/UpdateLogstashDescriptionResponseBody.hpp>
#include <alibabacloud/models/UpdateLogstashDescriptionResponse.hpp>
#include <alibabacloud/models/UpdateLogstashSettingsRequest.hpp>
#include <alibabacloud/models/UpdateLogstashSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateLogstashSettingsResponse.hpp>
#include <alibabacloud/models/UpdatePipelineManagementConfigRequest.hpp>
#include <alibabacloud/models/UpdatePipelineManagementConfigResponseBody.hpp>
#include <alibabacloud/models/UpdatePipelineManagementConfigResponse.hpp>
#include <alibabacloud/models/UpdatePipelinesRequest.hpp>
#include <alibabacloud/models/UpdatePipelinesResponseBody.hpp>
#include <alibabacloud/models/UpdatePipelinesResponse.hpp>
#include <alibabacloud/models/UpdatePrivateNetworkWhiteIpsRequest.hpp>
#include <alibabacloud/models/UpdatePrivateNetworkWhiteIpsResponseBody.hpp>
#include <alibabacloud/models/UpdatePrivateNetworkWhiteIpsResponse.hpp>
#include <alibabacloud/models/UpdatePublicNetworkRequest.hpp>
#include <alibabacloud/models/UpdatePublicNetworkResponseBody.hpp>
#include <alibabacloud/models/UpdatePublicNetworkResponse.hpp>
#include <alibabacloud/models/UpdatePublicWhiteIpsRequest.hpp>
#include <alibabacloud/models/UpdatePublicWhiteIpsResponseBody.hpp>
#include <alibabacloud/models/UpdatePublicWhiteIpsResponse.hpp>
#include <alibabacloud/models/UpdateReadWritePolicyRequest.hpp>
#include <alibabacloud/models/UpdateReadWritePolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateReadWritePolicyResponse.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingRequest.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingResponseBody.hpp>
#include <alibabacloud/models/UpdateSnapshotSettingResponse.hpp>
#include <alibabacloud/models/UpdateSynonymsDictsRequest.hpp>
#include <alibabacloud/models/UpdateSynonymsDictsResponseBody.hpp>
#include <alibabacloud/models/UpdateSynonymsDictsResponse.hpp>
#include <alibabacloud/models/UpdateTemplateRequest.hpp>
#include <alibabacloud/models/UpdateTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateTemplateResponse.hpp>
#include <alibabacloud/models/UpdateWhiteIpsRequest.hpp>
#include <alibabacloud/models/UpdateWhiteIpsResponseBody.hpp>
#include <alibabacloud/models/UpdateWhiteIpsResponse.hpp>
#include <alibabacloud/models/UpdateXpackMonitorConfigRequest.hpp>
#include <alibabacloud/models/UpdateXpackMonitorConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateXpackMonitorConfigResponse.hpp>
#include <alibabacloud/models/UpgradeEngineVersionRequest.hpp>
#include <alibabacloud/models/UpgradeEngineVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeEngineVersionResponse.hpp>
#include <alibabacloud/models/ValidateConnectionRequest.hpp>
#include <alibabacloud/models/ValidateConnectionResponseBody.hpp>
#include <alibabacloud/models/ValidateConnectionResponse.hpp>
#include <alibabacloud/models/ValidateShrinkNodesRequest.hpp>
#include <alibabacloud/models/ValidateShrinkNodesResponseBody.hpp>
#include <alibabacloud/models/ValidateShrinkNodesResponse.hpp>
#include <alibabacloud/models/ValidateSlrPermissionRequest.hpp>
#include <alibabacloud/models/ValidateSlrPermissionResponseBody.hpp>
#include <alibabacloud/models/ValidateSlrPermissionResponse.hpp>
#include <alibabacloud/models/ValidateTransferableNodesRequest.hpp>
#include <alibabacloud/models/ValidateTransferableNodesResponseBody.hpp>
#include <alibabacloud/models/ValidateTransferableNodesResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>

#endif
