// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLOUDAUTHINTL20220809MODEL_HPP_
#define ALIBABACLOUD_CLOUDAUTHINTL20220809MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddressCompareIntlRequest.hpp>
#include <alibabacloud/models/AddressCompareIntlResponseBody.hpp>
#include <alibabacloud/models/AddressCompareIntlResponse.hpp>
#include <alibabacloud/models/AddressVerifyIntlRequest.hpp>
#include <alibabacloud/models/AddressVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/AddressVerifyIntlResponse.hpp>
#include <alibabacloud/models/AddressVerifyV2intlRequest.hpp>
#include <alibabacloud/models/AddressVerifyV2intlResponseBody.hpp>
#include <alibabacloud/models/AddressVerifyV2intlResponse.hpp>
#include <alibabacloud/models/BankMetaVerifyIntlRequest.hpp>
#include <alibabacloud/models/BankMetaVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/BankMetaVerifyIntlResponse.hpp>
#include <alibabacloud/models/CardOcrRequest.hpp>
#include <alibabacloud/models/CardOcrResponseBody.hpp>
#include <alibabacloud/models/CardOcrResponse.hpp>
#include <alibabacloud/models/CheckResultRequest.hpp>
#include <alibabacloud/models/CheckResultResponseBody.hpp>
#include <alibabacloud/models/CheckResultResponse.hpp>
#include <alibabacloud/models/CheckVerifyLogRequest.hpp>
#include <alibabacloud/models/CheckVerifyLogResponseBody.hpp>
#include <alibabacloud/models/CheckVerifyLogResponse.hpp>
#include <alibabacloud/models/CredentialGetResultIntlRequest.hpp>
#include <alibabacloud/models/CredentialGetResultIntlResponseBody.hpp>
#include <alibabacloud/models/CredentialGetResultIntlResponse.hpp>
#include <alibabacloud/models/CredentialRecognitionIntlRequest.hpp>
#include <alibabacloud/models/CredentialRecognitionIntlResponseBody.hpp>
#include <alibabacloud/models/CredentialRecognitionIntlResponse.hpp>
#include <alibabacloud/models/CredentialSubmitIntlRequest.hpp>
#include <alibabacloud/models/CredentialSubmitIntlResponseBody.hpp>
#include <alibabacloud/models/CredentialSubmitIntlResponse.hpp>
#include <alibabacloud/models/CredentialVerifyIntlRequest.hpp>
#include <alibabacloud/models/CredentialVerifyIntlAdvanceRequest.hpp>
#include <alibabacloud/models/CredentialVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/CredentialVerifyIntlResponse.hpp>
#include <alibabacloud/models/DeepfakeDetectIntlRequest.hpp>
#include <alibabacloud/models/DeepfakeDetectIntlResponseBody.hpp>
#include <alibabacloud/models/DeepfakeDetectIntlResponse.hpp>
#include <alibabacloud/models/DeleteFaceGroupRequest.hpp>
#include <alibabacloud/models/DeleteFaceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteFaceGroupResponse.hpp>
#include <alibabacloud/models/DeleteFaceRecordRequest.hpp>
#include <alibabacloud/models/DeleteFaceRecordResponseBody.hpp>
#include <alibabacloud/models/DeleteFaceRecordResponse.hpp>
#include <alibabacloud/models/DeleteVerifyResultRequest.hpp>
#include <alibabacloud/models/DeleteVerifyResultResponseBody.hpp>
#include <alibabacloud/models/DeleteVerifyResultResponse.hpp>
#include <alibabacloud/models/DocOcrRequest.hpp>
#include <alibabacloud/models/DocOcrResponseBody.hpp>
#include <alibabacloud/models/DocOcrResponse.hpp>
#include <alibabacloud/models/DocOcrMaxRequest.hpp>
#include <alibabacloud/models/DocOcrMaxResponseBody.hpp>
#include <alibabacloud/models/DocOcrMaxResponse.hpp>
#include <alibabacloud/models/EkycVerifyRequest.hpp>
#include <alibabacloud/models/EkycVerifyResponseBody.hpp>
#include <alibabacloud/models/EkycVerifyResponse.hpp>
#include <alibabacloud/models/FaceCompareRequest.hpp>
#include <alibabacloud/models/FaceCompareResponseBody.hpp>
#include <alibabacloud/models/FaceCompareResponse.hpp>
#include <alibabacloud/models/FaceCrossCompareIntlRequest.hpp>
#include <alibabacloud/models/FaceCrossCompareIntlResponseBody.hpp>
#include <alibabacloud/models/FaceCrossCompareIntlResponse.hpp>
#include <alibabacloud/models/FaceDuplicationCheckIntlRequest.hpp>
#include <alibabacloud/models/FaceDuplicationCheckIntlResponseBody.hpp>
#include <alibabacloud/models/FaceDuplicationCheckIntlResponse.hpp>
#include <alibabacloud/models/FaceGuardRiskRequest.hpp>
#include <alibabacloud/models/FaceGuardRiskResponseBody.hpp>
#include <alibabacloud/models/FaceGuardRiskResponse.hpp>
#include <alibabacloud/models/FaceLivenessRequest.hpp>
#include <alibabacloud/models/FaceLivenessResponseBody.hpp>
#include <alibabacloud/models/FaceLivenessResponse.hpp>
#include <alibabacloud/models/FraudResultCallBackRequest.hpp>
#include <alibabacloud/models/FraudResultCallBackResponseBody.hpp>
#include <alibabacloud/models/FraudResultCallBackResponse.hpp>
#include <alibabacloud/models/Id2metaPeriodVerifyIntlRequest.hpp>
#include <alibabacloud/models/Id2metaPeriodVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/Id2metaPeriodVerifyIntlResponse.hpp>
#include <alibabacloud/models/Id2metaVerifyIntlRequest.hpp>
#include <alibabacloud/models/Id2metaVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/Id2metaVerifyIntlResponse.hpp>
#include <alibabacloud/models/InitializeRequest.hpp>
#include <alibabacloud/models/InitializeShrinkRequest.hpp>
#include <alibabacloud/models/InitializeResponseBody.hpp>
#include <alibabacloud/models/InitializeResponse.hpp>
#include <alibabacloud/models/KeepaliveIntlResponseBody.hpp>
#include <alibabacloud/models/KeepaliveIntlResponse.hpp>
#include <alibabacloud/models/Mobile2metaVerifyIntlRequest.hpp>
#include <alibabacloud/models/Mobile2metaVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/Mobile2metaVerifyIntlResponse.hpp>
#include <alibabacloud/models/Mobile3metaVerifyIntlRequest.hpp>
#include <alibabacloud/models/Mobile3metaVerifyIntlResponseBody.hpp>
#include <alibabacloud/models/Mobile3metaVerifyIntlResponse.hpp>
#include <alibabacloud/models/ModifyFaceGroupRequest.hpp>
#include <alibabacloud/models/ModifyFaceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyFaceGroupResponse.hpp>
#include <alibabacloud/models/ModifyFaceRecordRequest.hpp>
#include <alibabacloud/models/ModifyFaceRecordResponseBody.hpp>
#include <alibabacloud/models/ModifyFaceRecordResponse.hpp>
#include <alibabacloud/models/QueryFaceGroupRequest.hpp>
#include <alibabacloud/models/QueryFaceGroupResponseBody.hpp>
#include <alibabacloud/models/QueryFaceGroupResponse.hpp>
#include <alibabacloud/models/QueryFaceRecordRequest.hpp>
#include <alibabacloud/models/QueryFaceRecordResponseBody.hpp>
#include <alibabacloud/models/QueryFaceRecordResponse.hpp>
#include <alibabacloud/models/TempAccessTokenIntlRequest.hpp>
#include <alibabacloud/models/TempAccessTokenIntlResponseBody.hpp>
#include <alibabacloud/models/TempAccessTokenIntlResponse.hpp>
#include <alibabacloud/models/TempOssUrlIntlRequest.hpp>
#include <alibabacloud/models/TempOssUrlIntlResponseBody.hpp>
#include <alibabacloud/models/TempOssUrlIntlResponse.hpp>
#include <alibabacloud/models/AddressCompareIntlResponseBodyResult.hpp>
#include <alibabacloud/models/AddressVerifyIntlResponseBodyResultObject.hpp>
#include <alibabacloud/models/AddressVerifyV2intlResponseBodyResult.hpp>
#include <alibabacloud/models/BankMetaVerifyIntlResponseBodyResultObject.hpp>
#include <alibabacloud/models/CardOcrResponseBodyResult.hpp>
#include <alibabacloud/models/CheckResultResponseBodyResult.hpp>
#include <alibabacloud/models/CheckVerifyLogResponseBodyResult.hpp>
#include <alibabacloud/models/CredentialGetResultIntlResponseBodyResult.hpp>
#include <alibabacloud/models/CredentialRecognitionIntlResponseBodyResult.hpp>
#include <alibabacloud/models/CredentialSubmitIntlResponseBodyResult.hpp>
#include <alibabacloud/models/CredentialVerifyIntlResponseBodyResultObject.hpp>
#include <alibabacloud/models/DeepfakeDetectIntlResponseBodyResultObject.hpp>
#include <alibabacloud/models/DeleteVerifyResultResponseBodyResult.hpp>
#include <alibabacloud/models/DocOcrResponseBodyResult.hpp>
#include <alibabacloud/models/DocOcrMaxResponseBodyResult.hpp>
#include <alibabacloud/models/EkycVerifyResponseBodyResult.hpp>
#include <alibabacloud/models/FaceCompareResponseBodyResult.hpp>
#include <alibabacloud/models/FaceCrossCompareIntlResponseBodyResult.hpp>
#include <alibabacloud/models/FaceDuplicationCheckIntlResponseBodyResult.hpp>
#include <alibabacloud/models/FaceGuardRiskResponseBodyResult.hpp>
#include <alibabacloud/models/FaceLivenessResponseBodyResultExtFaceInfo.hpp>
#include <alibabacloud/models/FaceLivenessResponseBodyResult.hpp>
#include <alibabacloud/models/Id2metaPeriodVerifyIntlResponseBodyResult.hpp>
#include <alibabacloud/models/Id2metaVerifyIntlResponseBodyResult.hpp>
#include <alibabacloud/models/InitializeResponseBodyResult.hpp>
#include <alibabacloud/models/KeepaliveIntlResponseBodyResult.hpp>
#include <alibabacloud/models/Mobile2metaVerifyIntlResponseBodyResult.hpp>
#include <alibabacloud/models/Mobile3metaVerifyIntlResponseBodyResult.hpp>
#include <alibabacloud/models/QueryFaceGroupResponseBodyItems.hpp>
#include <alibabacloud/models/QueryFaceRecordResponseBodyItems.hpp>
#include <alibabacloud/models/TempAccessTokenIntlResponseBodyData.hpp>
#include <alibabacloud/models/TempOssUrlIntlResponseBodyData.hpp>

#endif
