// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_CREATESCHEDULEDTASKRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_CREATESCHEDULEDTASKRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Ess20220222
{
namespace Models
{
  class CreateScheduledTaskResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const CreateScheduledTaskResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(ScheduledTaskId, scheduledTaskId_);
    };
    friend void from_json(const Darabonba::Json& j, CreateScheduledTaskResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(ScheduledTaskId, scheduledTaskId_);
    };
    CreateScheduledTaskResponseBody() = default ;
    CreateScheduledTaskResponseBody(const CreateScheduledTaskResponseBody &) = default ;
    CreateScheduledTaskResponseBody(CreateScheduledTaskResponseBody &&) = default ;
    CreateScheduledTaskResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~CreateScheduledTaskResponseBody() = default ;
    CreateScheduledTaskResponseBody& operator=(const CreateScheduledTaskResponseBody &) = default ;
    CreateScheduledTaskResponseBody& operator=(CreateScheduledTaskResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->requestId_ == nullptr
        && return this->scheduledTaskId_ == nullptr; };
    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline CreateScheduledTaskResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // scheduledTaskId Field Functions 
    bool hasScheduledTaskId() const { return this->scheduledTaskId_ != nullptr;};
    void deleteScheduledTaskId() { this->scheduledTaskId_ = nullptr;};
    inline string scheduledTaskId() const { DARABONBA_PTR_GET_DEFAULT(scheduledTaskId_, "") };
    inline CreateScheduledTaskResponseBody& setScheduledTaskId(string scheduledTaskId) { DARABONBA_PTR_SET_VALUE(scheduledTaskId_, scheduledTaskId) };


  protected:
    // The ID of the request.
    std::shared_ptr<string> requestId_ = nullptr;
    // The globally unique ID of the scheduled task. The globally unique ID is generated by the system.
    std::shared_ptr<string> scheduledTaskId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Ess20220222
#endif
