// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_CREATESCALINGRULERESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_CREATESCALINGRULERESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Ess20220222
{
namespace Models
{
  class CreateScalingRuleResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const CreateScalingRuleResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(ScalingRuleAri, scalingRuleAri_);
      DARABONBA_PTR_TO_JSON(ScalingRuleId, scalingRuleId_);
    };
    friend void from_json(const Darabonba::Json& j, CreateScalingRuleResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(ScalingRuleAri, scalingRuleAri_);
      DARABONBA_PTR_FROM_JSON(ScalingRuleId, scalingRuleId_);
    };
    CreateScalingRuleResponseBody() = default ;
    CreateScalingRuleResponseBody(const CreateScalingRuleResponseBody &) = default ;
    CreateScalingRuleResponseBody(CreateScalingRuleResponseBody &&) = default ;
    CreateScalingRuleResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~CreateScalingRuleResponseBody() = default ;
    CreateScalingRuleResponseBody& operator=(const CreateScalingRuleResponseBody &) = default ;
    CreateScalingRuleResponseBody& operator=(CreateScalingRuleResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->requestId_ == nullptr
        && this->scalingRuleAri_ == nullptr && this->scalingRuleId_ == nullptr; };
    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string getRequestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline CreateScalingRuleResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // scalingRuleAri Field Functions 
    bool hasScalingRuleAri() const { return this->scalingRuleAri_ != nullptr;};
    void deleteScalingRuleAri() { this->scalingRuleAri_ = nullptr;};
    inline string getScalingRuleAri() const { DARABONBA_PTR_GET_DEFAULT(scalingRuleAri_, "") };
    inline CreateScalingRuleResponseBody& setScalingRuleAri(string scalingRuleAri) { DARABONBA_PTR_SET_VALUE(scalingRuleAri_, scalingRuleAri) };


    // scalingRuleId Field Functions 
    bool hasScalingRuleId() const { return this->scalingRuleId_ != nullptr;};
    void deleteScalingRuleId() { this->scalingRuleId_ = nullptr;};
    inline string getScalingRuleId() const { DARABONBA_PTR_GET_DEFAULT(scalingRuleId_, "") };
    inline CreateScalingRuleResponseBody& setScalingRuleId(string scalingRuleId) { DARABONBA_PTR_SET_VALUE(scalingRuleId_, scalingRuleId) };


  protected:
    // The ID of the request.
    shared_ptr<string> requestId_ {};
    // The unique identifier of the scaling rule.
    shared_ptr<string> scalingRuleAri_ {};
    // The ID of the scaling rule, which is generated by the system and is globally unique.
    shared_ptr<string> scalingRuleId_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Ess20220222
#endif
