// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DCDN20180115MODEL_HPP_
#define ALIBABACLOUD_DCDN20180115MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/WafQuotaInteger.hpp>
#include <alibabacloud/models/WafQuotaString.hpp>
#include <alibabacloud/models/AddDcdnDomainRequest.hpp>
#include <alibabacloud/models/AddDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/AddDcdnDomainResponse.hpp>
#include <alibabacloud/models/AddDcdnIpaDomainRequest.hpp>
#include <alibabacloud/models/AddDcdnIpaDomainResponseBody.hpp>
#include <alibabacloud/models/AddDcdnIpaDomainResponse.hpp>
#include <alibabacloud/models/BatchAddDcdnDomainRequest.hpp>
#include <alibabacloud/models/BatchAddDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/BatchAddDcdnDomainResponse.hpp>
#include <alibabacloud/models/BatchCreateDcdnWafRulesRequest.hpp>
#include <alibabacloud/models/BatchCreateDcdnWafRulesResponseBody.hpp>
#include <alibabacloud/models/BatchCreateDcdnWafRulesResponse.hpp>
#include <alibabacloud/models/BatchDeleteDcdnDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDcdnDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvShrinkRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvResponse.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvWithHighCapacityRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvWithHighCapacityAdvanceRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvWithHighCapacityResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDcdnKvWithHighCapacityResponse.hpp>
#include <alibabacloud/models/BatchDeleteDcdnWafRulesRequest.hpp>
#include <alibabacloud/models/BatchDeleteDcdnWafRulesResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteDcdnWafRulesResponse.hpp>
#include <alibabacloud/models/BatchModifyDcdnWafRulesRequest.hpp>
#include <alibabacloud/models/BatchModifyDcdnWafRulesResponseBody.hpp>
#include <alibabacloud/models/BatchModifyDcdnWafRulesResponse.hpp>
#include <alibabacloud/models/BatchPutDcdnKvRequest.hpp>
#include <alibabacloud/models/BatchPutDcdnKvShrinkRequest.hpp>
#include <alibabacloud/models/BatchPutDcdnKvResponseBody.hpp>
#include <alibabacloud/models/BatchPutDcdnKvResponse.hpp>
#include <alibabacloud/models/BatchPutDcdnKvWithHighCapacityRequest.hpp>
#include <alibabacloud/models/BatchPutDcdnKvWithHighCapacityAdvanceRequest.hpp>
#include <alibabacloud/models/BatchPutDcdnKvWithHighCapacityResponseBody.hpp>
#include <alibabacloud/models/BatchPutDcdnKvWithHighCapacityResponse.hpp>
#include <alibabacloud/models/BatchSetDcdnDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchSetDcdnDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchSetDcdnDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchSetDcdnIpaDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchSetDcdnIpaDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchSetDcdnIpaDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchSetDcdnWafDomainConfigsRequest.hpp>
#include <alibabacloud/models/BatchSetDcdnWafDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/BatchSetDcdnWafDomainConfigsResponse.hpp>
#include <alibabacloud/models/BatchStartDcdnDomainRequest.hpp>
#include <alibabacloud/models/BatchStartDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/BatchStartDcdnDomainResponse.hpp>
#include <alibabacloud/models/BatchStopDcdnDomainRequest.hpp>
#include <alibabacloud/models/BatchStopDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/BatchStopDcdnDomainResponse.hpp>
#include <alibabacloud/models/CheckDcdnProjectExistRequest.hpp>
#include <alibabacloud/models/CheckDcdnProjectExistResponseBody.hpp>
#include <alibabacloud/models/CheckDcdnProjectExistResponse.hpp>
#include <alibabacloud/models/CommitStagingRoutineCodeRequest.hpp>
#include <alibabacloud/models/CommitStagingRoutineCodeResponseBody.hpp>
#include <alibabacloud/models/CommitStagingRoutineCodeResponse.hpp>
#include <alibabacloud/models/CreateDcdnCertificateSigningRequestRequest.hpp>
#include <alibabacloud/models/CreateDcdnCertificateSigningRequestResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnCertificateSigningRequestResponse.hpp>
#include <alibabacloud/models/CreateDcdnDeliverTaskRequest.hpp>
#include <alibabacloud/models/CreateDcdnDeliverTaskResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnDeliverTaskResponse.hpp>
#include <alibabacloud/models/CreateDcdnSlsrealTimeLogDeliveryRequest.hpp>
#include <alibabacloud/models/CreateDcdnSlsrealTimeLogDeliveryResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnSlsrealTimeLogDeliveryResponse.hpp>
#include <alibabacloud/models/CreateDcdnSubTaskRequest.hpp>
#include <alibabacloud/models/CreateDcdnSubTaskResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnSubTaskResponse.hpp>
#include <alibabacloud/models/CreateDcdnWafGroupRequest.hpp>
#include <alibabacloud/models/CreateDcdnWafGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnWafGroupResponse.hpp>
#include <alibabacloud/models/CreateDcdnWafPolicyRequest.hpp>
#include <alibabacloud/models/CreateDcdnWafPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateDcdnWafPolicyResponse.hpp>
#include <alibabacloud/models/CreateRoutineRequest.hpp>
#include <alibabacloud/models/CreateRoutineShrinkRequest.hpp>
#include <alibabacloud/models/CreateRoutineResponseBody.hpp>
#include <alibabacloud/models/CreateRoutineResponse.hpp>
#include <alibabacloud/models/CreateSlrAndSlsProjectRequest.hpp>
#include <alibabacloud/models/CreateSlrAndSlsProjectResponseBody.hpp>
#include <alibabacloud/models/CreateSlrAndSlsProjectResponse.hpp>
#include <alibabacloud/models/DeleteCustomDomainSampleRateRequest.hpp>
#include <alibabacloud/models/DeleteCustomDomainSampleRateResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomDomainSampleRateResponse.hpp>
#include <alibabacloud/models/DeleteDcdnDeliverTaskRequest.hpp>
#include <alibabacloud/models/DeleteDcdnDeliverTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnDeliverTaskResponse.hpp>
#include <alibabacloud/models/DeleteDcdnDomainRequest.hpp>
#include <alibabacloud/models/DeleteDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnDomainResponse.hpp>
#include <alibabacloud/models/DeleteDcdnIpaDomainRequest.hpp>
#include <alibabacloud/models/DeleteDcdnIpaDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnIpaDomainResponse.hpp>
#include <alibabacloud/models/DeleteDcdnIpaSpecificConfigRequest.hpp>
#include <alibabacloud/models/DeleteDcdnIpaSpecificConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnIpaSpecificConfigResponse.hpp>
#include <alibabacloud/models/DeleteDcdnKvRequest.hpp>
#include <alibabacloud/models/DeleteDcdnKvResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnKvResponse.hpp>
#include <alibabacloud/models/DeleteDcdnKvNamespaceRequest.hpp>
#include <alibabacloud/models/DeleteDcdnKvNamespaceResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnKvNamespaceResponse.hpp>
#include <alibabacloud/models/DeleteDcdnRealTimeLogProjectRequest.hpp>
#include <alibabacloud/models/DeleteDcdnRealTimeLogProjectResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnRealTimeLogProjectResponse.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificConfigRequest.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificConfigResponse.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificStagingConfigRequest.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificStagingConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnSpecificStagingConfigResponse.hpp>
#include <alibabacloud/models/DeleteDcdnSubTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnSubTaskResponse.hpp>
#include <alibabacloud/models/DeleteDcdnUserConfigRequest.hpp>
#include <alibabacloud/models/DeleteDcdnUserConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnUserConfigResponse.hpp>
#include <alibabacloud/models/DeleteDcdnWafGroupRequest.hpp>
#include <alibabacloud/models/DeleteDcdnWafGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnWafGroupResponse.hpp>
#include <alibabacloud/models/DeleteDcdnWafPolicyRequest.hpp>
#include <alibabacloud/models/DeleteDcdnWafPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteDcdnWafPolicyResponse.hpp>
#include <alibabacloud/models/DeleteRoutineRequest.hpp>
#include <alibabacloud/models/DeleteRoutineResponseBody.hpp>
#include <alibabacloud/models/DeleteRoutineResponse.hpp>
#include <alibabacloud/models/DeleteRoutineCodeRevisionRequest.hpp>
#include <alibabacloud/models/DeleteRoutineCodeRevisionResponseBody.hpp>
#include <alibabacloud/models/DeleteRoutineCodeRevisionResponse.hpp>
#include <alibabacloud/models/DeleteRoutineConfEnvsRequest.hpp>
#include <alibabacloud/models/DeleteRoutineConfEnvsShrinkRequest.hpp>
#include <alibabacloud/models/DeleteRoutineConfEnvsResponseBody.hpp>
#include <alibabacloud/models/DeleteRoutineConfEnvsResponse.hpp>
#include <alibabacloud/models/DescribeCustomDomainSampleRateRequest.hpp>
#include <alibabacloud/models/DescribeCustomDomainSampleRateResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomDomainSampleRateResponse.hpp>
#include <alibabacloud/models/DescribeDcdnAclFieldsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnAclFieldsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnAclFieldsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnBgpBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnBgpBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnBgpBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnBgpTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnBgpTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnBgpTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnBlockedRegionsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnBlockedRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnBlockedRegionsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateDetailRequest.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateDetailResponse.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDdosServiceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDdosServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDdosServiceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDdosSpecInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDdosSpecInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDeletedDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDeletedDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDeletedDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDeliverListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDeliverListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDeliverListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataByLayerRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataByLayerResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataByLayerResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainByCertificateRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainByCertificateResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainByCertificateResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCcActivityLogRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCcActivityLogResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCcActivityLogResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCertificateInfoRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCertificateInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCertificateInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCnameRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCnameResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCnameResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHitRateDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHitRateDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHitRateDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataByLayerRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataByLayerResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataByLayerResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaConnDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaConnDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaConnDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIspDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIspDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIspDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPropertyRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPropertyResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPropertyResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPvDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPvDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPvDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataByLayerRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataByLayerResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataByLayerResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeByteHitRateDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeByteHitRateDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeByteHitRateDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeDetailDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeDetailDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeDetailDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeQpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeQpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeQpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeReqHitRateDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeReqHitRateDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeReqHitRateDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRegionDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRegionDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRegionDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainStagingConfigRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainStagingConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainStagingConfigResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopReferVisitRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopReferVisitResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopReferVisitResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUsageDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUsageDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUsageDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUvDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUvDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUvDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketBpsDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketBpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketBpsDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnDomainsBySourceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnDomainsBySourceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnDomainsBySourceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnErUsageDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnErUsageDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnErUsageDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIpconfigRequest.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIpconfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIpconfigResponse.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIphistoryRequest.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIphistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIphistoryResponse.hpp>
#include <alibabacloud/models/DescribeDcdnHttpsDomainListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnHttpsDomainListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnHttpsDomainListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpInfoRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainCidrRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainCidrResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainCidrResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpaServiceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpaServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpaServiceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnKvAccountResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnKvAccountResponse.hpp>
#include <alibabacloud/models/DescribeDcdnKvAccountStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnKvAccountStatusResponse.hpp>
#include <alibabacloud/models/DescribeDcdnKvNamespaceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnKvNamespaceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnKvNamespaceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnL2ipsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnL2ipsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnL2vipsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnL2vipsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnL2vipsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnOriginSiteHealthStatusRequest.hpp>
#include <alibabacloud/models/DescribeDcdnOriginSiteHealthStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnOriginSiteHealthStatusResponse.hpp>
#include <alibabacloud/models/DescribeDcdnRealTimeDeliveryFieldRequest.hpp>
#include <alibabacloud/models/DescribeDcdnRealTimeDeliveryFieldResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnRealTimeDeliveryFieldResponse.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshQuotaRequest.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshQuotaResponse.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTaskByIdRequest.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTaskByIdResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTaskByIdResponse.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTasksRequest.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTasksResponse.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspRequest.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponse.hpp>
#include <alibabacloud/models/DescribeDcdnReportRequest.hpp>
#include <alibabacloud/models/DescribeDcdnReportResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnReportResponse.hpp>
#include <alibabacloud/models/DescribeDcdnReportListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnReportListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnReportListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealTimeLogTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealTimeLogTypeResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealtimeLogDeliveryRequest.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealtimeLogDeliveryResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealtimeLogDeliveryResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateDetailRequest.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateDetailResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListRequest.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSecFuncInfoRequest.hpp>
#include <alibabacloud/models/DescribeDcdnSecFuncInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSecFuncInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSecSpecInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSecSpecInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnServiceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnServiceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnStagingIpResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnStagingIpResponse.hpp>
#include <alibabacloud/models/DescribeDcdnSubListResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnSubListResponse.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesRequest.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesResponse.hpp>
#include <alibabacloud/models/DescribeDcdnTopDomainsByFlowRequest.hpp>
#include <alibabacloud/models/DescribeDcdnTopDomainsByFlowResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnTopDomainsByFlowResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillTypeRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillTypeResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillTypeResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserCertificateExpireCountResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserCertificateExpireCountResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserConfigsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserConfigsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserConfigsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserQuotaRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserQuotaResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserRealTimeDeliveryFieldRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserRealTimeDeliveryFieldResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserRealTimeDeliveryFieldResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserResourcePackageRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserResourcePackageResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserResourcePackageResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropByMinuteRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropByMinuteResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropByMinuteResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserTagsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnUserVipsByDomainRequest.hpp>
#include <alibabacloud/models/DescribeDcdnUserVipsByDomainResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnUserVipsByDomainResponse.hpp>
#include <alibabacloud/models/DescribeDcdnVerifyContentRequest.hpp>
#include <alibabacloud/models/DescribeDcdnVerifyContentResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnVerifyContentResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafBotAppKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafBotAppKeyResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafDefaultRulesRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafDefaultRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafDefaultRulesResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainDetailRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainDetailResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafPoliciesRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafPoliciesResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafPoliciesResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyValidDomainsRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyValidDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyValidDomainsResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafRuleRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafRuleResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafRuleResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafRulesRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafRulesResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafScenesRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafScenesResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafScenesResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafServiceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafServiceResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafSpecInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafSpecInfoResponse.hpp>
#include <alibabacloud/models/DescribeDcdnWafUsageDataRequest.hpp>
#include <alibabacloud/models/DescribeDcdnWafUsageDataResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnWafUsageDataResponse.hpp>
#include <alibabacloud/models/DescribeDcdnsecServiceRequest.hpp>
#include <alibabacloud/models/DescribeDcdnsecServiceResponseBody.hpp>
#include <alibabacloud/models/DescribeDcdnsecServiceResponse.hpp>
#include <alibabacloud/models/DescribeDdosAllEventListRequest.hpp>
#include <alibabacloud/models/DescribeDdosAllEventListResponseBody.hpp>
#include <alibabacloud/models/DescribeDdosAllEventListResponse.hpp>
#include <alibabacloud/models/DescribeEncryptRoutineUidResponseBody.hpp>
#include <alibabacloud/models/DescribeEncryptRoutineUidResponse.hpp>
#include <alibabacloud/models/DescribeHighlightInfoRequest.hpp>
#include <alibabacloud/models/DescribeHighlightInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeHighlightInfoResponse.hpp>
#include <alibabacloud/models/DescribeKvRealTimeQpsDataRequest.hpp>
#include <alibabacloud/models/DescribeKvRealTimeQpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeKvRealTimeQpsDataResponse.hpp>
#include <alibabacloud/models/DescribeKvUsageDataRequest.hpp>
#include <alibabacloud/models/DescribeKvUsageDataResponseBody.hpp>
#include <alibabacloud/models/DescribeKvUsageDataResponse.hpp>
#include <alibabacloud/models/DescribeRddomainConfigRequest.hpp>
#include <alibabacloud/models/DescribeRddomainConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeRddomainConfigResponse.hpp>
#include <alibabacloud/models/DescribeRddomainsRequest.hpp>
#include <alibabacloud/models/DescribeRddomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeRddomainsResponse.hpp>
#include <alibabacloud/models/DescribeRoutineRequest.hpp>
#include <alibabacloud/models/DescribeRoutineResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineResponse.hpp>
#include <alibabacloud/models/DescribeRoutineCanaryEnvsResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineCanaryEnvsResponse.hpp>
#include <alibabacloud/models/DescribeRoutineCodeRevisionRequest.hpp>
#include <alibabacloud/models/DescribeRoutineCodeRevisionResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineCodeRevisionResponse.hpp>
#include <alibabacloud/models/DescribeRoutineRelatedDomainsRequest.hpp>
#include <alibabacloud/models/DescribeRoutineRelatedDomainsResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineRelatedDomainsResponse.hpp>
#include <alibabacloud/models/DescribeRoutineSpecResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineSpecResponse.hpp>
#include <alibabacloud/models/DescribeRoutineUserInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeRoutineUserInfoResponse.hpp>
#include <alibabacloud/models/DescribeUserDcdnIpaStatusRequest.hpp>
#include <alibabacloud/models/DescribeUserDcdnIpaStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeUserDcdnIpaStatusResponse.hpp>
#include <alibabacloud/models/DescribeUserDcdnStatusRequest.hpp>
#include <alibabacloud/models/DescribeUserDcdnStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeUserDcdnStatusResponse.hpp>
#include <alibabacloud/models/DescribeUserErStatusRequest.hpp>
#include <alibabacloud/models/DescribeUserErStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeUserErStatusResponse.hpp>
#include <alibabacloud/models/DescribeUserLogserviceStatusRequest.hpp>
#include <alibabacloud/models/DescribeUserLogserviceStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeUserLogserviceStatusResponse.hpp>
#include <alibabacloud/models/EditRoutineConfRequest.hpp>
#include <alibabacloud/models/EditRoutineConfShrinkRequest.hpp>
#include <alibabacloud/models/EditRoutineConfResponseBody.hpp>
#include <alibabacloud/models/EditRoutineConfResponse.hpp>
#include <alibabacloud/models/GetDcdnKvRequest.hpp>
#include <alibabacloud/models/GetDcdnKvResponseBody.hpp>
#include <alibabacloud/models/GetDcdnKvResponse.hpp>
#include <alibabacloud/models/GetDcdnKvDetailRequest.hpp>
#include <alibabacloud/models/GetDcdnKvDetailResponseBody.hpp>
#include <alibabacloud/models/GetDcdnKvDetailResponse.hpp>
#include <alibabacloud/models/GetDcdnKvStatusRequest.hpp>
#include <alibabacloud/models/GetDcdnKvStatusResponseBody.hpp>
#include <alibabacloud/models/GetDcdnKvStatusResponse.hpp>
#include <alibabacloud/models/ListDcdnKvRequest.hpp>
#include <alibabacloud/models/ListDcdnKvResponseBody.hpp>
#include <alibabacloud/models/ListDcdnKvResponse.hpp>
#include <alibabacloud/models/ListDcdnRealTimeDeliveryProjectRequest.hpp>
#include <alibabacloud/models/ListDcdnRealTimeDeliveryProjectResponseBody.hpp>
#include <alibabacloud/models/ListDcdnRealTimeDeliveryProjectResponse.hpp>
#include <alibabacloud/models/ModifyCustomDomainSampleRateRequest.hpp>
#include <alibabacloud/models/ModifyCustomDomainSampleRateResponseBody.hpp>
#include <alibabacloud/models/ModifyCustomDomainSampleRateResponse.hpp>
#include <alibabacloud/models/ModifyDcdnDomainSchdmByPropertyRequest.hpp>
#include <alibabacloud/models/ModifyDcdnDomainSchdmByPropertyResponseBody.hpp>
#include <alibabacloud/models/ModifyDcdnDomainSchdmByPropertyResponse.hpp>
#include <alibabacloud/models/ModifyDcdnWafGroupRequest.hpp>
#include <alibabacloud/models/ModifyDcdnWafGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDcdnWafGroupResponse.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyRequest.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyResponse.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyDomainsRequest.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyDomainsResponseBody.hpp>
#include <alibabacloud/models/ModifyDcdnWafPolicyDomainsResponse.hpp>
#include <alibabacloud/models/ModifyDcdnWafRuleRequest.hpp>
#include <alibabacloud/models/ModifyDcdnWafRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyDcdnWafRuleResponse.hpp>
#include <alibabacloud/models/OpenDcdnServiceRequest.hpp>
#include <alibabacloud/models/OpenDcdnServiceResponseBody.hpp>
#include <alibabacloud/models/OpenDcdnServiceResponse.hpp>
#include <alibabacloud/models/PreloadDcdnObjectCachesRequest.hpp>
#include <alibabacloud/models/PreloadDcdnObjectCachesResponseBody.hpp>
#include <alibabacloud/models/PreloadDcdnObjectCachesResponse.hpp>
#include <alibabacloud/models/PublishDcdnStagingConfigToProductionRequest.hpp>
#include <alibabacloud/models/PublishDcdnStagingConfigToProductionResponseBody.hpp>
#include <alibabacloud/models/PublishDcdnStagingConfigToProductionResponse.hpp>
#include <alibabacloud/models/PublishRoutineCodeRevisionRequest.hpp>
#include <alibabacloud/models/PublishRoutineCodeRevisionShrinkRequest.hpp>
#include <alibabacloud/models/PublishRoutineCodeRevisionResponseBody.hpp>
#include <alibabacloud/models/PublishRoutineCodeRevisionResponse.hpp>
#include <alibabacloud/models/PutDcdnKvRequest.hpp>
#include <alibabacloud/models/PutDcdnKvResponseBody.hpp>
#include <alibabacloud/models/PutDcdnKvResponse.hpp>
#include <alibabacloud/models/PutDcdnKvNamespaceRequest.hpp>
#include <alibabacloud/models/PutDcdnKvNamespaceResponseBody.hpp>
#include <alibabacloud/models/PutDcdnKvNamespaceResponse.hpp>
#include <alibabacloud/models/PutDcdnKvWithHighCapacityRequest.hpp>
#include <alibabacloud/models/PutDcdnKvWithHighCapacityResponseBody.hpp>
#include <alibabacloud/models/PutDcdnKvWithHighCapacityResponse.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCacheByCacheTagRequest.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCacheByCacheTagResponseBody.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCacheByCacheTagResponse.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCachesRequest.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCachesResponseBody.hpp>
#include <alibabacloud/models/RefreshDcdnObjectCachesResponse.hpp>
#include <alibabacloud/models/RefreshErObjectCachesRequest.hpp>
#include <alibabacloud/models/RefreshErObjectCachesResponseBody.hpp>
#include <alibabacloud/models/RefreshErObjectCachesResponse.hpp>
#include <alibabacloud/models/RollbackDcdnStagingConfigRequest.hpp>
#include <alibabacloud/models/RollbackDcdnStagingConfigResponseBody.hpp>
#include <alibabacloud/models/RollbackDcdnStagingConfigResponse.hpp>
#include <alibabacloud/models/SetDcdnDomainCsrcertificateRequest.hpp>
#include <alibabacloud/models/SetDcdnDomainCsrcertificateResponseBody.hpp>
#include <alibabacloud/models/SetDcdnDomainCsrcertificateResponse.hpp>
#include <alibabacloud/models/SetDcdnDomainSmcertificateRequest.hpp>
#include <alibabacloud/models/SetDcdnDomainSmcertificateResponseBody.hpp>
#include <alibabacloud/models/SetDcdnDomainSmcertificateResponse.hpp>
#include <alibabacloud/models/SetDcdnDomainSslcertificateRequest.hpp>
#include <alibabacloud/models/SetDcdnDomainSslcertificateResponseBody.hpp>
#include <alibabacloud/models/SetDcdnDomainSslcertificateResponse.hpp>
#include <alibabacloud/models/SetDcdnDomainStagingConfigRequest.hpp>
#include <alibabacloud/models/SetDcdnDomainStagingConfigResponseBody.hpp>
#include <alibabacloud/models/SetDcdnDomainStagingConfigResponse.hpp>
#include <alibabacloud/models/SetDcdnFullDomainsBlockIprequest.hpp>
#include <alibabacloud/models/SetDcdnFullDomainsBlockIpresponseBody.hpp>
#include <alibabacloud/models/SetDcdnFullDomainsBlockIpresponse.hpp>
#include <alibabacloud/models/SetDcdnUserConfigRequest.hpp>
#include <alibabacloud/models/SetDcdnUserConfigResponseBody.hpp>
#include <alibabacloud/models/SetDcdnUserConfigResponse.hpp>
#include <alibabacloud/models/SetRoutineSubdomainRequest.hpp>
#include <alibabacloud/models/SetRoutineSubdomainShrinkRequest.hpp>
#include <alibabacloud/models/SetRoutineSubdomainResponseBody.hpp>
#include <alibabacloud/models/SetRoutineSubdomainResponse.hpp>
#include <alibabacloud/models/StartDcdnDomainRequest.hpp>
#include <alibabacloud/models/StartDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/StartDcdnDomainResponse.hpp>
#include <alibabacloud/models/StartDcdnIpaDomainRequest.hpp>
#include <alibabacloud/models/StartDcdnIpaDomainResponseBody.hpp>
#include <alibabacloud/models/StartDcdnIpaDomainResponse.hpp>
#include <alibabacloud/models/StopDcdnDomainRequest.hpp>
#include <alibabacloud/models/StopDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/StopDcdnDomainResponse.hpp>
#include <alibabacloud/models/StopDcdnIpaDomainRequest.hpp>
#include <alibabacloud/models/StopDcdnIpaDomainResponseBody.hpp>
#include <alibabacloud/models/StopDcdnIpaDomainResponse.hpp>
#include <alibabacloud/models/TagDcdnResourcesRequest.hpp>
#include <alibabacloud/models/TagDcdnResourcesResponseBody.hpp>
#include <alibabacloud/models/TagDcdnResourcesResponse.hpp>
#include <alibabacloud/models/UntagDcdnResourcesRequest.hpp>
#include <alibabacloud/models/UntagDcdnResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagDcdnResourcesResponse.hpp>
#include <alibabacloud/models/UpdateDcdnDeliverTaskRequest.hpp>
#include <alibabacloud/models/UpdateDcdnDeliverTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnDeliverTaskResponse.hpp>
#include <alibabacloud/models/UpdateDcdnDomainRequest.hpp>
#include <alibabacloud/models/UpdateDcdnDomainResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnDomainResponse.hpp>
#include <alibabacloud/models/UpdateDcdnIpaDomainRequest.hpp>
#include <alibabacloud/models/UpdateDcdnIpaDomainResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnIpaDomainResponse.hpp>
#include <alibabacloud/models/UpdateDcdnSlsrealtimeLogDeliveryRequest.hpp>
#include <alibabacloud/models/UpdateDcdnSlsrealtimeLogDeliveryResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnSlsrealtimeLogDeliveryResponse.hpp>
#include <alibabacloud/models/UpdateDcdnSubTaskRequest.hpp>
#include <alibabacloud/models/UpdateDcdnSubTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnSubTaskResponse.hpp>
#include <alibabacloud/models/UpdateDcdnUserRealTimeDeliveryFieldRequest.hpp>
#include <alibabacloud/models/UpdateDcdnUserRealTimeDeliveryFieldResponseBody.hpp>
#include <alibabacloud/models/UpdateDcdnUserRealTimeDeliveryFieldResponse.hpp>
#include <alibabacloud/models/UploadRoutineCodeRequest.hpp>
#include <alibabacloud/models/UploadRoutineCodeResponseBody.hpp>
#include <alibabacloud/models/UploadRoutineCodeResponse.hpp>
#include <alibabacloud/models/UploadStagingRoutineCodeRequest.hpp>
#include <alibabacloud/models/UploadStagingRoutineCodeResponseBody.hpp>
#include <alibabacloud/models/UploadStagingRoutineCodeResponse.hpp>
#include <alibabacloud/models/VerifyDcdnDomainOwnerRequest.hpp>
#include <alibabacloud/models/VerifyDcdnDomainOwnerResponseBody.hpp>
#include <alibabacloud/models/VerifyDcdnDomainOwnerResponse.hpp>
#include <alibabacloud/models/AddDcdnDomainRequestTag.hpp>
#include <alibabacloud/models/BatchCreateDcdnWafRulesResponseBodyRuleIds.hpp>
#include <alibabacloud/models/BatchPutDcdnKvRequestKvList.hpp>
#include <alibabacloud/models/BatchSetDcdnDomainConfigsResponseBodyDomainConfigListDomainConfigModel.hpp>
#include <alibabacloud/models/BatchSetDcdnDomainConfigsResponseBodyDomainConfigList.hpp>
#include <alibabacloud/models/CheckDcdnProjectExistResponseBodyContent.hpp>
#include <alibabacloud/models/CreateDcdnSlsrealTimeLogDeliveryResponseBodyContentDomains.hpp>
#include <alibabacloud/models/CreateDcdnSlsrealTimeLogDeliveryResponseBodyContent.hpp>
#include <alibabacloud/models/CreateSlrAndSlsProjectResponseBodySlsInfo.hpp>
#include <alibabacloud/models/DescribeCustomDomainSampleRateResponseBodyContentDomainContent.hpp>
#include <alibabacloud/models/DescribeCustomDomainSampleRateResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnAclFieldsResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnBgpBpsDataResponseBodyBgpDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnBgpTrafficDataResponseBodyBgpDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnBlockedRegionsResponseBodyInfoListInfoItem.hpp>
#include <alibabacloud/models/DescribeDcdnBlockedRegionsResponseBodyInfoList.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListResponseBodyCertificateListModelCertListCert.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListResponseBodyCertificateListModelCertList.hpp>
#include <alibabacloud/models/DescribeDcdnCertificateListResponseBodyCertificateListModel.hpp>
#include <alibabacloud/models/DescribeDcdnDdosSpecInfoResponseBodySpecInfosConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnDdosSpecInfoResponseBodySpecInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDeletedDomainsResponseBodyDomainsPageData.hpp>
#include <alibabacloud/models/DescribeDcdnDeletedDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataResponseBodyBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataResponseBodyBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataByLayerResponseBodyBpsDataIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainBpsDataByLayerResponseBodyBpsDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainByCertificateResponseBodyCertInfosCertInfo.hpp>
#include <alibabacloud/models/DescribeDcdnDomainByCertificateResponseBodyCertInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCcActivityLogResponseBodyActivityLog.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCertificateInfoResponseBodyCertInfosCertInfo.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCertificateInfoResponseBodyCertInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCnameResponseBodyCnameDatasData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainCnameResponseBodyCnameDatas.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponseBodyDomainConfigsDomainConfigFunctionArgsFunctionArg.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponseBodyDomainConfigsDomainConfigFunctionArgs.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponseBodyDomainConfigsDomainConfig.hpp>
#include <alibabacloud/models/DescribeDcdnDomainConfigsResponseBodyDomainConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailResponseBodyDomainDetailSourcesSource.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailResponseBodyDomainDetailSources.hpp>
#include <alibabacloud/models/DescribeDcdnDomainDetailResponseBodyDomainDetail.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHitRateDataResponseBodyHitRatePerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHitRateDataResponseBodyHitRatePerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponseBodyDataPerIntervalDataModuleHttpCodeDataPerIntervalHttpCodeDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponseBodyDataPerIntervalDataModuleHttpCodeDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponseBodyDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataResponseBodyDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataByLayerResponseBodyHttpCodeDataIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainHttpCodeDataByLayerResponseBodyHttpCodeDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaBpsDataResponseBodyBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaBpsDataResponseBodyBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaConnDataResponseBodyConnectionDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaConnDataResponseBodyConnectionDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaTrafficDataResponseBodyTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIpaTrafficDataResponseBodyTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIspDataResponseBodyValueIspProportionData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainIspDataResponseBodyValue.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBodyDomainLogDetailsDomainLogDetailLogInfosLogInfoDetail.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBodyDomainLogDetailsDomainLogDetailLogInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBodyDomainLogDetailsDomainLogDetailPageInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBodyDomainLogDetailsDomainLogDetail.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogResponseBodyDomainLogDetails.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBodyDomainLogDetailsDomainLogDetailLogInfosLogInfoDetail.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBodyDomainLogDetailsDomainLogDetailLogInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBodyDomainLogDetailsDomainLogDetailPageInfos.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBodyDomainLogDetailsDomainLogDetail.hpp>
#include <alibabacloud/models/DescribeDcdnDomainLogExTtlResponseBodyDomainLogDetails.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponseBodyRequestPerIntervalRequestDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponseBodyRequestPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponseBodyTrafficPerIntervalTrafficDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainMultiUsageDataResponseBodyTrafficPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginBpsDataResponseBodyOriginBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginBpsDataResponseBodyOriginBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginTrafficDataResponseBodyOriginTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainOriginTrafficDataResponseBodyOriginTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPvDataResponseBodyPvDataIntervalUsageData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainPvDataResponseBodyPvDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataResponseBodyQpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataResponseBodyQpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataByLayerResponseBodyQpsDataIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainQpsDataByLayerResponseBodyQpsDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeBpsDataResponseBodyDataBpsModel.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeBpsDataResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeByteHitRateDataResponseBodyDataByteHitRateDataModel.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeByteHitRateDataResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponseBodyRealTimeHttpCodeDataUsageDataValueRealTimeCodeProportionData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponseBodyRealTimeHttpCodeDataUsageDataValue.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponseBodyRealTimeHttpCodeDataUsageData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeHttpCodeDataResponseBodyRealTimeHttpCodeData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeQpsDataResponseBodyDataQpsModel.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeQpsDataResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeReqHitRateDataResponseBodyDataReqHitRateDataModel.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeReqHitRateDataResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcBpsDataResponseBodyRealTimeSrcBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcBpsDataResponseBodyRealTimeSrcBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponseBodyRealTimeSrcHttpCodeDataUsageDataValueRealTimeSrcCodeProportionData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponseBodyRealTimeSrcHttpCodeDataUsageDataValue.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponseBodyRealTimeSrcHttpCodeDataUsageData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcHttpCodeDataResponseBodyRealTimeSrcHttpCodeData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcTrafficDataResponseBodyRealTimeSrcTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeSrcTrafficDataResponseBodyRealTimeSrcTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeTrafficDataResponseBodyRealTimeTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRealTimeTrafficDataResponseBodyRealTimeTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRegionDataResponseBodyValueRegionProportionData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainRegionDataResponseBodyValue.hpp>
#include <alibabacloud/models/DescribeDcdnDomainStagingConfigResponseBodyDomainConfigsFunctionArgs.hpp>
#include <alibabacloud/models/DescribeDcdnDomainStagingConfigResponseBodyDomainConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopReferVisitResponseBodyTopReferListReferList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopReferVisitResponseBodyTopReferList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyAllUrlListUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyAllUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl200listUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl200list.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl300listUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl300list.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl400listUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl400list.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl500listUrlList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTopUrlVisitResponseBodyUrl500list.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTrafficDataResponseBodyTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainTrafficDataResponseBodyTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUsageDataResponseBodyUsageDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUsageDataResponseBodyUsageDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUvDataResponseBodyUvDataIntervalUsageData.hpp>
#include <alibabacloud/models/DescribeDcdnDomainUvDataResponseBodyUvDataInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketBpsDataResponseBodyBpsDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketBpsDataResponseBodyBpsDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponseBodyHttpCodeDataPerIntervalDataModuleWebsocketHttpCodeHttpCodeDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponseBodyHttpCodeDataPerIntervalDataModuleWebsocketHttpCode.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponseBodyHttpCodeDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketHttpCodeDataResponseBodyHttpCodeDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketTrafficDataResponseBodyTrafficDataPerIntervalDataModule.hpp>
#include <alibabacloud/models/DescribeDcdnDomainWebsocketTrafficDataResponseBodyTrafficDataPerInterval.hpp>
#include <alibabacloud/models/DescribeDcdnDomainsBySourceResponseBodyDomainInfoDomainList.hpp>
#include <alibabacloud/models/DescribeDcdnDomainsBySourceResponseBodyDomainInfo.hpp>
#include <alibabacloud/models/DescribeDcdnErUsageDataResponseBodyErAccDataErAccItem.hpp>
#include <alibabacloud/models/DescribeDcdnErUsageDataResponseBodyErAccData.hpp>
#include <alibabacloud/models/DescribeDcdnFullDomainsBlockIphistoryResponseBodyIpblockInfo.hpp>
#include <alibabacloud/models/DescribeDcdnHttpsDomainListResponseBodyCertInfosCertInfo.hpp>
#include <alibabacloud/models/DescribeDcdnHttpsDomainListResponseBodyCertInfos.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponseBodyDomainConfigsDomainConfigFunctionArgsFunctionArg.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponseBodyDomainConfigsDomainConfigFunctionArgs.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponseBodyDomainConfigsDomainConfig.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainConfigsResponseBodyDomainConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailResponseBodyDomainDetailSourcesSource.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailResponseBodyDomainDetailSources.hpp>
#include <alibabacloud/models/DescribeDcdnIpaDomainDetailResponseBodyDomainDetail.hpp>
#include <alibabacloud/models/DescribeDcdnIpaServiceResponseBodyOperationLocksLockReason.hpp>
#include <alibabacloud/models/DescribeDcdnIpaServiceResponseBodyOperationLocks.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsRequestTag.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponseBodyDomainsPageDataSourcesSource.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponseBodyDomainsPageDataSources.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponseBodyDomainsPageData.hpp>
#include <alibabacloud/models/DescribeDcdnIpaUserDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnKvAccountResponseBodyNamespaceList.hpp>
#include <alibabacloud/models/DescribeDcdnOriginSiteHealthStatusResponseBodyOriginSiteStatus.hpp>
#include <alibabacloud/models/DescribeDcdnRealTimeDeliveryFieldResponseBodyContentFields.hpp>
#include <alibabacloud/models/DescribeDcdnRealTimeDeliveryFieldResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTaskByIdResponseBodyTasks.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTasksResponseBodyTasksTask.hpp>
#include <alibabacloud/models/DescribeDcdnRefreshTasksResponseBodyTasks.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponseBodyIspsIsp.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponseBodyIsps.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeDcdnRegionAndIspResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealTimeLogTypeResponseBodyContentBusiness.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealTimeLogTypeResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnSlsrealtimeLogDeliveryResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateListResponseBodyCertificateListModelCertList.hpp>
#include <alibabacloud/models/DescribeDcdnSmcertificateListResponseBodyCertificateListModel.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListResponseBodyCertificateListModelCertListCert.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListResponseBodyCertificateListModelCertList.hpp>
#include <alibabacloud/models/DescribeDcdnSslcertificateListResponseBodyCertificateListModel.hpp>
#include <alibabacloud/models/DescribeDcdnSecFuncInfoResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnSecSpecInfoResponseBodySpecInfosRuleConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnSecSpecInfoResponseBodySpecInfos.hpp>
#include <alibabacloud/models/DescribeDcdnServiceResponseBodyOperationLocksLockReason.hpp>
#include <alibabacloud/models/DescribeDcdnServiceResponseBodyOperationLocks.hpp>
#include <alibabacloud/models/DescribeDcdnStagingIpResponseBodyIpv4s.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesRequestTag.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesResponseBodyTagResourcesTag.hpp>
#include <alibabacloud/models/DescribeDcdnTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/DescribeDcdnTopDomainsByFlowResponseBodyTopDomainsTopDomain.hpp>
#include <alibabacloud/models/DescribeDcdnTopDomainsByFlowResponseBodyTopDomains.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponseBodyBillHistoryDataBillHistoryDataItemBillingDataBillingDataItem.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponseBodyBillHistoryDataBillHistoryDataItemBillingData.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponseBodyBillHistoryDataBillHistoryDataItem.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillHistoryResponseBodyBillHistoryData.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillTypeResponseBodyBillTypeDataBillTypeDataItem.hpp>
#include <alibabacloud/models/DescribeDcdnUserBillTypeResponseBodyBillTypeData.hpp>
#include <alibabacloud/models/DescribeDcdnUserConfigsResponseBodyConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsRequestTag.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponseBodyDomainsPageDataSourcesSource.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponseBodyDomainsPageDataSources.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponseBodyDomainsPageData.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponseBodyDomainsPageDataSourcesSource.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponseBodyDomainsPageDataSources.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponseBodyDomainsPageData.hpp>
#include <alibabacloud/models/DescribeDcdnUserDomainsByFuncResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnUserRealTimeDeliveryFieldResponseBodyContentFields.hpp>
#include <alibabacloud/models/DescribeDcdnUserRealTimeDeliveryFieldResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnUserResourcePackageResponseBodyResourcePackageInfosResourcePackageInfo.hpp>
#include <alibabacloud/models/DescribeDcdnUserResourcePackageResponseBodyResourcePackageInfos.hpp>
#include <alibabacloud/models/DescribeDcdnUserSecDropByMinuteResponseBodyRows.hpp>
#include <alibabacloud/models/DescribeDcdnUserTagsResponseBodyTags.hpp>
#include <alibabacloud/models/DescribeDcdnUserVipsByDomainResponseBodyVips.hpp>
#include <alibabacloud/models/DescribeDcdnWafDefaultRulesResponseBodyContentRules.hpp>
#include <alibabacloud/models/DescribeDcdnWafDefaultRulesResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainResponseBodyOutPutDomains.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainDetailResponseBodyDomainDefenseScenes.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainDetailResponseBodyDomain.hpp>
#include <alibabacloud/models/DescribeDcdnWafDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponseBodyContentFieldsLogicalSymbolRegexp.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponseBodyContentFieldsLogicalSymbol.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponseBodyContentFields.hpp>
#include <alibabacloud/models/DescribeDcdnWafFilterInfoResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoResponseBodyContentContinentsRegions.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoResponseBodyContentContinents.hpp>
#include <alibabacloud/models/DescribeDcdnWafGeoInfoResponseBodyContent.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupsResponseBodyWafGroupsPolicies.hpp>
#include <alibabacloud/models/DescribeDcdnWafGroupsResponseBodyWafGroups.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsResponseBodyDomainLogDetailsLogInfos.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsResponseBodyDomainLogDetailsPageInfos.hpp>
#include <alibabacloud/models/DescribeDcdnWafLogsResponseBodyDomainLogDetails.hpp>
#include <alibabacloud/models/DescribeDcdnWafPoliciesResponseBodyPolicies.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyResponseBodyPolicy.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyValidDomainsResponseBodyDomainsPolicies.hpp>
#include <alibabacloud/models/DescribeDcdnWafPolicyValidDomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribeDcdnWafRuleResponseBodyRule.hpp>
#include <alibabacloud/models/DescribeDcdnWafRulesResponseBodyRules.hpp>
#include <alibabacloud/models/DescribeDcdnWafScenesResponseBodyDefenseScenes.hpp>
#include <alibabacloud/models/DescribeDcdnWafSpecInfoResponseBodySpecInfosConfigs.hpp>
#include <alibabacloud/models/DescribeDcdnWafSpecInfoResponseBodySpecInfos.hpp>
#include <alibabacloud/models/DescribeDcdnWafUsageDataResponseBodyWafUsageDataWafUsageDataItem.hpp>
#include <alibabacloud/models/DescribeDcdnWafUsageDataResponseBodyWafUsageData.hpp>
#include <alibabacloud/models/DescribeDcdnsecServiceResponseBodyOperationLocksLockReason.hpp>
#include <alibabacloud/models/DescribeDcdnsecServiceResponseBodyOperationLocks.hpp>
#include <alibabacloud/models/DescribeDdosAllEventListResponseBodyDataList.hpp>
#include <alibabacloud/models/DescribeHighlightInfoResponseBodyDataModule.hpp>
#include <alibabacloud/models/DescribeKvRealTimeQpsDataResponseBodyAggregateData.hpp>
#include <alibabacloud/models/DescribeKvRealTimeQpsDataResponseBodyKvQpsData.hpp>
#include <alibabacloud/models/DescribeKvUsageDataResponseBodyKvUsageData.hpp>
#include <alibabacloud/models/DescribeRddomainConfigResponseBodyDomainConfigsFunctionArgs.hpp>
#include <alibabacloud/models/DescribeRddomainConfigResponseBodyDomainConfigs.hpp>
#include <alibabacloud/models/DescribeRddomainsResponseBodyDomainsPageDataSourcesSource.hpp>
#include <alibabacloud/models/DescribeRddomainsResponseBodyDomainsPageDataSources.hpp>
#include <alibabacloud/models/DescribeRddomainsResponseBodyDomainsPageData.hpp>
#include <alibabacloud/models/DescribeRddomainsResponseBodyDomains.hpp>
#include <alibabacloud/models/ListDcdnKvResponseBodyKeys.hpp>
#include <alibabacloud/models/ListDcdnRealTimeDeliveryProjectResponseBodyContentProjects.hpp>
#include <alibabacloud/models/ListDcdnRealTimeDeliveryProjectResponseBodyContent.hpp>
#include <alibabacloud/models/ModifyCustomDomainSampleRateResponseBodyContent.hpp>
#include <alibabacloud/models/TagDcdnResourcesRequestTag.hpp>
#include <alibabacloud/models/UpdateDcdnSlsrealtimeLogDeliveryResponseBodyContentDomains.hpp>
#include <alibabacloud/models/UpdateDcdnSlsrealtimeLogDeliveryResponseBodyContent.hpp>

#endif
