// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_CREATEATIAGENTREGISTERINFOACMECHALLENGERECORDREQUEST_HPP_
#define ALIBABACLOUD_MODELS_CREATEATIAGENTREGISTERINFOACMECHALLENGERECORDREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Alidns20150109
{
namespace Models
{
  class CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& obj) { 
      DARABONBA_PTR_TO_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_TO_JSON(ClientToken, clientToken_);
    };
    friend void from_json(const Darabonba::Json& j, CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_FROM_JSON(ClientToken, clientToken_);
    };
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest() = default ;
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest(const CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest &) = default ;
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest(CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest &&) = default ;
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest() = default ;
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& operator=(const CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest &) = default ;
    CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& operator=(CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->agentRegisterInfoId_ == nullptr
        && this->clientToken_ == nullptr; };
    // agentRegisterInfoId Field Functions 
    bool hasAgentRegisterInfoId() const { return this->agentRegisterInfoId_ != nullptr;};
    void deleteAgentRegisterInfoId() { this->agentRegisterInfoId_ = nullptr;};
    inline string getAgentRegisterInfoId() const { DARABONBA_PTR_GET_DEFAULT(agentRegisterInfoId_, "") };
    inline CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& setAgentRegisterInfoId(string agentRegisterInfoId) { DARABONBA_PTR_SET_VALUE(agentRegisterInfoId_, agentRegisterInfoId) };


    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline CreateAtiAgentRegisterInfoAcmeChallengeRecordRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


  protected:
    // The agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform. It is automatically generated during the agent registration process. In the multi-step API registration and query process, this ID must be carried throughout. Call the ListAtiAgentRegisterInfos operation to query the target agent and obtain the AgentRegisterInfoId from the response.
    // 
    // This parameter is required.
    shared_ptr<string> agentRegisterInfoId_ {};
    // Ensures the idempotency of the request. Generate a unique parameter value from your client to ensure uniqueness across different requests. ClientToken supports only ASCII characters and cannot exceed 64 characters.
    // 
    // > If you do not specify this parameter, the system automatically uses the RequestId of the API request as the ClientToken. The RequestId may differ for each API request.
    shared_ptr<string> clientToken_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Alidns20150109
#endif
