// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_REVOKEATIAGENTREGISTERINFOREQUEST_HPP_
#define ALIBABACLOUD_MODELS_REVOKEATIAGENTREGISTERINFOREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Alidns20150109
{
namespace Models
{
  class RevokeAtiAgentRegisterInfoRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const RevokeAtiAgentRegisterInfoRequest& obj) { 
      DARABONBA_PTR_TO_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_TO_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(Reason, reason_);
      DARABONBA_PTR_TO_JSON(ReasonCode, reasonCode_);
    };
    friend void from_json(const Darabonba::Json& j, RevokeAtiAgentRegisterInfoRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_FROM_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(Reason, reason_);
      DARABONBA_PTR_FROM_JSON(ReasonCode, reasonCode_);
    };
    RevokeAtiAgentRegisterInfoRequest() = default ;
    RevokeAtiAgentRegisterInfoRequest(const RevokeAtiAgentRegisterInfoRequest &) = default ;
    RevokeAtiAgentRegisterInfoRequest(RevokeAtiAgentRegisterInfoRequest &&) = default ;
    RevokeAtiAgentRegisterInfoRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~RevokeAtiAgentRegisterInfoRequest() = default ;
    RevokeAtiAgentRegisterInfoRequest& operator=(const RevokeAtiAgentRegisterInfoRequest &) = default ;
    RevokeAtiAgentRegisterInfoRequest& operator=(RevokeAtiAgentRegisterInfoRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->agentRegisterInfoId_ == nullptr
        && this->clientToken_ == nullptr && this->reason_ == nullptr && this->reasonCode_ == nullptr; };
    // agentRegisterInfoId Field Functions 
    bool hasAgentRegisterInfoId() const { return this->agentRegisterInfoId_ != nullptr;};
    void deleteAgentRegisterInfoId() { this->agentRegisterInfoId_ = nullptr;};
    inline string getAgentRegisterInfoId() const { DARABONBA_PTR_GET_DEFAULT(agentRegisterInfoId_, "") };
    inline RevokeAtiAgentRegisterInfoRequest& setAgentRegisterInfoId(string agentRegisterInfoId) { DARABONBA_PTR_SET_VALUE(agentRegisterInfoId_, agentRegisterInfoId) };


    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline RevokeAtiAgentRegisterInfoRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // reason Field Functions 
    bool hasReason() const { return this->reason_ != nullptr;};
    void deleteReason() { this->reason_ = nullptr;};
    inline string getReason() const { DARABONBA_PTR_GET_DEFAULT(reason_, "") };
    inline RevokeAtiAgentRegisterInfoRequest& setReason(string reason) { DARABONBA_PTR_SET_VALUE(reason_, reason) };


    // reasonCode Field Functions 
    bool hasReasonCode() const { return this->reasonCode_ != nullptr;};
    void deleteReasonCode() { this->reasonCode_ = nullptr;};
    inline string getReasonCode() const { DARABONBA_PTR_GET_DEFAULT(reasonCode_, "") };
    inline RevokeAtiAgentRegisterInfoRequest& setReasonCode(string reasonCode) { DARABONBA_PTR_SET_VALUE(reasonCode_, reasonCode) };


  protected:
    // The Agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform. It is automatically generated during the Agent registration process. This ID must be included throughout the API registration and query processes. Call the ListAtiAgentRegisterInfos operation to query the target Agent and obtain the AgentRegisterInfoId from the response.
    // 
    // This parameter is required.
    shared_ptr<string> agentRegisterInfoId_ {};
    // The client token that is used to ensure the idempotence of the request. You can use the client to generate the token, but you must make sure that the token is unique among different requests. The token can contain only ASCII characters and cannot exceed 64 characters in length.
    // 
    // > If you do not specify this parameter, the system automatically uses the RequestId of the API request as the ClientToken. The RequestId may be different for each API request.
    shared_ptr<string> clientToken_ {};
    // The reason for unregistration. Valid values:
    // 
    // - Key compromise
    // - CA key compromise
    // - Affiliation changed
    // - Certificate superseded
    // - Cessation of operation
    // - Certificate hold
    // - Remove from CRL
    // - Privilege withdrawn
    // - AA compromise
    // - Unspecified
    shared_ptr<string> reason_ {};
    // The revocation reason code as defined in RFC 5280. Valid values:
    // 
    // - unspecified: Unspecified. Default value. Used when the CA does not provide a specific reason or the reason is unknown. This is the most common code.
    // - keyCompromise: Key compromise. The private key may have been obtained by an unauthorized party. This is the most serious reason and typically means the certificate must be revoked immediately and cannot be recovered.
    // - cACompromise: CA key compromise. The private key of the CA that issued the certificate has been compromised. This affects all certificates issued by the CA and typically results in the revocation of the entire subtree.
    // - affiliationChanged: Affiliation changed. The identity information of the certificate holder (such as name or organization name) has changed, but the public key is still valid. For example, an employee leaves the company or the company is renamed.
    // - superseded: Certificate superseded. The certificate holder has applied for a new certificate (for example, key rotation or algorithm upgrade), and the old certificate is revoked. The old key has not been compromised.
    // - cessationOfOperation: Cessation of operation. The certificate holder no longer uses the key for related operations (for example, server decommissioning or service termination). The key has not been compromised.
    // - certificateHold: Certificate hold. Temporary revocation. Typically used for investigating suspicious activities or for administrative reasons. The hold can be removed later (Unhold) to make the certificate valid again. Note: This code cannot be used for final revocation.
    // - removeFromCRL: Remove from CRL. Used only for delta CRLs (incremental revocation lists). Indicates that a certificate previously held by certificateHold has been released and should be removed from the revocation list. This is not a revocation reason but a status update instruction.
    // - privilegeWithdrawn: Privilege withdrawn. The privileges or attributes granted in the certificate have been revoked (primarily used for Attribute Certificates and rarely used for regular SSL/TLS certificates).
    // - aACompromise: AA compromise. The key of the Attribute Authority (AA) that issued the attribute certificate has been compromised. This is also primarily used in the attribute certificate system.
    // 
    // This parameter is required.
    shared_ptr<string> reasonCode_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Alidns20150109
#endif
