// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_SUBMITATIAGENTREGISTERINFOREQUEST_HPP_
#define ALIBABACLOUD_MODELS_SUBMITATIAGENTREGISTERINFOREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Alidns20150109
{
namespace Models
{
  class SubmitAtiAgentRegisterInfoRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const SubmitAtiAgentRegisterInfoRequest& obj) { 
      DARABONBA_PTR_TO_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_TO_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_TO_JSON(IdentityCsr, identityCsr_);
      DARABONBA_PTR_TO_JSON(ServerCertPem, serverCertPem_);
    };
    friend void from_json(const Darabonba::Json& j, SubmitAtiAgentRegisterInfoRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(AgentRegisterInfoId, agentRegisterInfoId_);
      DARABONBA_PTR_FROM_JSON(ClientToken, clientToken_);
      DARABONBA_PTR_FROM_JSON(IdentityCsr, identityCsr_);
      DARABONBA_PTR_FROM_JSON(ServerCertPem, serverCertPem_);
    };
    SubmitAtiAgentRegisterInfoRequest() = default ;
    SubmitAtiAgentRegisterInfoRequest(const SubmitAtiAgentRegisterInfoRequest &) = default ;
    SubmitAtiAgentRegisterInfoRequest(SubmitAtiAgentRegisterInfoRequest &&) = default ;
    SubmitAtiAgentRegisterInfoRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~SubmitAtiAgentRegisterInfoRequest() = default ;
    SubmitAtiAgentRegisterInfoRequest& operator=(const SubmitAtiAgentRegisterInfoRequest &) = default ;
    SubmitAtiAgentRegisterInfoRequest& operator=(SubmitAtiAgentRegisterInfoRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->agentRegisterInfoId_ == nullptr
        && this->clientToken_ == nullptr && this->identityCsr_ == nullptr && this->serverCertPem_ == nullptr; };
    // agentRegisterInfoId Field Functions 
    bool hasAgentRegisterInfoId() const { return this->agentRegisterInfoId_ != nullptr;};
    void deleteAgentRegisterInfoId() { this->agentRegisterInfoId_ = nullptr;};
    inline string getAgentRegisterInfoId() const { DARABONBA_PTR_GET_DEFAULT(agentRegisterInfoId_, "") };
    inline SubmitAtiAgentRegisterInfoRequest& setAgentRegisterInfoId(string agentRegisterInfoId) { DARABONBA_PTR_SET_VALUE(agentRegisterInfoId_, agentRegisterInfoId) };


    // clientToken Field Functions 
    bool hasClientToken() const { return this->clientToken_ != nullptr;};
    void deleteClientToken() { this->clientToken_ = nullptr;};
    inline string getClientToken() const { DARABONBA_PTR_GET_DEFAULT(clientToken_, "") };
    inline SubmitAtiAgentRegisterInfoRequest& setClientToken(string clientToken) { DARABONBA_PTR_SET_VALUE(clientToken_, clientToken) };


    // identityCsr Field Functions 
    bool hasIdentityCsr() const { return this->identityCsr_ != nullptr;};
    void deleteIdentityCsr() { this->identityCsr_ = nullptr;};
    inline string getIdentityCsr() const { DARABONBA_PTR_GET_DEFAULT(identityCsr_, "") };
    inline SubmitAtiAgentRegisterInfoRequest& setIdentityCsr(string identityCsr) { DARABONBA_PTR_SET_VALUE(identityCsr_, identityCsr) };


    // serverCertPem Field Functions 
    bool hasServerCertPem() const { return this->serverCertPem_ != nullptr;};
    void deleteServerCertPem() { this->serverCertPem_ = nullptr;};
    inline string getServerCertPem() const { DARABONBA_PTR_GET_DEFAULT(serverCertPem_, "") };
    inline SubmitAtiAgentRegisterInfoRequest& setServerCertPem(string serverCertPem) { DARABONBA_PTR_SET_VALUE(serverCertPem_, serverCertPem) };


  protected:
    // The Agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform. The ID is automatically generated during the Agent registration process. When you register or query an Agent by calling API operations, you must carry this ID throughout the entire process. Call the ListAtiAgentRegisterInfos operation to query the target Agent and obtain the AgentRegisterInfoId from the response.
    // 
    // This parameter is required.
    shared_ptr<string> agentRegisterInfoId_ {};
    // The client token that is used to ensure the idempotence of the request. You can use the client to generate the token, but you must make sure that the token is unique among different requests. The token can contain only ASCII characters and cannot exceed 64 characters in length.
    // 
    // If you do not specify this parameter, the system automatically uses the RequestId of the API request as the ClientToken. The RequestId may be different for each API request.
    shared_ptr<string> clientToken_ {};
    // The Certificate Signing Request (CSR) for the identity certificate. You can generate the CSR by following the instructions provided in Step 3 of the Register Agent process in the ATS console.
    // 
    // This parameter is required.
    shared_ptr<string> identityCsr_ {};
    // The server certificate, which is the certificate corresponding to the domain name (host address) used by the registered Agent.
    // 
    // This parameter is required.
    shared_ptr<string> serverCertPem_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Alidns20150109
#endif
