// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ECD20200930MODEL_HPP_
#define ALIBABACLOUD_ECD20200930MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CdsFileShareLinkModel.hpp>
#include <alibabacloud/models/FilePermissionMember.hpp>
#include <alibabacloud/models/Permission.hpp>
#include <alibabacloud/models/ActivateOfficeSiteRequest.hpp>
#include <alibabacloud/models/ActivateOfficeSiteResponseBody.hpp>
#include <alibabacloud/models/ActivateOfficeSiteResponse.hpp>
#include <alibabacloud/models/AddDesktopOversoldUserGroupRequest.hpp>
#include <alibabacloud/models/AddDesktopOversoldUserGroupResponseBody.hpp>
#include <alibabacloud/models/AddDesktopOversoldUserGroupResponse.hpp>
#include <alibabacloud/models/AddDevicesRequest.hpp>
#include <alibabacloud/models/AddDevicesResponseBody.hpp>
#include <alibabacloud/models/AddDevicesResponse.hpp>
#include <alibabacloud/models/AddFilePermissionRequest.hpp>
#include <alibabacloud/models/AddFilePermissionShrinkRequest.hpp>
#include <alibabacloud/models/AddFilePermissionResponseBody.hpp>
#include <alibabacloud/models/AddFilePermissionResponse.hpp>
#include <alibabacloud/models/AddUserToDesktopGroupRequest.hpp>
#include <alibabacloud/models/AddUserToDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/AddUserToDesktopGroupResponse.hpp>
#include <alibabacloud/models/AddUserToDesktopOversoldUserGroupRequest.hpp>
#include <alibabacloud/models/AddUserToDesktopOversoldUserGroupResponseBody.hpp>
#include <alibabacloud/models/AddUserToDesktopOversoldUserGroupResponse.hpp>
#include <alibabacloud/models/AllocateIpAddressRequest.hpp>
#include <alibabacloud/models/AllocateIpAddressResponseBody.hpp>
#include <alibabacloud/models/AllocateIpAddressResponse.hpp>
#include <alibabacloud/models/ApplyAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/ApplyAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/ApplyAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/ApplyCoordinatePrivilegeRequest.hpp>
#include <alibabacloud/models/ApplyCoordinatePrivilegeResponseBody.hpp>
#include <alibabacloud/models/ApplyCoordinatePrivilegeResponse.hpp>
#include <alibabacloud/models/ApplyCoordinationForMonitoringRequest.hpp>
#include <alibabacloud/models/ApplyCoordinationForMonitoringResponseBody.hpp>
#include <alibabacloud/models/ApplyCoordinationForMonitoringResponse.hpp>
#include <alibabacloud/models/ApproveFotaUpdateRequest.hpp>
#include <alibabacloud/models/ApproveFotaUpdateResponseBody.hpp>
#include <alibabacloud/models/ApproveFotaUpdateResponse.hpp>
#include <alibabacloud/models/AssociateIpAddressRequest.hpp>
#include <alibabacloud/models/AssociateIpAddressResponseBody.hpp>
#include <alibabacloud/models/AssociateIpAddressResponse.hpp>
#include <alibabacloud/models/AssociateNetworkPackageRequest.hpp>
#include <alibabacloud/models/AssociateNetworkPackageResponseBody.hpp>
#include <alibabacloud/models/AssociateNetworkPackageResponse.hpp>
#include <alibabacloud/models/AssociateRouteTableRequest.hpp>
#include <alibabacloud/models/AssociateRouteTableResponseBody.hpp>
#include <alibabacloud/models/AssociateRouteTableResponse.hpp>
#include <alibabacloud/models/AttachCenRequest.hpp>
#include <alibabacloud/models/AttachCenResponseBody.hpp>
#include <alibabacloud/models/AttachCenResponse.hpp>
#include <alibabacloud/models/AttachEndUserRequest.hpp>
#include <alibabacloud/models/AttachEndUserResponseBody.hpp>
#include <alibabacloud/models/AttachEndUserResponse.hpp>
#include <alibabacloud/models/BatchModifyEntitlementRequest.hpp>
#include <alibabacloud/models/BatchModifyEntitlementResponseBody.hpp>
#include <alibabacloud/models/BatchModifyEntitlementResponse.hpp>
#include <alibabacloud/models/BindConfigGroupRequest.hpp>
#include <alibabacloud/models/BindConfigGroupResponseBody.hpp>
#include <alibabacloud/models/BindConfigGroupResponse.hpp>
#include <alibabacloud/models/CancelAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/CancelAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/CancelAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/CancelCdsFileShareLinkRequest.hpp>
#include <alibabacloud/models/CancelCdsFileShareLinkResponseBody.hpp>
#include <alibabacloud/models/CancelCdsFileShareLinkResponse.hpp>
#include <alibabacloud/models/CancelCoordinationForMonitoringRequest.hpp>
#include <alibabacloud/models/CancelCoordinationForMonitoringResponseBody.hpp>
#include <alibabacloud/models/CancelCoordinationForMonitoringResponse.hpp>
#include <alibabacloud/models/CancelCopyImageRequest.hpp>
#include <alibabacloud/models/CancelCopyImageResponseBody.hpp>
#include <alibabacloud/models/CancelCopyImageResponse.hpp>
#include <alibabacloud/models/CloneCenterPolicyRequest.hpp>
#include <alibabacloud/models/CloneCenterPolicyResponseBody.hpp>
#include <alibabacloud/models/CloneCenterPolicyResponse.hpp>
#include <alibabacloud/models/ClonePolicyGroupRequest.hpp>
#include <alibabacloud/models/ClonePolicyGroupResponseBody.hpp>
#include <alibabacloud/models/ClonePolicyGroupResponse.hpp>
#include <alibabacloud/models/CompleteCdsFileRequest.hpp>
#include <alibabacloud/models/CompleteCdsFileResponseBody.hpp>
#include <alibabacloud/models/CompleteCdsFileResponse.hpp>
#include <alibabacloud/models/ConfigADConnectorTrustRequest.hpp>
#include <alibabacloud/models/ConfigADConnectorTrustResponseBody.hpp>
#include <alibabacloud/models/ConfigADConnectorTrustResponse.hpp>
#include <alibabacloud/models/ConfigADConnectorUserRequest.hpp>
#include <alibabacloud/models/ConfigADConnectorUserResponseBody.hpp>
#include <alibabacloud/models/ConfigADConnectorUserResponse.hpp>
#include <alibabacloud/models/CopyCdsFileRequest.hpp>
#include <alibabacloud/models/CopyCdsFileResponseBody.hpp>
#include <alibabacloud/models/CopyCdsFileResponse.hpp>
#include <alibabacloud/models/CopyImageRequest.hpp>
#include <alibabacloud/models/CopyImageResponseBody.hpp>
#include <alibabacloud/models/CopyImageResponse.hpp>
#include <alibabacloud/models/CreateADConnectorDirectoryRequest.hpp>
#include <alibabacloud/models/CreateADConnectorDirectoryResponseBody.hpp>
#include <alibabacloud/models/CreateADConnectorDirectoryResponse.hpp>
#include <alibabacloud/models/CreateADConnectorOfficeSiteRequest.hpp>
#include <alibabacloud/models/CreateADConnectorOfficeSiteResponseBody.hpp>
#include <alibabacloud/models/CreateADConnectorOfficeSiteResponse.hpp>
#include <alibabacloud/models/CreateAndBindNasFileSystemRequest.hpp>
#include <alibabacloud/models/CreateAndBindNasFileSystemResponseBody.hpp>
#include <alibabacloud/models/CreateAndBindNasFileSystemResponse.hpp>
#include <alibabacloud/models/CreateAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/CreateAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/CreateBandwidthResourcePackagesRequest.hpp>
#include <alibabacloud/models/CreateBandwidthResourcePackagesResponseBody.hpp>
#include <alibabacloud/models/CreateBandwidthResourcePackagesResponse.hpp>
#include <alibabacloud/models/CreateBundleRequest.hpp>
#include <alibabacloud/models/CreateBundleResponseBody.hpp>
#include <alibabacloud/models/CreateBundleResponse.hpp>
#include <alibabacloud/models/CreateCdsFileRequest.hpp>
#include <alibabacloud/models/CreateCdsFileResponseBody.hpp>
#include <alibabacloud/models/CreateCdsFileResponse.hpp>
#include <alibabacloud/models/CreateCdsFileShareLinkRequest.hpp>
#include <alibabacloud/models/CreateCdsFileShareLinkResponseBody.hpp>
#include <alibabacloud/models/CreateCdsFileShareLinkResponse.hpp>
#include <alibabacloud/models/CreateCenterPolicyRequest.hpp>
#include <alibabacloud/models/CreateCenterPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateCenterPolicyResponse.hpp>
#include <alibabacloud/models/CreateCloudDriveGroupRequest.hpp>
#include <alibabacloud/models/CreateCloudDriveGroupResponseBody.hpp>
#include <alibabacloud/models/CreateCloudDriveGroupResponse.hpp>
#include <alibabacloud/models/CreateCloudDriveServiceRequest.hpp>
#include <alibabacloud/models/CreateCloudDriveServiceResponseBody.hpp>
#include <alibabacloud/models/CreateCloudDriveServiceResponse.hpp>
#include <alibabacloud/models/CreateCloudDriveUsersRequest.hpp>
#include <alibabacloud/models/CreateCloudDriveUsersResponseBody.hpp>
#include <alibabacloud/models/CreateCloudDriveUsersResponse.hpp>
#include <alibabacloud/models/CreateConfigGroupRequest.hpp>
#include <alibabacloud/models/CreateConfigGroupResponseBody.hpp>
#include <alibabacloud/models/CreateConfigGroupResponse.hpp>
#include <alibabacloud/models/CreateDesktopGroupRequest.hpp>
#include <alibabacloud/models/CreateDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDesktopGroupResponse.hpp>
#include <alibabacloud/models/CreateDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/CreateDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/CreateDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/CreateDesktopsRequest.hpp>
#include <alibabacloud/models/CreateDesktopsShrinkRequest.hpp>
#include <alibabacloud/models/CreateDesktopsResponseBody.hpp>
#include <alibabacloud/models/CreateDesktopsResponse.hpp>
#include <alibabacloud/models/CreateDiskEncryptionServiceRequest.hpp>
#include <alibabacloud/models/CreateDiskEncryptionServiceResponseBody.hpp>
#include <alibabacloud/models/CreateDiskEncryptionServiceResponse.hpp>
#include <alibabacloud/models/CreateDriveRequest.hpp>
#include <alibabacloud/models/CreateDriveResponseBody.hpp>
#include <alibabacloud/models/CreateDriveResponse.hpp>
#include <alibabacloud/models/CreateEcdReportTaskRequest.hpp>
#include <alibabacloud/models/CreateEcdReportTaskResponseBody.hpp>
#include <alibabacloud/models/CreateEcdReportTaskResponse.hpp>
#include <alibabacloud/models/CreateForwardEntryRequest.hpp>
#include <alibabacloud/models/CreateForwardEntryResponseBody.hpp>
#include <alibabacloud/models/CreateForwardEntryResponse.hpp>
#include <alibabacloud/models/CreateImageRequest.hpp>
#include <alibabacloud/models/CreateImageResponseBody.hpp>
#include <alibabacloud/models/CreateImageResponse.hpp>
#include <alibabacloud/models/CreateNASFileSystemRequest.hpp>
#include <alibabacloud/models/CreateNASFileSystemResponseBody.hpp>
#include <alibabacloud/models/CreateNASFileSystemResponse.hpp>
#include <alibabacloud/models/CreateNatGatewayRequest.hpp>
#include <alibabacloud/models/CreateNatGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateNatGatewayResponse.hpp>
#include <alibabacloud/models/CreateNetworkPackageRequest.hpp>
#include <alibabacloud/models/CreateNetworkPackageResponseBody.hpp>
#include <alibabacloud/models/CreateNetworkPackageResponse.hpp>
#include <alibabacloud/models/CreatePolicyGroupRequest.hpp>
#include <alibabacloud/models/CreatePolicyGroupResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyGroupResponse.hpp>
#include <alibabacloud/models/CreateRAMDirectoryRequest.hpp>
#include <alibabacloud/models/CreateRAMDirectoryResponseBody.hpp>
#include <alibabacloud/models/CreateRAMDirectoryResponse.hpp>
#include <alibabacloud/models/CreateRouteEntryRequest.hpp>
#include <alibabacloud/models/CreateRouteEntryResponseBody.hpp>
#include <alibabacloud/models/CreateRouteEntryResponse.hpp>
#include <alibabacloud/models/CreateRouteTableRequest.hpp>
#include <alibabacloud/models/CreateRouteTableResponseBody.hpp>
#include <alibabacloud/models/CreateRouteTableResponse.hpp>
#include <alibabacloud/models/CreateSimpleOfficeSiteRequest.hpp>
#include <alibabacloud/models/CreateSimpleOfficeSiteResponseBody.hpp>
#include <alibabacloud/models/CreateSimpleOfficeSiteResponse.hpp>
#include <alibabacloud/models/CreateSnapshotRequest.hpp>
#include <alibabacloud/models/CreateSnapshotResponseBody.hpp>
#include <alibabacloud/models/CreateSnapshotResponse.hpp>
#include <alibabacloud/models/CreateSnatEntryRequest.hpp>
#include <alibabacloud/models/CreateSnatEntryResponseBody.hpp>
#include <alibabacloud/models/CreateSnatEntryResponse.hpp>
#include <alibabacloud/models/CreateSubnetRequest.hpp>
#include <alibabacloud/models/CreateSubnetResponseBody.hpp>
#include <alibabacloud/models/CreateSubnetResponse.hpp>
#include <alibabacloud/models/CreateTemplateRequest.hpp>
#include <alibabacloud/models/CreateTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/DeleteAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/DeleteBundlesRequest.hpp>
#include <alibabacloud/models/DeleteBundlesResponseBody.hpp>
#include <alibabacloud/models/DeleteBundlesResponse.hpp>
#include <alibabacloud/models/DeleteCdsFileRequest.hpp>
#include <alibabacloud/models/DeleteCdsFileResponseBody.hpp>
#include <alibabacloud/models/DeleteCdsFileResponse.hpp>
#include <alibabacloud/models/DeleteCenterPolicyRequest.hpp>
#include <alibabacloud/models/DeleteCenterPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteCenterPolicyResponse.hpp>
#include <alibabacloud/models/DeleteCloudDriveGroupsRequest.hpp>
#include <alibabacloud/models/DeleteCloudDriveGroupsResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudDriveGroupsResponse.hpp>
#include <alibabacloud/models/DeleteCloudDriveUsersRequest.hpp>
#include <alibabacloud/models/DeleteCloudDriveUsersResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudDriveUsersResponse.hpp>
#include <alibabacloud/models/DeleteConfigGroupRequest.hpp>
#include <alibabacloud/models/DeleteConfigGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteConfigGroupResponse.hpp>
#include <alibabacloud/models/DeleteDesktopGroupRequest.hpp>
#include <alibabacloud/models/DeleteDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteDesktopGroupResponse.hpp>
#include <alibabacloud/models/DeleteDesktopsRequest.hpp>
#include <alibabacloud/models/DeleteDesktopsResponseBody.hpp>
#include <alibabacloud/models/DeleteDesktopsResponse.hpp>
#include <alibabacloud/models/DeleteDevicesRequest.hpp>
#include <alibabacloud/models/DeleteDevicesResponseBody.hpp>
#include <alibabacloud/models/DeleteDevicesResponse.hpp>
#include <alibabacloud/models/DeleteDirectoriesRequest.hpp>
#include <alibabacloud/models/DeleteDirectoriesResponseBody.hpp>
#include <alibabacloud/models/DeleteDirectoriesResponse.hpp>
#include <alibabacloud/models/DeleteDriveRequest.hpp>
#include <alibabacloud/models/DeleteDriveResponseBody.hpp>
#include <alibabacloud/models/DeleteDriveResponse.hpp>
#include <alibabacloud/models/DeleteEduRoomRequest.hpp>
#include <alibabacloud/models/DeleteEduRoomResponseBody.hpp>
#include <alibabacloud/models/DeleteEduRoomResponse.hpp>
#include <alibabacloud/models/DeleteForwardEntryRequest.hpp>
#include <alibabacloud/models/DeleteForwardEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteForwardEntryResponse.hpp>
#include <alibabacloud/models/DeleteImagesRequest.hpp>
#include <alibabacloud/models/DeleteImagesResponseBody.hpp>
#include <alibabacloud/models/DeleteImagesResponse.hpp>
#include <alibabacloud/models/DeleteNASFileSystemsRequest.hpp>
#include <alibabacloud/models/DeleteNASFileSystemsResponseBody.hpp>
#include <alibabacloud/models/DeleteNASFileSystemsResponse.hpp>
#include <alibabacloud/models/DeleteNatGatewayRequest.hpp>
#include <alibabacloud/models/DeleteNatGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteNatGatewayResponse.hpp>
#include <alibabacloud/models/DeleteNetworkPackagesRequest.hpp>
#include <alibabacloud/models/DeleteNetworkPackagesResponseBody.hpp>
#include <alibabacloud/models/DeleteNetworkPackagesResponse.hpp>
#include <alibabacloud/models/DeleteOfficeSitesRequest.hpp>
#include <alibabacloud/models/DeleteOfficeSitesResponseBody.hpp>
#include <alibabacloud/models/DeleteOfficeSitesResponse.hpp>
#include <alibabacloud/models/DeletePolicyGroupsRequest.hpp>
#include <alibabacloud/models/DeletePolicyGroupsResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyGroupsResponse.hpp>
#include <alibabacloud/models/DeleteRouteEntryRequest.hpp>
#include <alibabacloud/models/DeleteRouteEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteEntryResponse.hpp>
#include <alibabacloud/models/DeleteRouteTableRequest.hpp>
#include <alibabacloud/models/DeleteRouteTableResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteTableResponse.hpp>
#include <alibabacloud/models/DeleteSnapshotRequest.hpp>
#include <alibabacloud/models/DeleteSnapshotResponseBody.hpp>
#include <alibabacloud/models/DeleteSnapshotResponse.hpp>
#include <alibabacloud/models/DeleteSnatEntryRequest.hpp>
#include <alibabacloud/models/DeleteSnatEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteSnatEntryResponse.hpp>
#include <alibabacloud/models/DeleteSubnetRequest.hpp>
#include <alibabacloud/models/DeleteSubnetResponseBody.hpp>
#include <alibabacloud/models/DeleteSubnetResponse.hpp>
#include <alibabacloud/models/DeleteTemplatesRequest.hpp>
#include <alibabacloud/models/DeleteTemplatesResponseBody.hpp>
#include <alibabacloud/models/DeleteTemplatesResponse.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceRequest.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceResponseBody.hpp>
#include <alibabacloud/models/DeleteVirtualMFADeviceResponse.hpp>
#include <alibabacloud/models/DescribeAclEntriesRequest.hpp>
#include <alibabacloud/models/DescribeAclEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeAclEntriesResponse.hpp>
#include <alibabacloud/models/DescribeAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/DescribeAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBundlesRequest.hpp>
#include <alibabacloud/models/DescribeBundlesResponseBody.hpp>
#include <alibabacloud/models/DescribeBundlesResponse.hpp>
#include <alibabacloud/models/DescribeCdsFileShareLinksRequest.hpp>
#include <alibabacloud/models/DescribeCdsFileShareLinksResponseBody.hpp>
#include <alibabacloud/models/DescribeCdsFileShareLinksResponse.hpp>
#include <alibabacloud/models/DescribeCensRequest.hpp>
#include <alibabacloud/models/DescribeCensResponseBody.hpp>
#include <alibabacloud/models/DescribeCensResponse.hpp>
#include <alibabacloud/models/DescribeCenterPolicyListRequest.hpp>
#include <alibabacloud/models/DescribeCenterPolicyListResponseBody.hpp>
#include <alibabacloud/models/DescribeCenterPolicyListResponse.hpp>
#include <alibabacloud/models/DescribeClientEventsRequest.hpp>
#include <alibabacloud/models/DescribeClientEventsResponseBody.hpp>
#include <alibabacloud/models/DescribeClientEventsResponse.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupDrivesRequest.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupDrivesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupDrivesResponse.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupsRequest.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudDiskGroupsResponse.hpp>
#include <alibabacloud/models/DescribeCloudDriveGroupsRequest.hpp>
#include <alibabacloud/models/DescribeCloudDriveGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudDriveGroupsResponse.hpp>
#include <alibabacloud/models/DescribeCloudDrivePermissionsRequest.hpp>
#include <alibabacloud/models/DescribeCloudDrivePermissionsResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudDrivePermissionsResponse.hpp>
#include <alibabacloud/models/DescribeCloudDriveUsersRequest.hpp>
#include <alibabacloud/models/DescribeCloudDriveUsersResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudDriveUsersResponse.hpp>
#include <alibabacloud/models/DescribeConfigGroupRequest.hpp>
#include <alibabacloud/models/DescribeConfigGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeConfigGroupResponse.hpp>
#include <alibabacloud/models/DescribeCustomizedListHeadersRequest.hpp>
#include <alibabacloud/models/DescribeCustomizedListHeadersResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomizedListHeadersResponse.hpp>
#include <alibabacloud/models/DescribeDesktopGroupSessionsRequest.hpp>
#include <alibabacloud/models/DescribeDesktopGroupSessionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopGroupSessionsResponse.hpp>
#include <alibabacloud/models/DescribeDesktopGroupsRequest.hpp>
#include <alibabacloud/models/DescribeDesktopGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopGroupsResponse.hpp>
#include <alibabacloud/models/DescribeDesktopInfoRequest.hpp>
#include <alibabacloud/models/DescribeDesktopInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopInfoResponse.hpp>
#include <alibabacloud/models/DescribeDesktopMetadataRequest.hpp>
#include <alibabacloud/models/DescribeDesktopMetadataResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopMetadataResponse.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserRequest.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserResponse.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserGroupRequest.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopOversoldUserGroupResponse.hpp>
#include <alibabacloud/models/DescribeDesktopSessionsRequest.hpp>
#include <alibabacloud/models/DescribeDesktopSessionsResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopSessionsResponse.hpp>
#include <alibabacloud/models/DescribeDesktopTypesRequest.hpp>
#include <alibabacloud/models/DescribeDesktopTypesResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopTypesResponse.hpp>
#include <alibabacloud/models/DescribeDesktopsRequest.hpp>
#include <alibabacloud/models/DescribeDesktopsResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopsResponse.hpp>
#include <alibabacloud/models/DescribeDesktopsInGroupRequest.hpp>
#include <alibabacloud/models/DescribeDesktopsInGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeDesktopsInGroupResponse.hpp>
#include <alibabacloud/models/DescribeDevicesRequest.hpp>
#include <alibabacloud/models/DescribeDevicesResponseBody.hpp>
#include <alibabacloud/models/DescribeDevicesResponse.hpp>
#include <alibabacloud/models/DescribeDirectoriesRequest.hpp>
#include <alibabacloud/models/DescribeDirectoriesResponseBody.hpp>
#include <alibabacloud/models/DescribeDirectoriesResponse.hpp>
#include <alibabacloud/models/DescribeDrivesRequest.hpp>
#include <alibabacloud/models/DescribeDrivesResponseBody.hpp>
#include <alibabacloud/models/DescribeDrivesResponse.hpp>
#include <alibabacloud/models/DescribeEcdReportTasksRequest.hpp>
#include <alibabacloud/models/DescribeEcdReportTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeEcdReportTasksResponse.hpp>
#include <alibabacloud/models/DescribeFlowMetricRequest.hpp>
#include <alibabacloud/models/DescribeFlowMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowMetricResponse.hpp>
#include <alibabacloud/models/DescribeFlowStatisticRequest.hpp>
#include <alibabacloud/models/DescribeFlowStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowStatisticResponse.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesRequest.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesResponse.hpp>
#include <alibabacloud/models/DescribeFotaPendingDesktopsRequest.hpp>
#include <alibabacloud/models/DescribeFotaPendingDesktopsResponseBody.hpp>
#include <alibabacloud/models/DescribeFotaPendingDesktopsResponse.hpp>
#include <alibabacloud/models/DescribeFotaTasksRequest.hpp>
#include <alibabacloud/models/DescribeFotaTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeFotaTasksResponse.hpp>
#include <alibabacloud/models/DescribeGlobalDesktopRecordsRequest.hpp>
#include <alibabacloud/models/DescribeGlobalDesktopRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalDesktopRecordsResponse.hpp>
#include <alibabacloud/models/DescribeGlobalTimerBatchesRequest.hpp>
#include <alibabacloud/models/DescribeGlobalTimerBatchesResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalTimerBatchesResponse.hpp>
#include <alibabacloud/models/DescribeGlobalTimerRecordsRequest.hpp>
#include <alibabacloud/models/DescribeGlobalTimerRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalTimerRecordsResponse.hpp>
#include <alibabacloud/models/DescribeGuestApplicationsRequest.hpp>
#include <alibabacloud/models/DescribeGuestApplicationsResponseBody.hpp>
#include <alibabacloud/models/DescribeGuestApplicationsResponse.hpp>
#include <alibabacloud/models/DescribeImageModifiedRecordsRequest.hpp>
#include <alibabacloud/models/DescribeImageModifiedRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeImageModifiedRecordsResponse.hpp>
#include <alibabacloud/models/DescribeImagePermissionRequest.hpp>
#include <alibabacloud/models/DescribeImagePermissionResponseBody.hpp>
#include <alibabacloud/models/DescribeImagePermissionResponse.hpp>
#include <alibabacloud/models/DescribeImagesRequest.hpp>
#include <alibabacloud/models/DescribeImagesResponseBody.hpp>
#include <alibabacloud/models/DescribeImagesResponse.hpp>
#include <alibabacloud/models/DescribeInvocationsRequest.hpp>
#include <alibabacloud/models/DescribeInvocationsResponseBody.hpp>
#include <alibabacloud/models/DescribeInvocationsResponse.hpp>
#include <alibabacloud/models/DescribeIpAddressesRequest.hpp>
#include <alibabacloud/models/DescribeIpAddressesResponseBody.hpp>
#include <alibabacloud/models/DescribeIpAddressesResponse.hpp>
#include <alibabacloud/models/DescribeKmsKeysRequest.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeKmsKeysResponse.hpp>
#include <alibabacloud/models/DescribeModificationPriceRequest.hpp>
#include <alibabacloud/models/DescribeModificationPriceResponseBody.hpp>
#include <alibabacloud/models/DescribeModificationPriceResponse.hpp>
#include <alibabacloud/models/DescribeNASFileSystemsRequest.hpp>
#include <alibabacloud/models/DescribeNASFileSystemsResponseBody.hpp>
#include <alibabacloud/models/DescribeNASFileSystemsResponse.hpp>
#include <alibabacloud/models/DescribeNatGatewaysRequest.hpp>
#include <alibabacloud/models/DescribeNatGatewaysResponseBody.hpp>
#include <alibabacloud/models/DescribeNatGatewaysResponse.hpp>
#include <alibabacloud/models/DescribeNetworkPackagesRequest.hpp>
#include <alibabacloud/models/DescribeNetworkPackagesResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkPackagesResponse.hpp>
#include <alibabacloud/models/DescribeOfficeSitesRequest.hpp>
#include <alibabacloud/models/DescribeOfficeSitesResponseBody.hpp>
#include <alibabacloud/models/DescribeOfficeSitesResponse.hpp>
#include <alibabacloud/models/DescribePolicyGroupsRequest.hpp>
#include <alibabacloud/models/DescribePolicyGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribePolicyGroupsResponse.hpp>
#include <alibabacloud/models/DescribePriceRequest.hpp>
#include <alibabacloud/models/DescribePriceResponseBody.hpp>
#include <alibabacloud/models/DescribePriceResponse.hpp>
#include <alibabacloud/models/DescribePriceForCreateDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/DescribePriceForCreateDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/DescribePriceForCreateDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/DescribePriceForModifyDesktopOversoldGroupSaleRequest.hpp>
#include <alibabacloud/models/DescribePriceForModifyDesktopOversoldGroupSaleResponseBody.hpp>
#include <alibabacloud/models/DescribePriceForModifyDesktopOversoldGroupSaleResponse.hpp>
#include <alibabacloud/models/DescribePriceForRenewDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/DescribePriceForRenewDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/DescribePriceForRenewDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/DescribeRecordFileRequest.hpp>
#include <alibabacloud/models/DescribeRecordFileResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordFileResponse.hpp>
#include <alibabacloud/models/DescribeRecordingsRequest.hpp>
#include <alibabacloud/models/DescribeRecordingsResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordingsResponse.hpp>
#include <alibabacloud/models/DescribeRefundPriceRequest.hpp>
#include <alibabacloud/models/DescribeRefundPriceResponseBody.hpp>
#include <alibabacloud/models/DescribeRefundPriceResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRenewalPriceRequest.hpp>
#include <alibabacloud/models/DescribeRenewalPriceResponseBody.hpp>
#include <alibabacloud/models/DescribeRenewalPriceResponse.hpp>
#include <alibabacloud/models/DescribeResourceByCenterPolicyIdRequest.hpp>
#include <alibabacloud/models/DescribeResourceByCenterPolicyIdResponseBody.hpp>
#include <alibabacloud/models/DescribeResourceByCenterPolicyIdResponse.hpp>
#include <alibabacloud/models/DescribeRouteEntryListRequest.hpp>
#include <alibabacloud/models/DescribeRouteEntryListResponseBody.hpp>
#include <alibabacloud/models/DescribeRouteEntryListResponse.hpp>
#include <alibabacloud/models/DescribeRouteTableListRequest.hpp>
#include <alibabacloud/models/DescribeRouteTableListResponseBody.hpp>
#include <alibabacloud/models/DescribeRouteTableListResponse.hpp>
#include <alibabacloud/models/DescribeSecurityGroupAttributeRequest.hpp>
#include <alibabacloud/models/DescribeSecurityGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityGroupAttributeResponse.hpp>
#include <alibabacloud/models/DescribeSessionStatisticRequest.hpp>
#include <alibabacloud/models/DescribeSessionStatisticResponseBody.hpp>
#include <alibabacloud/models/DescribeSessionStatisticResponse.hpp>
#include <alibabacloud/models/DescribeSnapshotsRequest.hpp>
#include <alibabacloud/models/DescribeSnapshotsResponseBody.hpp>
#include <alibabacloud/models/DescribeSnapshotsResponse.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesRequest.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesResponse.hpp>
#include <alibabacloud/models/DescribeSubnetsRequest.hpp>
#include <alibabacloud/models/DescribeSubnetsResponseBody.hpp>
#include <alibabacloud/models/DescribeSubnetsResponse.hpp>
#include <alibabacloud/models/DescribeTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeTimerGroupRequest.hpp>
#include <alibabacloud/models/DescribeTimerGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeTimerGroupResponse.hpp>
#include <alibabacloud/models/DescribeUserConnectTimeRequest.hpp>
#include <alibabacloud/models/DescribeUserConnectTimeResponseBody.hpp>
#include <alibabacloud/models/DescribeUserConnectTimeResponse.hpp>
#include <alibabacloud/models/DescribeUserConnectionRecordsRequest.hpp>
#include <alibabacloud/models/DescribeUserConnectionRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeUserConnectionRecordsResponse.hpp>
#include <alibabacloud/models/DescribeUserProfilePathRulesRequest.hpp>
#include <alibabacloud/models/DescribeUserProfilePathRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeUserProfilePathRulesResponse.hpp>
#include <alibabacloud/models/DescribeUsersInGroupRequest.hpp>
#include <alibabacloud/models/DescribeUsersInGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeUsersInGroupResponse.hpp>
#include <alibabacloud/models/DescribeUsersPasswordRequest.hpp>
#include <alibabacloud/models/DescribeUsersPasswordResponseBody.hpp>
#include <alibabacloud/models/DescribeUsersPasswordResponse.hpp>
#include <alibabacloud/models/DescribeVirtualMFADevicesRequest.hpp>
#include <alibabacloud/models/DescribeVirtualMFADevicesResponseBody.hpp>
#include <alibabacloud/models/DescribeVirtualMFADevicesResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DetachCenRequest.hpp>
#include <alibabacloud/models/DetachCenResponseBody.hpp>
#include <alibabacloud/models/DetachCenResponse.hpp>
#include <alibabacloud/models/DetachEndUserRequest.hpp>
#include <alibabacloud/models/DetachEndUserResponseBody.hpp>
#include <alibabacloud/models/DetachEndUserResponse.hpp>
#include <alibabacloud/models/DisableDesktopsInGroupRequest.hpp>
#include <alibabacloud/models/DisableDesktopsInGroupResponseBody.hpp>
#include <alibabacloud/models/DisableDesktopsInGroupResponse.hpp>
#include <alibabacloud/models/DisconnectDesktopSessionsRequest.hpp>
#include <alibabacloud/models/DisconnectDesktopSessionsResponseBody.hpp>
#include <alibabacloud/models/DisconnectDesktopSessionsResponse.hpp>
#include <alibabacloud/models/DissociateIpAddressRequest.hpp>
#include <alibabacloud/models/DissociateIpAddressResponseBody.hpp>
#include <alibabacloud/models/DissociateIpAddressResponse.hpp>
#include <alibabacloud/models/DissociateNetworkPackageRequest.hpp>
#include <alibabacloud/models/DissociateNetworkPackageResponseBody.hpp>
#include <alibabacloud/models/DissociateNetworkPackageResponse.hpp>
#include <alibabacloud/models/DownloadCdsFileRequest.hpp>
#include <alibabacloud/models/DownloadCdsFileResponseBody.hpp>
#include <alibabacloud/models/DownloadCdsFileResponse.hpp>
#include <alibabacloud/models/ExportClientEventsRequest.hpp>
#include <alibabacloud/models/ExportClientEventsResponseBody.hpp>
#include <alibabacloud/models/ExportClientEventsResponse.hpp>
#include <alibabacloud/models/ExportDesktopGroupInfoRequest.hpp>
#include <alibabacloud/models/ExportDesktopGroupInfoResponseBody.hpp>
#include <alibabacloud/models/ExportDesktopGroupInfoResponse.hpp>
#include <alibabacloud/models/ExportDesktopListInfoRequest.hpp>
#include <alibabacloud/models/ExportDesktopListInfoResponseBody.hpp>
#include <alibabacloud/models/ExportDesktopListInfoResponse.hpp>
#include <alibabacloud/models/GetAsyncTaskRequest.hpp>
#include <alibabacloud/models/GetAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/GetAsyncTaskResponse.hpp>
#include <alibabacloud/models/GetConnectionTicketRequest.hpp>
#include <alibabacloud/models/GetConnectionTicketResponseBody.hpp>
#include <alibabacloud/models/GetConnectionTicketResponse.hpp>
#include <alibabacloud/models/GetCoordinateTicketRequest.hpp>
#include <alibabacloud/models/GetCoordinateTicketResponseBody.hpp>
#include <alibabacloud/models/GetCoordinateTicketResponse.hpp>
#include <alibabacloud/models/GetDesktopGroupDetailRequest.hpp>
#include <alibabacloud/models/GetDesktopGroupDetailResponseBody.hpp>
#include <alibabacloud/models/GetDesktopGroupDetailResponse.hpp>
#include <alibabacloud/models/GetOfficeSiteSsoStatusRequest.hpp>
#include <alibabacloud/models/GetOfficeSiteSsoStatusResponseBody.hpp>
#include <alibabacloud/models/GetOfficeSiteSsoStatusResponse.hpp>
#include <alibabacloud/models/GetSpMetadataRequest.hpp>
#include <alibabacloud/models/GetSpMetadataResponseBody.hpp>
#include <alibabacloud/models/GetSpMetadataResponse.hpp>
#include <alibabacloud/models/HibernateDesktopsRequest.hpp>
#include <alibabacloud/models/HibernateDesktopsResponseBody.hpp>
#include <alibabacloud/models/HibernateDesktopsResponse.hpp>
#include <alibabacloud/models/ListCdsFilesRequest.hpp>
#include <alibabacloud/models/ListCdsFilesShrinkRequest.hpp>
#include <alibabacloud/models/ListCdsFilesResponseBody.hpp>
#include <alibabacloud/models/ListCdsFilesResponse.hpp>
#include <alibabacloud/models/ListDirectoryUsersRequest.hpp>
#include <alibabacloud/models/ListDirectoryUsersResponseBody.hpp>
#include <alibabacloud/models/ListDirectoryUsersResponse.hpp>
#include <alibabacloud/models/ListFilePermissionRequest.hpp>
#include <alibabacloud/models/ListFilePermissionResponseBody.hpp>
#include <alibabacloud/models/ListFilePermissionResponse.hpp>
#include <alibabacloud/models/ListInstalledAppsRequest.hpp>
#include <alibabacloud/models/ListInstalledAppsResponseBody.hpp>
#include <alibabacloud/models/ListInstalledAppsResponse.hpp>
#include <alibabacloud/models/ListOfficeSiteOverviewRequest.hpp>
#include <alibabacloud/models/ListOfficeSiteOverviewResponseBody.hpp>
#include <alibabacloud/models/ListOfficeSiteOverviewResponse.hpp>
#include <alibabacloud/models/ListOfficeSiteUsersRequest.hpp>
#include <alibabacloud/models/ListOfficeSiteUsersResponseBody.hpp>
#include <alibabacloud/models/ListOfficeSiteUsersResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTransferFileDownloadUrlRequest.hpp>
#include <alibabacloud/models/ListTransferFileDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/ListTransferFileDownloadUrlResponse.hpp>
#include <alibabacloud/models/ListTransferFilesRequest.hpp>
#include <alibabacloud/models/ListTransferFilesResponseBody.hpp>
#include <alibabacloud/models/ListTransferFilesResponse.hpp>
#include <alibabacloud/models/ListUserAdOrganizationUnitsRequest.hpp>
#include <alibabacloud/models/ListUserAdOrganizationUnitsResponseBody.hpp>
#include <alibabacloud/models/ListUserAdOrganizationUnitsResponse.hpp>
#include <alibabacloud/models/LockVirtualMFADeviceRequest.hpp>
#include <alibabacloud/models/LockVirtualMFADeviceResponseBody.hpp>
#include <alibabacloud/models/LockVirtualMFADeviceResponse.hpp>
#include <alibabacloud/models/MigrateDesktopsRequest.hpp>
#include <alibabacloud/models/MigrateDesktopsResponseBody.hpp>
#include <alibabacloud/models/MigrateDesktopsResponse.hpp>
#include <alibabacloud/models/MigrateImageProtocolRequest.hpp>
#include <alibabacloud/models/MigrateImageProtocolResponseBody.hpp>
#include <alibabacloud/models/MigrateImageProtocolResponse.hpp>
#include <alibabacloud/models/ModifyADConnectorDirectoryRequest.hpp>
#include <alibabacloud/models/ModifyADConnectorDirectoryResponseBody.hpp>
#include <alibabacloud/models/ModifyADConnectorDirectoryResponse.hpp>
#include <alibabacloud/models/ModifyADConnectorOfficeSiteRequest.hpp>
#include <alibabacloud/models/ModifyADConnectorOfficeSiteResponseBody.hpp>
#include <alibabacloud/models/ModifyADConnectorOfficeSiteResponse.hpp>
#include <alibabacloud/models/ModifyAclEntriesRequest.hpp>
#include <alibabacloud/models/ModifyAclEntriesResponseBody.hpp>
#include <alibabacloud/models/ModifyAclEntriesResponse.hpp>
#include <alibabacloud/models/ModifyAutoSnapshotPolicyRequest.hpp>
#include <alibabacloud/models/ModifyAutoSnapshotPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyAutoSnapshotPolicyResponse.hpp>
#include <alibabacloud/models/ModifyBundleRequest.hpp>
#include <alibabacloud/models/ModifyBundleResponseBody.hpp>
#include <alibabacloud/models/ModifyBundleResponse.hpp>
#include <alibabacloud/models/ModifyCdsFileRequest.hpp>
#include <alibabacloud/models/ModifyCdsFileResponseBody.hpp>
#include <alibabacloud/models/ModifyCdsFileResponse.hpp>
#include <alibabacloud/models/ModifyCdsFileShareLinkRequest.hpp>
#include <alibabacloud/models/ModifyCdsFileShareLinkResponseBody.hpp>
#include <alibabacloud/models/ModifyCdsFileShareLinkResponse.hpp>
#include <alibabacloud/models/ModifyCenterPolicyRequest.hpp>
#include <alibabacloud/models/ModifyCenterPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyCenterPolicyResponse.hpp>
#include <alibabacloud/models/ModifyCloudDriveGroupsRequest.hpp>
#include <alibabacloud/models/ModifyCloudDriveGroupsResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudDriveGroupsResponse.hpp>
#include <alibabacloud/models/ModifyCloudDrivePermissionRequest.hpp>
#include <alibabacloud/models/ModifyCloudDrivePermissionResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudDrivePermissionResponse.hpp>
#include <alibabacloud/models/ModifyCloudDriveUsersRequest.hpp>
#include <alibabacloud/models/ModifyCloudDriveUsersResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudDriveUsersResponse.hpp>
#include <alibabacloud/models/ModifyConfigGroupRequest.hpp>
#include <alibabacloud/models/ModifyConfigGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyConfigGroupResponse.hpp>
#include <alibabacloud/models/ModifyCustomizedListHeadersRequest.hpp>
#include <alibabacloud/models/ModifyCustomizedListHeadersResponseBody.hpp>
#include <alibabacloud/models/ModifyCustomizedListHeadersResponse.hpp>
#include <alibabacloud/models/ModifyDesktopChargeTypeRequest.hpp>
#include <alibabacloud/models/ModifyDesktopChargeTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopChargeTypeResponse.hpp>
#include <alibabacloud/models/ModifyDesktopGroupRequest.hpp>
#include <alibabacloud/models/ModifyDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopGroupResponse.hpp>
#include <alibabacloud/models/ModifyDesktopHostNameRequest.hpp>
#include <alibabacloud/models/ModifyDesktopHostNameResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopHostNameResponse.hpp>
#include <alibabacloud/models/ModifyDesktopNameRequest.hpp>
#include <alibabacloud/models/ModifyDesktopNameResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopNameResponse.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupSaleRequest.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupSaleResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldGroupSaleResponse.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldUserGroupRequest.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldUserGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopOversoldUserGroupResponse.hpp>
#include <alibabacloud/models/ModifyDesktopSpecRequest.hpp>
#include <alibabacloud/models/ModifyDesktopSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopSpecResponse.hpp>
#include <alibabacloud/models/ModifyDesktopTimerRequest.hpp>
#include <alibabacloud/models/ModifyDesktopTimerResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopTimerResponse.hpp>
#include <alibabacloud/models/ModifyDesktopsPolicyGroupRequest.hpp>
#include <alibabacloud/models/ModifyDesktopsPolicyGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyDesktopsPolicyGroupResponse.hpp>
#include <alibabacloud/models/ModifyDiskSpecRequest.hpp>
#include <alibabacloud/models/ModifyDiskSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyDiskSpecResponse.hpp>
#include <alibabacloud/models/ModifyEntitlementRequest.hpp>
#include <alibabacloud/models/ModifyEntitlementResponseBody.hpp>
#include <alibabacloud/models/ModifyEntitlementResponse.hpp>
#include <alibabacloud/models/ModifyImageAttributeRequest.hpp>
#include <alibabacloud/models/ModifyImageAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyImageAttributeResponse.hpp>
#include <alibabacloud/models/ModifyImagePermissionRequest.hpp>
#include <alibabacloud/models/ModifyImagePermissionResponseBody.hpp>
#include <alibabacloud/models/ModifyImagePermissionResponse.hpp>
#include <alibabacloud/models/ModifyNASDefaultMountTargetRequest.hpp>
#include <alibabacloud/models/ModifyNASDefaultMountTargetResponseBody.hpp>
#include <alibabacloud/models/ModifyNASDefaultMountTargetResponse.hpp>
#include <alibabacloud/models/ModifyNetworkPackageBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyNetworkPackageBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyNetworkPackageBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyNetworkPackageEnabledRequest.hpp>
#include <alibabacloud/models/ModifyNetworkPackageEnabledResponseBody.hpp>
#include <alibabacloud/models/ModifyNetworkPackageEnabledResponse.hpp>
#include <alibabacloud/models/ModifyOfficeSiteAttributeRequest.hpp>
#include <alibabacloud/models/ModifyOfficeSiteAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyOfficeSiteAttributeResponse.hpp>
#include <alibabacloud/models/ModifyOfficeSiteCrossDesktopAccessRequest.hpp>
#include <alibabacloud/models/ModifyOfficeSiteCrossDesktopAccessResponseBody.hpp>
#include <alibabacloud/models/ModifyOfficeSiteCrossDesktopAccessResponse.hpp>
#include <alibabacloud/models/ModifyOfficeSiteDnsInfoRequest.hpp>
#include <alibabacloud/models/ModifyOfficeSiteDnsInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyOfficeSiteDnsInfoResponse.hpp>
#include <alibabacloud/models/ModifyOfficeSiteMfaEnabledRequest.hpp>
#include <alibabacloud/models/ModifyOfficeSiteMfaEnabledResponseBody.hpp>
#include <alibabacloud/models/ModifyOfficeSiteMfaEnabledResponse.hpp>
#include <alibabacloud/models/ModifyPolicyGroupRequest.hpp>
#include <alibabacloud/models/ModifyPolicyGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyGroupResponse.hpp>
#include <alibabacloud/models/ModifyResourceCenterPolicyRequest.hpp>
#include <alibabacloud/models/ModifyResourceCenterPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyResourceCenterPolicyResponse.hpp>
#include <alibabacloud/models/ModifySecurityGroupAttributeRequest.hpp>
#include <alibabacloud/models/ModifySecurityGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityGroupAttributeResponse.hpp>
#include <alibabacloud/models/ModifyTemplateRequest.hpp>
#include <alibabacloud/models/ModifyTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyTemplateResponse.hpp>
#include <alibabacloud/models/ModifyTemplateBaseInfoRequest.hpp>
#include <alibabacloud/models/ModifyTemplateBaseInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyTemplateBaseInfoResponse.hpp>
#include <alibabacloud/models/ModifyTimerGroupRequest.hpp>
#include <alibabacloud/models/ModifyTimerGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyTimerGroupResponse.hpp>
#include <alibabacloud/models/ModifyUserEntitlementRequest.hpp>
#include <alibabacloud/models/ModifyUserEntitlementResponseBody.hpp>
#include <alibabacloud/models/ModifyUserEntitlementResponse.hpp>
#include <alibabacloud/models/ModifyUserToDesktopGroupRequest.hpp>
#include <alibabacloud/models/ModifyUserToDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyUserToDesktopGroupResponse.hpp>
#include <alibabacloud/models/MoveCdsFileRequest.hpp>
#include <alibabacloud/models/MoveCdsFileResponseBody.hpp>
#include <alibabacloud/models/MoveCdsFileResponse.hpp>
#include <alibabacloud/models/RebootDesktopsRequest.hpp>
#include <alibabacloud/models/RebootDesktopsResponseBody.hpp>
#include <alibabacloud/models/RebootDesktopsResponse.hpp>
#include <alibabacloud/models/RebuildDesktopsRequest.hpp>
#include <alibabacloud/models/RebuildDesktopsResponseBody.hpp>
#include <alibabacloud/models/RebuildDesktopsResponse.hpp>
#include <alibabacloud/models/ReleaseIpAddressRequest.hpp>
#include <alibabacloud/models/ReleaseIpAddressResponseBody.hpp>
#include <alibabacloud/models/ReleaseIpAddressResponse.hpp>
#include <alibabacloud/models/RemoveFilePermissionRequest.hpp>
#include <alibabacloud/models/RemoveFilePermissionShrinkRequest.hpp>
#include <alibabacloud/models/RemoveFilePermissionResponseBody.hpp>
#include <alibabacloud/models/RemoveFilePermissionResponse.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopGroupRequest.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopGroupResponse.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopOversoldUserGroupRequest.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopOversoldUserGroupResponseBody.hpp>
#include <alibabacloud/models/RemoveUserFromDesktopOversoldUserGroupResponse.hpp>
#include <alibabacloud/models/RenewDesktopGroupRequest.hpp>
#include <alibabacloud/models/RenewDesktopGroupResponseBody.hpp>
#include <alibabacloud/models/RenewDesktopGroupResponse.hpp>
#include <alibabacloud/models/RenewDesktopOversoldGroupRequest.hpp>
#include <alibabacloud/models/RenewDesktopOversoldGroupResponseBody.hpp>
#include <alibabacloud/models/RenewDesktopOversoldGroupResponse.hpp>
#include <alibabacloud/models/RenewDesktopsRequest.hpp>
#include <alibabacloud/models/RenewDesktopsResponseBody.hpp>
#include <alibabacloud/models/RenewDesktopsResponse.hpp>
#include <alibabacloud/models/RenewNetworkPackagesRequest.hpp>
#include <alibabacloud/models/RenewNetworkPackagesResponseBody.hpp>
#include <alibabacloud/models/RenewNetworkPackagesResponse.hpp>
#include <alibabacloud/models/ResetDesktopsRequest.hpp>
#include <alibabacloud/models/ResetDesktopsResponseBody.hpp>
#include <alibabacloud/models/ResetDesktopsResponse.hpp>
#include <alibabacloud/models/ResetNASDefaultMountTargetRequest.hpp>
#include <alibabacloud/models/ResetNASDefaultMountTargetResponseBody.hpp>
#include <alibabacloud/models/ResetNASDefaultMountTargetResponse.hpp>
#include <alibabacloud/models/ResetSnapshotRequest.hpp>
#include <alibabacloud/models/ResetSnapshotResponseBody.hpp>
#include <alibabacloud/models/ResetSnapshotResponse.hpp>
#include <alibabacloud/models/RevokeCoordinatePrivilegeRequest.hpp>
#include <alibabacloud/models/RevokeCoordinatePrivilegeResponseBody.hpp>
#include <alibabacloud/models/RevokeCoordinatePrivilegeResponse.hpp>
#include <alibabacloud/models/RunCommandRequest.hpp>
#include <alibabacloud/models/RunCommandResponseBody.hpp>
#include <alibabacloud/models/RunCommandResponse.hpp>
#include <alibabacloud/models/SendVerifyCodeRequest.hpp>
#include <alibabacloud/models/SendVerifyCodeResponseBody.hpp>
#include <alibabacloud/models/SendVerifyCodeResponse.hpp>
#include <alibabacloud/models/SetDesktopGroupScaleTimerRequest.hpp>
#include <alibabacloud/models/SetDesktopGroupScaleTimerResponseBody.hpp>
#include <alibabacloud/models/SetDesktopGroupScaleTimerResponse.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerRequest.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerResponseBody.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerResponse.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerStatusRequest.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerStatusResponseBody.hpp>
#include <alibabacloud/models/SetDesktopGroupTimerStatusResponse.hpp>
#include <alibabacloud/models/SetDesktopMaintenanceRequest.hpp>
#include <alibabacloud/models/SetDesktopMaintenanceResponseBody.hpp>
#include <alibabacloud/models/SetDesktopMaintenanceResponse.hpp>
#include <alibabacloud/models/SetDirectorySsoStatusRequest.hpp>
#include <alibabacloud/models/SetDirectorySsoStatusResponseBody.hpp>
#include <alibabacloud/models/SetDirectorySsoStatusResponse.hpp>
#include <alibabacloud/models/SetIdpMetadataRequest.hpp>
#include <alibabacloud/models/SetIdpMetadataResponseBody.hpp>
#include <alibabacloud/models/SetIdpMetadataResponse.hpp>
#include <alibabacloud/models/SetOfficeSiteSsoStatusRequest.hpp>
#include <alibabacloud/models/SetOfficeSiteSsoStatusResponseBody.hpp>
#include <alibabacloud/models/SetOfficeSiteSsoStatusResponse.hpp>
#include <alibabacloud/models/SetUserProfilePathRulesRequest.hpp>
#include <alibabacloud/models/SetUserProfilePathRulesShrinkRequest.hpp>
#include <alibabacloud/models/SetUserProfilePathRulesResponseBody.hpp>
#include <alibabacloud/models/SetUserProfilePathRulesResponse.hpp>
#include <alibabacloud/models/StartDesktopsRequest.hpp>
#include <alibabacloud/models/StartDesktopsResponseBody.hpp>
#include <alibabacloud/models/StartDesktopsResponse.hpp>
#include <alibabacloud/models/StopDesktopsRequest.hpp>
#include <alibabacloud/models/StopDesktopsResponseBody.hpp>
#include <alibabacloud/models/StopDesktopsResponse.hpp>
#include <alibabacloud/models/StopInvocationRequest.hpp>
#include <alibabacloud/models/StopInvocationResponseBody.hpp>
#include <alibabacloud/models/StopInvocationResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TransferTaskApprovalCallbackRequest.hpp>
#include <alibabacloud/models/TransferTaskApprovalCallbackResponseBody.hpp>
#include <alibabacloud/models/TransferTaskApprovalCallbackResponse.hpp>
#include <alibabacloud/models/UnbindConfigGroupRequest.hpp>
#include <alibabacloud/models/UnbindConfigGroupResponseBody.hpp>
#include <alibabacloud/models/UnbindConfigGroupResponse.hpp>
#include <alibabacloud/models/UnbindUserDesktopRequest.hpp>
#include <alibabacloud/models/UnbindUserDesktopResponseBody.hpp>
#include <alibabacloud/models/UnbindUserDesktopResponse.hpp>
#include <alibabacloud/models/UnlockVirtualMFADeviceRequest.hpp>
#include <alibabacloud/models/UnlockVirtualMFADeviceResponseBody.hpp>
#include <alibabacloud/models/UnlockVirtualMFADeviceResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateFotaTaskRequest.hpp>
#include <alibabacloud/models/UpdateFotaTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateFotaTaskResponse.hpp>
#include <alibabacloud/models/UploadImageRequest.hpp>
#include <alibabacloud/models/UploadImageResponseBody.hpp>
#include <alibabacloud/models/UploadImageResponse.hpp>
#include <alibabacloud/models/VerifyCenRequest.hpp>
#include <alibabacloud/models/VerifyCenResponseBody.hpp>
#include <alibabacloud/models/VerifyCenResponse.hpp>
#include <alibabacloud/models/WakeupDesktopsRequest.hpp>
#include <alibabacloud/models/WakeupDesktopsResponseBody.hpp>
#include <alibabacloud/models/WakeupDesktopsResponse.hpp>

#endif
