// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_AMQPOPEN20191212MODEL_HPP_
#define ALIBABACLOUD_AMQPOPEN20191212MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DataValue.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateBindingRequest.hpp>
#include <alibabacloud/models/CreateBindingResponseBody.hpp>
#include <alibabacloud/models/CreateBindingResponse.hpp>
#include <alibabacloud/models/CreateExchangeRequest.hpp>
#include <alibabacloud/models/CreateExchangeResponseBody.hpp>
#include <alibabacloud/models/CreateExchangeResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateQueueRequest.hpp>
#include <alibabacloud/models/CreateQueueResponseBody.hpp>
#include <alibabacloud/models/CreateQueueResponse.hpp>
#include <alibabacloud/models/CreateVirtualHostRequest.hpp>
#include <alibabacloud/models/CreateVirtualHostResponseBody.hpp>
#include <alibabacloud/models/CreateVirtualHostResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBindingRequest.hpp>
#include <alibabacloud/models/DeleteBindingResponseBody.hpp>
#include <alibabacloud/models/DeleteBindingResponse.hpp>
#include <alibabacloud/models/DeleteExchangeRequest.hpp>
#include <alibabacloud/models/DeleteExchangeResponseBody.hpp>
#include <alibabacloud/models/DeleteExchangeResponse.hpp>
#include <alibabacloud/models/DeleteQueueRequest.hpp>
#include <alibabacloud/models/DeleteQueueResponseBody.hpp>
#include <alibabacloud/models/DeleteQueueResponse.hpp>
#include <alibabacloud/models/DeleteVirtualHostRequest.hpp>
#include <alibabacloud/models/DeleteVirtualHostResponseBody.hpp>
#include <alibabacloud/models/DeleteVirtualHostResponse.hpp>
#include <alibabacloud/models/GetInstanceRequest.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetMetadataAmountRequest.hpp>
#include <alibabacloud/models/GetMetadataAmountResponseBody.hpp>
#include <alibabacloud/models/GetMetadataAmountResponse.hpp>
#include <alibabacloud/models/ListAccountsRequest.hpp>
#include <alibabacloud/models/ListAccountsResponseBody.hpp>
#include <alibabacloud/models/ListAccountsResponse.hpp>
#include <alibabacloud/models/ListBindingsRequest.hpp>
#include <alibabacloud/models/ListBindingsResponseBody.hpp>
#include <alibabacloud/models/ListBindingsResponse.hpp>
#include <alibabacloud/models/ListDownStreamBindingsRequest.hpp>
#include <alibabacloud/models/ListDownStreamBindingsResponseBody.hpp>
#include <alibabacloud/models/ListDownStreamBindingsResponse.hpp>
#include <alibabacloud/models/ListExchangeUpStreamBindingsRequest.hpp>
#include <alibabacloud/models/ListExchangeUpStreamBindingsResponseBody.hpp>
#include <alibabacloud/models/ListExchangeUpStreamBindingsResponse.hpp>
#include <alibabacloud/models/ListExchangesRequest.hpp>
#include <alibabacloud/models/ListExchangesResponseBody.hpp>
#include <alibabacloud/models/ListExchangesResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListQueueConsumersRequest.hpp>
#include <alibabacloud/models/ListQueueConsumersResponseBody.hpp>
#include <alibabacloud/models/ListQueueConsumersResponse.hpp>
#include <alibabacloud/models/ListQueueUpStreamBindingsRequest.hpp>
#include <alibabacloud/models/ListQueueUpStreamBindingsResponseBody.hpp>
#include <alibabacloud/models/ListQueueUpStreamBindingsResponse.hpp>
#include <alibabacloud/models/ListQueuesRequest.hpp>
#include <alibabacloud/models/ListQueuesResponseBody.hpp>
#include <alibabacloud/models/ListQueuesResponse.hpp>
#include <alibabacloud/models/ListVirtualHostsRequest.hpp>
#include <alibabacloud/models/ListVirtualHostsResponseBody.hpp>
#include <alibabacloud/models/ListVirtualHostsResponse.hpp>
#include <alibabacloud/models/UpdateInstanceRequest.hpp>
#include <alibabacloud/models/UpdateInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceResponse.hpp>
#include <alibabacloud/models/UpdateInstanceNameRequest.hpp>
#include <alibabacloud/models/UpdateInstanceNameResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceNameResponse.hpp>
#include <alibabacloud/models/CreateAccountResponseBodyData.hpp>
#include <alibabacloud/models/CreateInstanceRequestTags.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyDataTags.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyData.hpp>
#include <alibabacloud/models/GetMetadataAmountResponseBodyData.hpp>
#include <alibabacloud/models/ListBindingsResponseBodyDataBindings.hpp>
#include <alibabacloud/models/ListBindingsResponseBodyData.hpp>
#include <alibabacloud/models/ListDownStreamBindingsResponseBodyDataBindings.hpp>
#include <alibabacloud/models/ListDownStreamBindingsResponseBodyData.hpp>
#include <alibabacloud/models/ListExchangeUpStreamBindingsResponseBodyDataBindings.hpp>
#include <alibabacloud/models/ListExchangeUpStreamBindingsResponseBodyData.hpp>
#include <alibabacloud/models/ListExchangesResponseBodyDataExchanges.hpp>
#include <alibabacloud/models/ListExchangesResponseBodyData.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyDataInstancesTags.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyDataInstances.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyData.hpp>
#include <alibabacloud/models/ListQueueConsumersResponseBodyDataConsumers.hpp>
#include <alibabacloud/models/ListQueueConsumersResponseBodyData.hpp>
#include <alibabacloud/models/ListQueueUpStreamBindingsResponseBodyDataBindings.hpp>
#include <alibabacloud/models/ListQueueUpStreamBindingsResponseBodyData.hpp>
#include <alibabacloud/models/ListQueuesResponseBodyDataQueues.hpp>
#include <alibabacloud/models/ListQueuesResponseBodyData.hpp>
#include <alibabacloud/models/ListVirtualHostsResponseBodyDataVirtualHosts.hpp>
#include <alibabacloud/models/ListVirtualHostsResponseBodyData.hpp>

#endif
