// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SFMMULTIMODALAPP20250909MODEL_HPP_
#define ALIBABACLOUD_SFMMULTIMODALAPP20250909MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateCommandRequest.hpp>
#include <alibabacloud/models/CreateCommandShrinkRequest.hpp>
#include <alibabacloud/models/CreateCommandResponseBody.hpp>
#include <alibabacloud/models/CreateCommandResponse.hpp>
#include <alibabacloud/models/CreateMemoryRequest.hpp>
#include <alibabacloud/models/CreateMemoryShrinkRequest.hpp>
#include <alibabacloud/models/CreateMemoryResponseBody.hpp>
#include <alibabacloud/models/CreateMemoryResponse.hpp>
#include <alibabacloud/models/CreateMmAppRequest.hpp>
#include <alibabacloud/models/CreateMmAppShrinkRequest.hpp>
#include <alibabacloud/models/CreateMmAppResponseBody.hpp>
#include <alibabacloud/models/CreateMmAppResponse.hpp>
#include <alibabacloud/models/CreateProfileRequest.hpp>
#include <alibabacloud/models/CreateProfileShrinkRequest.hpp>
#include <alibabacloud/models/CreateProfileResponseBody.hpp>
#include <alibabacloud/models/CreateProfileResponse.hpp>
#include <alibabacloud/models/DeleteCommandRequest.hpp>
#include <alibabacloud/models/DeleteCommandResponseBody.hpp>
#include <alibabacloud/models/DeleteCommandResponse.hpp>
#include <alibabacloud/models/DeleteMemoryRequest.hpp>
#include <alibabacloud/models/DeleteMemoryResponseBody.hpp>
#include <alibabacloud/models/DeleteMemoryResponse.hpp>
#include <alibabacloud/models/DeleteMmAppRequest.hpp>
#include <alibabacloud/models/DeleteMmAppResponseBody.hpp>
#include <alibabacloud/models/DeleteMmAppResponse.hpp>
#include <alibabacloud/models/DeleteProfileRequest.hpp>
#include <alibabacloud/models/DeleteProfileResponseBody.hpp>
#include <alibabacloud/models/DeleteProfileResponse.hpp>
#include <alibabacloud/models/DescribeCommandRequest.hpp>
#include <alibabacloud/models/DescribeCommandResponseBody.hpp>
#include <alibabacloud/models/DescribeCommandResponse.hpp>
#include <alibabacloud/models/DescribeMmAppRequest.hpp>
#include <alibabacloud/models/DescribeMmAppResponseBody.hpp>
#include <alibabacloud/models/DescribeMmAppResponse.hpp>
#include <alibabacloud/models/DevicePageRequest.hpp>
#include <alibabacloud/models/DevicePageResponseBody.hpp>
#include <alibabacloud/models/DevicePageResponse.hpp>
#include <alibabacloud/models/DeviceUpdateRequest.hpp>
#include <alibabacloud/models/DeviceUpdateResponseBody.hpp>
#include <alibabacloud/models/DeviceUpdateResponse.hpp>
#include <alibabacloud/models/ListCommandRequest.hpp>
#include <alibabacloud/models/ListCommandResponseBody.hpp>
#include <alibabacloud/models/ListCommandResponse.hpp>
#include <alibabacloud/models/ListMmAppRequest.hpp>
#include <alibabacloud/models/ListMmAppResponseBody.hpp>
#include <alibabacloud/models/ListMmAppResponse.hpp>
#include <alibabacloud/models/ListPublishedMmAppRequest.hpp>
#include <alibabacloud/models/ListPublishedMmAppResponseBody.hpp>
#include <alibabacloud/models/ListPublishedMmAppResponse.hpp>
#include <alibabacloud/models/MmAppBindingMcpRequest.hpp>
#include <alibabacloud/models/MmAppBindingMcpShrinkRequest.hpp>
#include <alibabacloud/models/MmAppBindingMcpResponseBody.hpp>
#include <alibabacloud/models/MmAppBindingMcpResponse.hpp>
#include <alibabacloud/models/MmAppBindingRagRequest.hpp>
#include <alibabacloud/models/MmAppBindingRagShrinkRequest.hpp>
#include <alibabacloud/models/MmAppBindingRagResponseBody.hpp>
#include <alibabacloud/models/MmAppBindingRagResponse.hpp>
#include <alibabacloud/models/PatchMemoryConfigRequest.hpp>
#include <alibabacloud/models/PatchMemoryConfigResponseBody.hpp>
#include <alibabacloud/models/PatchMemoryConfigResponse.hpp>
#include <alibabacloud/models/PublishMmAppRequest.hpp>
#include <alibabacloud/models/PublishMmAppResponseBody.hpp>
#include <alibabacloud/models/PublishMmAppResponse.hpp>
#include <alibabacloud/models/QueryAppQuotaRequest.hpp>
#include <alibabacloud/models/QueryAppQuotaResponseBody.hpp>
#include <alibabacloud/models/QueryAppQuotaResponse.hpp>
#include <alibabacloud/models/QueryMemoryConfigRequest.hpp>
#include <alibabacloud/models/QueryMemoryConfigResponseBody.hpp>
#include <alibabacloud/models/QueryMemoryConfigResponse.hpp>
#include <alibabacloud/models/QueryMemoryListRequest.hpp>
#include <alibabacloud/models/QueryMemoryListResponseBody.hpp>
#include <alibabacloud/models/QueryMemoryListResponse.hpp>
#include <alibabacloud/models/QueryProfileRequest.hpp>
#include <alibabacloud/models/QueryProfileResponseBody.hpp>
#include <alibabacloud/models/QueryProfileResponse.hpp>
#include <alibabacloud/models/QueryUserProfileRequest.hpp>
#include <alibabacloud/models/QueryUserProfileResponseBody.hpp>
#include <alibabacloud/models/QueryUserProfileResponse.hpp>
#include <alibabacloud/models/UpdateCommandRequest.hpp>
#include <alibabacloud/models/UpdateCommandShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCommandResponseBody.hpp>
#include <alibabacloud/models/UpdateCommandResponse.hpp>
#include <alibabacloud/models/UpdateMemoryRequest.hpp>
#include <alibabacloud/models/UpdateMemoryShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMemoryResponseBody.hpp>
#include <alibabacloud/models/UpdateMemoryResponse.hpp>
#include <alibabacloud/models/UpdateMmAppRequest.hpp>
#include <alibabacloud/models/UpdateMmAppShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMmAppResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppResponse.hpp>
#include <alibabacloud/models/UpdateMmAppMemoryRequest.hpp>
#include <alibabacloud/models/UpdateMmAppMemoryResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppMemoryResponse.hpp>
#include <alibabacloud/models/UpdateMmAppRagRequest.hpp>
#include <alibabacloud/models/UpdateMmAppRagResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppRagResponse.hpp>
#include <alibabacloud/models/UpdateMmAppRagConfigRequest.hpp>
#include <alibabacloud/models/UpdateMmAppRagConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppRagConfigResponse.hpp>
#include <alibabacloud/models/UpdateMmAppRagWeightRequest.hpp>
#include <alibabacloud/models/UpdateMmAppRagWeightShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMmAppRagWeightResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppRagWeightResponse.hpp>
#include <alibabacloud/models/UpdateMmAppTransitionRequest.hpp>
#include <alibabacloud/models/UpdateMmAppTransitionResponseBody.hpp>
#include <alibabacloud/models/UpdateMmAppTransitionResponse.hpp>
#include <alibabacloud/models/UpdateProfileRequest.hpp>
#include <alibabacloud/models/UpdateProfileShrinkRequest.hpp>
#include <alibabacloud/models/UpdateProfileResponseBody.hpp>
#include <alibabacloud/models/UpdateProfileResponse.hpp>

#endif
