// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_APIG20240327MODEL_HPP_
#define ALIBABACLOUD_APIG20240327MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AgentServiceConfig.hpp>
#include <alibabacloud/models/AiServiceConfig.hpp>
#include <alibabacloud/models/AkSkIdentityConfig.hpp>
#include <alibabacloud/models/ApiKeyIdentityConfig.hpp>
#include <alibabacloud/models/ApiRouteConflictInfo.hpp>
#include <alibabacloud/models/Attachment.hpp>
#include <alibabacloud/models/AuthConfig.hpp>
#include <alibabacloud/models/AuthorizationResourceInfo.hpp>
#include <alibabacloud/models/Backend.hpp>
#include <alibabacloud/models/CheckServiceLinkedRoleResult.hpp>
#include <alibabacloud/models/ConsumerConfig.hpp>
#include <alibabacloud/models/ConsumerInfo.hpp>
#include <alibabacloud/models/DashboardFilter.hpp>
#include <alibabacloud/models/DomainInfo.hpp>
#include <alibabacloud/models/GatewayInfo.hpp>
#include <alibabacloud/models/SubDomainInfo.hpp>
#include <alibabacloud/models/EnvironmentInfo.hpp>
#include <alibabacloud/models/GatewayLogConfig.hpp>
#include <alibabacloud/models/HttpApiApiInfoDeployCntMapValue.hpp>
#include <alibabacloud/models/HttpApiMockContract.hpp>
#include <alibabacloud/models/HttpApiDeployConfig.hpp>
#include <alibabacloud/models/HttpApiVersionInfo.hpp>
#include <alibabacloud/models/HttpApiApiInfo.hpp>
#include <alibabacloud/models/HttpApiBackendMatchCondition.hpp>
#include <alibabacloud/models/HttpApiBackendMatchConditions.hpp>
#include <alibabacloud/models/HttpApiDomainInfo.hpp>
#include <alibabacloud/models/HttpApiInfoByName.hpp>
#include <alibabacloud/models/HttpApiParameter.hpp>
#include <alibabacloud/models/HttpApiRequestContract.hpp>
#include <alibabacloud/models/HttpApiResponseContract.hpp>
#include <alibabacloud/models/HttpApiOperation.hpp>
#include <alibabacloud/models/HttpApiOperationInfo.hpp>
#include <alibabacloud/models/HttpApiPublishRevisionInfo.hpp>
#include <alibabacloud/models/HttpApiVersionConfig.hpp>
#include <alibabacloud/models/HttpDubboTranscoder.hpp>
#include <alibabacloud/models/HttpRouteMatch.hpp>
#include <alibabacloud/models/HttpRoute.hpp>
#include <alibabacloud/models/JwtIdentityConfig.hpp>
#include <alibabacloud/models/KmsConfig.hpp>
#include <alibabacloud/models/LabelDetail.hpp>
#include <alibabacloud/models/McpServerConfig.hpp>
#include <alibabacloud/models/ParentResourceInfo.hpp>
#include <alibabacloud/models/PluginClassInfo.hpp>
#include <alibabacloud/models/PolicyClassInfo.hpp>
#include <alibabacloud/models/PolicyDetailInfo.hpp>
#include <alibabacloud/models/PolicyInfo.hpp>
#include <alibabacloud/models/ResourceInfo.hpp>
#include <alibabacloud/models/ResourceStatistic.hpp>
#include <alibabacloud/models/RiskCheckResults.hpp>
#include <alibabacloud/models/ServiceHealthCheck.hpp>
#include <alibabacloud/models/Service.hpp>
#include <alibabacloud/models/ServiceLinkedRole.hpp>
#include <alibabacloud/models/SslCertMetaInfo.hpp>
#include <alibabacloud/models/TlsCipherSuitesConfig.hpp>
#include <alibabacloud/models/AddGatewaySecurityGroupRuleRequest.hpp>
#include <alibabacloud/models/AddGatewaySecurityGroupRuleResponseBody.hpp>
#include <alibabacloud/models/AddGatewaySecurityGroupRuleResponse.hpp>
#include <alibabacloud/models/BatchDeleteConsumerAuthorizationRuleRequest.hpp>
#include <alibabacloud/models/BatchDeleteConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/BatchDeleteConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateAndAttachPolicyRequest.hpp>
#include <alibabacloud/models/CreateAndAttachPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateAndAttachPolicyResponse.hpp>
#include <alibabacloud/models/CreateConsumerRequest.hpp>
#include <alibabacloud/models/CreateConsumerResponseBody.hpp>
#include <alibabacloud/models/CreateConsumerResponse.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRuleRequest.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRulesRequest.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRulesResponseBody.hpp>
#include <alibabacloud/models/CreateConsumerAuthorizationRulesResponse.hpp>
#include <alibabacloud/models/CreateDomainRequest.hpp>
#include <alibabacloud/models/CreateDomainResponseBody.hpp>
#include <alibabacloud/models/CreateDomainResponse.hpp>
#include <alibabacloud/models/CreateEnvironmentRequest.hpp>
#include <alibabacloud/models/CreateEnvironmentResponseBody.hpp>
#include <alibabacloud/models/CreateEnvironmentResponse.hpp>
#include <alibabacloud/models/CreateGatewayRequest.hpp>
#include <alibabacloud/models/CreateGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateGatewayResponse.hpp>
#include <alibabacloud/models/CreateHttpApiRequest.hpp>
#include <alibabacloud/models/CreateHttpApiResponseBody.hpp>
#include <alibabacloud/models/CreateHttpApiResponse.hpp>
#include <alibabacloud/models/CreateHttpApiOperationRequest.hpp>
#include <alibabacloud/models/CreateHttpApiOperationResponseBody.hpp>
#include <alibabacloud/models/CreateHttpApiOperationResponse.hpp>
#include <alibabacloud/models/CreateHttpApiRouteRequest.hpp>
#include <alibabacloud/models/CreateHttpApiRouteResponseBody.hpp>
#include <alibabacloud/models/CreateHttpApiRouteResponse.hpp>
#include <alibabacloud/models/CreateMcpServerRequest.hpp>
#include <alibabacloud/models/CreateMcpServerResponseBody.hpp>
#include <alibabacloud/models/CreateMcpServerResponse.hpp>
#include <alibabacloud/models/CreatePluginAttachmentRequest.hpp>
#include <alibabacloud/models/CreatePluginAttachmentResponseBody.hpp>
#include <alibabacloud/models/CreatePluginAttachmentResponse.hpp>
#include <alibabacloud/models/CreatePolicyRequest.hpp>
#include <alibabacloud/models/CreatePolicyResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyResponse.hpp>
#include <alibabacloud/models/CreatePolicyAttachmentRequest.hpp>
#include <alibabacloud/models/CreatePolicyAttachmentResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyAttachmentResponse.hpp>
#include <alibabacloud/models/CreateSecretRequest.hpp>
#include <alibabacloud/models/CreateSecretResponseBody.hpp>
#include <alibabacloud/models/CreateSecretResponse.hpp>
#include <alibabacloud/models/CreateServiceRequest.hpp>
#include <alibabacloud/models/CreateServiceResponseBody.hpp>
#include <alibabacloud/models/CreateServiceResponse.hpp>
#include <alibabacloud/models/CreateServiceVersionRequest.hpp>
#include <alibabacloud/models/CreateServiceVersionResponseBody.hpp>
#include <alibabacloud/models/CreateServiceVersionResponse.hpp>
#include <alibabacloud/models/CreateSourceRequest.hpp>
#include <alibabacloud/models/CreateSourceResponseBody.hpp>
#include <alibabacloud/models/CreateSourceResponse.hpp>
#include <alibabacloud/models/DeleteConsumerResponseBody.hpp>
#include <alibabacloud/models/DeleteConsumerResponse.hpp>
#include <alibabacloud/models/DeleteConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/DeleteDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainResponse.hpp>
#include <alibabacloud/models/DeleteEnvironmentResponseBody.hpp>
#include <alibabacloud/models/DeleteEnvironmentResponse.hpp>
#include <alibabacloud/models/DeleteGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewayResponse.hpp>
#include <alibabacloud/models/DeleteGatewaySecurityGroupRuleRequest.hpp>
#include <alibabacloud/models/DeleteGatewaySecurityGroupRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteGatewaySecurityGroupRuleResponse.hpp>
#include <alibabacloud/models/DeleteHttpApiResponseBody.hpp>
#include <alibabacloud/models/DeleteHttpApiResponse.hpp>
#include <alibabacloud/models/DeleteHttpApiOperationResponseBody.hpp>
#include <alibabacloud/models/DeleteHttpApiOperationResponse.hpp>
#include <alibabacloud/models/DeleteHttpApiRouteResponseBody.hpp>
#include <alibabacloud/models/DeleteHttpApiRouteResponse.hpp>
#include <alibabacloud/models/DeleteMcpServerResponseBody.hpp>
#include <alibabacloud/models/DeleteMcpServerResponse.hpp>
#include <alibabacloud/models/DeletePluginAttachmentResponseBody.hpp>
#include <alibabacloud/models/DeletePluginAttachmentResponse.hpp>
#include <alibabacloud/models/DeletePolicyResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyResponse.hpp>
#include <alibabacloud/models/DeletePolicyAttachmentResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyAttachmentResponse.hpp>
#include <alibabacloud/models/DeleteSecretResponseBody.hpp>
#include <alibabacloud/models/DeleteSecretResponse.hpp>
#include <alibabacloud/models/DeleteServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceResponse.hpp>
#include <alibabacloud/models/DeleteServiceVersionResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceVersionResponse.hpp>
#include <alibabacloud/models/DeleteSourceResponseBody.hpp>
#include <alibabacloud/models/DeleteSourceResponse.hpp>
#include <alibabacloud/models/DeployHttpApiRequest.hpp>
#include <alibabacloud/models/DeployHttpApiResponseBody.hpp>
#include <alibabacloud/models/DeployHttpApiResponse.hpp>
#include <alibabacloud/models/DeployMcpServerResponseBody.hpp>
#include <alibabacloud/models/DeployMcpServerResponse.hpp>
#include <alibabacloud/models/ExportHttpApiResponseBody.hpp>
#include <alibabacloud/models/ExportHttpApiResponse.hpp>
#include <alibabacloud/models/GetConsumerResponseBody.hpp>
#include <alibabacloud/models/GetConsumerResponse.hpp>
#include <alibabacloud/models/GetConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/GetConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/GetDashboardRequest.hpp>
#include <alibabacloud/models/GetDashboardShrinkRequest.hpp>
#include <alibabacloud/models/GetDashboardResponseBody.hpp>
#include <alibabacloud/models/GetDashboardResponse.hpp>
#include <alibabacloud/models/GetDomainRequest.hpp>
#include <alibabacloud/models/GetDomainResponseBody.hpp>
#include <alibabacloud/models/GetDomainResponse.hpp>
#include <alibabacloud/models/GetEnvironmentRequest.hpp>
#include <alibabacloud/models/GetEnvironmentResponseBody.hpp>
#include <alibabacloud/models/GetEnvironmentResponse.hpp>
#include <alibabacloud/models/GetGatewayResponseBody.hpp>
#include <alibabacloud/models/GetGatewayResponse.hpp>
#include <alibabacloud/models/GetHttpApiResponseBody.hpp>
#include <alibabacloud/models/GetHttpApiResponse.hpp>
#include <alibabacloud/models/GetHttpApiOperationResponseBody.hpp>
#include <alibabacloud/models/GetHttpApiOperationResponse.hpp>
#include <alibabacloud/models/GetHttpApiRouteResponseBody.hpp>
#include <alibabacloud/models/GetHttpApiRouteResponse.hpp>
#include <alibabacloud/models/GetMcpServerResponseBody.hpp>
#include <alibabacloud/models/GetMcpServerResponse.hpp>
#include <alibabacloud/models/GetPluginAttachmentResponseBody.hpp>
#include <alibabacloud/models/GetPluginAttachmentResponse.hpp>
#include <alibabacloud/models/GetPolicyResponseBody.hpp>
#include <alibabacloud/models/GetPolicyResponse.hpp>
#include <alibabacloud/models/GetPolicyAttachmentResponseBody.hpp>
#include <alibabacloud/models/GetPolicyAttachmentResponse.hpp>
#include <alibabacloud/models/GetResourceOverviewRequest.hpp>
#include <alibabacloud/models/GetResourceOverviewResponseBody.hpp>
#include <alibabacloud/models/GetResourceOverviewResponse.hpp>
#include <alibabacloud/models/GetSecretValueResponseBody.hpp>
#include <alibabacloud/models/GetSecretValueResponse.hpp>
#include <alibabacloud/models/GetServiceResponseBody.hpp>
#include <alibabacloud/models/GetServiceResponse.hpp>
#include <alibabacloud/models/GetSourceResponseBody.hpp>
#include <alibabacloud/models/GetSourceResponse.hpp>
#include <alibabacloud/models/GetTraceConfigRequest.hpp>
#include <alibabacloud/models/GetTraceConfigResponseBody.hpp>
#include <alibabacloud/models/GetTraceConfigResponse.hpp>
#include <alibabacloud/models/ImportHttpApiRequest.hpp>
#include <alibabacloud/models/ImportHttpApiResponseBody.hpp>
#include <alibabacloud/models/ImportHttpApiResponse.hpp>
#include <alibabacloud/models/InstallPluginRequest.hpp>
#include <alibabacloud/models/InstallPluginResponseBody.hpp>
#include <alibabacloud/models/InstallPluginResponse.hpp>
#include <alibabacloud/models/ListConsumerAuthorizationRulesRequest.hpp>
#include <alibabacloud/models/ListConsumerAuthorizationRulesResponseBody.hpp>
#include <alibabacloud/models/ListConsumerAuthorizationRulesResponse.hpp>
#include <alibabacloud/models/ListConsumersRequest.hpp>
#include <alibabacloud/models/ListConsumersResponseBody.hpp>
#include <alibabacloud/models/ListConsumersResponse.hpp>
#include <alibabacloud/models/ListDomainsRequest.hpp>
#include <alibabacloud/models/ListDomainsResponseBody.hpp>
#include <alibabacloud/models/ListDomainsResponse.hpp>
#include <alibabacloud/models/ListEnvironmentsRequest.hpp>
#include <alibabacloud/models/ListEnvironmentsResponseBody.hpp>
#include <alibabacloud/models/ListEnvironmentsResponse.hpp>
#include <alibabacloud/models/ListGatewayFeaturesResponseBody.hpp>
#include <alibabacloud/models/ListGatewayFeaturesResponse.hpp>
#include <alibabacloud/models/ListGatewaysRequest.hpp>
#include <alibabacloud/models/ListGatewaysShrinkRequest.hpp>
#include <alibabacloud/models/ListGatewaysResponseBody.hpp>
#include <alibabacloud/models/ListGatewaysResponse.hpp>
#include <alibabacloud/models/ListHttpApiOperationsRequest.hpp>
#include <alibabacloud/models/ListHttpApiOperationsResponseBody.hpp>
#include <alibabacloud/models/ListHttpApiOperationsResponse.hpp>
#include <alibabacloud/models/ListHttpApiRoutesRequest.hpp>
#include <alibabacloud/models/ListHttpApiRoutesResponseBody.hpp>
#include <alibabacloud/models/ListHttpApiRoutesResponse.hpp>
#include <alibabacloud/models/ListHttpApisRequest.hpp>
#include <alibabacloud/models/ListHttpApisResponseBody.hpp>
#include <alibabacloud/models/ListHttpApisResponse.hpp>
#include <alibabacloud/models/ListMcpServersRequest.hpp>
#include <alibabacloud/models/ListMcpServersResponseBody.hpp>
#include <alibabacloud/models/ListMcpServersResponse.hpp>
#include <alibabacloud/models/ListPluginAttachmentsRequest.hpp>
#include <alibabacloud/models/ListPluginAttachmentsResponseBody.hpp>
#include <alibabacloud/models/ListPluginAttachmentsResponse.hpp>
#include <alibabacloud/models/ListPluginClassesRequest.hpp>
#include <alibabacloud/models/ListPluginClassesResponseBody.hpp>
#include <alibabacloud/models/ListPluginClassesResponse.hpp>
#include <alibabacloud/models/ListPluginsRequest.hpp>
#include <alibabacloud/models/ListPluginsResponseBody.hpp>
#include <alibabacloud/models/ListPluginsResponse.hpp>
#include <alibabacloud/models/ListPoliciesRequest.hpp>
#include <alibabacloud/models/ListPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListPoliciesResponse.hpp>
#include <alibabacloud/models/ListPolicyClassesRequest.hpp>
#include <alibabacloud/models/ListPolicyClassesResponseBody.hpp>
#include <alibabacloud/models/ListPolicyClassesResponse.hpp>
#include <alibabacloud/models/ListSecretReferencesRequest.hpp>
#include <alibabacloud/models/ListSecretReferencesResponseBody.hpp>
#include <alibabacloud/models/ListSecretReferencesResponse.hpp>
#include <alibabacloud/models/ListSecretsRequest.hpp>
#include <alibabacloud/models/ListSecretsResponseBody.hpp>
#include <alibabacloud/models/ListSecretsResponse.hpp>
#include <alibabacloud/models/ListServicesRequest.hpp>
#include <alibabacloud/models/ListServicesResponseBody.hpp>
#include <alibabacloud/models/ListServicesResponse.hpp>
#include <alibabacloud/models/ListSslCertsRequest.hpp>
#include <alibabacloud/models/ListSslCertsResponseBody.hpp>
#include <alibabacloud/models/ListSslCertsResponse.hpp>
#include <alibabacloud/models/ListZonesResponseBody.hpp>
#include <alibabacloud/models/ListZonesResponse.hpp>
#include <alibabacloud/models/QueryConsumerAuthorizationRulesRequest.hpp>
#include <alibabacloud/models/QueryConsumerAuthorizationRulesResponseBody.hpp>
#include <alibabacloud/models/QueryConsumerAuthorizationRulesResponse.hpp>
#include <alibabacloud/models/RemoveConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/RemoveConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/RestartGatewayResponseBody.hpp>
#include <alibabacloud/models/RestartGatewayResponse.hpp>
#include <alibabacloud/models/SyncMcpServersRequest.hpp>
#include <alibabacloud/models/SyncMcpServersResponseBody.hpp>
#include <alibabacloud/models/SyncMcpServersResponse.hpp>
#include <alibabacloud/models/UnDeployMcpServerResponseBody.hpp>
#include <alibabacloud/models/UnDeployMcpServerResponse.hpp>
#include <alibabacloud/models/UndeployHttpApiRequest.hpp>
#include <alibabacloud/models/UndeployHttpApiResponseBody.hpp>
#include <alibabacloud/models/UndeployHttpApiResponse.hpp>
#include <alibabacloud/models/UninstallPluginResponseBody.hpp>
#include <alibabacloud/models/UninstallPluginResponse.hpp>
#include <alibabacloud/models/UpdateAndAttachPolicyRequest.hpp>
#include <alibabacloud/models/UpdateAndAttachPolicyResponseBody.hpp>
#include <alibabacloud/models/UpdateAndAttachPolicyResponse.hpp>
#include <alibabacloud/models/UpdateConsumerRequest.hpp>
#include <alibabacloud/models/UpdateConsumerResponseBody.hpp>
#include <alibabacloud/models/UpdateConsumerResponse.hpp>
#include <alibabacloud/models/UpdateConsumerAuthorizationRuleRequest.hpp>
#include <alibabacloud/models/UpdateConsumerAuthorizationRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateConsumerAuthorizationRuleResponse.hpp>
#include <alibabacloud/models/UpdateDomainRequest.hpp>
#include <alibabacloud/models/UpdateDomainResponseBody.hpp>
#include <alibabacloud/models/UpdateDomainResponse.hpp>
#include <alibabacloud/models/UpdateEnvironmentRequest.hpp>
#include <alibabacloud/models/UpdateEnvironmentResponseBody.hpp>
#include <alibabacloud/models/UpdateEnvironmentResponse.hpp>
#include <alibabacloud/models/UpdateGatewayFeatureRequest.hpp>
#include <alibabacloud/models/UpdateGatewayFeatureResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayFeatureResponse.hpp>
#include <alibabacloud/models/UpdateGatewayNameRequest.hpp>
#include <alibabacloud/models/UpdateGatewayNameResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayNameResponse.hpp>
#include <alibabacloud/models/UpdateHttpApiRequest.hpp>
#include <alibabacloud/models/UpdateHttpApiResponseBody.hpp>
#include <alibabacloud/models/UpdateHttpApiResponse.hpp>
#include <alibabacloud/models/UpdateHttpApiOperationRequest.hpp>
#include <alibabacloud/models/UpdateHttpApiOperationResponseBody.hpp>
#include <alibabacloud/models/UpdateHttpApiOperationResponse.hpp>
#include <alibabacloud/models/UpdateHttpApiRouteRequest.hpp>
#include <alibabacloud/models/UpdateHttpApiRouteResponseBody.hpp>
#include <alibabacloud/models/UpdateHttpApiRouteResponse.hpp>
#include <alibabacloud/models/UpdateMcpServerRequest.hpp>
#include <alibabacloud/models/UpdateMcpServerResponseBody.hpp>
#include <alibabacloud/models/UpdateMcpServerResponse.hpp>
#include <alibabacloud/models/UpdatePluginAttachmentRequest.hpp>
#include <alibabacloud/models/UpdatePluginAttachmentResponseBody.hpp>
#include <alibabacloud/models/UpdatePluginAttachmentResponse.hpp>
#include <alibabacloud/models/UpdatePolicyRequest.hpp>
#include <alibabacloud/models/UpdatePolicyResponseBody.hpp>
#include <alibabacloud/models/UpdatePolicyResponse.hpp>
#include <alibabacloud/models/UpdateSecretRequest.hpp>
#include <alibabacloud/models/UpdateSecretResponseBody.hpp>
#include <alibabacloud/models/UpdateSecretResponse.hpp>
#include <alibabacloud/models/UpdateServiceRequest.hpp>
#include <alibabacloud/models/UpdateServiceResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceResponse.hpp>
#include <alibabacloud/models/UpdateServiceVersionRequest.hpp>
#include <alibabacloud/models/UpdateServiceVersionResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceVersionResponse.hpp>
#include <alibabacloud/models/UpgradeGatewayRequest.hpp>
#include <alibabacloud/models/UpgradeGatewayResponseBody.hpp>
#include <alibabacloud/models/UpgradeGatewayResponse.hpp>

#endif
