// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_DDOSBGP20180720MODEL_HPP_
#define ALIBABACLOUD_DDOSBGP20180720MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddIpRequest.hpp>
#include <alibabacloud/models/AddIpResponseBody.hpp>
#include <alibabacloud/models/AddIpResponse.hpp>
#include <alibabacloud/models/AddRdMemberListRequest.hpp>
#include <alibabacloud/models/AddRdMemberListShrinkRequest.hpp>
#include <alibabacloud/models/AddRdMemberListResponseBody.hpp>
#include <alibabacloud/models/AddRdMemberListResponse.hpp>
#include <alibabacloud/models/AttachAssetGroupToInstanceRequest.hpp>
#include <alibabacloud/models/AttachAssetGroupToInstanceShrinkRequest.hpp>
#include <alibabacloud/models/AttachAssetGroupToInstanceResponseBody.hpp>
#include <alibabacloud/models/AttachAssetGroupToInstanceResponse.hpp>
#include <alibabacloud/models/AttachToPolicyRequest.hpp>
#include <alibabacloud/models/AttachToPolicyShrinkRequest.hpp>
#include <alibabacloud/models/AttachToPolicyResponseBody.hpp>
#include <alibabacloud/models/AttachToPolicyResponse.hpp>
#include <alibabacloud/models/CheckAccessLogAuthRequest.hpp>
#include <alibabacloud/models/CheckAccessLogAuthResponseBody.hpp>
#include <alibabacloud/models/CheckAccessLogAuthResponse.hpp>
#include <alibabacloud/models/CheckGrantRequest.hpp>
#include <alibabacloud/models/CheckGrantResponseBody.hpp>
#include <alibabacloud/models/CheckGrantResponse.hpp>
#include <alibabacloud/models/CreatePolicyRequest.hpp>
#include <alibabacloud/models/CreatePolicyResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyResponse.hpp>
#include <alibabacloud/models/DeleteBlackholeRequest.hpp>
#include <alibabacloud/models/DeleteBlackholeResponseBody.hpp>
#include <alibabacloud/models/DeleteBlackholeResponse.hpp>
#include <alibabacloud/models/DeleteIpRequest.hpp>
#include <alibabacloud/models/DeleteIpResponseBody.hpp>
#include <alibabacloud/models/DeleteIpResponse.hpp>
#include <alibabacloud/models/DeletePolicyRequest.hpp>
#include <alibabacloud/models/DeletePolicyResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyResponse.hpp>
#include <alibabacloud/models/DeleteRdMemberListRequest.hpp>
#include <alibabacloud/models/DeleteRdMemberListShrinkRequest.hpp>
#include <alibabacloud/models/DeleteRdMemberListResponseBody.hpp>
#include <alibabacloud/models/DeleteRdMemberListResponse.hpp>
#include <alibabacloud/models/DescribeAssetGroupRequest.hpp>
#include <alibabacloud/models/DescribeAssetGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeAssetGroupResponse.hpp>
#include <alibabacloud/models/DescribeAssetGroupToInstanceRequest.hpp>
#include <alibabacloud/models/DescribeAssetGroupToInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeAssetGroupToInstanceResponse.hpp>
#include <alibabacloud/models/DescribeDdosEventRequest.hpp>
#include <alibabacloud/models/DescribeDdosEventResponseBody.hpp>
#include <alibabacloud/models/DescribeDdosEventResponse.hpp>
#include <alibabacloud/models/DescribeDdosOriginInstanceBillRequest.hpp>
#include <alibabacloud/models/DescribeDdosOriginInstanceBillResponseBody.hpp>
#include <alibabacloud/models/DescribeDdosOriginInstanceBillResponse.hpp>
#include <alibabacloud/models/DescribeExcpetionCountRequest.hpp>
#include <alibabacloud/models/DescribeExcpetionCountResponseBody.hpp>
#include <alibabacloud/models/DescribeExcpetionCountResponse.hpp>
#include <alibabacloud/models/DescribeInstanceListRequest.hpp>
#include <alibabacloud/models/DescribeInstanceListResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceListResponse.hpp>
#include <alibabacloud/models/DescribeInstanceSpecsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceSpecsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceSpecsResponse.hpp>
#include <alibabacloud/models/DescribeOpEntitiesRequest.hpp>
#include <alibabacloud/models/DescribeOpEntitiesResponseBody.hpp>
#include <alibabacloud/models/DescribeOpEntitiesResponse.hpp>
#include <alibabacloud/models/DescribePackIpListRequest.hpp>
#include <alibabacloud/models/DescribePackIpListResponseBody.hpp>
#include <alibabacloud/models/DescribePackIpListResponse.hpp>
#include <alibabacloud/models/DescribeRdMemberListRequest.hpp>
#include <alibabacloud/models/DescribeRdMemberListResponseBody.hpp>
#include <alibabacloud/models/DescribeRdMemberListResponse.hpp>
#include <alibabacloud/models/DescribeRdStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeRdStatusResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeTrafficRequest.hpp>
#include <alibabacloud/models/DescribeTrafficResponseBody.hpp>
#include <alibabacloud/models/DescribeTrafficResponse.hpp>
#include <alibabacloud/models/DetachFromPolicyRequest.hpp>
#include <alibabacloud/models/DetachFromPolicyShrinkRequest.hpp>
#include <alibabacloud/models/DetachFromPolicyResponseBody.hpp>
#include <alibabacloud/models/DetachFromPolicyResponse.hpp>
#include <alibabacloud/models/DettachAssetGroupToInstanceRequest.hpp>
#include <alibabacloud/models/DettachAssetGroupToInstanceShrinkRequest.hpp>
#include <alibabacloud/models/DettachAssetGroupToInstanceResponseBody.hpp>
#include <alibabacloud/models/DettachAssetGroupToInstanceResponse.hpp>
#include <alibabacloud/models/GetSlsOpenStatusRequest.hpp>
#include <alibabacloud/models/GetSlsOpenStatusResponseBody.hpp>
#include <alibabacloud/models/GetSlsOpenStatusResponse.hpp>
#include <alibabacloud/models/ListOpenedAccessLogInstancesRequest.hpp>
#include <alibabacloud/models/ListOpenedAccessLogInstancesResponseBody.hpp>
#include <alibabacloud/models/ListOpenedAccessLogInstancesResponse.hpp>
#include <alibabacloud/models/ListPolicyRequest.hpp>
#include <alibabacloud/models/ListPolicyResponseBody.hpp>
#include <alibabacloud/models/ListPolicyResponse.hpp>
#include <alibabacloud/models/ListPolicyAttachmentRequest.hpp>
#include <alibabacloud/models/ListPolicyAttachmentShrinkRequest.hpp>
#include <alibabacloud/models/ListPolicyAttachmentResponseBody.hpp>
#include <alibabacloud/models/ListPolicyAttachmentResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyPolicyRequest.hpp>
#include <alibabacloud/models/ModifyPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyResponse.hpp>
#include <alibabacloud/models/ModifyPolicyContentRequest.hpp>
#include <alibabacloud/models/ModifyPolicyContentShrinkRequest.hpp>
#include <alibabacloud/models/ModifyPolicyContentResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyContentResponse.hpp>
#include <alibabacloud/models/ModifyRemarkRequest.hpp>
#include <alibabacloud/models/ModifyRemarkResponseBody.hpp>
#include <alibabacloud/models/ModifyRemarkResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/ReleaseDdosOriginInstanceRequest.hpp>
#include <alibabacloud/models/ReleaseDdosOriginInstanceResponseBody.hpp>
#include <alibabacloud/models/ReleaseDdosOriginInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>

#endif
