// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_HSM20231113MODEL_HPP_
#define ALIBABACLOUD_HSM20231113MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ConfigAuditLogRequest.hpp>
#include <alibabacloud/models/ConfigAuditLogResponseBody.hpp>
#include <alibabacloud/models/ConfigAuditLogResponse.hpp>
#include <alibabacloud/models/ConfigBackupRemarkRequest.hpp>
#include <alibabacloud/models/ConfigBackupRemarkResponseBody.hpp>
#include <alibabacloud/models/ConfigBackupRemarkResponse.hpp>
#include <alibabacloud/models/ConfigBackupTaskRequest.hpp>
#include <alibabacloud/models/ConfigBackupTaskResponseBody.hpp>
#include <alibabacloud/models/ConfigBackupTaskResponse.hpp>
#include <alibabacloud/models/ConfigClusterCertificateRequest.hpp>
#include <alibabacloud/models/ConfigClusterCertificateResponseBody.hpp>
#include <alibabacloud/models/ConfigClusterCertificateResponse.hpp>
#include <alibabacloud/models/ConfigClusterNameRequest.hpp>
#include <alibabacloud/models/ConfigClusterNameResponseBody.hpp>
#include <alibabacloud/models/ConfigClusterNameResponse.hpp>
#include <alibabacloud/models/ConfigClusterSubnetRequest.hpp>
#include <alibabacloud/models/ConfigClusterSubnetShrinkRequest.hpp>
#include <alibabacloud/models/ConfigClusterSubnetResponseBody.hpp>
#include <alibabacloud/models/ConfigClusterSubnetResponse.hpp>
#include <alibabacloud/models/ConfigClusterWhitelistRequest.hpp>
#include <alibabacloud/models/ConfigClusterWhitelistResponseBody.hpp>
#include <alibabacloud/models/ConfigClusterWhitelistResponse.hpp>
#include <alibabacloud/models/ConfigImageRemarkRequest.hpp>
#include <alibabacloud/models/ConfigImageRemarkResponseBody.hpp>
#include <alibabacloud/models/ConfigImageRemarkResponse.hpp>
#include <alibabacloud/models/ConfigInstanceIpAddressRequest.hpp>
#include <alibabacloud/models/ConfigInstanceIpAddressResponseBody.hpp>
#include <alibabacloud/models/ConfigInstanceIpAddressResponse.hpp>
#include <alibabacloud/models/ConfigInstanceRemarkRequest.hpp>
#include <alibabacloud/models/ConfigInstanceRemarkResponseBody.hpp>
#include <alibabacloud/models/ConfigInstanceRemarkResponse.hpp>
#include <alibabacloud/models/ConfigInstanceWhitelistRequest.hpp>
#include <alibabacloud/models/ConfigInstanceWhitelistResponseBody.hpp>
#include <alibabacloud/models/ConfigInstanceWhitelistResponse.hpp>
#include <alibabacloud/models/CopyImageRequest.hpp>
#include <alibabacloud/models/CopyImageResponseBody.hpp>
#include <alibabacloud/models/CopyImageResponse.hpp>
#include <alibabacloud/models/CreateClusterRequest.hpp>
#include <alibabacloud/models/CreateClusterResponseBody.hpp>
#include <alibabacloud/models/CreateClusterResponse.hpp>
#include <alibabacloud/models/DeleteClusterRequest.hpp>
#include <alibabacloud/models/DeleteClusterResponseBody.hpp>
#include <alibabacloud/models/DeleteClusterResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DownloadClusterManagedCertRequest.hpp>
#include <alibabacloud/models/DownloadClusterManagedCertResponseBody.hpp>
#include <alibabacloud/models/DownloadClusterManagedCertResponse.hpp>
#include <alibabacloud/models/EnableBackupRequest.hpp>
#include <alibabacloud/models/EnableBackupResponseBody.hpp>
#include <alibabacloud/models/EnableBackupResponse.hpp>
#include <alibabacloud/models/ExportImageRequest.hpp>
#include <alibabacloud/models/ExportImageResponseBody.hpp>
#include <alibabacloud/models/ExportImageResponse.hpp>
#include <alibabacloud/models/GetAuditLogStatusRequest.hpp>
#include <alibabacloud/models/GetAuditLogStatusResponseBody.hpp>
#include <alibabacloud/models/GetAuditLogStatusResponse.hpp>
#include <alibabacloud/models/GetBackupRequest.hpp>
#include <alibabacloud/models/GetBackupResponseBody.hpp>
#include <alibabacloud/models/GetBackupResponse.hpp>
#include <alibabacloud/models/GetClusterRequest.hpp>
#include <alibabacloud/models/GetClusterResponseBody.hpp>
#include <alibabacloud/models/GetClusterResponse.hpp>
#include <alibabacloud/models/GetImageRequest.hpp>
#include <alibabacloud/models/GetImageResponseBody.hpp>
#include <alibabacloud/models/GetImageResponse.hpp>
#include <alibabacloud/models/GetInstanceRequest.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetJobRequest.hpp>
#include <alibabacloud/models/GetJobResponseBody.hpp>
#include <alibabacloud/models/GetJobResponse.hpp>
#include <alibabacloud/models/InitializeAuditLogResponseBody.hpp>
#include <alibabacloud/models/InitializeAuditLogResponse.hpp>
#include <alibabacloud/models/InitializeClusterRequest.hpp>
#include <alibabacloud/models/InitializeClusterResponseBody.hpp>
#include <alibabacloud/models/InitializeClusterResponse.hpp>
#include <alibabacloud/models/JoinClusterRequest.hpp>
#include <alibabacloud/models/JoinClusterResponseBody.hpp>
#include <alibabacloud/models/JoinClusterResponse.hpp>
#include <alibabacloud/models/LeaveClusterRequest.hpp>
#include <alibabacloud/models/LeaveClusterResponseBody.hpp>
#include <alibabacloud/models/LeaveClusterResponse.hpp>
#include <alibabacloud/models/ListBackupsRequest.hpp>
#include <alibabacloud/models/ListBackupsResponseBody.hpp>
#include <alibabacloud/models/ListBackupsResponse.hpp>
#include <alibabacloud/models/ListClustersRequest.hpp>
#include <alibabacloud/models/ListClustersResponseBody.hpp>
#include <alibabacloud/models/ListClustersResponse.hpp>
#include <alibabacloud/models/ListImagesRequest.hpp>
#include <alibabacloud/models/ListImagesResponseBody.hpp>
#include <alibabacloud/models/ListImagesResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/PauseInstanceRequest.hpp>
#include <alibabacloud/models/PauseInstanceResponseBody.hpp>
#include <alibabacloud/models/PauseInstanceResponse.hpp>
#include <alibabacloud/models/QuickDeployClusterRequest.hpp>
#include <alibabacloud/models/QuickDeployClusterShrinkRequest.hpp>
#include <alibabacloud/models/QuickDeployClusterResponseBody.hpp>
#include <alibabacloud/models/QuickDeployClusterResponse.hpp>
#include <alibabacloud/models/QuickInitInstanceRequest.hpp>
#include <alibabacloud/models/QuickInitInstanceResponseBody.hpp>
#include <alibabacloud/models/QuickInitInstanceResponse.hpp>
#include <alibabacloud/models/ResetBackupRequest.hpp>
#include <alibabacloud/models/ResetBackupResponseBody.hpp>
#include <alibabacloud/models/ResetBackupResponse.hpp>
#include <alibabacloud/models/ResetInstanceRequest.hpp>
#include <alibabacloud/models/ResetInstanceResponseBody.hpp>
#include <alibabacloud/models/ResetInstanceResponse.hpp>
#include <alibabacloud/models/RestoreInstanceRequest.hpp>
#include <alibabacloud/models/RestoreInstanceResponseBody.hpp>
#include <alibabacloud/models/RestoreInstanceResponse.hpp>
#include <alibabacloud/models/ResumeInstanceRequest.hpp>
#include <alibabacloud/models/ResumeInstanceResponseBody.hpp>
#include <alibabacloud/models/ResumeInstanceResponse.hpp>
#include <alibabacloud/models/RotateClusterManagedCertRequest.hpp>
#include <alibabacloud/models/RotateClusterManagedCertResponseBody.hpp>
#include <alibabacloud/models/RotateClusterManagedCertResponse.hpp>
#include <alibabacloud/models/SwitchClusterMasterRequest.hpp>
#include <alibabacloud/models/SwitchClusterMasterResponseBody.hpp>
#include <alibabacloud/models/SwitchClusterMasterResponse.hpp>
#include <alibabacloud/models/SyncClusterRequest.hpp>
#include <alibabacloud/models/SyncClusterResponseBody.hpp>
#include <alibabacloud/models/SyncClusterResponse.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsZones.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/ExportImageResponseBodyJob.hpp>
#include <alibabacloud/models/GetBackupResponseBodyBackup.hpp>
#include <alibabacloud/models/GetClusterResponseBodyClusterInstances.hpp>
#include <alibabacloud/models/GetClusterResponseBodyClusterZones.hpp>
#include <alibabacloud/models/GetClusterResponseBodyCluster.hpp>
#include <alibabacloud/models/GetImageResponseBodyImage.hpp>
#include <alibabacloud/models/GetInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/GetJobResponseBodyJob.hpp>
#include <alibabacloud/models/JoinClusterResponseBodyJob.hpp>
#include <alibabacloud/models/ListBackupsResponseBodyBackups.hpp>
#include <alibabacloud/models/ListClustersResponseBodyClusters.hpp>
#include <alibabacloud/models/ListImagesResponseBodyImages.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstances.hpp>
#include <alibabacloud/models/QuickDeployClusterResponseBodyJob.hpp>
#include <alibabacloud/models/QuickInitInstanceResponseBodyJob.hpp>
#include <alibabacloud/models/ResetInstanceResponseBodyJob.hpp>
#include <alibabacloud/models/RestoreInstanceResponseBodyJob.hpp>
#include <alibabacloud/models/RotateClusterManagedCertResponseBodyJob.hpp>
#include <alibabacloud/models/SyncClusterResponseBodyJob.hpp>

#endif
