// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_OUTBOUNDBOT20191226MODEL_HPP_
#define ALIBABACLOUD_OUTBOUNDBOT20191226MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AssignJobsRequest.hpp>
#include <alibabacloud/models/AssignJobsResponseBody.hpp>
#include <alibabacloud/models/AssignJobsResponse.hpp>
#include <alibabacloud/models/AssignJobsAsyncRequest.hpp>
#include <alibabacloud/models/AssignJobsAsyncShrinkRequest.hpp>
#include <alibabacloud/models/AssignJobsAsyncResponseBody.hpp>
#include <alibabacloud/models/AssignJobsAsyncResponse.hpp>
#include <alibabacloud/models/CancelJobsRequest.hpp>
#include <alibabacloud/models/CancelJobsResponseBody.hpp>
#include <alibabacloud/models/CancelJobsResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateAgentProfileRequest.hpp>
#include <alibabacloud/models/CreateAgentProfileResponseBody.hpp>
#include <alibabacloud/models/CreateAgentProfileResponse.hpp>
#include <alibabacloud/models/CreateAnnotationMissionRequest.hpp>
#include <alibabacloud/models/CreateAnnotationMissionShrinkRequest.hpp>
#include <alibabacloud/models/CreateAnnotationMissionResponseBody.hpp>
#include <alibabacloud/models/CreateAnnotationMissionResponse.hpp>
#include <alibabacloud/models/CreateBatchJobsRequest.hpp>
#include <alibabacloud/models/CreateBatchJobsResponseBody.hpp>
#include <alibabacloud/models/CreateBatchJobsResponse.hpp>
#include <alibabacloud/models/CreateBatchRepeatJobRequest.hpp>
#include <alibabacloud/models/CreateBatchRepeatJobResponseBody.hpp>
#include <alibabacloud/models/CreateBatchRepeatJobResponse.hpp>
#include <alibabacloud/models/CreateBeebotIntentRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentShrinkRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentResponseBody.hpp>
#include <alibabacloud/models/CreateBeebotIntentResponse.hpp>
#include <alibabacloud/models/CreateBeebotIntentLgfRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentLgfShrinkRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentLgfResponseBody.hpp>
#include <alibabacloud/models/CreateBeebotIntentLgfResponse.hpp>
#include <alibabacloud/models/CreateBeebotIntentUserSayRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentUserSayShrinkRequest.hpp>
#include <alibabacloud/models/CreateBeebotIntentUserSayResponseBody.hpp>
#include <alibabacloud/models/CreateBeebotIntentUserSayResponse.hpp>
#include <alibabacloud/models/CreateDialogueFlowRequest.hpp>
#include <alibabacloud/models/CreateDialogueFlowResponseBody.hpp>
#include <alibabacloud/models/CreateDialogueFlowResponse.hpp>
#include <alibabacloud/models/CreateDownloadUrlRequest.hpp>
#include <alibabacloud/models/CreateDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/CreateDownloadUrlResponse.hpp>
#include <alibabacloud/models/CreateGlobalQuestionRequest.hpp>
#include <alibabacloud/models/CreateGlobalQuestionResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalQuestionResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateInstanceBindNumberRequest.hpp>
#include <alibabacloud/models/CreateInstanceBindNumberResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceBindNumberResponse.hpp>
#include <alibabacloud/models/CreateIntentRequest.hpp>
#include <alibabacloud/models/CreateIntentResponseBody.hpp>
#include <alibabacloud/models/CreateIntentResponse.hpp>
#include <alibabacloud/models/CreateJobDataParsingTaskRequest.hpp>
#include <alibabacloud/models/CreateJobDataParsingTaskResponseBody.hpp>
#include <alibabacloud/models/CreateJobDataParsingTaskResponse.hpp>
#include <alibabacloud/models/CreateJobGroupRequest.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBody.hpp>
#include <alibabacloud/models/CreateJobGroupResponse.hpp>
#include <alibabacloud/models/CreateJobGroupExportTaskRequest.hpp>
#include <alibabacloud/models/CreateJobGroupExportTaskResponseBody.hpp>
#include <alibabacloud/models/CreateJobGroupExportTaskResponse.hpp>
#include <alibabacloud/models/CreateScriptRequest.hpp>
#include <alibabacloud/models/CreateScriptResponseBody.hpp>
#include <alibabacloud/models/CreateScriptResponse.hpp>
#include <alibabacloud/models/CreateScriptWaveformRequest.hpp>
#include <alibabacloud/models/CreateScriptWaveformResponseBody.hpp>
#include <alibabacloud/models/CreateScriptWaveformResponse.hpp>
#include <alibabacloud/models/CreateTagRequest.hpp>
#include <alibabacloud/models/CreateTagResponseBody.hpp>
#include <alibabacloud/models/CreateTagResponse.hpp>
#include <alibabacloud/models/CreateTaskExportTaskRequest.hpp>
#include <alibabacloud/models/CreateTaskExportTaskResponseBody.hpp>
#include <alibabacloud/models/CreateTaskExportTaskResponse.hpp>
#include <alibabacloud/models/DeleteAgentProfilesRequest.hpp>
#include <alibabacloud/models/DeleteAgentProfilesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAgentProfilesResponseBody.hpp>
#include <alibabacloud/models/DeleteAgentProfilesResponse.hpp>
#include <alibabacloud/models/DeleteAllNumberDistrictInfoResponseBody.hpp>
#include <alibabacloud/models/DeleteAllNumberDistrictInfoResponse.hpp>
#include <alibabacloud/models/DeleteBeebotIntentRequest.hpp>
#include <alibabacloud/models/DeleteBeebotIntentResponseBody.hpp>
#include <alibabacloud/models/DeleteBeebotIntentResponse.hpp>
#include <alibabacloud/models/DeleteBeebotIntentLgfRequest.hpp>
#include <alibabacloud/models/DeleteBeebotIntentLgfResponseBody.hpp>
#include <alibabacloud/models/DeleteBeebotIntentLgfResponse.hpp>
#include <alibabacloud/models/DeleteBeebotIntentUserSayRequest.hpp>
#include <alibabacloud/models/DeleteBeebotIntentUserSayResponseBody.hpp>
#include <alibabacloud/models/DeleteBeebotIntentUserSayResponse.hpp>
#include <alibabacloud/models/DeleteContactBlockListRequest.hpp>
#include <alibabacloud/models/DeleteContactBlockListResponseBody.hpp>
#include <alibabacloud/models/DeleteContactBlockListResponse.hpp>
#include <alibabacloud/models/DeleteContactWhiteListRequest.hpp>
#include <alibabacloud/models/DeleteContactWhiteListResponseBody.hpp>
#include <alibabacloud/models/DeleteContactWhiteListResponse.hpp>
#include <alibabacloud/models/DeleteDialogueFlowRequest.hpp>
#include <alibabacloud/models/DeleteDialogueFlowResponseBody.hpp>
#include <alibabacloud/models/DeleteDialogueFlowResponse.hpp>
#include <alibabacloud/models/DeleteGlobalQuestionRequest.hpp>
#include <alibabacloud/models/DeleteGlobalQuestionResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalQuestionResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteIntentRequest.hpp>
#include <alibabacloud/models/DeleteIntentResponseBody.hpp>
#include <alibabacloud/models/DeleteIntentResponse.hpp>
#include <alibabacloud/models/DeleteJobGroupRequest.hpp>
#include <alibabacloud/models/DeleteJobGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteJobGroupResponse.hpp>
#include <alibabacloud/models/DeleteOutboundCallNumberRequest.hpp>
#include <alibabacloud/models/DeleteOutboundCallNumberResponseBody.hpp>
#include <alibabacloud/models/DeleteOutboundCallNumberResponse.hpp>
#include <alibabacloud/models/DeleteScriptRequest.hpp>
#include <alibabacloud/models/DeleteScriptResponseBody.hpp>
#include <alibabacloud/models/DeleteScriptResponse.hpp>
#include <alibabacloud/models/DeleteScriptRecordingRequest.hpp>
#include <alibabacloud/models/DeleteScriptRecordingResponseBody.hpp>
#include <alibabacloud/models/DeleteScriptRecordingResponse.hpp>
#include <alibabacloud/models/DeleteScriptWaveformRequest.hpp>
#include <alibabacloud/models/DeleteScriptWaveformResponseBody.hpp>
#include <alibabacloud/models/DeleteScriptWaveformResponse.hpp>
#include <alibabacloud/models/DescribeBeebotIntentRequest.hpp>
#include <alibabacloud/models/DescribeBeebotIntentResponseBody.hpp>
#include <alibabacloud/models/DescribeBeebotIntentResponse.hpp>
#include <alibabacloud/models/DescribeDialogueNodeStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeDialogueNodeStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeDialogueNodeStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeDsReportsRequest.hpp>
#include <alibabacloud/models/DescribeDsReportsResponseBody.hpp>
#include <alibabacloud/models/DescribeDsReportsResponse.hpp>
#include <alibabacloud/models/DescribeGlobalQuestionRequest.hpp>
#include <alibabacloud/models/DescribeGlobalQuestionResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalQuestionResponse.hpp>
#include <alibabacloud/models/DescribeGroupExecutingInfoRequest.hpp>
#include <alibabacloud/models/DescribeGroupExecutingInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupExecutingInfoResponse.hpp>
#include <alibabacloud/models/DescribeInstanceRequest.hpp>
#include <alibabacloud/models/DescribeInstanceResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceResponse.hpp>
#include <alibabacloud/models/DescribeIntentRequest.hpp>
#include <alibabacloud/models/DescribeIntentResponseBody.hpp>
#include <alibabacloud/models/DescribeIntentResponse.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsRequest.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsResponseBody.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsResponse.hpp>
#include <alibabacloud/models/DescribeJobRequest.hpp>
#include <alibabacloud/models/DescribeJobResponseBody.hpp>
#include <alibabacloud/models/DescribeJobResponse.hpp>
#include <alibabacloud/models/DescribeJobDataParsingTaskProgressRequest.hpp>
#include <alibabacloud/models/DescribeJobDataParsingTaskProgressResponseBody.hpp>
#include <alibabacloud/models/DescribeJobDataParsingTaskProgressResponse.hpp>
#include <alibabacloud/models/DescribeJobGroupRequest.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeJobGroupResponse.hpp>
#include <alibabacloud/models/DescribeJobGroupExportTaskProgressRequest.hpp>
#include <alibabacloud/models/DescribeJobGroupExportTaskProgressResponseBody.hpp>
#include <alibabacloud/models/DescribeJobGroupExportTaskProgressResponse.hpp>
#include <alibabacloud/models/DescribeScriptRequest.hpp>
#include <alibabacloud/models/DescribeScriptResponseBody.hpp>
#include <alibabacloud/models/DescribeScriptResponse.hpp>
#include <alibabacloud/models/DescribeScriptVoiceConfigRequest.hpp>
#include <alibabacloud/models/DescribeScriptVoiceConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeScriptVoiceConfigResponse.hpp>
#include <alibabacloud/models/DescribeTtsConfigRequest.hpp>
#include <alibabacloud/models/DescribeTtsConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeTtsConfigResponse.hpp>
#include <alibabacloud/models/DescribeTtsDemoRequest.hpp>
#include <alibabacloud/models/DescribeTtsDemoResponseBody.hpp>
#include <alibabacloud/models/DescribeTtsDemoResponse.hpp>
#include <alibabacloud/models/DescribeTagHitsSummaryRequest.hpp>
#include <alibabacloud/models/DescribeTagHitsSummaryResponseBody.hpp>
#include <alibabacloud/models/DescribeTagHitsSummaryResponse.hpp>
#include <alibabacloud/models/DescribeTenantBindNumberRequest.hpp>
#include <alibabacloud/models/DescribeTenantBindNumberResponseBody.hpp>
#include <alibabacloud/models/DescribeTenantBindNumberResponse.hpp>
#include <alibabacloud/models/DialogueRequest.hpp>
#include <alibabacloud/models/DialogueResponseBody.hpp>
#include <alibabacloud/models/DialogueResponse.hpp>
#include <alibabacloud/models/DownloadRecordingRequest.hpp>
#include <alibabacloud/models/DownloadRecordingResponseBody.hpp>
#include <alibabacloud/models/DownloadRecordingResponse.hpp>
#include <alibabacloud/models/DownloadScriptRecordingRequest.hpp>
#include <alibabacloud/models/DownloadScriptRecordingResponseBody.hpp>
#include <alibabacloud/models/DownloadScriptRecordingResponse.hpp>
#include <alibabacloud/models/DuplicateScriptRequest.hpp>
#include <alibabacloud/models/DuplicateScriptResponseBody.hpp>
#include <alibabacloud/models/DuplicateScriptResponse.hpp>
#include <alibabacloud/models/ExportScriptRequest.hpp>
#include <alibabacloud/models/ExportScriptResponseBody.hpp>
#include <alibabacloud/models/ExportScriptResponse.hpp>
#include <alibabacloud/models/GenerateUploadUrlRequest.hpp>
#include <alibabacloud/models/GenerateUploadUrlResponseBody.hpp>
#include <alibabacloud/models/GenerateUploadUrlResponse.hpp>
#include <alibabacloud/models/GetAfterAnswerDelayPlaybackRequest.hpp>
#include <alibabacloud/models/GetAfterAnswerDelayPlaybackResponseBody.hpp>
#include <alibabacloud/models/GetAfterAnswerDelayPlaybackResponse.hpp>
#include <alibabacloud/models/GetAgentProfileRequest.hpp>
#include <alibabacloud/models/GetAgentProfileResponseBody.hpp>
#include <alibabacloud/models/GetAgentProfileResponse.hpp>
#include <alibabacloud/models/GetAgentProfileTemplateRequest.hpp>
#include <alibabacloud/models/GetAgentProfileTemplateResponseBody.hpp>
#include <alibabacloud/models/GetAgentProfileTemplateResponse.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryRequest.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBody.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponse.hpp>
#include <alibabacloud/models/GetAnnotationMissionTagInfoListRequest.hpp>
#include <alibabacloud/models/GetAnnotationMissionTagInfoListResponseBody.hpp>
#include <alibabacloud/models/GetAnnotationMissionTagInfoListResponse.hpp>
#include <alibabacloud/models/GetAsrServerInfoRequest.hpp>
#include <alibabacloud/models/GetAsrServerInfoResponseBody.hpp>
#include <alibabacloud/models/GetAsrServerInfoResponse.hpp>
#include <alibabacloud/models/GetAssignJobsAsyncResultRequest.hpp>
#include <alibabacloud/models/GetAssignJobsAsyncResultResponseBody.hpp>
#include <alibabacloud/models/GetAssignJobsAsyncResultResponse.hpp>
#include <alibabacloud/models/GetBaseStrategyPeriodRequest.hpp>
#include <alibabacloud/models/GetBaseStrategyPeriodResponseBody.hpp>
#include <alibabacloud/models/GetBaseStrategyPeriodResponse.hpp>
#include <alibabacloud/models/GetConcurrentConversationQuotaResponseBody.hpp>
#include <alibabacloud/models/GetConcurrentConversationQuotaResponse.hpp>
#include <alibabacloud/models/GetContactBlockListRequest.hpp>
#include <alibabacloud/models/GetContactBlockListResponseBody.hpp>
#include <alibabacloud/models/GetContactBlockListResponse.hpp>
#include <alibabacloud/models/GetContactWhiteListRequest.hpp>
#include <alibabacloud/models/GetContactWhiteListResponseBody.hpp>
#include <alibabacloud/models/GetContactWhiteListResponse.hpp>
#include <alibabacloud/models/GetCurrentConcurrencyRequest.hpp>
#include <alibabacloud/models/GetCurrentConcurrencyResponseBody.hpp>
#include <alibabacloud/models/GetCurrentConcurrencyResponse.hpp>
#include <alibabacloud/models/GetEmptyNumberNoMoreCallsInfoRequest.hpp>
#include <alibabacloud/models/GetEmptyNumberNoMoreCallsInfoResponseBody.hpp>
#include <alibabacloud/models/GetEmptyNumberNoMoreCallsInfoResponse.hpp>
#include <alibabacloud/models/GetJobDataUploadParamsRequest.hpp>
#include <alibabacloud/models/GetJobDataUploadParamsResponseBody.hpp>
#include <alibabacloud/models/GetJobDataUploadParamsResponse.hpp>
#include <alibabacloud/models/GetMaxAttemptsPerDayRequest.hpp>
#include <alibabacloud/models/GetMaxAttemptsPerDayResponseBody.hpp>
#include <alibabacloud/models/GetMaxAttemptsPerDayResponse.hpp>
#include <alibabacloud/models/GetNumberDistrictInfoTemplateDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/GetNumberDistrictInfoTemplateDownloadUrlResponse.hpp>
#include <alibabacloud/models/GetRealtimeConcurrencyReportRequest.hpp>
#include <alibabacloud/models/GetRealtimeConcurrencyReportResponseBody.hpp>
#include <alibabacloud/models/GetRealtimeConcurrencyReportResponse.hpp>
#include <alibabacloud/models/GetSummaryInfoRequest.hpp>
#include <alibabacloud/models/GetSummaryInfoResponseBody.hpp>
#include <alibabacloud/models/GetSummaryInfoResponse.hpp>
#include <alibabacloud/models/GetTaskByUuidRequest.hpp>
#include <alibabacloud/models/GetTaskByUuidResponseBody.hpp>
#include <alibabacloud/models/GetTaskByUuidResponse.hpp>
#include <alibabacloud/models/GetVersionResponseBody.hpp>
#include <alibabacloud/models/GetVersionResponse.hpp>
#include <alibabacloud/models/ImportScriptRequest.hpp>
#include <alibabacloud/models/ImportScriptResponseBody.hpp>
#include <alibabacloud/models/ImportScriptResponse.hpp>
#include <alibabacloud/models/InflightTaskTimeoutRequest.hpp>
#include <alibabacloud/models/InflightTaskTimeoutResponseBody.hpp>
#include <alibabacloud/models/InflightTaskTimeoutResponse.hpp>
#include <alibabacloud/models/ListAgentProfilesRequest.hpp>
#include <alibabacloud/models/ListAgentProfilesResponseBody.hpp>
#include <alibabacloud/models/ListAgentProfilesResponse.hpp>
#include <alibabacloud/models/ListAllTenantBindNumberBindingResponseBody.hpp>
#include <alibabacloud/models/ListAllTenantBindNumberBindingResponse.hpp>
#include <alibabacloud/models/ListAnnotationMissionRequest.hpp>
#include <alibabacloud/models/ListAnnotationMissionResponseBody.hpp>
#include <alibabacloud/models/ListAnnotationMissionResponse.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionRequest.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBody.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponse.hpp>
#include <alibabacloud/models/ListApiPluginsRequest.hpp>
#include <alibabacloud/models/ListApiPluginsResponseBody.hpp>
#include <alibabacloud/models/ListApiPluginsResponse.hpp>
#include <alibabacloud/models/ListBeebotIntentRequest.hpp>
#include <alibabacloud/models/ListBeebotIntentResponseBody.hpp>
#include <alibabacloud/models/ListBeebotIntentResponse.hpp>
#include <alibabacloud/models/ListBeebotIntentLgfRequest.hpp>
#include <alibabacloud/models/ListBeebotIntentLgfResponseBody.hpp>
#include <alibabacloud/models/ListBeebotIntentLgfResponse.hpp>
#include <alibabacloud/models/ListBeebotIntentUserSayRequest.hpp>
#include <alibabacloud/models/ListBeebotIntentUserSayResponseBody.hpp>
#include <alibabacloud/models/ListBeebotIntentUserSayResponse.hpp>
#include <alibabacloud/models/ListChatbotInstancesRequest.hpp>
#include <alibabacloud/models/ListChatbotInstancesResponseBody.hpp>
#include <alibabacloud/models/ListChatbotInstancesResponse.hpp>
#include <alibabacloud/models/ListDialogueFlowsRequest.hpp>
#include <alibabacloud/models/ListDialogueFlowsResponseBody.hpp>
#include <alibabacloud/models/ListDialogueFlowsResponse.hpp>
#include <alibabacloud/models/ListDownloadTasksRequest.hpp>
#include <alibabacloud/models/ListDownloadTasksResponseBody.hpp>
#include <alibabacloud/models/ListDownloadTasksResponse.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesRequest.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesResponse.hpp>
#include <alibabacloud/models/ListGlobalQuestionsRequest.hpp>
#include <alibabacloud/models/ListGlobalQuestionsResponseBody.hpp>
#include <alibabacloud/models/ListGlobalQuestionsResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListIntentionsRequest.hpp>
#include <alibabacloud/models/ListIntentionsResponseBody.hpp>
#include <alibabacloud/models/ListIntentionsResponse.hpp>
#include <alibabacloud/models/ListIntentsRequest.hpp>
#include <alibabacloud/models/ListIntentsResponseBody.hpp>
#include <alibabacloud/models/ListIntentsResponse.hpp>
#include <alibabacloud/models/ListJobGroupsRequest.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBody.hpp>
#include <alibabacloud/models/ListJobGroupsResponse.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncRequest.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponseBody.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponse.hpp>
#include <alibabacloud/models/ListJobsRequest.hpp>
#include <alibabacloud/models/ListJobsResponseBody.hpp>
#include <alibabacloud/models/ListJobsResponse.hpp>
#include <alibabacloud/models/ListJobsByGroupRequest.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBody.hpp>
#include <alibabacloud/models/ListJobsByGroupResponse.hpp>
#include <alibabacloud/models/ListOutboundCallNumbersRequest.hpp>
#include <alibabacloud/models/ListOutboundCallNumbersResponseBody.hpp>
#include <alibabacloud/models/ListOutboundCallNumbersResponse.hpp>
#include <alibabacloud/models/ListResourceTagsRequest.hpp>
#include <alibabacloud/models/ListResourceTagsResponseBody.hpp>
#include <alibabacloud/models/ListResourceTagsResponse.hpp>
#include <alibabacloud/models/ListScriptPublishHistoriesRequest.hpp>
#include <alibabacloud/models/ListScriptPublishHistoriesResponseBody.hpp>
#include <alibabacloud/models/ListScriptPublishHistoriesResponse.hpp>
#include <alibabacloud/models/ListScriptRecordingRequest.hpp>
#include <alibabacloud/models/ListScriptRecordingResponseBody.hpp>
#include <alibabacloud/models/ListScriptRecordingResponse.hpp>
#include <alibabacloud/models/ListScriptVoiceConfigsRequest.hpp>
#include <alibabacloud/models/ListScriptVoiceConfigsResponseBody.hpp>
#include <alibabacloud/models/ListScriptVoiceConfigsResponse.hpp>
#include <alibabacloud/models/ListScriptsRequest.hpp>
#include <alibabacloud/models/ListScriptsResponseBody.hpp>
#include <alibabacloud/models/ListScriptsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagsRequest.hpp>
#include <alibabacloud/models/ListTagsResponseBody.hpp>
#include <alibabacloud/models/ListTagsResponse.hpp>
#include <alibabacloud/models/ModifyAgentProfileRequest.hpp>
#include <alibabacloud/models/ModifyAgentProfileShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAgentProfileResponseBody.hpp>
#include <alibabacloud/models/ModifyAgentProfileResponse.hpp>
#include <alibabacloud/models/ModifyAnnotationMissionRequest.hpp>
#include <alibabacloud/models/ModifyAnnotationMissionResponseBody.hpp>
#include <alibabacloud/models/ModifyAnnotationMissionResponse.hpp>
#include <alibabacloud/models/ModifyBatchJobsRequest.hpp>
#include <alibabacloud/models/ModifyBatchJobsResponseBody.hpp>
#include <alibabacloud/models/ModifyBatchJobsResponse.hpp>
#include <alibabacloud/models/ModifyBeebotIntentRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentResponseBody.hpp>
#include <alibabacloud/models/ModifyBeebotIntentResponse.hpp>
#include <alibabacloud/models/ModifyBeebotIntentLgfRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentLgfShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentLgfResponseBody.hpp>
#include <alibabacloud/models/ModifyBeebotIntentLgfResponse.hpp>
#include <alibabacloud/models/ModifyBeebotIntentUserSayRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentUserSayShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBeebotIntentUserSayResponseBody.hpp>
#include <alibabacloud/models/ModifyBeebotIntentUserSayResponse.hpp>
#include <alibabacloud/models/ModifyDialogueFlowRequest.hpp>
#include <alibabacloud/models/ModifyDialogueFlowResponseBody.hpp>
#include <alibabacloud/models/ModifyDialogueFlowResponse.hpp>
#include <alibabacloud/models/ModifyEmptyNumberNoMoreCallsInfoRequest.hpp>
#include <alibabacloud/models/ModifyEmptyNumberNoMoreCallsInfoResponseBody.hpp>
#include <alibabacloud/models/ModifyEmptyNumberNoMoreCallsInfoResponse.hpp>
#include <alibabacloud/models/ModifyGlobalQuestionRequest.hpp>
#include <alibabacloud/models/ModifyGlobalQuestionResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalQuestionResponse.hpp>
#include <alibabacloud/models/ModifyInstanceRequest.hpp>
#include <alibabacloud/models/ModifyInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceResponse.hpp>
#include <alibabacloud/models/ModifyIntentRequest.hpp>
#include <alibabacloud/models/ModifyIntentResponseBody.hpp>
#include <alibabacloud/models/ModifyIntentResponse.hpp>
#include <alibabacloud/models/ModifyJobGroupRequest.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyJobGroupResponse.hpp>
#include <alibabacloud/models/ModifyOutboundCallNumberRequest.hpp>
#include <alibabacloud/models/ModifyOutboundCallNumberResponseBody.hpp>
#include <alibabacloud/models/ModifyOutboundCallNumberResponse.hpp>
#include <alibabacloud/models/ModifyScriptRequest.hpp>
#include <alibabacloud/models/ModifyScriptResponseBody.hpp>
#include <alibabacloud/models/ModifyScriptResponse.hpp>
#include <alibabacloud/models/ModifyScriptVoiceConfigRequest.hpp>
#include <alibabacloud/models/ModifyScriptVoiceConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyScriptVoiceConfigResponse.hpp>
#include <alibabacloud/models/ModifyTtsConfigRequest.hpp>
#include <alibabacloud/models/ModifyTtsConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyTtsConfigResponse.hpp>
#include <alibabacloud/models/ModifyTagGroupsRequest.hpp>
#include <alibabacloud/models/ModifyTagGroupsResponseBody.hpp>
#include <alibabacloud/models/ModifyTagGroupsResponse.hpp>
#include <alibabacloud/models/PublishScriptRequest.hpp>
#include <alibabacloud/models/PublishScriptResponseBody.hpp>
#include <alibabacloud/models/PublishScriptResponse.hpp>
#include <alibabacloud/models/PublishScriptForDebugRequest.hpp>
#include <alibabacloud/models/PublishScriptForDebugResponseBody.hpp>
#include <alibabacloud/models/PublishScriptForDebugResponse.hpp>
#include <alibabacloud/models/QueryJobsRequest.hpp>
#include <alibabacloud/models/QueryJobsResponseBody.hpp>
#include <alibabacloud/models/QueryJobsResponse.hpp>
#include <alibabacloud/models/QueryJobsWithResultRequest.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBody.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponse.hpp>
#include <alibabacloud/models/QueryScriptWaveformsRequest.hpp>
#include <alibabacloud/models/QueryScriptWaveformsResponseBody.hpp>
#include <alibabacloud/models/QueryScriptWaveformsResponse.hpp>
#include <alibabacloud/models/QueryScriptsByStatusRequest.hpp>
#include <alibabacloud/models/QueryScriptsByStatusResponseBody.hpp>
#include <alibabacloud/models/QueryScriptsByStatusResponse.hpp>
#include <alibabacloud/models/RecordFailureRequest.hpp>
#include <alibabacloud/models/RecordFailureResponseBody.hpp>
#include <alibabacloud/models/RecordFailureResponse.hpp>
#include <alibabacloud/models/ResumeJobsRequest.hpp>
#include <alibabacloud/models/ResumeJobsResponseBody.hpp>
#include <alibabacloud/models/ResumeJobsResponse.hpp>
#include <alibabacloud/models/RollbackScriptRequest.hpp>
#include <alibabacloud/models/RollbackScriptResponseBody.hpp>
#include <alibabacloud/models/RollbackScriptResponse.hpp>
#include <alibabacloud/models/SaveAfterAnswerDelayPlaybackRequest.hpp>
#include <alibabacloud/models/SaveAfterAnswerDelayPlaybackResponseBody.hpp>
#include <alibabacloud/models/SaveAfterAnswerDelayPlaybackResponse.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequest.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListResponseBody.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListResponse.hpp>
#include <alibabacloud/models/SaveAnnotationMissionTagInfoListRequest.hpp>
#include <alibabacloud/models/SaveAnnotationMissionTagInfoListResponseBody.hpp>
#include <alibabacloud/models/SaveAnnotationMissionTagInfoListResponse.hpp>
#include <alibabacloud/models/SaveBaseStrategyPeriodRequest.hpp>
#include <alibabacloud/models/SaveBaseStrategyPeriodResponseBody.hpp>
#include <alibabacloud/models/SaveBaseStrategyPeriodResponse.hpp>
#include <alibabacloud/models/SaveContactBlockListRequest.hpp>
#include <alibabacloud/models/SaveContactBlockListResponseBody.hpp>
#include <alibabacloud/models/SaveContactBlockListResponse.hpp>
#include <alibabacloud/models/SaveContactWhiteListRequest.hpp>
#include <alibabacloud/models/SaveContactWhiteListResponseBody.hpp>
#include <alibabacloud/models/SaveContactWhiteListResponse.hpp>
#include <alibabacloud/models/SaveEffectiveDaysRequest.hpp>
#include <alibabacloud/models/SaveEffectiveDaysResponseBody.hpp>
#include <alibabacloud/models/SaveEffectiveDaysResponse.hpp>
#include <alibabacloud/models/SaveMaxAttemptsPerDayRequest.hpp>
#include <alibabacloud/models/SaveMaxAttemptsPerDayResponseBody.hpp>
#include <alibabacloud/models/SaveMaxAttemptsPerDayResponse.hpp>
#include <alibabacloud/models/SearchTaskRequest.hpp>
#include <alibabacloud/models/SearchTaskResponseBody.hpp>
#include <alibabacloud/models/SearchTaskResponse.hpp>
#include <alibabacloud/models/StartJobRequest.hpp>
#include <alibabacloud/models/StartJobResponseBody.hpp>
#include <alibabacloud/models/StartJobResponse.hpp>
#include <alibabacloud/models/SubmitBatchJobsRequest.hpp>
#include <alibabacloud/models/SubmitBatchJobsResponseBody.hpp>
#include <alibabacloud/models/SubmitBatchJobsResponse.hpp>
#include <alibabacloud/models/SubmitRecordingRequest.hpp>
#include <alibabacloud/models/SubmitRecordingResponseBody.hpp>
#include <alibabacloud/models/SubmitRecordingResponse.hpp>
#include <alibabacloud/models/SubmitScriptReviewRequest.hpp>
#include <alibabacloud/models/SubmitScriptReviewResponseBody.hpp>
#include <alibabacloud/models/SubmitScriptReviewResponse.hpp>
#include <alibabacloud/models/SuspendCallRequest.hpp>
#include <alibabacloud/models/SuspendCallResponseBody.hpp>
#include <alibabacloud/models/SuspendCallResponse.hpp>
#include <alibabacloud/models/SuspendCallWithFileRequest.hpp>
#include <alibabacloud/models/SuspendCallWithFileResponseBody.hpp>
#include <alibabacloud/models/SuspendCallWithFileResponse.hpp>
#include <alibabacloud/models/SuspendJobsRequest.hpp>
#include <alibabacloud/models/SuspendJobsResponseBody.hpp>
#include <alibabacloud/models/SuspendJobsResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TaskPreparingRequest.hpp>
#include <alibabacloud/models/TaskPreparingResponseBody.hpp>
#include <alibabacloud/models/TaskPreparingResponse.hpp>
#include <alibabacloud/models/TerminateCallRequest.hpp>
#include <alibabacloud/models/TerminateCallResponseBody.hpp>
#include <alibabacloud/models/TerminateCallResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UploadScriptRecordingRequest.hpp>
#include <alibabacloud/models/UploadScriptRecordingResponseBody.hpp>
#include <alibabacloud/models/UploadScriptRecordingResponse.hpp>
#include <alibabacloud/models/WithdrawScriptReviewRequest.hpp>
#include <alibabacloud/models/WithdrawScriptReviewResponseBody.hpp>
#include <alibabacloud/models/WithdrawScriptReviewResponse.hpp>
#include <alibabacloud/models/CreateAgentProfileResponseBodyData.hpp>
#include <alibabacloud/models/CreateAnnotationMissionResponseBodyData.hpp>
#include <alibabacloud/models/CreateBatchJobsResponseBodyBatchJobStrategyWorkingTime.hpp>
#include <alibabacloud/models/CreateBatchJobsResponseBodyBatchJobStrategy.hpp>
#include <alibabacloud/models/CreateBatchJobsResponseBodyBatchJob.hpp>
#include <alibabacloud/models/CreateBatchRepeatJobResponseBodyJobGroup.hpp>
#include <alibabacloud/models/CreateBeebotIntentRequestIntentDefinition.hpp>
#include <alibabacloud/models/CreateBeebotIntentLgfRequestLgfDefinition.hpp>
#include <alibabacloud/models/CreateBeebotIntentUserSayRequestUserSayDefinition.hpp>
#include <alibabacloud/models/CreateInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/CreateInstanceBindNumberResponseBodyDataList.hpp>
#include <alibabacloud/models/CreateInstanceBindNumberResponseBodyData.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBodyJobGroupExportProgress.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBodyJobGroupRecallStrategy.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBodyJobGroupStrategyWorkingTime.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBodyJobGroupStrategy.hpp>
#include <alibabacloud/models/CreateJobGroupResponseBodyJobGroup.hpp>
#include <alibabacloud/models/CreateScriptResponseBodyScript.hpp>
#include <alibabacloud/models/DescribeBeebotIntentResponseBodyIntent.hpp>
#include <alibabacloud/models/DescribeDialogueNodeStatisticsResponseBodyHangUpDialogueNodes.hpp>
#include <alibabacloud/models/DescribeDialogueNodeStatisticsResponseBodyNoAnswerDialogueNodes.hpp>
#include <alibabacloud/models/DescribeGlobalQuestionResponseBodyGlobalQuestion.hpp>
#include <alibabacloud/models/DescribeGroupExecutingInfoResponseBodyExecutingInfoJobsProgress.hpp>
#include <alibabacloud/models/DescribeGroupExecutingInfoResponseBodyExecutingInfo.hpp>
#include <alibabacloud/models/DescribeInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/DescribeIntentResponseBodyIntent.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsResponseBodyGlobalIntents.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsResponseBodyIntentsAfterNoAnswer.hpp>
#include <alibabacloud/models/DescribeIntentStatisticsResponseBodyProcessIntents.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobContacts.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobExtras.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobScript.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobSummary.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobTasksContact.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobTasksConversationSummary.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobTasksConversation.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJobTasks.hpp>
#include <alibabacloud/models/DescribeJobResponseBodyJob.hpp>
#include <alibabacloud/models/DescribeJobDataParsingTaskProgressResponseBodyProgress.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupExportProgress.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupFlashSmsExtras.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupProgressBriefs.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupProgressCategories.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupProgress.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupRecallStrategy.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupResult.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupStrategyWorkingTime.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroupStrategy.hpp>
#include <alibabacloud/models/DescribeJobGroupResponseBodyJobGroup.hpp>
#include <alibabacloud/models/DescribeScriptResponseBodyScriptNluProfile.hpp>
#include <alibabacloud/models/DescribeScriptResponseBodyScript.hpp>
#include <alibabacloud/models/DescribeScriptVoiceConfigResponseBodyScriptVoiceConfig.hpp>
#include <alibabacloud/models/DescribeTtsConfigResponseBodyTtsConfig.hpp>
#include <alibabacloud/models/DescribeTagHitsSummaryResponseBodyTagGroups.hpp>
#include <alibabacloud/models/DescribeTagHitsSummaryResponseBodyTagHitsList.hpp>
#include <alibabacloud/models/DescribeTenantBindNumberResponseBodyDataList.hpp>
#include <alibabacloud/models/DescribeTenantBindNumberResponseBodyData.hpp>
#include <alibabacloud/models/DialogueResponseBodyFeedback.hpp>
#include <alibabacloud/models/DownloadRecordingResponseBodyDownloadParams.hpp>
#include <alibabacloud/models/DownloadScriptRecordingResponseBodyDownloadParams.hpp>
#include <alibabacloud/models/ExportScriptResponseBodyDownloadParams.hpp>
#include <alibabacloud/models/GenerateUploadUrlResponseBodyData.hpp>
#include <alibabacloud/models/GetAgentProfileResponseBodyData.hpp>
#include <alibabacloud/models/GetAgentProfileTemplateResponseBodyData.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBodyDataAsrSummaryInfo.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBodyDataIntentSummaryInfo.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBodyDataTagSummaryInfoTagSummaryInfoDetailList.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBodyDataTagSummaryInfo.hpp>
#include <alibabacloud/models/GetAnnotationMissionSummaryResponseBodyData.hpp>
#include <alibabacloud/models/GetAnnotationMissionTagInfoListResponseBodyDataAnnotationMissionTagInfoList.hpp>
#include <alibabacloud/models/GetAnnotationMissionTagInfoListResponseBodyData.hpp>
#include <alibabacloud/models/GetBaseStrategyPeriodResponseBodyWorkingTime.hpp>
#include <alibabacloud/models/GetContactBlockListResponseBodyContactBlocklistListList.hpp>
#include <alibabacloud/models/GetContactBlockListResponseBodyContactBlocklistList.hpp>
#include <alibabacloud/models/GetContactWhiteListResponseBodyContactWhitelistListList.hpp>
#include <alibabacloud/models/GetContactWhiteListResponseBodyContactWhitelistList.hpp>
#include <alibabacloud/models/GetJobDataUploadParamsResponseBodyUploadParams.hpp>
#include <alibabacloud/models/GetRealtimeConcurrencyReportResponseBodyReportsList.hpp>
#include <alibabacloud/models/GetRealtimeConcurrencyReportResponseBodyReports.hpp>
#include <alibabacloud/models/GetSummaryInfoResponseBodyAgentBotInstanceSummaryList.hpp>
#include <alibabacloud/models/GetTaskByUuidResponseBodyTaskConversations.hpp>
#include <alibabacloud/models/GetTaskByUuidResponseBodyTask.hpp>
#include <alibabacloud/models/ListAgentProfilesResponseBodyData.hpp>
#include <alibabacloud/models/ListAllTenantBindNumberBindingResponseBodyDataList.hpp>
#include <alibabacloud/models/ListAllTenantBindNumberBindingResponseBodyData.hpp>
#include <alibabacloud/models/ListAnnotationMissionResponseBodyDataAnnotationMissionList.hpp>
#include <alibabacloud/models/ListAnnotationMissionResponseBodyData.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatCustomizationDataInfoList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatIntentUserSayInfoList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatTagInfoList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatVocabularyInfoList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionListAnnotationMissionChatList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyDataAnnotationMissionSessionList.hpp>
#include <alibabacloud/models/ListAnnotationMissionSessionResponseBodyData.hpp>
#include <alibabacloud/models/ListApiPluginsResponseBodyApiPlugins.hpp>
#include <alibabacloud/models/ListBeebotIntentResponseBodyIntents.hpp>
#include <alibabacloud/models/ListBeebotIntentLgfResponseBodyLgfs.hpp>
#include <alibabacloud/models/ListBeebotIntentUserSayResponseBodyUserSays.hpp>
#include <alibabacloud/models/ListChatbotInstancesResponseBodyBots.hpp>
#include <alibabacloud/models/ListDialogueFlowsResponseBodyDialogueFlows.hpp>
#include <alibabacloud/models/ListDownloadTasksResponseBodyDownloadTasksListDownloadTaskFiles.hpp>
#include <alibabacloud/models/ListDownloadTasksResponseBodyDownloadTasksList.hpp>
#include <alibabacloud/models/ListDownloadTasksResponseBodyDownloadTasks.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesResponseBodyData.hpp>
#include <alibabacloud/models/ListGlobalQuestionsResponseBodyGlobalQuestionsList.hpp>
#include <alibabacloud/models/ListGlobalQuestionsResponseBodyGlobalQuestions.hpp>
#include <alibabacloud/models/ListInstancesRequestTag.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstancesResourceTags.hpp>
#include <alibabacloud/models/ListInstancesResponseBodyInstances.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListRuleCheck.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListSlotFeedbackFunctionsSwitch.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListSlotFeedbackFunctions.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListSlotTags.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListSlot.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListUserSayUserSayData.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentListUserSay.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyDataIntentList.hpp>
#include <alibabacloud/models/ListIntentionsResponseBodyData.hpp>
#include <alibabacloud/models/ListIntentsResponseBodyIntentsList.hpp>
#include <alibabacloud/models/ListIntentsResponseBodyIntents.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBodyJobGroupsListExportProgress.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBodyJobGroupsListProgress.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBodyJobGroupsListStrategy.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBodyJobGroupsList.hpp>
#include <alibabacloud/models/ListJobGroupsResponseBodyJobGroups.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponseBodyJobGroupsExportProgress.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponseBodyJobGroupsProgress.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponseBodyJobGroupsStrategy.hpp>
#include <alibabacloud/models/ListJobGroupsAsyncResponseBodyJobGroups.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsContacts.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsExtras.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsSummary.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsTasksContact.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsTasksConversationSummary.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsTasksConversation.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobsTasks.hpp>
#include <alibabacloud/models/ListJobsResponseBodyJobs.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBodyJobsListContacts.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBodyJobsListExtras.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBodyJobsListSummary.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBodyJobsList.hpp>
#include <alibabacloud/models/ListJobsByGroupResponseBodyJobs.hpp>
#include <alibabacloud/models/ListOutboundCallNumbersResponseBodyOutboundCallNumbersList.hpp>
#include <alibabacloud/models/ListOutboundCallNumbersResponseBodyOutboundCallNumbers.hpp>
#include <alibabacloud/models/ListResourceTagsResponseBodyResourceTagsList.hpp>
#include <alibabacloud/models/ListResourceTagsResponseBodyResourceTags.hpp>
#include <alibabacloud/models/ListScriptPublishHistoriesResponseBodyScriptPublishHistoriesList.hpp>
#include <alibabacloud/models/ListScriptPublishHistoriesResponseBodyScriptPublishHistories.hpp>
#include <alibabacloud/models/ListScriptRecordingResponseBodyScriptRecordings.hpp>
#include <alibabacloud/models/ListScriptVoiceConfigsResponseBodyScriptVoiceConfigsList.hpp>
#include <alibabacloud/models/ListScriptVoiceConfigsResponseBodyScriptVoiceConfigs.hpp>
#include <alibabacloud/models/ListScriptsResponseBodyScriptsListNluProfile.hpp>
#include <alibabacloud/models/ListScriptsResponseBodyScriptsList.hpp>
#include <alibabacloud/models/ListScriptsResponseBodyScripts.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListTagsResponseBodyTagGroups.hpp>
#include <alibabacloud/models/ListTagsResponseBodyTags.hpp>
#include <alibabacloud/models/ModifyAgentProfileResponseBodyData.hpp>
#include <alibabacloud/models/ModifyAnnotationMissionResponseBodyData.hpp>
#include <alibabacloud/models/ModifyBatchJobsResponseBodyJobGroupStrategyWorkingTime.hpp>
#include <alibabacloud/models/ModifyBatchJobsResponseBodyJobGroupStrategy.hpp>
#include <alibabacloud/models/ModifyBatchJobsResponseBodyJobGroup.hpp>
#include <alibabacloud/models/ModifyBeebotIntentRequestIntentDefinition.hpp>
#include <alibabacloud/models/ModifyBeebotIntentLgfRequestLgfDefinition.hpp>
#include <alibabacloud/models/ModifyBeebotIntentUserSayRequestUserSayDefinition.hpp>
#include <alibabacloud/models/ModifyInstanceResponseBodyInstance.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBodyJobGroupExportProgress.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBodyJobGroupRecallStrategy.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBodyJobGroupStrategyWorkingTime.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBodyJobGroupStrategy.hpp>
#include <alibabacloud/models/ModifyJobGroupResponseBodyJobGroup.hpp>
#include <alibabacloud/models/ModifyOutboundCallNumberResponseBodyOutboundCallNumber.hpp>
#include <alibabacloud/models/ModifyScriptResponseBodyScript.hpp>
#include <alibabacloud/models/ModifyScriptVoiceConfigResponseBodyScriptVoiceConfig.hpp>
#include <alibabacloud/models/ModifyTtsConfigResponseBodyTtsConfig.hpp>
#include <alibabacloud/models/ModifyTagGroupsResponseBodyTagGroups.hpp>
#include <alibabacloud/models/ModifyTagGroupsResponseBodyTags.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListContacts.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListExtras.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListSummary.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListTagHits.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListTasksContact.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsListTasks.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobsList.hpp>
#include <alibabacloud/models/QueryJobsResponseBodyJobs.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsListLatestTaskContact.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsListLatestTaskDialExceptionCodes.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsListLatestTaskExtras.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsListLatestTaskTagHits.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsListLatestTask.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobsList.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyJobs.hpp>
#include <alibabacloud/models/QueryJobsWithResultResponseBodyLabels.hpp>
#include <alibabacloud/models/QueryScriptWaveformsResponseBodyScriptWaveforms.hpp>
#include <alibabacloud/models/QueryScriptsByStatusResponseBodyScriptsList.hpp>
#include <alibabacloud/models/QueryScriptsByStatusResponseBodyScripts.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatCustomizationDataInfoList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatIntentUserSayInfoList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatTagInfoList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionListAnnotationMissionChatListAnnotationMissionChatVocabularyInfoList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionListAnnotationMissionChatList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListRequestAnnotationMissionSessionList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListResponseBodyDataSaveAnnotationMissionSessionListRequest.hpp>
#include <alibabacloud/models/SaveAnnotationMissionSessionListResponseBodyData.hpp>
#include <alibabacloud/models/SaveAnnotationMissionTagInfoListRequestAnnotationMissionTagInfoList.hpp>
#include <alibabacloud/models/SaveAnnotationMissionTagInfoListResponseBodyData.hpp>
#include <alibabacloud/models/SearchTaskResponseBodyLabels.hpp>
#include <alibabacloud/models/SearchTaskResponseBodySearchTaskInfoListLabels.hpp>
#include <alibabacloud/models/SearchTaskResponseBodySearchTaskInfoList.hpp>
#include <alibabacloud/models/StartJobResponseBodyCallIds.hpp>
#include <alibabacloud/models/StartJobResponseBodyTaskIds.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/WithdrawScriptReviewResponseBodyScript.hpp>

#endif
