// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLOUDSSO20210515MODEL_HPP_
#define ALIBABACLOUD_CLOUDSSO20210515MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddExternalSAMLIdPCertificateRequest.hpp>
#include <alibabacloud/models/AddExternalSAMLIdPCertificateResponseBody.hpp>
#include <alibabacloud/models/AddExternalSAMLIdPCertificateResponse.hpp>
#include <alibabacloud/models/AddPermissionPolicyToAccessConfigurationRequest.hpp>
#include <alibabacloud/models/AddPermissionPolicyToAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/AddPermissionPolicyToAccessConfigurationResponse.hpp>
#include <alibabacloud/models/AddUserToGroupRequest.hpp>
#include <alibabacloud/models/AddUserToGroupResponseBody.hpp>
#include <alibabacloud/models/AddUserToGroupResponse.hpp>
#include <alibabacloud/models/ClearExternalSAMLIdentityProviderRequest.hpp>
#include <alibabacloud/models/ClearExternalSAMLIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/ClearExternalSAMLIdentityProviderResponse.hpp>
#include <alibabacloud/models/CreateAccessAssignmentRequest.hpp>
#include <alibabacloud/models/CreateAccessAssignmentResponseBody.hpp>
#include <alibabacloud/models/CreateAccessAssignmentResponse.hpp>
#include <alibabacloud/models/CreateAccessConfigurationRequest.hpp>
#include <alibabacloud/models/CreateAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/CreateAccessConfigurationResponse.hpp>
#include <alibabacloud/models/CreateDirectoryRequest.hpp>
#include <alibabacloud/models/CreateDirectoryResponseBody.hpp>
#include <alibabacloud/models/CreateDirectoryResponse.hpp>
#include <alibabacloud/models/CreateGroupRequest.hpp>
#include <alibabacloud/models/CreateGroupResponseBody.hpp>
#include <alibabacloud/models/CreateGroupResponse.hpp>
#include <alibabacloud/models/CreateSCIMServerCredentialRequest.hpp>
#include <alibabacloud/models/CreateSCIMServerCredentialResponseBody.hpp>
#include <alibabacloud/models/CreateSCIMServerCredentialResponse.hpp>
#include <alibabacloud/models/CreateUserRequest.hpp>
#include <alibabacloud/models/CreateUserResponseBody.hpp>
#include <alibabacloud/models/CreateUserResponse.hpp>
#include <alibabacloud/models/CreateUserProvisioningRequest.hpp>
#include <alibabacloud/models/CreateUserProvisioningResponseBody.hpp>
#include <alibabacloud/models/CreateUserProvisioningResponse.hpp>
#include <alibabacloud/models/DeleteAccessAssignmentRequest.hpp>
#include <alibabacloud/models/DeleteAccessAssignmentResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessAssignmentResponse.hpp>
#include <alibabacloud/models/DeleteAccessConfigurationRequest.hpp>
#include <alibabacloud/models/DeleteAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessConfigurationResponse.hpp>
#include <alibabacloud/models/DeleteDirectoryRequest.hpp>
#include <alibabacloud/models/DeleteDirectoryResponseBody.hpp>
#include <alibabacloud/models/DeleteDirectoryResponse.hpp>
#include <alibabacloud/models/DeleteGroupRequest.hpp>
#include <alibabacloud/models/DeleteGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteGroupResponse.hpp>
#include <alibabacloud/models/DeleteMFADeviceForUserRequest.hpp>
#include <alibabacloud/models/DeleteMFADeviceForUserResponseBody.hpp>
#include <alibabacloud/models/DeleteMFADeviceForUserResponse.hpp>
#include <alibabacloud/models/DeleteSCIMServerCredentialRequest.hpp>
#include <alibabacloud/models/DeleteSCIMServerCredentialResponseBody.hpp>
#include <alibabacloud/models/DeleteSCIMServerCredentialResponse.hpp>
#include <alibabacloud/models/DeleteUserRequest.hpp>
#include <alibabacloud/models/DeleteUserResponseBody.hpp>
#include <alibabacloud/models/DeleteUserResponse.hpp>
#include <alibabacloud/models/DeleteUserProvisioningRequest.hpp>
#include <alibabacloud/models/DeleteUserProvisioningResponseBody.hpp>
#include <alibabacloud/models/DeleteUserProvisioningResponse.hpp>
#include <alibabacloud/models/DeleteUserProvisioningEventRequest.hpp>
#include <alibabacloud/models/DeleteUserProvisioningEventResponseBody.hpp>
#include <alibabacloud/models/DeleteUserProvisioningEventResponse.hpp>
#include <alibabacloud/models/DeprovisionAccessConfigurationRequest.hpp>
#include <alibabacloud/models/DeprovisionAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/DeprovisionAccessConfigurationResponse.hpp>
#include <alibabacloud/models/DisableDelegateAccountRequest.hpp>
#include <alibabacloud/models/DisableDelegateAccountResponseBody.hpp>
#include <alibabacloud/models/DisableDelegateAccountResponse.hpp>
#include <alibabacloud/models/DisableServiceResponseBody.hpp>
#include <alibabacloud/models/DisableServiceResponse.hpp>
#include <alibabacloud/models/EnableDelegateAccountRequest.hpp>
#include <alibabacloud/models/EnableDelegateAccountResponseBody.hpp>
#include <alibabacloud/models/EnableDelegateAccountResponse.hpp>
#include <alibabacloud/models/EnableServiceResponseBody.hpp>
#include <alibabacloud/models/EnableServiceResponse.hpp>
#include <alibabacloud/models/GetAccessConfigurationRequest.hpp>
#include <alibabacloud/models/GetAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/GetAccessConfigurationResponse.hpp>
#include <alibabacloud/models/GetDirectoryRequest.hpp>
#include <alibabacloud/models/GetDirectoryResponseBody.hpp>
#include <alibabacloud/models/GetDirectoryResponse.hpp>
#include <alibabacloud/models/GetDirectorySAMLServiceProviderInfoRequest.hpp>
#include <alibabacloud/models/GetDirectorySAMLServiceProviderInfoResponseBody.hpp>
#include <alibabacloud/models/GetDirectorySAMLServiceProviderInfoResponse.hpp>
#include <alibabacloud/models/GetDirectoryStatisticsRequest.hpp>
#include <alibabacloud/models/GetDirectoryStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetDirectoryStatisticsResponse.hpp>
#include <alibabacloud/models/GetExternalSAMLIdentityProviderRequest.hpp>
#include <alibabacloud/models/GetExternalSAMLIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/GetExternalSAMLIdentityProviderResponse.hpp>
#include <alibabacloud/models/GetGroupRequest.hpp>
#include <alibabacloud/models/GetGroupResponseBody.hpp>
#include <alibabacloud/models/GetGroupResponse.hpp>
#include <alibabacloud/models/GetLoginPreferenceRequest.hpp>
#include <alibabacloud/models/GetLoginPreferenceResponseBody.hpp>
#include <alibabacloud/models/GetLoginPreferenceResponse.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingInfoRequest.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingInfoResponseBody.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingInfoResponse.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingsRequest.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingsResponseBody.hpp>
#include <alibabacloud/models/GetMFAAuthenticationSettingsResponse.hpp>
#include <alibabacloud/models/GetMFAAuthenticationStatusRequest.hpp>
#include <alibabacloud/models/GetMFAAuthenticationStatusResponseBody.hpp>
#include <alibabacloud/models/GetMFAAuthenticationStatusResponse.hpp>
#include <alibabacloud/models/GetPasswordPolicyRequest.hpp>
#include <alibabacloud/models/GetPasswordPolicyResponseBody.hpp>
#include <alibabacloud/models/GetPasswordPolicyResponse.hpp>
#include <alibabacloud/models/GetSCIMSynchronizationStatusRequest.hpp>
#include <alibabacloud/models/GetSCIMSynchronizationStatusResponseBody.hpp>
#include <alibabacloud/models/GetSCIMSynchronizationStatusResponse.hpp>
#include <alibabacloud/models/GetServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetServiceStatusResponse.hpp>
#include <alibabacloud/models/GetTaskRequest.hpp>
#include <alibabacloud/models/GetTaskResponseBody.hpp>
#include <alibabacloud/models/GetTaskResponse.hpp>
#include <alibabacloud/models/GetTaskStatusRequest.hpp>
#include <alibabacloud/models/GetTaskStatusResponseBody.hpp>
#include <alibabacloud/models/GetTaskStatusResponse.hpp>
#include <alibabacloud/models/GetUserRequest.hpp>
#include <alibabacloud/models/GetUserResponseBody.hpp>
#include <alibabacloud/models/GetUserResponse.hpp>
#include <alibabacloud/models/GetUserIdRequest.hpp>
#include <alibabacloud/models/GetUserIdShrinkRequest.hpp>
#include <alibabacloud/models/GetUserIdResponseBody.hpp>
#include <alibabacloud/models/GetUserIdResponse.hpp>
#include <alibabacloud/models/GetUserMFAAuthenticationSettingsRequest.hpp>
#include <alibabacloud/models/GetUserMFAAuthenticationSettingsResponseBody.hpp>
#include <alibabacloud/models/GetUserMFAAuthenticationSettingsResponse.hpp>
#include <alibabacloud/models/GetUserProvisioningRequest.hpp>
#include <alibabacloud/models/GetUserProvisioningResponseBody.hpp>
#include <alibabacloud/models/GetUserProvisioningResponse.hpp>
#include <alibabacloud/models/GetUserProvisioningConfigurationRequest.hpp>
#include <alibabacloud/models/GetUserProvisioningConfigurationResponseBody.hpp>
#include <alibabacloud/models/GetUserProvisioningConfigurationResponse.hpp>
#include <alibabacloud/models/GetUserProvisioningEventRequest.hpp>
#include <alibabacloud/models/GetUserProvisioningEventResponseBody.hpp>
#include <alibabacloud/models/GetUserProvisioningEventResponse.hpp>
#include <alibabacloud/models/GetUserProvisioningRdAccountStatisticsRequest.hpp>
#include <alibabacloud/models/GetUserProvisioningRdAccountStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetUserProvisioningRdAccountStatisticsResponse.hpp>
#include <alibabacloud/models/GetUserProvisioningStatisticsRequest.hpp>
#include <alibabacloud/models/GetUserProvisioningStatisticsResponseBody.hpp>
#include <alibabacloud/models/GetUserProvisioningStatisticsResponse.hpp>
#include <alibabacloud/models/ListAccessAssignmentsRequest.hpp>
#include <alibabacloud/models/ListAccessAssignmentsResponseBody.hpp>
#include <alibabacloud/models/ListAccessAssignmentsResponse.hpp>
#include <alibabacloud/models/ListAccessConfigurationProvisioningsRequest.hpp>
#include <alibabacloud/models/ListAccessConfigurationProvisioningsResponseBody.hpp>
#include <alibabacloud/models/ListAccessConfigurationProvisioningsResponse.hpp>
#include <alibabacloud/models/ListAccessConfigurationsRequest.hpp>
#include <alibabacloud/models/ListAccessConfigurationsResponseBody.hpp>
#include <alibabacloud/models/ListAccessConfigurationsResponse.hpp>
#include <alibabacloud/models/ListDirectoriesResponseBody.hpp>
#include <alibabacloud/models/ListDirectoriesResponse.hpp>
#include <alibabacloud/models/ListExternalSAMLIdPCertificatesRequest.hpp>
#include <alibabacloud/models/ListExternalSAMLIdPCertificatesResponseBody.hpp>
#include <alibabacloud/models/ListExternalSAMLIdPCertificatesResponse.hpp>
#include <alibabacloud/models/ListGroupMembersRequest.hpp>
#include <alibabacloud/models/ListGroupMembersResponseBody.hpp>
#include <alibabacloud/models/ListGroupMembersResponse.hpp>
#include <alibabacloud/models/ListGroupsRequest.hpp>
#include <alibabacloud/models/ListGroupsResponseBody.hpp>
#include <alibabacloud/models/ListGroupsResponse.hpp>
#include <alibabacloud/models/ListJoinedGroupsForUserRequest.hpp>
#include <alibabacloud/models/ListJoinedGroupsForUserResponseBody.hpp>
#include <alibabacloud/models/ListJoinedGroupsForUserResponse.hpp>
#include <alibabacloud/models/ListMFADevicesForUserRequest.hpp>
#include <alibabacloud/models/ListMFADevicesForUserResponseBody.hpp>
#include <alibabacloud/models/ListMFADevicesForUserResponse.hpp>
#include <alibabacloud/models/ListPermissionPoliciesInAccessConfigurationRequest.hpp>
#include <alibabacloud/models/ListPermissionPoliciesInAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/ListPermissionPoliciesInAccessConfigurationResponse.hpp>
#include <alibabacloud/models/ListSCIMServerCredentialsRequest.hpp>
#include <alibabacloud/models/ListSCIMServerCredentialsResponseBody.hpp>
#include <alibabacloud/models/ListSCIMServerCredentialsResponse.hpp>
#include <alibabacloud/models/ListTasksRequest.hpp>
#include <alibabacloud/models/ListTasksResponseBody.hpp>
#include <alibabacloud/models/ListTasksResponse.hpp>
#include <alibabacloud/models/ListUserProvisioningEventsRequest.hpp>
#include <alibabacloud/models/ListUserProvisioningEventsResponseBody.hpp>
#include <alibabacloud/models/ListUserProvisioningEventsResponse.hpp>
#include <alibabacloud/models/ListUserProvisioningsRequest.hpp>
#include <alibabacloud/models/ListUserProvisioningsResponseBody.hpp>
#include <alibabacloud/models/ListUserProvisioningsResponse.hpp>
#include <alibabacloud/models/ListUsersRequest.hpp>
#include <alibabacloud/models/ListUsersResponseBody.hpp>
#include <alibabacloud/models/ListUsersResponse.hpp>
#include <alibabacloud/models/ProvisionAccessConfigurationRequest.hpp>
#include <alibabacloud/models/ProvisionAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/ProvisionAccessConfigurationResponse.hpp>
#include <alibabacloud/models/RemoveExternalSAMLIdPCertificateRequest.hpp>
#include <alibabacloud/models/RemoveExternalSAMLIdPCertificateResponseBody.hpp>
#include <alibabacloud/models/RemoveExternalSAMLIdPCertificateResponse.hpp>
#include <alibabacloud/models/RemovePermissionPolicyFromAccessConfigurationRequest.hpp>
#include <alibabacloud/models/RemovePermissionPolicyFromAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/RemovePermissionPolicyFromAccessConfigurationResponse.hpp>
#include <alibabacloud/models/RemoveUserFromGroupRequest.hpp>
#include <alibabacloud/models/RemoveUserFromGroupResponseBody.hpp>
#include <alibabacloud/models/RemoveUserFromGroupResponse.hpp>
#include <alibabacloud/models/ResetUserPasswordRequest.hpp>
#include <alibabacloud/models/ResetUserPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetUserPasswordResponse.hpp>
#include <alibabacloud/models/RetryUserProvisioningEventRequest.hpp>
#include <alibabacloud/models/RetryUserProvisioningEventResponseBody.hpp>
#include <alibabacloud/models/RetryUserProvisioningEventResponse.hpp>
#include <alibabacloud/models/SetExternalSAMLIdentityProviderRequest.hpp>
#include <alibabacloud/models/SetExternalSAMLIdentityProviderResponseBody.hpp>
#include <alibabacloud/models/SetExternalSAMLIdentityProviderResponse.hpp>
#include <alibabacloud/models/SetLoginPreferenceRequest.hpp>
#include <alibabacloud/models/SetLoginPreferenceResponseBody.hpp>
#include <alibabacloud/models/SetLoginPreferenceResponse.hpp>
#include <alibabacloud/models/SetMFAAuthenticationStatusRequest.hpp>
#include <alibabacloud/models/SetMFAAuthenticationStatusResponseBody.hpp>
#include <alibabacloud/models/SetMFAAuthenticationStatusResponse.hpp>
#include <alibabacloud/models/SetPasswordPolicyRequest.hpp>
#include <alibabacloud/models/SetPasswordPolicyResponseBody.hpp>
#include <alibabacloud/models/SetPasswordPolicyResponse.hpp>
#include <alibabacloud/models/SetSCIMSynchronizationStatusRequest.hpp>
#include <alibabacloud/models/SetSCIMSynchronizationStatusResponseBody.hpp>
#include <alibabacloud/models/SetSCIMSynchronizationStatusResponse.hpp>
#include <alibabacloud/models/UpdateAccessConfigurationRequest.hpp>
#include <alibabacloud/models/UpdateAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/UpdateAccessConfigurationResponse.hpp>
#include <alibabacloud/models/UpdateDirectoryRequest.hpp>
#include <alibabacloud/models/UpdateDirectoryResponseBody.hpp>
#include <alibabacloud/models/UpdateDirectoryResponse.hpp>
#include <alibabacloud/models/UpdateGroupRequest.hpp>
#include <alibabacloud/models/UpdateGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateGroupResponse.hpp>
#include <alibabacloud/models/UpdateInlinePolicyForAccessConfigurationRequest.hpp>
#include <alibabacloud/models/UpdateInlinePolicyForAccessConfigurationResponseBody.hpp>
#include <alibabacloud/models/UpdateInlinePolicyForAccessConfigurationResponse.hpp>
#include <alibabacloud/models/UpdateMFAAuthenticationSettingsRequest.hpp>
#include <alibabacloud/models/UpdateMFAAuthenticationSettingsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateMFAAuthenticationSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateMFAAuthenticationSettingsResponse.hpp>
#include <alibabacloud/models/UpdateSCIMServerCredentialStatusRequest.hpp>
#include <alibabacloud/models/UpdateSCIMServerCredentialStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateSCIMServerCredentialStatusResponse.hpp>
#include <alibabacloud/models/UpdateUserRequest.hpp>
#include <alibabacloud/models/UpdateUserResponseBody.hpp>
#include <alibabacloud/models/UpdateUserResponse.hpp>
#include <alibabacloud/models/UpdateUserMFAAuthenticationSettingsRequest.hpp>
#include <alibabacloud/models/UpdateUserMFAAuthenticationSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateUserMFAAuthenticationSettingsResponse.hpp>
#include <alibabacloud/models/UpdateUserProvisioningRequest.hpp>
#include <alibabacloud/models/UpdateUserProvisioningResponseBody.hpp>
#include <alibabacloud/models/UpdateUserProvisioningResponse.hpp>
#include <alibabacloud/models/UpdateUserProvisioningConfigurationRequest.hpp>
#include <alibabacloud/models/UpdateUserProvisioningConfigurationResponseBody.hpp>
#include <alibabacloud/models/UpdateUserProvisioningConfigurationResponse.hpp>
#include <alibabacloud/models/UpdateUserStatusRequest.hpp>
#include <alibabacloud/models/UpdateUserStatusResponseBody.hpp>
#include <alibabacloud/models/UpdateUserStatusResponse.hpp>

#endif
