// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CMS20240330MODEL_HPP_
#define ALIBABACLOUD_CMS20240330MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddonMeta.hpp>
#include <alibabacloud/models/AlertEventIntegrationPolicyForModify.hpp>
#include <alibabacloud/models/AlertEventIntegrationPolicyForView.hpp>
#include <alibabacloud/models/AlertRuleAction.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricFilterDef.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricInput.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricInputFilterValue.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricInputParamValue.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricParamDef.hpp>
#include <alibabacloud/models/AlertRuleCondition.hpp>
#include <alibabacloud/models/AlertRuleDataSource.hpp>
#include <alibabacloud/models/AlertRuleLabelFilter.hpp>
#include <alibabacloud/models/AlertRuleNotification.hpp>
#include <alibabacloud/models/AlertRuleNotificationFilter.hpp>
#include <alibabacloud/models/AlertRuleQuery.hpp>
#include <alibabacloud/models/AlertRuleSend.hpp>
#include <alibabacloud/models/AlertRuleSlsQueryJoin.hpp>
#include <alibabacloud/models/AlertRuleTimeSpan.hpp>
#include <alibabacloud/models/BizTraceConfig.hpp>
#include <alibabacloud/models/DataStorageItem.hpp>
#include <alibabacloud/models/EntityDiscoverRule.hpp>
#include <alibabacloud/models/EntityGroupBase.hpp>
#include <alibabacloud/models/FilterSetting.hpp>
#include <alibabacloud/models/IncidentContactStruct.hpp>
#include <alibabacloud/models/IncidentEscalationStageStruct.hpp>
#include <alibabacloud/models/IncidentEscalationStruct.hpp>
#include <alibabacloud/models/IncidentEventStruct.hpp>
#include <alibabacloud/models/IncidentMemberStruct.hpp>
#include <alibabacloud/models/IncidentNoteStruct.hpp>
#include <alibabacloud/models/IncidentPlanCorporationStruct.hpp>
#include <alibabacloud/models/IncidentPlanFieldPath.hpp>
#include <alibabacloud/models/IncidentPlanStruct.hpp>
#include <alibabacloud/models/IncidentResourceDetail.hpp>
#include <alibabacloud/models/IncidentResourceStruct.hpp>
#include <alibabacloud/models/IncidentStruct.hpp>
#include <alibabacloud/models/IncidentTimeline.hpp>
#include <alibabacloud/models/MaintainWindowForModify.hpp>
#include <alibabacloud/models/MaintainWindowForView.hpp>
#include <alibabacloud/models/MergeContact.hpp>
#include <alibabacloud/models/MergeContactGroup.hpp>
#include <alibabacloud/models/MergeRobot.hpp>
#include <alibabacloud/models/MergeWebhook.hpp>
#include <alibabacloud/models/NotifyStrategyForModify.hpp>
#include <alibabacloud/models/NotifyStrategyForView.hpp>
#include <alibabacloud/models/PrometheusManagedInstance.hpp>
#include <alibabacloud/models/RumDnsResponse.hpp>
#include <alibabacloud/models/SubscriptionForModify.hpp>
#include <alibabacloud/models/SubscriptionForView.hpp>
#include <alibabacloud/models/TransformAction.hpp>
#include <alibabacloud/models/TransformerForModify.hpp>
#include <alibabacloud/models/TransformerForView.hpp>
#include <alibabacloud/models/CreateEntityStoreResponseBody.hpp>
#include <alibabacloud/models/CreateEntityStoreResponse.hpp>
#include <alibabacloud/models/CreatePrometheusInstanceRequest.hpp>
#include <alibabacloud/models/CreatePrometheusInstanceResponseBody.hpp>
#include <alibabacloud/models/CreatePrometheusInstanceResponse.hpp>
#include <alibabacloud/models/CreateServiceRequest.hpp>
#include <alibabacloud/models/CreateServiceResponseBody.hpp>
#include <alibabacloud/models/CreateServiceResponse.hpp>
#include <alibabacloud/models/CreateTicketRequest.hpp>
#include <alibabacloud/models/CreateTicketResponseBody.hpp>
#include <alibabacloud/models/CreateTicketResponse.hpp>
#include <alibabacloud/models/CreateUmodelRequest.hpp>
#include <alibabacloud/models/CreateUmodelResponseBody.hpp>
#include <alibabacloud/models/CreateUmodelResponse.hpp>
#include <alibabacloud/models/DeleteEntityStoreResponseBody.hpp>
#include <alibabacloud/models/DeleteEntityStoreResponse.hpp>
#include <alibabacloud/models/DeleteServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteServiceResponse.hpp>
#include <alibabacloud/models/DeleteUmodelResponseBody.hpp>
#include <alibabacloud/models/DeleteUmodelResponse.hpp>
#include <alibabacloud/models/DeleteUmodelDataRequest.hpp>
#include <alibabacloud/models/DeleteUmodelDataResponseBody.hpp>
#include <alibabacloud/models/DeleteUmodelDataResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponse.hpp>
#include <alibabacloud/models/GetEntityStoreResponseBody.hpp>
#include <alibabacloud/models/GetEntityStoreResponse.hpp>
#include <alibabacloud/models/GetEntityStoreDataHeaders.hpp>
#include <alibabacloud/models/GetEntityStoreDataRequest.hpp>
#include <alibabacloud/models/GetEntityStoreDataResponseBody.hpp>
#include <alibabacloud/models/GetEntityStoreDataResponse.hpp>
#include <alibabacloud/models/GetServiceResponseBody.hpp>
#include <alibabacloud/models/GetServiceResponse.hpp>
#include <alibabacloud/models/GetServiceObservabilityResponseBody.hpp>
#include <alibabacloud/models/GetServiceObservabilityResponse.hpp>
#include <alibabacloud/models/GetUmodelResponseBody.hpp>
#include <alibabacloud/models/GetUmodelResponse.hpp>
#include <alibabacloud/models/GetUmodelDataRequest.hpp>
#include <alibabacloud/models/GetUmodelDataResponseBody.hpp>
#include <alibabacloud/models/GetUmodelDataResponse.hpp>
#include <alibabacloud/models/GetWorkspaceResponseBody.hpp>
#include <alibabacloud/models/GetWorkspaceResponse.hpp>
#include <alibabacloud/models/ListAlertActionsRequest.hpp>
#include <alibabacloud/models/ListAlertActionsShrinkRequest.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBody.hpp>
#include <alibabacloud/models/ListAlertActionsResponse.hpp>
#include <alibabacloud/models/ListServicesRequest.hpp>
#include <alibabacloud/models/ListServicesResponseBody.hpp>
#include <alibabacloud/models/ListServicesResponse.hpp>
#include <alibabacloud/models/ListWorkspacesRequest.hpp>
#include <alibabacloud/models/ListWorkspacesShrinkRequest.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBody.hpp>
#include <alibabacloud/models/ListWorkspacesResponse.hpp>
#include <alibabacloud/models/PutWorkspaceRequest.hpp>
#include <alibabacloud/models/PutWorkspaceResponseBody.hpp>
#include <alibabacloud/models/PutWorkspaceResponse.hpp>
#include <alibabacloud/models/UpdateServiceRequest.hpp>
#include <alibabacloud/models/UpdateServiceResponseBody.hpp>
#include <alibabacloud/models/UpdateServiceResponse.hpp>
#include <alibabacloud/models/UpdateUmodelRequest.hpp>
#include <alibabacloud/models/UpdateUmodelResponseBody.hpp>
#include <alibabacloud/models/UpdateUmodelResponse.hpp>
#include <alibabacloud/models/UpsertUmodelDataRequest.hpp>
#include <alibabacloud/models/UpsertUmodelDataResponseBody.hpp>
#include <alibabacloud/models/UpsertUmodelDataResponse.hpp>
#include <alibabacloud/models/AddonMetaDashboards.hpp>
#include <alibabacloud/models/AddonMetaEnvironmentsDependencies.hpp>
#include <alibabacloud/models/AddonMetaEnvironmentsPoliciesBindEntity.hpp>
#include <alibabacloud/models/AddonMetaEnvironmentsPoliciesMetricCheckRule.hpp>
#include <alibabacloud/models/AddonMetaEnvironmentsPoliciesProtocols.hpp>
#include <alibabacloud/models/AddonMetaEnvironmentsPolicies.hpp>
#include <alibabacloud/models/AddonMetaEnvironments.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricFilterDefSupportedOpts.hpp>
#include <alibabacloud/models/AlertRuleAlertMetricParamDefValues.hpp>
#include <alibabacloud/models/AlertRuleConditionCaseList.hpp>
#include <alibabacloud/models/AlertRuleConditionCompareListValueLevelList.hpp>
#include <alibabacloud/models/AlertRuleConditionCompareList.hpp>
#include <alibabacloud/models/AlertRuleConditionCompositeEscalationEscalations.hpp>
#include <alibabacloud/models/AlertRuleConditionCompositeEscalation.hpp>
#include <alibabacloud/models/AlertRuleConditionExpressEscalation.hpp>
#include <alibabacloud/models/AlertRuleConditionSimpleEscalationEscalations.hpp>
#include <alibabacloud/models/AlertRuleConditionSimpleEscalation.hpp>
#include <alibabacloud/models/AlertRuleDataSourceDsList.hpp>
#include <alibabacloud/models/AlertRuleQueryQueriesApmFilters.hpp>
#include <alibabacloud/models/AlertRuleQueryQueries.hpp>
#include <alibabacloud/models/AlertRuleSlsQueryJoinConditions.hpp>
#include <alibabacloud/models/EntityDiscoverRuleAnnotations.hpp>
#include <alibabacloud/models/EntityDiscoverRuleFieldRules.hpp>
#include <alibabacloud/models/EntityDiscoverRuleIpMatchRule.hpp>
#include <alibabacloud/models/EntityDiscoverRuleLabels.hpp>
#include <alibabacloud/models/EntityDiscoverRuleTags.hpp>
#include <alibabacloud/models/EntityGroupBaseEntityQueries.hpp>
#include <alibabacloud/models/FilterSettingConditions.hpp>
#include <alibabacloud/models/IncidentMemberStructAcknowledge.hpp>
#include <alibabacloud/models/IncidentMemberStructContacts.hpp>
#include <alibabacloud/models/IncidentMemberStructEscalation.hpp>
#include <alibabacloud/models/IncidentMemberStructScheduleGroup.hpp>
#include <alibabacloud/models/IncidentNoteStructOperator.hpp>
#include <alibabacloud/models/MaintainWindowForModifyEffectTimeRange.hpp>
#include <alibabacloud/models/MaintainWindowForViewEffectTimeRange.hpp>
#include <alibabacloud/models/MergeRobotExtend.hpp>
#include <alibabacloud/models/NotifyStrategyForModifyCustomTemplateEntries.hpp>
#include <alibabacloud/models/NotifyStrategyForModifyGroupingSetting.hpp>
#include <alibabacloud/models/NotifyStrategyForModifyRoutesChannels.hpp>
#include <alibabacloud/models/NotifyStrategyForModifyRoutesEffectTimeRange.hpp>
#include <alibabacloud/models/NotifyStrategyForModifyRoutes.hpp>
#include <alibabacloud/models/NotifyStrategyForViewCustomTemplateEntries.hpp>
#include <alibabacloud/models/NotifyStrategyForViewGroupingSetting.hpp>
#include <alibabacloud/models/NotifyStrategyForViewRoutesChannels.hpp>
#include <alibabacloud/models/NotifyStrategyForViewRoutesEffectTimeRange.hpp>
#include <alibabacloud/models/NotifyStrategyForViewRoutes.hpp>
#include <alibabacloud/models/SubscriptionForModifyPushingSetting.hpp>
#include <alibabacloud/models/SubscriptionForViewPushingSetting.hpp>
#include <alibabacloud/models/CreatePrometheusInstanceRequestTags.hpp>
#include <alibabacloud/models/GetServiceResponseBodyService.hpp>
#include <alibabacloud/models/GetServiceObservabilityResponseBodyEntryPointInfo.hpp>
#include <alibabacloud/models/GetUmodelResponseBodyCommonSchemaRef.hpp>
#include <alibabacloud/models/GetUmodelDataResponseBodyErrors.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsEbParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsEssParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsFc3param.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsFcParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsMnsParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsPagerDutyParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsSlsParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActionsWebhookParam.hpp>
#include <alibabacloud/models/ListAlertActionsResponseBodyAlertActions.hpp>
#include <alibabacloud/models/ListServicesResponseBodyServices.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBodyWorkspaces.hpp>

#endif
