// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_APPSTREAMCENTER20210901MODEL_HPP_
#define ALIBABACLOUD_APPSTREAMCENTER20210901MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApproveOtaTaskRequest.hpp>
#include <alibabacloud/models/ApproveOtaTaskResponseBody.hpp>
#include <alibabacloud/models/ApproveOtaTaskResponse.hpp>
#include <alibabacloud/models/AuthorizeInstanceGroupRequest.hpp>
#include <alibabacloud/models/AuthorizeInstanceGroupShrinkRequest.hpp>
#include <alibabacloud/models/AuthorizeInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/AuthorizeInstanceGroupResponse.hpp>
#include <alibabacloud/models/CreateAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/CreateAppInstanceGroupShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/CreateImageByInstanceRequest.hpp>
#include <alibabacloud/models/CreateImageByInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateImageByInstanceResponse.hpp>
#include <alibabacloud/models/CreateImageFromAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/CreateImageFromAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateImageFromAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/CreateWuyingServerRequest.hpp>
#include <alibabacloud/models/CreateWuyingServerResponseBody.hpp>
#include <alibabacloud/models/CreateWuyingServerResponse.hpp>
#include <alibabacloud/models/DeleteAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/DeleteAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/DeleteAppInstancesRequest.hpp>
#include <alibabacloud/models/DeleteAppInstancesResponseBody.hpp>
#include <alibabacloud/models/DeleteAppInstancesResponse.hpp>
#include <alibabacloud/models/DeleteImageRequest.hpp>
#include <alibabacloud/models/DeleteImageResponseBody.hpp>
#include <alibabacloud/models/DeleteImageResponse.hpp>
#include <alibabacloud/models/DeleteWuyingServerRequest.hpp>
#include <alibabacloud/models/DeleteWuyingServerResponseBody.hpp>
#include <alibabacloud/models/DeleteWuyingServerResponse.hpp>
#include <alibabacloud/models/DescribeWuyingServerEipInfoRequest.hpp>
#include <alibabacloud/models/DescribeWuyingServerEipInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeWuyingServerEipInfoResponse.hpp>
#include <alibabacloud/models/GetAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/GetAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/GetAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/GetConnectionTicketRequest.hpp>
#include <alibabacloud/models/GetConnectionTicketResponseBody.hpp>
#include <alibabacloud/models/GetConnectionTicketResponse.hpp>
#include <alibabacloud/models/GetDebugAppInstanceRequest.hpp>
#include <alibabacloud/models/GetDebugAppInstanceResponseBody.hpp>
#include <alibabacloud/models/GetDebugAppInstanceResponse.hpp>
#include <alibabacloud/models/GetOtaTaskByTaskIdRequest.hpp>
#include <alibabacloud/models/GetOtaTaskByTaskIdResponseBody.hpp>
#include <alibabacloud/models/GetOtaTaskByTaskIdResponse.hpp>
#include <alibabacloud/models/GetResourcePriceRequest.hpp>
#include <alibabacloud/models/GetResourcePriceResponseBody.hpp>
#include <alibabacloud/models/GetResourcePriceResponse.hpp>
#include <alibabacloud/models/GetResourceRenewPriceRequest.hpp>
#include <alibabacloud/models/GetResourceRenewPriceResponseBody.hpp>
#include <alibabacloud/models/GetResourceRenewPriceResponse.hpp>
#include <alibabacloud/models/ListAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/ListAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/ListAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/ListAppInstancesRequest.hpp>
#include <alibabacloud/models/ListAppInstancesResponseBody.hpp>
#include <alibabacloud/models/ListAppInstancesResponse.hpp>
#include <alibabacloud/models/ListAuthorizedUserGroupsRequest.hpp>
#include <alibabacloud/models/ListAuthorizedUserGroupsResponseBody.hpp>
#include <alibabacloud/models/ListAuthorizedUserGroupsResponse.hpp>
#include <alibabacloud/models/ListBindInfoRequest.hpp>
#include <alibabacloud/models/ListBindInfoResponseBody.hpp>
#include <alibabacloud/models/ListBindInfoResponse.hpp>
#include <alibabacloud/models/ListImageRequest.hpp>
#include <alibabacloud/models/ListImageResponseBody.hpp>
#include <alibabacloud/models/ListImageResponse.hpp>
#include <alibabacloud/models/ListNodeInstanceTypeRequest.hpp>
#include <alibabacloud/models/ListNodeInstanceTypeResponseBody.hpp>
#include <alibabacloud/models/ListNodeInstanceTypeResponse.hpp>
#include <alibabacloud/models/ListNodesRequest.hpp>
#include <alibabacloud/models/ListNodesResponseBody.hpp>
#include <alibabacloud/models/ListNodesResponse.hpp>
#include <alibabacloud/models/ListOtaTaskRequest.hpp>
#include <alibabacloud/models/ListOtaTaskResponseBody.hpp>
#include <alibabacloud/models/ListOtaTaskResponse.hpp>
#include <alibabacloud/models/ListPersistentAppInstancesRequest.hpp>
#include <alibabacloud/models/ListPersistentAppInstancesResponseBody.hpp>
#include <alibabacloud/models/ListPersistentAppInstancesResponse.hpp>
#include <alibabacloud/models/ListRegionsRequest.hpp>
#include <alibabacloud/models/ListRegionsResponseBody.hpp>
#include <alibabacloud/models/ListRegionsResponse.hpp>
#include <alibabacloud/models/ListTagCloudResourcesRequest.hpp>
#include <alibabacloud/models/ListTagCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagCloudResourcesResponse.hpp>
#include <alibabacloud/models/ListTenantConfigResponseBody.hpp>
#include <alibabacloud/models/ListTenantConfigResponse.hpp>
#include <alibabacloud/models/ListWuyingServerRequest.hpp>
#include <alibabacloud/models/ListWuyingServerResponseBody.hpp>
#include <alibabacloud/models/ListWuyingServerResponse.hpp>
#include <alibabacloud/models/LogOffAllSessionsInAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/LogOffAllSessionsInAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/LogOffAllSessionsInAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/ModifyAppInstanceGroupAttributeRequest.hpp>
#include <alibabacloud/models/ModifyAppInstanceGroupAttributeShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppInstanceGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyAppInstanceGroupAttributeResponse.hpp>
#include <alibabacloud/models/ModifyAppPolicyRequest.hpp>
#include <alibabacloud/models/ModifyAppPolicyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyAppPolicyResponse.hpp>
#include <alibabacloud/models/ModifyBrowserInstanceGroupRequest.hpp>
#include <alibabacloud/models/ModifyBrowserInstanceGroupShrinkRequest.hpp>
#include <alibabacloud/models/ModifyBrowserInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyBrowserInstanceGroupResponse.hpp>
#include <alibabacloud/models/ModifyNodePoolAmountRequest.hpp>
#include <alibabacloud/models/ModifyNodePoolAmountShrinkRequest.hpp>
#include <alibabacloud/models/ModifyNodePoolAmountResponseBody.hpp>
#include <alibabacloud/models/ModifyNodePoolAmountResponse.hpp>
#include <alibabacloud/models/ModifyNodePoolAttributeRequest.hpp>
#include <alibabacloud/models/ModifyNodePoolAttributeShrinkRequest.hpp>
#include <alibabacloud/models/ModifyNodePoolAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyNodePoolAttributeResponse.hpp>
#include <alibabacloud/models/ModifyTenantConfigRequest.hpp>
#include <alibabacloud/models/ModifyTenantConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyTenantConfigResponse.hpp>
#include <alibabacloud/models/ModifyWuyingServerAttributeRequest.hpp>
#include <alibabacloud/models/ModifyWuyingServerAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyWuyingServerAttributeResponse.hpp>
#include <alibabacloud/models/PageListAppInstanceGroupUserRequest.hpp>
#include <alibabacloud/models/PageListAppInstanceGroupUserResponseBody.hpp>
#include <alibabacloud/models/PageListAppInstanceGroupUserResponse.hpp>
#include <alibabacloud/models/RenewAppInstanceGroupRequest.hpp>
#include <alibabacloud/models/RenewAppInstanceGroupShrinkRequest.hpp>
#include <alibabacloud/models/RenewAppInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/RenewAppInstanceGroupResponse.hpp>
#include <alibabacloud/models/RenewWuyingServerRequest.hpp>
#include <alibabacloud/models/RenewWuyingServerResponseBody.hpp>
#include <alibabacloud/models/RenewWuyingServerResponse.hpp>
#include <alibabacloud/models/RestartWuyingServerRequest.hpp>
#include <alibabacloud/models/RestartWuyingServerResponseBody.hpp>
#include <alibabacloud/models/RestartWuyingServerResponse.hpp>
#include <alibabacloud/models/StartTaskForDistributeImageRequest.hpp>
#include <alibabacloud/models/StartTaskForDistributeImageResponseBody.hpp>
#include <alibabacloud/models/StartTaskForDistributeImageResponse.hpp>
#include <alibabacloud/models/StartWuyingServerRequest.hpp>
#include <alibabacloud/models/StartWuyingServerResponseBody.hpp>
#include <alibabacloud/models/StartWuyingServerResponse.hpp>
#include <alibabacloud/models/StopWuyingServerRequest.hpp>
#include <alibabacloud/models/StopWuyingServerResponseBody.hpp>
#include <alibabacloud/models/StopWuyingServerResponse.hpp>
#include <alibabacloud/models/TagCloudResourcesRequest.hpp>
#include <alibabacloud/models/TagCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/TagCloudResourcesResponse.hpp>
#include <alibabacloud/models/UnbindRequest.hpp>
#include <alibabacloud/models/UnbindResponseBody.hpp>
#include <alibabacloud/models/UnbindResponse.hpp>
#include <alibabacloud/models/UntagCloudResourcesRequest.hpp>
#include <alibabacloud/models/UntagCloudResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagCloudResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAppInstanceGroupImageRequest.hpp>
#include <alibabacloud/models/UpdateAppInstanceGroupImageResponseBody.hpp>
#include <alibabacloud/models/UpdateAppInstanceGroupImageResponse.hpp>
#include <alibabacloud/models/UpdateWuyingServerImageRequest.hpp>
#include <alibabacloud/models/UpdateWuyingServerImageResponseBody.hpp>
#include <alibabacloud/models/UpdateWuyingServerImageResponse.hpp>

#endif
