// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_TAG20180828MODEL_HPP_
#define ALIBABACLOUD_TAG20180828MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AttachPolicyRequest.hpp>
#include <alibabacloud/models/AttachPolicyResponseBody.hpp>
#include <alibabacloud/models/AttachPolicyResponse.hpp>
#include <alibabacloud/models/CheckCreatedByEnabledRequest.hpp>
#include <alibabacloud/models/CheckCreatedByEnabledResponseBody.hpp>
#include <alibabacloud/models/CheckCreatedByEnabledResponse.hpp>
#include <alibabacloud/models/CloseCreatedByRequest.hpp>
#include <alibabacloud/models/CloseCreatedByResponseBody.hpp>
#include <alibabacloud/models/CloseCreatedByResponse.hpp>
#include <alibabacloud/models/CreateAssociatedResourceRulesRequest.hpp>
#include <alibabacloud/models/CreateAssociatedResourceRulesResponseBody.hpp>
#include <alibabacloud/models/CreateAssociatedResourceRulesResponse.hpp>
#include <alibabacloud/models/CreatePolicyRequest.hpp>
#include <alibabacloud/models/CreatePolicyResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyResponse.hpp>
#include <alibabacloud/models/CreateTagsRequest.hpp>
#include <alibabacloud/models/CreateTagsResponseBody.hpp>
#include <alibabacloud/models/CreateTagsResponse.hpp>
#include <alibabacloud/models/DeleteAssociatedResourceRuleRequest.hpp>
#include <alibabacloud/models/DeleteAssociatedResourceRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteAssociatedResourceRuleResponse.hpp>
#include <alibabacloud/models/DeletePolicyRequest.hpp>
#include <alibabacloud/models/DeletePolicyResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyResponse.hpp>
#include <alibabacloud/models/DeleteTagRequest.hpp>
#include <alibabacloud/models/DeleteTagResponseBody.hpp>
#include <alibabacloud/models/DeleteTagResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DetachPolicyRequest.hpp>
#include <alibabacloud/models/DetachPolicyResponseBody.hpp>
#include <alibabacloud/models/DetachPolicyResponse.hpp>
#include <alibabacloud/models/DisablePolicyTypeRequest.hpp>
#include <alibabacloud/models/DisablePolicyTypeResponseBody.hpp>
#include <alibabacloud/models/DisablePolicyTypeResponse.hpp>
#include <alibabacloud/models/EnablePolicyTypeRequest.hpp>
#include <alibabacloud/models/EnablePolicyTypeResponseBody.hpp>
#include <alibabacloud/models/EnablePolicyTypeResponse.hpp>
#include <alibabacloud/models/GenerateConfigRuleReportRequest.hpp>
#include <alibabacloud/models/GenerateConfigRuleReportResponseBody.hpp>
#include <alibabacloud/models/GenerateConfigRuleReportResponse.hpp>
#include <alibabacloud/models/GetConfigRuleReportRequest.hpp>
#include <alibabacloud/models/GetConfigRuleReportResponseBody.hpp>
#include <alibabacloud/models/GetConfigRuleReportResponse.hpp>
#include <alibabacloud/models/GetEffectivePolicyRequest.hpp>
#include <alibabacloud/models/GetEffectivePolicyResponseBody.hpp>
#include <alibabacloud/models/GetEffectivePolicyResponse.hpp>
#include <alibabacloud/models/GetPolicyRequest.hpp>
#include <alibabacloud/models/GetPolicyResponseBody.hpp>
#include <alibabacloud/models/GetPolicyResponse.hpp>
#include <alibabacloud/models/GetPolicyEnableStatusRequest.hpp>
#include <alibabacloud/models/GetPolicyEnableStatusResponseBody.hpp>
#include <alibabacloud/models/GetPolicyEnableStatusResponse.hpp>
#include <alibabacloud/models/ListAssociatedResourceRulesRequest.hpp>
#include <alibabacloud/models/ListAssociatedResourceRulesResponseBody.hpp>
#include <alibabacloud/models/ListAssociatedResourceRulesResponse.hpp>
#include <alibabacloud/models/ListConfigRulesForTargetRequest.hpp>
#include <alibabacloud/models/ListConfigRulesForTargetResponseBody.hpp>
#include <alibabacloud/models/ListConfigRulesForTargetResponse.hpp>
#include <alibabacloud/models/ListPoliciesRequest.hpp>
#include <alibabacloud/models/ListPoliciesResponseBody.hpp>
#include <alibabacloud/models/ListPoliciesResponse.hpp>
#include <alibabacloud/models/ListPoliciesForTargetRequest.hpp>
#include <alibabacloud/models/ListPoliciesForTargetResponseBody.hpp>
#include <alibabacloud/models/ListPoliciesForTargetResponse.hpp>
#include <alibabacloud/models/ListResourcesByTagRequest.hpp>
#include <alibabacloud/models/ListResourcesByTagResponseBody.hpp>
#include <alibabacloud/models/ListResourcesByTagResponse.hpp>
#include <alibabacloud/models/ListSupportResourceTypesRequest.hpp>
#include <alibabacloud/models/ListSupportResourceTypesResponseBody.hpp>
#include <alibabacloud/models/ListSupportResourceTypesResponse.hpp>
#include <alibabacloud/models/ListTagKeysRequest.hpp>
#include <alibabacloud/models/ListTagKeysResponseBody.hpp>
#include <alibabacloud/models/ListTagKeysResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagValuesRequest.hpp>
#include <alibabacloud/models/ListTagValuesResponseBody.hpp>
#include <alibabacloud/models/ListTagValuesResponse.hpp>
#include <alibabacloud/models/ListTargetsForPolicyRequest.hpp>
#include <alibabacloud/models/ListTargetsForPolicyResponseBody.hpp>
#include <alibabacloud/models/ListTargetsForPolicyResponse.hpp>
#include <alibabacloud/models/ModifyPolicyRequest.hpp>
#include <alibabacloud/models/ModifyPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyResponse.hpp>
#include <alibabacloud/models/OpenCreatedByRequest.hpp>
#include <alibabacloud/models/OpenCreatedByResponseBody.hpp>
#include <alibabacloud/models/OpenCreatedByResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateAssociatedResourceRuleRequest.hpp>
#include <alibabacloud/models/UpdateAssociatedResourceRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateAssociatedResourceRuleResponse.hpp>
#include <alibabacloud/models/CreateAssociatedResourceRulesRequestCreateRulesList.hpp>
#include <alibabacloud/models/CreateTagsRequestTagKeyValueParamListTagValueParamList.hpp>
#include <alibabacloud/models/CreateTagsRequestTagKeyValueParamList.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/GetConfigRuleReportResponseBodyData.hpp>
#include <alibabacloud/models/GetEffectivePolicyResponseBodyPolicyAttachmentsPolicyList.hpp>
#include <alibabacloud/models/GetEffectivePolicyResponseBodyPolicyAttachments.hpp>
#include <alibabacloud/models/GetPolicyResponseBodyPolicy.hpp>
#include <alibabacloud/models/GetPolicyEnableStatusResponseBodyStatusModels.hpp>
#include <alibabacloud/models/ListAssociatedResourceRulesResponseBodyRules.hpp>
#include <alibabacloud/models/ListConfigRulesForTargetResponseBodyData.hpp>
#include <alibabacloud/models/ListPoliciesResponseBodyPolicyList.hpp>
#include <alibabacloud/models/ListPoliciesForTargetResponseBodyData.hpp>
#include <alibabacloud/models/ListResourcesByTagRequestTagFilter.hpp>
#include <alibabacloud/models/ListResourcesByTagResponseBodyResourcesTags.hpp>
#include <alibabacloud/models/ListResourcesByTagResponseBodyResources.hpp>
#include <alibabacloud/models/ListSupportResourceTypesResponseBodySupportResourceTypesSupportItems.hpp>
#include <alibabacloud/models/ListSupportResourceTypesResponseBodySupportResourceTypes.hpp>
#include <alibabacloud/models/ListTagKeysRequestTagFilter.hpp>
#include <alibabacloud/models/ListTagKeysResponseBodyKeysKey.hpp>
#include <alibabacloud/models/ListTagKeysResponseBodyKeys.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTags.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListTagValuesRequestTagFilter.hpp>
#include <alibabacloud/models/ListTagValuesResponseBodyValues.hpp>
#include <alibabacloud/models/ListTargetsForPolicyResponseBodyTargets.hpp>
#include <alibabacloud/models/TagResourcesResponseBodyFailedResourcesFailedResourceResult.hpp>
#include <alibabacloud/models/TagResourcesResponseBodyFailedResourcesFailedResource.hpp>
#include <alibabacloud/models/TagResourcesResponseBodyFailedResources.hpp>
#include <alibabacloud/models/UntagResourcesResponseBodyFailedResourcesFailedResourceResult.hpp>
#include <alibabacloud/models/UntagResourcesResponseBodyFailedResourcesFailedResource.hpp>
#include <alibabacloud/models/UntagResourcesResponseBodyFailedResources.hpp>

#endif
