// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_ALIGENIESSP_1_0MODEL_HPP_
#define ALIBABACLOUD_ALIGENIESSP_1_0MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/LoginStateInfo.hpp>
#include <alibabacloud/models/ResultValue.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentHeaders.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentRequest.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentShrinkRequest.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentResponseBody.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentResponse.hpp>
#include <alibabacloud/models/AddSubHeaders.hpp>
#include <alibabacloud/models/AddSubRequest.hpp>
#include <alibabacloud/models/AddSubShrinkRequest.hpp>
#include <alibabacloud/models/AddSubResponseBody.hpp>
#include <alibabacloud/models/AddSubResponse.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoHeaders.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoRequest.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoResponseBody.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoResponse.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoGeneratedByPhoneNumberHeaders.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoGeneratedByPhoneNumberRequest.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoGeneratedByPhoneNumberResponseBody.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoGeneratedByPhoneNumberResponse.hpp>
#include <alibabacloud/models/AuthLoginWithTaobaoUserInfoHeaders.hpp>
#include <alibabacloud/models/AuthLoginWithTaobaoUserInfoRequest.hpp>
#include <alibabacloud/models/AuthLoginWithTaobaoUserInfoResponseBody.hpp>
#include <alibabacloud/models/AuthLoginWithTaobaoUserInfoResponse.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoHeaders.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoRequest.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoShrinkRequest.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoResponseBody.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoResponse.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelHeaders.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelRequest.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelShrinkRequest.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponseBody.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponse.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtHeaders.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtRequest.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtShrinkRequest.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtResponseBody.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtResponse.hpp>
#include <alibabacloud/models/CloudPlayerHeaders.hpp>
#include <alibabacloud/models/CloudPlayerRequest.hpp>
#include <alibabacloud/models/CloudPlayerShrinkRequest.hpp>
#include <alibabacloud/models/CloudPlayerResponseBody.hpp>
#include <alibabacloud/models/CloudPlayerResponse.hpp>
#include <alibabacloud/models/CreateAlarmHeaders.hpp>
#include <alibabacloud/models/CreateAlarmRequest.hpp>
#include <alibabacloud/models/CreateAlarmShrinkRequest.hpp>
#include <alibabacloud/models/CreateAlarmResponseBody.hpp>
#include <alibabacloud/models/CreateAlarmResponse.hpp>
#include <alibabacloud/models/CreatePlayingListHeaders.hpp>
#include <alibabacloud/models/CreatePlayingListRequest.hpp>
#include <alibabacloud/models/CreatePlayingListShrinkRequest.hpp>
#include <alibabacloud/models/CreatePlayingListResponseBody.hpp>
#include <alibabacloud/models/CreatePlayingListResponse.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2request.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2shrinkRequest.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2responseBody.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2response.hpp>
#include <alibabacloud/models/CreateScheduleTaskHeaders.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequest.hpp>
#include <alibabacloud/models/CreateScheduleTaskShrinkRequest.hpp>
#include <alibabacloud/models/CreateScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/CreateScheduleTaskResponse.hpp>
#include <alibabacloud/models/DeleteAlarmsHeaders.hpp>
#include <alibabacloud/models/DeleteAlarmsRequest.hpp>
#include <alibabacloud/models/DeleteAlarmsShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAlarmsResponseBody.hpp>
#include <alibabacloud/models/DeleteAlarmsResponse.hpp>
#include <alibabacloud/models/DeleteScheduleTaskHeaders.hpp>
#include <alibabacloud/models/DeleteScheduleTaskRequest.hpp>
#include <alibabacloud/models/DeleteScheduleTaskShrinkRequest.hpp>
#include <alibabacloud/models/DeleteScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteScheduleTaskResponse.hpp>
#include <alibabacloud/models/DeleteSubHeaders.hpp>
#include <alibabacloud/models/DeleteSubRequest.hpp>
#include <alibabacloud/models/DeleteSubResponseBody.hpp>
#include <alibabacloud/models/DeleteSubResponse.hpp>
#include <alibabacloud/models/DeviceControlHeaders.hpp>
#include <alibabacloud/models/DeviceControlRequest.hpp>
#include <alibabacloud/models/DeviceControlShrinkRequest.hpp>
#include <alibabacloud/models/DeviceControlResponseBody.hpp>
#include <alibabacloud/models/DeviceControlResponse.hpp>
#include <alibabacloud/models/EcologyOpennessAuthenticateHeaders.hpp>
#include <alibabacloud/models/EcologyOpennessAuthenticateRequest.hpp>
#include <alibabacloud/models/EcologyOpennessAuthenticateResponseBody.hpp>
#include <alibabacloud/models/EcologyOpennessAuthenticateResponse.hpp>
#include <alibabacloud/models/EcologyOpennessSendVerificationCodeHeaders.hpp>
#include <alibabacloud/models/EcologyOpennessSendVerificationCodeRequest.hpp>
#include <alibabacloud/models/EcologyOpennessSendVerificationCodeResponseBody.hpp>
#include <alibabacloud/models/EcologyOpennessSendVerificationCodeResponse.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberHeaders.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberRequest.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberResponseBody.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberResponse.hpp>
#include <alibabacloud/models/GetAlarmHeaders.hpp>
#include <alibabacloud/models/GetAlarmRequest.hpp>
#include <alibabacloud/models/GetAlarmShrinkRequest.hpp>
#include <alibabacloud/models/GetAlarmResponseBody.hpp>
#include <alibabacloud/models/GetAlarmResponse.hpp>
#include <alibabacloud/models/GetAlbumHeaders.hpp>
#include <alibabacloud/models/GetAlbumRequest.hpp>
#include <alibabacloud/models/GetAlbumResponseBody.hpp>
#include <alibabacloud/models/GetAlbumResponse.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdHeaders.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdRequest.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdResponseBody.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdResponse.hpp>
#include <alibabacloud/models/GetAligenieUserInfoHeaders.hpp>
#include <alibabacloud/models/GetAligenieUserInfoRequest.hpp>
#include <alibabacloud/models/GetAligenieUserInfoResponseBody.hpp>
#include <alibabacloud/models/GetAligenieUserInfoResponse.hpp>
#include <alibabacloud/models/GetCodeEnhanceHeaders.hpp>
#include <alibabacloud/models/GetCodeEnhanceRequest.hpp>
#include <alibabacloud/models/GetCodeEnhanceShrinkRequest.hpp>
#include <alibabacloud/models/GetCodeEnhanceResponseBody.hpp>
#include <alibabacloud/models/GetCodeEnhanceResponse.hpp>
#include <alibabacloud/models/GetContentHeaders.hpp>
#include <alibabacloud/models/GetContentRequest.hpp>
#include <alibabacloud/models/GetContentResponseBody.hpp>
#include <alibabacloud/models/GetContentResponse.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemHeaders.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemRequest.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemShrinkRequest.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemResponseBody.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemResponse.hpp>
#include <alibabacloud/models/GetCurrentPlayingListHeaders.hpp>
#include <alibabacloud/models/GetCurrentPlayingListRequest.hpp>
#include <alibabacloud/models/GetCurrentPlayingListShrinkRequest.hpp>
#include <alibabacloud/models/GetCurrentPlayingListResponseBody.hpp>
#include <alibabacloud/models/GetCurrentPlayingListResponse.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoHeaders.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoRequest.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoShrinkRequest.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoResponseBody.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoResponse.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityHeaders.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityRequest.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityResponseBody.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityResponse.hpp>
#include <alibabacloud/models/GetDeviceSettingHeaders.hpp>
#include <alibabacloud/models/GetDeviceSettingRequest.hpp>
#include <alibabacloud/models/GetDeviceSettingShrinkRequest.hpp>
#include <alibabacloud/models/GetDeviceSettingResponseBody.hpp>
#include <alibabacloud/models/GetDeviceSettingResponse.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailHeaders.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailRequest.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailShrinkRequest.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponseBody.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponse.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoHeaders.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoRequest.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoShrinkRequest.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoResponseBody.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoResponse.hpp>
#include <alibabacloud/models/GetDeviceTagHeaders.hpp>
#include <alibabacloud/models/GetDeviceTagRequest.hpp>
#include <alibabacloud/models/GetDeviceTagShrinkRequest.hpp>
#include <alibabacloud/models/GetDeviceTagResponseBody.hpp>
#include <alibabacloud/models/GetDeviceTagResponse.hpp>
#include <alibabacloud/models/GetJiangSuTelecomDataHeaders.hpp>
#include <alibabacloud/models/GetJiangSuTelecomDataRequest.hpp>
#include <alibabacloud/models/GetJiangSuTelecomDataResponseBody.hpp>
#include <alibabacloud/models/GetJiangSuTelecomDataResponse.hpp>
#include <alibabacloud/models/GetScheduleTaskHeaders.hpp>
#include <alibabacloud/models/GetScheduleTaskRequest.hpp>
#include <alibabacloud/models/GetScheduleTaskShrinkRequest.hpp>
#include <alibabacloud/models/GetScheduleTaskResponseBody.hpp>
#include <alibabacloud/models/GetScheduleTaskResponse.hpp>
#include <alibabacloud/models/GetUnreadMessageCountHeaders.hpp>
#include <alibabacloud/models/GetUnreadMessageCountRequest.hpp>
#include <alibabacloud/models/GetUnreadMessageCountShrinkRequest.hpp>
#include <alibabacloud/models/GetUnreadMessageCountResponseBody.hpp>
#include <alibabacloud/models/GetUnreadMessageCountResponse.hpp>
#include <alibabacloud/models/GetUserByDeviceIdHeaders.hpp>
#include <alibabacloud/models/GetUserByDeviceIdRequest.hpp>
#include <alibabacloud/models/GetUserByDeviceIdShrinkRequest.hpp>
#include <alibabacloud/models/GetUserByDeviceIdResponseBody.hpp>
#include <alibabacloud/models/GetUserByDeviceIdResponse.hpp>
#include <alibabacloud/models/GetWeatherHeaders.hpp>
#include <alibabacloud/models/GetWeatherRequest.hpp>
#include <alibabacloud/models/GetWeatherShrinkRequest.hpp>
#include <alibabacloud/models/GetWeatherResponseBody.hpp>
#include <alibabacloud/models/GetWeatherResponse.hpp>
#include <alibabacloud/models/IndexControlPlayingListHeaders.hpp>
#include <alibabacloud/models/IndexControlPlayingListRequest.hpp>
#include <alibabacloud/models/IndexControlPlayingListShrinkRequest.hpp>
#include <alibabacloud/models/IndexControlPlayingListResponseBody.hpp>
#include <alibabacloud/models/IndexControlPlayingListResponse.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateHeaders.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateRequest.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateShrinkRequest.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateResponseBody.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateResponse.hpp>
#include <alibabacloud/models/ListAlarmsHeaders.hpp>
#include <alibabacloud/models/ListAlarmsRequest.hpp>
#include <alibabacloud/models/ListAlarmsShrinkRequest.hpp>
#include <alibabacloud/models/ListAlarmsResponseBody.hpp>
#include <alibabacloud/models/ListAlarmsResponse.hpp>
#include <alibabacloud/models/ListAlbumDetailHeaders.hpp>
#include <alibabacloud/models/ListAlbumDetailRequest.hpp>
#include <alibabacloud/models/ListAlbumDetailResponseBody.hpp>
#include <alibabacloud/models/ListAlbumDetailResponse.hpp>
#include <alibabacloud/models/ListAlbumIsAddedHeaders.hpp>
#include <alibabacloud/models/ListAlbumIsAddedRequest.hpp>
#include <alibabacloud/models/ListAlbumIsAddedShrinkRequest.hpp>
#include <alibabacloud/models/ListAlbumIsAddedResponseBody.hpp>
#include <alibabacloud/models/ListAlbumIsAddedResponse.hpp>
#include <alibabacloud/models/ListCateContentHeaders.hpp>
#include <alibabacloud/models/ListCateContentRequest.hpp>
#include <alibabacloud/models/ListCateContentShrinkRequest.hpp>
#include <alibabacloud/models/ListCateContentResponseBody.hpp>
#include <alibabacloud/models/ListCateContentResponse.hpp>
#include <alibabacloud/models/ListCateInfoHeaders.hpp>
#include <alibabacloud/models/ListCateInfoRequest.hpp>
#include <alibabacloud/models/ListCateInfoResponseBody.hpp>
#include <alibabacloud/models/ListCateInfoResponse.hpp>
#include <alibabacloud/models/ListCommonCateFirstFloorHeaders.hpp>
#include <alibabacloud/models/ListCommonCateFirstFloorRequest.hpp>
#include <alibabacloud/models/ListCommonCateFirstFloorResponseBody.hpp>
#include <alibabacloud/models/ListCommonCateFirstFloorResponse.hpp>
#include <alibabacloud/models/ListCommonCateSecondFloorHeaders.hpp>
#include <alibabacloud/models/ListCommonCateSecondFloorRequest.hpp>
#include <alibabacloud/models/ListCommonCateSecondFloorResponseBody.hpp>
#include <alibabacloud/models/ListCommonCateSecondFloorResponse.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoHeaders.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoRequest.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoShrinkRequest.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoResponseBody.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoResponse.hpp>
#include <alibabacloud/models/ListDeviceByUserIdHeaders.hpp>
#include <alibabacloud/models/ListDeviceByUserIdRequest.hpp>
#include <alibabacloud/models/ListDeviceByUserIdShrinkRequest.hpp>
#include <alibabacloud/models/ListDeviceByUserIdResponseBody.hpp>
#include <alibabacloud/models/ListDeviceByUserIdResponse.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelHeaders.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelRequest.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelShrinkRequest.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelResponseBody.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelResponse.hpp>
#include <alibabacloud/models/ListDeviceIdByIdentitiesHeaders.hpp>
#include <alibabacloud/models/ListDeviceIdByIdentitiesRequest.hpp>
#include <alibabacloud/models/ListDeviceIdByIdentitiesShrinkRequest.hpp>
#include <alibabacloud/models/ListDeviceIdByIdentitiesResponseBody.hpp>
#include <alibabacloud/models/ListDeviceIdByIdentitiesResponse.hpp>
#include <alibabacloud/models/ListMusicHeaders.hpp>
#include <alibabacloud/models/ListMusicRequest.hpp>
#include <alibabacloud/models/ListMusicShrinkRequest.hpp>
#include <alibabacloud/models/ListMusicResponseBody.hpp>
#include <alibabacloud/models/ListMusicResponse.hpp>
#include <alibabacloud/models/ListPlayHistoryHeaders.hpp>
#include <alibabacloud/models/ListPlayHistoryRequest.hpp>
#include <alibabacloud/models/ListPlayHistoryShrinkRequest.hpp>
#include <alibabacloud/models/ListPlayHistoryResponseBody.hpp>
#include <alibabacloud/models/ListPlayHistoryResponse.hpp>
#include <alibabacloud/models/ListRecommendContentHeaders.hpp>
#include <alibabacloud/models/ListRecommendContentRequest.hpp>
#include <alibabacloud/models/ListRecommendContentShrinkRequest.hpp>
#include <alibabacloud/models/ListRecommendContentResponseBody.hpp>
#include <alibabacloud/models/ListRecommendContentResponse.hpp>
#include <alibabacloud/models/ListSubHeaders.hpp>
#include <alibabacloud/models/ListSubRequest.hpp>
#include <alibabacloud/models/ListSubShrinkRequest.hpp>
#include <alibabacloud/models/ListSubResponseBody.hpp>
#include <alibabacloud/models/ListSubResponse.hpp>
#include <alibabacloud/models/ListSubAlbumHeaders.hpp>
#include <alibabacloud/models/ListSubAlbumRequest.hpp>
#include <alibabacloud/models/ListSubAlbumShrinkRequest.hpp>
#include <alibabacloud/models/ListSubAlbumResponseBody.hpp>
#include <alibabacloud/models/ListSubAlbumResponse.hpp>
#include <alibabacloud/models/ListSubscriptionAlbumCategoryHeaders.hpp>
#include <alibabacloud/models/ListSubscriptionAlbumCategoryRequest.hpp>
#include <alibabacloud/models/ListSubscriptionAlbumCategoryResponseBody.hpp>
#include <alibabacloud/models/ListSubscriptionAlbumCategoryResponse.hpp>
#include <alibabacloud/models/ListUserMessageHeaders.hpp>
#include <alibabacloud/models/ListUserMessageRequest.hpp>
#include <alibabacloud/models/ListUserMessageShrinkRequest.hpp>
#include <alibabacloud/models/ListUserMessageResponseBody.hpp>
#include <alibabacloud/models/ListUserMessageResponse.hpp>
#include <alibabacloud/models/MobileRecommendHeaders.hpp>
#include <alibabacloud/models/MobileRecommendRequest.hpp>
#include <alibabacloud/models/MobileRecommendShrinkRequest.hpp>
#include <alibabacloud/models/MobileRecommendResponseBody.hpp>
#include <alibabacloud/models/MobileRecommendResponse.hpp>
#include <alibabacloud/models/PlayAndPauseControlHeaders.hpp>
#include <alibabacloud/models/PlayAndPauseControlRequest.hpp>
#include <alibabacloud/models/PlayAndPauseControlShrinkRequest.hpp>
#include <alibabacloud/models/PlayAndPauseControlResponseBody.hpp>
#include <alibabacloud/models/PlayAndPauseControlResponse.hpp>
#include <alibabacloud/models/PlayModeControlHeaders.hpp>
#include <alibabacloud/models/PlayModeControlRequest.hpp>
#include <alibabacloud/models/PlayModeControlShrinkRequest.hpp>
#include <alibabacloud/models/PlayModeControlResponseBody.hpp>
#include <alibabacloud/models/PlayModeControlResponse.hpp>
#include <alibabacloud/models/PreviousAndNextControlHeaders.hpp>
#include <alibabacloud/models/PreviousAndNextControlRequest.hpp>
#include <alibabacloud/models/PreviousAndNextControlShrinkRequest.hpp>
#include <alibabacloud/models/PreviousAndNextControlResponseBody.hpp>
#include <alibabacloud/models/PreviousAndNextControlResponse.hpp>
#include <alibabacloud/models/ProgressControlHeaders.hpp>
#include <alibabacloud/models/ProgressControlRequest.hpp>
#include <alibabacloud/models/ProgressControlShrinkRequest.hpp>
#include <alibabacloud/models/ProgressControlResponseBody.hpp>
#include <alibabacloud/models/ProgressControlResponse.hpp>
#include <alibabacloud/models/QueryMusicTypeHeaders.hpp>
#include <alibabacloud/models/QueryMusicTypeRequest.hpp>
#include <alibabacloud/models/QueryMusicTypeShrinkRequest.hpp>
#include <alibabacloud/models/QueryMusicTypeResponseBody.hpp>
#include <alibabacloud/models/QueryMusicTypeResponse.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdHeaders.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdRequest.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdResponseBody.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdResponse.hpp>
#include <alibabacloud/models/ReadMessageHeaders.hpp>
#include <alibabacloud/models/ReadMessageRequest.hpp>
#include <alibabacloud/models/ReadMessageShrinkRequest.hpp>
#include <alibabacloud/models/ReadMessageResponseBody.hpp>
#include <alibabacloud/models/ReadMessageResponse.hpp>
#include <alibabacloud/models/ScanCodeBindHeaders.hpp>
#include <alibabacloud/models/ScanCodeBindRequest.hpp>
#include <alibabacloud/models/ScanCodeBindShrinkRequest.hpp>
#include <alibabacloud/models/ScanCodeBindResponseBody.hpp>
#include <alibabacloud/models/ScanCodeBindResponse.hpp>
#include <alibabacloud/models/ScgSearchHeaders.hpp>
#include <alibabacloud/models/ScgSearchRequest.hpp>
#include <alibabacloud/models/ScgSearchShrinkRequest.hpp>
#include <alibabacloud/models/ScgSearchResponseBody.hpp>
#include <alibabacloud/models/ScgSearchResponse.hpp>
#include <alibabacloud/models/SearchContentHeaders.hpp>
#include <alibabacloud/models/SearchContentRequest.hpp>
#include <alibabacloud/models/SearchContentShrinkRequest.hpp>
#include <alibabacloud/models/SearchContentResponseBody.hpp>
#include <alibabacloud/models/SearchContentResponse.hpp>
#include <alibabacloud/models/SendMessageHeaders.hpp>
#include <alibabacloud/models/SendMessageRequest.hpp>
#include <alibabacloud/models/SendMessageShrinkRequest.hpp>
#include <alibabacloud/models/SendMessageResponseBody.hpp>
#include <alibabacloud/models/SendMessageResponse.hpp>
#include <alibabacloud/models/SetDeviceSettingHeaders.hpp>
#include <alibabacloud/models/SetDeviceSettingRequest.hpp>
#include <alibabacloud/models/SetDeviceSettingShrinkRequest.hpp>
#include <alibabacloud/models/SetDeviceSettingResponseBody.hpp>
#include <alibabacloud/models/SetDeviceSettingResponse.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushHeaders.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushRequest.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponseBody.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponse.hpp>
#include <alibabacloud/models/UnbindAligenieUserHeaders.hpp>
#include <alibabacloud/models/UnbindAligenieUserRequest.hpp>
#include <alibabacloud/models/UnbindAligenieUserResponseBody.hpp>
#include <alibabacloud/models/UnbindAligenieUserResponse.hpp>
#include <alibabacloud/models/UnbindDeviceHeaders.hpp>
#include <alibabacloud/models/UnbindDeviceRequest.hpp>
#include <alibabacloud/models/UnbindDeviceShrinkRequest.hpp>
#include <alibabacloud/models/UnbindDeviceResponseBody.hpp>
#include <alibabacloud/models/UnbindDeviceResponse.hpp>
#include <alibabacloud/models/UpdateAlarmHeaders.hpp>
#include <alibabacloud/models/UpdateAlarmRequest.hpp>
#include <alibabacloud/models/UpdateAlarmShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAlarmResponseBody.hpp>
#include <alibabacloud/models/UpdateAlarmResponse.hpp>
#include <alibabacloud/models/ResultValueDeviceUnionIds.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentRequestDeviceInfo.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentRequestOpenAddAndRemoveFavoriteContentRequestOpenSourceRawIdPair.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentRequestOpenAddAndRemoveFavoriteContentRequest.hpp>
#include <alibabacloud/models/AddAndRemoveFavoriteContentRequestUserInfo.hpp>
#include <alibabacloud/models/AddSubRequestAddSubscriptionInfoRequestScheduleInfo.hpp>
#include <alibabacloud/models/AddSubRequestAddSubscriptionInfoRequest.hpp>
#include <alibabacloud/models/AddSubRequestDeviceInfo.hpp>
#include <alibabacloud/models/AddSubRequestUserInfo.hpp>
#include <alibabacloud/models/AddSubResponseBodyResultScheduleInfo.hpp>
#include <alibabacloud/models/AddSubResponseBodyResult.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoResponseBodyResult.hpp>
#include <alibabacloud/models/AuthLoginWithAligenieUserInfoGeneratedByPhoneNumberResponseBodyResult.hpp>
#include <alibabacloud/models/AuthLoginWithTaobaoUserInfoResponseBodyResult.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoResponseBodyDataObj.hpp>
#include <alibabacloud/models/AuthLoginWithThirdUserInfoResponseBodyResult.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelRequestDeviceInfo.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelRequestUserInfo.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponseBodyResultDeviceTargetsData.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponseBodyResultDeviceTargets.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponseBodyResultStartCallResult.hpp>
#include <alibabacloud/models/CheckAndDoVoipCallForHotelResponseBodyResult.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtRequestUserInfo.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtResponseBodyResultDeviceOpenInfo.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtResponseBodyResultUserOpenInfo.hpp>
#include <alibabacloud/models/CheckAuthCodeBindForExtResponseBodyResult.hpp>
#include <alibabacloud/models/CloudPlayerRequestDeviceInfo.hpp>
#include <alibabacloud/models/CloudPlayerRequestUserInfo.hpp>
#include <alibabacloud/models/CreateAlarmRequestDeviceInfo.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayloadMusicInfo.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayloadScheduleInfoOnce.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayloadScheduleInfoStatutoryWorkingDay.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayloadScheduleInfoWeekly.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayloadScheduleInfo.hpp>
#include <alibabacloud/models/CreateAlarmRequestPayload.hpp>
#include <alibabacloud/models/CreateAlarmRequestUserInfo.hpp>
#include <alibabacloud/models/CreatePlayingListRequestDeviceInfo.hpp>
#include <alibabacloud/models/CreatePlayingListRequestOpenCreatePlayingListRequestContentList.hpp>
#include <alibabacloud/models/CreatePlayingListRequestOpenCreatePlayingListRequest.hpp>
#include <alibabacloud/models/CreatePlayingListRequestUserInfo.hpp>
#include <alibabacloud/models/CreatePlayingListResponseBodyResultCover.hpp>
#include <alibabacloud/models/CreatePlayingListResponseBodyResult.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2requestDeviceInfo.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2requestOpenCreatePlayingListRequestContentList.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2requestOpenCreatePlayingListRequest.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2responseBodyResultCover.hpp>
#include <alibabacloud/models/CreatePlayingListOauth2responseBodyResult.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestDeviceInfo.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayloadActionDtos.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayloadScheduleDtoonce.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayloadScheduleDtostatutoryWorkingDay.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayloadScheduleDtoweekly.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayloadScheduleDto.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestPayload.hpp>
#include <alibabacloud/models/CreateScheduleTaskRequestUserInfo.hpp>
#include <alibabacloud/models/DeleteAlarmsRequestDeviceInfo.hpp>
#include <alibabacloud/models/DeleteAlarmsRequestPayload.hpp>
#include <alibabacloud/models/DeleteAlarmsRequestUserInfo.hpp>
#include <alibabacloud/models/DeleteScheduleTaskRequestDeviceInfo.hpp>
#include <alibabacloud/models/DeleteScheduleTaskRequestPayload.hpp>
#include <alibabacloud/models/DeleteScheduleTaskRequestUserInfo.hpp>
#include <alibabacloud/models/DeviceControlRequestControlRequest.hpp>
#include <alibabacloud/models/DeviceControlRequestDeviceInfo.hpp>
#include <alibabacloud/models/EcologyOpennessAuthenticateResponseBodyResult.hpp>
#include <alibabacloud/models/EcologyOpennessSendVerificationCodeResponseBodyResult.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberResponseBodyDataObj.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberResponseBodyResultUserListToAuthLogin.hpp>
#include <alibabacloud/models/FindUserlistToAuthLoginWithPhoneNumberResponseBodyResult.hpp>
#include <alibabacloud/models/GetAlarmRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetAlarmRequestPayload.hpp>
#include <alibabacloud/models/GetAlarmRequestUserInfo.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResultMusicInfo.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResultScheduleInfoOnce.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResultScheduleInfoStatutoryWorkingDay.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResultScheduleInfoWeekly.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResultScheduleInfo.hpp>
#include <alibabacloud/models/GetAlarmResponseBodyResult.hpp>
#include <alibabacloud/models/GetAlbumResponseBodyResultAuthors.hpp>
#include <alibabacloud/models/GetAlbumResponseBodyResultCover.hpp>
#include <alibabacloud/models/GetAlbumResponseBodyResult.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdResponseBodyResultAlbumContentList.hpp>
#include <alibabacloud/models/GetAlbumDetailByIdResponseBodyResult.hpp>
#include <alibabacloud/models/GetAligenieUserInfoResponseBodyResult.hpp>
#include <alibabacloud/models/GetCodeEnhanceRequestChannelInfo.hpp>
#include <alibabacloud/models/GetCodeEnhanceRequestUserInfo.hpp>
#include <alibabacloud/models/GetContentResponseBodyResultAuthors.hpp>
#include <alibabacloud/models/GetContentResponseBodyResultCover.hpp>
#include <alibabacloud/models/GetContentResponseBodyResult.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemRequestUserInfo.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemResponseBodyResultCover.hpp>
#include <alibabacloud/models/GetCurrentPlayingItemResponseBodyResult.hpp>
#include <alibabacloud/models/GetCurrentPlayingListRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetCurrentPlayingListRequestOpenQueryPlayListRequest.hpp>
#include <alibabacloud/models/GetCurrentPlayingListRequestUserInfo.hpp>
#include <alibabacloud/models/GetCurrentPlayingListResponseBodyResultCover.hpp>
#include <alibabacloud/models/GetCurrentPlayingListResponseBodyResult.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetDeviceBasicInfoResponseBodyResult.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityResponseBodyResultDeviceUnionIds.hpp>
#include <alibabacloud/models/GetDeviceIdByIdentityResponseBodyResult.hpp>
#include <alibabacloud/models/GetDeviceSettingRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponseBodyResultPlayer.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponseBodyResultPower.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponseBodyResultSpeaker.hpp>
#include <alibabacloud/models/GetDeviceStatusDetailResponseBodyResult.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetDeviceStatusInfoResponseBodyResult.hpp>
#include <alibabacloud/models/GetDeviceTagRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetDeviceTagResponseBodyResult.hpp>
#include <alibabacloud/models/GetJiangSuTelecomDataResponseBodyResult.hpp>
#include <alibabacloud/models/GetScheduleTaskRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetScheduleTaskRequestPayload.hpp>
#include <alibabacloud/models/GetScheduleTaskRequestUserInfo.hpp>
#include <alibabacloud/models/GetScheduleTaskResponseBodyResultActionTopicList.hpp>
#include <alibabacloud/models/GetScheduleTaskResponseBodyResult.hpp>
#include <alibabacloud/models/GetUnreadMessageCountRequestUserInfo.hpp>
#include <alibabacloud/models/GetUserByDeviceIdRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetUserByDeviceIdResponseBodyResultUserUnionIds.hpp>
#include <alibabacloud/models/GetUserByDeviceIdResponseBodyResult.hpp>
#include <alibabacloud/models/GetWeatherRequestDeviceInfo.hpp>
#include <alibabacloud/models/GetWeatherRequestPayload.hpp>
#include <alibabacloud/models/GetWeatherRequestUserInfo.hpp>
#include <alibabacloud/models/GetWeatherResponseBodyResultCurrentMeteorologyTemperature.hpp>
#include <alibabacloud/models/GetWeatherResponseBodyResultCurrentMeteorologyWeather.hpp>
#include <alibabacloud/models/GetWeatherResponseBodyResultCurrentMeteorology.hpp>
#include <alibabacloud/models/GetWeatherResponseBodyResult.hpp>
#include <alibabacloud/models/IndexControlPlayingListRequestDeviceInfo.hpp>
#include <alibabacloud/models/IndexControlPlayingListRequestOpenIndexControlRequest.hpp>
#include <alibabacloud/models/IndexControlPlayingListRequestUserInfo.hpp>
#include <alibabacloud/models/IndexControlPlayingListResponseBodyResultCover.hpp>
#include <alibabacloud/models/IndexControlPlayingListResponseBodyResult.hpp>
#include <alibabacloud/models/InvalidateThirdPartyAppLoginStateRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListAlarmsRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListAlarmsRequestPayload.hpp>
#include <alibabacloud/models/ListAlarmsRequestUserInfo.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModelMusicInfo.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModelScheduleInfoOnce.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModelScheduleInfoStatutoryWorkingDay.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModelScheduleInfoWeekly.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModelScheduleInfo.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResultModel.hpp>
#include <alibabacloud/models/ListAlarmsResponseBodyResult.hpp>
#include <alibabacloud/models/ListAlbumDetailResponseBodyResultOpenDataItemListAuthors.hpp>
#include <alibabacloud/models/ListAlbumDetailResponseBodyResultOpenDataItemListCover.hpp>
#include <alibabacloud/models/ListAlbumDetailResponseBodyResultOpenDataItemList.hpp>
#include <alibabacloud/models/ListAlbumDetailResponseBodyResult.hpp>
#include <alibabacloud/models/ListAlbumIsAddedRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListAlbumIsAddedRequestUserInfo.hpp>
#include <alibabacloud/models/ListAlbumIsAddedResponseBodyResult.hpp>
#include <alibabacloud/models/ListCateContentRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListCateContentRequestRequest.hpp>
#include <alibabacloud/models/ListCateContentRequestUserInfo.hpp>
#include <alibabacloud/models/ListCateContentResponseBodyResultOpenDataItemListAuthorsCover.hpp>
#include <alibabacloud/models/ListCateContentResponseBodyResultOpenDataItemListAuthors.hpp>
#include <alibabacloud/models/ListCateContentResponseBodyResultOpenDataItemListCover.hpp>
#include <alibabacloud/models/ListCateContentResponseBodyResultOpenDataItemList.hpp>
#include <alibabacloud/models/ListCateContentResponseBodyResult.hpp>
#include <alibabacloud/models/ListCateInfoResponseBodyResult.hpp>
#include <alibabacloud/models/ListCommonCateFirstFloorResponseBodyResult.hpp>
#include <alibabacloud/models/ListCommonCateSecondFloorResponseBodyResult.hpp>
#include <alibabacloud/models/ListDeviceBasicInfoRequestDeviceInfos.hpp>
#include <alibabacloud/models/ListDeviceByUserIdRequestUserInfo.hpp>
#include <alibabacloud/models/ListDeviceByUserIdResponseBodyResultDeviceUnionIds.hpp>
#include <alibabacloud/models/ListDeviceByUserIdResponseBodyResult.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelRequestChannelInfo.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelRequestUserInfo.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelResponseBodyResultDeviceUnionIds.hpp>
#include <alibabacloud/models/ListDeviceByUserIdAndChanelResponseBodyResult.hpp>
#include <alibabacloud/models/ListMusicRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListMusicRequestPayload.hpp>
#include <alibabacloud/models/ListMusicRequestUserInfo.hpp>
#include <alibabacloud/models/ListMusicResponseBodyResultModel.hpp>
#include <alibabacloud/models/ListMusicResponseBodyResult.hpp>
#include <alibabacloud/models/ListPlayHistoryRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListPlayHistoryRequestRequest.hpp>
#include <alibabacloud/models/ListPlayHistoryRequestUserInfo.hpp>
#include <alibabacloud/models/ListPlayHistoryResponseBodyResultAuthorsCover.hpp>
#include <alibabacloud/models/ListPlayHistoryResponseBodyResultAuthors.hpp>
#include <alibabacloud/models/ListPlayHistoryResponseBodyResultCover.hpp>
#include <alibabacloud/models/ListPlayHistoryResponseBodyResult.hpp>
#include <alibabacloud/models/ListRecommendContentRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListRecommendContentRequestRequest.hpp>
#include <alibabacloud/models/ListRecommendContentRequestUserInfo.hpp>
#include <alibabacloud/models/ListRecommendContentResponseBodyResultAuthorsCover.hpp>
#include <alibabacloud/models/ListRecommendContentResponseBodyResultAuthors.hpp>
#include <alibabacloud/models/ListRecommendContentResponseBodyResultCover.hpp>
#include <alibabacloud/models/ListRecommendContentResponseBodyResult.hpp>
#include <alibabacloud/models/ListSubRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListSubRequestPage.hpp>
#include <alibabacloud/models/ListSubRequestUserInfo.hpp>
#include <alibabacloud/models/ListSubResponseBodyResultDataListScheduleInfo.hpp>
#include <alibabacloud/models/ListSubResponseBodyResultDataList.hpp>
#include <alibabacloud/models/ListSubResponseBodyResult.hpp>
#include <alibabacloud/models/ListSubAlbumRequestDeviceInfo.hpp>
#include <alibabacloud/models/ListSubAlbumRequestQuerySubscriptionAlbumRequestPage.hpp>
#include <alibabacloud/models/ListSubAlbumRequestQuerySubscriptionAlbumRequest.hpp>
#include <alibabacloud/models/ListSubAlbumRequestUserInfo.hpp>
#include <alibabacloud/models/ListSubAlbumResponseBodyResultDataListScheduleInfo.hpp>
#include <alibabacloud/models/ListSubAlbumResponseBodyResultDataList.hpp>
#include <alibabacloud/models/ListSubAlbumResponseBodyResult.hpp>
#include <alibabacloud/models/ListSubscriptionAlbumCategoryResponseBodyResult.hpp>
#include <alibabacloud/models/ListUserMessageRequestUserInfo.hpp>
#include <alibabacloud/models/ListUserMessageResponseBodyResult.hpp>
#include <alibabacloud/models/MobileRecommendRequestDeviceInfo.hpp>
#include <alibabacloud/models/MobileRecommendRequestUserInfo.hpp>
#include <alibabacloud/models/MobileRecommendResponseBodyResult.hpp>
#include <alibabacloud/models/PlayAndPauseControlRequestDeviceInfo.hpp>
#include <alibabacloud/models/PlayAndPauseControlRequestOpenPlayAndPauseControlParam.hpp>
#include <alibabacloud/models/PlayAndPauseControlRequestUserInfo.hpp>
#include <alibabacloud/models/PlayModeControlRequestDeviceInfo.hpp>
#include <alibabacloud/models/PlayModeControlRequestOpenPlayModeControlRequest.hpp>
#include <alibabacloud/models/PlayModeControlRequestUserInfo.hpp>
#include <alibabacloud/models/PlayModeControlResponseBodyResult.hpp>
#include <alibabacloud/models/PreviousAndNextControlRequestDeviceInfo.hpp>
#include <alibabacloud/models/PreviousAndNextControlRequestOpenControlPlayingListRequest.hpp>
#include <alibabacloud/models/PreviousAndNextControlRequestUserInfo.hpp>
#include <alibabacloud/models/PreviousAndNextControlResponseBodyResultCover.hpp>
#include <alibabacloud/models/PreviousAndNextControlResponseBodyResult.hpp>
#include <alibabacloud/models/ProgressControlRequestDeviceInfo.hpp>
#include <alibabacloud/models/ProgressControlRequestOpenProgressControlRequest.hpp>
#include <alibabacloud/models/ProgressControlRequestUserInfo.hpp>
#include <alibabacloud/models/QueryMusicTypeRequestDeviceInfo.hpp>
#include <alibabacloud/models/QueryMusicTypeRequestPayload.hpp>
#include <alibabacloud/models/QueryMusicTypeRequestUserInfo.hpp>
#include <alibabacloud/models/QueryMusicTypeResponseBodyResult.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdResponseBodyResultAligenieUserInfoListAuthorizedDeviceList.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdResponseBodyResultAligenieUserInfoList.hpp>
#include <alibabacloud/models/QueryUserDeviceListByTmeUserIdResponseBodyResult.hpp>
#include <alibabacloud/models/ReadMessageRequestUserInfo.hpp>
#include <alibabacloud/models/ScanCodeBindRequestBindReq.hpp>
#include <alibabacloud/models/ScanCodeBindRequestUserInfo.hpp>
#include <alibabacloud/models/ScanCodeBindResponseBodyResult.hpp>
#include <alibabacloud/models/ScgSearchRequestScgFilterOffSetParam.hpp>
#include <alibabacloud/models/ScgSearchRequestScgFilterPageParam.hpp>
#include <alibabacloud/models/ScgSearchRequestScgFilterSortParam.hpp>
#include <alibabacloud/models/ScgSearchRequestScgFilter.hpp>
#include <alibabacloud/models/ScgSearchResponseBodyResultCover.hpp>
#include <alibabacloud/models/ScgSearchResponseBodyResult.hpp>
#include <alibabacloud/models/SearchContentRequestDeviceInfo.hpp>
#include <alibabacloud/models/SearchContentRequestRequest.hpp>
#include <alibabacloud/models/SearchContentRequestUserInfo.hpp>
#include <alibabacloud/models/SearchContentResponseBodyResultAuthorsCover.hpp>
#include <alibabacloud/models/SearchContentResponseBodyResultAuthors.hpp>
#include <alibabacloud/models/SearchContentResponseBodyResultCover.hpp>
#include <alibabacloud/models/SearchContentResponseBodyResult.hpp>
#include <alibabacloud/models/SendMessageRequestUserInfo.hpp>
#include <alibabacloud/models/SetDeviceSettingRequestDeviceInfo.hpp>
#include <alibabacloud/models/ThirdImmediateMsgPushResponseBodyModel.hpp>
#include <alibabacloud/models/UnbindDeviceRequestDeviceInfo.hpp>
#include <alibabacloud/models/UnbindDeviceRequestUserInfo.hpp>
#include <alibabacloud/models/UpdateAlarmRequestDeviceInfo.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayloadMusicInfo.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayloadScheduleInfoOnce.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayloadScheduleInfoStatutoryWorkingDay.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayloadScheduleInfoWeekly.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayloadScheduleInfo.hpp>
#include <alibabacloud/models/UpdateAlarmRequestPayload.hpp>
#include <alibabacloud/models/UpdateAlarmRequestUserInfo.hpp>

#endif
