// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_QUANMIAOLIGHTAPP20240801MODEL_HPP_
#define ALIBABACLOUD_QUANMIAOLIGHTAPP20240801MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ModelUsage.hpp>
#include <alibabacloud/models/CancelAsyncTaskRequest.hpp>
#include <alibabacloud/models/CancelAsyncTaskResponseBody.hpp>
#include <alibabacloud/models/CancelAsyncTaskResponse.hpp>
#include <alibabacloud/models/ExportAnalysisTagDetailByTaskIdRequest.hpp>
#include <alibabacloud/models/ExportAnalysisTagDetailByTaskIdShrinkRequest.hpp>
#include <alibabacloud/models/ExportAnalysisTagDetailByTaskIdResponseBody.hpp>
#include <alibabacloud/models/ExportAnalysisTagDetailByTaskIdResponse.hpp>
#include <alibabacloud/models/GenerateBroadcastNewsRequest.hpp>
#include <alibabacloud/models/GenerateBroadcastNewsResponseBody.hpp>
#include <alibabacloud/models/GenerateBroadcastNewsResponse.hpp>
#include <alibabacloud/models/GenerateOutputFormatRequest.hpp>
#include <alibabacloud/models/GenerateOutputFormatShrinkRequest.hpp>
#include <alibabacloud/models/GenerateOutputFormatResponseBody.hpp>
#include <alibabacloud/models/GenerateOutputFormatResponse.hpp>
#include <alibabacloud/models/GetEnterpriseVocAnalysisTaskRequest.hpp>
#include <alibabacloud/models/GetEnterpriseVocAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/GetEnterpriseVocAnalysisTaskResponse.hpp>
#include <alibabacloud/models/GetEssayCorrectionTaskRequest.hpp>
#include <alibabacloud/models/GetEssayCorrectionTaskResponseBody.hpp>
#include <alibabacloud/models/GetEssayCorrectionTaskResponse.hpp>
#include <alibabacloud/models/GetFileContentRequest.hpp>
#include <alibabacloud/models/GetFileContentResponseBody.hpp>
#include <alibabacloud/models/GetFileContentResponse.hpp>
#include <alibabacloud/models/GetTagMiningAnalysisTaskRequest.hpp>
#include <alibabacloud/models/GetTagMiningAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/GetTagMiningAnalysisTaskResponse.hpp>
#include <alibabacloud/models/GetVideoAnalysisConfigResponseBody.hpp>
#include <alibabacloud/models/GetVideoAnalysisConfigResponse.hpp>
#include <alibabacloud/models/GetVideoAnalysisTaskRequest.hpp>
#include <alibabacloud/models/GetVideoAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/GetVideoAnalysisTaskResponse.hpp>
#include <alibabacloud/models/GetVideoDetectShotConfigResponseBody.hpp>
#include <alibabacloud/models/GetVideoDetectShotConfigResponse.hpp>
#include <alibabacloud/models/GetVideoDetectShotTaskRequest.hpp>
#include <alibabacloud/models/GetVideoDetectShotTaskResponseBody.hpp>
#include <alibabacloud/models/GetVideoDetectShotTaskResponse.hpp>
#include <alibabacloud/models/HotNewsRecommendRequest.hpp>
#include <alibabacloud/models/HotNewsRecommendResponseBody.hpp>
#include <alibabacloud/models/HotNewsRecommendResponse.hpp>
#include <alibabacloud/models/ListAnalysisTagDetailByTaskIdRequest.hpp>
#include <alibabacloud/models/ListAnalysisTagDetailByTaskIdResponseBody.hpp>
#include <alibabacloud/models/ListAnalysisTagDetailByTaskIdResponse.hpp>
#include <alibabacloud/models/ListHotTopicSummariesRequest.hpp>
#include <alibabacloud/models/ListHotTopicSummariesResponseBody.hpp>
#include <alibabacloud/models/ListHotTopicSummariesResponse.hpp>
#include <alibabacloud/models/RunEnterpriseVocAnalysisRequest.hpp>
#include <alibabacloud/models/RunEnterpriseVocAnalysisShrinkRequest.hpp>
#include <alibabacloud/models/RunEnterpriseVocAnalysisResponseBody.hpp>
#include <alibabacloud/models/RunEnterpriseVocAnalysisResponse.hpp>
#include <alibabacloud/models/RunEssayCorrectionRequest.hpp>
#include <alibabacloud/models/RunEssayCorrectionResponseBody.hpp>
#include <alibabacloud/models/RunEssayCorrectionResponse.hpp>
#include <alibabacloud/models/RunHotTopicChatRequest.hpp>
#include <alibabacloud/models/RunHotTopicChatShrinkRequest.hpp>
#include <alibabacloud/models/RunHotTopicChatResponseBody.hpp>
#include <alibabacloud/models/RunHotTopicChatResponse.hpp>
#include <alibabacloud/models/RunHotTopicSummaryRequest.hpp>
#include <alibabacloud/models/RunHotTopicSummaryShrinkRequest.hpp>
#include <alibabacloud/models/RunHotTopicSummaryResponseBody.hpp>
#include <alibabacloud/models/RunHotTopicSummaryResponse.hpp>
#include <alibabacloud/models/RunMarketingInformationExtractRequest.hpp>
#include <alibabacloud/models/RunMarketingInformationExtractShrinkRequest.hpp>
#include <alibabacloud/models/RunMarketingInformationExtractResponseBody.hpp>
#include <alibabacloud/models/RunMarketingInformationExtractResponse.hpp>
#include <alibabacloud/models/RunMarketingInformationWritingRequest.hpp>
#include <alibabacloud/models/RunMarketingInformationWritingResponseBody.hpp>
#include <alibabacloud/models/RunMarketingInformationWritingResponse.hpp>
#include <alibabacloud/models/RunNetworkContentAuditRequest.hpp>
#include <alibabacloud/models/RunNetworkContentAuditShrinkRequest.hpp>
#include <alibabacloud/models/RunNetworkContentAuditResponseBody.hpp>
#include <alibabacloud/models/RunNetworkContentAuditResponse.hpp>
#include <alibabacloud/models/RunOcrParseRequest.hpp>
#include <alibabacloud/models/RunOcrParseResponseBody.hpp>
#include <alibabacloud/models/RunOcrParseResponse.hpp>
#include <alibabacloud/models/RunScriptChatRequest.hpp>
#include <alibabacloud/models/RunScriptChatResponseBody.hpp>
#include <alibabacloud/models/RunScriptChatResponse.hpp>
#include <alibabacloud/models/RunScriptContinueRequest.hpp>
#include <alibabacloud/models/RunScriptContinueResponseBody.hpp>
#include <alibabacloud/models/RunScriptContinueResponse.hpp>
#include <alibabacloud/models/RunScriptPlanningRequest.hpp>
#include <alibabacloud/models/RunScriptPlanningResponseBody.hpp>
#include <alibabacloud/models/RunScriptPlanningResponse.hpp>
#include <alibabacloud/models/RunScriptRefineRequest.hpp>
#include <alibabacloud/models/RunScriptRefineResponseBody.hpp>
#include <alibabacloud/models/RunScriptRefineResponse.hpp>
#include <alibabacloud/models/RunStyleWritingRequest.hpp>
#include <alibabacloud/models/RunStyleWritingShrinkRequest.hpp>
#include <alibabacloud/models/RunStyleWritingResponseBody.hpp>
#include <alibabacloud/models/RunStyleWritingResponse.hpp>
#include <alibabacloud/models/RunTagMiningAnalysisRequest.hpp>
#include <alibabacloud/models/RunTagMiningAnalysisShrinkRequest.hpp>
#include <alibabacloud/models/RunTagMiningAnalysisResponseBody.hpp>
#include <alibabacloud/models/RunTagMiningAnalysisResponse.hpp>
#include <alibabacloud/models/RunVideoAnalysisRequest.hpp>
#include <alibabacloud/models/RunVideoAnalysisShrinkRequest.hpp>
#include <alibabacloud/models/RunVideoAnalysisResponseBody.hpp>
#include <alibabacloud/models/RunVideoAnalysisResponse.hpp>
#include <alibabacloud/models/RunVideoDetectShotRequest.hpp>
#include <alibabacloud/models/RunVideoDetectShotShrinkRequest.hpp>
#include <alibabacloud/models/RunVideoDetectShotResponseBody.hpp>
#include <alibabacloud/models/RunVideoDetectShotResponse.hpp>
#include <alibabacloud/models/SubmitEnterpriseVocAnalysisTaskRequest.hpp>
#include <alibabacloud/models/SubmitEnterpriseVocAnalysisTaskShrinkRequest.hpp>
#include <alibabacloud/models/SubmitEnterpriseVocAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitEnterpriseVocAnalysisTaskResponse.hpp>
#include <alibabacloud/models/SubmitEssayCorrectionTaskRequest.hpp>
#include <alibabacloud/models/SubmitEssayCorrectionTaskShrinkRequest.hpp>
#include <alibabacloud/models/SubmitEssayCorrectionTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitEssayCorrectionTaskResponse.hpp>
#include <alibabacloud/models/SubmitTagMiningAnalysisTaskRequest.hpp>
#include <alibabacloud/models/SubmitTagMiningAnalysisTaskShrinkRequest.hpp>
#include <alibabacloud/models/SubmitTagMiningAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitTagMiningAnalysisTaskResponse.hpp>
#include <alibabacloud/models/SubmitVideoAnalysisTaskRequest.hpp>
#include <alibabacloud/models/SubmitVideoAnalysisTaskShrinkRequest.hpp>
#include <alibabacloud/models/SubmitVideoAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitVideoAnalysisTaskResponse.hpp>
#include <alibabacloud/models/SubmitVideoDetectShotTaskRequest.hpp>
#include <alibabacloud/models/SubmitVideoDetectShotTaskShrinkRequest.hpp>
#include <alibabacloud/models/SubmitVideoDetectShotTaskResponseBody.hpp>
#include <alibabacloud/models/SubmitVideoDetectShotTaskResponse.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisConfigRequest.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisConfigResponse.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTaskRequest.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTaskResponse.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTasksRequest.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTasksShrinkRequest.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTasksResponseBody.hpp>
#include <alibabacloud/models/UpdateVideoAnalysisTasksResponse.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotConfigRequest.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotConfigResponseBody.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotConfigResponse.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotTaskRequest.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateVideoDetectShotTaskResponse.hpp>

#endif
