// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_UMENGPUSH20220225MODEL_HPP_
#define ALIBABACLOUD_UMENGPUSH20220225MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/Alert.hpp>
#include <alibabacloud/models/Body.hpp>
#include <alibabacloud/models/Message2ThirdChannel.hpp>
#include <alibabacloud/models/AndroidPayload.hpp>
#include <alibabacloud/models/AndroidShortPayload.hpp>
#include <alibabacloud/models/Aps.hpp>
#include <alibabacloud/models/ChannelProperties.hpp>
#include <alibabacloud/models/HarmonyBody.hpp>
#include <alibabacloud/models/HarmonyPayload.hpp>
#include <alibabacloud/models/IosPayload.hpp>
#include <alibabacloud/models/Policy.hpp>
#include <alibabacloud/models/CancelByMsgIdRequest.hpp>
#include <alibabacloud/models/CancelByMsgIdResponseBody.hpp>
#include <alibabacloud/models/CancelByMsgIdResponse.hpp>
#include <alibabacloud/models/QueryMsgStatRequest.hpp>
#include <alibabacloud/models/QueryMsgStatResponseBody.hpp>
#include <alibabacloud/models/QueryMsgStatResponse.hpp>
#include <alibabacloud/models/SendByAliasRequest.hpp>
#include <alibabacloud/models/SendByAliasShrinkRequest.hpp>
#include <alibabacloud/models/SendByAliasResponseBody.hpp>
#include <alibabacloud/models/SendByAliasResponse.hpp>
#include <alibabacloud/models/SendByAliasFileIdRequest.hpp>
#include <alibabacloud/models/SendByAliasFileIdShrinkRequest.hpp>
#include <alibabacloud/models/SendByAliasFileIdResponseBody.hpp>
#include <alibabacloud/models/SendByAliasFileIdResponse.hpp>
#include <alibabacloud/models/SendByAppRequest.hpp>
#include <alibabacloud/models/SendByAppShrinkRequest.hpp>
#include <alibabacloud/models/SendByAppResponseBody.hpp>
#include <alibabacloud/models/SendByAppResponse.hpp>
#include <alibabacloud/models/SendByDeviceRequest.hpp>
#include <alibabacloud/models/SendByDeviceShrinkRequest.hpp>
#include <alibabacloud/models/SendByDeviceResponseBody.hpp>
#include <alibabacloud/models/SendByDeviceResponse.hpp>
#include <alibabacloud/models/SendByDeviceFileIdRequest.hpp>
#include <alibabacloud/models/SendByDeviceFileIdShrinkRequest.hpp>
#include <alibabacloud/models/SendByDeviceFileIdResponseBody.hpp>
#include <alibabacloud/models/SendByDeviceFileIdResponse.hpp>
#include <alibabacloud/models/SendByFilterRequest.hpp>
#include <alibabacloud/models/SendByFilterShrinkRequest.hpp>
#include <alibabacloud/models/SendByFilterResponseBody.hpp>
#include <alibabacloud/models/SendByFilterResponse.hpp>
#include <alibabacloud/models/UploadDeviceRequest.hpp>
#include <alibabacloud/models/UploadDeviceResponseBody.hpp>
#include <alibabacloud/models/UploadDeviceResponse.hpp>
#include <alibabacloud/models/AndroidShortPayloadBody.hpp>
#include <alibabacloud/models/CancelByMsgIdResponseBodyData.hpp>
#include <alibabacloud/models/QueryMsgStatResponseBodyData.hpp>
#include <alibabacloud/models/SendByAliasResponseBodyData.hpp>
#include <alibabacloud/models/SendByAliasFileIdResponseBodyData.hpp>
#include <alibabacloud/models/SendByAppResponseBodyData.hpp>
#include <alibabacloud/models/SendByDeviceResponseBodyData.hpp>
#include <alibabacloud/models/SendByDeviceFileIdResponseBodyData.hpp>
#include <alibabacloud/models/SendByFilterResponseBodyData.hpp>
#include <alibabacloud/models/UploadDeviceResponseBodyData.hpp>

#endif
