// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_AGENTLOOP20260520MODEL_HPP_
#define ALIBABACLOUD_AGENTLOOP20260520MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BackfillStrategy.hpp>
#include <alibabacloud/models/Evaluator.hpp>
#include <alibabacloud/models/ModelParameters.hpp>
#include <alibabacloud/models/PromptTemplateItem.hpp>
#include <alibabacloud/models/ExperimentConfig.hpp>
#include <alibabacloud/models/ExperimentRecord.hpp>
#include <alibabacloud/models/BatchGroup.hpp>
#include <alibabacloud/models/ContinuousStrategy.hpp>
#include <alibabacloud/models/DataFilter.hpp>
#include <alibabacloud/models/ExperimentPlanData.hpp>
#include <alibabacloud/models/IndexJsonKey.hpp>
#include <alibabacloud/models/IndexKey.hpp>
#include <alibabacloud/models/RunStrategies.hpp>
#include <alibabacloud/models/AddMem0MemoriesRequest.hpp>
#include <alibabacloud/models/AddMem0MemoriesResponse.hpp>
#include <alibabacloud/models/CreateAgentSpaceRequest.hpp>
#include <alibabacloud/models/CreateAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/CreateAgentSpaceResponse.hpp>
#include <alibabacloud/models/CreateContextStoreRequest.hpp>
#include <alibabacloud/models/CreateContextStoreResponseBody.hpp>
#include <alibabacloud/models/CreateContextStoreResponse.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/CreateDatasetRequest.hpp>
#include <alibabacloud/models/CreateDatasetResponseBody.hpp>
#include <alibabacloud/models/CreateDatasetResponse.hpp>
#include <alibabacloud/models/DeleteAgentSpaceRequest.hpp>
#include <alibabacloud/models/DeleteAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/DeleteAgentSpaceResponse.hpp>
#include <alibabacloud/models/DeleteContextStoreRequest.hpp>
#include <alibabacloud/models/DeleteContextStoreResponseBody.hpp>
#include <alibabacloud/models/DeleteContextStoreResponse.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/DeleteDatasetRequest.hpp>
#include <alibabacloud/models/DeleteDatasetResponseBody.hpp>
#include <alibabacloud/models/DeleteDatasetResponse.hpp>
#include <alibabacloud/models/DeleteMem0MemoriesRequest.hpp>
#include <alibabacloud/models/DeleteMem0MemoriesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteMem0MemoriesResponse.hpp>
#include <alibabacloud/models/DeleteMem0MemoryRequest.hpp>
#include <alibabacloud/models/DeleteMem0MemoryResponse.hpp>
#include <alibabacloud/models/DeletePipelineRequest.hpp>
#include <alibabacloud/models/DeletePipelineResponseBody.hpp>
#include <alibabacloud/models/DeletePipelineResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/ExecuteQueryRequest.hpp>
#include <alibabacloud/models/ExecuteQueryResponseBody.hpp>
#include <alibabacloud/models/ExecuteQueryResponse.hpp>
#include <alibabacloud/models/GetAgentSpaceRequest.hpp>
#include <alibabacloud/models/GetAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/GetAgentSpaceResponse.hpp>
#include <alibabacloud/models/GetContextStoreRequest.hpp>
#include <alibabacloud/models/GetContextStoreResponseBody.hpp>
#include <alibabacloud/models/GetContextStoreResponse.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/GetDatasetRequest.hpp>
#include <alibabacloud/models/GetDatasetResponseBody.hpp>
#include <alibabacloud/models/GetDatasetResponse.hpp>
#include <alibabacloud/models/GetMem0MemoriesRequest.hpp>
#include <alibabacloud/models/GetMem0MemoriesResponse.hpp>
#include <alibabacloud/models/GetMem0MemoryRequest.hpp>
#include <alibabacloud/models/GetMem0MemoryResponse.hpp>
#include <alibabacloud/models/GetPipelineRequest.hpp>
#include <alibabacloud/models/GetPipelineResponseBody.hpp>
#include <alibabacloud/models/GetPipelineResponse.hpp>
#include <alibabacloud/models/ListAgentSpacesRequest.hpp>
#include <alibabacloud/models/ListAgentSpacesResponseBody.hpp>
#include <alibabacloud/models/ListAgentSpacesResponse.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysRequest.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysResponseBody.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysResponse.hpp>
#include <alibabacloud/models/ListContextStoresRequest.hpp>
#include <alibabacloud/models/ListContextStoresResponseBody.hpp>
#include <alibabacloud/models/ListContextStoresResponse.hpp>
#include <alibabacloud/models/ListDatasetsRequest.hpp>
#include <alibabacloud/models/ListDatasetsResponseBody.hpp>
#include <alibabacloud/models/ListDatasetsResponse.hpp>
#include <alibabacloud/models/ListPipelinesRequest.hpp>
#include <alibabacloud/models/ListPipelinesResponseBody.hpp>
#include <alibabacloud/models/ListPipelinesResponse.hpp>
#include <alibabacloud/models/SearchContextRequest.hpp>
#include <alibabacloud/models/SearchContextResponseBody.hpp>
#include <alibabacloud/models/SearchContextResponse.hpp>
#include <alibabacloud/models/SearchMem0MemoriesRequest.hpp>
#include <alibabacloud/models/SearchMem0MemoriesResponse.hpp>
#include <alibabacloud/models/UpdateAgentSpaceRequest.hpp>
#include <alibabacloud/models/UpdateAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/UpdateAgentSpaceResponse.hpp>
#include <alibabacloud/models/UpdateContextStoreRequest.hpp>
#include <alibabacloud/models/UpdateContextStoreResponseBody.hpp>
#include <alibabacloud/models/UpdateContextStoreResponse.hpp>
#include <alibabacloud/models/UpdateDatasetRequest.hpp>
#include <alibabacloud/models/UpdateDatasetResponseBody.hpp>
#include <alibabacloud/models/UpdateDatasetResponse.hpp>
#include <alibabacloud/models/UpdateMem0MemoryRequest.hpp>
#include <alibabacloud/models/UpdateMem0MemoryResponse.hpp>
#include <alibabacloud/models/UpdatePipelineRequest.hpp>
#include <alibabacloud/models/UpdatePipelineResponseBody.hpp>
#include <alibabacloud/models/UpdatePipelineResponse.hpp>
#include <alibabacloud/models/ValidateMem0APIKeyRequest.hpp>
#include <alibabacloud/models/ValidateMem0APIKeyResponse.hpp>

#endif
