// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_AGENTLOOP20260520MODEL_HPP_
#define ALIBABACLOUD_AGENTLOOP20260520MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BackfillStrategy.hpp>
#include <alibabacloud/models/Evaluator.hpp>
#include <alibabacloud/models/ModelParameters.hpp>
#include <alibabacloud/models/PromptTemplateItem.hpp>
#include <alibabacloud/models/ExperimentConfig.hpp>
#include <alibabacloud/models/ExperimentRecord.hpp>
#include <alibabacloud/models/BatchGroup.hpp>
#include <alibabacloud/models/ConnectorProperties.hpp>
#include <alibabacloud/models/ContinuousStrategy.hpp>
#include <alibabacloud/models/DataFilter.hpp>
#include <alibabacloud/models/ExperimentPlanData.hpp>
#include <alibabacloud/models/IndexJsonKey.hpp>
#include <alibabacloud/models/IndexKey.hpp>
#include <alibabacloud/models/OfflineExperimentConfig.hpp>
#include <alibabacloud/models/RunStrategies.hpp>
#include <alibabacloud/models/AddDatasetDataRequest.hpp>
#include <alibabacloud/models/AddDatasetDataResponseBody.hpp>
#include <alibabacloud/models/AddDatasetDataResponse.hpp>
#include <alibabacloud/models/CancelPipelineRunRequest.hpp>
#include <alibabacloud/models/CancelPipelineRunResponseBody.hpp>
#include <alibabacloud/models/CancelPipelineRunResponse.hpp>
#include <alibabacloud/models/CreateAgentSpaceRequest.hpp>
#include <alibabacloud/models/CreateAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/CreateAgentSpaceResponse.hpp>
#include <alibabacloud/models/CreateContextStoreRequest.hpp>
#include <alibabacloud/models/CreateContextStoreResponseBody.hpp>
#include <alibabacloud/models/CreateContextStoreResponse.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/CreateContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/CreateDatasetRequest.hpp>
#include <alibabacloud/models/CreateDatasetResponseBody.hpp>
#include <alibabacloud/models/CreateDatasetResponse.hpp>
#include <alibabacloud/models/CreateEvaluationTaskRequest.hpp>
#include <alibabacloud/models/CreateEvaluationTaskResponseBody.hpp>
#include <alibabacloud/models/CreateEvaluationTaskResponse.hpp>
#include <alibabacloud/models/CreateEvaluatorRequest.hpp>
#include <alibabacloud/models/CreateEvaluatorResponseBody.hpp>
#include <alibabacloud/models/CreateEvaluatorResponse.hpp>
#include <alibabacloud/models/CreateEvaluatorSkillRequest.hpp>
#include <alibabacloud/models/CreateEvaluatorSkillResponseBody.hpp>
#include <alibabacloud/models/CreateEvaluatorSkillResponse.hpp>
#include <alibabacloud/models/CreateExperimentPlanRequest.hpp>
#include <alibabacloud/models/CreateExperimentPlanResponseBody.hpp>
#include <alibabacloud/models/CreateExperimentPlanResponse.hpp>
#include <alibabacloud/models/CreateExperimentRunRequest.hpp>
#include <alibabacloud/models/CreateExperimentRunResponseBody.hpp>
#include <alibabacloud/models/CreateExperimentRunResponse.hpp>
#include <alibabacloud/models/CreatePipelineRequest.hpp>
#include <alibabacloud/models/CreatePipelineResponseBody.hpp>
#include <alibabacloud/models/CreatePipelineResponse.hpp>
#include <alibabacloud/models/DeleteAgentSpaceRequest.hpp>
#include <alibabacloud/models/DeleteAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/DeleteAgentSpaceResponse.hpp>
#include <alibabacloud/models/DeleteContextStoreRequest.hpp>
#include <alibabacloud/models/DeleteContextStoreResponseBody.hpp>
#include <alibabacloud/models/DeleteContextStoreResponse.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/DeleteDatasetRequest.hpp>
#include <alibabacloud/models/DeleteDatasetResponseBody.hpp>
#include <alibabacloud/models/DeleteDatasetResponse.hpp>
#include <alibabacloud/models/DeleteEvaluationRunRequest.hpp>
#include <alibabacloud/models/DeleteEvaluationRunResponseBody.hpp>
#include <alibabacloud/models/DeleteEvaluationRunResponse.hpp>
#include <alibabacloud/models/DeleteEvaluationTaskRequest.hpp>
#include <alibabacloud/models/DeleteEvaluationTaskResponseBody.hpp>
#include <alibabacloud/models/DeleteEvaluationTaskResponse.hpp>
#include <alibabacloud/models/DeleteEvaluatorRequest.hpp>
#include <alibabacloud/models/DeleteEvaluatorResponseBody.hpp>
#include <alibabacloud/models/DeleteEvaluatorResponse.hpp>
#include <alibabacloud/models/DeleteEvaluatorSkillRequest.hpp>
#include <alibabacloud/models/DeleteEvaluatorSkillResponseBody.hpp>
#include <alibabacloud/models/DeleteEvaluatorSkillResponse.hpp>
#include <alibabacloud/models/DeleteExperimentPlanRequest.hpp>
#include <alibabacloud/models/DeleteExperimentPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteExperimentPlanResponse.hpp>
#include <alibabacloud/models/DeleteExperimentRunRequest.hpp>
#include <alibabacloud/models/DeleteExperimentRunResponseBody.hpp>
#include <alibabacloud/models/DeleteExperimentRunResponse.hpp>
#include <alibabacloud/models/DeletePipelineRequest.hpp>
#include <alibabacloud/models/DeletePipelineResponseBody.hpp>
#include <alibabacloud/models/DeletePipelineResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/ExecuteQueryRequest.hpp>
#include <alibabacloud/models/ExecuteQueryResponseBody.hpp>
#include <alibabacloud/models/ExecuteQueryResponse.hpp>
#include <alibabacloud/models/GetAgentSpaceRequest.hpp>
#include <alibabacloud/models/GetAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/GetAgentSpaceResponse.hpp>
#include <alibabacloud/models/GetContextStoreRequest.hpp>
#include <alibabacloud/models/GetContextStoreResponseBody.hpp>
#include <alibabacloud/models/GetContextStoreResponse.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyRequest.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyResponseBody.hpp>
#include <alibabacloud/models/GetContextStoreAPIKeyResponse.hpp>
#include <alibabacloud/models/GetDatasetRequest.hpp>
#include <alibabacloud/models/GetDatasetResponseBody.hpp>
#include <alibabacloud/models/GetDatasetResponse.hpp>
#include <alibabacloud/models/GetEvaluationRunRequest.hpp>
#include <alibabacloud/models/GetEvaluationRunResponseBody.hpp>
#include <alibabacloud/models/GetEvaluationRunResponse.hpp>
#include <alibabacloud/models/GetEvaluationTaskRequest.hpp>
#include <alibabacloud/models/GetEvaluationTaskResponseBody.hpp>
#include <alibabacloud/models/GetEvaluationTaskResponse.hpp>
#include <alibabacloud/models/GetEvaluatorRequest.hpp>
#include <alibabacloud/models/GetEvaluatorResponseBody.hpp>
#include <alibabacloud/models/GetEvaluatorResponse.hpp>
#include <alibabacloud/models/GetEvaluatorSkillRequest.hpp>
#include <alibabacloud/models/GetEvaluatorSkillResponseBody.hpp>
#include <alibabacloud/models/GetEvaluatorSkillResponse.hpp>
#include <alibabacloud/models/GetExperimentPlanRequest.hpp>
#include <alibabacloud/models/GetExperimentPlanResponseBody.hpp>
#include <alibabacloud/models/GetExperimentPlanResponse.hpp>
#include <alibabacloud/models/GetExperimentRunRequest.hpp>
#include <alibabacloud/models/GetExperimentRunResponseBody.hpp>
#include <alibabacloud/models/GetExperimentRunResponse.hpp>
#include <alibabacloud/models/GetPipelineRequest.hpp>
#include <alibabacloud/models/GetPipelineResponseBody.hpp>
#include <alibabacloud/models/GetPipelineResponse.hpp>
#include <alibabacloud/models/GetPipelineRunRequest.hpp>
#include <alibabacloud/models/GetPipelineRunResponseBody.hpp>
#include <alibabacloud/models/GetPipelineRunResponse.hpp>
#include <alibabacloud/models/GetPipelineStatsRequest.hpp>
#include <alibabacloud/models/GetPipelineStatsResponseBody.hpp>
#include <alibabacloud/models/GetPipelineStatsResponse.hpp>
#include <alibabacloud/models/ListAgentSpacesRequest.hpp>
#include <alibabacloud/models/ListAgentSpacesResponseBody.hpp>
#include <alibabacloud/models/ListAgentSpacesResponse.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysRequest.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysResponseBody.hpp>
#include <alibabacloud/models/ListContextStoreAPIKeysResponse.hpp>
#include <alibabacloud/models/ListContextStoresRequest.hpp>
#include <alibabacloud/models/ListContextStoresResponseBody.hpp>
#include <alibabacloud/models/ListContextStoresResponse.hpp>
#include <alibabacloud/models/ListDatasetsRequest.hpp>
#include <alibabacloud/models/ListDatasetsResponseBody.hpp>
#include <alibabacloud/models/ListDatasetsResponse.hpp>
#include <alibabacloud/models/ListEvaluationRunsRequest.hpp>
#include <alibabacloud/models/ListEvaluationRunsResponseBody.hpp>
#include <alibabacloud/models/ListEvaluationRunsResponse.hpp>
#include <alibabacloud/models/ListEvaluationTasksRequest.hpp>
#include <alibabacloud/models/ListEvaluationTasksResponseBody.hpp>
#include <alibabacloud/models/ListEvaluationTasksResponse.hpp>
#include <alibabacloud/models/ListEvaluatorSkillsRequest.hpp>
#include <alibabacloud/models/ListEvaluatorSkillsResponseBody.hpp>
#include <alibabacloud/models/ListEvaluatorSkillsResponse.hpp>
#include <alibabacloud/models/ListEvaluatorsRequest.hpp>
#include <alibabacloud/models/ListEvaluatorsResponseBody.hpp>
#include <alibabacloud/models/ListEvaluatorsResponse.hpp>
#include <alibabacloud/models/ListExperimentPlansRequest.hpp>
#include <alibabacloud/models/ListExperimentPlansResponseBody.hpp>
#include <alibabacloud/models/ListExperimentPlansResponse.hpp>
#include <alibabacloud/models/ListExperimentRunsRequest.hpp>
#include <alibabacloud/models/ListExperimentRunsResponseBody.hpp>
#include <alibabacloud/models/ListExperimentRunsResponse.hpp>
#include <alibabacloud/models/ListPipelineRunsRequest.hpp>
#include <alibabacloud/models/ListPipelineRunsResponseBody.hpp>
#include <alibabacloud/models/ListPipelineRunsResponse.hpp>
#include <alibabacloud/models/ListPipelinesRequest.hpp>
#include <alibabacloud/models/ListPipelinesResponseBody.hpp>
#include <alibabacloud/models/ListPipelinesResponse.hpp>
#include <alibabacloud/models/PausePipelineRequest.hpp>
#include <alibabacloud/models/PausePipelineResponseBody.hpp>
#include <alibabacloud/models/PausePipelineResponse.hpp>
#include <alibabacloud/models/PreviewPipelineRequest.hpp>
#include <alibabacloud/models/PreviewPipelineResponseBody.hpp>
#include <alibabacloud/models/PreviewPipelineResponse.hpp>
#include <alibabacloud/models/ResumePipelineRequest.hpp>
#include <alibabacloud/models/ResumePipelineResponseBody.hpp>
#include <alibabacloud/models/ResumePipelineResponse.hpp>
#include <alibabacloud/models/RunPipelineRequest.hpp>
#include <alibabacloud/models/RunPipelineResponseBody.hpp>
#include <alibabacloud/models/RunPipelineResponse.hpp>
#include <alibabacloud/models/SearchContextRequest.hpp>
#include <alibabacloud/models/SearchContextResponseBody.hpp>
#include <alibabacloud/models/SearchContextResponse.hpp>
#include <alibabacloud/models/TerminatePipelineRequest.hpp>
#include <alibabacloud/models/TerminatePipelineResponseBody.hpp>
#include <alibabacloud/models/TerminatePipelineResponse.hpp>
#include <alibabacloud/models/UpdateAgentSpaceRequest.hpp>
#include <alibabacloud/models/UpdateAgentSpaceResponseBody.hpp>
#include <alibabacloud/models/UpdateAgentSpaceResponse.hpp>
#include <alibabacloud/models/UpdateContextStoreRequest.hpp>
#include <alibabacloud/models/UpdateContextStoreResponseBody.hpp>
#include <alibabacloud/models/UpdateContextStoreResponse.hpp>
#include <alibabacloud/models/UpdateDatasetRequest.hpp>
#include <alibabacloud/models/UpdateDatasetResponseBody.hpp>
#include <alibabacloud/models/UpdateDatasetResponse.hpp>
#include <alibabacloud/models/UpdateEvaluationRunRequest.hpp>
#include <alibabacloud/models/UpdateEvaluationRunResponseBody.hpp>
#include <alibabacloud/models/UpdateEvaluationRunResponse.hpp>
#include <alibabacloud/models/UpdateEvaluationTaskRequest.hpp>
#include <alibabacloud/models/UpdateEvaluationTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateEvaluationTaskResponse.hpp>
#include <alibabacloud/models/UpdateEvaluatorRequest.hpp>
#include <alibabacloud/models/UpdateEvaluatorResponseBody.hpp>
#include <alibabacloud/models/UpdateEvaluatorResponse.hpp>
#include <alibabacloud/models/UpdateEvaluatorSkillRequest.hpp>
#include <alibabacloud/models/UpdateEvaluatorSkillResponseBody.hpp>
#include <alibabacloud/models/UpdateEvaluatorSkillResponse.hpp>
#include <alibabacloud/models/UpdateExperimentPlanRequest.hpp>
#include <alibabacloud/models/UpdateExperimentPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateExperimentPlanResponse.hpp>
#include <alibabacloud/models/UpdateExperimentRunRequest.hpp>
#include <alibabacloud/models/UpdateExperimentRunResponseBody.hpp>
#include <alibabacloud/models/UpdateExperimentRunResponse.hpp>
#include <alibabacloud/models/UpdatePipelineRequest.hpp>
#include <alibabacloud/models/UpdatePipelineResponseBody.hpp>
#include <alibabacloud/models/UpdatePipelineResponse.hpp>

#endif
