// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLOUDAPI20160714MODEL_HPP_
#define ALIBABACLOUD_CLOUDAPI20160714MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AbolishApiRequest.hpp>
#include <alibabacloud/models/AbolishApiResponseBody.hpp>
#include <alibabacloud/models/AbolishApiResponse.hpp>
#include <alibabacloud/models/AddAccessControlListEntryRequest.hpp>
#include <alibabacloud/models/AddAccessControlListEntryResponseBody.hpp>
#include <alibabacloud/models/AddAccessControlListEntryResponse.hpp>
#include <alibabacloud/models/AddIpControlPolicyItemRequest.hpp>
#include <alibabacloud/models/AddIpControlPolicyItemResponseBody.hpp>
#include <alibabacloud/models/AddIpControlPolicyItemResponse.hpp>
#include <alibabacloud/models/AddTrafficSpecialControlRequest.hpp>
#include <alibabacloud/models/AddTrafficSpecialControlResponseBody.hpp>
#include <alibabacloud/models/AddTrafficSpecialControlResponse.hpp>
#include <alibabacloud/models/AssociateInstanceWithPrivateDnsRequest.hpp>
#include <alibabacloud/models/AssociateInstanceWithPrivateDnsShrinkRequest.hpp>
#include <alibabacloud/models/AssociateInstanceWithPrivateDnsResponseBody.hpp>
#include <alibabacloud/models/AssociateInstanceWithPrivateDnsResponse.hpp>
#include <alibabacloud/models/AttachApiProductRequest.hpp>
#include <alibabacloud/models/AttachApiProductResponseBody.hpp>
#include <alibabacloud/models/AttachApiProductResponse.hpp>
#include <alibabacloud/models/AttachGroupPluginRequest.hpp>
#include <alibabacloud/models/AttachGroupPluginResponseBody.hpp>
#include <alibabacloud/models/AttachGroupPluginResponse.hpp>
#include <alibabacloud/models/AttachPluginRequest.hpp>
#include <alibabacloud/models/AttachPluginResponseBody.hpp>
#include <alibabacloud/models/AttachPluginResponse.hpp>
#include <alibabacloud/models/BatchAbolishApisRequest.hpp>
#include <alibabacloud/models/BatchAbolishApisResponseBody.hpp>
#include <alibabacloud/models/BatchAbolishApisResponse.hpp>
#include <alibabacloud/models/BatchDeployApisRequest.hpp>
#include <alibabacloud/models/BatchDeployApisResponseBody.hpp>
#include <alibabacloud/models/BatchDeployApisResponse.hpp>
#include <alibabacloud/models/CreateAccessControlListRequest.hpp>
#include <alibabacloud/models/CreateAccessControlListResponseBody.hpp>
#include <alibabacloud/models/CreateAccessControlListResponse.hpp>
#include <alibabacloud/models/CreateApiRequest.hpp>
#include <alibabacloud/models/CreateApiResponseBody.hpp>
#include <alibabacloud/models/CreateApiResponse.hpp>
#include <alibabacloud/models/CreateApiGroupRequest.hpp>
#include <alibabacloud/models/CreateApiGroupResponseBody.hpp>
#include <alibabacloud/models/CreateApiGroupResponse.hpp>
#include <alibabacloud/models/CreateApiStageVariableRequest.hpp>
#include <alibabacloud/models/CreateApiStageVariableResponseBody.hpp>
#include <alibabacloud/models/CreateApiStageVariableResponse.hpp>
#include <alibabacloud/models/CreateAppRequest.hpp>
#include <alibabacloud/models/CreateAppResponseBody.hpp>
#include <alibabacloud/models/CreateAppResponse.hpp>
#include <alibabacloud/models/CreateAppCodeRequest.hpp>
#include <alibabacloud/models/CreateAppCodeResponseBody.hpp>
#include <alibabacloud/models/CreateAppCodeResponse.hpp>
#include <alibabacloud/models/CreateAppKeyRequest.hpp>
#include <alibabacloud/models/CreateAppKeyResponseBody.hpp>
#include <alibabacloud/models/CreateAppKeyResponse.hpp>
#include <alibabacloud/models/CreateBackendRequest.hpp>
#include <alibabacloud/models/CreateBackendResponseBody.hpp>
#include <alibabacloud/models/CreateBackendResponse.hpp>
#include <alibabacloud/models/CreateBackendModelRequest.hpp>
#include <alibabacloud/models/CreateBackendModelResponseBody.hpp>
#include <alibabacloud/models/CreateBackendModelResponse.hpp>
#include <alibabacloud/models/CreateDatasetRequest.hpp>
#include <alibabacloud/models/CreateDatasetResponseBody.hpp>
#include <alibabacloud/models/CreateDatasetResponse.hpp>
#include <alibabacloud/models/CreateDatasetItemRequest.hpp>
#include <alibabacloud/models/CreateDatasetItemResponseBody.hpp>
#include <alibabacloud/models/CreateDatasetItemResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateIntranetDomainRequest.hpp>
#include <alibabacloud/models/CreateIntranetDomainResponseBody.hpp>
#include <alibabacloud/models/CreateIntranetDomainResponse.hpp>
#include <alibabacloud/models/CreateIpControlRequest.hpp>
#include <alibabacloud/models/CreateIpControlResponseBody.hpp>
#include <alibabacloud/models/CreateIpControlResponse.hpp>
#include <alibabacloud/models/CreateLogConfigRequest.hpp>
#include <alibabacloud/models/CreateLogConfigResponseBody.hpp>
#include <alibabacloud/models/CreateLogConfigResponse.hpp>
#include <alibabacloud/models/CreateModelRequest.hpp>
#include <alibabacloud/models/CreateModelResponseBody.hpp>
#include <alibabacloud/models/CreateModelResponse.hpp>
#include <alibabacloud/models/CreateMonitorGroupRequest.hpp>
#include <alibabacloud/models/CreateMonitorGroupResponseBody.hpp>
#include <alibabacloud/models/CreateMonitorGroupResponse.hpp>
#include <alibabacloud/models/CreatePluginRequest.hpp>
#include <alibabacloud/models/CreatePluginResponseBody.hpp>
#include <alibabacloud/models/CreatePluginResponse.hpp>
#include <alibabacloud/models/CreatePrivateDnsRequest.hpp>
#include <alibabacloud/models/CreatePrivateDnsShrinkRequest.hpp>
#include <alibabacloud/models/CreatePrivateDnsResponseBody.hpp>
#include <alibabacloud/models/CreatePrivateDnsResponse.hpp>
#include <alibabacloud/models/CreateSignatureRequest.hpp>
#include <alibabacloud/models/CreateSignatureResponseBody.hpp>
#include <alibabacloud/models/CreateSignatureResponse.hpp>
#include <alibabacloud/models/CreateTrafficControlRequest.hpp>
#include <alibabacloud/models/CreateTrafficControlResponseBody.hpp>
#include <alibabacloud/models/CreateTrafficControlResponse.hpp>
#include <alibabacloud/models/DeleteAccessControlListRequest.hpp>
#include <alibabacloud/models/DeleteAccessControlListResponseBody.hpp>
#include <alibabacloud/models/DeleteAccessControlListResponse.hpp>
#include <alibabacloud/models/DeleteAllTrafficSpecialControlRequest.hpp>
#include <alibabacloud/models/DeleteAllTrafficSpecialControlResponseBody.hpp>
#include <alibabacloud/models/DeleteAllTrafficSpecialControlResponse.hpp>
#include <alibabacloud/models/DeleteApiRequest.hpp>
#include <alibabacloud/models/DeleteApiResponseBody.hpp>
#include <alibabacloud/models/DeleteApiResponse.hpp>
#include <alibabacloud/models/DeleteApiGroupRequest.hpp>
#include <alibabacloud/models/DeleteApiGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteApiGroupResponse.hpp>
#include <alibabacloud/models/DeleteApiProductRequest.hpp>
#include <alibabacloud/models/DeleteApiProductResponseBody.hpp>
#include <alibabacloud/models/DeleteApiProductResponse.hpp>
#include <alibabacloud/models/DeleteApiStageVariableRequest.hpp>
#include <alibabacloud/models/DeleteApiStageVariableResponseBody.hpp>
#include <alibabacloud/models/DeleteApiStageVariableResponse.hpp>
#include <alibabacloud/models/DeleteAppRequest.hpp>
#include <alibabacloud/models/DeleteAppResponseBody.hpp>
#include <alibabacloud/models/DeleteAppResponse.hpp>
#include <alibabacloud/models/DeleteAppCodeRequest.hpp>
#include <alibabacloud/models/DeleteAppCodeResponseBody.hpp>
#include <alibabacloud/models/DeleteAppCodeResponse.hpp>
#include <alibabacloud/models/DeleteAppKeyRequest.hpp>
#include <alibabacloud/models/DeleteAppKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteAppKeyResponse.hpp>
#include <alibabacloud/models/DeleteBackendRequest.hpp>
#include <alibabacloud/models/DeleteBackendResponseBody.hpp>
#include <alibabacloud/models/DeleteBackendResponse.hpp>
#include <alibabacloud/models/DeleteBackendModelRequest.hpp>
#include <alibabacloud/models/DeleteBackendModelResponseBody.hpp>
#include <alibabacloud/models/DeleteBackendModelResponse.hpp>
#include <alibabacloud/models/DeleteDatasetRequest.hpp>
#include <alibabacloud/models/DeleteDatasetResponseBody.hpp>
#include <alibabacloud/models/DeleteDatasetResponse.hpp>
#include <alibabacloud/models/DeleteDatasetItemRequest.hpp>
#include <alibabacloud/models/DeleteDatasetItemResponseBody.hpp>
#include <alibabacloud/models/DeleteDatasetItemResponse.hpp>
#include <alibabacloud/models/DeleteDomainRequest.hpp>
#include <alibabacloud/models/DeleteDomainResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainResponse.hpp>
#include <alibabacloud/models/DeleteDomainCertificateRequest.hpp>
#include <alibabacloud/models/DeleteDomainCertificateResponseBody.hpp>
#include <alibabacloud/models/DeleteDomainCertificateResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteIpControlRequest.hpp>
#include <alibabacloud/models/DeleteIpControlResponseBody.hpp>
#include <alibabacloud/models/DeleteIpControlResponse.hpp>
#include <alibabacloud/models/DeleteLogConfigRequest.hpp>
#include <alibabacloud/models/DeleteLogConfigResponseBody.hpp>
#include <alibabacloud/models/DeleteLogConfigResponse.hpp>
#include <alibabacloud/models/DeleteModelRequest.hpp>
#include <alibabacloud/models/DeleteModelResponseBody.hpp>
#include <alibabacloud/models/DeleteModelResponse.hpp>
#include <alibabacloud/models/DeleteMonitorGroupRequest.hpp>
#include <alibabacloud/models/DeleteMonitorGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteMonitorGroupResponse.hpp>
#include <alibabacloud/models/DeletePluginRequest.hpp>
#include <alibabacloud/models/DeletePluginResponseBody.hpp>
#include <alibabacloud/models/DeletePluginResponse.hpp>
#include <alibabacloud/models/DeletePrivateDnsRequest.hpp>
#include <alibabacloud/models/DeletePrivateDnsResponseBody.hpp>
#include <alibabacloud/models/DeletePrivateDnsResponse.hpp>
#include <alibabacloud/models/DeleteSignatureRequest.hpp>
#include <alibabacloud/models/DeleteSignatureResponseBody.hpp>
#include <alibabacloud/models/DeleteSignatureResponse.hpp>
#include <alibabacloud/models/DeleteTrafficControlRequest.hpp>
#include <alibabacloud/models/DeleteTrafficControlResponseBody.hpp>
#include <alibabacloud/models/DeleteTrafficControlResponse.hpp>
#include <alibabacloud/models/DeleteTrafficSpecialControlRequest.hpp>
#include <alibabacloud/models/DeleteTrafficSpecialControlResponseBody.hpp>
#include <alibabacloud/models/DeleteTrafficSpecialControlResponse.hpp>
#include <alibabacloud/models/DeployApiRequest.hpp>
#include <alibabacloud/models/DeployApiResponseBody.hpp>
#include <alibabacloud/models/DeployApiResponse.hpp>
#include <alibabacloud/models/DescribeAbolishApiTaskRequest.hpp>
#include <alibabacloud/models/DescribeAbolishApiTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeAbolishApiTaskResponse.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeRequest.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponse.hpp>
#include <alibabacloud/models/DescribeAccessControlListsRequest.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponse.hpp>
#include <alibabacloud/models/DescribeApiRequest.hpp>
#include <alibabacloud/models/DescribeApiResponseBody.hpp>
#include <alibabacloud/models/DescribeApiResponse.hpp>
#include <alibabacloud/models/DescribeApiDocRequest.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBody.hpp>
#include <alibabacloud/models/DescribeApiDocResponse.hpp>
#include <alibabacloud/models/DescribeApiGroupRequest.hpp>
#include <alibabacloud/models/DescribeApiGroupResponseBody.hpp>
#include <alibabacloud/models/DescribeApiGroupResponse.hpp>
#include <alibabacloud/models/DescribeApiGroupVpcWhitelistRequest.hpp>
#include <alibabacloud/models/DescribeApiGroupVpcWhitelistResponseBody.hpp>
#include <alibabacloud/models/DescribeApiGroupVpcWhitelistResponse.hpp>
#include <alibabacloud/models/DescribeApiGroupsRequest.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponse.hpp>
#include <alibabacloud/models/DescribeApiHistoriesRequest.hpp>
#include <alibabacloud/models/DescribeApiHistoriesResponseBody.hpp>
#include <alibabacloud/models/DescribeApiHistoriesResponse.hpp>
#include <alibabacloud/models/DescribeApiHistoryRequest.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBody.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponse.hpp>
#include <alibabacloud/models/DescribeApiIpControlsRequest.hpp>
#include <alibabacloud/models/DescribeApiIpControlsResponseBody.hpp>
#include <alibabacloud/models/DescribeApiIpControlsResponse.hpp>
#include <alibabacloud/models/DescribeApiLatencyDataRequest.hpp>
#include <alibabacloud/models/DescribeApiLatencyDataResponseBody.hpp>
#include <alibabacloud/models/DescribeApiLatencyDataResponse.hpp>
#include <alibabacloud/models/DescribeApiMarketAttributesRequest.hpp>
#include <alibabacloud/models/DescribeApiMarketAttributesResponseBody.hpp>
#include <alibabacloud/models/DescribeApiMarketAttributesResponse.hpp>
#include <alibabacloud/models/DescribeApiProductApisRequest.hpp>
#include <alibabacloud/models/DescribeApiProductApisResponseBody.hpp>
#include <alibabacloud/models/DescribeApiProductApisResponse.hpp>
#include <alibabacloud/models/DescribeApiProductsByAppRequest.hpp>
#include <alibabacloud/models/DescribeApiProductsByAppResponseBody.hpp>
#include <alibabacloud/models/DescribeApiProductsByAppResponse.hpp>
#include <alibabacloud/models/DescribeApiQpsDataRequest.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponseBody.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponse.hpp>
#include <alibabacloud/models/DescribeApiSignaturesRequest.hpp>
#include <alibabacloud/models/DescribeApiSignaturesResponseBody.hpp>
#include <alibabacloud/models/DescribeApiSignaturesResponse.hpp>
#include <alibabacloud/models/DescribeApiTrafficControlsRequest.hpp>
#include <alibabacloud/models/DescribeApiTrafficControlsResponseBody.hpp>
#include <alibabacloud/models/DescribeApiTrafficControlsResponse.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataRequest.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponseBody.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponse.hpp>
#include <alibabacloud/models/DescribeApisRequest.hpp>
#include <alibabacloud/models/DescribeApisResponseBody.hpp>
#include <alibabacloud/models/DescribeApisResponse.hpp>
#include <alibabacloud/models/DescribeApisByAppRequest.hpp>
#include <alibabacloud/models/DescribeApisByAppResponseBody.hpp>
#include <alibabacloud/models/DescribeApisByAppResponse.hpp>
#include <alibabacloud/models/DescribeApisByBackendRequest.hpp>
#include <alibabacloud/models/DescribeApisByBackendResponseBody.hpp>
#include <alibabacloud/models/DescribeApisByBackendResponse.hpp>
#include <alibabacloud/models/DescribeApisByIpControlRequest.hpp>
#include <alibabacloud/models/DescribeApisByIpControlResponseBody.hpp>
#include <alibabacloud/models/DescribeApisByIpControlResponse.hpp>
#include <alibabacloud/models/DescribeApisBySignatureRequest.hpp>
#include <alibabacloud/models/DescribeApisBySignatureResponseBody.hpp>
#include <alibabacloud/models/DescribeApisBySignatureResponse.hpp>
#include <alibabacloud/models/DescribeApisByTrafficControlRequest.hpp>
#include <alibabacloud/models/DescribeApisByTrafficControlResponseBody.hpp>
#include <alibabacloud/models/DescribeApisByTrafficControlResponse.hpp>
#include <alibabacloud/models/DescribeApisByVpcAccessRequest.hpp>
#include <alibabacloud/models/DescribeApisByVpcAccessResponseBody.hpp>
#include <alibabacloud/models/DescribeApisByVpcAccessResponse.hpp>
#include <alibabacloud/models/DescribeApisWithStageNameIntegratedByAppRequest.hpp>
#include <alibabacloud/models/DescribeApisWithStageNameIntegratedByAppResponseBody.hpp>
#include <alibabacloud/models/DescribeApisWithStageNameIntegratedByAppResponse.hpp>
#include <alibabacloud/models/DescribeAppRequest.hpp>
#include <alibabacloud/models/DescribeAppResponseBody.hpp>
#include <alibabacloud/models/DescribeAppResponse.hpp>
#include <alibabacloud/models/DescribeAppAttributesRequest.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponse.hpp>
#include <alibabacloud/models/DescribeAppSecuritiesRequest.hpp>
#include <alibabacloud/models/DescribeAppSecuritiesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppSecuritiesResponse.hpp>
#include <alibabacloud/models/DescribeAppSecurityRequest.hpp>
#include <alibabacloud/models/DescribeAppSecurityResponseBody.hpp>
#include <alibabacloud/models/DescribeAppSecurityResponse.hpp>
#include <alibabacloud/models/DescribeAppsRequest.hpp>
#include <alibabacloud/models/DescribeAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppsResponse.hpp>
#include <alibabacloud/models/DescribeAppsByApiProductRequest.hpp>
#include <alibabacloud/models/DescribeAppsByApiProductResponseBody.hpp>
#include <alibabacloud/models/DescribeAppsByApiProductResponse.hpp>
#include <alibabacloud/models/DescribeAuthorizedApisRequest.hpp>
#include <alibabacloud/models/DescribeAuthorizedApisResponseBody.hpp>
#include <alibabacloud/models/DescribeAuthorizedApisResponse.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsRequest.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponse.hpp>
#include <alibabacloud/models/DescribeBackendInfoRequest.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponse.hpp>
#include <alibabacloud/models/DescribeBackendListRequest.hpp>
#include <alibabacloud/models/DescribeBackendListResponseBody.hpp>
#include <alibabacloud/models/DescribeBackendListResponse.hpp>
#include <alibabacloud/models/DescribeDatasetInfoRequest.hpp>
#include <alibabacloud/models/DescribeDatasetInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDatasetInfoResponse.hpp>
#include <alibabacloud/models/DescribeDatasetItemInfoRequest.hpp>
#include <alibabacloud/models/DescribeDatasetItemInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeDatasetItemInfoResponse.hpp>
#include <alibabacloud/models/DescribeDatasetItemListRequest.hpp>
#include <alibabacloud/models/DescribeDatasetItemListResponseBody.hpp>
#include <alibabacloud/models/DescribeDatasetItemListResponse.hpp>
#include <alibabacloud/models/DescribeDatasetListRequest.hpp>
#include <alibabacloud/models/DescribeDatasetListResponseBody.hpp>
#include <alibabacloud/models/DescribeDatasetListResponse.hpp>
#include <alibabacloud/models/DescribeDeployApiTaskRequest.hpp>
#include <alibabacloud/models/DescribeDeployApiTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeDeployApiTaskResponse.hpp>
#include <alibabacloud/models/DescribeDeployedApiRequest.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBody.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponse.hpp>
#include <alibabacloud/models/DescribeDeployedApisRequest.hpp>
#include <alibabacloud/models/DescribeDeployedApisResponseBody.hpp>
#include <alibabacloud/models/DescribeDeployedApisResponse.hpp>
#include <alibabacloud/models/DescribeDomainRequest.hpp>
#include <alibabacloud/models/DescribeDomainResponseBody.hpp>
#include <alibabacloud/models/DescribeDomainResponse.hpp>
#include <alibabacloud/models/DescribeGroupLatencyRequest.hpp>
#include <alibabacloud/models/DescribeGroupLatencyResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupLatencyResponse.hpp>
#include <alibabacloud/models/DescribeGroupQpsRequest.hpp>
#include <alibabacloud/models/DescribeGroupQpsResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupQpsResponse.hpp>
#include <alibabacloud/models/DescribeGroupTrafficRequest.hpp>
#include <alibabacloud/models/DescribeGroupTrafficResponseBody.hpp>
#include <alibabacloud/models/DescribeGroupTrafficResponse.hpp>
#include <alibabacloud/models/DescribeHistoryApisRequest.hpp>
#include <alibabacloud/models/DescribeHistoryApisResponseBody.hpp>
#include <alibabacloud/models/DescribeHistoryApisResponse.hpp>
#include <alibabacloud/models/DescribeImportOasTaskRequest.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponse.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoRequest.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoResponse.hpp>
#include <alibabacloud/models/DescribeInstanceClusterListRequest.hpp>
#include <alibabacloud/models/DescribeInstanceClusterListResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceClusterListResponse.hpp>
#include <alibabacloud/models/DescribeInstanceDropConnectionsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceDropConnectionsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceDropConnectionsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceDropPacketRequest.hpp>
#include <alibabacloud/models/DescribeInstanceDropPacketResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceDropPacketResponse.hpp>
#include <alibabacloud/models/DescribeInstanceHttpCodeRequest.hpp>
#include <alibabacloud/models/DescribeInstanceHttpCodeResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceHttpCodeResponse.hpp>
#include <alibabacloud/models/DescribeInstanceLatencyRequest.hpp>
#include <alibabacloud/models/DescribeInstanceLatencyResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceLatencyResponse.hpp>
#include <alibabacloud/models/DescribeInstanceNewConnectionsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceNewConnectionsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceNewConnectionsResponse.hpp>
#include <alibabacloud/models/DescribeInstancePacketsRequest.hpp>
#include <alibabacloud/models/DescribeInstancePacketsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancePacketsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceQpsRequest.hpp>
#include <alibabacloud/models/DescribeInstanceQpsResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceQpsResponse.hpp>
#include <alibabacloud/models/DescribeInstanceSlbConnectRequest.hpp>
#include <alibabacloud/models/DescribeInstanceSlbConnectResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceSlbConnectResponse.hpp>
#include <alibabacloud/models/DescribeInstanceTrafficRequest.hpp>
#include <alibabacloud/models/DescribeInstanceTrafficResponseBody.hpp>
#include <alibabacloud/models/DescribeInstanceTrafficResponse.hpp>
#include <alibabacloud/models/DescribeInstancesRequest.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancesResponse.hpp>
#include <alibabacloud/models/DescribeIpControlPolicyItemsRequest.hpp>
#include <alibabacloud/models/DescribeIpControlPolicyItemsResponseBody.hpp>
#include <alibabacloud/models/DescribeIpControlPolicyItemsResponse.hpp>
#include <alibabacloud/models/DescribeIpControlsRequest.hpp>
#include <alibabacloud/models/DescribeIpControlsResponseBody.hpp>
#include <alibabacloud/models/DescribeIpControlsResponse.hpp>
#include <alibabacloud/models/DescribeLogConfigRequest.hpp>
#include <alibabacloud/models/DescribeLogConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeLogConfigResponse.hpp>
#include <alibabacloud/models/DescribeMarketRemainsQuotaRequest.hpp>
#include <alibabacloud/models/DescribeMarketRemainsQuotaResponseBody.hpp>
#include <alibabacloud/models/DescribeMarketRemainsQuotaResponse.hpp>
#include <alibabacloud/models/DescribeModelsRequest.hpp>
#include <alibabacloud/models/DescribeModelsResponseBody.hpp>
#include <alibabacloud/models/DescribeModelsResponse.hpp>
#include <alibabacloud/models/DescribePluginApisRequest.hpp>
#include <alibabacloud/models/DescribePluginApisResponseBody.hpp>
#include <alibabacloud/models/DescribePluginApisResponse.hpp>
#include <alibabacloud/models/DescribePluginGroupsRequest.hpp>
#include <alibabacloud/models/DescribePluginGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribePluginGroupsResponse.hpp>
#include <alibabacloud/models/DescribePluginSchemasRequest.hpp>
#include <alibabacloud/models/DescribePluginSchemasResponseBody.hpp>
#include <alibabacloud/models/DescribePluginSchemasResponse.hpp>
#include <alibabacloud/models/DescribePluginTemplatesRequest.hpp>
#include <alibabacloud/models/DescribePluginTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribePluginTemplatesResponse.hpp>
#include <alibabacloud/models/DescribePluginsRequest.hpp>
#include <alibabacloud/models/DescribePluginsResponseBody.hpp>
#include <alibabacloud/models/DescribePluginsResponse.hpp>
#include <alibabacloud/models/DescribePluginsByApiRequest.hpp>
#include <alibabacloud/models/DescribePluginsByApiResponseBody.hpp>
#include <alibabacloud/models/DescribePluginsByApiResponse.hpp>
#include <alibabacloud/models/DescribePluginsByGroupRequest.hpp>
#include <alibabacloud/models/DescribePluginsByGroupResponseBody.hpp>
#include <alibabacloud/models/DescribePluginsByGroupResponse.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupRequest.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupResponseBody.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupResponse.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupsRequest.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupsResponse.hpp>
#include <alibabacloud/models/DescribePurchasedApisRequest.hpp>
#include <alibabacloud/models/DescribePurchasedApisResponseBody.hpp>
#include <alibabacloud/models/DescribePurchasedApisResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeSignaturesRequest.hpp>
#include <alibabacloud/models/DescribeSignaturesResponseBody.hpp>
#include <alibabacloud/models/DescribeSignaturesResponse.hpp>
#include <alibabacloud/models/DescribeSignaturesByApiRequest.hpp>
#include <alibabacloud/models/DescribeSignaturesByApiResponseBody.hpp>
#include <alibabacloud/models/DescribeSignaturesByApiResponse.hpp>
#include <alibabacloud/models/DescribeSummaryDataRequest.hpp>
#include <alibabacloud/models/DescribeSummaryDataResponseBody.hpp>
#include <alibabacloud/models/DescribeSummaryDataResponse.hpp>
#include <alibabacloud/models/DescribeSystemParametersRequest.hpp>
#include <alibabacloud/models/DescribeSystemParametersResponseBody.hpp>
#include <alibabacloud/models/DescribeSystemParametersResponse.hpp>
#include <alibabacloud/models/DescribeTrafficControlsRequest.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBody.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponse.hpp>
#include <alibabacloud/models/DescribeTrafficControlsByApiRequest.hpp>
#include <alibabacloud/models/DescribeTrafficControlsByApiResponseBody.hpp>
#include <alibabacloud/models/DescribeTrafficControlsByApiResponse.hpp>
#include <alibabacloud/models/DescribeUpdateBackendTaskRequest.hpp>
#include <alibabacloud/models/DescribeUpdateBackendTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeUpdateBackendTaskResponse.hpp>
#include <alibabacloud/models/DescribeUpdateVpcInfoTaskRequest.hpp>
#include <alibabacloud/models/DescribeUpdateVpcInfoTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeUpdateVpcInfoTaskResponse.hpp>
#include <alibabacloud/models/DescribeVpcAccessesRequest.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DetachApiProductRequest.hpp>
#include <alibabacloud/models/DetachApiProductResponseBody.hpp>
#include <alibabacloud/models/DetachApiProductResponse.hpp>
#include <alibabacloud/models/DetachGroupPluginRequest.hpp>
#include <alibabacloud/models/DetachGroupPluginResponseBody.hpp>
#include <alibabacloud/models/DetachGroupPluginResponse.hpp>
#include <alibabacloud/models/DetachPluginRequest.hpp>
#include <alibabacloud/models/DetachPluginResponseBody.hpp>
#include <alibabacloud/models/DetachPluginResponse.hpp>
#include <alibabacloud/models/DisableInstanceAccessControlRequest.hpp>
#include <alibabacloud/models/DisableInstanceAccessControlResponseBody.hpp>
#include <alibabacloud/models/DisableInstanceAccessControlResponse.hpp>
#include <alibabacloud/models/DissociateInstanceWithPrivateDnsRequest.hpp>
#include <alibabacloud/models/DissociateInstanceWithPrivateDnsShrinkRequest.hpp>
#include <alibabacloud/models/DissociateInstanceWithPrivateDnsResponseBody.hpp>
#include <alibabacloud/models/DissociateInstanceWithPrivateDnsResponse.hpp>
#include <alibabacloud/models/DryRunSwaggerRequest.hpp>
#include <alibabacloud/models/DryRunSwaggerShrinkRequest.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBody.hpp>
#include <alibabacloud/models/DryRunSwaggerResponse.hpp>
#include <alibabacloud/models/EnableInstanceAccessControlRequest.hpp>
#include <alibabacloud/models/EnableInstanceAccessControlResponseBody.hpp>
#include <alibabacloud/models/EnableInstanceAccessControlResponse.hpp>
#include <alibabacloud/models/ExportOasRequest.hpp>
#include <alibabacloud/models/ExportOasShrinkRequest.hpp>
#include <alibabacloud/models/ExportOasResponseBody.hpp>
#include <alibabacloud/models/ExportOasResponse.hpp>
#include <alibabacloud/models/ImportOasRequest.hpp>
#include <alibabacloud/models/ImportOasResponseBody.hpp>
#include <alibabacloud/models/ImportOasResponse.hpp>
#include <alibabacloud/models/ImportSwaggerRequest.hpp>
#include <alibabacloud/models/ImportSwaggerShrinkRequest.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBody.hpp>
#include <alibabacloud/models/ImportSwaggerResponse.hpp>
#include <alibabacloud/models/ListPrivateDnsRequest.hpp>
#include <alibabacloud/models/ListPrivateDnsResponseBody.hpp>
#include <alibabacloud/models/ListPrivateDnsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyApiRequest.hpp>
#include <alibabacloud/models/ModifyApiResponseBody.hpp>
#include <alibabacloud/models/ModifyApiResponse.hpp>
#include <alibabacloud/models/ModifyApiConfigurationRequest.hpp>
#include <alibabacloud/models/ModifyApiConfigurationResponseBody.hpp>
#include <alibabacloud/models/ModifyApiConfigurationResponse.hpp>
#include <alibabacloud/models/ModifyApiGroupRequest.hpp>
#include <alibabacloud/models/ModifyApiGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyApiGroupResponse.hpp>
#include <alibabacloud/models/ModifyApiGroupInstanceRequest.hpp>
#include <alibabacloud/models/ModifyApiGroupInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyApiGroupInstanceResponse.hpp>
#include <alibabacloud/models/ModifyApiGroupNetworkPolicyRequest.hpp>
#include <alibabacloud/models/ModifyApiGroupNetworkPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyApiGroupNetworkPolicyResponse.hpp>
#include <alibabacloud/models/ModifyApiGroupVpcWhitelistRequest.hpp>
#include <alibabacloud/models/ModifyApiGroupVpcWhitelistResponseBody.hpp>
#include <alibabacloud/models/ModifyApiGroupVpcWhitelistResponse.hpp>
#include <alibabacloud/models/ModifyAppRequest.hpp>
#include <alibabacloud/models/ModifyAppResponseBody.hpp>
#include <alibabacloud/models/ModifyAppResponse.hpp>
#include <alibabacloud/models/ModifyBackendRequest.hpp>
#include <alibabacloud/models/ModifyBackendResponseBody.hpp>
#include <alibabacloud/models/ModifyBackendResponse.hpp>
#include <alibabacloud/models/ModifyBackendModelRequest.hpp>
#include <alibabacloud/models/ModifyBackendModelResponseBody.hpp>
#include <alibabacloud/models/ModifyBackendModelResponse.hpp>
#include <alibabacloud/models/ModifyDatasetRequest.hpp>
#include <alibabacloud/models/ModifyDatasetResponseBody.hpp>
#include <alibabacloud/models/ModifyDatasetResponse.hpp>
#include <alibabacloud/models/ModifyDatasetItemRequest.hpp>
#include <alibabacloud/models/ModifyDatasetItemResponseBody.hpp>
#include <alibabacloud/models/ModifyDatasetItemResponse.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeShrinkRequest.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyInstanceSpecRequest.hpp>
#include <alibabacloud/models/ModifyInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceSpecResponse.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAttributeForConsoleRequest.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAttributeForConsoleResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceVpcAttributeForConsoleResponse.hpp>
#include <alibabacloud/models/ModifyIntranetDomainPolicyRequest.hpp>
#include <alibabacloud/models/ModifyIntranetDomainPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyIntranetDomainPolicyResponse.hpp>
#include <alibabacloud/models/ModifyIpControlRequest.hpp>
#include <alibabacloud/models/ModifyIpControlResponseBody.hpp>
#include <alibabacloud/models/ModifyIpControlResponse.hpp>
#include <alibabacloud/models/ModifyIpControlPolicyItemRequest.hpp>
#include <alibabacloud/models/ModifyIpControlPolicyItemResponseBody.hpp>
#include <alibabacloud/models/ModifyIpControlPolicyItemResponse.hpp>
#include <alibabacloud/models/ModifyLogConfigRequest.hpp>
#include <alibabacloud/models/ModifyLogConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyLogConfigResponse.hpp>
#include <alibabacloud/models/ModifyModelRequest.hpp>
#include <alibabacloud/models/ModifyModelResponseBody.hpp>
#include <alibabacloud/models/ModifyModelResponse.hpp>
#include <alibabacloud/models/ModifyPluginRequest.hpp>
#include <alibabacloud/models/ModifyPluginResponseBody.hpp>
#include <alibabacloud/models/ModifyPluginResponse.hpp>
#include <alibabacloud/models/ModifySignatureRequest.hpp>
#include <alibabacloud/models/ModifySignatureResponseBody.hpp>
#include <alibabacloud/models/ModifySignatureResponse.hpp>
#include <alibabacloud/models/ModifyTrafficControlRequest.hpp>
#include <alibabacloud/models/ModifyTrafficControlResponseBody.hpp>
#include <alibabacloud/models/ModifyTrafficControlResponse.hpp>
#include <alibabacloud/models/ModifyVpcAccessAndUpdateApisRequest.hpp>
#include <alibabacloud/models/ModifyVpcAccessAndUpdateApisResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcAccessAndUpdateApisResponse.hpp>
#include <alibabacloud/models/OpenApiGatewayServiceResponseBody.hpp>
#include <alibabacloud/models/OpenApiGatewayServiceResponse.hpp>
#include <alibabacloud/models/QueryRequestLogsRequest.hpp>
#include <alibabacloud/models/QueryRequestLogsResponseBody.hpp>
#include <alibabacloud/models/QueryRequestLogsResponse.hpp>
#include <alibabacloud/models/ReactivateDomainRequest.hpp>
#include <alibabacloud/models/ReactivateDomainResponseBody.hpp>
#include <alibabacloud/models/ReactivateDomainResponse.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryRequest.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryResponseBody.hpp>
#include <alibabacloud/models/RemoveAccessControlListEntryResponse.hpp>
#include <alibabacloud/models/RemoveApiProductsAuthoritiesRequest.hpp>
#include <alibabacloud/models/RemoveApiProductsAuthoritiesShrinkRequest.hpp>
#include <alibabacloud/models/RemoveApiProductsAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/RemoveApiProductsAuthoritiesResponse.hpp>
#include <alibabacloud/models/RemoveApisAuthoritiesRequest.hpp>
#include <alibabacloud/models/RemoveApisAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/RemoveApisAuthoritiesResponse.hpp>
#include <alibabacloud/models/RemoveAppsAuthoritiesRequest.hpp>
#include <alibabacloud/models/RemoveAppsAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/RemoveAppsAuthoritiesResponse.hpp>
#include <alibabacloud/models/RemoveIpControlApisRequest.hpp>
#include <alibabacloud/models/RemoveIpControlApisResponseBody.hpp>
#include <alibabacloud/models/RemoveIpControlApisResponse.hpp>
#include <alibabacloud/models/RemoveIpControlPolicyItemRequest.hpp>
#include <alibabacloud/models/RemoveIpControlPolicyItemResponseBody.hpp>
#include <alibabacloud/models/RemoveIpControlPolicyItemResponse.hpp>
#include <alibabacloud/models/RemoveSignatureApisRequest.hpp>
#include <alibabacloud/models/RemoveSignatureApisResponseBody.hpp>
#include <alibabacloud/models/RemoveSignatureApisResponse.hpp>
#include <alibabacloud/models/RemoveTrafficControlApisRequest.hpp>
#include <alibabacloud/models/RemoveTrafficControlApisResponseBody.hpp>
#include <alibabacloud/models/RemoveTrafficControlApisResponse.hpp>
#include <alibabacloud/models/RemoveVpcAccessRequest.hpp>
#include <alibabacloud/models/RemoveVpcAccessResponseBody.hpp>
#include <alibabacloud/models/RemoveVpcAccessResponse.hpp>
#include <alibabacloud/models/RemoveVpcAccessAndAbolishApisRequest.hpp>
#include <alibabacloud/models/RemoveVpcAccessAndAbolishApisResponseBody.hpp>
#include <alibabacloud/models/RemoveVpcAccessAndAbolishApisResponse.hpp>
#include <alibabacloud/models/ResetAppCodeRequest.hpp>
#include <alibabacloud/models/ResetAppCodeResponseBody.hpp>
#include <alibabacloud/models/ResetAppCodeResponse.hpp>
#include <alibabacloud/models/ResetAppSecretRequest.hpp>
#include <alibabacloud/models/ResetAppSecretResponseBody.hpp>
#include <alibabacloud/models/ResetAppSecretResponse.hpp>
#include <alibabacloud/models/SdkGenerateByAppRequest.hpp>
#include <alibabacloud/models/SdkGenerateByAppResponseBody.hpp>
#include <alibabacloud/models/SdkGenerateByAppResponse.hpp>
#include <alibabacloud/models/SdkGenerateByAppForRegionRequest.hpp>
#include <alibabacloud/models/SdkGenerateByAppForRegionResponseBody.hpp>
#include <alibabacloud/models/SdkGenerateByAppForRegionResponse.hpp>
#include <alibabacloud/models/SdkGenerateByGroupRequest.hpp>
#include <alibabacloud/models/SdkGenerateByGroupResponseBody.hpp>
#include <alibabacloud/models/SdkGenerateByGroupResponse.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeRequest.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeResponseBody.hpp>
#include <alibabacloud/models/SetAccessControlListAttributeResponse.hpp>
#include <alibabacloud/models/SetApiProductsAuthoritiesRequest.hpp>
#include <alibabacloud/models/SetApiProductsAuthoritiesShrinkRequest.hpp>
#include <alibabacloud/models/SetApiProductsAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/SetApiProductsAuthoritiesResponse.hpp>
#include <alibabacloud/models/SetApisAuthoritiesRequest.hpp>
#include <alibabacloud/models/SetApisAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/SetApisAuthoritiesResponse.hpp>
#include <alibabacloud/models/SetAppsAuthToApiProductRequest.hpp>
#include <alibabacloud/models/SetAppsAuthToApiProductResponseBody.hpp>
#include <alibabacloud/models/SetAppsAuthToApiProductResponse.hpp>
#include <alibabacloud/models/SetAppsAuthoritiesRequest.hpp>
#include <alibabacloud/models/SetAppsAuthoritiesResponseBody.hpp>
#include <alibabacloud/models/SetAppsAuthoritiesResponse.hpp>
#include <alibabacloud/models/SetDomainRequest.hpp>
#include <alibabacloud/models/SetDomainResponseBody.hpp>
#include <alibabacloud/models/SetDomainResponse.hpp>
#include <alibabacloud/models/SetDomainCertificateRequest.hpp>
#include <alibabacloud/models/SetDomainCertificateResponseBody.hpp>
#include <alibabacloud/models/SetDomainCertificateResponse.hpp>
#include <alibabacloud/models/SetDomainWebSocketStatusRequest.hpp>
#include <alibabacloud/models/SetDomainWebSocketStatusResponseBody.hpp>
#include <alibabacloud/models/SetDomainWebSocketStatusResponse.hpp>
#include <alibabacloud/models/SetGroupAuthAppCodeRequest.hpp>
#include <alibabacloud/models/SetGroupAuthAppCodeResponseBody.hpp>
#include <alibabacloud/models/SetGroupAuthAppCodeResponse.hpp>
#include <alibabacloud/models/SetIpControlApisRequest.hpp>
#include <alibabacloud/models/SetIpControlApisResponseBody.hpp>
#include <alibabacloud/models/SetIpControlApisResponse.hpp>
#include <alibabacloud/models/SetSignatureApisRequest.hpp>
#include <alibabacloud/models/SetSignatureApisResponseBody.hpp>
#include <alibabacloud/models/SetSignatureApisResponse.hpp>
#include <alibabacloud/models/SetTrafficControlApisRequest.hpp>
#include <alibabacloud/models/SetTrafficControlApisResponseBody.hpp>
#include <alibabacloud/models/SetTrafficControlApisResponse.hpp>
#include <alibabacloud/models/SetVpcAccessRequest.hpp>
#include <alibabacloud/models/SetVpcAccessResponseBody.hpp>
#include <alibabacloud/models/SetVpcAccessResponse.hpp>
#include <alibabacloud/models/SetWildcardDomainPatternsRequest.hpp>
#include <alibabacloud/models/SetWildcardDomainPatternsResponseBody.hpp>
#include <alibabacloud/models/SetWildcardDomainPatternsResponse.hpp>
#include <alibabacloud/models/SwitchApiRequest.hpp>
#include <alibabacloud/models/SwitchApiResponseBody.hpp>
#include <alibabacloud/models/SwitchApiResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdatePrivateDnsRequest.hpp>
#include <alibabacloud/models/UpdatePrivateDnsShrinkRequest.hpp>
#include <alibabacloud/models/UpdatePrivateDnsResponseBody.hpp>
#include <alibabacloud/models/UpdatePrivateDnsResponse.hpp>
#include <alibabacloud/models/ValidateVpcConnectivityRequest.hpp>
#include <alibabacloud/models/ValidateVpcConnectivityResponseBody.hpp>
#include <alibabacloud/models/ValidateVpcConnectivityResponse.hpp>
#include <alibabacloud/models/AttachApiProductRequestApis.hpp>
#include <alibabacloud/models/BatchAbolishApisRequestApi.hpp>
#include <alibabacloud/models/BatchDeployApisRequestApi.hpp>
#include <alibabacloud/models/CreateApiRequestTag.hpp>
#include <alibabacloud/models/CreateApiGroupRequestTag.hpp>
#include <alibabacloud/models/CreateAppRequestTag.hpp>
#include <alibabacloud/models/CreateBackendRequestTag.hpp>
#include <alibabacloud/models/CreateDatasetRequestTag.hpp>
#include <alibabacloud/models/CreateInstanceRequestTag.hpp>
#include <alibabacloud/models/CreateInstanceRequestZoneVSwitchSecurityGroup.hpp>
#include <alibabacloud/models/CreateIpControlRequestIpControlPolicys.hpp>
#include <alibabacloud/models/CreateModelRequestTag.hpp>
#include <alibabacloud/models/CreatePluginRequestTag.hpp>
#include <alibabacloud/models/CreatePrivateDnsRequestRecords.hpp>
#include <alibabacloud/models/DeleteApiGroupRequestTag.hpp>
#include <alibabacloud/models/DeleteAppRequestTag.hpp>
#include <alibabacloud/models/DeleteInstanceRequestTag.hpp>
#include <alibabacloud/models/DeletePluginRequestTag.hpp>
#include <alibabacloud/models/DescribeAbolishApiTaskResponseBodyApiAbolishResultsApiAbolishResult.hpp>
#include <alibabacloud/models/DescribeAbolishApiTaskResponseBodyApiAbolishResults.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyAclEntrysAclEntry.hpp>
#include <alibabacloud/models/DescribeAccessControlListAttributeResponseBodyAclEntrys.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAclsAcl.hpp>
#include <alibabacloud/models/DescribeAccessControlListsResponseBodyAcls.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyBackendConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyConstantParametersConstantParameter.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyConstantParameters.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyCustomSystemParametersCustomSystemParameter.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyCustomSystemParameters.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyDeployedInfosDeployedInfo.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyDeployedInfos.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyErrorCodeSamplesErrorCodeSample.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyErrorCodeSamples.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyOpenIdConnectConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyRequestConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyRequestParametersRequestParameter.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyRequestParameters.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigEventBridgeConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigFunctionComputeConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigMockHeadersMockHeader.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigMockHeaders.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigOssConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfigVpcConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceConfig.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceParametersServiceParameter.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceParameters.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceParametersMapServiceParameterMap.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyServiceParametersMap.hpp>
#include <alibabacloud/models/DescribeApiResponseBodySystemParametersSystemParameter.hpp>
#include <alibabacloud/models/DescribeApiResponseBodySystemParameters.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyTagListTag.hpp>
#include <alibabacloud/models/DescribeApiResponseBodyTagList.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBodyErrorCodeSamplesErrorCodeSample.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBodyErrorCodeSamples.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBodyRequestConfig.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBodyRequestParametersRequestParameter.hpp>
#include <alibabacloud/models/DescribeApiDocResponseBodyRequestParameters.hpp>
#include <alibabacloud/models/DescribeApiGroupRequestTag.hpp>
#include <alibabacloud/models/DescribeApiGroupResponseBodyCustomDomainsDomainItem.hpp>
#include <alibabacloud/models/DescribeApiGroupResponseBodyCustomDomains.hpp>
#include <alibabacloud/models/DescribeApiGroupResponseBodyStageItemsStageInfo.hpp>
#include <alibabacloud/models/DescribeApiGroupResponseBodyStageItems.hpp>
#include <alibabacloud/models/DescribeApiGroupsRequestTag.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponseBodyApiGroupAttributesApiGroupAttributeTagsTagInfo.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponseBodyApiGroupAttributesApiGroupAttributeTags.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponseBodyApiGroupAttributesApiGroupAttribute.hpp>
#include <alibabacloud/models/DescribeApiGroupsResponseBodyApiGroupAttributes.hpp>
#include <alibabacloud/models/DescribeApiHistoriesResponseBodyApiHisItemsApiHisItem.hpp>
#include <alibabacloud/models/DescribeApiHistoriesResponseBodyApiHisItems.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyBackendConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyConstantParametersConstantParameter.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyConstantParameters.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyCustomSystemParametersCustomSystemParameter.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyCustomSystemParameters.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyErrorCodeSamplesErrorCodeSample.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyErrorCodeSamples.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyOpenIdConnectConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyRequestConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyRequestParametersRequestParameter.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyRequestParameters.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyResultDescriptionsResultDescription.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyResultDescriptions.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigEventBridgeConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigFunctionComputeConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigMockHeadersMockHeader.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigMockHeaders.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigOssConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfigVpcConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceConfig.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceParametersServiceParameter.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceParameters.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceParametersMapServiceParameterMap.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodyServiceParametersMap.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodySystemParametersSystemParameter.hpp>
#include <alibabacloud/models/DescribeApiHistoryResponseBodySystemParameters.hpp>
#include <alibabacloud/models/DescribeApiIpControlsResponseBodyApiIpControlsApiIpControlItem.hpp>
#include <alibabacloud/models/DescribeApiIpControlsResponseBodyApiIpControls.hpp>
#include <alibabacloud/models/DescribeApiLatencyDataResponseBodyCallLatencysMonitorItem.hpp>
#include <alibabacloud/models/DescribeApiLatencyDataResponseBodyCallLatencys.hpp>
#include <alibabacloud/models/DescribeApiProductApisResponseBodyApiInfoListApiInfo.hpp>
#include <alibabacloud/models/DescribeApiProductApisResponseBodyApiInfoList.hpp>
#include <alibabacloud/models/DescribeApiProductsByAppResponseBodyApiProductInfoListApiProductInfo.hpp>
#include <alibabacloud/models/DescribeApiProductsByAppResponseBodyApiProductInfoList.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponseBodyCallFailsMonitorItem.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponseBodyCallFails.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponseBodyCallSuccessesMonitorItem.hpp>
#include <alibabacloud/models/DescribeApiQpsDataResponseBodyCallSuccesses.hpp>
#include <alibabacloud/models/DescribeApiSignaturesResponseBodyApiSignaturesApiSignatureItem.hpp>
#include <alibabacloud/models/DescribeApiSignaturesResponseBodyApiSignatures.hpp>
#include <alibabacloud/models/DescribeApiTrafficControlsResponseBodyApiTrafficControlsApiTrafficControlItem.hpp>
#include <alibabacloud/models/DescribeApiTrafficControlsResponseBodyApiTrafficControls.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponseBodyCallDownloadsMonitorItem.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponseBodyCallDownloads.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponseBodyCallUploadsMonitorItem.hpp>
#include <alibabacloud/models/DescribeApiTrafficDataResponseBodyCallUploads.hpp>
#include <alibabacloud/models/DescribeApisRequestTag.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarysApiSummaryDeployedInfosDeployedInfo.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarysApiSummaryDeployedInfos.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarysApiSummaryTagListTag.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarysApiSummaryTagList.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarysApiSummary.hpp>
#include <alibabacloud/models/DescribeApisResponseBodyApiSummarys.hpp>
#include <alibabacloud/models/DescribeApisByAppResponseBodyAppApiRelationInfosAppApiRelationInfo.hpp>
#include <alibabacloud/models/DescribeApisByAppResponseBodyAppApiRelationInfos.hpp>
#include <alibabacloud/models/DescribeApisByBackendResponseBodyApiInfoListApiInfo.hpp>
#include <alibabacloud/models/DescribeApisByBackendResponseBodyApiInfoList.hpp>
#include <alibabacloud/models/DescribeApisByIpControlResponseBodyApiInfosApiInfo.hpp>
#include <alibabacloud/models/DescribeApisByIpControlResponseBodyApiInfos.hpp>
#include <alibabacloud/models/DescribeApisBySignatureResponseBodyApiInfosApiInfo.hpp>
#include <alibabacloud/models/DescribeApisBySignatureResponseBodyApiInfos.hpp>
#include <alibabacloud/models/DescribeApisByTrafficControlResponseBodyApiInfosApiInfo.hpp>
#include <alibabacloud/models/DescribeApisByTrafficControlResponseBodyApiInfos.hpp>
#include <alibabacloud/models/DescribeApisByVpcAccessResponseBodyApiVpcAccessInfosApiVpcAccessInfo.hpp>
#include <alibabacloud/models/DescribeApisByVpcAccessResponseBodyApiVpcAccessInfos.hpp>
#include <alibabacloud/models/DescribeApisWithStageNameIntegratedByAppResponseBodyAppApiRelationInfosAppApiRelationInfo.hpp>
#include <alibabacloud/models/DescribeApisWithStageNameIntegratedByAppResponseBodyAppApiRelationInfos.hpp>
#include <alibabacloud/models/DescribeAppAttributesRequestTag.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponseBodyAppsAppAttributeTagsTagInfo.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponseBodyAppsAppAttributeTags.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponseBodyAppsAppAttribute.hpp>
#include <alibabacloud/models/DescribeAppAttributesResponseBodyApps.hpp>
#include <alibabacloud/models/DescribeAppSecuritiesResponseBodyAppSecuritysAppSecurity.hpp>
#include <alibabacloud/models/DescribeAppSecuritiesResponseBodyAppSecuritys.hpp>
#include <alibabacloud/models/DescribeAppSecurityRequestTag.hpp>
#include <alibabacloud/models/DescribeAppsResponseBodyAppsAppItem.hpp>
#include <alibabacloud/models/DescribeAppsResponseBodyApps.hpp>
#include <alibabacloud/models/DescribeAppsByApiProductResponseBodyAuthorizedAppsAuthorizedApp.hpp>
#include <alibabacloud/models/DescribeAppsByApiProductResponseBodyAuthorizedApps.hpp>
#include <alibabacloud/models/DescribeAuthorizedApisResponseBodyAuthorizedApisAuthorizedApi.hpp>
#include <alibabacloud/models/DescribeAuthorizedApisResponseBodyAuthorizedApis.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponseBodyAuthorizedAppsAuthorizedAppTagTagInfo.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponseBodyAuthorizedAppsAuthorizedAppTag.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponseBodyAuthorizedAppsAuthorizedApp.hpp>
#include <alibabacloud/models/DescribeAuthorizedAppsResponseBodyAuthorizedApps.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigDiscoveryConfigNacosConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigDiscoveryConfigZookeeperConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigDiscoveryConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigEdasConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigEventBridgeConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigFunctionComputeConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigMockConfigMockHeaders.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigMockConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigOssConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfigVpcConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModelsBackendConfig.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfoBackendModels.hpp>
#include <alibabacloud/models/DescribeBackendInfoResponseBodyBackendInfo.hpp>
#include <alibabacloud/models/DescribeBackendListRequestTag.hpp>
#include <alibabacloud/models/DescribeBackendListResponseBodyBackendInfoListTags.hpp>
#include <alibabacloud/models/DescribeBackendListResponseBodyBackendInfoList.hpp>
#include <alibabacloud/models/DescribeDatasetInfoResponseBodyDatasetInfo.hpp>
#include <alibabacloud/models/DescribeDatasetItemInfoResponseBodyDatasetItemInfo.hpp>
#include <alibabacloud/models/DescribeDatasetItemListResponseBodyDatasetItemInfoList.hpp>
#include <alibabacloud/models/DescribeDatasetListRequestTag.hpp>
#include <alibabacloud/models/DescribeDatasetListResponseBodyDatasetInfoListTags.hpp>
#include <alibabacloud/models/DescribeDatasetListResponseBodyDatasetInfoList.hpp>
#include <alibabacloud/models/DescribeDeployApiTaskResponseBodyDeployedResultsDeployedResult.hpp>
#include <alibabacloud/models/DescribeDeployApiTaskResponseBodyDeployedResults.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyConstantParametersConstantParameter.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyConstantParameters.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyCustomSystemParametersCustomSystemParameter.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyCustomSystemParameters.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyErrorCodeSamplesErrorCodeSample.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyErrorCodeSamples.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyOpenIdConnectConfig.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyRequestConfig.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyRequestParametersRequestParameter.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyRequestParameters.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyResultDescriptionsResultDescription.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyResultDescriptions.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceConfigFunctionComputeConfig.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceConfigMockHeadersMockHeader.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceConfigMockHeaders.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceConfigVpcConfig.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceConfig.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceParametersServiceParameter.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceParameters.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceParametersMapServiceParameterMap.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodyServiceParametersMap.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodySystemParametersSystemParameter.hpp>
#include <alibabacloud/models/DescribeDeployedApiResponseBodySystemParameters.hpp>
#include <alibabacloud/models/DescribeDeployedApisRequestTag.hpp>
#include <alibabacloud/models/DescribeDeployedApisResponseBodyDeployedApisDeployedApiItem.hpp>
#include <alibabacloud/models/DescribeDeployedApisResponseBodyDeployedApis.hpp>
#include <alibabacloud/models/DescribeGroupLatencyResponseBodyLatencyPacketMonitorItem.hpp>
#include <alibabacloud/models/DescribeGroupLatencyResponseBodyLatencyPacket.hpp>
#include <alibabacloud/models/DescribeGroupQpsResponseBodyGroupQpsMonitorItem.hpp>
#include <alibabacloud/models/DescribeGroupQpsResponseBodyGroupQps.hpp>
#include <alibabacloud/models/DescribeGroupTrafficResponseBodyTrafficPerSecondMonitorItem.hpp>
#include <alibabacloud/models/DescribeGroupTrafficResponseBodyTrafficPerSecond.hpp>
#include <alibabacloud/models/DescribeHistoryApisResponseBodyApiHisItemsApiHisItem.hpp>
#include <alibabacloud/models/DescribeHistoryApisResponseBodyApiHisItems.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponseBodyApiResultsApiResult.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponseBodyApiResults.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponseBodyModelResultsModelResult.hpp>
#include <alibabacloud/models/DescribeImportOasTaskResponseBodyModelResults.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoResponseBodyInstanceClusterAttribute.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoResponseBodyInstanceListInstance.hpp>
#include <alibabacloud/models/DescribeInstanceClusterInfoResponseBodyInstanceList.hpp>
#include <alibabacloud/models/DescribeInstanceClusterListResponseBodyInstanceClustersInstanceCluster.hpp>
#include <alibabacloud/models/DescribeInstanceClusterListResponseBodyInstanceClusters.hpp>
#include <alibabacloud/models/DescribeInstanceDropConnectionsResponseBodyInstanceDropConnectionsMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceDropConnectionsResponseBodyInstanceDropConnections.hpp>
#include <alibabacloud/models/DescribeInstanceDropPacketResponseBodyInstanceDropPacketMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceDropPacketResponseBodyInstanceDropPacket.hpp>
#include <alibabacloud/models/DescribeInstanceHttpCodeResponseBodyInstanceHttpCodeMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceHttpCodeResponseBodyInstanceHttpCode.hpp>
#include <alibabacloud/models/DescribeInstanceLatencyResponseBodyInstanceLatencyMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceLatencyResponseBodyInstanceLatency.hpp>
#include <alibabacloud/models/DescribeInstanceNewConnectionsResponseBodyInstanceNewConnectionsMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceNewConnectionsResponseBodyInstanceNewConnections.hpp>
#include <alibabacloud/models/DescribeInstancePacketsResponseBodyInstancePacketsMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstancePacketsResponseBodyInstancePackets.hpp>
#include <alibabacloud/models/DescribeInstanceQpsResponseBodyInstanceQpsMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceQpsResponseBodyInstanceQps.hpp>
#include <alibabacloud/models/DescribeInstanceSlbConnectResponseBodyInstanceSlbConnectMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceSlbConnectResponseBodyInstanceSlbConnect.hpp>
#include <alibabacloud/models/DescribeInstanceTrafficResponseBodyInstanceTrafficMonitorItem.hpp>
#include <alibabacloud/models/DescribeInstanceTrafficResponseBodyInstanceTraffic.hpp>
#include <alibabacloud/models/DescribeInstancesRequestTag.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeInstanceSpecAttributesSpecAttribute.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeInstanceSpecAttributes.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeNetworkInterfaceAttributesNetworkInterfaceAttribute.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeNetworkInterfaceAttributes.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributePrivateDnsList.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeTagsTagInfo.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttributeTags.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstancesInstanceAttribute.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBodyInstances.hpp>
#include <alibabacloud/models/DescribeIpControlPolicyItemsResponseBodyIpControlPolicyItemsIpControlPolicyItem.hpp>
#include <alibabacloud/models/DescribeIpControlPolicyItemsResponseBodyIpControlPolicyItems.hpp>
#include <alibabacloud/models/DescribeIpControlsResponseBodyIpControlInfosIpControlInfo.hpp>
#include <alibabacloud/models/DescribeIpControlsResponseBodyIpControlInfos.hpp>
#include <alibabacloud/models/DescribeLogConfigResponseBodyLogInfosLogInfo.hpp>
#include <alibabacloud/models/DescribeLogConfigResponseBodyLogInfos.hpp>
#include <alibabacloud/models/DescribeModelsRequestTag.hpp>
#include <alibabacloud/models/DescribeModelsResponseBodyModelDetailsModelDetailTagsTagInfo.hpp>
#include <alibabacloud/models/DescribeModelsResponseBodyModelDetailsModelDetailTags.hpp>
#include <alibabacloud/models/DescribeModelsResponseBodyModelDetailsModelDetail.hpp>
#include <alibabacloud/models/DescribeModelsResponseBodyModelDetails.hpp>
#include <alibabacloud/models/DescribePluginApisResponseBodyApiSummarysApiPluginSummary.hpp>
#include <alibabacloud/models/DescribePluginApisResponseBodyApiSummarys.hpp>
#include <alibabacloud/models/DescribePluginGroupsResponseBodyGroupSummarysGroupPluginSummary.hpp>
#include <alibabacloud/models/DescribePluginGroupsResponseBodyGroupSummarys.hpp>
#include <alibabacloud/models/DescribePluginSchemasResponseBodyPluginSchemasPluginSchema.hpp>
#include <alibabacloud/models/DescribePluginSchemasResponseBodyPluginSchemas.hpp>
#include <alibabacloud/models/DescribePluginTemplatesResponseBodyTemplatesTemplate.hpp>
#include <alibabacloud/models/DescribePluginTemplatesResponseBodyTemplates.hpp>
#include <alibabacloud/models/DescribePluginsRequestTag.hpp>
#include <alibabacloud/models/DescribePluginsResponseBodyPluginsPluginAttributeTagsTagInfo.hpp>
#include <alibabacloud/models/DescribePluginsResponseBodyPluginsPluginAttributeTags.hpp>
#include <alibabacloud/models/DescribePluginsResponseBodyPluginsPluginAttribute.hpp>
#include <alibabacloud/models/DescribePluginsResponseBodyPlugins.hpp>
#include <alibabacloud/models/DescribePluginsByApiResponseBodyPluginsPluginAttribute.hpp>
#include <alibabacloud/models/DescribePluginsByApiResponseBodyPlugins.hpp>
#include <alibabacloud/models/DescribePluginsByGroupResponseBodyPluginsPluginAttribute.hpp>
#include <alibabacloud/models/DescribePluginsByGroupResponseBodyPlugins.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupResponseBodyDomainsDomainItem.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupResponseBodyDomains.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupsResponseBodyPurchasedApiGroupAttributesPurchasedApiGroupAttribute.hpp>
#include <alibabacloud/models/DescribePurchasedApiGroupsResponseBodyPurchasedApiGroupAttributes.hpp>
#include <alibabacloud/models/DescribePurchasedApisResponseBodyPurchasedApisPurchasedApi.hpp>
#include <alibabacloud/models/DescribePurchasedApisResponseBodyPurchasedApis.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeSignaturesResponseBodySignatureInfosSignatureInfo.hpp>
#include <alibabacloud/models/DescribeSignaturesResponseBodySignatureInfos.hpp>
#include <alibabacloud/models/DescribeSignaturesByApiResponseBodySignaturesSignatureItem.hpp>
#include <alibabacloud/models/DescribeSignaturesByApiResponseBodySignatures.hpp>
#include <alibabacloud/models/DescribeSystemParametersResponseBodySystemParamsSystemParamItem.hpp>
#include <alibabacloud/models/DescribeSystemParametersResponseBodySystemParams.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControlsTrafficControlSpecialPoliciesSpecialPolicySpecialsSpecial.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControlsTrafficControlSpecialPoliciesSpecialPolicySpecials.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControlsTrafficControlSpecialPoliciesSpecialPolicy.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControlsTrafficControlSpecialPolicies.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControlsTrafficControl.hpp>
#include <alibabacloud/models/DescribeTrafficControlsResponseBodyTrafficControls.hpp>
#include <alibabacloud/models/DescribeTrafficControlsByApiResponseBodyTrafficControlItemsTrafficControlItem.hpp>
#include <alibabacloud/models/DescribeTrafficControlsByApiResponseBodyTrafficControlItems.hpp>
#include <alibabacloud/models/DescribeUpdateBackendTaskResponseBodyApiUpdateBackendResultsApiUpdateBackendResult.hpp>
#include <alibabacloud/models/DescribeUpdateBackendTaskResponseBodyApiUpdateBackendResults.hpp>
#include <alibabacloud/models/DescribeUpdateVpcInfoTaskResponseBodyApiUpdateVpcInfoResultsApiUpdateVpcInfoResult.hpp>
#include <alibabacloud/models/DescribeUpdateVpcInfoTaskResponseBodyApiUpdateVpcInfoResults.hpp>
#include <alibabacloud/models/DescribeVpcAccessesRequestTag.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponseBodyVpcAccessAttributesVpcAccessAttributeTagsTagInfo.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponseBodyVpcAccessAttributesVpcAccessAttributeTags.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponseBodyVpcAccessAttributesVpcAccessAttribute.hpp>
#include <alibabacloud/models/DescribeVpcAccessesResponseBodyVpcAccessAttributes.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZonesZone.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZones.hpp>
#include <alibabacloud/models/DetachApiProductRequestApis.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyFailedApiImportSwaggerFailed.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyFailed.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyModelFailedApiImportModelFailed.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyModelFailed.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyModelSuccessApiImportModelSuccess.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodyModelSuccess.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodySuccessApiDryRunSwaggerSuccess.hpp>
#include <alibabacloud/models/DryRunSwaggerResponseBodySuccess.hpp>
#include <alibabacloud/models/ImportOasResponseBodyErrorMessages.hpp>
#include <alibabacloud/models/ImportOasResponseBodyFailedApisFailedApi.hpp>
#include <alibabacloud/models/ImportOasResponseBodyFailedApis.hpp>
#include <alibabacloud/models/ImportOasResponseBodyFailedModelsFailedModel.hpp>
#include <alibabacloud/models/ImportOasResponseBodyFailedModels.hpp>
#include <alibabacloud/models/ImportOasResponseBodySuccessApisSuccessApi.hpp>
#include <alibabacloud/models/ImportOasResponseBodySuccessApis.hpp>
#include <alibabacloud/models/ImportOasResponseBodySuccessModelsSuccessModel.hpp>
#include <alibabacloud/models/ImportOasResponseBodySuccessModels.hpp>
#include <alibabacloud/models/ImportOasResponseBodyWarningMessages.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyFailedApiImportSwaggerFailed.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyFailed.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyModelFailedApiImportModelFailed.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyModelFailed.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyModelSuccessApiImportModelSuccess.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodyModelSuccess.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodySuccessApiImportSwaggerSuccess.hpp>
#include <alibabacloud/models/ImportSwaggerResponseBodySuccess.hpp>
#include <alibabacloud/models/ListPrivateDnsResponseBodyPrivateDnsListRecords.hpp>
#include <alibabacloud/models/ListPrivateDnsResponseBodyPrivateDnsList.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResourcesTagResource.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyApiGroupRequestTag.hpp>
#include <alibabacloud/models/ModifyApiGroupInstanceRequestTag.hpp>
#include <alibabacloud/models/ModifyAppRequestTag.hpp>
#include <alibabacloud/models/ModifyInstanceAttributeRequestToConnectVpcIpBlock.hpp>
#include <alibabacloud/models/ModifyPluginRequestTag.hpp>
#include <alibabacloud/models/QueryRequestLogsResponseBodyRequestLogsRequestLog.hpp>
#include <alibabacloud/models/QueryRequestLogsResponseBodyRequestLogs.hpp>
#include <alibabacloud/models/RemoveVpcAccessResponseBodyApisApi.hpp>
#include <alibabacloud/models/RemoveVpcAccessResponseBodyApis.hpp>
#include <alibabacloud/models/SetVpcAccessRequestTag.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>
#include <alibabacloud/models/UpdatePrivateDnsRequestRecords.hpp>

#endif
