// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_FOASCONSOLE20190601MODEL_HPP_
#define ALIBABACLOUD_FOASCONSOLE20190601MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/ConvertInstanceRequest.hpp>
#include <alibabacloud/models/ConvertInstanceResponseBody.hpp>
#include <alibabacloud/models/ConvertInstanceResponse.hpp>
#include <alibabacloud/models/ConvertPrepayInstanceRequest.hpp>
#include <alibabacloud/models/ConvertPrepayInstanceResponseBody.hpp>
#include <alibabacloud/models/ConvertPrepayInstanceResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateNamespaceRequest.hpp>
#include <alibabacloud/models/CreateNamespaceResponseBody.hpp>
#include <alibabacloud/models/CreateNamespaceResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteNamespaceRequest.hpp>
#include <alibabacloud/models/DeleteNamespaceResponseBody.hpp>
#include <alibabacloud/models/DeleteNamespaceResponse.hpp>
#include <alibabacloud/models/DescribeInstancesRequest.hpp>
#include <alibabacloud/models/DescribeInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeInstancesResponse.hpp>
#include <alibabacloud/models/DescribeNamespacesRequest.hpp>
#include <alibabacloud/models/DescribeNamespacesResponseBody.hpp>
#include <alibabacloud/models/DescribeNamespacesResponse.hpp>
#include <alibabacloud/models/DescribeSupportedRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeSupportedRegionsResponse.hpp>
#include <alibabacloud/models/DescribeSupportedZonesRequest.hpp>
#include <alibabacloud/models/DescribeSupportedZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeSupportedZonesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyPrepayInstanceSpecRequest.hpp>
#include <alibabacloud/models/ModifyPrepayInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyPrepayInstanceSpecResponse.hpp>
#include <alibabacloud/models/ModifyPrepayNamespaceSpecRequest.hpp>
#include <alibabacloud/models/ModifyPrepayNamespaceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyPrepayNamespaceSpecResponse.hpp>
#include <alibabacloud/models/QueryConvertInstancePriceRequest.hpp>
#include <alibabacloud/models/QueryConvertInstancePriceResponseBody.hpp>
#include <alibabacloud/models/QueryConvertInstancePriceResponse.hpp>
#include <alibabacloud/models/QueryConvertPrepayInstancePriceRequest.hpp>
#include <alibabacloud/models/QueryConvertPrepayInstancePriceResponseBody.hpp>
#include <alibabacloud/models/QueryConvertPrepayInstancePriceResponse.hpp>
#include <alibabacloud/models/QueryCreateInstancePriceRequest.hpp>
#include <alibabacloud/models/QueryCreateInstancePriceResponseBody.hpp>
#include <alibabacloud/models/QueryCreateInstancePriceResponse.hpp>
#include <alibabacloud/models/QueryModifyInstancePriceRequest.hpp>
#include <alibabacloud/models/QueryModifyInstancePriceResponseBody.hpp>
#include <alibabacloud/models/QueryModifyInstancePriceResponse.hpp>
#include <alibabacloud/models/QueryRenewInstancePriceRequest.hpp>
#include <alibabacloud/models/QueryRenewInstancePriceResponseBody.hpp>
#include <alibabacloud/models/QueryRenewInstancePriceResponse.hpp>
#include <alibabacloud/models/RenewInstanceRequest.hpp>
#include <alibabacloud/models/RenewInstanceResponseBody.hpp>
#include <alibabacloud/models/RenewInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>

#endif
