// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CLICKHOUSE20230522MODEL_HPP_
#define ALIBABACLOUD_CLICKHOUSE20230522MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateAccountRequest.hpp>
#include <alibabacloud/models/CreateAccountShrinkRequest.hpp>
#include <alibabacloud/models/CreateAccountResponseBody.hpp>
#include <alibabacloud/models/CreateAccountResponse.hpp>
#include <alibabacloud/models/CreateBackupPolicyRequest.hpp>
#include <alibabacloud/models/CreateBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/CreateBackupPolicyResponse.hpp>
#include <alibabacloud/models/CreateDbrequest.hpp>
#include <alibabacloud/models/CreateDbresponseBody.hpp>
#include <alibabacloud/models/CreateDbresponse.hpp>
#include <alibabacloud/models/CreateDbinstanceRequest.hpp>
#include <alibabacloud/models/CreateDbinstanceShrinkRequest.hpp>
#include <alibabacloud/models/CreateDbinstanceResponseBody.hpp>
#include <alibabacloud/models/CreateDbinstanceResponse.hpp>
#include <alibabacloud/models/CreateEndpointRequest.hpp>
#include <alibabacloud/models/CreateEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateEndpointResponse.hpp>
#include <alibabacloud/models/DeleteAccountRequest.hpp>
#include <alibabacloud/models/DeleteAccountResponseBody.hpp>
#include <alibabacloud/models/DeleteAccountResponse.hpp>
#include <alibabacloud/models/DeleteBackupPolicyRequest.hpp>
#include <alibabacloud/models/DeleteBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupPolicyResponse.hpp>
#include <alibabacloud/models/DeleteDbrequest.hpp>
#include <alibabacloud/models/DeleteDbresponseBody.hpp>
#include <alibabacloud/models/DeleteDbresponse.hpp>
#include <alibabacloud/models/DeleteDbinstanceRequest.hpp>
#include <alibabacloud/models/DeleteDbinstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteDbinstanceResponse.hpp>
#include <alibabacloud/models/DeleteEndpointRequest.hpp>
#include <alibabacloud/models/DeleteEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteEndpointResponse.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityRequest.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityResponse.hpp>
#include <alibabacloud/models/DescribeAccountsRequest.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccountsResponse.hpp>
#include <alibabacloud/models/DescribeBackupPolicyRequest.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPolicyResponse.hpp>
#include <alibabacloud/models/DescribeBackupsRequest.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupsResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigChangeLogRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigChangeLogResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigChangeLogResponse.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSourcesRequest.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSourcesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSourcesResponse.hpp>
#include <alibabacloud/models/DescribeDbinstancesRequest.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponse.hpp>
#include <alibabacloud/models/DescribeEndpointsRequest.hpp>
#include <alibabacloud/models/DescribeEndpointsResponseBody.hpp>
#include <alibabacloud/models/DescribeEndpointsResponse.hpp>
#include <alibabacloud/models/DescribeProcessListRequest.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBody.hpp>
#include <alibabacloud/models/DescribeProcessListResponse.hpp>
#include <alibabacloud/models/DescribeSecurityIplistRequest.hpp>
#include <alibabacloud/models/DescribeSecurityIplistResponseBody.hpp>
#include <alibabacloud/models/DescribeSecurityIplistResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponse.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendRequest.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBody.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponse.hpp>
#include <alibabacloud/models/KillProcessRequest.hpp>
#include <alibabacloud/models/KillProcessResponseBody.hpp>
#include <alibabacloud/models/KillProcessResponse.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityRequest.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityResponse.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionRequest.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBody.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponse.hpp>
#include <alibabacloud/models/ModifyBackupPolicyRequest.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponseBody.hpp>
#include <alibabacloud/models/ModifyBackupPolicyResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceClassRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceClassResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceClassResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigResponse.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringRequest.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringResponseBody.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringResponse.hpp>
#include <alibabacloud/models/ModifySecurityIplistRequest.hpp>
#include <alibabacloud/models/ModifySecurityIplistResponseBody.hpp>
#include <alibabacloud/models/ModifySecurityIplistResponse.hpp>
#include <alibabacloud/models/ResetAccountPasswordRequest.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBody.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponse.hpp>
#include <alibabacloud/models/RestartDbinstanceRequest.hpp>
#include <alibabacloud/models/RestartDbinstanceResponseBody.hpp>
#include <alibabacloud/models/RestartDbinstanceResponse.hpp>
#include <alibabacloud/models/StartDbinstanceRequest.hpp>
#include <alibabacloud/models/StartDbinstanceResponseBody.hpp>
#include <alibabacloud/models/StartDbinstanceResponse.hpp>
#include <alibabacloud/models/StopDbinstanceRequest.hpp>
#include <alibabacloud/models/StopDbinstanceResponseBody.hpp>
#include <alibabacloud/models/StopDbinstanceResponse.hpp>
#include <alibabacloud/models/UpgradeMinorVersionRequest.hpp>
#include <alibabacloud/models/UpgradeMinorVersionResponseBody.hpp>
#include <alibabacloud/models/UpgradeMinorVersionResponse.hpp>
#include <alibabacloud/models/CreateAccountRequestDmlAuthSetting.hpp>
#include <alibabacloud/models/CreateAccountResponseBodyData.hpp>
#include <alibabacloud/models/CreateDbresponseBodyData.hpp>
#include <alibabacloud/models/CreateDbinstanceRequestMultiZone.hpp>
#include <alibabacloud/models/CreateDbinstanceResponseBodyData.hpp>
#include <alibabacloud/models/DeleteAccountResponseBodyData.hpp>
#include <alibabacloud/models/DeleteDbresponseBodyData.hpp>
#include <alibabacloud/models/DeleteDbinstanceResponseBodyData.hpp>
#include <alibabacloud/models/DescribeAccountAuthorityResponseBodyData.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyDataAccounts.hpp>
#include <alibabacloud/models/DescribeAccountsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeBackupsResponseBodyItems.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyDataMultiZones.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyDataNodes.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyDataTags.hpp>
#include <alibabacloud/models/DescribeDbinstanceAttributeResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigResponseBodyDataParams.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigChangeLogResponseBodyDataParamChangeLogs.hpp>
#include <alibabacloud/models/DescribeDbinstanceConfigChangeLogResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSourcesResponseBodyDataColumns.hpp>
#include <alibabacloud/models/DescribeDbinstanceDataSourcesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyDataDbinstancesTags.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyDataDbinstances.hpp>
#include <alibabacloud/models/DescribeDbinstancesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeEndpointsResponseBodyDataEndpointsPorts.hpp>
#include <alibabacloud/models/DescribeEndpointsResponseBodyDataEndpoints.hpp>
#include <alibabacloud/models/DescribeEndpointsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyDataResultSet.hpp>
#include <alibabacloud/models/DescribeProcessListResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSecurityIplistResponseBodyDataGroupItems.hpp>
#include <alibabacloud/models/DescribeSecurityIplistResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyDataResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogRecordsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodyDataResultSet.hpp>
#include <alibabacloud/models/DescribeSlowLogTrendResponseBodyData.hpp>
#include <alibabacloud/models/KillProcessResponseBodyData.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityRequestDmlAuthSetting.hpp>
#include <alibabacloud/models/ModifyAccountAuthorityResponseBodyData.hpp>
#include <alibabacloud/models/ModifyAccountDescriptionResponseBodyData.hpp>
#include <alibabacloud/models/ModifyDbinstanceClassResponseBodyData.hpp>
#include <alibabacloud/models/ModifyDbinstanceConfigResponseBodyData.hpp>
#include <alibabacloud/models/ModifyDbinstanceConnectionStringResponseBodyData.hpp>
#include <alibabacloud/models/ModifySecurityIplistResponseBodyData.hpp>
#include <alibabacloud/models/ResetAccountPasswordResponseBodyData.hpp>
#include <alibabacloud/models/RestartDbinstanceResponseBodyData.hpp>
#include <alibabacloud/models/StartDbinstanceResponseBodyData.hpp>
#include <alibabacloud/models/StopDbinstanceResponseBodyData.hpp>
#include <alibabacloud/models/UpgradeMinorVersionResponseBodyData.hpp>

#endif
