// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_IQS20241111MODEL_HPP_
#define ALIBABACLOUD_IQS20241111MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AiSearchQuery.hpp>
#include <alibabacloud/models/IncludeImage.hpp>
#include <alibabacloud/models/ScorePageItem.hpp>
#include <alibabacloud/models/QueryContext.hpp>
#include <alibabacloud/models/SceneItem.hpp>
#include <alibabacloud/models/SearchInformation.hpp>
#include <alibabacloud/models/WeiboItem.hpp>
#include <alibabacloud/models/GenericSearchResult.hpp>
#include <alibabacloud/models/GetIqsUsageResult.hpp>
#include <alibabacloud/models/GlobalPageItem.hpp>
#include <alibabacloud/models/GlobalQueryContext.hpp>
#include <alibabacloud/models/GlobalSceneItem.hpp>
#include <alibabacloud/models/GlobalSearchInformation.hpp>
#include <alibabacloud/models/GlobalSearchResult.hpp>
#include <alibabacloud/models/ReadPageBody.hpp>
#include <alibabacloud/models/ReadPageItem.hpp>
#include <alibabacloud/models/ReadPageScrapeBody.hpp>
#include <alibabacloud/models/RequestContents.hpp>
#include <alibabacloud/models/SearchCredits.hpp>
#include <alibabacloud/models/ValueAddedCredits.hpp>
#include <alibabacloud/models/UnifiedCostCredits.hpp>
#include <alibabacloud/models/UnifiedOriginalQuery.hpp>
#include <alibabacloud/models/UnifiedPageItem.hpp>
#include <alibabacloud/models/UnifiedRewrite.hpp>
#include <alibabacloud/models/UnifiedQueryContext.hpp>
#include <alibabacloud/models/UnifiedSceneItem.hpp>
#include <alibabacloud/models/UnifiedSearchInformation.hpp>
#include <alibabacloud/models/UnifiedSearchInput.hpp>
#include <alibabacloud/models/UnifiedSearchOutput.hpp>
#include <alibabacloud/models/AiSearchRequest.hpp>
#include <alibabacloud/models/AiSearchResponseBody.hpp>
#include <alibabacloud/models/AiSearchResponse.hpp>
#include <alibabacloud/models/GenericAdvancedSearchRequest.hpp>
#include <alibabacloud/models/GenericAdvancedSearchResponse.hpp>
#include <alibabacloud/models/GenericSearchRequest.hpp>
#include <alibabacloud/models/GenericSearchShrinkRequest.hpp>
#include <alibabacloud/models/GenericSearchResponse.hpp>
#include <alibabacloud/models/GetIqsUsageRequest.hpp>
#include <alibabacloud/models/GetIqsUsageResponse.hpp>
#include <alibabacloud/models/GlobalSearchRequest.hpp>
#include <alibabacloud/models/GlobalSearchResponse.hpp>
#include <alibabacloud/models/ReadPageBasicRequest.hpp>
#include <alibabacloud/models/ReadPageBasicResponseBody.hpp>
#include <alibabacloud/models/ReadPageBasicResponse.hpp>
#include <alibabacloud/models/ReadPageScrapeRequest.hpp>
#include <alibabacloud/models/ReadPageScrapeResponseBody.hpp>
#include <alibabacloud/models/ReadPageScrapeResponse.hpp>
#include <alibabacloud/models/UnifiedSearchRequest.hpp>
#include <alibabacloud/models/UnifiedSearchResponse.hpp>
#include <alibabacloud/models/GetIqsUsageResultRecords.hpp>
#include <alibabacloud/models/GlobalQueryContextOriginalQuery.hpp>
#include <alibabacloud/models/QueryContextOriginalQuery.hpp>
#include <alibabacloud/models/QueryContextRewrite.hpp>
#include <alibabacloud/models/ReadPageBodyReadability.hpp>
#include <alibabacloud/models/ReadPageScrapeBodyReadability.hpp>
#include <alibabacloud/models/AiSearchResponseBodyHeaderQueryContextOriginalQuery.hpp>
#include <alibabacloud/models/AiSearchResponseBodyHeaderQueryContextRewrite.hpp>
#include <alibabacloud/models/AiSearchResponseBodyHeaderQueryContext.hpp>
#include <alibabacloud/models/AiSearchResponseBodyHeader.hpp>

#endif
