// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_VPC20160428MODEL_HPP_
#define ALIBABACLOUD_VPC20160428MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ActivateRouterInterfaceRequest.hpp>
#include <alibabacloud/models/ActivateRouterInterfaceResponseBody.hpp>
#include <alibabacloud/models/ActivateRouterInterfaceResponse.hpp>
#include <alibabacloud/models/ActiveFlowLogRequest.hpp>
#include <alibabacloud/models/ActiveFlowLogResponseBody.hpp>
#include <alibabacloud/models/ActiveFlowLogResponse.hpp>
#include <alibabacloud/models/AddBgpNetworkRequest.hpp>
#include <alibabacloud/models/AddBgpNetworkResponseBody.hpp>
#include <alibabacloud/models/AddBgpNetworkResponse.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpRequest.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpResponseBody.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpResponse.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpsRequest.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpsResponseBody.hpp>
#include <alibabacloud/models/AddCommonBandwidthPackageIpsResponse.hpp>
#include <alibabacloud/models/AddGlobalAccelerationInstanceIpRequest.hpp>
#include <alibabacloud/models/AddGlobalAccelerationInstanceIpResponseBody.hpp>
#include <alibabacloud/models/AddGlobalAccelerationInstanceIpResponse.hpp>
#include <alibabacloud/models/AddIPv6TranslatorAclListEntryRequest.hpp>
#include <alibabacloud/models/AddIPv6TranslatorAclListEntryResponseBody.hpp>
#include <alibabacloud/models/AddIPv6TranslatorAclListEntryResponse.hpp>
#include <alibabacloud/models/AddPublicIpAddressPoolCidrBlockRequest.hpp>
#include <alibabacloud/models/AddPublicIpAddressPoolCidrBlockResponseBody.hpp>
#include <alibabacloud/models/AddPublicIpAddressPoolCidrBlockResponse.hpp>
#include <alibabacloud/models/AddSourcesToTrafficMirrorSessionRequest.hpp>
#include <alibabacloud/models/AddSourcesToTrafficMirrorSessionResponseBody.hpp>
#include <alibabacloud/models/AddSourcesToTrafficMirrorSessionResponse.hpp>
#include <alibabacloud/models/AllocateEipAddressRequest.hpp>
#include <alibabacloud/models/AllocateEipAddressResponseBody.hpp>
#include <alibabacloud/models/AllocateEipAddressResponse.hpp>
#include <alibabacloud/models/AllocateEipAddressProRequest.hpp>
#include <alibabacloud/models/AllocateEipAddressProResponseBody.hpp>
#include <alibabacloud/models/AllocateEipAddressProResponse.hpp>
#include <alibabacloud/models/AllocateEipSegmentAddressRequest.hpp>
#include <alibabacloud/models/AllocateEipSegmentAddressResponseBody.hpp>
#include <alibabacloud/models/AllocateEipSegmentAddressResponse.hpp>
#include <alibabacloud/models/AllocateIpv6AddressRequest.hpp>
#include <alibabacloud/models/AllocateIpv6AddressResponseBody.hpp>
#include <alibabacloud/models/AllocateIpv6AddressResponse.hpp>
#include <alibabacloud/models/AllocateIpv6InternetBandwidthRequest.hpp>
#include <alibabacloud/models/AllocateIpv6InternetBandwidthResponseBody.hpp>
#include <alibabacloud/models/AllocateIpv6InternetBandwidthResponse.hpp>
#include <alibabacloud/models/AllocateVpcIpv6CidrRequest.hpp>
#include <alibabacloud/models/AllocateVpcIpv6CidrResponseBody.hpp>
#include <alibabacloud/models/AllocateVpcIpv6CidrResponse.hpp>
#include <alibabacloud/models/ApplyPhysicalConnectionLoaRequest.hpp>
#include <alibabacloud/models/ApplyPhysicalConnectionLoaResponseBody.hpp>
#include <alibabacloud/models/ApplyPhysicalConnectionLoaResponse.hpp>
#include <alibabacloud/models/AssociateEipAddressRequest.hpp>
#include <alibabacloud/models/AssociateEipAddressResponseBody.hpp>
#include <alibabacloud/models/AssociateEipAddressResponse.hpp>
#include <alibabacloud/models/AssociateEipAddressBatchRequest.hpp>
#include <alibabacloud/models/AssociateEipAddressBatchResponseBody.hpp>
#include <alibabacloud/models/AssociateEipAddressBatchResponse.hpp>
#include <alibabacloud/models/AssociateHaVipRequest.hpp>
#include <alibabacloud/models/AssociateHaVipResponseBody.hpp>
#include <alibabacloud/models/AssociateHaVipResponse.hpp>
#include <alibabacloud/models/AssociateNetworkAclRequest.hpp>
#include <alibabacloud/models/AssociateNetworkAclResponseBody.hpp>
#include <alibabacloud/models/AssociateNetworkAclResponse.hpp>
#include <alibabacloud/models/AssociatePhysicalConnectionToVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/AssociatePhysicalConnectionToVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/AssociatePhysicalConnectionToVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/AssociateRouteTableRequest.hpp>
#include <alibabacloud/models/AssociateRouteTableResponseBody.hpp>
#include <alibabacloud/models/AssociateRouteTableResponse.hpp>
#include <alibabacloud/models/AssociateRouteTableWithGatewayRequest.hpp>
#include <alibabacloud/models/AssociateRouteTableWithGatewayResponseBody.hpp>
#include <alibabacloud/models/AssociateRouteTableWithGatewayResponse.hpp>
#include <alibabacloud/models/AssociateRouteTablesWithVpcGatewayEndpointRequest.hpp>
#include <alibabacloud/models/AssociateRouteTablesWithVpcGatewayEndpointResponseBody.hpp>
#include <alibabacloud/models/AssociateRouteTablesWithVpcGatewayEndpointResponse.hpp>
#include <alibabacloud/models/AssociateVpcCidrBlockRequest.hpp>
#include <alibabacloud/models/AssociateVpcCidrBlockResponseBody.hpp>
#include <alibabacloud/models/AssociateVpcCidrBlockResponse.hpp>
#include <alibabacloud/models/AssociateVpnGatewayWithCertificateRequest.hpp>
#include <alibabacloud/models/AssociateVpnGatewayWithCertificateResponseBody.hpp>
#include <alibabacloud/models/AssociateVpnGatewayWithCertificateResponse.hpp>
#include <alibabacloud/models/AttachDhcpOptionsSetToVpcRequest.hpp>
#include <alibabacloud/models/AttachDhcpOptionsSetToVpcResponseBody.hpp>
#include <alibabacloud/models/AttachDhcpOptionsSetToVpcResponse.hpp>
#include <alibabacloud/models/AttachVbrToVpconnRequest.hpp>
#include <alibabacloud/models/AttachVbrToVpconnResponseBody.hpp>
#include <alibabacloud/models/AttachVbrToVpconnResponse.hpp>
#include <alibabacloud/models/CancelCommonBandwidthPackageIpBandwidthRequest.hpp>
#include <alibabacloud/models/CancelCommonBandwidthPackageIpBandwidthResponseBody.hpp>
#include <alibabacloud/models/CancelCommonBandwidthPackageIpBandwidthResponse.hpp>
#include <alibabacloud/models/CancelPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/CancelPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/CancelPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckCanAllocateVpcPrivateIpAddressRequest.hpp>
#include <alibabacloud/models/CheckCanAllocateVpcPrivateIpAddressResponseBody.hpp>
#include <alibabacloud/models/CheckCanAllocateVpcPrivateIpAddressResponse.hpp>
#include <alibabacloud/models/CheckVpnBgpEnabledRequest.hpp>
#include <alibabacloud/models/CheckVpnBgpEnabledResponseBody.hpp>
#include <alibabacloud/models/CheckVpnBgpEnabledResponse.hpp>
#include <alibabacloud/models/CompletePhysicalConnectionLoaRequest.hpp>
#include <alibabacloud/models/CompletePhysicalConnectionLoaResponseBody.hpp>
#include <alibabacloud/models/CompletePhysicalConnectionLoaResponse.hpp>
#include <alibabacloud/models/ConfirmPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/ConfirmPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/ConfirmPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/ConnectRouterInterfaceRequest.hpp>
#include <alibabacloud/models/ConnectRouterInterfaceResponseBody.hpp>
#include <alibabacloud/models/ConnectRouterInterfaceResponse.hpp>
#include <alibabacloud/models/ConvertBandwidthPackageRequest.hpp>
#include <alibabacloud/models/ConvertBandwidthPackageResponseBody.hpp>
#include <alibabacloud/models/ConvertBandwidthPackageResponse.hpp>
#include <alibabacloud/models/CopyNetworkAclEntriesRequest.hpp>
#include <alibabacloud/models/CopyNetworkAclEntriesResponseBody.hpp>
#include <alibabacloud/models/CopyNetworkAclEntriesResponse.hpp>
#include <alibabacloud/models/CreateBgpGroupRequest.hpp>
#include <alibabacloud/models/CreateBgpGroupResponseBody.hpp>
#include <alibabacloud/models/CreateBgpGroupResponse.hpp>
#include <alibabacloud/models/CreateBgpPeerRequest.hpp>
#include <alibabacloud/models/CreateBgpPeerResponseBody.hpp>
#include <alibabacloud/models/CreateBgpPeerResponse.hpp>
#include <alibabacloud/models/CreateCommonBandwidthPackageRequest.hpp>
#include <alibabacloud/models/CreateCommonBandwidthPackageResponseBody.hpp>
#include <alibabacloud/models/CreateCommonBandwidthPackageResponse.hpp>
#include <alibabacloud/models/CreateCustomerGatewayRequest.hpp>
#include <alibabacloud/models/CreateCustomerGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateCustomerGatewayResponse.hpp>
#include <alibabacloud/models/CreateDefaultVSwitchRequest.hpp>
#include <alibabacloud/models/CreateDefaultVSwitchResponseBody.hpp>
#include <alibabacloud/models/CreateDefaultVSwitchResponse.hpp>
#include <alibabacloud/models/CreateDefaultVpcRequest.hpp>
#include <alibabacloud/models/CreateDefaultVpcResponseBody.hpp>
#include <alibabacloud/models/CreateDefaultVpcResponse.hpp>
#include <alibabacloud/models/CreateDhcpOptionsSetRequest.hpp>
#include <alibabacloud/models/CreateDhcpOptionsSetResponseBody.hpp>
#include <alibabacloud/models/CreateDhcpOptionsSetResponse.hpp>
#include <alibabacloud/models/CreateExpressCloudConnectionRequest.hpp>
#include <alibabacloud/models/CreateExpressCloudConnectionResponseBody.hpp>
#include <alibabacloud/models/CreateExpressCloudConnectionResponse.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosRequest.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosResponseBody.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosResponse.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosQueueRequest.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosQueueResponseBody.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosQueueResponse.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosRuleRequest.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosRuleResponseBody.hpp>
#include <alibabacloud/models/CreateExpressConnectTrafficQosRuleResponse.hpp>
#include <alibabacloud/models/CreateFailoverTestJobRequest.hpp>
#include <alibabacloud/models/CreateFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/CreateFailoverTestJobResponse.hpp>
#include <alibabacloud/models/CreateFlowLogRequest.hpp>
#include <alibabacloud/models/CreateFlowLogResponseBody.hpp>
#include <alibabacloud/models/CreateFlowLogResponse.hpp>
#include <alibabacloud/models/CreateForwardEntryRequest.hpp>
#include <alibabacloud/models/CreateForwardEntryResponseBody.hpp>
#include <alibabacloud/models/CreateForwardEntryResponse.hpp>
#include <alibabacloud/models/CreateFullNatEntryRequest.hpp>
#include <alibabacloud/models/CreateFullNatEntryResponseBody.hpp>
#include <alibabacloud/models/CreateFullNatEntryResponse.hpp>
#include <alibabacloud/models/CreateGlobalAccelerationInstanceRequest.hpp>
#include <alibabacloud/models/CreateGlobalAccelerationInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateGlobalAccelerationInstanceResponse.hpp>
#include <alibabacloud/models/CreateHaVipRequest.hpp>
#include <alibabacloud/models/CreateHaVipResponseBody.hpp>
#include <alibabacloud/models/CreateHaVipResponse.hpp>
#include <alibabacloud/models/CreateHighReliablePhysicalConnectionRequest.hpp>
#include <alibabacloud/models/CreateHighReliablePhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/CreateHighReliablePhysicalConnectionResponse.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorRequest.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorResponseBody.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorResponse.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorAclListRequest.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorAclListResponseBody.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorAclListResponse.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorEntryRequest.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorEntryResponseBody.hpp>
#include <alibabacloud/models/CreateIPv6TranslatorEntryResponse.hpp>
#include <alibabacloud/models/CreateIpsecServerRequest.hpp>
#include <alibabacloud/models/CreateIpsecServerResponseBody.hpp>
#include <alibabacloud/models/CreateIpsecServerResponse.hpp>
#include <alibabacloud/models/CreateIpv4GatewayRequest.hpp>
#include <alibabacloud/models/CreateIpv4GatewayResponseBody.hpp>
#include <alibabacloud/models/CreateIpv4GatewayResponse.hpp>
#include <alibabacloud/models/CreateIpv6EgressOnlyRuleRequest.hpp>
#include <alibabacloud/models/CreateIpv6EgressOnlyRuleResponseBody.hpp>
#include <alibabacloud/models/CreateIpv6EgressOnlyRuleResponse.hpp>
#include <alibabacloud/models/CreateIpv6GatewayRequest.hpp>
#include <alibabacloud/models/CreateIpv6GatewayResponseBody.hpp>
#include <alibabacloud/models/CreateIpv6GatewayResponse.hpp>
#include <alibabacloud/models/CreateNatGatewayRequest.hpp>
#include <alibabacloud/models/CreateNatGatewayShrinkRequest.hpp>
#include <alibabacloud/models/CreateNatGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateNatGatewayResponse.hpp>
#include <alibabacloud/models/CreateNatIpRequest.hpp>
#include <alibabacloud/models/CreateNatIpResponseBody.hpp>
#include <alibabacloud/models/CreateNatIpResponse.hpp>
#include <alibabacloud/models/CreateNatIpCidrRequest.hpp>
#include <alibabacloud/models/CreateNatIpCidrResponseBody.hpp>
#include <alibabacloud/models/CreateNatIpCidrResponse.hpp>
#include <alibabacloud/models/CreateNetworkAclRequest.hpp>
#include <alibabacloud/models/CreateNetworkAclResponseBody.hpp>
#include <alibabacloud/models/CreateNetworkAclResponse.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionRequest.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionResponse.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionOccupancyOrderRequest.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionOccupancyOrderResponseBody.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionOccupancyOrderResponse.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionSetupOrderRequest.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionSetupOrderResponseBody.hpp>
#include <alibabacloud/models/CreatePhysicalConnectionSetupOrderResponse.hpp>
#include <alibabacloud/models/CreatePublicIpAddressPoolRequest.hpp>
#include <alibabacloud/models/CreatePublicIpAddressPoolResponseBody.hpp>
#include <alibabacloud/models/CreatePublicIpAddressPoolResponse.hpp>
#include <alibabacloud/models/CreateRouteEntriesRequest.hpp>
#include <alibabacloud/models/CreateRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/CreateRouteEntriesResponse.hpp>
#include <alibabacloud/models/CreateRouteEntryRequest.hpp>
#include <alibabacloud/models/CreateRouteEntryResponseBody.hpp>
#include <alibabacloud/models/CreateRouteEntryResponse.hpp>
#include <alibabacloud/models/CreateRouteTableRequest.hpp>
#include <alibabacloud/models/CreateRouteTableResponseBody.hpp>
#include <alibabacloud/models/CreateRouteTableResponse.hpp>
#include <alibabacloud/models/CreateRouteTargetGroupRequest.hpp>
#include <alibabacloud/models/CreateRouteTargetGroupResponseBody.hpp>
#include <alibabacloud/models/CreateRouteTargetGroupResponse.hpp>
#include <alibabacloud/models/CreateRouterInterfaceRequest.hpp>
#include <alibabacloud/models/CreateRouterInterfaceResponseBody.hpp>
#include <alibabacloud/models/CreateRouterInterfaceResponse.hpp>
#include <alibabacloud/models/CreateSnatEntryRequest.hpp>
#include <alibabacloud/models/CreateSnatEntryResponseBody.hpp>
#include <alibabacloud/models/CreateSnatEntryResponse.hpp>
#include <alibabacloud/models/CreateSslVpnClientCertRequest.hpp>
#include <alibabacloud/models/CreateSslVpnClientCertResponseBody.hpp>
#include <alibabacloud/models/CreateSslVpnClientCertResponse.hpp>
#include <alibabacloud/models/CreateSslVpnServerRequest.hpp>
#include <alibabacloud/models/CreateSslVpnServerResponseBody.hpp>
#include <alibabacloud/models/CreateSslVpnServerResponse.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterRequest.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterResponseBody.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterResponse.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterRulesRequest.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterRulesResponseBody.hpp>
#include <alibabacloud/models/CreateTrafficMirrorFilterRulesResponse.hpp>
#include <alibabacloud/models/CreateTrafficMirrorSessionRequest.hpp>
#include <alibabacloud/models/CreateTrafficMirrorSessionResponseBody.hpp>
#include <alibabacloud/models/CreateTrafficMirrorSessionResponse.hpp>
#include <alibabacloud/models/CreateVSwitchRequest.hpp>
#include <alibabacloud/models/CreateVSwitchResponseBody.hpp>
#include <alibabacloud/models/CreateVSwitchResponse.hpp>
#include <alibabacloud/models/CreateVSwitchCidrReservationRequest.hpp>
#include <alibabacloud/models/CreateVSwitchCidrReservationResponseBody.hpp>
#include <alibabacloud/models/CreateVSwitchCidrReservationResponse.hpp>
#include <alibabacloud/models/CreateVbrHaRequest.hpp>
#include <alibabacloud/models/CreateVbrHaResponseBody.hpp>
#include <alibabacloud/models/CreateVbrHaResponse.hpp>
#include <alibabacloud/models/CreateVcoRouteEntryRequest.hpp>
#include <alibabacloud/models/CreateVcoRouteEntryResponseBody.hpp>
#include <alibabacloud/models/CreateVcoRouteEntryResponse.hpp>
#include <alibabacloud/models/CreateVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/CreateVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/CreateVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/CreateVirtualPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/CreateVirtualPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/CreateVirtualPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/CreateVpcRequest.hpp>
#include <alibabacloud/models/CreateVpcResponseBody.hpp>
#include <alibabacloud/models/CreateVpcResponse.hpp>
#include <alibabacloud/models/CreateVpcGatewayEndpointRequest.hpp>
#include <alibabacloud/models/CreateVpcGatewayEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateVpcGatewayEndpointResponse.hpp>
#include <alibabacloud/models/CreateVpcPrefixListRequest.hpp>
#include <alibabacloud/models/CreateVpcPrefixListResponseBody.hpp>
#include <alibabacloud/models/CreateVpcPrefixListResponse.hpp>
#include <alibabacloud/models/CreateVpconnFromVbrRequest.hpp>
#include <alibabacloud/models/CreateVpconnFromVbrResponseBody.hpp>
#include <alibabacloud/models/CreateVpconnFromVbrResponse.hpp>
#include <alibabacloud/models/CreateVpnAttachmentRequest.hpp>
#include <alibabacloud/models/CreateVpnAttachmentResponseBody.hpp>
#include <alibabacloud/models/CreateVpnAttachmentResponse.hpp>
#include <alibabacloud/models/CreateVpnConnectionRequest.hpp>
#include <alibabacloud/models/CreateVpnConnectionResponseBody.hpp>
#include <alibabacloud/models/CreateVpnConnectionResponse.hpp>
#include <alibabacloud/models/CreateVpnGatewayRequest.hpp>
#include <alibabacloud/models/CreateVpnGatewayResponseBody.hpp>
#include <alibabacloud/models/CreateVpnGatewayResponse.hpp>
#include <alibabacloud/models/CreateVpnPbrRouteEntryRequest.hpp>
#include <alibabacloud/models/CreateVpnPbrRouteEntryResponseBody.hpp>
#include <alibabacloud/models/CreateVpnPbrRouteEntryResponse.hpp>
#include <alibabacloud/models/CreateVpnRouteEntryRequest.hpp>
#include <alibabacloud/models/CreateVpnRouteEntryResponseBody.hpp>
#include <alibabacloud/models/CreateVpnRouteEntryResponse.hpp>
#include <alibabacloud/models/DeactivateRouterInterfaceRequest.hpp>
#include <alibabacloud/models/DeactivateRouterInterfaceResponseBody.hpp>
#include <alibabacloud/models/DeactivateRouterInterfaceResponse.hpp>
#include <alibabacloud/models/DeactiveFlowLogRequest.hpp>
#include <alibabacloud/models/DeactiveFlowLogResponseBody.hpp>
#include <alibabacloud/models/DeactiveFlowLogResponse.hpp>
#include <alibabacloud/models/DeleteBgpGroupRequest.hpp>
#include <alibabacloud/models/DeleteBgpGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteBgpGroupResponse.hpp>
#include <alibabacloud/models/DeleteBgpNetworkRequest.hpp>
#include <alibabacloud/models/DeleteBgpNetworkResponseBody.hpp>
#include <alibabacloud/models/DeleteBgpNetworkResponse.hpp>
#include <alibabacloud/models/DeleteBgpPeerRequest.hpp>
#include <alibabacloud/models/DeleteBgpPeerResponseBody.hpp>
#include <alibabacloud/models/DeleteBgpPeerResponse.hpp>
#include <alibabacloud/models/DeleteCommonBandwidthPackageRequest.hpp>
#include <alibabacloud/models/DeleteCommonBandwidthPackageResponseBody.hpp>
#include <alibabacloud/models/DeleteCommonBandwidthPackageResponse.hpp>
#include <alibabacloud/models/DeleteCustomerGatewayRequest.hpp>
#include <alibabacloud/models/DeleteCustomerGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteCustomerGatewayResponse.hpp>
#include <alibabacloud/models/DeleteDhcpOptionsSetRequest.hpp>
#include <alibabacloud/models/DeleteDhcpOptionsSetResponseBody.hpp>
#include <alibabacloud/models/DeleteDhcpOptionsSetResponse.hpp>
#include <alibabacloud/models/DeleteExpressConnectRequest.hpp>
#include <alibabacloud/models/DeleteExpressConnectResponseBody.hpp>
#include <alibabacloud/models/DeleteExpressConnectResponse.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosRequest.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosResponseBody.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosResponse.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosQueueRequest.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosQueueResponseBody.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosQueueResponse.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosRuleRequest.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteExpressConnectTrafficQosRuleResponse.hpp>
#include <alibabacloud/models/DeleteFailoverTestJobRequest.hpp>
#include <alibabacloud/models/DeleteFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/DeleteFailoverTestJobResponse.hpp>
#include <alibabacloud/models/DeleteFlowLogRequest.hpp>
#include <alibabacloud/models/DeleteFlowLogResponseBody.hpp>
#include <alibabacloud/models/DeleteFlowLogResponse.hpp>
#include <alibabacloud/models/DeleteForwardEntryRequest.hpp>
#include <alibabacloud/models/DeleteForwardEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteForwardEntryResponse.hpp>
#include <alibabacloud/models/DeleteFullNatEntryRequest.hpp>
#include <alibabacloud/models/DeleteFullNatEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteFullNatEntryResponse.hpp>
#include <alibabacloud/models/DeleteGlobalAccelerationInstanceRequest.hpp>
#include <alibabacloud/models/DeleteGlobalAccelerationInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteGlobalAccelerationInstanceResponse.hpp>
#include <alibabacloud/models/DeleteHaVipRequest.hpp>
#include <alibabacloud/models/DeleteHaVipResponseBody.hpp>
#include <alibabacloud/models/DeleteHaVipResponse.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorRequest.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorResponseBody.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorResponse.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorAclListRequest.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorAclListResponseBody.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorAclListResponse.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorEntryRequest.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteIPv6TranslatorEntryResponse.hpp>
#include <alibabacloud/models/DeleteIpsecServerRequest.hpp>
#include <alibabacloud/models/DeleteIpsecServerResponseBody.hpp>
#include <alibabacloud/models/DeleteIpsecServerResponse.hpp>
#include <alibabacloud/models/DeleteIpv4GatewayRequest.hpp>
#include <alibabacloud/models/DeleteIpv4GatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteIpv4GatewayResponse.hpp>
#include <alibabacloud/models/DeleteIpv6EgressOnlyRuleRequest.hpp>
#include <alibabacloud/models/DeleteIpv6EgressOnlyRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteIpv6EgressOnlyRuleResponse.hpp>
#include <alibabacloud/models/DeleteIpv6GatewayRequest.hpp>
#include <alibabacloud/models/DeleteIpv6GatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteIpv6GatewayResponse.hpp>
#include <alibabacloud/models/DeleteIpv6InternetBandwidthRequest.hpp>
#include <alibabacloud/models/DeleteIpv6InternetBandwidthResponseBody.hpp>
#include <alibabacloud/models/DeleteIpv6InternetBandwidthResponse.hpp>
#include <alibabacloud/models/DeleteNatGatewayRequest.hpp>
#include <alibabacloud/models/DeleteNatGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteNatGatewayResponse.hpp>
#include <alibabacloud/models/DeleteNatIpRequest.hpp>
#include <alibabacloud/models/DeleteNatIpResponseBody.hpp>
#include <alibabacloud/models/DeleteNatIpResponse.hpp>
#include <alibabacloud/models/DeleteNatIpCidrRequest.hpp>
#include <alibabacloud/models/DeleteNatIpCidrResponseBody.hpp>
#include <alibabacloud/models/DeleteNatIpCidrResponse.hpp>
#include <alibabacloud/models/DeleteNetworkAclRequest.hpp>
#include <alibabacloud/models/DeleteNetworkAclResponseBody.hpp>
#include <alibabacloud/models/DeleteNetworkAclResponse.hpp>
#include <alibabacloud/models/DeletePhysicalConnectionRequest.hpp>
#include <alibabacloud/models/DeletePhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/DeletePhysicalConnectionResponse.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolRequest.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolResponseBody.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolResponse.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolCidrBlockRequest.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolCidrBlockResponseBody.hpp>
#include <alibabacloud/models/DeletePublicIpAddressPoolCidrBlockResponse.hpp>
#include <alibabacloud/models/DeleteRouteEntriesRequest.hpp>
#include <alibabacloud/models/DeleteRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteEntriesResponse.hpp>
#include <alibabacloud/models/DeleteRouteEntryRequest.hpp>
#include <alibabacloud/models/DeleteRouteEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteEntryResponse.hpp>
#include <alibabacloud/models/DeleteRouteTableRequest.hpp>
#include <alibabacloud/models/DeleteRouteTableResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteTableResponse.hpp>
#include <alibabacloud/models/DeleteRouteTargetGroupRequest.hpp>
#include <alibabacloud/models/DeleteRouteTargetGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteRouteTargetGroupResponse.hpp>
#include <alibabacloud/models/DeleteRouterInterfaceRequest.hpp>
#include <alibabacloud/models/DeleteRouterInterfaceResponseBody.hpp>
#include <alibabacloud/models/DeleteRouterInterfaceResponse.hpp>
#include <alibabacloud/models/DeleteSnatEntryRequest.hpp>
#include <alibabacloud/models/DeleteSnatEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteSnatEntryResponse.hpp>
#include <alibabacloud/models/DeleteSslVpnClientCertRequest.hpp>
#include <alibabacloud/models/DeleteSslVpnClientCertResponseBody.hpp>
#include <alibabacloud/models/DeleteSslVpnClientCertResponse.hpp>
#include <alibabacloud/models/DeleteSslVpnServerRequest.hpp>
#include <alibabacloud/models/DeleteSslVpnServerResponseBody.hpp>
#include <alibabacloud/models/DeleteSslVpnServerResponse.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterRequest.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterResponseBody.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterResponse.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterRulesRequest.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterRulesResponseBody.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorFilterRulesResponse.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorSessionRequest.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorSessionResponseBody.hpp>
#include <alibabacloud/models/DeleteTrafficMirrorSessionResponse.hpp>
#include <alibabacloud/models/DeleteVSwitchRequest.hpp>
#include <alibabacloud/models/DeleteVSwitchResponseBody.hpp>
#include <alibabacloud/models/DeleteVSwitchResponse.hpp>
#include <alibabacloud/models/DeleteVSwitchCidrReservationRequest.hpp>
#include <alibabacloud/models/DeleteVSwitchCidrReservationResponseBody.hpp>
#include <alibabacloud/models/DeleteVSwitchCidrReservationResponse.hpp>
#include <alibabacloud/models/DeleteVbrHaRequest.hpp>
#include <alibabacloud/models/DeleteVbrHaResponseBody.hpp>
#include <alibabacloud/models/DeleteVbrHaResponse.hpp>
#include <alibabacloud/models/DeleteVcoRouteEntryRequest.hpp>
#include <alibabacloud/models/DeleteVcoRouteEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteVcoRouteEntryResponse.hpp>
#include <alibabacloud/models/DeleteVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/DeleteVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/DeleteVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/DeleteVpcRequest.hpp>
#include <alibabacloud/models/DeleteVpcResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcResponse.hpp>
#include <alibabacloud/models/DeleteVpcGatewayEndpointRequest.hpp>
#include <alibabacloud/models/DeleteVpcGatewayEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcGatewayEndpointResponse.hpp>
#include <alibabacloud/models/DeleteVpcPrefixListRequest.hpp>
#include <alibabacloud/models/DeleteVpcPrefixListResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcPrefixListResponse.hpp>
#include <alibabacloud/models/DeleteVpnAttachmentRequest.hpp>
#include <alibabacloud/models/DeleteVpnAttachmentResponseBody.hpp>
#include <alibabacloud/models/DeleteVpnAttachmentResponse.hpp>
#include <alibabacloud/models/DeleteVpnConnectionRequest.hpp>
#include <alibabacloud/models/DeleteVpnConnectionResponseBody.hpp>
#include <alibabacloud/models/DeleteVpnConnectionResponse.hpp>
#include <alibabacloud/models/DeleteVpnGatewayRequest.hpp>
#include <alibabacloud/models/DeleteVpnGatewayResponseBody.hpp>
#include <alibabacloud/models/DeleteVpnGatewayResponse.hpp>
#include <alibabacloud/models/DeleteVpnPbrRouteEntryRequest.hpp>
#include <alibabacloud/models/DeleteVpnPbrRouteEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteVpnPbrRouteEntryResponse.hpp>
#include <alibabacloud/models/DeleteVpnRouteEntryRequest.hpp>
#include <alibabacloud/models/DeleteVpnRouteEntryResponseBody.hpp>
#include <alibabacloud/models/DeleteVpnRouteEntryResponse.hpp>
#include <alibabacloud/models/DeletionProtectionRequest.hpp>
#include <alibabacloud/models/DeletionProtectionResponseBody.hpp>
#include <alibabacloud/models/DeletionProtectionResponse.hpp>
#include <alibabacloud/models/Describe95TrafficRequest.hpp>
#include <alibabacloud/models/Describe95TrafficResponseBody.hpp>
#include <alibabacloud/models/Describe95TrafficResponse.hpp>
#include <alibabacloud/models/DescribeAccessPointsRequest.hpp>
#include <alibabacloud/models/DescribeAccessPointsResponseBody.hpp>
#include <alibabacloud/models/DescribeAccessPointsResponse.hpp>
#include <alibabacloud/models/DescribeBgpGroupsRequest.hpp>
#include <alibabacloud/models/DescribeBgpGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeBgpGroupsResponse.hpp>
#include <alibabacloud/models/DescribeBgpNetworksRequest.hpp>
#include <alibabacloud/models/DescribeBgpNetworksResponseBody.hpp>
#include <alibabacloud/models/DescribeBgpNetworksResponse.hpp>
#include <alibabacloud/models/DescribeBgpPeersRequest.hpp>
#include <alibabacloud/models/DescribeBgpPeersResponseBody.hpp>
#include <alibabacloud/models/DescribeBgpPeersResponse.hpp>
#include <alibabacloud/models/DescribeCommonBandwidthPackagesRequest.hpp>
#include <alibabacloud/models/DescribeCommonBandwidthPackagesResponseBody.hpp>
#include <alibabacloud/models/DescribeCommonBandwidthPackagesResponse.hpp>
#include <alibabacloud/models/DescribeCustomerGatewayRequest.hpp>
#include <alibabacloud/models/DescribeCustomerGatewayResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomerGatewayResponse.hpp>
#include <alibabacloud/models/DescribeCustomerGatewaysRequest.hpp>
#include <alibabacloud/models/DescribeCustomerGatewaysResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomerGatewaysResponse.hpp>
#include <alibabacloud/models/DescribeEcGrantRelationRequest.hpp>
#include <alibabacloud/models/DescribeEcGrantRelationResponseBody.hpp>
#include <alibabacloud/models/DescribeEcGrantRelationResponse.hpp>
#include <alibabacloud/models/DescribeEipAddressesRequest.hpp>
#include <alibabacloud/models/DescribeEipAddressesResponseBody.hpp>
#include <alibabacloud/models/DescribeEipAddressesResponse.hpp>
#include <alibabacloud/models/DescribeEipGatewayInfoRequest.hpp>
#include <alibabacloud/models/DescribeEipGatewayInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeEipGatewayInfoResponse.hpp>
#include <alibabacloud/models/DescribeEipMonitorDataRequest.hpp>
#include <alibabacloud/models/DescribeEipMonitorDataResponseBody.hpp>
#include <alibabacloud/models/DescribeEipMonitorDataResponse.hpp>
#include <alibabacloud/models/DescribeEipSegmentRequest.hpp>
#include <alibabacloud/models/DescribeEipSegmentResponseBody.hpp>
#include <alibabacloud/models/DescribeEipSegmentResponse.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosRequest.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosResponseBody.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosResponse.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosQueueRequest.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosQueueResponseBody.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosQueueResponse.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosRuleRequest.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosRuleResponseBody.hpp>
#include <alibabacloud/models/DescribeExpressConnectTrafficQosRuleResponse.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobRequest.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobResponse.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobsRequest.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobsResponseBody.hpp>
#include <alibabacloud/models/DescribeFailoverTestJobsResponse.hpp>
#include <alibabacloud/models/DescribeFlowLogsRequest.hpp>
#include <alibabacloud/models/DescribeFlowLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeFlowLogsResponse.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesRequest.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeForwardTableEntriesResponse.hpp>
#include <alibabacloud/models/DescribeGlobalAccelerationInstancesRequest.hpp>
#include <alibabacloud/models/DescribeGlobalAccelerationInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeGlobalAccelerationInstancesResponse.hpp>
#include <alibabacloud/models/DescribeGrantRulesToCenRequest.hpp>
#include <alibabacloud/models/DescribeGrantRulesToCenResponseBody.hpp>
#include <alibabacloud/models/DescribeGrantRulesToCenResponse.hpp>
#include <alibabacloud/models/DescribeGrantRulesToEcrRequest.hpp>
#include <alibabacloud/models/DescribeGrantRulesToEcrResponseBody.hpp>
#include <alibabacloud/models/DescribeGrantRulesToEcrResponse.hpp>
#include <alibabacloud/models/DescribeHaVipsRequest.hpp>
#include <alibabacloud/models/DescribeHaVipsResponseBody.hpp>
#include <alibabacloud/models/DescribeHaVipsResponse.hpp>
#include <alibabacloud/models/DescribeHighDefinitionMonitorLogAttributeRequest.hpp>
#include <alibabacloud/models/DescribeHighDefinitionMonitorLogAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeHighDefinitionMonitorLogAttributeResponse.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListAttributesRequest.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListAttributesResponseBody.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListAttributesResponse.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListsRequest.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListsResponseBody.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorAclListsResponse.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorEntriesRequest.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorEntriesResponse.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorsRequest.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorsResponseBody.hpp>
#include <alibabacloud/models/DescribeIPv6TranslatorsResponse.hpp>
#include <alibabacloud/models/DescribeIpv6AddressesRequest.hpp>
#include <alibabacloud/models/DescribeIpv6AddressesResponseBody.hpp>
#include <alibabacloud/models/DescribeIpv6AddressesResponse.hpp>
#include <alibabacloud/models/DescribeIpv6EgressOnlyRulesRequest.hpp>
#include <alibabacloud/models/DescribeIpv6EgressOnlyRulesResponseBody.hpp>
#include <alibabacloud/models/DescribeIpv6EgressOnlyRulesResponse.hpp>
#include <alibabacloud/models/DescribeIpv6GatewayAttributeRequest.hpp>
#include <alibabacloud/models/DescribeIpv6GatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeIpv6GatewayAttributeResponse.hpp>
#include <alibabacloud/models/DescribeIpv6GatewaysRequest.hpp>
#include <alibabacloud/models/DescribeIpv6GatewaysResponseBody.hpp>
#include <alibabacloud/models/DescribeIpv6GatewaysResponse.hpp>
#include <alibabacloud/models/DescribeNatGatewayAssociateNetworkInterfacesRequest.hpp>
#include <alibabacloud/models/DescribeNatGatewayAssociateNetworkInterfacesResponseBody.hpp>
#include <alibabacloud/models/DescribeNatGatewayAssociateNetworkInterfacesResponse.hpp>
#include <alibabacloud/models/DescribeNatGatewaysRequest.hpp>
#include <alibabacloud/models/DescribeNatGatewaysResponseBody.hpp>
#include <alibabacloud/models/DescribeNatGatewaysResponse.hpp>
#include <alibabacloud/models/DescribeNetworkAclAttributesRequest.hpp>
#include <alibabacloud/models/DescribeNetworkAclAttributesResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkAclAttributesResponse.hpp>
#include <alibabacloud/models/DescribeNetworkAclsRequest.hpp>
#include <alibabacloud/models/DescribeNetworkAclsResponseBody.hpp>
#include <alibabacloud/models/DescribeNetworkAclsResponse.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionLoaRequest.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionLoaResponseBody.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionLoaResponse.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionsRequest.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionsResponseBody.hpp>
#include <alibabacloud/models/DescribePhysicalConnectionsResponse.hpp>
#include <alibabacloud/models/DescribePublicIpAddressRequest.hpp>
#include <alibabacloud/models/DescribePublicIpAddressResponseBody.hpp>
#include <alibabacloud/models/DescribePublicIpAddressResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRouteEntryListRequest.hpp>
#include <alibabacloud/models/DescribeRouteEntryListResponseBody.hpp>
#include <alibabacloud/models/DescribeRouteEntryListResponse.hpp>
#include <alibabacloud/models/DescribeRouteTableListRequest.hpp>
#include <alibabacloud/models/DescribeRouteTableListResponseBody.hpp>
#include <alibabacloud/models/DescribeRouteTableListResponse.hpp>
#include <alibabacloud/models/DescribeRouteTablesRequest.hpp>
#include <alibabacloud/models/DescribeRouteTablesResponseBody.hpp>
#include <alibabacloud/models/DescribeRouteTablesResponse.hpp>
#include <alibabacloud/models/DescribeRouterInterfaceAttributeRequest.hpp>
#include <alibabacloud/models/DescribeRouterInterfaceAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeRouterInterfaceAttributeResponse.hpp>
#include <alibabacloud/models/DescribeRouterInterfacesRequest.hpp>
#include <alibabacloud/models/DescribeRouterInterfacesResponseBody.hpp>
#include <alibabacloud/models/DescribeRouterInterfacesResponse.hpp>
#include <alibabacloud/models/DescribeServerRelatedGlobalAccelerationInstancesRequest.hpp>
#include <alibabacloud/models/DescribeServerRelatedGlobalAccelerationInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeServerRelatedGlobalAccelerationInstancesResponse.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesRequest.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeSnatTableEntriesResponse.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertRequest.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertResponseBody.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertResponse.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertsRequest.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertsResponseBody.hpp>
#include <alibabacloud/models/DescribeSslVpnClientCertsResponse.hpp>
#include <alibabacloud/models/DescribeSslVpnClientsRequest.hpp>
#include <alibabacloud/models/DescribeSslVpnClientsResponseBody.hpp>
#include <alibabacloud/models/DescribeSslVpnClientsResponse.hpp>
#include <alibabacloud/models/DescribeSslVpnServersRequest.hpp>
#include <alibabacloud/models/DescribeSslVpnServersResponseBody.hpp>
#include <alibabacloud/models/DescribeSslVpnServersResponse.hpp>
#include <alibabacloud/models/DescribeTagKeysRequest.hpp>
#include <alibabacloud/models/DescribeTagKeysResponseBody.hpp>
#include <alibabacloud/models/DescribeTagKeysResponse.hpp>
#include <alibabacloud/models/DescribeTagKeysForExpressConnectRequest.hpp>
#include <alibabacloud/models/DescribeTagKeysForExpressConnectResponseBody.hpp>
#include <alibabacloud/models/DescribeTagKeysForExpressConnectResponse.hpp>
#include <alibabacloud/models/DescribeTagsRequest.hpp>
#include <alibabacloud/models/DescribeTagsResponseBody.hpp>
#include <alibabacloud/models/DescribeTagsResponse.hpp>
#include <alibabacloud/models/DescribeVRoutersRequest.hpp>
#include <alibabacloud/models/DescribeVRoutersResponseBody.hpp>
#include <alibabacloud/models/DescribeVRoutersResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchAttributesRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchAttributesResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchAttributesResponse.hpp>
#include <alibabacloud/models/DescribeVSwitchesRequest.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponseBody.hpp>
#include <alibabacloud/models/DescribeVSwitchesResponse.hpp>
#include <alibabacloud/models/DescribeVbrHaRequest.hpp>
#include <alibabacloud/models/DescribeVbrHaResponseBody.hpp>
#include <alibabacloud/models/DescribeVbrHaResponse.hpp>
#include <alibabacloud/models/DescribeVcoRouteEntriesRequest.hpp>
#include <alibabacloud/models/DescribeVcoRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeVcoRouteEntriesResponse.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersRequest.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersResponseBody.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersResponse.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersForPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersForPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/DescribeVirtualBorderRoutersForPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/DescribeVpcAttributeRequest.hpp>
#include <alibabacloud/models/DescribeVpcAttributeResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcAttributeResponse.hpp>
#include <alibabacloud/models/DescribeVpcGrantRulesToEcrRequest.hpp>
#include <alibabacloud/models/DescribeVpcGrantRulesToEcrResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcGrantRulesToEcrResponse.hpp>
#include <alibabacloud/models/DescribeVpcsRequest.hpp>
#include <alibabacloud/models/DescribeVpcsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpcsResponse.hpp>
#include <alibabacloud/models/DescribeVpnAttachmentsRequest.hpp>
#include <alibabacloud/models/DescribeVpnAttachmentsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnAttachmentsResponse.hpp>
#include <alibabacloud/models/DescribeVpnConnectionRequest.hpp>
#include <alibabacloud/models/DescribeVpnConnectionResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnConnectionResponse.hpp>
#include <alibabacloud/models/DescribeVpnConnectionLogsRequest.hpp>
#include <alibabacloud/models/DescribeVpnConnectionLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnConnectionLogsResponse.hpp>
#include <alibabacloud/models/DescribeVpnConnectionsRequest.hpp>
#include <alibabacloud/models/DescribeVpnConnectionsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnConnectionsResponse.hpp>
#include <alibabacloud/models/DescribeVpnCrossAccountAuthorizationsRequest.hpp>
#include <alibabacloud/models/DescribeVpnCrossAccountAuthorizationsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnCrossAccountAuthorizationsResponse.hpp>
#include <alibabacloud/models/DescribeVpnGatewayRequest.hpp>
#include <alibabacloud/models/DescribeVpnGatewayResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnGatewayResponse.hpp>
#include <alibabacloud/models/DescribeVpnGatewayAvailableZonesRequest.hpp>
#include <alibabacloud/models/DescribeVpnGatewayAvailableZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnGatewayAvailableZonesResponse.hpp>
#include <alibabacloud/models/DescribeVpnGatewaysRequest.hpp>
#include <alibabacloud/models/DescribeVpnGatewaysResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnGatewaysResponse.hpp>
#include <alibabacloud/models/DescribeVpnPbrRouteEntriesRequest.hpp>
#include <alibabacloud/models/DescribeVpnPbrRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnPbrRouteEntriesResponse.hpp>
#include <alibabacloud/models/DescribeVpnRouteEntriesRequest.hpp>
#include <alibabacloud/models/DescribeVpnRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnRouteEntriesResponse.hpp>
#include <alibabacloud/models/DescribeVpnSslServerLogsRequest.hpp>
#include <alibabacloud/models/DescribeVpnSslServerLogsResponseBody.hpp>
#include <alibabacloud/models/DescribeVpnSslServerLogsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DetachDhcpOptionsSetFromVpcRequest.hpp>
#include <alibabacloud/models/DetachDhcpOptionsSetFromVpcResponseBody.hpp>
#include <alibabacloud/models/DetachDhcpOptionsSetFromVpcResponse.hpp>
#include <alibabacloud/models/DiagnoseVpnConnectionsRequest.hpp>
#include <alibabacloud/models/DiagnoseVpnConnectionsResponseBody.hpp>
#include <alibabacloud/models/DiagnoseVpnConnectionsResponse.hpp>
#include <alibabacloud/models/DiagnoseVpnGatewayRequest.hpp>
#include <alibabacloud/models/DiagnoseVpnGatewayResponseBody.hpp>
#include <alibabacloud/models/DiagnoseVpnGatewayResponse.hpp>
#include <alibabacloud/models/DisableNatGatewayEcsMetricRequest.hpp>
#include <alibabacloud/models/DisableNatGatewayEcsMetricResponseBody.hpp>
#include <alibabacloud/models/DisableNatGatewayEcsMetricResponse.hpp>
#include <alibabacloud/models/DisableVpcClassicLinkRequest.hpp>
#include <alibabacloud/models/DisableVpcClassicLinkResponseBody.hpp>
#include <alibabacloud/models/DisableVpcClassicLinkResponse.hpp>
#include <alibabacloud/models/DissociateRouteTableFromGatewayRequest.hpp>
#include <alibabacloud/models/DissociateRouteTableFromGatewayResponseBody.hpp>
#include <alibabacloud/models/DissociateRouteTableFromGatewayResponse.hpp>
#include <alibabacloud/models/DissociateRouteTablesFromVpcGatewayEndpointRequest.hpp>
#include <alibabacloud/models/DissociateRouteTablesFromVpcGatewayEndpointResponseBody.hpp>
#include <alibabacloud/models/DissociateRouteTablesFromVpcGatewayEndpointResponse.hpp>
#include <alibabacloud/models/DissociateVpnGatewayWithCertificateRequest.hpp>
#include <alibabacloud/models/DissociateVpnGatewayWithCertificateResponseBody.hpp>
#include <alibabacloud/models/DissociateVpnGatewayWithCertificateResponse.hpp>
#include <alibabacloud/models/DownloadVpnConnectionConfigRequest.hpp>
#include <alibabacloud/models/DownloadVpnConnectionConfigResponseBody.hpp>
#include <alibabacloud/models/DownloadVpnConnectionConfigResponse.hpp>
#include <alibabacloud/models/EnableNatGatewayEcsMetricRequest.hpp>
#include <alibabacloud/models/EnableNatGatewayEcsMetricResponseBody.hpp>
#include <alibabacloud/models/EnableNatGatewayEcsMetricResponse.hpp>
#include <alibabacloud/models/EnablePhysicalConnectionRequest.hpp>
#include <alibabacloud/models/EnablePhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/EnablePhysicalConnectionResponse.hpp>
#include <alibabacloud/models/EnableVpcClassicLinkRequest.hpp>
#include <alibabacloud/models/EnableVpcClassicLinkResponseBody.hpp>
#include <alibabacloud/models/EnableVpcClassicLinkResponse.hpp>
#include <alibabacloud/models/EnableVpcIpv4GatewayRequest.hpp>
#include <alibabacloud/models/EnableVpcIpv4GatewayResponseBody.hpp>
#include <alibabacloud/models/EnableVpcIpv4GatewayResponse.hpp>
#include <alibabacloud/models/GetDhcpOptionsSetRequest.hpp>
#include <alibabacloud/models/GetDhcpOptionsSetResponseBody.hpp>
#include <alibabacloud/models/GetDhcpOptionsSetResponse.hpp>
#include <alibabacloud/models/GetFlowLogServiceStatusRequest.hpp>
#include <alibabacloud/models/GetFlowLogServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetFlowLogServiceStatusResponse.hpp>
#include <alibabacloud/models/GetIpv4GatewayAttributeRequest.hpp>
#include <alibabacloud/models/GetIpv4GatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/GetIpv4GatewayAttributeResponse.hpp>
#include <alibabacloud/models/GetNatGatewayAttributeRequest.hpp>
#include <alibabacloud/models/GetNatGatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/GetNatGatewayAttributeResponse.hpp>
#include <alibabacloud/models/GetPhysicalConnectionServiceStatusRequest.hpp>
#include <alibabacloud/models/GetPhysicalConnectionServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetPhysicalConnectionServiceStatusResponse.hpp>
#include <alibabacloud/models/GetPublicIpAddressPoolServiceStatusRequest.hpp>
#include <alibabacloud/models/GetPublicIpAddressPoolServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetPublicIpAddressPoolServiceStatusResponse.hpp>
#include <alibabacloud/models/GetRouteTargetGroupRequest.hpp>
#include <alibabacloud/models/GetRouteTargetGroupResponseBody.hpp>
#include <alibabacloud/models/GetRouteTargetGroupResponse.hpp>
#include <alibabacloud/models/GetTrafficMirrorServiceStatusRequest.hpp>
#include <alibabacloud/models/GetTrafficMirrorServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetTrafficMirrorServiceStatusResponse.hpp>
#include <alibabacloud/models/GetVSwitchCidrReservationUsageRequest.hpp>
#include <alibabacloud/models/GetVSwitchCidrReservationUsageResponseBody.hpp>
#include <alibabacloud/models/GetVSwitchCidrReservationUsageResponse.hpp>
#include <alibabacloud/models/GetVpcGatewayEndpointAttributeRequest.hpp>
#include <alibabacloud/models/GetVpcGatewayEndpointAttributeResponseBody.hpp>
#include <alibabacloud/models/GetVpcGatewayEndpointAttributeResponse.hpp>
#include <alibabacloud/models/GetVpcPrefixListAssociationsRequest.hpp>
#include <alibabacloud/models/GetVpcPrefixListAssociationsResponseBody.hpp>
#include <alibabacloud/models/GetVpcPrefixListAssociationsResponse.hpp>
#include <alibabacloud/models/GetVpcPrefixListEntriesRequest.hpp>
#include <alibabacloud/models/GetVpcPrefixListEntriesResponseBody.hpp>
#include <alibabacloud/models/GetVpcPrefixListEntriesResponse.hpp>
#include <alibabacloud/models/GetVpcRouteEntrySummaryRequest.hpp>
#include <alibabacloud/models/GetVpcRouteEntrySummaryResponseBody.hpp>
#include <alibabacloud/models/GetVpcRouteEntrySummaryResponse.hpp>
#include <alibabacloud/models/GetVpnGatewayDiagnoseResultRequest.hpp>
#include <alibabacloud/models/GetVpnGatewayDiagnoseResultResponseBody.hpp>
#include <alibabacloud/models/GetVpnGatewayDiagnoseResultResponse.hpp>
#include <alibabacloud/models/GrantInstanceToCenRequest.hpp>
#include <alibabacloud/models/GrantInstanceToCenResponseBody.hpp>
#include <alibabacloud/models/GrantInstanceToCenResponse.hpp>
#include <alibabacloud/models/GrantInstanceToVbrRequest.hpp>
#include <alibabacloud/models/GrantInstanceToVbrShrinkRequest.hpp>
#include <alibabacloud/models/GrantInstanceToVbrResponseBody.hpp>
#include <alibabacloud/models/GrantInstanceToVbrResponse.hpp>
#include <alibabacloud/models/ListBusinessAccessPointsRequest.hpp>
#include <alibabacloud/models/ListBusinessAccessPointsResponseBody.hpp>
#include <alibabacloud/models/ListBusinessAccessPointsResponse.hpp>
#include <alibabacloud/models/ListBusinessRegionsRequest.hpp>
#include <alibabacloud/models/ListBusinessRegionsResponseBody.hpp>
#include <alibabacloud/models/ListBusinessRegionsResponse.hpp>
#include <alibabacloud/models/ListDhcpOptionsSetsRequest.hpp>
#include <alibabacloud/models/ListDhcpOptionsSetsResponseBody.hpp>
#include <alibabacloud/models/ListDhcpOptionsSetsResponse.hpp>
#include <alibabacloud/models/ListEnhanhcedNatGatewayAvailableZonesRequest.hpp>
#include <alibabacloud/models/ListEnhanhcedNatGatewayAvailableZonesResponseBody.hpp>
#include <alibabacloud/models/ListEnhanhcedNatGatewayAvailableZonesResponse.hpp>
#include <alibabacloud/models/ListFullNatEntriesRequest.hpp>
#include <alibabacloud/models/ListFullNatEntriesResponseBody.hpp>
#include <alibabacloud/models/ListFullNatEntriesResponse.hpp>
#include <alibabacloud/models/ListGatewayRouteTableEntriesRequest.hpp>
#include <alibabacloud/models/ListGatewayRouteTableEntriesResponseBody.hpp>
#include <alibabacloud/models/ListGatewayRouteTableEntriesResponse.hpp>
#include <alibabacloud/models/ListGeographicSubRegionsResponseBody.hpp>
#include <alibabacloud/models/ListGeographicSubRegionsResponse.hpp>
#include <alibabacloud/models/ListIpsecServerLogsRequest.hpp>
#include <alibabacloud/models/ListIpsecServerLogsResponseBody.hpp>
#include <alibabacloud/models/ListIpsecServerLogsResponse.hpp>
#include <alibabacloud/models/ListIpsecServersRequest.hpp>
#include <alibabacloud/models/ListIpsecServersResponseBody.hpp>
#include <alibabacloud/models/ListIpsecServersResponse.hpp>
#include <alibabacloud/models/ListIpv4GatewaysRequest.hpp>
#include <alibabacloud/models/ListIpv4GatewaysResponseBody.hpp>
#include <alibabacloud/models/ListIpv4GatewaysResponse.hpp>
#include <alibabacloud/models/ListNatIpCidrsRequest.hpp>
#include <alibabacloud/models/ListNatIpCidrsResponseBody.hpp>
#include <alibabacloud/models/ListNatIpCidrsResponse.hpp>
#include <alibabacloud/models/ListNatIpsRequest.hpp>
#include <alibabacloud/models/ListNatIpsResponseBody.hpp>
#include <alibabacloud/models/ListNatIpsResponse.hpp>
#include <alibabacloud/models/ListPhysicalConnectionFeaturesRequest.hpp>
#include <alibabacloud/models/ListPhysicalConnectionFeaturesResponseBody.hpp>
#include <alibabacloud/models/ListPhysicalConnectionFeaturesResponse.hpp>
#include <alibabacloud/models/ListPrefixListsRequest.hpp>
#include <alibabacloud/models/ListPrefixListsResponseBody.hpp>
#include <alibabacloud/models/ListPrefixListsResponse.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolCidrBlocksRequest.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolCidrBlocksResponseBody.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolCidrBlocksResponse.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolsRequest.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolsResponseBody.hpp>
#include <alibabacloud/models/ListPublicIpAddressPoolsResponse.hpp>
#include <alibabacloud/models/ListRouteTargetGroupsRequest.hpp>
#include <alibabacloud/models/ListRouteTargetGroupsResponseBody.hpp>
#include <alibabacloud/models/ListRouteTargetGroupsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListTagResourcesForExpressConnectRequest.hpp>
#include <alibabacloud/models/ListTagResourcesForExpressConnectResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesForExpressConnectResponse.hpp>
#include <alibabacloud/models/ListTrafficMirrorFiltersRequest.hpp>
#include <alibabacloud/models/ListTrafficMirrorFiltersResponseBody.hpp>
#include <alibabacloud/models/ListTrafficMirrorFiltersResponse.hpp>
#include <alibabacloud/models/ListTrafficMirrorSessionsRequest.hpp>
#include <alibabacloud/models/ListTrafficMirrorSessionsResponseBody.hpp>
#include <alibabacloud/models/ListTrafficMirrorSessionsResponse.hpp>
#include <alibabacloud/models/ListVSwitchCidrReservationsRequest.hpp>
#include <alibabacloud/models/ListVSwitchCidrReservationsResponseBody.hpp>
#include <alibabacloud/models/ListVSwitchCidrReservationsResponse.hpp>
#include <alibabacloud/models/ListVirtualPhysicalConnectionsRequest.hpp>
#include <alibabacloud/models/ListVirtualPhysicalConnectionsResponseBody.hpp>
#include <alibabacloud/models/ListVirtualPhysicalConnectionsResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponse.hpp>
#include <alibabacloud/models/ListVpcGatewayEndpointsRequest.hpp>
#include <alibabacloud/models/ListVpcGatewayEndpointsResponseBody.hpp>
#include <alibabacloud/models/ListVpcGatewayEndpointsResponse.hpp>
#include <alibabacloud/models/ListVpcPublishedRouteEntriesRequest.hpp>
#include <alibabacloud/models/ListVpcPublishedRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/ListVpcPublishedRouteEntriesResponse.hpp>
#include <alibabacloud/models/ListVpnCertificateAssociationsRequest.hpp>
#include <alibabacloud/models/ListVpnCertificateAssociationsResponseBody.hpp>
#include <alibabacloud/models/ListVpnCertificateAssociationsResponse.hpp>
#include <alibabacloud/models/ModifyBgpGroupAttributeRequest.hpp>
#include <alibabacloud/models/ModifyBgpGroupAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyBgpGroupAttributeResponse.hpp>
#include <alibabacloud/models/ModifyBgpPeerAttributeRequest.hpp>
#include <alibabacloud/models/ModifyBgpPeerAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyBgpPeerAttributeResponse.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageAttributeRequest.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageAttributeResponse.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageIpBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageIpBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageIpBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageSpecRequest.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyCommonBandwidthPackageSpecResponse.hpp>
#include <alibabacloud/models/ModifyCustomerGatewayAttributeRequest.hpp>
#include <alibabacloud/models/ModifyCustomerGatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyCustomerGatewayAttributeResponse.hpp>
#include <alibabacloud/models/ModifyEipAddressAttributeRequest.hpp>
#include <alibabacloud/models/ModifyEipAddressAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyEipAddressAttributeResponse.hpp>
#include <alibabacloud/models/ModifyEipForwardModeRequest.hpp>
#include <alibabacloud/models/ModifyEipForwardModeResponseBody.hpp>
#include <alibabacloud/models/ModifyEipForwardModeResponse.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionAttributeRequest.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionAttributeResponse.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyExpressCloudConnectionBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosRequest.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosResponseBody.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosResponse.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosQueueRequest.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosQueueResponseBody.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosQueueResponse.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosRuleRequest.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosRuleResponseBody.hpp>
#include <alibabacloud/models/ModifyExpressConnectTrafficQosRuleResponse.hpp>
#include <alibabacloud/models/ModifyFlowLogAttributeRequest.hpp>
#include <alibabacloud/models/ModifyFlowLogAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyFlowLogAttributeResponse.hpp>
#include <alibabacloud/models/ModifyForwardEntryRequest.hpp>
#include <alibabacloud/models/ModifyForwardEntryResponseBody.hpp>
#include <alibabacloud/models/ModifyForwardEntryResponse.hpp>
#include <alibabacloud/models/ModifyFullNatEntryAttributeRequest.hpp>
#include <alibabacloud/models/ModifyFullNatEntryAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyFullNatEntryAttributeResponse.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceAttributesRequest.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceAttributesResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceAttributesResponse.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceSpecRequest.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyGlobalAccelerationInstanceSpecResponse.hpp>
#include <alibabacloud/models/ModifyHaVipAttributeRequest.hpp>
#include <alibabacloud/models/ModifyHaVipAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyHaVipAttributeResponse.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclAttributeRequest.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclAttributeResponse.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclListEntryRequest.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclListEntryResponseBody.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAclListEntryResponse.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAttributeRequest.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorAttributeResponse.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorEntryRequest.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorEntryResponseBody.hpp>
#include <alibabacloud/models/ModifyIPv6TranslatorEntryResponse.hpp>
#include <alibabacloud/models/ModifyIpv6AddressAttributeRequest.hpp>
#include <alibabacloud/models/ModifyIpv6AddressAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyIpv6AddressAttributeResponse.hpp>
#include <alibabacloud/models/ModifyIpv6GatewayAttributeRequest.hpp>
#include <alibabacloud/models/ModifyIpv6GatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyIpv6GatewayAttributeResponse.hpp>
#include <alibabacloud/models/ModifyIpv6InternetBandwidthRequest.hpp>
#include <alibabacloud/models/ModifyIpv6InternetBandwidthResponseBody.hpp>
#include <alibabacloud/models/ModifyIpv6InternetBandwidthResponse.hpp>
#include <alibabacloud/models/ModifyNatGatewayAttributeRequest.hpp>
#include <alibabacloud/models/ModifyNatGatewayAttributeShrinkRequest.hpp>
#include <alibabacloud/models/ModifyNatGatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyNatGatewayAttributeResponse.hpp>
#include <alibabacloud/models/ModifyNatGatewaySpecRequest.hpp>
#include <alibabacloud/models/ModifyNatGatewaySpecResponseBody.hpp>
#include <alibabacloud/models/ModifyNatGatewaySpecResponse.hpp>
#include <alibabacloud/models/ModifyNatIpAttributeRequest.hpp>
#include <alibabacloud/models/ModifyNatIpAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyNatIpAttributeResponse.hpp>
#include <alibabacloud/models/ModifyNatIpCidrAttributeRequest.hpp>
#include <alibabacloud/models/ModifyNatIpCidrAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyNatIpCidrAttributeResponse.hpp>
#include <alibabacloud/models/ModifyNetworkAclAttributesRequest.hpp>
#include <alibabacloud/models/ModifyNetworkAclAttributesResponseBody.hpp>
#include <alibabacloud/models/ModifyNetworkAclAttributesResponse.hpp>
#include <alibabacloud/models/ModifyPhysicalConnectionAttributeRequest.hpp>
#include <alibabacloud/models/ModifyPhysicalConnectionAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyPhysicalConnectionAttributeResponse.hpp>
#include <alibabacloud/models/ModifyRouteEntryRequest.hpp>
#include <alibabacloud/models/ModifyRouteEntryResponseBody.hpp>
#include <alibabacloud/models/ModifyRouteEntryResponse.hpp>
#include <alibabacloud/models/ModifyRouteTableAttributesRequest.hpp>
#include <alibabacloud/models/ModifyRouteTableAttributesResponseBody.hpp>
#include <alibabacloud/models/ModifyRouteTableAttributesResponse.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceAttributeRequest.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceAttributeResponse.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceSpecRequest.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceSpecResponseBody.hpp>
#include <alibabacloud/models/ModifyRouterInterfaceSpecResponse.hpp>
#include <alibabacloud/models/ModifySnatEntryRequest.hpp>
#include <alibabacloud/models/ModifySnatEntryResponseBody.hpp>
#include <alibabacloud/models/ModifySnatEntryResponse.hpp>
#include <alibabacloud/models/ModifySslVpnClientCertRequest.hpp>
#include <alibabacloud/models/ModifySslVpnClientCertResponseBody.hpp>
#include <alibabacloud/models/ModifySslVpnClientCertResponse.hpp>
#include <alibabacloud/models/ModifySslVpnServerRequest.hpp>
#include <alibabacloud/models/ModifySslVpnServerResponseBody.hpp>
#include <alibabacloud/models/ModifySslVpnServerResponse.hpp>
#include <alibabacloud/models/ModifyTunnelAttributeRequest.hpp>
#include <alibabacloud/models/ModifyTunnelAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyTunnelAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVRouterAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVRouterAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVRouterAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVSwitchAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVSwitchAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVSwitchAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVSwitchCidrReservationAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVSwitchCidrReservationAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVSwitchCidrReservationAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVcoRouteEntryWeightRequest.hpp>
#include <alibabacloud/models/ModifyVcoRouteEntryWeightResponseBody.hpp>
#include <alibabacloud/models/ModifyVcoRouteEntryWeightResponse.hpp>
#include <alibabacloud/models/ModifyVirtualBorderRouterAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVirtualBorderRouterAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVirtualBorderRouterAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpcAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVpcAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpcPrefixListRequest.hpp>
#include <alibabacloud/models/ModifyVpcPrefixListResponseBody.hpp>
#include <alibabacloud/models/ModifyVpcPrefixListResponse.hpp>
#include <alibabacloud/models/ModifyVpnAttachmentAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVpnAttachmentAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnAttachmentAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpnConnectionAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVpnConnectionAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnConnectionAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpnGatewayAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVpnGatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnGatewayAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryAttributeRequest.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryAttributeResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryAttributeResponse.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryPriorityRequest.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryPriorityResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryPriorityResponse.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryWeightRequest.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryWeightResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnPbrRouteEntryWeightResponse.hpp>
#include <alibabacloud/models/ModifyVpnRouteEntryWeightRequest.hpp>
#include <alibabacloud/models/ModifyVpnRouteEntryWeightResponseBody.hpp>
#include <alibabacloud/models/ModifyVpnRouteEntryWeightResponse.hpp>
#include <alibabacloud/models/MoveResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveResourceGroupResponse.hpp>
#include <alibabacloud/models/MoveVpnResourceGroupRequest.hpp>
#include <alibabacloud/models/MoveVpnResourceGroupResponseBody.hpp>
#include <alibabacloud/models/MoveVpnResourceGroupResponse.hpp>
#include <alibabacloud/models/OpenFlowLogServiceRequest.hpp>
#include <alibabacloud/models/OpenFlowLogServiceResponseBody.hpp>
#include <alibabacloud/models/OpenFlowLogServiceResponse.hpp>
#include <alibabacloud/models/OpenPhysicalConnectionServiceRequest.hpp>
#include <alibabacloud/models/OpenPhysicalConnectionServiceResponseBody.hpp>
#include <alibabacloud/models/OpenPhysicalConnectionServiceResponse.hpp>
#include <alibabacloud/models/OpenPublicIpAddressPoolServiceRequest.hpp>
#include <alibabacloud/models/OpenPublicIpAddressPoolServiceResponseBody.hpp>
#include <alibabacloud/models/OpenPublicIpAddressPoolServiceResponse.hpp>
#include <alibabacloud/models/OpenTrafficMirrorServiceRequest.hpp>
#include <alibabacloud/models/OpenTrafficMirrorServiceResponseBody.hpp>
#include <alibabacloud/models/OpenTrafficMirrorServiceResponse.hpp>
#include <alibabacloud/models/PublishVpcRouteEntriesRequest.hpp>
#include <alibabacloud/models/PublishVpcRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/PublishVpcRouteEntriesResponse.hpp>
#include <alibabacloud/models/PublishVpnRouteEntryRequest.hpp>
#include <alibabacloud/models/PublishVpnRouteEntryResponseBody.hpp>
#include <alibabacloud/models/PublishVpnRouteEntryResponse.hpp>
#include <alibabacloud/models/RecoverPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/RecoverPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/RecoverPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/RecoverVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/RecoverVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/RecoverVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/ReleaseEipAddressRequest.hpp>
#include <alibabacloud/models/ReleaseEipAddressResponseBody.hpp>
#include <alibabacloud/models/ReleaseEipAddressResponse.hpp>
#include <alibabacloud/models/ReleaseEipSegmentAddressRequest.hpp>
#include <alibabacloud/models/ReleaseEipSegmentAddressResponseBody.hpp>
#include <alibabacloud/models/ReleaseEipSegmentAddressResponse.hpp>
#include <alibabacloud/models/ReleaseIpv6AddressRequest.hpp>
#include <alibabacloud/models/ReleaseIpv6AddressResponseBody.hpp>
#include <alibabacloud/models/ReleaseIpv6AddressResponse.hpp>
#include <alibabacloud/models/RemoveCommonBandwidthPackageIpRequest.hpp>
#include <alibabacloud/models/RemoveCommonBandwidthPackageIpResponseBody.hpp>
#include <alibabacloud/models/RemoveCommonBandwidthPackageIpResponse.hpp>
#include <alibabacloud/models/RemoveGlobalAccelerationInstanceIpRequest.hpp>
#include <alibabacloud/models/RemoveGlobalAccelerationInstanceIpResponseBody.hpp>
#include <alibabacloud/models/RemoveGlobalAccelerationInstanceIpResponse.hpp>
#include <alibabacloud/models/RemoveIPv6TranslatorAclListEntryRequest.hpp>
#include <alibabacloud/models/RemoveIPv6TranslatorAclListEntryResponseBody.hpp>
#include <alibabacloud/models/RemoveIPv6TranslatorAclListEntryResponse.hpp>
#include <alibabacloud/models/RemoveSourcesFromTrafficMirrorSessionRequest.hpp>
#include <alibabacloud/models/RemoveSourcesFromTrafficMirrorSessionResponseBody.hpp>
#include <alibabacloud/models/RemoveSourcesFromTrafficMirrorSessionResponse.hpp>
#include <alibabacloud/models/ReplaceVpcDhcpOptionsSetRequest.hpp>
#include <alibabacloud/models/ReplaceVpcDhcpOptionsSetResponseBody.hpp>
#include <alibabacloud/models/ReplaceVpcDhcpOptionsSetResponse.hpp>
#include <alibabacloud/models/RetryVpcPrefixListAssociationRequest.hpp>
#include <alibabacloud/models/RetryVpcPrefixListAssociationResponseBody.hpp>
#include <alibabacloud/models/RetryVpcPrefixListAssociationResponse.hpp>
#include <alibabacloud/models/RevokeInstanceFromCenRequest.hpp>
#include <alibabacloud/models/RevokeInstanceFromCenResponseBody.hpp>
#include <alibabacloud/models/RevokeInstanceFromCenResponse.hpp>
#include <alibabacloud/models/RevokeInstanceFromVbrRequest.hpp>
#include <alibabacloud/models/RevokeInstanceFromVbrShrinkRequest.hpp>
#include <alibabacloud/models/RevokeInstanceFromVbrResponseBody.hpp>
#include <alibabacloud/models/RevokeInstanceFromVbrResponse.hpp>
#include <alibabacloud/models/SecondApplyPhysicalConnectionLoaRequest.hpp>
#include <alibabacloud/models/SecondApplyPhysicalConnectionLoaResponseBody.hpp>
#include <alibabacloud/models/SecondApplyPhysicalConnectionLoaResponse.hpp>
#include <alibabacloud/models/SetHighDefinitionMonitorLogStatusRequest.hpp>
#include <alibabacloud/models/SetHighDefinitionMonitorLogStatusResponseBody.hpp>
#include <alibabacloud/models/SetHighDefinitionMonitorLogStatusResponse.hpp>
#include <alibabacloud/models/StartFailoverTestJobRequest.hpp>
#include <alibabacloud/models/StartFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/StartFailoverTestJobResponse.hpp>
#include <alibabacloud/models/StopFailoverTestJobRequest.hpp>
#include <alibabacloud/models/StopFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/StopFailoverTestJobResponse.hpp>
#include <alibabacloud/models/SwitchActiveRouteTargetRequest.hpp>
#include <alibabacloud/models/SwitchActiveRouteTargetResponseBody.hpp>
#include <alibabacloud/models/SwitchActiveRouteTargetResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/TagResourcesForExpressConnectRequest.hpp>
#include <alibabacloud/models/TagResourcesForExpressConnectResponseBody.hpp>
#include <alibabacloud/models/TagResourcesForExpressConnectResponse.hpp>
#include <alibabacloud/models/TerminatePhysicalConnectionRequest.hpp>
#include <alibabacloud/models/TerminatePhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/TerminatePhysicalConnectionResponse.hpp>
#include <alibabacloud/models/TerminateVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/TerminateVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/TerminateVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/TransformEipSegmentToPublicIpAddressPoolRequest.hpp>
#include <alibabacloud/models/TransformEipSegmentToPublicIpAddressPoolResponseBody.hpp>
#include <alibabacloud/models/TransformEipSegmentToPublicIpAddressPoolResponse.hpp>
#include <alibabacloud/models/UnTagResourcesRequest.hpp>
#include <alibabacloud/models/UnTagResourcesResponseBody.hpp>
#include <alibabacloud/models/UnTagResourcesResponse.hpp>
#include <alibabacloud/models/UnassociateEipAddressRequest.hpp>
#include <alibabacloud/models/UnassociateEipAddressResponseBody.hpp>
#include <alibabacloud/models/UnassociateEipAddressResponse.hpp>
#include <alibabacloud/models/UnassociateGlobalAccelerationInstanceRequest.hpp>
#include <alibabacloud/models/UnassociateGlobalAccelerationInstanceResponseBody.hpp>
#include <alibabacloud/models/UnassociateGlobalAccelerationInstanceResponse.hpp>
#include <alibabacloud/models/UnassociateHaVipRequest.hpp>
#include <alibabacloud/models/UnassociateHaVipResponseBody.hpp>
#include <alibabacloud/models/UnassociateHaVipResponse.hpp>
#include <alibabacloud/models/UnassociateNetworkAclRequest.hpp>
#include <alibabacloud/models/UnassociateNetworkAclResponseBody.hpp>
#include <alibabacloud/models/UnassociateNetworkAclResponse.hpp>
#include <alibabacloud/models/UnassociatePhysicalConnectionFromVirtualBorderRouterRequest.hpp>
#include <alibabacloud/models/UnassociatePhysicalConnectionFromVirtualBorderRouterResponseBody.hpp>
#include <alibabacloud/models/UnassociatePhysicalConnectionFromVirtualBorderRouterResponse.hpp>
#include <alibabacloud/models/UnassociateRouteTableRequest.hpp>
#include <alibabacloud/models/UnassociateRouteTableResponseBody.hpp>
#include <alibabacloud/models/UnassociateRouteTableResponse.hpp>
#include <alibabacloud/models/UnassociateVpcCidrBlockRequest.hpp>
#include <alibabacloud/models/UnassociateVpcCidrBlockResponseBody.hpp>
#include <alibabacloud/models/UnassociateVpcCidrBlockResponse.hpp>
#include <alibabacloud/models/UntagResourcesForExpressConnectRequest.hpp>
#include <alibabacloud/models/UntagResourcesForExpressConnectResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesForExpressConnectResponse.hpp>
#include <alibabacloud/models/UpdateDhcpOptionsSetAttributeRequest.hpp>
#include <alibabacloud/models/UpdateDhcpOptionsSetAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateDhcpOptionsSetAttributeResponse.hpp>
#include <alibabacloud/models/UpdateFailoverTestJobRequest.hpp>
#include <alibabacloud/models/UpdateFailoverTestJobResponseBody.hpp>
#include <alibabacloud/models/UpdateFailoverTestJobResponse.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTableEntryAttributeRequest.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTableEntryAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateGatewayRouteTableEntryAttributeResponse.hpp>
#include <alibabacloud/models/UpdateIpsecServerRequest.hpp>
#include <alibabacloud/models/UpdateIpsecServerResponseBody.hpp>
#include <alibabacloud/models/UpdateIpsecServerResponse.hpp>
#include <alibabacloud/models/UpdateIpv4GatewayAttributeRequest.hpp>
#include <alibabacloud/models/UpdateIpv4GatewayAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateIpv4GatewayAttributeResponse.hpp>
#include <alibabacloud/models/UpdateNatGatewayNatTypeRequest.hpp>
#include <alibabacloud/models/UpdateNatGatewayNatTypeResponseBody.hpp>
#include <alibabacloud/models/UpdateNatGatewayNatTypeResponse.hpp>
#include <alibabacloud/models/UpdateNetworkAclEntriesRequest.hpp>
#include <alibabacloud/models/UpdateNetworkAclEntriesResponseBody.hpp>
#include <alibabacloud/models/UpdateNetworkAclEntriesResponse.hpp>
#include <alibabacloud/models/UpdatePublicIpAddressPoolAttributeRequest.hpp>
#include <alibabacloud/models/UpdatePublicIpAddressPoolAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdatePublicIpAddressPoolAttributeResponse.hpp>
#include <alibabacloud/models/UpdateRouteTargetGroupRequest.hpp>
#include <alibabacloud/models/UpdateRouteTargetGroupResponseBody.hpp>
#include <alibabacloud/models/UpdateRouteTargetGroupResponse.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterAttributeRequest.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterAttributeResponse.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterRuleAttributeRequest.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterRuleAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorFilterRuleAttributeResponse.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorSessionAttributeRequest.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorSessionAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateTrafficMirrorSessionAttributeResponse.hpp>
#include <alibabacloud/models/UpdateVirtualBorderBandwidthRequest.hpp>
#include <alibabacloud/models/UpdateVirtualBorderBandwidthResponseBody.hpp>
#include <alibabacloud/models/UpdateVirtualBorderBandwidthResponse.hpp>
#include <alibabacloud/models/UpdateVirtualPhysicalConnectionRequest.hpp>
#include <alibabacloud/models/UpdateVirtualPhysicalConnectionResponseBody.hpp>
#include <alibabacloud/models/UpdateVirtualPhysicalConnectionResponse.hpp>
#include <alibabacloud/models/UpdateVpcGatewayEndpointAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcGatewayEndpointAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcGatewayEndpointAttributeResponse.hpp>
#include <alibabacloud/models/VpcDescribeVpcNatGatewayNetworkInterfaceQuotaRequest.hpp>
#include <alibabacloud/models/VpcDescribeVpcNatGatewayNetworkInterfaceQuotaResponseBody.hpp>
#include <alibabacloud/models/VpcDescribeVpcNatGatewayNetworkInterfaceQuotaResponse.hpp>
#include <alibabacloud/models/WithdrawVpcPublishedRouteEntriesRequest.hpp>
#include <alibabacloud/models/WithdrawVpcPublishedRouteEntriesResponseBody.hpp>
#include <alibabacloud/models/WithdrawVpcPublishedRouteEntriesResponse.hpp>

#endif
