// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_RTC20180111MODEL_HPP_
#define ALIBABACLOUD_RTC20180111MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddRecordTemplateRequest.hpp>
#include <alibabacloud/models/AddRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/AddRecordTemplateResponse.hpp>
#include <alibabacloud/models/CreateAppAgentTemplateRequest.hpp>
#include <alibabacloud/models/CreateAppAgentTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppAgentTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateAppAgentTemplateResponse.hpp>
#include <alibabacloud/models/CreateAppLayoutRequest.hpp>
#include <alibabacloud/models/CreateAppLayoutShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppLayoutResponseBody.hpp>
#include <alibabacloud/models/CreateAppLayoutResponse.hpp>
#include <alibabacloud/models/CreateAppRecordTemplateRequest.hpp>
#include <alibabacloud/models/CreateAppRecordTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateAppRecordTemplateResponse.hpp>
#include <alibabacloud/models/CreateAppStreamingOutTemplateRequest.hpp>
#include <alibabacloud/models/CreateAppStreamingOutTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppStreamingOutTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateAppStreamingOutTemplateResponse.hpp>
#include <alibabacloud/models/CreateAppViewTemplateRequest.hpp>
#include <alibabacloud/models/CreateAppViewTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppViewTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateAppViewTemplateResponse.hpp>
#include <alibabacloud/models/CreateAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/CreateAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/CreateAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/CreateCloudNotePhrasesRequest.hpp>
#include <alibabacloud/models/CreateCloudNotePhrasesShrinkRequest.hpp>
#include <alibabacloud/models/CreateCloudNotePhrasesResponseBody.hpp>
#include <alibabacloud/models/CreateCloudNotePhrasesResponse.hpp>
#include <alibabacloud/models/CreateEventSubscribeRequest.hpp>
#include <alibabacloud/models/CreateEventSubscribeResponseBody.hpp>
#include <alibabacloud/models/CreateEventSubscribeResponse.hpp>
#include <alibabacloud/models/CreateMPULayoutRequest.hpp>
#include <alibabacloud/models/CreateMPULayoutResponseBody.hpp>
#include <alibabacloud/models/CreateMPULayoutResponse.hpp>
#include <alibabacloud/models/DeleteAppAgentTemplateRequest.hpp>
#include <alibabacloud/models/DeleteAppAgentTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteAppAgentTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAppLayoutRequest.hpp>
#include <alibabacloud/models/DeleteAppLayoutShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAppLayoutResponseBody.hpp>
#include <alibabacloud/models/DeleteAppLayoutResponse.hpp>
#include <alibabacloud/models/DeleteAppRecordTemplateRequest.hpp>
#include <alibabacloud/models/DeleteAppRecordTemplateShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAppRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteAppRecordTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAppStreamingOutTemplateRequest.hpp>
#include <alibabacloud/models/DeleteAppStreamingOutTemplateShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAppStreamingOutTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteAppStreamingOutTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAppViewTemplateRequest.hpp>
#include <alibabacloud/models/DeleteAppViewTemplateShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAppViewTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteAppViewTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/DeleteAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/DeleteAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/DeleteChannelRequest.hpp>
#include <alibabacloud/models/DeleteChannelResponseBody.hpp>
#include <alibabacloud/models/DeleteChannelResponse.hpp>
#include <alibabacloud/models/DeleteCloudNotePhrasesRequest.hpp>
#include <alibabacloud/models/DeleteCloudNotePhrasesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteCloudNotePhrasesResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudNotePhrasesResponse.hpp>
#include <alibabacloud/models/DeleteEventSubscribeRequest.hpp>
#include <alibabacloud/models/DeleteEventSubscribeResponseBody.hpp>
#include <alibabacloud/models/DeleteEventSubscribeResponse.hpp>
#include <alibabacloud/models/DeleteMPULayoutRequest.hpp>
#include <alibabacloud/models/DeleteMPULayoutResponseBody.hpp>
#include <alibabacloud/models/DeleteMPULayoutResponse.hpp>
#include <alibabacloud/models/DeleteRecordTemplateRequest.hpp>
#include <alibabacloud/models/DeleteRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/DeleteRecordTemplateResponse.hpp>
#include <alibabacloud/models/DescribeAllCallbackResponseBody.hpp>
#include <alibabacloud/models/DescribeAllCallbackResponse.hpp>
#include <alibabacloud/models/DescribeAppAgentFunctionStatusRequest.hpp>
#include <alibabacloud/models/DescribeAppAgentFunctionStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAppAgentFunctionStatusResponse.hpp>
#include <alibabacloud/models/DescribeAppAgentTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeAppAgentTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppAgentTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeAppCallStatusRequest.hpp>
#include <alibabacloud/models/DescribeAppCallStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAppCallStatusResponse.hpp>
#include <alibabacloud/models/DescribeAppCallbackSecretKeyRequest.hpp>
#include <alibabacloud/models/DescribeAppCallbackSecretKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeAppCallbackSecretKeyResponse.hpp>
#include <alibabacloud/models/DescribeAppKeyRequest.hpp>
#include <alibabacloud/models/DescribeAppKeyResponseBody.hpp>
#include <alibabacloud/models/DescribeAppKeyResponse.hpp>
#include <alibabacloud/models/DescribeAppLayoutsRequest.hpp>
#include <alibabacloud/models/DescribeAppLayoutsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeAppLayoutsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppLayoutsResponse.hpp>
#include <alibabacloud/models/DescribeAppLiveStreamStatusRequest.hpp>
#include <alibabacloud/models/DescribeAppLiveStreamStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAppLiveStreamStatusResponse.hpp>
#include <alibabacloud/models/DescribeAppRecordStatusRequest.hpp>
#include <alibabacloud/models/DescribeAppRecordStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAppRecordStatusResponse.hpp>
#include <alibabacloud/models/DescribeAppRecordTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeAppRecordTemplatesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeAppRecordTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppRecordTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeAppRecordingFilesRequest.hpp>
#include <alibabacloud/models/DescribeAppRecordingFilesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeAppRecordingFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppRecordingFilesResponse.hpp>
#include <alibabacloud/models/DescribeAppStreamingOutTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeAppStreamingOutTemplatesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeAppStreamingOutTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppStreamingOutTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeAppViewStatusRequest.hpp>
#include <alibabacloud/models/DescribeAppViewStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeAppViewStatusResponse.hpp>
#include <alibabacloud/models/DescribeAppViewTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeAppViewTemplatesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeAppViewTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeAppViewTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeAppsRequest.hpp>
#include <alibabacloud/models/DescribeAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppsResponse.hpp>
#include <alibabacloud/models/DescribeAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/DescribeAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/DescribeAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/DescribeCallRequest.hpp>
#include <alibabacloud/models/DescribeCallResponseBody.hpp>
#include <alibabacloud/models/DescribeCallResponse.hpp>
#include <alibabacloud/models/DescribeCallListRequest.hpp>
#include <alibabacloud/models/DescribeCallListResponseBody.hpp>
#include <alibabacloud/models/DescribeCallListResponse.hpp>
#include <alibabacloud/models/DescribeCallbacksRequest.hpp>
#include <alibabacloud/models/DescribeCallbacksResponseBody.hpp>
#include <alibabacloud/models/DescribeCallbacksResponse.hpp>
#include <alibabacloud/models/DescribeChannelRequest.hpp>
#include <alibabacloud/models/DescribeChannelResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelResponse.hpp>
#include <alibabacloud/models/DescribeChannelAllUsersRequest.hpp>
#include <alibabacloud/models/DescribeChannelAllUsersResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelAllUsersResponse.hpp>
#include <alibabacloud/models/DescribeChannelAreaDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeChannelAreaDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelAreaDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeChannelDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeChannelDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeChannelOverallDataRequest.hpp>
#include <alibabacloud/models/DescribeChannelOverallDataResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelOverallDataResponse.hpp>
#include <alibabacloud/models/DescribeChannelParticipantsRequest.hpp>
#include <alibabacloud/models/DescribeChannelParticipantsResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelParticipantsResponse.hpp>
#include <alibabacloud/models/DescribeChannelTopPubUserListRequest.hpp>
#include <alibabacloud/models/DescribeChannelTopPubUserListResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelTopPubUserListResponse.hpp>
#include <alibabacloud/models/DescribeChannelUserRequest.hpp>
#include <alibabacloud/models/DescribeChannelUserResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelUserResponse.hpp>
#include <alibabacloud/models/DescribeChannelUserMetricsRequest.hpp>
#include <alibabacloud/models/DescribeChannelUserMetricsResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelUserMetricsResponse.hpp>
#include <alibabacloud/models/DescribeChannelUsersRequest.hpp>
#include <alibabacloud/models/DescribeChannelUsersResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelUsersResponse.hpp>
#include <alibabacloud/models/DescribeChannelsRequest.hpp>
#include <alibabacloud/models/DescribeChannelsResponseBody.hpp>
#include <alibabacloud/models/DescribeChannelsResponse.hpp>
#include <alibabacloud/models/DescribeCloudNotePhrasesRequest.hpp>
#include <alibabacloud/models/DescribeCloudNotePhrasesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeCloudNotePhrasesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudNotePhrasesResponse.hpp>
#include <alibabacloud/models/DescribeCloudNotesRequest.hpp>
#include <alibabacloud/models/DescribeCloudNotesShrinkRequest.hpp>
#include <alibabacloud/models/DescribeCloudNotesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudNotesResponse.hpp>
#include <alibabacloud/models/DescribeCloudRecordStatusRequest.hpp>
#include <alibabacloud/models/DescribeCloudRecordStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudRecordStatusResponse.hpp>
#include <alibabacloud/models/DescribeEndPointEventListRequest.hpp>
#include <alibabacloud/models/DescribeEndPointEventListResponseBody.hpp>
#include <alibabacloud/models/DescribeEndPointEventListResponse.hpp>
#include <alibabacloud/models/DescribeEndPointMetricDataRequest.hpp>
#include <alibabacloud/models/DescribeEndPointMetricDataResponseBody.hpp>
#include <alibabacloud/models/DescribeEndPointMetricDataResponse.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisFactorDistributionStatRequest.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisFactorDistributionStatResponseBody.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisFactorDistributionStatResponse.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisOverallDataRequest.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisOverallDataResponseBody.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisOverallDataResponse.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserDetailRequest.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserDetailResponse.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserListRequest.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserListResponseBody.hpp>
#include <alibabacloud/models/DescribeFaultDiagnosisUserListResponse.hpp>
#include <alibabacloud/models/DescribeMPULayoutInfoListRequest.hpp>
#include <alibabacloud/models/DescribeMPULayoutInfoListResponseBody.hpp>
#include <alibabacloud/models/DescribeMPULayoutInfoListResponse.hpp>
#include <alibabacloud/models/DescribePubUserListBySubUserRequest.hpp>
#include <alibabacloud/models/DescribePubUserListBySubUserResponseBody.hpp>
#include <alibabacloud/models/DescribePubUserListBySubUserResponse.hpp>
#include <alibabacloud/models/DescribeQoeMetricDataRequest.hpp>
#include <alibabacloud/models/DescribeQoeMetricDataResponseBody.hpp>
#include <alibabacloud/models/DescribeQoeMetricDataResponse.hpp>
#include <alibabacloud/models/DescribeQualityAreaDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeQualityAreaDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeQualityAreaDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeQualityDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeQualityDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeQualityDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeQualityOsSdkVersionDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeQualityOsSdkVersionDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeQualityOsSdkVersionDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeQualityOverallDataRequest.hpp>
#include <alibabacloud/models/DescribeQualityOverallDataResponseBody.hpp>
#include <alibabacloud/models/DescribeQualityOverallDataResponse.hpp>
#include <alibabacloud/models/DescribeRecordFilesRequest.hpp>
#include <alibabacloud/models/DescribeRecordFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordFilesResponse.hpp>
#include <alibabacloud/models/DescribeRecordTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeRecordTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeRecordTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeRtcChannelListRequest.hpp>
#include <alibabacloud/models/DescribeRtcChannelListResponseBody.hpp>
#include <alibabacloud/models/DescribeRtcChannelListResponse.hpp>
#include <alibabacloud/models/DescribeRtcChannelMetricRequest.hpp>
#include <alibabacloud/models/DescribeRtcChannelMetricResponseBody.hpp>
#include <alibabacloud/models/DescribeRtcChannelMetricResponse.hpp>
#include <alibabacloud/models/DescribeRtcDurationDataRequest.hpp>
#include <alibabacloud/models/DescribeRtcDurationDataResponseBody.hpp>
#include <alibabacloud/models/DescribeRtcDurationDataResponse.hpp>
#include <alibabacloud/models/DescribeRtcPeakChannelCntDataRequest.hpp>
#include <alibabacloud/models/DescribeRtcPeakChannelCntDataResponseBody.hpp>
#include <alibabacloud/models/DescribeRtcPeakChannelCntDataResponse.hpp>
#include <alibabacloud/models/DescribeRtcUserCntDataRequest.hpp>
#include <alibabacloud/models/DescribeRtcUserCntDataResponseBody.hpp>
#include <alibabacloud/models/DescribeRtcUserCntDataResponse.hpp>
#include <alibabacloud/models/DescribeStreamingOutStatusRequest.hpp>
#include <alibabacloud/models/DescribeStreamingOutStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeStreamingOutStatusResponse.hpp>
#include <alibabacloud/models/DescribeSystemLayoutListRequest.hpp>
#include <alibabacloud/models/DescribeSystemLayoutListResponseBody.hpp>
#include <alibabacloud/models/DescribeSystemLayoutListResponse.hpp>
#include <alibabacloud/models/DescribeUsageAreaDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeUsageAreaDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeUsageAreaDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeUsageDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeUsageDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeUsageDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeUsageOsSdkVersionDistributionStatDataRequest.hpp>
#include <alibabacloud/models/DescribeUsageOsSdkVersionDistributionStatDataResponseBody.hpp>
#include <alibabacloud/models/DescribeUsageOsSdkVersionDistributionStatDataResponse.hpp>
#include <alibabacloud/models/DescribeUsageOverallDataRequest.hpp>
#include <alibabacloud/models/DescribeUsageOverallDataResponseBody.hpp>
#include <alibabacloud/models/DescribeUsageOverallDataResponse.hpp>
#include <alibabacloud/models/DescribeUserInfoInChannelRequest.hpp>
#include <alibabacloud/models/DescribeUserInfoInChannelResponseBody.hpp>
#include <alibabacloud/models/DescribeUserInfoInChannelResponse.hpp>
#include <alibabacloud/models/DisableAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/DisableAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/DisableAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/EnableAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/EnableAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/EnableAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/GetAgentRequest.hpp>
#include <alibabacloud/models/GetAgentResponseBody.hpp>
#include <alibabacloud/models/GetAgentResponse.hpp>
#include <alibabacloud/models/GetMPUTaskStatusRequest.hpp>
#include <alibabacloud/models/GetMPUTaskStatusResponseBody.hpp>
#include <alibabacloud/models/GetMPUTaskStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppRequest.hpp>
#include <alibabacloud/models/ModifyAppResponseBody.hpp>
#include <alibabacloud/models/ModifyAppResponse.hpp>
#include <alibabacloud/models/ModifyAppAgentFunctionStatusRequest.hpp>
#include <alibabacloud/models/ModifyAppAgentFunctionStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyAppAgentFunctionStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppAgentTemplateRequest.hpp>
#include <alibabacloud/models/ModifyAppAgentTemplateShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppAgentTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyAppAgentTemplateResponse.hpp>
#include <alibabacloud/models/ModifyAppCallbackStatusRequest.hpp>
#include <alibabacloud/models/ModifyAppCallbackStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyAppCallbackStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppLayoutRequest.hpp>
#include <alibabacloud/models/ModifyAppLayoutShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppLayoutResponseBody.hpp>
#include <alibabacloud/models/ModifyAppLayoutResponse.hpp>
#include <alibabacloud/models/ModifyAppLiveStreamStatusRequest.hpp>
#include <alibabacloud/models/ModifyAppLiveStreamStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyAppLiveStreamStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppRecordStatusRequest.hpp>
#include <alibabacloud/models/ModifyAppRecordStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyAppRecordStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppRecordTemplateRequest.hpp>
#include <alibabacloud/models/ModifyAppRecordTemplateShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyAppRecordTemplateResponse.hpp>
#include <alibabacloud/models/ModifyAppStreamingOutTemplateRequest.hpp>
#include <alibabacloud/models/ModifyAppStreamingOutTemplateShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppStreamingOutTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyAppStreamingOutTemplateResponse.hpp>
#include <alibabacloud/models/ModifyAppViewStatusRequest.hpp>
#include <alibabacloud/models/ModifyAppViewStatusResponseBody.hpp>
#include <alibabacloud/models/ModifyAppViewStatusResponse.hpp>
#include <alibabacloud/models/ModifyAppViewTemplateRequest.hpp>
#include <alibabacloud/models/ModifyAppViewTemplateShrinkRequest.hpp>
#include <alibabacloud/models/ModifyAppViewTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifyAppViewTemplateResponse.hpp>
#include <alibabacloud/models/ModifyCallbackMetaRequest.hpp>
#include <alibabacloud/models/ModifyCallbackMetaShrinkRequest.hpp>
#include <alibabacloud/models/ModifyCallbackMetaResponseBody.hpp>
#include <alibabacloud/models/ModifyCallbackMetaResponse.hpp>
#include <alibabacloud/models/ModifyCloudNotePhrasesRequest.hpp>
#include <alibabacloud/models/ModifyCloudNotePhrasesShrinkRequest.hpp>
#include <alibabacloud/models/ModifyCloudNotePhrasesResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudNotePhrasesResponse.hpp>
#include <alibabacloud/models/ModifyMPULayoutRequest.hpp>
#include <alibabacloud/models/ModifyMPULayoutResponseBody.hpp>
#include <alibabacloud/models/ModifyMPULayoutResponse.hpp>
#include <alibabacloud/models/ModifyStreamingPropertyRequest.hpp>
#include <alibabacloud/models/ModifyStreamingPropertyShrinkRequest.hpp>
#include <alibabacloud/models/ModifyStreamingPropertyResponseBody.hpp>
#include <alibabacloud/models/ModifyStreamingPropertyResponse.hpp>
#include <alibabacloud/models/ModifyViewLayoutRequest.hpp>
#include <alibabacloud/models/ModifyViewLayoutShrinkRequest.hpp>
#include <alibabacloud/models/ModifyViewLayoutResponseBody.hpp>
#include <alibabacloud/models/ModifyViewLayoutResponse.hpp>
#include <alibabacloud/models/NotifyAgentRequest.hpp>
#include <alibabacloud/models/NotifyAgentShrinkRequest.hpp>
#include <alibabacloud/models/NotifyAgentResponseBody.hpp>
#include <alibabacloud/models/NotifyAgentResponse.hpp>
#include <alibabacloud/models/RemoveTerminalsRequest.hpp>
#include <alibabacloud/models/RemoveTerminalsResponseBody.hpp>
#include <alibabacloud/models/RemoveTerminalsResponse.hpp>
#include <alibabacloud/models/RemoveUsersRequest.hpp>
#include <alibabacloud/models/RemoveUsersResponseBody.hpp>
#include <alibabacloud/models/RemoveUsersResponse.hpp>
#include <alibabacloud/models/RtcCancelSipInviteRequest.hpp>
#include <alibabacloud/models/RtcCancelSipInviteResponseBody.hpp>
#include <alibabacloud/models/RtcCancelSipInviteResponse.hpp>
#include <alibabacloud/models/RtcSipInviteMemberRequest.hpp>
#include <alibabacloud/models/RtcSipInviteMemberResponseBody.hpp>
#include <alibabacloud/models/RtcSipInviteMemberResponse.hpp>
#include <alibabacloud/models/RtcSipMuteRequest.hpp>
#include <alibabacloud/models/RtcSipMuteResponseBody.hpp>
#include <alibabacloud/models/RtcSipMuteResponse.hpp>
#include <alibabacloud/models/StartAgentRequest.hpp>
#include <alibabacloud/models/StartAgentShrinkRequest.hpp>
#include <alibabacloud/models/StartAgentResponseBody.hpp>
#include <alibabacloud/models/StartAgentResponse.hpp>
#include <alibabacloud/models/StartCategoryCallbackRequest.hpp>
#include <alibabacloud/models/StartCategoryCallbackShrinkRequest.hpp>
#include <alibabacloud/models/StartCategoryCallbackResponseBody.hpp>
#include <alibabacloud/models/StartCategoryCallbackResponse.hpp>
#include <alibabacloud/models/StartCloudNoteRequest.hpp>
#include <alibabacloud/models/StartCloudNoteShrinkRequest.hpp>
#include <alibabacloud/models/StartCloudNoteResponseBody.hpp>
#include <alibabacloud/models/StartCloudNoteResponse.hpp>
#include <alibabacloud/models/StartCloudRecordRequest.hpp>
#include <alibabacloud/models/StartCloudRecordShrinkRequest.hpp>
#include <alibabacloud/models/StartCloudRecordResponseBody.hpp>
#include <alibabacloud/models/StartCloudRecordResponse.hpp>
#include <alibabacloud/models/StartMPUTaskRequest.hpp>
#include <alibabacloud/models/StartMPUTaskResponseBody.hpp>
#include <alibabacloud/models/StartMPUTaskResponse.hpp>
#include <alibabacloud/models/StartRecordTaskRequest.hpp>
#include <alibabacloud/models/StartRecordTaskResponseBody.hpp>
#include <alibabacloud/models/StartRecordTaskResponse.hpp>
#include <alibabacloud/models/StartStreamingOutRequest.hpp>
#include <alibabacloud/models/StartStreamingOutShrinkRequest.hpp>
#include <alibabacloud/models/StartStreamingOutResponseBody.hpp>
#include <alibabacloud/models/StartStreamingOutResponse.hpp>
#include <alibabacloud/models/StartViewRequest.hpp>
#include <alibabacloud/models/StartViewShrinkRequest.hpp>
#include <alibabacloud/models/StartViewResponseBody.hpp>
#include <alibabacloud/models/StartViewResponse.hpp>
#include <alibabacloud/models/StopAgentRequest.hpp>
#include <alibabacloud/models/StopAgentResponseBody.hpp>
#include <alibabacloud/models/StopAgentResponse.hpp>
#include <alibabacloud/models/StopCategoryCallbackRequest.hpp>
#include <alibabacloud/models/StopCategoryCallbackShrinkRequest.hpp>
#include <alibabacloud/models/StopCategoryCallbackResponseBody.hpp>
#include <alibabacloud/models/StopCategoryCallbackResponse.hpp>
#include <alibabacloud/models/StopChannelRequest.hpp>
#include <alibabacloud/models/StopChannelResponseBody.hpp>
#include <alibabacloud/models/StopChannelResponse.hpp>
#include <alibabacloud/models/StopCloudNoteRequest.hpp>
#include <alibabacloud/models/StopCloudNoteResponseBody.hpp>
#include <alibabacloud/models/StopCloudNoteResponse.hpp>
#include <alibabacloud/models/StopCloudRecordRequest.hpp>
#include <alibabacloud/models/StopCloudRecordResponseBody.hpp>
#include <alibabacloud/models/StopCloudRecordResponse.hpp>
#include <alibabacloud/models/StopMPUTaskRequest.hpp>
#include <alibabacloud/models/StopMPUTaskResponseBody.hpp>
#include <alibabacloud/models/StopMPUTaskResponse.hpp>
#include <alibabacloud/models/StopRecordTaskRequest.hpp>
#include <alibabacloud/models/StopRecordTaskResponseBody.hpp>
#include <alibabacloud/models/StopRecordTaskResponse.hpp>
#include <alibabacloud/models/StopStreamingOutRequest.hpp>
#include <alibabacloud/models/StopStreamingOutResponseBody.hpp>
#include <alibabacloud/models/StopStreamingOutResponse.hpp>
#include <alibabacloud/models/StopViewRequest.hpp>
#include <alibabacloud/models/StopViewResponseBody.hpp>
#include <alibabacloud/models/StopViewResponse.hpp>
#include <alibabacloud/models/UpdateAgentRequest.hpp>
#include <alibabacloud/models/UpdateAgentShrinkRequest.hpp>
#include <alibabacloud/models/UpdateAgentResponseBody.hpp>
#include <alibabacloud/models/UpdateAgentResponse.hpp>
#include <alibabacloud/models/UpdateAutoLiveStreamRuleRequest.hpp>
#include <alibabacloud/models/UpdateAutoLiveStreamRuleResponseBody.hpp>
#include <alibabacloud/models/UpdateAutoLiveStreamRuleResponse.hpp>
#include <alibabacloud/models/UpdateCloudRecordRequest.hpp>
#include <alibabacloud/models/UpdateCloudRecordShrinkRequest.hpp>
#include <alibabacloud/models/UpdateCloudRecordResponseBody.hpp>
#include <alibabacloud/models/UpdateCloudRecordResponse.hpp>
#include <alibabacloud/models/UpdateMPUTaskRequest.hpp>
#include <alibabacloud/models/UpdateMPUTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateMPUTaskResponse.hpp>
#include <alibabacloud/models/UpdateRecordTaskRequest.hpp>
#include <alibabacloud/models/UpdateRecordTaskResponseBody.hpp>
#include <alibabacloud/models/UpdateRecordTaskResponse.hpp>
#include <alibabacloud/models/UpdateRecordTemplateRequest.hpp>
#include <alibabacloud/models/UpdateRecordTemplateResponseBody.hpp>
#include <alibabacloud/models/UpdateRecordTemplateResponse.hpp>
#include <alibabacloud/models/UpdateStreamingOutRequest.hpp>
#include <alibabacloud/models/UpdateStreamingOutShrinkRequest.hpp>
#include <alibabacloud/models/UpdateStreamingOutResponseBody.hpp>
#include <alibabacloud/models/UpdateStreamingOutResponse.hpp>

#endif
