// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_OUTBOUNDBOT20251111MODEL_HPP_
#define ALIBABACLOUD_OUTBOUNDBOT20251111MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreateCloneVoiceRequest.hpp>
#include <alibabacloud/models/CreateCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/CreateCloneVoiceResponse.hpp>
#include <alibabacloud/models/CreateFlashSmsAccessProfileRequest.hpp>
#include <alibabacloud/models/CreateFlashSmsAccessProfileShrinkRequest.hpp>
#include <alibabacloud/models/CreateFlashSmsAccessProfileResponseBody.hpp>
#include <alibabacloud/models/CreateFlashSmsAccessProfileResponse.hpp>
#include <alibabacloud/models/CreateInstanceRequest.hpp>
#include <alibabacloud/models/CreateInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateInstanceResponse.hpp>
#include <alibabacloud/models/CreateOutboundCallRestrictionRequest.hpp>
#include <alibabacloud/models/CreateOutboundCallRestrictionShrinkRequest.hpp>
#include <alibabacloud/models/CreateOutboundCallRestrictionResponseBody.hpp>
#include <alibabacloud/models/CreateOutboundCallRestrictionResponse.hpp>
#include <alibabacloud/models/CreateScriptRequest.hpp>
#include <alibabacloud/models/CreateScriptResponseBody.hpp>
#include <alibabacloud/models/CreateScriptResponse.hpp>
#include <alibabacloud/models/CreateScriptVersionRequest.hpp>
#include <alibabacloud/models/CreateScriptVersionShrinkRequest.hpp>
#include <alibabacloud/models/CreateScriptVersionResponseBody.hpp>
#include <alibabacloud/models/CreateScriptVersionResponse.hpp>
#include <alibabacloud/models/CreateVoiceAccessProfileRequest.hpp>
#include <alibabacloud/models/CreateVoiceAccessProfileShrinkRequest.hpp>
#include <alibabacloud/models/CreateVoiceAccessProfileResponseBody.hpp>
#include <alibabacloud/models/CreateVoiceAccessProfileResponse.hpp>
#include <alibabacloud/models/DeleteCloneVoiceRequest.hpp>
#include <alibabacloud/models/DeleteCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/DeleteCloneVoiceResponse.hpp>
#include <alibabacloud/models/DeleteFlashSmsAccessProfileRequest.hpp>
#include <alibabacloud/models/DeleteFlashSmsAccessProfileResponseBody.hpp>
#include <alibabacloud/models/DeleteFlashSmsAccessProfileResponse.hpp>
#include <alibabacloud/models/DeleteInstanceRequest.hpp>
#include <alibabacloud/models/DeleteInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteInstanceResponse.hpp>
#include <alibabacloud/models/DeleteOutboundCallRestrictionRequest.hpp>
#include <alibabacloud/models/DeleteOutboundCallRestrictionShrinkRequest.hpp>
#include <alibabacloud/models/DeleteOutboundCallRestrictionResponseBody.hpp>
#include <alibabacloud/models/DeleteOutboundCallRestrictionResponse.hpp>
#include <alibabacloud/models/DeleteScriptRequest.hpp>
#include <alibabacloud/models/DeleteScriptResponseBody.hpp>
#include <alibabacloud/models/DeleteScriptResponse.hpp>
#include <alibabacloud/models/DeleteVoiceAccessProfileRequest.hpp>
#include <alibabacloud/models/DeleteVoiceAccessProfileResponseBody.hpp>
#include <alibabacloud/models/DeleteVoiceAccessProfileResponse.hpp>
#include <alibabacloud/models/DisableSubscriptionRequest.hpp>
#include <alibabacloud/models/DisableSubscriptionResponseBody.hpp>
#include <alibabacloud/models/DisableSubscriptionResponse.hpp>
#include <alibabacloud/models/GetInstanceRequest.hpp>
#include <alibabacloud/models/GetInstanceResponseBody.hpp>
#include <alibabacloud/models/GetInstanceResponse.hpp>
#include <alibabacloud/models/GetScriptProfileTemplateRequest.hpp>
#include <alibabacloud/models/GetScriptProfileTemplateResponseBody.hpp>
#include <alibabacloud/models/GetScriptProfileTemplateResponse.hpp>
#include <alibabacloud/models/GetSubscriptionRequest.hpp>
#include <alibabacloud/models/GetSubscriptionResponseBody.hpp>
#include <alibabacloud/models/GetSubscriptionResponse.hpp>
#include <alibabacloud/models/ListCloneVoiceModelsRequest.hpp>
#include <alibabacloud/models/ListCloneVoiceModelsResponseBody.hpp>
#include <alibabacloud/models/ListCloneVoiceModelsResponse.hpp>
#include <alibabacloud/models/ListCloneVoicesRequest.hpp>
#include <alibabacloud/models/ListCloneVoicesResponseBody.hpp>
#include <alibabacloud/models/ListCloneVoicesResponse.hpp>
#include <alibabacloud/models/ListFlashSmsAccessProfilesRequest.hpp>
#include <alibabacloud/models/ListFlashSmsAccessProfilesResponseBody.hpp>
#include <alibabacloud/models/ListFlashSmsAccessProfilesResponse.hpp>
#include <alibabacloud/models/ListFlashSmsProvidersRequest.hpp>
#include <alibabacloud/models/ListFlashSmsProvidersResponseBody.hpp>
#include <alibabacloud/models/ListFlashSmsProvidersResponse.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesRequest.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListFlashSmsTemplatesResponse.hpp>
#include <alibabacloud/models/ListInstancesRequest.hpp>
#include <alibabacloud/models/ListInstancesResponseBody.hpp>
#include <alibabacloud/models/ListInstancesResponse.hpp>
#include <alibabacloud/models/ListOutboundCallRestrictionsRequest.hpp>
#include <alibabacloud/models/ListOutboundCallRestrictionsResponseBody.hpp>
#include <alibabacloud/models/ListOutboundCallRestrictionsResponse.hpp>
#include <alibabacloud/models/ListScriptProfileTemplatesRequest.hpp>
#include <alibabacloud/models/ListScriptProfileTemplatesResponseBody.hpp>
#include <alibabacloud/models/ListScriptProfileTemplatesResponse.hpp>
#include <alibabacloud/models/ListScriptsRequest.hpp>
#include <alibabacloud/models/ListScriptsShrinkRequest.hpp>
#include <alibabacloud/models/ListScriptsResponseBody.hpp>
#include <alibabacloud/models/ListScriptsResponse.hpp>
#include <alibabacloud/models/ListScriptsByFlowRequest.hpp>
#include <alibabacloud/models/ListScriptsByFlowResponseBody.hpp>
#include <alibabacloud/models/ListScriptsByFlowResponse.hpp>
#include <alibabacloud/models/ListSystemConfigsRequest.hpp>
#include <alibabacloud/models/ListSystemConfigsResponseBody.hpp>
#include <alibabacloud/models/ListSystemConfigsResponse.hpp>
#include <alibabacloud/models/ListVoiceAccessProfilesRequest.hpp>
#include <alibabacloud/models/ListVoiceAccessProfilesResponseBody.hpp>
#include <alibabacloud/models/ListVoiceAccessProfilesResponse.hpp>
#include <alibabacloud/models/PublishScriptRequest.hpp>
#include <alibabacloud/models/PublishScriptResponseBody.hpp>
#include <alibabacloud/models/PublishScriptResponse.hpp>
#include <alibabacloud/models/UpdateCloneVoiceRequest.hpp>
#include <alibabacloud/models/UpdateCloneVoiceResponseBody.hpp>
#include <alibabacloud/models/UpdateCloneVoiceResponse.hpp>
#include <alibabacloud/models/UpdateFlashSmsAccessProfileRequest.hpp>
#include <alibabacloud/models/UpdateFlashSmsAccessProfileShrinkRequest.hpp>
#include <alibabacloud/models/UpdateFlashSmsAccessProfileResponseBody.hpp>
#include <alibabacloud/models/UpdateFlashSmsAccessProfileResponse.hpp>
#include <alibabacloud/models/UpdateInstanceRequest.hpp>
#include <alibabacloud/models/UpdateInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceResponse.hpp>
#include <alibabacloud/models/UpdateScriptRequest.hpp>
#include <alibabacloud/models/UpdateScriptResponseBody.hpp>
#include <alibabacloud/models/UpdateScriptResponse.hpp>
#include <alibabacloud/models/UpdateSubscriptionRequest.hpp>
#include <alibabacloud/models/UpdateSubscriptionShrinkRequest.hpp>
#include <alibabacloud/models/UpdateSubscriptionResponseBody.hpp>
#include <alibabacloud/models/UpdateSubscriptionResponse.hpp>
#include <alibabacloud/models/UpdateSystemConfigsRequest.hpp>
#include <alibabacloud/models/UpdateSystemConfigsShrinkRequest.hpp>
#include <alibabacloud/models/UpdateSystemConfigsResponseBody.hpp>
#include <alibabacloud/models/UpdateSystemConfigsResponse.hpp>
#include <alibabacloud/models/UpdateVoiceAccessProfileRequest.hpp>
#include <alibabacloud/models/UpdateVoiceAccessProfileShrinkRequest.hpp>
#include <alibabacloud/models/UpdateVoiceAccessProfileResponseBody.hpp>
#include <alibabacloud/models/UpdateVoiceAccessProfileResponse.hpp>

#endif
