// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_SAFCONSOLE20250521MODEL_HPP_
#define ALIBABACLOUD_SAFCONSOLE20250521MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/ApplyBastionAccountRequest.hpp>
#include <alibabacloud/models/ApplyBastionAccountResponseBody.hpp>
#include <alibabacloud/models/ApplyBastionAccountResponse.hpp>
#include <alibabacloud/models/AssociatePocTaskRequest.hpp>
#include <alibabacloud/models/AssociatePocTaskResponseBody.hpp>
#include <alibabacloud/models/AssociatePocTaskResponse.hpp>
#include <alibabacloud/models/CompleteModelingProjectRequest.hpp>
#include <alibabacloud/models/CompleteModelingProjectResponseBody.hpp>
#include <alibabacloud/models/CompleteModelingProjectResponse.hpp>
#include <alibabacloud/models/CreateCustomerModuleBasicInfoRequest.hpp>
#include <alibabacloud/models/CreateCustomerModuleBasicInfoResponseBody.hpp>
#include <alibabacloud/models/CreateCustomerModuleBasicInfoResponse.hpp>
#include <alibabacloud/models/CreateCustomerModuleMetaInfoRequest.hpp>
#include <alibabacloud/models/CreateCustomerModuleMetaInfoResponseBody.hpp>
#include <alibabacloud/models/CreateCustomerModuleMetaInfoResponse.hpp>
#include <alibabacloud/models/CreateCustomerModuleOutputInfoRequest.hpp>
#include <alibabacloud/models/CreateCustomerModuleOutputInfoResponseBody.hpp>
#include <alibabacloud/models/CreateCustomerModuleOutputInfoResponse.hpp>
#include <alibabacloud/models/CreateModelingProjectRequest.hpp>
#include <alibabacloud/models/CreateModelingProjectResponseBody.hpp>
#include <alibabacloud/models/CreateModelingProjectResponse.hpp>
#include <alibabacloud/models/DeleteModelRequest.hpp>
#include <alibabacloud/models/DeleteModelResponseBody.hpp>
#include <alibabacloud/models/DeleteModelResponse.hpp>
#include <alibabacloud/models/DeployModelFileRequest.hpp>
#include <alibabacloud/models/DeployModelFileResponseBody.hpp>
#include <alibabacloud/models/DeployModelFileResponse.hpp>
#include <alibabacloud/models/DescribeCustomerModuleBasicInfoRequest.hpp>
#include <alibabacloud/models/DescribeCustomerModuleBasicInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomerModuleBasicInfoResponse.hpp>
#include <alibabacloud/models/DescribeCustomerModuleMetaInfoRequest.hpp>
#include <alibabacloud/models/DescribeCustomerModuleMetaInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomerModuleMetaInfoResponse.hpp>
#include <alibabacloud/models/DescribeCustomerModuleOutputInfoRequest.hpp>
#include <alibabacloud/models/DescribeCustomerModuleOutputInfoResponseBody.hpp>
#include <alibabacloud/models/DescribeCustomerModuleOutputInfoResponse.hpp>
#include <alibabacloud/models/DescribeFeatureOptionRequest.hpp>
#include <alibabacloud/models/DescribeFeatureOptionResponseBody.hpp>
#include <alibabacloud/models/DescribeFeatureOptionResponse.hpp>
#include <alibabacloud/models/DescribeFeatureTemplateListResponseBody.hpp>
#include <alibabacloud/models/DescribeFeatureTemplateListResponse.hpp>
#include <alibabacloud/models/DescribeFileDownloadUrlRequest.hpp>
#include <alibabacloud/models/DescribeFileDownloadUrlResponseBody.hpp>
#include <alibabacloud/models/DescribeFileDownloadUrlResponse.hpp>
#include <alibabacloud/models/DescribeModelFeatureRequest.hpp>
#include <alibabacloud/models/DescribeModelFeatureResponseBody.hpp>
#include <alibabacloud/models/DescribeModelFeatureResponse.hpp>
#include <alibabacloud/models/DescribeModelOssTokenResponseBody.hpp>
#include <alibabacloud/models/DescribeModelOssTokenResponse.hpp>
#include <alibabacloud/models/DescribeModelingProjectDetailRequest.hpp>
#include <alibabacloud/models/DescribeModelingProjectDetailResponseBody.hpp>
#include <alibabacloud/models/DescribeModelingProjectDetailResponse.hpp>
#include <alibabacloud/models/DescribeModelingProjectListRequest.hpp>
#include <alibabacloud/models/DescribeModelingProjectListResponseBody.hpp>
#include <alibabacloud/models/DescribeModelingProjectListResponse.hpp>
#include <alibabacloud/models/DescribeModuleServiceExistRequest.hpp>
#include <alibabacloud/models/DescribeModuleServiceExistResponseBody.hpp>
#include <alibabacloud/models/DescribeModuleServiceExistResponse.hpp>
#include <alibabacloud/models/DescribeModuleStatusRequest.hpp>
#include <alibabacloud/models/DescribeModuleStatusResponseBody.hpp>
#include <alibabacloud/models/DescribeModuleStatusResponse.hpp>
#include <alibabacloud/models/DescribePocTaskListResponseBody.hpp>
#include <alibabacloud/models/DescribePocTaskListResponse.hpp>
#include <alibabacloud/models/DescribeSafRmmpOrderResponseBody.hpp>
#include <alibabacloud/models/DescribeSafRmmpOrderResponse.hpp>
#include <alibabacloud/models/DescribeServiceAndSceneRequest.hpp>
#include <alibabacloud/models/DescribeServiceAndSceneResponseBody.hpp>
#include <alibabacloud/models/DescribeServiceAndSceneResponse.hpp>
#include <alibabacloud/models/DescribeUserModelListRequest.hpp>
#include <alibabacloud/models/DescribeUserModelListResponseBody.hpp>
#include <alibabacloud/models/DescribeUserModelListResponse.hpp>
#include <alibabacloud/models/DuplicateModelRequest.hpp>
#include <alibabacloud/models/DuplicateModelResponseBody.hpp>
#include <alibabacloud/models/DuplicateModelResponse.hpp>
#include <alibabacloud/models/EditModelRequest.hpp>
#include <alibabacloud/models/EditModelResponseBody.hpp>
#include <alibabacloud/models/EditModelResponse.hpp>
#include <alibabacloud/models/GetBastionHostCertificationRequest.hpp>
#include <alibabacloud/models/GetBastionHostCertificationResponseBody.hpp>
#include <alibabacloud/models/GetBastionHostCertificationResponse.hpp>
#include <alibabacloud/models/IterateModelRequest.hpp>
#include <alibabacloud/models/IterateModelResponseBody.hpp>
#include <alibabacloud/models/IterateModelResponse.hpp>
#include <alibabacloud/models/OfflineModelRequest.hpp>
#include <alibabacloud/models/OfflineModelResponseBody.hpp>
#include <alibabacloud/models/OfflineModelResponse.hpp>
#include <alibabacloud/models/OnlineModelRequest.hpp>
#include <alibabacloud/models/OnlineModelResponseBody.hpp>
#include <alibabacloud/models/OnlineModelResponse.hpp>
#include <alibabacloud/models/ParseExpressionParametersRequest.hpp>
#include <alibabacloud/models/ParseExpressionParametersResponseBody.hpp>
#include <alibabacloud/models/ParseExpressionParametersResponse.hpp>
#include <alibabacloud/models/PrepublishModelRequest.hpp>
#include <alibabacloud/models/PrepublishModelResponseBody.hpp>
#include <alibabacloud/models/PrepublishModelResponse.hpp>
#include <alibabacloud/models/RequestModelFileSyncRequest.hpp>
#include <alibabacloud/models/RequestModelFileSyncResponseBody.hpp>
#include <alibabacloud/models/RequestModelFileSyncResponse.hpp>
#include <alibabacloud/models/RollbackModelRequest.hpp>
#include <alibabacloud/models/RollbackModelResponseBody.hpp>
#include <alibabacloud/models/RollbackModelResponse.hpp>
#include <alibabacloud/models/TestModelRequest.hpp>
#include <alibabacloud/models/TestModelResponseBody.hpp>
#include <alibabacloud/models/TestModelResponse.hpp>
#include <alibabacloud/models/TestPreModelRequest.hpp>
#include <alibabacloud/models/TestPreModelResponseBody.hpp>
#include <alibabacloud/models/TestPreModelResponse.hpp>
#include <alibabacloud/models/TestProcessExpressionRequest.hpp>
#include <alibabacloud/models/TestProcessExpressionResponseBody.hpp>
#include <alibabacloud/models/TestProcessExpressionResponse.hpp>
#include <alibabacloud/models/UpdateModuleBasicInfoRequest.hpp>
#include <alibabacloud/models/UpdateModuleBasicInfoResponseBody.hpp>
#include <alibabacloud/models/UpdateModuleBasicInfoResponse.hpp>
#include <alibabacloud/models/ValidateModelFileRequest.hpp>
#include <alibabacloud/models/ValidateModelFileResponseBody.hpp>
#include <alibabacloud/models/ValidateModelFileResponse.hpp>
#include <alibabacloud/models/ValidateTestFileRequest.hpp>
#include <alibabacloud/models/ValidateTestFileResponseBody.hpp>
#include <alibabacloud/models/ValidateTestFileResponse.hpp>

#endif
