// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELSTUDIO20260210MODEL_HPP_
#define ALIBABACLOUD_MODELSTUDIO20260210MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddOrganizationMemberRequest.hpp>
#include <alibabacloud/models/AddOrganizationMemberResponseBody.hpp>
#include <alibabacloud/models/AddOrganizationMemberResponse.hpp>
#include <alibabacloud/models/BatchAssignSeatsRequest.hpp>
#include <alibabacloud/models/BatchAssignSeatsResponseBody.hpp>
#include <alibabacloud/models/BatchAssignSeatsResponse.hpp>
#include <alibabacloud/models/CreateApiKeyRequest.hpp>
#include <alibabacloud/models/CreateApiKeyResponseBody.hpp>
#include <alibabacloud/models/CreateApiKeyResponse.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyRequest.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyResponseBody.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyResponse.hpp>
#include <alibabacloud/models/CreateWorkspaceRequest.hpp>
#include <alibabacloud/models/CreateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/CreateWorkspaceResponse.hpp>
#include <alibabacloud/models/DeleteApiKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteApiKeyResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceRequest.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponse.hpp>
#include <alibabacloud/models/DisableApiKeyRequest.hpp>
#include <alibabacloud/models/DisableApiKeyResponseBody.hpp>
#include <alibabacloud/models/DisableApiKeyResponse.hpp>
#include <alibabacloud/models/EnableApiKeyRequest.hpp>
#include <alibabacloud/models/EnableApiKeyResponseBody.hpp>
#include <alibabacloud/models/EnableApiKeyResponse.hpp>
#include <alibabacloud/models/GetApiKeyResponseBody.hpp>
#include <alibabacloud/models/GetApiKeyResponse.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsRequest.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsResponseBody.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsResponse.hpp>
#include <alibabacloud/models/ListApiKeysRequest.hpp>
#include <alibabacloud/models/ListApiKeysResponseBody.hpp>
#include <alibabacloud/models/ListApiKeysResponse.hpp>
#include <alibabacloud/models/ListWorkspacesRequest.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBody.hpp>
#include <alibabacloud/models/ListWorkspacesResponse.hpp>
#include <alibabacloud/models/ResetApiKeyRequest.hpp>
#include <alibabacloud/models/ResetApiKeyResponseBody.hpp>
#include <alibabacloud/models/ResetApiKeyResponse.hpp>
#include <alibabacloud/models/UpdateApiKeyRequest.hpp>
#include <alibabacloud/models/UpdateApiKeyResponseBody.hpp>
#include <alibabacloud/models/UpdateApiKeyResponse.hpp>

#endif
