// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELSTUDIO20260210MODEL_HPP_
#define ALIBABACLOUD_MODELSTUDIO20260210MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddOrganizationMemberRequest.hpp>
#include <alibabacloud/models/AddOrganizationMemberResponseBody.hpp>
#include <alibabacloud/models/AddOrganizationMemberResponse.hpp>
#include <alibabacloud/models/BatchAssignSeatsRequest.hpp>
#include <alibabacloud/models/BatchAssignSeatsResponseBody.hpp>
#include <alibabacloud/models/BatchAssignSeatsResponse.hpp>
#include <alibabacloud/models/BatchRevokeSeatsRequest.hpp>
#include <alibabacloud/models/BatchRevokeSeatsShrinkRequest.hpp>
#include <alibabacloud/models/BatchRevokeSeatsResponseBody.hpp>
#include <alibabacloud/models/BatchRevokeSeatsResponse.hpp>
#include <alibabacloud/models/CreateApiKeyRequest.hpp>
#include <alibabacloud/models/CreateApiKeyResponseBody.hpp>
#include <alibabacloud/models/CreateApiKeyResponse.hpp>
#include <alibabacloud/models/CreateTokenPlanInviteLinkRequest.hpp>
#include <alibabacloud/models/CreateTokenPlanInviteLinkResponseBody.hpp>
#include <alibabacloud/models/CreateTokenPlanInviteLinkResponse.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyRequest.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyResponseBody.hpp>
#include <alibabacloud/models/CreateTokenPlanKeyResponse.hpp>
#include <alibabacloud/models/CreateWorkspaceRequest.hpp>
#include <alibabacloud/models/CreateWorkspaceResponseBody.hpp>
#include <alibabacloud/models/CreateWorkspaceResponse.hpp>
#include <alibabacloud/models/DeleteApiKeyResponseBody.hpp>
#include <alibabacloud/models/DeleteApiKeyResponse.hpp>
#include <alibabacloud/models/DeleteWorkspaceRequest.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponseBody.hpp>
#include <alibabacloud/models/DeleteWorkspaceResponse.hpp>
#include <alibabacloud/models/DisableApiKeyRequest.hpp>
#include <alibabacloud/models/DisableApiKeyResponseBody.hpp>
#include <alibabacloud/models/DisableApiKeyResponse.hpp>
#include <alibabacloud/models/EnableApiKeyRequest.hpp>
#include <alibabacloud/models/EnableApiKeyResponseBody.hpp>
#include <alibabacloud/models/EnableApiKeyResponse.hpp>
#include <alibabacloud/models/GetApiKeyResponseBody.hpp>
#include <alibabacloud/models/GetApiKeyResponse.hpp>
#include <alibabacloud/models/GetOrganizationRequest.hpp>
#include <alibabacloud/models/GetOrganizationResponseBody.hpp>
#include <alibabacloud/models/GetOrganizationResponse.hpp>
#include <alibabacloud/models/GetOrganizationMemberSeatStatsRequest.hpp>
#include <alibabacloud/models/GetOrganizationMemberSeatStatsResponseBody.hpp>
#include <alibabacloud/models/GetOrganizationMemberSeatStatsResponse.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsRequest.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsResponseBody.hpp>
#include <alibabacloud/models/GetSubscriptionSeatDetailsResponse.hpp>
#include <alibabacloud/models/GetSubscriptionStatsRequest.hpp>
#include <alibabacloud/models/GetSubscriptionStatsResponseBody.hpp>
#include <alibabacloud/models/GetSubscriptionStatsResponse.hpp>
#include <alibabacloud/models/GetTokenPlanAccountDetailRequest.hpp>
#include <alibabacloud/models/GetTokenPlanAccountDetailResponseBody.hpp>
#include <alibabacloud/models/GetTokenPlanAccountDetailResponse.hpp>
#include <alibabacloud/models/GetTokenPlanInviteLinkRequest.hpp>
#include <alibabacloud/models/GetTokenPlanInviteLinkResponseBody.hpp>
#include <alibabacloud/models/GetTokenPlanInviteLinkResponse.hpp>
#include <alibabacloud/models/GetTokenPlanOrgInviteConfigRequest.hpp>
#include <alibabacloud/models/GetTokenPlanOrgInviteConfigResponseBody.hpp>
#include <alibabacloud/models/GetTokenPlanOrgInviteConfigResponse.hpp>
#include <alibabacloud/models/ListApiKeysRequest.hpp>
#include <alibabacloud/models/ListApiKeysResponseBody.hpp>
#include <alibabacloud/models/ListApiKeysResponse.hpp>
#include <alibabacloud/models/ListOrganizationMembersRequest.hpp>
#include <alibabacloud/models/ListOrganizationMembersResponseBody.hpp>
#include <alibabacloud/models/ListOrganizationMembersResponse.hpp>
#include <alibabacloud/models/ListSubscriptionSharedPackagesRequest.hpp>
#include <alibabacloud/models/ListSubscriptionSharedPackagesResponseBody.hpp>
#include <alibabacloud/models/ListSubscriptionSharedPackagesResponse.hpp>
#include <alibabacloud/models/ListWorkspacesRequest.hpp>
#include <alibabacloud/models/ListWorkspacesResponseBody.hpp>
#include <alibabacloud/models/ListWorkspacesResponse.hpp>
#include <alibabacloud/models/RemoveOrganizationMemberRequest.hpp>
#include <alibabacloud/models/RemoveOrganizationMemberResponseBody.hpp>
#include <alibabacloud/models/RemoveOrganizationMemberResponse.hpp>
#include <alibabacloud/models/ResetApiKeyRequest.hpp>
#include <alibabacloud/models/ResetApiKeyResponseBody.hpp>
#include <alibabacloud/models/ResetApiKeyResponse.hpp>
#include <alibabacloud/models/RevokeTokenPlanInviteLinkRequest.hpp>
#include <alibabacloud/models/RevokeTokenPlanInviteLinkResponseBody.hpp>
#include <alibabacloud/models/RevokeTokenPlanInviteLinkResponse.hpp>
#include <alibabacloud/models/RotateTokenPlanKeyRequest.hpp>
#include <alibabacloud/models/RotateTokenPlanKeyResponseBody.hpp>
#include <alibabacloud/models/RotateTokenPlanKeyResponse.hpp>
#include <alibabacloud/models/SetTokenPlanOrgInviteConfigRequest.hpp>
#include <alibabacloud/models/SetTokenPlanOrgInviteConfigResponseBody.hpp>
#include <alibabacloud/models/SetTokenPlanOrgInviteConfigResponse.hpp>
#include <alibabacloud/models/UpdateApiKeyRequest.hpp>
#include <alibabacloud/models/UpdateApiKeyResponseBody.hpp>
#include <alibabacloud/models/UpdateApiKeyResponse.hpp>
#include <alibabacloud/models/UpdateOrganizationRequest.hpp>
#include <alibabacloud/models/UpdateOrganizationResponseBody.hpp>
#include <alibabacloud/models/UpdateOrganizationResponse.hpp>
#include <alibabacloud/models/UpdateOrganizationMemberRequest.hpp>
#include <alibabacloud/models/UpdateOrganizationMemberResponseBody.hpp>
#include <alibabacloud/models/UpdateOrganizationMemberResponse.hpp>

#endif
