// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_GENERATEGROUPIMAGESHRINKREQUEST_HPP_
#define ALIBABACLOUD_MODELS_GENERATEGROUPIMAGESHRINKREQUEST_HPP_
#include <darabonba/Core.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace AgentRetailVision20260506
{
namespace Models
{
  class GenerateGroupImageShrinkRequest : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const GenerateGroupImageShrinkRequest& obj) { 
      DARABONBA_PTR_TO_JSON(CallbackSecret, callbackSecret_);
      DARABONBA_PTR_TO_JSON(CallbackUrl, callbackUrl_);
      DARABONBA_PTR_TO_JSON(GroupId, groupId_);
      DARABONBA_PTR_TO_JSON(GroupType, groupType_);
      DARABONBA_PTR_TO_JSON(PlatformItemIdList, platformItemIdListShrink_);
    };
    friend void from_json(const Darabonba::Json& j, GenerateGroupImageShrinkRequest& obj) { 
      DARABONBA_PTR_FROM_JSON(CallbackSecret, callbackSecret_);
      DARABONBA_PTR_FROM_JSON(CallbackUrl, callbackUrl_);
      DARABONBA_PTR_FROM_JSON(GroupId, groupId_);
      DARABONBA_PTR_FROM_JSON(GroupType, groupType_);
      DARABONBA_PTR_FROM_JSON(PlatformItemIdList, platformItemIdListShrink_);
    };
    GenerateGroupImageShrinkRequest() = default ;
    GenerateGroupImageShrinkRequest(const GenerateGroupImageShrinkRequest &) = default ;
    GenerateGroupImageShrinkRequest(GenerateGroupImageShrinkRequest &&) = default ;
    GenerateGroupImageShrinkRequest(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~GenerateGroupImageShrinkRequest() = default ;
    GenerateGroupImageShrinkRequest& operator=(const GenerateGroupImageShrinkRequest &) = default ;
    GenerateGroupImageShrinkRequest& operator=(GenerateGroupImageShrinkRequest &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->callbackSecret_ == nullptr
        && this->callbackUrl_ == nullptr && this->groupId_ == nullptr && this->groupType_ == nullptr && this->platformItemIdListShrink_ == nullptr; };
    // callbackSecret Field Functions 
    bool hasCallbackSecret() const { return this->callbackSecret_ != nullptr;};
    void deleteCallbackSecret() { this->callbackSecret_ = nullptr;};
    inline string getCallbackSecret() const { DARABONBA_PTR_GET_DEFAULT(callbackSecret_, "") };
    inline GenerateGroupImageShrinkRequest& setCallbackSecret(string callbackSecret) { DARABONBA_PTR_SET_VALUE(callbackSecret_, callbackSecret) };


    // callbackUrl Field Functions 
    bool hasCallbackUrl() const { return this->callbackUrl_ != nullptr;};
    void deleteCallbackUrl() { this->callbackUrl_ = nullptr;};
    inline string getCallbackUrl() const { DARABONBA_PTR_GET_DEFAULT(callbackUrl_, "") };
    inline GenerateGroupImageShrinkRequest& setCallbackUrl(string callbackUrl) { DARABONBA_PTR_SET_VALUE(callbackUrl_, callbackUrl) };


    // groupId Field Functions 
    bool hasGroupId() const { return this->groupId_ != nullptr;};
    void deleteGroupId() { this->groupId_ = nullptr;};
    inline string getGroupId() const { DARABONBA_PTR_GET_DEFAULT(groupId_, "") };
    inline GenerateGroupImageShrinkRequest& setGroupId(string groupId) { DARABONBA_PTR_SET_VALUE(groupId_, groupId) };


    // groupType Field Functions 
    bool hasGroupType() const { return this->groupType_ != nullptr;};
    void deleteGroupType() { this->groupType_ = nullptr;};
    inline int32_t getGroupType() const { DARABONBA_PTR_GET_DEFAULT(groupType_, 0) };
    inline GenerateGroupImageShrinkRequest& setGroupType(int32_t groupType) { DARABONBA_PTR_SET_VALUE(groupType_, groupType) };


    // platformItemIdListShrink Field Functions 
    bool hasPlatformItemIdListShrink() const { return this->platformItemIdListShrink_ != nullptr;};
    void deletePlatformItemIdListShrink() { this->platformItemIdListShrink_ = nullptr;};
    inline string getPlatformItemIdListShrink() const { DARABONBA_PTR_GET_DEFAULT(platformItemIdListShrink_, "") };
    inline GenerateGroupImageShrinkRequest& setPlatformItemIdListShrink(string platformItemIdListShrink) { DARABONBA_PTR_SET_VALUE(platformItemIdListShrink_, platformItemIdListShrink) };


  protected:
    // The key used for callback signature verification.
    shared_ptr<string> callbackSecret_ {};
    // The callback URL of the customer.
    shared_ptr<string> callbackUrl_ {};
    // The composite image request ID generated by the caller.
    shared_ptr<string> groupId_ {};
    // The composite image type. Valid values:
    // - 1: single-SKU multi-image composite.
    // - 2: multi-SKU composite.
    shared_ptr<int32_t> groupType_ {};
    // The list of platform item IDs, corresponding to smart_retail_item.platform_item_id.
    shared_ptr<string> platformItemIdListShrink_ {};
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace AgentRetailVision20260506
#endif
