// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_WEBSITEBUILD20250429MODEL_HPP_
#define ALIBABACLOUD_WEBSITEBUILD20250429MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/BindAppDomainRequest.hpp>
#include <alibabacloud/models/BindAppDomainResponseBody.hpp>
#include <alibabacloud/models/BindAppDomainResponse.hpp>
#include <alibabacloud/models/CreateLogoTaskRequest.hpp>
#include <alibabacloud/models/CreateLogoTaskResponseBody.hpp>
#include <alibabacloud/models/CreateLogoTaskResponse.hpp>
#include <alibabacloud/models/DeleteAppDomainCertificateRequest.hpp>
#include <alibabacloud/models/DeleteAppDomainCertificateResponseBody.hpp>
#include <alibabacloud/models/DeleteAppDomainCertificateResponse.hpp>
#include <alibabacloud/models/DeleteAppDomainRedirectRequest.hpp>
#include <alibabacloud/models/DeleteAppDomainRedirectResponseBody.hpp>
#include <alibabacloud/models/DeleteAppDomainRedirectResponse.hpp>
#include <alibabacloud/models/DescribeAppDomainDnsRecordRequest.hpp>
#include <alibabacloud/models/DescribeAppDomainDnsRecordResponseBody.hpp>
#include <alibabacloud/models/DescribeAppDomainDnsRecordResponse.hpp>
#include <alibabacloud/models/GetCreateLogoTaskRequest.hpp>
#include <alibabacloud/models/GetCreateLogoTaskResponseBody.hpp>
#include <alibabacloud/models/GetCreateLogoTaskResponse.hpp>
#include <alibabacloud/models/GetDomainInfoForPartnerRequest.hpp>
#include <alibabacloud/models/GetDomainInfoForPartnerResponseBody.hpp>
#include <alibabacloud/models/GetDomainInfoForPartnerResponse.hpp>
#include <alibabacloud/models/GetIcpFilingInfoForPartnerRequest.hpp>
#include <alibabacloud/models/GetIcpFilingInfoForPartnerResponseBody.hpp>
#include <alibabacloud/models/GetIcpFilingInfoForPartnerResponse.hpp>
#include <alibabacloud/models/GetUserTmpIdentityForPartnerRequest.hpp>
#include <alibabacloud/models/GetUserTmpIdentityForPartnerResponseBody.hpp>
#include <alibabacloud/models/GetUserTmpIdentityForPartnerResponse.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsRequest.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsResponseBody.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsResponse.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsRequest.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBody.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponse.hpp>
#include <alibabacloud/models/OperateAppInstanceForPartnerRequest.hpp>
#include <alibabacloud/models/OperateAppInstanceForPartnerResponseBody.hpp>
#include <alibabacloud/models/OperateAppInstanceForPartnerResponse.hpp>
#include <alibabacloud/models/OperateAppServiceForPartnerRequest.hpp>
#include <alibabacloud/models/OperateAppServiceForPartnerResponseBody.hpp>
#include <alibabacloud/models/OperateAppServiceForPartnerResponse.hpp>
#include <alibabacloud/models/SearchImageRequest.hpp>
#include <alibabacloud/models/SearchImageShrinkRequest.hpp>
#include <alibabacloud/models/SearchImageResponseBody.hpp>
#include <alibabacloud/models/SearchImageResponse.hpp>
#include <alibabacloud/models/SetAppDomainCertificateRequest.hpp>
#include <alibabacloud/models/SetAppDomainCertificateResponseBody.hpp>
#include <alibabacloud/models/SetAppDomainCertificateResponse.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerRequest.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerShrinkRequest.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerResponseBody.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerResponse.hpp>
#include <alibabacloud/models/UnbindAppDomainRequest.hpp>
#include <alibabacloud/models/UnbindAppDomainResponseBody.hpp>
#include <alibabacloud/models/UnbindAppDomainResponse.hpp>
#include <alibabacloud/models/BindAppDomainResponseBodyModule.hpp>
#include <alibabacloud/models/DeleteAppDomainCertificateResponseBodyModule.hpp>
#include <alibabacloud/models/DeleteAppDomainRedirectResponseBodyModule.hpp>
#include <alibabacloud/models/DescribeAppDomainDnsRecordResponseBodyModule.hpp>
#include <alibabacloud/models/GetCreateLogoTaskResponseBodyTask.hpp>
#include <alibabacloud/models/GetDomainInfoForPartnerResponseBodyDataOwnership.hpp>
#include <alibabacloud/models/GetDomainInfoForPartnerResponseBodyData.hpp>
#include <alibabacloud/models/GetIcpFilingInfoForPartnerResponseBodyData.hpp>
#include <alibabacloud/models/GetUserTmpIdentityForPartnerResponseBodyDataCredentials.hpp>
#include <alibabacloud/models/GetUserTmpIdentityForPartnerResponseBodyData.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsResponseBodyModuleData.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsResponseBodyModuleNext.hpp>
#include <alibabacloud/models/ListAppDomainRedirectRecordsResponseBodyModule.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataCertificate.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataOwnership.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataResolutionDnsRecord.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataResolution.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataVerificationDnsRecord.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleDataVerification.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleData.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextCertificate.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextOwnership.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextResolutionDnsRecord.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextResolution.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextVerificationDnsRecord.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNextVerification.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModuleNext.hpp>
#include <alibabacloud/models/ListAppInstanceDomainsResponseBodyModule.hpp>
#include <alibabacloud/models/SearchImageResponseBodyImageResponseImageList.hpp>
#include <alibabacloud/models/SearchImageResponseBodyImageResponse.hpp>
#include <alibabacloud/models/SetAppDomainCertificateResponseBodyModule.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerRequestAppInstanceProfile.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerRequestAppInstance.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerResponseBodyDataAppInstance.hpp>
#include <alibabacloud/models/SyncAppInstanceForPartnerResponseBodyData.hpp>
#include <alibabacloud/models/UnbindAppDomainResponseBodyModule.hpp>

#endif
