// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_VPCIPAM20230228MODEL_HPP_
#define ALIBABACLOUD_VPCIPAM20230228MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddIpamPoolCidrRequest.hpp>
#include <alibabacloud/models/AddIpamPoolCidrResponseBody.hpp>
#include <alibabacloud/models/AddIpamPoolCidrResponse.hpp>
#include <alibabacloud/models/AssociateIpamResourceDiscoveryRequest.hpp>
#include <alibabacloud/models/AssociateIpamResourceDiscoveryResponseBody.hpp>
#include <alibabacloud/models/AssociateIpamResourceDiscoveryResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CreateIpamRequest.hpp>
#include <alibabacloud/models/CreateIpamResponseBody.hpp>
#include <alibabacloud/models/CreateIpamResponse.hpp>
#include <alibabacloud/models/CreateIpamPoolRequest.hpp>
#include <alibabacloud/models/CreateIpamPoolResponseBody.hpp>
#include <alibabacloud/models/CreateIpamPoolResponse.hpp>
#include <alibabacloud/models/CreateIpamPoolAllocationRequest.hpp>
#include <alibabacloud/models/CreateIpamPoolAllocationResponseBody.hpp>
#include <alibabacloud/models/CreateIpamPoolAllocationResponse.hpp>
#include <alibabacloud/models/CreateIpamResourceDiscoveryRequest.hpp>
#include <alibabacloud/models/CreateIpamResourceDiscoveryResponseBody.hpp>
#include <alibabacloud/models/CreateIpamResourceDiscoveryResponse.hpp>
#include <alibabacloud/models/CreateIpamScopeRequest.hpp>
#include <alibabacloud/models/CreateIpamScopeResponseBody.hpp>
#include <alibabacloud/models/CreateIpamScopeResponse.hpp>
#include <alibabacloud/models/DeleteIpamRequest.hpp>
#include <alibabacloud/models/DeleteIpamResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamResponse.hpp>
#include <alibabacloud/models/DeleteIpamPoolRequest.hpp>
#include <alibabacloud/models/DeleteIpamPoolResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamPoolResponse.hpp>
#include <alibabacloud/models/DeleteIpamPoolAllocationRequest.hpp>
#include <alibabacloud/models/DeleteIpamPoolAllocationResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamPoolAllocationResponse.hpp>
#include <alibabacloud/models/DeleteIpamPoolCidrRequest.hpp>
#include <alibabacloud/models/DeleteIpamPoolCidrResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamPoolCidrResponse.hpp>
#include <alibabacloud/models/DeleteIpamResourceDiscoveryRequest.hpp>
#include <alibabacloud/models/DeleteIpamResourceDiscoveryResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamResourceDiscoveryResponse.hpp>
#include <alibabacloud/models/DeleteIpamScopeRequest.hpp>
#include <alibabacloud/models/DeleteIpamScopeResponseBody.hpp>
#include <alibabacloud/models/DeleteIpamScopeResponse.hpp>
#include <alibabacloud/models/DissociateIpamResourceDiscoveryRequest.hpp>
#include <alibabacloud/models/DissociateIpamResourceDiscoveryResponseBody.hpp>
#include <alibabacloud/models/DissociateIpamResourceDiscoveryResponse.hpp>
#include <alibabacloud/models/GetIpamPoolAllocationRequest.hpp>
#include <alibabacloud/models/GetIpamPoolAllocationResponseBody.hpp>
#include <alibabacloud/models/GetIpamPoolAllocationResponse.hpp>
#include <alibabacloud/models/GetIpamPoolNextAvailableCidrRequest.hpp>
#include <alibabacloud/models/GetIpamPoolNextAvailableCidrResponseBody.hpp>
#include <alibabacloud/models/GetIpamPoolNextAvailableCidrResponse.hpp>
#include <alibabacloud/models/GetVpcIpamServiceStatusRequest.hpp>
#include <alibabacloud/models/GetVpcIpamServiceStatusResponseBody.hpp>
#include <alibabacloud/models/GetVpcIpamServiceStatusResponse.hpp>
#include <alibabacloud/models/ListIpamDiscoveredResourceRequest.hpp>
#include <alibabacloud/models/ListIpamDiscoveredResourceResponseBody.hpp>
#include <alibabacloud/models/ListIpamDiscoveredResourceResponse.hpp>
#include <alibabacloud/models/ListIpamPoolAllocationsRequest.hpp>
#include <alibabacloud/models/ListIpamPoolAllocationsResponseBody.hpp>
#include <alibabacloud/models/ListIpamPoolAllocationsResponse.hpp>
#include <alibabacloud/models/ListIpamPoolCidrsRequest.hpp>
#include <alibabacloud/models/ListIpamPoolCidrsResponseBody.hpp>
#include <alibabacloud/models/ListIpamPoolCidrsResponse.hpp>
#include <alibabacloud/models/ListIpamPoolsRequest.hpp>
#include <alibabacloud/models/ListIpamPoolsResponseBody.hpp>
#include <alibabacloud/models/ListIpamPoolsResponse.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsRequest.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsResponseBody.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsResponse.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesRequest.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesResponseBody.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesResponse.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveryAssociationsRequest.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveryAssociationsResponseBody.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveryAssociationsResponse.hpp>
#include <alibabacloud/models/ListIpamScopesRequest.hpp>
#include <alibabacloud/models/ListIpamScopesResponseBody.hpp>
#include <alibabacloud/models/ListIpamScopesResponse.hpp>
#include <alibabacloud/models/ListIpamsRequest.hpp>
#include <alibabacloud/models/ListIpamsResponseBody.hpp>
#include <alibabacloud/models/ListIpamsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/OpenVpcIpamServiceRequest.hpp>
#include <alibabacloud/models/OpenVpcIpamServiceResponseBody.hpp>
#include <alibabacloud/models/OpenVpcIpamServiceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateIpamRequest.hpp>
#include <alibabacloud/models/UpdateIpamResponseBody.hpp>
#include <alibabacloud/models/UpdateIpamResponse.hpp>
#include <alibabacloud/models/UpdateIpamPoolRequest.hpp>
#include <alibabacloud/models/UpdateIpamPoolResponseBody.hpp>
#include <alibabacloud/models/UpdateIpamPoolResponse.hpp>
#include <alibabacloud/models/UpdateIpamPoolAllocationRequest.hpp>
#include <alibabacloud/models/UpdateIpamPoolAllocationResponseBody.hpp>
#include <alibabacloud/models/UpdateIpamPoolAllocationResponse.hpp>
#include <alibabacloud/models/UpdateIpamResourceDiscoveryRequest.hpp>
#include <alibabacloud/models/UpdateIpamResourceDiscoveryResponseBody.hpp>
#include <alibabacloud/models/UpdateIpamResourceDiscoveryResponse.hpp>
#include <alibabacloud/models/UpdateIpamScopeRequest.hpp>
#include <alibabacloud/models/UpdateIpamScopeResponseBody.hpp>
#include <alibabacloud/models/UpdateIpamScopeResponse.hpp>
#include <alibabacloud/models/CreateIpamRequestTag.hpp>
#include <alibabacloud/models/CreateIpamPoolRequestTag.hpp>
#include <alibabacloud/models/CreateIpamResourceDiscoveryRequestTag.hpp>
#include <alibabacloud/models/CreateIpamScopeRequestTag.hpp>
#include <alibabacloud/models/ListIpamDiscoveredResourceResponseBodyIpamDiscoveredResourcesIpCountDetail.hpp>
#include <alibabacloud/models/ListIpamDiscoveredResourceResponseBodyIpamDiscoveredResources.hpp>
#include <alibabacloud/models/ListIpamPoolAllocationsResponseBodyIpamPoolAllocations.hpp>
#include <alibabacloud/models/ListIpamPoolCidrsResponseBodyIpamPoolCidrs.hpp>
#include <alibabacloud/models/ListIpamPoolsRequestTags.hpp>
#include <alibabacloud/models/ListIpamPoolsResponseBodyIpamPoolsTags.hpp>
#include <alibabacloud/models/ListIpamPoolsResponseBodyIpamPools.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsResponseBodyIpamResourceCidrsIpCountDetail.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsResponseBodyIpamResourceCidrsOverlapDetail.hpp>
#include <alibabacloud/models/ListIpamResourceCidrsResponseBodyIpamResourceCidrs.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesRequestTags.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesResponseBodyIpamResourceDiscoveriesTags.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveriesResponseBodyIpamResourceDiscoveries.hpp>
#include <alibabacloud/models/ListIpamResourceDiscoveryAssociationsResponseBodyIpamResourceDiscoveryAssociations.hpp>
#include <alibabacloud/models/ListIpamScopesRequestTags.hpp>
#include <alibabacloud/models/ListIpamScopesResponseBodyIpamScopesTags.hpp>
#include <alibabacloud/models/ListIpamScopesResponseBodyIpamScopes.hpp>
#include <alibabacloud/models/ListIpamsRequestTags.hpp>
#include <alibabacloud/models/ListIpamsResponseBodyIpamsTags.hpp>
#include <alibabacloud/models/ListIpamsResponseBodyIpams.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
