// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_HBR20170908MODEL_HPP_
#define ALIBABACLOUD_HBR20170908MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/OtsDetail.hpp>
#include <alibabacloud/models/OtsTableRestoreDetail.hpp>
#include <alibabacloud/models/Report.hpp>
#include <alibabacloud/models/Rule.hpp>
#include <alibabacloud/models/AddContainerClusterRequest.hpp>
#include <alibabacloud/models/AddContainerClusterResponseBody.hpp>
#include <alibabacloud/models/AddContainerClusterResponse.hpp>
#include <alibabacloud/models/CancelBackupJobRequest.hpp>
#include <alibabacloud/models/CancelBackupJobResponseBody.hpp>
#include <alibabacloud/models/CancelBackupJobResponse.hpp>
#include <alibabacloud/models/CancelRestoreJobRequest.hpp>
#include <alibabacloud/models/CancelRestoreJobResponseBody.hpp>
#include <alibabacloud/models/CancelRestoreJobResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckRoleRequest.hpp>
#include <alibabacloud/models/CheckRoleResponseBody.hpp>
#include <alibabacloud/models/CheckRoleResponse.hpp>
#include <alibabacloud/models/CreateBackupJobRequest.hpp>
#include <alibabacloud/models/CreateBackupJobShrinkRequest.hpp>
#include <alibabacloud/models/CreateBackupJobResponseBody.hpp>
#include <alibabacloud/models/CreateBackupJobResponse.hpp>
#include <alibabacloud/models/CreateBackupPlanRequest.hpp>
#include <alibabacloud/models/CreateBackupPlanShrinkRequest.hpp>
#include <alibabacloud/models/CreateBackupPlanResponseBody.hpp>
#include <alibabacloud/models/CreateBackupPlanResponse.hpp>
#include <alibabacloud/models/CreateClientsRequest.hpp>
#include <alibabacloud/models/CreateClientsResponseBody.hpp>
#include <alibabacloud/models/CreateClientsResponse.hpp>
#include <alibabacloud/models/CreateHanaBackupPlanRequest.hpp>
#include <alibabacloud/models/CreateHanaBackupPlanResponseBody.hpp>
#include <alibabacloud/models/CreateHanaBackupPlanResponse.hpp>
#include <alibabacloud/models/CreateHanaInstanceRequest.hpp>
#include <alibabacloud/models/CreateHanaInstanceResponseBody.hpp>
#include <alibabacloud/models/CreateHanaInstanceResponse.hpp>
#include <alibabacloud/models/CreateHanaRestoreRequest.hpp>
#include <alibabacloud/models/CreateHanaRestoreResponseBody.hpp>
#include <alibabacloud/models/CreateHanaRestoreResponse.hpp>
#include <alibabacloud/models/CreatePolicyBindingsRequest.hpp>
#include <alibabacloud/models/CreatePolicyBindingsShrinkRequest.hpp>
#include <alibabacloud/models/CreatePolicyBindingsResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyBindingsResponse.hpp>
#include <alibabacloud/models/CreatePolicyV2Request.hpp>
#include <alibabacloud/models/CreatePolicyV2ShrinkRequest.hpp>
#include <alibabacloud/models/CreatePolicyV2ResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyV2Response.hpp>
#include <alibabacloud/models/CreateReplicationVaultRequest.hpp>
#include <alibabacloud/models/CreateReplicationVaultResponseBody.hpp>
#include <alibabacloud/models/CreateReplicationVaultResponse.hpp>
#include <alibabacloud/models/CreateRestoreJobRequest.hpp>
#include <alibabacloud/models/CreateRestoreJobShrinkRequest.hpp>
#include <alibabacloud/models/CreateRestoreJobResponseBody.hpp>
#include <alibabacloud/models/CreateRestoreJobResponse.hpp>
#include <alibabacloud/models/CreateTempFileUploadUrlRequest.hpp>
#include <alibabacloud/models/CreateTempFileUploadUrlResponseBody.hpp>
#include <alibabacloud/models/CreateTempFileUploadUrlResponse.hpp>
#include <alibabacloud/models/CreateVaultRequest.hpp>
#include <alibabacloud/models/CreateVaultResponseBody.hpp>
#include <alibabacloud/models/CreateVaultResponse.hpp>
#include <alibabacloud/models/CreateVaultReplicationRequest.hpp>
#include <alibabacloud/models/CreateVaultReplicationResponseBody.hpp>
#include <alibabacloud/models/CreateVaultReplicationResponse.hpp>
#include <alibabacloud/models/DeleteAirEcsInstanceRequest.hpp>
#include <alibabacloud/models/DeleteAirEcsInstanceShrinkRequest.hpp>
#include <alibabacloud/models/DeleteAirEcsInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteAirEcsInstanceResponse.hpp>
#include <alibabacloud/models/DeleteBackupClientRequest.hpp>
#include <alibabacloud/models/DeleteBackupClientResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupClientResponse.hpp>
#include <alibabacloud/models/DeleteBackupClientResourceRequest.hpp>
#include <alibabacloud/models/DeleteBackupClientResourceShrinkRequest.hpp>
#include <alibabacloud/models/DeleteBackupClientResourceResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupClientResourceResponse.hpp>
#include <alibabacloud/models/DeleteBackupPlanRequest.hpp>
#include <alibabacloud/models/DeleteBackupPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupPlanResponse.hpp>
#include <alibabacloud/models/DeleteClientRequest.hpp>
#include <alibabacloud/models/DeleteClientResponseBody.hpp>
#include <alibabacloud/models/DeleteClientResponse.hpp>
#include <alibabacloud/models/DeleteHanaBackupPlanRequest.hpp>
#include <alibabacloud/models/DeleteHanaBackupPlanResponseBody.hpp>
#include <alibabacloud/models/DeleteHanaBackupPlanResponse.hpp>
#include <alibabacloud/models/DeleteHanaInstanceRequest.hpp>
#include <alibabacloud/models/DeleteHanaInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteHanaInstanceResponse.hpp>
#include <alibabacloud/models/DeletePolicyBindingRequest.hpp>
#include <alibabacloud/models/DeletePolicyBindingShrinkRequest.hpp>
#include <alibabacloud/models/DeletePolicyBindingResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyBindingResponse.hpp>
#include <alibabacloud/models/DeletePolicyV2Request.hpp>
#include <alibabacloud/models/DeletePolicyV2ResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyV2Response.hpp>
#include <alibabacloud/models/DeleteSnapshotRequest.hpp>
#include <alibabacloud/models/DeleteSnapshotResponseBody.hpp>
#include <alibabacloud/models/DeleteSnapshotResponse.hpp>
#include <alibabacloud/models/DeleteUdmDiskRequest.hpp>
#include <alibabacloud/models/DeleteUdmDiskResponseBody.hpp>
#include <alibabacloud/models/DeleteUdmDiskResponse.hpp>
#include <alibabacloud/models/DeleteUdmEcsInstanceRequest.hpp>
#include <alibabacloud/models/DeleteUdmEcsInstanceResponseBody.hpp>
#include <alibabacloud/models/DeleteUdmEcsInstanceResponse.hpp>
#include <alibabacloud/models/DeleteVaultRequest.hpp>
#include <alibabacloud/models/DeleteVaultResponseBody.hpp>
#include <alibabacloud/models/DeleteVaultResponse.hpp>
#include <alibabacloud/models/DeleteVaultReplicationRequest.hpp>
#include <alibabacloud/models/DeleteVaultReplicationResponseBody.hpp>
#include <alibabacloud/models/DeleteVaultReplicationResponse.hpp>
#include <alibabacloud/models/DescribeBackupClientsRequest.hpp>
#include <alibabacloud/models/DescribeBackupClientsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeBackupClientsResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupClientsResponse.hpp>
#include <alibabacloud/models/DescribeBackupJobs2Request.hpp>
#include <alibabacloud/models/DescribeBackupJobs2ResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupJobs2Response.hpp>
#include <alibabacloud/models/DescribeBackupPlansRequest.hpp>
#include <alibabacloud/models/DescribeBackupPlansResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupPlansResponse.hpp>
#include <alibabacloud/models/DescribeClientsRequest.hpp>
#include <alibabacloud/models/DescribeClientsResponseBody.hpp>
#include <alibabacloud/models/DescribeClientsResponse.hpp>
#include <alibabacloud/models/DescribeContainerClusterRequest.hpp>
#include <alibabacloud/models/DescribeContainerClusterResponseBody.hpp>
#include <alibabacloud/models/DescribeContainerClusterResponse.hpp>
#include <alibabacloud/models/DescribeCrossAccountsRequest.hpp>
#include <alibabacloud/models/DescribeCrossAccountsResponseBody.hpp>
#include <alibabacloud/models/DescribeCrossAccountsResponse.hpp>
#include <alibabacloud/models/DescribeHanaBackupPlansRequest.hpp>
#include <alibabacloud/models/DescribeHanaBackupPlansResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaBackupPlansResponse.hpp>
#include <alibabacloud/models/DescribeHanaBackupSettingRequest.hpp>
#include <alibabacloud/models/DescribeHanaBackupSettingResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaBackupSettingResponse.hpp>
#include <alibabacloud/models/DescribeHanaBackupsAsyncRequest.hpp>
#include <alibabacloud/models/DescribeHanaBackupsAsyncResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaBackupsAsyncResponse.hpp>
#include <alibabacloud/models/DescribeHanaDatabasesRequest.hpp>
#include <alibabacloud/models/DescribeHanaDatabasesResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaDatabasesResponse.hpp>
#include <alibabacloud/models/DescribeHanaInstancesRequest.hpp>
#include <alibabacloud/models/DescribeHanaInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaInstancesResponse.hpp>
#include <alibabacloud/models/DescribeHanaRestoresRequest.hpp>
#include <alibabacloud/models/DescribeHanaRestoresResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaRestoresResponse.hpp>
#include <alibabacloud/models/DescribeHanaRetentionSettingRequest.hpp>
#include <alibabacloud/models/DescribeHanaRetentionSettingResponseBody.hpp>
#include <alibabacloud/models/DescribeHanaRetentionSettingResponse.hpp>
#include <alibabacloud/models/DescribeOtsTableSnapshotsRequest.hpp>
#include <alibabacloud/models/DescribeOtsTableSnapshotsResponseBody.hpp>
#include <alibabacloud/models/DescribeOtsTableSnapshotsResponse.hpp>
#include <alibabacloud/models/DescribePoliciesV2Request.hpp>
#include <alibabacloud/models/DescribePoliciesV2ResponseBody.hpp>
#include <alibabacloud/models/DescribePoliciesV2Response.hpp>
#include <alibabacloud/models/DescribePolicyBindingsRequest.hpp>
#include <alibabacloud/models/DescribePolicyBindingsShrinkRequest.hpp>
#include <alibabacloud/models/DescribePolicyBindingsResponseBody.hpp>
#include <alibabacloud/models/DescribePolicyBindingsResponse.hpp>
#include <alibabacloud/models/DescribeRecoverableOtsInstancesRequest.hpp>
#include <alibabacloud/models/DescribeRecoverableOtsInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeRecoverableOtsInstancesResponse.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeRestoreJobs2Request.hpp>
#include <alibabacloud/models/DescribeRestoreJobs2ResponseBody.hpp>
#include <alibabacloud/models/DescribeRestoreJobs2Response.hpp>
#include <alibabacloud/models/DescribeTaskRequest.hpp>
#include <alibabacloud/models/DescribeTaskResponseBody.hpp>
#include <alibabacloud/models/DescribeTaskResponse.hpp>
#include <alibabacloud/models/DescribeUdmSnapshotsRequest.hpp>
#include <alibabacloud/models/DescribeUdmSnapshotsShrinkRequest.hpp>
#include <alibabacloud/models/DescribeUdmSnapshotsResponseBody.hpp>
#include <alibabacloud/models/DescribeUdmSnapshotsResponse.hpp>
#include <alibabacloud/models/DescribeVaultReplicationRegionsRequest.hpp>
#include <alibabacloud/models/DescribeVaultReplicationRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeVaultReplicationRegionsResponse.hpp>
#include <alibabacloud/models/DescribeVaultsRequest.hpp>
#include <alibabacloud/models/DescribeVaultsResponseBody.hpp>
#include <alibabacloud/models/DescribeVaultsResponse.hpp>
#include <alibabacloud/models/DetachNasFileSystemRequest.hpp>
#include <alibabacloud/models/DetachNasFileSystemResponseBody.hpp>
#include <alibabacloud/models/DetachNasFileSystemResponse.hpp>
#include <alibabacloud/models/DisableBackupPlanRequest.hpp>
#include <alibabacloud/models/DisableBackupPlanResponseBody.hpp>
#include <alibabacloud/models/DisableBackupPlanResponse.hpp>
#include <alibabacloud/models/DisableHanaBackupPlanRequest.hpp>
#include <alibabacloud/models/DisableHanaBackupPlanResponseBody.hpp>
#include <alibabacloud/models/DisableHanaBackupPlanResponse.hpp>
#include <alibabacloud/models/EnableBackupPlanRequest.hpp>
#include <alibabacloud/models/EnableBackupPlanResponseBody.hpp>
#include <alibabacloud/models/EnableBackupPlanResponse.hpp>
#include <alibabacloud/models/EnableHanaBackupPlanRequest.hpp>
#include <alibabacloud/models/EnableHanaBackupPlanResponseBody.hpp>
#include <alibabacloud/models/EnableHanaBackupPlanResponse.hpp>
#include <alibabacloud/models/ExecuteBackupPlanRequest.hpp>
#include <alibabacloud/models/ExecuteBackupPlanResponseBody.hpp>
#include <alibabacloud/models/ExecuteBackupPlanResponse.hpp>
#include <alibabacloud/models/ExecutePolicyV2Request.hpp>
#include <alibabacloud/models/ExecutePolicyV2ResponseBody.hpp>
#include <alibabacloud/models/ExecutePolicyV2Response.hpp>
#include <alibabacloud/models/GenerateRamPolicyRequest.hpp>
#include <alibabacloud/models/GenerateRamPolicyResponseBody.hpp>
#include <alibabacloud/models/GenerateRamPolicyResponse.hpp>
#include <alibabacloud/models/GetTempFileDownloadLinkRequest.hpp>
#include <alibabacloud/models/GetTempFileDownloadLinkResponseBody.hpp>
#include <alibabacloud/models/GetTempFileDownloadLinkResponse.hpp>
#include <alibabacloud/models/InstallBackupClientsRequest.hpp>
#include <alibabacloud/models/InstallBackupClientsShrinkRequest.hpp>
#include <alibabacloud/models/InstallBackupClientsResponseBody.hpp>
#include <alibabacloud/models/InstallBackupClientsResponse.hpp>
#include <alibabacloud/models/ListProtectedResourcesRequest.hpp>
#include <alibabacloud/models/ListProtectedResourcesResponseBody.hpp>
#include <alibabacloud/models/ListProtectedResourcesResponse.hpp>
#include <alibabacloud/models/OpenHbrServiceResponseBody.hpp>
#include <alibabacloud/models/OpenHbrServiceResponse.hpp>
#include <alibabacloud/models/SearchHistoricalSnapshotsRequest.hpp>
#include <alibabacloud/models/SearchHistoricalSnapshotsShrinkRequest.hpp>
#include <alibabacloud/models/SearchHistoricalSnapshotsResponseBody.hpp>
#include <alibabacloud/models/SearchHistoricalSnapshotsResponse.hpp>
#include <alibabacloud/models/StartHanaDatabaseAsyncRequest.hpp>
#include <alibabacloud/models/StartHanaDatabaseAsyncResponseBody.hpp>
#include <alibabacloud/models/StartHanaDatabaseAsyncResponse.hpp>
#include <alibabacloud/models/StopHanaDatabaseAsyncRequest.hpp>
#include <alibabacloud/models/StopHanaDatabaseAsyncResponseBody.hpp>
#include <alibabacloud/models/StopHanaDatabaseAsyncResponse.hpp>
#include <alibabacloud/models/UninstallBackupClientsRequest.hpp>
#include <alibabacloud/models/UninstallBackupClientsShrinkRequest.hpp>
#include <alibabacloud/models/UninstallBackupClientsResponseBody.hpp>
#include <alibabacloud/models/UninstallBackupClientsResponse.hpp>
#include <alibabacloud/models/UninstallClientRequest.hpp>
#include <alibabacloud/models/UninstallClientResponseBody.hpp>
#include <alibabacloud/models/UninstallClientResponse.hpp>
#include <alibabacloud/models/UpdateBackupPlanRequest.hpp>
#include <alibabacloud/models/UpdateBackupPlanShrinkRequest.hpp>
#include <alibabacloud/models/UpdateBackupPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateBackupPlanResponse.hpp>
#include <alibabacloud/models/UpdateClientSettingsRequest.hpp>
#include <alibabacloud/models/UpdateClientSettingsResponseBody.hpp>
#include <alibabacloud/models/UpdateClientSettingsResponse.hpp>
#include <alibabacloud/models/UpdateContainerClusterRequest.hpp>
#include <alibabacloud/models/UpdateContainerClusterResponseBody.hpp>
#include <alibabacloud/models/UpdateContainerClusterResponse.hpp>
#include <alibabacloud/models/UpdateHanaBackupPlanRequest.hpp>
#include <alibabacloud/models/UpdateHanaBackupPlanResponseBody.hpp>
#include <alibabacloud/models/UpdateHanaBackupPlanResponse.hpp>
#include <alibabacloud/models/UpdateHanaBackupSettingRequest.hpp>
#include <alibabacloud/models/UpdateHanaBackupSettingResponseBody.hpp>
#include <alibabacloud/models/UpdateHanaBackupSettingResponse.hpp>
#include <alibabacloud/models/UpdateHanaInstanceRequest.hpp>
#include <alibabacloud/models/UpdateHanaInstanceResponseBody.hpp>
#include <alibabacloud/models/UpdateHanaInstanceResponse.hpp>
#include <alibabacloud/models/UpdateHanaRetentionSettingRequest.hpp>
#include <alibabacloud/models/UpdateHanaRetentionSettingResponseBody.hpp>
#include <alibabacloud/models/UpdateHanaRetentionSettingResponse.hpp>
#include <alibabacloud/models/UpdatePolicyBindingRequest.hpp>
#include <alibabacloud/models/UpdatePolicyBindingShrinkRequest.hpp>
#include <alibabacloud/models/UpdatePolicyBindingResponseBody.hpp>
#include <alibabacloud/models/UpdatePolicyBindingResponse.hpp>
#include <alibabacloud/models/UpdatePolicyV2Request.hpp>
#include <alibabacloud/models/UpdatePolicyV2ShrinkRequest.hpp>
#include <alibabacloud/models/UpdatePolicyV2ResponseBody.hpp>
#include <alibabacloud/models/UpdatePolicyV2Response.hpp>
#include <alibabacloud/models/UpdateVaultRequest.hpp>
#include <alibabacloud/models/UpdateVaultResponseBody.hpp>
#include <alibabacloud/models/UpdateVaultResponse.hpp>
#include <alibabacloud/models/UpgradeBackupClientsRequest.hpp>
#include <alibabacloud/models/UpgradeBackupClientsShrinkRequest.hpp>
#include <alibabacloud/models/UpgradeBackupClientsResponseBody.hpp>
#include <alibabacloud/models/UpgradeBackupClientsResponse.hpp>
#include <alibabacloud/models/UpgradeClientRequest.hpp>
#include <alibabacloud/models/UpgradeClientResponseBody.hpp>
#include <alibabacloud/models/UpgradeClientResponse.hpp>

#endif
