// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_CONTACTCENTERAI20240603MODEL_HPP_
#define ALIBABACLOUD_CONTACTCENTERAI20240603MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequest.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncResponseBody.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncResponse.hpp>
#include <alibabacloud/models/AnalyzeConversationRequest.hpp>
#include <alibabacloud/models/AnalyzeConversationResponseBody.hpp>
#include <alibabacloud/models/AnalyzeConversationResponse.hpp>
#include <alibabacloud/models/AnalyzeImageRequest.hpp>
#include <alibabacloud/models/AnalyzeImageResponseBody.hpp>
#include <alibabacloud/models/AnalyzeImageResponse.hpp>
#include <alibabacloud/models/CreateTaskRequest.hpp>
#include <alibabacloud/models/CreateTaskResponseBody.hpp>
#include <alibabacloud/models/CreateTaskResponse.hpp>
#include <alibabacloud/models/CreateVocabRequest.hpp>
#include <alibabacloud/models/CreateVocabResponseBody.hpp>
#include <alibabacloud/models/CreateVocabResponse.hpp>
#include <alibabacloud/models/DeleteVocabRequest.hpp>
#include <alibabacloud/models/DeleteVocabResponseBody.hpp>
#include <alibabacloud/models/DeleteVocabResponse.hpp>
#include <alibabacloud/models/GeneralAnalyzeImageRequest.hpp>
#include <alibabacloud/models/GeneralAnalyzeImageResponseBody.hpp>
#include <alibabacloud/models/GeneralAnalyzeImageResponse.hpp>
#include <alibabacloud/models/GetTaskResultRequest.hpp>
#include <alibabacloud/models/GetTaskResultShrinkRequest.hpp>
#include <alibabacloud/models/GetTaskResultResponseBody.hpp>
#include <alibabacloud/models/GetTaskResultResponse.hpp>
#include <alibabacloud/models/GetVocabRequest.hpp>
#include <alibabacloud/models/GetVocabResponseBody.hpp>
#include <alibabacloud/models/GetVocabResponse.hpp>
#include <alibabacloud/models/ListVocabRequest.hpp>
#include <alibabacloud/models/ListVocabResponseBody.hpp>
#include <alibabacloud/models/ListVocabResponse.hpp>
#include <alibabacloud/models/RunCompletionRequest.hpp>
#include <alibabacloud/models/RunCompletionResponseBody.hpp>
#include <alibabacloud/models/RunCompletionResponse.hpp>
#include <alibabacloud/models/RunCompletionMessageRequest.hpp>
#include <alibabacloud/models/RunCompletionMessageResponseBody.hpp>
#include <alibabacloud/models/RunCompletionMessageResponse.hpp>
#include <alibabacloud/models/UpdateVocabRequest.hpp>
#include <alibabacloud/models/UpdateVocabResponseBody.hpp>
#include <alibabacloud/models/UpdateVocabResponse.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestCategoryTags.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestFieldsEnumValues.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestFields.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestServiceInspectionInspectionContents.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestServiceInspection.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestTranscription.hpp>
#include <alibabacloud/models/AnalyzeAudioSyncRequestVariables.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestCategoryTags.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestDialogueSentences.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestDialogue.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestExamplesSentences.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestExamples.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestFieldsEnumValues.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestFields.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestServiceInspectionInspectionContents.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestServiceInspection.hpp>
#include <alibabacloud/models/AnalyzeConversationRequestUserProfiles.hpp>
#include <alibabacloud/models/CreateTaskRequestCategoryTags.hpp>
#include <alibabacloud/models/CreateTaskRequestDialogueSentences.hpp>
#include <alibabacloud/models/CreateTaskRequestDialogue.hpp>
#include <alibabacloud/models/CreateTaskRequestExamplesSentences.hpp>
#include <alibabacloud/models/CreateTaskRequestExamples.hpp>
#include <alibabacloud/models/CreateTaskRequestFieldsEnumValues.hpp>
#include <alibabacloud/models/CreateTaskRequestFields.hpp>
#include <alibabacloud/models/CreateTaskRequestServiceInspectionInspectionContents.hpp>
#include <alibabacloud/models/CreateTaskRequestServiceInspection.hpp>
#include <alibabacloud/models/CreateTaskRequestTranscription.hpp>
#include <alibabacloud/models/CreateTaskRequestVariables.hpp>
#include <alibabacloud/models/CreateTaskResponseBodyData.hpp>
#include <alibabacloud/models/CreateVocabRequestWordWeightList.hpp>
#include <alibabacloud/models/CreateVocabResponseBodyData.hpp>
#include <alibabacloud/models/GetTaskResultResponseBodyDataAsrResult.hpp>
#include <alibabacloud/models/GetTaskResultResponseBodyData.hpp>
#include <alibabacloud/models/GetVocabResponseBodyDataWordWeightList.hpp>
#include <alibabacloud/models/GetVocabResponseBodyData.hpp>
#include <alibabacloud/models/ListVocabResponseBodyDataWordWeightList.hpp>
#include <alibabacloud/models/ListVocabResponseBodyData.hpp>
#include <alibabacloud/models/RunCompletionRequestDialogueSentences.hpp>
#include <alibabacloud/models/RunCompletionRequestDialogue.hpp>
#include <alibabacloud/models/RunCompletionRequestFieldsEnumValues.hpp>
#include <alibabacloud/models/RunCompletionRequestFields.hpp>
#include <alibabacloud/models/RunCompletionRequestServiceInspectionInspectionContents.hpp>
#include <alibabacloud/models/RunCompletionRequestServiceInspection.hpp>
#include <alibabacloud/models/RunCompletionRequestVariables.hpp>
#include <alibabacloud/models/RunCompletionMessageRequestMessages.hpp>
#include <alibabacloud/models/UpdateVocabRequestWordWeightList.hpp>

#endif
