// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_CREATEPLAYBOOKRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_CREATEPLAYBOOKRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/CreatePlaybookResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sophonsoar20220728
{
namespace Models
{
  class CreatePlaybookResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const CreatePlaybookResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, CreatePlaybookResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    CreatePlaybookResponseBody() = default ;
    CreatePlaybookResponseBody(const CreatePlaybookResponseBody &) = default ;
    CreatePlaybookResponseBody(CreatePlaybookResponseBody &&) = default ;
    CreatePlaybookResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~CreatePlaybookResponseBody() = default ;
    CreatePlaybookResponseBody& operator=(const CreatePlaybookResponseBody &) = default ;
    CreatePlaybookResponseBody& operator=(CreatePlaybookResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->data_ == nullptr
        && return this->requestId_ == nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const CreatePlaybookResponseBodyData & data() const { DARABONBA_PTR_GET_CONST(data_, CreatePlaybookResponseBodyData) };
    inline CreatePlaybookResponseBodyData data() { DARABONBA_PTR_GET(data_, CreatePlaybookResponseBodyData) };
    inline CreatePlaybookResponseBody& setData(const CreatePlaybookResponseBodyData & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline CreatePlaybookResponseBody& setData(CreatePlaybookResponseBodyData && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline CreatePlaybookResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // The result of the creation.
    std::shared_ptr<CreatePlaybookResponseBodyData> data_ = nullptr;
    // The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sophonsoar20220728
#endif
