// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBESOARRECORDSRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBESOARRECORDSRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DescribeSoarRecordsResponseBodyPage.hpp>
#include <vector>
#include <alibabacloud/models/DescribeSoarRecordsResponseBodySoarExecuteRecords.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sophonsoar20220728
{
namespace Models
{
  class DescribeSoarRecordsResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeSoarRecordsResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Page, page_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
      DARABONBA_PTR_TO_JSON(SoarExecuteRecords, soarExecuteRecords_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeSoarRecordsResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Page, page_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
      DARABONBA_PTR_FROM_JSON(SoarExecuteRecords, soarExecuteRecords_);
    };
    DescribeSoarRecordsResponseBody() = default ;
    DescribeSoarRecordsResponseBody(const DescribeSoarRecordsResponseBody &) = default ;
    DescribeSoarRecordsResponseBody(DescribeSoarRecordsResponseBody &&) = default ;
    DescribeSoarRecordsResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeSoarRecordsResponseBody() = default ;
    DescribeSoarRecordsResponseBody& operator=(const DescribeSoarRecordsResponseBody &) = default ;
    DescribeSoarRecordsResponseBody& operator=(DescribeSoarRecordsResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->page_ == nullptr
        && return this->requestId_ == nullptr && return this->soarExecuteRecords_ == nullptr; };
    // page Field Functions 
    bool hasPage() const { return this->page_ != nullptr;};
    void deletePage() { this->page_ = nullptr;};
    inline const DescribeSoarRecordsResponseBodyPage & page() const { DARABONBA_PTR_GET_CONST(page_, DescribeSoarRecordsResponseBodyPage) };
    inline DescribeSoarRecordsResponseBodyPage page() { DARABONBA_PTR_GET(page_, DescribeSoarRecordsResponseBodyPage) };
    inline DescribeSoarRecordsResponseBody& setPage(const DescribeSoarRecordsResponseBodyPage & page) { DARABONBA_PTR_SET_VALUE(page_, page) };
    inline DescribeSoarRecordsResponseBody& setPage(DescribeSoarRecordsResponseBodyPage && page) { DARABONBA_PTR_SET_RVALUE(page_, page) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeSoarRecordsResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


    // soarExecuteRecords Field Functions 
    bool hasSoarExecuteRecords() const { return this->soarExecuteRecords_ != nullptr;};
    void deleteSoarExecuteRecords() { this->soarExecuteRecords_ = nullptr;};
    inline const vector<DescribeSoarRecordsResponseBodySoarExecuteRecords> & soarExecuteRecords() const { DARABONBA_PTR_GET_CONST(soarExecuteRecords_, vector<DescribeSoarRecordsResponseBodySoarExecuteRecords>) };
    inline vector<DescribeSoarRecordsResponseBodySoarExecuteRecords> soarExecuteRecords() { DARABONBA_PTR_GET(soarExecuteRecords_, vector<DescribeSoarRecordsResponseBodySoarExecuteRecords>) };
    inline DescribeSoarRecordsResponseBody& setSoarExecuteRecords(const vector<DescribeSoarRecordsResponseBodySoarExecuteRecords> & soarExecuteRecords) { DARABONBA_PTR_SET_VALUE(soarExecuteRecords_, soarExecuteRecords) };
    inline DescribeSoarRecordsResponseBody& setSoarExecuteRecords(vector<DescribeSoarRecordsResponseBodySoarExecuteRecords> && soarExecuteRecords) { DARABONBA_PTR_SET_RVALUE(soarExecuteRecords_, soarExecuteRecords) };


  protected:
    // Information displayed on the page.
    // 
    // This parameter is required.
    std::shared_ptr<DescribeSoarRecordsResponseBodyPage> page_ = nullptr;
    // The ID of the current request, generated by Alibaba Cloud as a unique identifier for the request, which can be used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
    // Execution record result set.
    std::shared_ptr<vector<DescribeSoarRecordsResponseBodySoarExecuteRecords>> soarExecuteRecords_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sophonsoar20220728
#endif
