// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBEPROCESSTASKCOUNTRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBEPROCESSTASKCOUNTRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/DescribeProcessTaskCountResponseBodyData.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sophonsoar20220728
{
namespace Models
{
  class DescribeProcessTaskCountResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeProcessTaskCountResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(Data, data_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeProcessTaskCountResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(Data, data_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    DescribeProcessTaskCountResponseBody() = default ;
    DescribeProcessTaskCountResponseBody(const DescribeProcessTaskCountResponseBody &) = default ;
    DescribeProcessTaskCountResponseBody(DescribeProcessTaskCountResponseBody &&) = default ;
    DescribeProcessTaskCountResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeProcessTaskCountResponseBody() = default ;
    DescribeProcessTaskCountResponseBody& operator=(const DescribeProcessTaskCountResponseBody &) = default ;
    DescribeProcessTaskCountResponseBody& operator=(DescribeProcessTaskCountResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->data_ == nullptr
        && return this->requestId_ == nullptr; };
    // data Field Functions 
    bool hasData() const { return this->data_ != nullptr;};
    void deleteData() { this->data_ = nullptr;};
    inline const vector<DescribeProcessTaskCountResponseBodyData> & data() const { DARABONBA_PTR_GET_CONST(data_, vector<DescribeProcessTaskCountResponseBodyData>) };
    inline vector<DescribeProcessTaskCountResponseBodyData> data() { DARABONBA_PTR_GET(data_, vector<DescribeProcessTaskCountResponseBodyData>) };
    inline DescribeProcessTaskCountResponseBody& setData(const vector<DescribeProcessTaskCountResponseBodyData> & data) { DARABONBA_PTR_SET_VALUE(data_, data) };
    inline DescribeProcessTaskCountResponseBody& setData(vector<DescribeProcessTaskCountResponseBodyData> && data) { DARABONBA_PTR_SET_RVALUE(data_, data) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeProcessTaskCountResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Transmitted data.
    std::shared_ptr<vector<DescribeProcessTaskCountResponseBodyData>> data_ = nullptr;
    // The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request, used for troubleshooting and problem localization.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sophonsoar20220728
#endif
