// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_MODELS_DESCRIBEVENDORAPILISTRESPONSEBODY_HPP_
#define ALIBABACLOUD_MODELS_DESCRIBEVENDORAPILISTRESPONSEBODY_HPP_
#include <darabonba/Core.hpp>
#include <vector>
#include <alibabacloud/models/DescribeVendorApiListResponseBodyApiList.hpp>
#include <alibabacloud/models/DescribeVendorApiListResponseBodyPage.hpp>
using namespace std;
using json = nlohmann::json;
namespace AlibabaCloud
{
namespace Sophonsoar20220728
{
namespace Models
{
  class DescribeVendorApiListResponseBody : public Darabonba::Model {
  public:
    friend void to_json(Darabonba::Json& j, const DescribeVendorApiListResponseBody& obj) { 
      DARABONBA_PTR_TO_JSON(ApiList, apiList_);
      DARABONBA_PTR_TO_JSON(Page, page_);
      DARABONBA_PTR_TO_JSON(RequestId, requestId_);
    };
    friend void from_json(const Darabonba::Json& j, DescribeVendorApiListResponseBody& obj) { 
      DARABONBA_PTR_FROM_JSON(ApiList, apiList_);
      DARABONBA_PTR_FROM_JSON(Page, page_);
      DARABONBA_PTR_FROM_JSON(RequestId, requestId_);
    };
    DescribeVendorApiListResponseBody() = default ;
    DescribeVendorApiListResponseBody(const DescribeVendorApiListResponseBody &) = default ;
    DescribeVendorApiListResponseBody(DescribeVendorApiListResponseBody &&) = default ;
    DescribeVendorApiListResponseBody(const Darabonba::Json & obj) { from_json(obj, *this); };
    virtual ~DescribeVendorApiListResponseBody() = default ;
    DescribeVendorApiListResponseBody& operator=(const DescribeVendorApiListResponseBody &) = default ;
    DescribeVendorApiListResponseBody& operator=(DescribeVendorApiListResponseBody &&) = default ;
    virtual void validate() const override {
    };
    virtual void fromMap(const Darabonba::Json &obj) override { from_json(obj, *this); validate(); };
    virtual Darabonba::Json toMap() const override { Darabonba::Json obj; to_json(obj, *this); return obj; };
    virtual bool empty() const override { return this->apiList_ == nullptr
        && return this->page_ == nullptr && return this->requestId_ == nullptr; };
    // apiList Field Functions 
    bool hasApiList() const { return this->apiList_ != nullptr;};
    void deleteApiList() { this->apiList_ = nullptr;};
    inline const vector<DescribeVendorApiListResponseBodyApiList> & apiList() const { DARABONBA_PTR_GET_CONST(apiList_, vector<DescribeVendorApiListResponseBodyApiList>) };
    inline vector<DescribeVendorApiListResponseBodyApiList> apiList() { DARABONBA_PTR_GET(apiList_, vector<DescribeVendorApiListResponseBodyApiList>) };
    inline DescribeVendorApiListResponseBody& setApiList(const vector<DescribeVendorApiListResponseBodyApiList> & apiList) { DARABONBA_PTR_SET_VALUE(apiList_, apiList) };
    inline DescribeVendorApiListResponseBody& setApiList(vector<DescribeVendorApiListResponseBodyApiList> && apiList) { DARABONBA_PTR_SET_RVALUE(apiList_, apiList) };


    // page Field Functions 
    bool hasPage() const { return this->page_ != nullptr;};
    void deletePage() { this->page_ = nullptr;};
    inline const DescribeVendorApiListResponseBodyPage & page() const { DARABONBA_PTR_GET_CONST(page_, DescribeVendorApiListResponseBodyPage) };
    inline DescribeVendorApiListResponseBodyPage page() { DARABONBA_PTR_GET(page_, DescribeVendorApiListResponseBodyPage) };
    inline DescribeVendorApiListResponseBody& setPage(const DescribeVendorApiListResponseBodyPage & page) { DARABONBA_PTR_SET_VALUE(page_, page) };
    inline DescribeVendorApiListResponseBody& setPage(DescribeVendorApiListResponseBodyPage && page) { DARABONBA_PTR_SET_RVALUE(page_, page) };


    // requestId Field Functions 
    bool hasRequestId() const { return this->requestId_ != nullptr;};
    void deleteRequestId() { this->requestId_ = nullptr;};
    inline string requestId() const { DARABONBA_PTR_GET_DEFAULT(requestId_, "") };
    inline DescribeVendorApiListResponseBody& setRequestId(string requestId) { DARABONBA_PTR_SET_VALUE(requestId_, requestId) };


  protected:
    // Product information.
    std::shared_ptr<vector<DescribeVendorApiListResponseBodyApiList>> apiList_ = nullptr;
    // Pagination query information.
    std::shared_ptr<DescribeVendorApiListResponseBodyPage> page_ = nullptr;
    // The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request, and can be used to troubleshoot and locate issues.
    std::shared_ptr<string> requestId_ = nullptr;
  };

  } // namespace Models
} // namespace AlibabaCloud
} // namespace Sophonsoar20220728
#endif
