// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_EDSAIC20230930MODEL_HPP_
#define ALIBABACLOUD_EDSAIC20230930MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/DataImageRegionDistributeMapValue.hpp>
#include <alibabacloud/models/AttachKeyPairRequest.hpp>
#include <alibabacloud/models/AttachKeyPairResponseBody.hpp>
#include <alibabacloud/models/AttachKeyPairResponse.hpp>
#include <alibabacloud/models/AuthorizeAndroidInstanceRequest.hpp>
#include <alibabacloud/models/AuthorizeAndroidInstanceResponseBody.hpp>
#include <alibabacloud/models/AuthorizeAndroidInstanceResponse.hpp>
#include <alibabacloud/models/BackupFileRequest.hpp>
#include <alibabacloud/models/BackupFileResponseBody.hpp>
#include <alibabacloud/models/BackupFileResponse.hpp>
#include <alibabacloud/models/BatchGetAcpConnectionTicketRequest.hpp>
#include <alibabacloud/models/BatchGetAcpConnectionTicketResponseBody.hpp>
#include <alibabacloud/models/BatchGetAcpConnectionTicketResponse.hpp>
#include <alibabacloud/models/ChangeCloudPhoneNodeRequest.hpp>
#include <alibabacloud/models/ChangeCloudPhoneNodeResponseBody.hpp>
#include <alibabacloud/models/ChangeCloudPhoneNodeResponse.hpp>
#include <alibabacloud/models/CheckResourceStockRequest.hpp>
#include <alibabacloud/models/CheckResourceStockResponseBody.hpp>
#include <alibabacloud/models/CheckResourceStockResponse.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupRequest.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupShrinkRequest.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupResponse.hpp>
#include <alibabacloud/models/CreateAppRequest.hpp>
#include <alibabacloud/models/CreateAppShrinkRequest.hpp>
#include <alibabacloud/models/CreateAppResponseBody.hpp>
#include <alibabacloud/models/CreateAppResponse.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeRequest.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeShrinkRequest.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeResponseBody.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeResponse.hpp>
#include <alibabacloud/models/CreateCustomImageRequest.hpp>
#include <alibabacloud/models/CreateCustomImageResponseBody.hpp>
#include <alibabacloud/models/CreateCustomImageResponse.hpp>
#include <alibabacloud/models/CreateKeyPairRequest.hpp>
#include <alibabacloud/models/CreateKeyPairResponseBody.hpp>
#include <alibabacloud/models/CreateKeyPairResponse.hpp>
#include <alibabacloud/models/CreatePolicyGroupRequest.hpp>
#include <alibabacloud/models/CreatePolicyGroupShrinkRequest.hpp>
#include <alibabacloud/models/CreatePolicyGroupResponseBody.hpp>
#include <alibabacloud/models/CreatePolicyGroupResponse.hpp>
#include <alibabacloud/models/CreateScreenshotRequest.hpp>
#include <alibabacloud/models/CreateScreenshotResponseBody.hpp>
#include <alibabacloud/models/CreateScreenshotResponse.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateRequest.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateShrinkRequest.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateResponseBody.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateResponse.hpp>
#include <alibabacloud/models/DeleteAndroidInstanceGroupRequest.hpp>
#include <alibabacloud/models/DeleteAndroidInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/DeleteAndroidInstanceGroupResponse.hpp>
#include <alibabacloud/models/DeleteAppsRequest.hpp>
#include <alibabacloud/models/DeleteAppsResponseBody.hpp>
#include <alibabacloud/models/DeleteAppsResponse.hpp>
#include <alibabacloud/models/DeleteBackupFileRequest.hpp>
#include <alibabacloud/models/DeleteBackupFileResponseBody.hpp>
#include <alibabacloud/models/DeleteBackupFileResponse.hpp>
#include <alibabacloud/models/DeleteCloudPhoneNodesRequest.hpp>
#include <alibabacloud/models/DeleteCloudPhoneNodesResponseBody.hpp>
#include <alibabacloud/models/DeleteCloudPhoneNodesResponse.hpp>
#include <alibabacloud/models/DeleteImagesRequest.hpp>
#include <alibabacloud/models/DeleteImagesShrinkRequest.hpp>
#include <alibabacloud/models/DeleteImagesResponseBody.hpp>
#include <alibabacloud/models/DeleteImagesResponse.hpp>
#include <alibabacloud/models/DeleteKeyPairsRequest.hpp>
#include <alibabacloud/models/DeleteKeyPairsResponseBody.hpp>
#include <alibabacloud/models/DeleteKeyPairsResponse.hpp>
#include <alibabacloud/models/DeletePolicyGroupRequest.hpp>
#include <alibabacloud/models/DeletePolicyGroupResponseBody.hpp>
#include <alibabacloud/models/DeletePolicyGroupResponse.hpp>
#include <alibabacloud/models/DeleteSystemPropertyTemplatesRequest.hpp>
#include <alibabacloud/models/DeleteSystemPropertyTemplatesResponseBody.hpp>
#include <alibabacloud/models/DeleteSystemPropertyTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsRequest.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsResponseBody.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsResponse.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesRequest.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBody.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponse.hpp>
#include <alibabacloud/models/DescribeAppsRequest.hpp>
#include <alibabacloud/models/DescribeAppsResponseBody.hpp>
#include <alibabacloud/models/DescribeAppsResponse.hpp>
#include <alibabacloud/models/DescribeBackupFilesRequest.hpp>
#include <alibabacloud/models/DescribeBackupFilesResponseBody.hpp>
#include <alibabacloud/models/DescribeBackupFilesResponse.hpp>
#include <alibabacloud/models/DescribeBucketsRequest.hpp>
#include <alibabacloud/models/DescribeBucketsResponseBody.hpp>
#include <alibabacloud/models/DescribeBucketsResponse.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesRequest.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponseBody.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponse.hpp>
#include <alibabacloud/models/DescribeDisplayConfigRequest.hpp>
#include <alibabacloud/models/DescribeDisplayConfigResponseBody.hpp>
#include <alibabacloud/models/DescribeDisplayConfigResponse.hpp>
#include <alibabacloud/models/DescribeImageListRequest.hpp>
#include <alibabacloud/models/DescribeImageListResponseBody.hpp>
#include <alibabacloud/models/DescribeImageListResponse.hpp>
#include <alibabacloud/models/DescribeInvocationsRequest.hpp>
#include <alibabacloud/models/DescribeInvocationsResponseBody.hpp>
#include <alibabacloud/models/DescribeInvocationsResponse.hpp>
#include <alibabacloud/models/DescribeKeyPairsRequest.hpp>
#include <alibabacloud/models/DescribeKeyPairsResponseBody.hpp>
#include <alibabacloud/models/DescribeKeyPairsResponse.hpp>
#include <alibabacloud/models/DescribeMetricLastRequest.hpp>
#include <alibabacloud/models/DescribeMetricLastResponseBody.hpp>
#include <alibabacloud/models/DescribeMetricLastResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeSpecRequest.hpp>
#include <alibabacloud/models/DescribeSpecResponseBody.hpp>
#include <alibabacloud/models/DescribeSpecResponse.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesRequest.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesResponseBody.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesResponse.hpp>
#include <alibabacloud/models/DescribeTasksRequest.hpp>
#include <alibabacloud/models/DescribeTasksResponseBody.hpp>
#include <alibabacloud/models/DescribeTasksResponse.hpp>
#include <alibabacloud/models/DetachKeyPairRequest.hpp>
#include <alibabacloud/models/DetachKeyPairResponseBody.hpp>
#include <alibabacloud/models/DetachKeyPairResponse.hpp>
#include <alibabacloud/models/DisconnectAndroidInstanceRequest.hpp>
#include <alibabacloud/models/DisconnectAndroidInstanceResponseBody.hpp>
#include <alibabacloud/models/DisconnectAndroidInstanceResponse.hpp>
#include <alibabacloud/models/DistributeImageRequest.hpp>
#include <alibabacloud/models/DistributeImageResponseBody.hpp>
#include <alibabacloud/models/DistributeImageResponse.hpp>
#include <alibabacloud/models/DowngradeAndroidInstanceGroupRequest.hpp>
#include <alibabacloud/models/DowngradeAndroidInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/DowngradeAndroidInstanceGroupResponse.hpp>
#include <alibabacloud/models/EndCoordinationRequest.hpp>
#include <alibabacloud/models/EndCoordinationResponseBody.hpp>
#include <alibabacloud/models/EndCoordinationResponse.hpp>
#include <alibabacloud/models/ExpandDataVolumeRequest.hpp>
#include <alibabacloud/models/ExpandDataVolumeResponseBody.hpp>
#include <alibabacloud/models/ExpandDataVolumeResponse.hpp>
#include <alibabacloud/models/ExpandPhoneDataVolumeRequest.hpp>
#include <alibabacloud/models/ExpandPhoneDataVolumeResponseBody.hpp>
#include <alibabacloud/models/ExpandPhoneDataVolumeResponse.hpp>
#include <alibabacloud/models/FetchFileRequest.hpp>
#include <alibabacloud/models/FetchFileResponseBody.hpp>
#include <alibabacloud/models/FetchFileResponse.hpp>
#include <alibabacloud/models/GenerateCoordinationCodeRequest.hpp>
#include <alibabacloud/models/GenerateCoordinationCodeResponseBody.hpp>
#include <alibabacloud/models/GenerateCoordinationCodeResponse.hpp>
#include <alibabacloud/models/GetInstancePropertiesRequest.hpp>
#include <alibabacloud/models/GetInstancePropertiesResponseBody.hpp>
#include <alibabacloud/models/GetInstancePropertiesResponse.hpp>
#include <alibabacloud/models/ImportKeyPairRequest.hpp>
#include <alibabacloud/models/ImportKeyPairResponseBody.hpp>
#include <alibabacloud/models/ImportKeyPairResponse.hpp>
#include <alibabacloud/models/InstallAppRequest.hpp>
#include <alibabacloud/models/InstallAppResponseBody.hpp>
#include <alibabacloud/models/InstallAppResponse.hpp>
#include <alibabacloud/models/InstallMonitorAgentRequest.hpp>
#include <alibabacloud/models/InstallMonitorAgentResponseBody.hpp>
#include <alibabacloud/models/InstallMonitorAgentResponse.hpp>
#include <alibabacloud/models/InstanceHealerRequest.hpp>
#include <alibabacloud/models/InstanceHealerResponseBody.hpp>
#include <alibabacloud/models/InstanceHealerResponse.hpp>
#include <alibabacloud/models/ListPolicyGroupsRequest.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBody.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceRequest.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceResponseBody.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceResponse.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceGroupRequest.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyAndroidInstanceGroupResponse.hpp>
#include <alibabacloud/models/ModifyAppRequest.hpp>
#include <alibabacloud/models/ModifyAppResponseBody.hpp>
#include <alibabacloud/models/ModifyAppResponse.hpp>
#include <alibabacloud/models/ModifyCloudPhoneNodeRequest.hpp>
#include <alibabacloud/models/ModifyCloudPhoneNodeResponseBody.hpp>
#include <alibabacloud/models/ModifyCloudPhoneNodeResponse.hpp>
#include <alibabacloud/models/ModifyDisplayConfigRequest.hpp>
#include <alibabacloud/models/ModifyDisplayConfigShrinkRequest.hpp>
#include <alibabacloud/models/ModifyDisplayConfigResponseBody.hpp>
#include <alibabacloud/models/ModifyDisplayConfigResponse.hpp>
#include <alibabacloud/models/ModifyInstanceChargeTypeRequest.hpp>
#include <alibabacloud/models/ModifyInstanceChargeTypeResponseBody.hpp>
#include <alibabacloud/models/ModifyInstanceChargeTypeResponse.hpp>
#include <alibabacloud/models/ModifyKeyPairNameRequest.hpp>
#include <alibabacloud/models/ModifyKeyPairNameResponseBody.hpp>
#include <alibabacloud/models/ModifyKeyPairNameResponse.hpp>
#include <alibabacloud/models/ModifyPolicyGroupRequest.hpp>
#include <alibabacloud/models/ModifyPolicyGroupShrinkRequest.hpp>
#include <alibabacloud/models/ModifyPolicyGroupResponseBody.hpp>
#include <alibabacloud/models/ModifyPolicyGroupResponse.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateRequest.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateShrinkRequest.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateResponseBody.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateResponse.hpp>
#include <alibabacloud/models/OperateAppRequest.hpp>
#include <alibabacloud/models/OperateAppResponseBody.hpp>
#include <alibabacloud/models/OperateAppResponse.hpp>
#include <alibabacloud/models/RebootAndroidInstancesInGroupRequest.hpp>
#include <alibabacloud/models/RebootAndroidInstancesInGroupResponseBody.hpp>
#include <alibabacloud/models/RebootAndroidInstancesInGroupResponse.hpp>
#include <alibabacloud/models/RecoveryFileRequest.hpp>
#include <alibabacloud/models/RecoveryFileResponseBody.hpp>
#include <alibabacloud/models/RecoveryFileResponse.hpp>
#include <alibabacloud/models/RenewAndroidInstanceGroupsRequest.hpp>
#include <alibabacloud/models/RenewAndroidInstanceGroupsResponseBody.hpp>
#include <alibabacloud/models/RenewAndroidInstanceGroupsResponse.hpp>
#include <alibabacloud/models/RenewCloudPhoneNodesRequest.hpp>
#include <alibabacloud/models/RenewCloudPhoneNodesResponseBody.hpp>
#include <alibabacloud/models/RenewCloudPhoneNodesResponse.hpp>
#include <alibabacloud/models/ResetAndroidInstancesInGroupRequest.hpp>
#include <alibabacloud/models/ResetAndroidInstancesInGroupResponseBody.hpp>
#include <alibabacloud/models/ResetAndroidInstancesInGroupResponse.hpp>
#include <alibabacloud/models/RunCommandRequest.hpp>
#include <alibabacloud/models/RunCommandResponseBody.hpp>
#include <alibabacloud/models/RunCommandResponse.hpp>
#include <alibabacloud/models/SendFileRequest.hpp>
#include <alibabacloud/models/SendFileResponseBody.hpp>
#include <alibabacloud/models/SendFileResponse.hpp>
#include <alibabacloud/models/SendSystemPropertyTemplateRequest.hpp>
#include <alibabacloud/models/SendSystemPropertyTemplateResponseBody.hpp>
#include <alibabacloud/models/SendSystemPropertyTemplateResponse.hpp>
#include <alibabacloud/models/SetAdbSecureRequest.hpp>
#include <alibabacloud/models/SetAdbSecureResponseBody.hpp>
#include <alibabacloud/models/SetAdbSecureResponse.hpp>
#include <alibabacloud/models/StartAndroidInstanceRequest.hpp>
#include <alibabacloud/models/StartAndroidInstanceResponseBody.hpp>
#include <alibabacloud/models/StartAndroidInstanceResponse.hpp>
#include <alibabacloud/models/StopAndroidInstanceRequest.hpp>
#include <alibabacloud/models/StopAndroidInstanceResponseBody.hpp>
#include <alibabacloud/models/StopAndroidInstanceResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UninstallAppRequest.hpp>
#include <alibabacloud/models/UninstallAppResponseBody.hpp>
#include <alibabacloud/models/UninstallAppResponse.hpp>
#include <alibabacloud/models/UninstallMonitorAgentRequest.hpp>
#include <alibabacloud/models/UninstallMonitorAgentResponseBody.hpp>
#include <alibabacloud/models/UninstallMonitorAgentResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateCustomImageNameRequest.hpp>
#include <alibabacloud/models/UpdateCustomImageNameResponseBody.hpp>
#include <alibabacloud/models/UpdateCustomImageNameResponse.hpp>
#include <alibabacloud/models/UpdateInstanceGroupImageRequest.hpp>
#include <alibabacloud/models/UpdateInstanceGroupImageResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceGroupImageResponse.hpp>
#include <alibabacloud/models/UpdateInstanceImageRequest.hpp>
#include <alibabacloud/models/UpdateInstanceImageResponseBody.hpp>
#include <alibabacloud/models/UpdateInstanceImageResponse.hpp>
#include <alibabacloud/models/UpgradeAndroidInstanceGroupRequest.hpp>
#include <alibabacloud/models/UpgradeAndroidInstanceGroupResponseBody.hpp>
#include <alibabacloud/models/UpgradeAndroidInstanceGroupResponse.hpp>
#include <alibabacloud/models/AttachKeyPairResponseBodyData.hpp>
#include <alibabacloud/models/BackupFileResponseBodyData.hpp>
#include <alibabacloud/models/BatchGetAcpConnectionTicketRequestInstanceTasks.hpp>
#include <alibabacloud/models/BatchGetAcpConnectionTicketResponseBodyInstanceConnectionModels.hpp>
#include <alibabacloud/models/ChangeCloudPhoneNodeResponseBodyNodeInfosInstanceInfos.hpp>
#include <alibabacloud/models/ChangeCloudPhoneNodeResponseBodyNodeInfos.hpp>
#include <alibabacloud/models/CheckResourceStockResponseBodyResourceStockModels.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupRequestNetworkInfo.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupRequestTag.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupShrinkRequestTag.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupResponseBodyInstanceGroupInfos.hpp>
#include <alibabacloud/models/CreateAndroidInstanceGroupResponseBodyNetworkPackageOrderModel.hpp>
#include <alibabacloud/models/CreateAppRequestCustomAppInfo.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeRequestDisplayConfig.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeRequestNetworkInfo.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeRequestTag.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeShrinkRequestTag.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeResponseBodyNetworkPackageOrderModel.hpp>
#include <alibabacloud/models/CreateCloudPhoneNodeResponseBodyNodeInfos.hpp>
#include <alibabacloud/models/CreateKeyPairResponseBodyData.hpp>
#include <alibabacloud/models/CreatePolicyGroupRequestNetRedirectPolicyRules.hpp>
#include <alibabacloud/models/CreatePolicyGroupRequestNetRedirectPolicy.hpp>
#include <alibabacloud/models/CreatePolicyGroupRequestWatermark.hpp>
#include <alibabacloud/models/CreateScreenshotResponseBodyTasks.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateRequestSystemPropertyInfoCustomPropertyInfos.hpp>
#include <alibabacloud/models/CreateSystemPropertyTemplateRequestSystemPropertyInfo.hpp>
#include <alibabacloud/models/DeleteImagesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsRequestTags.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsResponseBodyInstanceGroupModelDisks.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsResponseBodyInstanceGroupModelTags.hpp>
#include <alibabacloud/models/DescribeAndroidInstanceGroupsResponseBodyInstanceGroupModel.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesRequestTag.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelAppManagePolicy.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelBizTags.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelDisks.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelDisplayConfig.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelPhoneDataInfo.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModelTags.hpp>
#include <alibabacloud/models/DescribeAndroidInstancesResponseBodyInstanceModel.hpp>
#include <alibabacloud/models/DescribeAppsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeBackupFilesResponseBodyData.hpp>
#include <alibabacloud/models/DescribeBucketsResponseBodyDataOssObjectListOwner.hpp>
#include <alibabacloud/models/DescribeBucketsResponseBodyDataOssObjectList.hpp>
#include <alibabacloud/models/DescribeBucketsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponseBodyNodeModelBizTags.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponseBodyNodeModelNetworkInfos.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponseBodyNodeModelPhoneDataInfo.hpp>
#include <alibabacloud/models/DescribeCloudPhoneNodesResponseBodyNodeModel.hpp>
#include <alibabacloud/models/DescribeDisplayConfigResponseBodyDisplayConfigModel.hpp>
#include <alibabacloud/models/DescribeImageListRequestImageBizTags.hpp>
#include <alibabacloud/models/DescribeImageListResponseBodyDataImageBizTags.hpp>
#include <alibabacloud/models/DescribeImageListResponseBodyData.hpp>
#include <alibabacloud/models/DescribeInvocationsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeKeyPairsResponseBodyData.hpp>
#include <alibabacloud/models/DescribeMetricLastResponseBodyMetricTotalModelMetricModelListDataPoints.hpp>
#include <alibabacloud/models/DescribeMetricLastResponseBodyMetricTotalModelMetricModelListProcessLastInfos.hpp>
#include <alibabacloud/models/DescribeMetricLastResponseBodyMetricTotalModelMetricModelList.hpp>
#include <alibabacloud/models/DescribeMetricLastResponseBodyMetricTotalModel.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionModels.hpp>
#include <alibabacloud/models/DescribeSpecResponseBodySpecInfoModel.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesResponseBodySystemPropertyTemplateModelSystemPropertyInfoCustomPropertyInfos.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesResponseBodySystemPropertyTemplateModelSystemPropertyInfo.hpp>
#include <alibabacloud/models/DescribeSystemPropertyTemplatesResponseBodySystemPropertyTemplateModel.hpp>
#include <alibabacloud/models/DescribeTasksResponseBodyData.hpp>
#include <alibabacloud/models/DetachKeyPairResponseBodyData.hpp>
#include <alibabacloud/models/FetchFileResponseBodyData.hpp>
#include <alibabacloud/models/GetInstancePropertiesResponseBodyPropertyTemplateModel.hpp>
#include <alibabacloud/models/ImportKeyPairResponseBodyData.hpp>
#include <alibabacloud/models/InstanceHealerResponseBodyInstanceHealerModel.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBodyPolicyGroupModelNetRedirectPolicyRules.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBodyPolicyGroupModelNetRedirectPolicy.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBodyPolicyGroupModelPolicyRelatedResources.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBodyPolicyGroupModelWatermark.hpp>
#include <alibabacloud/models/ListPolicyGroupsResponseBodyPolicyGroupModel.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ModifyDisplayConfigRequestDisplayConfig.hpp>
#include <alibabacloud/models/ModifyPolicyGroupRequestNetRedirectPolicyRules.hpp>
#include <alibabacloud/models/ModifyPolicyGroupRequestNetRedirectPolicy.hpp>
#include <alibabacloud/models/ModifyPolicyGroupRequestWatermark.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateRequestSystemPropertyInfoCustomPropertyInfos.hpp>
#include <alibabacloud/models/ModifySystemPropertyTemplateRequestSystemPropertyInfo.hpp>
#include <alibabacloud/models/RecoveryFileResponseBodyData.hpp>
#include <alibabacloud/models/RunCommandResponseBodyRunCommandInfos.hpp>
#include <alibabacloud/models/SendFileResponseBodyData.hpp>
#include <alibabacloud/models/SetAdbSecureResponseBodyData.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
