// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_PRIVATELINK20200415MODEL_HPP_
#define ALIBABACLOUD_PRIVATELINK20200415MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/AddUserToVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/AddUserToVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/AddUserToVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/AddZoneToVpcEndpointRequest.hpp>
#include <alibabacloud/models/AddZoneToVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/AddZoneToVpcEndpointResponse.hpp>
#include <alibabacloud/models/AttachResourceToVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/AttachResourceToVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/AttachResourceToVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/AttachSecurityGroupToVpcEndpointRequest.hpp>
#include <alibabacloud/models/AttachSecurityGroupToVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/AttachSecurityGroupToVpcEndpointResponse.hpp>
#include <alibabacloud/models/ChangeResourceGroupRequest.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponseBody.hpp>
#include <alibabacloud/models/ChangeResourceGroupResponse.hpp>
#include <alibabacloud/models/CheckProductOpenResponseBody.hpp>
#include <alibabacloud/models/CheckProductOpenResponse.hpp>
#include <alibabacloud/models/CreateVpcEndpointRequest.hpp>
#include <alibabacloud/models/CreateVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/CreateVpcEndpointResponse.hpp>
#include <alibabacloud/models/CreateVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/CreateVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/CreateVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/DeleteVpcEndpointRequest.hpp>
#include <alibabacloud/models/DeleteVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcEndpointResponse.hpp>
#include <alibabacloud/models/DeleteVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/DeleteVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/DeleteVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/DescribeRegionsRequest.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBody.hpp>
#include <alibabacloud/models/DescribeRegionsResponse.hpp>
#include <alibabacloud/models/DescribeZonesRequest.hpp>
#include <alibabacloud/models/DescribeZonesResponseBody.hpp>
#include <alibabacloud/models/DescribeZonesResponse.hpp>
#include <alibabacloud/models/DetachResourceFromVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/DetachResourceFromVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/DetachResourceFromVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/DetachSecurityGroupFromVpcEndpointRequest.hpp>
#include <alibabacloud/models/DetachSecurityGroupFromVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/DetachSecurityGroupFromVpcEndpointResponse.hpp>
#include <alibabacloud/models/DisableVpcEndpointConnectionRequest.hpp>
#include <alibabacloud/models/DisableVpcEndpointConnectionResponseBody.hpp>
#include <alibabacloud/models/DisableVpcEndpointConnectionResponse.hpp>
#include <alibabacloud/models/DisableVpcEndpointZoneConnectionRequest.hpp>
#include <alibabacloud/models/DisableVpcEndpointZoneConnectionResponseBody.hpp>
#include <alibabacloud/models/DisableVpcEndpointZoneConnectionResponse.hpp>
#include <alibabacloud/models/EnableVpcEndpointConnectionRequest.hpp>
#include <alibabacloud/models/EnableVpcEndpointConnectionResponseBody.hpp>
#include <alibabacloud/models/EnableVpcEndpointConnectionResponse.hpp>
#include <alibabacloud/models/EnableVpcEndpointZoneConnectionRequest.hpp>
#include <alibabacloud/models/EnableVpcEndpointZoneConnectionResponseBody.hpp>
#include <alibabacloud/models/EnableVpcEndpointZoneConnectionResponse.hpp>
#include <alibabacloud/models/GetVpcEndpointAttributeRequest.hpp>
#include <alibabacloud/models/GetVpcEndpointAttributeResponseBody.hpp>
#include <alibabacloud/models/GetVpcEndpointAttributeResponse.hpp>
#include <alibabacloud/models/GetVpcEndpointServiceAttributeRequest.hpp>
#include <alibabacloud/models/GetVpcEndpointServiceAttributeResponseBody.hpp>
#include <alibabacloud/models/GetVpcEndpointServiceAttributeResponse.hpp>
#include <alibabacloud/models/ListTagResourcesRequest.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBody.hpp>
#include <alibabacloud/models/ListTagResourcesResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointConnectionsRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointConnectionsResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointConnectionsResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointSecurityGroupsRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointSecurityGroupsResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointSecurityGroupsResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceResourcesRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceResourcesResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceResourcesResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceUsersRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceUsersResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceUsersResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointZonesRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointZonesResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointZonesResponse.hpp>
#include <alibabacloud/models/ListVpcEndpointsRequest.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponseBody.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponse.hpp>
#include <alibabacloud/models/OpenPrivateLinkServiceRequest.hpp>
#include <alibabacloud/models/OpenPrivateLinkServiceResponseBody.hpp>
#include <alibabacloud/models/OpenPrivateLinkServiceResponse.hpp>
#include <alibabacloud/models/RemoveUserFromVpcEndpointServiceRequest.hpp>
#include <alibabacloud/models/RemoveUserFromVpcEndpointServiceResponseBody.hpp>
#include <alibabacloud/models/RemoveUserFromVpcEndpointServiceResponse.hpp>
#include <alibabacloud/models/RemoveZoneFromVpcEndpointRequest.hpp>
#include <alibabacloud/models/RemoveZoneFromVpcEndpointResponseBody.hpp>
#include <alibabacloud/models/RemoveZoneFromVpcEndpointResponse.hpp>
#include <alibabacloud/models/TagResourcesRequest.hpp>
#include <alibabacloud/models/TagResourcesResponseBody.hpp>
#include <alibabacloud/models/TagResourcesResponse.hpp>
#include <alibabacloud/models/UntagResourcesRequest.hpp>
#include <alibabacloud/models/UntagResourcesResponseBody.hpp>
#include <alibabacloud/models/UntagResourcesResponse.hpp>
#include <alibabacloud/models/UpdateVpcEndpointAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcEndpointAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcEndpointAttributeResponse.hpp>
#include <alibabacloud/models/UpdateVpcEndpointConnectionAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcEndpointConnectionAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcEndpointConnectionAttributeResponse.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceAttributeResponse.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceResourceAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceResourceAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcEndpointServiceResourceAttributeResponse.hpp>
#include <alibabacloud/models/UpdateVpcEndpointZoneConnectionResourceAttributeRequest.hpp>
#include <alibabacloud/models/UpdateVpcEndpointZoneConnectionResourceAttributeResponseBody.hpp>
#include <alibabacloud/models/UpdateVpcEndpointZoneConnectionResourceAttributeResponse.hpp>
#include <alibabacloud/models/CreateVpcEndpointRequestTag.hpp>
#include <alibabacloud/models/CreateVpcEndpointRequestZone.hpp>
#include <alibabacloud/models/CreateVpcEndpointServiceRequestResource.hpp>
#include <alibabacloud/models/CreateVpcEndpointServiceRequestTag.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegionServiceResourceTypes.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegionsRegion.hpp>
#include <alibabacloud/models/DescribeRegionsResponseBodyRegions.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZonesZone.hpp>
#include <alibabacloud/models/DescribeZonesResponseBodyZones.hpp>
#include <alibabacloud/models/ListTagResourcesRequestTag.hpp>
#include <alibabacloud/models/ListTagResourcesResponseBodyTagResources.hpp>
#include <alibabacloud/models/ListVpcEndpointConnectionsResponseBodyConnectionsZones.hpp>
#include <alibabacloud/models/ListVpcEndpointConnectionsResponseBodyConnections.hpp>
#include <alibabacloud/models/ListVpcEndpointSecurityGroupsResponseBodySecurityGroups.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceResourcesResponseBodyResources.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceUsersResponseBodyUserArNs.hpp>
#include <alibabacloud/models/ListVpcEndpointServiceUsersResponseBodyUsers.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesRequestTag.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesResponseBodyServicesTags.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesResponseBodyServices.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserRequestTag.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponseBodyServicesTags.hpp>
#include <alibabacloud/models/ListVpcEndpointServicesByEndUserResponseBodyServices.hpp>
#include <alibabacloud/models/ListVpcEndpointZonesResponseBodyZones.hpp>
#include <alibabacloud/models/ListVpcEndpointsRequestTag.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponseBodyEndpointsTags.hpp>
#include <alibabacloud/models/ListVpcEndpointsResponseBodyEndpoints.hpp>
#include <alibabacloud/models/TagResourcesRequestTag.hpp>

#endif
